#+LATEX_CLASS: ctexart

#+TITLE: 线性方程组解

currnet mark: 24

* 域<<MK24>>

设[[~/OneDrive/高等代数/Algb-4-Multi-equ.org][环-其他定义-交换环]] $<U,+,\cdot>$ 满足：

（1） 存在乘法[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-特殊元素-幺元]]，定义为 $1$  

（2） $1$ 不等于加法[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-特殊元素-幺元]]（定义为 $0$ ）

（3） $\forall a\left(a\in U\land a\ne0\rightarrow\exists y(y\in U\land a\cdot y=1)\right)$ 即任意不等于加法幺元的元素存在乘乘法[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-特殊元素-逆元]]

则该代数结构定义为域

** 定理

代数结构 $F=<U,+,\cdot>$ 是一个域， $0$ 是其加法幺元 $e$ 是乘法幺元，则以下两种情况成立其一：

（1） 对于任意 $a\in\mathbb{Z}^+$ 均有 $ae\ne0$

（2） 存在素数 $a\in\mathbb{Z}^+$ 使得 $ae=0$ 成立的最小正整数

其中 $ae$ 代表 $a$ 个 $e$ 相加

*** 证明

条件（1）的逆否命题为存在 $a\in\mathbb{Z}^+$ 使得 $ae=0$ 成立。故若条件（1）不成立，则以上条件成立。

下面证明满足条件的最小的正整数是素数：

假定 $m\in\mathbb{Z}^+$ 是满足 $me=0$ 的最小正整数，若 $m$ 是合数，则有 $m=ab$ 

其中 $1<a<m,1<b<m$ 且均为正整数，由于 $m$ 为最小正整数，故 $ae\ne0\land be\ne0$

根据[[~/OneDrive/高等代数/Algb-4-Multi-equ.org][环-其他定义-交换环]]中加乘法分配率，对于任意 $\{z_1,z_2\}\subset U$ 有：

\begin{aligned}
(az_1)(bz_2)=&\left(\sum_{i=1}^az_1\right)\left(\sum_{i=1}^bz_2\right)\\
=&\sum_{i=1}^a\left(z_1\left(\sum_i=1^bz_2\right)\right)\\
=&\sum_{i=1}^a\left(\sum_i=1^bz_1z_2))\\
=&\sum_{i=1}^{ab}z_1z_2\\
=&(ab)(z_1z_2)
\end{aligned}

故有 $(ae)(be)=(ab)(ee)=me=0$ 根据域定义，存在 $(ae)^{-1}$ 使得 $(ae)^{-1}(ae)=e$

故有 $(ae)^{-1}\left((ae)(be)\right)=(ae)^{-1}0$ 

根据环中乘法结合律可得 $(ae)^{-1}\left((ae)(be)\right)=\left((ae)^{-1}(ae)\right)be=ebe=be$ 

根据[[~/OneDrive/高等代数/Algb-4-Multi-equ.org][环-其他定义-零因子-定理]]可得 $(ae)^{-1}0=0$

故有 $be=0$ 与条件矛盾，故 $m$ 不能为合数 

* 数域

定义 $K$ 为复数集的子集，若满足：

（1） $0,1\in K$

（2） $a,b\in K\Rightarrow a\pm b\in K, ab\in K$

（3） $a,b\in K$ 且 $b\ne0\Rightarrow \frac{a}{b}\in K$

则为域。进一步由于是数字组成，称为数域。

** 证明

*** 证明是交换环

根据复数上的加法/乘法，以及[[~/OneDrive/高等代数/Algb-4-Multi-equ.org][环-其他定义-交换环]]可知

（1） 加法满足结合律

（2） 加法满足交换律

（3） $0$ 是加法幺元，根据条件（1）有 $0\in K$

（4） 根据条件（2）有 $\forall a\in K\rightarrow 0-a=-a\in K\land a+(-a)=0$ 即有加法逆元

（5） 乘法满足结合律

（6） 满足分配率

（7） 根据条件（2）加乘法封闭

即 $<K,+,\cdot>$ 是环，且由于乘法满足交换律，故是交换环

*** 证明是域

根据[复数上的加法/乘法

（1） $\forall a\in K\rightarrow 1\cdot a=a\cdot 1=a$

（2） $\forall a\in K\rightarrow a+0=0+a=a$

（3） $\forall a\in K\rightarrow a\cdot0=0\cdota=0$

故 $K$ 上乘法幺元为 $1$ ，加法幺元为 $0$，两者不想等

且根据条件（3）对于任意 $a\in K\land a\ne0$ 必有 $\frac{1}{a}\in K$ 满足 $a\frac{1}{a}=1$

故根据[[MK24][域定义]]得出代数结构 $<K,+,\cdot>$ 是域

** 推论1：最小的数据是有理数域

由于 $0,1\in K$ 则 $1+1=2\in K$ 故有 $2+1=3\in K$ 依次类推，正正数 $N^+\subset K$

由于 $0\in K$ 故结合上述证明当 $n\in N^+\subset k\Rightarrow 0-n\in K$ 故整数 $N\subset K$

结合上述证明及条件（3） $\forall a,b\in N\subset K, b\ne 0\Rightarrow \frac{a}{b}\in K$ 故分数 $P\subset K$

综上所述，有理数 $Q\subset K$

** 推论2：复数为最大数域

由于 $K$ 为复数的子集故复数全集为最大数域

* 线性方程组

** <<MK3>>线性方程组定义

有未知量 $x_1,x_2,..,x_n$ 具备线性关系 $\begin{cases}a_{11}x_1+a_{12}x_2+...+a_{1n}x_n=b_1&\textcircled{1}\\a_{21}x_1+a_{22}x_2+...+a_{2n}x_n=b_2&\textcircled{2}\\...\\a_{m1}x_1+a_{m2}x_2+...+a_{mn}x_n=b_m&\textcircled{m}\end{cases}$

则称未知量的线性关系为线性方程组

** 其他定义

*** <<MK4>>增广矩阵

若有线性方程组满足[[MK3][定义]]，则其增广矩阵为 $E=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}&b_1\\a_{21}&a_{22}&...&a_{2n}&b_2\\...&...&...&...&...\\a_{m1}&a_{m2}&...&a_{mn}&b_m\end{matrix}\right]$ 

*** 行的主元

在矩阵中，第 $r$ 行的主元为改行第一个非零元素。

*** <<MK2>>阶梯矩阵

定义 $d_r$ 为第 $r$ 行的主元所在的列（从左只有，从 $1$ 开始），矩阵共 $n$ 列，若矩阵 $E$ 为阶梯矩阵，则满足：

（1） 若第 $r$ 行主元存在，则 $d_r>d_{r+1}$

（2） 若第 $r$ 行主元不存在（即该行元素全部为零）则 $\forall n$ 有第 $r+n$ 行主元也不存在。

*** <<MK5>>简化行阶梯型矩阵

定义 $d_r$ 为第 $r$ 行的主元所在的列（从左只有，从 $1$ 开始），若 $E$ 为简化行阶梯型矩阵，则满足：

（1） 第 $r$ 行的主元值为 $1$

（2） 除第 $r$ 行外任意一行的第 $d_r$ 个元素值为 $0$

简化行阶梯型矩阵可由阶梯矩阵经过[[MK1][初等行变换]]得到。

** 解法

*** <<MK6>>线性方程组矩阵消元法

定义增广矩阵 $E=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}&b_1\\a_{21}&a_{22}&...&a_{2n}&b_2\\...&...&...&...&...\\a_{m1}&a_{m2}&...&a_{mn}&b_m\end{matrix}\right]$ 当 $a_{11}\ne0$ 时对第一行以外的行做运算 $E\xrightarrow[k\ne1]{\textcircled{k}-\frac{a{k1}}{a_{11}}\textcircled{1}}E_1=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}&b_1\\0&a_{22_1}&...&a_{2n_1}&b_{2_1}\\0&...&...&...&...\\0&a_{m2_1}&...&a_{mn_1}&b_{m_1}\end{matrix}\right]$

该操作可视为 $&\textcircled{1}$ 式乘以系数加到 $&\textcircled{k}$ 式，故操作后方程组解相同，改类操作称为<<MK1>> *初等行变换*

当 $a_{22_1}\ne0$ 时对第一，二行意外的行做运算 $E_1\xrightarrow[k\ne1,2]{\textcircled{k}-\frac{a{k2}}{a_{22}}\textcircled{2}}E_2$ 经过 $m$ 次得阶梯矩阵 $E_m=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}&b_1\\0&a_{22_1}&...&a_{2n_1}&b_{2_1}\\0&0&\ddots&...&...\\0&0&...&a_{mn_m}&b_{m_m}\end{matrix}\right]$

同理 $E_m$ 所表示的线性方程组与 $E$ 同解

上述方法称为线性方程组的矩阵消元法。

** <<MK7>>线性方程组解的情况

$n$ 元线性方程组解的情况只有三种，当增广矩阵经过[[MK1][初等行变换]]后称为阶梯型矩阵 $E$ 时，若：

（1） 出现 $0=d$ 的等式（ $d\ne0$ ）则无解；

（2） 若没有出现情形（1）且非零行数目 $r$ 等于未知数数目 $n$ 则有唯一解；

（3） 若没有出现情形（1）且非零行数目 $r$ 小于未知数数目 $n$ 则有无穷多解；

*** 证明

**** 条件（1）

显然无解

**** 条件（2）

根据[[MK4][增广矩阵]]定义，线性方程组对应的增广矩阵列数为 $n+1$ 行数为 $m$

由于不存在（1）所述情况，且 $r=n$ ，故有 $m\geq n$ 且最后的非零行主元所在列 $d_r<n+1$

又根据[[MK2][阶梯矩阵]]定义，得第 $r-1$ 行的主元所在列满足 $d_{r-1}<d_r$ 最大为 $d_r-1$

以此类推，第 $1$ 行主元所在列最大为 $d_r-(n-1)$ 且 $d_1>0$

故，当且仅当 $d_r=n$ 且每一行主元列数都取最大时，才满足 $d_1>0$ 即 $d_1=d_r-(n-1)=1$

阶梯矩阵中第 $i$ 行满足 $d_i=i$

故根据[[MK5][简化行阶梯型矩阵]]定义，上述阶梯矩阵可由初等变换得到简化行阶梯型矩阵 $E_k$ 且根据定义 $E_k$ 满足

（1） 当 $i>n$ 时第 $i$ 行的元素全部为零

（2） 当 $i<1$ 时第 $i$ 行的第 $i$ 个元素为 $1$ 其余全为零

故根据[[MK6][矩阵消元法]]得经过初等行变换的矩阵与原线性方程组通解。

$E_k$ 对于每一个未知量 $x_i$ 均有赋值，故 $E_k$ 有唯一解，同理原线性方程组也仅有唯一解

**** 条件（3）

同理根据[[MK5][简化行阶梯型矩阵]]定义，阶梯矩阵可由初等变换得到简化行阶梯型矩阵 $E_k$ 

由于 $r<n$ 故必定存在 $n-r$ 个正整数 $u_j,1\leq j\leq n-r$ 满足 $u_j\leq n$ 且 $\forall 1\leq i\leq r\Rightarrow d_i\ne u_j$

故 $E_k$ 第 $i$ 行表示的方程为 $x_i+\sum_{j=1}^{n-r}d_jx_{u_j}=b_i$ 即 $x_i=b_i-\sum_{j=1}^{n-r}d_jx_{u_j}$ 

由上述结论可知，方程组在固定 $x_{u_j}$ 的情况下，有唯一解，且 $x_{u_j}$ 取值为实数全体

故有无穷解。

** 齐次线性方程组

*** 定义

线性方程组的常数项均为零，即 $x_1,x_2,..,x_n$ 具备线性关系 $\begin{cases}a_{11}x_1+a_{12}x_2+...+a_{1n}x_n=0&\textcircled{1}\\a_{21}x_1+a_{22}x_2+...+a_{2n}x_n=0&\textcircled{2}\\...\\a_{m1}x_1+a_{m2}x_2+...+a_{mn}x_n=0&\textcircled{m}\end{cases}$

*** 推论1：$n$ 元齐次线性方程组只有零解和无穷解两种情况。

根据定义 $x_1=x_2=...=x_n=0$ 必为其中一解，且根据[[MK7][线性方程组解的情况]]，若有非零解，则线性方程组有无穷解。

*** 推论2：$n$ 元齐次线性方程组有非零解的充分条件为方程数目小于未知数数目

根据[[MK7][线性方程组解的情况]]，若转化为阶梯型矩阵 $E$ 的非零行数目 $r$ 小于未知数数目 $n$ 则有有无穷解，故有非零解。

若当方程数目小于未知数数目时，阶梯矩阵非零行数目必小于未知数数目。

* $n$ 阶行列式

** <<MK8>>逆序数

对于任意自然数排列 $j_1j_2...j_n$ 对所有 $i\in N^+,1\leq i\leq n$ 依次对比 $j_i$ 和 $j_k,k>i$ 若 $j_i>j_k$ 则称此情况为 *逆序*

逆序数是逆序个数的加总，定义为 $\tau(j_1j_2...j_n)$ ，定义逆序数为奇数的排列为 *奇排列* ，反之则为 *偶排列*

*** <<MK9>>定理1

对于一组排列中的任意两个数交换位置，排列的奇偶性改变

**** 证明

***** 互换相邻数

若相有排列 $\dc...p...j_uj_v...q...\a$ 将 $j_u,j_v$ 互换，对于任意在 $j_uj_v$ 前的数 $p$ 与后的数 $q$ 来说，是否为逆序不变

对于 $j_u,j_v$ 若原来不为逆序，互换后为逆序；原来为逆序，互换后不为逆序。

故 $\tau(...p...j_vj_u...q...)=\tau(...p...j_uj_v...q...)+1$ 或 $\tau(...p...j_vj_u...q...)=\tau(...p...j_uj_v...q...)-1$ 故奇偶性必变

***** 不相邻数互换

若有排列 $\dc...j_uk_1k_2...k_sj_v...\a$ 可由 $s+1$ 次相邻数互换得到 $\dc...k_1k_2...k_sj_vj_u...\a$ 再由 $s$ 次相邻数互换得到 $\dc...j_uk_1k_2...k_sj_v...\a$ 

共经历 $2s+1$ 次，改变奇偶性 $2s+1$ 次，故由此法交换的排序奇偶性改变。且一个排列的奇偶性唯一，故定理成立。

*** <<MK23>>定理2

任一排列 $j_1j_2...j_n$ 若通过数字互换变成排列 $j_{i_1}j_{i_2}...j_{i_n}$ 且有 $j_{i_1}<j_{i_2}<...<j_{i_n}$ 则互换次数的奇偶性与排列的奇偶性相同

**** 证明

由于 $j_{i_1}<j_{i_2}<...<j_{i_n}$ 故 $j_{i_1}j_{i_2}...j_{i_n}$ 的逆序数为零，故为偶排列。根据[[MK9][定理1]]每次互换均改变排列奇偶性。

故若 $j_1j_2...j_n$ 为奇排列，变为偶排列需要的互换次数必为奇数，反之必为偶数。证毕。

** <<MK11>>行列式定义

\begin{aligned}
\det(A)=|A|=\left|\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right|=\sum_{\forall j_1j_2...j_n}(-1)^{\tau(j_1j_2...j_n)}a_{1j_1}a_{2j_2}...a_{nj_n}
\end{aligned}

其中:

（1） $j_1j_2...j_n$ 为自然数 $1,2,...,n$ 的排列，累加条件中 $\forall j_1j_2...j_n$ 为所有可能排列

（2） $\tau(j_1j_2...j_n)$ 为排列的[[MK8][逆序数]]

*** <<MK10>>定理1

若有项 $(-1)^{\tau(j_1j_2...j_n)}a_{1j_1}a_{2j_2}...a_{nj_n}$ 其中 $12...n$ 经过 $s$ 次变换成为 $i_1i_2...i_n$ 对应 $j_1j_2...j_n$ 变换为 $k_1k_2...k_n$ 则有

$(-1)^{\tau(j_1j_2...j_n)}a_{1j_1}a_{2j_2}...a_{nj_n}=(-1)^{\tau(i_1i_2...i_n)+\tau(k_1k_2...k_n)}a_{i_1k_1}a_{i_2k_2}...a_{i_nk_n}$

**** 证明

假设 $12...n$ 经过 $s$ 次变换成为 $i_1i_2...i_n$ 则 $j_1j_2...j_n$ 亦经过 $s$ 次变换称为 $k_1k_2...k_n$

根据[[MK9][定理1]] $\tau(k_1k_2...k_n)$ 与 $\tau(j_1j_2...j_n)$ 相比奇偶性改变 $s$ 次，且 $\tau(i_1i_2...i_n)=s$

故 $\tau(j_1j_2...j_n)$ 与 $\tau(i_1i_2...i_n)+\tau(k_1k_2...k_n)$ 相比奇偶性改变 $2s$ 故奇偶性不变。

则 $(-1)^{\tau(j_1j_2...j_n)}=(-1)^{\tau(i_1i_2...i_n)+\tau(k_1k_2...k_n)}$ 并根据乘法交换律 $a_{1j_1}a_{2j_2}...a_{nj_n}=a_{i_1k_1}a_{i_2k_2}...a_{i_nk_n}$

故有 $(-1)^{\tau(j_1j_2...j_n)}a_{1j_1}a_{2j_2}...a_{nj_n}=(-1)^{\tau(i_1i_2...i_n)+\tau(k_1k_2...k_n)}a_{i_1k_1}a_{i_2k_2}...a_{i_nk_n}$ 证毕。

** 其他定义

*** 单个元素余子式

对于矩阵 $A=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]$ 来说第 $a_{ij}$ 的余子式为 $\left|\begin{matrix}a_{11}&...&a_{1(j-1)}&a_{1(j+1)}&...&a_{1n}\\...&...&...&...&...&...\\a_{(i-1)1}&...&a_{(i-1)(j-1)}&a_{(i-1)(j+1)}&...&a_{(i-1)n}\\a_{(i+1)1}&...&a_{(i+1)(j-1)}&a_{(i+1)(j+1)}&...&a_{(i+1)n}\\...&...&...&...&...&...\\a_{n1}&...&a_{n(j-1)}&a_{n(j+1)}&...&a_{nn}\end{matrix}\right|$

即划掉 $a_{ij}$ 所在行列元素的子行列式，记作 $M_{ij}$

*** <<MK17>>单个元素代数余子式

代数余子式记作 $A_{ij}=(-1)^{i+j}\overline{M}_{ij}$ 其中 $\overline{M}_{ij}$ 为[[MK22][余子式]]

*** <<MK21>>子式

综合来说，子式为取矩阵 $k$ 行 $k$ 列上的元素组成的子矩阵的行列式

对于 $I=\left\{i_1\leq i_2\leq...\leq i_k\right\}$ 以及 $J=\left\{j_1\leq j_2\leq...\leq j_k\right\}$ 属于非零自然数，定义矩阵 $A=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]$ 

则对于 $I,J$ 的子式定义为 $M\left(\begin{matrix}i_1&i_2&...&i_k\\j_1&j_2&...&j_k\end{matrix}\right)=\left|\begin{matrix}a_{i_1j_1}&a_{i_1j_2}&...&a_{i_1j_k}\\a_{i_2j_1}&a_{i_2j_2}&...&a_{i_2j_k}\\...&...&...&...\\a_{i_kj_1}&a_{i_kj_2}&...&a_{i_kj_k}\end{matrix}\right|$ 

*** <<MK22>>余子式

综合来说，余子式是去除[[MK21][子式]]取的行列后，剩下的行列上元素组成的行列式

对于 $I=\left\{i_1\leq i_2\leq...\leq i_k\right\}$ 以及 $J=\left\{j_1\leq j_2\leq...\leq j_k\right\}$ 属于非零自然数，定义矩阵 $A=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]$ 

定义 $I'=\left\{i_1'\leq i_2'\leq ...\leq i_{n-k}'\right\}=\left\{\forall(u\in N^+,1\leq u\leq n-k)\Rightarrow(1\leq i_u\leq n,i_u\not\in I)\right\}$

定义 $J'=\left\{j_1'\leq j_2'\leq ...\leq j_{n-k}'\right\}=\left\{\forall(u\in N^+,1\leq u\leq n-k)\Rightarrow(1\leq j_u\leq n,j_u\not\in I)\right\}$

则对于 $I',J'$ 的余子式定义为 $M\left(\begin{matrix}i'_1&i'_2&...&i'_{n-k}\\j'_1&j'_2&...&j'_{n-k}\end{matrix}\right)=\left|\begin{matrix}a_{i'_1j'_1}&a_{i'_1j'_2}&...&a_{i'_1j'_{n-k}}\\a_{i'_2j'_1}&a_{i'_2j'_2}&...&a_{i'_2j'_{n-k}}\\...&...&...&...\\a_{i'_{n-k}j'_1}&a_{i'_{n-k}j'_2}&...&a_{i'_{n-k}j'_{n-k}}\end{matrix}\right|$ 记作 $\overline{M}\left(\begin{matrix}i_1&i_2&...&i_k\\j_1&j_2&...&j_k\end{matrix}\right)$

*** 多个元素代数余子式

定义对应 $I=\left\{i_1\leq i_2\leq...\leq i_k\right\}$ 以及 $J=\left\{j_1\leq j_2\leq...\leq j_k\right\}$ 得代数余子式为 $(-1)^{\sum_{u=1}^k i_u+\sum_{u=1}^k j_u}\overline{M}\left(\begin{matrix}i_1&i_2&...&i_k\\j_1&j_2&...&j_k\end{matrix}\right)$

当 $k=1$ 时，其定义与[[MK17][单个元素]]相同

** 性质

*** <<MK12>>转置相等

$|A|=|A^T|$ 其中 $A^T$ 为矩阵 $A$ 的转置矩阵

**** 证明

根据[[MK10][定理1]]有 $|A|=\sum_{\forall j_1j_2...j_n}(-1)^{\tau(j_1j_2...j_n)}a_{1j_1}a_{2j_2}...a_{nj_n}=\sum_{\forall i_1i_2...i_n}(-1)^{\tau(i_1i_2...i_n)}a_{i_11}a_{i_22}...a_{i_nn}=|A^T|$

*** <<MK14>>行乘系数

$A=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\...&...&...&...\\a_{i1}&a_{i2}&...&a_{in}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]$ 若 $B=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\...&...&...&...\\Ka_{i1}&Ka_{i2}&...&Ka_{in}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]$ 其中 $K$ 为常数

则有 $|B|=K|A|$

**** 证明

根据[[MK11][定义]] $|B|=\sum_{\forall j_1j_2...j_n}(-1)^{\tau(j_1j_2...j_n)}a_{1j_1}...Ka_{ij_i}...a_{nj_n}=K\sum_{\forall j_1j_2...j_n}(-1)^{\tau(j_1j_2...j_n)}a_{1j_1}a_{2j_2}...a_{nj_n}=K|A|$

**** 推论

且根据[[MK12][转置相等]]性质可得，列乘系数同样 $|B|=K|A|$

*** <<MK15>>行为两组数的和

若

$A=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\...&...&...&...\\a_{i1}&a_{i2}&...&a_{in}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right],B=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\...&...&...&...\\b_{i1}&b_{i2}&...&b_{in}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right],C=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\...&...&...&...\\a_{i1}+b_{i1}&a_{i2}+b_{i2}&...&a_{in}+b_{in}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]$

则有 $|C|=|A|+|B|$

**** 证明

根据[[MK11][定义]] 

\begin{aligned}
|C|&=\sum_{\forall j_1j_2...j_n}(-1)^{\tau(j_1j_2...j_n)}a_{1j_1}...(a_{ij_i}+b_{ij_i})...a_{nj_n}\\
&=\sum_{\forall j_1j_2...j_n}(-1)^{\tau(j_1j_2...j_n)}a_{1j_1}...a_{ij_i}...a_{nj_n}+\sum_{\forall j_1j_2...j_n}(-1)^{\tau(j_1j_2...j_n)}a_{1j_1}...b_{ij_i}...a_{nj_n}\\
&=|A|+|B|
\end{aligned}

**** 推论

且根据[[MK12][转置相等]]性质可得列为两组数和同样 $|C|=|A|+|B|$

*** <<MK13>>两行互换

$A=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\...&...&...&...\\a_{u1}&a_{u2}&...&a_{un}\\...&...&...&...\\a_{v1}&a_{v2}&...&a_{vn}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right],B=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\...&...&...&...\\a_{v1}&a_{v2}&...&a_{vn}\\...&...&...&...\\a_{u1}&a_{u2}&...&a_{un}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]$

则有 $|A|=-|B|$

**** 证明

根据[[MK11][定义]] $|A|=\sum_{\forall j_1j_2...j_n}(-1)^{\tau(j_1...j_{u-1}j_uj_{u+1}...j_{v-1}j_vj_{v+1}...j_n)}a_{1j_1}...a_{(u-1)j_{u-1}}a_{uj_u}a_{(u+1)j_{u+1}}...a_{(v-1)j_{v-1}}a_{vj_v}a_{(v+1)j_{v+1}}...a_{nj_n}$

同理则有 $|B|=\sum_{\forall j_1j_2...j_n}(-1)^{\tau(j_1...j_{u-1}j_uj_{u+1}...j_{v-1}j_vj_{v+1}...j_n)}a_{1j_1}...a_{(u-1)j_{u-1}}a_{vj_u}a_{(u+1)j_{u+1}}...a_{(v-1)j_{v-1}}a_{uj_v}a_{(v+1)j_{v+1}}...a_{nj_n}$

由于对于 $j_1j_2...j_n$ 排列为遍历，对于 $|A|$ 中给定 $(-1)^{\tau(j_1...j_{u-1}j_uj_{u+1}...j_{v-1}j_vj_{v+1}...j_n)}a_{1j_1}...a_{(u-1)j_{u-1}}a_{uj_u}a_{(u+1)j_{u+1}}...a_{(v-1)j_{v-1}}a_{vj_v}a_{(v+1)j_{v+1}}...a_{nj_n}$ 

必存在 $|B|$ 中对应的 $(-1)^{\tau(j_1...j_{u-1}j_vj_{u+1}...j_{v-1}j_uj_{v+1}...j_n)}a_{1j_1}...a_{(u-1)j_{u-1}}a_{vj_v}a_{(u+1)j_{u+1}}...a_{(v-1)j_{v-1}}a_{uj_u}a_{(v+1)j_{v+1}}...a_{nj_n}$

根据[[MK9][定理1]]及乘法交换律

\begin{aligned}
&(-1)^{\tau(j_1...j_{u-1}j_vj_{u+1}...j_{v-1}j_uj_{v+1}...j_n)}a_{1j_1}...a_{(u-1)j_{u-1}}a_{vj_v}a_{(u+1)j_{u+1}}...a_{(v-1)j_{v-1}}a_{uj_u}a_{(v+1)j_{v+1}}...a_{nj_n}\\
=&-\left\{(-1)^{\tau(j_1...j_{u-1}j_uj_{u+1}...j_{v-1}j_vj_{v+1}...j_n)}a_{1j_1}...a_{(u-1)j_{u-1}}a_{uj_u}a_{(u+1)j_{u+1}}...a_{(v-1)j_{v-1}}a_{vj_v}a_{(v+1)j_{v+1}}...a_{nj_n}\right\}
\end{aligned}

又根据 $|A|$ 与 $|B|$ 中累加的项数相等可得 $|B|=-|A|$

**** 推论

若矩阵 $B$ 为矩阵 $A$ 两列互换，则有 $|B|=-|A|$

***** 证明

由于 $B$ 为 $A$ 两列互换，则有 $B^T$ 为 $A^T$ 两列互换，故有 $|B^T|=|A^T|$

根据[[MK12][转置相等]]可得 $|B|=|B^T|=-|A^T|=-|A|$

*** <<MK18>>上三角矩阵行列式

若 $A=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\0&a_{22}&...&a_{2n}\\\vdots&\vdots&\ddots&\vdots\\0&0&...&a_{nn}\end{matrix}\right]$ 则有 $|A|=\prod_{i=1}^n a_{ii}$

**** 证明

根据行列式[[MK11][定义]]，行列式为每行取一个元素的乘积的和，故第 $n$ 行唯一不为零的元素是 $a_{nn}$

同理第 $n-1$ 行不为零的元素为 $a_{(n-1)(n-1)},a_{n(n-1)}$ 但由于 $a_{nn}$ 已由最后一行占据，故只能取 $a_{(n-1)(n-1)}$

依次类推，得除 $a_{11}a_{22}..a_{nn}$ 以外的乘积项均为零，故 $|A|=\prod_{i=1}^n a_{ii}$

**** 推论

且根据[[MK12][转置相等]]性质可得，下三角行列式同样 $|A^T|=\prod_{i=1}^n a_{ii}$

*** <<MK16>>一行为另一行 $K$ 倍

若 $A=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\...&...&...&...\\a_{i1}&a_{i2}&...&a_{in}\\...&...&...&...\\a_{j1}&a_{j2}&...&a_{jn}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]$ 其中 $a_{ik}=Ka_{jk},k\in[0,n]$ 则有 $|A|=0$

**** 证明

根据[[MK14][行乘系数]]可得 $|A|=K\left|\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\...&...&...&...\\a_{i1}&a_{i2}&...&a_{in}\\...&...&...&...\\a_{i1}&a_{i2}&...&a_{in}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right|=K|E|$ 将 $i,j$ 两行互换后的矩阵 $B$

由于两行互换后矩行列式计算同理可提出系数，则有 $B=K|E'|$ 且提出系数后 $|E'|=|E|$ 

根据[[MK13][两行互换]]可得 $|B|=-|A|=-K|E|$ 结合上式得 $K|E|=-K|E|\Rightarrow |E|=0$

故有 $|A|=0$

**** 推论

且根据[[MK12][转置相等]]性质可得，一列为另一列 $K$ 倍 $|A|=0$

*** <<MK19>>初等行变换

若 $A\xrightarrow[i\ne j]{\textcircled{j}+K\textcircled{i}}D$ 则有 $|A|=|D|$

**** 证明

矩阵 $A=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\...&...&...&...\\a_{j1}&a_{i2}&...&a_{in}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]$ 则有矩阵 $D=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\...&...&...&...\\a_{j1}+Ka_{i1}&a_{i2}+Ka_{i2}&...&a_{in}+Ka_{in}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]$

根据[[MK15][行为两组数和]]得 $|D|=|A|+\left|\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\...&...&...&...\\Ka_{i1}&Ka_{i2}&...&Ka_{in}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right|$ 又根据[[MK16][一行为另一行K倍]]得 $\left|\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\...&...&...&...\\Ka_{i1}&Ka_{i2}&...&Ka_{in}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right|=0$

故得 $|A|=|D|$

**** 推论

且根据[[MK12][转置相等]]性质可得，初等列变换 $|A|=|D|$

*** <<MK20>>行列式拆分

定义矩阵 $A=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]$ 取任意一行 $k$ 则有 $|A|=\sum_{i=1}^n a_{ki}A_{ki}$ 其中 $A_{ki}$ 为矩阵 $A$ 对于元素 $a_{ki}$ 的[[MK17][代数余子式]] 

**** 证明

根据[[MK11][定义]]得 $|A|=\sum_{\forall j_1j_2...j_n}(-1)^{\tau(j_1j_2...j_n)}a_{1j_1}a_{2j_2}...a_{nj_n}$

又根据[[MK10][定理1]]得 $|A|=\sum_{\forall j_1j_2...j_n}(-1)^{\tau(j_kj_1...j_{k-1}j_{k+1}...j_n)+\tau(k1..(k-1)(k+1)...n)}a_{kj_k}a_{1j_1}...a_{(k-1)j_{k-1}}a_{(k+1)j_{k+1}}..a_{nj_n}$

对于 $\tau(k1..(k-1)(k+1)...n)$ 把 $k$ 移动到最前，则之后有 $k-1$ 个数比 $k$ 小，剩余逆序数为零，故 $\tau(k1..(k-1)(k+1)...n)=k-1$

对于 $\tau(j_kj_1...j_{k-1}j_{k+1}...j_n)$ 来说，由于是自然数排列，则比 $j_k$ 小的数必为 $j_k-1$ 个，剩余逆序数与 $j_k$ 无关，故为 $\tau(j_1...j_{k-1}j_{k+1}...j_n)$

则有 $\tau(j_kj_1...j_{k-1}j_{k+1}...j_n)=j_k-1+\tau(j_1...j_{k-1}j_{k+1}...j_n)$ 

更因为 $j_1j_2...j_n$ 为自然数排列，故当 $j_k$ 为自然数 $1,2,...,n$ 且每一项必有对应 $(n-1)!$ 个连乘项 $a_{kj_k}a_{1j_1}...a_{(k-1)j_{k-1}}a_{(k+1)j_{k+1}}..a_{nj_n}$ ，故有 

\begin{aligned}
|A|&=\sum_{\forall j_1j_2...j_n}(-1)^{k-1+j_k-1+\tau(j_1...j_{k-1}j_{k+1}...j_n)}a_{kj_k}a_{1j_1}...a_{(k-1)j_{k-1}}a_{(k+1)j_{k+1}}..a_{nj_n}\\
&=\sum_{i=1}^n\left\{a_{ki}\left((-1)^{i+j}\sum_{\forall j_1...j_{k-1}j_{k+1}...j_n}(-1)^{\tau(j_1...j_{k-1}j_{k+1}...j_n)}a_{kj_k}a_{1j_1}...a_{(k-1)j_{k-1}}a_{(k+1)j_{k+1}}..a_{nj_n}\right)\right\}\\
&=\sum_{i=1}^na_{ki}A_{ki}
\end{aligned}

证毕。

**** 推论

当矩阵中某一行为零时，取该行的行列式 $|A|=\sum_{i=1}^n 0A_{ki}=0$ ，且根据[[MK12][转置相等]]某一列为零时亦然

** 行列式与解的关系

线性方程组有唯一解的充要条件为系数矩阵 $A$ 的行列式 $|A|\ne0$

*** 证明

**** 充分性（克莱默法则第一部分）

若增广矩阵 $D$ 经过初等行变换称为阶梯矩阵 $E$ ，系数矩阵 $A$ 通过初等行变换化为阶梯矩阵 $B$ ，若

***** 无解

根据[[MK7][解的情况]]有 $0=d$ 的等式出现，则 $B$ 必有某行全部为零，根据[[MK18][上三角矩阵]]可得 $|B|=\prod_{i=1}^n b_{ii}=0$

又根据[[MK19][初等行变换]]可得 $|B|=|A|$

***** 有无穷解

根据[[MK7][解的情况]]非零行数目小于未知数数目，则 $B$ 必有某行全部为零，根据[[MK18][上三角矩阵]]可得 $|B|=\prod_{i=1}^n b_{ii}=0$

又根据[[MK19][初等行变换]]可得 $|B|=|A|$

***** 有唯一解

根据[[MK7][解的情况]]非零行数目等于未知数数目，则 $B$ 为上三角矩阵且对角线上的数字均不等于零，则有 $|B|=\prod_{i=1}^n b_{ii}\ne0$ 

又根据[[MK19][初等行变换]]可得 $|B|\ne0\Rightarrow|A|\ne0$

**** 必要性

若 $|A|\ne 0$ 根据[[MK19][初等行变换]]经过初等行变换获得阶梯矩阵 $B$ 后行列式 $|B|=|A|$

又由于 $B$ 为上三角矩阵，则有 $|B|=\prod_{i=1}^n b_{ii}$ 故对角线上的数字均不为零，证毕。

*** 推论

$n$ 元齐次线性方程组有非零解的充要条件是 $|A|=0$ ，只有零解的充要条件是 $|A|\ne0$

** 拉普拉斯定理

定义矩阵 $A=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]$ 任意选取 $k$ 行，分别为 $I=\left\{i_1\leq i_2\leq...\leq i_k\right\}$ 

则有 $$|A|=\sum_{\forall 1\leq j_1\leq j_2\leq...\leq j_k\leq n}(-1)^{\sum_{u=1}^k i_u+\sum_{u=1}^k j_u}M\left(\begin{matrix}i_1&i_2&...&i_k\\j_1&j_2&...&j_k\end{matrix}\right)\overline{M}\left(\begin{matrix}i_1&i_2&...&i_k\\j_1&j_2&...&j_k\end{matrix}\right)$$

其中 $M\left(\begin{matrix}i_1&i_2&...&i_k\\j_1&j_2&...&j_k\end{matrix}\right),\overline{M}\left(\begin{matrix}i_1&i_2&...&i_k\\j_1&j_2&...&j_k\end{matrix}\right)$ 分别为 $A$ 的[[MK21][子式]]和[[MK22][余子式]]，

故有 $\left\{j_1\leq j_2\leq ...\leq j_k\right\},\left\{j'_1\leq j'_2\leq ...\leq j'_k\right\}$

*** 证明

**** 准备阶段

定义 $I'=\left\{i_1'\leq i_2'\leq ...\leq i_{n-k}'\right\}=\left\{\forall(u\in N^+,1\leq u\leq n-k)\Rightarrow(1\leq i_u\leq n,i_u\not\in I)\right\}$

根据[[MK11][行列式定义]]有 $|A|=\sum_{\forall j_1j_2...j_n}(-1)^{\tau(j_1j_2...j_n)}a_{1j_1}a_{2j_2}...a_{nj_n}$

根据[[MK10][定理1]]将所有行标属于 $I$ 的移动到最前面 $|A|=\sum_{\forall j_1j_2...j_n}(-1)^{\tau(i_1...i_ki'_1...i'_{n-k})+\tau(j_{i_1}...j_{i_k}j_{i'_k}...j_{i'_{n-k}})}a_{i_1j_{i_1}}...a_{i_kj_{i_k}}a_{i'_1j_{i'_1}}...a_{i'_{n-k}j_{i'_{n-k}}}$

**** 连加分层

接下来将连加分成3层:

（1） 最外层是从 $n$ 列中取 $k$ 列的组合

（2） 第二层是 $k$ 列的排列

（3） 最后是 剩下 $j'_1,...,j'_{n-k}$ 的排列

故得 $|A|=\sum_{\forall 1\leq j_1\leq...\leq j_k\leq n}\sum_{\forall j_1...j_k}\sum_{\forall j'_1...j'_{n-k}}(-1)^{\tau(i_1...i_ki'_1...i'_{n-k})+\tau(j_{i_1}...j_{i_k}j_{i'_k}...j_{i'_{n-k}})}a_{i_1j_{i_1}}...a_{i_kj_{i_k}}a_{i'_1j_{i'_1}}...a_{i'_{n-k}j_{i'_{n-k}}}$

**** 计算逆序数

对于 $\tau(i_1...i_ki'_1...i'_{n-k})$ 由于 $i_1'\leq i_2'\leq ...\leq i_{n-k}'$ 以及 $i_1\leq i_2\leq...\leq i_k$ 且 $i_1,...,i_k,i'_1,...,i'_{n-k}$ 占据所有 $1,2,...,n$ 的自然数

故对于 $i_1$ 仅有 $i_1-1$ 项比他小

对于 $i_2$ 仅有 $i_2-1$ 项比他小，且 $i_1<i_2$ 故之后的逆序数为 $i_2-2$

以此类推，对于 $i_m$ 的逆序数为 $i_m-m$

从 $i'_1$ 开始，由于从小到大排列，故逆序数为零

综上所述 $\tau(i_1...i_ki'_1...i'_{n-k})=\sum_{u=1}^k{i_k-k}=\sum_{u=1}^ki_k+\frac{k(1+k)}{2}$

对于 $\tau(j_{i_1}...j_{i_k}j_{i'_k}...j_{i'_{n-k}})$ 将 $j_{i_1}...j_{i_k}$ 转换为 $j_1j_2...j_k$ 满足 $j_1<j_2<...j_k$

由于 $j_1j_2...j_k$ 逆序数为零，故根据[[MK23][定理2]]转换的次数的奇偶性与 $\tau(j_{i_1}...j_{i_k})$ 的奇偶性一致

且根据[[MK9][定理1]]，每转换一次逆序数的奇偶性改变一次

综上所述得 $(-1)^{\tau(j_{i_1}...j_{i_k}j_{i'_k}...j_{i'_{n-k}})}=(-1)^{\tau(j_{i_1}...j_{i_k})+\tau(j_{i_1}...j_{i_k}j_{i'_k}...j_{i'_{n-k}})}$

同理 $\tau(j_{i_1}...j_{i_k}j_{i'_k}...j_{i'_{n-k}})=\sum_{u=1}^k j_u +\frac{k(k+2)}{2}+\tau(j_{i'_k}...j_{i'_{n-k}})$

**** 计算分成连加

根据[[MK22][定义]] $M\left(\begin{matrix}i'_1&i'_2&...&i'_{n-k}\\j'_1&j'_2&...&j'_{n-k}\end{matrix}\right)=\sum_{\forall j'_1...j'_{n-k}}\left((-1)^{\tau(j_{i'_k}...j_{i'_{n-k}})}a_{i'_1j_{i'_1}}...a_{i'_{n-k}j_{i'_{n-k}}}\right)$

根据[[MK21][定义]] $M\left(\begin{matrix}i_1&i_2&...&i_k\\j_1&j_2&...&j_k\end{matrix}\right)=\sum_{\forall j_1...j_k}\left[(-1)^{\tau(j_{i_1}...j_{i_k})}a_{i_1j_{i_1}}...a_{i_kj_{i_k}}\right]$

故有

\begin{aligned}
|A|&=\sum_{\forall 1\leq j_1\leq...\leq j_k\leq n}\sum_{\forall j_1...j_k}\sum_{\forall j'_1...j'_{n-k}}(-1)^{\tau(i_1...i_ki'_1...i'_{n-k})+\tau(j_{i_1}...j_{i_k}j_{i'_k}...j_{i'_{n-k}})}a_{i_1j_{i_1}}...a_{i_kj_{i_k}}a_{i'_1j_{i'_1}}...a_{i'_{n-k}j_{i'_{n-k}}}\\
&=\sum_{\forall 1\leq j_1\leq...\leq j_k\leq n}\sum_{\forall j_1...j_k}\sum_{\forall j'_1...j'_{n-k}}(-1)^{\sum_{u=1}^ki_k+\frac{k(1+k)}{2}+\sum_{u=1}^k j_u +\frac{k(k+2)}{2}+\tau(j_{i_1}...j_{i_k})+\tau(j_{i'_k}...j_{i'_{n-k}})}a_{i_1j_{i_1}}...a_{i_kj_{i_k}}a_{i'_1j_{i'_1}}...a_{i'_{n-k}j_{i'_{n-k}}}\\
&=\sum_{\forall 1\leq j_1\leq...\leq j_k\leq n}\sum_{\forall j_1...j_k}\sum_{\forall j'_1...j'_{n-k}}(-1)^{\sum_{u=1}^ki_k+\sum_{u=1}^k j_u + \tau(j_{i_1}...j_{i_k})+\tau(j_{i'_k}...j_{i'_{n-k}})}a_{i_1j_{i_1}}...a_{i_kj_{i_k}}a_{i'_1j_{i'_1}}...a_{i'_{n-k}j_{i'_{n-k}}}\\
&=\sum_{\forall 1\leq j_1\leq...\leq j_k\leq n}\left\{(-1)^{\sum_{u=1}^ki_k+\sum_{u=1}^k j_u}\sum_{\forall j_1...j_k}\left[(-1)^{\tau(j_{i_1}...j_{i_k})}a_{i_1j_{i_1}}...a_{i_kj_{i_k}}\sum_{\forall j'_1...j'_{n-k}}\left((-1)^{\tau(j_{i'_k}...j_{i'_{n-k}})}a_{i'_1j_{i'_1}}...a_{i'_{n-k}j_{i'_{n-k}}}\right)\right]\right\}\\
&=\sum_{\forall 1\leq j_1\leq...\leq j_k\leq n}\left\{(-1)^{\sum_{u=1}^ki_k+\sum_{u=1}^k j_u}\sum_{\forall j_1...j_k}\left[(-1)^{\tau(j_{i_1}...j_{i_k})}a_{i_1j_{i_1}}...a_{i_kj_{i_k}}M\left(\begin{matrix}i'_1&i'_2&...&i'_{n-k}\\j'_1&j'_2&...&j'_{n-k}\end{matrix}\right)\right]\right\}\\
&=\sum_{\forall 1\leq j_1\leq...\leq j_k\leq n}\left\{(-1)^{\sum_{u=1}^ki_k+\sum_{u=1}^k j_u}M\left(\begin{matrix}i'_1&i'_2&...&i'_{n-k}\\j'_1&j'_2&...&j'_{n-k}\end{matrix}\right)\sum_{\forall j_1...j_k}\left[(-1)^{\tau(j_{i_1}...j_{i_k})}a_{i_1j_{i_1}}...a_{i_kj_{i_k}}\right]\right\}\\
&=\sum_{\forall 1\leq j_1\leq...\leq j_k\leq n}\left\{(-1)^{\sum_{u=1}^ki_k+\sum_{u=1}^k j_u}M\left(\begin{matrix}i'_1&i'_2&...&i'_{n-k}\\j'_1&j'_2&...&j'_{n-k}\end{matrix}\right)M\left(\begin{matrix}i_1&i_2&...&i_k\\j_1&j_2&...&j_k\end{matrix}\right)\right\}\\
&=\sum_{\forall 1\leq j_1\leq j_2\leq...\leq j_k\leq n}(-1)^{\sum_{u=1}^k i_u+\sum_{u=1}^k j_u}M\left(\begin{matrix}i_1&i_2&...&i_k\\j_1&j_2&...&j_k\end{matrix}\right)M\left(\begin{matrix}i'_1&i'_2&...&i'_{n-k}\\j'_1&j'_2&...&j'_{n-k}\end{matrix}\right)\\
&=\sum_{\forall 1\leq j_1\leq j_2\leq...\leq j_k\leq n}(-1)^{\sum_{u=1}^k i_u+\sum_{u=1}^k j_u}M\left(\begin{matrix}i_1&i_2&...&i_k\\j_1&j_2&...&j_k\end{matrix}\right)\overline{M}\left(\begin{matrix}i_1&i_2&...&i_k\\j_1&j_2&...&j_k\end{matrix}\right)
\end{aligned}

*** 推论

根据[[MK12][转置相等]]性质可得任取 $k$ 列亦可

** 部分矩阵行列式公式

*** 对角线不同矩阵

定义 $A=\left[\begin{matrix}x&y&...&y\\y&x&...&y\\\vdots&\vdots&\ddots&\vdots\\y&y&...&x\end{matrix}\right]$ 则 $|A|=(x+(n-1)y)(x-y)^{n-1}$

**** 证明 

根据[[MK19][初等行变换推论]]做初等列变换，将所有 $k,k\ne1$ 列加到第一列得 $|A|=|A_2|=\left|\begin{matrix}x+(n-1)y&y&...&y\\x+(n-1)y&x&...&y\\\vdots&\vdots&\ddots&\vdots\\x+(n-1)y&y&...&x\end{matrix}\right|$

根据[[MK14][行乘系数推论]]对第一列提出 $x+(n-1)y$ 故得 $|A|=|A_3|=(x+(n-1)y)\left|\begin{matrix}1&y&...&y\\1&x&...&y\\\vdots&\vdots&\ddots&\vdots\\1&y&...&x\end{matrix}\right|$

根据[[MK19][初等行变换]]，将所有 $k,k\ne1$ 行减去第一行得 $|A|=|A_4|=(x+(n-1)y)\left|\begin{matrix}1&y&...&y\\0&x-y&...&y\\\vdots&\vdots&\ddots&\vdots\\0&0&...&x-y\end{matrix}\right|$

根据[[MK18][上三角矩阵]]得 $|A|=|A_4|=(x+(n-1)y)(x-y)^{n-1}$

*** 行的指数增加

定义 $A=\left[\begin{matrix}1&1&...&1\\a_1&a_2&...&a_n\\...&...&...&...\\a_1^{n-1}&a_2^{n-1}&...&a_n^{n-1}\end{matrix}\right]$ 则有 $|A|=\prod_{1\leq j\leq i\leq n}(a_i-a_j)$

**** 证明

假设 $n-1$ 阶矩阵上式成立

根据[[MK19][初等行变换]]，将第 $n$ 行减去第 $n-1$ 行乘以 $a_n$ 得 $|A|=|A_1|=\left|\begin{matrix}1&1&...&1&1\\a_1&a_2&...&a_{n-1}&a_n\\...&...&...&...&...\\a_1^{n-2}(a_1-a_n)&a_2^{n-2}(a_2-a_n)&...&a_{n-1}^{n-2}(a_{n-1}-a_n)&0\end{matrix}\right|$

同样对 $n-1$ 行做以上操作 $|A|=|A_2|=\left|\begin{matrix}1&1&...&1&1\\a_1&a_2&...&a_{n-1}&a_n\\...&...&...&...&...\\a_1^{n-3}(a_1-a_n)&a_2^{n-3}(a_2-a_n)&...&a_{n-1}^{n-3}(a_{n-1}-a_n)&0\\a_1^{n-2}(a_1-a_n)&a_2^{n-2}(a_2-a_n)&...&a_{n-1}^{n-2}(a_{n-1}-a_n)&0\end{matrix}\right|$

以此类推 $|A|=|A_{n-1}|=\left|\begin{matrix}1&1&...&1&1\\a_1-a_n&a_2-a_n&...&a_{n-1}-a_n&0\\...&...&...&...&...\\a_1^{n-3}(a_1-a_n)&a_2^{n-3}(a_2-a_n)&...&a_{n-1}^{n-3}(a_{n-1}-a_n)&0\\a_1^{n-2}(a_1-a_n)&a_2^{n-2}(a_2-a_n)&...&a_{n-1}^{n-2}(a_{n-1}-a_n)&0\end{matrix}\right|$

根据[[MK14][行乘系数推论]]对 $k,k\ne n$ 列提出系数 $|A|=|A_n|=\prod_{i=1}^{n-1}(a_i-a_n)\left|\begin{matrix}\frac{1}{a_1-a_n}&\frac{1}{a_2-a_n}&...&\frac{1}{a_{n-1}-a_n}&1\\1&1&...&1&0\\...&...&...&...&...\\a_1^{n-3}&a_2^{n-3}&...&a_{n-1}^{n-3}&0\\a_1^{n-2}&a_2^{n-2}&...&a_{n-1}^{n-2}&0\end{matrix}\right|$

又根据[[MK20][行列式拆分]] $\left|\begin{matrix}\frac{1}{a_1-a_n}&\frac{1}{a_2-a_n}&...&\frac{1}{a_{n-1}-a_n}&1\\1&1&...&1&0\\...&...&...&...&...\\a_1^{n-3}&a_2^{n-3}&...&a_{n-1}^{n-3}\\a_1^{n-2}&a_2^{n-2}&...&a_{n-1}^{n-2}&0\end{matrix}\right|=(-1)^{n+1}\left|\begin{matrix}1&1&...&1\\...&...&...&...\\a_1^{n-3}&a_2^{n-3}&...&a_{n-1}^{n-3}\\a_1^{n-2}&a_2^{n-2}&...&a_{n-1}^{n-2}\end{matrix}\right|$

又根据定义 $\left|\begin{matrix}1&1&...&1\\...&...&...&...\\a_1^{n-3}&a_2^{n-3}&...&a_{n-1}^{n-3}\\a_1^{n-2}&a_2^{n-2}&...&a_{n-1}^{n-2}\end{matrix}\right|= \prod_{1\leq j\leq i\leq n-1}(a_i-a_j)$ 故有 

\begin{aligned}
|A|&=\left\{\prod_{i=1}^{n-1}(a_i-a_n)\right\}\left\{(-1)^{n+1}\prod_{1\leq j\leq i\leq n-1}(a_i-a_j)\right\}\\
&=\left\{(-1)^{n-1}\prod_{i=1}^{n-1}(a_i-a_n)\right\}\left\{\prod_{1\leq j\leq i\leq n-1}(a_i-a_j)\right\}\\
&=\left\{\prod_{i=1}^{n-1}(a_n-a_i)\right\}\left\{\prod_{1\leq j\leq i\leq n-1}(a_i-a_j)\right\}\\
&=\prod_{1\leq j\leq i\leq n}(a_i-a_j)
\end{aligned}
