#+LATEX_CLASS: ctexart

#+TITLE: 多项式

current mark: 86

* 环<<MK10>>

若非空集合 $U$ 上定义有加法（ $+$ ）、乘法（ $\cdot$ ）计算且满足：

（1） 加法结合律： $\forall \{a,b,c\}\subset U\rightarrow (a+b)+c=a+(b+c)$ 

（2） 加法交换律： $\forall\{a,b\}\subset U\rightarrow a+b=b+a$ 

（3） 存在加法[[~/OneDrive/离散数学/Disc_Math.org::MK311][幺元]]： $\exists 0\in U\rightarrow\left((\forall a\in U)\rightarrow(a+0=0+a=a)\right)$ 记作零元

（4） 存在加法[[~/OneDrive/离散数学/Disc_Math.org::MK314][逆元]]： $\forall a\in U(\exists b\in U\rightarrow a+b=b+a=0)$ 其中 $0$ 是加法幺元 

（5） 乘法结合律： $\forall \{a,b,c\}\subset U\rightarrow (ab)c=a(bc)$ 

（6） 分配率： $\forall \{a,b,c\}\subset U\rightarrow(a(b+c)=ab+ac)\land((b+c)a=ba+bc)$ 

（7） 加法和乘法运算封闭，即 $\forall \{a,b\}\subset U\rightarrow a+b\in U\land ab\in U$ 

则称 $\mathcal{U}=<U,+,\cdot>$ 是一个环（ring）

** 其他定义

*** 交换环<<MK12>>

若 $U$ 是环，且满足乘法交换律，即 $\forall\{a,b\}\subset U\rightarrow ab=ba$ 则称为交换环

*** 单位元<<MK11>>

若 $U$ 是环，存在元素 $e\in U$ 与环中的乘法满足[[~/OneDrive/离散数学/Disc_Math.org::MK311][幺元]]定义，则称 $e$ 为单位元

且根据[[~/OneDrive/离散数学/Disc_Math.org::MK312][性质]]可得 $e$ 唯一

** 零元定理<<MK9>>

任意[[MK12][交换环]] $\mathcal{U}=<U,+,\cdot>$ 存在乘法[[~/OneDrive/离散数学/Disc_Math.org::MK313][零元]]，且等于[[MK10][环定义]]中加法幺元

*** 证明

定义 $\foral a\in U$ 由加法幺元（记作 $0$ ）定义可得 $0=0+0$ 则有 $a0=a(0+0)=a0+a0$

由于乘法封闭，故 $a0\in U$ ，根据定义有逆元 $-a0$ 满足 $a0+(-a0)=0$

则有 $a0+(-a0)=a0+a0+(-a0)\rightarrow 0=a0$ 

同理根据乘法交换律可证 $0a=0$ 综上所述 $0$ 是零因子 

** 子环

若存在环 $U$ 其非空子集 $V$ 对于 $U$ 上的加法，乘法满足[[MK10][环定义]]中的条件，则称 $V$ 是 $U$ 的子环

*** 定理

若 $U$ 是环，则 $V\subset U$ 是子环的充要条件是对于任意 $\{a,b\}\subset V$ 均有:

（1） $-b\in V$

（2） $a+(-b)\in V$

（3） $ab\in V$

**** 证明

***** 充分

已知 $V$ 是环，则有逆元 $\forall b\in V\rightarrow -b\in V$ 

由于环的加法封闭，故 $\forall \{a,b\}\subset V\rightarrow a+(-b)\in V$

由于环乘法封闭，故 $\forall \{a,b\}\subset V\rightarrow ab\in V$

***** 必要

已知 $U$ 是环 $V\subset U\land V\ne\varnothing$

故必有元素 $a\in V$ 

根据条件（1），必存在逆元 $-a\in V$ 使得 $a+(-a)=0$ 此处 $0$ 为 $U$ 的零元

根据条件（2）可得 $a+(-a)=0\in V$ 且对于任意 $-b\in V\rightarrow b\in V$

则同理根据条件（2） $a+(-(-b))=a+b\in V$ 故加法封闭

根据条件（3）乘法封闭

综上所述

由于加法封闭，乘法封闭，则满足条件（7）

由于零元逆元均封闭， $V$ 满足[[MK10][环定义]]中条件（3）,（4）

由于加法封闭，则 $V$ 的加法可继承 $U$ 满足环定义中条件（1），（2）

由于乘法封闭，则 $V$ 的乘法可继承 $U$ 满足条件（5），（6）

** 同构

*** 定义<<MK13>>

有环 $U,V$ 若存在[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-特殊函数-双射函数]] $\sigma:U\rightarrow V$ 满足对于任意 $\{a,b\}\subset U$ ：

（1） $\sigma(a+b)=\sigma(a)+\sigma(b)$

（2） $\sigma(ab)=\sigma(a)\sigma(b)$

以上表述中，等式左边 $\sigma$ 内的加/乘法为环 $U$ 上的加/乘法，等式右边的加/乘法为环 $V$ 上的加/乘法

则称 $U,V$ 同构，函数 $\sigma$ 为同构函数

*** 性质

**** 性质1

环 $U,V$ 同构且同构映射为 $\sigma:U\rightarrow V$ 若 $1\in U$ 为 $U$ 的[[MK11][单位元]]，则 $V$ 有单位元且为 $\sigma(1)$

***** 证明

根据单位元定义，对于 $U$ 中的乘法及任意 $a\in U$ 有 $1a=a1=a$

由于同构映射为双射，故对于任意 $a'\in V$ 必有 $a\in U$ 使得 $\sigma(a)=a'$

根据同构函数定义 $a'=\sigma(a)=\sigma(1a)=\sigma(1)\sigma(a)=\sigma(1)a'$

同理可证 $a'\sigma(1)=a'$ 故 $\sigma(1)$ 为 $V$ 的单位元

**** 性质2<<MK70>>

设有数域 $K$ ，环 $R$ 是[[MK12][交换环]]且有[[MK11][单位元]] $1$ ， $R$ 中有一个包含 $1$ 的子环 $I$

若存在[[MK13][同构函数]] $\sigma:K\rightarrow I$ 则定义 $I[\tau]$ 是表达式 $\sum_{i=1}^\infty b_i\tau$ 其中 $b_i\in I$ ， $\tau\in R$ 是变元为 $\tau$ 的[[MK1][一元多项式]]

同时定义 $K[x]$ 是数域 $K$ 上变元为 $x$ 的一元多项式

定义对于表达式 $f(x)=\sum_{i=1}^\infty a_ix^i\land f(x)\in K[x]$ 则有对应表达式 $f(\tau)=\sum_{i=1}^n\sigma(a_i)\tau^i$

则满足：

（1） 根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-相关定义-函数定义]]， $f(x)$ 到 $f(\tau)$ 的关系形成函数

（2） 若有 $\{f(x),g(x),h(x)\}\in K[x]$ 且满足 $f(x)+g(x)=h(x)$ ，则有 $f(\tau)+g(\tau)=h(\tau)$

（3） 若有 $\{f(x),g(x),h(x)\}\in K[x]$ 且满足 $f(x)g(x)=h(x)$ ，则有 $f(\tau)g(\tau)=h(\tau)$

***** 证明

****** 证明（1）

根据函数定义证明

由于 $\sigma$ 是函数，故 $\forall a(a\in K\rightarrow\exists b\in I(<a,b>\in\sigma))$ 

对于任意 $\sum_{i=1}^\infty a_ix^i\in K[x]$ 存在表达式 $\sum_{i=1}^\infty\sigma(a_i)\tau$ 根据定义 $\sum_{i=1}^\infty\sigma(a_i)\tau\in I[\tau]$

由于 $K[x],I[\tau]$ 均为一元多项式，则根据[[MK5][一元多项式相等]]可知元素相同的充要条件为系相同

由于 $\sigma$ 为[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-特殊函数-双射函数]]，故必为单射 $\forall a\forall a'(\{a,a'\}\subset K\land a\ne a'\rightarrow \sigma(a)\ne\sigma(a'))$

故有 $\forall f(x)\forall f'(x)\big(\{f(x),f'(x)\}\subset K[x]\land f(x)\ne f'(x)\rightarrow \f(\tau)\ne f'(\tau)\big)$

故 $f(x)\rightarrow f(\tau)$ 是函数（映射）

****** 证明（2）

定义 $f(x)=\sum_{i=1}^\infty a_ix^i,g(x)=\sum_{i=1}^\infty b_ix^i$ 由于 $\sigma$ 为同构函数，则有：

\begin{aligned}
f(\tau)+g(\tau)&=\sum_{i=1}^\infty \sigma(a_i)x^i+\sum_{i=1}^\infty\sigma(b_i)x^i\\
&=\sum_{i=1}^\infty (\sigma(a_i)+\sigma(b_i))x^i=\sum_{i=1}^\infty\sigma(a_i+b_i)x^i\\
h(x)&=\sum_{i=1}^\infty a_ix^i+\sum_{i=1}^\infty b_ix^i=\sum_{i=1}^\infty(a_i+b_i)x^i\\
h(\tau)&=\sum_{i=1}^\infty\sigma(a_i+b_i)x^i
\end{aligned}

故有 $f(\tau)+g(\tau)=h(\tau)$

****** 证明（3）

定义 $f(x)=\sum_{i=1}^\infty a_ix^i,g(x)=\sum_{i=1}^\infty b_ix^i$ 由于 $\sigma$ 为同构函数，则有：

\begin{aligned}
f(\tau)g(\tau)&=\left(\sum_{i=1}^\infty \sigma(a_i)x^i\right)\left(\sum_{i=1}^\infty\sigma(b_i)x^i\right)\\
&=\sum_{i=1}^\infty\left(\sum_{j=0}^\infty\sigma(a_i)\sigma(b_j)x^{i+j}\right)=\sum_{i=1}^\infty\left(\sum_{j=0}^\infty\sigma(a_ib_j)x^{i+j}\right)\\
h(x)&=\left(\sum_{i=1}^\infty a_ix^i\right)\left(\sum_{i=1}^\infty b_ix^i\right)=\sum_{i=1}^\infty\left(\sum_{j=0}^\infty a_ib_jx^{i+j}\right)\\
h(\tau)&=\sum_{i=1}^\infty\left(\sum_{j=0}^\infty\sigma(a_ib_j)x^{i+j}\right)
\end{aligned}

故有 $f(\tau)g(\tau)=h(\tau)$

* 一元多项式

** 定义<<MK1>>

定义[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][数域]] $K$ ，若有表达式形式为 $f(x)=\sum_{i=0}^d a_ix^i$ ，其中 $a_i\in K$ ，其中 $x$ 是变元，可以有定义域

则称表达式为数域 $K$ 上的一元多项式，满足该条件的所有表达式的集合记作 $K[x]$

若某些项的 $a_i=0$ 则在表达式中可以省略

** 其他定义

*** 零元<<MK3>>

若 $f(x)=\sum_{i=1}^\infty a_ix^i$ 是数域 $K$ 上的一元多项式，若 $\forall i\in N$ 均有 $a_i=0$ 则称 $f(x)$ 为一元多项式的零元，记作 $0(x)$

根据[[MK6][乘法]]定义可得 $0(x)$ 乘以任何一元多项式均为 $0(x)$

根据[[MK2][加法]]定义可得 $0(x)$ 加任意一元多项式 $f(x)$ 有 $f(x)=f(x)+0(x)=0(x)+f(x)$

*** 一元多项式次数<<MK17>>

若一元多项式 $f(x)=\sum_{i=1}^\infty a_ix^i$ 定义集合 $I=\left\{i\big|a_i\ne0\land i\in N\right\}$ 

则根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-特殊关系-序关系-元]]集合 $I$ 的最大元为多项式 $f(x)$ 的次数，记作 $\deg(f(x))$

特殊的，当 $I$ 的最大元为零时，定义 $\deg(f(x))=-\infty$

**** 定理<<MK18>>

若 $f(x),g(x)$ 均为[[MK1][一元多项式]]，则有：

（1） 若 $\deg(f(x))\ne\deg(g(x))$ 则 $\deg(f(x)+g(x))=\max\left(\deg(f(x)),\deg(g(x))\right)$

（2） 若 $\deg(f(x))=\deg(g(x))$ 则 $\deg(f(x)+g(x))\leq\deg(f(x))$

（3） 若 $\deg(f(x))<\infty\land\deg(g(x))<\infty$ 则 $\deg(f(x)g(x))=\deg(f(x))+\deg(g(x))$

***** 证明

仅证（3）

若 $\deg(f(x))=-\infty\lor\deg(g(x))=-\infty$ 则有 $f(x)=0(x)\lor g(x)=0(x)$

根据[[MK3][零元]]可得 $f(x)g(x)=0(x)$ 且 $\deg(0(x))=-\infty$ 

假设 $f(x)=0(x)$ 则有 $\deg(f(x)g(x))=-\infty+\deg(g(x))=-\infty$

若 $\deg(f(x))\ne-\infty\land\deg(g(x))\ne-\infty$ 则假设 $\deg(f(x))=n,\deg(g(x))=m$

则根据[[MK6][乘法]]可得 $f(x)g(x)=\sum_{s=1}^\infty(\sum_{i+j=s}a_ib_j)x^s$

根据次的定义可得 $\forall i>n\rightarrow a_i=0,\forall j>n\rightarrow b_j=0$ 故 $\deg(f(x)g(x))=m+n$

***** 推论1

若 $f(x),f(x)$ 均为一元多项式，则 $f(x)\ne0(x)\land g(x)\ne0(x)$ 的充要条件是 $f(x)g(x)\ne0(x)$

***** 推论2

若 $f(x)g(x)=f(x)h(x)$ 且 $f(x)\ne0(x)$ 则有 $g(x)=h(x)$

****** 证明

根据[[MK7][负元]]可得存在 $-f(x)h(x)$ 使得 $-f(x)h(x)+(-f(x)h(x))=0(x)$ 

则有 $f(x)g(x)+(-f(x)h(x))=f(x)h(x)+(-f(x)h(x))$

化简及应用[[MK8][分配率]]得 $f(x)(g(x)-h(x))=0(x)$ 由于 $f(x)\ne0(x)$

则必有 $g(x)-h(x)=0(x)$ 同理应用负元得 $g(x)=h(x)$

** 代数结构

*** 一元多项式线性空间

根据[[~/OneDrive/高等代数/Algb-2-Liner_Space.org][线性空间定义]]，定义集合 $V$ 为所有[[MK1][一元多项式]]组成的集合，则 $V$ 是线性空间

其中一组基为 $\{x^0,...,x^n,...\}$ 该空间为无限维线性空间，即 $\dim(V)=\infty$

**** 证明

***** 证明是线性空间

****** 加法交换律

若 $f(x)=\sum_{i=0}^\infty a_ix^i,g(x)=\sum_{i=0}^\infty b_ix^i$ 且 $\{f(x),g(x)\}\subset V$

则根据[[MK2][加法]]定义可得 $f(x)+g(x)=\sum_{i=1}^\infty(a_i+b_i)x^i=\sum_{i=1}^\infty(b_i+a_i)x^i=g(x)+f(x)$

****** 加法结合律

若 $f(x)=\sum_{i=0}^\infty a_ix^i,g(x)=\sum_{i=0}^\infty b_ix^i,h(x)=\sum_{i=0}^\infty c_ix^i$ 且 $\{f(x),g(x),h(x)\}\subset V$

则根据[[MK2][加法]]定义可得 $(f(x)+g(x))+h(x)=\sum_{i=1}^\infty((a_i+b_i)+c_i)x^i=\sum_{i=1}^\infty(a_i+(b_i+c_i))x^i=f(x)+(g(x)+h(x))$

****** 零元

根据[[MK3][零元]]定义

****** 负元<<MK7>>

对于任意 $f(x)\in V$ 其负元为 $(-1)f(x)$ 根据[[MK1][定义]]函数有形式 $f(x)=\sum_{i=1}^\infty a_ix^i$

则根据[[MK4][数乘]]运算可得 $(-1)f(x)=\sum_{i=1}^\infty -a_ix^i$ 同时根据[[MK3][加法]]可得 $f(x)+(-1)f(x)=\sum_{i=1}^n(a_i-a_i)x_i$

根据[[MK3][零元]]定义可得 $f(x)+(-1)f(x)=0(x)$

****** 幺元

对于任意 $f(x)\in V$ 函数有形式 $f(x)=\sum_{i=1}^\infty a_ix^i$

根据[[MK4][数乘]]运算可得 $1\times f(x)=\sum_{i=1}^\infty 1\times a_ix^i=\sum_{i=1}^\infty a_ix^i$

****** 数乘结合律

对于任意 $f(x)\in V$ 函数有形式 $f(x)=\sum_{i=1}^\infty a_ix^i$

对于任意 $\{l,k\}\subset K$ 根据[[MK4][数乘]]运算可得 $(lk)f(x)=\sum_{i=1}^\infty (lk)a_ix^i=\sum_{i=1}^\infty l(ka_ix^i)=l(kf(x))$

****** 数乘前分配率

对于任意 $f(x)\in V$ 函数有形式 $f(x)=\sum_{i=1}^\infty a_ix^i$

对于任意 $\{l,k\}\subset K$ 根据[[MK4][数乘]]运算可得 $(l+k)f(x)=\sum_{i=1}^\infty (l+k)a_ix^i=\sum_{i=1}^\infty la_ix^i+\sum_{i=1}^\infty ka_ix^i=lf(x)+kf(x)$

****** 数乘后分配率

对于任意 $\{f(x),g(x)\}\subset V$ 函数有形式 $f(x)=\sum_{i=1}^\infty a_ix^i,g(x)=\sum_{i=1}^\infty b_ix^i$

对于任意 $l\in K$ 根据[[MK4][数乘]]以及[[MK2][加法]]运算可得 $(l+k)f(x)=\sum_{i=1}^\infty (l+k)a_ix^i=\sum_{i=1}^\infty la_ix^i+\sum_{i=1}^\infty ka_ix^i=lf(x)+kf(x)$

***** 证明基

****** step 1

先证明 $\forall l\in N\rightarrow x^l\in V$ 根据[[MK1][定义]]可得对于任意 $f(x)\in V$ 均有 $f(x)=\sum_{i=1}^\infty a_ix^i$ 的形式

则定义 $a_i=\begin{cases}1&i=l\\0&i\ne l\end{cases}$ 固有 $f(x)=\sum_{i=1}^\infty a_ix^i=x^l$ 

****** step 2

再证明 $\{x^0,...,x^n,...\}$ 线性不相关

根据[[~/OneDrive/高等代数/Algb-2-Liner_Space.org][线性空间的基和维数-线性空间中向量组的定义-子集线性无关]]，取任意 $\{x^{i_1},...,x^{i_n}\}\subset\{x^0,...,x^n,...\}$ 其中 $n\leq\infty$

根据集合定义 $a\ne b\rightarrow i_a\ne i_b$ 构造等式 $0(x)=\sum_{j=1}^nk_jx^{i_j}$ 其中 $k_j\in K$ 且 $0(x)$ 为[[MK3][零元]]

根据零元定义以及[[MK5][相等]]定义可得，当且仅当 $(\forall j\in N\land 0\leq j\leq n)\rightarrow k_j=0$ 成立时 $0(x)=\sum_{j=1}^nk_jx^{i_j}$

故线性不相关 

****** step 3

最后证所有元素均可由集合中的元素线性表述

根据定义，任意 $f(x)\in V$ 均有 $f(x)=\sum_{i=0}^\infty a_ix^i$ 的形式

由于 $x^i\in\{x^0,...,x^n,...\}$ 则根据[[MK4][数乘]]定义可得任意 $f(x)\in V$ 均可取 $k_i=a_i$ 使得 $f(x)=\sum_{i=0}^\infty k_ix^i$

即由 $\{x^0,...,x^n,...\}$ 线性表述

***** 证明维数

由于之前证明得 $V$ 的一组基为 $\{x^0,...,x^n,...\}$ ，则根据[[~/OneDrive/高等代数/Algb-2-Liner_Space.org][线性空间的基和维数-线性空间的维数]]可得 $\dim(V)=\infty$

*** 一元多项式环<<MK15>>

[[MK1][一元多项式]]集合 $K[x]$ 是[[MK10][环]]

**** 证明

定义 $f(x)=\sum_{i=0}^\infty a_ix^i,g(x)=\sum_{i=0}^\infty b_ix^i,h(x)=\sum_{i=0}^\infty c_ix^i$ 是 $K[x]$ 的任意一元多项式  根据[[MK10][环定义]]证明

（1） 根据[[MK2][加法]]可得 $(f(x)+g(x))+h(x)=\sum_{i=1}^\infty((a_i+b_i)+c_i)x^i=\sum_{i=1}^\infty(a_i+(b_i+c_i))x^i=f(x)+(g(x)+h(x))$

（2） 根据[[MK2][加法]]可得 $f(x)+g(x)=\sum_{i=1}^\infty(a_i+b_i)x^i=\sum_{i=1}^\infty(b_i+a_i)x^i=g(x)+f(x)$ 

（3） 根据[[MK3][零元]]可得 $\forall f(x)\bigg(f(x)\in K[x]\rightarrow\exists 0(x)\big(f(x)+0(x)=0(x)+f(x)=f(x)\big)\bigg)$

（4） 根据[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][数域]]可得 $-1\in K$ 则结合乘法 $\forall \sum_{i=0}^\infty a_ix^i\in K[x]$ 均有 $(-1)\sum_{i=0}^\infty a_ix^i=\sum_{i=0}^\infty -a_ix^i\in K[x]$

     结合加法可得 $\sum_{i=0}^\infty a_ix^i+(-1)\sum_{i=0}^\infty a_ix^i=\sum_{i=0}^\infty 0x^i=0(x)$

（5） 根据[[MK8][乘法性质]]可得交换律

（6） 根据[[MK6][乘法性质]]可得与加法的分配率

（7） 由于 $K$ 为数域，故 $\forall\{a,b\}\subset K\rightarrow ab\in K\land a+b\in K$ 则有加法，乘法封闭

** 一元多项式运算

*** 相等<<MK5>>

定义 $f(x)=\sum_{i=0}^\infty a_ix^i,g(x)=\sum_{i=0}^\infty b_ix^i$ ，若 $f(x)=g(x)$ 则其充要条件为 $a_i=b_i$ 对于任意 $i\in N$

**** 性质<<MK20>>

$f_1(x)=g_1(x)\land f_2(x)=g_2(x)\rightarrow f_1(x)+f_2(x)=g_1(x)+g_2(x)$

交换律： $f(x)+g(x)=g(x)+f(x)$

结合律： $(f(x)+g(x))+h(x)=f(x)+(g(x)+h(x))$

传递性： $f(x)=g(x)\land g(x)=h(x)\rightarrow f(x)=h(x)$

*** 加法<<MK2>>

若 $f(x)=\sum_{i=0}^\infty a_ix^i,g(x)=\sum_{i=0}^\infty b_ix^i$ 是一元多项式，则定义 $f(x)+g(x)=\sum_{i=1}^\infty(a_i+b_i)x^i$

**** 性质<<MK20>>

交换律： $f(x)+g(x)=g(x)+f(x)$

结合律： $(f(x)+g(x))+h(x)=f(x)+(g(x)+h(x))$

加法相等： $f_1(x)=g_1(x)\land f_2(x)=g_2(x)\rightarrow f_1(x)+f_2(x)=g_1(x)+g_2(x)$

*** 减法<<MK53>>

定义为 $f(x)-g(x)=f(x)+(-1)g(x)$

**** 性质<<MK54>>

$f(x)-g(x)=0(x)\rightarrow f(x)=g(x)$

*** 乘法<<MK6>>

若 $f(x)=\sum_{i=0}^\infty a_ix^i,g(x)=\sum_{i=0}^\infty b_ix^i$ 是一元多项式，则定义 $f(x)g(x)=\left(\sum_{i=0}^\infty a_ix^i\right)\left(\sum_{i=0}^\infty b_ix^i\right)$

进一步 $f(x)g(x)=\sum_{i=1}^\infty\left(\sum_{j=1}^na_ib_jx^{i+j}\right)=\sum_{s=0}^\infty\left(\sum_{i+j=s}a_ib_j\right)x^s$

**** 性质<<MK8>>

交换律： $f(x)g(x)=g(x)f(x)$

结合律： $(f(x)g(x))h(x)=f(x)(g(x)h(x))$

对于加法的分配率： $f(x)(g(x)+h(x))=f(x)g(x)+f(x)h(x)$

存在幺元 $1$ ： $1f(x)=f(x)1=f(x)$

消去律： $f(x)g(x)=f(x)h(x)\land f(x)\ne0(x)\rightarrow g(x)=h(x)$

***** 证明

仅证消去律

****** 等式整理

根据 $K[x]$ [[MK15][是环]]的证明：（1）任意元素存在逆元;（2）加/乘法封闭

故有 $f(x)h(x)$ 存在逆元为 $(-1)f(x)h(x)$

则根据[[MK20][加法性质]]两边同加 $f(x)g(x)+(-f(x)h(x))=f(x)h(x)+(-f(x)h(x))$

根据逆元定，乘法交换律结合律义得 $f(x)g(x)+f(x)((-1)h(x))=0(x)$

根据分配率得 $f(x)(g(x)+(-1)h(x))=0(x)$

****** 反证第二项为零元

根据运算封闭性定义 $f(x)=\sum_{i=1}^\infty a_ix^i,g(x)+(-1)h(x)=\sum_{i=1}^\infty b_ix^i$

则根据定义有 $f(x)(g(x)+(-1)h(x))=\sum_{s=0}^\infty\left(\sum_{i+j=s}a_ib_j\right)x^s$

由于 $f(x)\ne0(x)$ 根据[[MK3][零元]]定义得必存在 $a_k\ne 0$

此时假 $g(x)+(-1)h(x)\ne0(x)$ 则存在 $b_u\ne0$ 

故 $f(x)(g(x)+(-1)h(x))$ 必有 $a_kb_ux^{u+k}$ 一项系数不为零

根据[[MK3][零元]]定义 $f(x)(g(x)+(-1)h(x))\ne0(x)$ 与定义冲突，故必有 $g(x)+(-1)h(x)=0(x)$ 

****** 证明结论

同样根据[[MK20][加法性质]] $g(x)+(-1)h(x)+h(x)=h(x)$ 

根据逆元、零元性质 $g(x)+(-1)h(x)+h(x)=g(x)+0(x)=g(x)$

最终有 $g(x)=h(x)$

*** 幂<<MK49>>

若 $f(x)\in K[x]$ 则定义 $f^n(x)=\prod_{i=1}^n f(x)$ 称为 $f(x)$ 的 $n$ 次幂

定义 $f^0(x)=1$

*** 数乘<<MK4>>

若 $f(x)=\sum_{i=0}^\infty a_ix^i$ 是数域 $K$ 上的一元多项式，若 $k\in K$ 则可视为 $g(x)=k=\sum_{i=0}^\infty b(i)x^i$ 其中 $b(i)=\begin{cases}k&i=0\\0&else\end{cases}$

则 $kf(x)=k\sum_{i=1}^na_ix^i=\sum_{i=1}^nka_ix^i$

*** 整除

**** 定义<<MK19>>

对于 $\{f(x),g(x)\}\subset K[x]$ 若存在 $h(x)\in K[x]$ 满足 $f(x)=h(x)g(x)$ 则称 $g(x)$ 可以整除 $f(x)$ 记作 $g(x)\mid f(x)$

此时 $g(x)$ 称为 $f(x)$ 的因式， $f(x)$ 是 $g(x)$ 的被式， $h(x)$ 为商式

反之则称 $g(x)$ 可以不能 $f(x)$ 记作 $g(x)\nmid f(x)$

**** 性质

***** 零次多项式是所有元素的因式<<MK30>>

定义 $b\in K[x]$ 为零次[[MK1][多项式]]且 $b\ne0$ ，则有 $\forall f(x)(f(x)\in K[x]\rightarrow b\nmid f(x))$

****** 证明

零次多项式定义为 $b=a_0x^0\land b\ne 0$ 根据[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][数域]] $1\in K$ 则有 $\frac{1}{b}\in K$ 同理 $\frac{1}{b}$ 亦为零次一元多项式

根据[[MK6][乘法]]可得 $f(x)=\left(\frac{1}{b}f(x)\right)b=f(x)$

***** 零元是任意多项式的被式<<MK44>>

若 $0(x)\in K[x]$ 是[[MK3][零元]]，则 $\forall f(x)\in K[x]$ 均有 $f(x)\mid 0(x)$

****** 证明

根据[[MK15][一元多项式环]]可得 $0(x)$ 是 $K[x]$ 的零元，根据[[MK9][定理]]可得零元是零因子，即 $0(x)f(x)=0(x)$

故得结论 $f(x)\mid 0(x)$

***** 零元的被式是零元<<MK21>>

若 $0(x)\in K[x]$ 是[[MK3][零元]]且 $0(x)$ 可以整除 $f(x)$ 即 $0(x)\mid f(x)$ 则 $f(x)=0(x)$

****** 证明

根据定义必须满足 $f(x)=0(x)h(x)$ 根据[[MK9][定理]] $\forall h(x)\in K[x]\rightarrow 0(x)h(x)=0(x)$

故得定理

***** 因式的次数小于等于被试<<MK22>>

若 $g(x)\mid f(x)$ 且 $\deg(f(x))\ne-\infty$ 则他们的[[MK17][次数]]关系是 $\deg(g(x))\leq\deg(f(x))$

****** 证明

根据定义满足 $f(x)=g(x)h(x)$ 则根据[[MK18][定理]]可得 $\deg(f(x))=\deg(g(x))+\deg(h(x))$

由于 $\deg(f(x))\in N^+\cup\{0,-\infty\}$ 故若 $\deg(f(x))\ne-\infty$ 则有 $\deg(g(x))\ne-\infty\land\deg(h(x))\ne-\infty$

故 $\deg(h(x))\in N^+\cup\{0,-\infty\}$ 故 $\deg(f(x))-\deg(h(x))=\deg(g(x))$

故得 $\deg(g(x))\leq\deg(f(x))$

***** 被试和整除<<MK28>>

若 $g(x)\mid f_i(x),i=1,2,...,n$ 则对于任意 $\{u_1(x),...,u_n(x)\}\subset K[x]$ 均有 $g(x)\mid \sum_{i=1}^n u_i(x)f_i(x)$

****** 证明 

根据定义有 $f_i(x)=h_i(x)g(x)$ 则根据[[MK8][乘法性质]]交换律，结合律有

\begin{aligned}
\sum_{i=1}^n u_i(x)f_i(x)&=\sum_{i=1}^n u_i(x)h_i(x)g(x)\\
&=g(x)\sum_{i=1}^n u_i(x)h_i(x)
\end{aligned}

故 $g(x)\mid \sum_{i=1}^n u_i(x)f_i(x)$

***** 整除性与数域无关<<MK77>>

若在数域 $K[x]$ 上有 $p(x)\mid f(x)$ 则对于任意数域 $K'[x]$ ，只要满足 $\{p(x),f(x)\}\subset K'[x]$ 则有 $p(x)\mid f(x)$

****** 证明

由于在 $K[x]$ 上有 $p(x)\mid f(x)$ 根据定义有 $f(x)=h(x)p(x)$

则定义 $h(x)=\sum_{i=0}^\infty a_ix^i,p(x)=\sum_{i=0}^\infty b_ix^i$ 故有 $f(x)=\sum_{s=0}^\infty\left(\sum_{i+j=s}a_ib_j\right)x^s$

根据[[MK1][定义]]及条件 $\{p(x),f(x)\}\subset K'[x]$ ，则 $\forall i\in\mathbb{N}\forall s\in\mathbb{N}(b_i\in K'[x]\land \sum_{i+j=s}a_ib_j\in K'[x])$

故根据[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][数域]]可得 $a_i\in K'[x]$ 则 $h(x)\in K'[x]$

则根据[[MK5][相等]]定义可得在数域 $K'[x]$ 上有 $h(x)p(x)=f(x)$ 即满足整除定义

**** 整除关系

***** 定义

根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-二元关系-基础定义]]，对于任意 $\{f(x),g(x)\}\subset K[x]$ 要么 $g(x)\mid f(x)$ 要么 $g(x)\nmid f(x)$

则把满足 $g(x)\mid f(x)$ 的元素对组成[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-基本定义-有序组]]

进一步把所有满足条件元素对组成的有序组的集合定义为 $R\subset K[x]\times K[x]$

则此时根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-二元关系-基础定义]] $R$ 是集合 $K[x],K[x]$ 上的二元关系

***** 性质

根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-二元关系-关系性质-定义]]

****** 自反性

对于任意 $f(x)\in K[x]$ 均有 $f(x)\mid f(x)$

******* 证明

$f(x)=1f(x)$

****** 传递性

对于任意 $\{f(x),g(x),h(x)\}\in K[x]$ 若 $f(x)\mid g(x)\land g(x)\mid h(x)$ 则有 $f(x)\mid h(x)$

******* 证明

根据[[MK19][定义]]可得存在 $u(x),v(x)$ 使得 $g(x)=u(x)f(x)\land h(x)=v(x)g(x)$

则有 $h(x)=v(x)(u(x)f(x))$ 根据[[MK8][结合律]] $h(x)=(v(x)u(x))f(x)$ 故满足 $f(x)\mid h(x)$

**** 相伴<<MK31>>

若 $\{f(x),g(x)\}\subset K[x]$ 且有 $f(x)\mid g(x)\land g(x)\mid f(x)$ 则称 $f(x),g(x)$ 相伴，记作 $f(x)\sim g(x)$

***** 定理<<MK36>>

$f(x),g(x)$ 相伴且的充要条件是 $f(x)=cg(x)$ 其中 $c\in K$

****** 证明

******* 充分

若 $f(x)\mid g(x)\land g(x)\mid f(x)$ 根据[[MK19][定义]]则有 $f(x)=u(x)g(x)\land g(x)=v(x)f(x)$

若 $f(x)=0(x)$ 是零元，则根据[[MK21][零元被式]]可得 $g(x)=0(x)$ 则满足 $f(x)=cg(x)=0(x)$

若 $f(x)\ne0(x)$ 则 $f(x)=u(x)(v(x)f(x))$ 根据[[MK8][乘法性质]]结合律、交换律可得 $1f(x)=(u(x)v(x))f(x)$

根据[[MK8][乘法性质]]消去律可得 $1=u(x)v(x)$ 根据[[MK18][次数定理]]可得 $\deg(v(x))\leq\deg(1)=0$

若 $\deg(v(x))=-\infty$ 则 $v(x)=0(x)$ 故 $u(x)v(x)=0(x)$ 与条件不符

故 $\deg(v(x))=0$ 故 $v(x)$ 为常数，有 $f(x)=cg(x)$

******* 必要

$f(x)=cg(x)$ 则根据[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][数域]] $1\in K\rightarrow \frac{1}{c}\in K$ 则有 $g(x)=\frac{1}{c}f(x)$

则根据[[MK19][定义]]可得 $f(x)\mid g(x)\land g(x)\mid f(x)$ 

*** 带余除法

**** 定义<<MK23>>

对于任意 $\{f(x),g(x)\}\subset K[x]$ 其中 $\deg(f(x))\geq\deg(g(x))$

则若存在 $\{h(x),r(x)\}\subset K[x]$ 满足 $f(x)=h(x)g(x)+r(x)$ 且 $\deg(r(x))<\deg(g(x))$

则定义 $h(x)g(x)+r(x)$ 为 $f(x)$ 对 $g(x)$ 的带余除法表达

$h(x)$ 为商式， $f(x)$ 为被试， $g(x)$ 为除式 $r(x)$ 称为余式

**** 性质

***** 存在性<<MK24>>

对于任意有限[[MK17][次数]]的 $\{f(x),g(x)\}\subset K[x]$ 且 $\deg(f(x))\geq\deg(g(x))$ ，带余除法表达一定存在

****** 证明

由于次数有限，故元素根据[[MK1][定义]]可表达为 $f(x)=\sum_{i=0}^n a_ix^i,g(x)=\sum_{i=0}^m b_ix^i$ 且 $n\geq m$

******* 证明 $m=n$

假设 $n=m$ 且由于 $K$ 是[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][数域]]且 $\{a_n,b_m\}\subset K$ 故有 $\frac{a_n}{b_m}\in K$

则有 $f(x)-\frac{a_n}{b_m}g(x)=\sum_{i=0}^{n-1}\left(a_i-\frac{a_n}{b_m}b_i\right)x^i$

根据[[MK20][加法性质]]，两边同加 $\frac{a_n}{b_m}g(x)$ 则有 $f(x)=\frac{a_n}{b_m}g(x)+\sum_{i=0}^{n-1}\left(a_i-\frac{a_n}{b_m}b_i\right)x^i$ 

此时 $\deg(r(x))<\deg(g(x))$ 满足带余除法表达[[MK23][定义]]

******* 当 $m+1$ 存在带余除法表达时 $m$ 亦存在

假设 $n\geq m+1$ 定义 $g'(x)=\sum_{i=1}^{m+1}b_{i-1}x^i$ 

根据条件 $g'(x)$ 与 $f(x)$ 存在带余除法表达，定义为 $f(x)=h(x)g'(x)+r(x)$

定义 $h'(x)=x$ 则有 $h'(x)g(x)=\sum_{i=1}^{m+1}b_{i-1}x^i=g'(x)$

故有 $f(x)=h(x)\left(h'(x)g(x)\right)+r(x)$ 根据[[MK8][结合律]]可得 $f(x)=(h(x)h'(x))g(x)+r(x)$

此时若 $\deg(r(x))<\deg(g(x))$ 则满足带余除法表达

若 $\deg(r(x))=\deg(g(x))$ 则根据第一步证明，存在带余除法表达 $r(x)=h''(x)g(x)+r'(x)$ 

根据[[MK2][加法]]和[[MK6][乘法]]及其性质可得 

\begin{aligned}
f(x)&=(h(x)h'(x))g(x)+h''(x)g(x)+r'(x)\\
&=(h(x)h'(x)+h''(x))g(x)+r'(x)
\end{aligned}

此时 $\deg(r'(x))<\deg(g(x))$ 故满足带余除法表达[[MK23][定义]]

******* 结论

对于任意 $f(x)\in K[x]$ 若其 $\deg(f(x))=n$ 则对于任意 $g(x)\in K[x]$ 

（1） 若 $\deg(g(x))=\deg(f(x))$ 则根据第一步证明存在带余除法表达

（2） 当 $\deg(g(x))=n$ 时存在带余除法表达，则根据证明第二步 $\deg(g(x))=n-1$ 时亦存在带余除法表达

（3） 以此类推

故对于任意 $\{f(x),g(x)\}\subset K[x]$ 当 $\deg(f(x))\geq\deg(g(x))$ 时，根据数学归纳法，均存在带余除法表达

***** 唯一性<<MK25>>

对于任意 $\{f(x),g(x)\}\subset K[x]$ 其中 $\deg(f(x))\geq\deg(g(x))$ ，带余除法表达唯一

****** 证明

假设存在带余除法表达：

（1） $f(x)=h(x)g(x)+r(x)$ 且 $\deg(r(x))<\deg(g(x))$

（2） $f(x)=h'(x)g(x)+r'(x)$ 且 $\deg(r'(x))<\deg(g(x))$

若 $g(x)=0(x)$ 则：

必有 $f(x)=r(x)\land f(x)=r'(x)$ 根据[[MK20][传递性]]可得 $r(x)=r'(x)$

若 $g(x)\ne0(x)$ 则：

根据[[MK20][加法性质]]及[[MK8][乘法性质]]等式相减并整理

\begin{aligned}
f(x)-f(x)&=(h(x)-h'(x))g(x)+(r(x)-r'(x))\\
0(x)&=(h(x)-h'(x))g(x)+(r(x)-r'(x))\\
r(x)-r'(x)&=(h(x)-h'(x))g(x)\\
\end{aligned}

若 $r(x)-r'(x)\ne0(x)$ 则根据[[MK19][定义]] $g(x)$ 整除 $r(x)-r'(x)$

根据[[MK22][性质]]可得 $\deg(r(x)-r'(x))\geq g(x)$ 由于 $r(x)<g(x)\land r'(x)<g(x)$

根据[[MK2][加法]]可得 $\deg(r(x)-r'(x))<g(x)$ 两者矛盾

故必有 $r(x)-r'(x)=0(x)$ 移项可得 $r(x)=r'(x)$

由于 $g(x)\ne0(x)$ 故必有 $h(x)-h'(x)=0(x)$ 同理移项得 $h(x)=h'(x)$

故有 $h(x)g(x)+r(x)=h'(x)g(x)+r'(x)$ 即唯一。

****** 推论1

若 $\{g(x),f(x)\}\subset K[x]$ 且 $g(x)\mid f(x)$ 即 $g(x)$ [[MK19][整除]] $f(x)$

则 $f(x)$ 对 $g(x)$ 的带余除法表达式中余式为 $0(x)$

******* 证明

根据整除定义，存在 $h(x)$ 使得 $f(x)=h(x)g(x)=h(x)g(x)+0(x)$

根据[[MK23][带余除法定义]] $f(x)=h(x)g(x)+0(x)$ 满足带余除法表达

根据唯一性 $f(x)$ 对 $g(x)$ 的带余除法表达唯一，余式只能为 $0(x)$

***** 定理

若 $\{g(x),f(x)\}\subset K[x]$ 存在 $K\subset E$ 同为[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][数域]]，则有 $\{g(x),f(x)\}\subset E[x]$

则在 $E[x]$ 上 $g(x)\mid f(x)$ 的充要条件是在 $K[x]$ 上 $g(x)\mid f(x)$

****** 证明

******* 充分

假设在 $E[x]$ 上 $g(x)\mid f(x)$ 则根据[[MK19][整除定义]]在 $E[x]$ 上存在 $h'(x)$ 使得 $f(x)=h'(x)g(x)=h'(x)g(x)+0(x)$

根据[[MK24][存在性]]可得在 $K[x]$ 上存在带余除法表达式 $f(x)=h(x)g(x)+r(x)$ 其中 $\{h(x),r(x)\}\subset E[x]$

由于 $K\subset E$ 则有 $\{h(x),r(x)\}\subset E[x]$ 故 $f(x)=h(x)g(x)+r(x)$ 亦为 $E(x)$ 上的表达式。

根据[[MK25][唯一性]]可得 $r(x)=0(x)\land h'(x)=h(x)$ 故在 $K[x]$ 上有 $f(x)=h(x)g(x)$

故在 $K[x]$ 上 $g(x)\mid f(x)$

******* 必要

若在 $K[x]$ 上 $g(x)\mid f(x)$ 根据整除定义可得在 $K[x]$ 上有 $f(x)=h(x)g(x)$ 其中 $h(x)\in K[x]$

由于 $K\subset E$ 则有 $h(x)\in E[x]$ 则在 $E[x]$ 上 $g(x)\mid f(x)$

* 因式、可约与根

** 因式

*** 因式<<MK40>>

若 $f(x)\in K[x]$ 存在 $g(x)\mid f(x)$ 即[[MK19][整除]]，则称 $g(x)$ 是 $f(x)$ 的一个因式

*** 公因式<<MK42>>

若 $\{f_1(x),...,f_n(x)\}\subset K[x]$ 若 $h(x)\in K[x]$ 满足 $h(x)\mid f_1(x)\land...\land h(x)\mid f_n(x)$ 

即[[MK19][整除]]，则称 $h(x)$ 是 $f_1(x),...,f_n(x)$ 的公因式

*** 最大公因式<<MK26>>

若 $\{f_1(x),...,f_n(x)\}\subset K[x]$ 存在 $d(x)$ 满足对于任意 $f_1(x),...,f_n(x)$ 的[[MK42][公因式]] $h(x)$ 均有 $h(x)\mid d(x)$ 

则称 $d(x)$ 是 $f_1(x),...,f_n(x)$ 的最大公因式

*** 首一最大公因式<<MK38>>

若 $\{f_1(x),...,f_n(x)\}\subset K[x]$ 且 $d(x)$ 是 $f_1(x),...,f_n(x)$ 的最大公因式

由于[[MK32][性质]]可知最大公因式相伴，故根据[[MK36][定理]]任意最大公因式 $a(x)=kb(x)$ 

则定义 $(f_1(x),...,f_n(x))$ 为最高[[MK17][次]]项系数为 $1$ 的[[MK26][最大公因式]]

亦可称为首一最大公因式

*** 重因式

若 $f(x)\in K[x]$ 若存在 $p(x)$ 满足：

（1） $p(x)$ 不可约

（2） $p^n(x)\mid f(x)$ 即 $p(x)$ 的 $n$ 次[[MK49][幂]]整除 $f(x)$

（3） $p^{n+1}(x)\nmid f(x)$

则称 $p(x)$ 是 $f(x)$ 的 $n$ 重因式

** 互素<<MK34>>

若 $\{f_1(x),...,f_n(x)\}\subset K[x]$ 且其[[MK38][首一最大公因式]] $(f_1(x),...,f_n(x))=1$ 

则称 $f_1(x),...,f_n(x)$ 互素

*** 性质

**** 多项式与零多项式的公因式<<MK21>>

$\forall f(x)\in K[x]$ 其与 $0(x)$ 的公因式为 $f(x)$

***** 证明

根据[[MK19][整除]]可得 $f(x)\mid f(x)\land f(x)\mid 0(x)$ 则 $f(x)$ 为公因式

假设公因式 $h(x)$ 则必有 $h(x)\mid f(x)$

故任意公因式均可整除 $f(x)$ 根据[[MK26][定义]]可得 $f(x)$ 为最大公因式

且根据[[MK21][零元被试]]，当 $f(x)\ne0(x)$ 时，不成立 $0(x)\mid f(x)$ 故 $0(x)$ 不为公因式

**** 零多项式与零多项式的公因式

$0(x)$ 与 $0(x)$ 的公因式为 $0(x)$

***** 说明

根据[[MK19][整除]]可得 $\forall f(x)\in K[x]\rightarrow f(x)\mid 0(x)$ 此时 $\deg(f(x))$ 为自然数 $\deg(0(x))=-\infty$

但根据[[MK21][性质1]]可得 $0(x)$ 与 $0(x)$ 的最大公因式为 $0(x)$

**** 引理<<MK29>>

若 $\{f(x),g(x)\}\subset K[x]$ 假设其[[MK23][带余除法]]表达式为 $f(x)=h(x)g(x)+r(x)$ 则有：

（1） $c(x)\in K[x]$ 为 $f(x),g(x)$ 公因式的充要条件为 $c(x)$ 是 $g(x),r(x)$ 的公因式

（2） $d(x)\in K[x]$ 为 $f(x),g(x)$ 最大公因式的充要条件为 $d(x)$ 是 $g(x),r(x)$ 的最大公因式

***** 证明

****** 证明（1）

******* 充分

由于 $f(x)=h(x)g(x)+r(x)$ 根据[[MK20][加法相等]]两边同加 $h(x)g(x)$ 逆元得 $f(x)-h(x)g(x)=r(x)$

由于 $c(x)$ 是 $f(x),g(x)$ 的公因式，故有 $c(x)\mid f(x)\land c(x)\mid g(x)$ 根据[[MK28][被试和整除]]有 $c(x)\mid f(x)-h(x)g(x)$

故有 $c(x)\mid r(x)$ 结合 $c(x)\mid g(x)$ 得 $c(x)$ 为 $g(x),r(x)$ 公因式

******* 必要

由于 $f(x)=h(x)g(x)+r(x)$ 且 $c(x)$ 是 $r(x),g(x)$ 的公因式，故有 $c(x)\mid r(x)\land c(x)\mid g(x)$ 根据[[MK28][被试和整除]]有 $c(x)\mid h(x)g(x)+r(x)$

故有 $c(x)\mid f(x)$ 结合 $c(x)\mid g(x)$ 得 $c(x)$ 为 $g(x),f(x)$ 公因式

****** 证明（2）

******* 充分

根据本引理结论（1）结合 $d(x)$ 是 $f(x),g(x)$ 公因式可得 $d(x)$ 亦为 $g(x),r(x)$ 公因式

同理对于任意 $c(x)$ 为 $r(x),g(x)$ 公因式可得 $c(x)$ 亦为 $g(x),f(x)$ 公因式

由于 $d(x)$ 为 $f(x),g(x)$ 的[[MK26][最大公因式]]，则有 $c(x)\mid d(x)$

综上所述：

（1） $d(x)$ 为 $g(x),r(x)$ 公因式

（2） 任意 $c(x)$ 为 $r(x),g(x)$ 公因式可得 $c(x)\mid d(x)$

故 $d(x)$ 为 $r(x),g(x)$ 的最大公因式

******* 必要

根据本引理结论（1）结合 $d(x)$ 是 $r(x),g(x)$ 公因式可得 $d(x)$ 亦为 $g(x),f(x)$ 公因式

同理对于任意 $c(x)$ 为 $f(x),g(x)$ 公因式可得 $c(x)$ 亦为 $r(x),f(x)$ 公因式

由于 $d(x)$ 为 $r(x),g(x)$ 的[[MK26][最大公因式]]，则有 $c(x)\mid d(x)$

综上所述：

（1） $d(x)$ 为 $g(x),f(x)$ 公因式

（2） 任意 $c(x)$ 为 $f(x),g(x)$ 公因式可得 $c(x)\mid d(x)$

故 $d(x)$ 为 $f(x),g(x)$ 的最大公因式

**** 辗转相除法<<MK33>>

对于任意有限[[MK17][次]]一元多项式 $\{f(x),g(x)\}\subset K[x]$ ，根据[[MK24][存在性]]必有[[MK23][带余除法]]表达式 $f(x)=h_1(x)g(x)+r_1(x)$ 其中 $\{h_1(x),r_1(x)\}\subset K[x]$ 且 $\deg(r_1(x))<\deg(g(x))$

同理存在 $g(x)=h_2(x)r_1(x)+r_2(x)$ 且 $\deg(r_2(x))<\deg(r_1(x))$

故当 $\deg(r_{n-1}(x))>\deg(r_n(x))>0$ 时存在带余除法表达式 $r_{n-1}(x)=h_{n+1}(x)r_n(x)+r_{n+1}(x)$ 且 $\deg(r_{n+1}(x))<\deg(r_n(x))$

综上所述 $\deg(g(x))>\deg(r_i(x))\land \deg(r_i(x))>\deg(r_{i+1}(x))$

根据[[MK30][零次多项式]]可得当 $\deg(r_n(x))=0$ 时必满足 $r_n(x)\mid r_{n-1}(x)$

根据[[MK17][次数]]定义 $\deg(g(x))$ 为自然数，且有限。 $\deg(r_i(x))$ 定义域为 $N\cup-\infty$ 

由于每次带余除法余式的次数均下降，次数不为负，且当除式次数为零时余式为[[MK3][零元]]。

故必然在有限次后有 $r_s(x)$ 满足 $\deg(r_s(x))\geq0\land r_{s-1}(x)=h_s(x)r_s(x)+0(x)$

此时 $r_{s+1}(x)=0(x)$ 则根据[[MK21][性质1]]可得 $r_s(x),0(x)$ 最大公因式为 $r_s(x)$ 进一步根据[[MK29][引理]]中（2）可得 $r_s(x),r_{s-1}(x)$ 最大公因式为 $r_s(x)$

以此类推有限次可得 $f(x),g(x)$ 的最大公因式亦为 $r_s(x)$

***** 推论1

对于任意 $\{f(x),g(x)\}\subset K[x]$ 最大公因式一定存在

***** 推论2<<MK35>>

对于任意 $\{f(x),g(x)\}\subset K[x]$ 若 $c(x)$ 为其[[MK26][最大公因式]]，则必有 $c(x)=u(x)f(x)+v(x)g(x)$

****** 证明

定义辗转相除求得最大公因式 $r_s(x)$ 由于 $c(x)$ 亦为最大公因式，故有 $r_s(x)\mid c(x)\rightarrow c(x)=z(x)r_s(x)=z(x)r_s(x)+0(x)$

由于辗转，则对于任意 $3\leq i\leq s$ 均有 $r_{i-2}(x)=h_{i-1}(x)r_{i-1}(x)+r_i(x)\rightarrow r_i(x)=r_{i-2}(x)-h_{i-1}(x)r_{i-1}(x)$

且 $r_1(x)=f(x)-h_1(x)g(x),r_2(x)=g(x)-h_2(x)r_1(x)$ 进一步根据[[MK2][加法]]和[[MK6][乘法]]的性质可得

\begin{aligned}
&r_{i-1}(x)+h_i(x)r_i(x)\\
=&r_{i-1}(x)+h_i(x)\{r_{i-2}(x)-h_{i-1}(x)r_{i-1}(x)\}\\
=&h_i(x)r_{i-2}(x)+r_{i-1}(x)-h_i(x)h_{i-1}(x)r_{i-1}(x)\\
=&h_i(x)r_{i-2}(x)+\{1-h_i(x)h_{i-1}(x)\}r_{i-1}(x)\\
=&u_i(x)r_{i-2}(x)+v_i(x)r_{i-1}(x)
\end{aligned}

由于一元多项式 $K[x]$ [[MK15][是环]]，且根据[[MK10][定义]]加法，乘法封闭，故 $u_i(x)\in K[x]\land v_i(x)\in K[x]$

故经过有限次代换后 $c(x)$ 必可有表达式 $u(x)f(x)+v(x)g(x)$ 其中 $\{u(x),v(x)\}\in K[x]$

**** 最大公因式相伴<<MK32>>

若 $a(x),b(x)$ 均为 $X\subset K[x]$ 的最大公因式，则 $a(x),b(x)$ [[MK31][相伴]]，即 $a(x)=kb(x)$

***** 证明

根据[[MK26][定义]]可得 $a(x)\mid b(x)\land b(x)\mid a(x)$ 符合相伴定义

**** 首一最大公因式不随数域扩大改变<<MK37>>

若有[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][数域]] $E,K$ 满足 $K\subset E$ 有 $\{f(x),g(x)\}\subset K[x]$

则 $f(x),g(x)$ 在 $K[x]$ 上的首一最大公因式等于 $f(x),g(x)$ 在 $E[x]$ 上的[[MK38][首一最大公因式]] 

***** 证明

分别在 $K[x],E[x]$ 上运用[[MK33][辗转相除]]求最大公因式，根据带余除法表达式[[MK25][唯一性]]可得最终获得相同结果 $r_s(x)$

则根据[[MK32][最大公因式相伴]]可得 $K[x]$ 上任意最大公因式皆可表达为 $kr_s(x)$ ，同理 $E[x]$ 上任意最大公因式可表达为 $er_s(x)$

由于 $\{f(x),g(x)\}\subset K[x]$ 故 $r_s(x)\in K[x]$ 故最高次项系数 $a\in K$

根据数域定义 $\frac{1}{a}\in K\subset E$ 故首一最大公因式均为 $\frac{1}{a}r_s(x)$

**** 互素充要条件<<MK39>>

若 $\{f(x),g(x)\}\subset K[x]$ 且 $f(x),g(x)$ [[MK34][互素]]则其充要条件为存在 $\{u(x),v(x)\}\subset K[x]$

满足 $u(x)f(x)+v(x)g(x)=1$

***** 证明

****** 充分

由于互素，根据定义得首一最大公因式为 $1$ 

故根据[[MK35][推论2]]可得存在 $\{u(x),v(x)\}\subset K[x]$ 满足 $u(x)f(x)+v(x)g(x)=1$

****** 必要

若 $u(x)f(x)+v(x)g(x)=1$ 则定义 $c(x)$ 为 $f(x),g(x)$ 的最大公因式

根据[[MK28][整除性质]]可得 $c(x)\mid u(x)f(x)+v(x)g(x)\rightarrow c(x)\mid 1$

同理根据[[MK30][整除性质]]可得 $1\mid c(x)$ 故满足[[MK31][相伴]]，则根据[[MK36][定理]]有 $c(x)=k1=k$

故求首一最大公因式 $\frac{1}{k}c(x)=1$

**** 互素性不随数域扩大改变

若有[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][数域]] $E,K$ 满足 $K\subset E$ 有 $\{f(x),g(x)\}\subset K[x]$

若 $f(x),g(x)$ 在 $K[x]$ 中互素，则其在 $E[x]$ 中也互素

***** 证明

若 $f(x),g(x)$ 在 $K[x]$ 上[[MK34][互素]]，则其在 $K[x]$ 上[[MK38][首一最大公因式]]为 $1$

根据[[MK37][性质]]可得其在 $E[x]$ 上的首一最大公因式亦为 $1$

则根据定义 $f(x),g(x)$ 在 $E[x]$ 上[[MK34][互素]]

**** 互素性质1<<MK43>>

若 $\{f(x),g(x),h(x)\}\subset K[x]$ 满足 $f(x)\mid g(x)h(x)$ 且 $(f(x),g(x))=1$ 则有 $f(x)\mid h(x)$

***** 证明

根据[[mk39][互素充要条件]]可得存在 $\{u(x),v(x)\}\subset K[x]$ 满足 $u(x)f(x)+v(x)g(x)=1$

则两边同乘 $h(x)$ 得 $u(x)f(x)h(x)+v(x)g(x)h(x)=h(x)$

根据[[MK8][乘法交换律]]可得 $u(x)h(x)f(x)+v(x)g(x)h(x)=h(x)$

由于 $f(x)\mid g(x)h(x)\land f(x)\mid f(x)$ 则根据[[MK28][被试和]]可得 $f(x)\mid u(x)h(x)f(x)+v(x)g(x)h(x)\rightarrow f(x)\mid h(x)$

**** 互素性质2<<MK76>>

若 $\{f(x),g(x),h(x)\}\subset K[x]$ 满足 $f(x)\mid h(x)\land g(x)\mid h(x)$ 且 $f(x),g(x)$ [[MK34][互素]]，则 $f(x)g(x)\mid h(x)$

***** 证明

由于[[mk19][整除]]可得 $h(x)=a(x)f(x)\land h(x)=b(x)g(x)$

根据[[mk39][互素充要条件]]可得 $u(x)f(x)+v(x)g(x)=1$

故有：

\begin{aligned}
u(x)f(x)+v(x)g(x)&=1\\
u(x)f(x)h(x)+v(x)g(x)h(x)&=h(x)\\
u(x)b(x)f(x)g(x)+v(x)a(x)f(x)g(x)&=h(x)
\end{aligned}

可见 $f(x)g(x)\mid u(x)b(x)f(x)g(x)\land f(x)g(x)\mid v(x)a(x)f(x)g(x)$

故有 $f(x)g(x)\mid u(x)b(x)f(x)g(x)+v(x)a(x)f(x)g(x)\rightarrow f(x)g(x)\mid h(x)$

**** 互素性质3

若 $\{f(x),g(x),h(x)\}\subset K[x]$ 满足 $f(x),h(x)$ [[MK34][互素]] 且 $g(x),h(x)$ [[MK34][互素]]，则有 $f(x)g(x),h(x)$ [[MK34][互素]]

***** 证明

根据[[mk39][互素充要条件]]可得

（1） $u(x)f(x)+v(x)h(x)=1$

（2） $u'(x)g(x)+v'(x)h(x)=1$

则两式左右两边相乘

\begin{aligned}
1&=\{u(x)f(x)+v(x)h(x)\}\{u'(x)g(x)+v'(x)h(x)\}\\
1&=u(x)u'(x)f(x)g(x)+u'(x)g(x)v(x)h(x)+u(x)f(x)v'(x)h(x)+v(x)h(x)v'(x)h(x)\\
1&=\{u(x)u'(x)f(x)\}f(x)g(x)+\{u'(x)g(x)v(x)+u(x)f(x)v'(x)+v(x)h(x)v'(x)\}h(x)
\end{aligned}

故存在 $a(x)=u(x)u'(x)f(x),b(x)=u'(x)g(x)v(x)+u(x)f(x)v'(x)+v(x)h(x)v'(x)$

满足 $a(x)g(x)f(x)+b(x)h(x)=1$ 故根据[[mk39][互素充要条件]]可得 $f(x)g(x),h(x)$ [[MK34][互素]]

***** 推论

若 $f_i(x)\in K[x]\ i=1,2,...,n$ 与 $h(x)\in K[x]$ [[MK34][互素]]，则有 $\prod_{i=1}^nf_i(x),h(x)$ [[MK34][互素]]

** 可约

*** 不可约元素<<MK41>>

若 $f(x)\in K[x]$ 且 $f(x)$ 的[[MK40][因式]]仅有零[[mk17][次]]多项式和他本身的[[MK31][相伴]]元素，则称 $f(x)$ 为不可约元素

反之则为可约元素

**** 推论

$0(x)$ 可约

***** 证明

对于任意 $f(x)\in K[x]$ 可得 $f(x)\mid 0(x)$ 故不满足不可约定律，则可约

*** 定理<<MK45>>

对于 $p(x)\in K[x]\land p(x)>0$ 以下命题等价

（1） $p(x)$ [[MK41][不可约]]

（2） 对于任意 $f(x)\in K[x]$ 其与 $p(x)$ 的[[MK42][公因式]]只能为零[[MK17][次]]多项式，或 $p(x)$ 的[[MK31][相伴]]元素

（3） 对于任意 $\{f(x),g(x)\}\in K[x]$ 若 $p(x)\mid f(x)g(x)$ 则 $p(x)\mid f(x)\lor p(x)\mid g(x)$

（4） 不存在 $\{f(x),g(x)\}\in K[x]$ 满足 $p(x)=f(x)g(x)\land \deg(f(x))<\deg(p(x))\land\deg(g(x))<\deg(p(x))$

**** 证明 

***** （1）到（2）

若存在 $f(x)\in K[x]$ 其与 $p(x)$ 存在一个公因式 $c(x)$ 次数不为零且不为相伴元素

则有 $c(x)\mid p(x)$ 故 $c(x)$ 为 $p(x)$ 的[[MK40][因式]]，根据[[MK41][定义]]不可约，故与条件冲突。

***** （2）到（3）

若 $p(x)\mid f(x)$ 则满足条件

若 $p(x)\nmid f(x)$ 根据（1）有 $f(x),g(x)$ 公因式为零次多项式，即 $(f(x),g(x))=1$ [[MK34][互素]]

则根据[[MK43][互素性质]]可得 $p(x)\mid g(x)$

***** （3）到（4）

由于 $p(x)=f(x)g(x)$ 则有 $p(x)\mid f(x)g(x)$

根据[[MK18][定理]]可得 $\deg(p(x))=\deg(f(x)g(x))=\deg(f(x))+\deg(g(x))$

根据（3）可得必有一个可以被 $p(x)$ 整除，设为 $f(x)$

则有 $p(x)\mid f(x)$ 根据[[MK22][整除性质]]可得 $\deg(p(x))\leq\deg(f(x))$

此时当 $g(x)=0(x)$ 时 $p(x)=f(x)0(x)=0(x)$ 则 $\deg(p(x))=\deg(g(x))=-\infty$ 不满足要求

当 $g(x)\ne0(x)$ 则仅有当 $\deg(g(x))=0$ 时满足 $\deg(p(x))=\deg(f(x))+\deg(g(x))\land\deg(p(x))\leq\deg(f(x))$

则有 $\deg(p(x))=\deg(f(x))$ 同样不满足条件

***** （4）到（1）

对于任意 $c(x)\in K[x]$ 且是 $p(x)$ 的[[MK40][因式]]，则有 $c(x)\mid f(x)$ 根据[[MK19][定义]]可得存在 $f(x)\in K[x]$ 满足 $p(x)=f(x)c(x)$

若 $c(x)=0(x)\lor f(x)=0(x)$ 则有 $p(x)=0(x)$ 则 $\deg(p(x))=-\infty<0$ 与其定义不符

故 $c(x)\ne0(x)\land f(x)\ne0(x)$ 即 $\deg(c(x))\geq0\land\deg(f(x))\geq0$

根据[[MK18][定理]]可得 $\deg(p(x))=\deg(f(x))+\deg(c(x))$ 

且根据（4）不会有 $\deg(f(x))<\deg(p(x))\land\deg(c(x))<\deg(p(x))$

故必有 $\deg(f(x))=\deg(p(x))\lor\deg(c(x))=\deg(p(x))$

若 $\deg(f(x))=\deg(p(x))$ 则 $\deg(c(x))=0$ 即 $c(x)$ 为零次多项式

若 $\deg(c(x))=\deg(p(x))$ 则 $f(x)$ 为零次多项式，即 $f(x)=k,k\in K$

又根据 $p(x)=f(x)c(x)=kc(x)$ 可得 $c(x)$ 为 $p(x)$ 的相伴元素

故根据定义 $p(x)$ 不可约

**** 推论1<<MK46>>

设 $p(x)\in K[x]$ 且[[MK41][不可约]]，若 $p(x)\mid \prod_{i=1}^n f_i(x),f_i(x)\in K[x]\land n<\infty$ 即[[mk19][整除]] $n$ 个多项式乘积

则存在 $1\leq s\leq n\rightarrow p(x)\mid f_s(x)$

***** 证明

由于一元多项式是[[MK15][环]]，根据[[MK10][环定义]]（7）可得乘法封闭，故有 $\prod_{i=1}^n f_i(x)=f_1(x)\prod_{i=2}^n f_i(x)$

且 $\prod_{i=2}^n f_i(x)\in K[x]$ 故根据定理中（3）可得 $p(x)\mid f_1(x)\lor p(x)\mid \prod_{i=2}^n f_i(x)$

若前者，则 $s=1$ 若后者，则继续拆分，最终找到 $s$

**** 推论2<<MK51>>

在 $K[x]$ 中一[[MK17][次]]多项式[[MK41][不可约]]

**** 推论3<<MK47>>

设 $p(x)\in K[x]$ 且[[MK41][不可约]]，若 $p(x)=\prod_{i=1}^n f_i(x),f_i(x)\in K[x]\land n<\infty$

则存在 $1\leq s\leq n\rightarrow p(x)\sim f_s(x)\land \deg\left(\prod_{1\leq i\leq n\land i\ne s}f_i(x)\right)=c$ 其中 $c\in K$ 

***** 证明

由于一元多项式是[[MK15][环]]，根据[[MK10][环定义]]（7）可得乘法封闭，故有 $\prod_{i=1}^n f_i(x)=f_1(x)\prod_{i=2}^n f_i(x)$

且 $\prod_{i=2}^n f_i(x)\in K[x]$ 故有 $p(x)=f_1(x)\left\{\prod_{i=2}^n f_i(x)\right\}$ 由于不可约，故 $p(x)\ne0(x)$

根据定理中（4）及[[MK18][定理]]可得必有 $\deg(p(x))=\deg(f_1(x))\lor \deg(p(x))=\deg\left(\prod_{i=2}^n f_i(x)\right)$

若为前者，则根据 $\deg(p(x))=\deg(f_1(x))+\deg\left(\prod_{i=2}^n f_i(x)\right)$ 可得 $\deg\left(\prod_{i=2}^n f_i(x)\right)=0$

故根据[[MK17][次数]]定义有 $\prod_{i=2}^n f_i(x)=d\land d\in K$ 则有 $p(x)=df_1(x)$ 

若为后者，则根据 $\deg(p(x))=\deg(f_1(x))+\deg\left(\prod_{i=2}^n f_i(x)\right)$ 可得 $\deg(f_1(x))=0$

故根据[[MK17][次数]]定义有 $f_1(x)=c_1\land c_1\in K$ 则有 $p(x)=c_1\prod_{i=2}^nf_i(x)=c_1f_2(x)\prod_{i=3}^nf_i(x)$

继续以此类推。

由于 $n$ 有限，故得必将在有限次达到 $p(x)=d\left(\prod_{i=1}^s c_i\right) f_s(x)=kf_s(x)$ 即结论

*** 唯一因式分解定理<<MK50>>

定义 $f(x)\in K[x]\land\deg(f(x))\geq 0$ 为有限[[MK17][次]]多项式，则：

（1） 存在有限个[[MK41][不可约]]多项式 $p_1(x),...,p_n(x)\ \ n<\infty$ 满足 $f(x)=\prod_{i=1}^n p_i(x)$

上述定义为一元多项式因式分解的存在性

且若存在另一组不可约多项式 $f(x)=\prod_{i=1}^m q_i(x)$ 其中 $q_i(x)\in K[x]$ 且不可约，则有：

（1） $m=n$

（2） $\forall i(1\leq i\leq m\rightarrow \exists j(1\leq j\leq n\land q_i(x)\sim p_j(x)))$ 其中 $\sim$ 为[[mk31][相伴]]符号

上述定义为一元多项式因式分解的唯一性

**** 证明

***** 证明存在性<<MK48>>

根据[[MK41][定义]]可得若 $f(x)\in K[x]$ 不可约，则 $f(x)=f(x)$ 满足条件

若 $f(x)$ 可约，由于 $\deg(f(x))\geq 0$ 及 $f(x)$ 不是不可约，根据[[MK45][定理]]不满足（4）

则有分解 $f(x)=p_1(x)p_2(x)$ 且满足 $\deg(p_1(x))<\deg(f(x))\land\deg(p_2(x))<\deg(f(x))$

依次对所有可约元素分解。由于 $f(x)$ 有限次，故 $\deg(f(x))\ne\pm\infty$ 根据次数定义域 $f(x)$ 的次数必为正整数

并且每次分解次数严格下降一个正整数，故分解只能进行有限次。根据[[MK45][定理]]中（4）可得所有可约元素均可分解。

故存在有限个[[MK41][不可约]]多项式 $p_1(x),...,p_n(x)\ \ n<\infty$ 满足 $f(x)=\prod_{i=1}^n p_i(x)$

***** 证明唯一性

****** 当 $n=1$ 时成立

此时 $f(x)=p_1(x)=\prod_{i=1}^m q_i(x)$ 根据条件 $p_1(x)$ 不可约

则根据[[MK47][推论3]]可得必存在一个 $q_s(x)$ 满足 $p_i(x)=cq_s(x)$

故有 $p_1(x)\sim q_s(x)$

****** 当 $n-1$ 成立时 $n$ 成立

由于一元多项式是[[MK15][环]]，根据[[MK10][环定义]]（7）可得加乘法封闭

由于 $\deg(f(x))\geq0\rightarrow f(x)\ne0(x)$ 则 $p_i(x)\ne0(x)\land q_i(x)\ne0(x)$

此时 $f(x)=\prod_{i=1}^n p_i(x)=\prod_{i=1}^m q_i(x)=p_1(x)\prod_{i=2}^n p_i(x)=\prod_{i=1}^m q_i(x)$

由于 $p_1(x)$ 不可约，根据[[MK46][推论1]]可得存在 $1\leq s\leq m\rightarrow p_1(x)\mid q_s(x)$

此时，不妨设 $s=1$ 则有 $p_1(x)\mid q_1(x)$ 又根据 $q_1(x)$ [[MK41][不可约]]则有 $\deg(p_1(x))=0\lor p_1(x)\sim q_1(x)$

又由于 $p_1(x)$ 不可约，则必有 $p_1(x)\sim q_1(x)$ 故 $p_1(x)=cq_1(x)$

则根据 $cq_1(x)\prod_{i=2}^n p_i(x)=q_1(x)\prod_{i=2}^m q_i(x)$ 以及[[MK8][乘法]]交换，结合，消去率有 $c\prod_{i=2}^n p_i(x)=\prod_{i=2}^m q_i(x)$

定义 $g(x)=(cp_2(x))\prod_{i=3}^n p_i(x)=\prod_{i=2}^m q_i(x)$ 由 $p_i(x),q_i(x)$ 不可约则：

（1） $p_i(x)\ne0(x)$ 故 $g(x)\ne0(x)$

（2） $g(x)\in K[x]$ 且满足 $n-1$ 的情况

故有 $n-1=m-1$ 且 $\forall i(2\leq i\leq m\rightarrow \exists j(2\leq j\leq n\land q_i(x)\sim p_j(x)))$

又由于 $p_1(x)\sim q_1(x)$ 故当 $n-1$ 满足时 $n$ 亦满足

****** 结论

根据[[MK48][上一步证明]]可知对于任意 $f(x)\in K[x]$ 均存在 $f(x)=\prod_{i=1}^n p_i(x)$ 且 $n<\infty$ 有限

则根据数学归纳法 $f(x)=\prod_{i=1}^n p_i(x)=\prod_{i=1}^m q_i(x)$ 必满足唯一性

*** 标准分解式

若 $f(x)\in K[x]$ 若因式分解 $f(x)=c\prod_{i=1}^n p_i^{l_i}(x)$ 满足 $p_i(x)$ 为最高[[MK17][次]]项系数为 $1$ 的[[MK41][不可约]]多项式，且 $l_i>0$

则称该式为 $f(x)$ 的标准分解式

** 根

*** 定义<<MK52>>

若 $f(x)\in K[x]$ 存在 $c\in K$ 满足 $(x-c)\mid f(x)$ 即[[MK19][整除]]，则称 $c$ 是 $f(x)$ 的一个跟

**** 推论<<MK71>>

若 $c$ 是 $f(x)\in K[x]$ 的跟的充要条件是 $f(c)=0(x)$ 即：

（1） 将 $x$ 用 $c$ 代替

（2） 引入定义在数域 $K$ 上封闭的加乘法

（3） 经过运算后得结果为[[MK3][零元]]

***** 证明

根据定义存在 $h(x)\in K[x]$ 满足 $f(x)=(x-c)h(x)$ 

则当 $x=c$ 时有 $f(c)=(c-c)h(c)$ 根据[[MK53][减法]]可得 $c-c=0[x]$ 即零多项式

根据[[MK3][零元]]可得 $0(x)h(c)=0(x)$ 则有 $f(c)=0(x)$

*** Bezout定理<<MK73>>

对于 $f(x)\in K[x]\land\infty\geq\deg(f(x))\geq0$ 中 $(x-c)\mid f(x)$ 的充要条件是 $c$ 是 $f(x)$ 的根

**** 证明 

***** 充分

若 $(x-c)\mid f(x)$ 则 $f(x)=g(x)(x-c)$

根据数域减法 $c-c=0$ 根据数域乘法 $0$ 乘任意数均为 $0$

故有 $f(c)=g(c)0=0$ 即 $c$ 是 $f(x)$ 的根

***** 必要

根据[[MK1][定义]]可得 $x-c=x+(-1)c\in K[x]$

根据带余除法[[MK24][存在性]]必有 $f(x)=g_1(x)(x-c)+r_1(x)$ 其中 $\deg(r_1(x))<\deg(f(x))$ 

根据数域减法 $c-c=0$ 根据数域乘法 $0$ 乘任意数均为 $0$

则有 $f(c)=g_1(c)0+r_1(c)=r_1(c)=0$ 故 $r_1(c)=0$ 即 $c$ 是 $r_1(x)$ 的根 

依次类推，由于 $\deg(f(x))<\infty$ 且每次余式的次数均严格下降。

故必将在有限次得到 $\deg(r_s(x))=0$ 即 $r_s(x)=k\in K$

依次带入得 $f(x)=\sum_{i=1}^{s-1}g_i(x)(x-c)+k$ 此时带入 $f(c)=k=0$ 

故有 $f(x)=\sum_{i=1}^{s-1}g_i(x)(x-c)$ 根据[[MK8][乘法]]分配率可得 $f(x)=(x-c)\left(\sum_{i=1}^{s-1}g_i(x)\right)$

由于一元多项式是[[MK15][环]]，根据[[MK10][环定义]]（7）可得加乘法封闭

故有 $x-c\in K[x]\land \sum_{i=1}^{s-1}g_i(x)\in K[x]$ 则根据[[MK19][定义]]可得 $x-c\mid f(x)$

*** 根的个数

对于 $f(x)\in K[x]\land \deg(f(x))\geq 0$ 而言，其跟的个数 $n$ 一定满足 $n\leq\deg(f(x))$

**** 证明

根据[[MK50][唯一因式分解]]可得必有 $f(x)=\prod_{i=1}^mp_i(x)$ 其中 $p_i(x)$ [[MK41][不可约]]

根据[[MK51][推论2]]可得一次多项式 $x+b$ 不可约，固若 $(x+b)\mid f(x)\rightarrow (x+b)\mid \prod_{i=1}^mp_i(x)$

则根据因式分解唯一性必有 $p_s(x)\sim (x+b)$ 即根据[[mk31][相伴]] $p_s=c(x+b)$

由于若相伴定义故当 $x=-b$ 时 $p_s(x)=c0=0$

故若存在 $b$ 为 $f(x)$ 的根，则必存在 $p_s(x)=c_s(x-b)$

假设 $f(x)$ 根为 $b_1,...,b_n$ 则必有 $f(x)=\prod_{i=1}^nc_i(x-b_i)\prod_{i=n+1}^mp_i(x)$

由于 $p_i(x)$ 不可约，故 $p_i(x)\ne0(x)\rightarrow\deg(p_i(x))>\infty$ 且 $\deg(f(x))\geq 0$ 

则根据[[MK18][次数定理]]可得 $\deg(f(x))=n+\sum_{i=n+1}^m\deg(p_i(x))$

由于次数均大于等于零，故得 $\max(n)=\deg(f(x))$ 证毕

**** 推论1

若 $f(x)\in K[x]$ 且 $\deg(f(x))\leq n$ 却有 $n+1$ 个[[MK52][根]]，则 $f(x)=0(x)$

**** 推论2<<MK66>>

假设 $\{f(x),g(x)\}\subset K[x]$ 且 $\deg(f(x))\leq n\land\deg(g(x))\leq n$

若存在 $\{c_1,...,c_{n+1}\}\subset K$ 使得 $f(c_i)=g(c_i)$ 则 $f(x)=g(x)$

注：此处 $f(c)$ 为带入 $c$ 的表达式，即 $1$ 次多项式或 $0$ 次多项式

***** 证明

定义 $h(x)=f(x)-g(x)$ 根据[[MK53][减法]]定义 $h(x)=f(x)+(-1)g(x)$

则根据[[MK18][次数定理]]可得 $\deg(h(x))\leq\max(\deg(f(x)),\deg(g(x))\leq n$

又根据条件得 $h(c_i)=g(c_i)-f(c_i)=0(x)$ 则 $c_i$ 为 $h(x)$ 的根

由于有 $n+1$ 个根且 $\deg(h(x))\leq n$ 则 $h(x)=0(x)$

根据[[MK54][减法性质]]可得 $f(x)=g(x)$

** 复数域上[[MK41][不可约]]多项式

*** 代数基本定理<<MK74>>

任何[[MK17][次数]]大于 $0$ 的[[MK1][一元多项式]] $f(x)$ 在复数域上有[[MK52][根]]

**** 证明

***** 构建函数环

****** 定义运算集合<<MK68>>

假设 $f(x)=\sum_{i=0}^da_ix^i\in K[x]$ 为[[MK1][多项式表达式]]，若定义 $\tau\in K$ 是定义域为数域 $K$ 的自变量

将 $\tau$ 替换 $x$ 引入数域 $K$ 上的乘法，则显然根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-相关定义-函数定义]] $f(\tau)=\sum_{i=0}^da_i\tau^i$ 为函数

此时称 $f(\tau)$ 为 $f(x)$ 诱导的函数。定义集合 $K_{pol}$ 为所有 $f(x)\in K[x]$ 诱导的函数的集合

****** 定义加法乘法<<MK67>>

在 $K_{pol}$ 上定义加法、乘法为函数式的加乘

则有 $f(\tau)+g(\tau)=h(\tau)=\sum_{i=0}^\infty(a_i+b_i)\tau$ 显然 $h(\tau)$ 是 $h(x)$ 诱导的函数且 $h(x)\in K[x]$

由于 $K_{pol}$ 是所有属于内表达式诱导的函数集合，故有 $h(\tau)\in K_{pol}$ 。同理可证 $f(\tau)g(\tau)\in K_{pol}$

****** 定义函数相等<<MK65>>

若 $f(\tau)$ 与 $g(\tau)$ 相等，则 $\forall\tau\in K(f(\tau)=g(\tau))$ 即对于任意数域内的自变量，函数的值相等 

****** 定义环

根据[[MK10][环]]的定义可证明 $<K_{pol},+,*>$ 组成环，其中零元为 $f(\tau)=0$

***** 同构映射

****** 定义映射函数

定义对应关系 $\sigma:f(x)\to f(\tau),f(x)\in K[x]\land f(\tau)\in K_{pol}$

其中函数 $f(\tau)$ 为表达式 $f(x)$ 诱导的函数

若有 $\sigma(f(x))=f(\tau)\land\sigma(g(x))=g(x)\land f(\tau)=g(x)$

显然根据[[MK68][定义]] $g(x),f(x)$ 均诱导出次数与系数相同的多项式函数 $f(\tau),g(\tau)$

则有 $f(\tau)-g(\tau)=0$ 故对于任意 $\tau\in K$ 均有 $f(\tau)=g(\tau)$

即根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数]]可得 $\sigma:f(x)\to f(\tau)$ 是函数映射

****** 证明是同构映射

******* 证明是双射

根据 $K_{pol}$ 的[[MK68][定义]]可得对于任意 $f(\tau)\in K_{pol}$ 均由 $f(x)\in K$ 诱导，即满足 $\sigma(f(x))=f(\tau)$ 

则根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-特殊的函数类型-满射]]可得 $\sigma$ 为满射

若 $f(x)\ne g(x)$ 则定义 $f(x)=\sum_{i=0}^{d_1}a_ix^i,g(x)=\sum_{i=0}^{d_2}b_ix^i$

则其诱导的函数分别为 $f(\tau)=\sum_{i=0}^{d_1}a_i\tau^i,g(\tau)=\sum_{i=0}^{d_2}b_i\tau^i$

由于不[[MK5][相等]]，故不满足 $d_1=d_2\land a_i=b_i$

根据 $K_{pol}$ 的[[MK67][加法乘法]]可得 $f(\tau)-g(\tau)=\sum_{i=0}^{\max(d_1,d_2)}(a_i-b_i)\tau^i$ 故 $f(\tau)-g(\tau)\ne0$

则不满足 $\forall\tau\rightarrow f(\tau)-g(\tau)=0$ 根据[[MK65][相等定义]]可得 $f(\tau)\ne g(\tau)$ 

则根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-特殊的函数类型-单射]]可得 $\sigma$ 为单射

故 $\sigma$ 是双摄函数

******* 证明保持加乘法

定义 $f(x)=\sum_{i=0}^{d_1}a_ix,g(x)=\sum_{i=0}^{d_2}b_ix$ 则其诱导的函数分别为 $f(\tau)=\sum_{i=0}^{d_1}a_i\tau,g(\tau)=\sum_{i=0}^{d_2}b_i\tau$

根据多项式[[MK2][加法]]可得 $f(x)+g(x)=\sum_{i=0}^{\max(d_1,d_2)}(a_i+b_i)x^i=h(x)$

根据 $K_{pol}$ [[MK67][加法]]可得 $f(\tau)+g(\tau)=\sum_{i=0}^{\max(d_1,d_2)}(a_i+b_i)\tau^i=h(\tau)$

根据[[MK68][定义]]可得 $h(\tau)$ 为 $h(x)$ 诱导的函数，则有 $\sigma(f(x)+g(x))=\sigma(h(x))=h(\tau)=f(\tau)+g(\tau)$

即保持加法。同理可证保持乘法

******* 结论<<MK72>>

即 $\sigma$ 是[[MK13][同构映射]]，则根据[[MK71][推论]]若 $c$ 是 $f(x)$ 的根，则有 $f(x)=(x-c)h(x)$

根据[[MK70][同构性质]]有 $\sigma(f(x))=\sigma(x-c)\sigma(h(x))\Rightarrow f(\tau)=(x-c)h(\tau)=0$

即数域 $K$ 上的多项式 $f(x)$ 有根 $c$ 等价于系数 $a_i\in K$ 的多项式函数 $f(\tau)$ 当 $\tau=c$ 时函数值为零

***** 证明定理

若 $K=\mathbb{C}$ 是复数域，若 $f(x)$ 无根，则根据[[MK72][结论]] $f(\tau)$ 在 $\tau\in\mathbb{C}$ 上恒不等于零

则定义函数 $\Phi(\tau)=\frac{1}{f(\tau)}$ 则根据[[~/OneDrive/复变函数/Cplx_fc.org][导数、微分与解析-导数-基本公式]]可得 $$\Phi'(\tau)=-\frac{f'(\tau)}{(f(\tau))^2}$$

且根据导数公式在复数域上多项式函数 $f'(\tau)$ 导数存，结合 $f(\tau)\ne0$ 可得在复数域上 $\Phi'(\tau)$ 存在

则根据[[~/OneDrive/复变函数/Cplx_fc.org][导数、微分与解析-解析]]可得函数 $\Phi(\tau)$ 解析。

根据[[~/OneDrive/复变函数/Cplx_fc.org][构建复数-模-性质]]以及[[~/OneDrive/复变函数/Cplx_fc.org::MK57][函数极限]]可得 $\lim_{|\tau|\to\infty}\frac{1}{\tau^i}=0,i\in\mathbb{N}$

则有 $$\lim_{|\tau|\to\infty}\Phi(\tau)=\lim_{|\tau|\to\infty}\frac{\frac{1}{\tau^n}}{a_n+\sum_{i=0}^{n-1}a_i\frac{1}{\tau^{n-i}}}=0$$ 则根据定义，存在 $M$ 对于任意 $|\tau|>M$ 均有 $\left|\Phi(\tau)\right|<1$

当 $|\tau|\leq M$ 时，根据[[~/OneDrive/复变函数/Cplx_fc.org][导数、微分与解析-导数-可导必连续]]定义可得多项式函数连续

又由于 $|\tau|\leq M$ 有界闭区间，故根据[[~/OneDrive/数学分析/Chap11Note.org][连续函数性质-有界性定理]]可得有界，最终得 $\Phi(\tau)$ 有界且解析。

故根据[[~/OneDrive/复变函数/Cplx_fc.org][积分-定理-刘维尔定理]]可得 $\Phi(\tau)$ 必为常值函数。即 $\Phi(\tau)=A$

则有 $f(\tau)=\frac{1}{A}$ 为零[[MK17][次]]多项式函数。根据[[MK68][定义]]为零次多项式诱导的函数。

即当且仅当 $f(x)=a_0\ne0$ 为零次多项式时，多项式无[[MK52][根]]

**** 推论1

对于任意 $f(x)\in\mathbb{C}[x]$ 若 $\deg(f(x))>1$ 则可约

***** 证明

根据代数基本定理 $f(x)$ 有根，则根据[[MK73][Bezout定理]] $f(x)$ 有一次因式，则根据[[MK41][可约]]

**** 推论2

根据推论1对于任意 $f(x)\in\mathbb{C}[x]$ 只有一次多项式不可约

**** 推论3

对于任意 $f(x)\in\mathbb{C}[x]\land\deg(f(x))>1$ 其可写成 $f(x)=a\prod_{i=1}^n(x-c_i)^{j_i}$ 

且有 $\sum_{i=1}^nj_i=\deg(f(x))$

** 实数域上[[MK41][不可约]]多项式

*** 命题<<MK75>>

若 $f(x)=\sum_{i=0}^na_ix^i\in\mathbb{R}[x]$ 此时根据[[MK72][多项式函数同构]]可得若 $c$ 是 $f(x)$ 的根，则 $f(c)=0$

根据[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][数域-推论2]]可得最大数域为 $\mathbb{C}$ 则 $c\in\mathbb{C}$ ，故 $c$ 存在[[~/OneDrive/复变函数/Cplx_fc.org][构建复数-共轭复数]]

取 $c$ 的共轭复数 $\overline{c}$ 带入亦有 $f(\overline{c})=0$ 即等价于 $\overline{c}$ 亦是多项式的根

**** 证明

对于函数 $\sum_{i=0}^na_ic^i=0$ 两边取共轭复数，则根据[[~/OneDrive/复变函数/Cplx_fc.org][构建复数-共轭复数-性质]]中加法乘法保持可得

\begin{aligned}
\overline{\sum_{i=0}^na_ic^i}&=\sum_{i=1}^n\overline{a_ic^i}\\
&=\sum_{i=1}^n\overline{a_i}\overline{c^i}\\
&=\sum_{i=1}^na_i\overline{c}^i\\
\end{aligned}

由于 $0$ 的共轭复数为本身，故有 $\sum_{i=0}^na_i\overline{c}^i=0$ 即 $f(\overline{c})=0$ 则根据[[MK72][多项式函数同构]]可得 $\overline{c}$ 亦为根。

*** 定理

实数域上的不可约多项式，仅有一次多项式和判别式小于零的二次多项式

**** 证明

定义 $p(x)\in\mathbb{R}[x]$ 为 $\deg(p(x))\geq1$ 的[[MK41][不可约]]多项式，则根据[[MK74][代数基本定理]]当 $x\in\mathbb{C}$ 时 $p(x)$ 存在根

定义为 $c$ ，若 $c$ 为实数，则根据[[MK52][定义]]可得 $p(x)=(x-c)h(x)$ 则根据[[MK41][不可约]]得 $p(x)\sim(x-c)$

即 $p(x)=a(x-c)$ 为一次多项式

若 $c$ 虚部不为零，则根据[[MK75][命题]]可得 $\overline{c}$ 亦为根，固有 $(x-c)\mid p(x)\land (x-\overline{c})\mid p(x)$

由于 $x-c,x-\overline{c}$ 满足[[MK34][互素]]，故根据[[MK76][互素性质2]]可得 $(x-c)(x-\overline{c})\mid p(x)$

则根据[[MK19][整除定义]]可得 $p(x)=(x-c)(x-\overline{c})\prod_{i=1}^nf_i(x)=(x-c)(x-\overline{c})h'(x)$ 

则有 $(x-c)(x-\overline{c})=x^2-(c+\overline{c})x+c\overline{c}$ 根据[[~/OneDrive/复变函数/Cplx_fc.org][构建复数-共轭复数]]定义，若 $c=a+ib$ 则有 $\overline{c}=c-ib$

则 $c+\overline{c}=2a\in\mathbb{R}$ 及 $c\overline{c}=a^2-b^2\in\mathbb{R}$ 故 $x^2-(c+\overline{c})x+c\overline{c}\in\mathbb{R}[x]$

则有 $\mathbb{C}$ 上有 $p(x)=(x-c)(x-\overline{c})h(x)=(x^2-(c+\overline{c})x+c\overline{c})h(x)$ 

根据[[MK77][整除与数域无关]]可得在数域 $\mathbb{R}$ 上有 $p(x)=(x^2-(c+\overline{c})x+c\overline{c})h'(x)$ 

由于 $p(x)$ 与 $\mathbb{R}$ 上[[MK41][不可约]]，则 $p(x)\sim x^2-(c+\overline{c})x+c\overline{c}$ 即 $p(x)=a(x^2-(c+\overline{c})x+c\overline{c})$ 

且由于虚部不为零，可得 $x^2-(c+\overline{c})x+c\overline{c}$ 判别式小于零

证毕。

** 有理数域上[[MK41][不可约]]多项式

*** 本源多项式<<MK79>>

若 $f(x)\in K[x]$ 定义为 $f(x)=\sum_{i=0}^n a_ix^i$ 。若满足：

（1） $\forall i(0\leq i\leq n\land i\in\mathbb{N}\rightarrow a_i\in\mathbb{N})$

（2） $\left\{a_i\big|0\leq i\leq n\land i\in\mathbb{N}\right\}$ 的最大公因式为 $\pm 1$

则称为本源多项式

**** 推论1<<MK80>>

若 $f(x)\in\mathbb{Q}$ 即有理数义[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][数域]]多项式，则必有本源多项式与之相伴。

***** 证明

由于 $a_i\in\mathbb{Q}$ 故有 $a_i=\frac{q_i}{p_i}$ 取 $\{p_i,...,p_n\}$ 的最小公倍数 $P$

则 $a_i=\frac{1}{P}\frac{Pq_i}{p_i}$ 故根据[[MK4][数乘]]可得 $f(x)=\frac{1}{P}\sum_{i=0}^n\frac{Pq_i}{p_i}x^i$

由于 $P$ 是最小公倍数，故 $\frac{P}{p_i}$ 为整除，故进一步取 $\left\{\frac{Pq_i}{p_i}\big|0\leq i\leq n\land i\in\mathbb{N}\right\}$ 的最大公因数 $Q$

同理根据多项式乘法可得 $f(x)=\frac{Q}{P}\sum_{i=0}^n\frac{Pq_i}{Qp_i}x^i$ 其中 $\frac{Pq_i}{Qp_i}x^i$ 均为整数，且最大公因数为 $\pm1$ 

故根据[[MK31][相伴]]定义证得。

**** 推论2<<MK82>>

若两个本源多项式 $\{f(x),g(x)\}\subset\mathbb{Q}[x]$ [[MK31][相伴]]，则其充要条件为 $f(x)=\pm g(x)$

***** 证明

****** 充分

定义 $f(x)=\sum_{i=1}^na_ix^i$ 由于相伴，故必有 $g(x)=\sum_{i=1}^n b_ix^i$

由于有理数域上相伴，固有 $f(x)=\frac{q}{p}g(x)$ 此处 $p,q$ 互素

根据[[MK4][数乘]]可得 $pf(x)=qg(x)$ 根据[[MK5][相等]]可得 $pa_i=qb_i$ 由于本源多项式，故 $p,q,a_i,b_i$ 均为整数

故有 $\frac{qb_i}{p}=a_i$ 由于 $q,p$ 互素，故若 $\frac{b_i}{p}$ 不为整数，则 $q\frac{b_i}{p}$ 亦不为整数，与 $a_i$ 为整数矛盾

故必有对任意 $1\leq i\leq n\land i\in\mathbb{N}$ 均有 $\frac{b_i}{p}$ 为整数，即 $p$ 为 $\{b_0,...,b_n\}$ 的公约数。

根据本源定义 $\{b_0,...,b_n\}$ 仅有 $\pm1$ 故 $p=\pm1$ 同理可证 $q=\pm1$

故有 $f(x)=\pm g(x)$

****** 必要

根据[[MK31][相伴]]定义显然

**** 高斯引理（推论3）<<MK81>>

有理数域上，两个本源多项式的乘积仍为本源多项式

***** 证明

定义 $\{f(x),g(x)\}\subset\mathbb{Q}[x]$ 以及 $f(x)=\sum_{i=1}^na_ix^i,g(x)=\sum_{i=1}^mb_ix^i$

根据[[MK6][乘法]]有 $h(x)=f(x)g(x)=\sum_{s=0}^{m+n}\left(\sum_{i+j=s}a_ib_j\right)x^s=\sum_{s=0}^{m+n}c_sx^s$

假设 $h(x)$ 不是本源多项式，即有不为 $\pm1$ 的素公因数 $p$

由于 $f(x),g(x)$ 均为本源多项式，故公因数不存在 $p$

则必有 $a_k$ 满足 $\frac{a_k}{p}$ 不为整数， $b_j$ 满足 $\frac{b_j}{p}$ 不为整数，且 $k\leq n\land j\leq m$

故必有 $c_{k+j}=\sum_{i+j=k+j}a_ib_j$ 由于 $p$ 为 $c_{k+j}$ 的因数，故 $p$ 为 $a_kb_j$ 的因数

由于 $p\ne\pm1$ 且 $\frac{a_k}{p},\frac{b_j}{p}$ 均无法化为整数，且 $p$ 为素数

故有 $\frac{a_kb_j}{p}$ 不为整数，即 $p$ 不为 $a_kb_j$ 的因数，即矛盾。

故 $h(x)$ 是本源多项式

**** 定理1<<MK83>>

定义 $f(x)\in\mathbb{Q}[x]$ 为[[MK79][本源多项式]]且[[MK41][可约]]的充要条件是 $f(x)$ 可表示为两个次数比他低的本源多项式乘积

***** 证明

****** 充分

已知 $f(x)$ 可约，则必有 $f(x)=g(x)h(x)$ 根据[[MK80][推论1]]可得 $g(x)=Ag'(x),h(x)=Bh'(x)$

其中 $\{A,B\}\subset\mathbb{Q}$ 且 $g'(x),h'(x)$ 为本源多项式，则 $f(x)=ABg'(x)h'(x)$

根据[[MK81][高斯引理]]可得 $h'(x)g'(x)$ 亦为本源多项式，根据[[MK31][相伴定义]]可得 $f(x)\sim h'(x)g'(x)$

根据[[MK82][推论2]]有 $AB=\pm 1$ 显然 $-h'(x)$ 亦为本源多项式，故充分性证毕。

****** 必要

已知 $f(x)=h(x)g(x)$ 其中 $h(x),g(x)$ 为本源多项式，根据[[MK41][可约定义]]可约

**** 定理2<<MK84>>

定义 $f(x)\in\mathbb{Q}[x]$ 是整系数多项式，则[[MK41][可约]]的充要条件是可以分解成两个次数比他低的整系数多项式。

***** 证明

根据[[MK79][定义]]可得若 $f(x)$ 不为本源多项式，则存在整数 $r\in\mathbb{N}$ 使得 $f(x)=rh(x)$

其中 $h(x)$ 为本源多项式，则 $f(x)$ 可约等价于 $h(x)$ 可约。

根据[[MK83][定理1]]可得等价于 $h(x)=h_1(x)h_2(x)$ 两个本源多项式。

则有 $f(x)=rh_1(x)h_2(x)$ 故可分解为两个整系数多项式

*** Eisenstein判别法

定义 $f(x)=\sum_{i=0}^na_ix^i\in\mathbb{Q}[x]$ 是次数若存在一个素数 $p$ 满足：

（1） $\frac{a_n}{p}$ 不是整数

（2） $\frac{a_i}{p}$ 是整数 $i=0,1,...,n-1$

（3） $\frac{a_0}{p^2}$ 不是整数

则 $f(x)$ 是有理数域上[[MK41][不可约]]

**** 证明

假设 $f(x)$ 可约，则根据[[MK84][定理2]]必有 $f(x)=h(x)g(x)$ 分解为两个整系数多项式

定义 $f(x)=\left(\sum_{i=0}^mb_ix^i\right)\left(\sum_{i=0}^lc_ix^i\right)$ 根据[[MK6][乘法]]可得 $f(x)=\sum_{s=0}^n\left(\sum_{i+j=s}b_ic_j\right)x^s$

则有 $a_0=b_0c_0\land a_n=b_mc_l$ 

由于 $\frac{a_0}{p}$ 是整数，故 $\frac{b_0c_0}{p}$ 亦为整数，由于 $\frac{a_0}{p^2}$ 不是整数，故 $\frac{b_0}{p},\frac{c_0}{p}$ 不能同时为整数，假设 $\frac{b_0}{p}$ 是整数。

由于 $\frac{a_n}{p}$ 不为整数，故 $\frac{b_m}{p}$ 不为整数。

故假设从 $b_0$ 开始逐步加 $1$ ，第一个使 $\frac{b_i}{p}$ 不为整数的 $i=k$ ，则有 $\frac{b_i}{p}\begin{cases}\in\mathbb{N}&i<k\\\not\in\mathbb{N}&i=k\end{cases}$ 

其中 $0\leq k\leq m$ 根据[[MK18][定理]]可得 $l+m=n$ 由于 $l>0$ 故有 $m<n\rightarrow k<n$

同样根据乘法，有 $a_k=\sum_{i+j=k}b_ic_j$ 其中 $b_kc_0$ 为其中一项

由于 $k<n$ 故 $a_k\ne a_n$ 故根据条件（2）可得 $\frac{a_k}{p}$ 是整数，则有 $\frac{b_kc_0}{p}$ 亦为整数

由于 $p$ 是素数，故必有 $\frac{b_k}{p}\in\mathbb{N}\land\frac{c_0}{p}\in\mathbb{N}$ ，与上述证明矛盾。

故 $f(x)$ 不可约

**** 推论1

有理[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][数域]]上存在任意次不可约多项式

***** 证明

对于任意 $n\in\mathbb{N}^+$ 构建多项式 $f(x)=x^n+2$ 定义 $p=2$ 即为素数，则满足：

（1） $\frac{a_n}{p}=\frac{1}{2}$ 不是整数

（2） $\frac{a_0}{p}=\frac{2}{2}=1\land\frac{a_i}{p}=\frac{0}{2}$ 是整数 $i=0,1,...,n-1$

（3） $\frac{a_0}{p^2}=\frac{2}{4}=\frac{1}{2}$ 不是整数

故根据Eisenstein判别法 $f(x)=x^n+2$ 在有理数域上不可约

**** 推论2

若 $f(x)\in\mathbb{Q}[x]$ 是次数大于零的整系数多项式，则其可约的充要条件是 $g(x)=f(x+b)$ 可约

***** 证明

****** 充分

设 $f(x)$ 可约，则根据[[MK84][定理2]]可得 $f(x)=h_1(x)h_2(x)\land \deg(f(x))>\deg(h_1(x))$

则有 $g(x)=f(x+b)=h_1(x+b)h_2(x+b)$ 即 $g(x)$ 可约

****** 必要

由于 $g(x)=f(x+b)\rightarrow f(x)=g(x-b)$ 同理可由充分性证得

* 剩余类环

** 定义<<MK85>>

*** 定义集合

对于任意整数 $m$ 以及整数集合 $\mathbb{Z}$ 有 $m\in\mathbb{Z}$

根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-基本定义-笛卡尔积]]以及[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-二元关系-基础定义]]定义关系 $R=\left\{<a,b>\in Z\times Z\big|a\mod m=b\mod m\right\}$

根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-特殊关系-等价关系]]可知 $R$ 满足自反性，对称性以及传递性，故 $R$ 为等价关系

则根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-特殊关系-划分-定理-定理1]] $R$ 的[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-特殊关系-等价关系-等价类]]划分 $\mathbb{Z}$

对于任意 $x\in \mathbb{Z}$ 定义其等价类 $\overline{x}=\left\{y\big|y\in\mathbb{Z}\land xRy\right\}$ 显然 $\mathbb{Z}$ 被划分为 $\overline{0},\overline{1},...,\overline{m-1}$ 这 $m$ 个等价类

故定义集合 $U=\left\{\overline{x}\big|x\in\mathbb{Z}\right\}$ 由于 $m$ 的余数是小于 $m$ 的整数，故 $U$ 的[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-基数]]是 $|U|=m$

*** 定义加法

当 $x\in\mathbb{Z}\land y\in\mathbb{Z}$ 时定义加法为 $\overline{x}+\overline{y}=\overline{x+y}$

**** 唯一性

由于 $\overline{x},\overline{y}$ 亦可表述为 $\overline{a},\overline{b}$ ，对于任意 $a\in[x]_R\land b\in[y]_R$ ，同样有 $\overline{a}+\overline{b}=\overline{a+b}$

根据[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-代数的构建-运算]]可知运算是[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数]]，必须满足唯一性。

对于任意 $a\in[x]_R\land b\in[y]_R$ 均可表示为 $a=a'm+x'\land b=b'm+y'$ 其中 $\{a',b'\}\subset\mathbb{Z}$ 且 $\{x',y'\}\subset\left\{z\big|z\in\mathbb{Z}\land z<m\right\}$

则有 $(a+b)\mod m = ((a'+b')m+x'+y')\mod m=(x'+y')\mod m$

故有任意 $[x]_R,[y]_R$ 中的元素想加后，均属于 $[x+y]_R$

*** 定义乘法

当 $x\in\mathbb{Z}\land y\in\mathbb{Z}$ 时定义乘法为 $\overline{x}\times\overline{y}=\overline{xy}$

**** 唯一性

由于 $\overline{x},\overline{y}$ 亦可表述为 $\overline{a},\overline{b}$ ，对于任意 $a\in[x]_R\land b\in[y]_R$ ，同样有 $\overline{a}\times\overline{b}=\overline{ab}$

根据[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-代数的构建-运算]]可知运算是[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数]]，必须满足唯一性。

对于任意 $a\in[x]_R\land b\in[y]_R$ 均可表示为 $a=a'm+x'\land b=b'm+y'$ 其中 $\{a',b'\}\subset\mathbb{Z}$ 且 $\{x',y'\}\subset\left\{z\big|z\in\mathbb{Z}\land z<m\right\}$

则有 $(ab)\mod m=((a'b'm+a'y'+x'b')m+x'y')\mod m=(x'y')\mod m$

故有任意 $[x]_R,[y]_R$ 中的元素想乘后，均属于 $[xy]_R$

*** 证明是环

根据[[MK10][定义]]有：

（1） $\overline{x}+\overline{y}+\overline{z}=\overline{x+y}+\overline{z}=\overline{x+y+z}=\overline{x+(y+z)}=\overline{x}+\overline{y+z}=\overline{x}+(\overline{y}+\overline{z})$ 满足加法结合律

（2） $\overline{x}+\overline{y}=\overline{x+y}=\overline{y+x}=\overline{y}+\overline{x}$ 满足加法交换律

（3） $\forall \overline{x}\in U\rightarrow \overline{0}+\overline{x}=\overline{x+0}=\overline{x}$ 存在加法幺元

（4） $\forall \overline{x}\in U\rightarrow \exists\left(\overline{-x}\in\mathbb{Z}\rightarrow\overline{-x}+\overline{x}=\overline{0}\right)$ 存在加法逆元

（5） $\overline{x}\times\overline{y}\times\overline{z}=\overline{xy}\times\overline{z}=\overline{xyz}=\overline{x(yz)}=\overline{x}\times\overline{yz}=\overline{x}\times(\overline{y}\times\overline{z})$ 满足乘法结合律

（6） $\overline{x}\times\left(\overline{y}＋\overline{z}\right)=\overline{x}\times\overline{y+z}=\overline{x(y+z)}=\overline{xy+xz}=\overline{xy}+\overline{xz}=\overline{x}\times\overline{y}+\overline{x}\times\overline{z}$ 满足分配率

（7） 显然加法，乘法封闭

故 $<U,+,\times>$ 是环，进一步显然有乘法交换律，故是交换环。进一步有 $\forall a\left(\overline{a}\in\mathbb{Z}\rightarrow\overline{1}\times\overline{a}=\overline{a}\right)$ 即 $\overline{1}$ 是[[MK10][环]]中的乘法幺元。

最终称代数结构 $\mathbb{Z}_m=<U,+,\cdot>$ 为 $m$ 的剩余类环

** 引理

若 $\{a,b\}\subset\mathbb{Z}$ 且 $a,b$ 互素，则其充要条件是存在 $\{u,v\}\subset\mathbb{Z}$ 满足 $ua+vb=1$

*** 证明

定义 $(a,b)$ 为 $a,b$ 的最大公因数

**** 充份

假设 $x=ua+vb$ 其中 $\{u,v\}\subset\mathbb{Z}$ 由于 $a,b$ 为整数即有限，故存在 $d=u_0a+v_0b$ 满足 $\forall\{u,v\}\subset\mathbb{Z}\rightarrow ua+vb\geq d>0$

则对于任意 $x$ 均可表述为 $x=pd+q$ 其中 $\{p,q\}\subset\mathbb{Z}$ 且 $0\leq q<d$

故有 $q=x-pd=ua+vb-pu_0a-pv_0b=(u-pu_0)a+(v-pv_0)b$ 则 $q$ 亦为 $u'a+v'b$ 形式

由于 $d$ 为该形式最小可能的正整数，且 $0\leq q<d$ 故 $q=0$

故对于任意 $\{u,v\}\in\mathbb{Z}$ 均有 $ua+vb=pd$ 即 $d\mid(ua+vb)$

去 $u=1,v=0$ 则可得 $d\mid a$ 同理可证 $d\mid b$ 故有 $d\mid(a,b)$ 即 $d\mid 1$ 由于 $d\in\mathbb{Z}$ 故 $d=1$

即存在 $\{u_0,v_0\}\in\mathbb{Z}$ 使得 $u_0a+v_0b=1$

**** 必要

由于 $(a,b)\mid a\land(a,b)\mid b$ 则必有 $(a,b)\mid ua+vb$

由于 $ua+vb=1$ 故有 $(a,b)\mid 1$ 即整除 $1$ 则 $(a,b)=1$

** 定理1

若 $\mathbb{Z}_m=<U,+,\cdot>$ 是一个 $m$ 的[[MK85][剩余类环]]，若 $m$ 是素数，则 $Z_m$ 是[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][域]]

*** 证明

取 $\overline{x}\in \mathbb{Z}_m$ 其中 $0< x<m$ 由于剩余类环是有限元，故 $\overline{x}$ 可代表其中的任意元素。

由于 $m$ 是素数，且 $x<m$ 故有 $(m,x)=1$ 即最大公因数为 $1$

根据[[MK86][引理]]可得存在 $\{u,v\}\subset\mathbb{Z}$ 使得 $um+vx=1$ ，则根据[[MK85][定义]]中的加法乘法可得 

\begin{aligned}
\overline{1}=&\overline{um+vx}\\
=&\overline{u}\times\overline{m}+\overline{vx}\\
=&\overline{0}+\overline{vx}\\
=&\overline{0+vx}\\
=&\overline{vx}\\
=&\overline{v}\times\overline{x}
\end{aligned}

即 $\overline{v}\times\overline{x}=\overline{1}$ 由于 $v\in\mathbb{Z}$ 可得 $\overline{v}\in\mathbb{Z}_m$ 即对于任意 $\overline{x}\in\mathbb{Z}\land\overline{x}\ne\overline{0}$ 存在 $\overline{v}\in\mathbb{Z}$ 使得 $\overline{v}\times\overline{x}=\overline{1}$

又根据[[MK85][定义]]可得剩余类环 $\mathbb{Z}_m$ 是交换环，故根据[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][域]]定义可得 $\mathbb{Z}_m$ 是域

** 定理2

若 $\mathbb{Z}_m=<U,+,\cdot>$ 是一个 $m$ 的[[MK85][剩余类环]]，若 $m$ 是合数，则 $Z_m$ 不是[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][域]]

*** 证明

若 $m$ 为合数，则必有 $ab=m$ 其中 $1<a<m\land1<b<m$ 且 $\{a,b\}\subset\mathbb{Z}$

若存在 $\overline{x}\in\mathbb{Z}_m$ 使得 $\overline{a}\times\overline{x}=\overline{1}$ 则有 $\overline{xa}=\overline{1}$ 即 $xa=pm+1$ 其中 $p\in\mathbb{Z}$

两侧同除 $a$ 得 $x=pb+\frac{1}{a}$ 由于 $b\in\mathbb{Z}$ 故有 $pb\in\mathbb{Z}$

由于 $a>1$ 故有 $\frac{1}{a}\not\in\mathbb{Z}$ 故 $x=pb+\frac{1}{a}\not\in\mathbb{Z}$ 即 $\overline{x}\not\in\mathbb{Z}_m$ ，即矛盾。

故对于 $\overline{a}\in\mathbb{Z}_m\land\overline{a}\ne\overline{0}$ 不存在乘法[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-特殊元素-逆元]]，故不是[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][域]]
