#+LATEX_CLASS: ctexart

#+TITLE: 矩阵运算

current mark: 80

* 矩阵基础

** 矩阵的表述<<MK6>>

定义 $M_{s\times n}(K)$ 为[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK24][数域]] $K$ 上的 $s$ 行 $n$ 列的 *所有* 矩阵的集合

定义 $M=\left[m_{ij}\right]_{s\times n}$ 为第 $i$ 行 $j$ 列上的元素为 $m_{ij}$ 的 $s$ 行 $n$ 列的矩阵

** 矩阵相等<<MK1>>

定义矩阵 $M_{s\times n}(K)=N_{x\times y}(K')$ 为满足：

（1） $s=x\land n=y$ 

（2） 第 $i$ 行 $j$ 列的元素相等

* 矩阵空间

** 矩阵组成的线性空间<<MK10>>

$\mathcal{V}=<M_{s\times n}(K),K,+,\cdot>$ 是[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK24][数域]] $K$ 上的[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性空间]]，记为 $M_{s\times n}(K)$

其中 $+$ 是[[MK2][矩阵乘法]]， $\cdot$ 是[[MK3][矩阵数乘]]

*** 证明

由于 $K$ 亦是[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK24][数域]]，故为[[~/文档/note/高等代数/Algb-4-Multi-equ.org::MK12][交换环]]，即矩阵中的元素满足：

（1） 加法结合律

（2） 加法交换律

（3） 存在加法幺元 $0$

（4） 存在加法逆元 $-a$

（5） 存在乘法幺元 $1$

（6） 乘法结合律

（7） 乘法分配率

则根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性空间]]定义以及以下证明可得 $\mathcal{V}$ 是线性空间

**** 交换律

根据[[MK1][矩阵相等]]以及[[MK2][矩阵加法]]可得 $M+N=\left[a_{ij}+b_{ij}\right]_{s\times n}=\left[b_{ij}+a_{ij}\right]_{s\times n}=N+M$

**** 结合律

根据[[MK1][矩阵相等]]以及[[MK2][矩阵加法]]可得 $(M+N)+L=\left[(a_{ij}+b_{ij})+c_{ij}\right]_{s\times n}=\left[a_{ij}+(b_{ij}+c_{ij})\right]_{s\times n}=M_(N+L)$

**** 加法幺元<<MK9>>

记录 $O=\left[0\right]_{s\times n}$ 为零元

**** 加法逆元

根据[[MK3][矩阵数乘]]定义 $(-1)M = \left[-a_{ij}\right]_{s\times n}$ 为 $M$ 的负元，且 $M+(-1)M=\left[a_{ij}-a_{ij}\right]_{s\times n}=\left[0\right]_{s\times n}$ 为零元

**** 数乘 $1$

根据[[MK3][矩阵数乘]]定义 $1M=\left[1\times a_{ij}\right]_{s\times n}=\left[a_{ij}\right]_{s\times n}$

**** 数乘结合律

根据[[MK3][矩阵数乘]]定义 $(kl)M=\left[(kl)a_{ij}\right]_{s\times n}=\left[k(la_{ij})\right]_{s\times n}=k(lM)$

**** 数乘分配律1

根据[[MK3][矩阵数乘]]定义 $(k+l)M=\left[(k+l)a_{ij}\right]_{s\times n}=\left[ka_{ij}+la_{ij})\right]_{s\times n}=kM+lM$

**** 数乘分配率2

根据[[MK3][矩阵数乘]]以及[[MK2][矩阵加法]]可得 $k(M+N)=\left[k(a_{ij}+b_{ij})\right]_{s\times n}=\left[ka_{ij}+kb_{ij}\right]_{s\times n}=kM+kN$

** 矩阵线性空间的基<<MK20>>

对于矩阵线性空间 $\mathcal{V}=<M_{s\times n}(K),K,+,\cdot>$

其有一组基为集合 $\left\{E_{ij}\big|1\leq i\leq s\land 1\leq j\leq n\right\}$ 中的所有元素，其中 $E_{ij}$ 是[[MK8][基本矩阵]]

*** 证明

根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK36][基的定义]]，做以下证明

**** 任意元素可由基现行表述

定义 $A=[a_{ij}]_{s\times n}$ 为任意矩阵，则根据[[MK2][矩阵加法]]以及[[MK3][矩阵数乘]]可得

$A=\sum_{l=1}^s\left\{\sum_{k=1}^n[D(i,j,l,k)]_{s\times n}\right\}$ 其中 $D(i,j,l,k)=\begin{cases}a_{lk}&i=l\land j=k\\0&i\ne l\lor j\ne k\end{cases}$

根据[[MK8][基本矩阵定义]]可得进一步 $A=\sum_{l=1}^s\left\{\sum_{k=1}^na_{lk}E_{lk}\right\}$

故任意同维度矩阵 $A$ 可由集合 $\left\{E_{ij}\big|1\leq i\leq s\land 1\leq j\leq n\right\}$ 中的元素线性表述

**** 基中的元素线性不相关

根据[[MK9][零元定义]]以及[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK8][定义]]可得当且仅当 $\forall i\forall j(k_{ij}=0)$ 时有 $\sum_{l=1}^s\left\{\sum_{k=1}^nk_{lk}E_{lk}\right\}=[0]_{s\times n}$ 则线性不相关

其中 $k_{ij}\in K$

由于 $[0]_{s\times n}$ 中每个元素都为零，故若 $k_{ij}\ne 0$ 则有 $\sum_{l=1}^s\left\{\sum_{k=1}^nk_{lk}E_{lk}\right\}\ne[0]_{s\times n}$

总上所述，线性不相关

*** 推论1

根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK43][定理2]]可得 $M_{s\times n}(K)$ 任意基包含的向量个数为 $sn$

*** 推论2<<MK52>>

根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK51][线性空间的维数]]可得 $\dim\left(\mathcal{V}\right)=sn$

** 定理1

根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性子空间-子空间的运算-直和]]，线性空间 $M_{n\times n}(K)$ 是其[[MK15][对称子空间]]和[[MK16][斜对称子空间]]的直和

*** 证明

**** 证明相加为直和

定义 $M_{n\times n}(K)$ 的对称子空间为 $S$ 斜对称子空间为 $S$ 根据[[MK10][线性空间定义]]此时 $[0]_{n\times n}$ 为零元

假设 $A+B=[0]_{n\times n}$ 且 $A\in S\land B\in S'$ 对于任意 $A$ 中的元素 $a_{ij}$ 根据[[MK17][对称矩阵定义]]此时 $a_{ji}=a_{ij}$

若 $A+B=[0]_{n\times n}$ 则必满足 $b_{ij}=-a_{ij}\land b_{ji}=-a_{ji}$ 同理根据[[MK18][斜对称矩阵定义]] $b_{ij}=-b_{ji}$

综上所述 $a_{ij}=a_{ji}=-b_{ji}=b_{ij}=-a_{ij}$ 即 $a_{ij}=-a_{ji}$ 则 $a_{ij}=0$

故 $A=B=[0]_{n\times n}$ 则根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性子空间-子空间的运算-直和-两个子空间直和-性质]]可得 $S+S'$ 为直和，即  $S+S'=S\textcircled{+}S'$

**** 求子空间得基

定义 $Z_{uv}=[f(i,j)]$ 其中 $f(i,j)=\begin{cases}1&i=u\land j=v\\1&i=v\land j=u\\0&else\end{cases}$ 则 $Z_{uv}$ 满足 $f(i,j)=f(j,i)$ 为对称矩阵

对于任意对称矩阵 $A=[a_{ij}]_{n\times n}$ 中某个元素 $a_{ij}$ 且 $i\leq j$ 可表述为 $a_{ij}Z_{ij}$

故最终 $A=\sum_{i=1}^n\left\{\sum_{j=i}^na_{ij}Z_{ij}\right\}$ 故 $A$ 可由 $\left\{Z_{ij}\big|i\leq j\right\}$ 中的元素线性表述。

且当且仅当 $k_{ij}=0$ 时满足 $[0]_{n\times n}=\sum_{i=1}^n\left\{\sum_{j=i}^nk_{ij}Z_{ij}\right\}$ 因为不同 $i,j$ 导致 $Z_{ij}$ 非零的位置不同，无法相互抵消。

故 $\left\{Z_{ij}\big|i\leq j\right\}$ 为 $S$ 的基。

定义 $Z'_{uv}=[f'(i,j)]$ 其中 $f'(i,j)=\begin{cases}0&i=j\\1&i=u\land j=v\\-1&i=v\land j=u\\0&else\end{cases}$ 

则根据[[MK19][主对角线性质]]以及[[MK18][斜对称矩阵定义]]，同理可证 $\left\{Z'_{ij}\big|i>j\right\}$ 为 $S'$ 的基。

**** 证明基可以互相表述

根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性子空间-子空间的运算-直和-两个子空间直和-性质]]可得 $S+S'$ 的基为 $\left\{Z_{ij}\big|i>j\right\}\cup\left\{Z'_{ij}\big|i\leq j\right\}$

根据[[MK20][矩阵空间基]]可得 $M_{n\times n}(K)$ 的一组基为 $\left\{E_{ij}\big|1\leq i\leq n\land 1\leq j\leq n\right\}$ 

根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性空间的基和维数-线性空间的维数]]可知 $\dim(M_{n\times n}(K))=n^2=\dim(S+S')$

由于 $\left\{Z_{ij}\big|i>j\right\}\cup\left\{Z'_{ij}\big|i\leq j\right\}$ 是基，故线性不相关

则根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性空间的基和维数-线性空间的维数-命题2]] $\left\{Z_{ij}\big|i>j\right\}\cup\left\{Z'_{ij}\big|i\leq j\right\}$ 亦为 $M_{n\times n}(K)$ 的一组基

即任意 $A\in M_{n\times n}(K)$ 同样可由 $\left\{Z_{ij}\big|i>j\right\}\cup\left\{Z'_{ij}\big|i\leq j\right\}$ 线性表述，且根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性空间定义]]线性表述运算封闭

故对于任意 $A\in M_{n\times n}(K)$ 可得 $A\in S+S'$ 由于线性空间本身为集合，则根据[[~/文档/note/离散数学/Disc_Math.org][集合论-集合定义-ZFC公理化集合论-外延公理]]可得 $M_{n\times n}(K)=S+S'$

* 方阵环<<MK75>>

任意 $A=[a_{ij}]_{n\times n}$ 为[[~/文档/note/抽象代数/cxds.org::MK338][域]] $\mathcal{K}=\left<K,\mathfrak{g}\right>$ 上的方阵，定义：

（1） 任意 $k\in K$ 定义 $E(k)=[e(i,j)]_{n\times n}$ 其中 $e(i,j)=\begin{cases}k&i=j\\\mathfrak{g}(c_0)&i\ne j\end{cases}$

（2） $I_A(f_\times)$ 为[[MK5][矩阵乘法]]

（3） $I_A(f_+)$ 为[[MK2][矩阵加法]]

（4） 任意 $[a'_ {ij}]_{n\times n}\in M_A$ 定义 $I_A(f_-)([a'_ {ij}]_{n\times n})=\left[\mathfrak{g}(f_\times)(\mathfrak{g}(f_-)(\mathfrak{g}(c_1)),a_{ij})\right]_{n\times n}$

（5） $I_A(c_0)=[\mathfrak{g}(c_0)]_{n\times n}$

（6） $I_A(c_1)=[e(i,j)]_{n\times n}$ 其中 $e(i,j)=\begin{cases}\mathfrak{g}(c_1)&i=j\\\mathfrak{g}(c_0)&i\ne j\end{cases}$

（7） $M_A=\left\{\sum_{i=1}^n E(k_i)A^i\big|k_i\in K\land n\in\mathbb{N}\right\}$ 其中加法为 $I_A(f_\times)$ ，乘法为 $I_A(f_+)$ 

则结构 $\mathcal{M}_A=\left<M_A,I_A\right>$ 为[[~/文档/note/抽象代数/cxds.org::MK362][非零幺元]]且 $\mathcal{M}_A\vDash(\forall x_1(\forall x_2(f_\times(x_1,x_2)\hat{=}f_\times(x_2,x_1))))$

** 证明

根据[[MK50][加法交换律、结合律]]以及[[MK21][乘法结合律]]、[[MK54][乘法分配律]]以及 $I_A(c_0),I_A(c_1)$ 相关性质易证 $\mathcal{M}_A=\left<M_A,I_A\right>$ 为[[~/文档/note/抽象代数/cxds.org::MK362][非零幺元]]

显然根据[[MK5][乘法]]可得 $E(k)[a'_ {ij}]_{n\times n}=[ka'_ {ij}]_{n\times n}$ ，则根据[[MK74][幂性质]]以及[[MK54][乘法分配律]]、[[MK50][加法交换律]]易证：

\begin{aligned}
\left(\sum_{i=1}^{n_1}E(k_{i,1})A^i\right)\left(\sum_{j=1}^{n_2}E(k_{j,2})A^j\right)=&\sum_{i=1}^{n_1}\left(E(k_{i,1})A^i\left(\sum_{j=1}^{n_2}E(k_{j,2})A^j\right)\right)
=\sum_{i=1}^{n_1}\left(\sum_{j=1}^{n_2}\left(E(k_{i,1})A^iE(k_{j,2})A^j\right)\right)\\
=&\sum_{i=1}^{n_1}\left(\sum_{j=1}^{n_2}\left((E(k_{i,1})E(k_{j,2}))(A^i A^j)\right)\right)
=\sum_{i=1}^{n_1}\left(\sum_{j=1}^{n_2}\left((E(k_{j,2})E(k_{i,1}))(A^j A^i)\right)\right)\\
=&\sum_{i=1}^{n_1}\left(\sum_{j=1}^{n_2}\left(E(k_{j,2})A^j E(k_{i,1})A^i\right)\right)
=\sum_{j=1}^{n_2}\left(\sum_{i=1}^{n_1}\left(E(k_{j,2})A^j E(k_{i,1})A^i\right)\right)\\
=&\sum_{j=1}^{n_2}\left(\sum_{i=1}^{n_1}\left(E(k_{j,2})A^j E(k_{i,1})A^i\right)\right)
=\sum_{j=1}^{n_2}\left(E(k_{j,2})A^j\left(\sum_{i=1}^{n_1} E(k_{i,1})A^i\right)\right)\\
=&\left(\sum_{j=1}^{n_2}E(k_{j,2})A^j\right)\left(\sum_{i=1}^{n_1} E(k_{i,1})A^i\right)
\end{aligned}

** 单位[[~/文档/note/抽象代数/cxds.org::MK338][域]]<<MK76>>

定义：

（1） 任意 $k\in K$ 定义 $E(k)=[e(i,j)]_{n\times n}$ 其中 $e(i,j)=\begin{cases}k&i=j\\\mathfrak{g}(c_0)&i\ne j\end{cases}$

（2） $I_E(f_\times)$ 为[[MK5][矩阵乘法]]

（3） $I_E(f_+)$ 为[[MK2][矩阵加法]]

（4） 任意 $[a'_ {ij}]_{n\times n}\in M_A$ 定义 $I_E(f_-)([a'_ {ij}]_{n\times n})=\left[\mathfrak{g}(f_\times)(\mathfrak{g}(f_-)(\mathfrak{g}(c_1)),a_{ij})\right]_{n\times n}$

（5） $I_E(c_0)=[\mathfrak{g}(c_0)]_{n\times n}$

（6） $I_E(c_1)=[e(i,j)]_{n\times n}$ 其中 $e(i,j)=\begin{cases}\mathfrak{g}(c_1)&i=j\\\mathfrak{g}(c_0)&i\ne j\end{cases}$

（7） $M_E=\left\{E(k_i)\big|k_i\in K\right\}$ 其中加法为 $I_E(f_\times)$ ，乘法为 $I_E(f_+)$ 

则结构 $\mathcal{M}_E=\left<M_1,I_E\right>$ 为[[~/文档/note/抽象代数/cxds.org::MK338][域]]

*** 证明

显然根据[[MK5][矩阵乘法]]，[[MK2][矩阵加法]]易证对于任意 $\{A_1,A_2\}\subset M_E$ 有 $I_E(f_+)(A_1,A_2)\in M_E,I_E(f_\times)(A_1,A_2)\in M_E,I_E(f_-)(A_1)\in M_E$

故可得 $\mathcal{M}_E$ 是[[~/文档/note/抽象代数/cxds.org::MK335][域语言]] $\mathcal{L}_{\mathcal{A}_\mathcbb{F}}$ 上的[[~/文档/note/数理逻辑/sllj.org::MK153][结构]]。[[MK75][同理可证]] $\mathcal{M}_E$ 为[[~/文档/note/抽象代数/cxds.org::MK362][非零幺元]]且 $\mathcal{M}_E\vDash(\forall x_1(\forall x_2(f_\times(x_1,x_2)\hat{=}f_\times(x_2,x_1))))$

显然对于任意 $E(k)$ 由于 $k\in K$ 故存在 $k^{-1}\in K$ 使得 $\mathfrak{g}(f_\times)(k,k^{-1})=\mathfrak{g}(c_1)$

则根据[[MK5][矩阵乘法]]易证 $E(k)E(k^{-1})=I_E(c_1)$ 即根据[[~/文档/note/抽象代数/cxds.org::MK356][性质4]]有 $\mathcal{M}_E\vDash(\forall x_1((\lnot(x_1\hat{=}c_0))\to(\exists x_2(f_\times(x_1,x_2)\hat{ =}c_1))))$

* 特殊矩阵

** 单位矩阵<<MK4>>

定义单位矩阵 $I_n=[D(i,j)]_{n\times n}$ 其中 $D(i,j)=\begin{cases}1&i=j\\0&i\ne j\end{cases}$

*** 性质<<MK22>>

\begin{aligned}
A_{s\times n}I_n&= A_{s\times n}\\
I_nA_{n\times s}&= A_{s\times n}\\
\end{aligned}

**** 证明

仅证 $A_{s\times n}I_n&= A_{s\times n}$ 其他同理

根据[[MK6][矩阵定义]]以及[[MK5][矩阵乘法]]可的：

\begin{aligned}
&A_{s\times n}I_n\\
=&\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{s1}&a_{s2}&...&a_{sn}\end{matrix}\right]\left[\begin{matrix}1&0&...&0\\0&1&...&0\\...&...&...&...\\0&0&...&1\end{matrix}\right]\\
=&\left[t_{ij}=\sum_{k=1}^n a_{ik}D(k,j)\right]_{s\times n}\\
=&\left[t_{ij}=a_{ij}\right]_{s\times n}
\end{aligned}

** 基本矩阵<<MK8>>

单位矩阵定义为 $E_{lk}=[D(i,j)]_{s\times n}$ 其中 $D(i,j)=\begin{cases}1&i=l\land j=k\\0&i\ne l\lor j\ne k\end{cases}$

** 对角矩阵<<MK70>>

定义对角矩阵为 $A_n=[D(i,j)]_{n\times n}$ 其中 $D(i,j)=\begin{cases}a_{ij}&i=j\\0&i\ne j\end{cases}$

*** 性质

**** 子空间

所有对角矩阵是[[MK10][线性空间]] $M_{n\times n}(K)$ 的子空间

***** 证明<<MK11>>

根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性子空间-线性子空间充要条件]]依次证明

（1）显然对于 $M_{n\times n}(K)$ 对角矩阵不为空集

（2）根据[[MK2][矩阵加法]] $A_n+B_n$ 亦为对角矩阵

（3）根据[[MK3][矩阵数乘]] $kA_n$ 亦为对角矩阵

综上所述，对角矩阵是 $M_{n\times n}(K)$ 的线性子空间

**** 乘法封闭

定义 $A_n,B_n$ 为对角阵，则 $A_nB_n$ 根据[[MK5][矩阵乘法]]亦为对角阵

** 伴随矩阵<<MK73>>

若 $A_n=[a_{ij}]_{n\times n}$ 为 $n$ 阶方阵，定义 $B=[U_{ij}]^T_{n\times n}$ ，其中 $U_{ij}$ 定义为 $A_n$ 对于元素 $a_{ij}$ 的[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK25][代数余子式]]

则称 $B$ 为 $A_n$ 的伴随矩阵，记作 $B=\text{adj}(A_n)$

** 分块对角矩阵<<MK72>>

定义分块对角矩阵为 $A_n=[D(i,j)]_{n\times n}$ 满足存在 $1\leq n_1<...<n_k\leq n$ 使得

其中 $D(i,j)=\begin{cases}a_{ij}&(\exists u((n_u\leq i<n_{u+1})\land(n_u\leq j<n_{u+1})))\\0&else\end{cases}$ 定义 $N=\{n_1,...,n_k\}$ 则分块对角矩阵记作 $\left[a_{ij}\right]^N_{n\times n}$

** 数量矩阵

定义 $kI_n$ 为数量矩阵，其中 $k\in K$ 且 $I_n$ 为[[MK4][单位矩阵]]

*** 性质

**** 子空间

所有数量矩阵是[[MK10][线性空间]] $M_{n\times n}(K)$ 的子空间

***** 证明

同[[MK11][之前证明]]

**** 运算性质

\begin{aligned}
(k_1I_n)(k_2I_n)&=k_1k_2I_n\\
(kI_n)A_n&=kA_n\\
(kI_n)A_n&=A_n(kI_n)
\end{aligned}

** 上（下）三角矩阵<<MK33>>

定义 $A_n=\left[D(i,j)\right]_{n\times n}$ 若：

（1） $D(i,j)=\begin{cases}a_{ij}&j\geq i\\0&j<i\end{cases}$ 则为上三角矩阵

（2） $D(i,j)=\begin{cases}a_{ij}&j\leq i\\0&j>i\end{cases}$ 则为下三角矩阵

*** 性质

**** 子空间

所有上（下）三角矩阵是[[MK10][线性空间]] $M_{n\times n}(K)$ 的子空间

证明[[MK11][同理]]

**** 乘法封闭

根据[[MK5][矩阵乘法]]定义，任意两个上三角矩阵相乘仍然得上三角矩阵

同理，任意两个下三角矩阵相乘仍然得下三角矩阵

** 对称矩阵<<MK17>>

若 $A_{s\times n}$ 为对称矩阵，则有 $A^T=A$ 即：

（1） $s=n$

（2） $A_{n\times n}^T=A_{n\times n}$

*** 性质

**** 子空间<<MK15>>

所有对称矩阵是[[MK10][线性空间]] $M_{n\times n}(K)$ 的子空间

证明[[MK11][同理]]

**** 计算性质

若 $A=[a_{ij}]_{n\times n}$ 为对称矩阵，则根据[[MK14][矩阵转置]] $a_{ij}=a_{ij}$

** 斜对称矩阵

*** 定义<<MK18>>

若 $A_{s\times n}$ 为斜对称矩阵，则有 $A^T=A$ 即：

（1） $s=n$

（2） $A_{n\times n}^T=-A_{n\times n}$

*** 性质

**** 子空间<<MK16>>

所有斜对称矩阵是[[MK10][线性空间]] $M_{n\times n}(K)$ 的子空间

证明[[MK11][同理]]

**** 主对角线<<MK19>>

斜对称矩阵的主对角线上的元素全部为 $0$

***** 证明

根据定义可得若 $A_n=\left[a_{ij}\right]_{n\times n}$ 为斜对称矩阵，则 $A_n^T=-A_n$

故有 $a_{ij}=-a_{ji}$ 则对角线上的元素有 $a_{ii}=-a_{ii}=0$

** 初等矩阵<<MK13>>

以[[MK4][单位矩阵]]为基础，初等矩阵主要包含一下三种

**** 第一型<<MK12>>

单位矩阵 $I_n\xrightarrow{\textcircled{i}+k\textcircled{j}}P^2_n(i,kj)$ 即单位矩阵得第 $j$ 列乘以 $k$ 加到第 $i$ 行
 
或者 $I_n\xrightarrow[\textcircled{j}+k\textcircled{i}]{} P^1_n(i,kj)$ 即单位矩阵第 $i$ 列乘以 $k$ 加到第 $j$ 列

由于单位矩阵仅对角线上的元素为 $1$ 其余均为 $0$ ，故 $j$ 行仅有 $j$ 列的元素为 $1$ 乘以 $k$ 后加到 $i$ 行，则 $i$ 行 $j$ 列元素变为 $k$

同理 $i$ 列仅有 $i$ 行元素为 $1$ 乘以 $k$ 后加到 $j$ 列后第 $j$ 列 $i$ 行的元素为 $k$

故得 $P^1_n(i,kj)=P^2_n(i,kj)$ 综合把转换后得第一型初等矩阵记作 $P_n(i,kj)$

**** 第二型

单位矩阵 $I_n\xrightarrow{\textcircled{i}\Leftrightarrow\textcircled{j}}P^1_n(i,j)$ 即单位矩阵 $i,j$ 行互换

或者 $I_n\xrightarrow[\textcircled{j}\Leftrightarrow\textcircled{i}]{}P^2_n(i,j)$ 即单位矩阵第 $j,i$ 列互换

[[MK12][同理可证]] $P^2_n(i,j)=P^1_n(i,j)$ 故记作 $P_n(i,j)$

**** 第三型

单位矩阵 $I_n\xrightarrow{k\textcircled{i}}P^1_n(ki)$ 即单位矩阵 $i$ 行乘以 $k$

或者 $I_n\xrightarrow[k\textcircled{i}]{}P^2_n(ki)$ 即单位矩阵第 $i$ 列乘以 $k$

[[MK12][同理可证]] $P^2_n(ki)=P^1_n(ki)$ 故记作 $P_n(ki)$

*** 初等变换<<MK32>>

初等矩阵相当于初等行变换，其中

**** 第一型<<MK30>>

$P_n(i,kj)A_{n\times s}$ 相当于 $A\xrightarrow{\textcircled{i}+k\textcircled{j}}B$

$A_{s\times n}P_n(i,kj)$ 相当于 $A\xrightarrow[\textcircled{i}+k\textcircled{j}]{}B$

***** 证明

仅证右乘，左乘同理

根据[[MK13][定义]] $P_n(u,kv)=\left[f(i,j)\right]_{n\times n}$ 其中 $f(i,j)=\begin{cases}k&i=u\land j=v\\1&i=j\\0&else\end{cases}$

故根据[[MK5][矩阵乘法]]可得 $P_n(u,kv)A_{s\times n}=\left[t_{ij}=\sum_{k=1}^n f(i,k)a_{kj}\right]_{s\times n}$

根据 $f(i,j)$ 的定义，对于任意 $i\ne a$ 可得 $t_{ij}=a_{ij}$

对于 $i=u$ 则有 $f(u,j)=\begin{cases}k&j=v\\1&j=u\\0&else\end{cases}$ 故有 $t_{ij}=ka_{vj}+a_{uj}$ 即矩阵 $A_{n\times s}$ 的第 $v$ 行乘以 $k$ 加上第 $u$ 行

**** 第二型<<MK42>>

$P_n(i,j)$ 右乘矩阵 $A_{n\times s}$ 相当于 $A\xrightarrow{\textcircled{i}\leftrightarrow\textcircled{j}}B$

$P_n(i,j)$ 左乘矩阵 $A_{s\times n}$ 相当于 $A\xrightarrow[\textcircled{i}\Leftrightarrow\textcircled{j}]{}B$

***** 证明

仅证右乘，左乘同理

根据[[MK13][定义]] $P_n(u,v)=\left[f(i,j)\right]_{n\times n}$ 其中 $f(i,j)=\begin{cases}1&(i=u\land j=v)\lor(i=v\land j=v)\\1&i\ne u\land i\ne v\land i=j\\0&else\end{cases}$

故根据[[MK5][矩阵乘法]]可得 $P_n(u,kv)A_{s\times n}=\left[t_{ij}=\sum_{k=1}^n f(i,k)a_{kj}\right]_{s\times n}$

当 $i\ne u\land i\ne v$ 时有 $t_{ij}=a_{ij}$

当 $i=u$ 时 $f(u,j)=\begin{cases}1&j=v\\0&else\end{cases}$ 故有 $t_{uj}=a_{vj}$ 同理可证当 $i=v$ 时 $t_{vj}=a_{uj}$

综上所述，右乘的结果为矩阵 $A_{n\times s}$ 得 $u,v$ 行互换

**** 第三型<<MK43>>

$P_n(ki)$ 右乘矩阵 $A_{n\times s}$ 相当于 $A\xrightarrow{k\textcircled{i}}B$

$P_n(ki)$ 左乘矩阵 $A_{s\times n}$ 相当于 $A\xrightarrow[k\textcircled{i}]{}B$

***** 证明

仅证右乘，左乘同理

根据[[MK13][定义]] $P_n(ku)=\left[f(i,j)\right]_{n\times n}$ 其中 $f(i,j)=\begin{cases}k&i=u\land j=u\\1&i=j\\0&else\end{cases}$

故根据[[MK5][矩阵乘法]]可得 $P_n(u,kv)A_{s\times n}=\left[t_{ij}=\sum_{k=1}^n f(i,k)a_{kj}\right]_{s\times n}$

当 $i\ne u$ 时右 $t_{ij}-a_{ij}$

当 $i=u$ 时  $f(u,j)=\begin{cases}k&j=u\\0&else\end{cases}$ 则有 $t_{uj}=ka_{uj}$ 即 $A_{n\times s}$ 的第 $u$ 行乘以 $k$

*** 与矩阵乘法<<MK48>>

初等矩阵 $P$ 与任意 $n$ 阶矩阵 $A$ 相乘有 $|PA|=|AP|=|P||A|$

**** 证明

***** 第一型

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK18][上三角矩阵行列式]]可得该型初等矩阵行列式 $|P|=1$

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK19][初等行变换]]以及[[MK32][初等变换]]可得 $|PA|=|AP|=|A|$

此时 $|PA|=|AP|=|P||A|=1|A|=|A|$ 成立

***** 第二型

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK13][两行互换]]可得该型初等矩阵行列式 $|P|=-1$

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK19][初等行变换]]以及[[MK32][初等变换]]可得 $|PA|=|AP|=-|A|$

此时 $|PA|=|AP|=|P||A|=-1|A|=-|A|$ 成立

***** 第三型

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK14][行乘系数]]可得该型初等矩阵行列式 $|P|=k$ 其中 $k$ 为对应的系数

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK19][初等行变换]]以及[[MK32][初等变换]]可得 $|PA|=|AP|=k|A|$

此时 $|PA|=|AP|=|P||A|=k|A|$ 成立

* 基本运算<<MK49>>

** 基本运算定义

*** 矩阵加法<<MK2>>

若 $M=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{m1}&a_{m2}&...&a_{mn}\end{matrix}\right],N=\left[\begin{matrix}b_{11}&b_{12}&...&b_{1n}\\b_{21}&b_{22}&...&b_{2n}\\...&...&...&...\\b_{m1}&b_{m2}&...&b_{mn}\end{matrix}\right]$ 

则定义 $M+N=\left[\begin{matrix}a_{11}+b_{11}&a_{12}+b_{12}&...&a_{1n}+b_{1n}\\a_{21}+b_{21}&a_{22}+b_{22}&...&a_{2n}+b_{2n}\\...&...&...&...\\a_{m1}+b_{m1}&a_{m2}+b_{m2}&...&a_{mn}+b_{mn}\end{matrix}\right]$ 

*** 矩阵数乘<<MK3>>

若 $M=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{m1}&a_{m2}&...&a_{mn}\end{matrix}\right],k\in K$ 则定义 $kM=\left[\begin{matrix}ka_{11}&ka_{12}&...&ka_{1n}\\ka_{21}&ka_{22}&...&ka_{2n}\\...&...&...&...\\ka_{m1}&ka_{m2}&...&ka_{mn}\end{matrix}\right]$

*** 矩阵乘法<<MK5>>

若 $M=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{s1}&a_{s2}&...&a_{sn}\end{matrix}\right],N=\left[\begin{matrix}b_{11}&b_{12}&...&b_{1t}\\b_{21}&b_{22}&...&b_{2t}\\...&...&...&...\\b_{n1}&b_{n2}&...&b_{nt}\end{matrix}\right]$ 

则定义 $MN=\left[t_{ij}=\sum_{k=1}^n a_{ik}b_{kj}\right]_{s\times t}$

*** 矩阵的幂

定义 $A_n$ 为 $n$ 行 $n$ 列的矩阵，则定义 $A^k_n=A_nA_n...A_n$ 即 $A$ 的 $n$ 次幂为 $n$ 个 $A_n$ [[MK5][相乘]]

若 $k=0$ 则 $A^0_n=I_n$ 为 $n$ 阶[[MK4][单位矩阵]]

*** 矩阵转置<<MK14>>

若矩阵 $A=[a_{ij}]$ 则有 $A^t=[b_{ij}=a_{ji}]$ 即行列位置交换

*** 矩阵求逆

若矩阵 $A=[a_{ij}]$ 且[[MK28][可逆]]，则 $A^{-1}_n=\frac{1}{|A_n|}\left([U_{ij}]^T_{n\times n}\right)$ 为其逆矩阵，其中 $U_{ij}$ 定义为[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org][行列式-其他定义-代数余子式]]。

** 基本运算性质

*** 加法<<MK50>>

**** 交换律

若矩阵 $A,B$ 可加，则有 $A+B=B+A$

***** 证明

易证，略

**** 结合律

若矩阵 $A,B,C$ 两两可加，则有 $(A+B)+C=A+(B+C)$ 

***** 证明

易证，略

*** 乘法<<MK51>>

**** 结合律<<MK21>>

若可乘矩阵 $A,B,C$ 则有 $(AB)C=A(BC)$

***** 证明

定义 $A=[a_{ij}]_{u\times v},B=[b_{ij}]_{v\times w},C=[c_{ij}]_{w\times x}$ 则有

（1） $AB = \left[\sum_{l=1}^v a_{il}b_{lj}\right]_{u\times w}$

（2） $BC = \left[\sum_{l=1}^v b_{il}c_{lj}\right]_{v\times x}$

故进一步有：

（1）  $(AB)C = \left[\sum_{l=1}^w \left\{\left(\sum_{k=1}^v a_{ik}b_{kl}\right) c_{lj}\right\}\right]_{u\times x}$

（2）  $A(BC) = \left[\sum_{l=1}^v\left\{a_{il}\left(\sum_{k=1}^w b_{lk}c_{kj}\right)\right\}\right]_{u\times w}$

由于

\begin{aligned}
\sum_{l=1}^w\left\{\left(\sum_{k=1}^v a_{ik}b_{kl}\right) c_{lj}\right\}&=\sum_{l=1}^w \left(\sum_{k=1}^v a_{ik}b_{kl}c_{lj}\right)\\
&=\sum_{l=1}^w \left(a_{i1}b_{1l}c_{lj}+\sum_{k=2}^v a_{ik}b_{kl}c_{lj}\right)\\
&=\sum_{l=1}^wa_{i1}b_{1l}c_{lj} + \sum_{l=1}^w \left(\sum_{k=2}^v a_{ik}b_{kl}c_{lj}\right)\\
&=a_{i1}\sum_{l=1}^wb_{1l}c_{lj} + \sum_{l=1}^w \left(\sum_{k=2}^v a_{ik}b_{kl}c_{lj}\right)\\
&=a_{i1}\sum_{l=1}^wb_{1l}c_{lj}+a_{i2}\sum_{l=1}^wb_{2l}c_{lj}+...+a_{iv}\sum_{l=1}^wb_{vl}c_{lj}\\
&=\sum_{k=1}^v\left(a_{ik}\sum_{l=1}^wb_{kl}c_{lj}\right)\\
\end{aligned}

故有 $\sum_{l=1}^w \left\{\left(\sum_{k=1}^v a_{ik}b_{kl}\right) c_{lj}\right\}=\sum_{l=1}^v\left\{a_{il}\left(\sum_{k=1}^w b_{lk}c_{kj}\right)\right\}$ 则 $(AB)C=A(BC)$

**** 分配律<<MK54>>

若可乘矩阵 $A,B,C$ 则有 $A(B+C)=AB+AC, (A+B)C=AC+BC$

***** 证明

仅证 $A(B+C)=AB+AC$ ，另一半同理可证

定义 $A=[a_{ij}]_{u\times v},B=[b_{ij}]_{v\times w},C=[c_{ij}]_{v\times w}$ 则有

（1） $B+C=[b_{ij}+c_{ij}]_{v\times w}$

（2） $AB = \left[\sum_{l=1}^v a_{il}b_{lj}\right]_{u\times w}$

（3） $AC = \left[\sum_{l=1}^v a_{il}c_{lj}\right]_{u\times w}$

则有

（1） $AB+AC=\left[\sum_{l=1}^v a_{il}b_{lj}+\sum_{l=1}^v a_{il}c_{lj}\right]_{u\times w}=\left[\sum_{l=1}^v a_{il}(b_{lj}+c_{lj})\right]_{u\times w}$

（2） $A(B+C)=\left[\sum_{l=1}^v a_{il}(b_{lj}+c_{lj})\right]_{u\times w}$

故有 $A(B+C)=AB+AC$ 

**** 单位矩阵相乘得本身

若[[MK4][单位矩阵]] $I_n$ 与矩阵 $A=[a_{ij}]_{n\times s},B=[b_{ij}]_{s\times n}$ 则有 $I_nA=A,BI_n=B$

**** 特殊可交换<<MK79>>

若 $A=aI_{n\times n}$ 其中 $a\in K$ 且 $I_{n\times n}$ 为[[MK4][单位矩阵]]，则对于任意 $B=[b_{ij}]_{n\times n}$ 有 $AB=BA$

***** 证明

定义 $AB=[c_{ij}]_{n\times n}$ 则 $c_{ij}=\sum_{k=1}^na_{ik}b_{kj}$ 由于任意 $k\ne i$ 均有 $a_{ik}=0$ 故可得 $c_{ij}=a_{ii}b_{ij}$

定义 $BA=[d_{ij}]_{n\times n}$ 则 $d_{ij}=\sum_{k=1}^nb_{ik}a_{kj}$ 由于任意 $k\ne j$ 均有 $a_{kj}=0$ 故可得 $d_{ij}=b_{ij}a_{jj}$

根据 $A$ 的定义显然有 $a_{ii}=a_{jj}$ 故可得 $c_{ij}=d_{ij}$

**** 矩阵秩的关系<<MK24>>

若矩阵 $A,B$ 可以相乘，则有 $rank(AB)\leq\min\left\{rank(A),rank(B)\right\}$ 

其中 $rank(X)$ 表示 $X$ 的[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK55][秩]]

***** 证明

定义 $A=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{s1}&a_{s2}&...&a_{sn}\end{matrix}\right]=\left[\vec{a}_1,...,\vec{a}_n\right]$ 其中 $\vec{a}_i=\left[\begin{matrix}a_{1i}\\a_{2i}\\...\\a_{si}\end{matrix}\right]$ 即矩阵 $A$ 的列向量

定义 $B=\left[\begin{matrix}b_{11}&b_{12}&...&b_{1t}\\b_{21}&b_{22}&...&b_{2t}\\...&...&...&...\\b_{n1}&b_{n2}&...&b_{nt}\end{matrix}\right]$ 则根据[[MK5][乘法定义]]可得 $AB=\left[\begin{matrix}\sum_{i=1}^n\vec{a}_ib_{i1}&\sum_{i=1}^n\vec{a}_ib_{i2}&...&\sum_{i=1}^n\vec{a}_ib_{it}\end{matrix}\right]$

则根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][向量组关系-线性表述]]， $AB$ 的列向量可由 $A$ 的列向量线性表述

故根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][向量组关系-向量组秩的性质-性质2]]可得 $AB$ 的列秩小于等于 $A$ 的列秩

进一步由于[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性空间与矩阵-一般矩阵行秩与列秩-定义]]可的 $rank(AB)\leq rank(A)$

根据[[MK7][转置性质]]可的 $(AB)^T=B^TA^T$ 则根据本性质有 $rank\left((AB)^T\right)=rank\left(B^TA^T\right)\leq rank\left(B^T\right)$

由于[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性空间与矩阵-一般矩阵行秩与列秩]]可的同一矩阵行秩等于列秩，固有 $rank(AB)=rank\left((AB)^T\right),rank(B)=rank\left(B^T\right)$

故亦有 $rank(AB)\leq rank(B)$

综上所述 $rank(AB)\leq\min\left\{rank(A),rank(B)\right\}$ 

*** 数乘<<MK25>>

若 $k\in K$ 其中 $K$ 为[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK24][数域]]， $A,B$ 为可相乘的矩阵，则有 $(kA)B=k(AB)=A(kB)$

*** 幂<<MK74>>

由定义可的

\begin{aligned}
A_n^kA_n^l&=A_n^lA_n^k=A_n^{k+l}\\
\left(A_n^k\right)^l&=A_n^{kl}
\end{aligned}

*** 转置<<MK7>>

\begin{aligned}
(A+B)^T&=A^T+B^T\\
(kA)^T&=kA^T\\
(AB)^T&=B^TA^T\\
\end{aligned}

**** 证明

仅证 $(AB)^T&=B^TA^T$ 定义 $A=[a_{ij}]_{s\times n},B=[b_{ij}]_{n\times m}$ 则有

\begin{aligned}
(AB)^T&=\left[t_{ij}=\sum_{k=1}^n a_{ik}b_{kj}\right]_{s\times m}^T\\
&=\left[u_{ij}=\sum_{k=1}^n a_{jk}b_{ki}\right]_{m\times s}
\end{aligned}

同理有

\begin{aligned}
B^TA^T&=\left[b'_{ij}=b_{ji}\right]_{m\times n}\left[a'_{ij}=a_{ji}\right]_{n\times s}\\
&=\left[u_{ij}=\sum_{k=1}^n b'_{ik}a'_{kj}=\sum_{k=1}^n b_{ki}a_{jk}\right]_{m\times s}\\
\end{aligned}

* 矩阵的逆<<MK28>>

矩阵 $A_n$ 行列数均为 $n$ ，若存在矩阵 $B$ 满足 $A_nB=BA_n=I$

则称 $A$ 为可逆矩阵 $B$ 为 $A$ 的逆矩阵，记作 $A^{-1}$ 其中 $I$ 为单位矩阵

** 性质

*** 逆矩阵为行列数相等的方阵<<MK23>>

由于 $A_n$ 行数为 $n$ 则 $A_nB$ 行数亦为 $n$ 。由于 $A_nB=I$ 为单位矩阵，根据[[MK4][定义]]行列相等，故得 $A_nB$ 列数亦为 $n$ 

根据[[MK5][矩阵乘法]]可得 $B$ 的行列数亦为 $n$

*** 逆矩阵唯一<<MK26>>

若 $A_n$ 可逆，则存在唯一逆矩阵

**** 证明

若 $AB=BA=I$ 且 $AC=CA=I$

则根据[[MK21][结合率]]可得 $(BA)C=B(AC)$ 进一步 $IC=BI$

根据[[MK23][之前证明]]可得 $A,B,C,I$ 行列数均相等，故根据[[MK22][单位矩阵性质]]可得 $C=B$

*** 可逆的充要条件<<MK29>>

方阵 $A_n$ 可逆的充要条件为 $|A_n|\ne0$

**** 证明

***** 必要

若 $A_n$ 可逆，则有 $A_nA^{-1}_n=I_n$ 根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK8][线性相关与线性无关]] $I_n$ 列向量均线性不相关

故根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK58][推论1]]可得 $rank(I_n)=n$

根据[[MK24][乘法性质]]可得 $rank(I_n)=rank(A_nA^{-1}_n)\leq rank(A_n)$ 

根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK55][秩的定义]]可得 $A_n$ 秩最大为 $n$ 即 $rank(A_n)\leq n$ 故得 $rank(A_n)=n$

根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK57][行列式与线性相关性]]可得 $|A_n|\ne0$ 时行列向量线性无关

同理根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK55][列秩与行秩的定义]]以及[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK56][一般矩阵行秩与列秩]]可得当且仅当行列向量线性无关时 $rank(A_n)=n$

综上所属若 $A_n$ 可逆，则 $rank(A_n)=n$ 则 $|A_n|\ne0$

***** 充分<<MK27>>

构建矩阵 $B=[U_{ij}]^T_{n\times n}$ ，其中 $U_{ij}$ 定义为 $A_n$ 对于元素 $a_{ij}$ 的[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK25][代数余子式]]。

根据[[MK5][矩阵乘法]]可得 $A_nB=\left[t_{ij}=\sum_{k=1}^n a_{ik}U_{jk}\right]_{n\times n}$ ，则根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK107][推论2]]可得 $t_{ij}=\begin{cases}|A_n|&i=j\\0&i\ne j\end{cases}$

则根据[[MK3][矩阵数乘]]可得 $\frac{1}{|A_n|}A_nB=I_n$ 根据[[MK25][数乘性质]]可得 $\frac{1}{|A_n|}A_nB=A_n\left(\frac{1}{|A_n|}B\right)=I_n$

类似可证 $\left(\frac{1}{|A_n|}B\right)A_n=I_n$ 且根据[[MK26][唯一性]]可得 $A^{-1}_n=\left(\frac{1}{|A_n|}B\right)$

故当 $|A_n|\ne0$ 时 $\left(\frac{1}{|A_n|}B\right)$ 存在且有定义，故 $A_n$ 可逆

** 定理

*** 定理1

若 $A_n=[a_{ij}]_{n\times n}$ 可逆，则 $A^{-1}_n=\frac{1}{|A_n|}\left([U_{ij}]^T_{n\times n}\right)$ ，其中 $U_{ij}$ 定义为 $a_{ij}$ 的[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK25][代数余子式]]

证明与[[MK27][之前]]同理。显然 $A^*=[U_{ij}]^T_{n\times n}$ 成为矩阵 $A$ 的[[MK73][伴随矩阵]]

*** 定理2<<MK31>>

若 $n$ 阶矩阵 $A_n,B_n$ 满足 $A_nB_n=I_n$ 其中 $I_n$ 是[[MK4][单位矩阵]]，则有 $A_n,B_n$ 可逆且 $A_n^{-1}=B_n,B^{-1}_n=A_n$

**** 证明

根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性相关与线性无关-定义]] $I_n$ 行、列向量均线性不相关，故根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性空间与矩阵-一般矩阵行秩与列秩-推论1]]可得 $rank(I_n)=n$

根据[[MK24][乘法性质]]可得 $rank(I_n)=rank(A_nB_n)\leq rank(A_n)$ 

根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性空间与矩阵-矩阵的秩与行列式]]可得 $A_n$ 秩最大为 $n$ 即 $rank(A_n)\leq n$ 故得 $rank(A_n)=n$

根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性空间与矩阵-行列式与线性相关性]]可得 $|A_n|\ne0$ 故根据[[MK29][充要条件]]可得 $A_n$ 可逆

即存在 $A_n^{-1}$ 满足 $A_n^{-1}A_n=A_nA_n^{-1}=I_n$ 又根据[[MK26][唯一性]]可得 $B=A_n^{-1}$

同理可证 $B_n$ 可逆且 $B^{-1}_n=A_n$

*** 定理3<<MK36>>

[[MK13][初等矩阵]]均可逆，且有：

\begin{aligned}
&P_n(i,kj)^{-1}=P_n(i,-kj)\\
&P_n(i,j)^{-1}=P_n(i,j)\\
&P_n(ki)^{-1}=P_n\left(\frac{1}{k}i\right)
\end{aligned}

**** 证明

仅证 $P_n(i,kj)^{-1}=P_n(i,-kj)$ 根据[[MK12][定义]]可得该矩阵位[[MK4][单位矩阵]]第 $i$ 行加上 $j$ 行的 $k$ 倍所得

故仅需在 $i$ 行减去 $j$ 行的 $k$ 倍即得单位矩阵。

根据[[MK30][初等变换]]可得当乘以 $P_n(i,-kj)$ 相当与该初等变换。

*** 定理4<<MK35>>

若矩阵 $S_i,i\in N\land 1\leq i\leq n$ 为 $n$ 个 $k$ 阶可逆矩阵，则有 $\prod_{i=1}^n S_i$ 可逆

且其逆矩阵位 $\prod_{i=n}^1 S^{-1}_i$ （注意：此处第一个位 $S^{-1}_n$ 依次递减）

即可逆矩阵乘法封闭

**** 证明

当 $n=2$ 时根据[[MK21][结合律]] $(S_1S_2)(S^{-1}_2S^{-1}_1)=S_1(S_2S^{-1}_2)S^{-1}_1=S_1IS^{-1}_1=I$ 根据[[MK31][定理2]]可得 $(S_1S_2)$ 可逆，且 $(S_1S_2)^{-1}=S^{-1}_2S^{-1}_1$

当 $n=k+1$ 且 $n=k$ 成立时 $\prod_{i=1}^k S_i$ 可逆且逆矩阵为 $\prod_{i=k}^1 S^{-1}_i$ 

则根据 $n=2$ 时证明 $\left(\prod_{i=k}^1 S_i\right)S_{k+1}$ 可逆，且 $\left[\left(\prod_{i=k}^1 S_i\right)S_{k+1}\right]^{-1}=S^{-1}_{k+1}\left(\prod_{i=k}^1 S^{-1}_i\right)=\left(\prod_{i=k+1}^1 S^{-1}_i\right)$

*** 定理5

若矩阵 $A_n$ 可逆，则其[[MK14][转置]]矩阵 $A^T_n$ 亦可逆，且其逆矩阵为 $\left(A^T_n\right)^{-1}=\left(A^{-1}_n\right)^T$ 

**** 证明

根据[[MK7][转置性质]]可得 $I=I^T=\left(AA^{-1}\right)^T=\left(A^{-1}\right)^TA^T$ 同理可证 $A^T\left(A^{-1}\right)^T=I$

*** 定理6<<MK35>>

若矩阵 $A_n$ 可逆，则必可经过[[MK32][初等变换]]化为[[MK4][单位矩阵]]

**** 证明

由于任意行列式可经过[[MK32][初等变换]]化为[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org][线性方程组-其他定义-阶梯矩阵]]

则根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性空间与矩阵-阶梯矩阵的行秩与列秩]]可知 $\dim(A_n)=n$ 与主元个数相等

由于 $A_n$ 为 $n$ 行列的方阵，则化为阶梯矩阵后必为[[MK33][上三角矩阵]]

故可通过初等变换：

（1）将所有主元除以自身变为 $1$

（2）从最后一行开始，依次递减消去该行主元同列的所有元素，使其为零

故得单位矩阵

*** 定理7<<MK37>>

方阵 $A_n$ 可逆的充要条件是 $A_n=\prod_{i=1}^n P_i$ 其中 $n$ 为有限数，$P_i$ 为[[MK13][初等矩阵]]

**** 证明

***** 充分

根据[[MK35][定理6]]以及[[MK32][初等变换]]可得 $A_n$ 可逆，则有 $A_n\prod_{i=1}^n P_i=I_n$ 其中 $I_n$ 位 $n$ 阶[[MK4][单位矩阵]]

根据[[MK35][定理4]]可得 $\left(\prod_{i=1}^nP_i\right)^{-1}=\prod_{i=n}^1P^{-1}_i$ 故有 $A_n=A_nI_n=A_n\prod_{i=1}^nP_i\left(\prod_{i=1}^nP_i\right)^{-1}=I_n\left(\prod_{i=1}^nP_i\right)^{-1}=I_n\prod_{i=n}^1P^{-1}_i$

故有 $A_n=\prod_{i=n}^1P^{-1}_i$ 其中 $P^{-1}_n$ 为初等矩阵的逆矩阵

根据[[MK36][定理3]]可得初等矩阵逆矩阵仍为初等矩阵，故证毕。

***** 必要

若 $A_n=\prod_{i=1}^n P_i$ 根据[[MK36][定理3]]初等矩阵可逆，根据[[MK35][定理4]]可得可逆矩阵相乘仍然可逆。

故 $A_n$ 可逆

*** 定理8<<MK46>>

定义矩阵 $A=[a_{ij}]_{s\times n}$ ，另外定义可逆矩阵 $B_s,C_n$ 分别位 $s$ 阶 $n$ 阶可逆矩阵。

则有 $\dim(A)=\dim(B_sA)=\dim(AC_n)$ 即矩阵乘以可逆矩阵，其秩不变

**** 证明

根据[[MK37][定理7]]可得 $AC_n=\prod_{i=1}^u P_i$ 其中 $P_i$ 为[[MK13][初等矩阵]]

根据[[MK32][初等变换]]可得上述乘法可定义为对矩阵 $A$ 做初等变换，

故根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性空间与矩阵-一般矩阵行秩与列秩-推论3]]可得初等变换不改变矩阵的秩。

故有 $\dim(A)=\dim(AC_n)$ 同理可证 $\dim(A)=\dim(B_sA)$

*** 定理9

若 $A_n=[a_{ij}]_{n\times n}$ 为可逆矩阵，则定义矩阵 $[A_n\ I]=[f(i,j)]_{n\times 2n}$ 其中 $f(i,j)=\begin{cases}a_{ij}&j\leq n\\1&j>n\land j=i\\0&else\end{cases}$

即矩阵的前 $n$ 行列为 $A_n$ 的元素，第 $n+1$ 列开始为[[MK4][单位矩阵]] $I$ 中的元素

则若 $A_n$ 经过一系列初等行变换 $\prod_{i=1}^z P_i$ 可得 $I$ 则有 $[A_n\ I]$ 经过同样的初等行变换可得 $[I\ A^{-1}_n]$

**** 证明

根据[[MK35][定理6]]可得 $A_n$ 可逆则必有 $\left(\prod_{i=1}^z P_i\right)A_n=I$ 则有  $\left(\prod_{i=1}^z P_i\right)I=\left(\prod_{i=1}^z P_i\right)A_nA^{-1}_n=IA^{-1}_n=A^{-1}_n$

故 $I$ 经过同样 $\prod_{i=1}^z P_i$ 的初等行变换，可得 $A^{-1}_n$

由于 $[A_n\ I]$ 矩阵中所有初等行变换同样操作与 $A_n$ 和 $I$ 上。故若初等行变换 $\prod_{i=1}^z P_i$ 能使 $A_n$ 成为 $I$ 则根据上述证明能使 $I$ 成为 $A^{-1}_n$

* 矩阵分块<<MK38>>

定义矩阵 $A=[a_{ij}]_{s\times n}$ 定义 $0=x_1\leq...\leq x_u=s$ 以及 $0=y_1\leq...\leq y_v=n$

则定义 $A_{lk}=[a'_{ij}]_{(x_{l+1}-x_l)\times(y_{k+1}-y_k)}$ 为子矩阵，其中 $a'_{ij}=a_{(x_l+i)(y_k+j)}$

故 $A$ 可分解为由子矩阵构成的 $A=[A_{ij}]_{u\times v}$ 。该过程定义位矩阵的分块

** 性质

*** 分块矩阵乘法<<MK41>>

定义矩阵 $A=[a_{ij}]_{s\times n}$ 以及 $0=x_1\leq...\leq x_u=s,0=y_1\leq...\leq y_v=n$ 以及分块后 $A=[A_{ij}]_{u\times v}$ 

其中 $A_{lk}=[a'_{ij}]_{(x_{l+1}-x_l)\times(y_{k+1}-y_k)}$ ，且 $a'_{ij}=a_{(x_l+i)(y_k+j)}$

定义矩阵 $B=[b_{ij}]_{n\times m}$ 以及 $0=y_1\leq...\leq y_v=n,0=z_1\leq...\leq z_w=m$ 以及分块后 $B=[B_{ij}]_{v\times w}$

其中 $B_{lk}=[b'_{ij}]_{(y_{l+1}-x_l)\times(z_{k+1}-y_k)}$ ，且 $b'_{ij}=b_{(y_l+i)(z_k+j)}$

则有 $AB=C$ 可根据 $0=x_1\leq...\leq x_u=s,0=z_1\leq...\leq z_w=m$ 分块，分块后 $AB=[C_{ij}]_{u\times w}$ 

且 $C_{ij}=\sum_{k=1}^vA_{ik}B_{kj}$

**** 证明 

定义 $C_{qr}=[c_{ij}]_{(x_{q+1}-x_q)\times(z_{r+1}-z_r)}$ 根据[[MK5][矩阵乘法]]可得 $c_{ij}=\sum_{k=1}^na_{(x_q+i)k}b_{k(z_r+j)}=\sum_{k=1}^v\left(\sum_{l=y_k+1}^{y_{k+1}} a_{(x_q+i)l}b_{l(z_r+j)}\right)$

同理可得 $A_{qk}B_{kr}=[d_{ij}]$ 其中 $d_{ij}=\sum_{l=y_k+1}^{y_{k+1}} a'_{il}b'_{lj}=\sum_{l=y_k+1}^{y_{k+1}} a_{(x_q+i)l}b_{l(z_r+j)}$

定义 $C'_{qr}=\sum_{k=1}^vA_{qk}B_{kr}$ 

则根据定义 $A_{qk}$ 为 $x_{q+1}-x_q$ 行 $y_{k+1}-y_k$ 列矩阵

同理可得 $B_{kr}$ 为 $y_{k+1}-y_k$ 行 $z_{r+1}-z_r$ 列矩阵

则根据矩阵乘法可得 $A_{qk}B_{kr}$ 为 $x_{q+1}-x_q$ 行 $z_{r+1}-z_r$ 列矩阵

故根据[[MK2][矩阵加法]] $C'_{qr}$ 存在，且 $C'_{qr}=[c'_{ij}]_{(x_{q+1}-x_q)\times(z_{r+1}-z_r)}$ 

进一步 $c'_{ij}=\sum_{k=1}^v\left(\sum_{l=y_k+1}^{y_{k+1}} a_{(x_q+i)l}b_{l(z_r+j)}\right)$ 即 $c'_{ij}=c_{ij}$

由于 $C'_{qr},C_{qr}$ 均为 $x_{q+1}-x_q$ 行 $z_{r+1}-z_r$ 列矩阵，且 $c'_{ij}=c_{ij}$ 固根据[[MK1][矩阵相等]]有 $C_{ij}=C'_{ij}=\sum_{k=1}^vA_{ik}B_{kj}$

*** 分块矩阵初等变换<<MK44>>

**** 初等行变换<<MK39>>

定义矩阵 $A$ ，可分块为 $A=[A_{ij}]_{s\times n}$ ，则分块矩阵初等行变换分为以下三型

***** 第一型

$A$ 的第 $k$ 分块行左乘矩阵 $P$ 后加到第 $l$ 分块行，即 $A'=[A'_{ij}]_{x\times n}$ 其中 $A'_{ij}=\begin{cases}A_{ij}+PA_{kj}&i=l\\A_{ij}&else\end{cases}$

记作 $A\xrightarrow[]{\textcircled{l}+P\textcircled{k}}A'$

***** 第二型

$A$ 的第 $k,l$ 分块行互换，即 $A'=[A'_{ij}]$ 其中 $A'_{ij}=\begin{cases}A_{kj}&i=l\\A_{lj}&i=k\\A_{ij}&else\end{cases}$

记作 $A\xrightarrow[]{\textcircled{l}\leftrightarrow\textcircled{k}}A'$

***** 第三型

A 的第 $k$ 分块行左乘以可逆矩阵 $P$ ，即 $A'= [A'_{ij}]$ 其中 $A ' _{ij}=\begin{cases}PA_{ij}&i=k\\A_{ij}&else\end{cases}$

记作 $A\xrightarrow[]{P\textcircled{k}}A'$

**** 初等列变换<<MK40>>

定义矩阵 $A$ ，可分块为 $A=[A_{ij}]_{s\times n}$ ，则分块矩阵初等列变换分为以下三型

***** 第一型

$A$ 的第 $k$ 分块列右乘矩阵 $P$ 后加到第 $l$ 分块列，即 $A'= [A'_{ij}]_{x\times n}$ 其中 $A'_{ij}=\begin{cases}A_{ij}+A_{ik}P&j=l\\A_{ij}&else\end{cases}$

记作 $A\xrightarrow[\textcircled{l}+P\textcircled{k}]{}A'$

***** 第二型

$A$ 的第 $k,l$ 分块列互换，即 $A'= [A'_{ij}]$ 其中 $A'_{ij}=\begin{cases}A_{ik}&j=l\\A_{il}&j=k\\A_{ij}&else\end{cases}$

记作 $A\xrightarrow[\textcircled{l}\leftrightarrow\textcircled{k}]{}A'$

***** 第三型

A 的第 $k$ 分块列右乘以可逆矩阵 $P$ ，即 $A'= [A'_{ij}]$ 其中 $A ' _{ij}=\begin{cases}A_{ij}P&j=k\\A_{ij}&else\end{cases}$

记作 $A\xrightarrow[\textcircled{k}P]{}A'$

*** 分块初等矩阵<<MK45>>

定义[[MK4][单位矩阵]] $I$ 经过[[MK38][分块]]后 $I=[I_{ij}]$ 其中 $I_{ij}$ 只能为[[MK4][单位矩阵]]或[[MK9][零矩阵]]。

由于子矩阵只能为单位矩阵或零矩阵，故分块行列必须相等，以保证子矩阵仅有对角上的元素为 $1$ 。

且由于根据[[MK3][矩阵乘法]]以及[[MK22][单位矩阵性质]]可得：

（1） 左（右）乘仅需行（列）数特定即可

（2） $P$ 只要可乘，则 $IP=PI=P$

综上所述，该限制不影响初等矩阵功能。

由于每个子矩阵阶可能不同，故必须分行列。

**** 行初等矩阵

分块后行初等矩阵分为以下三型：

***** 第一型

根据[[MK39][初等行变换]]的第一型，定义为 $I$ 的第 $k$ 分块行乘以矩阵 $P$ 加到第 $l$ 行

最终结果 $I'=[I'_{ij}]$ 其中 $I'_{ij}=\begin{cases}P&i=l\land j=k\\I_{ii}&i=j\\ [0] &else\end{cases}$ 其中 $I_{ii}$ 为单位矩阵

根据[[MK41][分块矩阵乘法]]以及[[MK30][之前证明]]可证该 $I'A$ 相当于[[MK39][初等行变换第一型]]

***** 第二型

根据[[MK39][初等行变换]]的第二型，定义为 $I$ 的第 $k,l$ 分块行互换

最终结果 $I'= [I'_{ij}]$ 其中 $I'_{ij}=\begin{cases}[0]&i=j=l\lor i=j=k\\I_{kk}&i=l\land j=k\\I_{ll}&i=k\land j=l\\I_{ij}&else\end{cases}$

根据[[MK41][分块矩阵乘法]]以及[[MK42][之前证明]]可证该 $I'A$ 相当于[[MK39][初等行变换第二型]]

***** 第三型

根据[[MK39][初等行变换]]的第三型，定义为 $I$ 的第 $k$ 分块行乘以可逆矩阵 $P$

最终结果 $I'= [I'_{ij}]$ 其中 $I'_{ij}=\begin{cases}P&i=j=k\\I_{ij}&else\end{cases}$

根据[[MK41][分块矩阵乘法]]以及[[MK42][之前证明]]可证该 $I'A$ 相当于[[MK39][初等行变换第三型]]

**** 列初等矩阵

分块后列初等矩阵分为以下三型：

***** 第一型

根据[[MK40][初等列变换]]的第一型，定义为 $I$ 的第 $k$ 分块列乘以矩阵 $P$ 加到第 $l$ 列

最终结果 $I'= [I'_{ij}]$ 其中 $I'_{ij}=\begin{cases}I_{ij}+P&j=l\land i=k\\I_{ij}&else\end{cases}$

根据[[MK41][分块矩阵乘法]]以及[[MK30][之前证明]]可证该 $AI'$ 相当于[[MK40][初等列变换第一型]]

***** 第二型

根据[[MK40][初等列变换]]的第二型，定义为 $I$ 的第 $k,l$ 分块列互换

最终结果 $I'= [I'_{ij}]$ 其中 $I'_{ij}=\begin{cases}[0]&i=j=l\lor i=j=k\\I_{ll}&i=l\land j=k\\I_{kk}&i=k\land j=l\\I_{ij}&else\end{cases}$

根据[[MK41][分块矩阵乘法]]以及[[MK30][之前证明]]可证该 $AI'$ 相当于[[MK40][初等列变换第二型]]

***** 第三型

根据[[MK40][初等列变换]]的第三型，定义为 $I$ 的第 $k$ 分块列乘以可逆矩阵 $P$

最终结果 $I'= [I'_{ij}]$ 其中 $I'_{ij}=\begin{cases}P&i=j=k\\I_{ij}&else\end{cases}$

根据[[MK41][分块矩阵乘法]]以及[[MK42][之前证明]]可证该 $AI'$ 相当于[[MK40][初等列变换第三型]]

** 定理

*** 定理1<<MK47>>

[[MK45][分块初等矩阵]]均可逆

**** 证明

根据[[MK4][单位矩阵]]定义可得 $I$ 为满秩，即可逆。

则根据[[MK45][分块初等矩阵]]可得，显然第一，二型不改变可逆性。

第三型由于 $P,I_{kk}$ 可逆，则根据[[MK35][定理4]]可得 $I_{kk}P=PI_{kk}=P$ 可逆。则 $\dim(P)=n$ 其中 $n=\dim(I_{kk})$ 

故根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org][线性空间与矩阵-一般矩阵行秩与列秩-推论1]]可得调整后 $I'$ 矩阵中 $P$ 分块所在的列线性不相关

且显然除去 $P$ 分块的其他列也线性不相关，故 $I'$ 所有列线性不相关，即满秩，即可逆

*** 定理2

矩阵[[MK44][分块初等变换]]不改变矩阵的秩

**** 证明

根据[[MK45][分块初等矩阵]]可得初等变换相当于乘以相应的初等矩阵。

根据[[MK47][定理1]]可知所有分块初等矩阵均可逆，则根据[[MK46][定理8]]可得矩阵乘以分块初等矩阵不改变秩。

故，矩阵的分块初等变换亦不改变秩。

* 特征值和特征向量<<MK55>>

设 $A=[a_{ij}]_{n\times n}\in M_{n\times n}(K)$ 为[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK24][数域]] $K$ 上 $n$ 阶矩阵

存在常数 $\lambda\in K$ 及不全为零 $n$ 维向量 $\vec{x}\in M_{n\times 1}(K)$ 使得 $A\vec{x}=\lambda\vec{x}$

则称 $\lambda$ 为 $A$ 的 *特征值* $\vec{x}$ 为相应的 *特征向量*

** 求解

由于 $A\vec{x}=\lambda\vec{x}$ 则根据[[MK2][矩阵加法]]，[[MK54][乘法分配率]]、[[MK21][乘法结合律]]以及[[MK22][单位矩阵性质]]

可得 $A\vec{x}=\lambda I\vec{x}\rightarrow \left(I\lambda-A\right)\vec{x}=\vec{0}\in M_{n\times 1}(K)$ 其中 $I$ 为[[MK4][单位矩阵]]

显然 $\left(I\lambda-A\right)\vec{x}=\vec{0}$ 可对应[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK28][其次线性方程组]]，由于 $\vec{x}$ 为非零向量，即有非零解

则根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK30][推论]]可得 $|I\lambda-A|=0$ 进而求解使行列式为零的 $\lambda$

** 特征多项式<<MK67>>

定义 $\lambda$ 为变量，根据 $|I\lambda-A|=0$ 又根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK11][行列式定义]]可得 $|I\lambda-A|$ 是关于 $\lambda$ 的[[~/文档/note/高等代数/Algb-4-Multi-equ.org::MK1][一元多项式]]

故可得特征值为 $|I\lambda-A|$ 在[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK24][域]] $F$ 上的所有[[~/文档/note/高等代数/Algb-4-Multi-equ.org::MK52][根]]

*** 定理1<<MK68>>

若有矩阵 $\{A,B\}\subset M_{n\times n}(K)$ 满足 $A\sim B$ [[MK64][相似]]，则有 $|I\lambda-A|=|I\lambda-B|$

即[[MK67][特征多项式]]相等

**** 证明

根据[[MK64][相似]]存在[[MK28][可逆矩阵]] $P\in M_{n\times n}(K)$ 满足 $A=P^{-1}BP$

则对于任意 $\lambda\in K$ 有 $|I\lambda-A|=|I\lambda-P^{-1}BP|$ 根据[[MK28][逆矩阵]]定义及[[MK4][单位矩阵]]可得 $I=P^{-1}P=P^{-1}IP$

则根据[[MK25][数乘]]，[[MK54][分配率]]有 $|I\lambda-A|=|P^{-1}\lambda IP-P^{-1}BP|=|P^{-1}(\lambda I- B)P|$

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK32][行列式与乘法]]可得 $|I\lambda-A|=|P^{-1}||\lambda I- B||P|=|P^{-1}||P||\lambda I- B|$

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK33][可逆矩阵与行列式]]可得 $|I\lambda-A|=|\lambda I- B|$ 根据 $\lambda$ 的任意性可得[[MK67][特征多项式]]相等

*** 定理2<<MK69>>

行列式可化为 $\left|\lambda I- A\right|=\sum_{k=0}^n\left(\sum_{i=1}^{C_n^k}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|\right)$

其中 $C_n^k$ 为 $n$ 选 $k$ 组合， $\{j_{n,i,1},...,j_{n,i,k}\}\subset\{1,...,n\}$ 为一种在 $\{1,...,n\}$ 中选 $k$ 个元素的子集

且满足 $i\ne l\rightarrow \{j_{n,i,1},...,j_{n,i,k}\}\ne\{j_{n,l,1},...,j_{n,l,k}\}$ 根据组合可得共可能有 $C_n^k$ 个 $\{j_{n,i,1},...,j_{n,i,k}\}$ 

其中 $Z_n(\{j_{n,i,1},...,j_{n,i,k}\})=[z_{ij}]_{n\times n},z_{ij}=\begin{cases}-a_{ij}&i\not\in \{j_{n,i,1},...,j_{n,i,k}\}\\0&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i\ne j\\\lambda&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i=j\end{cases}$

**** 证明

根据以下证明以及数学归纳法可证对于任意 $n<\infty$ 阶矩阵 $A$

均有 $\left|\lambda I- A\right|=\sum_{k=0}^n\left(\sum_{i=1}^{C_n^k}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|\right)$ 

***** 二阶行列式

对于二阶行列式

\begin{aligned}
\left|\begin{matrix}\lambda-a_{11}&-a_{12}\\-a_{21}&\lambda-a_{22}\end{matrix}\right|=&\left|\begin{matrix}\lambda&0\\-a_{21}&\lambda-a_{22}\end{matrix}\right|+\left|\begin{matrix}-a_{11}&-a_{12}\\-a_{21}&\lambda-a_{22}\end{matrix}\right|\\
=&\left|\begin{matrix}\lambda&0\\0&\lambda\end{matrix}\right|+\left|\begin{matrix}\lambda&0\\-a_{21}&-a_{22}\end{matrix}\right|+\left|\begin{matrix}-a_{11}&-a_{12}\\0&\lambda\end{matrix}\right|+\left|\begin{matrix}-a_{11}&-a_{12}\\-a_{21}&-a_{22}\end{matrix}\right|\\
=&\sum_{k=0}^n\left(\sum_{i=1}^{C_n^k}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|\right)
\end{aligned}

其中 $C_n^k$ 为 $n$ 选 $k$ 组合， $\{j_{n,i,1},...,j_{n,i,k}\}\subset\{1,...,n\}$ 为一种在 $\{1,...,n\}$ 中选 $k$ 个元素的子集

且满足 $i\ne l\rightarrow \{j_{n,i,1},...,j_{n,i,k}\}\ne\{j_{n,l,1},...,j_{n,l,k}\}$ 根据组合可得共可能有 $C_n^k$ 个 $\{j_{n,i,1},...,j_{n,i,k}\}$ 

其中 $Z_n(J_{n,k,i})=[z_{ij}]_{n\times n},z_{ij}=\begin{cases}-a_{ij}&i\not\in \{j_{n,i,1},...,j_{n,i,k}\}\\0&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i\ne j\\\lambda&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i=j\end{cases}$

***** 归纳假设

假设对于任意 $A\in M_{u\times u}(K),u<n$ 阶行列式有 $\left|\lambda I- A\right|=\sum_{k=0}^n\left(\sum_{i=1}^{C_n^k}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|\right)$

***** $n$ 阶行列式

对于任意 $A\in M_{n\times n}(K)$ 由于是对行拆分，则可根据归纳假设，对前 $n-1$ 行均可进行同样拆分

故可得 $\left|\lambda I- A\right|=\sum_{k=0}^{n-1}\left(\sum_{i=1}^{C_{n-1}^k}\left|Z_n(\{j_{n-1,i,1},...,j_{n-1,i,k}\})\right|\right)$

其中 $\{j_{n,i,1},...,j_{n,i,k}\}\subset\{1,...,n\}$ 为一种在 $\{1,...,n\}$ 中选 $k$ 个元素的子集

其中 $Z_n(J_{n-1,k,i})=[z_{ij}]_{n\times n},z_{ij}=\begin{cases}-a_{ij}&i\not\in \{j_{n,i,1},...,j_{n,i,k}\}\\0&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i\ne j\\\lambda&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i=j\\-a_{ij}& i=n\land j\ne n\\\lambda-a_{nn}&i=n\land j=n\end{cases}$

故对于每一个 $|Z_n(J_{n-1,k,i})|$ 均有

\begin{aligned}
|Z_n(\{j_{n-1,i,1},...,j_{n-1,i,k}\})|=&\left|\begin{matrix}z_{11}&z_{12}&...&z_{1n}\\z_{21}&z_{22}&...&z_{2n}\\...&...&...&...\\z_{(n-1)1}&z_{(n-1)2}&...&z_{(n-1)n}\\-a_{n1}&-a_{n2}&...&\lambda-a_{nn}\end{matrix}\right|\\
=&\left|\begin{matrix}z_{11}&z_{12}&...&z_{1n}\\z_{21}&z_{22}&...&z_{2n}\\...&...&...&...\\z_{(n-1)1}&z_{(n-1)2}&...&z_{(n-1)n}\\0&0&...&\lambda\end{matrix}\right|+\left|\begin{matrix}z_{11}&z_{12}&...&z_{1n}\\z_{21}&z_{22}&...&z_{2n}\\...&...&...&...\\z_{(n-1)1}&z_{(n-1)2}&...&z_{(n-1)n}\\-a_{n1}&-a_{n2}&...&-a_{nn}\end{matrix}\right|\\
=&|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})|+|Z_n(\{j_{n,i,1},...,j_{n,i,k},n\})|
\end{aligned}

故其行列式可化为

\begin{aligned}
\left|\lambda I- A\right|=&\sum_{k=0}^{n-1}\left(\sum_{i=1}^{C_{n-1}^k}\left(\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|+\left|Z_n(\{j_{n,i,1},...,j_{n,i,k},n\})\right|\right)\right)\\
=&\sum_{k=0}^{n-1}\left(\sum_{i=1}^{C_{n-1}^k}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|+\sum_{i=1}^{C_{n-1}^k}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k},n\})\right|\right)\\
\end{aligned}

根据组合 $\sum_{i=1}^{C_{n}^k}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|=\sum_{i=1}^{C_{n-1}^k}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|+\sum_{i=1}^{C_{n-1}^{k-1}}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k},n\})\right|$

即 $n$ 选 $k$ 的情况，等价于当集合不包含 $n$ 时任取 $k$ 个数和当集合包含 $n$ 时任取 $k-1$ 个数两种情况，故

\begin{aligned}
\left|\lambda I- A\right|=&\sum_{k=0}^{n-1}\left(\sum_{i=1}^{C_{n-1}^k}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|+\sum_{i=1}^{C_{n-1}^k}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k},n\})\right|\right)\\
=&\sum_{k=0}^{n-1}\left(\sum_{i=1}^{C_{n}^k}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|\right)+\sum_{i=1}^{C_{n-1}^{n-1}}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k},n\})\right|\\
=&\sum_{k=0}^{n-1}\left(\sum_{i=1}^{C_{n}^k}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|\right)+\sum_{i=1}^{C_{n}^{n}}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|\\
=&\sum_{k=0}^n\left(\sum_{i=1}^{C_n^k}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|\right)
\end{aligned}

证毕

*** 定理3<<MK71>>

$|I\lambda-A|=(-1)^n|A|+\sum_{k=1}^{n-1}\left((-1)^k\sum_{i=1}^{C_n^k}\lambda^k\overline{M}^*\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\end{matrix}\right)\right)+\lambda^n$

其中 $C_n^k$ 为 $n$ 选 $k$ 组合， $\{j_{n,i,1},...,j_{n,i,k}\}\subset\{1,...,n\}$ 为一种在 $\{1,...,n\}$ 中选 $k$ 个元素的子集

且满足 $i\ne l\rightarrow \{j_{n,i,1},...,j_{n,i,k}\}\ne\{j_{n,l,1},...,j_{n,l,k}\}$ 根据组合可得共可能有 $C_n^k$ 个 $\{j_{n,i,1},...,j_{n,i,k}\}$ 

其中 $Z_n(\{j_{n,i,1},...,j_{n,i,k}\})=[z_{ij}]_{n\times n},z_{ij}=\begin{cases}-a_{ij}&i\not\in \{j_{n,i,1},...,j_{n,i,k}\}\\0&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i\ne j\\\lambda&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i=j\end{cases}$

其中 $\overline{M}^*\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\end{matrix}\right)$ 是 $A$ 去除 $j_{n,i,1},...,j_{n,i,k}$ 行 $j_{n,i,1},...,j_{n,i,k}$ 列的[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK22][余子式]]

**** 证明

显然当 $k=0$ 时 $C_n^0=1$ 则 $\sum_{i=1}^{C_n^0}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|=\left|Z_n(\varnothing)\right|$ 即 $Z_n(\varnothing)=[-a_{ij}]$

则根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK14][行乘系数]]可得 $\sum_{i=1}^{C_n^0}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|=(-1)^n|A|$

当 $k=n$ 时 $C_n^n=1$ 则 $\sum_{i=1}^{C_n^n}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|=\left|Z_n(\{1,...,n\})\right|$

即 $Z_n(\{1,...,n\})=[z_{ij}]_{n\times n},z_{ij}=\begin{cases}0&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i\ne j\\\lambda&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i=j\end{cases}$

则根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK18][上三角矩阵行列式]]可得 $\sum_{i=1}^{C_n^n}\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|=\lambda^n$

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK26][拉普拉斯定理]]可得

\begin{aligned}
&\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|\\
=&\sum_{\forall 1\leq i_1\leq i_2\leq...\leq i_k\leq n}(-1)^{\sum_{u=1}^k i_u+\sum_{u=1}^k j_{n,i,u}}M\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\i_1&i_2&...&i_k\end{matrix}\right)\overline{M}\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\i_1&i_2&...&i_k\end{matrix}\right)
\end{aligned}

其中 $M\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\i_1&i_2&...&i_k\end{matrix}\right),\overline{M}\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\i_1&i_2&...&i_k\end{matrix}\right)$

分别为 $Z_n(\{j_{n,i,1},...,j_{n,i,k}\})$ 对于 $j_{n,i,1},...,j_{n,i,k}$ 行 $i_1,...,i_k$ 列的[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK21][子式]]和[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK22][余子式]]

根据 $Z_n(\{j_{n,i,1},...,j_{n,i,k}\})=[z_{ij}]_{n\times n},z_{ij}=\begin{cases}-a_{ij}&i\not\in \{j_{n,i,1},...,j_{n,i,k}\}\\0&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i\ne j\\\lambda&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i=j\end{cases}$

可得对于任意 $M\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\i_1&i_2&...&i_k\end{matrix}\right)=\left|[m_{ij}]\right|$ 当且仅当 $i_u=j_{n,i,u}$ 时 $m_{uu}=\lambda$ 其余均为 $0$

故和中非零[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK21][子式]]有且仅有 $M\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\end{matrix}\right)$ 且为对角矩阵的行列式，对角线上的值均为 $\lambda$

即 $M\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\end{matrix}\right)=\lambda^k$ 即进一步有

\begin{aligned}
&\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|\\
=&(-1)^{\sum_{u=1}^k j_{n,i,u}+\sum_{u=1}^k j_{n,i,u}}M\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\end{matrix}\right)\overline{M}\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\end{matrix}\right)\\
=&\lambda^k\overline{M}\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\end{matrix}\right)
\end{aligned}

又根据 $Z_n(\{j_{n,i,1},...,j_{n,i,k}\})=[z_{ij}]_{n\times n},z_{ij}=\begin{cases}-a_{ij}&i\not\in \{j_{n,i,1},...,j_{n,i,k}\}\\0&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i\ne j\\\lambda&i\in \{j_{n,i,1},...,j_{n,i,k}\}\land i=j\end{cases}$

可得 $\overline{M}\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\end{matrix}\right)=|[m_{ij}]|$ 有 $m_{ij}=-a_{ij}$ 故根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK14][行乘系数]]可得

\begin{aligned}
&\left|Z_n(\{j_{n,i,1},...,j_{n,i,k}\})\right|\\
=&\lambda^k\overline{M}\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\end{matrix}\right)\\
=&\lambda^k(-1)^k\overline{M}^*\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\end{matrix}\right)
\end{aligned}

最终根据[[MK69][定理2]]可得$|I\lambda-A|=\sum_{k=0}^n\left((-1)^k\sum_{i=1}^{C_n^k}\lambda^k\overline{M}^*\left(\begin{matrix}j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\\j_{n,i,1}&j_{n,i,2}&...&j_{n,i,k}\end{matrix}\right)\right)$

**** 推论<<MK77>>

设 $A=[a_{ij}]_{n\times n}\in M_{n\times n}(K)$ 是[[~/文档/note/抽象代数/cxds.org::MK338][域]] $\mathcal{K}=\left<K,\mathfrak{g}\right>$ 上的 $n$ 阶矩阵，

则其[[MK67][特征多项式]] $f(\lambda)$ 的最高[[~/文档/note/抽象代数/cxds.org::MK519][次]]为 $n$ 且 $\lambda^{n$ 的系数为 $\mathfrak{g}(c_1)$

***** 证明

显然根据 $f(\lambda)=|I\lambda-A|=(-1)^n|A|+\sum_{k=1}^{n-1}\left((-1)^k\sum_{i=1}^{C_n^k}\lambda^k\overline{M}^*_{ij}\right)+\lambda^n$ 可得 

*** 定理4<<MK80>>

设 $A=[a_{ij}]_{n\times n}\in M_{n\times n}(K)$ 是[[~/文档/note/抽象代数/cxds.org::MK338][域]] $\mathcal{K}=\left<K,\mathfrak{g}\right>$ 上的 $n$ 阶矩阵，定义 $f(x)=|Ix-A|$ 为 $A$ 的[[MK67][特征多项式]]

显然 $f(x)\in M_E[x]$ 是[[MK76][单位域]]上的[[~/文档/note/抽象代数/cxds.org::MK436][多项式]]，且[[MK75][方阵环]]为[[MK76][单位域]]的[[~/文档/note/抽象代数/cxds.org::MK518][扩张交换环]]

则[[~/文档/note/抽象代数/cxds.org::MK441][带入值]] $f(A)=\sum_{i=1}^nk_iA^i=[\mathfrak{g}(c_0)]_{n\times n}$

**** 证明

对于 $I\lambda-A$ 定义[[MK73][伴随矩阵]]为 $\text{adj}(I\lambda-A)=[b_{ij}]_{n\times n}$ 显然 $b_{ij}=\sum_{z=0}^{n_{ij}}k_{ij,z}\lambda^z$ 亦为 $\lambda$ 的多项式

则定义 $B_z=\left[k_{ij,z}\right]$ 则有 $\adj(I\lambda-A)=\sum_{z=0}^{\max\left(\left\{n_{ij}\big|1\leq i\leq n,1\leq j\leq n\right\}\right)}B_z\lambda^z$ ，根据[[MK78][引理]]易证 $\max\left(\left\{n_{ij}\big|1\leq i\leq n,1\leq j\leq n\right\}\right)=n-1$

根据[[MK5][矩阵乘法]]可得 $(Ix-A)\cdot\text{adj}(Ix-A)=\left[t_{ij}(x)=\sum_{k=1}^n a_{ik}(x)U_{jk}(x)\right]_{n\times n}$ ，根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK107][推论2]]可得 $t_{ij}(x)=\begin{cases}|Ix-A|&i=j\\\mathfrak{g}(c_0)&i\ne j\end{cases}$

即有 $(I\lambda-A)\cdot\text{adj}(I\lambda-A)=f(\lambda)I$ 其中 $f(\lambda)$ 为 $A$ 的[[MK67][特征多项式]]，则进一步定义 $n^*=\max(\left\{n_{ij}\big|1\leq i\leq n,1\leq j\leq n\right\})$ 则1有

\begin{aligned}
(I\lambda-A)\cdot\text{adj}(I\lambda-A)=&(I\lambda-A)\left(\sum_{z=0}^{n-1}B_z\lambda^z\right)\\
=&\sum_{z=0}^{n-1}B_z\lambda^{z+1}-\sum_{z=0}^{n-1}AB_z\lambda^z\\
=&B_{n-1}\lambda^{n}+\sum_{z=1}^{n-1}(B_{z-1}-AB_z)\lambda^z-B_0
\end{aligned}

根据[[MK77][推论]]可得 $f(\lambda)$ 最高[[~/文档/note/抽象代数/cxds.org::MK519][次]]为 $n$ 故有 $f(\lambda)=\sum_{z=0}^{n}k_z I\lambda$ 根据[[MK79][特殊可交换]]可得任意 $z$ 均有 $A^z(B_{z-1}-AB)=(B_{z-1}-AB)A^z$

则带入 $A$ 可得 $f(A)=\sum_{z=0}^nk_zA=\sum_{z=0}^nk_zIA=\left(\sum_{z=0}^nk_zA\right)I=f(A)I$ 则进一步

\begin{aligned}
f(A)=&f(A)I=B_{n-1}A^{n}+\sum_{z=1}^{n-1}(B_{z-1}-AB_z)A^z-B_0\\
=&A^{n}B_{n-1}+\sum_{z=1}^{n-1}A^z(B_{z-1}-AB_z)-B_0\\
=&A^{n}B_{n-1}+\sum_{z=1}^{n-1}(A^zB_{z-1}-A^{z+1}B_z)-B_0\\
=&A^{n}B_{n-1}+\sum_{z=1}^{n-1}A^zB_{z-1}-\sum_{z=1}^{n-1}A^{z+1}B_z-B_0\\
=&A^{n}B_{n-1}+\sum_{z=0}^{n-2}A^{z+1}B_{z}-\sum_{z=1}^{n-1}A^{z+1}B_z-B_0\\
=&\sum_{z=0}^{n-1}A^{z+1}B_{z}-\sum_{z=0}^{n-1}A^{z+1}B_z\\
=&[\mathfrak{g}(c_0)]_{n\times n}
\end{aligned}

**** 引理<<MK78>>

设 $A=[a_{ij}]_{n\times n}\in M_{n\times n}(K)$ 是[[~/文档/note/抽象代数/cxds.org::MK338][域]] $\mathcal{K}=\left<K,\mathfrak{g}\right>$ 上的 $n$ 阶矩阵，定义其[[MK73][伴随矩阵]]为 $\text{adj}(I\lambda-A)=[b_{ij}]_{n\times n}$

显然有 $b_{ij}$ 均为 $\lambda$ 的[[~/文档/note/抽象代数/cxds.org::MK436][多项式]]，则有：

（1） $b_{ii}$ 最高[[~/文档/note/抽象代数/cxds.org::MK519][次]]为 $n-1$ 且 $\lambda^{n-1}$ 的系数为 $\mathfrak{g}(c_1)$

（2） 任意 $b_{ij}$ 满足 $i\ne j$ 最高[[~/文档/note/抽象代数/cxds.org::MK519][次]]均小于 $n-1$

***** 证明

定义 $M(A,i,j)$ 为矩阵 $A$ 取出第 $i$ 行 $j$ 列的子矩阵

定义 $E(A,i,j)$ 为矩阵 $A$ 的第 $i$ 行 $j$ 列的元素

则根据以下步骤以及数学归纳法可得结论

****** $n=2$

显然当 $n=2$ 时根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK26][拉普拉斯定理]] $b_{11}=|M(A,1,1)|=\left|\lambda-a_{22}\right|=\lambda-a_{22}$ 即有 $k_1=1$

同理可证 $b_{22}$ 亦满足条件。且对于 $b_{12},b_{21}$ 显然易证最高[[~/文档/note/抽象代数/cxds.org::MK519][次]]均小于 $1$

****** 归纳假设

对于任意 $n<N$ 均有：

（1） $b_{ii}$ 最高[[~/文档/note/抽象代数/cxds.org::MK519][次]]为 $n-1$ 且 $\lambda^{n-1}$ 的系数为 $\mathfrak{g}(c_1)$

（2） 任意 $b_{ij}$ 满足 $i\ne j$ 最高[[~/文档/note/抽象代数/cxds.org::MK519][次]]均小于 $n-1$

****** $n=N$

******* 证明（1）

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK26][拉普拉斯定理]]有 $b_{ii}=|M(A,i,i)|=\sum_{z=2}^nE(M(A,i,i),1,z)\cdot\det\left(M(M(A,i,i),1,z)\right)$

当 $z=1$ 时有 $\det\left(M(M(A,i,i),1,1)\right)$ 为 $M(A,i,i)$ 的[[MK73][伴随矩阵]] $E(\text{adj}(M(A,i,i)),1,1)$

由于 $M(A,i,i)$ 为 $n-1$ 阶方阵，则根据归纳假设可得为最高[[~/文档/note/抽象代数/cxds.org::MK519][次]]为 $n-2$ 且 $\lambda^{n-2}$ 的系数为 $\mathfrak{g}(c_1)$ 的[[~/文档/note/抽象代数/cxds.org::MK436][多项式]]

由于 $E(M(A,i,i),1,1)=\begin{cases}\lambda-a_{11}&i\ne 1\\\lambda-a_{22}&i=1\end{cases}$ 故可得 $E(M(A,i,i),1,1)\cdot\det\left(M(M(A,i,i),1,1)\right)$

为最高[[~/文档/note/抽象代数/cxds.org::MK519][次]]为 $n-1$ 且 $\lambda^{n-2}$ 的系数为 $\mathfrak{g}(c_1)$ 的[[~/文档/note/抽象代数/cxds.org::MK436][多项式]]

当 $z\ne 1$ 时有 $E(M(A,i,i),1,z)=\begin{cases}\lambda-a_{1z}&i\ne 1\\\lambda-a_{2z}&i=1\end{cases}$ 由于 $M(A,i,i)$ 为 $n-1$ 阶方阵

则根据归纳假设可得 $\det\left(M(M(A,i,i),1,z)\right)$ 最高[[~/文档/note/抽象代数/cxds.org::MK519][次]]均小于 $n-2$

则显然 $E(M(A,i,i),1,z)\cdot\det\left(M(M(A,i,i),1,z)\right),z\ne1$ 为最高[[~/文档/note/抽象代数/cxds.org::MK519][次]]均小于 $n-2$ 的[[~/文档/note/抽象代数/cxds.org::MK436][多项式]]

综上所述 $b_{ii}$ 最高[[~/文档/note/抽象代数/cxds.org::MK519][次]]为 $n-1$ 且 $\lambda^{n-2}$ 的系数为 $\mathfrak{g}(c_1)$ 的[[~/文档/note/抽象代数/cxds.org::MK436][多项式]]

******* 证明（2）

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK26][拉普拉斯定理]]有 $b_{ij}=|M(A,i,j)|=\sum_{z=2}^nE(M(A,i,j),1,z)\cdot\det\left(M(M(A,i,j),1,z)\right)$

根据上一步以及归纳假设类似可证其最高[[~/文档/note/抽象代数/cxds.org::MK519][次]]均小于 $n-1$

** 性质

*** 性质1<<MK62>>

[[MK17][对称矩阵]] $A$ 有不同[[MK55][特征值]] $\lambda_1\ne\lambda_2$ 以及对应特征向量 $\vec{x}_1,\vec{x}_2$ 则 $\vec{x}_1^T\vec{x}_2=0$ 即正交

**** 证明

定义 $A\vec{x}_1=\lambda_1\vec{x}_1,A\vec{x}_2=\lambda_2\vec{x}_2$ 其中 $\lambda_1\ne\lambda_2$ 则有 $\vec{x}_2^TA\vec{x}_1=\lambda_1\vec{x}_2^T\vec{x}_1$

由于实对称矩阵 $A^T=A$ 且由于[[MK5][矩阵乘法]]以及[[MK14][转置]]有 $\vec{x}_2^TA\vec{x}_1=(A\vec{x}_2)^T\vec{x}_1=(\lambda_2\vec{x}_2)^T\vec{x}_1=\lambda_2\vec{x}_2^T\vec{x}_1$

即 $\lambda_1\vec{x}_2^T\vec{x}_1=\lambda_2\vec{x}_2^T\vec{x}_1\Rightarrow (\lambda_1-\lambda_2)\vec{x}_2^T\vec{x}_1=0$ 由于 $\lambda_1\ne\lambda_2$ 故有 $\vec{x}_2^T\vec{x}_1=0$

** 实对称矩阵

矩阵 $A$ 满足 $A\in M_{n\times n}(\mathbb{R})$ 且为[[MK17][对称矩阵]]

*** 性质

**** 性质1<<MK56>>

实对称矩阵[[MK55][特征值]]为实数

***** 证明

根据特征值定义以及[[MK14][转置]] $A\vec{x}=\lambda\vec{x}\Rightarrow (A\vec{x})^T=(\lambda\vec{x})^T\Rightarrow\vec{x}^TA^T=\vec{x}^T\lambda$

对以上等式两边取[[~/文档/note/复变函数/Cplx_fc.org::MK93][共轭]] $\overline{\vec{x}^TA^T}=\overline{\vec{x}^T\lambda}\Rightarrow \overline{\vec{x}^T}\cdot\overline{A^T}=\overline{\lambda}\cdot\overline{\vec{x}^T}\Rightarrow\overline{\vec{x}^T}\cdot\overline{A^T}\cdot\vec{x}=\overline{\lambda}\cdot\overline{\vec{x}^T}\cdot\vec{x}$

由于对称实矩阵 $A^T=A,\overline{A}=A\Rightarrow \overline{A^T}=A$ 故有 $\overline{\vec{x}^T}\cdot A\cdot\vec{x}=\overline{\vec{x}^T}\cdot \lambda\cdot\vec{x}=\overline{\lambda}\cdot\overline{\vec{x}^T}\cdot\vec{x}$

故 $\overline{\lambda}=\lambda$ 得出特征值必为实数

**** 性质2<<MK63>>

实对称矩阵[[MK55][特征向量]]亦为实数

***** 证明

由于 $(E\lambda-A)\vec{x}=0$ 根据[[MK56][性质1]] $\lambda$ 为实数，故得 $E\lambda-A$ 亦为实数矩阵

显然若存在 $\vec{x}$ 满足 $(E\lambda-A)\vec{x}=0$ 则 $\vec{x}$ 必为实数

*** 定理<<MK61>>

实对称矩阵 $A\in M_{n\times n}(\mathbb{R})$ 必存在 $n$ 个[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK8][线性无关]]的特征向量。即实对称矩阵可[[MK57][对角化]]

**** 证明

***** 实数[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK105][幂空间]]的[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK51][维度]]<<MK58>>

定义 $\mathcal{V}=<\mathbb{R},\mathbb{R},+,\times>$ 易证 $\dim(\mathcal{V})=1$ 则根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK104][定理2]]可得 $\mathcal{V}^n=<\mathbb{R}^n,\mathbb{R},+,\times>$ 的维度为 $n$      

***** 证明存在正交矩阵转换为上三角矩阵<<MK59>>

假设对于 $n-1$ 阶实对称矩阵 $B$ 存在正交矩阵 $S=[\begin{matrix}\vec{s}_2&\vec{s}_3&...&\vec{s}_n\end{matrix}]$

其中 $|\vec{s}_i|=1,\vec{s}_i\cdot\vec{s}_j=0,i\ne j$ 使得 $S^{-1} B S=S^T A_{n-1} S=\left[\begin{matrix}\lambda_2&*&...&*\\0&\lambda_3&...&*\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]$

对于 $n$ 阶矩阵 $A$ 假设其中一个特征值为 $\lambda$ 对应特征向量 $\vec{q}_1$ 其长度为 $|\vec{q}_1|=1$

以 $\vec{q}_1$ 为基准建立一组长度为 $1$ ，易证存在 $\vec{q}_2,...,\vec{q}_n$ 满足正交，即 $\vec{q}_1,\vec{q}_2,...,\vec{q}_n\Rightarrow |\vec{q}_i|=1,\vec{q}_i\cdot\vec{q}_j=0,i\ne j$

则定义 $Q=[\begin{matrix}\vec{q}_1&\vec{q}_2&...&\vec{q}_n\end{matrix}]$ 故有 $AQ=[\begin{matrix}A\vec{q}_1&A\vec{q}_2&...&A\vec{q}_n\end{matrix}]$

由于 $A\vec{q}_i\in \mathbb{R}^n$ 故本质上是[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK105][幂空间]] $\mathcal{V}^n=<\mathbb{R}^n,\mathbb{R},+,\times>$ 的元素，同理 $\vec{q}_i\in\mathbb{R}^n$ 亦为幂空间元素

由于正交，故根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK103][定理1]] $\{\vec{q}_1,...,\vec{q}_n\}$ [[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK8][线性无关]]，进一步根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK42][命题2]]可得 $\{\vec{q}_1,...,\vec{q}_n\}$ 是幂空间的[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK36][基]]

故 $A\vec{q}_i$ 必可用 $\vec{q}_i$ 的线性组合表示，即 $A\vec{q}_i=\sum_{j=1}^n b_{ij}\vec{q}_j$ ，进一步根据根据特征值定义有

\begin{aligned}
AQ&=\left[\begin{matrix}\lambda\vec{q}_1&\left[\begin{matrix}b_{21}\\b_{22}\\...\\b_{2n}\end{matrix}\right]^T\vec{q}_2&...&\left[\begin{matrix}b_{n1}\\b_{n2}\\...\\b_{nn}\end{matrix}\right]^T\vec{q}_n\end{matrix}\right]\\
&=\left[\begin{matrix}\vec{q}_1&\vec{q}_2&...&\vec{q}_n\end{matrix}\right]\left[\begin{matrix}\lambda&b_{21}&...&b_{n1}\\0&b_{22}&...&b_{n2}\\...&...&...&...\\0&b_{2n}&...&b_{nn}\end{matrix}\right]
\end{aligned}

又由于 $\{\vec{q}_1,...,\vec{q}_n\}$ [[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK8][线性无关]]，则根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK57][行列式与线性相关]]有 $|Q|\ne0$ 故根据[[MK29][可逆充要条件]]可得存在逆矩阵 $Q^{-1}$

\begin{aligned}
Q^{-1}AQ&=\left[\begin{matrix}\vec{q}_1&\vec{q}_1&...&\vec{q}_1\end{matrix}\right]^{-1}\left[\begin{matrix}\vec{q}_1&\vec{q}_1&...&\vec{q}_1\end{matrix}\right]\left[\begin{matrix}\lambda&b_{21}&...&b_{n1}\\0&b_{22}&...&b_{n2}\\...&...&...&...\\0&b_{2n}&...&b_{nn}\end{matrix}\right]\\
&=\left[\begin{matrix}\lambda&b_{21}&...&b_{n1}\\0&b_{22}&...&b_{n2}\\...&...&...&...\\0&b_{2n}&...&b_{nn}\end{matrix}\right]\\
&=\left[\begin{matrix}\lambda&\vec{b}\\\vec{0}&B\end{matrix}\right]
\end{aligned}

由于根据假设使任意 $n-1$ 阶矩阵 $B$ 存在正交阵 $S$ 使得 $S^{-1}BS$ 为上三角矩阵，则定义 $Q'=\left[\begin{matrix}1&0&...&0\\0& & & \\...& &S& \\0& & &\\\end{matrix}\right]$

则有 $(QQ')^TQQ'=Q'^TQ^TQQ'=Q'^TEQ'=E$ 故 $QQ'$ 正交矩阵且有 

\begin{aligned}
(QQ')^{-1}AQQ'&=(QQ')^TAQQ'\\
&=\left[\begin{matrix}1&\vec{0}\\\vec{0}&S\end{matrix}\right]^T \left[\begin{matrix}\lambda&\vec{b}\\\vec{0}&B\end{matrix}\right]\left[\begin{matrix}1&\vec{0}\\\vec{0}&S\end{matrix}\right]\\
&=\left[\begin{matrix}\lambda&*&...&*\\0&\lambda_2&...&*\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]
\end{aligned}

由于对于 $1$ 阶矩阵，显然成立。故根据数学归纳法，证得。

***** 证明对称矩阵必可对角化<<MK60>>

设 $A$ 为对称矩阵，根据[[MK59][上三角矩阵变换]]得，必可有正交矩阵 $P$ 使得 $H=P^{-1}AP=\left[\begin{matrix}\lambda_1&*&...&*\\0&\lambda_2&...&*\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]$

由于矩阵乘法满足结合律 $H^T=(P^{-1}AP)^T=(AP)^T(P^{-1})^T=P^TA^T(P^T)^T=P^TA^TP$

由于 $A$ 为对称矩阵，故 $H^T=P^TA^TP=P^TAP=H$ 

又因为 $H$ 是上三角矩阵，故必为对角阵，即 $H=\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]$

***** 证明对角化后对角线为特征值，正交阵向量为特征向量

根据[[MK60][可对角化]]有 $n$ 阶对称矩阵 $A$ 必然存在正交阵 $P$ 使得 $P^{-1}AP=\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]$

故根据[[MK5][矩阵乘法]]有

\begin{aligned}
&P^{-1}AP=\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]\\
\therefore&AP=P\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]\\
\therefore&A[\begin{matrix}\vec{p}_1&\vec{p}_2&...&\vec{p}_n\end{matrix}]=[\begin{matrix}\vec{p}_1&\vec{p}_1&...&\vec{p}_1\end{matrix}]\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]
\end{aligned}

故推出 $A\vec{p}_i=\lambda_i\vec{p}_i$ 所以 $\lambda_i$ 为特征值 $\vec{p}_i$ 为对应的特征向量

* 矩阵对角化<<MK57>>

对于任意 $n$ 阶矩阵 $A=[a_{ij}]_{n\times n}$ 若存在[[MK65][相似]]的[[MK70][对角矩阵]] $\Lambda=[l_{ij}],l_{ij}=\begin{cases}\lambda_{i}&i=j\\0&i\ne j\end{cases}$

即存在[[MK28][可逆矩阵]] $P=[x_{ij}]_{n\times n}$ 满足 $P^{-1}AP=\Lambda=\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]$

则称 $A$ 可对角化

** 定理

$n$ 阶矩阵 $A$ 存在[[MK28][可逆矩阵]] $P=[x_{ij}]_{n\times n}$ 满足 $P^{-1}AP=\Lambda=\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]$ ，即可[[MK57][对角化]]的充要条件是

矩阵 $A$ 存在 $n$ 个[[MK8][线性不相关]]的[[MK55][特征向量]] $\{\vec{x}_1,\vec{x}_2,...,\vec{x}_n\}$ 其中 $\vec{x}_i=\left[\begin{matrix}x_{i1}\\x_{i2}\\...\\x_{in}\end{matrix}\right]$ 且 $\lambda_i$ 是矩阵 $A$ 的[[MK55][特征值]]

*** 证明

**** 充分

若存在[[MK28][可逆矩阵]] $P=[x_{ij}]_{n\times n}$ 满足 $P^{-1}AP=\Lambda=\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]$ 则定义 $\vec{x}_i=\left[\begin{matrix}x_{i1}\\x_{i2}\\...\\x_{in}\end{matrix}\right]$

根据[[MK21][结合律]]以及[[MK22][单位矩阵性质]]可得 $P(P^{-1}AP)=P\Lambda\rightarrow AP=P\Lambda$ 则根据[[MK5][矩阵乘法]]，[[MK54][分配率]]，[[MK2][矩阵加法]]

\begin{aligned}
&AP=P\Lambda\\
\Rightarrow&\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]\left[\begin{matrix}x_{11}&x_{12}&...&x_{1n}\\x_{21}&x_{22}&...&x_{2n}\\...&...&...&...\\x_{n1}&x_{n2}&...&x_{nn}\end{matrix}\right]=\left[\begin{matrix}x_{11}&x_{12}&...&x_{1n}\\x_{21}&x_{22}&...&x_{2n}\\...&...&...&...\\x_{n1}&x_{n2}&...&x_{nn}\end{matrix}\right]\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]\\
\end{aligned}

即有 $\sum_{k=1}^na_{ik}x_{kj}=\lambda_jx_{ij}$ 故对于任意 $\vec{x}_j=\left[\begin{matrix}x_{j1}\\x_{j2}\\...\\x_{jn}\end{matrix}\right]$ 有 $A\vec{x}_j=[a'_{i}]_{n\times 1}$ 其中 $a'_{i}=\sum_{k=1}^na_{ik}x_{kj}=\lambda_jx_{ij}$

即最终有 $A\vec{x}_j=[\lambda_jx_{ij}]_{n\times 1}=\lambda_j\vec{x}_j$ 故可得 $\vec{x}_j$ 为[[MK55][特征向量]] $\lambda_i$ 为[[MK55][特征值]]

又由于 $P$ [[MK28][可逆]]，故根据[[MK29][可逆充要条件]]可得 $\{\vec{x}_1,\vec{x}_2,...,\vec{x}_n\}$ [[MK8][线性不相关]]

**** 必要

定义矩阵 $P=[x_{ij}]$ ，由于线性无关，故根据[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK57][行列式与线性相关]]可得 $|P|\ne0$ 进一步根据[[MK29][可逆充要条件]]可得存在逆矩阵 $P^{-1}$

根据[[MK5][矩阵乘法]]，[[MK54][分配率]]，[[MK2][矩阵加法]]以及 $A\vec{x}=\lambda_i\vec{x}_i$ 有

\begin{aligned}
AP=&\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]\left[\begin{matrix}x_{11}&x_{12}&...&x_{1n}\\x_{21}&x_{22}&...&x_{2n}\\...&...&...&...\\x_{n1}&x_{n2}&...&x_{nn}\end{matrix}\right]\\
=&\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]\left(\left[\begin{matrix}x_{11}&0&...&0\\x_{21}&0&...&0\\...&...&...&...\\x_{n1}&0&...&0\end{matrix}\right]+...+\left[\begin{matrix}0&0&...&x_{1n}\\0&0&...&x_{2n}\\...&...&...&...\\0&0&...&x_{nn}\end{matrix}\right]\right)\\
=&\left[\begin{matrix}\lambda_1x_{11}&0&...&0\\\lambda_1x_{21}&0&...&0\\...&...&...&...\\\lambda_1x_{n1}&0&...&0\end{matrix}\right]+...+\left[\begin{matrix}0&0&...&\lambda_nx_{1n}\\0&0&...&\lambda_nx_{2n}\\...&...&...&...\\0&0&...&\lambda_nx_{nn}\end{matrix}\right]\\
=&\left[\begin{matrix}\lambda_1x_{11}&\lambda_2x_{12}&...&\lambda_nx_{1n}\\\lambda_1x_{21}&\lambda_2a_{22}&...&\lambda_nx_{2n}\\...&...&...&...\\\lambda_1x_{n1}&\lambda_2x_{n2}&...&\lambda_nx_{nn}\end{matrix}\right]\\
=&\left[\begin{matrix}x_{11}&x_{12}&...&x_{1n}\\x_{21}&a_{22}&...&x_{2n}\\...&...&...&...\\x_{n1}&x_{n2}&...&x_{nn}\end{matrix}\right]\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]\\
=&P\Lambda
\end{aligned}

故根据[[MK21][结合律]]以及[[MK22][单位矩阵性质]]可得 $P^{-1}AP=P^{-1}(AP)=P^{-1}(P\Lambda)=P^{-1}P\Lambda=I\Lambda=\Lambda$

* 矩阵的迹<<MK65>>

对于任意 $A=[a_{ij}]\in M_{n\times n}(K)$ 为 $n$ 阶方阵，则其迹定义为 $tr(A)=\sum_{i=1}^na_{ii}$

** 性质1

任意 $\{A,B\}\subset M_{n\times n}(K)$ 有 $tr(A+B)=tr(A)+tr(B)$

*** 证明

定义 $A=[a_{ij}],B=[b_{ij}]$ ，根据[[MK2][加法定义]]可得 $A+B=[a_{ij}+b_{ij}]$ 则 $tr(A+B)=\sum_{i=1}^n(a_{ii}+b_{ii})$

显然 $tr(A)+tr(B)=\sum_{i=1}^na_{ii}+\sum_{i=1}^nb_{ii}=\sum_{i=1}^n(a_{ii}+b_{ii})$

** 性质2

任意 $A=[a_{ij}]\in M_{n\times n}(K)$ 有 $tr(kA)=ktr(A)$

*** 证明

根据[[MK3][数乘]]可得 $kA=[ka_{ij}]$ 则有 $tr(kA)=\sum_{i=1}^nka_{ii}=k\sum_{i=1}^na_{ii}=k\cdot tr(A)$

** 性质3<<MK66>>

任意 $\{A,B\}\subset M_{n\times n}(K)$ 有 $tr(AB)=tr(BA)$

*** 证明

定义 $A=[a_{ij}],B=[b_{ij}],AB=[c_{ij}]$ 则 $tr(AB)=\sum_{i=1}^nc_{ii}$

根据[[MK5][乘法]]有 $c_{ii}=\sum_{k=1}^na_{ik}b_{ki}$ 则 $tr(AB)=\sum_{i=1}^n\left(\sum_{k=1}^na_{ik}b_{ki}\right)$

易证 $tr(AB)=\sum_{k=1}^n\left(\sum_{i=1}^nb_{ki}a_{ik}\right)$ 又根据[[MK5][乘法]]易证 $tr(BA)=\sum_{k=1}^n\left(\sum_{i=1}^nb_{ki}a_{ik}\right)$ 

* 矩阵相似<<MK64>>

定义 $\{A,B\}\subset M_{n\times n}(K)$ 为 $n$ 阶方阵，若存在[[MK28][可逆]]矩阵 $P\in M_{n\times n}(K)$ 满足 $P^{-1}AP=B$

则称矩阵 $A$ 相似与矩阵 $B$ ，记作 $A\sim B$

** 定理1

矩阵相似是[[~/文档/note/离散数学/Disc_Math.org::MK176][等价关系]]

*** 证明

**** 自反性

根据[[MK28][可逆]]定义可得 $n$ 阶[[MK4][单位矩阵]]的逆矩阵为自身，进一步根据[[MK22][性质]]可得 $I^{-1}AI=IAI=AI=A$

**** 对称性

若 $A\sim B$ 则有可逆矩阵满足 $P^{-1}AP=B$ 进一步 $PP^{-1}APP^{-1}=PBP^{-1}$

根据[[MK21][结合律]]可得 $PP^{-1}APP^{-1}=IAI=A=PBP^{-1}$ 即 $PBP^{-1}=A$ 即 $B\sim A$

**** 传递性

若 $A\sim B\land B\sim C$ 则有 $P_1^{-1}AP_1=B\land P_2^{-1}BP_2=C$ 即有 $P_2^{-1}P_1^{-1}AP_1P_2=C$

定义 $P=P_1P_2$ 显然 $P^{-1}_2P^{-1}_1P_1P_2=P^{-1}_2IP_2=I$ 根据[[MK28][可逆]]定义有 $P^{-1}=P_2^{-1}P_1^{-1}$

即根据[[MK21][结合律]]有 $P^{-1}AP=C$

** 性质

*** 性质1

若矩阵 $A\sim B$ [[MK64][相似]]，则有 $|A|=|B|$ 即[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK11][行列式]]相等

（2） $rank(A)=rank(B)$ 即[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK87][秩]]相等

**** 证明

根据[[MK64][相似]]可得存在[[MK28][可逆矩阵]] $P$ 满足 $A=PBP^{-1}$ 即有 $|A|=|PBP^{-1}|$

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK32][行列式与乘法]]可得 $|A|=|P||B||P^{-1}|=|P||P^{-1}||B|$

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK33][可逆矩阵行列式]]可得 $|A|=|P|\frac{1}{|P|}|B|=|B|$

*** 性质2

若矩阵 $A\sim B$ [[MK64][相似]]，则有 $rank(A)=rank(B)$ 即[[~/文档/note/高等代数/Algb-2-Liner_Space.org::MK87][秩]]相等

**** 证明

根据[[MK64][相似]]可得存在[[MK28][可逆矩阵]] $P$ 满足 $A=PBP^{-1}$ 则有 $rank(A)=rank(PBP^{-1})$

根据[[MK46][定理8]]可得 $rank(PBP^{-1})=rank(B)$

*** 性质3

若矩阵 $A\sim B$ [[MK64][相似]]，则有 $tr(A)=tr(B)$ 即[[MK65][迹]]相等

**** 证明

根据[[MK64][相似]]可得存在[[MK28][可逆矩阵]] $P$ 满足 $A=PBP^{-1}$ 则有 $tr(A)=tr(PBP^{-1})$

根据[[MK66][性质3]]可得 $tr(PBP^{-1})=tr(PP^{-1}B)=tr(B)$

*** 性质4<<MK68>>

若有矩阵 $\{A,B\}\subset M_{n\times n}(K)$ 满足 $A\sim B$ [[MK64][相似]]，则有 $|I\lambda-A|=|I\lambda-B|$

即[[MK67][特征多项式]]相等，进而[[MK55][特征值]]相等

**** 证明

根据[[MK64][相似]]存在[[MK28][可逆矩阵]] $P\in M_{n\times n}(K)$ 满足 $A=P^{-1}BP$

则对于任意 $\lambda\in K$ 有 $|I\lambda-A|=|I\lambda-P^{-1}BP|$ 根据[[MK28][逆矩阵]]定义及[[MK4][单位矩阵]]可得 $I=P^{-1}P=P^{-1}IP$

则根据[[MK25][数乘]]，[[MK54][分配率]]有 $|I\lambda-A|=|P^{-1}\lambda IP-P^{-1}BP|=|P^{-1}(\lambda I- B)P|$

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK32][行列式与乘法]]可得 $|I\lambda-A|=|P^{-1}||\lambda I- B||P|=|P^{-1}||P||\lambda I- B|$

根据[[~/文档/note/高等代数/Algb-1-Liner_sys_func.org::MK33][可逆矩阵与行列式]]可得 $|I\lambda-A|=|\lambda I- B|$ 根据 $\lambda$ 的任意性可得[[MK67][特征多项式]]相等
