#+LATEX_CLASS: ctexart

#+TITLE: 傅里叶级数

current mark: MK9

* Cauchy-Schwarz不等式

** <<MK7>>形式1

$\left(\sum_{i=1}^n a_ib_i\right)^2\leq \sum_{i=1}^na_i^2\sum_{i=1}^nb_i^2$

*** 证明

定义函数 $f(x)=\sum_{i=1}^n(xa_i-b_i)^2$ 由于均为实数，则有 $f(x)\geq0,\forall x\in R$ 故

\begin{aligned}
\sum_{i=1}^n(xa_i-b_i)^2&=\sum_{i=1}^n(x^2a_i^2-2xa_ib_i+b_i^2)\\
&=x^2\sum_{i=1}^na_i^2-2x\sum_{i=1}^na_ib_i+\sum_{i=1}^nb_i^2\geq0
\end{aligned}

故根据二元一次函数公式有 $4\left(\sum_{i=1}^n a_ib_i\right)^2- 4\sum_{i=1}^na_i^2\sum_{i=1}^nb_i^2\leq0$

化简后得 $\left(\sum_{i=1}^n a_ib_i\right)^2\leq \sum_{i=1}^na_i^2\sum_{i=1}^nb_i^2$ 证毕。

** 形式2

若 $f(x),g(x)$ 在 $[a,b]$ 上可积，则有 $\left(\int_a^bf(x)g(x)dx\right)^2\leq\int_a^bf(x)^2dx\int_a^bf(x)^2dx$

*** 证明

根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-乘积可积]]可得 $f(x)^2,g(x)^2,f(x)g(x)$ 均在 $[a,b]$ 上可积

根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分定义]]，对于任意可积函数在任意划分与取点下，只要满足 $\lambda\to0$ 黎曼和均收敛于定积分，故有：

 $\int_a^bf(x)^2dx=\lim_{n\to\infty}\sum_{i=1}^nf(\xi_i)^2\frac{b-a}{n},\xi\in[x_i,x_{i+1}]$

 $\int_a^bg(x)^2dx=\lim_{n\to\infty}\sum_{i=1}^ng(\xi_i)^2\frac{b-a}{n},\xi\in[x_i,x_{i+1}]$

 $\int_a^bf(x)g(x)dx=\lim_{n\to\infty}\sum_{i=1}^nf(\xi_i)g(\xi_i)\frac{b-a}{n},\xi\in[x_i,x_{i+1}]$

由于根据[[MK7][形式1]]有 $\left(\sum_{i=1}^n f(\xi_i)g(\xi_i)\right)^2\leq \sum_{i=1}^nf(\xi_i)^2\sum_{i=1}^ng(\xi_i)^2$

故根据极限保号性有 $\lim_{n\to\infty}\left\{\left(\sum_{i=1}^n f(\xi_i)g(\xi_i)\right)^2\right\}\leq \lim_{n\to\infty}\left\{\sum_{i=1}^nf(\xi_i)^2\sum_{i=1}^ng(\xi_i)^2\right\}$

根据极限四则运算有 $\lim_{n\to\infty}\left\{\left(\sum_{i=1}^n f(\xi_i)g(\xi_i)\right)^2\right\}=\lim_{n\to\infty}\left(\sum_{i=1}^n f(\xi_i)g(\xi_i)\right)\lim_{n\to\infty}\left(\sum_{i=1}^n f(\xi_i)g(\xi_i)\right)=\int_a^bf(x)g(x)dx\int_a^bf(x)g(x)dx$

同理有 $\lim_{n\to\infty}\left\{\sum_{i=1}^nf(\xi_i)^2\sum_{i=1}^ng(\xi_i)^2\right\}=\lim_{n\to\infty}\left\{\sum_{i=1}^nf(\xi_i)^2\right\}\lim_{n\to\infty}\left\{\sum_{i=1}^ng(\xi_i)^2\right\}=\int_a^bf(x)^2dx\int_a^bf(x)^2dx$

故综上所述 $\left(\int_a^bf(x)g(x)dx\right)^2\leq\int_a^bf(x)^2dx\int_a^bf(x)^2dx$ 

同理对于反常积分，若 $b$ 为奇点则同根据极限的极限四则运算有 

$\left(\lim_{B\to b}\int_a^Bf(x)g(x)dx\right)^2=\lim_{B\to b}\int_a^Bf(x)g(x)dx\lim_{B\to b}\int_a^Bf(x)g(x)dx=\lim_{B\to b}\left(\int_a^Bf(x)g(x)dx\right)^2$

$\lim_{B\to b}\int_a^Bf(x)^2dx\lim_{B\to b}\int_a^Bf(x)^2dx=\lim_{B\to b}\left(\int_a^Bf(x)^2dx\int_a^Bf(x)^2dx\right)$

同理根据极限保号性有 $\lim_{B\to b}\left(\int_a^Bf(x)g(x)dx\right)^2\leq \lim_{B\to b}\left(\int_a^Bf(x)^2dx\int_a^Bf(x)^2dx\right)$

即 $\left(\lim_{B\to b}\int_a^Bf(x)g(x)dx\right)^2\leq \lim_{B\to b}\int_a^Bf(x)^2dx\lim_{B\to b}\int_a^Bf(x)^2dx$ 故反常积分下同样成立

* 傅里叶级数展开

** 周期为 $2\pi$ 函数的傅里叶展开

函数 $f(x),x\in[-\pi,\pi]$ 则他的傅里叶展开为 $\frac{a_0}{2}+\sum_{i=1}^\infty\left(a_i\cos(ix)+b_i\sin(ix)\right)$

其中 $\begin{cases}a_i=\frac{1}{\pi}\int_{-\pi}^\pi f(x)\cos(ix)dx\\b_i=\frac{1}{\pi}\int_{-\pi}^\pi f(x)\sin(ix)dx\end{cases}$

*** 推导

假设 $f(x)$ 可以写为 $\frac{a_0}{2}+\sum_{i=1}^\infty\left(a_i\cos(ix)+b_i\sin(ix)\right)$ 的形式，且级数一致连续

则根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分几何应用-三角函数正交性]]及[[e:/OneDrive/数学分析/Note/Chapter 10/Chap10Note.org][函数项级数-一致收敛性质-可积性]]有

\begin{aligned}
\int_{-\pi}^\pi f(x)\cos(nx)dx=&\int_{-\pi}^\pi\left\{\frac{a_0}{2}\cos(nx)+\cos(nx)\sum_{i=1}^\infty\left(a_i\cos(ix)+b_i\sin(ix)\right)\right\}dx\\
=&\int_{-\pi}^\pi\frac{a_0}{2}\cos(nx)dx+\sum_{i=1}^\infty\left(a_i\int_{-\pi}^\pi\cos(ix)\cos(nx)dx\right)+\sum_{i=1}^\infty\left(b_i\int_{-\pi}^\pi\sin(ix)\cos(nx)dx\right)\\
=&\frac{a_0}{2}\int_{-\pi}^\pi\cos(nx)dx+\sum_{i=1}^\infty\left(a_i\int_{-\pi}^\pi\cos(ix)\cos(nx)dx\right)
\end{aligned}

若 $n=0$ 则 $cos(0\pi)=1\Rightarrow\begin{cases}\int_{-\pi}^\pi\cos(ix)\cdot1dx=0&i=1,2,...\\\int_{-\pi}^\pi1dx=2\pi\end{cases}$ 故有 $a_0=\frac{1}{\pi}\int_{-\pi}^\pi f(x)\cos(ix)dx$

若 $n>0$ 则 $\begin{cases}\int_{-\pi}^\pi\cos(ix)\cos(nx)dx=0&i\ne n\\\int_{-\pi}^\pi\cos(ix)\cos(nx)dx=\pi&i=n\end{cases}$ 故有 $a_0=\frac{1}{\pi}\int_{-\pi}^\pi f(x)\cos(ix)dx$

又因为 $\sin(0x)=0\Rightarrow\int_{\pi}^{\pi}f(x)\sin(0x)dx=0$ 故同理可推出 $b_i=\frac{1}{\pi}\int_{-\pi}^\pi f(x)\sin(ix)dx$

** 正弦级数和余弦级数

* 傅里叶级数的收敛判别

** <<MK1>>引理1

$\forall 0\leq a<b<\infty,\exists 0<K<\infty\Rightarrow\left|\int_a^b\frac{\sin(x)}{x}dx\right|<K$

*** 证明

**** 证明反常积分在 $(0,\infty)$ 收敛

根据积分[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-区间可加]] $\int_0^\infty\frac{\sin(x)}{x}dx=\int_0^{\frac{\pi}{2}}\frac{\sin(x)}{x}dx+\int_{\frac{\pi}{2}}^\infty\frac{\sin(x)}{x}dx$

分别为区间无限及无界反常积分由于 $\int_a^b\sin(x)dx$ 有界，对于任意 $0\leq a<b<\infty$ 且 $\lim_{x\to\infty}\frac{1}{x}=0$ 且 $\frac{1}{x}$ 单调

故根据[[e:/OneDrive/数学分析/Note/Chapter 8/Chap8Note.org][区间无限反常积分收敛判别-一般函数（不定号）反常积分判别法-Dirichlet]] $\int_{\frac{\pi}{2}}^\infty\frac{\sin(x)}{x}dx$ 收敛

又因为 $\frac{\sin(x)}{x}<1$ 且有 $\lim_{a\to0}\int_a^\frac{\pi}{2}1dx=\frac{\pi}{2}$ 收敛，故根据[[e:/OneDrive/数学分析/Note/Chapter 8/Chap8Note.org][无界函数反常积分收敛判别-非负反常积分判别]] $\int_0^{\frac{\pi}{2}}\frac{\sin(x)}{x}dx$ 亦收敛

故 $\int_0^\infty\frac{\sin(x)}{x}dx$ 收敛

**** 根据周期证明

由于 $\sin(x)$ 为周期函数，当 $x\in[2i\pi,(2i+1)\pi],i\in N^+$ 时 $\sin(x)\geq0$ 当 $x\in[(2i+1)\pi,(2i+2)\pi],i\in N^+$ 时 $\sin(x)\leq0$ 

故定义 $u_i=\int_{2i\pi}^{(2i+2)\pi}\frac{\sin(x)}{x}dx$ 则有 $\sum_{i=0}^nu_i=\sum_{i=1}^n\left\{\int_{2i\pi}^{(2i+1)\pi}\frac{\sin(x)}{x}dx+\int_{(2i+1)\pi}^{(2i+2)\pi}\frac{\sin(x)}{x}dx\right\}=\sum_{i=1}^n\int_{2i\pi}^{(2i+1)\pi}\left(\frac{\sin(x)}{x}+\frac{\sin(x+\pi)}{x+\pi}\right)dx$ 其中 $\frac{\sin(x)}{x}\geq0,\frac{\sin(x+\pi)}{x+\pi}\leq0$

且有 $\sin(x)=-\sin(x+\pi)$ 故 $\frac{\sin(x)}{x}+\frac{\sin(x+\pi)}{x+\pi}>0$ 根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-保序]]可得 $\int_{2i\pi}^{(2i+1)\pi}\left(\frac{\sin(x)}{x}+\frac{\sin(x+\pi)}{x+\pi}\right)dx\geq0$

同理有 $\int_0^\pi\frac{\sin(x)}{x}dx\geq\left|\int_{i\pi}^{(i+1)\pi}\frac{\sin(x)}{x}dx\right|$ 且根据之前证明 $\int_0^\pi\frac{\sin(x)}{x}dx$ 收敛，故定义 $L=\int_0^\pi\frac{\sin(x)}{x}dx$

即 $u_i>0$ 由于 $\sum_{i=1}^n u_n=\int_0^{(2n+2)\pi}\frac{\sin(x)}{x}dx$ 故有 $\lim_{n\to\infty}\sum_{i=0}^nu_n=\frac{\pi}{2}$ 故有 $0\leq\sum_{i=k}^n u_i\leq\frac{\pi}{2}$

**** 证明结论

将区间 $[a,b]$ 划分成 $[a,2n\pi]\cup[2n\pi,2m\pi]\cup[2m\pi,b]$ 其中 $2n\pi-a<2\pi,b-2m\pi<2\pi$ 且 $n\in N^+,m\in N^+,m\geq n$ 则有 

\begin{aligned}
\left|\int_a^b\frac{\sin(x)}{x}dx\right|=&\left|\int_a^{2n\pi}\frac{\sin(x)}{x}dx+\int_{2n\pi}^{2m\pi}\frac{\sin(x)}{x}dx+\int_{2m\pi}^b\frac{\sin(x)}{x}dx\right|\\
\leq&\left|\int_a^{2n\pi}\frac{\sin(x)}{x}dx\right|+\left|\int_{2n\pi}^{2m\pi}\frac{\sin(x)}{x}dx\right|+\left|\int_{2m\pi}^b\frac{\sin(x)}{x}dx\right|\\
\leq&\left|\int_a^{2n\pi}\frac{\sin(x)}{x}dx\right|+\left|\int_{2m\pi}^b\frac{\sin(x)}{x}dx\right|+\frac{\pi}{2}\\
=&\left|\int_a^{(2n-1)\pi}\frac{\sin(x)}{x}dx+\int_{(2n-1)\pi}^{2n\pi}\frac{\sin(x)}{x}dx\right|+\left|\int_{2m\pi}^{(2m+1)\pi}\frac{\sin(x)}{x}dx+\int_{(2m+1)\pi}^b\frac{\sin(x)}{x}dx\right|+\frac{\pi}{2}\\
\leq&\left|\int_a^{(2n-1)\pi}\frac{\sin(x)}{x}dx\right|+\left|\int_{(2n-1)\pi}^{2n\pi}\frac{\sin(x)}{x}dx\right|+\left|\int_{2m\pi}^{(2m+1)\pi}\frac{\sin(x)}{x}dx\right|+\left|\int_{(2m+1)\pi}^b\frac{\sin(x)}{x}dx\right|+\frac{\pi}{2}\\
\leq&\left|\int_a^{(2n-1)\pi}\frac{\sin(x)}{x}dx\right|+\left|\int_{(2m+1)\pi}^b\frac{\sin(x)}{x}dx\right|+2L+\frac{\pi}{2}\\
\end{aligned}

且由于 $2n\pi-a<2\pi\Rightarrow(2n-1)\pi-a<\pi$ 且当 $x\in[(2n-2)\pi,(2n-1)\pi]$ 时函数 $\frac{\sin(x)}{x}$ 同号

故有 $\left|\int_a^{(2n-1)\pi}\frac{\sin(x)}{x}dx\right|<\left|\int_{(2n-2)\pi}^{(2n-1)\pi}\frac{\sin(x)}{x}dx\right|<L$ 同理 $\left|\int_{(2m+1)\pi}^b\frac{\sin(x)}{x}dx\right|<\left|\int_{(2m+1)\pi}^{(2m+2)\pi}\frac{\sin(x)}{x}dx\right|<L$

则有 $\left|\int_a^b\frac{\sin(x)}{x}dx\right|<4L+\frac{\pi}{2}$ 证毕。

** <<MK2>>黎曼引理

设函数 $\phi(x)$ 在 $[a,b]$ 上可积或反常积分绝对可积，则有 $\lim_{p\to\infty}\int_a^b\phi(x)\sin(px)dx=\lim_{p\to\infty}\int_a^b\phi(x)\cos(px)dx=0$

*** 证明

**** <<MK1>>可积情况下

由于可积，则根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定积分可积充要条件2]]有 $\forall\epsilon>0,\exists\delta,\forall\lambda<\delta,\forall P\Rightarrow\left|\sum_{i=1}^\infty\omega_i\Delta x_i\right|<\frac{\epsilon}{2}$

且根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-乘积可积]]得 $\phi(x)\sin(px)$ 亦可积

其中 $P:a=x_1<x_2<...<x_n=b$ 为黎曼和划分 $\Delta x_i=x_i-x_{i-1},\omega_i=sup(x)-inf(x),x\in[x_{i-1},x_i]$

且定义 $m_i=inf(x),x\in[x_{i-1},x_i]$ ，并取一种满足上述条件的划分 $P$

则根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-线性]]，[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-绝对可积]]，[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-乘积可积]]以及[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-区间可加]]可得

\begin{aligned}
\left|\int_a^b\phi(x)\sin(px)dx\right|=&\left|\sum_{i=1}^n\int_{x_{i-1}}^{x_i}\phi(x)\sin(px)dx-\sum_{i=1}^n\int_{x_{i-1}}^{x_i}m_i\sin(px)dx+\sum_{i=1}^n\int_{x_{i-1}}^{x_i}m_i\sin(px)dx\right|\\
\leq&\left|\sum_{i=1}^n\int_{x_{i-1}}^{x_i}\left[\phi(x)-m_i\right]\sin(px)dx\right|+\left|\sum_{i=1}^n\int_{x_{i-1}}^{x_i}m_i\sin(px)dx\right|\\
\leq&\sum_{i=1}^n\left|\int_{x_{i-1}}^{x_i}\left[\phi(x)-m_i\right]\sin(px)dx\right|+\sum_{i=1}^n\left|\int_{x_{i-1}}^{x_i}m_i\sin(px)dx\right|\\
\leq&\sum_{i=1}^n\int_{x_{i-1}}^{x_i}|\phi(x)-m_i||\sin(px)|dx+\sum_{i=1}^n\left|\frac{1}{p}\int_{px_{i-1}}^{px_i}m_i\sin(u)du\right|\\
\leq&\sum_{i=1}^n\int_{x_{i-1}}^{x_i}\omega_idx+\frac{1}{p}\sum_{i=1}^n\left|\int_{px_{i-1}}^{px_i}m_i\sin(u)du\right|\\
=&\sum_{i=1}^n\omega_i\Delta x_i+\frac{1}{p}\sum_{i=1}^n\left|\int_{px_{i-1}}^{px_i}m_i\sin(u)du\right|\\
\end{aligned}

由于划分已确定，函数 $\sin(u)$ 在有界区域内可积，故取 $P=\frac{2}{\epsilon}\sum_{i=1}^n\left|\int_{px_{i-1}}^{px_i}m_i\sin(u)du\right|$ 则当 $p>P$ 时有
\begin{aligned}
\left|\int_a^b\phi(x)\sin(px)dx\right|\leq&\sum_{i=1}^n\omega_i\Delta x_i+\frac{1}{p}\sum_{i=1}^n\left|\int_{px_{i-1}}^{px_i}m_i\sin(u)du\right|\\
<&\frac{\epsilon}{2}+\frac{\epsilon}{2}\\
=\epsilon
\end{aligned}

同理可证 $\left|\int_a^b\phi(x)\cos(px)dx\right|<\epsilon$ 证毕。

**** 反常积分绝对可积

定义 $b$ 为奇点，则根据条件有 $\int_a^b|\phi(x)|dx$ 存在，根据[[e:/OneDrive/数学分析/Note/Chapter 8/Chap8Note.org][无界函数反常积分收敛判别-定义]] $\forall\epsilon>0,\exists\delta>0,\forall\eta<\delta\Rightarrow\int_{b-\eta}^b|\phi(x)|dx<\frac{\epsilon}{2}$

且根据[[MK1][可积条件下证明]]有 $\lim_{p\to\infty}\int_a^{b-\eta}\phi(x)\sin(px)dx=0$ 故 $\forall\epsilon>0,\eixsts P,\forall p>P\Rightarrow\left|\int_a^{b-\eta}\phi(x)\sin(px)dx\right|<\frac{\epsilon}{2}$

故根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-绝对可积]]以及根据[[e:/OneDrive/数学分析/Note/Chapter 8/Chap8Note.org][无界函数反常积分收敛判别-反常积分绝对收敛]]得

\begin{aligned}
\left|\int_a^b\phi(x)\sin(px)dx\right|=&\left|\int_a^{b-\eta}\phi(x)\sin(px)dx+\int_a^b\phi(x)\sin(px)dx\right|\\
\leq&\left|\int_a^{b-\eta}\phi(x)\sin(px)dx\right|+\left|\int_a^b\phi(x)\sin(px)dx\right|\\
\leq&\left|\int_a^{b-\eta}\phi(x)\sin(px)dx\right|+\int_a^b|\phi(x)||\sin(px)|dx\\
\leq&\left|\int_a^{b-\eta}\phi(x)\sin(px)dx\right|+\int_a^b|\phi(x)|dx\\
<&\frac{\epsilon}{2}+\frac{\epsilon}{2}\\
\end{aligned}

同理可证 $\left|\int_a^b\phi(x)\cos(px)dx\right|<\epsilon$ 证毕。

*** <<MK4>>推论

$\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{\phi(u)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du=\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{\phi(u)}{u}\sin\left(\frac{2m+1}{2}u\right)\right\}du$

**** 证明

定义 $g(u)=\begin{cases}\frac{1}{2\sin\left(\frac{u}{2}\right)}-\frac{1}{u}&u>0\\0&u=0\end{cases}$ 由于 $\lim_{u\to0}\frac{u}{2\sin\left(\frac{u}{2}\right)}=1\Rightarrow\lim_{u\to0}g(u)=0$ 故 $g(u)$ 连续

故根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定积分可积充要条件2-推论1]]得出 $g(u)$ 在 $[0,\pi]$ 上可积

故根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-乘积可积]]有 $g(u)\phi(u)$ 在 $u\in[0,\delta]$ 上亦可积或绝对可积 则有

\begin{aligned}
&\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{\phi(u)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du-\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{\phi(u)}{u}\sin\left(\frac{2m+1}{2}u\right)\right\}du\\
=&\lim_{m\to\infty}\left\{\int_{0}^{\delta}\left\{\frac{\phi(u)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du-\int_{0}^{\delta}\left\{\frac{\phi(u)}{u}\sin\left(\frac{2m+1}{2}u\right)\right\}du\right\}\\
=&\lim_{m\to\infty}\left\{\int_{0}^{\delta}\left\{\phi(u)\left(\frac{1}{2\sin\left(\frac{u}{2}\right)}-\frac{1}{u}\right)\sin\left(\frac{2m+1}{2}u\right)\right\}du\right\}\\
=&\lim_{m\to\infty}\left\{\int_{0}^{\delta}\left\{\phi(u)g(u)\sin\left(\frac{2m+1}{2}u\right)\right\}du\right\}\\
\end{aligned}

根据[[MK2][黎曼引理]]得 $\lim_{m\to\infty}\left\{\int_{0}^{\delta}\left\{\phi(u)g(u)\sin\left(\frac{2m+1}{2}u\right)\right\}du\right\}=0$ 证毕

** <<MK5>>Dirichlet引理

若函数 $\phi(u)$ 在 $[0,\delta]$ 上单调，则有 $\lim_{p\to\infty}\int_0^\delta\frac{\phi(u)-\phi(0^+)}{u}\sin(pu)du=0$

其中 $\phi(0^+)=\lim_{u\to0^+}\phi(u)$

*** 证明

**** 拆分积分

根据[[MK1][引理1]]存在一个常数 $K$ 有对于任意 $0\leq a<b\leq\infty$ 均有 $\left|\int_a^b\frac{\sin(x)}{x}dx\right|<K$ 其中 $K$ 为常数

假设 $\phi(u)$ 单调增加，由于 $\phi(0^+)=\lim_{u\to0^+}\phi(u)$ 则有 $\forall\epsilon>0,\exists\eta>0,\forall u<\eta\Rightarrow\phi(u)-\phi(0^+)<\frac{\epsilon}{K+1}$

将积分分为两部分 $\left|\int_0^\delta\frac{\phi(u)-\phi(0^+)}{u}\sin(pu)du\right|\leq\left|\int_0^\eta\frac{\phi(u)-\phi(0^+)}{u}\sin(pu)du\right|+\left|\int_\eta^\delta\frac{\phi(u)-\phi(0^+)}{u}\sin(pu)du\right|$

**** 第二部分

由于 $\phi(u)$ 单调，则 $\phi(u)-\phi(0^+)$ 亦单调，根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定积分可积充要条件2-推论2]]得出可积

由于 $\frac{1}{u}$ 在 $[\eta,\delta]$ 上亦可积，则根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-乘积可积]] $\frac{\phi(u)-\phi(0^+)}{u}$ 可积

故根据[[MK2][黎曼引理]]得 $\lim_{p\to\infty}\int_\eta^\delta\frac{\phi(u)-\phi(0^+)}{u}\sin(pu)du=0$ 即 $\forall\epsilon>0\exists P,\forall p>P\Rightarrow\left|\int_\eta^\delta\frac{\phi(u)-\phi(0^+)}{u}\sin(pu)du\right|<\frac{\epsilon}{K+1}$

**** 第一部分

由于 $\left|\int_0^\eta\frac{\phi(u)-\phi(0^+)}{u}\sin(pu)du\right|$ 为反常积分，故定义当 $u=0$ 时 $\frac{\sin(pu)}{u}=1$

则有 $\left|\int_0^\eta[\phi(u)-\phi(0^+)]\frac{\sin(pu)}{u}du\right|$ 为积分区间在 $[0,\eta]$ 上的常义积分

同理定义积分区间在 $(0,\eta]$ 的反常积分，可以理解为积分区域在 $[0,\eta]$ 但当 $u=0$ 时函数值为 $0$ 的积分

故根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-线性-推论]]有在 $(0,\eta]$ 上的反常积分等于在 $[0,\eta]$ 上的常义积分

故有 $\left|\int_0^\eta[\phi(u)-\phi(0^+)]\frac{\sin(pu)}{u}du\right|=\lim_{a\to0}\left|\int_a^\eta[\phi(u)-\phi(0^+)]\frac{\sin(pu)}{u}du\right|$ 左边为常义积分，右边为反常积分

由于 $\phi(u)-\phi(0^+)$ 单调 $\frac{\sin(pu)}{u}$ 在 $[0,\eta]$ 上连续，则根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定积分可积充要条件2-推论1]]得必可积

故根据[[e:/OneDrive/数学分析/Note/Chapter 8/Chap8Note.org][积分中值定理-第二积分中值定理]]得

\begin{aligned}
\left|\int_0^\eta[\phi(u)-\phi(0^+)]\frac{\sin(pu)}{u}du\right|=&\left|(\phi(0^+)-\phi(0^+))\int_a^{\xi}\frac{\sin(pu)}{u}du+(\phi(\eta^-)-\phi(0^+))\int_\xi^{\eta}\frac{\sin(pu)}{u}du\right|&\xi\in[0,\eta]\\
=&\left|(\phi(\eta)-\phi(0^+))\int_\xi^{\eta}\frac{\sin(pu)}{u}du\right|&\xi\in[a,\eta]\\
<&\frac{\epsilon}{K+1}\left|\int_\xi^{\eta}\frac{\sin(pu)}{u}du\right|&\xi\in[a,\eta]\\
\end{aligned}

根据[[MK1][引理1]]存在一个常数 $K$ 有对于任意 $0\leq a<b\leq\infty$ （ $a=0$ 或 $b=\infty$ 时为反常积分 ）

均有 $\left|\int_a^b\frac{\sin(x)}{x}dx\right|<K$ 故 $\left|\int_a^\eta\frac{\phi(u)-\phi(0^+)}{u}\sin(pu)du\right|<\frac{K\epsilon}{K+1}$

**** 结论

结合第一第二部分，对于任意 $\epsilon>0$ 存在 $P$ 对于任意 $p>P$ 可得 $\left|\int_0^\delta\frac{\phi(u)-\phi(0^+)}{u}\sin(pu)du\right|<\frac{K\epsilon}{K+1}+\frac{\epsilon}{K+1}=\epsilon$ 其中 $K$ 为固定常数，与 $p$ 取值无关

故得 $\lim_{p\to\infty}\int_0^\delta\frac{\phi(u)-\phi(0^+)}{u}\sin(pu)du=0$

** <<MK6>>收敛判别

设函数 $f(x)$ 在 $[-\pi,\pi]$ 上常义积分可积或反常积分绝对可积，且满足下列条件之一：

（1） （Dirichlet-Jordan判别） $f(x)$ 在 $x$ 点的某个领域 $O(x,\delta)$ 是分段单调有界函数

（2） （Dini-Lipschitz） $f(x)$ 在点 $x$ 处满足指数为 $a\in(0,1]$ 的 Holden 条件

则有傅里叶级数收敛于周期拓展的 $\frac{f(x^+)+f(x^-)}{2}$ 其中 $f(x^+)=\lim_{u\to0^+}f(x+u),f(x^-)=\lim_{u\to0^+}f(x-u)$

*** 证明

**** 转化为Dirichlet积分

函数 $f(x)$ 的傅里叶级数为 $\frac{a_0}{2}+\sum_{i=1}^\infty\left(a_i\cos(ix)+b_i\sin(ix)\right)$ 故定义 $S_m(x)=\frac{a_0}{2}+\sum_{i=1}^m\left(a_i\cos(ix)+b_i\sin(ix)\right)$ 为级数的部分和

则根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-线性]]，三角函数和差化积

\begin{aligned}
S_m(x)=&\frac{a_0}{2}+\sum_{i=1}^m\left(a_i\cos(ix)+b_i\sin(ix)\right)\\
=&\frac{1}{\pi}\left\{\frac{1}{2}\int_{-\pi}^\pi f(t)dt+\sum_{i=1}^m\left(\int_{-\pi}^\pi f(t)\cos(it)dt\cos(ix)+\int_{-\pi}^\pi f(t)\sin(it)dt\sin(ix)\right)\right\}\\
=&\frac{1}{\pi}\int_{-\pi}^\pi\left\{f(t)\left[\frac{1}{2}+\sum_{i=1}^m\left(\cos(it)\cos(ix)+\sin(it)\sin(ix)\right)\right]\right\}dt\\
=&\frac{1}{\pi}\int_{-\pi}^\pi\left\{f(t)\left[\frac{1}{2}+\sum_{i=1}^m\cos(i(t-x))\right]\right\}dt\\
\end{aligned}

由于根据积化和差共识有：

\begin{aligned}
&\sin\left(\frac{\theta}{2}\right)+2\sin\left(\frac{\theta}{2}\right)\sum_{i=1}^m\cos(i\theta)\\
=&\sin\left(\frac{\theta}{2}\right)+2\sin\left(\frac{\theta}{2}\right)\cos(\theta)+2\sin\left(\frac{\theta}{2}\right)\cos(2\theta)+...+2\sin\left(\frac{\theta}{2}\right)\cos(m\theta)\\
=&\sin\left(\frac{\theta}{2}\right)+\left[\sin\left(\theta+\frac{\theta}{2}\right)-\sin\left(\theta-\frac{\theta}{2}\right)\right]+\left[\sin\left(2\theta+\frac{\theta}{2}\right)-\sin\left(2\theta-\frac{\theta}{2}\right)\right]+...+\left[\sin\left(m\theta+\frac{\theta}{2}\right)-\sin\left(m\theta-\frac{\theta}{2}\right)\right]\\
=&\sin\left(m\theta+\frac{\theta}{2}\right)\\
\end{aligned}

故有 $\sin\left(\frac{\theta}{2}\right)+2\sin\left(\frac{\theta}{2}\right)\sum_{i=1}^m\cos(i\theta)=\sin\left(\frac{2m+1}{2}\theta\right)\Rightarrow\frac{1}{2}+\sum_{i=1}^m\cos(i\theta)=\frac{\sin\left(\frac{2m+1}{2}\theta\right)}{2\sin\left(\frac{\theta}{2}\right)}$ 

定义 $\sin\left(\frac{\theta}{2}\right)=0$ 时等式右边为 $\lim_{\theta\to0}\frac{\sin\left(\frac{2m+1}{2}\theta\right)}{\sin\left(\frac{\theta}{2}\right)}$ ，故等式在 $\theta\in(-\infty,\infty)$ 上成立，

由于周期函数任何一个长度等于周期的区间积分值相等，故带入积分式有

\begin{aligned}
 S_m(x)=&\frac{1}{\pi}\int_{-\pi}^\pi\left\{f(t)\left[\frac{1}{2}+\sum_{i=1}^m\cos(i(t-x))\right]\right\}dt\\
=&\frac{1}{\pi}\int_{-\pi}^\pi\left\{f(t)\frac{\sin\left(\frac{2m+1}{2}(t-x)\right)}{2\sin\left(\frac{(t-x)}{2}\right)}\right\}dt\\
=&\frac{1}{\pi}\int_{-\pi-x}^{\pi-x}\left\{f(u+x)\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du&u=t-x,du=dt\\
=&\frac{1}{\pi}\int_{-\pi}^{\pi}\left\{f(u+x)\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du\\
\end{aligned}

由于 $\frac{\sin\left(\frac{2m+1}{2}u\right)}{\sin\left(\frac{u}{2}\right)}$ 为偶函数，故

\begin{aligned}
 S_m(x)=&\frac{1}{\pi}\int_{-\pi}^{\pi}\left\{f(u+x)\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du\\
=&\frac{1}{\pi}\int_{-\pi}^{0}\left\{f(u+x)\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du+\frac{1}{\pi}\int_{0}^{\pi}\left\{f(u+x)\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du\\
=&\frac{1}{\pi}\int_{0}^{\pi}\left\{f(x-u)\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du+\frac{1}{\pi}\int_{0}^{\pi}\left\{f(u+x)\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du\\
=&\frac{1}{\pi}\int_{0}^{\pi}\left\{[f(x-u)+f(x+u)]\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du
\end{aligned}

由于在 $u\in[-\pi,\pi]$ 上时 $u=0\Rightarrow\sin\left(\frac{u}{2}\right)=0$ 根据之前定义此时 $\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}=\lim_{u\to0}\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}$

同理定义积分区间在 $(0,\pi]$ 的反常积分，可以理解为积分区域在 $[0,\pi]$ 但当 $u=0$ 时函数值为 $0$ 的积分

故根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-线性-推论]]有在 $(0,\pi]$ 上的反常积分等于在 $[0,\pi]$ 上的常义积分

故 $S_m(x)=\frac{1}{\pi}\int_{0}^{\pi}\left\{[f(x-u)+f(x+u)]\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du=\lim_{a\to0}\frac{1}{\pi}\int_{a}^{\pi}\left\{[f(x-u)+f(x+u)]\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du$

**** 转换收敛目标

由于 $\int_0^{\pi}\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}du=\int_0^{\pi}\left\{\frac{1}{2}+\sum_{i=1}^m\cos(iu)\right\}du=\int_0^{\pi}\frac{1}{2}du=\frac{\pi}{2}$

定义 $\sigma(x)$ 为 $S_m(x)$ 的收敛值，则有 $\lim_{m\to\infty}\{S_m(x)-\sigma(x)\}=0$ 根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-线性]]有

\begin{aligned}
&\lim_{m\to\infty}\left\{\frac{1}{\pi}\int_{0}^{\pi}\left\{[f(x-u)+f(x+u)]\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du-\sigma(x)\right\}\\
=&\lim_{m\to\infty}\left\{\frac{1}{\pi}\int_{0}^{\pi}\left\{[f(x-u)+f(x+u)]\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du-\sigma(x)\frac{2}{\pi}\int_0^{\pi}\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}du\right\}\\
=&\lim_{m\to\infty}\left\{\frac{1}{\pi}\int_{0}^{\pi}\left\{[f(x-u)+f(x+u)-2\sigma(x)]\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du\right\}\\
\end{aligned}

定义 $\phi(u,x)=f(x-u)+f(x+u)-2\sigma(x)$ 则当 $\lim_{m\to\infty}\left\{\frac{1}{\pi}\int_{0}^{\pi}\left\{\phi(u,x)\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du\right\}=0$ 是为目标极限

根据条件 $\sigma(x)=\frac{f(x^+)+f(x^-)}{2}$ 其中 $f(x^+)=\lim_{u\to0^+}f(x+u),f(x^-)=\lim_{u\to0^+}f(x-u)$ 下面证明结论

**** 证明条件（1）

根据定义

由于条件（1），则必存在领域当 $x\in[x-\delta,x+\delta]$ 时函数 $f(x)$ 单调，定义 $\phi(u)=f(x+u),\phi'(u)=f(x-u)$

则有当 $u\in[0,\delta]$ 时 $\phi(u),\phi'(u)$ 单调，故根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-区间可加]]和极限四则运算拆分积分

\begin{aligned}
&\lim_{m\to\infty}\left\{\frac{1}{\pi}\int_{0}^{\pi}\left\{\phi(u,x)\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du\right\}\\
=&\frac{1}{\pi}\lim_{m\to\infty}\left\{\int_{0}^{\delta}\left\{\phi(u,x)\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du+\int_{\delta}^{\pi}\left\{\phi(u,x)\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du\right\}\\
=&\frac{1}{\pi}\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{\phi(u,x)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du+\frac{1}{\pi}\lim_{m\to\infty}\int_{\delta}^{\pi}\left\{\frac{\phi(u,x)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du\\
=&\frac{1}{\pi}\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x+u)-f(x^+)+f(x-u)-f(x^-)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du+\frac{1}{\pi}\lim_{m\to\infty}\int_{\delta}^{\pi}\left\{\frac{\phi(u,x)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du\\
=&\frac{1}{\pi}\lim_{m\to\infty}\left\{\int_{0}^{\delta}\left\{\frac{f(x+u)-f(x^+)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du+\int_{0}^{\delta}\left\{\frac{f(x-u)-f(x^-)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du\right\}+\frac{1}{\pi}\lim_{m\to\infty}\int_{\delta}^{\pi}\left\{\frac{\phi(u,x)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du\\
=&\frac{1}{\pi}\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x+u)-f(x^+)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du+\frac{1}{\pi}\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x-u)-f(x^-)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du+\frac{1}{\pi}\lim_{m\to\infty}\int_{\delta}^{\pi}\left\{\frac{\phi(u,x)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du\\
\end{aligned}

由于当 $u\in[a,\pi],0<a<\pi$ 时 $f(x+u)$ 为周期拓展可积或绝对可积，故 $\phi(u,x)$ 可积或绝对可积

同理 $\frac{1}{\sin\left(\frac{u}{2}\right)}$ 可积，故根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-乘积可积]] $\frac{\phi(u,x)}{\sin\left(\frac{u}{2}\right)}$ 在 $u\in[a,\pi],0<a<\pi$ 可积或绝对可积

故满足[[MK2][黎曼引理]]条件，则有 $\lim_{m\to\infty}\int_{\delta}^{\pi}\left\{\frac{\phi(u,x)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du=0$

根据[[MK4][黎曼引理推论]]有 $\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x+u)-f(x^+)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du=\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x+u)-f(x^+)}{u}\sin\left(\frac{2m+1}{2}u\right)\right\}du$

定义 $\psi(u)=f(x+u)$ 则有 $\psi(0^+)=\lim_{u\to0^+}\psi(u)=\lim_{u\to0^+}f(s+u)=f(x^+)$ 

故 $\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x+u)-f(x^+)}{u}\sin\left(\frac{2m+1}{2}u\right)\right\}du=\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{\psi(u)-\psi(0^+)}{u}\sin\left(\frac{2m+1}{2}u\right)\right\}du$

且根据条件 $\psi(u)$ 在 $u\in[0,\delta]$ 上单调，故满足[[MK5][Dirichlet引理]]，

则有 $\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x+u)-f(x^+)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du=\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{\psi(u)-\psi(0^+)}{u}\sin\left(\frac{2m+1}{2}u\right)\right\}du=0$

同理可证 $\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x-u)-f(x^-)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du=0$

故当满足条件（1）时函数收敛于 $\frac{f(x^+)+f(x^-)}{2}$ ，证毕。 

**** 证明条件（2）

Holden 条件的定义为对充分小的 $\delta>0$ 存在常数 $L>0,\alpha\in(0,1]$ 使得 $\forall u\in(0,\delta)\Rightarrow|f(x\pm u)-f(x^{\pm})|<Lu^\alpha$

同上拆分积分

\begin{aligned}
&\lim_{m\to\infty}\left\{\frac{1}{\pi}\int_{0}^{\pi}\left\{\phi(u,x)\frac{\sin\left(\frac{2m+1}{2}u\right)}{2\sin\left(\frac{u}{2}\right)}\right\}du\right\}\\
=&\frac{1}{\pi}\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x+u)-f(x^+)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du+\frac{1}{\pi}\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x-u)-f(x^-)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du+\frac{1}{\pi}\lim_{m\to\infty}\int_{\delta}^{\pi}\left\{\frac{\phi(u,x)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du\\
\end{aligned}

同上可得 $\lim_{m\to\infty}\int_{\delta}^{\pi}\left\{\frac{\phi(u,x)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du=0$

同上亦可得 $\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x+u)-f(x^+)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du=\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x+u)-f(x^+)}{u}\sin\left(\frac{2m+1}{2}u\right)\right\}du$

根据条件有 $\left|\frac{f(x+u)-f(x^{+})}{u}\right|<\frac{L}{u^{1-\alpha}},u\in(0,\delta]$ 且有 $\int_0^\delta \frac{L}{u^{1-\alpha}}du=Lu^\alpha\big|_0^\delta=Lu^\delta$ 在上述条件下反常积分存在

由于 $\left|\frac{f(x+u)-f(x^{+})}{u}\right|>0$ 故根据[[e:/OneDrive/数学分析/Note/Chapter 8/Chap8Note.org][无界函数反常积分收敛判别-非负反常积分判别]] $\left|\frac{f(x+u)-f(x^{ +})}{u}\right|$ 亦可积

故有 $\frac{f(x+u)-f(x^{+})}{u}$ 在 $u\in(0,\delta]$ 上反常积分绝对可积，满足[[MK2][黎曼引理]]条件

则有 $\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x+u)-f(x^+)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du=\lim_{m\to\infty}\int_{0}^{\delta}\frac{f(x+u)-f(x^{+})}{u}\sin\left(\frac{2m+1}{2}u\right)\right\}du=0$

同理可证  $\lim_{m\to\infty}\int_{0}^{\delta}\left\{\frac{f(x-u)-f(x^-)}{2\sin\left(\frac{u}{2}\right)}\sin\left(\frac{2m+1}{2}u\right)\right\}du=\lim_{m\to\infty}\int_{0}^{\delta}\frac{f(x-u)-f(x^{-})}{u}\sin\left(\frac{2m+1}{2}u\right)\right\}du=0$

故当满足条件（2）时函数收敛于 $\frac{f(x^+)+f(x^-)}{2}$ ，证毕。 

* 傅里叶级数性质

** 性质1

函数 $f(x)$ 在 $[-\pi,\pi]$ 上可积或绝对可积，且 $a_n,b_n$ 为 $f(x)$ 的傅里叶系数

则有 $\lim_{n\to\infty}a_n=\lim_{n\to\infty}b_n=0$

*** 证明

由于 $f(x)$ 可积或绝对可积，根据[[MK2][黎曼引理]] $\lim_{i\to\infty}a_n=\lim_{i\to\infty}\frac{1}{\pi}\int_{-\pi}^\pi f(x)\cos(ix)dx=0$

同理 $\lim_{i\to\infty}a_n=\lim_{i\to\infty}\frac{1}{\pi}\int_{-\pi}^\pi f(x)\sin(ix)dx=0$

** 逐项积分

函数 $f(x)$ 在 $[-\pi,\pi]$ 上可积或绝对可积，则函数的傅里叶级数可逐项求积分

即 $\forall c,x\in[-\pi,\pi]\Rightarrow\int_c^x f(t)dt=\int_c^x\frac{a_0}{2}dt+\sum_{i=1}^\infty\int_c^x(a_i\cos(it)+b_i\sin(it))dt$

*** 证明

*仅证明有有限个第一类不连续点（左右极限均存在但不相等）的情况，其他情况数学工具尚未具备*

定义 $F(x)=\int_c^x\left(f(t)-\frac{a_0}{2}\right)dt$ 则有

\begin{aligned}
F(x+2\pi)-F(x)=&\int_c^{x+2\pi}\left(f(t)-\frac{a_0}{2}\right)dt-\int_c^x\left(f(t)-\frac{a_0}{2}\right)dt\\
=&\int_x^{x+2\pi}\left(f(t)-\frac{a_0}{2}\right)dt\\
=&\int_x^{x+2\pi}f(t)dt-\frac{a_0}{2}2\pi\\
=&\int_x^{x+2\pi}f(t)dt-\frac{1}{\pi}\int_x^{x+2\pi}f(t)dt\pi\\
=&0
\end{aligned}

故 $F(x)$ 为周期函数，周期为 $2\pi$ 。且则根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][牛顿莱布尼茨公式-定理1]]可得 $F(x)$ 连续

且根据证明有 $\lim_{\Delta x\to0^+}\frac{F(x+\Delta x)-F(x)}{\Delta x}=\lim_{\xi\to x^+}f(\xi)=f(x^+),\lim_{\Delta x\to0^-}\frac{F(x+\Delta x)-F(x)}{\Delta x}=\lim_{\xi\to x^-}f(\xi)=f(x^-)$ 

即左右导数均存在，且等于 $f(x)$ 在 $x$ 点的左右极限，故根据[[MK6][Dini-Lipschitz判别]]，结合连续得 $F(x)$ 的傅里叶级数收敛于 $F(x)$

即 $F(x)=\frac{A_0}{2}+\sum_{i=1}^\infty\left(A_i\cos(ix)+B_i\sin(ix)\right)$ 其中

\begin{aligned}
A_i=&\frac{1}{\pi}\int_{-\pi}^\pi F(x)\cos(ix)dx\\
=&\frac{1}{i\pi}\int_{-\pi}^\pi F(x)d\sin(ix)\\
=&\frac{1}{i\pi}F(x)\sin(x)\bigg|_{-\pi}^\pi-\frac{1}{i\pi}\int_{-\pi}^\pi\sin(x)dF(x)\\
=&-\frac{1}{i\pi}\int_{-\pi}^\pi f(x)\sin(x)dx\\
=&-\frac{b_i}{i}
\end{aligned}

同理可证 $B_i=\frac{a_n}{i}$ 整理上式得 $F(x)=\frac{A_0}{2}+\sum_{i=1}^\infty\left(-\frac{b_i}{i}\cos(ix)+\frac{a_i}{i}\sin(ix)\right)$


由于 $F(c)=0$ 故 $\frac{A_0}{2}=-\sum_{i=1}^\infty\left(-\frac{b_i}{i}\cos(ic)+\frac{a_i}{i}\sin(ic)\right)$ 故根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-线性]]有

\begin{aligned}
F(x)=&\sum_{i=1}^\infty\left(a_i\frac{\sin(ix)-\sin(ic)}{i}+b_i\frac{-\cos(ix)+\cos(ic)}{i}\right)\\
=&\sum_{i=1}^\infty\left(a_i\int_c^x\cos(it)dt+b_i\int_c^x\sin(it)dt\right)\\
=&\sum_{i=1}^\infty\int_c^x\left(a_i\cos(it)+b_i\sin(it)\right)dt\\
\end{aligned}

则有 $\int_c^x\left(f(t)-\frac{a_0}{2}\right)dt=\sum_{i=1}^\infty\int_c^x\left(a_i\cos(it)+b_i\sin(it)\right)dt\Rightarrow\int_c^xf(t)dt=\int_c^x\frac{a_0}{2}dt+\sum_{i=1}^\infty\int_c^x\left(a_i\cos(it)+b_i\sin(it)\right)dt$

证毕

** 逐项求导

* 傅里叶级数逼近性质

** 一般线性空间最佳平方逼近

*** 前提定义

假设 $S$ 为定义了內积运算 $(\cdot,\cdot)$ 的线性空间，且<<MK8>>內积性质有：

（1） 范数 $\|\vec{x}\|=\sqrt{(\vec{x},\vec{x})}\geq0,\vec{x}\in S$ 即范数为自身的內积，且范数大于零

（2） 当且仅当 $\vec{x}$ 为零元时，范数为零

（3） $(\vec{x}+\vec{y},\vec{z})=(\vec{x},\vec{z})+(\vec{y},\vec{z})$ 即內积满足分配率

（4） $(\vec{x},\vec{y})=(\vec{y},\vec{x})$ 即满足交换律

（5） $(A\vec{x},B\vec{y})=AB(\vec{x},\vec{y})$ 即系数可以提出

定义 $T\subset S$ 是 $S$ 的子空间，且有正交基 $\vec{\phi}_1,\vec{\phi}_1,...,\vec{\phi}_m$ 即 $T=span\{\vec{\phi}_1,\vec{\phi}_1,...,\vec{\phi}_m\}$

对于任意 $\vec{x}\in S$ 有 $\vec{x}_T=\sum_{i=1}^mc_i\vec{\phi}_i\in T$ 使得 $\|\vec{x}-\vec{x}_T\|=\min_{\vec{y}\in T}\|\vec{x}-\vec{y}\|$ 即范数最小

则称 $\vec{x}_T$ 是 $x$ 在 $T$ 中的最佳平方逼近。

*** 定理

（1） 对于任意给定 $\vec{x}\in S$ ， $T$ 的最佳逼近元素 $\vec{x}_T$ 存在且唯一

（2） $\vec{x}_T\in T$ 是最佳逼近元素的充要条件是 $\vec{x}-\vec{x}_T\perp T$ 即 $(\vec{x}-\vec{x}_T,\vec{\phi}_i)=0,1\leq i\leq m$ ，或等价的 $c_i=\frac{(\vec{x},\vec{\phi}_i)}{(\vec{\phi}_i,\vec{\phi}_i)}$

（3） $\|\vec{x}-\vec{x}_T\|^2=\|\vec{x}\|^2-\sum_{i=1}^mc_i^2\|\vec{\phi}_i\|^2$

**** 证明

***** <<MK9>>先证（1），（3）

定义 $\vec{y}=\sum_{i=1}^m d_i\vec{\phi}_i$ 其中 $d_i$ 为常系数，故有 $d_i\in T$ 

故根据[[MK8][內积性质]]以及基向量的正交性

\begin{aligned}
\|\vec{x}-\vec{y}\|^2&=(\vec{x}-\vec{y},\vec{x}-\vec{y})\\
&=(\vec{x},\vec{x})-2\left(\sum_{i=1}^m d_i\vec{\phi}_i,\vec{x}\right)+\left(\sum_{i=1}^m d_i\vec{\phi}_i,\sum_{i=1}^m d_i\vec{\phi}_i\right)\\
&=\|x\|^2-2\sum_{i=1}^md_i(\vec{\phi}_i,\vec{x})+\sum_{i=1}^m d_i^2\|\vec{\phi}_i\|^2\\
&=\|x\|^2-\sum_{i=1}^m\left(\frac{(\vec{\phi}_i,\vec{x})}{\|\vec{\phi}_i\|}\right)^2+\sum_{i=1}^m\left(\frac{(\vec{\phi}_i,\vec{x})}{\|\vec{\phi}_i\|}\right)^2-2\sum_{i=1}^md_i(\vec{\phi}_i,\vec{x})+\sum_{i=1}^m d_i^2\|\vec{\phi}_i\|^2\\
&=\|x\|^2-\sum_{i=1}^m\left(\frac{(\vec{\phi}_i,\vec{x})}{\|\vec{\phi}_i\|}\right)^2+\sum_{i=1}^m\left[\left(\frac{(\vec{\phi}_i,\vec{x})}{\|\vec{\phi}_i\|}\right)^2-2d_i(\vec{\phi}_i,\vec{x})+d_i^2\|\vec{\phi}_i\|^2\right]\\
&=\|x\|^2-\sum_{i=1}^m\left(\frac{(\vec{\phi}_i,\vec{x})}{\|\vec{\phi}_i\|}\right)^2+\sum_{i=1}^m\left(\frac{(\vec{\phi}_i,\vec{x})}{\|\vec{\phi}_i\|}-d_i\|\vec{\phi}_i\|\right)^2
\end{aligned}

由于 $\|x\|^2-\sum_{i=1}^m\frac{(\vec{\phi}_i,\vec{x})}{\|\vec{\phi}_i\|}$ 与 $d_i$ 无关，且 $\sum_{i=1}^m\left(\frac{(\vec{\phi}_i,\vec{x})}{\|\vec{\phi}_i\|}-d_i\|\vec{\phi}_i\|\right)^2\geq0$ 

故当且仅当 $d_i=\frac{(\vec{\phi}_i,\vec{x})}{\|\vec{\phi}_i\|^2}=\frac{(\vec{\phi}_i,\vec{x})}{(\vec{\phi}_i,\vec{\phi}_i)}$ 时范数最小

且此时范数的平方 $\|\vec{x}-\vec{y}\|^2=\|x\|^2-\sum_{i=1}^m\left(\frac{(\vec{\phi}_i,\vec{x})}{\|\vec{\phi}_i\|}\right)^2=\|\vec{x}\|^2-\sum_{i=1}^mc_i^2\|\vec{\phi}_i\|^2$ 其中 $c_i=\frac{(\vec{x},\vec{\phi}_i)}{(\vec{\phi}_i,\vec{\phi}_i)}$

证毕。

***** 再证（2）

****** 充分性

定义 $\vec{y}=\sum_{i=1}^m d_i\vec{\phi}_i$ 且 $\vec{x}-\vec{y}\perp T$ 则有 $(\vec{x}-\vec{y},\vec{\phi}_i)=0$ 根据[[MK8][內积性质]] 

\begin{aligned}
(\vec{x}-\vec{y},\vec{\phi}_i)&=(\vec{x},\vec{\phi}_i)-(\vec{y},\vec{\phi}_i)\\
&=(\vec{x},\vec{\phi}_i)- d_i(\vec{\phi}_i,\vec{\phi}_i)=0\\
&\Rightarrow d_i=\frac{(\vec{x},\vec{\phi}_i)}{(\vec{\phi}_i,\vec{\phi}_i)}
\end{aligned}

根据[[MK9][之前证明]]得当 $d_i=\frac{(\vec{\phi}_i,\vec{x})}{(\vec{\phi}_i,\vec{\phi}_i)}$ 时为最佳平方逼近 

****** 必要性

定义 $\vec{y}=\sum_{i=1}^m d_i\vec{\phi}_i$ 为最佳平方逼近，则根据[[MK9][之前证明]]得 $d_i=\frac{(\vec{\phi}_i,\vec{x})}{(\vec{\phi}_i,\vec{\phi}_i)}$ 则有

\begin{aligned}
(\vec{x}-\vec{y},\vec{\phi}_i)&=(\vec{x},\vec{\phi}_i)-(\vec{y},\vec{\phi}_i)\\
&=(\vec{x},\vec{\phi}_i)- d_i(\vec{\phi}_i,\vec{\phi}_i)\\
&=(\vec{x},\vec{\phi}_i)-(\vec{x},\vec{\phi}_i)\\
&=0\\
\end{aligned}

故有 $\vec{x}-\vec{y}\perp T$ 

** 傅里叶级数



