#+LATEX_CLASS: ctexart

#+TITLE: 多元函数微分

current mark: MK27

* 矩阵基本知识

** 特征值与特征向量

设 $A=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]$ 为 $n$ 阶矩阵，存在常数 $\lambda$ 及非零 $n$ 维向量 $\vec{x}$ 使得 $A\vec{x}=\lambda\vec{x}$ 则称 $\lambda$ 为 $A$ 的特征值 $\vec{x}$ 为相应的特征向量

** 求解特征值和特征向量

根据定义有 $A\vec{x}=\lambda\vec{x}=\lambda E\vec{x}$ 故根据矩阵运算定义 $\left(E\lambda-A\right)\vec{x}=\vec{0}$ 其中 $E$ 为单位矩阵

由于 $\vec{x}$ 为非零向量，故 $\left(E\lambda-A\right)$ 不存在逆阵使得 $\vec{x}=\vec{0}\left(E\lambda-A\right)=\vec{0}$ 故 $\left|E\lambda-A\right|=0$

根据行列式计算方法 $D=\Pi_{i=1}^n (a_{ii}-\lambda)+C$ 其中 $C$ 为排除连乘的其他项，故根据代数基本定理 $\lambda$ 可有 $n$ 个复根

** 矩阵对角化

若 $n$ 阶矩阵 $A$ 存在 $n$ 个线性不相关特征向量 $\vec{x}=[\begin{matrix}\vec{x}_1&\vec{x}_2&..&\vec{x}_n\end{matrix}]$ 则存在正交矩阵 $P=\vec{x}$ 使得 $P^{-1}AP=\Lambda=\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]$ 其中 $\lambda_i$ 为特征向量 $\vec{x}$ 对应的特征值

*** 证明

根据矩阵乘法

\begin{aligned}
AP&=\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right][\begin{matrix}\vec{x}_1&\vec{x}_2&..&\vec{x}_n\end{matrix}]\\
&=[\begin{matrix}A\vec{x}_1&A\vec{x}_2&..&A\vec{x}_n\end{matrix}]\\
&=[\begin{matrix}\lambda_1\vec{x}_1&\lambda_2\vec{x}_2&..&\lambda_n\vec{x}_n\end{matrix}]\\
&=[\begin{matrix}\vec{x}_1&\vec{x}_2&..&\vec{x}_n\end{matrix}]\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]\\
&=P\Lambda\\
\end{aligned}

若 $P$ 可逆，即 $\vec{x}_i$ 线性不相关，则有 $P^{-1}P=E$

同时由于矩阵乘法满足结合律，故 $P^{-1}AP=P^{-1}(AP)=P^{-1}P\Lambda=E\Lambda=\Lambda$ 证毕

** 实对称矩阵

定义矩阵 $A$ 为 $n$ 阶实对称矩阵

*** <<MK19>>实对称矩阵特征值为实数

根据特征值定义 $A\vec{x}=\lambda\vec{x}\Rightarrow (A\vec{x})^T=(\lambda\vec{x})^T\Rightarrow\vec{x}^TA^T=\vec{x}^T\lambda$

对以上等式两边取共轭 $\overline{\vec{x}^TA^T}=\overline{\vec{x}^T\lambda}\Rightarrow \overline{\vec{x}^T}\cdot\overline{A^T}=\overline{\lambda}\cdot\overline{\vec{x}^T}\Rightarrow\overline{\vec{x}^T}\cdot\overline{A^T}\cdot\vec{x}=\overline{\lambda}\cdot\overline{\vec{x}^T}\cdot\vec{x}$

由于对称实矩阵 $A^T=A,\overline{A}=A\Rightarrow \overline{A^T}=A$ 故有 $\overline{\vec{x}^T}\cdot A\cdot\vec{x}=\overline{\vec{x}^T}\cdot \lambda\cdot\vec{x}=\overline{\lambda}\cdot\overline{\vec{x}^T}\cdot\vec{x}$

故 $\overline{\lambda}=\lambda$ 得出特征值必为实数

*** <<MK22>>实对称矩阵不同特征值的特征向量正交

定义 $A\vec{x}_1=\lambda_1\vec{x}_1,A\vec{x}_2=\lambda_2\vec{x}_2$ 其中 $\lambda_1\ne\lambda_2$

则有 $\vec{x}_2^TA\vec{x}_1=\vec{x}_2^T\lambda_1\vec{x}_1$ 由于实对称矩阵 $A^T=A$ 且由于根据矩阵乘法 $BA=(A^TB^T)^T$ 其中 $B$ 为列数为 $n$ 的任意矩阵，故有 $BA=(AB^T)^T$

故 $\vec{x}_2^TA\vec{x}_1=(A\vec{x}_2)^T\vec{x}_1=(\lambda_2\vec{x}_2)^T\vec{x}_1=\vec{x}_2^T\lambda_1\vec{x}_1\Rightarrow (\lambda_1-\lambda_2)\vec{x}_2^T\vec{x}_1=0$ 因为 $\lambda_1\ne\lambda_2$ 故有 $\vec{x}_2^T\vec{x}_1=0$

*** <<MK23>>实对称矩阵必有实数特征向量

由于 $(E\lambda-A)\vec{x}=0$ 其中根据[[MK19][特征值为实数]]可得计算的 $\vec{x}$ 亦为实数

*** <<MK24>>实对称矩阵必可对角化

**** <<MK20>>证明存在正交矩阵转换为上三角矩阵

假设对于 $n-1$ 阶矩阵 $B$ 存在正交矩阵 $S=[\begin{matrix}\vec{s}_2&\vec{s}_3&...&\vec{s}_n\end{matrix}]$ 其中 $|\vec{s}_i|=1,\vec{s}_i\cdot\vec{s}_j=0,i\ne j$ 使得 $S^{-1} B S=S^T A_{n-1} S=\left[\begin{matrix}\lambda_2&*&...&*\\0&\lambda_3&...&*\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]$

对于 $n$ 阶矩阵 $A$ 假设其中一个特征值为 $\lambda$ 对应特征向量 $\vec{q}_1$ 其长度为 $|\vec{q}_1|=1$ 以 $\vec{q}_1$ 为基准建议一组长度为1，相互正交的向量 $\vec{q}_1,\vec{q}_2,...,\vec{q}_n\Rightarrow |\vec{q}_i|=1,\vec{q}_i\cdot\vec{q}_j=0,i\ne j$

则定义 $Q=[\begin{matrix}\vec{q}_1&\vec{q}_2&...&\vec{q}_n\end{matrix}]$ 故有 $AQ=[\begin{matrix}A\vec{q}_1&A\vec{q}_2&...&A\vec{q}_n\end{matrix}]$ 由于 $A\vec{q}_i\in R^n$ 且 $Q$ 为维度为 $n$ 的正交向量，故 $A\vec{q}_i$ 必可用 $\vec{q}_i$ 的线性组合表示，即 $A\vec{q}_i=\sum_{j=1}^n b_{ij}\vec{q}_j$

且有根据特征值定义故 

\begin{aligned}
AQ&=\left[\begin{matrix}\lambda\vec{q}_1&\vec{q}_2\left[\begin{matrix}b_{21}\\b_{22}\\...\\b_{2n}\end{matrix}\right]&...&\vec{q}_n\left[\begin{matrix}b_{n1}\\b_{n2}\\...\\b_{nn}\end{matrix}\right]\end{matrix}\right]\\
&=\left[\begin{matrix}\vec{q}_1&\vec{q}_1&...&\vec{q}_1\end{matrix}\right]\left[\begin{matrix}\lambda&b_{21}&...&b_{n1}\\0&b_{22}&...&b_{n2}\\...&...&...&...\\0&b_{2n}&...&b_{nn}\end{matrix}\right]
\end{aligned}

故有

\begin{aligned}
Q^{-1}AQ&=\left[\begin{matrix}\vec{q}_1&\vec{q}_1&...&\vec{q}_1\end{matrix}\right]^{-1}\left[\begin{matrix}\vec{q}_1&\vec{q}_1&...&\vec{q}_1\end{matrix}\right]\left[\begin{matrix}\lambda&b_{21}&...&b_{n1}\\0&b_{22}&...&b_{n2}\\...&...&...&...\\0&b_{2n}&...&b_{nn}\end{matrix}\right]\\
&=\left[\begin{matrix}\lambda&b_{21}&...&b_{n1}\\0&b_{22}&...&b_{n2}\\...&...&...&...\\0&b_{2n}&...&b_{nn}\end{matrix}\right]\\
&=\left[\begin{matrix}\lambda&\vec{b}\\\vec{0}&B\end{matrix}\right]
\end{aligned}

由于根据假设使任意 $n-1$ 阶矩阵 $B$ 存在正交阵 $S$ 使得 $S^{-1}BS$ 为上三角矩阵，则定义 $Q'=\left[\begin{matrix}1&0&...&0\\0& & & \\...& &S& \\0& & &\\\end{matrix}\right]$

则有 $(QQ')^TQQ'=Q'^TQ^TQQ'=Q'^TEQ'=E$ 故 $QQ'$ 正交矩阵且有 

\begin{aligned}
(QQ')^{-1}AQQ'&=(QQ')^TAQQ'\\
&=\left[\begin{matrix}1&\vec{0}\\\vec{0}&S\end{matrix}\right]^T \left[\begin{matrix}\lambda&\vec{b}\\\vec{0}&B\end{matrix}\right]\left[\begin{matrix}1&\vec{0}\\\vec{0}&S\end{matrix}\right]\\
&=\left[\begin{matrix}\lambda&*&...&*\\0&\lambda_2&...&*\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]
\end{aligned}

由于对于 $1$ 阶矩阵，显然成立。故根据数学归纳法，证得。

**** <<MK21>>证明对称矩阵必可对角化

设 $A$ 为对称矩阵，根据[[MK20][上三角矩阵变换]]得，必可有正交矩阵 $P$ 使得 $H=P^{-1}AP=\left[\begin{matrix}\lambda_1&*&...&*\\0&\lambda_2&...&*\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]$

由于矩阵乘法满足结合律 $H^T=(P^{-1}AP)^T=(AP)^T(P^{-1})^T=P^TA^T(P^T)^T=P^TA^TP$ 由于 $A$ 为对称矩阵，故 $H^T=P^TA^TP=P^TAP=H$ 

又因为 $H$ 是上三角矩阵，故必为对角阵，即 $H=\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]$

**** 证明对角化后对角线为特征值，正交阵向量为特征向量

根据[[MK21][可对角化]]有 $n$ 阶对称矩阵 $A$ 必然存在正交阵 $P$ 使得 $P^{-1}AP=\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]$

故整理得

\begin{aligned}
P^{-1}AP&=\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]\\
AP&=P\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]\\
A[\begin{matrix}\vec{p}_1&\vec{p}_1&...&\vec{p}_1\end{matrix}]&=[\begin{matrix}\vec{p}_1&\vec{p}_1&...&\vec{p}_1\end{matrix}]\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]
\end{aligned}

故推出 $A\vec{p}_i=\lambda_i\vec{p}_i$ 所以 $\lambda_i$ 为特征值 $\vec{p}_i$ 为对应的特征向量

* 正定矩阵

** 定义

设 $f(\vec{x})=\vec{x}^T A \vec{x}=\left[\begin{matrix}x_1&x_2&...&x_n\end{matrix}\right]\left[\begin{matrix}a_{11}&a_{12}&...&a_{1n}\\a_{21}&a_{22}&...&a_{2n}\\...&...&...&...\\a_{n1}&a_{n2}&...&a_{nn}\end{matrix}\right]\left[\begin{matrix}x_1\\x_2\\...\\x_n\end{matrix}\right]$ 若对于任意 $\vec{x}\ne\vec{0}$ 都有 $f(\vec{x})>0$ 则称矩阵 $A$ 为正定矩阵 $f(\vec{x})$ 为正定二次型

** <<MK26>>正定的充要条件

*** <<MK25>>实对称矩阵正定的充要条件是特征值都是正数

定义 $n$ 阶实数对称矩阵 $A$ ，根据[[MK19][实对称矩阵特征值为实数]]，[[MK22][实对称矩阵特征向量正交]]，[[MK23][实对称矩阵特征向量为实数]]以及[[MK24][实对称矩阵必可对角化]]

可得存在正交实数阵 $P$ 使得 $P^{-1}AP=\Lambda=\left[\begin{matrix}\lambda_1&0&...&0\\0&\lambda_2&...&0\\...&...&...&...\\0&0&...&\lambda_n\end{matrix}\right]$ 其中 $P,\lambda_i$ 均为实数

故定义 $\vec{y}=P^{-1}\vec{x}\Rightarrow \vec{x}=P\vec{y}$ 由于 $\vec{x}$ 非零且 $P$ 正交（即非零），故 $\vec{y}=P^{-1}\vec{x}\ne 0$ 则 $f(\vec{x})=(P\vec{y})^TAP\vec{y}=\vec{y}^TP^TAP\vec{y}=\vec{y}^TP^{-1}AP\vec{y}^T=\sum_{i=1}^n \lambda_i y_i^2$

**** 充分性

若 $\lambda_i>0\Rightarrow \vec{x}^TA\vec{x}=\sum_{i=1}^n\lambda_i y_i^2>0,\vec{y}\ne\vec{0}$ 故充分

**** 必要性

又由于正定满足 $\forall \vec{x}\ne\vec{0}\Rightarrow f(\vec{x})>0$ 且 $P$ 为正交阵 $\vec{y}=P^{-1}\vec{x}=P^T\vec{x}$ 故 $\vec{y}$ 可表示为空间 $R^n$ 中任意一非零点

反证若 $\lambda_j<0$ 则有特殊 $\vec{x}_j$ 使得 $y_i=\begin{cases}0&i\ne j\\C&i=j\end{cases}$ 其中 $C$ 为某一常数，则有 $\sum_{i=1}^n\lambda_iy_i^2=\lambda_jC^2<0$ 故不满足正定。所以必要条件为 $\lambda_i>0$

*** 实对称矩阵 $A$ 正定的充要条件是存在可逆矩阵 $P$ 使得 $A=P^TP$

**** 必要性

由于可逆，故对于任意 $\vec{x}\ne\vec{0}$ 都有 $P\vec{x}\ne\vec{0}$

故有 $f(\vec{x})=\vec{x}^T(P^TP)\vec{x}=(P\vec{x})^T(P\vec{x})=(P\vec{x})^2$ 由于 $P\vec{x}\ne\vec{0}$ 故 $f(\vec{x})>0,\forall \vec{x}\ne\vec{0}$ 故为必要条件

**** 充分性

由于正定矩阵充分条件为 $\lambda_i>0$ 则有 $A=(PP^{-1})^TAPP^{-1}=(P^{-1})^TP^TAPP^{-1}$ 根据[[MK22][实对称矩阵特征向量正交]]可得 $P$ 为正交阵，故 $P^{-1}=P^T$

则有 $A=(P^{-1})^TP^TAPP^{-1}=(P^{-1})^T\Lambda P^{-1}=P\sqrt{\Lambda}^T \sqrt{\Lambda}P^T=(\sqrt{\Lambda}P^T)^T\sqrt{\Lambda}P^T$ 故充分

*** 实对称矩阵正定的充要条件是其顺序主子式全部大于零

**** 定义顺序主子式

对于给定 $n$ 阶矩阵 $A$ 其顺序主子式为 $A$ 的 $s\leq n$ 阶内阵的行列式，即 $|A_s|=\left|\begin{matrix}a_{11}&a_{12}&...&a_{1s}\\a_{21}&a_{22}&...&a_{2s}\\...&...&...&...\\a_{s1}&a_{s2}&...&a_{ss}\end{matrix}\right|$

**** 证明

***** 充分性

根据特征值定义 $|E\lambda-A|=0\Rightarrow |E\lambda-A|=\Pi_{i=1}^n(\lambda-\lambda_i)$ 由于 $\lambda$ 符号为正，故 $\lambda_i$ 为减项

故带入 $\lambda=0\Rightarrow |-A|=\Pi_{i=1}^n(0-\lambda_i)\Rightarrow (-1)^n|A|=(-1)^n\Pi_{i=1}^n\lambda_i\Rightarrow |A|=\Pi_{i=1}^n\lambda_i$

由于正定，则对任意 $\vec{x}$ 成立，故定义 $\vec{x}'=[\begin{matrix}x_1&..&x_s&0&..&0\end{matrix}]^T$ 当前 $s$ 项不同时为零时，任然有 $\vec{x}'^T A \vec{x}' =\vec{x}'^T A_s \vec{x}'>0$ 故 $A$ 的内阵 $A_s$ 亦为正定

根据[[MK25][正定充要条件1]]有 $A_s$ 的特征值 $\lambda^s_i>0$ 有根据上述证明可得 $|A_s|=\Pi_{i=1}^s\lambda_i^s>0$ 故证得充分

***** 必要性

假定条件对 $n-1$ 阶实对称阵成立，推导满足条件 $n$ 阶实对称矩阵 $A$ 亦为正定

根据 $A$ 为对称矩阵，即 $a_{ij}=a_{ji}$ 函数做以下变换

\begin{aligned}
f(\vec{x})=&\sum_{i=1}^n\sum_{j=1}^n a_{ij}x_ix_j\\
=&a_{11}x_1x_1+a_{12}x_1x_2 +... + a_{1n}x_1x_n\\
&+a_{21}x_2x_1+a_{22}x_2x_2 +... + a_{1n}x_2x_n\\
&+...\\
&+a_{n1}x_nx_1+a_{22}x_nx_2 +... + a_{1n}x_nx_n\\
=&a_{11}x_1^2+2a_{12}x_1x_2 +... + 2a_{1n}x_1x_n\\
&+a_{22}x_2x_2 +... + a_{1n}x_2x_n\\
&+...\\
&+a_{22}x_nx_2 +... + a_{1n}x_nx_n\\
=&a_{11}x_1^2+2a_{12}x_1x_2 +... + 2a_{1n}x_1x_n\\
&+\sum_{i=2}^n\sum_{j=2}^n a_{ij}x_1x_2\\
\end{aligned}

根据二项式公式

\begin{aligned}
\left(\sum_{i=1}^n a_{1i}x_i\right)^2=&\sum_{i=1}^n\sum_{j=1}^n a_{1i}a_{1j}x_ix_j\\
=&a_{11}a_{11}x_1x_1+a_{11}a_{12}x_1x_2 +... + a_{11}a_{1n}x_1x_n\\
&+a_{12}a_{11}x_2x_1+a_{12}a_{12}x_2x_2 +... + a_{12}a_{1n}x_2x_n\\
& +...\\
&+a_{1n}a_{11}x_nx_1+a_{1n}a_{12}x_nx_2 +... + a_{1n}a_{1n}x_nx_n\\
=&a_{11}^2x_1^2+2a_{11}a_{12}x_1x_2 +... + 2a_{11}a_{1n}x_1x_n\\
&+a_{12}a_{12}x_2x_2 +... + a_{12}a_{1n}x_2x_n\\
& +...\\
&+a_{1n}a_{12}x_nx_2 +... + a_{1n}a_{1n}x_nx_n\\
=&a_{11}^2x_1^2+2a_{11}a_{12}x_1x_2 +... + 2a_{11}a_{1n}x_1x_n\\
&+\sum_{i=2}^n\sum_{j=2}^n a_{1i}a_{1j}x_1x_2
\end{aligned}

由于顺序主子式大于零，故有 $|A_1|=a_{11}>0$ 故有 $\frac{1}{a_{11}}\left(\sum_{i=1}^n a_{1i}x_i\right)^2=a_{11}x_1^2+2a_{12}x_1x_2 +... + 2a_{1n}x_1x_n +\sum_{i=2}^n\sum_{j=2}^n \frac{a_{1i}a_{1j}}{a_{11}}x_1x_2$ 根据此式对 $f(\vec{x})$ 配方

\begin{aligned}
f(\vec{x})=&a_{11}x_1^2+2a_{12}x_1x_2 + ...+ 2a_{1n}x_1x_n+\sum_{i=2}^n\sum_{j=2}^n a_{ij}x_1x_2\\
&=\frac{1}{a_{11}}\left(\sum_{i=1}^n a_{1i}x_i\right)^2-\sum_{i=2}^n\sum_{j=2}^n \frac{a_{1i}a_{1j}}{a_{11}}x_1x_2+\sum_{i=2}^n\sum_{j=2}^n a_{ij}x_1x_2\\
&=\frac{1}{a_{11}}\left(\sum_{i=1}^n a_{1i}x_i\right)^2+\sum_{i=2}^n\sum_{j=2}^n\left(a_{ij}-\frac{a_{1i}a_{1j}}{a_{11}}\right)x_1x_2
\end{aligned}

定义 $b_{ij}=a_{ij}-\frac{a_{1i}a_{1j}}{a_{11}}$ 则有 $f(\vec{x})=\frac{1}{a_{11}}\left(\sum_{i=1}^n a_{1i}x_i\right)^2+\sum_{i=2}^n\sum_{j=2}^n b_{ij}x_ix_j$ 由于 $A$ 为实数阵，故 $\frac{1}{a_{11}}\left(\sum_{i=1}^n a_{1i}x_i\right)^2>0$

所以若 $\sum_{i=2}^n\sum_{j=2}^n b_{ij}x_ix_j>0$ 则 $f(\vec{x})$ 正定，即 $n-1$ 阶矩阵 $B=\left[\begin{matrix}b_{22}&b_{23}&...&b_{2n}\\b_{32}&b_{33}&...&b_{3n}\\...&...&...&...\\b_{n2}&b_{n3}&...&b_{nn}\\\end{matrix}\right]$ 正定，则 $f(\vec{x})$ 正定，即 $A$ 正定

由于 $A$ 为对称矩阵 $A_s$ 亦为对称矩阵，故可做以下行变换，行列式值不变

\begin{aligned}
|A_s|=\left|\begin{matrix}a_{11}&a_{12}&...&a_{1s}\\a_{21}&a_{22}&...&a_{2s}\\...&...&...&...\\a_{s1}&a_{s2}&...&a_{ss}\end{matrix}\right|
\xrightarrow{r_i=r_i-\frac{a_{i1}}{a_{11}}r_1}\left|\begin{matrix}a_{11}&a_{12}&...&a_{1s}\\0&b_{22}&...&b_{2s}\\...&...&...&...\\0&b_{s2}&...&b_{ss}\end{matrix}\right|
=a_{11}\left|\begin{matrix}b_{22}&...&b_{2s}\\...&...&...\\b_{s2}&...&b_{ss}\\\end{matrix}\right|>0
\end{aligned}

故对于矩阵 $B$ 其顺序主子式 $|B_s|=\frac{1}{a_{11}}|A_x|>0$ 根据之前假设 $B$ 正定，故推出 $A$ 正定

由于当 $n=1$ 时显然成立，故根据数学归纳法，命题成立。

* 导数链式法则


若函数 $f(g(x))$ 在 $x_0,g_0=g(x_0)$ 处 $f(g),g(x)$ 可导，则有 $\frac{df(g(x_0))}{dx}=\frac{df(x_0)}{dg}\frac{dg(x_0)}{dx}=f'(x_0)g'(x_0)$

** 证明

\begin{aligned}
\frac{df(g(x_0))}{dx}&=\lim_{\Delta x\to 0}\frac{f(g(x_0+\Delta x))-f(g(x_0))}{\Delta x}\\
&=\lim_{\Delta x\to 0}\left\{\left[\frac{f(g(x_0+\Delta x))-f(g(x_0))}{g(x_0+\Delta x)-g(x_0)}\right]\left[\frac{g(x_0+\Delta x)-g(x_0)}{\Delta x}\right]\right\}
\end{aligned}

根据极限四则运算

\begin{aligned}
\frac{df(g(x_0))}{dx}&=\lim_{\Delta x\to 0}\frac{f(g(x_0+\Delta x))-f(g(x_0))}{g(x_0+\Delta x)-g(x_0)}\lim_{\Delta x\to 0}\frac{g(x_0+\Delta x)-g(x_0)}{\Delta x}\\
&=\lim_{\Delta x\to 0}\frac{f(g_0+\Detla g)-f(g_0)}{\Delta g}\lim_{\Delta x\to 0}\frac{g(x_0+\Delta x)-g(x_0)}{\Delta x}\\
\end{aligned}

由于在 $x_0,g_0=g(x_0)$ 处 $f(g),g(x)$ 可导，故有 

\begin{aligned}
\frac{df(g(x_0))}{dx}&=\lim_{\Delta x\to 0}\frac{f(g_0+\Detla g)-f(g_0)}{\Delta g}\lim_{\Delta x\to 0}\frac{g(x_0+\Delta x)-g(x_0)}{\Delta x}\\
&=\frac{df(x_0)}{dg}\frac{dg(x_0)}{dx}=f'(x_0)g'(x_0)
\end{aligned}

* <<MK12>>克莱默法则

线性方程组满足 

\begin{aligned}
&\begin{cases}
a_{11}x_1+a_{12}x_2+...+a_{1n}x_n=b_1\\
a_{21}x_1+a_{22}x_2+...+a_{2n}x_n=b_2\\
...\\
a_{n1}x_1+a_{n2}x_2+...+a_{nn}x_n=b_n\\
\end{cases}\\
&\left[\begin{matrix}
a_{11}&a_{12}&...&a_{1n}\\
a_{21}&a_{22}&...&a_{2n}\\
...&...&...&...\\
a_{n1}&a_{n2}&...&a_{nn}\\
\end{matrix}\right]
\left[\begin{matrix}
x_1\\
x_2\\
...\\
x_n\\
\end{matrix}\right]
=
\left[\begin{matrix}
b_1\\
b_2\\
...\\
b_n\\
\end{matrix}\right]\\
\end{aligned}

即 $A\vec{x}=\vec{b}$ 则若 $D=|A|\ne0$ ：

（1） 线性方程组有唯一解 $\vec{x}=A^{-1}\vec{b}$

（2） 期解亦可 $x_j=\frac{D_j}{D}$ 其中 $D_j$ 是把 $D$ 中第 $j$ 列元素换成常数项 $\vec{b}$ ，其余保持不变的行列式

** 证明

设 $A$ 可逆，则 $\vec{x}_0=A^{-1}\vec{b}$ 为 $A\vec{x}=\vec{b}$ 的其中一个解，且若 $\vec{x}$ 满足 $A\vec{x}=\vec{b}$ 则有 $A^{-1}A\vec{x}=A^{-1}\vec{b}=\vec{x}_0$ 故 $\vec{x}_0$ 是唯一解

由于 $A^{-1}=\frac{M}{D}$ 其中分子为代数余子式阵的转置 $$M=\left[\begin{matrix}
M_{11}&M_{12}&...&M_{1m}\\
M_{21}&M_{22}&...&M_{2m}\\
...&...&...&...\\
M_{m1}&M_{m2}&...&M_{mm}\\
\end{matrix}\right]^T$$

即 $x_j=\frac{\sum_{i=1}^n M_{ji}b_i}{D}$ 由于任意一列代数余子式与该列元素的乘积和为该矩阵行列式，则有 $$\sum_{i=1}^n M_{ji}b_i=\left|\begin{matrix}
a_{11}&...&a_{1(j-1)}&b_1&a_{1(j+1)}&...&a_{1n}\\
a_{12}&...&a_{2(j-1)}&b_2&a_{2(j+1)}&...&a_{2n}\\
...&...&...&...&...&...&...\\
a_{1n}&...&a_{n(j-1)}&b_n&a_{n(j+1)}&...&a_{nn}\\
\end{matrix}\right|=D_j$$ 证毕

* 偏导数与全微分

** 偏导数，方向导数及全微分

*** <<MK1>>偏导数

函数 $z=f(\vec{x})=f(x_1,x_2,...,x_n),\vec{x}\in D$ 为 $R^n$ 到 $R$ 的映射，若在点 $\vec{x}_0=(x_{1_0},x_{2_0},...,x_{n_0})$ 极限

\begin{aligned}
\lim_{\Delta x_i\to 0}\frac{f(...,x_{i_0}+\Delta x_i,...)-f(x_{1_0},x_{2_0},...,x_{n_0})}{\Delta x_i}=A
\end{aligned}

存在则称 $f(\vec{x})$ 在 $\vec{x}_0$ 点关于 $x_i$ 的偏导数为 $A$ 记为

\begin{aligned}
\frac{\partial f(\vec{x}_0)}{\partial x_i}=A
\end{aligned}

若对于任意 $\vec{x}\in D$ 极限都存在，则有偏导函数

\begin{aligned}
\frac{\partial f(\vec{x})}{\partial x_i}=f_{x_i}(\vec{x})
\end{aligned}

若 $f(\vec{x})$ 对于任意 $\vec{x}\in D$ 对所有分量均可偏导，则 $f(\vec{x})$ 在 $D$ 上可偏导。

**** 性质

***** <<MK2>>线性

函数 $f(\vec{x})=f(x_1,x_2,...,x_n)=z,g(\vec{x})=f(x_1,x_2,...,x_n)=y,\vec{x}\in D$ 为 $R^n$ 到 $R$ 的映射，若在点 $\vec{x}_0=(x_{1_0},x_{2_0},...,x_{n_0})$ 处两个函数对于 $x_i$ 的偏导数存在

则有 $\frac{\partial [Af(\vec{x}_0) + Bg(\vec{x}_0)]}{\partial x_i}=A\frac{\partial f(\vec{x}_0)}{\partial x_i}+b\frac{\partial g(\vec{x}_0)}{\partial x_i}$

****** 证明

\begin{aligned}
\frac{\partial [Af(\vec{x}_0) + Bg(\vec{x}_0)]}{\partial x_i}&=\lim_{\Delta x_i\to 0}\frac{Af(...,x_{i_0}+\Delta x_i,...)+Bg(...,x_{i_0}+\Delta x_i,...)-Af(\vec{x}_0)-Bg(\vec{x}_0)}{\Delta x_i}\\
&=A\lim_{\Delta x_i\to 0}\frac{f(...,x_{i_0}+\Delta x_i,...)-f(\vec{x}_0)}{\Delta x_i}+B\lim_{\Delta x_i\to 0}\frac{g(...,x_{i_0}+\Delta x_i,...)-g(\vec{x}_0)}{\Delta x_i}\\
&=A\frac{\partial f(\vec{x}_0)}{\partial x_i}+b\frac{\partial g(\vec{x}_0)}{\partial x_i}\\
\end{aligned}

***** <<MK3>>偏导数乘法 

函数 $f(\vec{x})=f(x_1,x_2,...,x_n)=z,g(\vec{x})=f(x_1,x_2,...,x_n)=y,\vec{x}\in D$ 为 $R^n$ 到 $R$ 的映射，若在点 $\vec{x}_0=(x_{1_0},x_{2_0},...,x_{n_0})$ 处两个函数对于 $x_i$ 的偏导数存在

则有 $\frac{\partial [f(\vec{x}_0) \cdot g(\vec{x}_0)]}{\partial x_i}=\lim_{\Delta x_i\to 0}f(...,x_{i_0}+\Delta x_i,...)\frac{\partial g(\vec{x}_0)}{x_i}+g(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_i}$

若 $\lim_{\Delta x_i\to 0}f(...,x_{i_0}+\Delta x_i,...)=f(\vec{x}_0)$ 则有

则有 $\frac{\partial [f(\vec{x}_0) \cdot g(\vec{x}_0)]}{\partial x_i}=f(\vec{x}_0)\frac{\partial g(\vec{x}_0)}{x_i}+g(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_i}$

****** 证明

\begin{aligned}
\frac{\partial [f(\vec{x}_0) \cdot g(\vec{x}_0)]}{\partial x_i}&=\lim_{\Delta x_i\to 0}\frac{f(...,x_{i_0}+\Delta x_i,...)g(...,x_{i_0}+\Delta x_i,...)-f(\vec{x}_0)g(\vec{x}_0)}{\Delta x_i}\\
&=\lim_{\Delta x_i\to 0}\left\{\frac{f(...,x_{i_0}+\Delta x_i,...)g(...,x_{i_0}+\Delta x_i,...)-f(...,x_{i_0}+\Delta x_i,...)g(\vec{x}_0)}{\Delta x_i}+\frac{f(...,x_{i_0}+\Delta x_i,...)g(\vec{x}_0)-f(\vec{x}_0)g(\vec{x}_0)}{\Delta x_i}\right\}\\
&=\lim_{\Delta x_i\to 0}\left\{f(...,x_{i_0}+\Delta x_i,...)\frac{g(...,x_{i_0}+\Delta x_i,...)-g(\vec{x}_0)}{\Delta x_i}\right\}+g(\vec{x}_0)\lim_{\Delta x_i\to 0}\left\{\frac{f(...,x_{i_0}+\Delta x_i,...)-f(\vec{x}_0)}{\Delta x_i}\right\}\\
&=\lim_{\Delta x_i\to 0}f(...,x_{i_0}+\Delta x_i,...)\lim_{\Delta x_i\to 0}\left\{\frac{g(...,x_{i_0}+\Delta x_i,...)-g(\vec{x}_0)}{\Delta x_i}\right\}+g(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_i}\\
\end{aligned}

若 $\lim_{\Delta x_i\to 0}f(...,x_{i_0}+\Delta x_i,...)=f(\vec{x}_0)$ 

则有  

\begin{aligned}
\frac{\partial [f(\vec{x}_0) \cdot g(\vec{x}_0)]}{\partial x_i}=f(\vec{x}_0)\frac{\partial g(\vec{x}_0)}{x_i}+g(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_i}
\end{aligned}

***** <<MK4>>偏导数除法

函数 $f(\vec{x})=f(x_1,x_2,...,x_n)=z,g(\vec{x})=f(x_1,x_2,...,x_n)=y,\vec{x}\in D$ 为 $R^n$ 到 $R$ 的映射，若在点 $\vec{x}_0=(x_{1_0},x_{2_0},...,x_{n_0})$ 处两个函数对于 $x_i$ 的偏导数存在

则有 $\frac{\partial \left[\frac{f(\vec{x}_0)}{g(\vec{x}_0)}\right]}{\partial x_i}=\lim_{\Delta x_i\to 0}\frac{1}{g(...,x_{i_0}+\Delta x_i,...)}\frac{g(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_i}-f(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_i}}{g(\vec{x}_0)}$ 其中 $g(\vec{x}_0)\ne 0,\lim_{\Delta x_i\to 0}\frac{1}{g(...,x_{i_0}+\Delta x_i,...)}\ne 0$

若有 $\lim_{\Delta x_i\to 0}g(...,x_{i_0}+\Delta x_i,...)=g(\vec{x}_0)$ 

则有 $\frac{\partial \left[\frac{f(\vec{x}_0)}{g(\vec{x}_0)}\right]}{\partial x_i}=\frac{g(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_i}-f(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_i}}{g(\vec{x}_0)^2}$

****** 证明

\begin{aligned}
\frac{\partial \left[\frac{f(\vec{x}_0)}{g(\vec{x}_0)}\right]}{\partial x_i}&=\lim_{\Delta x_i\to 0}\frac{\frac{f(...,x_{i_0}+\Delta x_i,...)}{g(...,x_{i_0}+\Delta x_i,...)}-\frac{f(\vec{x}_0)}{g(\vec{x}_0)}}{\Delta x_i}\\
&=\lim_{\Delta x_i\to 0}\frac{f(...,x_{i_0}+\Delta x_i,...)g(\vec{x}_0)-g(...,x_{i_0}+\Delta x_i,...)f(\vec{x}_0)}{\Delta x_ig(...,x_{i_0}+\Delta x_i,...)g(\vec{x}_0)}\\
&=\lim_{\Delta x_i\to 0}\frac{1}{g(...,x_{i_0}+\Delta x_i,...)g(\vec{x}_0)}\lim_{\Delta x_i\to 0}\frac{f(...,x_{i_0}+\Delta x_i,...)g(\vec{x}_0)-g(\vec{x}_0)f(\vec{x}_0)+g(\vec{x}_0)f(\vec{x}_0)-g(...,x_{i_0}+\Delta x_i,...)f(\vec{x}_0)}{\Delta x_i}\\
&=\frac{1}{g(\vec{x}_0)}\lim_{\Delta x_i\to 0}\frac{1}{g(...,x_{i_0}+\Delta x_i,...)}\left\{g(\vec{x}_0)\lim_{\Delta x_i\to 0}\frac{f(...,x_{i_0}+\Delta x_i,...)-f(\vec{x}_0)}{\Delta x_i}-f(\vec{x}_0)\lim_{\Delta x_i\to 0}\frac{g(...,x_{i_0}+\Delta x_i,...)-g(\vec{x}_0)}{\Delta x_i}\right\}\\
&=\lim_{\Delta x_i\to 0}\frac{1}{g(...,x_{i_0}+\Delta x_i,...)}\frac{g(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{\partial x_i}-f(\vec{x}_0)\frac{\partial g(\vec{x}_0)}{\partial x_i}}{g(\vec{x}_0)}\\

\end{aligned}

若 $\lim_{\Delta x_i\to 0}g(...,x_{i_0}+\Delta x_i,...)=g(\vec{x}_0)$ 

则有 

\begin{aligned}
\frac{\partial \left[\frac{f(\vec{x}_0)}{g(\vec{x}_0)}\right]}{\partial x_i}=\frac{g(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_i}-f(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_i}}{g(\vec{x}_0)^2}\
\end{aligned}

*** 方向导数

函数 $z=f(\vec{x})=f(x_1,x_2,...,x_n),\vec{x}\in D$ 为 $R^n$ 到 $R$ 的映射，向量 $\vec{v}\in R^n$ 为长度为 $1$ 与 $x_i$ 轴夹角为 $\cos \alpha_i$ 的单位向量 $i=1,2,...,n$

若 $\vec{x}_0\in D$ 极限

\begin{aligned}
\frac{\partial f(\vec{x})}{\partial \vec{v}}=\lim_{t\to 0^+}\frac{f(\vec{x}_0+t\vec{v})-f(\vec{x}_0)}{t}=A
\end{aligned}

存在，则称 $f(\vec{x})$ 在 $\vec{x}_0$ 点沿 $\vec{v}$ 方向的导数为 $A$

*** 全微分

函数 $z=f(\vec{x})=f(x_1,x_2,...,x_n),\vec{x}\in D$ 为 $R^n$ 到 $R$ 的映射

若在 $\vec{x}_0=(x_{1_0},...,x_{n_0})\in D$ 点处存在一系列实数 $A_i,i=1,2,...,n$ 使得以下形式成立

\begin{aligned}
\Delta z&=f(\vec{x}_0+\Delta\vec{x})-f(\vec{x}_0)\\
&=\sum_{i=1}^n A_i \Delta x_i+o(|\Delta\vec{x}|)\\
\end{aligned}

且 $o(|\Delta\vec{x}|)$ 满足 $\lim_{|\Delta\vec{x}|\to 0}\frac{o(|\Delta\vec{x}|)}{|\Delta\vec{x}|}=0$ 则称函数 $f(\vec{x})$ 在 $\vec{x}_0$ 点可微，且定义

\begin{aligned}
\lim_{|\Delta\vec{x}|\to 0}\Delta z&=\lim_{|\Delta\vec{x}|\to 0}\left\{f(\vec{x}_0+\Delta\vec{x})-f(\vec{x}_0)\right\}\\
&=\lim_{|\Delta\vec{x}|\to 0}\left\{\sum_{i=1}^n A_i \Delta x_i+o(|\Delta\vec{x}|)\right\}\\
&\Rightarrow dz=\sum_{i=1}^n A_i dx_i\\
\end{aligned}

称为函数 $f(\vec{x})$ 在 $\vec{x}_0$ 点的全微分。

注1： $A_i,i=1,2,...,n$ 与 $\Delta \vec{x}$ 的长度，方向均无关

注2： $\lim_{|\Delta\vec{x}|\to 0}\frac{o(|\Delta\vec{x}|)}{|\Delta\vec{x}|}=0$ 隐含条件 $\lim_{|\Delta\vec{x}|\to 0}o(|\Delta\vec{x}|)=0$

** 欧几里得空间连续，可导，可微及方向导数关系

*** 可导与方向导数

若函数 $z=f(\vec{x})=f(x_1,x_2,...,x_n),\vec{x}\in D$ 为 $R^n$ 到 $R$ 的映射在 $\vec{x}_0=(x_{1_0},...,x_{n_0})\in D$ 点处存对于 $x_1$ 存在偏导函数

则对于 $\vec{v}=(1,0,...,0)$ 及 $\vec{v}'= (-1,0,...,0)$ 两个方向导数存在，且 $\frac{\partial z}{\partial \vec{v}}=\frac{\partial z}{\partial x_1}=-\frac{\partial z}{\partial \vec{v}'}$

**** 证明

因为导数存在，则有 

\begin{aligned}
\lim_{\Delta x\to 0}\frac{f(x_{1_0}+\Delta x,x_{2_0},...,x_{n_0})-f(x_{1_0},x_{2_0},...,x_{n_0})}{\Delta x}=A
\end{aligned}

又根据方向导数定义：

\begin{aligned}
\frac{f(\vec{x})}{\partial \vec{v}}&=\lim_{t\to 0^+}\frac{f(x_{1_0}+t,x_{2_0},...,x_{n_0})-f(x_{1_0},x_{2_0},...,x_{n_0})}{t}\\
&=\lim_{\Delta x\to 0^+}\frac{f(x_{1_0}+\Delta x,x_{2_0},...,x_{n_0})-f(x_{1_0},x_{2_0},...,x_{n_0})}{\Delta x}=A\\
\frac{f(\vec{x})}{\partial \vec{v}'}&=\lim_{t\to 0^+}\frac{f(x_{1_0}-t,x_{2_0},...,x_{n_0})-f(x_{1_0},x_{2_0},...,x_{n_0})}{t}\\
&=\lim_{t\to 0^-}\frac{f(x_{1_0}+t,x_{2_0},...,x_{n_0})-f(x_{1_0},x_{2_0},...,x_{n_0})}{-t}\\
&=\lim_{\Delta x\to 0^-}\frac{f(x_{1_0}+\Delta x,x_{2_0},...,x_{n_0})-f(x_{1_0},x_{2_0},...,x_{n_0})}{-\Delta x}=-A\\
\end{aligned}

*** <<MK9>>可微与连续

若函数 $z=f(\vec{x})=f(x_1,x_2,...,x_n),\vec{x}\in D$ 为 $R^n$ 到 $R$ 的映射在 $\vec{x}_0=(x_{1_0},...,x_{n_0})\in D$ 点处可微

则函数与 $\vec{x}_0$ 处连续

**** 证明

因为可微，则有 $\Delta z&=f(\vec{x}_0+\Delta\vec{x})-f(\vec{x}_0)=\sum_{i=1}^n A_i \Delta x_i+o(|\Delta\vec{x}|)$ 由于任意点可以写成 $\vec{x}=\vec{x}_0+\Delta \vec{x}$ 故有

\begin{aligned}
\lim_{\vec{x}\to\vec{x}_0}\left\{f(\vec{x})-f(\vec{x}_0)\right\}&=\lim_{|\Delta \vec{x}|\to 0}\left\{f(\vec{x}_0+\Delta\vec{x})-f(\vec{x}_0)\right\}\\
&=\lim_{|\Delta \vec{x}|\to 0}\left\{f\sum_{i=1}^n A_i \Delta x_i+o(|\Delta\vec{x}|)\right\}\\
&=0\\
\end{aligned}

则根据极限四则运算 $\lim_{\vec{x}\to\vec{x}_0}\left\{f(\vec{x})-f(\vec{x}_0)\right\}=\lim_{\vec{x}\to\vec{x}_0}f(\vec{x})-\lim_{\vec{x}\to\vec{x}_0}f(\vec{x}_0)=0\Rightarrow \lim_{\vec{x}\to\vec{x}_0}f(\vec{x})=f(\vec{x}_0)$

*** <<MK6>>可微与偏导

若函数 $z=f(\vec{x})=f(x_1,x_2,...,x_n),\vec{x}\in D$ 为 $R^n$ 到 $R$ 的映射在 $\vec{x}_0=(x_{1_0},...,x_{n_0})\in D$ 点处可微，则函数可偏导，且有 $dz=\sum_{i=1}^n \frac{\partial f(\vec{x}_0)}{\partial x_i} dx_i$

**** 证明

因为可微，则有 $\Delta z&=f(\vec{x}_0+\Delta\vec{x})-f(\vec{x}_0)=\sum_{i=1}^n A_i \Delta x_i+o(|\Delta\vec{x}|)$ 且 $A_i,i=1,2,...,n$ 与 $\Delta \vec{x}$ 的长度，方向均无关

取 $\Delta \vec{x}=(...,0,\Delta x,0,...)$ 则有 $\Delta z&=f(...,x_{i-1_0},x_{i_0}+\Delta x,x_{i+1_0},...)-f(\vec{x}_0)=A_i \Delta x+o(|\Delta\vec{x}|)$ 故做调整

\begin{aligned}
&f(...,x_{i-1_0},x_{i_0}+\Delta x,x_{i+1_0},...)-f(\vec{x}_0)=A_i \Delta x+o(|\Delta\vec{x}|)\\
&A_i=\frac{f(...,x_{i-1_0},x_{i_0}+\Delta x,x_{i+1_0},...)-f(\vec{x}_0)}{\Delta x}-\frac{o(|\Delta\vec{x}|)}{\Delta x}\\
\end{aligned}

则两边取极限，且极限四则运算及 $o(|\Delta\vec{x}|)$ 的定义，并且 $|\Delta\vec{x}|=\Delta x$ 故有：

\begin{aligned}
\lim_{\Detla x\to 0}A_i&=A_i\\
&=\lim_{\Detla x\to 0}\frac{f(...,x_{i-1_0},x_{i_0}+\Delta x,x_{i+1_0},...)-f(\vec{x}_0)}{\Delta x}-\lim_{\Detla x\to 0}\frac{o(|\Delta\vec{x}|)}{\Delta x}\\
&=\frac{\partial f(\vec{x}_0)}{\partial x_i}\\
\end{aligned}

即 $A_i=\frac{\partial f(\vec{x}_0)}{\partial x}$

*** 可微与方向导数

若函数 $z=f(\vec{x})=f(x_1,x_2,...,x_n),\vec{x}\in D$ 为 $R^n$ 到 $R$ 的映射在 $\vec{x}_0=(x_{1_0},...,x_{n_0})\in D$ 点处可微，则方向导数必存在。

若向量 $\vec{v}\in R^n$ 为长度为 $1$ 与 $x_i$ 轴夹角为 $\cos \alpha_i$ 的单位向量 $i=1,2,...,n$ 则在 $\vec{x}_0$ 点沿 $\vec{v}$ 方向的方向导数为 $\frac{\partial f(\vec{x}_0)}{\partial \vec{x}}=\sum_{i=1}^n \frac{\partial f(\vec{x}_0)}{\partial x_i}\cos\alpha_i$

**** 证明

根据方向导数及可微定义

\begin{aligned}
\frac{f(\vec{x})}{\partial \vec{v}}&=\lim_{t\to 0^+}\frac{f(\vec{x}_0+t\vec{v})-f(\vec{x}_0)}{t}\\
&=\lim_{t\to 0^+}\frac{\sum_{i=1}^n \frac{\partial f(\vec{x}_0)}{\partial x_i}\cos\alpha_i t+o(t|\vec{v}|)}{t}\\
&=\sum_{i=1}^n \frac{\partial f(\vec{x}_0)}{\partial x_i}\cos\alpha_i+ \lim_{t\to 0^+}\frac{o(t|\vec{v}|)}{t}\\
&=\sum_{i=1}^n \frac{\partial f(\vec{x}_0)}{\partial x_i}\cos\alpha_i+|\vec{v}|\lim_{t\to 0^+}\frac{o(t|\vec{v}|)}{t|\vec{v}|}\\
&=\sum_{i=1}^n \frac{\partial f(\vec{x}_0)}{\partial x_i}\cos\alpha_i
\end{aligned}

** <<MK5>>可微条件

若函数 $z=f(\vec{x})=f(x_1,x_2,...,x_n),\vec{x}\in D$ 为 $R^n$ 到 $R$ 的映射

在 $\vec{x}_0=(x_{1_0},...,x_{n_0})\in D$ 的所有偏导函数 $f_{x_i}(\vec{x})=\frac{\partial f(\vec{x})}{\partial x_i}$ 在 $x_0\in S\subset D$ 上都存在且在 $\vec{x}_0$ 处连续，

则 $f(\vec{x})$ 在 $\vec{x}_0$ 点可微

*** 证明

根据定义 

\begin{aligned}
\Delta z=&f(\vec{x}_0 + \Delta \vec{x})-f(\vec{x}_0)\\
=&f(x_{1_0} + \Delta x_1,x_{2_0} + \Delta x_2,...,x_{n_0} + \Delta x_n)-f(x_{1_0},x_{2_0} + \Delta x_2,...,x_{n_0} + \Delta x_n)+\\
&f(x_{1_0},x_{2_0} + \Delta x_2,x_{3_0} + \Delta x_3,...,x_{n_0} + \Delta x_n)-f(x_{1_0},x_{2_0},x_{3_0}+\Delta x_3,...,x_{n_0} + \Delta x_n)+\\
&...+\\
&f(x_{1_0},x_{2_0},...,x_{{n-1}_0},x_{n_0} + \Delta x_n)-f(\vec{x}_0)\\
\end{aligned}

对于某一对差 $f(x_{1_0} + \Delta x_1,x_{2_0} + \Delta x_2,...,x_{n_0} + \Delta x_n)-f(x_{1_0},x_{2_0} + \Delta x_2,...,x_{n_0} + \Delta x_n)$ 来说，两者变动为 $\Delta x_1$ ，其他可视为常数

则定义 $u=x_{1_0}+\Delta x_1,u_0=x_{1_0}$ 则有 $\Phi(u)=f(u,x_{2_0} + \Delta x_2,...,x_{n_0} + \Delta x_n),\frac{d\Phi(u)}{du}=\frac{\partial f(\vec{x})}{\partial x_1}$ 

且由于偏导函数 $\frac{\partial f(\vec{x})}{\partial x_1}$ 存在，故对于给定的除 $u$ 以外的参数，存在一个闭区间 $[a,b]$ 使得所有 $u\in (a,b)$ 上导数均存在

根据[[~/OneDrive/大学物理/Note/DiffEq.org][导数基本知识-可导必连续]]得出 $\Phi(u)$ 在某个闭区间 $u\in (a,b)$ 上连续，则存在区域 $[c,d]\subset [a,b]$ 使得函数在 $u\in(c,d)$ 上可导， $u\in [c,d]$ 上连续

综合上述条件根据[[~/OneDrive/大学物理/Note/DiffEq.org][导数基本知识-拉格朗日中值定理]]有 $\Phi(u)-\Phi(u_0)=\Phi(\xi)(u-u_0),\xi\in (u_0,u)$ 

即 $f(x_{1_0} + \Delta x_1,x_{2_0} + \Delta x_2,...,x_{n_0} + \Delta x_n)-f(x_{1_0},x_{2_0} + \Delta x_2,...,x_{n_0} + \Delta x_n)=f_{x_1}(\xi_1,x_{2_0} + \Delta x_2,...,x_{n_0} + \Delta x_n)\Delta x_1$

其他差同理，故有

\begin{aligned}
\Delta z=&f(\vec{x}_0 + \Delta \vec{x})-f(\vec{x}_0)\\
=&f_{x_1}(\xi_1,x_{2_0} + \Delta x_2,...,x_{n_0} + \Delta x_n)\Delta x_1+\\
&f_{x_2}(x_{1_0},\xi_2,x_{3_0} + \Delta x_3,...,x_{n_0} + \Delta x_n)\Delta x_2+\\
&...+\\
&f_{x_n}(x_{1_0},x_{2_0},...,x_{{n-1}_0},\xi_n)\Delta x_n\\
\end{aligned}

其中 $\xi_i\in (x_{i_0},x_{i_0}+\Delta x_i)$ 由于函数连续，故有 $\lim_{\vec{x}\to \vec{x}_0}f_{x_i}(\vec{x})=f_{x_i}(\vec{x}_0)\Rightarrow \lim_{|\Delta \vec{x}|\to 0}\left\{f_{x_i}(\vec{x}_0)-f_{x_i}(\vec{x}_0+\Delta \vec{x})\right\}=0$

故定义 $o_i(|\Delta\vec{x}|)=f_{x_i}(\vec{x}_0)-f_{x_i}(\vec{x}_0+\Delta \vec{x})$ 则函数为 $\Delta \vec{x}$ 的高阶无穷小量满足 $\lim_{|\Delta \vec{x}|\to 0}o_i(|\Delta\vec{x}|)=0$ 且 $f_{x_i}(\vec{x}_0+\Delta \vec{x})=f_{x_i}(\vec{x}_0)+o_i(|\Delta\vec{x}|)$

故原式

\begin{aligned}
\Delta z=&f(\vec{x}_0 + \Delta \vec{x})-f(\vec{x}_0)\\
=&f_{x_1}(\vec{x}_0)\Delta x_1+o_1(|\Delta \vec{x}|)\Delta x_1\\
&f_{x_2}(\vec{x}_0)\Delta x_2+o_2(|\Delta \vec{x}|)\Delta x_2\\
&...+\\
&f_{x_n}(\vec{x}_0)\Delta x_n+o_n(|\Delta \vec{x}|)\Delta x_n\\
=&\sum_{i=1}^n f_{x_i}(\vec{x}_0)\Delta x_i +o(|\Delta \vec{x}|)\\
\end{aligned}

根据极限四则运算  $\lim_{|\Delta \vec{x}|\to 0}o(|\Delta\vec{x}|)=\lim_{|\Delta \vec{x}|\to 0}\sum_{i=1}^n o_i(|\Delta\vec{x}|)\Delta x_i=0$

** 梯度

*** 定义

若函数 $z=f(\vec{x})=f(x_1,x_2,...,x_n),\vec{x}\in D$ 为 $R^n$ 到 $R$ 的映射在 $\vec{x}_0=(x_{1_0},...,x_{n_0})\in D$ 向量 $grad(f(\vec{x}_0))=\nabla f(\vec{x}_0)=\left(\frac{\partial f(\vec{x}_0)}{\partial x_1},\frac{\partial f(\vec{x}_0)}{\partial x_2},...,\frac{\partial f(\vec{x}_0)}{\partial x_n}\right)$

*** 性质

**** $f(\vec{x})=c\Rightarrow \nabla f(\vec{x}_0)=\vec{0}$

\begin{aligned}
\nabla f(\vec{x}_0)&=\left(\frac{\partial f(\vec{x}_0)}{\partial x_1},\frac{\partial f(\vec{x}_0)}{\partial x_2},...,\frac{\partial f(\vec{x}_0)}{\partial x_n}\right)\\
&=(0,0,...,0)\\
&=\vec{0}\\
\end{aligned}

**** $\nabla \{Af(\vec{x}_0)+Bg(\vec{x}_0)\}=A\nabla f(\vec{x}_0)+B\nabla g(\vec{x}_0)$

\begin{aligned}
\nabla \{Af(\vec{x}_0)+Bg(\vec{x}_0)\}&=\left(\frac{\partial [Af(\vec{x}_0)+Bg(\vec{x}_0)]}{\partial x_1},\frac{\partial [Af(\vec{x}_0)+Bg(\vec{x}_0)]}{\partial x_2},...,\frac{\partial [Af(\vec{x}_0)+Bf(\vec{x}_0)]}{\partial x_n}\right)\\
\end{aligned}

根据[[MK2][线性性质]]

\begin{aligned}
\nabla \{Af(\vec{x}_0)+Bg(\vec{x}_0)\}&=\left(A\frac{\partial f(\vec{x}_0)}{\partial x_1}+B\frac{\partial g(\vec{x}_0)}{\partial x_1},A\frac{\partial f(\vec{x}_0)}{\partial x_2}+B\frac{\partial g(\vec{x}_0)}{\partial x_2},...,A\frac{\partial f(\vec{x}_0)}{\partial x_n}+B\frac{\partial g(\vec{x}_0)}{\partial x_n}\right)\\
&=A\nabla f(\vec{x}_0)+B\nabla g(\vec{x}_0)\\
\end{aligned}

**** $\nabla f(\vec{x}_0)\cdot g(\vec{x}_0)=g(\vec{x}_0) \cdot \nabla f(\vec{x}_0)+f(\vec{x}_0) \cdot \nabla g(\vec{x}_0)$

\begin{aligned}
\nabla \{f(\vec{x}_0)g(\vec{x}_0)\}&=\left(\frac{\partial [f(\vec{x}_0)g(\vec{x}_0)]}{\partial x_1},\frac{\partial [f(\vec{x}_0)g(\vec{x}_0)]}{\partial x_2},...,\frac{\partial [f(\vec{x}_0)f(\vec{x}_0)]}{\partial x_n}\right)\\
\end{aligned}

根据[[MK3][乘法]]

\begin{aligned}
\nabla \{f(\vec{x}_0)g(\vec{x}_0)\}&=\left(g(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{\partial x_1}+f(\vec{x}_0)\frac{\partial g(\vec{x}_0)}{\partial x_1},g(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{\partial x_2}+f(\vec{x}_0)\frac{\partial g(\vec{x}_0)}{\partial x_2},...,g(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{\partial x_n}+f(\vec{x}_0)\frac{\partial g(\vec{x}_0)}{\partial x_n}\right)\\
&=g(\vec{x}_0) \cdot \nabla f(\vec{x}_0)+f(\vec{x}_0) \cdot \nabla g(\vec{x}_0)\\
\end{aligned}

**** $\nabla \frac{f(\vec{x}_0)}{g(\vec{x}_0)}=\frac{g(\vec{x}_0)\nabla f(\vec{x}_0)-f(\vec{x}_0)\nabla g(\vec{x}_0)}{g(\vec{x}_0)^2}$


\begin{aligned}
\nabla \frac{f(\vec{x}_0)}{g(\vec{x}_0)}&=\left(\frac{\partial \left[\frac{f(\vec{x}_0)}{g(\vec{x}_0)}\right]}{\partial x_1},\frac{\partial \left[\frac{f(\vec{x}_0)}{g(\vec{x}_0)}\right]}{\partial x_2},...,\frac{\partial \left[\frac{f(\vec{x}_0)}{g(\vec{x}_0)}\right]}{\partial x_n}\right)\\
\end{aligned}

根据[[MK4][偏导数除法]]

\begin{aligned}
\nabla \frac{f(\vec{x}_0)}{g(\vec{x}_0)}&=\left(\frac{g(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_1}-f(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_1}}{g(\vec{x}_0)^2},...,\frac{g(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_n}-f(\vec{x}_0)\frac{\partial f(\vec{x}_0)}{x_n}}{g(\vec{x}_0)^2}\right)\\
&=\frac{g(\vec{x}_0)\nabla f(\vec{x}_0)-f(\vec{x}_0)\nabla g(\vec{x}_0)}{g(\vec{x}_0)^2}\\
\end{aligned}

** 高阶偏导数

*** 定义

若函数 $z=f(x,y)$ 在定义域 $D\in R^2$ 上存在偏导函数 $\frac{\partial f(x,y)}{\partial x},\frac{\partial f(x,y)}{\partial y}$ 且偏导函数亦可导

则有二次偏导函数 $\frac{\partial^2 f(x,y)}{\partial x^2},\frac{\partial^2 f(x,y)}{\partial y^2},\frac{\partial^2 f(x,y)}{\partial y\partial x},\frac{\partial^2 f(x,y)}{\partial x\partial y}$ 为对偏导函数的二次偏导

*** <<MK17>>二次混合偏导顺序

若函数 $z=f(x,y)$ 在定义域 $D\in R^2$ 上存在二次偏导函数 $\frac{\partial^2 f(x,y)}{\partial y\partial x},\frac{\partial^2 f(x,y)}{\partial x\partial y}$ 且在点 $(x_0,y_0)$ 处连续，则有 $\frac{\partial^2 f(x_0,y_0)}{\partial y\partial x}=\frac{\partial^2 f(x_0,y_0)}{\partial x\partial y}$

**** 证明

***** 条件导出函数连续

因为二次偏导函数存在且点 $(x_0,y_0)$ 处连续，则偏导函数必在 $(x_0,y_0)$ 为中心的某个领域内有定义，记作 $O(\vec{r}_0,\delta),\vec{r}_0=(x_0,y_0)$

因为二次偏导函数在 $O(\vec{r}_0,\delta)$ 上有定义，则：

（1）对于任意给定 $y'$ 在 $(x,y')\in O(\vec{r}_0,\delta)$ 上函数 $\frac{\partial f(x,y')}{\partial x}$ 存在且对于 $x$ 连续并可导；
（2）对于任意给定 $x'$ 在 $(x',y)\in O(\vec{r}_0,\delta)$ 上函数 $\frac{\partial f(x',y)}{\partial y}$ 存在且对于 $y$ 连续并可导

同理，由于一次偏导函数在 $O(\vec{x}_0,\delta)$ 上有存在，则：

（1）对于任意给定 $y'$ 在 $(x,y')\in O(\vec{r}_0,\delta)$ 上函数 $f(x,y')$ 存在且对于 $x$ 连续并可导；
（2）对于任意给定 $x'$ 在 $(x',y)\in O(\vec{r}_0,\delta)$ 上函数 $f(x',y)$ 存在且对于 $y$ 连续并可导

***** 推演公式_1

\begin{aligned}
\frac{\partial^2 f(x_0,y_0)}{\partial x\partial y}&=\lim_{y\to y_0}\frac{\lim_{x\to x_0}\frac{f(x,y)-f(x_0,y)}{x-x_0}-\lim_{x\to x_0}\frac{f(x,y_0)-f(x_0,y_0)}{x-x_0}}{y-y_0}\\
&=\lim_{y\to y_0}\left\{\lim_{x\to x_0}\left\{\frac{[f(x,y)-f(x_0,y)]-[f(x,y_0)-f(x_0,y_0)]}{(x-x_0)(y-y_0)}\right\}\right\}\\
&=\lim_{y\to y_0}\left\{\frac{1}{(y-y_0)}\lim_{x\to x_0}\left\{\frac{[f(x,y)-f(x_0,y)]-[f(x,y_0)-f(x_0,y_0)]}{(x-x_0)}\right\}\right\}\\
\end{aligned}

***** 套用拉格朗日定理

对于上式有：

（1）对于函数式 $f(x,y)$ 当 $|y-y_0|<\delta$ 时，存在一个领域范围 $x\in O(x_0,\delta'),\delta'\leq \delta$ 使得 $\sqrt{(x-x_0)^2+(y-y_0)^2}<\delta\Rightarrow (x,y)\in O(\vec{x}_0,\delta)$

（2）对于函数式 $f(x_0,y)$ 当 $|y-y_0|<\delta$ 时成立 $\sqrt{(x_0-x_0)^2+(y-y_0)^2}<\delta\Rightarrow (x,y)\in O(\vec{x}_0,\delta)$

故对于任意 $|y-y_0|<\delta$ 存在一个范围内的 $x\in O(x_0,\delta')$ 使得 $\{(x,y),(x_0,y)\}\subset O(x_0,\delta)$ 

且对于任意 $k\in [y,y_0]$ 都有 $\sqrt{(x-x_0)^2+(k-y_0)^2}\leq\sqrt{(x-x_0)^2+(y-y_0)^2}\Rightarrow \{(x,k),(x_0,k)\}\subset O(\vec{x}_0,\delta)$

则有对于任意 $|y-y_0|<\delta$ ，若 $x\in O(x_0,\delta'),\delta'\leq \delta$ 则有函数 $f(x,k),f(x_0,k)$ 在 $[y_0,y]$ 上连续 $(y_0,y)$ 上可导

根据[[~/OneDrive/大学物理/Note/DiffEq.org][导数基本知识-拉格朗日中值定理]]在 $\sqrt{(x-x_0)^2+(y-y_0)^2}<\delta$ 时有 $[f(x,y)-f(x_0,y)]-[f(x,y_0)-f(x_0,y_0)]=\frac{\partial [f(x,y)-f(x_0,y)]}{\partial y}\big|_{y=\xi},\xi\in (y,y_0)$

***** 证明关于 $x$ 极限

以上结论均在 $\sqrt{(x-x_0)^2+(y-y_0)^2}<\delta$ 条件下成立，由于极限趋于点 $(x_0,y_0)$ 故可视为

（1）对于给定 $|y-y_0|<\delta$ 在 $x\in O(x_0,\delta'),\delta'\leq \delta$ 时有 $[f(x,y)-f(x_0,y)]-[f(x,y_0)-f(x_0,y_0)]=\frac{\partial [f(x,y)-f(x_0,y)]}{\partial y}\big|_{y=\xi},\xi\in (y,y_0)$

（2）假设 $\lim_{x\to x_0}\left\{\frac{[f(x,y)-f(x_0,y)]-[f(x,y_0)-f(x_0,y_0)]}{(x-x_0)}\right\}=A$ 则先定义 $g(x)=\frac{[f(x,y)-f(x_0,y)]-[f(x,y_0)-f(x_0,y_0)]}{(x-x_0)}$ 有 $\forall \epsilon>0.\exists l, \forall |x-x_0|<l\Rightarrow |g(x)-A|<\epsilon$

（3）故对于 $\lim_{x\to x_0}\left\{\frac{\frac{\partial[f(x,\xi)-f(x_0,\xi)]}{\partial y}}{(x-x_0)}\right\}$ 则先定义 $h(x)=\frac{\frac{\partial[f(x,\xi)-f(x_0,\xi)]}{\partial y}}{(x-x_0)}$ 有 $\forall \epsilon>0,\exists l'=\min(l,\delta'), \forall |x-x_0|<\delta\Rightarrow |h(x)-A|<\epsilon$

综合上述条件可以得出当 $|y-y_0|<\delta$ 时 $\lim_{x\to x_0}\left\{\frac{[f(x,y)-f(x_0,y)]-[f(x,y_0)-f(x_0,y_0)]}{(x-x_0)}\right\}=\lim_{x\to x_0}\left\{\frac{\frac{\partial[f(x,\xi)-f(x_0,\xi)]}{\partial y}}{(x-x_0)}\right\}$ 

***** 推演公式_2

由于 $(x_0,\xi)\in O(\vec{x}_0,\delta)$ 故二次偏导函数 $\frac{\partial^2 f(x_0,\xi)}{\partial y \partial x}$ 根据定义存在，即当 $|y-y_0|<\delta$ 有

\begin{aligned}
\frac{\partial^2 f(x,y)}{\partial x\partial y}&=\lim_{y\to y_0}\left\{\lim_{x\to x_0}\left\{\frac{\frac{\partial[f(x,\xi)-f(x_0,\xi)]}{\partial y}}{(x-x_0)}\right\}\right\},&\xi\in(y,y_0)\\
&=\lim_{y\to y_0}\left\{\lim_{x\to x_0}\left\{\frac{\frac{\partial f(x,\xi)}{\partial y}-\frac{\partial f(x_0,\xi)}{\partial y}}{(x-x_0)}\right\}\right\},&\xi\in(y,y_0)\\
&=\lim_{y\to y_0}\left\{\frac{\partial^2 f(x_0,\xi)}{\partial y \partial x}\right\},&\xi\in(y,y_0)\\
\end{aligned}

***** 证明关于 $y$ 极限

同上，根据条件

（1）假设 $\lim_{y\to y_0}\left\{\lim_{x\to x_0}\left\{\frac{[f(x,y)-f(x_0,y)]-[f(x,y_0)-f(x_0,y_0)]}{(x-x_0)(y-y_0)}\right\}\right\}=A$ 则先定义 $g(y)=\frac{[f(x,y)-f(x_0,y)]-[f(x,y_0)-f(x_0,y_0)]}{(x-x_0)(y-y_0)}$ 有 $\forall \epsilon>0.\exists l, \forall |y-y_0|<l\Rightarrow |g(y)-A|<\epsilon$

（3）故对于 $\lim_{y\to y_0}\left\{\frac{\partial^2 f(x_0,\xi)}{\partial y \partial x}\right\},&\xi\in(y,y_0)$ 则先定义 $h(x)=\frac{\partial^2 f(x_0,\xi)}{\partial y \partial x},&\xi\in(y,y_0)$ 有 $\forall \epsilon>0,\exists l'=\min(l,\delta'), \forall |y-y_0|<\delta\Rightarrow |h(y)-A|<\epsilon$

综合上述条件 $\lim_{y\to y_0}\left\{\lim_{x\to x_0}\left\{\frac{[f(x,y)-f(x_0,y)]-[f(x,y_0)-f(x_0,y_0)]}{(x-x_0)(y-y_0)}\right\}\right\}=\lim_{y\to y_0}\left\{\frac{\partial^2 f(x_0,\xi)}{\partial y \partial x}\right\},&\xi\in(y,y_0)$

***** 证明结论

由于  $\frac{\partial^2 f(x,y)}{\partial y\partial x},\frac{\partial^2 f(x,y)}{\partial x\partial y}$ 在点 $(x_0,y_0)$ 处连续，则有 $\frac{\partial^2 f(x_0,y_0)}{\partial x \partial y}=\lim_{y\to y_0}\left\{\frac{\partial^2 f(x_0,\xi)}{\partial y \partial x}\right\}=\frac{\partial^2 f(x_0,y_0)}{\partial y \partial x}, \xi\in(y,y_0)$

** 高阶微分

若函数 $z=f(\vec{x})=f(x_1,x_2,...,x_n)$ 在 $D$ 上可微，则有全微分函数 $\Delta z=\sum_{i=1}^n \frac{\partial f(\vec{x})}{\partial x_i} \Delta x_i+o(|\Delta\vec{x}|),\vec{x}\in D$ 期微分表述为当 $|\Delta x|\to 0$ 时 $dz=\sum_{i=1}^n \frac{\partial f(\vec{x})}{\partial x_i} dx_i$

其中任意一个系数 $\frac{\partial f(\vec{x})}{\partial x_i}$ 为同样维度的多元函数，故若

（1） $a'_i=\frac{\partial f(\vec{x})}{\partial x_i}$ 的所有偏导数存在且在 $\vec{x}_0$ 连续，则根据[[MK5][可微条件]] $\Delta a'_i=\sum_{j=1}^n \frac{\partial^2 f(\vec{x}_0)}{\partial x_i\partial x_j} \Delta x_j+o(|\Delta \vec{x}|)$ 或微分形式 $da'_i=\sum_{j=1}^n \frac{\partial^2 f(\vec{x}_0)}{\partial x_i\partial x_j} dx_j$

（2） $a'_i=\frac{\partial f(\vec{x})}{\partial x_i}$ 的所有偏导数存在且在 $\vec{x}\in D$ 连续，则有偏导函数  $\Delta a'_i=\sum_{j=1}^n \frac{\partial^2 f(\vec{x})}{\partial x_i\partial x_j} \Delta x_j+o(|\Delta \vec{x}|)$ 或微分形式 $da'_i=\sum_{j=1}^n \frac{\partial^2 f(\vec{x})}{\partial x_i\partial x_j} dx_j$

（3） $d(dx)$ 的定义为当 $x$ 变化时 $dx$ 的改变量。即 $u=g(x)=dx$ 则 $\Delta u = g(x_0+\Delta x)-g(x_0)=dx-dx=0$ 故 $d(dx)=0$

将所有系数做全微分并带入原全微分式，得到二次全微分

\begin{aligned}
d^2z=d(dz)&=\sum_{i=1}^n\left\{ \sum_{j=1}^n \left\{\frac{\partial^2 f(\vec{x}_0)}{\partial x_i \partial x_j}dx_j\right\} dx_i\right\}\\
&=\left\{\sum_{i=1}^n \left[dx_i\frac{\partial}{\partial x_i}\right] \right\}^2 f(\vec{x}_0)
\end{aligned}

则同理有 $d^nz=\left\{\sum_{i=1}^n \left[dx_i\frac{\partial}{\partial x_i}\right] \right\}^n f(\vec{x}_0)$

** 向量值函数

*** 导数
函数 $\vec{f}(\vec{x})=\vec{z}\Rightarrow \begin{cases}f_1(x_1,...,x_n)=z_1\\...\\f_m(x_1,...,x_n)=z_n\end{cases}$ 在 $\vec{x}_0$ 的导数定义为所有分量函数偏导组成的矩阵，即

\begin{aligned}
\left(\frac{\partial f_i(\vec{x}_0)}{\partial x_j}\right)_{m\times n}=\left(\begin{matrix}
\frac{\partial f_1(\vec{x}_0)}{\partial x_1 & \frac{\partial f_1(\vec{x}_0)}{\partial x_2}} & ... & \frac{\partial f_1(\vec{x}_0)}{\partial x_n}\\
\frac{\partial f_2(\vec{x}_0)}{\partial x_1 & \frac{\partial f_2(\vec{x}_0)}{\partial x_2}} & ... & \frac{\partial f_2(\vec{x}_0)}{\partial x_n}\\
...\\
\frac{\partial f_m(\vec{x}_0)}{\partial x_1 & \frac{\partial f_m(\vec{x}_0)}{\partial x_2}} & ... & \frac{\partial f_m(\vec{x}_0)}{\partial x_n}\\
\end{matrix}\right)
\end{aligned}

为 $\vec{f}(\vec{x})$ 在 $\vec{x}_0$ 点的导数，或雅可比矩阵，亦可写为 $\vec{f}'(\vec{x}_0),J_f(\vec{x}_0),D_f(\vec{x}_0)$

*** 微分

函数 $\vec{z}=\vec{f}(\vec{x})=\vec{z}\Rightarrow \begin{cases}f_1(x_1,...,x_n)=z_1\\...\\f_m(x_1,...,x_n)=z_n\end{cases}$ 在 $\vec{x}_0$ 可微的定义为函数有以下表达式

\begin{aligned}
\Delta \vec{z} &= \vec{f}(\vec{x}_0+\Delta \vec{x}) - \vec{f}(\vec{x}_0+\Delta \vec{x})=\vec{A}\cdot \Delta\vec{x}+\vec{o}(\Delta \vec{x})\\
&=\left[\begin{matrix}
a_{11}&a_{12}&...&a_{1n}\\
a_{21}&a_{22}&...&a_{2n}\\
...&...&...&...\\
a_{m1}&a_{m2}&...&a_{mn}\\
\end{matrix}\right]
\cdot 
\left[\begin{matrix}
\Delta x_1\\
\Delta x_2\\
...\\
\Delta x_n\\
\end{matrix}\right]
-
\left[\begin{matrix}
o_1(|\Delta \vec{x}|)\\
o_2(|\Delta \vec{x}|)\\
...\\
o_n(|\Delta \vec{x}|)\\
\end{matrix}\right]
\end{aligned}

其中 $\vec{A}$ 为与 $\Delta \vec{x}$ 无关的矩阵， $\lim_{|\Delta\vec{x}|\to 0}o_i(|\Delta\vec{x}|)=0$

微分形式 $d\vec{z}=\vec{A}d\vec{x}$

**** 向量值函数可微充要条件

向量值函数可微的充要条件是每个分量函数都可微。

若可微，则有 $d\vec{z}=\vec{f}'(\vec{x}_0)d\vec{x}$

***** 证明

****** 充分性

若向量值函数可微，即 $\Delta\vec{z}=\vec{A}\Delta\vec{x}+\vec{o}(|\Delta \vec{x}|)$ 即有每一个分量函数 $\Delta z_i=\sum_{j=1}^n a_{ji}\Delta x_j+o_i(|\Delta \vec{x}|)$ 

此式满足 $a_{ij}$ 与 $\Delta\vec{x}$ 无关，且 $\lim_{|\Delta\vec{x}|\to 0}o_i(|\Delta\vec{x}|)=0$

故满足 $f_i(\vec{x})$ 可微，根据[[MK6][可微与偏导]]可得 $\Delta z_i=\sum_{j=1}^n \frac{\partial f_i(\vec{x}_0)}{\partial x_j}\Delta x_j+o_i(|\Delta \vec{x}|)$

则有 w$\Delta\vec{z}=\vec{f}'(\vec{x}_0)\Delta\vec{x}+\vec{o}(|\Delta \vec{x}|)$

****** 必要性

若对于任意 $f_i(\vec{x})$ 可微，则有 $\Delta z_i=\sum_{j=1}^n a_{ji}\Delta x_j+o_i(|\Delta \vec{x}|)$ 且根据[[MK6][可微与偏导]]可得 $\Delta z_i=\sum_{j=1}^n \frac{\partial f_i(\vec{x}_0)}{\partial x_j}\Delta x_j+o_i(|\Delta \vec{x}|)$

上式满足 $\frac{\partial f_i(\vec{x}_0)}{\partial x_j}$ 与 $\Delta x$ 无关，且 $\lim_{|\Delta\vec{x}|\to 0}o_i(|\Delta\vec{x}|)=0$

将上式列为向量得 $\Delta\vec{z}=\vec{f}'(\vec{x}_0)\Delta\vec{x}+\vec{o}(|\Delta \vec{x}|)$ 由于 $\vec{f}'(\vec{x}_0)$ 与 $\Delta \vec{x}$ 无关，且 $\lim_{|\Delta\vec{x}|\to 0}o_i(|\Delta\vec{x}|)=0$

* 多元复合函数求导

** <<MK7>>链式法则

函数 $z=f\circ \vec{y}(\vec{x})$ 为复合映射，其中

（1） $\vec{u}=\vec{y}(\vec{x})$ 为向量值函数 $\vec{x}\in D\subset R^m$

（2） $v=f(\vec{u})$ 位多元函数 $\vec{u}\in S\subset R^n$

若函数满足：

（1） $\vec{u}=\vec{y}(\vec{x})$ 的每个分量函数 $u_i=y_i(\vec{x})$ 在 $\vec{x}_0$ 点对于 $x_i$ 均可导

（2） $v=f(\vec{u})$ 在 $\vec{u}_0=\vec{y}(\vec{x}_0)$ 点处可微

则有：

\begin{aligned}
\frac{\partial f(\vec{y}(\vec{x}_0))}{\parital x_i}=\sum_{j=1}^n\left\{\frac{\partial f(\vec{u}_0)}{\partial u_j}\frac{\partial y_j(\vec{x}_0)}{\partial x_i}\right\}
\end{aligned}

*** 证明

因为可微，则有 $\Delta v = f(\vec{u}_0+\Delta\vec{u})-f(\vec{u}_0) = \sum_{i=1}^n \frac{\partial f(\vec{u}_0)}{\partial u_i}\Delta u_i+ o(|\Delta \vec{u}|)$

则定义 $\Delta\vec{u}=\vec{y}(\vec{x}_0+\Delta\vec{x})-\vec{y}(\vec{x}_0)$ 为 $\vec{u}$ 的线性部分

故有 $\Delta z=f(\vec{y}(\vec{x}_0+\Delta\vec{x}))-f(\vec{y}(\vec{x}_0))=\sum_{i=1}^n \frac{\partial f(\vec{u}_0)}{\partial u_i}\left(\vec{y}(\vec{x}_0+\Delta\vec{x})-\vec{y}(\vec{x}_0)\right)+ o(|\vec{y}(\vec{x}_0+\Delta\vec{x})-\vec{y}(\vec{x}_0)|)$

以上式带入偏导数定义

\begin{aligned}
\frac{\partial f\circ \vec{y}(\vec{x}_0)}{\partial x_i}&=\lim_{\Delta x_i \to 0}\frac{f(\vec{y}(...,x_i+\Delta x_i,...))-f(\vec{y}(\vec{x}_0))}{\Delta x_i}\\
&=\lim_{\Delta x_i \to 0}\frac{\sum_{i=1}^n \frac{\partial f(\vec{u}_0)}{\partial u_i}\left(\vec{y}(...,x_i+\Delta x_i,...)-\vec{y}(\vec{x}_0)\right)+ o(|\vec{y}(...,x_i+\Delta x_i,...)-\vec{y}(\vec{x}_0)|)}{\Delta x_i}\\
&=\sum_{i=1}^n\left\{\frac{\partial f(\vec{u}_0)}{\partial u_i}\frac{\partial y_i(\vec{x}_0)}{\partial x_i}\right\} + \lim_{\Delta x_i \to 0}\frac{o(|\vec{y}(...,x_i+\Delta x_i,...)-\vec{y}(\vec{x}_0)|)}{\Delta x_i}\\
&=\sum_{i=1}^n\left\{\frac{\partial f(\vec{u}_0)}{\partial u_i}\frac{\partial y_i(\vec{x}_0)}{\partial x_i}\right\} + 
\lim_{\Delta x_i \to 0}\left\{\frac{o\left(\sqrt{\sum_{j=1}^n [y_j(...,x_i+\Delta x_i,...)-y_j(\vec{x}_0)]^2}\right)}{\sqrt{\sum_{j=1}^n [y_j(...,x_i+\Delta x_i,...)-y_j(\vec{x}_0)]^2}}\frac{|\Delta x_i|}{\Delta x_i}\sqrt{\sum_{j=1}^n \left[\frac{y_j(...,x_i+\Delta x_i,...)-y_j(\vec{x}_0)}{\Delta x_i}\right]^2\right\}\\
\end{aligned}

因为所有 $y_j(\vec{x})$ 对于 $x_i$ 均可导，则在 $x_i$ 方向连续，故 $\lim_{\Delta x_i \to 0}\sqrt{\sum_{j=1}^n [y_j(...,x_i+\Delta x_i,...)-y_j(\vec{x}_0)]^2}=0$

则有 $\lim_{\Delta x_i \to 0}\frac{o\left(\sqrt{\sum_{j=1}^n [y_j(...,x_i+\Delta x_i,...)-y_j(\vec{x}_0)]^2}\right)}{\sqrt{\sum_{j=1}^n [y_j(...,x_i+\Delta x_i,...)-y_j(\vec{x}_0)]^2}}=0$

由于初等函数一致连续，故有 $\lim_{\Delta x_i \to 0}\sqrt{\sum_{j=1}^n \left[\frac{y_j(...,x_i+\Delta x_i,...)-y_j(\vec{x}_0)}{\Delta x_i}\right]^2}=\sqrt{\sum_{j=1}^n \frac{\partial y_i(\vec{x}_0)}{\partial x_i}^2$ 由于可导，故不为无穷

综上所述 $\lim_{\Delta x_i \to 0}\left\{\frac{o\left(\sqrt{\sum_{j=1}^n [y_j(...,x_i+\Delta x_i,...)-y_j(\vec{x}_0)]^2}\right)}{\sqrt{\sum_{j=1}^n [y_j(...,x_i+\Delta x_i,...)-y_j(\vec{x}_0)]^2}}\frac{|\Delta x_i|}{\Delta x_i}\sqrt{\sum_{j=1}^n \left[\frac{y_j(...,x_i+\Delta x_i,...)-y_j(\vec{x}_0)}{\Delta x_i}\right]^2\right\}=0$

故 $\frac{\partial f\circ \vec{y}(\vec{x}_0)}{\partial x_i}=\sum_{i=1}^n\left\{\frac{\partial f(\vec{u}_0)}{\partial u_i}\frac{\partial y_i(\vec{x}_0)}{\partial x_i}\right\}$ 证毕

*** <<MK8>>向量表述

由于 $\frac{\partial f(\vec{y}(\vec{x}_0))}{\parital x_i}=\sum_{j=1}^n\left\{\frac{\partial f(\vec{u}_0)}{\partial u_j}\frac{\partial y_j(\vec{x}_0)}{\partial x_i}\right\}$ 故一阶偏导数矩阵 $\left[\begin{matrix}\frac{\partial f(\vec{y}(\vec{x}_0))}{\parital x_1} & \frac{\partial f(\vec{y}(\vec{x}_0))}{\parital x_2}&...&\frac{\partial f(\vec{y}(\vec{x}_0))}{\parital x_m}\end{matrix}\right]$ 可用矩阵表述

\begin{aligned}
&\left[\begin{matrix}\frac{\partial f(\vec{y}(\vec{x}_0))}{\parital x_1} & \frac{\partial f(\vec{y}(\vec{x}_0))}{\parital x_2}&...&\frac{\partial f(\vec{y}(\vec{x}_0))}{\parital x_m}\end{matrix}\right]\\
=&\left[\begin{matrix}
\frac{\partial f(\vec{u}_0)}{\parital u_1}&\frac{\partial f(\vec{u}_0)}{\parital u_2}&...&\frac{\partial f(\vec{u}_0)}{\parital u_n}
\end{matrix}\right]
\left[\begin{matrix}
\frac{\partial y_1(\vec{x}_0)}{\partial x_1}&\frac{\partial y_1(\vec{x}_0)}{\partial x_2}&...&\frac{\partial y_1(\vec{x}_0)}{\partial x_m}\\
\frac{\partial y_2(\vec{x}_0)}{\partial x_1}&\frac{\partial y_2(\vec{x}_0)}{\partial x_2}&...&\frac{\partial y_2(\vec{x}_0)}{\partial x_m}\\
...&...&...&...\\
\frac{\partial y_n(\vec{x}_0)}{\partial x_1}&\frac{\partial y_n(\vec{x}_0)}{\partial x_2}&...&\frac{\partial y_n(\vec{x}_0)}{\partial x_m}\\
\end{matrix}\right]\\
\end{aligned}

为方便，可表述为 $(f\circ g)'(\vec{x}_0)=f'(\vec{u}_0)\cdot \vec{y}(\vec{x}_0)$

** 向量值函数复合求导

函数 $\vec{z}=\vec{f}\circ \vec{y}(\vec{x})$ 定义域 $\vec{x}\in D\in R^n$ ，值域 $\vec{z}\in S\subset R^m$ 为复合映射，两个函数拆分分别为

（1） $\vec{u}=\vec{y}(\vec{x}),\vec{x}\in D, \vec{u}\in T\subset R^o$ 

（2） $\vec{v}=\vec{f}(\vec{u}),\vec u\in T, \vec{v}\in S$

若在 $\vec{x}_0\in D$ 点上有以下条件

（1） $\vec{y}(\vec{x})$ 函数的每个分量函数 $u_i=y_i(\vec{x})$ 对于 $x_i$ 均可导

（2） $\vec{f}(\vec{u})$ 函数的每个分量函数 $v_i=f_i(\vec{u})$ 对于点 $\vec{u}_0=\vec{y}(\vec{x}_0)$ 均可微

则根据[[MK7][链式法则]]有 $\vec{z}$ 对于 $x_i$ 的偏导数为

\begin{aligned}
\frac{\partial \vec{f}\circ\vec{g}(\vec{x})}{\partial x_i}=
\left[\begin{matrix}
\sum_{j=1}^o \frac{\partial f_1(\vec{u}_0)}{\partial u_j}\frac{\partial y_j(\vec{u}_0)}{\partial x_i}\\
\sum_{j=1}^o \frac{\partial f_2(\vec{u}_0)}{\partial u_j}\frac{\partial y_j(\vec{u}_0)}{\partial x_i}\\
...\\
\sum_{j=1}^o \frac{\partial f_m(\vec{u}_0)}{\partial u_j}\frac{\partial y_j(\vec{u}_0)}{\partial x_i}\\
\end{matrix}\right]
=\left[\begin{matrix}
\frac{\partial f_1(\vec{u}_0)}{\partial u_1}&\frac{\partial f_1(\vec{u}_0)}{\partial u_2}&...&\frac{\partial f_1(\vec{u}_0)}{\partial u_o}\\
\frac{\partial f_2(\vec{u}_0)}{\partial u_1}&\frac{\partial f_2(\vec{u}_0)}{\partial u_2}&...&\frac{\partial f_2(\vec{u}_0)}{\partial u_o}\\
...&...&...&...\\
\frac{\partial f_m(\vec{u}_0)}{\partial u_1}&\frac{\partial f_m(\vec{u}_0)}{\partial u_2}&...&\frac{\partial f_m(\vec{u}_0)}{\partial u_o}\\
\end{matrix}\right]
\left[\begin{matrix}
\frac{\partial y_1(\vec{u}_0)}{\partial x_i}\\
\frac{\partial y_2(\vec{u}_0)}{\partial x_i}\\
...\\
\frac{\partial y_o(\vec{u}_0)}{\partial x_i}\\
\end{matrix}\right]
=\vec{f}'(\vec{u}_0)\cdot \frac{\partial\vec{y}(\vec{x})}{x_i}
\end{aligned}

** 一阶全微分形式不变性

函数 $z=f\circ \vec{y}(\vec{x})$ 为复合映射，其中

（1） $\vec{u}=\vec{y}(\vec{x})$ 为向量值函数 $\vec{x}\in D\subset R^m$

（2） $v=f(\vec{u})$ 位多元函数 $\vec{u}\in S\subset R^n$

若函数满足：

（1） $\vec{u}=\vec{y}(\vec{x})$ 的每个分量函数 $u_i=y_i(\vec{x})$ 在 $\vec{x}_0$ 点对于 $x_i$ 均可导

（2） $v=f(\vec{u})$ 在 $\vec{u}_0=\vec{y}(\vec{x}_0)$ 点处可微

则根据[[MK8][向量表述]]有
 
\begin{aligned}
dz&=\sum_{i=1}^m \left\{\frac{\partial f(\vec{g}(\vec{x}_0))}{\partial x_i}dx_i\right\}\\
&=\sum_{i=1}^m \left\{\sum_{j=1}^n\left\{\frac{\partial f(\vec{u}_0)}{\partial u_j}\frac{\partial y_j(\vec{x}_0)}{\partial x_i}\right\}dx_i\right\}\\
&=\left[\begin{matrix}
\frac{\partial f(\vec{u}_0)}{\parital u_1}&\frac{\partial f(\vec{u}_0)}{\parital u_2}&...&\frac{\partial f(\vec{u}_0)}{\parital u_n}
\end{matrix}\right]
\left[\begin{matrix}
\frac{\partial y_1(\vec{x}_0)}{\partial x_1}&\frac{\partial y_1(\vec{x}_0)}{\partial x_2}&...&\frac{\partial y_1(\vec{x}_0)}{\partial x_m}\\
\frac{\partial y_2(\vec{x}_0)}{\partial x_1}&\frac{\partial y_2(\vec{x}_0)}{\partial x_2}&...&\frac{\partial y_2(\vec{x}_0)}{\partial x_m}\\
...&...&...&...\\
\frac{\partial y_n(\vec{x}_0)}{\partial x_1}&\frac{\partial y_n(\vec{x}_0)}{\partial x_2}&...&\frac{\partial y_n(\vec{x}_0)}{\partial x_m}\\
\end{matrix}\right]
\left[\begin{matrix}
dx_1\\
dx_2\\
...\\
dx_m
\end{matrix}\right]
\\
&=\left[\begin{matrix}
\frac{\partial f(\vec{u}_0)}{\parital u_1}&\frac{\partial f(\vec{u}_0)}{\parital u_2}&...&\frac{\partial f(\vec{u}_0)}{\parital u_n}
\end{matrix}\right]
\left[\begin{matrix}
\frac{\partial y_1(\vec{x}_0)}{\partial x_1}dx_1+\frac{\partial y_1(\vec{x}_0)}{\partial x_2}dx_2+...+\frac{\partial y_1(\vec{x}_0)}{\partial x_m}dx_m\\
\frac{\partial y_2(\vec{x}_0)}{\partial x_1}dx_1+\frac{\partial y_2(\vec{x}_0)}{\partial x_2}dx_2+...+\frac{\partial y_2(\vec{x}_0)}{\partial x_m}dx_m\\
...\\
\frac{\partial y_n(\vec{x}_0)}{\partial x_1}dx_1+\frac{\partial y_n(\vec{x}_0)}{\partial x_2}dx_2+...+\frac{\partial y_n(\vec{x}_0)}{\partial x_m}dx_m\\
\end{matrix}\right]\\
&=\sum_{i=1}^n\frac{\partial f(\vec{u}_0)}{\parital u_i}\left\{\sum_{j=1}^m \frac{\partial y_i(\vec{x}_0)}{\partial x_j}dx_j \right\}\\
&=\sum_{i=1}^n\frac{\partial f(\vec{u}_0)}{\parital u_i}du_i\right\}
\end{aligned}

即对于复合函数 $z=f(\vec{y}(\vec{x}))$ 来说 $dv=\sum_{i=1}^n\frac{\partial f(\vec{u}_0)}{\parital u_i}du_i\right\}=dz$ 最外复合函数的微分与函数的微分相等

* 多元函数中值定理与Taylor公式

** <<MK10>>中值定理

*** 定义凸区域

若区域 $D\subset R^n$ 为连通集（根据[[~/OneDrive/数学分析/Chap11Note.org][连续函数性质-补充连通定义]]）其中任意两点 $\vec{x},\vec{y}$ 相连的直线属于该区域 $\left\{\vec{x}+t(\vec{y}-\vec{x})\big|t\in [0,1]\right\}\in D$ 则 $D$ 为凸区域

*** 中值定理描述

若 $z=f(\vec{x})$ 在凸区域 $D\subset R^n$ 上有定义

对于任意两点 $\vec{x}=[\begin{matrix}x_1&x_2&...&x_n\end{matrix}]^T,\vec{y}=[\begin{matrix}y_1&y_2&...&y_n\end{matrix}]^T\in D$ 函数在 $\left\{\vec{x}+t(\vec{y}-\vec{x})\big|t\in [0,1]\right\}\in D$ 上可微，

则有

\begin{aligned}
f(\vec{y})-f(\vec{x})&=\sum_{i=1}^n\frac{\partial f(\vec{x}+\theta(\vec{y}-\vec{x}))}{\partial x_i}(y_i-x_i) &,\theta\in (0,1)\\
&=\left[\begin{matrix}
\frac{\partial f(\vec{x}+\theta(\vec{y}-\vec{x}))}{\partial x_1}&\frac{\partial f(\vec{x}+\theta(\vec{y}-\vec{x}))}{\partial x_2}&...&\frac{\partial f(\vec{x}+\theta(\vec{y}-\vec{x}))}{\partial x_n}
\end{matrix}\right]
\left[\begin{matrix}
y_1-x_1\\
y_2-x_2\\
...\\
y_n-x_n\\
\end{matrix}\right]&,\theta\in (0,1)\\
&=f'(\vec{x}+\theta(\vec{y}-\vec{x}))\cdot (\vec{y}-\vec{x})&,\theta\in (0,1)\\
\end{aligned}

*** 定理证明

因为 $D\subset R^n$ 为凸区域，则 $S=\left\{\vec{x}+t(\vec{y}-\vec{x})\big|t\in [0,1]\right\}\in D$

因为函数在 $\left\{\vec{x}+t(\vec{y}-\vec{x})\big|t\in [0,1]\right\}\in D$ 上可微，则有对于任何点 $\vec{x}+t(\vec{y}-\vec{x})$ 来说有

\begin{aligned}
\Delta z&=f(\vec{x}+t(\vec{y}-\vec{x})+\Delta \vec{x})-f(\vec{x}+t(\vec{y}-\vec{x}))\\
&=\sum_{i=1}^n \frac{\partial f(\vec{x}+t(\vec{y}-\vec{x}))}{\partial x_i}\Delta x_i + o(|\Delta \vec{x}|)
\end{aligned}

定义函数 $\Phi(t)=f(\vec{x}+t(\vec{y}-\vec{x}))$ 则导数为

\begin{aligned}
\frac{d(\Phi(t_0))}{dt}&=\lim_{\Delta t\to 0}\frac{\Phi(t_0+\Delta t)-\Phi(t_0)}{\Delta t}\\
&=\lim_{\Delta t\to 0}\frac{f(\vec{x}+(t_0+\Delta t)(\vec{y}-\vec{x}))-f(\vec{x}+t_0(\vec{y}-\vec{x}))}{\Delta t}\\
&=\lim_{\Delta t\to 0}\frac{f(\vec{x}+(t_0)(\vec{y}-\vec{x})+\Delta t(\vec{y}-\vec{x}))-f(\vec{x}+t_0(\vec{y}-\vec{x}))}{\Delta t}\\
&=\lim_{\Delta t\to 0}\frac{\sum_{i=1}^n \left\{\frac{\partial f(\vec{x}+t(\vec{y}-\vec{x}))}{\partial x_i}\Delta t(y_i-x_i)\right\} + o(|\Delta \vec{x}|)}{\Delta t}\\
&=\sum_{i=1}^n \left\{\frac{\partial f(\vec{x}+t(\vec{y}-\vec{x}))}{\partial x_i}(y_i-x_i)\right\}+\lim_{\Delta t\to 0}\frac{o(|\Delta \vec{x}|)}{\Delta t}
\end{aligned}

其中最后一项有

\begin{aligned}
\lim_{\Delta t\to 0}\frac{o(|\Delta \vec{x}|)}{\Delta t}&=\lim_{\Delta t\to 0}\left\{\frac{o(|\Delta \vec{x}|)}{|\Delta \vec{x}|}\frac{|\Delta \vec{x}|}{|\Delta t|}\frac{|\Delta t|}{\Delta t}\right\}\\
&=\lim_{\Delta t\to 0}\left\{o(\frac{\sqrt{\sum_{i=1}^n \Delta t^2(y_i-x_i)^2})}{\sqrt{\sum_{i=1}^n \Delta t^2(y_i-x_i)^2}}\frac{\sqrt{\sum_{i=1}^n \Delta t^2(y_i-x_i)^2}}{|\Delta t|}\frac{|\Delta t|}{\Delta t}\right\}\\
&=\lim_{\Delta t\to 0}\left\{\frac{o(\sqrt{\sum_{i=1}^n \Delta t^2(y_i-x_i)^2})}{\sqrt{\sum_{i=1}^n \Delta t^2(y_i-x_i)^2}}\right\}\lim_{\Delta t\to 0}\left\{\frac{\sqrt{\sum_{i=1}^n \Delta t^2(y_i-x_i)^2}}{|\Delta t|}\right\}\lim_{\Delta t\to 0}\left\{\frac{|\Delta t|}{\Delta t}\right\}\\
&=0\cdot\lim_{\Delta t\to 0}\sqrt{\sum_{i=1}^n \frac{\Delta t^2(y_i-x_i)^2}{\Delta t}}\cdot \pm 1\\
&=0\cdot\lim_{\Delta t\to 0}\sqrt{\sum_{i=1}^n (y_i-x_i)^2}\cdot \pm 1\\
&=0
\end{aligned}

因为 $|\vec{y}-\vec{x}|=\sqrt{\sum_{i=1}^n(y_i-x_i)^2}$ 不为无限大。

故 $\frac{d(\Phi(t_0))}{dt}=\sum_{i=1}^n \left\{\frac{\partial f(\vec{x}+t_0(\vec{y}-\vec{x}))}{\partial x_i}(y_i-x_i)\right\},t_0\in[0,1]$ 故 $\Phi(t)$ 在 $(0,1)$ 上可导 $[0,1]$ 上连续，则应用一元函数[[~/OneDrive/大学物理/Note/DiffEq.org][导数基本知识-拉格朗日中值定理]]可得

\begin{aligned}
&\frac{d\Phi(\theta)}{dt}=\frac{\Phi(1)-\Phi(0)}{1}&\theta\in(0,1)\\
&\sum_{i=1}^n \left\{\frac{\partial f(\vec{x}+\theta(\vec{y}-\vec{x}))}{\partial x_i}(y_i-x_i)\right\}=f(\vec{y})-f(\vec{x})&\theta\in(0,1)\\
&f(\vec{y})-f(\vec{x})=\sum_{i=1}^n \left\{\frac{\partial f(\vec{x}+\theta(\vec{y}-\vec{x}))}{\partial x_i}(y_i-x_i)\right\}=f'(\vec{x}+\theta(\vec{y}-\vec{x}))\cdot (\vec{y}-\vec{x})&,\theta\in (0,1)\\
\end{aligned}

** <<MK16>>多元函数Taylor公式

若 $f=(\vec{x})$ 对于领域 $U=O(\vec{x}_0,r)$ 内有有 $k+1$ 阶连续偏导，则对于任意点  $\vec{x}_0+\Delta\vec{x}\in U$ 有以下Taylor展开式

\begin{aligned}
f(\vec{x}_0+\Delta\vec{x})&=\sum_{i=0}^k \frac{1}{i!}\left(\sum_{j=1}^n\Delta x_j\frac{\partial}{\partial x_j}\right)^i f(\vec{x}_0)+R_{k+1}
\end{aligned}

其中余项 $R_{k+1}$ 的拉格朗日余项表达式为

\begin{aligned}
R_{k+1}=\frac{1}{(k+1)!}\left(\sum_{j=1}^n\Delta x_j\frac{\partial}{\partial x_j}\right)^{k+1}f(\vec{x}_0+\theta\Delta\vec{x}),\theta\in[0,1]
\end{aligned}

若满足：

（1） $\lim_{k\to\infty}R_{k+1}=0$

（2） $S=\sum_{i=1}^\infty \frac{1}{i!}\left(\sum_{j=1}^n\Delta x_j\frac{\partial}{\partial x_j}\right)^i f(\vec{x}_0)y$ 即无穷级数 $S$ 收敛

则Taylor展开成立 

*** 证明

**** 定义辅助函数 $\Phi(t)$

构造辅助函数 $\Phi(t)=f(\vec{x}_0+t\Delta\vec{x}),t\in [0,1]$ 由于领域为凸区域，故点集 $\left\{\vec{x}_0+t\Delta\vec{x}\big|t\in[0,1]\right\}\subset U$ 故辅助函数在定义域内有定义

由于 $\vec{x}_0+t\Delta{x}\in U$ 故函数 $f(\vec{x})$ 在 $\vec{x}_0+t\Delta\vec{x}$ 处有 $k+1$ 阶连续偏导，即 $k$ 阶可微。

由于 $k$ 阶可微，根据[[MK9][可微与连续]]得 $f(\vec{x}_0+t\Delta\vec{x}), t\in[0,1]$ 的所有点连续

由于 $\vec{g}(t)=\vec{x}_0+t\Delta\vec{x}$ 有任意阶连续偏导，故复合函数 $\Phi(t)=f\circ\vec{g}(t)$ 在 $t\in(0,1)$ 处且在 $k$ 阶满[[MK7][链式法则]]条件，故 $k+1$ 阶可导

综上所述 $\Phi(t)$ 在 $t\in[0,1]$ 有定义，且在 $t\in[0,1]$ 连续 $t\in(0,1)$ 可导

**** 演算 $\frac{d^u\Phi(t_0)}{dt^u}$

故函数 $\Phi(t)$ 为复合函数，即 $\Phi(t)=f\circ\vec{g}(t)$ 其中 $\vec{g}(t)$ 为 $R\to R^n$ 的映射，

根据条件 $f(\vec{x})$ 在点 $\vec{x}+t_0\Delta\vec{x}=\vec{g}(t_0)$ 点处可微（所有偏导连续），且 $\frac{\partial g_i(t_0)}{\partial t}=\Delta x_i$ 可导，故根据[[MK7][链式法则]]有

\begin{aligned}
\frac{d\Phi(t_0)}{dt}&=\sum_{i=1}^n \frac{\partial f(\vec{x}_0+t_0\Delta\vec{x})}{\partial x_i}\frac{\partial \vec{g}(t_0)}{\partial t}\\
&=\sum_{i=1}^n \frac{\partial f(\vec{x}_0+t_0\Delta\vec{x})}{\partial x_i}\Delta x_i\\
&=\left(\sum_{i=1}^n \Delta x_i\frac{\partial}{\partial x_i}\right)f(\vec{x}_0+t_0\Delta\vec{x})
\end{aligned}

对于二阶导数 $\frac{d^2\Phi(t_0)}{dt^2}$ 可做如下推导

\begin{aligned}
\frac{d^2\Phi(t_0)}{dt^2}&=\frac{d}{dt}\left(\frac{d\Phi(t_0)}{dt}\right)\\
&=\frac{d}{dt}\left(\sum_{i=1}^n \frac{\partial f(\vec{x}_0+t_0\Delta\vec{x})}{\partial x_i}\Delta x_i\right)\\
&=\sum_{i=1}^n \Delta x_i\frac{d}{dt}\left(\frac{\partial f(\vec{x}_0+t_0\Delta\vec{x})}{\partial x_i}\right)\\
\end{aligned}

同理 $f_{x_i}(\vec{x}_0+t\Delta\vec{x})=\frac{\partial f(\vec{x}_0+t\Delta\vec{x})}{\partial x_i}$ 亦可看为复合函数 $f_{x_i}\circ \vec{g}(t)$

同理 $f_{x_i}(\vec{x})$ 在点 $\vec{x}+t_0\Delta\vec{x}=\vec{g}(t_0)$ 点处可微（所有偏导连续），且 $\frac{\partial g_i(t_0)}{\partial t}=\Delta x_i$ 可导，故根据[[MK7][链式法则]]有

\begin{aligned}
\frac{d}{dt}\left(\frac{\partial f(\vec{x}_0+t_0\Delta\vec{x})}{\partial x_i}\right)&=\sum_{j=1}^n \frac{\partial^2 f(\vec{x}_0+t_0\Delta\vec{x})}{\partial x_i\partial x_j}\frac{\partial \vec{g}(t_0)}{\partial t}\\
&=\sum_{j=1}^n \frac{\partial^2 f(\vec{x}_0+t_0\Delta\vec{x})}{\partial x_i\partial x_j}\Delta x_j\\
\end{aligned}

带入上式得

\begin{aligned}
\frac{d^2\Phi(t_0)}{dt^2}&=\sum_{i=1}^n \left\{\Delta x_i\sum_{j=1}^n \left\{\frac{\partial^2 f(\vec{x}_0+t_0\Delta\vec{x})}{\partial x_i\partial x_j}\Delta x_j\right\}\right\}\\
&=\left(\sum_{i=1}^n \Delta x_i\frac{\partial}{\partial x_i}\right)^2f(\vec{x}_0+t_0\Delta\vec{x})
\end{aligned}

同理可得，对于 $\Phi(t_0)$ 的 $u$ 阶导数 $u\leq k+1$ 有

\begin{aligned}
\frac{d^u\Phi(t_0)}{dt^u}&=\left(\sum_{i=1}^n \Delta x_i\frac{\partial}{\partial x_i}\right)^uf(\vec{x}_0+t_0\Delta\vec{x})
\end{aligned}

**** 对 $\Phi(1)$ 在 $t=0$ 处使用一元函数泰勒展开

由于 $\Phi(t)$ 在 $t\in[0,1]$ 有定义，且在 $t\in[0,1]$ 连续 $t\in(0,1)$ 可导，故根据[[~/OneDrive/数学分析/Chap10Note.org][幂级数-幂级数展开-补充2：Taylor公式]]有

\begin{aligned}
\Phi(1)&=\sum_{i=0}^k \frac{1}{i!}\frac{d^i\Phi(0)}{dt^i}(1-0)^i+R_n(x)\\
&=\sum_{i=0}^k \frac{1}{i!}\frac{d^i\Phi(0)}{dt^i}+R_n(x)
\end{aligned}

带入之前证明得

\begin{aligned}
f(\vec{x}_0+\Delta\vec{x})&=\sum_{i=0}^k \frac{1}{i!}\left(\sum_{j=1}^n \Delta x_j\frac{\partial}{\partial x_j}\right)^if(\vec{x}_0)+R_n(x)
\end{aligned}

同理根据[[~/OneDrive/数学分析/Chap10Note.org][幂级数-幂级数展开-补充2：Taylor公式]]的拉格朗日余项有

\begin{aligned}
R_n(x)&=\frac{1}{(k+1)!}\frac{d^{k+1}\Phi(\theta)}{dt^{k+1}}(1-0)^{n+1} &\theta\in [0,1]\\
&=\frac{1}{(k+1)!}\frac{d^{k+1}\Phi(\theta)}{dt^{k+1}}&\theta\in [0,1]\\
\end{aligned}

同样带入之前证明有

\begin{aligned}
R_n(x)&=\frac{1}{(k+1)!}\left(\sum_{j=1}^n \Delta x_j\frac{\partial}{\partial x_j}\right)^{k+1}f(\vec{x}_0+\theta\Delta\vec{x}) &\theta\in [0,1]\\
\end{aligned}

* 隐函数

** 一元隐函数存在定理

若二元函数 $F(x,y)$ 满足下列条件：

（1） $F(x_0,y_0)=0$

（2） 存在闭矩形 $D=\left\{(x,y)\big||x-x_0|<a,|y-y_0|<b\right\}$ 上函数连续且具有连续偏导

（3） $F_y(x_0,y_0)\ne0$

则有

（1） 在 $(x_0,y_0)$ 点附近可以根据函数方程 $F(x,y)=0$ 来确定隐函数 $y=f(x), x\in O(x_0,\rho)$

（2） 隐函数 $y=f(x)$ 在一定领域 $O(x_0,\rho)$ 内连续

（3） 隐函数 $y=f(x)$ 在一定领域 $O(x_0,\rho)$ 内有连续的导数，且 $\frac{dy}{dx}=-\frac{F_x(x,y)}{F_y(x,y)}$

*** 证明

**** 证明有唯一映射关系 $y=f(x)$

由于偏导数连续，故 $F_y(x,y)=\frac{\partial F(x,y)}{\partial y}$ 在 $D$ 上连续

假设 $F_y(x_0,y_0)>0$ 由于连续，则必有一个闭矩形 $D^*=\left\{(x,y)\big||x-x_0|\leq a^*\leq a,|y-y_0|\leq b^*\leq b\right\}$ 使得 $(x,y)\in D^*\Rightarrow F_y(x,y)>0$ 

即函数对于给定 $x$ 关于 $y$ 单调递增，由于 $F_y(x_0,y_0)>0,(x_0,y_0)\in D^*,F(x_0,y_0)=0$ 故得 $F_x(x_0,y_0+b^*)>0,F_x(x_0,y_0+b^*)<0$

又由于偏导数连续，则根据[[MK5][可微条件]]推出可微，且根据[[MK9][可微与连续]]可推出连续，故存在区域 $D'=\left\{(x,y)\big||x-x_0|<\rho,|y-y_0|\leq b^*\right\}$ 使得成立以下条件

（1） $F_y(x,y)>0,(x,y)\in D'$ 即 $F(x,y)$ 在定义域 $D'$ 上固定 $x$ 时关于 $y$ 单调增加

（2） $F(x,y_0-b^*)<0,x\in(x_0-\rho,x_0+\rho)$

（3） $F(x,y_0+b^*)>0,x\in(x_0-\rho,x_0+\rho)$

故当 $x\in(x_0-\rho,x_0+\rho)$ 时必存在唯一一点 $\bar{y}\in [y_0-b^*,y_0+b^*]$ 使得 $F(x,\bar{y})=0$ 即确定唯一 $x$ 与 $y$ 映射关系 $y=f(x)$

**** 证明连续

假设对于 $(\bar{x},\bar{y})\in D',F(\bar{x},\bar{y})=0$ （由于 $F(x,y_0-b^*)<0,F(x,y_0+b^*)>0$ 故 $y_0-b^*<\bar{y}<y_0+b^*$ ），则有 $\forall \epsilon>0,y\in [\bar{y}-\epsilon,\bar{y}+\epsilon]\cap D'\Rightarrow F_y(\bar{x},y)>0$

定义 $y_u=\min(y_0+b^*,\bar{y}+\epsilon),y_d=\max(y_0-b^*,\bar{y}-\epsilon)$ 则有 $F(\bar{x},y_u)>0,F(\bar{x},y_d)<0$

由于偏导数连续，则根据[[MK5][可微条件]]推出可微，且根据[[MK9][可微与连续]]可推出连续由于点 $(\bar{x},y_u),(\bar{x},y_d)\in D$ 故函数在该两连点连续

故必然存在一个领域 $O(\bar{x},\delta)\cap D'$ 使得 $\forall x\in O(\bar{x},\delta)\cap D'\Rightarrow F(x,y_u)>0,F(x,y_d)<0$

故对于给定 $x'\in O(\bar{x},\delta)$ 有以下条件

（1） $F_y(x',y)>0$ 即 $F(x',y)$ 对于 $y$ 单调递增

（2） $F(x',y_u)>0,F(x',y_d)<0$

故必然存在 $y\in (y_d,y_u)\Rightarrow F(x',y)=0$ 即 $|y-\bar{y}|<\epsilon$

整理条件得 $\forall \epsilon>0, \exists \delta, \forall x\in O(\bar{x},\delta)\cap D'\Rightarrow |y-\bar{y}|=|f(x)-f(\bar{x})|<\epsilon$ 证毕。

**** 证明有连续导数

对于任意一点 $\bar{x}\in O(x_0,\rho)$ 有 $F(\bar{x},\bar{y})=0$ ，且对于任意 $\bar{x}+\Delta x\in D'$ 根据定义有唯一对应的 $\bar{y}+\Delta y$ 使得 $F(\bar{x}+\Delta x,\bar{y}+\Delta y)=0$

由于 $D,D'$ 为闭矩形，故为凸区域。且由于偏导数连续，则根据[[MK5][可微条件]]推出函数在点集 $\left\{(\bar{x},\bar{y})+\theta(\Delta x,\Delta y)\big|\theta\in [0,1]\right\}\in D'$ 上可微。

根据[[MK10][中值定理]]有

\begin{aligned}
&0=F(\bar{x}+\Delta x,\bar{y}+\Delta y) - F(\bar{x},\bar{y})\\
&0=F_x(\bar{x}+\theta\Delta x,\bar{y}+\theta\Delta y)\Delta x+F_y(\bar{x}+\theta\Delta x,\bar{y}+\theta\Delta y)\Delta y&\theta\in(0,1)\\
&\frac{\Delta y}{\Delta x}=-\frac{F_x(\bar{x}+\theta\Delta x,\bar{y}+\theta\Delta y)}{F_y(\bar{x}+\theta\Delta x,\bar{y}+\theta\Delta y)}&\theta\in(0,1)\\
\end{aligned}

且由 $f(x)$ 于连续，故当 $\Delta x\to 0$ 时 $\Delta y\to 0$ ，即 $F(\bar{x}+\Delta x,f(\bar{x}+\Delta x))=0,F(\bar{x},f(\bar{x}))=0$ 因此

\begin{aligned}
\frac{dy}{dx}&=\lim_{\Delta x\to 0}\frac{\Delta y}{\Delta x}\\
&=-\lim_{\Delta x\to 0}\frac{F_x(\bar{x}+\theta\Delta x,\bar{y}+\theta\Delta y)}{F_y(\bar{x}+\theta\Delta x,\bar{y}+\theta\Delta y)}&,\theta\in(0,1)\\
&=-\frac{F_x(\bar{x},\bar{y})}{F_y(\bar{x},\bar{y})}\\
\end{aligned}

由于 $F_y(\bar{x},\bar{y})\ne 0$ 且连续 $F_x(\bar{x},\bar{y})$ 连续，故 $-\frac{F_x(\bar{x},\bar{y})}{F_y(\bar{x},\bar{y})}$ 连续，故 $f(x)$ 有连续导数

** <<MK11>>多元隐函数存在定理

若函数 $F(x_1,x_2,...,x_n,y)=F(\vec{x},y)$ 满足下列条件：

（1） $F(\vec{x}_0,y_0)=0$

（2） 在包含 $(\vec{x}_0,y_0)$ 的闭长方体 $D=\left\{(\vec{x},y)\big||x_i-x_{i_0}|<a_i,|y-y_0|<b\right\}$ 上函数有偏导连续

（3） $F_y(\vec{x}_0,y_0)\ne0$

则有

（1） 在 $(\vec{x}_0,y_0)$ 点附近可以根据函数方程 $F(\vec{x},y)=0$ 来确定隐函数 $y=f(\vec{x}),\vec{x}\in O(\vec{x}_0,\rho)\subset D$ ，值域 $|y-y_0|<b$

（2） 隐函数 $y=f(\vec{x})$ 在一定领域 $O(\vec{x}_0,\rho)\subset D$ 内连续

（3） 隐函数 $y=f(\vec{x})$ 在一定领域 $O(\vec{x}_0,\rho)\subset D$ 内有连续的导数，且 $\frac{dy}{dx_i}=-\frac{F_{x_i}(\vec{x},y)}{F_y(\vec{x},y)}$

*** 证明

**** 证明有唯一映射关系 $y=f(\vec{x})$

由于偏导数连续，故 $F_y(\vec{x},y)=\frac{\partial F(\vec{x},y)}{\partial y}$ 在 $D$ 上连续

假设 $F_y(\vec{x}_0,y_0)>0$ 由于连续，则必有一个闭矩形 $D^*=\left\{(\vec{x},y)\big||x_i-x_{i_0}|\leq a_i^*\leq a,|y-y_0|\leq b^*\leq b\right\}\subset D$ 使得 $(\vec{x},y)\in D^*\Rightarrow F_y(\vec{x},y)>0$ 

即函数对于给定 $\vec{x}$ 关于 $y$ 单调递增，由于 $F_y(\vec{x}_0,y_0)>0,(\vec{x}_0,y_0)\in D^*,F(\vec{x}_0,y_0)=0$ 故得 $F_x(\vec{x}_0,y_0+b^*)>0,F_x(\vec{x}_0,y_0+b^*)<0$

又由于偏导数连续，则根据[[MK5][可微条件]]推出可微，且根据[[MK9][可微与连续]]可推出连续，故存在区域 $D'=\left\{(\vec{x},y)\big||\vec{x}-\vec{x_0}|<\rho,|y-y_0|\leq b^*\right\}$ 使得成立以下条件

（1） $F_y(\vec{x},y)>0,(\vec{x},y)\in D'$ 即 $F(\vec{x},y)$ 在定义域 $D'$ 上固定 $\vec{x}$ 时关于 $y$ 单调增加

（2） $F(\vec{x},y_0-b^*)<0,\vec{x}\in O(\vec{x}_0,\rho)$

（3） $F(\vec{x},y_0+b^*)>0,\vec{x}\in O(\vec{x}_0,\rho)$

故当 $\vec{x}\in O(\vec{x}_0,\rho)$ 时必存在唯一一点 $\bar{y}\in [y_0-b^*,y_0+b^*]$ 使得 $F(\vec{x},\bar{y})=0$ 即确定唯一 $\vec{x}$ 与 $y$ 映射关系 $y=f(\vec{x})$ ，且 $|y-y_0|<b^*\leq b$

**** 证明连续

假设对于 $(\vec{x}',\bar{y})\in D',F(\vec{x}',\bar{y})=0$ （由于 $F(\vec{x},y_0-b^*)<0,F(\vec{x},y_0+b^*)>0$ 故 $y_0-b^*<\bar{y}<y_0+b^*$ ），则有 $\forall \epsilon>0,y\in [\bar{y}-\epsilon,\bar{y}+\epsilon]\cap D'\Rightarrow F_y(\vec{x}',y)>0$

定义 $y_u=\min(y_0+b^*,\bar{y}+\epsilon),y_d=\max(y_0-b^*,\bar{y}-\epsilon)$ 则有 $F(\vec{x}',y_u)>0,F(\vec{x}',y_d)<0$

由于偏导数连续，则根据[[MK5][可微条件]]推出可微，且根据[[MK9][可微与连续]]可推出连续由于点 $(\vec{x}',y_u),(\vec{x}',y_d)\in D$ 故函数在该两连点连续

故必然存在一个领域 $O(\vec{x}',\delta)\cap D'$ 使得 $\forall x\in O(\vec{x}',\delta)\cap D'\Rightarrow F(\vec{x},y_u)>0,F(x,y_d)<0$

故对于给定 $\vec{x}\in O(\vec{x}',\delta)$ 有以下条件

（1） $F_y(\vec{x},y)>0$ 即 $F(\vec{x},y)$ 对于 $y$ 单调递增

（2） $F(\vec{x},y_u)>0,F(\vec{x},y_d)<0$

故必然存在 $y\in (y_d,y_u)\Rightarrow F(x',y)=0$ 即 $|y-\bar{y}|<\epsilon$

整理条件得 $\forall \epsilon>0, \exists \delta, \forall \vec{x}\in O(\vec{x}',\delta)\cap D'\Rightarrow |y-\bar{y}|=|f(x)-f(\bar{x})|<\epsilon$ 证毕。

**** 证明有连续导数导

对于任意一点 $\vec{x}\in O(\vec{x}_0,\rho)$ 有 $F(\vec{x},\bar{y})=0$ ，且对于任意 $(x_1,x_2,...,x_i+\Delta x_i,..,x_n)\in O(\vec{x}_0,\rho)$ 根据定义有唯一对应的 $\bar{y}+\Delta y$ 使得 $F(x_1,x_2,...,x_i+\Delta x_i,..,x_n,\bar{y}+\Delta y)=0$

由于 $D,D'$ 为闭矩形，故为凸区域。且由于偏导数连续，则根据[[MK5][可微条件]]推出函数在点集 $\left\{(x_1,x_2,...,x_i+\theta\Delta x_i,..,x_n,\bar{y}+\theta\Delta y)\big|\theta\in [0,1]\right\}\in D'$ 上可微。

根据[[MK10][中值定理]]有

\begin{aligned}
&0=F(x_1,x_2,...,x_i+\Delta x_i,..,x_n,\bar{y}+\Delta y) - F(\vec{x},\bar{y})\\
&0=F_{x_i}(x_1,x_2,...,x_i+\theta\Delta x_i,..,x_n,\bar{y}+\theta\Delta y)\Delta x_i+F_y(x_1,x_2,...,x_i+\theta\Delta x_i,..,x_n,\bar{y}+\theta\Delta y)\Delta y&\theta\in(0,1)\\
&\frac{\Delta y}{\Delta x_i}=-\frac{F_x(x_1,x_2,...,x_i+\theta\Delta x_i,..,x_n,\bar{y}+\theta\Delta y)}{F_y(x_1,x_2,...,x_i+\theta\Delta x_i,..,x_n,\bar{y}+\theta\Delta y)}&\theta\in(0,1)\\
\end{aligned}

且由 $f(x)$ 于连续，故当 $\Delta x_i\to 0$ 时 $\Delta y\to 0$ 且 $F(\vec{x},y)$ 所有偏导函数连续因此

\begin{aligned}
\frac{dy}{dx_i}&=\lim_{\Delta x\to 0}\frac{\Delta y}{\Delta x_i}\\
&=-\lim_{\Delta x_i\to 0}\frac{F_x(x_1,x_2,...,x_i+\theta\Delta x_i,..,x_n,\bar{y}+\theta\Delta y)}{F_y(x_1,x_2,...,x_i+\theta\Delta x_i,..,x_n,\bar{y}+\theta\Delta y)}&,\theta\in(0,1)\\
&=-\frac{F_{x_i}(\vec{x},\bar{y})}{F_y(\vec{x},\bar{y})}\\
\end{aligned}

由于 $F_y(\vec{x},\vec{y})\ne 0$ 且连续 $F_{x_i}(\vec{x},\bar{y})$ 连续，故 $-\frac{F_{x_i}(\vec{x},\bar{y})}{F_y(\vec{x},\bar{y})}$ 连续，故函数 $f(\vec{x})$ 对于任意 $x_i$ 有连续偏导 

** <<MK13>>向量值隐函数存在定理

若函数组 $\vec{F}(\vec{x},\vec{y})=\begin{cases}F_1(x_1,x_2,...,x_n,y_1,y_2,...,y_m)\\F_2(x_1,x_2,...,x_n,y_1,y_2,...,y_m)\\...\\F_m(x_1,x_2,...,x_n,y_1,y_2,...,y_m)\\\end{cases}$ 满足下列条件

（1） $\vec{F}(\vec{x}_0,\vec{y}_0)=\vec{0}$

（2） 在包含 $(\vec{x}_0,\vec{y}_0)$ 的闭长方体 $G=\left\{(\vec{x},\vec{y})\big||x_i-x_{i_0}|<a_i,|y_i-y_{i_0}|<b_i\right\}$ 上所有分量函数的所有偏导连续

（3） 函数在 $(\vec{x}_0,\vec{y}_0)$ 处关于 $\vec{y}$ 的雅克比行列式不为零，即 $$
\left|\frac{\partial \vec{F}(\vec{x}_0,\vec{y}_0)}{\partial \vec{y}}\right|=\left|\begin{matrix}
&\frac{\partial F_1(\vec{x}_0,\vec{y}_0)}{\partial y_1}&\frac{\partial F_1(\vec{x}_0,\vec{y}_0)}{\partial y_2}&...&\frac{\partial F_1(\vec{x}_0,\vec{y}_0)}{\partial y_m}\\
&\frac{\partial F_2(\vec{x}_0,\vec{y}_0)}{\partial y_1}&\frac{\partial F_2(\vec{x}_0,\vec{y}_0)}{\partial y_2}&...&\frac{\partial F_2(\vec{x}_0,\vec{y}_0)}{\partial y_m}\\
&...&...&...&...\\
&\frac{\partial F_m(\vec{x}_0,\vec{y}_0)}{\partial y_1}&\frac{\partial F_m(\vec{x}_0,\vec{y}_0)}{\partial y_2}&...&\frac{\partial F_m(\vec{x}_0,\vec{y}_0)}{\partial y_m}\\
\end{matrix}\right|\ne0$$

则有

（1） 在点 $(\vec{x}_0,\vec{y}_0)$ 的某个领域内可由 $\vec{F}(\vec{x},\vec{y})=0$ 确定唯一向量值隐函数 $\vec{y}=\vec{f}(\vec{x}),\vec{x}\in O(\vec{x}_0,\rho)$ 满足 $\vec{F}\left(\vec{x},\vec{f}(\vec{x})\right)=0,\vec{y}_0=\vec{f}(\vec{x}_0)$ 值域 $|y_i-y_{i_0}|<b_i$

（2） 向量值隐函数在 $\vec{x}\in O(\vec{x}_0,\rho)$ 上连续

（3） 向量值隐函数在 $\vec{x}\in O(\vec{x}_0,\rho)$ 上有连续偏导且导数为 $$\frac{\partial \vec{f}(\vec{x})}{\partial \vec{x}}=\left[\begin{matrix}
\frac{\partial y_1}{\partial x_1}&\frac{\partial y_1}{\partial x_2}&...&\frac{\partial y_1}{\partial x_n}\\
\frac{\partial y_2}{\partial x_1}&\frac{\partial y_2}{\partial x_2}&...&\frac{\partial y_2}{\partial x_n}\\
...&...&...&...\\
\frac{\partial y_m}{\partial x_1}&\frac{\partial y_m}{\partial x_2}&...&\frac{\partial y_m}{\partial x_n}\\
\end{matrix}\right]
=-\left[\begin{matrix}
\frac{\partial F_1}{\partial y_1}&\frac{\partial F_1}{\partial y_2}&...&\frac{\partial F_1}{\partial y_m}\\
\frac{\partial F_2}{\partial y_1}&\frac{\partial F_2}{\partial y_2}&...&\frac{\partial F_2}{\partial y_m}\\
...&...&...&...\\
\frac{\partial F_m}{\partial y_1}&\frac{\partial F_m}{\partial y_2}&...&\frac{\partial F_m}{\partial y_m}\\
\end{matrix}\right]^{-1}
\left[\begin{matrix}
\frac{\partial F_1}{\partial x_1}&\frac{\partial F_1}{\partial x_2}&...&\frac{\partial F_1}{\partial x_n}\\
\frac{\partial F_2}{\partial x_1}&\frac{\partial F_2}{\partial x_2}&...&\frac{\partial F_2}{\partial x_n}\\
...&...&...&...\\
\frac{\partial F_m}{\partial x_1}&\frac{\partial F_m}{\partial x_2}&...&\frac{\partial F_m}{\partial x_n}\\
\end{matrix}\right]$$

*** 证明

基本思路：

假设对于给定 $m$ 定理成立试图证明 $m+1$ 的情况也成立

由于 $m=1$ 的情况可已在[[MK11][多元隐函数存在定理]]中证明，故若以上假设成立，定理成立

**** 设立函数，列出基本结论
设向量值函数  $\vec{F}(\vec{x},\vec{y},u)=\begin{cases}F_1(x_1,x_2,...,x_n,y_1,y_2,...,y_m,u)\\F_2(x_1,x_2,...,x_n,y_1,y_2,...,y_m,u)\\...\\F_{m+1}(x_1,x_2,...,x_n,y_1,y_2,...,y_m,u)\\\end{cases}$ 满足以下3个条件：

（1） $\vec{F}(\vec{x}_0,\vec{y}_0,u_0)=\vec{0}$

（2） 在包含 $(\vec{x}_0,\vec{y}_0,u_0)$ 的闭长方体 $D=\left\{(\vec{x},\vec{y})\big||x_i-x_{i_0}|<a_i,|y_i-y_{i_0}|<b_i,|u-u_0|<c\right\}$ 上所有分量函数的所有偏导连续

（3） 函数在 $(\vec{x}_0,\vec{y}_0,u_0)$ 处关于 $\vec{y},u$ 的雅克比行列 $D'$ 式不为零

由于对于 $m+1$ 维度雅克比行列式不为零，则必有一个 $m$ 维度的（去掉一个分量函数 $F_i,1\leq i\leq m+1$ ）雅克比行列式不为零。

不妨假设由 $F_1,F_2,...,F_m$ 组成函数组雅克比行列式不为零。

由于假设定理在 $m$ 阶成立，且另外两个条件（连续偏导与一点为零）在 $m$ 阶可由 $m+1$ 阶直接推导

则根据分量函数 $F_1,F_2,...,F_m$ 有

（1） 在点 $(\vec{x}_0,\vec{y}_0,u_0)$ 的某个领域内可由 $\vec{F}(\vec{x},\vec{y},u)=0$ 确定唯一向量值隐函数 $\vec{y}=\vec{\Phi}(\vec{x},u),(\vec{x},u)\in O((\vec{x}_0,u_0),\rho_1)$ 满足 $\vec{F}\left(\vec{x},\vec{\Phi}(\vec{x},u),u\right)=\vec{0},\vec{y}_0=\vec{\Phi}(\vec{x}_0,u_0)$ ，值域 $|y_i-y_{i_0}|<b_i$

（2） 向量值隐函数在 $(\vec{x},u)\in O((\vec{x}_0,u_0),\rho_1)$ 上连续

（3） 向量值隐函数在 $(\vec{x},u)\in O((\vec{x}_0,u_0),\rho_1)$ 上有连续偏导且导数为 $$\frac{\partial \vec{\Phi}(\vec{x},u)}{\partial (\vec{x},u)}=\left[\begin{matrix}
\frac{\partial y_1}{\partial x_1}&\frac{\partial y_1}{\partial x_2}&...&\frac{\partial y_1}{\partial x_n}&\frac{\partial y_1}{\partial u}\\
\frac{\partial y_2}{\partial x_1}&\frac{\partial y_2}{\partial x_2}&...&\frac{\partial y_2}{\partial x_n}&\frac{\partial y_2}{\partial u}\\
...&...&...&...\\
\frac{\partial y_m}{\partial x_1}&\frac{\partial y_m}{\partial x_2}&...&\frac{\partial y_m}{\partial x_n}&\frac{\partial y_m}{\partial u}\\
\end{matrix}\right]
=-\left[\begin{matrix}
\frac{\partial F_1}{\partial y_1}&\frac{\partial F_1}{\partial y_2}&...&\frac{\partial F_1}{\partial y_m}\\
\frac{\partial F_2}{\partial y_1}&\frac{\partial F_2}{\partial y_2}&...&\frac{\partial F_2}{\partial y_m}\\
...&...&...&...\\
\frac{\partial F_m}{\partial y_1}&\frac{\partial F_m}{\partial y_2}&...&\frac{\partial F_m}{\partial y_m}\\
\end{matrix}\right]^{-1}
\left[\begin{matrix}
\frac{\partial F_1}{\partial x_1}&\frac{\partial F_1}{\partial x_2}&...&\frac{\partial F_1}{\partial x_n}&\frac{\partial F_1}{\partial u}\\
\frac{\partial F_2}{\partial x_1}&\frac{\partial F_2}{\partial x_2}&...&\frac{\partial F_2}{\partial x_n}&\frac{\partial F_2}{\partial u}\\
...&...&...&...\\
\frac{\partial F_m}{\partial x_1}&\frac{\partial F_m}{\partial x_2}&...&\frac{\partial F_m}{\partial x_n}&\frac{\partial F_m}{\partial u}\\
\end{matrix}\right]$$

**** 推导偏导数

定义雅克比行列式 $$D=\left|\begin{matrix}
\frac{\partial F_1}{\partial y_1}&\frac{\partial F_1}{\partial y_2}&...&\frac{\partial F_1}{\partial y_m}\\
\frac{\partial F_2}{\partial y_1}&\frac{\partial F_2}{\partial y_2}&...&\frac{\partial F_2}{\partial y_m}\\
...&...&...&...\\
\frac{\partial F_m}{\partial y_1}&\frac{\partial F_m}{\partial y_2}&...&\frac{\partial F_m}{\partial y_m}\\
\end{matrix}\right|$$

定义在 $i,j$ 位置上的代数余子式为 $M_{ij}$ ，定义代数余子式阵 $$A=\left[\begin{matrix}
M_{11}&M_{12}&...&M_{1m}\\
M_{21}&M_{22}&...&M_{2m}\\
...&...&...&...\\
M_{m1}&M_{m2}&...&M_{mm}\\
\end{matrix}\right]$$

故逆矩阵为

\begin{aligned}
\left[\begin{matrix}
\frac{\partial F_1}{\partial y_1}&\frac{\partial F_1}{\partial y_2}&...&\frac{\partial F_1}{\partial y_m}\\
\frac{\partial F_2}{\partial y_1}&\frac{\partial F_2}{\partial y_2}&...&\frac{\partial F_2}{\partial y_m}\\
...&...&...&...\\
\frac{\partial F_m}{\partial y_1}&\frac{\partial F_m}{\partial y_2}&...&\frac{\partial F_m}{\partial y_m}\\
\end{matrix}\right]^{-1}=\frac{1}{D}A=\frac{1}{D}\left[\begin{matrix}
M_{11}&M_{12}&...&M_{1m}\\
M_{21}&M_{22}&...&M_{2m}\\
...&...&...&...\\
M_{m1}&M_{m2}&...&M_{mm}\\
\end{matrix}\right]^T
\end{aligned}

故，对于 $u$ 的偏导可写为

\begin{aligned}
\frac{\partial \vec{\Phi}(\vec{x},u)}{\partial u}&=\left[\begin{matrix}
\frac{\partial y_1}{\partial u}\\
\frac{\partial y_2}{\partial u}\\
...\\
\frac{\partial y_m}{\partial u}\\
\end{matrix}\right]
=-\left[\begin{matrix}
\frac{\partial F_1}{\partial y_1}&\frac{\partial F_1}{\partial y_2}&...&\frac{\partial F_1}{\partial y_m}\\
\frac{\partial F_2}{\partial y_1}&\frac{\partial F_2}{\partial y_2}&...&\frac{\partial F_2}{\partial y_m}\\
...&...&...&...\\
\frac{\partial F_m}{\partial y_1}&\frac{\partial F_m}{\partial y_2}&...&\frac{\partial F_m}{\partial y_m}\\
\end{matrix}\right]^{-1}
\left[\begin{matrix}
\frac{\partial F_1}{\partial u}\\
\frac{\partial F_2}{\partial u}\\
...\\
\frac{\partial F_m}{\partial u}\\
\end{matrix}\right]\\
&=-
\left[\begin{matrix}
\frac{1}{D}\sum_{i=1}^m M_{i1}\frac{\partial F_i}{\partial u}\\
\frac{1}{D}\sum_{i=1}^m M_{i2}\frac{\partial F_i}{\partial u}\\
...\\
\frac{1}{D}\sum_{i=1}^m M_{im}\frac{\partial F_i}{\partial u}\\
\end{matrix}\right]\\
\end{aligned}

定义函数 $H(\vec{x},u)=F_{m+1}\left(\vec{x},\vec{\Phi}(\vec{x},u),u\right)$ 由于 $\vec{\Phi}(\vec{x},u)$ 有连续偏导且 $F_{m+1}(\vec{x},\vec{y},u)$ 有连续偏导，故根据[[MK7][链式法则]]得出 $H(\vec{x},u)$ 有连续偏导，且有

\begin{aligned}
\frac{\partial H(\vec{x}_0,u_0)}{\partial u}&=F_{(m+1)u}+\sum_{j=1}^m F_{(m+1)y_j}\frac{\partial y_j}{\partial u}\\
&=F_{(m+1)u}-\sum_{j=1}^m \left\{F_{(m+1)y_j}\left\{\frac{1}{D}\sum_{i=1}^m M_{ij}F_{iu}\right\}\right\}\\
\end{aligned}

由于对于行列式，任意一行或一列的元素与代数余子式的乘积和等于矩阵行列式，且行列式中任意两列互换需要改变符号

故有

\begin{aligned}
\sum_{i=1}^m M_{ij}F_{iu}
&=\left|\begin{matrix}
\frac{\partial F_1}{\partial y_1}&...&\frac{\partial F_1}{\partial y_{i-1}}&\frac{\partial F_1}{\partial u}&\frac{\partial F_1}{\partial y_{i+1}}&...&\frac{\partial F_1}{\partial y_m}\\
\frac{\partial F_2}{\partial y_1}&...&\frac{\partial F_2}{\partial y_{i-1}}&\frac{\partial F_2}{\partial u}&\frac{\partial F_2}{\partial y_{i+1}}&...&\frac{\partial F_2}{\partial y_m}\\
...&...&...&...&...&...\\
\frac{\partial F_m}{\partial y_1}&...&\frac{\partial F_m}{\partial y_{i-1}}&\frac{\partial F_m}{\partial u}&\frac{\partial F_m}{\partial y_{i+1}}&...&\frac{\partial F_m}{\partial y_m}\\
\end{matrix}\right|
=(-1)^{m-j}\left|\begin{matrix}
\frac{\partial F_1}{\partial y_1}&...&\frac{\partial F_1}{\partial y_{i-1}}&\frac{\partial F_1}{\partial y_{i+1}}&...&\frac{\partial F_1}{\partial y_m}&\frac{\partial F_1}{\partial u}\\
\frac{\partial F_2}{\partial y_1}&...&\frac{\partial F_2}{\partial y_{i-1}}&\frac{\partial F_2}{\partial y_{i+1}}&...&\frac{\partial F_2}{\partial y_m}&\frac{\partial F_2}{\partial u}\\
...&...&...&...&...&...\\
\frac{\partial F_m}{\partial y_1}&...&\frac{\partial F_m}{\partial y_{i-1}}&\frac{\partial F_m}{\partial y_{i+1}}&...&\frac{\partial F_m}{\partial y_m}&\frac{\partial F_m}{\partial u}\\
\end{matrix}\right|
\end{aligned}

由于行列式 $$D'=\left|\begin{matrix}
\frac{\partial F_1}{\partial y_1}&\frac{\partial F_1}{\partial y_2}&...&\frac{\partial F_1}{\partial y_m}&\frac{\partial F_1}{\partial u}\\
\frac{\partial F_2}{\partial y_1}&\frac{\partial F_2}{\partial y_2}&...&\frac{\partial F_2}{\partial y_m}&\frac{\partial F_2}{\partial u}\\
...&...&...&...\\
\frac{\partial F_m}{\partial y_1}&\frac{\partial F_m}{\partial y_2}&...&\frac{\partial F_m}{\partial y_m}&\frac{\partial F_m}{\partial u}\\
\frac{\partial F_{m+1}}{\partial y_1}&\frac{\partial F_{m+1}}{\partial y_2}&...&\frac{\partial F_{m+1}}{\partial y_m}&\frac{\partial F_{m+1}}{\partial u}\\
\end{matrix}\right|$$ 且定义该行列式的代数余子式阵 $$A'=\left[\begin{matrix}
M_{11}'&M_{12}'&...&M_{1m}'\\
M_{21}'&M_{22}'&...&M_{2m}'\\
...&...&...&...\\
M_{m1}'&M_{m2}'&...&M_{mm}'\\
\end{matrix}\right]$$

故 $\sum_{i=1}^m M_{ij}F_{iu}=M'_{mj}$ 且 $D=M'_{mm}$ 故有

\begin{aligned}
\frac{\partial H(\vec{x}_0,u_0)}{\partial u}&=\frac{\sum_{j=1}^{m} F_{(m+1)y_j}M'_{mj}+ F_{(m+1)u}D}{D}\\
&=\frac{D'}{D}\\
\end{aligned}

由于假设 $D\ne 0$ 故只要 $D'\ne0$ 则有 $\frac{\partial H(\vec{x}_0,u_0)}{\partial u}\ne 0$ 

**** 运用隐函数存在定理

故综上所述当 $H(\vec{x},u)$ 满足

（1） $H(\vec{x}_0,u_0)=F_{m+1}\left(\vec{x}_0,\vec{\Phi}(\vec{x}_0,u_0),u_0\right)=0$

（2） 在 $(\vec{x},u)\in O((\vec{x}_0,u_0),\rho_1)$ 上函 $\vec{\Phi}(\vec{x},u)$ 有连续偏导且 $F_{m+1}(\vec{x},\vec{y},u)$ 在 $G$ 上有连续偏导，

     则根据复合函数[[MK7][链式求导法则]] $H(\vec{x},u)$ 有连续偏导，故必然存在一个闭长方体 $G'=\left\{(\vec{x},u)\big||x_i-x_{i_0}|<a^*_i,|u-u_0|<c^*\right\}\subset O((\vec{x}_0,u_0),\rho_1)$ 使得 $H(\vec{x},u)$ 有连续偏导且 $(\vec{x}_0,u_0)\in G'$

（3） $D'\ne0\Rightarrow \frac{\partial H(\vec{x}_0,u_0)}{\partial u}=\frac{D'}{D}\ne0$

根据[[MK11][多元隐函数存在定理]]有以下结论

（1） 在 $(\vec{x}_0,u_0)$ 点附近可以根据函数方程 $H(\vec{x},u)=0$ 来确定隐函数 $u=f_{m+1}(\vec{x}),\vec{x}\in O(\vec{x}_0,\rho_2)\subset G'$ 且 $H(\vec{x},u)=F_{m+1}\left(\vec{x},\vec{\Phi}(\vec{x}_0,f_{m+1}(\vec{x})),f_{m+1}(\vec{x})\right)=0$ 值域 $|u-u_0|<c^*$

（2） 隐函数 $u=f_{m+1}(\vec{x})$ 在定领域 $O(\vec{x}_0,\rho_2)\subset G'$ 内连续

（3） 隐函数 $u=f_{m+1}(\vec{x})$ 在定领域 $O(\vec{x}_0,\rho_2)\subset G'$ 内有连续偏导数

定义 $\rho=\min(\rho_1,\rho_2)$ 则当 $\vec{x}\in O(\vec{x}_0,\rho)$ 时有 $(\vec{x},u)=(\vec{x},f_{m+1}(\vec{x}))\in G'\subset O((\vec{x}_0,u_0),\rho_1)$

故满足 $\vec{F}\left(\vec{x},\vec{\Phi}(\vec{x},f_{m+1}(\vec{x})),u\right)=0,\vec{y}_0=\vec{\Phi}(\vec{x}_0,f_{m+1}(\vec{x}))$

定义 $\vec{f}(\vec{x})=\vec{\Phi}(\vec{x},f_{m+1}(\vec{x}))$ 则综合以上描述有：

（1） 在点 $(\vec{x}_0,\vec{y}_0,u_0)$ 的某个领域内可由 $\vec{F}(\vec{x},\vec{y},u)=0$ 确定唯一向量值隐函数 $(\vec{y},u)=\left(\vec{f}(\vec{x}),f_{m+1}(\vec{x})\right),\vec{x}\in O(\vec{x}_0,\rho)$ 满足 $\vec{F}\left(\vec{x},\vec{f}(\vec{x}),f_{m+1}(\vec{x})\right)=\vec{0},\vec{y}_0=\vec{f}(\vec{x}_0),u_0=f_{m+1}(\vec{x}_0)$

（2） 向量值隐函数在 $\vec{x}\in O(\vec{x}_0,\rho)$ 上连续

（3） 向量值隐函数在 $\vec{x}\in O(\vec{x}_0,\rho)$ 上可导

**** 推导隐函数导数

由于 $\vec{f}(\vec{x})=\vec{\Phi}(\vec{x},f_{m+1}(\vec{x}))$ 且 $f_{m+1}(\vec{x}),\vec{\Phi}(\vec{x},u)$ 有连续偏导，即可微。故根据链式法则 $\vec{f}(\vec{x})$ 亦有连续偏导数

根据 $\vec{F}\left(\vec{x},\vec{f}(\vec{x}),f_{m+1}(\vec{x})\right)=0,\vec{x}\in O(\vec{x}_0,\rho)$ 可得偏导数为零

由于 $\vec{f}(\vec{x}),f_{m+1}(\vec{x})$ 在 $\vec{x}\in O(\vec{x}_0,\rho)$ 上均有连续偏导 $\vec{F}(\vec{x},\vec{y},u)$ 在 $G$ 上有连续偏导，则根据[[MK7][链式求导法则]] 

\begin{aligned}
&\frac{\partal F_i(\vec{x},\vec{f}(\vec{x}),f_{m=1}(\vec{x}))}{\partial x_j}=\frac{\partial F_i}{\partial x_j}+\sum_{k=1}^m \frac{\partial F_i}{\parital y_k}\frac{\partial f_k(\vec{x})}{\partial x_j}+\frac{\partial F_i}{\parital u}\frac{\partial f_{m+1}(\vec{x})}{\partial x_j}=0\\
&\sum_{k=1}^m \frac{\partial F_i}{\parital y_k}\frac{\partial f_k(\vec{x})}{\partial x_j}+\frac{\partial F_i}{\parital u}\frac{\partial f_{m+1}(\vec{x})}{\partial x_j}=-\frac{\partial F_i}{\partial x_j}\\
&\left[\begin{matrix}
\frac{\partial F_i}{\parital y_1}&\frac{\partial F_i}{\parital y_2}&...&\frac{\partial F_i}{\parital y_m}&\frac{\partial F_i}{\parital u}
\end{matrix}\right]
\left[\begin{matrix}
\frac{\partial f_1(\vec{x})}{\partial x_j}\\
\frac{\partial f_2(\vec{x})}{\partial x_j}\\
...\\
\frac{\partial f_m(\vec{x})}{\partial x_j}\\
\frac{\partial f_{m+1}(\vec{x})}{\partial x_j}\\
\end{matrix}\right]=-\frac{\partial F_i}{\partial x_j}\\
\end{aligned}

则进一步有

\begin{aligned}
&\left[\begin{matrix}
\frac{\partial F_1}{\parital y_1}&\frac{\partial F_1}{\parital y_2}&...&\frac{\partial F_1}{\parital y_m}&\frac{\partial F_1}{\parital u}\\
\frac{\partial F_2}{\parital y_1}&\frac{\partial F_2}{\parital y_2}&...&\frac{\partial F_2}{\parital y_m}&\frac{\partial F_2}{\parital u}\\
...&...&...&...&...\\
\frac{\partial F_m}{\parital y_1}&\frac{\partial F_m}{\parital y_2}&...&\frac{\partial F_m}{\parital y_m}&\frac{\partial F_m}{\parital u}\\
\frac{\partial F_{m+1}}{\parital y_1}&\frac{\partial F_{m+1}}{\parital y_2}&...&\frac{\partial F_{m+1}}{\parital y_m}&\frac{\partial F_{m+1}}{\parital u}\\
\end{matrix}\right]
\left[\begin{matrix}
\frac{\partial f_1(\vec{x})}{\partial x_1}&\frac{\partial f_1(\vec{x})}{\partial x_2}&...&\frac{\partial f_1(\vec{x})}{\partial x_n}\\
\frac{\partial f_2(\vec{x})}{\partial x_1}&\frac{\partial f_2(\vec{x})}{\partial x_2}&...&\frac{\partial f_2(\vec{x})}{\partial x_n}\\
...&...&...&...\\
\frac{\partial f_m(\vec{x})}{\partial x_1}&\frac{\partial f_m(\vec{x})}{\partial x_2}&...&\frac{\partial f_m(\vec{x})}{\partial x_n}\\
\frac{\partial f_{m+1}(\vec{x})}{\partial x_1}&\frac{\partial f_{m+1}(\vec{x})}{\partial x_2}&...&\frac{\partial f_{m+1}(\vec{x})}{\partial x_n}\\
\end{matrix}\right]=-
\left[\begin{matrix}
\frac{\partial F_1}{\partial x_1}&\frac{\partial F_1}{\partial x_2}&...&\frac{\partial F_1}{\partial x_n}\\
\frac{\partial F_2}{\partial x_1}&\frac{\partial F_2}{\partial x_2}&...&\frac{\partial F_2}{\partial x_n}\\
...&...&...&...\\
\frac{\partial F_m}{\partial x_1}&\frac{\partial F_m}{\partial x_2}&...&\frac{\partial F_m}{\partial x_n}\\
\frac{\partial F_{m+1}}{\partial x_1}&\frac{\partial F_{m+1}}{\partial x_2}&...&\frac{\partial F_{m+1}}{\partial x_n}\\
\end{matrix}\right]\\
&\left[\begin{matrix}
\frac{\partial f_1(\vec{x})}{\partial x_1}&\frac{\partial f_1(\vec{x})}{\partial x_2}&...&\frac{\partial f_1(\vec{x})}{\partial x_n}\\
\frac{\partial f_2(\vec{x})}{\partial x_1}&\frac{\partial f_2(\vec{x})}{\partial x_2}&...&\frac{\partial f_2(\vec{x})}{\partial x_n}\\
...&...&...&...\\
\frac{\partial f_m(\vec{x})}{\partial x_1}&\frac{\partial f_m(\vec{x})}{\partial x_2}&...&\frac{\partial f_m(\vec{x})}{\partial x_n}\\
\frac{\partial f_{m+1}(\vec{x})}{\partial x_1}&\frac{\partial f_{m+1}(\vec{x})}{\partial x_2}&...&\frac{\partial f_{m+1}(\vec{x})}{\partial x_n}\\
\end{matrix}\right]=-
\left[\begin{matrix}
\frac{\partial F_1}{\parital y_1}&\frac{\partial F_1}{\parital y_2}&...&\frac{\partial F_1}{\parital y_m}&\frac{\partial F_1}{\parital u}\\
\frac{\partial F_2}{\parital y_1}&\frac{\partial F_2}{\parital y_2}&...&\frac{\partial F_2}{\parital y_m}&\frac{\partial F_2}{\parital u}\\
...&...&...&...&...\\
\frac{\partial F_m}{\parital y_1}&\frac{\partial F_m}{\parital y_2}&...&\frac{\partial F_m}{\parital y_m}&\frac{\partial F_m}{\parital u}\\
\frac{\partial F_{m+1}}{\parital y_1}&\frac{\partial F_{m+1}}{\parital y_2}&...&\frac{\partial F_{m+1}}{\parital y_m}&\frac{\partial F_{m+1}}{\parital u}\\
\end{matrix}\right]^{-1}
\left[\begin{matrix}
\frac{\partial F_1}{\partial x_1}&\frac{\partial F_1}{\partial x_2}&...&\frac{\partial F_1}{\partial x_n}\\
\frac{\partial F_2}{\partial x_1}&\frac{\partial F_2}{\partial x_2}&...&\frac{\partial F_2}{\partial x_n}\\
...&...&...&...\\
\frac{\partial F_m}{\partial x_1}&\frac{\partial F_m}{\partial x_2}&...&\frac{\partial F_m}{\partial x_n}\\
\frac{\partial F_{m+1}}{\partial x_1}&\frac{\partial F_{m+1}}{\partial x_2}&...&\frac{\partial F_{m+1}}{\partial x_n}\\
\end{matrix}\right]
\end{aligned}

证毕

*** <<MK14>>克莱默法则表述

由于根据上述结果，对于 $x_j$ 的偏导有

                       \begin{aligned}
&\left[\begin{matrix}
\frac{\partial F_1}{\parital y_1}&\frac{\partial F_1}{\parital y_2}&...&\frac{\partial F_1}{\parital y_m}\\
\frac{\partial F_2}{\parital y_1}&\frac{\partial F_2}{\parital y_2}&...&\frac{\partial F_2}{\parital y_m}\\
...&...&...&...\\
\frac{\partial F_m}{\parital y_1}&\frac{\partial F_m}{\parital y_2}&...&\frac{\partial F_m}{\parital y_m}\\
\end{matrix}\right]
\left[\begin{matrix}
\frac{\partial f_1(\vec{x})}{\partial x_j}\\
\frac{\partial f_2(\vec{x})}{\partial x_j}\\
...\\
\frac{\partial f_m(\vec{x})}{\partial x_j}\\
\end{matrix}\right]=-
\left[\begin{matrix}
\frac{\partial F_1}{\partial x_j}\\
\frac{\partial F_2}{\partial x_j}\\
...\\
\frac{\partial F_m}{\partial x_j}\\
\end{matrix}\right]
\end{aligned}

则根据[[MK12][克莱默法则]]有

\begin{aligned}
\frac{\partial f_k(\vec{x})}{\partial x_j}&=\frac{D_j}{D}\\
&=\frac{1}{D}\left|\begin{matrix}
\frac{\partial F_1}{\parital y_1}&...&\frac{\partial F_1}{\parital y_{k-1}}&-\frac{\partial F_1}{\partial x_j}&\frac{\partial F_1}{\parital y_{k+1}}&...&\frac{\partial F_1}{\parital y_m}\\
\frac{\partial F_2}{\parital y_1}&...&\frac{\partial F_2}{\parital y_{k-1}}&-\frac{\partial F_2}{\partial x_j}&\frac{\partial F_2}{\parital y_{k+1}}&...&\frac{\partial F_2}{\parital y_m}\\
...&...&...&...&...&...&...\\
\frac{\partial F_m}{\parital y_1}&...&\frac{\partial F_m}{\parital y_{k-1}}&-\frac{\partial F_m}{\partial x_j}&\frac{\partial F_m}{\parital y_{k+1}}&...&\frac{\partial F_m}{\parital y_m}\\
\end{matrix}\right|\\
&=-\frac{\frac{\partial \vec{F}(\vec{x},\vec{y})}{\partial (y_1,...,y_{k-1},x_j,y_{k+1},...,y_m)}}{\frac{\partial \vec{F}(\vec{x},\vec{y})}{\partial \vec{y}}}
\end{aligned}

** <<MK15>>逆映射定理

给定映射 $\vec{y}=\vec{f}(\vec{x})=\begin{cases}f_1(x_1,x_2,...,x_n)=y_1\\f_2(x_1,x_2,...,x_n)=y_2\\...\\f_n(x_1,x_2,...,x_n)=y_n\\\end{cases}$ 若存在点 $\vec{x}_0$ 满足

（1） $\vec{y}_0=\vec{f}(\vec{x}_0)$

（2） $\vec{f}(\vec{x})$ 在闭长方体 $G=\left\{(\vec{x},\vec{y})\big||x_i-x_{i_0}|<a_i\right\}$ 内有连续偏导

（3） 函数在 $\vec{x}_0$ 处关于 $\vec{x}$ 的雅克比行列式不为零，即 $$
\left|\frac{\partial \vec{f}(\vec{x}_0)}{\partial \vec{x}}\right|=\left|\begin{matrix}
&\frac{\partial f_1(\vec{x}_0)}{\partial x_1}&\frac{\partial f_1(\vec{x}_0)}{\partial x_2}&...&\frac{\partial f_1(\vec{x}_0)}{\partial x_m}\\
&\frac{\partial f_2(\vec{x}_0)}{\partial x_1}&\frac{\partial f_2(\vec{x}_0)}{\partial x_2}&...&\frac{\partial f_2(\vec{x}_0)}{\partial x_m}\\
&...&...&...&...\\
&\frac{\partial f_m(\vec{x}_0)}{\partial x_1}&\frac{\partial f_m(\vec{x}_0)}{\partial x_2}&...&\frac{\partial f_m(\vec{x}_0)}{\partial x_m}\\
\end{matrix}\right|\ne0$$

则在 $O(\vec{y}_0,\rho)$ 内有逆函数 $\vec{x}=\vec{g}(\vec{y})=\begin{cases}g_1(y_1,y_2,...,y_n)=x_1\\g_2(y_1,y_2,...,y_n)=x_2\\...\\g_n(y_1,y_2,...,y_n)=x_n\\\end{cases}$ 满足

（1） $\vec{x}_0=\vec{g}(\vec{y}_0)$

（2） $\frac{\partial \vec{g}(\vec{y})}{\partial \vec{y}}=\left(\frac{\partial \vec{f}(\vec{x})}{\partial \vec{x}}\right)^{-1}$

*** 证明

定义 $\vec{F}(\vec{x},\vec{y})=\begin{cases}F_1(\vec{x},\vec{y})=f_1(x_1,x_2,...,x_n)-y_1\\F_2(\vec{x},\vec{y})=f_2(x_1,x_2,...,x_n)-y_2\\...\\F_n(\vec{x},\vec{y})=f_n(x_1,x_2,...,x_n)-y_n\\\end{cases}$ 则有

（1） $\vec{F}(\vec{x}_0,\vec{y}_0)=0$

（2） $\frac{\partial F_i}{\partial y_j}=\begin{cases}1,i=j\\0,i\ne j\end{cases}$ 且条件（2），故必存在闭长方体 $G'$ 使得 $(\vec{x},\vec{y})\in G'$ 内函数有连续偏导

（3） 函数在 $(\vec{x}_0,\vec{y}_0)$ 处关于 $\vec{x}$ 的雅克比行列式不为零

故根据[[MK13][向量值隐函数存在定理]]有

（1） 在点 $(\vec{x}_0,\vec{y}_0)$ 的某个领域内可由 $\vec{F}(\vec{x},\vec{y})=0$ 确定唯一向量值隐函数 $\vec{x}=\vec{g}(\vec{y}),\vec{y}\in O(\vec{y}_0,\rho)$ 满足 $\vec{F}\left(\vec{x},\vec{f}(\vec{x})\right)=0,\vec{x}_0=\vec{g}(\vec{y}_0)$

（2） 向量值隐函数在 $\vec{y}\in O(\vec{y}_0,\rho)$ 上连续

（3） 向量值隐函数在 $\vec{y}\in O(\vec{y}_0,\rho)$ 上可导且导数为 $$\frac{\partial \vec{g}(\vec{y})}{\partial \vec{y}}=\left[\begin{matrix}
\frac{\partial x_1}{\partial y_1}&\frac{\partial x_1}{\partial y_2}&...&\frac{\partial x_1}{\partial y_n}\\
\frac{\partial x_2}{\partial y_1}&\frac{\partial x_2}{\partial y_2}&...&\frac{\partial x_2}{\partial y_n}\\
...&...&...&...\\
\frac{\partial x_n}{\partial y_1}&\frac{\partial x_n}{\partial y_2}&...&\frac{\partial x_n}{\partial y_n}\\
\end{matrix}\right]
=-\left[\begin{matrix}
\frac{\partial F_1}{\partial x_1}&\frac{\partial F_1}{\partial x_2}&...&\frac{\partial F_1}{\partial x_n}\\
\frac{\partial F_2}{\partial x_1}&\frac{\partial F_2}{\partial x_2}&...&\frac{\partial F_2}{\partial x_n}\\
...&...&...&...\\
\frac{\partial F_n}{\partial x_1}&\frac{\partial F_n}{\partial x_2}&...&\frac{\partial F_n}{\partial x_n}\\
\end{matrix}\right]^{-1}
\left[\begin{matrix}
\frac{\partial F_1}{\partial y_1}&\frac{\partial F_1}{\partial y_2}&...&\frac{\partial F_1}{\partial y_n}\\
\frac{\partial F_2}{\partial y_1}&\frac{\partial F_2}{\partial y_2}&...&\frac{\partial F_2}{\partial y_n}\\
...&...&...&...\\
\frac{\partial F_n}{\partial y_1}&\frac{\partial F_n}{\partial y_2}&...&\frac{\partial F_n}{\partial y_n}\\
\end{matrix}\right]$$

又根据 $F_i=f_i(\vec{x})-y_i$ 可得条件（3）为

\begin{aligned}
\frac{\partial \vec{g}(\vec{y})}{\partial \vec{y}}&=-\left[\begin{matrix}
\frac{\partial F_1}{\partial x_1}&\frac{\partial F_1}{\partial x_2}&...&\frac{\partial F_1}{\partial x_n}\\
\frac{\partial F_2}{\partial x_1}&\frac{\partial F_2}{\partial x_2}&...&\frac{\partial F_2}{\partial x_n}\\
...&...&...&...\\
\frac{\partial F_n}{\partial x_1}&\frac{\partial F_n}{\partial x_2}&...&\frac{\partial F_n}{\partial x_n}\\
\end{matrix}\right]^{-1}
\left[\begin{matrix}
\frac{\partial F_1}{\partial y_1}&\frac{\partial F_1}{\partial y_2}&...&\frac{\partial F_1}{\partial y_n}\\
\frac{\partial F_2}{\partial y_1}&\frac{\partial F_2}{\partial y_2}&...&\frac{\partial F_2}{\partial y_n}\\
...&...&...&...\\
\frac{\partial F_n}{\partial y_1}&\frac{\partial F_n}{\partial y_2}&...&\frac{\partial F_n}{\partial y_n}\\
\end{matrix}\right]\\
&=-\left[\begin{matrix}
\frac{\partial f_1}{\partial x_1}&\frac{\partial f_1}{\partial x_2}&...&\frac{\partial f_1}{\partial x_n}\\
\frac{\partial f_2}{\partial x_1}&\frac{\partial f_2}{\partial x_2}&...&\frac{\partial f_2}{\partial x_n}\\
...&...&...&...\\
\frac{\partial f_n}{\partial x_1}&\frac{\partial f_n}{\partial x_2}&...&\frac{\partial f_n}{\partial x_n}\\
\end{matrix}\right]^{-1} \left[\begin{matrix}
-1&0&...&0\\
0&-1&...&0\\
...&...&...&...\\
0&0&...&-1\\
\end{matrix}\right]\\
&=\left(\frac{\partial \vec{f}(\vec{x})}{\partial \vec{x}}\right)^{-1}I
\end{aligned}

* 偏导数几何应用

** 空间曲线

*** 参数方程

定义 $R^3$ 空间，曲线方程为 $\vec{\Gamma}(t)=\begin{cases}x=x(t)\\y=y(t)\\z=z(t)\end{cases},a\leq t\leq b$ 是空间曲线的参数表述

亦可写成向量形式 $\vec{\Gamma}(t)=x(t)\vec{i}+y(t)\vec{j}+z(t)\vec{k}$

*** 定义光滑曲线

$\frac{d\vec{\Gamma}(t)}{dt}=\frac{dx(t)}{dt}\vec{i}+\frac{dy(t)}{dt}\vec{j}+\frac{dz(t)}{dt}\vec{k}$ 连续，即 $\lim_{t\to t_0}\frac{d\vec{\Gamma}(t)}{dt}=\frac{d\vec{\Gamma}(t_0)}{dt}$

*** 光滑曲线切线和切向量

求在 $(x_0,y_0,z_0)=(x(t_0),y(t_0),z(t_0))$ 点的切线，取定义域内曲线上另一点 $(x(t),y(t),z(t))$ 构成割线

割线上的点满足 $\frac{x-x(t_0)}{x(t)-x(t_0)}=\frac{y-y(t_0)}{y(t)-y(t_0)}=\frac{z-z(t_0)}{z(t)-z(t_0)}$ 全部乘以 $t-t_0$ 等式仍然成立，即 $\frac{x-x(t_0)}{\frac{x(t)-x(t_0)}{t-t_0}}=\frac{y-y(t_0)}{\frac{y(t)-y(t_0)}{t-t_0}}=\frac{z-z(t_0)}{\frac{z(t)-z(t_0)}{t-t_0}}$ 

当 $t\to t_0$ 时，割线变为切线，等式满足 $\frac{x-x(t_0)}{\frac{dx(t_0)}{dt}}=\frac{y-y(t_0)}{\frac{dy(t_0)}{dt}}=\frac{z-z(t_0)}{\frac{dz(t_0)}{dt}}$ 即 $\frac{x-x(t_0)}{x'(t_0)}=\frac{y-y(t_0)}{y'(t_0)}=\frac{z-z(t_0)}{z'(t_0)}$ 

若 $z'(t)=0$ 则有 $\begin{cases}z-z(t_0)=0\\\frac{x-x(t_0)}{x'(t_0)}=\frac{y-y(t_0)}{y'(t_0)}\\\end{cases}$ 若 $z'(t)=y'(t)=0$ 则有 $\begin{cases}z-z(t_0)=0\\y-y(t_0)=0\\\end{cases}$ 

故定义切向量 $(x'(t_0),y'(t_0),z'(t_0))$ 切线与切向量同方向

*** 法平面

垂直于切向量，即与切向量的点积为零，即 $(x-x_0)x'(t_0)+(y-y_0)y'(t_0)+(z-z_0)z'(t_0)=0$

*** 一般表述的空间曲线

定义 $R^3$ 空间，曲线方程为 $\begin{cases}F(x,y,z)=0\\G(x,y,z)=0\end{cases}$ 若满足

（1） 存在一点 $(x_0,y_0,z_0)\Rightarrow \begin{cases}F(x_0,y_0,z_0)=0\\G(x_0,y_0,z_0)=0\\\end{cases}$

（2） 函数 $\begin{cases}F(x,y,z)\\G(x,y,z)\end{cases}$ 的偏导在比长方体 $G$ 内连续

（3） 函数偏导 $\left|\begin{matrix}F_x&F_y&F_z\\G_x&G_y&G_z\\\end{matrix}\right|$ 满秩，即有任意两个偏导组成的行列式不为零

则有

（1） 在 $(x_0,y_0,z_0)$ 附近曲线有参数表示，若 $\left|\begin{matrix}F_y&F_z\\G_y&G_z\\\end{matrix}\right|\ne 0$ 则有 $\vec{\Gamma}(t)=\begin{cases}x=t\\y=y(t)\\z=z(t)\end{cases},|t-x_0|<\rho$

（2） 在 $(x_0,y_0,z_0)$ 点有切向量 $\left(\frac{\partial (F,G)}{\partial (y,z)},\frac{\partial (F,G)}{\partial (z,x)},\frac{\partial (F,G)}{\partial (x,y)}\right)$

（3） 法平面为 $(F_x,F_y,F_z)$ 及 $(G_x,G_y,G_z)$ 向量张开的平面

**** 证明

由于 $\left|\begin{matrix}F_x&F_y&F_z\\G_x&G_y&G_z\\\end{matrix}\right|$ 满秩，即有任意两个偏导组成的行列式不为零，不妨设 $\left|\begin{matrix}F_y&F_z\\G_y&G_z\\\end{matrix}\right|\ne 0$ 故函数组满足：

（1） 存在一点 $(x_0,y_0,z_0)\Rightarrow \begin{cases}F(x_0,y_0,z_0)=0\\G(x_0,y_0,z_0)=0\\\end{cases}$

（2） 函数 $\begin{cases}F(x,y,z)\\G(x,y,z)\end{cases}$ 的偏导在比长方体 $G$ 内连续

（3） 函数在 $(x_0,y_0,z_0)$ 点的雅克比矩阵 $\frac{\partial (F,G)}{\partial (y,z)}=\left|\begin{matrix}F_y&F_z\\G_y&G_z\\\end{matrix}\right|\ne 0$ 

故根据[[MK13][向量值隐函数存在定理]]有

（1） 在点 $(x_0,y_0,z_0)$ 的某个领域内可由 $\begin{cases}F(x_0,y_0,z_0)=0\\G(x_0,y_0,z_0)=0\\\end{cases}$ 确定唯一向量值隐函数 $\begin{cases}y=y(x)\\z=z(x)\end{cases},|x-x_0|<\rho$ 且 $\begin{cases}y_0=y(x_0)\\z_0=z(x_0)\end{cases}$ 

（2） 向量值隐函数在 $|x-x_0|<\rho$ 上连续

（3） 向量值隐函数在 $|x-x_0|<\rho$ 上有连续偏导且导数为 $$\frac{\partial (y,z)}{\partial x}=-\left[\begin{matrix}
F_y&F_z\\
G_y&G_z\\
\end{matrix}\right]^{-1}
\left[\begin{matrix}
F_x\\
G_x\\
\end{matrix}\right]
$$

令 $x=t$ 得到曲线参数表示 $\vec{\Gamma}(t)=\begin{cases}x=t\\y=y(t)\\z=z(t)\end{cases},|t-x_0|<\rho$

根据[[MK14][克莱默表述]]有

\begin{aligned}
\frac{\partial y}{\partial x}=-\frac{\frac{\partial (F,G)}{\partial (x,z)}}{\frac{\partial (F,G)}{\partial (y,z)}}=\frac{\frac{\partial (F,G)}{\partial (z,x)}}{\frac{\partial (F,G)}{\partial (y,z)}}\\
\frac{\partial z}{\partial x}=-\frac{\frac{\partial (F,G)}{\partial (y,x)}}{\frac{\partial (F,G)}{\partial (y,z)}}=\frac{\frac{\partial (F,G)}{\partial (x,y)}}{\frac{\partial (F,G)}{\partial (y,z)}}\\
\end{aligned}

故在 $x=t_0$ 点有切向量 $\left(1,\frac{\frac{\partial (F,G)}{\partial (z,x)}}{\frac{\partial (F,G)}{\partial (y,z)}},\frac{\frac{\partial (F,G)}{\partial (x,y)}}{\frac{\partial (F,G)}{\partial (y,z)}}\right)$ 整理得 $\left(\frac{\partial (F,G)}{\partial (y,z)},\frac{\partial (F,G)}{\partial (z,x)},\frac{\partial (F,G)}{\partial (x,y)}\right)$ 上述偏导均在 $(x_0,y_0,z_0)$ 点

因为任意一行或一列的元素与代数余子式的乘积和等于矩阵行列式，故点积

\begin{aligned}
&(F_x,F_y,F_z)\cdot \left(\frac{\partial (F,G)}{\partial (y,z)},\frac{\partial (F,G)}{\partial (z,x)},\frac{\partial (F,G)}{\partial (x,y)}\right)\\
&=F_x\frac{\partial (F,G)}{\partial (y,z)}+F_y\frac{\partial (F,G)}{\partial (z,x)}+F_z\frac{\partial (F,G)}{\partial (x,y)}\\
&=\left|\begin{matrix}
F_x&F_y&F_z\\
F_x&F_y&F_z\\
G_x&G_y&G_z\\
\end{matrix}\right|\\
&=0
\end{aligned}

则 $(F_x,F_y,F_z)$ 与切向量垂直，同理可证 $(G_x,G_y,G_z)$ 与切向量垂直，故法平面为 $(F_x,F_y,F_z)$ 及 $(G_x,G_y,G_z)$ 向量张开的平面

** 空间平面

*** 曲面一般表述

$F(x,y,z)=0$

*** 定义光滑平面

在一般表述下，曲面函数 $F(x,y,z)=0$ 有连续偏导

*** 法向量，法线方程，法平面

**** 曲面一般表述

***** 定义

$F(x,y,z)=0$ 为曲面的一般表述

***** 求法

先给出以下定义

（1） 法向量垂直于曲面的切平面

（2） 曲面一点的切平面定义为过该点曲面上的任意光滑曲线的切向量位于的平面

（3） 即法向量与面上的任意光滑曲线的切向量垂直

定义 $\vec{\Gamma}(t)=\begin{cases}x=x(t)\\y=y(t)\\z=z(t)\end{cases},a\leq t\leq b$ 为曲面 $F(x,y,z)=0$ 上过点 $(x_0,y_0,z_0)$ 的一条光滑曲线，则有 $\begin{cases}x_0=x(t_0)\\y_0=y(t_0)\\z_0=z(t_0)\end{cases}$ , $F(x_0,y_0,z_0)=0$ , $H(t)=F(x(t),y(t),z(t))=0$

由于：

（1） 光滑曲线，故 $x(t),y(t),z(t)$ 可导

（2） 光滑平面，故 $F(x,y,z)$ 有连续偏导，根据[[MK5][可谓条件]]得出可微

故根据[[MK7][链式法则]]有 $\frac{\partial H(t_0)}{\partial t}=F_xx'(t_0)+F_yy'(t_0)+F_zz'(t_0)=(F_x,F_y,F_z)\cdot(x'(t_0),y'(t_0),z'(t_0))=0$

若 $(F_x,F_y,F_z),(x'(t_0),y'(t_0),z'(t_0))$ 均不为零向量，则两个向量垂直

故法向量为 $(F_x,F_y,F_z)$ 在 $(x_0,y_0,z_0)$ 点处，法平面为 $(x-x_0)F_x+(y-y_0)F_y+(z-z_0)F_z=0$ 法线方程为 $\frac{x-x_0}{F_x}=\frac{y-y_0}{F_y}=\frac{z-z_0}{F_z}$

**** 参数表示平面

***** 定义

$\vec{\Pi}(u,v)=\begin{cases}x=x(u,v)\\y=y(u,v)\\z=z(u,v)\end{cases},(u,v)\in D$ 为曲面的参数表示

***** 求法 

****** 需要条件

（1） $\begin{cases}x_0=x(u_0,v_0)\\y_0=y(u_0,v_0)\\z_0=z(u_0,v_0)\end{cases}$

（2） 函数 $x(u,v),y(u,v),z(u,v)$ 有连续偏导

（3） 雅克比矩阵 $\left[\begin{matrix}x_u&x_v\\y_u&y_v\\z_u&z_v\\\end{matrix}\right]$ 满秩，即有一组2阶行列式不为零

****** 求法

根据条件（3）不妨设 $\left|\begin{matrix}x_u&x_v\\y_u&y_v\\\end{matrix}\right|\ne0$ 则综合条件（1），（2）可应用[[MK15][逆映射定理]]得到逆函数 $\begin{cases}u=u(x,y)\\v=v(x,y)\\\end{cases},(x,y)\in O((x_0,y_0),\rho)$

逆函数有连续导数且导数为 $\frac{\partial (u,v)}{\partial (x,y)}=\frac{\partial (x,y)}{\partial (u,v)}^{-1}=\left[\begin{matrix}x_u&x_v\\y_u&y_v\\\end{matrix}\right]^{-1}$ 

带入 $z=z(u,v)$ 定义函数 $F(x,y,z)=z-z(u(x,y),v(x,y))$ 由于 $z(u,v)$ 有连续导数，根据[[MK5][可谓条件]]得出可微，加上可导可用[[MK7][链式法则]]

\begin{cases}
F_x=-z_uu_x-z_vv_x=-z_u\frac{y_v}{x_uy_v-x_vy_u}+z_v\frac{y_u}{x_uy_v-x_vy_u}\\
F_y=-z_uu_y-z_vv_y=z_u\frac{x_v}{x_uy_v-x_vy_u}-z_v\frac{x_u}{x_uy_v-x_vy_u}\\
F_z=1
\end{cases}

故法向量 $(y_uz_v-z_uy_v,z_ux_v-z_vx_u,x_uy_v-x_vy_u)$ 则可根据法向量求出法线方程和法平面

*** 曲面正交定义

对于两张曲面 $\Pi_1,\Pi_2$ 若在交线上任意点两张曲面的法向量 $\vec{n}_1,\vec{n}_2$ 正交，即 $\vec{n}_1\cdot\vec{n}_2=0,\forall (x,y,z)\in \Pi_1\cap\Pi_2$ 即称两张曲面正交

* 无条件极值

** 极值定义

假设 $y=f(\vec{x}),\vec{x}\in D$ 为多元函数，对于 $\vec{x}_0$ 成立 $\exists \rho,\forall \vec{x}\in O(\vec{x}_0,\rho)\Rightarrow f(\vec{x})\leq f(\vec{x}_0)$ 则称 $\vec{x}_0$ 为 $f(\vec{x})$ 的一个极大值点，反之则为极小值点。

** <<MK27>>无条件极值必要条件

若 $\vec{x}_0=(x_{1_0},x_{2_0},...,x_{n_0})$ 为函数 $f(\vec{x})$ 的一个极值且 $f(\vec{x})$ 在 $\vec{x}_0$ 点导数存在，则必定有 $\frac{\partial f(\vec{x}_0)}{\partial x_i}=0$

*** 证明

定义 $\Phi(x_i)=f(...,x_{(i-1)_0},x_i,x_{(i+1)_0}...)$ 则有 $x_{i_0}$ 为 $\Phi(x_i)$ 的极值点，则根据[[~/OneDrive/大学物理/Note/DiffEq.org][导数基本知识-费马引理]]可得 $\frac{d\Phi(x_i)}{dx_i}=0$

即 $\frac{\partial f(\vec{x}_0)}{\partial x_i}=\frac{d\Phi(x_i)}{dx_i}=0$

** 定义驻点

若 $\vec{x}_0$ 为 $f(\vec{x})$ 的驻点，则对于任意 $1\leq i\leq n$ 都有 $\frac{\partial f(\vec{x}_0)}{\partial x_i}=0$

** <<MK18>>极大（小）值判断

若函数 $f(\vec{x})$ 在 $O(\vec{x}_0,\rho)$ 上有二阶连续偏导，点 $\vec{x}_0+\Delta\vec{x}\in O(\vec{x}_0,\rho)$ ，且 $\vec{x}_0$ 为驻点，则有

\begin{aligned}
f(\vec{x}_0+\Delta\vec{x})-f(\vec{x}_0)&=\frac{\phi^2}{2}\sum_{1\leq j\leq n,1\leq i\leq n}\left\{r_jr_i\left(\frac{\partial f^2(\vec{x}_0)}{\partial x_j\partial x_i}+o_{ij}(\phi)\right)\right\}\\
&=\frac{\phi^2}{2}\left\{\sum_{1\leq j\leq n,1\leq i\leq n}\left\{r_jr_i\frac{\partial f^2(\vec{x}_0)}{\partial x_j\partial x_i}\right\}+o(\phi)\right\}
\end{aligned}

其中 $\phi=\sqrt{\sum_{i=1}^n \Delta x_i^2}>0, r_i=\frac{\Delta x_i}{\phi}$ 且 $\lim_{\phi\to0}o(\phi)=0$ 

定义 $f_{x_ix_j}=\frac{\partial^2 f(\vec{x}_0)}{\partial x_i\partial x_j}$ 定义 $H=\left[\begin{matrix}f_{x_1x_1}&f_{x_1x_2}&...&f_{x_1x_n}\\f_{x_2x_1}&f_{x_2x_2}&...&f_{x_2x_n}\\...&...&...&...\\f_{x_nx_1}&f_{x_nx_2}&...&f_{x_nx_n}\\\end{matrix}\right]$ 为实对称矩阵，且有

若 $H$ 正定则 $\vec{x}_0$ 为极小值

若 $H$ 负定则 $\vec{x}_0$ 为极大值

若 $H$ 不定则 $\vec{x}_0$ 不是极值

可根据[[MK26][正定充要条件]]判断 $H$ 是否为正定或负定。

*** 证明  

根据二阶连续偏导，根据[[MK5][可微条件]]一阶偏导可微，根据[[MK9][可谓与连续]]一阶偏导连续，同理可证明一阶偏导连续，故根据[[MK17][二阶函数混合偏导]]可得 $f_{x_ix_j}=f_{x_jx_i}$

又由于函数为实函数，故 $H$ 为实对称矩阵，故可用[[MK26][正定充要条件]]判断矩阵是否正定。

若函数 $f(\vec{x})$ 在 $O(\vec{x}_0,\rho)$ 上有二阶连续偏导，点 $\vec{x}_0+\Delta\vec{x}\in O(\vec{x}_0,\rho)$ ，且 $\frac{\partial f(\vec{x}_0)}{\partial x_i}=0$ 故根据[[MK16][泰勒公式]]有

\begin{aligned}
f(\vec{x}_0+\Delta\vec{x})&=f(\vec{x}_0)+\sum_{j=1}^n \Delta x_j \frac{\partial f(\vec{x}_0)}{\partial x_j} +R_2\\
&=f(\vec{x}_0)+0+\frac{1}{2}\left(\sum_{j=1}^n\Delta x_j\frac{\partial}{\partial x_j}\right)^{2}f(\vec{x}_0+\theta\Delta\vec{x})&\theta\in[0,1]\\
&=f(\vec{x}_0)+\frac{1}{2}\sum_{1\leq j\leq n,1\leq i\leq n}\left\{\Delta x_j\Delta x_i\frac{\partial f^2(\vec{x}_0+\theta\Delta\vec{x})}{\partial x_j\partial x_i}\right\}&\theta\in[0,1]\\
\end{aligned}

故有 

\begin{aligned}
f(\vec{x}_0+\Delta\vec{x})-f(\vec{x}_0)&=\frac{1}{2}\sum_{1\leq j\leq n,1\leq i\leq n}\left\{\Delta x_j\Delta x_i\frac{\partial f^2(\vec{x}_0+\theta\Delta\vec{x})}{\partial x_j\partial x_i}\right\}&\theta\in[0,1]\\
\end{aligned}

由于二阶偏导数均连续，则有 $\lim_{|\Delta\vec{x}|\to0}\frac{\partial f^2(\vec{x}_0+\Delta\vec{x})}{\partial x_j\partial x_i}=\frac{\partial f^2(\vec{x}_0)}{\partial x_j\partial x_i}$ 进一步定义 $\phi=\sqrt{\sum_{i=1}^n \Delta x_i^2}>0$ 则若向量 $\Delta \vec{x}$ 方向不变，就有 $\frac{\Delta x_i}{\phi}=r_i$ 为常数，即 $\Delta \vec{x}=\phi \vec{r}$ 

另外根据连续定义 $\lim_{\phi\to0}\frac{\partial f^2(\vec{x}_0+\theta\Delta\vec{x})}{\partial x_j\partial x_i}=\lim_{\phi\to0}\frac{\partial f^2(\vec{x}_0+\theta\rho\vec{r})}{\partial x_j\partial x_i}=\frac{\partial f^2(\vec{x}_0)}{\partial x_j\partial x_i}$ 当 $\theta$ 为有限常量时

即 $\frac{\partial f^2(\vec{x}_0+\theta\Delta\vec{x})}{\partial x_j\partial x_i}=\frac{\partial f^2(\vec{x}_0)}{\partial x_j\partial x_i}+o_{ij}(\phi)$ 其中 $\lim_{\phi\to0}o_{ij}(\phi)=0$ 故上述等式可变换为 

\begin{aligned}
f(\vec{x}_0+\Delta\vec{x})-f(\vec{x}_0)&=\frac{\phi^2}{2}\sum_{1\leq j\leq n,1\leq i\leq n}\left\{r_jr_i\left(\frac{\partial f^2(\vec{x}_0)}{\partial x_j\partial x_i}+o_{ij}(\phi)\right)\right\}\\
&=\frac{\phi^2}{2}\left\{\sum_{1\leq j\leq n,1\leq i\leq n}\left\{r_jr_i\frac{\partial f^2(\vec{x}_0)}{\partial x_j\partial x_i}\right\}+o(\phi)\right\}
\end{aligned}

其中 $o(\phi)=\sum_{1\leq j\leq n,1\leq i\leq n}r_ir_jo_{ij}(\phi)$ 且 $\lim_{\phi\to0}o(\phi)=\lim_{\phi\to0}\sum_{1\leq j\leq n,1\leq i\leq n}r_ir_jo_{ij}(\phi)$ 

由于 $n$ 为有限正整数，故可根据极限四则运算 $\lim_{\phi\to0}\sum_{1\leq j\leq n,1\leq i\leq n}r_ir_jo_{ij}(\phi)=\sum_{1\leq j\leq n,1\leq i\leq n}r_ir_j\lim_{\phi\to0}o_{ij}(\phi)=0$

若 $\sum_{1\leq j\leq n,1\leq i\leq n}\left\{r_jr_i\frac{\partial f^2(\vec{x}_0)}{\partial x_j\partial x_i}\right\}$ 对于任意 $\Delta \vec{x}$ 有下界 $m>0$ 则有

\begin{aligned}
f(\vec{x}_0+\Delta\vec{x})-f(\vec{x}_0)&=\frac{\phi^2}{2}\left\{\sum_{1\leq j\leq n,1\leq i\leq n}\left\{r_jr_i\frac{\partial f^2(\vec{x}_0)}{\partial x_j\partial x_i}\right\}+o(\phi)\right\}\\
&\geq \frac{\phi^2}{2}\left\{m+o(\phi)\right\}\\
\end{aligned}

由于 $\lim_{\phi\to0}o(\phi)=0$ 则必定存在 $\Phi,\forall\phi<\Phi\Rightarrow o(\phi)<m\Rightarrow \frac{\phi^2}{2}\left\{m+o(\phi)\right\}>0$ 故可确定 $\vec{x}_0$ 为极小值，反之同理

** 二元函数极大（小）值判断

若 $(x_0,y_0)$ 为二元函数 $f(x,y)$ 的驻点，且函数在 $O((x_0,y_0),\rho)$ 上有二阶连续偏导

定义 $f_{xx}=\frac{\partial^2 f(x_0,y_0)}{\partial x\partial x},f_{xy}=\frac{\partial^2 f(x_0,y_0)}{\partial x\partial y},f_{yx}=\frac{\partial^2 f(x_0,y_0)}{\partial y\partial x},f_{yy}=\frac{\partial^2 f(x_0,y_0)}{\partial y\partial y}$

定义 $H=\left|\begin{matrix}f_{xx}&f_{xy}\\f_{yx}&f_{yy}\end{matrix}\right|$

则有：

（1） 若 $H>0,f_{xx}>0$ 则 $(x_0,y_0)$ 是 $f(x,y)$ 的极小值

（2） 若 $H>0,f_{xx}<0$ 则 $(x_0,y_0)$ 是 $f(x,y)$ 的极大值 

（3） 若 $H<0$ 则 $(x_0,y_0)$ 不是极值 

（4） 若 $H=0$ 则需要另行判断

*** 证明

由于在 $(x_0,y_0)$ 点有二阶连续偏导，根据[[MK5][可微条件]]一阶偏导可微，根据[[MK9][可谓与连续]]一阶偏导连续，同理可证明一阶偏导连续

故根据[[MK17][二阶函数混合偏导]]可得 $f_{xy}=f_{yx}$ 则 $H=f_{xx}f_{yy}-f_{xy}^2$

由于 $(x_0,y_0)$ 是驻点，且在 $O((x_0,y_0),\rho)$ 上 $f(x,y)$ 有二阶连续偏导，故根据[[MK18][极值判断]]有 

\begin{aligned}
f(x_0+\Delta x,y_0+\Delta y)-f(x_0,y_0)&=\frac{\phi^2}{2}\left\{f_{xx}r_x^2+f_{xy}r_xr_y+f_{yx}r_xr_y+f_{yy}r_y^2+o(\phi)\right\}\\
&=\frac{\phi^2}{2}\left\{f_{xx}r_x^2+2f_{xy}r_xr_y+f_{yy}r_y^2+o(\phi)\right\}
\end{aligned}

其中 $\phi=\Delta x^2+\Delta y^2,r_x=\frac{\Delta x}{\phi},r_y=\frac{\Delta y}{\phi}$ 则有 $r_x^2+r_y^2=1$ 故 $r_xr_y\ne0$

若 $r_x\ne0$ 则有 $f_{xx}r_x^2+2f_{xy}r_xr_y+f_{yy}r_y^2=r_x^2\left(f_{xx}+2f_{xy}\frac{r_y}{r_x}+f_{yy}\left(\frac{r_y}{r_x}\right)^2\right)$ 则若 $(2f_{xy})^2-4f_{xx}f_{yy}<0\Rightarrow f_{xx}f_{yy}-f_{xy}^2>0$ 则二次项与数轴无交点，且若 $f_{yy}>0$ 二次项恒大于零

由于 $f_{xx}f_{yy}-f_{xy}^2>0$ 故 $f_{xx},f_{yy}$ 必定同号，则 $f_{xx}>0\Rightarrow f_{yy}>0$

故若 $H=f_{xx}f_{yy}-f_{xy}^2>0,f_{xx}>0$ 则 $f_{xx}r_x^2+2f_{xy}r_xr_y+f_{yy}r_y^2$ 有大于零下界，根据[[MK18][极值判断]]点 $(x_0,y_0)$ 是 $f(x,y)$ 的极小值

若 $H=f_{xx}f_{yy}-f_{xy}^2>0,f_{xx}<0$ 则 $f_{xx}r_x^2+2f_{xy}r_xr_y+f_{yy}r_y^2$ 有小于零上界，根据[[MK18][极值判断]]点 $(x_0,y_0)$ 是 $f(x,y)$ 的极大值

若 $H=0$ 则 $f_{xx}r_x^2+2f_{xy}r_xr_y+f_{yy}r_y^2=f_{xx}r_x^2+2\sqrt{|f_{xx}||f_{yy}|}r_xr_y+f_{yy}r_y^2=\pm (|f_{xx}|r_x+|f_{yy}|r_y)^2$ 为完全平方，但可能为零，故不能判断

同理可证 $r_y\ne0$ 的情况

* 条件极值

** 条件极值的必要条件（Lagrange乘数法）

$(\vec{x}_0,\vec{y}_0)$ 是 $H(\vec{x},\vec{y})=H(x_1,x_2,...,x_n,y_1,y_2,...,y_m)$ 的条件极值且：

（1） $H(\vec{x},\vec{y})$ 在 $(\vec{x}_0,\vec{y}_0)$ 处导数存在

（2） 满足条件 $\vec{G}(\vec{x},\vec{y})=\vec{0}\Rightarrow\begin{cases}G_1(x_1,x_2,...,x_n,y_1,y_2,...,y_m)=0\\G_2(x_1,x_2,...,x_n,y_1,y_2,...,y_m)=0\\...\\G_m(x_1,x_2,...,x_n,y_1,y_2,...,y_m)=0\\\end{cases}$ 

（3） 在包含 $(\vec{x}_0,\vec{y}_0)$ 的闭长方体 $D=\left\{(\vec{x},\vec{y})\big||x_i-x_{i_0}|<a_i,|y_i-y_{i_0}|<b_i\right\}$ 上 $\vec{G}(\vec{x},\vec{y})$ 有连续偏导

（4） 函数在 $(\vec{x}_0,\vec{y}_0)$ 处关于 $\vec{y}$ 的雅克比行列式不为零，即 $$
\left|\frac{\partial \vec{G}(\vec{x}_0,\vec{y}_0)}{\partial \vec{y}}\right|=\left|\begin{matrix}
&\frac{\partial G_1(\vec{x}_0,\vec{y}_0)}{\partial y_1}&\frac{\partial G_1(\vec{x}_0,\vec{y}_0)}{\partial y_2}&...&\frac{\partial G_1(\vec{x}_0,\vec{y}_0)}{\partial y_m}\\
&\frac{\partial G_2(\vec{x}_0,\vec{y}_0)}{\partial y_1}&\frac{\partial G_2(\vec{x}_0,\vec{y}_0)}{\partial y_2}&...&\frac{\partial G_2(\vec{x}_0,\vec{y}_0)}{\partial y_m}\\
&...&...&...&...\\
&\frac{\partial G_m(\vec{x}_0,\vec{y}_0)}{\partial y_1}&\frac{\partial G_m(\vec{x}_0,\vec{y}_0)}{\partial y_2}&...&\frac{\partial G_m(\vec{x}_0,\vec{y}_0)}{\partial y_m}\\
\end{matrix}\right|\ne0$$ （即雅克比矩阵 $J=\frac{\partial G(\vec{x}_0,\vec{y}_0)}{\partial (\vec{x},\vec{y})}$ 满秩)

则定义Lagrange函数 $L\left(\vec{x},\vec{y},\vec{\lambda}\right)=H(\vec{x},\vec{y})-\sum_{i=1}^m\lambda_i G_i(\vec{x},\vec{y})$ 则条件极值点 $(\vec{x}_0,\vec{y}_0)$ 必定包含在 $\frac{\partial L\left(\vec{x},\vec{y},\vec{\lambda}\right)}{\partial \left(\vec{x},\vec{y},\vec{\lambda}\right)}=\vec{0}$ 的解对应的 $(\vec{x},\vec{y})$ 中

*** <<MK28>>证明

由于条件（2），（3），（4）则根据[[MK13][向量值隐函数存在定理]]

（1） 在点 $(\vec{x}_0,\vec{y}_0)$ 的某个领域内可由 $\vec{G}(\vec{x},\vec{y})=0$ 确定唯一向量值隐函数 $\vec{y}=\vec{g}(\vec{x})=\begin{cases}y_1=g_1(x_1,x_2,...,x_n)\\y_2=g_2(x_1,x_2,...,x_n)\\..\\y_m=g_n(x_1,x_2,...,x_n)\end{cases},\vec{x}\in O(\vec{x}_0,\rho)$ 

      满足 $\vec{G}\left(\vec{x},\vec{g}(\vec{x})\right)=0,\vec{y}_0=\vec{g}(\vec{x}_0)$ 值域 $|y_i-y_{i_0}|<b_i$

（2） 向量值隐函数在 $\vec{x}\in O(\vec{x}_0,\rho)$ 上连续

（3） 向量值隐函数在 $\vec{x}\in O(\vec{x}_0,\rho)$ 上有连续偏导且导数为 $$\frac{\partial \vec{g}(\vec{x})}{\partial \vec{x}}=\left[\begin{matrix}
\frac{\partial g_1}{\partial x_1}&\frac{\partial g_1}{\partial x_2}&...&\frac{\partial g_1}{\partial x_n}\\
\frac{\partial g_2}{\partial x_1}&\frac{\partial g_2}{\partial x_2}&...&\frac{\partial g_2}{\partial x_n}\\
...&...&...&...\\
\frac{\partial g_m}{\partial x_1}&\frac{\partial g_m}{\partial x_2}&...&\frac{\partial g_m}{\partial x_n}\\
\end{matrix}\right]
=-\left[\begin{matrix}
\frac{\partial G_1}{\partial y_1}&\frac{\partial G_1}{\partial y_2}&...&\frac{\partial G_1}{\partial y_m}\\
\frac{\partial G_2}{\partial y_1}&\frac{\partial G_2}{\partial y_2}&...&\frac{\partial G_2}{\partial y_m}\\
...&...&...&...\\
\frac{\partial G_m}{\partial y_1}&\frac{\partial G_m}{\partial y_2}&...&\frac{\partial G_m}{\partial y_m}\\
\end{matrix}\right]^{-1}
\left[\begin{matrix}
\frac{\partial G_1}{\partial x_1}&\frac{\partial G_1}{\partial x_2}&...&\frac{\partial G_1}{\partial x_n}\\
\frac{\partial G_2}{\partial x_1}&\frac{\partial G_2}{\partial x_2}&...&\frac{\partial G_2}{\partial x_n}\\
...&...&...&...\\
\frac{\partial G_m}{\partial x_1}&\frac{\partial G_m}{\partial x_2}&...&\frac{\partial G_m}{\partial x_n}\\
\end{matrix}\right]$$

根据上述结论（3）有 $\frac{\partial G_j(\vec{x}_0,\vec{g}(\vec{x}_0))}{\partial x_i}&=\frac{\partial G_j(\vec{x}_0,\vec{y}_0)}{\partial x_i}+\sum_{k=1}^m \frac{\partial G_j(\vec{x}_0,\vec{y}_0)}{\partial y_k}\frac{\partial g_k(\vec{x}_0)}{x_i}=0$

定义 $\Phi(\vec{x})=H\left(\vec{x},\vec{g}(\vec{x})\right)$ 则函数 $\Phi(\vec{x})$ 的值等于满足 $\vec{G}(\vec{x},\vec{y})=0$ 的 $H(\vec{x},\vec{y})$ 的值，故 $\Phi(\vec{x})$ 的无条件极值点即 $H(\vec{x},\vec{y})$ 在满足 $\vec{G}(\vec{x},\vec{y})=0$ 下的条件极值点

根据[[MK27][无条件极值必要条件]]得到 $\frac{\partial \Phi(\vec{x}_0)}{\partial \vec{x}}=\vec{0}\Rightarrow \begin{cases}\frac{\partial H(\vec{x}_0,\vec{y}_0)}{\partial x_1}+\sum_{i=1}^m\frac{\partial H(\vec{x}_0,\vec{y}_0)}{\partial y_i}\frac{\partial g_i(\vec{x}_0)}{\partial x_1}=0\\\frac{\partial H(\vec{x}_0,\vec{y}_0)}{\partial x_2}+\sum_{i=1}^m\frac{\partial H(\vec{x}_0,\vec{y}_0)}{\partial y_i}\frac{\partial g_i(\vec{x}_0)}{\partial x_2}=0\\...\\\frac{\partial H(\vec{x}_0,\vec{y}_0)}{\partial x_n}+\sum_{i=1}^m\frac{\partial H(\vec{x}_0,\vec{y}_0)}{\partial y_i}\frac{\partial g_i(\vec{x}_0)}{\partial x_n}=0\\\end{cases}$

由于 $\left|\frac{\partial \vec{G}(\vec{x}_0,\vec{y}_0)}{\partial \vec{y}}\right|\ne0$ 故矩阵可逆，则有：

\begin{aligned}
\left[\begin{matrix}
\frac{\partial G_1}{\partial y_1}&\frac{\partial G_2}{\partial y_1}&...&\frac{\partial G_m}{\partial y_1}\\
\frac{\partial G_1}{\partial y_2}&\frac{\partial G_2}{\partial y_2}&...&\frac{\partial G_m}{\partial y_2}\\
...&...&...&...\\
\frac{\partial G_1}{\partial y_m}&\frac{\partial G_2}{\partial y_m}&...&\frac{\partial G_m}{\partial y_m}\\
\end{matrix}\right]
\left[\begin{matrix}
\lambda_1\\
\lambda_2\\
...\\
\lambda_m
\end{matrix}\right]
=
\left[\begin{matrix}
\frac{\partial H}{\partial y_1}\\
\frac{\partial H}{\partial y_2}\\
...\\
\frac{\partial H}{\partial y_m}\\
\end{matrix}\right]
\Rightarrow
\left[\begin{matrix}
\lambda_1\\
\lambda_2\\
...\\
\lambda_m
\end{matrix}\right]
=
\left[\begin{matrix}
\frac{\partial G_1}{\partial y_1}&\frac{\partial G_1}{\partial y_2}&...&\frac{\partial G_1}{\partial y_m}\\
\frac{\partial G_2}{\partial y_1}&\frac{\partial G_2}{\partial y_2}&...&\frac{\partial G_2}{\partial y_m}\\
...&...&...&...\\
\frac{\partial G_m}{\partial y_1}&\frac{\partial G_m}{\partial y_2}&...&\frac{\partial G_m}{\partial y_m}\\
\end{matrix}\right]^{-1}
\left[\begin{matrix}
\frac{\partial H}{\partial y_1}\\
\frac{\partial H}{\partial y_2}\\
...\\
\frac{\partial H}{\partial y_m}\\
\end{matrix}\right]
\end{aligned}

推出 $\frac{\partial H}{\partial y_j}=\sum_{i=1}^m \lambda_i \frac{\partial G_i(\vec{x}_0,\vec{y}_0)}{\partial y_j},\ j=1,2,...,m$ 结合无条件极值推导结果及 $\frac{\partial G_j(\vec{x}_0,\vec{g}(\vec{x}_0))}{\partial x_i}&=\frac{\partial G_j(\vec{x}_0,\vec{y}_0)}{\partial x_i}+\sum_{k=1}^m \frac{\partial G_j(\vec{x}_0,\vec{y}_0)}{\partial y_k}\frac{\partial g_k(\vec{x}_0)}{x_i}=0$ ，对于 $k=1,2,...,n$ 有 

\begin{aligned}
\frac{\partial H(\vec{x}_0,\vec{y}_0)}{\partial x_k}&=-\sum_{i=1}^m\frac{\partial H(\vec{x}_0,\vec{y}_0)}{\partial y_i}\frac{\partial g_i(\vec{x}_0)}{\partial x_k}\\
&=-\sum_{i=1}^m \left\{\frac{\partial g_i(\vec{x}_0)}{\partial x_k}\left\{ \sum_{j=1}^m \lambda_j \frac{\partial G_j(\vec{x}_0,\vec{y}_0)}{\partial y_i}\right\}\right\}\\
&=\sum_{j=1}^m \lambda_j \left\{ -\sum_{i=1}^m \frac{\partial G_j(\vec{x}_0,\vec{y}_0)}{\partial y_i}\frac{\partial g_i(\vec{x}_0)}{\partial x_k}\right\}\right\}\\
&=\sum_{j=1}^m \lambda_j \frac{\partial G_j(\vec{x}_0,\vec{y}_0)}{\partial x_i}\\
\end{aligned}

故结合上述条件，当 $(\vec{x}_0,\vec{y}_0)$ 为条件极值点时有 $\frac{\partial H(\vec{x}_0,\vec{y}_0)}{\partial (\vec{x},\vec{y})}=\sum_{i=1}^m\lambda_i\frac{\partial G_i(\vec{x}_0,\vec{y}_0)}{\partial (\vec{x},\vec{y})}$ ，即满足 $\frac{\partial L\left(\vec{x},\vec{y},\vec{\lambda}\right)}{\partial \left(\vec{x},\vec{y}\right)}=\frac{\partial H(\vec{x}_0,\vec{y}_0)}{\partial (\vec{x},\vec{y})}-\sum_{i=1}^m\lambda_i\frac{\partial G_i(\vec{x}_0,\vec{y}_0)}{\partial (\vec{x},\vec{y})}=\vec{0}$

又因为 $\frac{\partial L\left(\vec{x},\vec{y},\vec{\lambda}\right)}{\partial \vec{\lambda}}=\vec{G}(\vec{x}_0,\vec{y}_0)}=0$ 为极值必须满足的条件

综合上述条件得，当 $(\vec{x}_0,\vec{y}_0)$ 为条件极值点时Lagrange函数的一阶偏导比为零，即 $\frac{\partial L\left(\vec{x},\vec{y},\vec{\lambda}\right)}{\partial \left(\vec{x},\vec{y},\vec{\lambda}\right)}=\vec{0}$ 证毕。

** 条件极值的充分条件（Lagrange乘数法）

定义Lagrange函数 $L\left(\vec{x},\vec{\lambda}\right)=H(\vec{x})-\sum_{i=1}^m\lambda_i G_i(\vec{x})$ 其中

（1） $H(\vec{x})$ 为极值函数，在 $\vec{x}_0$ 处存在连续二阶偏导

（2） $\vec{G}(\vec{x})=\vec{0}\Rightarrow\begin{cases}G_1(x_1,x_2,...,x_n)=0\\G_2(x_1,x_2,...,x_n)=0\\...\\G_m(x_1,x_2,...,x_n)=0\\\end{cases}$ 为极值条件，在包含 $\vec{x}_0$ 的闭长方体  $D=\left\{(\vec{x},\vec{y})\big||x_i-x_{i_0}|<a_i\right\}$  上存在连续二阶偏导

（3） $m<n$

（4） 在 $\vec{x}_0$ 处的雅克比矩阵 $J=\frac{\partial \vec{G}(\vec{x}_0)}{\partial \vec{x}}$ 满秩

若点 $\left(\vec{x}_0,\vec{\lambda}_0\right)$ 满足 $\frac{\partial L\left(\vec{x}_0,\vec{\lambda}_0\right)}{\partial \left(\vec{x},\vec{\lambda}\right)}=\vec{0}$ 则定义矩阵 $A=\left(\frac{\partial ^2L\left(\vec{x}_0,\vec{\lambda}_0\right)}{\partial x_i\parital x_j}\right)_{n\times n},\ i=1,2,...,n,j=1,2,...,n$ 

若 $A$ 正定，则点 $\vec{x}_0$ 为条件极小值

若 $A$ 负定，则点 $\vec{x}_0$ 为条件极大值

*** 证明

根据条件  $\frac{\partial L\left(\vec{x}_0,\vec{\lambda}_0\right)}{\partial \vec{\lambda}}=\vec{0}\Rightarrow \vec{G}(\vec{x}_0)=\vec{0}\Rightarrow L\left(\vec{x}_0,\vec{\lambda}_0\right)=H(\vec{x}_0)-\sum_{i=1}^m\lambda_{i_0} G_i(\vec{x}_0)=H(\vec{x}_0)$ 

定义 $\Phi(\vec{x}_0)=L\left(\vec{x},\vec{\lambda}_0\right)=H(\vec{x})-\sum_{i=1}^m\lambda_{i_0} G_i(\vec{x})$ 由于 $H(\vec{x}),\vec{G}(\vec{x})$ 均有二阶连续偏导，故 $\Phi(\vec{x})$ 有二阶连续偏导

又因为 $\frac{\partial L\left(\vec{x}_0,\vec{\lambda}_0\right)}{\partial \vec{x}}=\vec{0}$ 则有 $\frac{\partial\Phi(\vec{x}_0)}{\partial \vec{x}}=0$ 

故：（1） $\vec{x}_0$ 为 $\Phi(\vec{x})$ 的驻点；（2） $\Phi(\vec{x})$ 有二阶连续偏导。则定义 $\Phi_{x_ix_j}=\frac{\partial^2 \Phi(\vec{x}_0)}{\partial x_i\partial x_j}=\frac{\partial^2 L(\vec{x}_0,\vec{\lambda}_0)}{\partial x_i\partial x_j}$ 定义 $A=\left[\begin{matrix}\Phi_{x_1x_1}&\Phi_{x_1x_2}&...&\Phi_{x_1x_n}\\\Phi_{x_2x_1}&\Phi_{x_2x_2}&...&\Phi_{x_2x_n}\\...&...&...&...\\\Phi_{x_nx_1}&\Phi_{x_nx_2}&...&\Phi_{x_nx_n}\\\end{matrix}\right]$ ，根据[[MK18][极大（小）值判断]]有：

（1） 若 $A$ 正定，则 $\vec{x}_0$ 为 $\Phi(\vec{x})$ 的极小值，即 $\exists \rho,\forall \vec{x}\in O(\vec{x}_0,\rho)\Rightarrow \Phi(\vec{x})\geq \Phi(\vec{x}_0)$ ；

（2） 若 $A$ 负定，则 $\vec{x}_0$ 为 $\Phi(\vec{x})$ 的极大值，即 $\exists \rho,\forall \vec{x}\in O(\vec{x}_0,\rho)\Rightarrow \Phi(\vec{x})\leq \Phi(\vec{x}_0)$ ；

定义 $\vec{x}'=(x_1,x_2,...,x_{n-m}),\vec{x}''=(x_{n-m+1},x_{n-m+2},...,x_n)$ 则有 $(\vec{x}'_0,\vec{x}''_0) =\vec{x}_0$ 。由于有条件：

（1） $\frac{\partial L\left(\vec{x}_0,\vec{\lambda}_0\right)}{\partial \vec{\lambda}}=\vec{0}\Rightarrow \vec{G}(\vec{x}_0)=\vec{0}$

（2） 函数 $\vec{G}(\vec{x})$ 在 $D$ 上有二阶连续偏导，根据[[MK5][可微条件]] $\vec{G}(\vec{x})$ 在 $D$ 上可微，根据[[MK9][可微与连续]] $\vec{G}(\vec{x})$ 在 $D$ 上的一阶偏导数连续

（3） $J=\frac{\partial \vec{G}(\vec{x}_0)}{\partial \vec{x}}$ 满秩，即必有一 $m\times m$ 子阵的行列式不为零，不妨设 $|J'|=\left|\frac{\partial \vec{G}(\vec{x}_0)}{\partial \vec{x}''}\right|\ne 0$

故根据[[MK13][向量值隐函数存在定理]]

（1） 在点 $(\vec{x}_0)$ 的某个领域内可由 $\vec{G}(\vec{x})=0$ 确定唯一向量值隐函数 $\vec{x}''= \vec{g}(\vec{x}'),\vec{x}'\in O(\vec{x}'_0,\rho')$ 满足 $\vec{G}\left(\vec{x}',\vec{g}(\vec{x}')\right)=0,\vec{x}''_0=\vec{g}(\vec{x}'_0)$

（2） 向量值隐函数在 $\vec{x}''\in O(\vec{x}''_0,\rho')$ 上连续

由于 $\vec{x}''_0=\vec{g}(\vec{x}'_0)$ 且 $\vec{g}(\vec{x})$ 在 $\vec{x}'\in O(\vec{x}',\rho')$ 上连续，故 $\exists \rho'',\forall \vec{x}'\in O(\vec{x}' _0,\rho'')\Rightarrow |\vec{g}(\vec{x})-\vec{x}''_0|<\frac{\rho}{\sqrt{2}}$

故当 $\vec{x}'\in O\left(\vec{x}'_0,\min\left(\frac{\rho}{\sqrt{2}},\rho''\right)\right)$ 时有 $|\vec{x}'-\vec{x}'_0|=\sqrt{\sum_{i=1}^{n-m}(x_i-x_{i_0})^2}<\frac{\rho}{\sqrt{2}}$ 及 $|\vec{g}(\vec{x}')-\vec{x}''_0|=\sqrt{\sum_{i=n-m+1}^{n}(g_i(\vec{x}')-x_{i_0})^2}<\frac{\rho}{\sqrt{2}}$

则 $\left((\vec{x}',\vec{g}(\vec{x}'))-\vec{x}_0\right)^2=\sum_{i=1}^{n-m}(x_i-x_{i_0})^2+\sum_{i=n-m+1}^{n}(g_i(\vec{x}')-x_{i_0})^2<\rho^2$ 即 $|(\vec{x}',\vec{g}(\vec{x}'))-\vec{x}_0|<\rho\Rightarrow (\vec{x}',\vec{g}(\vec{x}'))\in O(\vec{x}_0,\rho)$

此时若 $A$ 正定，则有 $H(\vec{x}',\vec{g}(\vec{x}'))=L(\vec{x},\vec{\lambda}_0)=\Phi(\vec{x}',\vec{g}(\vec{x}'))\geq \Phi(\vec{x}_0)=H(\vec{x}_0)$ 且 $\vec{G}(\vec{x}',\vec{g}(\vec{x}'))=0$ 

由于唯一确定隐函数，故对于任意给定 $\vec{x}'\in O\left(\vec{x}'_0,\min\left(\frac{\rho}{\sqrt{2}},\rho''\right)\right)$ 不存在 $\vec{x}''\ne\vec{g}(\vec{x}')\Rightarrow \vec{G}(\vec{x}',\vec{g}(\vec{x}'))=0$ 故 $\vec{x}_0$ 为满足条件的极小值。

若负定，同理可证极大值。


