#+LATEX_CLASS: ctexart

#+TITLE: 曲面，曲线积分与场论

current mark: MK56

* 点积

对于向量 $\vec{x}=(x_1,...,x_n)^T,\vec{y}=(y_1,...,y_n)^T$ 其点积为 $\vec{x}\cdot\vec{y}=\sum_{i=1}^nx_iy_i$

** 乘法分配律<<MK54>>

$\vec{x}\cdot(\vec{y}'+ \vec{y}'')=\vec{x}\cdot\vec{y}'+\vec{x}\cdot\vec{y}''$

*** 证明

\begin{aligned}
&\vec{x}\cdot(\vec{y}'+\vec{y}'')\\
=&\sum_{i=1}^nx_i(y'_i+y''_i)\\
=&\sum_{i=1}^nx_iy'_i+\sum_{i=1}^nx_iy''_i\\
=&\vec{x}\cdot\vec{y}'+\vec{x}\cdot\vec{y}''
\end{aligned}

** 绝对值不等式<<MK55>>

$\left|\vec{x}\cdot\vec{y}\right|\leq \left|\vec{x}\right|\left|\vec{y}\right|$ 其中 $n$ 是 $\vec{x},\vec{y}$ 的维度

不等式左边为绝对值，右边为求摸后的乘积

*** 证明

由于 $\left|\vec{x}\cdot\vec{y}\right|=\left|\vec{x}\right|\left|\vec{y}\right|\cos(\alpha)$ 且 $0\leq\cos(\alpha)\leq 1$

故有 $\left|\vec{x}\cdot\vec{y}\right|\leq \left|\vec{x}\right|\left|\vec{y}\right|$

* 可求长线段<<MK52>>

在 $R^n$ 上的曲线段 $L\subset R^n$ 做分点 $P:P_0,...,P_{m+1}$ 其中 $P_0,P_{m+1}$ 分别为线段的端点。

定义 $P_i$ 点对应的坐标为 $\vec{x}_i$ 定义 $\lambda=\max(P_i,P_{i+1})$ 

定义极限 $\lim_{\lambda\to0}\sum_{i=1}^m|\vec{x}_{i+1}-\vec{x}_i|=l$ 其中 $|\vec{x}_{i+1}-\vec{x}|=\sqrt{\sum_{j=1}^n\left(x_{(i+1)j}-x_{(i)j}\right)^2}$ 为 $\vec{x}_{i+1}-\vec{x}$ 的模

若极限收敛，则称曲线可求长，且其长度为 $l$

** 推论<<MK56>>

若 $L$ 可求长，则曲线分段可求长

*** 证明

对于任意分段 $L'\subset L$ 其长度为 $\lim_{\lambda\to0}\sum_{i=1}^m\left[\sqrt{\sum_{j=1}^n\left(x_{(i+1)j}-x_{(i)j}\right)^2}\right]$

由于每一项均为正数，故若不可求长度，必发散，故有 $\lim_{\lambda\to0}\sum_{i=1}^m\left[\sqrt{\sum_{j=1}^n\left(x_{(i+1)j}-x_{(i)j}\right)^2}\right]=\infty$

由于 $L$ 的长度包含任意分段，故当与上述 $L'$ 分段重合时必有 $L=m(L')+m(L/L')$

上述公式中 $m(x)$ 为求曲线长度。由于 $m(L')=\infty\land m(L/L')\geq0$ 故有 $m(L)=\infty$

与可求长定义不符，故 $L'$ 必定可求长

* <<MK2>> $R^n$ 空间光滑曲线长度

** 定义参数表示光滑曲线<<MK48>>

设向量值函数 $\vec{x}(t)$ 为 $R$ 到 $R^n$ 的映射，且 $t\in[a,b]$ 则映射的曲线称为 $L$

若 $x'_j(t)$ 连续且 $x'_j(t)$ 不同时全部为零，则称光滑

** 定义划分

划分 $P$ 将 $[a,b]$ 划分为 $a=t_0<t_1<...<t_m=b$

则两点 $\vec{x}(t_i),\vec{x}(t_{i-1})$ 之间的直线距离为 $\sqrt{\sum_{j=1}^n\left(x_j(t_i)-x_j(t_{i-1})\right)^2}$

定义 $\Delta t_i=t_i-t_{i-1},\lambda=\max(t_i-t_{i-1})$ 则根据空间连续曲线长度定义 $\lim_{\lambda\to0}\sum_{i=1}^m \sqrt{\sum_{j=1}^n\left(x_j(t_i)-x_j(t_{i-1})\right)^2}=S$ 为 $L$ 的长度

** 转换和式

由于 $x'_j(t)$ 存在且连续，故 $x_j(t)$ 在 $[a,b]$ 上连续且可导，则 $x_j(t)$ 在 $[t_{i-1},t_i]$ 上连续 $(t_{i-1},t_i)$ 上可导

故根据[[~/文档/note/大学物理/Note/DiffEq.org][导数基本知识-拉格朗日中值定理]]得 $x_j(t_i)-x_j(t_{i-1})=x'_j(\xi_{ij})\Delta t_i$ 其中 $\xi_{ij}\in[t_{i-1},t_i]$

故长度和式可写为 $\sum_{i=1}^m \sqrt{\sum_{j=1}^n\left(x_j(t_i)-x_j(t_{i-1})\right)^2}=\sum_{i=1}^m \left\{\sqrt{\sum_{j=1}^n x'_j(\xi_{ij})^2}\Delta t_i\right\}$

** 定义函数

定义 $\phi_i(\vec{\xi}_i)=\sqrt{\sum_{j=1}^n x'_j(\xi_{ij})^2}$ 由于 $x'_j(t)$ 连续且函数为连续函数的初等变换，故 $\phi_i(\vec{\xi}_i)$ 也连续

又根据[[~/文档/note/数学分析/Chap11Note.org][连续函数性质-康托定理]]可得 $\phi_i(\vec{\xi}_i)$ 在 $[t_{i-1},t_i]$ 上一致连续

根据[[~/文档/note/数学分析/Chap11Note.org][连续函数性质-补充多元函数一致连续定义]]可得 $\forall \epsilon>0,\exists \delta_1>0,\forall|\vec{\xi}_{i_1}-\vec{\xi}_{i_2}|<\delta\Rightarrow |\phi_i(\vec{\xi}_{i_1})-\phi_i(\vec{\xi}_{i_2})|<\frac{\epsilon}{2(b-a)}$

** 证明结论

根据定义 $\forall\epsilon>0,\exists\delta_2,\forall \lambda<\delta\Rightarrow \left|\sum_{i=1}^m \sqrt{\sum_{j=1}^n\left(x_j(t_i)-x_j(t_{i-1})\right)^2}-S\right|<\frac{\epsilon}{2}$

即 $\forall\epsilon>0,\exists\delta_2,\forall \lambda<\delta\Rightarrow \left|\sum_{i=1}^m \left\{\sqrt{\sum_{j=1}^n x_j(\xi_{ij})^2}\Delta t_i\right\}-S\right|<\frac{\epsilon}{2}\Rightarrow  \left|\sum_{i=1}^m \left\{\phi_i(\vec{\xi}_i)\Delta t_i\right\}-S\right|<\frac{\epsilon}{2}$

则当 $\lambda<\min(\delta_1,\delta_2)$ 时 $\left|\sum_{i=1}^n \left\{\phi_i(\vec{\xi}_i)\Delta t_i\right\}-\sum_{i=1}^n \left\{\phi_i(\vec{t}_i^*)\Delta t_i\right\}\right|$ 其中 $\vec{t}^*_i=(t_i,t_i,...,t_i),t_i^*\in[t_{i-1},t_i]$

故有 $\forall\epsilon>0,\exists\delta=\min(\delta_1,\delta_2),\forall \lambda<\delta$ 时有

\begin{aligned}
&\left|\sum_{i=1}^m \left\{\sqrt{\sum_{j=1}^n x'_j(t^*_i)^2}\Delta t_i\right\}-S\right|\\
=&\left|\sum_{i=1}^m \left\{\phi_i(\vec{t}^*_i)\Delta t_i\right\}-\sum_{i=1}^m \left\{\phi_i(\vec{\xi}_i)\Delta t_i\right\}+\sum_{i=1}^m \left\{\phi_i(\vec{\xi}_i)\Delta t_i\right\}-S\right|\\
\leq &\left|\sum_{i=1}^m \left\{\phi_i(\vec{t}^*_i)\Delta t_i\right\}-\sum_{i=1}^m \left\{\phi_i(\vec{\xi}_i)\Delta t_i\right\}\right|+\left|\sum_{i=1}^m \left\{\phi_i(\vec{\xi}_i)\Delta t_i\right\}-S\right|\\
<&\left|\frac{\epsilon}{2(b-a)}\sum_{i=1}^m\Delta t_i\right|+\frac{\epsilon}{2}\\
=&\epsilon
\end{aligned}

即 $\lim_{\lambda\to0}\sum_{i=1}^m \left\{\sqrt{\sum_{j=1}^n x'_j(t^*_i)^2}\Delta t_i\right\}=S$ 的定义，且与 $P,\vec{t}^*_i$ 的划分与取点无关

故 $\int_a^b \sqrt{\sum_{j=1}^n x'_j(t)^2}dt=S$

* <<MK27>>有界闭区域上的连续函数必能分成有限个 $>0,<0,=0$ 的区域

定义 $D\subset R^n$ 为有界闭集，函数 $F(\vec{x}),x\in D$ 上连续，则区域 $D$ 必能划分为 $k<\infty$ 个子区域，每个子区域上 $F(\vec{x})$ 不变号或等于零

** 证明

反正法，假设 $k=\infty$ 因为有界闭集，故存在 $D_0=[a^0_1,b^0_1]\times[a^0_2,b^0_2]\times...\times[a^0_n,b^0_n]\Rightarrow D\subset D_0$

将 $D_s$ 的每个维度取点 $\frac{a^0_i+b^0_i}{2}$ 切分成 $\left[a^0_i,\frac{a^0_i+b^0_i}{2}\right],\left[\frac{a^0_i+b^0_i}{2},b^0_i\right]$ 两个区间，每个维度分为两个区间，将区间划分组合，形成 $2^n$ 个子区域

其中必有一个子区域与 $D$ 的交集可被划分为无限个 $F(\vec{x})$ 不变号或等于零的子区域，不妨设 $D_1=[a^1_1,b^1_1]\times[a^1_2,b^1_2]\times...\times[a^1_n,b^1_n],S_1=D\cap D_1$

以此类推，则有一组区域 $\{S_i\}$ 满足

（1） $S_1\supset S_2\supset S_3\supset...\supset S_n\supset...\\$

（2） $\lim_{i\to\infty} diam S_i=0$ ，其中 $diamS_i=sup\{|x-y|\big|x,y\in S_i\}$

则根据[[~/文档/note/数学分析/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-康托闭区域套定理]]有且仅有唯一点 $\vec{x}_0\in\cap_{i=1}^\infty S_i$

又因为根据定义 $S_i$ 必定包含无限个 $F(\vec{x})$ 不变号或等于零的子区域，故函数 $F(\vec{x})$ 在 $\vec{x}_0$ 点必不连续

由于 $\vec{x}_0\subset...\subset S_i\subset...\subset S_1\subset D$ 且 $F(\vec{x})$ 在 $D$ 上连续，故 $F(\vec{x}_0)$ 也连续，故推出矛盾。

* 第一类曲线积分

** 定义

若 $L$ 是 $R^n$ 空间内的可求长曲线 $f(\vec{x})$ 在 $L$ 上有界

对 $L$ 做划分 $P$ 分点为 $P_0,P_2,...,P_n$ 其中 $P_0,P_n$ 分别为曲线的两个端点

对于某段弧 $P_{i-1}P_i$ 定义 $\Delta s_i$ 为弧长 $\vec{x}_i$ 为弧上一点

定义 $\lambda=\max(\Delta s_i)$

若 $\forall (P,\vec{x}_i)$ 即对于任意划分与取点，均有 $\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x}_i)\Delta s_i=I$ （ $-\infty<I<\infty$ 不随划分与取点变动）

则称此极限为曲线 $L$ 上的第一类曲线积分，记为 $\int_L f(\vec{x})ds=\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x}_i)\Delta s_i$

由于曲线积分为黎曼和，故其必满足黎曼积分充要条件

** 收敛条件

*** <<MK1>>连续函数

若 $f(\vec{x})$ 为定义在 $L$ 上的连续函数，则 $\int_Lf(\vec{x})ds$ 存在

**** 证明

由于 $f(\vec{x})$ 连续，且线段 $L$ 为有界闭区域（所有点均为聚点）故根据[[~/文档/note/数学分析/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-Heine-Borel定理]] $L$ 是紧集，根据[[~/文档/note/数学分析/Chap11Note.org][连续函数性质-康托定理]] $f(\vec{x})$ 一致连续

即 $\forall\epsilon>0,\exists\delta',\forall|\vec{x}_1-\vec{x}_2|<\delta\Rightarrow |f(\vec{x}_1)-f(\vec{x}_2)|<\frac{\epsilon}{S}$ 其中 $S$ 为线段 $L$ 的长度

故有 $\forall\epsilon>0,\exists\delta=\delta',\forall\lambda<\delta\Rightarrow\sum_{i=1}^n \omega_i\Delta s_i<\sum_{i=1}^n \frac{\epsilon}{S}\Delta s_i=\frac{\epsilon}{S}\sum_{i=1}^ns_i=\epsilon$

故根据[[~/文档/note/数学分析/Chap7Note.org][定积分可积定理-定积分可积充要条件2]]黎曼和 $\forall(P,\vec{x}_i)$ 收敛，故 $\int_Lf(\vec{x})ds$ 存在

** 性质

*** <<MK6>>线性

若 $\int_Lf(\vec{x})ds,\int_Lg(\vec{x})ds$ 存在，则 $\int_LAf(\vec{x})+Bg(\vec{x})ds=A\int_Lf(\vec{x})ds+B\int_Lg(\vec{x})ds$

**** 证明

根据定义 $\forall(P,\vec{x}):\int_LAf(\vec{x})+Bg(\vec{x})ds=\lim_{\lambda\to0}\left(\sum_{i=1}^n Af(\vec{x}_i)+\sum_{i=1}^n Bg(\vec{x}_i)\right)\Delta s_i$

根据极限四则运算 $\lim_{\lambda\to0}\left(\sum_{i=1}^n Af(\vec{x}_i)+\sum_{i=1}^n Bg(\vec{x}_i)\right)\Delta s_i=A\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x}_i)\Delta s_i+B\lim_{\lambda\to0}\sum_{i=1}^n g(\vec{x}_i)\Delta s_i$

由于 $\int_Lf(\vec{x})ds,\int_Lg(\vec{x})ds$ 存在，故 $\forall (P,\vec{x}_i)$ 均有 $\int_L f(\vec{x})ds=\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x}_i)\Delta s_i,\int_L g(\vec{x})ds=\lim_{\lambda\to0}\sum_{i=1}^n g(\vec{x}_i)\Delta s_i$

证毕。

*** <<MK7>>区间可加

若 $L$ 分为 $L_1,L_2$ 两段，则

（1） $\int_L f(\vec{x})ds$ 存在，则 $\int_{L_1} f(\vec{x})ds,\int_{L_2} f(\vec{x})ds$ 也存在

（2） $\int_{L_1} f(\vec{x})ds,\int_{L_2} f(\vec{x})ds$ 存在，则 $\int_L f(\vec{x})ds$ 也存在

且两种情况都有 $\int_L f(\vec{x})ds=\int_{L_1} f(\vec{x})ds+\int_{L_2} f(\vec{x})ds$

**** 证明 

由于曲线积分为黎曼和，故其必满足黎曼积分充要条件

***** 证明（1）

由于 $\int_L f(\vec{x})ds$ 存在，故根据[[~/文档/note/数学分析/Chap7Note.org][定积分可积定理-定积分可积充要条件2]] $\forall\epsilon>0,\exists\delta,\forall\lambda<\delta\Rightarrow \forall P:\sum_{i=1}^n \omega_i\Delta s_i<\epsilon$ 

则存在一组划分 $P^*$ 使得 $P^*_k$ 正好划分 $L_1,L_2$ ，且由于 $\omega_i\Delta s_i>0$ 故有

$\forall\epsilon>0,P^*\Rightarrow \sum_{i=1}^k \omega_i\Delta s_i<\epsilon$ 

$\forall\epsilon>0,P^*\Rightarrow \sum_{i=k+1}^n \omega_i\Delta s_i<\epsilon$

又根据[[~/文档/note/数学分析/Chap7Note.org][定积分可积定理-定积分可积充要条件3]]得 $\int_{L_1} f(\vec{x})ds,\int_{L_2} f(\vec{x})ds$ 均可积收敛

***** 证明（2）

由于 $\int_{L_1} f(\vec{x})ds,\int_{L_2} f(\vec{x})ds$ 存在，故根据[[~/文档/note/数学分析/Chap7Note.org][定积分可积定理-定积分可积充要条件2]]有：

$\forall\epsilon>0,\exists\delta_1,\forall\lambda<\delta\Rightarrow \forall P_1:\sum_{i=1}^k \omega_i\Delta s_i<\frac{\epsilon}{2}$ 

$\forall\epsilon>0,\exists\delta_2,\forall\lambda<\delta\Rightarrow \forall P_2:\sum_{i=k+1}^n \omega_i\Delta s_i<\frac{\epsilon}{2}$

则 $\forall\epsilon>0,\exists P=P_1\cup P_2\Rightarrow \sum_{i=1}^n\omega_i s_i=\sum_{i=1}^k\omega_i s_i+\sum_{i=k+1}^n\omega_i s_i<\epsilon$

又根据[[~/文档/note/数学分析/Chap7Note.org][定积分可积定理-定积分可积充要条件3]]得 $\int_L f(\vec{x})ds$ 存在

***** 证明等式

由于 $\int_L f(\vec{x})ds$ 存在

则 $\forall (P,\vec{x}_i)\Rightarrow \lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x}_i)\Delta s_i=I$

则存在特殊 $P^*$ 正好区分 $L$ 为 $L_1,L_2$ 与 $P_k$ 点

则有 $\forall (P^*,\vec{x})\Rightarrow \lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x}_i)\Delta s_i=\lim_{\lambda\to0}\left(\sum_{i=1}^k f(\vec{x}_i)\Delta s_i+\sum_{i=k+1}^n f(\vec{x}_i)\Delta s_i\right)=I$

根据极限四则运算 $\lim_{\lambda\to0}\left(\sum_{i=1}^k f(\vec{x}_i)\Delta s_i+\sum_{i=k+1}^n f(\vec{x}_i)\Delta s_i\right)=\lim_{\lambda\to0}\sum_{i=1}^k f(\vec{x}_i)\Delta s_i+\lim_{\lambda\to0}\sum_{i=k+1}^n f(\vec{x}_i)\Delta s_i$  

又由于 $\int_{L_1} f(\vec{x})ds,\int_{L_2} f(\vec{x})ds$ 均存在 则有 $\forall (P^*,\vec{x})\Rightarrow \lim_{\lambda\to0}\sum_{i=1}^k f(\vec{x}_i)\Delta s_i=\int_{L_1}f(\vec{x})ds$

同理有 $\forall (P^*,\vec{x})\Rightarrow \lim_{\lambda\to0}\sum_{i=k+1}^n f(\vec{x}_i)\Delta s_i=\int_{L_2}f(\vec{x})ds$

故 $I=\int_{L_2}f(\vec{x})ds+\int_{L_1}f(\vec{x})ds$ 证毕

** <<MK8>>计算

定义 $L$ 的参数表示为 $\vec{x}(t)=\begin{cases}x_1(t)\\x_2(t)\\...\\x_n(t)\end{cases},t\in[a,b]$ 为 $R$ 到 $R^n$ 的一一对应映射。若：

（1） 函数 $f(\vec{x})$ 为在曲线 $L$ 上连续的函数

（2） $x_j(t),t\in(a,b)$ 一阶导数存在且连续

（3） $\sum_{j=1}^n x'_j(t)^2\ne 0$

则有 $\int_L f(\vec{x})ds=\int_a^b\left\{f(\vec{x}(t))\sqrt{\sum_{j=1}^n x'_j(t)^2}\right\}dt$

*** 证明

由于 $\vec{x}$ 为 $t\in[a,b]$ 到 $L$ 上的满射（ $L$ 上任意一点都有对应 $\vec{x}(t),t\in[a,b]$ ）故任意对 $L$ 的划分 $P$ 上的分点 $P_i$ 均有对应的 $t_i\in[a,b]$

所以之后定义 $P$ 为对 $[a,b]$ 的划分

由于 $f(\vec{x})$ 连续故根据[[MK1][连续函数]]曲线积分 $\int_Df(\vec{x})ds$ 存在

写出曲线积分黎曼和 $\sum_{i=1}^n f(\vec{x}_i)\Delta s_i$ 

根据[[MK2][弧长公式]] $\Delta s_i=\int_{t_{i-1}}^{t_i} \sqrt{\sum_{j=1}^n x'_i(t)}dt$

根据参数方程 $\vec{x}_i=\vec{x}(t_i)$

改写曲线积分黎曼和为 $\sum_{i=1}^n f(\vec{x}(t_i))\int_{t_{i-1}}^{t_i} \sqrt{\sum_{j=1}^n x'_i(t)}dt$

根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-区间可加]]亦有 $\int_a^b\left\{f(\vec{x}(t))\sqrt{\sum_{j=1}^n x'_j(t)^2}\right\}dt=\sum_{i=1}^n \int_{t_{i-1}}^{t_i}f(\vec{x}(t))\sqrt{\sum_{j=1}^n x'_j(t)^2}dt$

由于 $x'_j(t)$ 连续，故 $x_j(t)$ 为连续函数，又由于 $f(\vec{x})$ 连续，故 $f(\vec{x}(t))$ 连续，又由于 $t\in[a,b]$

故根据[[~/文档/note/数学分析/Chap7Note.org][函数一致连续-康托定理]] $f(\vec{x}(t))$ 一致连续

即 $\forall\epsilon>0,\exists\delta,\forall|t'-t|<\delta,t',t\in[a,b]\Rightarrow\left|f(\vec{x}(t'))-f(\vec{x}(t))\right|<\frac{\epsilon}{S}$

则根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-保序]]有 $\int_{t_{i-1}}^{t_i}\left\{\left[f(\vec{x}(t'))-f(\vec{x}(t))\right]\sqrt{\sum_{j=1}^n x'_j(t)^2}\right\}dt<\int_{t_{i-1}}^{t_i}\left\{\frac{\epsilon}{S}\sqrt{\sum_{j=1}^n x'_j(t)^2}\right\}dt=\frac{\epsilon}{S}\int_{t_{i-1}}^{t_i}\sqrt{\sum_{j=1}^n x'_j(t)^2}dt$

则当 $\lambda<\delta$ 时，根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-线性]]及[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-区间可加]]

\begin{aligned}
&\sum_{i=1}^n f(\vec{x}(t_i))\int_{t_{i-1}}^{t_i} \sqrt{\sum_{j=1}^n x'_i(t)^2}dt-\sum_{i=1}^n \int_{t_{i-1}}^{t_i}f(\vec{x}(t))\sqrt{\sum_{j=1}^n x'_j(t)^2}dt\\
=&\sum_{i=1}^n\int_{t_{i-1}}^{t_i}\left\{\left[f(\vec{x}(t_i))-f(\vec{x}(t))\right]\sqrt{\sum_{j=1}^n x'_j(t)^2}\right\}dt\\
<&\sum_{i=1}^n\frac{\epsilon}{S}\int_{t_{i-1}}^{t_i}\sqrt{\sum_{j=1}^n x'_j(t)^2}dt\\
=&\epsilon\\
\end{aligned}

* $R^n$ 下曲面面积

若曲面 $\Omega\subset R^n$ 的参数表示为 $\vec{x}(u,v)=\begin{cases}x_1(u,v)\\x_2(u,v)\\...\\x_n(u,v)\end{cases},(u,v)\in D\subset R^2$ 为 $R^2$ 到 $R^n$ 的一一对应映射，且满足

（1） 参数函数的偏导数在 $(u,v)\in D$ 上存在且连续

（2） 雅克比矩阵 $\left|\frac{\partial \vec{x}(u,v)}{\partial (u,v)}\right|=\left|\begin{matrix}\frac{\partial x_1(u,v)}{\partial u}&\frac{\partial x_1(u,v)}{\partial v}\\\frac{\partial x_2(u,v)}{\partial u}&\frac{\partial x_2(u,v)}{\partial v}\\...&...\\\frac{\partial x_n(u,v)}{\partial u}&\frac{\partial x_n(u,v)}{\partial v}\end{matrix}\right|$ 满秩，即有一组2阶行列式不为零

则曲面 $\Omega$ 的面积为 $\int_D\left\|\vec{r}_u(u,v)\times \vec{r}_v(u,v)\rignt\|dudv$ 其中 $\vec{r}_u(u,v)=\frac{\partial \vec{x}(u,v)}{\partial u}$ ，$\vec{r}_v(u,v)$ 同理

** 证明

*** <<MK4>>证明重积分可积

由于 $\left\|\vec{r}_u(u,v)\times \vec{r}_v(u,v)\rignt\|$ 为向量操作，定义为 $\sin(\theta)\left|\vec{r}_u(u,v)\right|\left|\vec{r}_v(u,v)\right|$ 其中 $\theta$ 为两向量的夹角

向量长度分别为 $|\vec{r}_u(u,v)|=\sqrt{\sum_{i=1}^n\left(\frac{\partial x_i(u,v)}{\partial u}\right)^2},|\vec{r}_v(u,v)|=\sqrt{\sum_{i=1}^n\left(\frac{\partial x_i(u,v)}{\partial v}\right)^2}$ 由向量点积可知 $\cos(\theta)=\frac{\sum_{i=1}^n \frac{\partial x_i(u,v)}{\partial u}\frac{\partial x_i(u,v)}{\partial v}}{|\vec{r}_u(u,v)||\vec{r}_v(u,v)|}$ 则 $\sin(\theta)=\pm\sqrt{1-\cos(\theta)^2}$

且由于向量连续变化，角度也连续变化。

综合上式得 $$\|\vec{r}_u(u,v)\times \vec{r}_v(u,v)\|=\pm\sqrt{1-\left(\frac{\sum_{i=1}^n \frac{\partial x_i(u,v)}{\partial u}\frac{\partial x_i(u,v)}{\partial v}}{\sqrt{\sum_{i=1}^n\left(\frac{\partial x_i(u,v)}{\partial u}\right)^2}\sqrt{\sum_{i=1}^n\left(\frac{\partial x_i(u,v)}{\partial v}\right)^2}}\right)^2}\sqrt{\sum_{i=1}^n\left(\frac{\partial x_i(u,v)}{\partial u}\right)^2}\sqrt{\sum_{i=1}^n\left(\frac{\partial x_i(u,v)}{\partial u}\right)^2}$$

由于雅克比行列式满秩，故 $\sqrt{\sum_{i=1}^n\left(\frac{\partial x_i(u,v)}{\partial u}\right)^2}\sqrt{\sum_{i=1}^n\left(\frac{\partial x_i(u,v)}{\partial u}\right)^2}>0$

且由于偏导数连续，则函数 $\phi(u,v)=\left\|\vec{r}_u(u,v)\times \vec{r}_v(u,v)\rignt\|$ 也连续

故根据[[~/文档/note/数学分析/Chap13Note.org][有界闭集上的重积分-二重积分-推论]]重积分可积

*** 证明重积分为曲面面积

假设 $D$ 上有矩形面积微元，四个顶点分别为 $P_1(u_0,v_0),P_2(u_0+\Delta u,v_0),P_3(u_0+\Delta u,v_0+\Delta v),P_4(u_0,v_0+\Delta v)$

映射到 $\Omega$ 上的四个顶点分别为 $Q_1=\vec{x}(u_0,v_0),Q_2=\vec{x}(u_0+\Delta u,v_0),Q_3=\vec{x}(u_0+\Delta u,v_0+\Delta v),Q_4=\vec{x}(u_0,v_0+\Delta v)$

此时平面上直线 $P_1P_2$ 被映射成弧 $Q_1Q_2=\vec{x}(u_0+\Delta u,v_0)-\vec{x}(u_0,v_0)=\sum_{i=1}^n (x_i(u_0+\Delta u,v_0)-x_i(u_0,v_0))\vec{e}_i$ 其中 $\vec{e}_i$ 为沿空间第 $i$ 个数轴的单位向量

由于偏导数均存在且连续，故根据[[~/文档/note/数学分析/Chap12Note.org][偏导数与全微分-可微条件]]分量函数均可微

故根据[[~/文档/note/数学分析/Chap12Note.org][偏导数与全微分-欧几里得空间连续，可导，可微及方向导数关系-可微与偏导]]有 $x_i(u_0+\Delta u,v_0)-x_i(u_0,v_0)=\frac{\partial x_i(u_0,v_0)}{\partial u}\Delta u+o_i(\Delta u)$ 

其中 $v_0$ 不变可视为常数且 $\lim_{\Delta u\to0}\frac{o_i(\Delta u)}{\Delta u}=0$ ，故定义 $\vec{o}(\Delta u)=\sum_{i=1}^n o_i(\Delta u)$

则 $\overrightarrow{Q_1Q_2}=\sum_{i=1}^n\left(\frac{\partial x_i(u_0,v_0)}{\partial u}\Delta u+o_{x_i}(\Delta u)\right)\vec{e}_i=\vec{r}_u(u_0,v_0)\Delta u + \vec{o}(\Delta u)$ 同理 $\overrightarrow{Q_1Q_4}=\sum_{i=1}^n\left(\frac{\partial x_i(u_0,v_0)}{\partial v}\Delta u+o_{x_i}(\Delta u)\right)\vec{e}_i=\vec{r}_v(u_0,v_0)\Delta u + \vec{o}(\Delta u)$

故根据极限四则运算 $\lim_{\Delta u\to0,\Delta v\to0}\frac{\left\|Q_1Q_2\times Q_1Q_3\right\|}{\Delta u\Delta v}=\left\|\vec{r}_u(u_0,v_0)\times \vec{r}_v(u_0,v_0)\right\|$

由于 $\left\|Q_1Q_2\times Q_1Q_3\right\|$ 为向量围成平行四边形面积，当 $\Delta u,\Delta v$ 无限小时等于 $Q_1Q_2Q_3Q_4$ 围成小片面积

故面积微元 $ds=\left\|\vec{r}_u(u_0,v_0)\times \vec{r}_v(u_0,v_0)\right\|dudv$ 

由于重积分可积，则任意划分不影响重积分的结果，故重积分 $\iint_D\left\|\vec{r}_u(u_0,v_0)\times \vec{r}_v(u_0,v_0)\right\|dudv$ 的值同特殊矩形划分的值，为曲面面积

*** <<MK24>> $R^3$ 下的曲面面积

**** $R^3$ 下向量叉乘的范数

由于 $R^3$ 下

\begin{aligned}
\vec{r}_u(u,v)\times \vec{r}_v(u,v)=&\left|\begin{matrix}\vec{i}&\vec{j}&\vec{k}\\\frac{\partial x(u,v)}{\partial u}&\frac{\partial y(u,v)}{\partial u}&\frac{\partial z(u,v)}{\partial u}\\\frac{\partial x(u,v)}{\partial v}&\frac{\partial y(u,v)}{\partial v}&\frac{\partial z(u,v)}{\partial v}\end{matrix}\right|\\
=&\left(\frac{\partial y(u,v)}{\partial u}\frac{\partial z(u,v)}{\partial v}-\frac{\partial y(u,v)}{\partial v}\frac{\partial z(u,v)}{\partial u}\right)\vec{i}+
\left(\frac{\partial x(u,v)}{\partial u}\frac{\partial z(u,v)}{\partial v}-\frac{\partial x(u,v)}{\partial v}\frac{\partial z(u,v)}{\partial u}\right)\vec{j}+
\left(\frac{\partial x(u,v)}{\partial u}\frac{\partial y(u,v)}{\partial v}-\frac{\partial x(u,v)}{\partial v}\frac{\partial y(u,v)}{\partial u}\right)\vec{k}\\
=&(y_uz_v-y_vz_u)\vec{i}+(x_uz_v-x_vz_u)\vec{j}+(x_uy_v-x_vy_u)\vec{k}
\end{aligned} 

<<MK13>>故范数为 

\begin{aligned}
\left\|\vec{r}_u(u,v)\times \vec{r}_v(u,v)\right\|^2=&\left\|(y_uz_v-y_vz_u)\vec{i}+(x_uz_v-x_vz_u)\vec{j}+(x_uy_v-x_vy_u)\vec{k}\right\|^2\\
=&(y_uz_v-y_vz_u)^2+(x_uz_v-x_vz_u)^2+(x_uy_v-x_vy_u)^2\\
=&y_u^2z_v^2+y_v^2z_u^2+x_u^2z_v^2+x_v^2z_u^2+x_u^2y_v^2+x_v^2y_u^2-2y_uz_vy_vz_u-2x_uz_vx_vz_u-2x_uy_vx_vy_u\\
=&(x_u^2+y_u^2+z_u^2)(x_v^2+y_v^2+z_v^2)-(x_ux_v+y_uy_v+z_uz_v)^2\\
=&EG-F^2
\end{aligned} 

**** $R^3$ 下面积公式整理

综合上述证明， $R^3$ 下面积公式为 $\iint_D\sqrt{EG-F^2}dudv$ 其中 $E=x_u^2+y_u^2+z_u^2,G=x_v^2+y_v^2+z_v^2,F=x_ux_v+y_uy_v+z_uz_v$

若 $x=x,y=y,z=f(x,y)$ 则有 $\iint_D\sqrt{EG-F^2}dudv=\iint_D \sqrt{1+f_x(x,y)^2+f_y(x,y)^2}dxdy$

若存在一个函数 $H(x,y,z)$ 在区域 $(x,y)\in D$ 上有 $H(x,y,z)=0$ 且 $H(x,y,z)$ 有连续偏导

则根据[[~/文档/note/数学分析/Chap12Note.org][隐函数-多元隐函数存在定理]]存在 $z=f(x,y),(x,y)\in D$ 有连续导数且 $\frac{\partial f(x,y)}{\partial x}=\frac{H_x(x,y,z)}{H_z(x,y,z)}$

故有 $\iint_D \sqrt{1+f_x(x,y)^2+f_y(x,y)^2}dxdy=\iint_D \frac{\sqrt{H_z(x,y,z)^2+H_z(x,y,z)^2+H_z(x,y,z)^2}}{|H_z(x,y,z)|}dxdy$

* 第一类曲面积分

** <<MK5>>定义

若 $\Omega$ 是 $R^n$ 空间上的曲面，将曲面用光滑曲线分割为小曲面 $\Delta\Omega_i$ 定义

（1） $\vec{x}_i\in\Delta\Omega_i$ 为小区面内任意一点

（2） $\Delta\Omega_i$ 面积为 $\Delta S_i$ 

（3） $\lambda_i$ 为曲面 $\Delta\Omega_i$ 的直径， $\lambda=\max(\lambda_i)$

函数 $f(\vec{x})$ 在曲面 $\Omega$ 上有定义，若对于任意划分与取点均有 $\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x})\Delta S_i=I,-\infty<I<+\infty$

则称此极限为曲线 $\Omega$ 上的第一类曲面积分，记为 $\iint_\Omega f(\vec{x})ds=\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x})\Delta S_i$

** 收敛条件

*** <<MK3>>连续函数

若 $f(\vec{x})$ 为定义在 $\Omega$ 上的连续函数，则 $\iint_\Omega f(\vec{x})ds$ 存在

**** 证明

由于 $f(\vec{x})$ 连续，且曲面 $\Omega$ 为有界闭区域（所有点均为聚点）故根据[[~/文档/note/数学分析/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-Heine-Borel定理]] $\Omega$ 是紧集，

根据[[~/文档/note/数学分析/Chap11Note.org][连续函数性质-康托定理]] $f(\vec{x})$ 一致连续，即 $\forall\epsilon>0,\exists\delta',\forall|\vec{x}_1-\vec{x}_2|<\delta\Rightarrow |f(\vec{x}_1)-f(\vec{x}_2)|<\frac{\epsilon}{S}$ 其中 $S$ 为曲面 $\Omega$ 的总面积

则有 $\forall\epsilon>0,\exists\delta=\delta',\forall\lambda<\delta\Rightarrow\sum_{i=1}^n \omega_i\Delta s_i<\sum_{i=1}^n \frac{\epsilon}{S}\Delta s_i=\frac{\epsilon}{S}\sum_{i=1}^n\Delta S_i=\epsilon$ 其中 $\omega_i$ 为曲面 $\Delta\Omega_i$ 内函数 $f(\vec{x})$ 的振幅

故根据[[~/文档/note/数学分析/Chap13Note.org][可积条件-可积充要条件2]] $\iint_\Omega f(\vec{x})ds$ 存在收敛

** 性质

*** <<MK10>>线性

若 $\iint_\Omega f(\vec{x})ds,\iint_\Omega g(\vec{x})ds$ 均存在，则 $A\iint_\Omega f(\vec{x})ds+B\iint_\Omega f(\vec{x})ds=\iint_\Omega \left\{Af(\vec{x})+ Bg(\vec{x})\right\}ds$

**** 证明

根据曲面积分定义 $\iint_\Omega \left\{Af(\vec{x})+ Bg(\vec{x})\right\}ds=\lim_{\lambda\to0}\sum_{i=1}^n \left\{Af(\vec{x}_i)+ Bg(\vec{x}_i)\right\}\Delta S_i$

根据极限四则运算 $\lim_{\lambda\to0}\sum_{i=1}^n \left\{Af(\vec{x})+ Bg(\vec{x})\right\}\Delta S_i=A\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x}_i)\Delta S_i+B\lim_{\lambda\to0}\sum_{i=1}^n g(\vec{x}_i)\Delta S_i$

同理 $\iint_\Omega f(\vec{x})ds=\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x}_i)\Delta S_i,\iint_\Omega g(\vec{x})ds=\lim_{\lambda\to0}\sum_{i=1}^n g(\vec{x}_i)\Delta S_i$ 对于任意划分与取点都成立

故有 $A\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x}_i)\Delta S_i+B\lim_{\lambda\to0}\sum_{i=1}^n g(\vec{x}_i)\Delta S_i=\lim_{\lambda\to0}\sum_{i=1}^n \left\{Af(\vec{x}_i)+ Bg(\vec{x}_i)\right\}\Delta S_i$ 对于任意划分与取点均成立

则 $A\iint_\Omega f(\vec{x})ds+B\iint_\Omega f(\vec{x})ds=\iint_\Omega \left\{Af(\vec{x})+ Bg(\vec{x})\right\}ds$

*** 区间可加

若 $\Omega$ 分为 $\Omega_1,\Omega_2$ 两段，则

（1） $\iint_\Omega f(\vec{x})ds$ 存在，则 $\iint_{\Ometa_1} f(\vec{x})ds,\iint_{\Omega_2} f(\vec{x})ds$ 也存在

（2） $\iint_{\Omega_1} f(\vec{x})ds,\iint_{\Omega_2} f(\vec{x})ds$ 存在，则 $\int_\Omega f(\vec{x})ds$ 也存在

且两种情况都有 $\int_\Omega f(\vec{x})ds=\int_{\Omega_1} f(\vec{x})ds+\int_{\Omega_2} f(\vec{x})ds$

**** 证明

***** 证明（1）

由于 $\iint_\Omega f(\vec{x})ds$ 存在，故根据[[~/文档/note/数学分析/Chap13Note.org][可积条件-可积充要条件2]] $\forall\epsilon>0,\exists\delta,\forall\lambda<\delta\Rightarrow \forall P:\sum_{i=1}^n \omega_i\Delta S_i<\epsilon$ 

则定义 $\{P^*\}$ 为正好将曲面划分为 $\Omega_1,\Omega_2$ 的分割集合，且由于 $\omega_i\Delta S_i>0$ 故有

$\forall\epsilon>0,P^*\Rightarrow \sum_{i=1}^k \omega_i\Delta S_i<\epsilon$ 

$\forall\epsilon>0,P^*\Rightarrow \sum_{i=k+1}^n \omega_i\Delta S_i<\epsilon$

由于对 $\Omega_1,\Omega_2$ 的任意分割均为 $\{P^*\}$ 的子集

故根据[[~/文档/note/数学分析/Chap13Note.org][可积条件-可积充要条件2]] $\int_{\Omega_1} f(\vec{x})ds,\int_{\Omega_2} f(\vec{x})ds$ 均可积收敛

***** 证明（2）

由于 $\int_{\Omega_1} f(\vec{x})ds,\int_{\Omega_2} f(\vec{x})ds$ 存在，故根据[[~/文档/note/数学分析/Chap13Note.org][可积条件-可积充要条件2]]有：

$\forall\epsilon>0,\exists\delta_1,\forall\lambda<\delta\Rightarrow \forall P_1:\sum_{i=1}^k \omega_i\Delta s_i<\frac{\epsilon}{2}$ 

$\forall\epsilon>0,\exists\delta_2,\forall\lambda<\delta\Rightarrow \forall P_2:\sum_{i=k+1}^n \omega_i\Delta s_i<\frac{\epsilon}{2}$

则 $\forall\epsilon>0,\exists P=P_1\cup P_2\Rightarrow \sum_{i=1}^n\omega_i s_i=\sum_{i=1}^k\omega_i s_i+\sum_{i=k+1}^n\omega_i s_i<\epsilon$

又根据[[~/文档/note/数学分析/Chap13Note.org][可积条件-重积分可积充要条件3]]得 $\int_\Omega f(x,y,z)ds$ 存在

***** 证明等式

由于 $\int_\Omega f(\vec{x})ds$ 存在

则 $\forall (P,\vec{x}_i)\Rightarrow \lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x}_i)\Delta S_i=I$

则存在特殊 $P^*$ 正好区分 $\Omega$ 为 $\Omega_1,\Omega_2$ 

则有 $\forall (P^*,\vec{x}_i)\Rightarrow \lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x}_i)\Delta S_i=\lim_{\lambda\to0}\left(\sum_{i=1}^k f(\vec{x}_i)\Delta S_i+\sum_{i=k+1}^n f(\vec{x}_i)\Delta S_i\right)=I$

根据极限四则运算 $\lim_{\lambda\to0}\left(\sum_{i=1}^k f(\vec{x}_i)\Delta S_i+\sum_{i=k+1}^n f(x_i,y_i,z_i)\Delta S_i\right)=\lim_{\lambda\to0}\sum_{i=1}^k f(\vec{x}_i)\Delta S_i+\lim_{\lambda\to0}\sum_{i=k+1}^n f(\vec{x}_i)\Delta S_i$  

又由于 $\int_{\Omega_1} f(\vec{x})ds,\int_{\Omega_2} f(\vec{x})ds$ 均存在 则有 $\forall (P^*,\vec{x})\Rightarrow \lim_{\lambda\to0}\sum_{i=1}^k f(\vec{x}_i)\Delta S_i=\int_{\Omega_1}f(\vec{x})ds$

同理有 $\forall (P^*,\vec{x})\Rightarrow \lim_{\lambda\to0}\sum_{i=k+1}^n f(\vec{x}_i)\Delta S_i=\int_{\Omega_2}f(\vec{x})ds$

故 $I=\int_{\Omega_2}f(\vec{x})ds+\int_{\Omega_1}f(\vec{x})ds$ 证毕

** <<MK38>>计算

若曲面 $\Omega\subset R^n$ 的参数表示为 $\vec{x}(u,v)=\begin{cases}x_1(u,v)\\x_2(u,v)\\...\\x_n(u,v)\end{cases},(u,v)\in D\subset R^2$ 为 $R^2$ 到 $R^n$ 的一一对应映射，且满足

（1） 参数函数的偏导数在 $(u,v)\in D$ 上存在且连续

（2） 雅克比矩阵 $\left|\frac{\partial \vec{x}(u,v)}{\partial (u,v)}\right|=\left|\begin{matrix}\frac{\partial x_1(u,v)}{\partial u}&\frac{\partial x_1(u,v)}{\partial v}\\\frac{\partial x_2(u,v)}{\partial u}&\frac{\partial x_2(u,v)}{\partial v}\\...&...\\\frac{\partial x_n(u,v)}{\partial u}&\frac{\partial x_n(u,v)}{\partial v}\end{matrix}\right|$ 满秩，即有一组2阶行列式不为零

若 $f(\vec{x})$ 在曲面上连续，则第一类曲面积分存在且 $\iint_\Omega f(x,y,z)ds=\iint_D f(x(u,v),y(u,v),z(u,v))\left\|\frac{\partial\vec{x}(u,v)}{\partial u}\times\frac{\partial\vec{x}(u,v)}{\partial u}\right\|dudv$

当 $n=3$ 即三维空间时， $\iint_\Omega f(x,y,z)ds=\iint_D f(x(u,v),y(u,v),z(u,v))\sqrt{EG-F^2}dudv$

其中 $E=x_u^2+y_u^2+z_u^2,G=x_v^2+y_v^2+z_v^2,F=x_ux_v+y_uy_v+z_uz_v$

若曲面函数为 $z=z(x,y)$ 则 $$\iint_\Omega f(x,y,z)ds=\iint_D f(x,y,z(x,y))\sqrt{1+\left(\frac{\partial z(x,y)}{\partial x}\right)^2+\left(\frac{\partial z(x,y)}{\partial x}\right)^2}dxdy$$

*** 证明

由于 $f(\vec{x})$ 在曲面上连续，根据[[MK3][连续函数条件]]得第一类曲面积分收敛，即对于任意取点与划分 $\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x}_i)\Delta S_i$

定义 $(u_i,v_i)$ 对应使得 $\vec{x}_i=\vec{x}_i(u_i,v_i)$ 并用面积公式代替 $\Delta S_i=\iint_{D_i}\left\|\frac{\partial\vec{x}(u,v)}{\partial u}\times\frac{\partial\vec{x}(u,v)}{\partial u}\right\|dudv$ 

由于 $\left\|\frac{\partial\vec{x}(u,v)}{\partial u}\times\frac{\partial\vec{x}(u,v)}{\partial u}\right\|$ 为 $u,v$ 的函数，定义 $\phi(u,v)=\left\|\frac{\partial\vec{x}(u,v)}{\partial u}\times\frac{\partial\vec{x}(u,v)}{\partial u}\right\|$

故重写和式为 $\sum_{i=1}^n f(\vec{x}(u_i,v_i))\iint_{D_i}\phi(u,v)dudv$ 

由于偏导数连续，且 $f(\vec{x})$ 连续，则 $f(\vec{x}(u,v))$ 连续，又根据[[MK4][之前证明]]函数 $\phi(u,v)$ 也连续

则 $f(\vec{x}(u,v))\phi(u,v)$ 是连续函数则根据[[~/文档/note/数学分析/Chap13Note.org][有界闭集上的重积分-二重积分-推论]]重积分收敛，即 $\iint_D f(\vec{x}(u,v))\phi(u,v)dudv$ 存在

故根据[[~/文档/note/数学分析/Chap13Note.org][重积分性质与计算-性质-区间可加性]]得 $\iint_D f(\vec{x}(u,v))\phi(u,v)dudv=\sum_{i=1}^n \iint_{D_i} f(\vec{x}(u,v))\phi(u,v)dudv$ 

其中 $D_i$ 为小曲面 $\Omega_i$ 对应的 $D$ 上的区域（由于 $\Omega$ 与 $D$ 一一映射，故任意划分曲面 $\Omega$ 有对应的 $D$ 划分，反之亦然）

由于 $(u,v)\in D$ 是有界闭集且 $f(\vec{x}(u,v))$ 连续，故根据[[~/文档/note/数学分析/Chap7Note.org][函数一致连续-康托定理]] $f(\vec{x}(u,v))$ 一致连续

即为 $\forall\epsilon>0,\exists\delta,\forall|(u_1,v_1)-(u_2,v_2)|<\delta\Rightarrow\left|f(\vec{x}(u_1,v_1))-f(\vec{x}(u_2,v_2))\right|<\frac{\epsilon}{S}$

其中 $S$ 为曲面面积，故若对 $D$ 的划分中 $\lambda<\delta$

\begin{aligned}
&\sum_{i=1}^n f(\vec{x}(u_i,v_i))\iint_{D_i}\phi(u,v)dudv-\sum_{i=1}^n \iint_{D_i} f(\vec{x}(u,v))\phi(u,v)dudv\\
=&\sum_{i=1}^n\iint_{D_i}\left\{f(\vec{x}(u_i,v_i))-f(\vec{x}(u,v))\right\}\phi(u,v)dudv\\
<&\sum_{i=1}^n\iint_{D_i}\frac{\epsilon}{S}\phi(u,v)dudv\\
=&\frac{\epsilon}{S}\sum_{i=1}^n\iint_{D_i}\phi(u,v)dudv\\
=&\epsilon\\
\end{aligned}

故 $\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x})\Delta S_i=\iint_D f(x(u,v),y(u,v),z(u,v))\left\|\frac{\partial\vec{x}(u,v)}{\partial u}\times\frac{\partial\vec{x}(u,v)}{\partial u}\right\|dudv$

根据[[MK5][定义]] $\iint_\Omega f(\vec{x})ds=\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{x})\Delta S_i$ 故证毕。 

* 第二类曲线积分

** 定义<<MK22>>

假设[[MK52][可求长]]曲线 $L\subset\mathbb{R}^n$ 两个端点分别为 $A$ 到 $B$ ，首先定义曲线方向为 $A$ 到 $B$

若存在向量值函数 $\vec{F}(\vec{x})=\begin{cases}f_1(\vec{x})\\f_2(\vec{x})\\...\\f_k(\vec{x})\end{cases},\vec{x}\in L$ 有定义（有界）

对 $L$ 做划分 $P$ 分点为 $\vec{x}_0,\vec{x}_1,...,\vec{x}_{n+1}$ 其中 $\vec{x}_0,\vec{x}_{n+1}$ 分别为曲线的两个端点

对于某段弧 $\vec{x}_i\vec{x}_{i+1}$ 定义 $\Delta s_i$ 为弧长 $\vec{\xi}_i$ 为弧上一点

定义 $\lambda=\max(\Delta s_i),\Delta \vec{x}_i=\vec{x}_{i+1}-\vec{x}_i$

若 $\forall (P,\vec{\xi}_i)$ 即对于任意划分与取点，均有 $\lim_{\lambda\to0}\sum_{i=1}^n \vec{F}(\vec{\xi}_i)\cdot\Delta \vec{x}_i=I$ （ $-\infty<I<\infty$ 不随划分与取点变动）

则称此极限为曲线 $L$ 上的第二类曲线积分，记作 $$\lim_{\lambda\to0}\sum_{i=1}^n \vec{F}(\vec{\xi}_i)\cdot\Delta \vec{x}_i=\int_L\vec{F}(\vec{x})\cdot d\vec{x}$$

** 性质

*** 连续函数可积

若 $\vec{F}(\vec{x})$ 有限维，在可求长曲线 $L\subset\mathbb{R}^n$ 上连续，则其第二类曲线积分存在

**** 证明

***** 特殊的收敛数列<<MK53>>

定义划分 $P^n=\{\vec{x}_1,...,\vec{x}_{n+1}\}$ 将 $L$ 按其长度 $n$ 等分，定义取点 $\vec{\xi}_{i}$ 为弧 $\vec{x}_{i}\vec{x}_{i+1}$ 的长度中点。

根据[[MK22][定义]]可积，则 $\vec{F}(\vec{x})$ 有界，定义其 *模* 最大值 $\left|\vec{F}(\vec{x})\right|\leq M,\vec{x}\in L$

则有 $\left|\vec{F}(\vec{x}_i)\cdot\Delta\vec{x}_i\right|=\left|\sum_{i=1}^mf_j(\vec{x}_i)\Delta x_{(j)i}\right|\leq\sum_{i=1}^m\left|f_j(\vec{x}_i)\right|\left|\Delta x_{(j)i}\right|\leq M\sum_{i=1}^m\left|\Delta x_{(j)i}\right|$

由于弧长大于弦长大于边的投影，固有 $S_n=\sum_{i=1}^n\vec{F}(\vec{x})\cdot\Delta\vec{x}_i\leq M\sum_{i=1}^n\left(\sum_{j=1}^n\left|\Delta x_{(j)i}\right|\right)\leq Mml$

上式中 $l$ 为曲线 $L$ 的[[MK52][长度]]，故数列 $S_n$ 有界，根据[[~/文档/note/数学分析/Chap11Note.org][实数系基本定理-Bolzano-Weierstrass定理]]必有收敛子列

定义 $S_n$ 收敛子列 $S_{n_k}$ 且 $\lim_{k\to\infty}S_{n_k}=A$ 即 $\forall\epsilon>0,\exists K,\forall k>K\Rightarrow\left|\sum_{i=1}^n\vec{F}(\vec{x})\cdot\Delta\vec{x}_i-A\right|<\epsilon$

由于弧长 $\lambda=\Delta s=\frac{1}{n_k}$ 故亦有 $\forall\epsilon>0,\exists\delta''=\frac{1}{n_K},\forall \lambda<\delta\Rightarrow\left|\sum_{i=1}^n\vec{F}(\vec{x})\cdot\Delta\vec{x}_i-A\right|<\epsilon$

***** 利用连续性

由于连续，且 $L$ 为有界闭区间，故根据[[~/文档/note/数学分析/Chap11Note.org][连续函数性质-康托定理]]可得 $\vec{F}(\vec{x})$ 一致连续

即 $\forall\epsilon>0,\exists\delta'>0,\forall\left|\vec{x}'-\vec{x}''\right|<\Delta'\Rightarrow\left|\vec{F}(\vec{x}')-\vec{F}(\vec{x}'')\right|<\frac{\epsilon}{ml}$ 其中 $m$ 是函数 $\vec{F}$ 的维度

***** 证明结论

$\forall\epsilon>0$ 取 $\delta=\min(\delta',\delta'')$ 此时对应的[[MK53][特殊划分取点]]记作 $P^*,\vec{\xi}^*_i$ 则有和试 $\sum_{i=1}^{n^*}\vec{F}(\vec{\xi}^*_i)\cdot\Delta\vec{x}^*_i$

定义 $P'=P\cup P^*$ 为包含两组分点的分段，并有一组取点 $\vec{\xi}'_i$ 则有和式 $\sum_{i=1}^{n'}\vec{F}(\vec{\xi}’_i)\cdot\Delta\vec{x}'_i$

由于 $P'$ 包含 $P$ 的划分，故 $P$ 的分段可根据 $P'$ 继续划分

则定义 $P'$ 把 $P$ 的第 $i$ 段划分成 $n_i$ 段，且 $P$ 第 $i$ 段被 $P'$ 划分的第 $j$ 段 $P'$ 的取点为 $\vec{\xi}'_{ij}$ 两点的向量差为 $\Delta\vec{x}_{ij}$  

则根据[[MK54][乘法分配律]]，三角不等式以及前两步证明可得

\begin{aligned}
&\left|\sum_{i=1}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-\sum_{i=1}^{n'}\vec{F}(\vec{\xi}’_i)\cdot\Delta\vec{x}'_i\right|\\
=&\left|\sum_{i=1}^{n}\left\{\vec{F}(\vec{\xi}_i)\cdot\left(\sum_{j=1}^{n_i}\Delta\vec{x}_{ij}\right)\right\}-\sum_{i=1}^{n}\left\{\sum_{j=1}^{n_i}\vec{F}(\vec{\xi}'_{ij})\cdot\Delta\vec{x}_{ij}\right\}\right|\\
=&\left|\sum_{i=1}^{n}\left\{\sum_{j=1}^{n_i}\left(\vec{F}(\vec{\xi}_i)-\vec{F}(\vec{\xi}'_{ij})\right)\cdot\Delta\vec{x}_{ij}\right\}\right|\\
\leq&\sum_{i=1}^{n}\left\{\sum_{j=1}^{n_i}\left|\left(\vec{F}(\vec{\xi}_i)-\vec{F}(\vec{\xi}'_{ij})\right)\cdot\Delta\vec{x}_{ij}\right|\right\}\\
\leq&\sum_{i=1}^{n}\left\{\sum_{j=1}^{n_i}m\left|\vec{F}(\vec{\xi}_i)-\vec{F}(\vec{\xi}'_{ij})\right|\left|\Delta\vec{x}_{ij}\right|\right\}\\
<&\sum_{i=1}^{n}\left\{\sum_{j=1}^{n_i}m\frac{\epsilon}{ml}\left|\Delta\vec{x}_{ij}\right|\right\}\\
=&\frac{\epsilon}{l}\sum_{i=1}^{n}\left\{\sum_{j=1}^{n_i}\left|\Delta\vec{x}_{ij}\right|\right\}\\
\leq&\frac{\epsilon}{l}l=\epsilon
\end{aligned}

同理可得 $$\left|\sum_{i=1}^{n‘}\vec{F}(\vec{\xi}’_i)\cdot\Delta\vec{x}'_i-\sum_{i=1}^{n^*}\vec{F}(\vec{\xi}^*_i)\cdot\Delta\vec{x}^*_i\right|<\epsilon$$ 故有：

\begin{aligned}
&\left|\sum_{i=1}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-A\right|\\
=&\left|\sum_{i=1}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-\sum_{i=1}^{n'}\vec{F}(\vec{\xi}’_i)\cdot\Delta\vec{x}'_i+\sum_{i=1}^{n'}\vec{F}(\vec{\xi}’_i)\cdot\Delta\vec{x}'_i-\sum_{i=1}^{n^*}\vec{F}(\vec{\xi}^*_i)\cdot\Delta\vec{x}^*_i+\sum_{i=1}^{n^*}\vec{F}(\vec{\xi}^*_i)\cdot\Delta\vec{x}^*_i-A\right|\\
\leq&\left|\sum_{i=1}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-\sum_{i=1}^{n'}\vec{F}(\vec{\xi}’_i)\cdot\Delta\vec{x}'_i\right|+\left|\sum_{i=1}^{n'}\vec{F}(\vec{\xi}’_i)\cdot\Delta\vec{x}'_i-\sum_{i=1}^{n^*}\vec{F}(\vec{\xi}^*_i)\cdot\Delta\vec{x}^*_i\right|+\left|\sum_{i=1}^{n^*}\vec{F}(\vec{\xi}^*_i)\cdot\Delta\vec{x}^*_i-A\right|\\
<&\epsilon+\epsilon+\epsilon
\end{aligned}

故证毕

*** 方向性<<MK15>>

$$\int_L \vec{F}(\vec{x})\cdot d\vec{x}=-\int_{-L} \vec{F}(\vec{x})\cdot d\vec{x}$$

*** 线性<<MK19>>

若 $\int_L \vec{F}(\vec{x})\cdot d\vec{x},\int_L \vec{G}(\vec{x})\cdot d\vec{x}$ 收敛，则有 $$\int_L \left(A\vec{F}(\vec{x})+B\vec{F}(\vec{x})\right)\cdot d\vec{x}=A\int_L \vec{F}(\vec{x})\cdot d\vec{x}+B\int_L \vec{G}(\vec{x})\cdot d\vec{x}$$

**** 证明

根据定义 $$\lim_{\lambda\to0}\sum_{i=1}^n \vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i=\int_L\vec{F}(\vec{x})\cdot d\vec{x},\lim_{\lambda\to0}\sum_{i=1}^n \vec{G}(\vec{x}_i)\cdot\Delta \vec{x}_i=\int_L\vec{G}(\vec{x})\cdot d\vec{x}$$

同样根据定义 $$\lim_{\lambda\to0}\sum_{i=1}^n\left\{A\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i+B\vec{G}(\vec{x}_i)\cdot\Delta \vec{x}_i\right\}=A\int_L \vec{F}(\vec{x})\cdot d\vec{x}+B\int_L \vec{G}(\vec{x})\cdot d\vec{x}$$

由于极限存在，则根据极限四则运算:

$$\lim_{\lambda\to0}\sum_{i=1}^n\left\{A\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i+B\vec{G}(\vec{x}_i)\cdot\Delta \vec{x}_i\right\}=A\lim_{\lambda\to0}\sum_{i=1}^n\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i+B\lim_{\lambda\to0}\sum_{i=1}^n\vec{G}(\vec{x}_i)\cdot\Delta \vec{x}_i$$

由于上述表述对于任意划分取点均可证得，故有 $$\int_L \left(A\vec{F}(\vec{x})+B\vec{F}(\vec{x})\right)\cdot d\vec{x}=A\int_L \vec{F}(\vec{x})\cdot d\vec{x}+B\int_L \vec{G}(\vec{x})\cdot d\vec{x}$$

*** 区间可加<<MK9>>

若 $L$ 分为 $L_1,L_2$ 两段，则

（1） $\int_L \vec{F}(\vec{x})\cdot d\vec{x}$ 存在，则 $\int_{L_1} \vec{F}(\vec{x})\cdot d\vec{x},\int_{L_2} \vec{F}(\vec{x})\cdot d\vec{x}$ 也存在

（2） $\int_{L_1} \vec{F}(\vec{x})\cdot d\vec{x},\int_{L_2} \vec{F}(\vec{x})\cdot d\vec{x}$ 存在，则 $\int_L \vec{F}(\vec{x})\cdot d\vec{x}$ 也存在

且两种情况都有 $\int_L \vec{F}(\vec{x})\cdot d\vec{x}=\int_{L_1} \vec{F}(\vec{x})\cdot d\vec{x}+\int_{L_2} \vec{F}(\vec{x})\cdot d\vec{x}$

**** 证明

***** 证明（1）

****** 建立反证条件

根据[[MK22][定义]]可得 $\forall (P,\vec{\xi}_i)$ 均有 $\lim_{\lambda\to0}\sum_{i=1}^n \vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i=I$ 

则必有分点 $P^*=\{\vec{x}_1,...,\vec{x}_{n+1}\}$ 使得 $\vec{x}_z$ 恰好划分 $L_1,L_2$ ，

则有 $\lim_{\lambda\to0}\sum_{i=1}^n \vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i=\lim_{\lambda\to0}\left\{\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i\right\}=I$ 

假设 $\lim_{\lambda\to0}\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i$ 不收敛

则 $\exists\epsilon_1>0,\forall\delta>0,\exists\lambda_1<\delta$ 均存在特殊的取点划分 $\exists(P^1,\vec{\xi}^1_i)$ 对于任意实数 $\forall A\in\mathbb{R}$

均有 $\left|\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-A\right|>\epsilon_1$

****** 使用可积定义

根据极限定义引入另一个条件，当 $\forall\epsilon>0,\exists\delta,\forall\lambda<\delta$ 时

可推出对于任意划分取点均有 $\left|\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-I\right|<\epsilon$

此时取 $\epsilon=\frac{\epsilon_1}{2}$ 则有 $\left|\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-I\right|<\frac{\epsilon_1}{2}$

此时 $L_1$ 段采用特殊划分取点 $(P^1,\vec{\xi}^1_i)$ 则有 

\begin{aligned}
\because&\frac{\epsilon_1}{2}>\left|\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-I\right|\\
=&\left|\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-A+\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-(I-A)\right|\\
\geq&\left|\left|\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-A\right|-\left|\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-(I-A)\right|\right|\\
\therefore&-\frac{\epsilon_1}{2}<\left|\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-(I-A)\right|-\left|\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-A\right|<\frac{\epsilon_1}{2}\\
\because&\left|\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-A\right|>\epsilon_1\\
\therefore&\left|\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-(I-A)\right|>\frac{\epsilon_1}{2}
\end{aligned}

即 $L_2$ 上当分段 $\lambda<\delta$ 时，上述结果对于任意 $A$ 任意划分取点均成立

****** 构建特殊划分，推出矛盾

由于 $L$ [[MK52][可求长]]，则根据[[MK56][推论]]可得 $L_2$ 亦可求长

由于可积，故 $\vec{F}(\vec{x})$ 在 $\vec{x}\in L$ 上有界，定义 $\left|\vec{F}(\vec{x})\right|\leq M$ 

根据[[MK55][绝对值不等式]]得 $\left|\vec{F}(\vec{x})\cdot\Delta\vec{x}\right|\leq \left|\vec{F}(\vec{x})\right|\left|\Delta\vec{x}\right|\leq M\left|\Delta\vec{x}\right|$

则根据三角不等式 $\left|\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i\right|\leq\sum_{i=k}^{n}\left|\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i\right|\leq\sum_{i=k}^{n}\left|\vec{F}(\vec{\xi}_i)\right|\left|\Delta\vec{x}_i\right|<Ml_2$ 

其中 $l_2$ 为 $L_2$ 的长度。故 $\left|\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i\right|$ 有界

定义划分 $P^n=\{\vec{x}_k,...,\vec{x}_{n+1}\}$ 将 $L_2$ 按其长度 $n-k$ 等分，定义取点 $\vec{\xi}_{i}$ 为弧 $\vec{x}_{i}\vec{x}_{i+1}$ 的长度中点。

定义数列 $S_n=\sum_{i=k}^n\vec{F}(\vec{x})\cdot\Delta\vec{x}_i$ 由于有界，故根据[[~/文档/note/数学分析/Chap11Note.org][实数系基本定理-Bolzano-Weierstrass定理]]必有收敛子列

定义其收敛子列为 $S_{n_1},...,S_{n_u},...\a$ 其极限为 $B$ 则有 $\forall\epsilon>0,\exists U,\forall u>U\Rightarrow\left|\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-B\right|<\epsilon$

由于 $L_2$ 上当分段当 $\lambda<\delta$ 时，上述结果对于任意 $A$ 任意划分取点均成立 $\left|\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-(I-A)\right|>\frac{\epsilon_1}{2}$

显然上述特殊分点亦需满足，故矛盾。

最终推出 $L_1$ 的极限 $\lim_{\lambda\to0}\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i$ 必然对于任意划分取点均收敛

****** 证明结论

同理 $L_2$ 的极限 $\lim_{\lambda\to0}\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i$ 对于任意划分取点亦均收敛

当 $L_1$ 保持一种划分取点时极限不变，定义为 $C$ ，对于任意 $L_2$ 的划分取点均有 $C+\lim_{\lambda\to0}\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i=I$

故 $L_2$ 的任意划分取点均收敛于同一值 $I-C$ 同理 $L_1$ 的划分取点亦收敛与同一值

固有 $$\int_{L_1} \vec{F}(\vec{x})\cdot d\vec{x},\int_{L_2} \vec{F}(\vec{x})\cdot d\vec{x}$$ 均存在，且有

\begin{aligned}
&\int_L\vec{F}(\vec{x})\cdot d\vec{x}\\
=&\lim_{\lambda\to0}\sum_{i=1}^n \vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\\
=&\lim_{\lambda\to0}\left\{\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i\right\}\\
=&\lim_{\lambda\to0}\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\lim_{\lambda\to0}\sum_{i=k}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i\\
=&\int_{L_1}\vec{F}(\vec{x})\cdot d\vec{x}+\int_{L_2}\vec{F}(\vec{x})\cdot d\vec{x}\\
=&I
\end{aligned}

***** 证明（2）

根据[[MK22][定义]]可得对于 $L_1$ 有 $\forall (P,\vec{\xi}_i)\Rightarrow\lim_{\lambda\to0}\sum_{i=1}^{n_1} \vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i=I_1$ 

同理对于 $L_2$ 有 $\forall (P,\vec{\xi}_i)\Rightarrow\lim_{\lambda\to0}\sum_{i=1}^{n_2} \vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i=I_1$ 即

$\forall\epsilon>0,\exists\delta_1,\forall\lambda<\delta_1\rightarrow\left|\sum_{i=1}^{n_1} \vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i-I_1\right|<\epsilon$

$\forall\epsilon>0,\exists\delta_2,\forall\lambda<\delta_1\rightarrow\left|\sum_{i=1}^{n_2} \vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i-I_2\right|<\epsilon$ 

同样根据定义可得 $\vec{F}(\vec{x})$ 在 $L_1,L_2$ 上可积，故必有界，定义 *模* 的最大值 $\left|\vec{F}(\vec{x})\right|\leq M,\vec{x}\in L_1\cup L_2$

又定义 $\vec{F}(\vec{x})=\left(f_1(\vec{x}),...,f_m(\vec{x})\right)^T$

则对于任意划分 $P$ 假设 $L_1,L_2$ 分界点 $\vec{x}_s$ 落在 $\vec{x}_k,\vec{x}_{k+1}$ 之间，则 $\forall\epsilon$ 取 $\delta=\min\left(\delta_1,\delta_2,\frac{\epsilon}{mM}\right)$ 

任取两点 $\vec{\xi}_a\in \vec{x}_k\vec{x}_s,\vec{\xi}_b\in \vec{x}_k\vec{x}_s$ 且定义 $\Delta\vec{x}_a=\vec{x}_s-\vec{x}_k,\Delta\vec{x}_b=\vec{x}_{k+1}-\vec{x}_s$ 则有：

\begin{aligned}
&\left|\sum_{i=1}^n\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-I_1-I_2\right|\\
=&\left|\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\sum_{i=k+1}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-I_1-I_2+\vec{F}(\vec{\xi}_k)\cdot\Delta\vec{x}_k\right|\\
=&\left|\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\vec{F}(\vec{\xi}_a)\cdot\Delta\vec{x}_a-I_1+\sum_{i=k+1}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\vec{F}(\vec{\xi}_b)\cdot\Delta\vec{x}_b-I_2+\vec{F}(\vec{\xi}_k)\cdot\Delta\vec{x}_k-\vec{F}(\vec{\xi}_a)\cdot\Delta\vec{x}_a-\vec{F}(\vec{\xi}_b)\cdot\Delta\vec{x}_b\right|\\
\leq&\left|\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\vec{F}(\vec{\xi}_a)\cdot\Delta\vec{x}_a-I_1\right|+\left|\sum_{i=k+1}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\vec{F}(\vec{\xi}_b)\cdot\Delta\vec{x}_b-I_2\right|+\left|\vec{F}(\vec{\xi}_k)\cdot\Delta\vec{x}_k\right|+\left|\vec{F}(\vec{\xi}_a)\cdot\Delta\vec{x}_a\right|+\left|\vec{F}(\vec{\xi}_b)\cdot\Delta\vec{x}_b\right|\\
\end{aligned}

由于 $\left|\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\vec{F}(\vec{\xi}_a)\cdot\Delta\vec{x}_a-I_1\right|$ 构成 $L_1$ 内 $\lambda<\delta_1$ 的划分取点

固有 $\left|\sum_{i=1}^{k-1}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\vec{F}(\vec{\xi}_a)\cdot\Delta\vec{x}_a-I_1\right|<\epsilon$ 同理可得 $\left|\sum_{i=k+1}^{n}\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i+\vec{F}(\vec{\xi}_b)\cdot\Delta\vec{x}_b-I_2\right|<\epsilon$

又对于 $\left|\vec{F}(\vec{\xi}_b)\cdot\Delta\vec{x}_b\right|=\left|\sum_{j=1}^mf_j(\vec{\xi}_b)\Delta x_{(j)b}\right|\leq\sum_{j=1}^m\left|f_j(\vec{\xi}_b)\right|\left|\Delta x_{(j)b}\right|$

由于 $\left|f_j(\vec{\xi}_b)\right|$ 必定小于模的最大值（斜边最长）故有 $\left|f_j(\vec{\xi}_b)\right|\leq M$ 同理 $\left|\Delta x_{(j)i}\right|<\frac{\epsilon}{mM}$

固有 $\left|\vec{F}(\vec{\xi}_b)\cdot\Delta\vec{x}_b\right|<\sum_{j=1}^m\frac{\epsilon}{mM}M=\epsilon$ 同理可证 $\left|\vec{F}(\vec{\xi}_k)\cdot\Delta\vec{x}_k\right|+\left|\vec{F}(\vec{\xi}_a)\cdot\Delta\vec{x}_a\right|+\left|\vec{F}(\vec{\xi}_b)\cdot\Delta\vec{x}_b\right|<3\epsilon$

综上所述，对于任意划分取点均成立 $$\forall\epsilon,\exists\delta,\forall\lambda<\delta\Rightarrow\left|\sum_{i=1}^n\vec{F}(\vec{\xi}_i)\cdot\Delta\vec{x}_i-I_1-I_2\right|<5\epsilon$$ 

故积分存在且有 $\int_L \vec{F}(\vec{x})\cdot d\vec{x}=\int_{L_1} \vec{F}(\vec{x})\cdot d\vec{x}+\int_{L_2} \vec{F}(\vec{x})\cdot d\vec{x}$

** <<MK12>>计算

若曲线 $L$ 有参数表示 $\vec{x}(t)=\begin{cases}x_1(t)\\x_2(t)\\...\\x_n(t)\end{cases},t:a\to b$ 满足：

（1） 分量函数一阶导数连续（光滑）

（2） 分量函数的一阶导数在 $t:a\to b$ 的任意点上不全为零

（3） 参数方程一一对应

若存在向量值函数 $\vec{F}(\vec{x})=\begin{cases}f_1(\vec{x})\\f_2(\vec{x})\\...\\f_n(\vec{x})\end{cases}$ 在 $\vec{x}\in L$ 上连续且不为无限维

则 $\int_L \vec{F}(\vec{x})\cdot d\vec{x}=\int_a^b\left\{\sum_{i=1}^n f_i(\vec{x}(t))x_i'(t)\right\}dt$ 或微分形式 $\int_L \vec{F}(\vec{x})\cdot d\vec{x}=\int_a^b \vec{F}(\vec{x}(t))\cdot \frac{d\vec{x}(t)}{dt}dt$ 

*** 证明

**** 高维曲线切线方向<<MK46>>

已知点 $\vec{x}(t_0)$ 与 $\vec{x}(t)$ 为曲线上的两点， $\vec{y}=(y_1,y_2,...,y_n)$ 为过两点的割线上的点

由于是直线，故满足 $\frac{y_i-x_i(t_0)}{x_i(t)-x_i(t_0)}=\frac{y_j-x_j(t_0)}{x_j(t)-x_j(t_0)}\ \ i,j=1,2,...,n$ 

同乘 $t-t_0$ 得 $\frac{y_i-x_i(t_0)}{\frac{x_i(t)-x_i(t_0)}{t-t_0}}=\frac{y_j-x_j(t_0)}{\frac{x_j(t)-x_j(t_0)}{t-t_0}}\ \ i,j=1,2,...,n$ 

当 $t\to t_0$ 时，割线变切线，故等式调整为 $\frac{y_i-x_i(t_0)}{x_i'(t_0)}=\frac{y_j-x_j(t_0)}{x_j'(t_0)}\ \ i,j=1,2,...,n$ 

若 $x'_{i_1}(t_0)=0,x'_{i_2}(t_0)=0,...,x'_{i_k}(t_0)=0$ 则 $\vec{y}$ 满足条件 $\begin{cases}y_i-x_i(t_0)=0&i=i_1,i_2,...,i_k\\\frac{y_i-x_i(t_0)}{x_i'(t_0)}=\frac{y_j-x_j(t_0)}{x_j'(t_0)}&i,j\ne i_1,i_2,...,i_k\end{cases}$

故 $\vec{x}'(t_0)=(x_1'(t_0),x_2'(t_0),...,x_n'(t_0))$ 为切线方向

**** 证明等价式<<MK25>>

下面证明在已给出条件下，无论划分取点，均有 $\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i=\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)$

其中 $\tau(\vec{x})=(\cos(\alpha_1(\vec{x})),\cos(\alpha_2(\vec{x})),...,\cos(\alpha_k(\vec{x})))$ 并定义 $\cos(\alpha_k(\vec{x}))=\lim_{s\to0}\frac{x'_k-x_k}{s}$ 

其中 $s$ 为 $\vec{x}\vec{x}'$ 的弧长 $x_k,x'_k$ 分别为点 $\vec{x},\vec{x}'$ 在第 $k$ 轴上的分量

***** 证明弦长形式<<MK51>>

构建和式，根据三角不等式

\begin{aligned}
&\left|\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta l_i\right|\\
=&\left|\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)(\Delta s_i-\Delta l_i)\right|\\
\leq&\sum_{i=1}^m \left|\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right||\Delta s_i-\Delta l_i|
\end{aligned}

由于 $\vec{F}(\vec{x})$ 连续，且由于曲线光滑，故 $\tau(\vec{x})$ 也连续，故 $\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)$ 在有界闭区间 $L$ 上连续

由于 $L$ 是有界闭集，故根据[[~/文档/note/数学分析/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-Heine-Borel定理]]得 $L$ 是紧集

再根据[[~/文档/note/数学分析/Chap11Note.org][连续函数性质-有界性定理]]得 $\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)$ 在 $L$ 上有界，定义 $\max\left|\vec{F}(\vec{x})\cdot\tau(\vec{x})\right|=M$

故有

\begin{aligned}
&\left|\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta l_i\right|\\
\leq&\sum_{i=1}^m \left|\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right||\Delta s_i-\Delta l_i|\\
\leq&\sum_{i=1}^m M(\Delta s_i-\Delta l_i)\\
=&M\sum_{i=1}^m (\Delta s_i-\Delta l_i)
\end{aligned}

根据光滑线段弧长定义有对于任意划分 $\lim_{\lambda\to0}\Delta l_i=S$ 其中 $S$ 为线段 $L$ 的弧长 $\Delta l_i$ 为相邻两个分点间的弦长 $\lambda=\max(\Delta l_i)$

故有 $\forall\frac{\epsilon}{M}>0,\exists\delta,\forall\lambda<\delta'\Rightarrow \left|\sum_{i=1}^m\Delta l_i-S\right|<\epsilon$ 即 $\left|\sum_{i=1}^m\left(\Delta l_i-\Delta s_i\right)\right|<\frac{\epsilon}{M}$ 其中 $\Delta s_i$ 为第 $i$ 分段的弧长

由于弧长必大于弦长，故有 $\sum_{i-1}^m\left(\Delta s_i-\Delta l_i\right)<\frac{\epsilon}{M}$ 

综上所述，有 $\forall\epsilon>0,\exists\delta,\forall\lambda<\delta\Rightarrow\forall\lambda<\delta$ 均有：

\begin{aligned}
&\left|\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta l_i\right|\\
\leq&\sum_{i=1}^m \left|\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right||\Delta s_i-\Delta l_i|\\
\leq&\sum_{i=1}^m M(\Delta s_i-\Delta l_i)\\
=&M\sum_{i=1}^m (\Delta s_i-\Delta l_i)\\
<&M\frac{\epsilon}{M}\\
=&\epsilon
\end{aligned}

故有 $\lim_{\lambda\to0}\sum_{i=1}^n \left(\vec{F}(\vec{x}_i)\cdot\tau\right)\Delta s_i=\lim_{\lambda\to0}\sum_{i=1}^n \left(\vec{F}(\vec{x}_i)\cdot\tau\right)\Delta l_i$

***** 证明余弦形式

****** 前提引理

根据[[MK47][之前证明]]有 $\cos(\alpha_u(t))=\pm\frac{x_i'(t)}{\sqrt{\sum_{j=1}^n x_u'(t)^2}}$

由于[[MK48][光滑]]，故一阶导数连续，故对于任意 $\{t',t''\}\subset[a,b]$ 其参数函数 $x_k(t)$ 必定在开区间可导，闭区间连续。

假设 $t''>t'$ ，根据[[~/文档/note/大学物理/Note/DiffEq.org][导数基本知识-拉格朗日中值定理]]可得

存在 $\xi\in[t',t'']$ 使得 $x'_k(\xi)=\frac{x_k(t'')-x_k(t')}{t''-t'}$ 且 $x'_k(\xi)(t''-t')=x'_k(t'')-x'_k(t')$

同理由于光滑，故其一阶导数连续，又根据：

（1） [[~/文档/note/数学分析/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-Heine-Borel定理]]

（2） [[~/文档/note/数学分析/Chap11Note.org][连续函数性质-康托定理]]

可得 $x'_k(t)$ 在闭区间 $[a,b]$ 上一致连续，故有 $\forall\epsilon>0,\exists\delta',\forall|t''-t'|<\delta\Rightarrow|x'_k(t'')-x'_k(t')|<\epsilon$

又由于当 $[t',t'']$ 确定时存在 $\xi\in[t',t'']$ 满足之前结论

故有 $\big|x'_k(t)-x'_k(\xi)\big|<\epsilon\Rightarrow\left|x'_k(t)-\frac{x_k(t'')-x_k(t')}{t''-t'}\right|\right|<\epsilon$

又由于当 $|t''-t'|<1$ 时亦有 

\begin{aligned}
&|x'_k(t)(t''-t')-(x'_k(t'')-x'_k(t'))|\\
=&|x'_k(t)(t''-t')-x'_k(\xi)(t''-t')|\\
=&|(x'_k(t)-x'_k(\xi))||t''-t'|\\
<&\epsilon|t''-t'|\\
<&\epsilon
\end{aligned}

其中 $t\in[t',t'']$

故有结论 $\forall\epsilon>0,\exists\delta=\min(\delta',1),\forall|t''-t'|<\delta\land\{t'',t'\}\subset[a,b]$ 有结论：

（1） $\left|x'_k(\xi)-\frac{x_k(t'')-x_k(t')}{t''-t'}\right|<\epsilon$

（2） $|x'_k(t)(t''-t')-(x'_k(t'')-x'_k(t'))|<\epsilon$

其中 $\forall t\in[t',t'']$ 均成立

****** 拓展引理

由于光滑曲线，即参数函数连续，其一阶导数也连续，故根据：

（1） [[~/文档/note/数学分析/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-Heine-Borel定理]]

（2） [[~/文档/note/数学分析/Chap11Note.org][连续函数性质-有界性定理]]

故在 $\{t,t'\}\subset[a,b]$ 上 $x'_k(t),\frac{x_k(t')-x_k(t)}{t'-t'}$ 均有界，即存在 $M_1\geq|x'_k(\xi)|,M_2\geq\left|\frac{x_k(t'')-x_k(t')}{t''-t'}\right|$ 对于任意 $\{t,t'\}\subset[a,b]$ 

取 $M=\max(M_1,M_2)$ 由于函数 $f(x)=x^2$ 连续，故根据[[~/文档/note/数学分析/Chap11Note.org][连续函数性质-康托定理]] $f(x)$ 在闭区间 $[-M,M]$ 上一致连续

故在 $[-M,M]$ 上 $\forall\epsilon>0,\exists\delta',\forall|x''-x'|<\delta\Rightarrow |f(x'')-f(x')|<\epsilon$

又根据上一步引理 $\forall\delta'>0,\exists\delta,\forall|t''-t'|<\delta\land\{t'',t'\}\subset[a,b]\rightarrow\left|x'_k(t)-\frac{x_k(t'')-x_k(t')}{t''-t'}\right|<\epsilon$ 对于任意 $t\in[t',t'']$ 

综上所述 $\forall\epsilon>0,\exists\delta_k,\forall|t''-t'|<\delta\Rightarrow\left|\left(x'_k(t)\right)^2-\left(\frac{x_k(t'')-x_k(t')}{t''-t'}\right)^2\right|<\epsilon$ 对于任意 $t\in[t',t'']$ 

同理可证 $\forall\epsilon>0,\exists\delta=\min(\delta_k),\forall|t''-t'|<\delta\Rightarrow\left|\sum_{j=1}^n\left(x'_j(t)\right)^2-\sum_{j=1}^n\left(\frac{x_j(t'')-x_j(t')}{t''-t'}\right)^2\right|<n\epsilon$ 对于任意 $t\in[t',t'']$ 

由于 $n$ 是维度，确定且不为无限维。

同理可证 $$\forall\epsilon>0,\exists\delta,\forall|t''-t'|<\delta\Rightarrow\left|\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}-\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}\right|<\epsilon$$ 对于任意 $t\in[t',t'']$ 

由于分量函数导数在任意点上均不全为零，故有 $\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}>0$ 且由于导数连续，故 $\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}>0$ 连续

由于 $a\to b$ 有界闭集，故根据[[~/文档/note/数学分析/Chap11Note.org][连续函数性质-有界性定理]] $\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}$ 在 $t\in a\to b$ 上必有下界，定义为 $\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}>m$

则 $$\forall\epsilon>0,\exists\delta,\forall|t''-t'|<\delta\Rightarrow\left|\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}-\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}\right|<m\epsilon$$ 转化

\begin{aligned}
\because&\left|\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}-\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}\right|<m\epsilon\\
\therefore&\left|\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}-\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}\right|<m\epsilon\\
\therefore&\left|\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-1\right|<\frac{m\epsilon}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}\\
\because &m<\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}\rightarrow \frac{m}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}<1\\
\therefore&\left|\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-1\right|<\frac{m\epsilon}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}<\epsilon\\
\end{aligned} 

****** 综合引理<<MK49>>

综上所述，归结为两条引理：

（1） $\forall\epsilon>0,\exists\delta,\forall|t''-t'|<\delta\Rightarrow\left|x'_k(t)-\frac{x_k(t'')-x_k(t')}{t''-t'}\right|<\epsilon$ 对于任意 $t\in[t',t'']$，对于任意 $k\in\mathbb{N}\land1\leq k\leq n$

（2） $\forall\epsilon>0,\exists\delta,\forall|t''-t'|<\delta\Rightarrow\left|\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-1\right|<\epsilon$ 对于任意 $t\in[t',t'']$

****** 合并引理<<MK50>>

化简下式：

\begin{aligned}
&\left|x'_k(t)\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-\frac{x_k(t'')-x_k(t')}{t''-t'}\right|\\
=&\left|x'_k(t)\left(\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-1+1\right)-\frac{x_k(t'')-x_k(t')}{t''-t'}\right|\\
=&\left|x'_k(t)\left(\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-1\right)+x'_k(t)-\frac{x_k(t'')-x_k(t')}{t''-t'}\right|\\
\leq&\left|x'_k(t)\left(\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-1\right)\right|+\left|x'_k(t)-\frac{x_k(t'')-x_k(t')}{t''-t'}\right|\\
=&|x'_k(t)|\left|\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-1\right|+\left|x'_k(t)-\frac{x_k(t'')-x_k(t')}{t''-t'}\right|
\end{aligned}

由于导函数连续，且区域有界闭区间，故根据[[~/文档/note/数学分析/Chap11Note.org][连续函数性质-有界性定理]]可得 $|x'_k(t)|$ 在 $t\in a\to b$ 上必有界

定义 $|x'_k(t)|<M_k$ 对于任意 $t\in a\to b$ 进一步定义 $M=\max(M_k)$

根据[[MK49][综合引理]]中（2）可得 $\forall\epsilon>0,\exists\delta',\forall|t''-t'|<\delta'\Rightarrow\left|\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-1\right|<\frac{\epsilon}{M}$

则有 $|x'_k(t)|\left|\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-1\right|<M\left|\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-1\right|<M\frac{\epsilon}{M}=\epsilon$ 

又根据[[MK49][综合引理]]中（1）可得 $\forall\epsilon>0,\exists\delta'',\forall|t''-t'|<\delta'\Rightarrow\left|x'_k(t)-\frac{x_k(t'')-x_k(t')}{t''-t'}\right|<\epsilon$

故有 $\forall\epsilon>0,\exists\delta=\min(\delta'',\delta'),\forall|t''-t'|<\delta$ 有

\begin{aligned}
&\left|x'_k(t)\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-\frac{x_k(t'')-x_k(t')}{t''-t'}\right|\\
\leq&|x'_k(t)|\left|\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-1\right|+\left|x'_k(t)-\frac{x_k(t'')-x_k(t')}{t''-t'}\right|\\
<&\epsilon+\epsilon=2\epsilon
\end{aligned}

****** 整理余弦等式

定义划分 $P$ 将曲线分为 $l_1,l_2,...,l_m$ 分点为 $P_1,P_2,...,P_{m+1}$ 且 $\vec{x}_i$ 为曲线 $l_i$ 上的任意一点， $\Delta l_i$ 为 $P_i,P_{i+1}$ 之间正方向的弦长

由于 $\cos(\alpha_u(t))=\pm\frac{x_i'(t)}{\sqrt{\sum_{j=1}^n x_u'(t)^2}}$ 且正方向亦有 $\Delta l_i$ 故两者相乘，正负号抵消。

由于一一对应，故必有 $T_i$ 与分点 $P_i$ 对应， $t_i$ 与 $\vec{x}_i$ 对应，构造等式：

\begin{aligned}
&\left|\sum_{i=1}^m \left(\vec{F}(\vec{x}(t_i))\cdot\tau(\vec{x}(t_i))\right)\Delta l_i-\sum_{i=1}^m \left(\vec{F}(\vec{x}(t_i))\cdot\left(\vec{x}(T_{i+1})-\vec{x}(T_{i+1})\right)\right)\right|\\
=&\left|\sum_{i=1}^m \left(\vec{F}(\vec{x}(t_i))\cdot\tau(\vec{x}(t_i))\Delta l_i-\vec{F}(\vec{x}(t_i))\cdot\left(\vec{x}(T_{i+1})-\vec{x}(T_{i+1})\right)\right)\right|\\
=&\left|\sum_{i=1}^m \left(\sum_{j=1}^nf_j(\vec{x}(t_i))\cos(\alpha_j(\vec{x}(t_i)))\Delta l_i-\sum_{j=1}^nf_j(\vec{x}(t_i))\left(x_j(T_{i+1})-x_j(T_{i+1})\right)\right)\right|\\
=&\left|\sum_{i=1}^m \left(\sum_{j=1}^n\left(f_j(\vec{x}(t_i))\left(\cos(\alpha_j(\vec{x}(t_i)))\Delta l_i-\left(x_j(T_{i+1})-x_j(T_{i+1})\right)\right)\right)\right)\right|\\
=&\left|\sum_{i=1}^m \left(\sum_{j=1}^n\left(f_j(\vec{x}(t_i))\left(\frac{x_j'(t_i)}{\sqrt{\sum_{u=1}^n x_u'(t_i)^2}}\sqrt{\sum_{j=1}^n\left(x_j(T_{i+1})-x_j(T_i)\right)^2}-\left(x_j(T_{i+1})-x_j(T_{i+1})\right)\right)\right)\right)\right|\\
=&\left|\sum_{i=1}^m \left(\sum_{j=1}^n\left(f_j(\vec{x}(t_i))\left(x_j'(t_i)(T_{i+1}-T_i)\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(T_{i+1})-x_j(T_i)\right)^2}}{T_{i+1}-T_i}}{\sqrt{\sum_{u=1}^n x_u'(t_i)^2}}-\left(x_j(T_{i+1})-x_j(T_{i+1})\right)\right)\right)\right)\right|\\
=&\left|\sum_{i=1}^m \left((T_{i+1}-T_i)\sum_{j=1}^n\left(f_j(\vec{x}(t_i))\left(x_j'(t_i)\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(T_{i+1})-x_j(T_i)\right)^2}}{T_{i+1}-T_i}}{\sqrt{\sum_{u=1}^n x_u'(t_i)^2}}-\frac{x_j(T_{i+1})-x_j(T_{i+1})}{T_{i+1}-T_i}\right)\right)\right)\right|\\
\leq&\sum_{i=1}^m \left(|T_{i+1}-T_i|\sum_{j=1}^n\left(|f_j(\vec{x}(t_i))|\left|x_j'(t_i)\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(T_{i+1})-x_j(T_i)\right)^2}}{T_{i+1}-T_i}}{\sqrt{\sum_{u=1}^n x_u'(t_i)^2}}-\frac{x_j(T_{i+1})-x_j(T_{i+1})}{T_{i+1}-T_i}\right|\right)\right)
\end{aligned}

由于光滑且 $L$ 有界，故 $f_j(\vec{x}(t))$ 必有上界，定义为 $M_j$ 定义 $M=\max(M_j)$ 故有

\begin{aligned}
&\left|\sum_{i=1}^m \left(\vec{F}(\vec{x}(t_i))\cdot\tau(\vec{x}(t_i))\right)\Delta l_i-\sum_{i=1}^m \left(\vec{F}(\vec{x}(t_i))\cdot\left(\vec{x}(T_{i+1})-\vec{x}(T_{i+1})\right)\right)\right|\\
\leq&\sum_{i=1}^m \left(|T_{i+1}-T_i|\sum_{j=1}^n\left(|f_j(\vec{x}(t_i))|\left|x_j'(t_i)\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(T_{i+1})-x_j(T_i)\right)^2}}{T_{i+1}-T_i}}{\sqrt{\sum_{u=1}^n x_u'(t_i)^2}}-\frac{x_j(T_{i+1})-x_j(T_{i+1})}{T_{i+1}-T_i}\right|\right)\right)\\
\leq&\sum_{i=1}^m \left(|T_{i+1}-T_i|\sum_{j=1}^n\left(M\left|x_j'(t_i)\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(T_{i+1})-x_j(T_i)\right)^2}}{T_{i+1}-T_i}}{\sqrt{\sum_{u=1}^n x_u'(t_i)^2}}-\frac{x_j(T_{i+1})-x_j(T_{i+1})}{T_{i+1}-T_i}\right|\right)\right)\\
=&M\sum_{i=1}^m \left(|T_{i+1}-T_i|\sum_{j=1}^n\left(\left|x_j'(t_i)\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(T_{i+1})-x_j(T_i)\right)^2}}{T_{i+1}-T_i}}{\sqrt{\sum_{u=1}^n x_u'(t_i)^2}}-\frac{x_j(T_{i+1})-x_j(T_{i+1})}{T_{i+1}-T_i}\right|\right)\right)\\
\end{aligned}

****** 证明结论

定义 $\lambda=\max(\Delta s_i)$ 其中 $\Delta s_i$ 为分点 $P_i,P_{i+1}$ 间的弧长。由于曲线光滑，故当 $\lambda\to 0$ 时有 $\max(|T_{i+1}-T_i|)\to0$

由于一一对应，且 $t$ 方向为 $a\to b$ 故必有 $\sum_{i=1}^m|T_{i+1}-T_i|=|b-a|$

据[[MK50][合并引理]]可得 $\forall\epsilon>0,\exists\delta,\forall\lambda<\delta\Rightarrow\left|x'_k(t)\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(t'')-x_j(t')\right)^2}}{t''-t'}}{\sqrt{\sum_{j=1}^n\left(x'_j(t)\right)^2}}-\frac{x_k(t'')-x_k(t')}{t''-t'}\right|<\frac{\epsilon}{nM|b-a|}$ 则有 

\begin{aligned}
&\left|\sum_{i=1}^m \left(\vec{F}(\vec{x}(t_i))\cdot\tau(\vec{x}(t_i))\right)\Delta l_i-\sum_{i=1}^m \left(\vec{F}(\vec{x}(t_i))\cdot\left(\vec{x}(T_{i+1})-\vec{x}(T_{i+1})\right)\right)\right|\\
\leq&M\sum_{i=1}^m \left(|T_{i+1}-T_i|\sum_{j=1}^n\left(\left|x_j'(t_i)\frac{\frac{\sqrt{\sum_{j=1}^n\left(x_j(T_{i+1})-x_j(T_i)\right)^2}}{T_{i+1}-T_i}}{\sqrt{\sum_{u=1}^n x_u'(t_i)^2}}-\frac{x_j(T_{i+1})-x_j(T_{i+1})}{T_{i+1}-T_i}\right|\right)\right)\\
<&M\sum_{i=1}^m \left(|T_{i+1}-T_i|\sum_{j=1}^n\frac{\epsilon}{nM|b-a|}\right)\\
=&M\sum_{i=1}^m \left(|T_{i+1}-T_i|\frac{\epsilon}{M|b-a|}\right)\\
=&M\frac{\epsilon}{M|b-a|}\sum_{i=1}^m|T_{i+1}-T_i|\\
=&\frac{\epsilon}{|b-a|}|b-a|\\
=&\epsilon
\end{aligned}

故有 $$\lim_{\lambda\to0}\left(\sum_{i=1}^m \left(\vec{F}(\vec{x}(t_i))\cdot\tau(\vec{x}(t_i))\right)\Delta l_i-\sum_{i=1}^m \left(\vec{F}(\vec{x}(t_i))\cdot\left(\vec{x}(T_{i+1})-\vec{x}(T_{i+1})\right)\right)\right)=0$$

根据极限四则运算 $$\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}(t_i))\cdot\tau(\vec{x}(t_i))\right)\Delta l_i=\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}(t_i))\cdot\left(\vec{x}(T_{i+1})-\vec{x}(T_{i+1})\right)\right)$$

去掉 $t$ 的参数代换得 $$\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta l_i=\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}(t_i))\cdot\Delta \vec{x}_i\right)\right)$$

***** 写出微分形式

根据之前推导：

\begin{aligned}
&\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i\\
=&\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta l_i\\
=&\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)\\
\end{aligned}

**** 计算

***** 准备工作<<MK47>>

由于分量一阶导数不全为零，故角度 $\cos(\alpha_i(t))=\frac{x_i'(t)}{\sqrt{\sum_{j=1}^n x_j'(t)^2}}$ 

根据定义 $\sum_{j=1}^n x_j'(t)\ne0$ 故 $\sqrt{\sum_{j=1}^n x_j'(t)^2}>0$ ，由于 $x'_i(t)$ 连续，故 $\cos(\alpha_i(t))$ 连续，故 $\phi(t)=\vec{F}(\vec{x}(t))\cdot\tau(\vec{x}(t))=\sum_{i=1}^n f_i(\vec{x}(t))\cos(\alpha_i(t))$ 连续

又由于 $t\in[a,b]$ 根据[[~/文档/note/数学分析/Chap7Note.org][函数一致连续-康托定理]] $\phi(t)$ 一致连续

即 $\forall\epsilon>0,\exists\delta,\forall|t'-t|<\delta,t',t\in[a,b]\Rightarrow\left|\phi(t')-\phi(t)\right|<\frac{\epsilon}{S}$ 其中 $S$ 为曲线长度

定义划分 $P$ 将曲线分为 $l_1,l_2,...,l_m$ 分点为 $P_1,P_2,...,P_m$ ，由于一一对应故对于任意分点 $P_i$ 必有 $r_i$ 与之对应

定义 $\Delta s_i$ 为分点 $P_{i-1},P_i$ 间的曲线长度， $\vec{x}_i$ 为曲线 $l_i$ 上的任意一点，由于一一对应故对于任意取值 $\vec{x}_i$ 必有 $t_i$ 与之对应

***** 证明定积分与黎曼和极限相等

根据定义写出第二类曲线积分黎曼和 $\sum_{i=1}^n \phi(t_i)\Delta s_i$ 根据[[MK2][多元曲线长度]]有

\begin{aligned}
&\left|\sum_{i=1}^m \phi(t_i)\Delta s_i-\int_a^b \phi(t)\sqrt{\sum_{j=1}^n x_j'(t)^2}dt\right|\\
=&\left|\sum_{i=1}^m \phi(t_i)\int_{r_{i-1}}^{r_i}\sqrt{\sum_{j=1}^n x_j'(t)^2}dt-\sum_{i=1}^m\int_{r_{i-1}}^{r_i} \phi(t)\sqrt{\sum_{j=1}^n x_j'(t)^2}dt\right|\\
=&\left|\sum_{i=1}^m \int_{r_{i-1}}^{r_i}\left\{\left(\phi(t_i)-\phi(t)\right)\sqrt{\sum_{j=1}^n x_j'(t)^2}\right\}dt\right|\\
\leq&\sum_{i=1}^m \left|\int_{r_{i-1}}^{r_i}\left\{\left(\phi(t_i)-\phi(t)\right)\sqrt{\sum_{j=1}^n x_j'(t)^2}\right\}dt\right|\\
\end{aligned}

由于 $\left(\phi(t_i)-\phi(t)\right)\sqrt{\sum_{j=1}^n x_j'(t)^2}$ 连续，根据[[~/文档/note/数学分析/Chap7Note.org][定积分可积定理-定积分可积充要条件2-推论1]]定积分 $\int_{r_{i-1}}^{r_i}\left\{\left(\phi(t_i)-\phi(t)\right)\sqrt{\sum_{j=1}^n x_j'(t)^2}\right\}dt$ 可积

又根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-绝对可积]] $\int_{r_{i-1}}^{r_i}\left|\left(\phi(t_i)-\phi(t)\right)\sqrt{\sum_{j=1}^n x_j'(t)^2}\right|dt=\int_{r_{i-1}}^{r_i}\left\{\left|\phi(t_i)-\phi(t)\right|\sqrt{\sum_{j=1}^n x_j'(t)^2}\right\}dt$ 也可积，故

\begin{aligned}
&\left|\sum_{i=1}^m \phi(t_i)\Delta s_i-\int_a^b \phi(t)\sqrt{\sum_{j=1}^n x_j'(t)^2}dt\right|\\
\leq&\sum_{i=1}^m \left|\int_{r_{i-1}}^{r_i}\left\{\left(\phi(t_i)-\phi(t)\right)\sqrt{\sum_{j=1}^n x_j'(t)^2}\right\}dt\right|\\
\leq&\sum_{i=1}^m \int_{r_{i-1}}^{r_i}\left\{\left|\phi(t_i)-\phi(t)\right|\sqrt{\sum_{j=1}^n x_j'(t)^2}\right\}dt\\
\end{aligned}

又根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-保序]]及[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-线性]]及[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-区间可加]]

\begin{aligned}
&\left|\sum_{i=1}^m \phi(t_i)\Delta s_i-\int_a^b \phi(t)\sqrt{\sum_{j=1}^n x_j'(t)^2}dt\right|\\
\leq&\sum_{i=1}^m \int_{r_{i-1}}^{r_i}\left\{\left|\phi(t_i)-\phi(t)\right|\sqrt{\sum_{j=1}^n x_j'(t)^2}\right\}dt\\
\leq&\sum_{i=1}^m \int_{r_{i-1}}^{r_i}\left\{\frac{\epsilon}{S}\sqrt{\sum_{j=1}^n x_j'(t)^2}\right\}dt\\
=&\frac{\epsilon}{S}\sum_{i=1}^m\int_{r_{i-1}}^{r_i}\sqrt{\sum_{j=1}^n x_j'(t)^2}dt\\
=&\frac{\epsilon}{S}\int_a^b\sqrt{\sum_{j=1}^n x_j'(t)^2}dt\\
=&\frac{\epsilon}{S}S\\
=&\epsilon
\end{aligned}

***** 证明结论

综上所述 $\forall\epsilon>0,\exists\delta,\forall\lambda<\delta,\forall(P,t_i)\Rightarrow\left|\sum_{i=1}^n \phi(t_i)\Delta s_i-\int_a^b \phi(t)\sqrt{\sum_{j=1}^n x_j'(t)^2}dt\right|<\epsilon$

由于连续，故根据[[~/文档/note/数学分析/Chap7Note.org][定积分可积定理-定积分可积充要条件2-推论1]] $\int_a^b \phi(t)\sqrt{\sum_{j=1}^n x_j'(t)^2}dt$ 可积

故任意划分取点下均有 $\lim_{\lambda\to0}\sum_{i=1}^m \phi(t_i)\Delta s_i=\int_a^b \phi(t)\sqrt{\sum_{j=1}^n x_j'(t)^2}dt$ 

则根据[[MK22][定义]]并带入 $\cos(\alpha_i(t))=\frac{x_i'(t)}{\sqrt{\sum_{j=1}^n x_j'(t)^2}}$ 

\begin{aligned}
\int_L\vec{F}(\vec{x})\cdot\tau(\vec{x})ds&=\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i\\
=&\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}(t_i))\cdot\tau(\vec{x}(t_i))\right)\Delta s_i\\
=&\int_a^b\left\{\vec{F}(\vec{x}(t))\cdot\tau(\vec{x}(t))\sqrt{\sum_{j=1}^n x_j'(t)^2}\right\}dt\\
=&\int_a^b\left\{\sum_{i=1}^n f_i(\vec{x}(t))\cos(\alpha_i(t))\sqrt{\sum_{j=1}^n x_j'(t)^2}\right\}dt\\
=&\int_a^b\left\{\sum_{i=1}^n f_i(\vec{x}(t))\frac{x_i'(t)}{\sqrt{\sum_{j=1}^n x_j'(t)^2}}\sqrt{\sum_{j=1}^n x_j'(t)^2}\right\}dt\\
=&\int_a^b\left\{\sum_{i=1}^n f_i(\vec{x}(t))x_i'(t)\right\}dt\\
\end{aligned}

*** 推论

条件（1）改为分段光滑，[[MK25][微分形式]]亦等价，即 $\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i=\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)$

**** 证明

***** 对于分两段光滑

设 $L=L_1\cup L_2$ 曲线方向 $L_1\to L_2$ ，则根据[[MK25][之前证明]]：

对 $L_1$ 有 $\forall\epsilon>0,\exists\delta_1>0,\forall\lambda<\delta_1\Rightarrow\forall (P,\vec{x}_i)\rightarrow\left|\sum_{i=1}^{m_k}\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=1}^{m_k} \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)\right|<\epsilon$ 

对 $L_2$ 有 $\forall\epsilon>0,\exists\delta_2>0,\forall\lambda<\delta_2\Rightarrow\forall (P,\vec{x}_i)\rightarrow\left|\sum_{i=m_k+1}^m\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=m_k+1}^m \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)\right|<\epsilon$ 

由于 $\vec{F}(\vec{x})$ 在有界闭区域 $L$ 上连续，故根据[[~/文档/note/数学分析/Chap11Note.org][连续函数性质-有界性定理]]必有界，则 $\exists M_1\geq\left|\vec{F}(\vec{x})\right|,\vec{x}\in L$

同理根据[[MK51][之前证明]]亦有 $\exists M_2\geq\left|\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right|,\vec{x}\in L$ 定义 $M=\max(M_1,M_2)$

故 $\forall\epsilon>0$ 可取 $\delta=\min(\delta_1,\delta_2,\frac{\epsilon}{M})$ 则 $\forall\lambda<\delta$ 若划分 $P$ 的分段 $P_{m_1}P_{m_1+1}$ 包含 $L_1,L_2$ 分点 $P_k$ 此时有

\begin{aligned}
&\left|\sum_{i=1}^{m}\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=1}^{m} \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)\right|\\
=&\bigg|\sum_{i=1}^{m_1-1}\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=1}^{m_1-1} \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)+\sum_{i=m_1+1}^{m}\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=m_1+1}^{m} \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)+\\&\left(\left(\vec{F}(\vec{x}_{m_1})\cdot\tau(\vec{x}_{m_1})\right)\Delta s_{m_1}-\left(\vec{F}(\vec{x}_{m_1})\cdot\Delta \vec{x}_{m_1}\right)\right)\bigg|\\
\leq&\left|\sum_{i=1}^{m_1-1}\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=1}^{m_1-1} \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)\right|+\left|\sum_{i=m_1+1}^{m}\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=m_1+1}^{m} \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)\right|+\\&\left|\vec{F}(\vec{x}_{m_1})\cdot\tau(\vec{x}_{m_1})\right|\Delta s_{m_1}+\left|\vec{F}(\vec{x}_{m_1})\cdot\Delta \vec{x}_{m_1}\right|\\
\end{aligned}

对于第三部分，有 $\left|\vec{F}(\vec{x}_{m_1})\cdot\tau(\vec{x}_{m_1})\right|\Delta s_{m_1}\leq M\frac{\epsilon}{M}=\epsilon$ ，

对于第四部分，有 $\left|\vec{F}(\vec{x}_{m_1})\cdot\Delta \vec{x}_{m_1}\right|=\left|\vec{F}(\vec{x}_{m_1})\right|\cos(\alpha)\left|\Delta \vec{x}_{m_1}\right|\leq\left|\vec{F}(\vec{x}_{m_1})\right|\left|\Delta \vec{x}_{m_1}\right|<M\frac{\epsilon}{M}=\epsilon$

对于第一部分，有：

\begin{aligned}
&\left|\sum_{i=1}^{m_1-1}\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=1}^{m_1-1} \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)\right|\\
=&\bigg|\sum_{i=1}^{m_1-1}\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=1}^{m_1-1} \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)+\left(\left(\vec{F}(\vec{x}_{m_k})\cdot\tau(\vec{x}_{m_k})\right)\Delta s_{m_k}-\left(\vec{F}(\vec{x}_{m_k})\cdot\Delta \vec{x}_{m_k}\right)\right)\\&-\left(\left(\vec{F}(\vec{x}_{m_k})\cdot\tau(\vec{x}_{m_k})\right)\Delta s_{m_k}-\left(\vec{F}(\vec{x}_{m_k})\cdot\Delta \vec{x}_{m_k}\right)\right)\bigg|\\
\leq&\left|\sum_{i=1}^{m_k}\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=1}^{m_k} \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)\right|+\left|\vec{F}(\vec{x}_{m_k})\cdot\tau(\vec{x}_{m_k})\right|\Delta s_{m_k}-\left|\vec{F}(\vec{x}_{m_k})\cdot\Delta \vec{x}_{m_k}\right|
\end{aligned}

其中 $\Delta s_{m_k}$ 为 $P_{m_1}P_k$ 的弧长 $\vec{x}_{m_k}\in P_{m_1}P_k$ 为弧上中点 $\Delta x_{m_k}$ 为点 $P_{m_k},P_{m_1}$ 的向量值的差

由于 $\Delta s_{m_k}<\delta$ 故有 $\left|\sum_{i=1}^{m_k}\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=1}^{m_k} \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)\right|<\epsilon$ 

结合第三、四部分证明得 $\left|\sum_{i=1}^{m_1-1}\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=1}^{m_1-1} \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)\right|<3\epsilon$

同理可证第二部分 $\left|\sum_{i=m_1+1}^{m}\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=m_1+1}^{m} \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)\right|<3\epsilon$

最终得 $\forall\epsilon,\exists\delta,\forall\lambda<\delta\Rightarrow\forall(P,\vec{x}_i)\rightarrow\left|\sum_{i=1}^{m}\left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i-\sum_{i=1}^{m} \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)\right|<8\epsilon$

即对于 $L$ 有 $\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\tau(\vec{x}_i)\right)\Delta s_i=\lim_{\lambda\to0}\sum_{i=1}^m \left(\vec{F}(\vec{x}_i)\cdot\Delta \vec{x}_i\right)$

***** 对于多段光滑

对于有限分段光滑，可按上述证法依次类推。

* 第二类曲面积分

** <<MK35>>双侧曲面定义

给定曲面 $\Omega$ 上一点 $\vec{x}_0$ 的法线方向 $\vec{n}(\vec{x}_0)$ 在不接触曲面边界点的情况下沿任意轨迹（在 $\Omega$ 曲面内）移动 $\vec{x}$ 后回到 $\vec{x}_0$ 方向不变，则称双侧曲面。

摩比斯带为单侧曲面例子

** <<MK11>>定义 

若 $\Omega$ 是 $R^3$ 空间上的曲面，定义 $\vec{r}=(x,y,z)$ ， $P$ 为用光滑曲线对曲面的划分，划分为 $\Delta\Omega_i$ 定义

（1） $\vec{r}_i\in\Delta\Omega_i$ 为小区面内任意一点

（2） $\Delta\Omega_i$ 面积为 $\Delta S_i$ 

（3） $\lambda_i$ 为曲面 $\Delta\Omega_i$ 的直径， $\lambda=\max(\lambda_i)$

（4） $\vec{e}(\vec{r}),\vec{r}\in\Omega$ 为定向单位长度 $\vec{r}$ 的法向量

向量值函数 $\vec{F}(\vec{r})=\begin{cases}f_1(\vec{r})\\f_2(\vec{r})\\f_3(\vec{r})\end{cases},\vec{r}\in\Omega$ 连续 

若对于任意划分与取点均有 $\lim_{\lambda\to0}\sum_{i=1}^n \vec{F}(\vec{r}_i)\cdot\vec{e}(\vec{r}_i)\Delta S_i=I,-\infty<I<+\infty$

则称此极限为曲线 $\Omega$ 上的第二类曲面积分，记为 $\iint_\Omega \vec{F}(\vec{r})\cdot\vec{e}(\vec{r})ds=\lim_{\lambda\to0}\sum_{i=1}^n \vec{F}(\vec{r}_i)\cdot\vec{e}(\vec{r}_i)\Delta S_i$

若 $\vec{e}(\vec{r})=\left(\cos(\alpha_1(\vec{r}))),\cos(\alpha_2(\vec{r}))),\cos(\alpha_3(\vec{r}))\right)$ 则 $\iint_\Omega \vec{F}(\vec{x})\cdot\vec{e}(\vec{x})ds=\iint_\Omega \left\{\sum_{i=1}^3 f_i(\vec{x})\cos(\alpha_i(\vec{x}))\right\}ds$ 转化为第一类曲面积分

** 性质

*** <<MK20>>方向性

若 $-\Omega$ 为双侧曲面 $\Omega$ 的反侧，则有 $\iint_\Omega \vec{F}(\vec{r})\cdot\vec{e}(\vec{r})ds=-\iint_{-\Omega} \vec{F}(\vec{r})\cdot\vec{e}(\vec{r})ds$

*** 线性

 $\iint_\Omega \left(A\vec{F}(\vec{r})+B\vec{G}(\vec{r})\right)\cdot\vec{e}(\vec{r})ds=A\iint_\Omega \vec{F}(\vec{r})\cdot\vec{e}(\vec{r})ds+B\iint_\Omega\vec{G}(\vec{r})\right)\cdot\vec{e}(\vec{r})ds$

**** 证明

根据向量点积分配律 $\iint_\Omega \left(A\vec{F}(\vec{r})+B\vec{G}(\vec{r})\right)\cdot\vec{e}(\vec{r})ds=\iint_\Omega \left(A\vec{F}(\vec{r})\cdot\vec{e}+B\vec{G}(\vec{r})\cdot\vec{e}(\vec{r})\right)ds=\iint_\Omega \left\{A\left[\sum_{i=1}^3f_i(\vec{r})\cos(\alpha_i(\vec{r}))\right]+B\left[\sum_{i=1}^3g_i(\vec{r})\cos(\beta_i(\vec{r}))\right]\right\}ds$

根据[[MK10][第一类曲面积分线性]]有 $\iint_\Omega \left\{A\left(\sum_{i=1}^3f_i(\vec{r})\cos(\alpha_i(\vec{r}))\right)+B\left(\sum_{i=1}^3g_i(\vec{r})\cos(\beta_i(\vec{r}))\right)\right\}ds=A\iint_\Omega \left[\sum_{i=1}^3f_i(\vec{r})\cos(\alpha_i(\vec{r}))\right]ds+B\iint_\Omega\left[\sum_{i=1}^3g_i(\vec{r})\cos(\beta_i(\vec{r}))\right]ds$

又根据[[MK11][定义]] $A\iint_\Omega \left[\sum_{i=1}^3f_i(\vec{r})\cos(\alpha_i(\vec{r}))\right]ds+B\iint_\Omega\left[\sum_{i=1}^3g_i(\vec{r})\cos(\beta_i(\vec{r}))\right]ds=A\iint_\Omega \vec{F}(\vec{r})\cdot\vec{e}(\vec{r})ds+B\iint_\Omega\vec{G}(\vec{r})\right)\cdot\vec{e}(\vec{r})ds$

*** 区间可加

若 $\Omega$ 分为 $\Omega_1,\Omega_2$ 两段，则

（1） $\iint_\Omega \vec{F}(\vec{r})\cdot \vec{e}(\vec{r})ds$ 存在，则 $\iint_{\Omega_1} \vec{F}(\vec{r})\cdot \vec{e}(\vec{r})ds,\iint_{\Omega_2} \vec{F}(\vec{r})\cdot \vec{e}(\vec{r})ds$ 也存在且三者方向一致

（2） $\iint_{\Omega_1}\vec{F}(\vec{r})\cdot \vec{e}(\vec{r})ds,\iint_{\Omega_2}\vec{F}(\vec{r})\cdot \vec{e}(\vec{r})ds$ 存在，则 $\int_\Omega\vec{F}(\vec{r})\cdot \vec{e}(\vec{r})ds$ 也存在

且两种情况都有 $\int_\Omega\vec{F}(\vec{r})\cdot \vec{e}(\vec{r})ds=\int_{\Omega_1}\vec{F}(\vec{r})\cdot \vec{e}(\vec{r})ds+\int_{\Omega_2}\vec{F}(\vec{r})\cdot \vec{e}(\vec{r})ds$

**** 证明

由于 $\vec{F}(\vec{r})\cdot \vec{e}(\vec{r})=\sum_{i=1}^3 f_i(\vec{r})\cos(\alhpa(\vec{r}))$ 故将上述第二类曲面积分转化为第一类

根据[[MK9][第一类曲面积分区间可加性]]便可证明上述结论。

** <<MK18>>计算

若曲面 $\Omega\subset R^3$ 的参数表示为 $\begin{cases}x(u,v)\\y(u,v)\\z(u,v)\end{cases},(u,v)\in D\subset R^2$ 为 $R^2$ 到 $R^3$ 的一一对应映射，且满足

（1） 参数函数的偏导数在 $(u,v)\in D$ 上存在且连续， $D$ 为有界闭区域

（2） 雅克比矩阵 $\left|\begin{matrix}\frac{\partial x(u,v)}{\partial u}&\frac{\partial x(u,v)}{\partial v}\\\frac{\partial y(u,v)}{\partial u}&\frac{\partial y(u,v)}{\partial v}\\\frac{\partial z(u,v)}{\partial u}&\frac{\partial z(u,v)}{\partial v}\end{matrix}\right|$ 满秩，即有一组2阶行列式不为零

（3） 参数表示一一对应

向量值函数 $\vec{F}(x,y,z)=\begin{cases}f_x(x,y,z)\\f_y(x,y,z)\\f_z(x,y,z)\end{cases},(x,y,z)\in\Omega$ 连续，定义 $\vec{r}=(x,y,z),\vec{r}(u,v)=(x(u,v),y(u,v),z(u,v))$

则第二类曲面积分 $\iint_\Omega \vec{F}(\vec{r})\cdot\vec{e}(\vec{r})ds=\pm\iint_D\left\{f_x(\vec{r}(x,y))\frac{\partial(y,z)}{\partial(u,v)}+f_y(\vec{r}(x,y))\frac{\partial(z,x)}{\partial(u,v)}+f_z(\vec{r}(x,y))\frac{\partial(x,y)}{\partial(u,v)}\right\}dudv$

尤其当曲面 $\Omega=\left\{(x,y,z)\big|x=f(y,z),(y,z)\in D_{yz}\right\}=\left\{(x,y,z)\big|y=g(x,z),(z,x)\in D_{zx}\right\}=\left\{(x,y,z)\big|z=h(y,z),(x,y)\in D_{xy}\right\}$ 

时有微分形式 $\iint_\Omega \vec{F}(\vec{r})\cdot\vec{e}(\vec{r})ds=\pm\iint_{D_{xz}} f_x(f(y,z),y,z)dxdz\pm\iint_{D_{yz}} f_z(x,g(x,z),z)dydz\pm\iint_{D_{xy}} f_z(x,y,h(x,y))dxdy$

*** 证明

**** 计算 $\cos(\alpha_i(\vec{r}(u,v)))$ 

根据[[~/文档/note/数学分析/Chap12Note.org][偏导数几何应用-空间平面-法向量，法线方程，法平面-参数表示平面]]可知 $R^3$ 下平面法向量为 $\left(\frac{\partial(y,z)}{\partial(u,v)},\frac{\partial(z,x)}{\partial(u,v)},\frac{\partial(x,y)}{\partial(u,v)}\right)$

其中 $\frac{\partial(y,z)}{\partial(u,v)}$ 为函数 $y(u,v),x(u,v)$ 关于 $(u,v)$ 的雅克比行列式。

由于单位向量，故需除以向量长度，即 $\sqrt{\left(\frac{\partial(y,z)}{\partial(u,v)}\right)^2+\left(\frac{\partial(z,x)}{\partial(u,v)}\right)^2+\left(\frac{\partial(x,y)}{\partial(u,v)}\right)^2}=\sqrt{(y_uz_v-y_vz_u)^2+(x_uz_v-x_vz_u)^2+(x_uy_v-x_vy_u)^2}$

根据[[MK13][之前证明]] $\sqrt{\left(\frac{\partial(y,z)}{\partial(u,v)}\right)^2+\left(\frac{\partial(z,x)}{\partial(u,v)}\right)^2+\left(\frac{\partial(x,y)}{\partial(u,v)}\right)^2}=\sqrt{EG-F^2}$ 由于

故 $\cos(\alpha_i(\vec{r}(u,v)))=\frac{\frac{\partial(y,z)}{\partial(u,v)}}{\sqrt{EG-F^2}}$ 且由于法向量定向，故 $\cos(\alpha_i(\vec{r}(u,v)))=\pm\frac{\frac{\partial(y,z)}{\partial(u,v)}}{\sqrt{EG-F^2}}$ 

**** 计算

***** 准备工作

$P$ 为满足[[MK11][定义]]的划分，并沿用[[MK11][定义]]中的相关符号

由于一一对应，故对于 $\Delta\Omega_i$ 必有对应区域 $\Delta D_i$ ，对于 $\vec{r}_i=(x_i,y_i,z_i)$ 必有对应 $(u_i,v_i)$ 使得 $\vec{r}(u_i,v_i)=\vec{r}_i$

写出黎曼和 $\sum_{i=1}^n \left(f_x(\vec{r}_i)\cos(\alpha_x(\vec{r}_i))+f_y(\vec{r}_i)\cos(\alpha_y(\vec{r}_i))+f_z(\vec{r}_i)\cos(\alpha_z(\vec{r}_i))\right)\Delta S_i$

带入 $\vec{r}(u_i,v_i)=\vec{r}_i$ 得  $\sum_{i=1}^n \left(f_x(\vec{r}(u_i,v_i)\cos(\alpha_x(\vec{r}(u_i,v_i)))+f_y(\vec{r}(u_i,v_i))\cos(\alpha_y(\vec{r}(u_i,v_i)))+f_z(\vec{r}(u_i,v_i))\cos(\alpha_z(\vec{r}(u_i,v_i)))\right)\Delta S_i$

定义 $\phi(u,v)=f_x(\vec{r}(u,v)\cos(\alpha_x(\vec{r}(u,v)))+f_y(\vec{r}(u,v))\cos(\alpha_y(\vec{r}(u,v)))+f_z(\vec{r}(u,v))\cos(\alpha_z(\vec{r}(u,v)))$ 故黎曼和简化为 $\sum_{i=1}^n\phi(u_i,v_i)\Delta S_i$

由于满秩，故 $\sqrt{\left(\frac{\partial(y,z)}{\partial(u,v)}\right)^2+\left(\frac{\partial(z,x)}{\partial(u,v)}\right)^2+\left(\frac{\partial(x,y)}{\partial(u,v)}\right)^2}=\sqrt{EG-F^2}\ne0$ 故 $\cos(\alpha_i(\vec{r}(u,v)))=\pm\frac{\frac{\partial(y,z)}{\partial(u,v)}}{\sqrt{EG-F^2}}$ 连续

由于 $\vec{F}(\vec{r})$ 根据条件连续，故 $\phi(u,v)$ 连续且 $D$ 有界闭集，根据[[~/文档/note/数学分析/Chap7Note.org][函数一致连续-康托定理]] $\phi(u,v)$ 一致连续

即 $\forall\epsilon>0,\exists\delta,\forall|(u',v')-(u,v)|<\delta,(u',v'),(u,v)\in D\Rightarrow\left|\phi(u',v')-\phi(u,v)\right|<\frac{\epsilon}{S}$ 其中 $S$ 为曲面面积

***** 证明重积分与黎曼和极限相等

根据[[MK24][曲面面积]]得

\begin{aligned}
&\left|\sum_{i=1}^n\phi(u_i,v_i)\Delta S_i-\iint_D\phi(u,v)\sqrt{EG-F^2}dudv\right|\\
=&\left|\sum_{i=1}^n\phi(u_i,v_i)\iint_{\Delta D_i}\sqrt{EG-F^2}dudv-\sum_{i=1}^n\iint_{\Delta D_i}\phi(u,v)\sqrt{EG-F^2}dudv\right|\\
=&\left|\sum_{i=1}^n\iint_{\Delta D_i}\left\{\left(\phi(u_i,v_i)-\phi(u,v)\right)\sqrt{EG-F^2}\right\}dudv\right|\\
\leq&\sum_{i=1}^n\left|\iint_{\Delta D_i}\left\{\left(\phi(u_i,v_i)-\phi(u,v)\right)\sqrt{EG-F^2}\right\}dudv\right|
\end{aligned}

由于一阶偏导数连续，故 $\sqrt{\left(\frac{\partial(y,z)}{\partial(u,v)}\right)^2+\left(\frac{\partial(z,x)}{\partial(u,v)}\right)^2+\left(\frac{\partial(x,y)}{\partial(u,v)}\right)^2}=\sqrt{EG-F^2}\ne0$ 也连续

故 $\left(\phi(u_i,v_i)-\phi(u,v)\right)\sqrt{EG-F^2}$ 亦连续，故根据[[~/文档/note/数学分析/Chap13Note.org][有界闭集上的重积分-二重积分-推论]]重积分 $\iint_{\Delta D_i}\left\{\left(\phi(u_i,v_i)-\phi(u,v)\right)\sqrt{EG-F^2}\right\}dudv$ 可积

又根据[[~/文档/note/数学分析/Chap13Note.org][重积分性质与计算-性质-绝对可积性]] $\iint_{\Delta D_i}\left|\left(\phi(u_i,v_i)-\phi(u,v)\right)\sqrt{EG-F^2}\right|dudv$ 也可积

且有 $\left|\iint_{\Delta D_i}\left\{\left(\phi(u_i,v_i)-\phi(u,v)\right)\sqrt{EG-F^2}\right\}dudv\right|\leq\iint_{\Delta D_i}\left|\left(\phi(u_i,v_i)-\phi(u,v)\right)\sqrt{EG-F^2}\right|dudv=\iint_{\Delta D_i}\left\{\left|\phi(u_i,v_i)-\phi(u,v)\right|\sqrt{EG-F^2}\right\}dudv$

则根据[[~/文档/note/数学分析/Chap13Note.org][重积分性质与计算-性质-线性]]及[[~/文档/note/数学分析/Chap13Note.org][重积分性质与计算-性质-保序性]]及[[~/文档/note/数学分析/Chap13Note.org][重积分性质与计算-性质-区间可加性]]

\begin{aligned}
&\left|\sum_{i=1}^n\phi(u_i,v_i)\Delta S_i-\iint_D\phi(u,v)\sqrt{EG-F^2}dudv\right|\\
\leq&\sum_{i=1}^n\left|\iint_{\Delta D_i}\left\{\left(\phi(u_i,v_i)-\phi(u,v)\right)\sqrt{EG-F^2}\right\}dudv\right|\\
\leq&\sum_{i=1}^n\iint_{\Delta D_i}\left|\left(\phi(u_i,v_i)-\phi(u,v)\right)\sqrt{EG-F^2}\right|dudv\\
\leq&\sum_{i=1}^n\iint_{\Delta D_i}\left\{\left|\phi(u_i,v_i)-\phi(u,v)\right|\sqrt{EG-F^2}\right\}dudv\\
\leq&\sum_{i=1}^n\iint_{\Delta D_i}\left\{\frac{\epsilon}{S}\sqrt{EG-F^2}\right\}dudv\\
=&\frac{\epsilon}{S}\sum_{i=1}^n\iint_{\Delta D_i}\left\{\sqrt{EG-F^2}\right\}dudv\\
=&\frac{\epsilon}{S}\iint_{\Delta D}\left\{\sqrt{EG-F^2}\right\}dudv\\
=&\frac{\epsilon}{S}S\\
=&\epsilon\\
\end{aligned}

***** 证明结论

综上所述，即 $$\forall\epsilon>0,\exists\delta,\forall\lambda<\delta,\forall(P,(u_i,v_i))\Rightarrow\left|\sum_{i=1}^n\vec{F}(\vec{r}(u_i,v_i))\cdot\tau(\vec{r}(u_i,v_i))\Delta S_i-\iint_D \vec{F}(\vec{r}(u,v))\cdot\tau(\vec{r}(u,v))\sqrt{EG-F^2}dudv\right|<\epsilon$$

即为 $\lim_{\lambda\to0}\sum_{i=1}^n\vec{F}(\vec{r}_i)\cdot\tau(\vec{r}_i)\Delta S_i=\lim_{\lambda\to0}\sum_{i=1}^n\vec{F}(\vec{r}(u_i,v_i))\cdot\tau(\vec{r}(u_i,v_i))\Delta S_i=\iint_D \vec{F}(\vec{r}(u,v))\cdot\tau(\vec{r}(u,v))\sqrt{EG-F^2}dudv$

又因为 $\vec{F}(\vec{r}(u,v))\cdot\tau(\vec{r}(u,v))$ 连续，故根据[[~/文档/note/数学分析/Chap13Note.org][有界闭集上的重积分-二重积分-推论]] $\iint_D \vec{F}(\vec{r}(u,v))\cdot\tau(\vec{r}(u,v))\sqrt{EG-F^2}dudv$ 收敛

则根据定义[[MK11][定义]] $\iint_\Omega \vec{F}(\vec{r})\cdot\tau(\vec{r})ds=\lim_{\lambda\to0}\sum_{i=1}^n\vec{F}(\vec{r}(u_i,v_i))\cdot\tau(\vec{r}(u_i,v_i))\Delta S_i=\iint_D \vec{F}(\vec{r}(u,v))\cdot\tau(\vec{r}(u,v))\sqrt{EG-F^2}dudv$ 

代入 $\cos(\alpha_i(\vec{r}(u,v)))=\pm\frac{\frac{\partial(y,z)}{\partial(u,v)}}{\sqrt{EG-F^2}}$ 到重积分
\begin{aligned}
\iint_\Omega \vec{F}(\vec{r})\cdot\tau(\vec{r})ds=&\iint_D \vec{F}(\vec{r}(u,v))\cdot\tau(\vec{r}(u,v))\sqrt{EG-F^2}dudv\\
=&\iint_D \left[f_x(\vec{r}(u,v)\cos(\alpha_x(\vec{r}(u,v)))+f_y(\vec{r}(u,v))\cos(\alpha_y(\vec{r}(u,v)))+f_z(\vec{r}(u,v))\cos(\alpha_z(\vec{r}(u,v)))\right]\sqrt{EG-F^2}dudv\\
=&\iint_D \left[f_x(\vec{r}(u,v)\left(\pm\frac{\frac{\partial(y,z)}{\partial(u,v)}}{\sqrt{EG-F^2}}\right)+f_y(\vec{r}(u,v))\left(\pm\frac{\frac{\partial(z,x)}{\partial(u,v)}}{\sqrt{EG-F^2}}\right)+f_z(\vec{r}(u,v))\left(\pm\frac{\frac{\partial(x,y)}{\partial(u,v)}}{\sqrt{EG-F^2}}\right)\right]\sqrt{EG-F^2}dudv\\
=&\pm\iint_D\left\{f_x(\vec{r})\frac{\partial(y,z)}{\partial(u,v)}+f_y(\vec{r})\frac{\partial(z,x)}{\partial(u,v)}+f_z(\vec{r})\frac{\partial(x,y)}{\partial(u,v)}\right\}dudv

\end{aligned}
 
**** <<MK26>>微分形式

定义 $dx\wedge dy=\cos(\alpha_3(\vec{r}))ds$ 则 $dx\wedge dy$ 可看成面积微元与 $x,y$ 平面的有向面积投影

故重曲面积分亦可写为

\begin{aligned}
&\iint_\Omega \vec{F}(\vec{r})\cdot\vec{e}(\vec{r})ds\\
=&\iint_\Omega f_x(\vec{r})\cos(\alpha_x(\vec{r}))ds+\iint_\Omega f_y(\vec{r})\cos(\alpha_y(\vec{r}))ds+\iint_\Omega f_z(\vec{r})\cos(\alpha_z(\vec{r}))ds\\
=&\iint_\Omega f_x(\vec{r})dy\wedge dz+\iint_\Omega f_y(\vec{r})dz\wedge dx+\iint_\Omega f_z(\vec{r})dx\wedge dy
\end{aligned}

若曲面可表示为 $z=h(x,y)$ 且一一对应（每一组 $(x,y)$ 对应一个 $z$ 值）则 $F(x,y,z)=f(x,y)-z=0$ 

故根据根据[[~/文档/note/数学分析/Chap12Note.org][偏导数几何应用-空间平面-法向量，法线方程，法平面-曲面一般表述]]法向量为 $(F_x,F_y,F_z)=\left(\frac{\partial f(x,y)}{\partial x},\frac{\partial f(x,y)}{\partial y},1\right)$

则根据[[MK12][第一类曲面积分计算]]，带入 $\cos(\alpha_z(\vec{r}(u,v)))=\pm\frac{1}{\sqrt{EG-F^2}}$ 于 $\iint_\Omega f_z(\vec{r})dx\wedge dy$ 有

\begin{aligned}
&\iint_\Omega f_z(\vec{r})dx\wedge dy\\
=&\iint_\Omega f_z(\vec{r})\cos(\alpha_z(\vec{r}))ds\\
=&\iint_{D_{xy}} f_z(x,y,h(x,y))\left(\pm\frac{1}{\sqrt{EG-F^2}}\right)\sqrt{EG-F^2}dxdy\\
=&\pm\iint_{D_{xy}} f_z(x,y,h(x,y))dxdy\\
\end{aligned}

同理在表述转换下也可得 $\iint_\Omega f_x(\vec{r})dy\wedge dz=\pm\iint_{D_{yz}}f_x(f(y,z),y,z)dydz,\iint_\Omega f_y(\vec{r})dz\wedge dx=\pm\iint_{D_{zx}}f_y(x,g(x,z),z)dzdx$ 

故有

\begin{aligned}
\iint_\Omega \vec{F}(\vec{r})\cdot\vec{e}(\vec{r})ds&=\iint_\Omega f_x(\vec{r})dy\wedge dz+\iint_\Omega f_y(\vec{r})dz\wedge dx+\iint_\Omega f_z(\vec{r})dx\wedge dy\\
&=\pm\iint_{D_{xz}} f_x(f(y,z),y,z)dxdz\pm\iint_{D_{yz}} f_z(x,g(x,z),z)dydz\pm\iint_{D_{xy}} f_z(x,y,h(x,y))dxdy
\end{aligned}

* Green公式，Gauss公式，Stokes公式

** 前提定义

*** 简单闭合曲线

曲线 $L$ 方程为 $\vec{r}(t)=x(t)\vec{i}+y(t)\vec{j},t:a\to b$ 若 $\vec{r}(\alpha)=\vec{r}(\beta),\alpha<\beta$ 则 $\forall \alpha<t_1<t_2<\beta\Rightarrow \vec{r}(t_1)\ne\vec{r}(t_2)$

*** <<MK40>>平面单连通区域

如果区域 $D\subset R^2$ 中的任意一条封闭曲线都可以不经过 $D$ 外的点而收缩成 $D$ 中的一点，且 $D$ 边界不想重，

则称为平面单连通区域。

等价于 $D$ 中任意闭合曲线所包围的区域 $S$ 均有 $S\subset D$ 

即若包含的区域存在不属于 $D$ 的点集，则 $S$ 无法不通过这些点收缩成 $D$ 中的点。

*** <<MK39>>空间单连通区域

如果区域 $D\subset R^3$ 中的任意一条封闭曲线都可以不经过 $D$ 外的点连续收缩成 $D$ 中的一点，则称为空间单连通区域。

*** <<MK41>>二维单连通区域

如果区域 $D\subset R^3$ 中的任意一封闭曲面都可以不经过 $D$ 外的点而收缩成 $D$ 中的一点，则称为二维单连通区域。

*** <<MK14>>二维标准区域

平面上区域 $D$ 可表示为 $D=\left\{(x,y)\big|a<x<b,y_1(x)<y<y_2(x)\right\}=\left\{(x,y)\big|c<y<d,x_1(y)<x<x_2(y)\right\}$

*** <<MK17>>三维标准区域

空间上区域 $D\in R^3$ 可表示为以下三种性质，其中 $D_{xy}$ 为 $D$ 在 $xy$ 平面的投影 $D_{yz},D_{zx}$ 同理

$D=\left\{(x,y,z)\big|z_1(x,y)<z<z_2(x,y),(x,y)\in D_{xy}\right\}$

$D=\left\{(x,y,z)\big|y_1(x,z)<y<y_2(x,z),(x,z)\in D_{xz}\right\}$

$D=\left\{(x,y,z)\big|x_1(z,y)<x<x_2(z,y),(z,y)\in D_{zy}\right\}$

*** <<MK23>>三维标准曲面

若曲面 $\Sigma=\left\{(x,y,z)\big|x=f(y,z),(y,z)\in D_{yz}\right\}=\left\{(x,y,z)\big|y=f(z,x),(z,x)\in D_{zx}\right\}=\left\{(x,y,z)\big|z=f(x,y),(x,y)\in D_{xy}\right\}$ 则定义为标准曲面

*** <<MK21>>诱导定向

规定曲线方向后，沿闭合曲线 $L\in R^2$ 朝该方向走走，围成的区域在左手边的方向为诱导定向

** <<MK16>>Green公式

若：

（1） $D$ 为平面（有限分段）光滑闭合曲线 $L$ 围成的[[MK40][单连通区域]]

（2） 函数 $P(x,y),Q(x,y)$ 在区域 $D$ 上有连续偏导

（3） $D$ 可由（有限分段）光滑曲线切割成有限个[[MK14][标准区域]]

则 $\int_L P(x,y)dx+Q(x,y)dy=\iint_D \left(\frac{\partial Q(x,y)}{\partial x}-\frac{\partial P(x,y)}{\partial y}\right)dxdy$ 曲线方向为逆时针时

即 $R^2$ 下的第二类曲线积分等于偏导数差在闭合曲线包含的面积的二重积分

*** 证明

**** 先证明标准区域

根据[[MK14][标准区域定义]] $D=\left\{(x,y)\big|a<x<b,y_1(x)<y<y_2(x)\right\}$

重积分化为累次积分 $\iint_D \frac{\partial P(x,y)}{\partial y}dxdy=\int_a^b\int_{y_1(x)}^{y_2(x)}\frac{\partial P(x,y)}{\partial y}dydx$

由于：

（1） $P(x,y),Q(x,y)$ 在区域 $D$ 上有连续偏导，故 $\frac{\partial P(x,y)}{\partial y}$ 连续，则根据[[~/文档/note/数学分析/Chap7Note.org][牛顿莱布尼茨公式]]有 $\int_{y_1(x)}^{y_2(x)}\frac{\partial P(x,y)}{\partial y}dy=P(x,y_2(x))-P(x,y_1(x))$ 必存在

（2） $P(x,y)$ 有连续偏导，则根据[[~/文档/note/数学分析/Chap12Note.org][偏导数与全微分-可微条件]]与根据[[~/文档/note/数学分析/Chap12Note.org][偏导数与全微分-欧几里得空间连续，可导，可微及方向导数关系]]得出 $P(x,y)$ 连续

（3） 又因为 $D$ 边界光滑，根据[[~/文档/note/数学分析/Chap13Note.org][光滑曲线（面）的面（体）积为零]]边界点面积为零，故根据[[~/文档/note/数学分析/Chap13Note.org][有界闭集上的重积分-二重积分-推论]]得出重积分可积

故重积分化为累次积分条件成立。

则有 $$\iint_D \frac{\partial P(x,y)}{\partial y}dxdy=\int_a^b\int_{y_1(x)}^{y_2(x)}\frac{\partial P(x,y)}{\partial y}dydx=\int_a^b\left\{P(x,y_2(x))-P(x,y_1(x))\right\}dx$$

又由于 $\int_L P(x,y)dx$ 为第二类曲线积分，同理根据[[MK9][第二类曲线积分区域可加性]]可

将 $L$ 分为 $L_1=\left\{(x,y)\big|y=y_1(x)\right\},L_2=\left\{(x,y)\big|y=y_1(x)\right\}$ 则根据[[MK9][第二类曲线积分区域可加性]] $\int_L P(x,y)dx=\int_{L_1} P\left(x,y_1(x)\right)dx+\int_{L_2} P\left(x,y_2(x)\right)dx$

定义 $x(t)=t$ 则 $\frac{dx}{dt}=1\Rightarrow dx=dt$ 根据[[MK12][第二类曲面积分计算]]得出 

\begin{aligned}
&\int_L P(x,y)dx\\
=&\int_{L_1} P(x,y_1(x))dx+\int_{L_2} P(x,y_2(x))dx\\
=&\int_a^b P(t,y_1(t))dt+\int_b^a P(t,y_2(t))dt\\
=&\int_a^b \left\{P(t,y_1(t))dt- P(t,y_2(t))\right\}dt\\
=&-\int_a^b \left\{P(x,y_2(x))dt- P(x,y_1(x))\right\}dx\\
=&-\iint_D \frac{\partial P(x,y)}{\partial y}dxdy
\end{aligned}

同理可证  $\int_L Q(x,y)dy=\iint_D\frac{\partial Q(x,y)}{\partial x}dxdy$

故对于标准区域 $\int_L P(x,y)dx+Q(x,y)dy=\iint_D \left(\frac{\partial Q(x,y)}{\partial x}-\frac{\partial P(x,y)}{\partial y}\right)dxdy$

**** 非标准区域

对于非标准区域，根据条件（3）可用光滑曲线分割为有限个标准区域，根据[[MK15][方向性]]可得分割线上的第二类曲线积分和为零，故同理定理成立。

** Green定理

区域 $D\in R^2$ 为单连通区域，函数 $P(x,y),Q(x,y)$ 在 $(x,y)\in D$ 上有连续偏导。则以下4个命题等价：

（1） 任意（有限分段）光滑闭合曲线 $L\in D$ 的第二类曲线积分 $\int_L P(x,y)dx+Q(x,y)dy=0$

（2） 第二类曲线积分 $\int_L P(x,y)dx+Q(x,y)dy$ 与路径无关

（3） 存在 $D$ 上可微函数 $U(x,y)$ 使得 $dU=P(x,y)dx+Q(x,y)dy$ 即 $P(x,y),Q(x,y)$ 组成 $U(x,y)$ 的全微分

（4） 在 $(x,y)\in D$ 上成立 $\frac{\partial P(x,y)}{\partial y}=\frac{\partial Q(x,y)}{\partial x}$

*** 证明  

**** 条件（1）推出条件（2）

定义曲线 $L=\begin{cases}x(t)\\y(t)\end{cases}t:a\to b$ 定义另一条曲线 $L'=\begin{cases}x'(t)\\y'(t)\end{cases}t:b\to a$ 其中 $(x(a),y(a))=(x'(a),y'(a)),(x(b),y(b))=(x'(b),y'(b))$ 

根据条件（1） $\int_{L+L'}P(x,y)dx+Q(x,y)dy=0$ 根据[[MK9][第二类曲线积分区间可加]] $\int_{L}P(x,y)dx+Q(x,y)dy+\int_{L'}P(x,y)dx+Q(x,y)dy=0$

根据[[MK15][方向性]] $\int_{L}P(x,y)dx+Q(x,y)dy=-\int_{L'}P(x,y)dx+Q(x,y)dy=\int_{-L'}P(x,y)dx+Q(x,y)dy$

由于 $-L'=\begin{cases}x'(t)\\y'(t)\end{cases}t:a\to b$ 故两条断点相同，不同路径的第二类曲线积分相等，则与路径无关。

**** 条件（2）推出条件（3）

***** 前提定义

定义 $U(x,y)=\int_L P(x,y)dx+Q(x,y)dy$ 其中 $L=\begin{cases}f_x(t)\\f_y(t)\end{cases}t:a\to b$ 其中 $(f_x(a),f_y(a))=(0,0),(f_x(b),f_y(b))=(x,y)$

根据条件 $\int_L P(x,y)dx+Q(x,y)dy$ 与路径无关，只与端点有关，故为方便，定义 $\int_L P(x,y)dx+Q(x,y)dy=\int_{(0,0)}^{(x,y)} P(u,v)du+Q(u,v)dv$

***** 证明 $\frac{\partial U(x,y)}{\parital x}=P(x,y), \frac{\partial U(x,y)}{\parital y}=Q(x,y)$ 

\begin{aligned}
\frac{\partial U(x,y)}{\parital x}=&\lim_{\Delta x\to 0}\frac{U(x+\Delta x,y)-U(x,y)}{\Delta x}\\
=&\lim_{\Delta x\to 0}\frac{\int_{(x,y)}^{(x+\Delta x,y)} P(u,v)du+Q(u,v)dv}{\Delta x}\\
\end{aligned}

由于积分与路径无关，对于 $\int_{(x,y)}^{(x+\Delta x,y)} P(u,v)du+Q(u,v)dv$ 可选择 $(x,y)$ 到 $(x+\Delta x,y)$ 的直线 $y$ 不变 $L=\begin{cases}f_x(t)=t\\f_y(t)=y\end{cases}t:x\to x+\Delta x$ 

故 $\int_{(x,y)}^{(x+\Delta x,y)} P(u,v)du+Q(u,v)dv=\int_{x}^{(x+\Delta x)} P(t,y)dt$

由于 $P(x,y),Q(x,y)$ 在 $(x,y)\in D$ 上有连续偏导，故 $P(x,y)$ 连续，且 $g(t)=1$ 为不变号函数，

故 $\int_{x}^{(x+\Delta x)} P(t,v)dt=P(\xi,y)\int_{x}^{(x+\Delta x)} dt=P(\xi,y)\Delta x, \xi\in[x,\Delta x]$

且根据夹逼定理 $\lim_{\Delta x\to 0}\xi=x$ 又根据 $P(x,y)$ 连续有 $\lim{\xi\to x}P(\xi,y)=P(\xi,y)$ 则有

\begin{aligned}
\frac{\partial U(x,y)}{\parital x}=&\lim_{\Delta x\to 0}\frac{\int_{(x,y)}^{(x+\Delta x,y)} P(u,v)du+Q(u,v)dv}{\Delta x}\\
=&\lim_{\Delta x\to 0}\frac{\int_{x}^{x+\Delta x} P(t,y)dt}{\Delta x}\\
=&\lim_{\Delta x\to 0}\frac{P(\xi,y)\int_{x}^{x+\Delta x}dt}{\Delta x}&\xi\in[x,x+\Delta x]\\
=&\lim_{\Delta x\to 0}P(\xi,y)&\xi\in[x,x+\Delta x]\\
=&\lim_{\xi\to x}P(\xi,y)&\xi\in[x,x+\Delta x]\\
=&P(x,y)\\
\end{aligned}

同理可证 $\frac{\partial U(x,y)}{\parital y}=Q(x,y)$ 

***** 证明结论

由于 $P(x,y),Q(x,y)$ 在 $(x,y)\in D$ 上有连续偏导，故连续

由于 $\frac{\partial U(x,y)}{\parital x}=P(x,y), \frac{\partial U(x,y)}{\parital y}=Q(x,y)$ 故 $U(x,y)$ 有连续偏导

则根据[[~/文档/note/数学分析/Chap12Note.org][偏导数与全微分-可微条件]]得出 $U(x,y)$ 可微，

根据[[~/文档/note/数学分析/Chap12Note.org][偏导数与全微分-欧几里得空间连续，可导，可微及方向导数关系-可微与偏导]]得出全微分 $dU=P(x,y)dx+Q(x,y)dy$

**** 条件（3）推出条件（4）

根据条件（3） $\frac{\partial P(x,y)}{\partial x}=\frac{\partial^2 U(x,y)}{\partial x\parital y},\frac{\partial Q(x,y)}{\partial x}=\frac{\partial^2 U(x,y)}{\partial y\parital x}$

由于 $\frac{\partial P(x,y)}{\partial y},\frac{\partial Q(x,y)}{\partial x}$ 连续，故 $U(x,y)$ 存在二次混合偏导数，且偏导数在 $(x,y)\in D$ 上连续。

故根据[[~/文档/note/数学分析/Chap12Note.org][偏导数与全微分-高阶偏导数-二次混合偏导顺序]] $\frac{\partial P(x,y)}{\partial x}=\frac{\partial^2 U(x,y)}{\partial x\parital y}=\frac{\partial^2 U(x,y)}{\partial y\parital x}=\frac{\partial Q(x,y)}{\partial x}$

**** 条件（4）推出条件（1）

由于 $D$ 为[[MK40][单连通区域]]，且函数 $P(x,y),Q(x,y)$ 在区域 $D$ 上有连续偏导，

若假定 $L$ 为闭合区间，围成单连通区域 $D_L$ ，故根据[[MK16][Green公式]] $\int_L P(x,y)dx+Q(x,y)dy=\iint_{D_L} \left(\frac{\partial Q(x,y)}{\partial x}-\frac{\partial P(x,y)}{\partial y}\right)dxdy$

又根据条件（4） $\frac{\partial P(x,y)}{\partial y}=\frac{\partial Q(x,y)}{\partial x}\Rightarrow\iint_{D_L} \left(\frac{\partial Q(x,y)}{\partial x}-\frac{\partial P(x,y)}{\partial y}\right)dxdy=0$ 

若闭合曲线 $L$ 围成的区域不为单连通，可将其分段处理（有限段）

** Gauss公式

若满足以下条件

（1） （有限分片）光滑闭合曲面 $\partial D$ 包含区域为[[MK41][二维单连通区域]] $D\in R^3$ 

（2） 函数 $P(x,y,z),Q(x,y,z),R(x,y,z)$ 在 $(x,y,z)\in D$ 上有定义且偏导数连续

（3） 第二类曲面积分方向为闭合曲面外侧

（4） 区域 $D$ 可用（有限分片）光滑曲面切分成有限个[[MK17][标准区域]]

则有 $$\iint_{\partial D}P(x,y,z)dydz+Q(x,y,z)dzdx+R(x,y,z)dxdy=\iiint_D\frac{\partial P(x,y,z)}{\partial x}+\frac{\partial Q(x,y,z)}{\partial y}+\frac{\partial R(x,y,z)}{\partial z}dxdydz$$

即第二类曲面积分等于偏导数和在闭合曲面包含的空间体的三重积分

*** 证明

**** 先证标准区域

***** 等式右边

根据[[MK17][标准区域定义]] $D=\left\{(x,y,z)\big|z_1(x,y)<z<z_2(x,y),(x,y)\in D_{xy}\right\}$

根据[[~/文档/note/数学分析/Chap14Note.org][重积分性质与计算-重积分计算-不规则区域上重积分]] 

$$\iiint_D\frac{\partial R(x,y,z)}{\partial z}dxdydz=\iint_{D_{xy}}\left\{\int_{z_1(x,y)}^{z_2(x,y)}\frac{\partial R(x,y,z)}{\partial z}dz\right\}dxdy$$

根据条件 $\frac{\partial R(x,y,z)}{\partial z}$ 则根据[[~/文档/note/数学分析/Chap7Note.org][牛顿莱布尼茨公式]]可得定积分 $\int_{z_1(x,y)}^{z_2(x,y)}\frac{\partial R(x,y,z)}{\partial z}dz=R(x,y,z_2(x,y))-R(x,y,z_1(x,y))$

故有 $$\iiint_D\frac{\partial R(x,y,z)}{\partial z}dxdydz=\iint_{D_{xy}}\left\{R(x,y,z_2(x,y))-R(x,y,z_1(x,y))\right\}dxdy$$

***** 等式左边

根据标准区域定义，可将 $\partial D$ 分为两个曲面 $\partial D_1=\left\{(x,y,z)\big|z_1(x,y)=z,(x,y)\in D_{xy}\right\},\partial D_2=\left\{(x,y,z)\big|z_2(x,y)=z,(x,y)\in D_{xy}\right\}$

则有 $\partial D=\partial D_1\cup\partial D_2\Rightarrow \iint_{\partial D}R(x,y,z)dxdy=\iint_{\partial D_1}R(x,y,z)dxdy+\iint_{\partial D_2}R(x,y,z)dxdy$

又由于曲面函数分别可表示为 $z=z_1(x,y),z=z_2(x,y)$ 

根据[[MK18][第二类曲面积分计算]]

$\iint_{\partial D_1}R(x,y,z)dxdy=\pm\iint_{D_{xy}}R(x,y,z_1(x,y))dxdy$

$\iint_{\partial D_2}R(x,y,z)dxdy=\pm\iint_{D_{xy}}R(x,y,z_2(x,y))dxdy$

根据 $z_2(x,y)>z_1(x,y)$ 且方向向外可得 

$\iint_{\partial D_1}R(x,y,z)dxdy=-\iint_{D_{xy}}R(x,y,z_1(x,y))dxdy$

$\iint_{\partial D_2}R(x,y,z)dxdy=+\iint_{D_{xy}}R(x,y,z_2(x,y))dxdy$

故 $\iint_{\partial D}R(x,y,z)dxdy=\iint_{\partial D_{xy}}R(x,y,z_2(x,y))dxdy-\iint_{\partial D_{xy}}R(x,y,z_1(x,y))dxdy$

***** 结论

故有 $$\iiint_D\frac{\partial R(x,y,z)}{\partial z}dxdydz=\iint_{\partial D}R(x,y,z)dxdy$$

同理可证  $$\iiint_D\frac{\partial P(x,y,z)}{\partial x}dxdydz=\iint_{\partial D}P(x,y,z)dydx,\iiint_D\frac{\partial Q(x,y,z)}{\partial y}dxdydz=\iint_{\partial D}Q(x,y,z)dzdx$$

根据[[MK19][第二类曲面积分线性]]以及[[~/文档/note/数学分析/Chap13Note.org][重积分性质与计算-性质-线性]]可得

 $$\iint_{\partial D}P(x,y,z)dydz+Q(x,y,z)dzdx+R(x,y,z)dxdy=\iiint_D\frac{\partial P(x,y,z)}{\partial x}+\frac{\partial Q(x,y,z)}{\partial y}+\frac{\partial R(x,y,z)}{\partial z}dxdydz$$

**** 非标准区域

 对于非标准区域，根据条件（4）可用光滑曲面分割为有限个标准区域，根据[[MK20][方向性]]可得分割面上的第二类曲线积分和为零，故同理定理成立。

*** 推论（体积公式）

$R^3$ 中闭合曲面包含的体积 $$V=\iiint_Ddxdydx$$ 则根据高斯公式，若定义 $P(x,y,z)=x$ 则有 $$\iint_{\partial D}P(x,y,z)dydz=\iint_{\partial D}xdydz=\iiint_Ddxdydx$$

同理 $$V=\iiint_Ddxdydx=\iint_{\partial D}xdydz=\iint_{\partial D}ydzdx=\iint_{\partial D}zdxdy=\frac{1}{3}\iint_{\partial D}xdydz+ydzdx+zdxdy$$

** <<MK37>>Stokes公式

若满足条件：

（1） $R^3$ 曲面 $\Sigma$ （有限分片）光滑

（2） $\Sigma$ 边界为（分段）光滑闭合曲线 $\partial\Sigma$

（3） 函数 $P(x,y,z),Q(x,y,z),R(x,y,z)$ 有连续偏导

（4） 曲线方向和曲面方向组成[[MK21][诱导定向]]

（5） 曲面 $\Sigma$ 可由（有限分段）光滑曲线分割为有限个[[MK23][标准曲面]]

（6） 每个[[MK23][标准曲面]]在所有坐标面的投影均可用光滑曲线分割为有限个[[MK14][二维标准区域]]

则成立 $$\int_{\partial\Sigma}P(x,y,z)dx+Q(x,y,z)dy+R(x,y,z)dz=\iint_\Sigma\left(\frac{\partial R(x,y,z)}{\partial y}-\frac{\partial Q(x,y,z)}{\partial z}\right)dydz+\left(\frac{\partial P(x,y,z)}{\partial z}-\frac{\partial R(x,y,z)}{\partial x}\right)dzdx+\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)dxdy$$

*** 证明

等式分列得 $$\begin{cases}\int_{\partial\Sigma}P(x,y,z)dx=\iint_\Sigma\frac{\partial P(x,y,z)}{\partial z}dzdx-\frac{\partial P(x,y,z)}{\partial y}dxdy\\\int_{\partial\Sigma}Q(x,y,z)dy=\iint_\Sigma\frac{\partial Q(x,y,z)}{\partial x}dxdy-\frac{\partial Q(x,y,z)}{\partial z}dydz\\\int_{\partial\Sigma}R(x,y,z)dz=\iint_\Sigma\frac{\partial R(x,y,z)}{\partial y}dydx-\frac{\partial R(x,y,z)}{\partial x}dzdx\end{cases}$$

下面证明 $$\int_{\partial\Sigma}P(x,y,z)dx=\iint_\Sigma\frac{\partial P(x,y,z)}{\partial z}dzdx-\frac{\partial P(x,y,z)}{\partial y}dxdy$$

**** 证明标准区域

***** 转换为二维第二类曲线积分

根据[[MK23][标准曲面定义]] $z=z(x,y)$ 则根据[[MK22][定义]] $\int_{\partial\Sigma}P(x,y,z)dx=\int_{\partial\Sigma}P(x,y,z(x,y))dx=\lim_{\lambda\to0}\sum_{i=1}^n P(x_i,y_i,z(x_i,y_i))\cos(\alpha_x(x_i,y_i))\Delta s_i$

又根据[[MK25][微分形式]] $\lim_{\lambda\to0}\sum_{i=1}^n P(x_i,y_i,z(x_i,y_i))\cos(\alpha_x(x_i,y_i))\Delta s_i=\lim_{\lambda\to0}\sum_{i=1}^n P(x_i,y_i,z(x_i,y_i))\Delta x_i$

其中 $\alpha_x(x_i,y_i)$ 为曲线 $\partial\Sigma$ 在 $(x_i,y_i,z(x_i,y_i))$ 点切向量与 $x$ 轴正方向的夹角，切向量方向与曲线方向一致

定义曲线 $\partial\Sigma$ 在 $xy$ 平面的投影为 $\partial D_{xy}$ 构造二维第二类曲线积分 $\int_{\partial D_{xy}}P(x,y,z(x,y))dx$ 

同理根据定义 $\int_{\partial D_{xy}}P(x,y,z(x,y))dx=\lim_{\lambda\to0}\sum_{i=1}^nP(x_i,y_i,z(x_i,y_i))\cos(\alpha'_x(x_i,y_i))\Delta s'_i$ 

同理 $\alpha'_x(x_i,y_i)$ 为曲线 $\partial D_{xy}$ 在 $(x_i,y_i)$ 点切向量与 $x$ 轴正方向的夹角，切向量方向与曲线方向一致，

且根据[[MK25][微分形式]]有 $\lim_{\lambda\to0}\sum_{i=1}^nP(x_i,y_i,z(x_i,y_i))\cos(\alpha'_x(x_i,y_i))\Delta s'_i=\lim_{\lambda\to0}\sum_{i=1}^n P(x_i,y_i,z(x_i,y_i))\Delta x'_i$

由于 $\partial D_{xy}$ 是 $\partial\Sigma$ 的投影，且任意 $(x_i,y_i,z(x_i,y_i))$ 皆有对应 $(x_i,y_i)$ 故 $\Delta x_i=\Delta x'_i$ 

故有 $\int_{\partial D_{xy}}P(x,y,z(x,y))dx=\int_{\partial\Sigma}P(x,y,z)dx$ 

***** 调用Green公式转化为平面曲面积分

根据现有条件：

（1） 由于光滑曲面，故 $\frac{\partial f(x,y)}{\partial x},\frac{\partial f(x,y)}{\partial y}$ 偏导数存在且连续，又因为 $P(x,y,z)$ 一阶偏导存在且连续故 $P(x,y,z(x,y))$ 一阶偏导亦存在且连续

（2） 由于 $\partial D_{xy}$ 为光滑曲线投影，故亦为光滑。

（3） 根据条件（6） $D_{xy}$ 可由光滑曲线分割为有限个限个[[MK14][二维标准区域]]

故根据Green公式得 $\int_{\partial D_{xy}}P(x,y,z(x,y))dx=-\int_{\partial D_{xy}}\frac{\partial P(x,y,z(x,y))}{\partial y}dx$

又根据[[~/文档/note/数学分析/Chap12Note.org][多元复合函数求导-链式法则]]  $\int_{\partial D_{xy}}P(x,y,z(x,y))dx=-\int_{D_{xy}}\left[\frac{\partial P(x,y,z(x,y))}{\partial y}+\frac{\partial P(x,y,z(x,y))}{\partial z}\frac{\partial z(x,y)}{dy}\right]dxdy$

***** 转化为空间曲面积分

根据[[MK26][第二类曲面积分微分形式]]有 $-\int_{D_{xy}}\left[\frac{\partial P(x,y,z(x,y))}{\partial y}+\frac{\partial P(x,y,z(x,y))}{\partial z}\frac{\partial z(x,y)}{dy}\right]dxdy=\pm\int_\Sigma\left[\frac{\partial P(x,y,z(x,y))}{\partial y}+\frac{\partial P(x,y,z(x,y))}{\partial z}\frac{\partial z(x,y)}{dy}\right]dxdy$

根据[[MK21][诱导定向]]，若曲面方向取上侧，故 $dxdy$ 不变号，曲线方向则取逆时针，则 $-\int_{D_{xy}}\left[\frac{\partial P(x,y,z(x,y))}{\partial y}+\frac{\partial P(x,y,z(x,y))}{\partial z}\frac{\partial z(x,y)}{dy}\right]dxdy=-\int_\Sigma\left[\frac{\partial P(x,y,z(x,y))}{\partial y}+\frac{\partial P(x,y,z(x,y))}{\partial z}\frac{\partial z(x,y)}{dy}\right]dxdy$

反之根据[[MK15][曲线方向性]]和[[MK20][曲面方向性]]可得两者均取负，则等式仍然成立

故有 $\int_{\partial\Sigma}P(x,y,z)dx=\int_\Sigma\left[\frac{\partial P(x,y,z(x,y))}{\partial y}+\frac{\partial P(x,y,z(x,y))}{\partial z}\frac{\partial z(x,y)}{dy}\right]dxdy$

***** 证明结论

根据[[MK23][标准曲面定义]] $z=z(x,y)\Rightarrow F(x,y,z)=z-z(x,y)=0$ 

则根据[[~/文档/note/数学分析/Chap12Note.org][偏导数几何应用-空间平面-法向量，法线方程，法平面-曲面一般表述-求法]]法向量为 $(F_x,F_y,F_z)=\left(-\frac{\partial z(x,y)}{\partial x},-\frac{\partial z(x,y)}{\partial y},1\right)=\left(\cos(\alpha_x),\cos(\alpha_y),\cos(\alpha_z)\right)$

故有 $\frac{\cos(\alpha_y)}{\cos(\alpha_z)}=-\frac{\partial z(x,y)}{\partial y}$ ，故根据[[MK26][第二类曲面积分微分形式]] 

\begin{aligned}
\int_{\partial\Sigma}P(x,y,z)dx=&-\int_\Sigma\left[\frac{\partial P(x,y,z(x,y))}{\partial y}+\frac{\partial P(x,y,z(x,y))}{\partial z}\frac{\partial z(x,y)}{dy}\right]dxdy\\
=&-\int_\Sigma\left[\frac{\partial P(x,y,z(x,y))}{\partial y}+\frac{\partial P(x,y,z(x,y))}{\partial z}\frac{\partial z(x,y)}{dy}\right]\cos(\alpha_z)dS\\
=&-\int_\Sigma\frac{\partial P(x,y,z(x,y))}{\partial z}\frac{\partial z(x,y)}{dy}\cos(\alpha_z)dS-\int_\Sigma\frac{\partial P(x,y,z(x,y))}{\partial y}dxdy\\
=&\int_\Sigma\frac{\partial P(x,y,z(x,y))}{\partial z}\frac{\cos(\alpha_y)}{\cos(\alpha_z)}\cos(\alpha_z)dS-\int_\Sigma\frac{\partial P(x,y,z(x,y))}{\partial y}dxdy\\
=&\int_\Sigma\frac{\partial P(x,y,z(x,y))}{\partial z}\cos(\alpha_y)dS-\int_\Sigma\frac{\partial P(x,y,z(x,y))}{\partial y}dxdy\\
=&\int_\Sigma\frac{\partial P(x,y,z(x,y))}{\partial z}dzdx-\int_\Sigma\frac{\partial P(x,y,z(x,y))}{\partial y}dxdy\\
\end{aligned}

同理可证另外两项。

故得 $$\int_{\partial\Sigma}P(x,y,z)dx+Q(x,y,z)dy+R(x,y,z)dz=\iint_\Sigma\left(\frac{\partial R(x,y,z)}{\partial y}-\frac{\partial Q(x,y,z)}{\partial z}\right)dydz+\left(\frac{\partial P(x,y,z)}{\partial z}-\frac{\partial R(x,y,z)}{\partial x}\right)dzdx+\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)dxdy$$

**** 非标准区域

根据条件（5），可将非标准区域以（有限分段）光滑曲线分割为有限个标准曲面，根据[[MK15][方向性]]可得分割线上的第二类曲线积分和为零，故同理定理成立。

*** 不同公式形式

\begin{aligned}
&\iint_\Sigma\left|\begin{matrix}dydz&dzdx&dxdy\\\frac{\partial}{\partial x}&\frac{\partial}{\partial x}&\frac{\partial}{\partial x}\\P(x,y,z)&Q(x,y,z)&R(x,y,z)\end{matrix}\right|
=\iint_\Sigma\left|\begin{matrix}\cos(\alpha_x)&\cos(\alpha_y)&\cos(\alpha_z)\\\frac{\partial}{\partial x}&\frac{\partial}{\partial x}&\frac{\partial}{\partial x}\\P(x,y,z)&Q(x,y,z)&R(x,y,z)\end{matrix}\right|dS\\
=&\iint_\Sigma\left(\frac{\partial R(x,y,z)}{\partial y}-\frac{\partial Q(x,y,z)}{\partial z}\right)dydz+\left(\frac{\partial P(x,y,z)}{\partial z}-\frac{\partial R(x,y,z)}{\partial x}\right)dzdx+\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)dxdy
\end{aligned}

* 微分形式

** 有向面积与向量外积

*** 定义外积

两个向量 $\vec{a},\vec{b}\in R^2$ 的外加表示为 $\vec{a}\wedge\vec{b}$ 其结果的绝对值为 $\left|\vec{a}\wedge\vec{b}\right|=\sin\theta |\vec{a}||\vec{b}|$ 其中：

（1） $\sin\theta$ 为向量 $\vec{a}$ 旋转到 $\vec{b}$ 的夹角

（2） $|\vec{a}|$ 为向量 $\vec{a}$ 的模长

当 $\vec{a},\vec{b}\in R^2$ 时，若 $\vec{a}$ 到 $\vec{b}$ 旋转为顺时针，结果为负，反之为正。

当 $\vec{a},\vec{b}\in R^3$ 时，若满足右手定则，结果为负，反之为正。

更高为的情况正负没有定义。

*** 向量外积性质

**** 反对称性

$\vec{a}\wedge\vec{b}=-\vec{b}\wedge\vec{a}$

定义触发可证

**** 相同向量外积为零

$\vec{a}\wedge\vec{a}=0$

$\vec{a}\wedge\vec{a}=-\vec{a}\wedge\vec{a}\Rightarrow 2\vec{a}\wedge\vec{a}=0$

**** 分配率

当 $\vec{a},\vec{b},\vec{c}\in R^2$ 时

$\vec{a}\wedge(\vec{b}+\vec{c})=\vec{a}\wedge\vec{b}+\vec{a}\wedge\vec{c}$

$(\vec{b}+\vec{c})\wedge\vec{a}=\vec{b}\wedge\vec{a}+\vec{c}\wedge\vec{a}$

***** 证明

$|\vec{a}|=\sqrt{\sum_{i=1}^n a_i^2}$ 则有 $\left|\vec{a}\wedge(\vec{b}+\vec{c})\right|=\sqrt{\sum_{i=1}^n a_i^2}\sqrt{\sum_{i=1}^n (b_i+c_i)^2}\sin\theta$ 且

\begin{aligned}
\left|\vec{a}\wedge\vec{b}\right|+\left|\vec{a}\wedge\vec{c}\right|&=\sin\theta_1\sqrt{\sum_{i=1}^n a_i^2}\sqrt{\sum_{i=1}^n b_i^2}+\sin\theta_2\sqrt{\sum_{i=1}^n a_i^2}\sqrt{\sum_{i=1}^n c_i^2}\\
&=\sqrt{\sum_{i=1}^n a_i^2}\left\{\sin\theta_1\sqrt{\sum_{i=1}^n b_i^2}+\sin\theta_2\sqrt{\sum_{i=1}^n c_i^2}\right\}
\end{aligned}

由于在平面上，均为投影在与 $\vec{a}$ 垂直的直线上的有向线段长度，故 $\sin\theta_1\sqrt{\sum_{i=1}^n b_i^2}+\sin\theta_2\sqrt{\sum_{i=1}^n c_i^2}=\sqrt{\sum_{i=1}^n (b_i+c_i)^2}\sin\theta$

**** 数乘

$(\lambda\vec{a})\wedge\vec{b}=\vec{a}\wedge(\lambda\vec{b})=\lambda(\vec{a}\wedge\vec{b})$

定义可证

*** 有向面积与雅克比行列式

设 $\vec{e}_1,\vec{e}_2\in R^2$ 为向量空间的基，有 $\vec{a}_1=a_{11}\vec{e}_1+a_{12}\vec{e}_2,\vec{a}_2=a_{21}\vec{e}_1+a_{22}\vec{e}_2$

则有:

\begin{aligned}
\vec{a}_1\wedge\vec{a}_1&=(a_{11}\vec{e}_1+a_{12}\vec{e}_2)\wedge(a_{21}\vec{e}_1+a_{22}\vec{e}_2)\\
&=a_{11}\vec{e}_1\wedge a_{22}\vec{e}_2 + a_{12}\vec{e}_2\wedge a_{21}\vec{e}_1\\
&=(a_{11}a_{22}-a_{12}a_{21})\vec{e}_1\wedge\vec{e}_2\\
&=\left|\begin{matrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{matrix}\right|\vec{e}_1\wedge\vec{e}_2\\
\end{aligned}

** 微分形式

对于 $R^n$ 空间下有 $U\in R^n$ 是 $n$ 维欧式空间的子区域 

定义 $C^1(U)$ 为所有在 $U$ 上具有连续一阶偏导数的函数全体

定义微分的外积 $dx_1\wedge dx_2\wedge....\wedge dx_n$ 为 $R^n$ 下的有向体积微元

且有如下性质

（1） <<MK32>> $dx_i\wedge dx_j=-dx_j\wedge dx_i$

（2） $dx_i\wedge dx_i=-dx_i\wedge dx_i\Rightarrow dx_i\wedge dx_i=0$

（3） $(dx_i\wedge dx_j)\wedge dx_k=dx_i\wedge (dx_j\wedge dx_k)$ 由于面积相同且左右顺序不变

*** 微分形式定义

**** 1 - 形式

将 $dx_1,...,dx_n$ 视为一组基，则其线性组合为 $\sum_{i=1}^n a_i(\vec{x})dx_i, a_i(\vec{x})\in C^1(U)$ 称为一次微分形式，简称“1 - 形式”

1 - 形式的全体称为 $\Lambda^1$ ，维数为 $C^1_n=n$

***** <<MK44>>定义向量空间

****** 加法

若 $\omega=\sum_{i=1}^n a_i(\vec{x})dx_i,\eta=\sum_{i=1}^n b_i(\vec{x})dx_i\in\Lambda^1$ 则定义 $\omega+\eta=\sum_{i=1}^n \left(a_i(\vec{x})+b_i(\vec{x})\right)dx_i$

****** 数乘

若 $\omega=\sum_{i=1}^n a_i(\vec{x})dx_i\in\Lambda^1,\lambda(\vec{x})\in C^1(U)$ 则定义 $\lambda\omega=\sum_{i=1}^n \lambda(\vec{x})a_i(\vec{x})dx_i$ 

****** 零元

若 $\omega=\sum_{i=1}^n 0dx_i\in\Lambda^1,\lambda(\vec{x})\in C^1(U)$ 则定义 $\omega$ 为；零元 

****** 负元

若 $\omega=\sum_{i=1}^n a_i(\vec{x})dx_i\in\Lambda^1,\lambda(\vec{x})\in C^1(U)$ 则定义 $\eta=\sum_{i=1}^n -a_i(\vec{x})dx_i\in\Lambda^1,\lambda(\vec{x})\in C^1(U)$ 为 $\omega$ 的负元，即 $\omega+\eta$ 为零元 

**** k - 形式

由于定义（1）（2），则 k - 形式的基 $dx_{i_1}\wedge dx_{i_2}\wedge...\wedge dx_{i_k}$ 必为有序唯一外积，不妨定义 $i_1<i_2<...<i_n$

故线性组合 $\sum_{i_u\ne i_v,i_1<i_2<...<i_n}^n a_{i_1,i_2,...,i_k}(\vec{x})dx_{i_1}\wedge dx_{i_2}\wedge...\wedge dx_{i_k}, a_i(\vec{x})\in C^1(U)$ 称为 k 次微分形式，简称“k - 形式”

k - 形式的全体称为 $\Lambda^k$ ，维数为 $C^k_n$ 同理根据[[MK44][1 - 形式向量空间]]定义向量空间

**** 0 - 形式

基为 $1$ ，故线性组合为 $a(\vec{x})$

0 - 形式的全体称为 $\Lambda^0$ ，维数为 $C^0_n=1$ 同理根据[[MK44][1 - 形式向量空间]]定义向量空间

**** 微分形式推广定义

定义 $\Lambda=\sum_{i=1}^n \Lambda^i$ 则 $\Lambda$ 的维数是 $\sum_{i=1}^n C_n^i=2^n$ 基为 $\Lambda^0,...,\Lambda^n$ 中的全体基

*** 微分形式外积

**** 定义

（1） 若 $dx_I=dx_{i_1}\wedge dx_{i_2}\wedge...\wedge dx_{i_p},dx_J=dx_{j_1}\wedge dx_{j_2}\wedge...\wedge dx_{j_p}$ 则 $dx_I\wedge dx_J=dx_{i_1}\wedge dx_{i_2}\wedge...\wedge dx_{i_p}\wedge dx_{j_1}\wedge dx_{j_2}\wedge...\wedge dx_{j_p}$

（2） 若 $\omega=\sum_I a_I(\vec{x})dx_I,\eta=\sum_J b_J(\vec{x})dx_J$ 则有 $\omega\wedge\eta=\sum_{I,J} a_i(\vec{x})b_J(\vec{x})dx_Idx_J$

（3） 若 $\omega=\sum_I a_I(\vec{x})dx_I,f(\vec{x})\in\Lambda^0$ 则有 $f(\vec{x})\wedge\omega=f(\vec{x})\omega=\sum_I f(\vec{x})dx_I$

**** 性质

***** 性质1

若 $\omega\in\Labmda^p,\eta\in\Lambda^q$ 且 $p+q>n$ 则 $\omega\wedge\eta=0$

****** 证明

若 $\omega=\sum_I a_I(\vec{x})dx_I,\eta=\sum b_J(\vec{x})dx_J$ 则根据定义（1）（2）有 $\omega\wedge\eta=\sum_{I,J} a_i(\vec{x})b_J(\vec{x})dx_Idx_J$ 其中 $dx_I\wedge dx_J=dx_{i_1}\wedge dx_{i_2}\wedge...\wedge dx_{i_p}\wedge dx_{j_1}\wedge dx_{j_2}\wedge...\wedge dx_{j_p}$

由于 $p+q>n$ 则 $dx_I\wedge dx_J$ 中必有重复元素，根据 $dx_i\wedge dx_i=0$ 则有 $dx_I\wedge dx_J=0$ 故 $\omega\wedge\eta=0$

***** 性质2

若 $\omega\in\Labmda^p,\eta\in\Lambda^q$ 则 $\omega\wedge\eta=(-1)^{pq}\eta\wedge\omega$

****** 证明

若 $\omega=\sum_I a_I(\vec{x})dx_I\in\Lambda^p,\eta=\sum b_J(\vec{x})dx_J\in\Lambda^q$ 则根据定义（1）（2）有 $\omega\wedge\eta=\sum_{I,J} a_i(\vec{x})b_J(\vec{x})dx_Idx_J$ 其中 $dx_I\wedge dx_J=dx_{i_1}\wedge dx_{i_2}\wedge...\wedge dx_{i_p}\wedge dx_{j_1}\wedge dx_{j_2}\wedge...\wedge dx_{j_p}$

根据 $dx_i\wedge dx_j=-dx_j\wedge dx_i$ 结果中 $dx_{i_1}\wedge dx_{i_2}\wedge...\wedge dx_{i_p}\wedge dx_{j_1}\wedge dx_{j_2}\wedge...\wedge dx_{j_p}$ 经历 $p*q$ 次换位成为 $dx_{j_2}\wedge...\wedge dx_{j_p}\wedge dx_{i_1}\wedge dx_{i_2}\wedge...\wedge dx_{i_p}$

故 $dx_I\wedge dx_J=(-1)^{pq}dx_J\wedge dx_I$ 则有  $\omega\wedge\eta=\sum_{I,J} a_i(\vec{x})b_J(\vec{x})dx_Idx_J=(-1)^{pq}\sum_{I,J} a_i(\vec{x})b_J(\vec{x})dx_Jdx_I=\eta\wedge\omega$

****** 推论

若 $\omega=\sum_I a_I(\vec{x})dx_I\in\Lambda^p$ 则当 $p$ 为奇数时 $\omega\wedge\omega=-\omega\wedge\omega\Rightarrow\omega\wedge\omega=0$ 

***** <<MK29>>性质3（分配率）

若 $\omega=\sum_I a_I(\vec{x})dx_I\in\Lambda^p,\eta=\sum b_J(\vec{x})dx_J\in\Lambda^q,\sigma=\sum_K c_K(\vec{x})dx_K\in\Lambda^r$ 则有 $(\omega+\eta)\wedge\sigma=\omega\wedge\sigma+\eta\wedge\sigma$

****** 证明 

\begin{aligned}
(\omega+\eta)\wedge\sigma&=\left(\sum_I a_I(\vec{x})dx_I+\sum_J b_J(\vec{x})dx_J\right)\wedge\sum_K c_K(\vec{x})dx_K\\
&=\sum_{I,K} a_I(\vec{x})dx_Ic_K(\vec{x})dx_K+\sum_{J,K} b_J(\vec{x})dx_J c_K(\vec{x})dx_K\\
&=\omega\wedge\sigma+\eta\wedge\sigma\\
\end{aligned}

***** 性质4（结合律）

若 $\omega=\sum_I a_I(\vec{x})dx_I\in\Lambda^p,\eta=\sum b_J(\vec{x})dx_J\in\Lambda^q,\sigma=\sum_K c_K(\vec{x})dx_K\in\Lambda^r$ 则有 $(\omega\wedge\eta)\wedge\sigma=\omega\wedge(\eta\wedge\sigma)$

****** 证明

\begin{aligned}
(\omega\wedge\eta)\wedge\sigma&=\left(\sum_{I,J} a_I(\vec{x})dx_Ib_J(\vec{x})dx_J\right)\wedge\sum_K c_K(\vec{x})dx_K\\
&=\sum_{I,J,K} a_I(\vec{x})dx_Ib_J(\vec{x})dx_Jc_K(\vec{x})dx_K\\
&=\left\{\sum_I a_I(\vec{x})dx_I\right\}\wedge\left\{\sum_{J,K} b_J(\vec{x})dx_Jc_K(\vec{x})dx_K\right\}\\
&=\omega\wedge(\eta\wedge\sigma)\\
\end{aligned}

*** 微分形式的变量代换

若 $\vec{y}=\vec{f}(\vec{x})$ 即 $\begin{cases}y_1=f_1(x_1,x_2,...,x_n)\\y_2=f_2(x_1,x_2,...,x_n)\\...\\y_n=f_n(x_1,x_2,...,x_n)\end{cases}$ 且 $f_i(\vec{x})\in C^1(U)$ 则根据[[~/文档/note/数学分析/Chap12Note.org][偏导数与全微分-可微条件]]函数 $f_i(\vec{x})$ 在定义域上可微

则有 $\begin{cases}dy_1=\frac{\partial f_1(\vec{x})}{\partial x_1}dx_1+\frac{\partial f_1(\vec{x})}{\partial x_2}dx_2+....+\frac{\partial f_1(\vec{x})}{\partial x_n}dx_n\\dy_2=\frac{\partial f_2(\vec{x})}{\partial x_1}dx_1+\frac{\partial f_2(\vec{x})}{\partial x_2}dx_2+....+\frac{\partial f_2(\vec{x})}{\partial x_n}dx_n\\...\\dy_n=\frac{\partial f_n(\vec{x})}{\partial x_1}dx_1+\frac{\partial f_n(\vec{x})}{\partial x_2}dx_2+....+\frac{\partial f_n(\vec{x})}{\partial x_n}dx_n\end{cases}$ 

则有 $dy_1\wedge dy_2\wedge...\wedge dy_n=\left\{\frac{\partial f_1(\vec{x})}{\partial x_1}dx_1+\frac{\partial f_1(\vec{x})}{\partial x_2}dx_2+....+\frac{\partial f_1(\vec{x})}{\partial x_n}dx_n\right\}\wedge...\wedge \left\{\frac{\partial f_n(\vec{x})}{\partial x_1}dx_1+\frac{\partial f_n(\vec{x})}{\partial x_2}dx_2+....+\frac{\partial f_n(\vec{x})}{\partial x_n}dx_n\right\}$

由于 $dx_i\wedge dx_i=0$ 且 $dx_i\wedge dx_j=-dx_j\wedge dx_i$ 故乘积为 $\sum(-1)^k\frac{\partial f_{k_1}(\vec{x})}{\partial x_{k_1}}\frac{\partial f_{k_2}(\vec{x})}{\partial x_{k_2}}...\frac{\partial f_{k_n}(\vec{x})}{\partial x_{k_n}}$ 其中 $k_1,k_2,...,k_n$ 是 $1,2,...,n$ 的元素次序交换 $k$ 次得到的序列

故 $\sum(-1)^k\frac{\partial f_{k_1}(\vec{x})}{\partial x_{k_1}}\frac{\partial f_{k_2}(\vec{x})}{\partial x_{k_2}}...\frac{\partial f_{k_n}(\vec{x})}{\partial x_{k_n}}=\det\left(\frac{\partial \vec{f}(\vec{x})}{\partial\vec{x}}\right)$

最终 $dy_1\wedge dy_2\wedge...\wedge dy_n=\det\left(\frac{\partial \vec{f}(\vec{x})}{\partial\vec{x}}\right)dx_1\wedge dx_2\wedge...\wedge dx_n$
** 外微分

*** 定义符号

定义 $\Lambda_{i=1}^n dx_i=dx_i\wedge dx_2\wedge...\wedge dx_n$

*** <<MK28>>定义1

若函数 $g(\vec{x}),\vec{x}\in U\subset R^n$ ，设 $\omega=\sum\left\{\frac{\partial^k g(\vec{x})}{\prod_{j=1}^k\partial x_{i_j}}\Lambda_{j=1}^k dx_{i_j}\right\}$ ，则 $d\omega=\sum\left\{\left[\sum_{u=1}^n\frac{\partial}{\parital x_u}\left(\frac{\partial^k g(\vec{x})}{\prod_{j=1}^k\partial x_{i_j}}\right)dx_u\right]\wedge\Lambda_{j=1}^kdx_{i_j}\right\}$

*** <<MK31>>定义2

若 $\omega=\Lambda_{j=1}^k dx_{i_j}$ 则 $d\omega=0$

*** <<MK30>>定义3

若 $\omega=\sum_{j=1}^k\omega_{i_j}$ , 其中 $\omega_{i_j}\in\Lambda_{i_j}$ 则有 $d\omega=\sum_{j=1}^kd\omega_{i_j}$ 即线性性

*** 性质

**** <<MK33>>性质1

若 $\omega\in\Lambda^k,\eta\in\Lambda^l$ 则有 $d(\omega\wedge\eta)=d\omega\wedge\eta+(-1)^k\omega\wedge d\eta$

***** 证明

若 $\omega=a(\vec{x})\Lambda_{u=1}^k dx_{i_u}, \eta=b(\vec{x})\Lambda_{u=1}^l dx_{j_u}$ 则 $\omega\wedge\eta=a(\vec{x})\Lambda_{u=1}^kdx_{i_u}\wedge b(\vec{x})\Lambda_{u=1}^ldx_{j_u}=a(\vec{x})b(\vec{x})\Lambda_{u=1}^kdx_{i_u}\wedge\Lambda_{u=1}^ldx_{j_u}$

故根据[[MK28][定义1]]及[[MK29][分配率]]有：

\begin{aligned}
d(\omega\wedge\eta)&=\left\{\sum_{i=1}^n\frac{\partial [a(\vec{x})b(\vec{x})]}{dx_i}dx_i\right\}\wedge\Lambda_{u=1}^kdx_{i_u}\wedge\Lambda_{u=1}^ldx_{j_u}\\
&=\left\{\sum_{i=1}^n\left[\frac{\partial a(\vec{x})}{dx_i}b(\vec{x})+a(\vec{x})\frac{\partial b(\vec{x})}{dx_i}\right]dx_i\right\}\wedge\Lambda_{u=1}^kdx_{i_u}\wedge\Lambda_{u=1}^ldx_{j_u}\\
&=\left\{\sum_{i=1}^n\frac{\partial a(\vec{x})}{dx_i}b(\vec{x})dx_i\right\}\wedge\Lambda_{u=1}^kdx_{i_u}\wedge\Lambda_{u=1}^ldx_{j_u}+\left\{\sum_{i=1}^na(\vec{x})\frac{\partial b(\vec{x})}{dx_i}dx_i\right\}\wedge\Lambda_{u=1}^kdx_{i_u}\wedge\Lambda_{u=1}^ldx_{j_u}\\
&=\left\{\left[\sum_{i=1}^n\frac{\partial a(\vec{x})}{dx_i}dx_i\right]\wedge\Lambda_{u=1}^kdx_{i_u}\right\}\wedge \left\{b(\vec{x})\wedge\Lambda_{u=1}^ldx_{j_u}\right\}+(-1)^k\left\{a(\vec{x})\wedge\Lambda_{u=k}^kdx_{i_u}\right\}\wedge\left\{\left[\sum_{i=1}^n\frac{\partial a(\vec{x})}{dx_i}dx_i\right]\wedge\Lambda_{u=1}^ldx_{j_u]\right\}\\
&=d\omega\wedge\eta+(-1)^k\omega\wedge d\eta
\end{aligned}

若 $\omega=\sum_{i=1}^n\omega_i,\eta=\sum_{i=1}^m\eta_i$ 其中 $\omega_i,\eta_i$ 分别有 $a(\vec{x})\Lambda_{u=1}^k dx_{i_u},b(\vec{x})\Lambda_{u=1}^l dx_{i_u}$ 的形式，

则根据[[MK30][定义3]]及[[MK29][分配率]]有：

\begin{aligned}
d(\omega\wedge\eta)=&d\left(\sum_{i=1}^n\sum_{j=1}^m\omega_i\wedge\eta_j\right)\\
=&\sum_{i=1}^n\sum_{j=1}^md(\omega_i\wedge\eta_j)\\
=&\sum_{i=1}^n\sum_{j=1}^m\left[d\omega_i\wedge\eta_j+(-1)^k\omega_i\wedge d\eta_j\right]\\
=&\sum_{i=1}^n\sum_{j=1}^md\omega_i\wedge\eta_j+(-1)^k\sum_{i=1}^n\sum_{j=1}^m\omega_i\wedge d\eta_j\\
=&d\omega\wedge\eta+(-1)^k\omega\wedge d\eta
\end{aligned}

**** <<MK34>>性质2

若 $f(\vec{x})$ 有二阶连续偏导，则外微分 $d^2(f(\vec{x}))=0$

***** 证明

根据[[MK28][定义1]] $d(f(\vec{x}))=\sum_{i=1}^n \frac{\partial f(\vec{x})}{\parital x_i}dx_i$ ，则根据[[MK31][定义3]] $d^2(f(\vec{x}))=d\left(\sum_{i=1}^n \frac{\partial f(\vec{x})}{\parital x_i}dx_i\right)=\sum_{i=1}^n\sum_{j=1}^n \frac{\partial^2 f(\vec{x})}{\partial x_i\partial x_j}dx_i\wedge dx_j$ 

又根据[[MK31][定义2]] $d^2(f(\vec{x}))=\sum_{i\ne j, 0<i\leq n,1<j\leq n}\frac{\partial^2 f(\vec{x})}{\partial x_i\partial x_j}dx_i\wedge dx_j$

又因为 $f(\vec{x})$ 有连续二阶偏导，故根据[[~/文档/note/数学分析/Chap12Note.org][偏导数与全微分-高阶偏导数-二次混合偏导顺序]]得 $\frac{\partial^2 f(\vec{x})}{\partial x_i\partial x_j}=\frac{\partial^2 f(\vec{x})}{\partial x_j\partial x_i}$

故有 $d^2(f(\vec{x}))=\sum_{i<j, 0<i\leq n,1<j\leq n}\left[\frac{\partial^2 f(\vec{x})}{\partial x_i\partial x_j}-\frac{\partial^2 f(\vec{x})}{\partial x_j\partial x_i}\right]dx_i\wedge dx_j=0$

**** 性质3

若 $\omega\in\Lambda^k$ 则 $d^2\omega=0$

***** 证明

若 $\omega=\sum_{i=1}^na_i(\vec{x})\Lambda_{j=1}^kdx_{i_j}$ 则根据[[MK28][定义1]]及[[MK30][定义3]] $d\omega=\sum_{i=1}^nd(a_i(\vec{x}))\wedge \Lambda_{j=1}^kdx_{i_j}$

则同理 $d^2\omega=\sum_{i=1}^n\left\{d^2(a_i(\vec{x}))\wedge\Lambda_{j=1}^kdx_{i_j}+d(a_i(\vec{x}))\wedge d(\Lambda_{j=1}^kdx_{i_j})\right\}$

则根据[[MK34][性质2]]及[[MK31][定义2]] $d^2\omega=\sum_{i=1}^n\left\{0\wedge\Lambda_{j=1}^kdx_{i_j}+d(a_i(\vec{x}))\wedge 0\right\}=0$

*** 应用

**** Green公式

定义 $\omega=P(x,y)dx+Q(x,y)dy,\omega\in\Lambda^1$ 

则 $d\omega=\frac{\partial P(x,y)}{\partial y}dx\wedge dy+\frac{\partial Q(x,y)}{\partial x}dy\wedge dx=\left(\frac{\partial P(x,y)}{\partial y}-\frac{\partial Q(x,y)}{\partial x}\right)dx\wedge dy$

故格林公式可写为 $\int_{\partial D}\omega=\int_{D}d\omega$

**** Gause公式

定义 $\omega=P(x,y,z)dy\wedge dz+Q(x,y,z)dz\wedge dx+R(x,y,z)dx\wedge dy$ 则

\begin{aligned}
d\omega&=\frac{\partial P(x,y,z)}{\partial x}dx\wedge dy\wedge dz+\frac{\partial Q(x,y,z)}{\partial y}dy\wedge dz\wedge dx+\frac{\partial R(x,y,z)}{\partial z}dz\wedge dx\wedge dy\\
&=\left(\frac{\partial P(x,y,z)}{\partial x}+\frac{\partial Q(x,y,z)}{\partial y}+\frac{\partial R(x,y,z)}{\partial z}\right)dx\wedge dy\wedge dz
\end{aligned}

故高斯公式可写为 $\int_{\partial D}\omega=\int_{D}d\omega$

**** Stokes公式

定义 $\omega=P(x,y,z)dx+Q(x,y,z)dy+R(x,y,z)dz$ 则

\begin{aligned}
d\omega&=\left(\frac{\partial P(x,y,z)}{\partial y}dy+\frac{\partial P(x,y,z)}{\partial z}dz\right)\wedge dx+\left(\frac{\partial Q(x,y,z)}{\partial x}dx+\frac{\partial Q(x,y,z)}{\partial z}dz\right)\wedge dy+\left(\frac{\partial R(x,y,z)}{\partial x}dx+\frac{\partial R(x,y,z)}{\partial y}dy\right)\wedge dz\\
=&\left(\frac{\partial R(x,y,z)}{\partial y}-\frac{\partial Q(x,y,z)}{\partial z}\right)dy\wedge dz+\left(\frac{\partial P(x,y,z)}{\partial z}-\frac{\partial R(x,y,z)}{\partial x}\right)dz\wedge dx+\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)dx\wedge dy
\end{aligned}

故斯托克斯公式可写为 $\int_{\partial \Sigma}\omega=\int_{\Simga}d\omega$

* 场论初步

** 哈密尔顿算子

定义 $\nabla=\frac{\partial}{\partial x}\vec{i}+\frac{\partial}{\partial y}\vec{j}+\frac{\partial}{\partial z}\vec{k}$ 则有：

*** 数量场 $f(x,y,z)$ 的梯度为

\begin{aligned}
\nabla f(x,y,z)&=\left(\frac{\partial}{\partial x}\vec{i}+\frac{\partial}{\partial y}\vec{j}+\frac{\partial}{\partial z}\vec{k}\right)f(x,y,z)\\
&=\frac{\partial f(x,y,z)}{\partial x}\vec{i}+\frac{\partial f(x,y,z)}{\partial y}\vec{j}+\frac{\partial f(x,y,z)}{\partial z}\vec{k}
\end{aligned}

*** 向量场 $\vec{a}(x,y,z)=P(x,y,z)\vec{i}+Q(x,y,z)\vec{j}+R(x,y,z)\vec{k}$ 的散度为:

\begin{aligned}
\nabla\cdot\vec{a}(x,y,z)&=\left(\frac{\partial}{\partial x}\vec{i}+\frac{\partial}{\partial y}\vec{j}+\frac{\partial}{\partial z}\vec{k}\right)\cdot\left(P(x,y,z)\vec{i}+Q(x,y,z)\vec{j}+R(x,y,z)\vec{k}\right)\\
&=\frac{\partial P(x,y,z)}{\partial x}+\frac{\partial Q(x,y,z)}{\partial y}+\frac{\partial R(x,y,z)}{\partial z}
\end{aligned}

*** 向量场 $\vec{a}(x,y,z)=P(x,y,z)\vec{i}+Q(x,y,z)\vec{j}+R(x,y,z)\vec{k}$ 的旋度为:

\begin{aligned}
\nabla\times\vec{a}(x,y,z)&=\left(\frac{\partial}{\partial x}\vec{i}+\frac{\partial}{\partial y}\vec{j}+\frac{\partial}{\partial z}\vec{k}\right)\times\left(P(x,y,z)\vec{i}+Q(x,y,z)\vec{j}+R(x,y,z)\vec{k}\right)\\
&=\left(\frac{\partial P(x,y,z)}{\partial z}-\frac{\partial R(x,y,z)}{\partial x}\right)+\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)+\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)
\end{aligned}

** 梯度

*** 基本定义

定义空间 $\Omega\in R^3$ ，函数 $f(x,y,z),(x,y,z)\in\Omega$ 在定义域内有连续一阶导数

则根据[[~/文档/note/数学分析/Chap12Note.org::MK29][定义]]在点 $(x,y,z)$ 上的梯度为 $\nabla f(x,y,z)=\frac{\partial f(x,y,z)}{\partial x}\vec{i}+\frac{\partial f(x,y,z)}{\partial y}\vec{j}+\frac{\partial f(x,y,z)}{\partial z}\vec{k}$

*** 性质及物理意义

对于空间 $\Omega$ 上的数量场函数 $f(x,y,z)$ 来说，梯度方向为函数增长速度最快方向

**** 证明

根据[[~/文档/note/数学分析/Chap12Note.org::MK30][方向导数]]可得方向导数 $\frac{\partial f(x,y,z)}{\partial \vec{v}}=\lim_{t\to 0^+}\frac{f(x+t\cos\alpha_x,y+t\cos\alpha_y,z+t\cos\alpha_z)-f(x,y,z)}{t}$

可定义为沿方向 $\vec{v}=(\cos\alpha_x,\cos\alpha_y,\cos\alpha_z)$ 的函数增长量

又由于 $f(x,y,z)$ 在定义域内有连续一阶导数，则根据[[~/文档/note/数学分析/Chap12Note.org::MK5][可微条件]]，函数可微

又根据[[~/文档/note/数学分析/Chap12Note.org::MK32][可微与方向导数]]得方向导数 

\begin{aligned}
\frac{\partial f(x,y,z)}{\partial \vec{v}}&=\frac{\partial f(x,y,z)}{\partial x}\cos\alpha_x+\frac{\partial f(x,y,z)}{\partial y}\cos\alpha_y+\frac{\partial f(x,y,z)}{\partial z}\cos\alpha_z\\
&=(\cos\alpha_x,\cos\alpha_y,\cos\alpha_z)\cdot\left(\frac{\partial f(x,y,z)}{\partial x},\frac{\partial f(x,y,z)}{\partial y},\frac{\partial f(x,y,z)}{\partial z}\right)\\
&=(\cos\alpha_x,\cos\alpha_y,\cos\alpha_z)\cdot\nabla f(x,y,z)\\
&=\left\|1\right\|\left\|\nabla f(x,y,z)\right\|\cos\theta\\
&=\left\|\nabla f(x,y,z)\right\|\cos\theta\\
\end{aligned}

其中 $\theta$ 为 $\vec{v},\nabla f(x,y,z)$ 之间的夹角，故当 $\theta=0$ 即 $\vec{v}$ 与梯度方向一致时，函数方向导数最大，即沿该方向增长最快。

** 通量

若 $\vec{f}(x,y,z)=P(x,y,z)\vec{i}+Q(x,y,z)\vec{j}+R(x,y,z)\vec{k},\ (x,y,z)\in\Omega\subset R^3$ 为稳定向量场，且 $P(x,y,z),Q(x,y,z),R(x,y,z)$ 有一阶连续偏导

定义 $\Sigma$ 为 $\Omega$ 中的[[MK35][双侧曲面]]，则第二类曲面积分 $\iint_\Sigma \vec{f}(x,y,z)\cdot d\vec{s}$ 为该曲面的通量，为通过该曲面正向的向量总和。

** 散度

*** 定义

若 $\vec{r}=(x_0,y_0,z_0)\in\Omega$ 光滑闭合曲面 $\Sigma$ 包含 $V$ 且 $\vec{r}\in V$ ，被包空间体积为 $mV$ 。

向量场函数 $\vec{f}(x,y,z)$ 在 $\Omega$ 上有定义，曲面 $\Sigma$ 外侧为正

则散度为 $div\vec{f}(x,y,z)=\lim_{V\to \vec{r}}\frac{\iint_\Sigma\vec{f}(x,y,z)d\vec{s}}{mV}$ 为被包含空间 $V$ 收缩到 $\vec{r}$ 点时单位体积曲面积分的极限。

*** 计算

若 $\vec{f}(x,y,z)$ 在 $\Omega$ 有连续偏导，被包含区域 $V$ 可用（有限分片）光滑曲面切分成有限个[[MK17][标准区域]] 

则散度 $div\vec{f}(x,y,z)=\frac{\partial P(x,y,z)}{\partial x}+\frac{\partial Q(x,y,z)}{\partial y}+\frac{\partial R(x,y,z)}{\partial z}$

**** 证明

由于 $\Sigma$ 为光滑闭合曲面，且外侧为正，又根据条件有连续偏导且可用（有限分片）光滑曲面切分成有限个[[MK17][标准区域]]，故满足高斯公式条件。

\begin{aligned}
\iint_\Sigma\vec{f}(x,y,z)d\vec{s}&=\iiint_V\frac{\partial P(x,y,z)}{\partial x}+\frac{\partial Q(x,y,z)}{\partial y}+\frac{\partial R(x,y,z)}{\partial z}dxdydz\\
&=\iiint_V\left(\frac{\partial P(x,y,z)}{\partial x}+\frac{\partial Q(x,y,z)}{\partial y}+\frac{\partial R(x,y,z)}{\partial z}\right)\times 1dxdydz
\end{aligned}

根据定义 $\frac{\partial P(x,y,z)}{\partial x}+\frac{\partial Q(x,y,z)}{\partial y}+\frac{\partial R(x,y,z)}{\partial z}$ 连续 $1$ 不变号

则根据[[~/文档/note/数学分析/Chap13Note.org][重积分性质与计算-性质-积分中值定理]]

\begin{aligned}
\iint_\Sigma\vec{f}(x,y,z)d\vec{s}&=\left(\frac{\partial P(x_1,y_1,z_1)}{\partial x}+\frac{\partial Q(x_1,y_1,z_1)}{\partial y}+\frac{\partial R(x_1,y_1,z_1)}{\partial z}\right)\iiint_Vdxdydz\\
&=\left(\frac{\partial P(x_1,y_1,z_1)}{\partial x}+\frac{\partial Q(x_1,y_1,z_1)}{\partial y}+\frac{\partial R(x_1,y_1,z_1)}{\partial z}\right)mV
\end{aligned}

由于偏导函数连续，故偏导函数的和也连续，故有

\begin{aligned}
&\lim_{V\to\vec{r}}\frac{\iint_\Sigma\vec{f}(x,y,z)d\vec{s}}{mV}\\
=&\lim_{V\to\vec{r}}\frac{\partial P(x_1,y_1,z_1)}{\partial x}+\frac{\partial Q(x_1,y_1,z_1)}{\partial y}+\frac{\partial R(x_1,y_1,z_1)}{\partial z}&\vec{r}_1=(x_1,y_1,z_1)\in V\\
=&\lim_{\vec{r}_1\to\vec{r}}\frac{\partial P(x_1,y_1,z_1)}{\partial x}+\frac{\partial Q(x_1,y_1,z_1)}{\partial y}+\frac{\partial R(x_1,y_1,z_1)}{\partial z}\\
=&\frac{\partial P(x_0,y_0,z_0)}{\partial x}+\frac{\partial Q(x_0,y_0,z_0)}{\partial y}+\frac{\partial R(x_0,y_0,z_0)}{\partial z}
\end{aligned}

** 向量线

*** <<MK36>>定义

设 $\Gamma$ 是空间 $\Omega\in R^3$ 上的一条线， $\vec{a}(x,y,z)=P(x,y,z)\vec{i}+Q(x,y,z)\vec{j}+R(x,y,z)\vec{k}$ 为定义在 $(x,y,z)\in\Omega$ 上的向量场

若 $\Gamma$ 上每一点的切线与向量场方向相同，则称 $\Gamma$ 为该向量场的向量线。

*** 计算

若 $P(x,y,z),Q(x,y,z),R(x,y,z)$ 不同时为零，向量线为满足微分方程组 $\frac{dx}{P(x,y,z)}=\frac{dy}{Q(x,y,z)}=\frac{dz}{R(x,y,z)}$ 的曲线

**** 证明

设曲线参数表示为 $\begin{cases}x=x\\y=y(x)\\z=z(x)\end{cases}$ 且有连续偏导，

则根据[[~/文档/note/数学分析/Chap12Note.org][偏导数几何应用- 空间曲线-光滑曲线切线和切向量]]曲线且向量为 $\left(\frac{dx}{dx},\frac{dy}{dx},\frac{dz}{dx}\right)=\left(1,\frac{dy}{dx},\frac{dz}{dx}\right)$

根据[[MK36][向量线定义]]有 $\frac{dy}{dx}=\frac{Q(x,y,z)}{P(x,y,z)}\Rightarrow\frac{dx}{P(x,y,z)}=\frac{dy}{Q(x,y,z)}$ 同理可证 $\frac{dx}{P(x,y,z)}=\frac{dz}{R(x,y,z)}$

** 环量与旋度

*** 环量定义

向量场 $\vec{a}(x,y,z)=P(x,y,z)\vec{i}+Q(x,y,z)\vec{j}+R(x,y,z)\vec{k}, (x,y,z)\in\Omega\subset R^3$ ，分段光滑闭合曲线 $\Gamma\subset\Omega$ 则称 $\int_\Gamma \vec{a}\cdot d\vec{s}$ 为 $\Gamma$ 的环量。 

*** 旋度定义

点 $M=(x,y,z)\in\Omega$ ，对于给定单位向量 $\vec{n}=(\cos\alpha_x,\cos\alpha_y,\cos\alpha_z)$ 与之垂直的平面上有分段光滑闭合曲线 $\Gamma_{\vec{n}}$ 所围成的面积为 $S_\Gamma$ 。

则有极限 $\lim_{\Gamma_{\vec{n}}\to M}\frac{\int_{\Gamma_{\vec{n}}}\vec{a}\cdot d\vec{s}}{S_\Gamma}$ 定义为环量面密度。设 $\vec{n}_{\max}$ 为某一单位向量使得环量面密度最大，则旋度的方向与 $\vec{n}_{\max}$ 一致，大小与此时的环量面密度一致

*** <<MK42>>旋度计算

若 $P(x,y,z),Q(x,y,z),R(x,y,z)$ 有连续偏导，则点 $(x,y,z)$ 的旋度为 $\left(\frac{\partial P(x,y,z)}{\partial z}-\frac{\partial R(x,y,z)}{\partial x}\right)+\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)+\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)$

**** 证明

***** 前提定义

取 $\vec{n}=(\cos\alpha_x,\cos\alpha_y,\cos\alpha_z)$ 和与之垂直的平面 $\tau$ ，定义 $\partial\Sigma\subset\tau$ 是平面上的光滑闭合曲面，围成的区域为 $\Sigma$ 在该平面为[[MK14][二维标准区域]]。

由于 $\vec{n}$ 为平面 $\tau$ 法向量，故建立一一对应参数表示 $\begin{cases}x=x(u,v)\\y=y(u,v)\\z=z(u,v)\end{cases},(u,v)\in D$ ，由于 $\Sigma$ 在平面上，故必光滑（有连续偏导）且雅克比满秩

则根据[[~/文档/note/数学分析/Chap12Note.org][偏导数几何应用-空间平面-法向量，法线方程，法平面-参数表示平面]]的法量为 $\left(\frac{\partial(y,z)}{\partial(u,v)},\frac{\partial(z,x)}{\partial(u,v)},\frac{\partial(x,y)}{\partial(u,v)}\right)$ 与 $\vec{n}$ 方向一致

则有 $\frac{\partial(y,z)}{\partial(u,v)}=C\cos\alpha_x,\frac{\partial(z,x)}{\partial(u,v)}=C\cos\alpha_y,\frac{\partial(x,y)}{\partial(u,v)}=C\cos\alpha_z$

***** Stokes公式

由于 $\Sigma$ 存在于平面上，则：

（1） 曲面 $\Sigma$ 为[[MK23][标准曲面]]

（2） $\Sigma$ 在坐标面的投影均可用光滑曲线分割为有限个[[MK14][二维标准区域]]

且 $P(x,y,z),Q(x,y,z),R(x,y,z)$ 有连续偏导,则满足[[MK37][Stokes公式]]条件，

定义 $\vec{\psi}(x,y,z)=\left(\left(\frac{\partial P(x,y,z)}{\partial z}-\frac{\partial R(x,y,z)}{\partial x}\right),\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right),\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)\right)$ 

定义 $\vec{\phi}(u,v)=\vec{\psi}(x(u,v),y(u,v),z(u,v))$

再根据[[MK18][第二类曲面积分计算]]：


\begin{aligned}
\int_{\partial\Sigma}\vec{a}\cdot d\vec{s}=&\iint_\Sigma\left(\frac{\partial R(x,y,z)}{\partial y}-\frac{\partial Q(x,y,z)}{\partial z}\right)dydz+\left(\frac{\partial P(x,y,z)}{\partial z}-\frac{\partial R(x,y,z)}{\partial x}\right)dzdx+\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)dxdy\\
=&\iint_DC\left[\left(\frac{\partial R(x(u,v),y(u,v),z(u,v))}{\partial y}-\frac{\partial Q(x(u,v),y(u,v),z(u,v))}{\partial z}\right)\cos\alpha_x+
\left(\frac{\partial P(x(u,v),y(u,v),z(u,v))}{\partial z}-\frac{\partial R(x(u,v),y(u,v),z(u,v))}{\partial x}\right)\cos\alpha_y\right.\\
&\left.+\left(\frac{\partial Q(x(u,v),y(u,v),z(u,v))}{\partial x}-\frac{\partial P(x(u,v),y(u,v),z(u,v))}{\partial y}\right)\cos\alpha_z \right]dudv\\
=&\iint_D C\vec{\phi}(u,v)\cdot\vec{n} dudv\\
\end{aligned}

***** 重积分中值理

由于 $\vec{\phi}(u,v)\cdot\vec{n}$ 连续，故根据[[~/文档/note/数学分析/Chap13Note.org][重积分性质与计算-性质-积分中值定理]]存在 $(u^*,v^*)\in D$ 使得 $\vec{\phi}(u^*,v^*)\cdot\vec{n}\iint_DCdudv=\iint_DC\vec{\phi}(u,v)\cdot\vec{n}dudv$

***** 平面 $\Sigma$ 的面积

由于 $\frac{\partial(y,z)}{\partial(u,v)}=C\cos\alpha_x,\frac{\partial(z,x)}{\partial(u,v)}=C\cos\alpha_y,\frac{\partial(x,y)}{\partial(u,v)}=C\cos\alpha_z$ 且向量 $\vec{n}$ 范数为 $1$

则根据[[MK38][第一类曲面积分计算]]

\begin{aligned}
\iint_\Sigma ds&=\iint_D\left\|\left(\frac{\partial x(u,v)}{\partial u},\frac{\partial y(u,v)}{\partial u},\frac{\partial z(u,v)}{\partial u}\right)\times\left(\frac{\partial x(u,v)}{\partial v},\frac{\partial y(u,v)}{\partial v},\frac{\partial z(u,v)}{\partial v}\right)\right\|dudv\\
=&\iint_D\left\|\left(\frac{\partial(y,z)}{\partial(u,v)},\frac{\partial(z,x)}{\partial(u,v)},\frac{\partial(x,y)}{\partial(u,v)}\right)\right\|dudv\\
=&\iint_DCdudv\\
\end{aligned}

***** 证明结论

故综上所述 $\int_{\partial\Sigma}\vec{a}\cdot d\vec{s}=\vec{\phi}(u^*,v^*)\cdot\vec{n}S_\Gamma$ 其中 $S_\Gamma$ 为分段光滑闭合曲线 $\Gamma$ 所围成的面积

由于一一对应，则必有唯一 $(x^*,y^*,z^*)=(x(u^*,v^*),y(u^*,v^*),z(u^*,v^*))$ 使得 $\vec{\phi}(u^*,v^*)=\vec{\psi}(x^*,y^*,z^*)$

带入得 $\int_{\partial\Sigma}\vec{a}\cdot d\vec{s}=\vec{\psi}(x^*,y^*,z^*)\cdot\vec{n}S_\Gamma$ 

当 $\Sigma\to(x,y,z)$ 时 $(x^*,y^*,z^*)\to(x,y,z)$ 又由于连续偏导，则函数 $\psi(x,y,z)$ 连续

故得 $\lim_{\Sigma\to(x,y,z)}\frac{\int_{\partial\Sigma}\vec{a}\cdot d\vec{s}}{S_\Gamma}=\lim_{\Sigma\to(x,y,z)}\frac{\vec{\psi}(x^*,y^*,z^*)\cdot\vec{n}S_\Gamma}{S_\Gamma}=\lim_{(x^*,y^*,z^*)\to(x,y,z)}\vec{\psi}(x^*,y^*,z^*)=\vec{\psi}(x,y,z)\cdot\vec{n}$
定义 $\theta$ 为向量 $\left(\left(\frac{\partial P(x,y,z)}{\partial z}-\frac{\partial R(x,y,z)}{\partial x}\right),\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right),\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)\right),\vec{n}$ 的夹角

则有 

\begin{aligned}
\lim_{\Sigma\to(x,y,z)}\frac{\int_{\partial\Sigma}\vec{a}\cdot d\vec{s}}{S_\Gamma}&=\left(\left(\frac{\partial P(x,y,z)}{\partial z}-\frac{\partial R(x,y,z)}{\partial x}\right),\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right),\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)\right)\cdot\vec{n}\\
&=\left\|\left(\frac{\partial P(x,y,z)}{\partial z}-\frac{\partial R(x,y,z)}{\partial x}\right),\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right),\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)\right\|\cos(\theta)
\end{aligned}

** 保守场与势函数

*** 定义

**** <<MK44>>有势场和势函数

若向量场 $\vec{a}(x,y,z)=P(x,y,z)\vec{i}+Q(x,y,z)\vec{j}+R(x,y,z)\vec{k}, (x,y,z)\in\Omega\subset R^3$ 满足：

（1） $P(x,y,z),Q(x,y,z),R(x,y,z)$ 在定义域上连续

（2） 存在函数 $U(x,y,z)$ 使得 $\nabla U(x,y,z)=\vec{a}(x,y,z)$

则称向量场为有势场，且函数 $V(x,y,z)=-U(x,y,z)$ 为势函数

**** 保守场

若向量场 $\vec{a}(x,y,z)=P(x,y,z)\vec{i}+Q(x,y,z)\vec{j}+R(x,y,z)\vec{k}, (x,y,z)\in\Omega\subset R^3$ 

在（分段）光滑曲线上的第二类曲线积分 $\int_{\vec{x}_1}^{\vec{x}_2}\vec{a}(x,y,z)\cdot d\vec{s}$ 与积分路径无关，仅与 $\vec{x}_1,\vec{x}_2$ 有关，则称向量场为保守场

*** <<MK45>>定理1

若向量场 $\vec{a}(x,y,z)=P(x,y,z)\vec{i}+Q(x,y,z)\vec{j}+R(x,y,z)\vec{k}, (x,y,z)\in\Omega\subset R^3$ 满足

（1） $\Omega$ 为[[MK39][空间单连通区域]]

（2） 分量函数 $P(x,y,z),Q(x,y,z),R(x,y,z)$ 有连续偏导

则以下4个命题等价：

（1） $\Omega$ 中的（分段）光滑闭合曲线的第二类曲线积分为零

（2） $\vec{a}$ 为保守场

（3） $\vec{a}$ 为有势场

（4） $\vec{a}$ 为无旋场

**** 证明

***** （1） $\Rightarrow$ （2）

定义两点 $\vec{r}_1,\vec{r}_2$ 中任意两条分段光滑曲线 $l_1,l_2$ 形成闭合曲线，根据条件（1）闭合曲线积分为零，即 $\int_{l_1+(-l_2)}\vec{a}(x,y,z)\cdot d\vec{s}=0$

又根据[[MK15][方向性]]和[[MK9][区间可加性]] $\int_{l_1+(-l_2)}\vec{a}(x,y,z)\cdot d\vec{s}=\int_{l_1}\vec{a}(x,y,z)\cdot d\vec{s}+\int_{-l_2}\vec{a}(x,y,z)\cdot d\vec{s}=\int_{l_1}\vec{a}(x,y,z)\cdot d\vec{s}-\int_{l_2}\vec{a}(x,y,z)\cdot d\vec{s}=0$

故有 $\int_{l_1}\vec{a}(x,y,z)\cdot d\vec{s}=\int_{l_2}\vec{a}(x,y,z)\cdot d\vec{s}$

***** <<MK43>>（2） $\Rightarrow$ （3）

定义函数 $U(x,y,z)=\int_{(0,0,0)}^{(x,y,z)}\vec{a}(x,y,z)\cdot d\vec{s}$ 即函数为原点到 $(x,y,z)$ 的第二类曲线积分，由于与路径无关，故可写为 $U(x,y,z)$

定义两点 $(x,y,z),(x+\Delta x,y,z)$ ，定义直线参数表示 $\begin{cases}x=x+t\\y=y\\z=z\end{cases}$ ，其中 $x,y,z$ 均为常数， $t:0\to\Delta x$ 曲线满足

（1） 由于光滑曲线，故有连续偏导

（2） 由于 $x$ 的值一一对应，故参数表示一一对应

（3） $x$ 的偏导数为 $1$ ，其余为零，故偏导数不同时为零。

则根据[[MK12][第二类曲线积分计算]]，[[MK9][区间可加]]以及[[MK15][方向性]]可将曲线积分转化为定积分

\begin{aligned}
U(x+\Delta x,y,z)-U(x,y,z)&=\int_{(0,0,0)}^{(x+\Delta x,y,z)}\vec{a}(x,y,z)\cdot d\vec{s}-\int_{(0,0,0)}^{(x,y,z)}\vec{a}(x,y,z)\cdot d\vec{s}\\
&=\int_{(x,y,z)}^{(x+\Delta x,y,z)}\vec{a}(x,y,z)\cdot d\vec{s}\\
&=\int_{0}^{\Delta x}P(x+t,y,z)dt\\
\end{aligned}

由于 $P(x,y,z)$ 有连续偏导，根据[[~/文档/note/数学分析/Chap12Note.org][偏导数与全微分-可微条件]]与根据[[~/文档/note/数学分析/Chap12Note.org][偏导数与全微分-欧几里得空间连续，可导，可微及方向导数关系]]的出函数连续

故根据[[~/文档/note/数学分析/Chap8Note.org][积分中值定理-第一积分中值定理]]可得 $\int_{0}^{\Delta x}P(x+t,y,z)dt=P(x+\xi,y,z)\int_{0}^{\Delta x}dt=P(x+\xi,y,z)\Delta x$ 其中 $\xi\in[0,\Delta x]$

故根据定义 $U(x,y,z)$ 对于 $x$ 的偏导数为：

\begin{aligned}
\frac{\partial U(x,y,z)}{\partial x}=&\lim_{\Delta x\to0}\frac{U(x+\Delta x,y,z)-U(x,y,z)}{\Delta x}\\
=&\lim_{\Delta x\to0}\frac{P(x+\xi,y,z)\Delta x}{\Delta x} &\xi\in[0,\Delta x]\\
=&\lim_{\Delta x\to0}P(x+\xi,y,z) &\xi\in[0,\Delta x]\\
=&\lim_{\xi\to0}P(x+\xi,y,z)\\
=&\lim_{a\to x}P(a,y,z)\\
=&P(x,y,z)
\end{aligned}

其他分量同理可证。

***** （3） $\Rightarrow$ （4）

根据条件（2）分量函数有连续偏导，故根据[[MK42][旋度计算]]定义 $\nabla\times\vec{a}=\left(\frac{\partial P(x,y,z)}{\partial z}-\frac{\partial R(x,y,z)}{\partial x}\right)+\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)+\left(\frac{\partial Q(x,y,z)}{\partial x}-\frac{\partial P(x,y,z)}{\partial y}\right)$

由于 $\nabla U(x,y,z)=\vec{a}(x,y,z)$ 且根据条件（2），即 $U(x,y,z)$ 有连续二阶偏导

故 $\frac{\partial P(x,y,z)}{\partial z}-\frac{\partial R(x,y,z)}{\partial x}=\frac{\partial^2 U(x,y,z)}{\partial x\partial z}-\frac{\partial^2 U(x,y,z)}{\partial z\partial x}=0$ 其他分量同理为零。

***** （4） $\Rightarrow$ （1）

根据条件定义（分段）光滑闭合曲线 $\partial\Sigma$ ，以及满足[[MK37][Stokes公式]]条件的曲面 $\Sigma$ 

则环路积分 $\int_{\partial\Sigma}\vec{a}\cdotd\vec{s}&=\iint_\Sigma\nabla\times\vec{a}\cdot d\vec{s}=\iint_\Sigma\vec{0}\cdot d\vec{s}=0$

*** 定理2

若向量场 $\vec{a}(x,y,z)=P(x,y,z)\vec{i}+Q(x,y,z)\vec{j}+R(x,y,z)\vec{k}, (x,y,z)\in\Omega\subset R^3$ 满足：

（1） 分量函数 $P(x,y,z),Q(x,y,z),R(x,y,z)$ 有连续偏导

（2） 函数 $U(x,y,z)$ 满足 $\nabla U(x,y,z)=\vec{a}(x,y,z)$

（3） $\Omega$ 为[[MK39][空间单连通区域]]

则定义两点 $\vec{r}_1=(x_1,y_1,z_1),\vec{r}_2=(x_2,y_2,z_2)$ ，之间的第二类曲线积分 $\int_{\vec{r}_1}^{\vec{r}_2}\vec{a}\cdot d\vec{s}=U(x_2,y_2,z_2)-U(x_1,y_1,z_1)$

**** 证明

定义 $\vec{r}_3=(x_2,y_1,z_1)$ 则根据[[MK43][之前证明]]可得 $\int_{\vec{r}_1}^{\vec{r}_3}\vec{a}\cdot d\vec{s}=\int_{x_1}^{x_2}P(t,y,z)dt$

又由于 $P(x,y,z)$ 连续且根据条件（2） $\frac{\partial U(x,y,z)}{\partial x}=P(x,y,z)$ ，故根据[[~/文档/note/数学分析/Chap7Note.org][牛顿莱布尼茨公式]]可得 $\int_{\vec{r}_1}^{\vec{r}_3}\vec{a}\cdot d\vec{s}=U(x_2,y_1,z_1)-U(x_1,y_1,z_1)$

同理定义 $\vec{r}_4=(x_2,y_2,z_1)$ 则有 $\int_{\vec{r}_3}^{\vec{r}_4}\vec{a}\cdot d\vec{s}=U(x_2,y_2,z_1)-U(x_2,y_1,z_1)$ 及 $\int_{\vec{r}_4}^{\vec{r}_2}\vec{a}\cdot d\vec{s}=U(x_2,y_2,z_2)-U(x_2,y_2,z_1)$

则根据[[MK9][区间可加]]，该路径下曲线积分可示为 $\int_{\vec{r}_1}^{\vec{r}_2}\vec{a}\cdot d\vec{s}=\int_{\vec{r}_1}^{\vec{r}_3}\vec{a}\cdot d\vec{s}+\int_{\vec{r}_3}^{\vec{r}_4}\vec{a}\cdot d\vec{s}+\int_{\vec{r}_4}^{\vec{r}_2}\vec{a}\cdot d\vec{s}=U(x_2,y_2,z_2)-U(x_1,y_1,z_1)$

又由于条件（2）则根据[[MK44][定义]]向量场为有势场，又由于条件（1），（3）根据[[MK45][定理1]]得出积分与路径无关。




