#+LATEX_CLASS: ctexart

#+TITLE: Euclid空间上的极限与连续

current mark: MK21

* 笛卡尔乘积

假设两个集合：

$X=\{x_i|i\in U\}$
$Y=\{y_i|i\in V\}$

则两个集合的笛卡尔乘积： $X\times Y=\{(x_i,y_j)|i\in U,j\in V\}$

* 实数系基本定理

** 确界存在定理<<MK9>>

任意非空实数集 $S=\{x_n\}$ ，有上界必有实数上确界，有下界必有实数下确界。

*** 证明

**** 构造子集和确界

对于任意 $x_n\in S$ ，构建 $x_n=a_{n0}.a_{n1}a_{n2}a_{n3}...\\$ 其中 $a_{n0}$ 为整数部分， $a_{n1}$ 为第一位小数，以此类推。

由于有上界，故必定存在 $k\in\mathbb{R}$ 大于任意 $x_n\in S$ ，则 $a_{n0}$ 不可能为无限大，故必有最大值，

对于 $a_{ni},i>0$ 其取值范围是整数 $0$ 至 $9$ ，亦必有最大值

$a_0=\max(a_{n0}),\forall x_n\in S$ ，则构建 $S_0=\{x_n|[x_n]=a_0,x_n\in S\}$ ，所以 $S_0\subset S$

$a_1=\max(a_{n1}),\forall x_n\in S_0$ ，则构建 $S_1=\{x_n|[x_n]=a_0,x_n\in S_0\}$ ，所以 $S_1\subset S_0$

...

最终构建非空数集 $S\supset S_0 \supset S_1...\supset S_n \supset ...\\$

且构建确界 $\beta=a_0.a_1a_2a_2...\\$ 根据[[~/OneDrive/实变函数/SBHS.org][实数公理-推论]]可得 $\beta\in\mathbb{R}$

**** 确界满足 $\forall x\in S\Rightarrow \beta\geq x$

若 $[x]<a_0$ 则 $\beta\geq [\beta]>x$

若 $[x]=a_0$ 设 $[x]\in S_n$ ，则 $x=a_0.a_1a_1...a_nb_1b_2...\\$ 根据定义 $b_i\leq a_{n+i}$ 故有 $\beta\geq x$

**** 确界满足 $\forall \epsilon>0,\exists x_0\in S\Rightarrow \beta-x_0<\epsilon$

$\forall \epsilon>0,\exists n_0\Rightarrow \epsilon>\frac{1}{10^{n_0}}$ 则存在 $S_{n_0}\subset S\Rightarrow \forall x_0\in S_{n_0}\Rightarrow x_0=a_0.a_1a_2...a_{n_0}b_1b_2...\\$ 

故有 $\beta-x_0=0.00...(a_{n_0+1}-b_1)(a_{n_0+2}-b_2)...<\frac{1}{10^{n_0}}<\epsilon\\$

** 单调有界数列定理<<MK17>>

单调有界数列必收敛于单调确界

*** 证明

若 $a_n$ 单调增加有上界，则根据确界存在定理，必有上确界 $\xi$ 满足：

（1） $\forall n\in N^+\Rightarrow a_n\leq\xi$

（2） $\forall \epsilon>0,\exists a_{n^*}\Rightarrow \xi-a_{n^*}<\epsilon$

故取 $N=n^*$ 由于单调递增，则 $\forall n>N\Rightarrow a_n\geq a_{n^*}\Rightarrow \xi-a_{n^*}+a_{n^*}<\epsilon+a_n$

故 $\forall \epsilon >0,\exists N,\forall n>N\Rightarrow \xi-a_n<\epsilon$

故 $\lim_{n\to\infty}a_n=\xi$

** 闭区间套定理<<MK20>>

*** 描述

若一列闭区间 $\{[a_n,b_n]\}$ 满足：

（1） $[a_{n+1},b_{n+1}]\subset [a_{n},b_{n}]$
（2） $\lim_{n\to\infty}(b_n-a_n)=0$

则存在唯一实数 $\xi$ 属于所有 $[a_n,b_n]$ 且 $\xi=\lim_{n\to\infty}a_n=\lim_{n\to\infty}b_n$

*** 证明

**** $\lim_{n\to\infty}a_n=\lim_{n\to\infty}b_n=\xi$

根据条件（1）： $a_n \leq a_{n+1}<b_n$ 故 $a_n$ 单调增加有上届，同理 $b_n$ 单调减少有下界。故数列 $a_n,b_n$ 收敛。

假设 $\xi$ 为 $a_n$ 上确界，则 $lim_{n\to\infty}a_n=\xi$ ，

又根据条件（2）和极限四则运算 $\lim_{n\to\infty}b_n=\lim_{n\to\infty}(b_n-a_n)+\lim_{n\to\infty}a_n=0+\xi=\xi$

故得 $\lim_{n\to\infty}a_n=\lim_{n\to\infty}b_n=\xi$

**** 唯一一点

若存在 $\xi'$ 属于所有 $[a_n,b_n]$ ，则有 $\forall n\in N^+\Rightarrow a_n\leq\xi'\leq b_n$ ，故当 $n\to\infty$ ，根据夹逼定理 $\xi'=\xi$

** Bolzano-Weierstrass定理

有界数列必有收敛子列。

*** 子列定义<<MK16>>

给定数列 $\{x_n\}$ ，从中任意地选取无限项，按照原来的顺序组成的数列称为数列 $\{x_n\}$ 的一个子列。

*** 证明：

假设数列 $\{x_n\}$ 有界：$\forall n \in N^+\Rightarrow a<x_n<b$ 

取 $z_1 \in(a,b)$ ，划分为 $[a,z_1]$ 和 $[z_1,b]$ 长度相等的两个区域（两个区间长度为 $\frac{b-a}{2}$），因为 $\{x_n\}$ 有无穷多项，则必有一个区域包含无穷多个 $\{x_n\}$ 的子项。

定义该区域为 $[a_1,b_1]$ ，取任意 $y_1=x_i,\ x_i \in [a_1,b_1]$;

...

取 $z_n \in (a_{n-1},b_{n-1})$ ，划分为 $[a_{n-1},z_n]$ 和 $[z_n,b_{n-1}]$ 长度相等的两个区域（两个区间长度为 $\frac{b-a}{2^n}$），因为 $\{x_n\}$ 有无穷多项，则必有一个区域包含无穷多个 $\{x_n\}$ 的子项。

定义该区域为 $[a_n,b_n]$ ，取任意 $y_n=x_i,\ x_i \in [a_n,b_n]$;

故得到数列 $\{y_n\}$ ，根据柯西收敛原理证明收敛性：

\begin{aligned}
&\forall \epsilon>0,\ \ N=max\left\{n \left|\frac{b-a}{2^n}<\epsilon\right\}\\
&\forall n,m>N \\
&\Rightarrow y_n,y_m \in [a_N,b_N],\ \ b_N-a_N<\frac{b-a}{2}<\epsilon\\
&\therefore |y_n-y_m|<\epsilon\\
\end{aligned}

** 柯西收敛原理<<MK21>>

*** 描述

数列 $S=\{x_n\}$ 收敛的充要条件 $\forall \epsilon>0,\exists N,\forall n,m>N\Rightarrow |x_n-x_m|<\epsilon$

*** 证明

**** 充分

假设 $\{x_n\}$ 收敛于 $A$ 则有: 

\begin{aligned}
\forall \epsilon>0, \exists N,\forall m,n>N\Rightarrow |x_n-A|<\frac{\epsilon}{2},|A-x_m|<\frac{\epsilon}{2}\Rightarrow |x_n-x_m|\leq |x_n-A|+|A-x_m|<\epsilon
\end{aligned}

**** 必要

是实数系的[[~/OneDrive/实变函数/SBHS.org][实数公理-公理定义-完备性公理]]，故成立

亦可根据[[~/OneDrive/实变函数/SBHS.org][实数公理-等价定理]]从[[MK9][确界存在定理]]证得

* 构造Euclid空间

** 向量空间的定义

*** 定义空间集合

$R$ 为实数全体，定义 $R^n=R\times R\times...\times R=\{(x_1,x_2,...,x_n)|x_i\in R\}$

其中 $\vec{x}=(x_1,x_2,...,x_n)$ 定义为向量，是Euclid空间的基本单元。

*** 定义加法

假设 $\vec{x}=(x_1,x_2,...,x_n),\ \vec{y}=(y_1,y_2,...,y_n)$ 则 $\vec{x}+\vec{y}=(x_1+y_1,x_2+y_2,...,x_n+y_n)$

*** 定义数乘

假设 $\vec{x}=(x_1,x_2,...,x_n)$ 则 $\alpha\vec{x}=(\alpha x_1,\alpha x_2,...,\alpha x_n)$

** 定义內积（定义內积后成为Euclid空间）

对于向量 $\vec{x},\vec{y}$ 其內积为 $\langle\vec{x},\vec{y}\rangle=\sum_{i=1}^n x_iy_i$

*** 內积的性质

**** 正定性 $\langle\vec{x},\vec{x}\rangle\geq 0$

**** 对称性 $\langle\vec{x},\vec{y}\rangle=\langle\vec{y},\vec{x}\rangle$

**** 线性   $\langle\alphe\vec{x}+\beta\vec{y},\vec{z}\rangle=\alpha\langle\vec{x},\vec{z}\rangle+\beta\langle\vec{y},\vec{z}\rangle$

**** Schwarz不等式 $\langle\vec{x},\vec{y}\rangle^2\leq \langle\vec{x},\vec{x}\rangle\cdot \langle\vec{x},\vec{x}\rangle$

证明：

\begin{aligned}
\because &\langle \lambda\vec{x}+\vec{y},\lambda\vec{x}+\vec{y}\rangle =\lambda^2\langle\vec{x},\vec{x}\rangle+2\lambda\langle\vec{x},\vec{y}\rangle+\langle\vec{y},\vec{y}\rangle\geq 0\\
\therefore & (2\langle\vec{x},\vec{y}\rangle)^2-4\langle\vec{x},\vec{x}\rangle \langle\vec{y},\vec{y}\rangle<0\\
\therefore &\langle\vec{x},\vec{y}\rangle^2<\langle\vec{x},\vec{x}\rangle \langle\vec{y},\vec{y}\rangle\\
\end{aligned}

** 定义范数

*** 拓扑定义

若 $V$ 是[[~/OneDrive/高等代数/Algb-1-Liner_sys_func.org][数域]] $K$ 上的根据[[~/OneDrive/高等代数/Algb-2-Liner_Space.org][线性空间]]，定义 $R$ 为实数，则根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数]]有函数 $\|\cdot\|:V\rightarrow R$ 满足：

（1） 正定型： $\forall x\in V\rightarrow \|x\|\geq 0$ 且 $\|x\|=0\Leftrightarrow x=0$

（2） 正其次性： $(\forall x\in V\land\forall k\in K)\rightarrow(\|kx\|=|k|\|x\|)$ 

（3） 次可加性： $\forall x,y\in V$ 满足 $\|x+y\|\leq\|x\|+\|y\|$

*** 欧式空间定义

$||\vec{x}||=\sqrt{<\vec{x},\vec{x}>}$

** 定义距离

$R^n$ 上 $\vec{x}=(x_1,x_2,...,x_n),\ \vec{y}=(y_1,y_2,...,y_n)$ 的距离定义为 $|\vec{x}-\vec{y}|=\sqrt{\sum_{i=1}^n(x_i-y_i)^2}$

*** 距离的性质：

**** 正定型： $|\vec{x}-\vec{y}|\geq 0,|\vec{x}-\vec{y}|=0\Leftrightarrow \vec{x}=\vec{y}$

**** 对称性： $|\vec{x}-\vec{y}|=|\vec{y}-\vec{x}|$

**** 三角不等式： $|\vec{x}-\vec{y}|+|\vec{y}-\vec{z}|\geq |\vec{x}-\vec{z}|$

证明，由于 $|\vec{x}|+|\vec{y}|>0,\ |\vec{x}-\vec{y}|>0$ ，故两边平方:

\begin{aligned}
&|\vec{x}|^2=\sum_{i=1}^n x_i^2,\ |\vec{y}|^2=\sum_{i=1}^n y_i^2\\
&(|\vec{y}|+|\vec{x}|)^2=|\vec{x}|^2+|\vec{y}|^2+2|\vec{x}||\vec{y}|\\
&|\vec{x}-\vec{y}|^2=\sum_{i=1}^n (x_i-y_i)^2=\sum_{i=1}^n \{x_i^2-2x_iy_i+y_i^2\}=|\vec{x}|^2+|\vec{y}|^2 -2 \sum_{i=1}^nx_iy_i\\
&
\end{aligned}

故只需比较 $2|\vec{x}||\vec{y}|$ 以及 $-2 \sum_{i=1}^nx_iy_i$ 的大小，由于前者恒大于0，故当 $-2 \sum_{i=1}^nx_iy_i\leq0$ 时，等式成立，当 $-2 \sum_{i=1}^nx_iy_i>0$ 时，两边平方：

\begin{aligned}
&(2|\vec{x}||\vec{y}|)^2=4\sum_{i=1}^n x_i^2 \sum_{i=1}^n y_i^2=\sum_{i=1}^n x_i^2y_i^2+\sum_{i\ne j;i<j}x_i^2y_j^2+x_j^2y_i^2\\
&\left(-2 \sum_{i=1}^nx_iy_i\right)^2=4\sum_{i=1}^nx_iy_i\sum_{i=1}^nx_iy_i=\sum_{i=1}^n x_i^2y_i^2+\sum_{i\ne j;i<j}2x_iy_ix_jy_j\\
\therefore &(2|\vec{x}||\vec{y}|)^2-\left(-2 \sum_{i=1}^nx_iy_i\right)^2=\sum_{i\ne j;i<j}\{x_i^2y_j^2+x_j^2y_i^2-2x_iy_ix_jy_j\}\\
&=\sum_{i\ne j;i<j} (x_iy_j-x_jy_i)^2\geq 0\\
\end{aligned}

故 $|\vec{x}-\vec{y}|+|\vec{y}-\vec{z}|\geq |\vec{x}-\vec{z}|$ ，证毕。

** 定义极限

假设Euclid空间中有点列 $\vec{x}_n$ ,和向量 $\vec{A}$ 若 $\forall \epsilon>0, \exists N, \forall n>N\Rightarrow |\vec{x}-\vec{A}|<\epsilon$ 则称 $\lim_{n\to\infty}\vec{x}_n=\vec{A}$

** 点的定义

若Euclid空间内 $S\subset R^n$ ，且 $S^c$ 为 $S$ 的补集 $R^n\backslash S=S^c$

定义符号 $O(\vec{x},\delta)=\left\{\vec{a}\big||\vec{x}-\vec{a}|<\delta\right\}$ 为以 $\vec{x}$ 为中心的领域

于空间中的一个点 $\vec{x}$ 来说：

*** $S$ 的内点 $S_i$ <<MK7>>

$\exists \delta>0\land\delta\in\mathbb{R}\rightarrow O(\vec{x},\delta)\subset S$ ，所有内点集合 $S_i$
 
*** $S$ 的外点

$\exists \delta>0, O(\vec{x},\delta)\not\subset S$

*** $S$ 的边界点

$\forall \delta>0, \exists \vec{\alpha},\vec{\beta} \in O(\vec{x},\delta)\Rightarrow \alpha\in S, \beta\in S^c$

*** $S$ 的孤立点<<MK14>>

$\exists\delta>0\rightarrow \vec{x}\in S\land O(\vec{x},\delta)\vec{x}\subset S^c$

*** $S$ 的聚点 $S'$ <<MK8>>

$\forall \delta>0,\exists A\subset O(\vec{x},\delta)\Rightarrow A\subset S$ 其中 $A$ 为任意包含无限个点（不同点）的集合

即 $S$ 的聚点 $\vec{x}$ 的任意领域 $O(\vec{x},\delta),\delta>0$ 都包含 $S$ 中的无限个点（不同点）

定义 $S$ 的聚点的集合为 $S'$

**** <<JDCYTJ1>>充要条件1

$\forall \delta>0,\exists\vec{a}\ne\vec{x}\land\vec{a}\in S\rightarrow \vec{a}\in O(\vec{x},\delta)$

**** <<JDCYTJ2>>充要条件2

$\exists \{\vec{x}_k\} \in S,\vec{x}_k\ne \vec{x}\Rightarrow \lim_{k\to\infty} \vec{x}_k=\vec{x}$

** 集合定义

若Euclid空间内 $S\subset R^n$ ，且 $S^c$ 为 $S$ 的补集 $R^n\backslash S=S^c$

定义符号 $O(\vec{x},\delta)=\left\{\vec{a}\big||\vec{x}-\vec{a}|<\delta\right\}$ 为以 $\vec{x}$ 为中心的领域

*** 开集定义<<MK10>>

$\forall \vec{x}\in S\Rightarrow \vec{x}\in S_i$ 即所有 $S$ 包含的点均为 $S$ 的[[MK7][内点]]

**** 满足拓扑定义

根据[[~/OneDrive/实变函数/SBHS.org::MK39][拓扑定义]]有[[MK15][定理8]]可得（1）、[[P2][定理3]]可得（2）以及[[P3][定理4]]可得（3）

故该定义为有效拓扑定义

*** 开覆盖<<MK11>>

若 $S\subset R^n$ ，存在一组[[MK10][开集]] $\{U_\alpha\}\Rightarrow S\subset\cup_\alpha U_\alpha$ ，则称 $\{U_\alpha\}$ 是 $S$ 的开覆盖

*** 闭集定义<<MK13>>

$S'\subset S$ 或 $S'=\varnothing$ 即 $S$ 包含的点均为 $S$ 的[[MK8][聚点]]，或 $S$ 没有聚点

*** 紧集<<MK5>>

若 $S$ 的任意一个[[MK11][开覆盖]]，必有有限子覆盖，即 $\exists U_{\alpha_i}\in \{U_\alpha\},0\leq i\leq p<+\infty\Rightarrow S\subset \cup_{i=0}^p U_{\alpha_i}$ 

则定义 $S$ 为紧集

注： $U_{\alpha_i}$ 为集合 $\{U_\alpha\}$ 的元素

**** 引理

任意紧集的闭子集亦为紧集

***** 证明

若 $M\subset\mathbb{R}^n$ 为紧集，其闭子集 $F\subset M$ 对于任意 $F$ 的开覆盖 $\{U_{\lambda\in\Lambda}\}$ 

根据定义 $F^c$ 为 $F$ 的补集，且有 $F\cup F^c=\mathbb{R}^n$  

可知 $M\subset\mathbb{R}^n=\left(\bigcup_{\lambda\in\Lambda}U_\lambda\right)\cup F^c$ 根据[[P1][定理1]]以及 $F$ 是闭集的条件可得 $F^c$ 是开集 

则有 $\{U_{\lambda\in\Lambda},F^c\}$ 是 $M$ 的开覆盖，由于 $M$ 是[[MK5][紧集]]则必有有限子覆盖 $\{U_1,...,U_n,F^c\}$

由于 $F^c\cap F=\varnothing$ 且 $F\subset M$ 故 $\bigcup_{i=1}^n U_i$ 必定覆盖 $F$ 即 $F$ 亦有有限子覆盖

*** 完备集

不存在[[MK14][孤立点]]的[[MK13][闭集]]是完备集

**** 证明

根据[[~/OneDrive/实变函数/SBHS.org][拓扑-子集分类-完备集]]，进一步根据闭集定义以及[[MK8][聚点]]定义，

可得若闭集 $S$ 不存在孤立点，则对于任意 $x\in S$ 不是孤立点的定义为对于任意 $\delta\in\mathbb{R}\land\delta>0$

均有 $y\in S\rightarrow d(x,y)<\delta$ 即聚点[[JDCYTJ1][充要条件1]]。故所有 $S$ 中的点均为聚点。即是完备集

*** 部分定理

**** 定理1<<P1>>

在 $R^n$ 上 $S$ 为闭集的充要条件是 $S^c$ 是开集

***** 证明

****** 证明充分

已知 $S$ 为闭集，若点 $\vec{x}\in S^c$ 则 $\vec{x}$ 不是 $S$ 的聚点，根据[[JDCYTJ1][聚点充要条件1]]可得不是聚点的充要条件为：

\begin{aligned}
&\exists \delta>0,\forall\vec{a}\ne\vec{x}\land\vec{a}\in S\rightarrow \vec{a}\not\in O(\vec{x},\delta)\\
\because &\vec{x}\in S^c\\
\therefore &\vec{x}\not\in S\\
\therefore &\forall \vec{x}\in S^c,\exists \delta\Rightarrow O(\vec{x},\delta)\not\subset S\\
\therefore &\forall \vec{x}\in S^c \Rightarrow \vec{x}\in S^c_i\\
\end{aligned}

****** 证明必要

已知 $S^c$ 是开集，若点 $\vec{x}\in S'$

\begin{aligned}
\because & \forall \delta>0, \exists \vec{a}\in O(\vec{x},\delta)\Rightarrow \vec{a}\in S\\
\because & \forall \vec{a}\in S^c, \exists \delta\Rightarrow O(\vec{a},\delta)\in S^c\\
\therefore & \forall \vec{a}\in S^c, \exists \delta\Rightarrow O(\vec{a},\delta)\not\in S\\
\therefore & \forall \vec{x}\not\in S^c\\
\therefore & S'\subset S
\end{aligned}

***** 推论

在 $R^n$ 上 $S$ 为开集的充要条件是 $S^c$ 是闭集

**** 定理2<<MK19>>

领域为开集

***** 证明

\begin{aligned}
\forall \vec{a}\in O(\vec{x},\delta),\exists 0<h<\delta-|\vec{a}-\vec{x}|\rightarrow O(\vec{a},h)\subset O(\vec{x},\delta)
\end{aligned}

**** 定理3<<P2>> 

任意一组开集 $\{S_\alpha\}$ 的并集 $\cup_\alpha S_\alpha$ 是开集

***** 证明

\begin{aligned}
&\forall\vec{x} \in \cup_\alpha S_\alpha\\
\because &\vec{x} \in \cup_\alpha S_\alpha\\
\therefore &\vec{x} \in S_i\\
\therefore &\exists \delta\Rightarrow O(\vec{x},\delta)\subset S_i \subset \cup_\alpha S_\alpha
\end{aligned}

**** 定理4<<P3>>

有限个开集 $\{S_i|1\leq i \leq k\}$ 的交集 $\cap_{i=1}^k S_i$ 为开集

***** 证明

\begin{aligned}
&\forall \vec{x} \in \cap_{i=1}^k S_i\\
\therefore &\vec{x} \in S_i,i=1,2,...,k\\
\therefore &\exists \delta_i>0\Rightarrow O(\vec{x},\delta_i)\subset S_i\\
\therefore &0<\delta<min(\delta_i)\Rightarrow O(\vec{x},\delta)\subset \cap_{i=1}^k S_i\\
\end{aligned}

**** 定理5<<P4>>

任意一组闭集 $\{S_\alpha\}$ 的交集 $\cap_\alpha S_\alpha$ 是闭集

***** 证明

因为 $\cap_\alpha S_\alpha=\cup_\alpha S_\alpha^c$ 有根据[[P1][之前证明]] $S_\alpha^c$ 为开集，则根据[[P2][之前证明]]任意 $\cup_\alpha S_\alpha^c$ 为开集，则其补集为闭集

**** 定理6

有限个闭集 $\{S_i|1\leq i \leq k\}$ 的并集 $\cup_{i=1}^k S_i$ 为闭集

***** 证明

因为 $\cup_{i=1}^k S_i=\cap_{i=1}^k S_i^c$ 有根据[[P1][之前证明]] $S_\alpha^c$ 为开集，则根据[[P3][之前证明]]有限个 $\cap_{i=1}^k S_i^c$ 为开集，则其补集为闭集

**** 定理7

若两个闭集 $A,B$ 均为 $\mathbb{R}^n$ 的子集，且有 $A\cap B=\varnothing$ 则必有两个开集 $A',B'$ 满足：

（1） 均是 $\mathbb{R}$ 的子集

（2） $A\subset A'\land B\subset B'$

（3） $A'\cap B'=\varnothing$

***** 证明

对于任意 $a\in A$ 定义 $\delta(a)=\frac{1}{2}d(\{a\},B)$ 其中 $d(a,B)$ 是[[~/OneDrive/实变函数/SBHS.org][测度-相关定义-子集距离]]

同样对于任意 $b\in B$ 定义 $\delta(b)=\frac{1}{2}d(\{b\},A)$

由于 $\{a\}\subset A$ 且 $d(A,B)$ 是下确界，故必有 $d(A,B)\leq d(\{a\},B)\land d(A,B)\leq d(\{b\},A)$ 对于任意 $a\in A,b\in B$

定义 $A'=\bigcup_{a\in A}O(a,\delta(a)),B'=\bigcup_{b\in B}O(b,\delta(b))$

则显然 $A',B'$ 均为 $\mathbb{R}^n$ 的子集

且有 $\forall a\in A\rightarrow a\in O(a,\delta(a))\subset A'$ 同理 $\forall b\in B\rightarrow b\in B'$ 故有 $A\subset A'\land B\subset B'$

若存在 $x\in\mathbb{R}^n$ 满足 $x\in A'\land x\in B'$ 则必定存在 $a'\in A\land b'\in B$ 满足 $x\in O(a',\delta(a'))\land x\in O(b',\delta(b'))$

则根据[[~/OneDrive/实变函数/SBHS.org][测度-相关定义-度量空间]]三角性可得 $d(a',x)+d(x,b')\geq d(a',b')$

又有 $d(a',x)<\frac{1}{2}d(\{a'\},B)\leq\frac{1}{2}d(a',b')$ 同理有 $d(x,b')<\frac{1}{2}d(a',b')$

则有 $\frac{1}{2}d(a',b')+\frac{1}{2}d(a',b')>d(a',x)+d(x,b')\geq d(a',b')$ 即 $d(a',b')>d(a',b')$ 矛盾

故不存在，即 $A'\cap B'=\varnothing$ 

**** 定理8<<MK15>>

空集即是开集也是闭集

***** 证明

****** 开集

根据[[MK10][开集定义]]表达式 $\forall \vec{x}\in S\rightarrow \vec{x}\in S_i$ 为真是 $S$ 为开集的等价条件

此处 $\rightarrow$ 为[[~/OneDrive/离散数学/Disc_Math.org::MK60][蕴含]]，由于对于空集 $\vec{x}\in S'$ 永假，

故根据真值表 $\forall \vec{x}\in S\rightarrow \vec{x}\in S_i$ 为真，则根据等价性空集是开集

****** 闭集

对于全集 $\mathbb{R}^n$ 显然任意点均为内点，根据[[MK10][开集定义]] $\mathbb{R}^n$ 是开集

根据[[P1][定理1]]可得其补集为闭集，由于全集的补集是空集，故空集为闭集

***** 推论

根据本定理以及[[P1][定理1]]可得全集 $\mathbb{R}^n$ 既是开集也是闭集

** Euclid空间基本定理

*** <<KTDL>>康托闭区域套定理

**** 描述

$\{S_k\}$ 为 $R^n$ 上的非空闭集序列，满足：

（1） $S_1\supset S_2\supset S_3\supset...\supset S_n\supset...\\$
（2） $\lim_{k\to\infty} diam S_k=0$ ，其中 $diamS_k=sup\{|x-y|\big|x,y\in S_k\}$

则存在唯一一点 $\vec{x}\in \cap_{k=1}^\infty S_k$

**** 证明

\begin{aligned}
\because & diamS_k=sup\{|x-y|\big|x,y\in S_k\}\\
\therefore & \exists S'_k=[a_{k1},a_{k1}+diamS_k]\times [a_{k2},a_{k2}+diamS_k]\times...\times [a_{kn},a_{kn}+diamS_k]\Rightarrow S_k\subset S'_k\\
\because & S_1\supset S_2 \supset...\\
\because & diamS_k\leq diamS_{k+1}\\
\therefore & \exists \{S'_k\}\Rightarrow S_k\subset S'_k,\ S'_1\supset S'_2\supset...\\
\therefore & \forall k\in N^+\Rightarrow diamS_{k+1}\leq diamS_k\Rightarrow [a_{ki},a_{ki}+diamS_k]\supset [a_{(k+1)i},a_{(k+1)i}+diamS_{k+1}]\\
\because & \lim_{k\to\infty} diam S_k=0\\
\therefore & \lim_{k\to\infty} a_{ki}+diamS_k-a_{ki}=0\\
\end{aligned}

故根据实数闭区间套定理，存在唯一 $\xi_i$ 使得 $\xi_i\in \cap_{k=1}^\infty [a_{ki},a_{ki}+diamS_k]$

故存在唯一点 $\vec{x}=(\xi_1,\xi_2,...,\xi_n)$ 使得 $\vec{x}\in \cap_{k=1}^\infty S'_k$

又因为对于 $\{S'_k\}$ 来说 $\lim_{k\to\infty}diamS'_k=\lim_{k\to\infty}diamS_k=0$ 且 $S_k\subset S'_k$

\begin{aligned}
\therefore &\forall \delta>0,\exists K,\forall k>K\Rightarrow S'_k\subset O(\vec{x},\delta)\\
\because &S_k\subset S'_k\\
\therefore & \forall \delta>0,\exists \vec{a}\in S_k\Rightarrow \vec{a}\in O(\vec{x},\delta)\\
\because & S_1\supset S_2\supset...\supset S_k \supset...\\
\therefore & \forall i\in N^+:\forall \delta>0,\exists \vec{a}\in S_i,\Rightarrow \vec{a}\in O(\vec{x},\delta)\\
\end{aligned}

故可推断 $\vec{x}$ 是 $S_i$ 的聚点，其中 $i\in N^+$

又因为 $S_i$ 是闭集，所以 $\vec{x}\in \cap_{k=1}^\infty S_k$

*** <<BW>>Bolzano-Weierstrass定理

**** 描述

$R^n$ 上有界点列 $\{\vec{x}_k=(a_{1k},a_{2k},...,a_{nk})\}$ 必有收敛子列

**** 证明

由于 $\{x_n\}$ 有界，则存在区间 $a_k\in[m_k,M_k]$ 

则对于 $a_{1k}$ 根据实数系Bolzano-Weierstrass定理，必有收敛子列 $\lim_{k\to\infty}a_{1k_1}=A_1$ 对应点 $\{\vec{x}_{k1}=(a_{1k_1},a_{2k_1},...,a_{nk_1})\}$

在点列 $\vec{x}_{k1}$ 中 $a_{2k_1}\in [m_2,M_2]$ 则存在收敛子列 $\lim_{k\to\infty}a_{2k_2}=A_2$ 对应点 $\{\vec{x}_{k2}=(a_{1k_2},a_{2k_2},...,a_{nk_2})\}$ 且由于 $\{a_{1k_2}\}\subset\{a_{1k_1}\}$ 故 $\lim_{k\to\infty}a_{1k_2}=A_1$

...

在点列 $\vec{x}_{k(n-1)}$ 中 $a_{nk_{(n-1)}}\in [m_{n-1},M_{n-1}]$ 则存在收敛子列 $\lim_{k\to\infty}a_{nk_{(n-1)}}=A_n$ 对应点 $\{\vec{x}_{kn}=(a_{1k_n},a_{2k_n},...,a_{nk_n})\}$ 且由于 $\{a_{ik_n}\}\subset\{a_{ik_{(n-1)}}\}$ 故 $\lim_{k\to\infty}a_{ik_n}=A_i$

故存在点列 $\{\vec{x}_{kn}=(a_{1k_n},a_{2k_n},...,a_{nk_n})\}\subset \{\vec{x}\}$ 收敛于 $\vec{A}'=(A_1,A_2,...,A_n)$

**** 推论：

$R^n$ 上有界无限点集 $S$ 至少有一个聚点

***** 证明：

因为 $S$ 有界，且 $S$ 为无限点集，所以 $S$ 中存在无限不重复点，则有界数列必有收敛子列：

\begin{aligned}
&\exists \{\vec{x}_k\}\Rightarrow \lim_{k\to\infty}\vec{x}_k=\vec{x}\subset S\\
&\forall k\in N^+\Rightarrow \vec{x}_k\ne \vec{x}\\
\end{aligned}

故根据[[JDCYTJ2][聚点充要条件2]]得出， $\vec{x}$ 为聚点。

*** 柯西收敛原理

**** 描述

$R^n$ 上点列 $\{\vec{x}_n\}$ 收敛的充要条件是 $\forall \epsilon>0,\exist N,\forall n,m>N\Rightarrow |\vec{x}_n-\vec{x}_m|<\epsilon$

**** 证明

***** 充分

已知收敛 $\lim_{n\to\infty}\vec{x}_n=\vec{A}$ ，则 $\forall \epsilon>0, \exists N, \forall m,n>N\Rightarrow |\vec{x}_n-\vec{A}|<\frac{\epsilon}{2},|\vec{x}_m-\vec{A}|<\frac{\epsilon}{2}$

则 $|\vec{x}_n-\vec{x}_m|\leq |\vec{x}_n-\vec{A}|+|\vec{x}_m-\vec{A}|<\epsilon$

***** 必要

由于 $\forall \epsilon>0,\exist N,\forall n,m>N\Rightarrow |\vec{x}_n-\vec{x}_m|<\epsilon$

故对于 $\vec{x}=(a_{1k},a_{2k},...,a_{nk})$ 中的任一维度来说 $\forall \epsilon >0,\exists N,\forall n,m>N\Rightarrow |a_{in}-a_{im}|\leq |\vec{x}_n-\vec{x}_m|<\epsilon$

根据实数系柯西收敛原理可得 $\lim_{k\to\infty}a_{ik}=A_i$ 所有维度都收敛，故 $\lim_{k\to\infty}\vec{x}=\vec{A}$

*** Heine-Borel定理

**** 描述

在 $R^n$ 中 $S$ 为紧集的充要条件是 $S$ 是有界闭集

**** 证明

***** 充分性

有界闭集 $\Rightarrow$ 紧集

设 $\{U_n\}$ 为任意一个 $S$ 的无限开覆盖

因为 $S$ 有界，故 $\exists I_0=[a_{01},a_{01}+diamS]\times [a_{02},a_{02}+diamS]\times...\times [a_{0n},a_{0n}+diamS]\Rightarrow S\subset I_0$ 其中 $diamS=sup\{|x-y|\big|x,y\in S\}$

将 $I_0$ 分割:

\begin{aligned}
&I_1^1=[a_{01},a_{01}+\frac{1}{2}diamS]\times [a_{02},a_{02}+\frac{1}{2}diamS]\times...\times [a_{0n},a_{0n}+\frac{1}{2}diamS]\Rightarrow S\subset I_0\\
&I_1^2=[a_{01}+\frac{1}{2}diamS,a_{01}+diamS]\times [a_{02},a_{02}+\frac{1}{2}diamS]\times...\times [a_{0n},a_{0n}+\frac{1}{2}diamS]\Rightarrow S\subset I_0\\
&...
\end{aligned}

故必存在至少一个 $I_1^i \cap S$ 不能被有限子覆盖，假设唯一一个 $I_1^{\alpha_1}\cap S$ 

以此类推，在第 $j$ 次分割后有 $I_j^{\alpha_j}\cap S$ 不能被有限子覆盖（假设每次分割只有不能被有限子覆盖）

故当 $j\to \infty$ 时，$diamI_j^{\alpha_j}\cap S\to 0$ 且 $I_j^{\alpha_j}\cap S\subset I_{j-1}^{\alpha_{j-1}}\cap S$ 故根据[[P4][任意闭集交集为闭集]]以及[[KTDL][康托闭区域套定理]] $\exists \vec{x}\in \cap_{j=1}^\infty I_j^{\alpha_j} \cap S$

故 $\vec{x}\in S$ 则，必有一个 $\vec{x}\in U_\beta\subset \{U_n\}$ ，有根据开集的定义 $\exists \delta>0\Rightarrow O(\vec{x},\delta)\subset U_\beta$

又因为 $\lim_{j\to\infty}diamI_j^{\alpha_j}\cap S= 0$ 且 $\exists \vec{x}\in \cap_{j=1}^\infty I_j^{\alpha_j} \cap S$ 故 $\exists K,\forall j>K\Rightarrow I_j^{\alpha_j} \cap S\subset O(\vec{x},\delta)\subset U_\beta$ 与不能被有限子覆盖矛盾。

***** 必要性

紧集 $\Rightarrow$ 有界闭集

****** 证明有界

取开覆盖 $\{O(\vec{x},1)|\vec{x}\in S\}$ 因为紧集，故必有有限子覆盖 $\cup_{i=0}^p O(\vec{x},1)$ ，由于任何一个开集都有界，故 $S$ 有界

****** 证明闭集

定义 $S\in\mathbb{R}^n$ 是紧集，则其补集定义为 $S^c$ 根据之前证明 $S$ 有界，故 $S^c\ne\varnothing$

任去一点 $q\in S^c$ 对于任意 $p\in S$ 存在 $\delta_p$ 使得 $O(p,\delta_p)\cap O(q,\delta_p)=\varnothing$

定义 $S$ 的开覆盖为 $\bigcup_{p\in S}O(p,\delta_p)$ 则由于是紧集，有有限子覆盖 $\bigcup_{i=1}^nO(p_i,\delta_{p_i})$

则取 $\delta=\min(\delta_{p_1},...,\delta_{p_n})$ 则有 $O(q,\delta)\cap S=\varnothing$ 即 $q$ 是 $S^c$ 的[[MK7][内点]]

由于 $q$ 的任意性，故根据[[MK10][定义]]可得 $S^c$ 是开集，进一步根据[[P1][定理1]]可得 $S^c$ 的补集是[[MK13][闭集]]，即 $S$ 是闭集。

**** <<MK2>>推论

设 $S$ 是 $R^n$ 上点集，那么以下3个命题等价：

（1） $S$ 有界闭集；
（2） $S$ 紧集；
（3） $S$ 的任意无限点集在 $S$ 中必有聚点。

***** 证明：

条件（1）和（2）等价由Heine-Borel定理

****** 证明条件（1） $\Rightarrow$ （3）

设 $U\subset S$ 且为无限点集。因为 $S$ 有界，则 $U$ 有界

根据[[BW][Bolzano-Weierstrass定理]]必有收敛子列，定义为 $\exists \{\vec{x}_k\} \in U\Rightarrow \lim_{k\to\infty}\vec{x}_k=\vec{a},\vec{x}_k\ne\vec{a}$

故 $U$ 必有聚点，且聚点为 $\vec{a}$ 故有

\begin{aligned}
\because &U\subset S\\
\therefore &\vec{x}_k\in S\\
\therefore &\{\vec{x}_k\} \in S\Rightarrow \lim_{k\to\infty}\vec{x}_k=\vec{a},\vec{x}_k\ne\vec{a}\\
\end{aligned}

故 $\vec{a}$ 是 $S$ 的聚点，根据闭集定义 $\vec{a}\in S$

****** 证明条件（3） $\Rightarrow$ （1）

根据条件 $S$ 的任意无限点集（不重复点）在 $S$ 中必有聚点，则对于任一收敛点列 $\{\vec{x}_k\}\subset S$ 极限必在 $S$ 中，

则对于所有满足 $\{\vec{x}_k\}\in S,\lim_{k\to\infty}\vec{x}_k=\vec{a},\vec{x}_k\ne\vec{a}$ 来说 $\vec{a}$ 必在 $S$ 中，根据[[JDCYTJ2][聚点充要条件2]]推出 $S$ 为闭集。

又因为若 $S$ 无界，则存在点列 $\{\vec{x}_k\}$ 趋向无穷不收敛，与条件冲突。

* 多元函数

** 定义

设 $\vec{x}\in D\subset R^n$ 映射 $f(\vec{x})=z\in R$ 即 $f(x_1,x_2,...,x_n)=z\in R$ 为 $n$ 元函数， $D$ 为 $f$ 的定义域， $f(D)=\{z|z=f(\vec{x}),\vec{x}\in D\}$ 为 $f$ 的值域。

** 多元函数的极限（多重极限）

设 $D$ 为 $R^n$ 上开集， $\vec{x}_0\in D$ 则有极限定义 

\begin{aligned}
&\forall \epsilon>0, \exists \delta,\forall \vec{x} \in O(\vec{x}_0,\delta),\vec{x}\ne \vec{x}_0\Rightarrow |f(\vec{x})-A|<\epsilon\Rightarrow \lim_{\vec{x}\to\vec{x}_0}f(\vec{x})=A\\
\end{aligned}

注：条件 $\vec{x}\in O(\vec{x}_0,\delta)\Leftrightarrow \sqrt{\sum_{i=1}^n\left(x_i-x_{0_i}\right)^2}<\delta$

** 多元函数极限性质

*** 唯一性

极限是唯一的，即 $\lim_{\vec{x}\to\vec{x}_0}f(\vec{x})=A$ 

**** 证明

若存在 $B$ 使得 $\lim_{\vec{x}\to\vec{x}_0}f(\vec{x})=A,\lim_{\vec{x}\to\vec{x}_0}f(\vec{x})=B$ 同时成立，即

\begin{aligned}
&\forall \epsilon>0, \exists \delta,\forall \vec{x} \in O(\vec{x}_0,\delta),\vec{x}\ne \vec{x}_0\Rightarrow |f(\vec{x})-A|<\epsilon\\
&\forall \epsilon>0, \exists \delta,\forall \vec{x} \in O(\vec{x}_0,\delta),\vec{x}\ne \vec{x}_0\Rightarrow |f(\vec{x})-B|<\epsilon\\
\end{aligned}

则取 $\epsilon=\left|\frac{B-A}{2}\right|>0$ 故根据实数系三角不等式

\begin{aligned}
&|(f(\vec{x})-A)-(f(\vec{x})-B)|\leq |f(\vec{x})-A|+|f(\vec{x})-B| < \left|\frac{B-A}{2}\right|+\left|\frac{B-A}{2}\right|\\
\therefore &|B-A|\leq |f(\vec{x})-A|+|f(\vec{x})-B|<|B-A|\\
\therefore &|B-A|<|B-A|\\
\end{aligned}

推出矛盾。

*** 局部有界性

若 $\lim_{\vec{x}\to\vec{x}_0}f(\vec{x})=A$ 则 $\exists \delta\Rightarrow -\infty<L<f(\vec{x})<U<+\infty, \vec{x} \in O(\vec{x}_0,\delta),L<A<U$ 即在 $\vec{x}_0$ 的领域内 $f(\vec{x})$ 有界

**** 证明

根据定义 $\forall \epsilon>0, \exists \delta,\forall \vec{x} \in O(\vec{x}_0,\delta),\vec{x}\ne \vec{x}_0\Rightarrow |f(\vec{x})-A|<\epsilon$ ，故取 $\epsilon=min(|U-A|,|L-A|)$

\begin{aligned}
\therefore &\exists \delta\Rightarrow |f(\vec{x})-A|<\epsilon,\forall \vec{x}\in O(\vec{x}_0,\delta)\\
\therefore & -\epsilon<f(\vec{x})-A<\epsilon,\forall \vec{x}\in O(\vec{x}_0,\delta)\\
\therefore & -\infty<L\leq A-\epsilon<f(\vec{x})<A+\epsilon\leq U<+\infty,\forall \vec{x}\in O(\vec{x}_0,\delta)\\
\end{aligned}

*** 局部保序性

若 $\lim_{\vec{x}\to\vec{x}_0}f(\vec{x})=A,\lim_{\vec{x}\to\vec{x}_0}g(\vec{x})=B,A>B$ 则 $\exists \delta\Rightarrow f(\vec{x})>g(\vec{x}),\vec{x}\in O(\vec{x}_0,\delta)$

**** 证明

则取 $\epsilon=\frac{A-B}{2}>0$ 则根据定义有

\begin{aligned}
& |f(\vec{x})-A|<\frac{A-B}{2},|g(\vec{x})-B|<\frac{A-B}{2}\\
\therefore & f(\vec{x})>A-\frac{A-B}{2}=\frac{A+B}{2},g(\vec{x})<B+\frac{A-B}{2}=\frac{A+B}{2}\\
\therefore & f(\vec{x})>\frac{A+B}{2}>g(\vec{x})\\
\end{aligned}

*** 夹逼定理

\begin{aligned}
&f(\vec{x})\geq h(\vec{x})\geq g(\vec{x}),\lim_{\vec{x}\to\vec{x}_0}f(\vec{x})=\lim_{\vec{x}\to\vec{x}_0}g(\vec{x})=A\\
&\Rightarrow \lim_{\vec{x}\to\vec{x}_0}h(\vec{x})=A\\
\end{aligned}

**** 证明

对于任意 $\epsilon>0$ 根据定义有

\begin{aligned}
&\exists \delta_1\Rightarrow |f(\vec{x})-A|<\epsilon\Rightarrow f(\vec{x})<A+\epsilon\\
&\exists \delta_2\Rightarrow |g(\vec{x})-A|<\epsilon\Rightarrow g(\vec{x})>A-\epsilon\\
\therefore &\exists \delta=\min(\delta_1,\delta_2)\Rightarrow A-\epsilon<g(\vec{x})\leq h(\vec{x})\leq g(\vec{x})<A+\epsilon\\
\therefore &|h(\vec{x})-A|<\epsilon\\
\end{aligned}

** 多元函数极限四则运算

*** 加减法

\begin{aligned}
&\lim_{\vec{x}\to\vec{x}_0}f(\vec{x})=A,\lim_{\vec{x}\to\vec{x}_0}g(\vec{x})=B\\
&\lim_{\vec{x}\to\vec{x}_0}\{f(\vec{x})+g(\vec{x})\}=A+B\\
\end{aligned}

**** 证明

根据极限定义有

\begin{aligned}
&\exists \delta_1,\forall \vec{x}\in O(\vec{x}_0,\delta_1)\Rightarrow |f(\vec{x})-A|<\frac{\epsilon}{2}\\
&\exists \delta_2,\forall \vec{x}\in O(\vec{x}_0,\delta_2)\Rightarrow |g(\vec{x})-B|<\frac{\epsilon}{2}\\
\therefore &\exists \delta=\min(\delta_1,\delta_2)\Rightarrow |f(\vec{x})+g(\vec{x})-A-B|\leq |f(\vec{x})-A|+|g(\vec{x})-B|<\epsilon\\
\therefore &\lim_{\vec{x}\to\vec{x}_0}\{f(\vec{x})+g(\vec{x})\}=A+B\\
\end{aligned}

*** 乘法

\begin{aligned}
&\lim_{\vec{x}\to\vec{x}_0}f(\vec{x})=A,\lim_{\vec{x}\to\vec{x}_0}g(\vec{x})=B\\
&\lim_{\vec{x}\to\vec{x}_0}\{f(\vec{x})g(\vec{x})\}=AB\\
\end{aligned}

**** 证明

\begin{aligned}
&\exists \delta_a,\forall \vec{x}\in O(\vec{x}_0,\delta_a)\Rightarrow |f(\vec{x})-A|<\epsilon\frac{1}{2|B|}\\
&\exists \delta_b,\forall \vec{x}\in O(\vec{x}_0,\delta_b)\Rightarrow |f(\vec{x})|-|A|\leq |f(\vec{x})-A|<1\Rightarrow |f(\vec{x})|<|A|+1\\
\therefore &\exists \delta_1=min(\delta_a,\delta_b),\forall \vec{x}\in O(\vec{x}_0,\delta_1)\Rightarrow |f(\vec{x})-A|<\epsilon\frac{1}{2|B|},|f(\vec{x})|<|A|+1\\
&\exists \delta_2,\forall \vec{x}\in O(\vec{x}_0,\delta_2)\Rightarrow |g(\vec{x})-B|<\epsilon\frac{|A|+1}{2}\\
\therefore &\exists \delta_2=min(\delta_a,\delta_b)\Rightarrow |g(\vec{x})-B|<\frac{\epsilon}{2}\\
\therefore &\exists \delta=\min(\delta_1,\delta_2)\Rightarrow |f(\vec{x})g(\vec{x})-AB|=|f(\vec{x})g(\vec{x})-f(\vec{x})B+f(\vec{x})B-AB|=|f(\vec{x})(g(\vec{x})-B)+B(f(\vec{x})-A)|\\
&\leq|f(\vec{x})||g(\vec{x})-B|+|B||f(\vec{x})-A|<(|A|+1)\epsilon\frac{|A|+1}{2}+|B|\epsilon\frac{1}{2|B|}<\epsilon\\
\therefore &\lim_{\vec{x}\to\vec{x}_0}\{f(\vec{x})+g(\vec{x})\}=A+B\\
\end{aligned}

*** 除法

\begin{aligned}
&\lim_{\vec{x}\to\vec{x}_0}f(\vec{x})=A,\lim_{\vec{x}\to\vec{x}_0}g(\vec{x})=B\ne 0\\
&\lim_{\vec{x}\to\vec{x}_0}\frac{f(\vec{x})}{g(\vec{x})}=\frac{A}{B}\\
\end{aligned}

**** 证明

\begin{aligned}
&\exists \delta_1,\forall \vec{x}\in O(\vec{x}_0,\delta_1)\Rightarrow |f(\vec{x})-A|<\epsilon\frac{1}{4|B|}\\
\because &\left||g(\vec{x})|-|B|\right|\leq |g(\vec{x})-B|\\
\therefore &\lim_{\vec{x}\to\vec{x}_0}|g(\vec{x})|=|B|\\
\therefore &\exists \delta_a,\forall \vec{x}\in O(\vec{x}_0,\delta_a)\Rightarrow \left||g(\vec{x})|-|B|\right|<\frac{|B|}{2}\Rightarrow -\frac{|B|}{2}<|g(\vec{x})|-|B|<\frac{|B|}{2}\Rightarrow |g(\vec{x})|>\frac{|B|}{2}\\
&\exists \delta_b,\forall \vec{x}\in O(\vec{x}_0,\delta_b)\Rightarrow |g(\vec{x})-B|<\epsilon\frac{|B|^2}{4|A|}\\
\therefore &\exists \delta_2=min(\delta_a,\delta_b),\forall \vec{x}\in O(\vec{x}_0,\delta_2)\Rightarrow |g(\vec{x})-B|<\epsilon\frac{|B|^2}{4|A|},|g(\vec{x})|>\frac{|B|}{2}\\
\therefore &\exists \delta=\min(\delta_1,\delta_2)\Rightarrow \left|\frac{f(\vec{x})}{g(\vec{x})}-\frac{A}{B}\right|
=\left|\frac{f(\vec{x})B-g(\vec{x})A}{g(\vec{x})B}\right|=\left|\frac{f(\vec{x})B-AB+AB-g(\vec{x})A}{g(\vec{x})B}\right|\\
&=\left|\frac{f(\vec{x})-A}{g(\vec{x})}- A\frac{g(\vec{x})-B}{g(\vec{x})B}\right|\leq \left|\frac{f(\vec{x})-A}{g(\vec{x})}\right|+\left|A\frac{g(\vec{x})-B}{g(\vec{x})B}\right|
=\frac{|f(\vec{x})-A|}{|g(\vec{x})|}+\frac{|g(\vec{x})-B|}{|g(\vec{x})|}\frac{|A|}{|B|}\\
&<\frac{\epsilon\frac{1}{4|B|}}{\frac{|B|}{2}}+\frac{\epsilon\frac{|B|^2}{4|A|}}{\frac{|B|}{2}}\frac{|A|}{|B|}=\epsilon\\
\therefore &\lim_{\vec{x}\to\vec{x}_0}\frac{f(\vec{x})}{g(\vec{x})}=\frac{A}{B}\\
\end{aligned}

** 多重极限与多次极限

*** 多次极限定义

对于 $\vec{x}=\{x_1,x_2,...,x_n\}\in R^n$ 多元函数 $f(\vec{x})$ 在定义域 $D$ 上有定义，则 $n$ 次极限为 $A$ 的定义是 $\lim_{x_1\to a_1}\left\{\lim_{x_2\to a_2}\left\{...\lim_{x_n\to a_n}\left\{f(\vec{x})\right\}\right\}\right\}=A$ 

注：

（1）$n$ 次极限与取极限顺序有关；
（2）必须满足先求的极限在 $x_i\ne a_i$ 的某个领域内存在，后求的极限才有定义。

*** <<MK1>>多重极限与多次极限的联系

若多重极限 $\lim_{\vec{x}\to\vec{a}}f(\vec{x})=A$ 且 $\lim_{x_2\to a_2}\left\{...\lim_{x_n\to a_n}\left\{f(\vec{x})\right\}\right\}=\Phi_2(x_1)$ 在去心领域 $O(a_2,\delta_2)$ 存在，则 $\lim_{x_1\to a_1}\left\{\lim_{x_2\to a_2}\left\{...\lim_{x_n\to a_n}\left\{f(\vec{x})\right\}\right\}\right\}=A$

**** 证明

因为 $\lim_{\vec{x}\to\vec{a}}f(\vec{x})=A$ 故 $\forall \epsilon>0, \exists \delta,\forall \vec{x} \in O(\vec{x}_0,\delta),\vec{x}\ne \vec{x}_0\Rightarrow |f(\vec{x})-A|<\epsilon$

因为 $\lim_{x_2\to a_2}\left\{...\lim_{x_n\to a_n}\left\{f(\vec{x})\right\}\right\}=\Phi_2(x_1)$ 存在：

则 $\lim_{x_n\to a_n}\left\{f(\vec{x})\right\}=\Phi_n(x_1,x_2,...,x_{n-1})$ 在去心领域 $O(a_n,\delta_n)$ 上存在，

则有 $\forall \epsilon_n>0,\exists \delta_n,\forall x_n\in O(a_n,\delta_n),x_n\ne a_n\Rightarrow |f(\vec{x})-\Phi_n(x_1,...,x_{n-1})|<\epsilon_n$

则 $\lim_{x_{n-1}\to a_{n-1}}\{\lim_{x_n\to a_n}\{f(\vec{x})\}\}=\Phi_{n-1}(x_1,x_2,...x_{n-2})$ 在去心领域 $O(a_{n-1},\delta_{n-1})$ 上存在，

则有 $\forall \epsilon_{n-1}>0,\exists \delta_{n-1},\forall x_{n-1}\in O(a_{n-1},\delta_{n-1}),x_{n-1}\ne a_{n-1}\Rightarrow |\Phi_n(x_1,...,x_{n-1})-\Phi_{n-1}(x_1,...,x_{n-2})|<\epsilon_{n-1}$

...

则 $\lim_{x_2\to a_2}\left\{...\lim_{x_n\to a_n}\left\{f(\vec{x})\right\}\right\}=\Phi_2(x_1)$ 在去心领域 $O(a_2,\delta_2)$ 上存在

则有 $\forall \epsilon_2>0,\exists \delta_2},\forall x_2\in O(a_2,\delta_2),x_2\ne a_2\Rightarrow |\Phi_2(x_1)-\Phi_3(x_1,x_2)|<\epsilon_2$

取 $\delta=\min(\delta', \delta_i),i=1,2,...,n$ 则对于任意维度 $j$ 均有 $(x_j-a_j)^2\leq \sum_{i=1}^n\left(x_i-a_i\right)^2<\delta^2 \Rightarrow |x_j-a_j|<\delta\leq\delta_j$ 则 $\lim_{x_2\to a_2}\left\{...\lim_{x_n\to a_n}\left\{f(\vec{x})\right\}\right\}=\Phi_2(x_1)$ 存在

又因为 $\Phi_2(x_1)$ 定义 $x_i\to a_i, i=2,3,...,n$ 所以 $\lim_{x_2\to a_2}\left\{...\lim_{x_n\to a_n}\left\{\sum_{i=2}^n(x_i-a_i)^2\right\}\right\}=0$ 

故当 $(x_1-a_1)^2<\delta^2$ 时条件 $(x_1-a_1)^2+\sum_{i=2}^n(x_i-a_i)^2<\delta^2$ 得以满足

\begin{aligned}
|\Phi_2(x_1)-A|&=\left|(f(\vec{x})-A)-(f(\vec{x})-\Phi_n(x_1,...,x_{n-1}))-(\Phi_n(x_1,...,x_{n-1})-\Phi_{n-1}(x_1,...,x_{n-2}))-...-(\Phi_3(x_1,x_2)-\Phi_2(x_1))\right|\\
&\leq |f(\vec{x})-A|+|f(\vec{x})-\Phi_n(x_1,...,x_{n-1})|+|\Phi_n(x_1,...,x_{n-1})-\Phi_{n-1}(x_1,...,x_{n-2})|+...+|\Phi_3(x_1,x_2)-\Phi_2(x_1)|\\
\end{aligned}

且 $|f(\vec{x})-\Phi_n(x_1,...,x_{n-1})|+|\Phi_n(x_1,...,x_{n-1})-\Phi_{n-1}(x_1,...,x_{n-2})|+...+|\Phi_3(x_1,x_2)-\Phi_2(x_1)|\to 0$ 以及 $|f(\vec{x})-A|<\epsilon$

故有 $|\Phi_2(x_1)-A|\leq \epsilon$ 。

综合上述条件 $\forall \epsilon>0,\exists \delta,\forall 0<|x_1-a_1|<\delta \Rightarrow |\Phi_2(x_1)-A|\leq \epsilon$ 证毕。

**** 推论

若函数 $f(\vec{x})$ 在 $\vec{a}$ 点多重极限与任意次序多次极限都存在，则上述极限相等。

***** 证明

假设极限次序 $\lim_{x_1\to a_1}\left\{\lim_{x_2\to a_2}\left\{...\lim_{x_n\to a_n}\left\{f(\vec{x})\right\}\right\}\right\}$ 存在，则根据多次极限定义，极限 $\left\{\lim_{x_2\to a_2}\left\{...\lim_{x_n\to a_n}\left\{f(\vec{x})\right\}\right\}=\Phi_2(x_1)$ 必存在。

根据[[MK1][多重极限与多次极限的联系]]，则有  $\lim_{x_1\to a_1}\left\{\lim_{x_2\to a_2}\left\{...\lim_{x_n\to a_n}\left\{f(\vec{x})\right\}\right\}\right\}=\lim_{\vec{x}\to\vec{a}}f(\vec{x})$

其他次序极限同理。

** 多元函数连续

*** 定义

$$\lim_{\vec{x}\to\vec{x_0}}f(\vec{x})=f(\vec{x}_0),\vec{x}\in D$$

$$\forall \epsilon>0,\exists \delta>0,\forall |\vec{x}-\vec{x}_0|<\delta\Rightarrow |f(\vec{x})-f(\vec{x}_0)|<\epsilon$$

*** 多元初等函数

指幂函数，指数函数，对数函数，三角函数，反三角函数，常数

经过有限次的有理运算（加、减、乘、除、有理数次乘方、有理数次开方）及有限次函数复合所产生的函数

多元初等函数在其定义域上连续

* 向量值函数

** 定义

$D\in R^n$ 映射 $\vec{f}:D\to R^m\Rightarrow \vec{x}=(x_1,...,x_n)\to\vec{z}=(z_1,...,z_m)$ 记为 $\vec{f}(\vec{x})=\vec{z}\Rightarrow \begin{cases}&f_1(x_1,...,x_n)=z_1\\&...\\&f_m(x_1,...,x_n)=z_n\end{cases}$

** 向量值函数极限

对于向量值函数 $\vec{f}(\vec{x})=\vec{z},\vec{x}\in D\subset R^n, \vec{z} \in R^m$ 若有 $\forall \epsilon>0, \exists \delta>0, \forall 0<|\vec{x}-\vec{x}_0|<\delta\Rightarrow |\vec{f}(\vec{x})-\vec{A}|<\epsilon$

则 $\lim_{\vec{x}\to\vec{x}_0}\vec{f}(\vec{x})=\vec{A}$

** 向量值函数连续<<MK18>>

 $\lim_{\vec{x}\to\vec{x}_0}\vec{f}(\vec{x})=\vec{f}(\vec{x}_0)$ 即他的分析表述 $\forall \epsilon>0, \exists \delta>0, \forall 0<|\vec{x}-\vec{x}_0|<\delta\Rightarrow |\vec{f}(\vec{x})-\vec{f}(\vec{x}_0)|<\epsilon$

*** 定理

向量值函数 $\vec{f}(\vec{x})=\vec{z},\vec{x}\in D\subset R^n, \vec{z} \in R^m$ 连续的充要条件是  $\begin{cases}&\lim_{\vec{x}\to\vec{x}_0}f_1(\vec{x})=f_1(\vec{x}_0)\\&...\\&\lim_{\vec{x}\to\vec{x}_0}f_m(\vec{x})=f_m(\vec{x}_0)\\\end{cases},\vec{x},\vec{x}_0\in D\subset R^n$

**** 证明

\begin{aligned}
\because &|\vec{f}(\vec{x})-\vec{f}(\vec{x}_0)|=\sqrt{\sum_{i=1}^m \left(f_i(\vec{x})-f_i(\vec{x}_0)\right)^2}\\
\therefore & \left|f_j(\vec{x})-f_j(\vec{x}_0)\right| \leq |\vec{f}(\vec{x})-\vec{f}(\vec{x}_0)|\leq \sum_{i=1}^m \left|f_i(\vec{x})-f_i(\vec{x}_0)\right|,j=1,2,...,m\\
\therefore & \lim_{\vec{x}\to\vec{x}_0}f_j(\vec{x})=f_j(\vec{x}_0)\Rightarrow \forall \epsilon>0, \exists \delta>0, \forall 0<|\vec{x}-\vec{x}_0|<\delta\Rightarrow |f_j(\vec{x})-f_j(\vec{x}_0)|<\frac{\epsilon}{m}\Rightarrow |\vec{f}(\vec{x})-\vec{f}(\vec{x}_0)| \leq \sum_{i=1}^m \left|f_i(\vec{x})-f_i(\vec{x}_0)\right| <m \frac{\epsilon}{m}=\epsilon\\
\therefore & \lim_{\vec{x}\to\vec{x}_0}\vec{f}(\vec{x})=\vec{f}(\vec{x}_0)\Rightarrow \forall \epsilon>0, \exists \delta>0, \forall 0<|\vec{x}-\vec{x}_0|<\delta\Rightarrow |\vec{f}(\vec{x})-\vec{f}(\vec{x}_0)|<\epsilon\Rightarrow \left|f_j(\vec{x})-f_j(\vec{x}_0)\right| \leq |\vec{f}(\vec{x})-\vec{f}(\vec{x}_0)|<\epsilon\\
\end{aligned}

** 向量值函数复合

若 $\begin{cases}&\vec{f}(\vec{x})=\vec{y},\vec{x}\in D\subset R^n,\vec{y}\in R^m\\&\vec{g}(\vec{y})=\vec{z},\vec{x}\in \Omega\subset R^m,\vec{z}\in R^k\\\end{cases}$ 且 $\vec{y}\in \Omega$ 则两个函数可以复合 $\vec{f}\cdot\vec{g}(\vec{x})=\vec{f}(\vec{g}(\vec{x}))=\vec{z}$ 

*** <<MK6>>推论

若 $\begin{cases}&\vec{f}(\vec{x})=\vec{y},\vec{x}\in D\subset R^n,\vec{y}\in R^m\\&\vec{g}(\vec{y})=\vec{z},\vec{x}\in \Omega\subset R^m,\vec{z}\in R^k\\\end{cases}$ 且 $\vec{y}\in \Omega$ 且 $\vec{f}(\vec{x}),\vec{g}(\vec{y})$ 连续，则复合函数 $\vec{f}\cdot\vec{g}(\vec{x})=\vec{f}(\vec{g}(\vec{x}))=\vec{z}$ 也连续 

**** 证明

根据 $\vec{g}(\vec{y})$ 连续可得 $\forall \epsilon_1 >0,\exists \delta,\forall |\vec{y}-\vec{y}_0|<\delta,\vec{y},\vec{y}_0\in \Omega\Rightarrow |\vec{g}(\vec{y})-\vec{g}(\vec{y}_0)|<\epsilon_1$ 

根据 $\vec{f}(\vec{x})$ 连续可得 $\forall \epsilon_2 >0,\exists \alpha,\forall |\vec{x}-\vec{x}_0|<\alpha,\vec{x},\vec{x}_0\in D\Rightarrow |\vec{f}(\vec{x})-\vec{f}(\vec{x}_0)|<\epsilon_2$ 

则取 $\epsilon_2=\delta\Rightarrow \forall\epsilon_1, \exists \alpha_1, \forall |\vec{x}-\vec{x}_0|<\alpha_1,\vec{x},\vec{x}_0\in D\Rightarrow |\vec{f}(\vec{x})-\vec{f}(\vec{x}_0)|<\delta\Rightarrow |\vec{g}(\vec{f}(\vec{x}))-\vec{g}(\vec{f}(\vec{x}_0))|<\epsilon_1$

* 连续函数性质

** 补充边界点连续定义

若函数 $\vec{f}(\vec{x}), \vec{x}\in K \subset R^n$ 则 $\vec{f}(\vec{x})$ 在 $\vec{x}_0$ 点连续的定义为 $\forall \epsilon>0, \exists \delta, \forall \vec{x}\in O(x_0,\delta)\cap K\Rightarrow \left|\vec{f}(\vec{x})-\vec{f}(\vec{x}_0)\right|<\epsilon$

** 补充多元函数一致连续定义

若函数 $\vec{f}(\vec{x}), \vec{x}\in K \subset R^n$ 则 $\vec{f}(\vec{x})$ 一致连续的定义为 $\forall \epsilon>0, \exists \delta, \forall \vec{x}',\vec{x}''\in K, |\vec{x}'-\vec{x}''|<\delta \Rightarrow \left|\vec{f}(\vec{x}')-\vec{f}(\vec{x}'')\right|<\epsilon$

** 补充连通定义

*** 通路定义

存在一个连续映射 $\Gamma(x)=\vec{z},x\in [0,1],\vec{z}\in K$ ，则称集合 $\Gamma(x)$ 为集合 $K$ 中的一条通路

*** 连通集定义

若对于任意两点 $\vec{x},\vec{y}\in K\subset R^n$ 存在一个连续映射 $\Gamma(x)=\vec{z},x\in [0,1],\vec{z}\in K$ 且 $\Gamma(0)=\vec{x},\Gamma(1)=\vec{y}$ ，则称集合 $K$ 通路连通，或为连通集

** <<MK3>>紧集的连续映射（连续函数）也是紧集

若连续函数 $\vec{f}(\vec{x})=\vec{y}, \vec{x}\in K\subset R^n, S=\{\vec{y}\}\subset R^m$ 且 $K$ 是紧集，则 $S$ 也为紧集

*** 证明

对于任意无限点列 $\left\{\vec{y}_k=\vec{f}(\vec{x}_k)\big|\vec{y}_i\ne\vec{y}_i,i\ne j \right\} \subset S$ 因为 $\{\vec{x}_k\}\in K$ 为紧集，根据[[MK2][Heine-Borel定理推论]] $K$ 为有界闭集，故 $\{\vec{x}_k\}$ 有界，则存在 $\{\vec{x}_{k_i}\}\Rightarrow\lim_{i\to\infty} \vec{x}_{k_i}=\vec{a}$

又因为函数连续，则有 $\lim_{\vec{x}\to \vec{a}}\vec{f}(\vec{x})=\vec{f}(\vec{a})$ 即 $\lim_{i\to \infty}\vec{f}(\vec{x}_{k_i})=\vec{f}(\vec{a})$ 即 $\lim_{i\to \infty}\vec{y}_{k_i}=\vec{f}(\vec{a})$ 

根据定义 $\vec{a}$ 为 $K$ 的聚点，且 $K$ 为有界闭集，故 $\vec{a}\in K\Rightarrow \vec{f}(\vec{a})\in S$

故对于任意无限点列 $\left\{\vec{y}_k=\vec{f}(\vec{x}_k)\big|\vec{y}_i\ne\vec{y}_i,i\ne j \right\} \subset S$ 均存在聚点 $\vec{f}(\vec{a})\in S$ 根据[[MK2][Heine-Borel定理推论]]可得 $S$ 为紧集

** <<MK4>>有界性定理

若连续函数 $\vec{f}(\vec{x})=\vec{y}, \vec{x}\in K\subset R^n, S=\{\vec{y}\}\subset R^m$ 若 $K$ 为紧集， 则 $\vec{y}$ 有界

*** 证明

根据[[MK3][紧集映射]]可得 $S$ 亦为紧集，根据[[MK2][Heine-Borel定理推论]]可得 $S$ 为有界闭集，故 $\vec{y}\in S$ 有界

** 最大值定理

若连续函数 $\vec{f}(\vec{x})=\vec{y}, \vec{x}\in K\subset R^n, S=\{\vec{y}\}\subset R^m$ 若 $K$ 是紧集，

则必定 $\exists \vec{\eta}_i,\vec{\xi}_i\in S, f_i(\vec{\eta}_i) \leq f_i(\vec{x})\leq f_i(\vec{\xi}_i),i=1,2,...,m$

*** 证明

因为 $\lim_{\vec{x}\to \vec{x}_0}\vec{f}(\vec{x})=\vec{f}(\vec{x}_0)$ 故有 $\lim_{\vec{x}\to \vec{x}_0}\f_i(\vec{x})=f_i(\vec{x}_0)$ 故 $f_i(\vec{x})$ 亦连续，设 $f_i(\vec{x})=y_i,S_i=\{y_i\}$  

根据[[MK4][多元函数有界性定理]]可得映射 $S_i$ 有界闭集，故 $f_i(\vec{x})$ 有界

由于 $f_i(\vec{x})$ 映射结果为实数，故根据确界存在定理，有界必有确界。

上确界定义 $\forall \delta>0, \exists f_i(\vec{x})\Rightarrow f_i(\vec{x})\in \left(sup\{f_i(\vec{x})\}-\delta,sup\{f_i(\vec{x})\}\right]$ 故根据[[JDCYTJ1][聚点充要条件]]可得 $sup\{f_i(\vec{x})\}$ 为 $S_i$ 聚点

又因为 $S_i$ 为闭集，故 $sup\{f_i(\vec{x})\}\in S_i$

下确界同理，故 $\exists \vec{\eta}_i,\vec{\xi}_i\in S, f_i(\vec{\eta}_i) \leq f_i(\vec{x})\leq f_i(\vec{\xi}_i),i=1,2,...,m$

** 康托定理

若连续函数 $\vec{f}(\vec{x})=\vec{y}, \vec{x}\in K\subset R^n, S=\{\vec{y}\}\subset R^m$ 若 $K$ 是紧集，

则 $\vec{f}(\vec{x})$ 一致连续，此处添加一元函数[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][函数一致连续-康托定理]]的链接

*** 证明

因为连续，则对任意 $\vec{a}\in K$ 有 $\forall \epsilon>0,\exists \delta_{\vec{a}}, \forall \vec{x}\in O(\vec{a},\delta_{\vec{a}})\Rightarrow \left|\vec{f}(\vec{x})-\vec{f}(\vec{a})\right|<\frac{\epsilon}{2}$

取开覆盖 $\left\{O\left(\vec{a},\frac{\delta_{\vec{a}}}{2}\right)\big|\vec{a}\in K\right\}$ ，则根据[[MK5][紧集定义]]，必有有限子覆盖  $O_i\left(\vec{a}_i,\frac{\delta_{\vec{a}_i}}{2}\right),i=1,2,...,P$

取 $\delta=\min\left\{\frac{\delta_{\vec{a}_i}}{2}\right\},i=1,2,...,P$ 则若 $\vec{x}'\in O_i\left(\vec{a}_i,\frac{\delta_{\vec{a}_i}}{2}\right)$ 则有：

（1） $|\vec{x}'-\vec{a}|<\frac{\delta_{\vec{a}_i}}{2}<\delta_{\vec{a}_i}$

（2） $|\vec{x}''-\vec{a}|\leq |\vec{x}''-\vec{x}'|+|\vec{x}'-\vec{a}|<\frac{\delta_{\vec{a}_i}}{2}+\frac{\delta_{\vec{a}_i}}{2}=\delta_{\vec{a}_i}$

（3） $\left|\vec{f}(\vec{x}')-\vec{f}(\vec{x}'')\right| \leq \left|\vec{f}(\vec{x}')-\vec{f}(\vec{a})\right|+\left|\vec{f}(\vec{a})-\vec{f}(\vec{x}'')\right|<\frac{\epsilon}{2}+\frac{\epsilon}{2}$

证毕。

** 连通紧集的连续映射也是连通集

若连续函数 $\vec{f}(\vec{x})=\vec{y}, \vec{x}\in K\subset R^n, S=\{\vec{y}\}\subset R^m$ 且 $K$ 是连通集，则 $S$ 也为连通集

*** 证明

对于任意 $\vec{y}',\vec{y}''\in S$ 存在函数原相 $\vec{f}(\vec{x}')=\vec{y}',\vec{f}(\vec{x}'')=\vec{y}'',\{\vec{x}',\vec{x}''\}\subset K$ 因为 $K$ 为连通集，故存在连续映射 $\Gamma(u),u\in [0,1],\Gamma(0)=\vec{x}',\Gamma(1)=\vec{x}''$

根据[[MK6][向量值函数复合推论]]复合函数 $\vec{f}(\Gamma(u))=\vec{f}\cdot\Gamma(u)$ 亦为连续函数，且 $\vec{f}\cdot\Gamma(0)=\vec{y}',\vec{f}\cdot\Gamma(1)=\vec{y}''$ 故 $S$ 为连通集




 
