#+LATEX_CLASS: ctexart

#+TITLE: 含参变量积分

current mark: MK33

* <<MK27>>Cauchy-Bunyakovsky-Schwarz Inequality/Definite Integrals

$\left(\int_a^bf(t)g(t)dt\right)^2\leq\int_a^b(f(t))^2dt\int_a^b(g(t))^2dt$

** 证明

定义 $x\in R$ 则有 $0\leq \left(xf(t)+g(t)\right)^2$ 故根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-保序]]有 $0=\int_a^b0dt\leq\int_a^b\left(xf(t)+g(t)\right)^2dt$ 

故根据

\begin{aligned}
\int_a^b\left(xf(t)+g(t)\right)^2dt=&\int_a^b\left\{x^2(f(t))^2+2xf(t)g(t)+(g(t))^2\right\}dt\\
=&x^2\int_a^b(f(t))^2dt+2x\int_a^bf(t)g(t)dt+\int_a^b(g(t))^2dt\\
\end{aligned}

定义 $A=\int_a^b(f(t))^2dt,B=2\int_a^bf(t)g(t)dt,C=\int_a^b(g(t))^2dt$ 故有 $\forall x\in R\Rightarrow Ax^2+Bx+C\geq0$

则根据二元一次方程必有 $B^2-4AC\leq 0$ 故 $4\left(x\int_a^bf(t)g(t)dt\right)^2\leq4\int_a^b(f(t))^2dt\int_a^b(g(t))^2dt$

即 $\left(\int_a^bf(t)g(t)dt\right)^2\leq\int_a^b(f(t))^2dt\int_a^b(g(t))^2dt$ 证毕

* 含参变量常义积分

** <<MK1>>定义

定义有界闭区域 $D\in R^n$ ，定义 $\vec{x}=(x_1,x_2,...,x_i),\vec{y}=(y_1,y_2,...,y_j),\ i,j\in N^+,i+j=n$ ，定义函数 $f(\vec{x},\vec{y})$ 在 $D$ 上连续。

当给定 $\vec{y}$ 时定义区域 $\left\{S\big|\vec{x}\in D_{\vec{x}}\Rightarrow (\vec{x},\vec{y})\in D\right\}$ 且 $S$ 不随 $\vec{y}$ 变化而变化 则该区域上的重积分 $\int_{S}f(\vec{x},\vec{y})dv$ 的值与 $\vec{y}$ 有关

故定义 $I(\vec{y})=\int_{S}f(\vec{x},\vec{y})dv$

** <<MK4>>连续性定理

对于含参变量常义积分 $I(\vec{y})$ 在定义域上连续

*** 证明

欲证明连续，则需证明 $\lim_{\vec{y}\to\vec{y}_0}I(\vec{y})=I(\vec{y}_0)$

由于[[MK1][含参变量常义积分定义]]，被积函数 $f(\vec{x},\vec{y})$ 在区域 $D$ 上连续，又由于 $D$ 为有界闭区域，

故根据[[~/文档/note/数学分析/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-Heine-Borel定理]]得 $D$ 为紧集

又根据[[~/文档/note/数学分析/Chap11Note.org][连续函数性质-康托定理]]得 $f(\vec{x},\vec{y})$ 在区域 $D$ 上一致连续，定义积分区域 $S$ 的面积为 $V$

则根据[[~/文档/note/数学分析/Chap11Note.org][连续函数性质-补充多元函数一致连续定义]]

$\forall \epsilon>0, \exists \delta, \forall (\vec{x},\vec{y}_0),(\vec{x},\vec{y})\in d, |(\vec{x},\vec{y}_0)-(\vec{x},\vec{y})|<\delta \Rightarrow \left|f(\vec{x},\vec{y}_0)-f(\vec{x},\vec{y})\right|<\frac{\epsilon}{V}$

根据[[~/文档/note/数学分析/Chap13Note.org][重积分性质与计算-性质]]中[线性]，[当 $f(\vec{x})=1$ 时]，[保序性]以及[绝对可积性]得

\begin{aligned}
&\left|\int_S f(\vec{x},\vec{y}_0)dv - \int_S f(\vec{x},\vec{y})dv\right|\\
=&\left|\int_S f(\vec{x},\vec{y}_0)-f(\vec{x},\vec{y})dv\left|\\
\leq& \int_S \left|f(\vec{x},\vec{y}_0)-f(\vec{x},\vec{y})\right|dv\\
<&\int_S \frac{\epsilon}{V}dv\\
=&\frac{\epsilon}{V}S\\
=&\epsilon
\end{aligned}

*** <<MK2>>推论

由于连续，故有 $\lim_{\vec{y}\to\vec{y}_0}I(\vec{y})=I(\vec{y}_0)$

又因为 $f(\vec{x},\vec{y})$ 连续，则有 $\lim_{\vec{y}\to\vec{y}_0}f(\vec{x},\vec{y})=f(\vec{x},\vec{y}_0)$

故  $\lim_{\vec{y}\to\vec{y}_0}\int_{S}f(\vec{x},\vec{y})dv=\int_{S}f(\vec{x},\vec{y}_0)dv=\int_{S}\left\{\lim_{\vec{y}\to\vec{y}_0}f(\vec{x},\vec{y})\right\}dv$ 即积分与极限可互换次序

** <<MK7>>积分次序交换

若对含参变量积分 $I(\vec{y})$ 中的 $\vec{y}$ 再做积分，假设 $\vec{y}\in U$ 即 $\int_UI(\vec{y})dv =\int_U\left\{\int_S f(\vec{x},\vec{y})dv\right\}dv$

则有 $\int_U\left\{\int_S f(\vec{x},\vec{y})dv\right\}dv=\int_S\left\{\int_U f(\vec{x},\vec{y})dv\right\}dv$

*** 证明

由于[[MK1][含参变量常义积分定义]]，被积函数 $f(\vec{x},\vec{y})$ 在区域 $D$ 上连续，故根据[[~/文档/note/数学分析/Chap13Note.org][有界闭集上的重积分-多重积分-推论]]任意维度下子重积分均可积

故根据[[~/文档/note/数学分析/Chap13Note.org][重积分性质与计算-不规则区域上重积分]]重积分可化为累次积分。

又由于重积分 $\int_D f(\vec{x},\vec{y})dv$ 亦可积且能化为累次积分，且与 $\int_U\left\{\int_S f(\vec{x},\vec{y})dv\right\}dv,\int_S\left\{\int_U f(\vec{x},\vec{y})dv\right\}dv$ 所化累次积分相同

故 $\int_U\left\{\int_S f(\vec{x},\vec{y})dv\right\}dv=\int_S\left\{\int_U f(\vec{x},\vec{y})dv\right\}dv$

** <<MK3>>积分函数求导

若对含参变量积分 $I(\vec{y})$ 中的 $y_k$ 求导，则有 $\frac{\partial I(\vec{y})}{\partial y_k}=\int_S\frac{\partial f(\vec{x},\vec{y})}{\partial y_k}dv$

*** 证明

定义 $\vec{y}=(\vec{y}',y_k)$ ，故根据导数定义，[[~/文档/note/数学分析/Chap13Note.org][重积分性质与计算-性质]]中[线性]，以及[[MK2][连续性定义推论]]

\begin{aligned}
\frac{\partial I(\vec{y})}{\partial y_k}=&\lim_{\Delta y_k\to0}\frac{I(\vec{x},\vec{y}',y_k+\Delta y)-I(\vec{x},\vec{y}',y_k)}{\Delta y_k}\\
=&\lim_{\Delta y_k\to0}\frac{\int_Sf(\vec{x},\vec{y}',y_k+\Delta y)dv-\int_Sf(\vec{x},\vec{y}',y_k)dv}{\Delta y_k}\\
=&\lim_{\Delta y_k\to0}\frac{\int_Sf(\vec{x},\vec{y}',y_k+\Delta y)-f(\vec{x},\vec{y}',y_k)dv}{\Delta y_k}\\
=&\lim_{\Delta y_k\to0}\int_S\frac{f(\vec{x},\vec{y}',y_k+\Delta y)-f(\vec{x},\vec{y}',y_k)}{\Delta y_k}dv\\
=&\int_S\frac{\lim_{\Delta y_k\to0}f(\vec{x},\vec{y}',y_k+\Delta y)-f(\vec{x},\vec{y}',y_k)}{\Delta y_k}dv\\
=&\int_S\frac{\partial f(\vec{x},\vec{y})}{\partial y_k}dv
\end{aligned}

** 上下限积分函数

$f(x,y),f_y(x,y)=\frac{\partial f(x,y)}{\partial y}$ 在区域 $D=[a,b]\times[c,d]$ 上连续，且存在函数 $a(y),b(y)$ 在 $y\in[c,d]$ 上可导，

且有 $a\leq a(y)\leq b,a\leq b(y)\leq b$ ，若定义函数 $F(y)=\int_{a(y)}^{b(y)}f(x,y)dx$ ，

则函数在 $[c,d]$ 上可导，且有 $F'(y)=\int_{a(y)}^{b(y)}f_y(x,y)dx+f(b(y),y)b'(y)-f(a(y),y)a'(y)$

*** 证明

定义 $I(u,v,w)=\int_u^vf(x,w)dx$ 其中 $u=a(y),v=b(y),w(y)=y$ ，根据条件 $a(y),b(y)$ 可导 $w(y)$ 导数恒为 $1$

根据[[MK3][积分函数求导]] $\frac{\partial I(u,v,w)}{\partial w}=\int_u^vf_w(x,w)dx$ 由于 $f_y(x,y)$ 连续，又根据[[MK4][连续性定理]]可得 $\int_u^vf_w(x,w)dx$ 连续
 
定义 $\frac{\partial G(x,y)}{\partial x}=f(x,y)$ 即 $G(x,y)$ 是 $f(x,y)$ 关于 $x$ 的一个原函数，且根据条件 $f(x,y)$ 连续。

故根据[[~/文档/note/数学分析/Chap7Note.org][牛顿莱布尼茨公式]] $I(u,v,w)=\int_u^vf(x,w)dx=G(u,w)-G(v,w)$ 

则有 $\frac{\partial I(u,v,w)}{\partial u}=\frac{\partial G(u,w)}{\partial u}=f(u,w),\frac{\partial I(u,v,w)}{\partial v}=\frac{\partial -G(v,w)}{\partial u}=-f(u,w)$ 又由于 $f(x,y)$ 连续，故两个偏导函数连续

由于 $I(u,v,w)$ 的偏导数均连续，故根据[[~/文档/note/数学分析/Chap12Note.org][偏导数与全微分-可微条件]]函数在定义域上可微

综上所述，复合函数满足

（1） 分量函数 $a(y),b(y),w(y)$ 均可导

（2） 复合函数 $I(u,v,w)$ 对于定义域上的 $(u,v,w)$ 点均可微

故根据[[~/文档/note/数学分析/Chap12Note.org][多元复合函数求导-链式法则]] $\frac{\partial I(u,v,w)}{\partial y}=\frac{\partial I(u,v,w)}{\partial u}\frac{\partial u}{\partial y}+\frac{\partial I(u,v,w)}{\partial v}\frac{\partial v}{\partial y}+\frac{\partial I(u,v,w)}{\partial w}\frac{\partial w}{\partial y}$

则有 $\frac{dF(y)}{dy}=\frac{\partial I(u,v,w)}{\partial y}=\int_{a(y)}^{b(y)}f_y(x,y)dx+f(b(y),y)b'(y)-f(a(y),y)a'(y)$

* 含参变量的反常积分

** 无限区间

*** 定义

函数 $f(x,y)$ 在 $[a,\infty)\times[c,d]$ 上有定义且连续，若反常积分 $\int_a^\infty f(x,y)dx$ 对于任意 $y\in[c,d]$ 均收敛

则称 $I(y)=\int_a^\infty f(x,y)dx$ 是被积区间无限的含参变量的反常积分

*** <<MK5>>含参变量反常积分一致收敛定义

若 $I(y)=\int_a^\infty f(x,y)dx$ 是含参变量反常积分，若满足 $\forall\epsilon>0,\exists A_0>a,\forall A>A_0,\forall y\in[c,d]\Rightarrow \left|\int_A^\infty f(x,y)dx\right|<\epsilon$

则含参变量反常积分 $I(y)$ 关于 $y\in[c,d]$ 一致收敛

**** 补充非一致收敛定义

 $\exists\epsilon>0,\forall A_0>a,\exists A>A_0,\exists y\in[c,d]\Rightarrow \left|\int_A^\infty f(x,y)dx\right|>\epsilon$

*** 一致收敛判别法

**** 柯西收敛原理

若 $I(y)=\int_a^\infty f(x,y)dx$ 是含参变量反常积分 $\forall\epsilon>0,\exists A_0>a,\forall A''>A'>A_0,\forall y\in[c,d]\Rightarrow \left|\int_{A'}^{A''} f(x,y)dx\right|<\epsilon$

是含参变量反常积分一致收敛的充要条件

***** 证明

****** 充分性

若一致收敛，则有 $\forall\epsilon>0,\exists A_0>a,\forall A''>A'>A_0,\forall y\in[c,d]\Rightarrow \left|\int_{A'}^\infty f(x,y)dx\right|<\frac{\epsilon}{2},\left|\int_{A''}^\infty f(x,y)dx\right|<\frac{\epsilon}{2}$

\begin{aligned}
\left|\int_{A'}^{A''} f(x,y)dx\right|&=\left|\int_{A'}^\infty f(x,y)dx-\int_{A''}^\infty f(x,y)dx\right|\\
\leq&\left|\int_{A'}^\infty f(x,y)dx\right|+\left|\int_{A''}^\infty f(x,y)dx\right|\\
<&\epsilon
\end{aligned}

****** 必要性

已知 $\forall\epsilon>0,\exists A_0>a,\forall A''>A'>A_0,\forall y\in[c,d]\Rightarrow \left|\int_{A'}^{A''} f(x,y)dx\right|<\epsilon$

根据[[~/文档/note/数学分析/Chap8Note.org][区间无限反常积分收敛判别-柯西收敛原理-证明-必要]]可得在以上条件下 $\forall A>A_0,\forall y\in[c,d]\Rightarrow\left|\int_a^Af(x,y)dx-K(y)\right|<2\epsilon$

则有 $\forall\epsilon>0,\exists A_0>a,\forall A>A_0,\forall y\in[c,d]\Rightarrow \left|\int_a^Af(x,y)dx-K(y)\right|<\epsilon$ 根据[[~/文档/note/数学分析/Chap8Note.org][区间无限反常积分收敛判别-定义]]可得 $K(y)=\int_a^\infty f(x,y)dx=I(y)$

故 $\forall\epsilon>0,\exists A_0>a,\forall A>A_0,\forall y\in[c,d]\Rightarrow \left|\int_A^\infty f(x,y)dx\right|<\epsilon$

***** 推论1

若 $I(y)=\int_a^\infty f(x,y)dx$ 满足 $\exists\epsilon>0,\forall A_0>a,\exists A''>A'>A_0,\exists y\in[c,d]\Rightarrow \left|\int_{A'}^{A''} f(x,y)dx\right|>\epsilon$ 则含参变量反常积分 *非* 一致收敛

该命题为柯西收敛原理的逆命题

***** 推论2

若 $I(y)=\int_a^\infty f(x,y)dx$ 存在数列 $A'_n,A''_n,y_n$ 满足 $\lim_{n\to\infty}A'_n=\infty,\lim_{n\to\infty}A''_n=\infty$ 且 $y_n\in[c,d]\forall n\in N^+$ 使得 $\lim_{n\to\infty}\int_{A'_n}^{A''_n}f(x,y_n)dx\ne 0$

则含参变量反常积分 *非* 一致收敛

****** 证明

写出 $\lim_{n\to\infty}\int_{A'_n}^{A''_n}f(x,y_n)dx\ne0$ 的定义为 $\exists\epsilon>0,\forall N>0,\exists n>N\Rightarrow \left|\int_{A'_n}^{A''_n}f(x,y_n)dx\right|>\epsilon$

由于 $y_n\in[c,d]$ 故有 $\exists\epsilon>0,\forall N>0,\exists n>N,\exists y\in[c,d]\Rightarrow \left|\int_{A'_n}^{A''_n}f(x,y)dx\right|>\epsilon$

由于 $\lim_{n\to\infty}A'_n=\infty,\lim_{n\to\infty}A''_n=\infty$ 故 $\forall A_0>0,\exists N,\forall n>N\Rightarrow A'_n>A_0,A''_n>A_0$

故有 $\exists\epsilon>0,\forall A_0,\exists A''>A'>A_0,\exists y\in[c,d]\Rightarrow \left|\int_{A'}^{A''} f(x,y)dx\right|>\epsilon$ 

**** <<MK14>>Weierstrass判别

若 $|f(x,y)|\leq F(x),\forall x\in[a,\infty],y\in[c,d]$ 且 $\int_a^\infty F(x)dx$ 收敛，则有 $\int_a^\infty f(x,y)dx$ 一致收敛

***** 证明

由于 $\int_a^\infty F(x)dx$ 收敛，根据[[~/文档/note/数学分析/Chap8Note.org][区间无限反常积分收敛判别-柯西收敛原理]]可得 $\forall\epsilon>0,\exists A_0,\forall A''>A'>A_0\Rightarrow\left|\int_{A'}^{A''}F(x)dx\right|<\epsilon$

由于 $0\leq|f(x,y)|\leq F(x)$ 故有 $\forall\epsilon>0,\exists A_0,\forall A''>A'>A_0\Rightarrow\int_{A'}^{A''}F(x)dx<\epsilon$

根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-保序]]及[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-绝对可积]]可得 $\left|\int_{A'}^{A''}f(x,y)dx\right|\leq\int_{A'}^{A''}|f(x,y)|dx\leq\int_{A'}^{A''}F(x)dx$

**** Abel判别法

若含参变量反常积分 $I(y)=\int_a^\infty f(x,y)g(x,y)dx$ 满足

（1） $\int_a^\infty f(x,y)dx$ 关于 $y\in[c,d]$ 一致收敛

（2） $g(x,y)$ 对于给定 $y$ 关于 $x$ 单调，且 $\forall x\in[a,\infty),\forall y\in[c,d]\Rightarrow |g(x,y)|\leq L<\infty$

则 $I(y)$ 关于 $y\in[c,d]$ 一致收敛

***** 证明

根据[[MK5][一致收敛定义]]，条件（1）： $\forall\epsilon>0,\exists A_0,\forall A''>A'_A_0,\forall y\in[c,d]\Rightarrow \left|\int_{A'}^{A''}f(x,y)dx\right|<\frac{\epsilon}{2L}$

根据[[~/文档/note/数学分析/Chap8Note.org][积分中值定理-第二积分中值定理]]及条件（2）可得 $\forall y\in[c,d]$ 均有：

\begin{aligned}
\left|\int_{A'}^{A''}f(x,y)g(x,y)dx\right|=&\left|g(A',y)\int_{A'}^{\xi}f(x,y)dx+g(A'',y)\int_{\xi}^{A''}f(x,y)dx\right| &\xi\in[A',A'']\\
\leq&\left|g(A',y)\right|\left|\int_{A'}^{\xi}f(x,y)dx\right|+\left|g(A'',y)\right|\left|\int_{\xi}^{A''}f(x,y)dx\right| &\xi\in[A',A'']\\
<&L\frac{\epsilon}{2L}+L\frac{\epsilon}{2L}\\
=&\epsilon
\end{aligned}

**** <<MK9>>Dirichlet判别法

若含参变量反常积分 $I(y)=\int_a^\infty f(x,y)g(x,y)dx$ 满足

（1） $\forall A,\forall y\in[c,d]\Rightarrow\left|\int_a^A f(x,y)dx\right|\leq L$

（2） $g(x,y)$ 对于给定 $y$ 关于 $x$ 单调，且 $\forall\epsilon>0,\exists A,\forall a>A,\forall y\in[c,d]\Rightarrow|g(a,y)|<\epsilon$

则 $I(y)$ 关于 $y\in[c,d]$ 一致收敛

***** 证明

根据条件（2）： $\forall\epsilon>0,\exists A,\forall a>A,\forall y\in[c,d]\Rightarrow|g(a,y)|<\frac{\epsilon}{2L}$

根据[[~/文档/note/数学分析/Chap8Note.org][积分中值定理-第二积分中值定理]]及条件（1）可得 $\forall y\in[c,d]$ 均有：

\begin{aligned}
\left|\int_{A'}^{A''}f(x,y)g(x,y)dx\right|=&\left|g(A',y)\int_{A'}^{\xi}f(x,y)dx+g(A'',y)\int_{\xi}^{A''}f(x,y)dx\right| &\xi\in[A',A'']\\
\leq&\left|g(A',y)\right|\left|\int_{A'}^{\xi}f(x,y)dx\right|+\left|g(A'',y)\right|\left|\int_{\xi}^{A''}f(x,y)dx\right| &\xi\in[A',A'']\\
<&\frac{\epsilon}{2L}L+\frac{\epsilon}{2L}L\\
=&\epsilon
\end{aligned}

*** 一致收敛含参变量反常积分性质

定义数组 $a_n$ 满足 $a_0=a,\lim_{n\to\infty}a_n=\infty$ ，定义 $u_n(y)=\int_{a_n}^{a_{n+1}}f(x,y)dx$ 

则有函数项级数 $S(y)=I(y)=\int_a^\infty f(x,y)dx=\sum_{i=0}^\infty u_i(y)$ 另外定义 $S_n(y)=\sum_{i=1}^n u_i(y)$

则有以下性质

**** <<MK6>>引理

若含参变量反常积分一致收敛，对应级数亦一致收敛

***** 证明

已知 $\forall\epsilon>0,\exists A_0>a,\forall A>A_0,\forall y\in[c,d]\Rightarrow \left|\int_A^\infty f(x,y)dx\right|<\epsilon$

故取 $N$ 使得 $a_N>A_0$ 则有 $\forall n>N,\forall y\in[c,d]\Rightarrow\left|S_n(y)-S(y)\right|=\left|\sum_{i=a_n}^\infty u_n(y)\right|=\left|\int_{a_n}^\infty f(x,y)dx\right|<\epsilon$

根据[[~/文档/note/数学分析/Chap10Note.org][函数项级数-函数项级数一致收敛-定义]]，证毕。

**** <<MK17>>连续性

若 $I(y)=\int_a^\infty f(x,y)dx$ 是含参变量反常积分满足：

（1） $f(x,y)$ 在 $[a,\infty)\times[c,d]$ 上连续

（2） $I(y)$ 在 $[c,d]$ 上一致连续

则有 $I(y)$ 连续，且有 $\lim_{y\to y_0}\int_a^\infty f(x,y)dx = \int_a^\infty  \lim_{y\to y_0}f(x,y)dx$

***** 证明

根据[[MK4][连续性定理]]可得 $u(y)=\int_{a_n}^{a_{n+1}}f(x,y)dx$ 连续，根据[[MK6][引理]]及条件（2）可得级数 $S(y)$ 一致连续

根据[[~/文档/note/数学分析/Chap10Note.org][函数项级数-一致收敛性质-连续性]]可得 $S(y)$ 连续，即 $I(y)$ 连续

即 $\lim_{y\to y_0}\int_a^\infty f(x,y)dx=\lim_{y\to y_0} I(y) = I(y_0)=\int_a^\infty f(x,y_0)dx$

又根据条件（1）得 $\int_a^\infty f(x,y_0)dx=\int_a^\infty \lim_{y\to y_0}f(x,y)dx$

**** <<MK8>>可积性

若 $I(y)=\int_a^\infty f(x,y)dx$ 是含参变量反常积分满足：

（1） $f(x,y)$ 在 $[a,\infty)\times[c,d]$ 上连续

（2） $I(y)$ 在 $[c,d]$ 上一致收敛

则有 $I(y)$ 在 $[c,d]$ 上可积，且 $\int_c^d\int_a^\infty f(x,y)dxdy=\int_a^\infty\int_c^df(x,y)dydx$

***** 证明

根据[[MK4][连续性定理]]可得 $u(y)=\int_{a_n}^{a_{n+1}}f(x,y)dx$ 连续，根据[[MK6][引理]]及条件（2）可得级数 $S(y)$ 一致连续

根据[[~/文档/note/数学分析/Chap10Note.org][函数项级数-一致收敛性质-连续性]]可得 $\int_c^d S(y)dy = \sum_{i=1}^\infty \int_c^d dy\int_{a_i}^{a_{i+1}}f(x,y)dx$

根据[[MK7][常义积分次序交换]]可得 $\int_c^d dy\int_{a_i}^{a_{i+1}}f(x,y)dx = \int_{a_i}^{a_{i+1}}\int_c^df(x,y)dydx$

故 $\int_c^d I(y)dy = \sum_{i=1}^\infty \int_{a_i}^{a_{i+1}}\int_c^df(x,y)dydx = \int_a^\infty\int_c^df(x,y)dydx$

**** <<MK10>>可导性

若 $I(y)=\int_a^\infty f(x,y)dx$ 是含参变量反常积分满足：

（1） $f(x,y)$ 在 $[a,\infty)\times[c,d]$ 上连续

（2） $f_y(x,y)=\frac{\partial f(x,y)}{\partial y}$ 在 $[a,\infty)\times[c,d]$ 上连续

（3） $I(y)$ 在 $[c,d]$ 上点态收敛

（4） $\int_a^\infty f_y(x,y)dx$ 在 $[c,d]$ 上一致收敛

则有 $I'(y)=\int_a^\infty f_y(x,y)dx$

***** 证明

定义 $I_y(y) = \int_a^\infty f_y(x,y)dx$ 根据条件（2），（3），[[MK8][可积性]]及[[~/文档/note/数学分析/Chap7Note.org][牛顿莱布尼茨公式]] 

$\int_c^u I_y(y)dy=\int_a^\infty \int_c^uf_y(x,y)dydx = \int_a^\infty f(x,u)-f(x,c)dydx=I(u)+C$

故有 $\frac{\partial\int_c^uf(x)dx}{dx}=\frac{\partial(F(c)-F(u))}{dx}=f(u)$

故 $I'(u)=I_y(y)=\int_a^\inftyf_y(x,y)dx$

*** 经典例题（Dirichlet积分）

求 $I=\int_a^\infty \frac{\sin(x)}{x}dx$

**** 解

***** 定义含参变量积分并建立联系

定义 $f(x,\alpha)=e^{-\alphax}\frac{\sin(x)}{x}dx$ ，则有 $I(\alpha)=\int_a^\infty f(x,\alpha)dx=\int_a^\infty e^{-\alpha x}\frac{\sin(x)}{x}dx,\alpha\in[0,\infty)$

且定义 $f(0,\alpha) = 1$ 则有 $f(x,\alpha)$ 在 $[0,\infty)\times[0,1]$ 上连续

其中 $\int_0^\infty\sin(x)dx$ 有界，且由于 $\alpha\geq0$ 可推出 $\frac{e^{-\alpha x}}{x}$ 单调递减且 $\forall\alpha\in[0,\infty)\Rightarrow\lim_{x\to\infty}\frac{e^{-\alpha x}}{x}=0$

故根据[[MK9][Dirichlet判别]] $I(\alpha)$ 关于 $\alpha\in[0,1]$ 一致收敛

故有 $\lim_{\alpha\to 0}I(\alpha)=I(0)=I=\int_a^\infty \frac{\sin(x)}{x}dx$

***** 求导

取 $0<\alpha_0<1$ 当 $\alpha\in[\alpha_0,1]$ 时 $f_y(x,\alpha)=\frac{\partial f(x,\alpha)}{\partial\alpha}=-\sin(x)e^{-\alpha x}$

其中 $\int_0^\infty\sin(x)dx$ 有界，且由于 $\alpha\geq\alpha_0>0$ 可推出 $e^{-\alpha x}$ 单调递减且 $\forall\alpha\in[\alpha_0,\infty)\Rightarrow\lim_{x\to\infty}e^{-\alpha x}=0$

故根据[[MK9][Dirichlet判别]]可推出 $f_y(x,\alpha)$ 关于 $\alpha\in[\alpha_0,\infty)$ 一致收敛，其中 $\alpha_0$ 为 $(0,1]$ 间任意值。

故根据[[MK10][可导性]]能推出

\begin{aligned}
I'(\alpha) &= \int_0^\infty f_y(x,\alpha)dx&,\alpha\in[\alpha_0,\infty)\\
&=\int_0^\infty -\sin(x)e^{-\alpha x}dx&,\alpha\in[\alpha_0,\infty)\\
&=\int_0^\infty -\sin(x)e^{-\alpha x}dx&,\alpha\in[\alpha_0,\infty)\\
&=\frac{\alpha}{\alpha^2+1}\left[\sin(x)e^{-\alpha x}+\frac{1}{\alpha}\cos(x)e^{-\alpha x}\right]\bigg|_0^\infty&,\alpha\in[\alpha_0,\infty)\\
&=-\frac{1}{\alpha^2+1}&,\alpha\in[\alpha_0,\infty)\\
\end{aligned}

***** 求解

由于 $I'(\alpha)=-\frac{1}{1+\alpha^2}\Rightarrow I(\alpha)=-\arctan(\alpha)+C,\alpha\in[\alpha_0,\infty)$

由于 $|I(\alpha)|=\left|\int_0^\infty e^{-\alpha x}\frac{\sin(x)}{x}dx\right|\leq\int_0^\infty e^{-\alpha x}\left|\frac{\sin(x)}{x}\right|dx\leq\int_0^\infty e^{-\alpha x}dx=\frac{1}{\alpha}$

则有 $\lim_{\alpha\to\infty}|I(\alpha)| = 0$ 故根据夹逼定理 $\lim_{\alpha\to\infty}I(\alpha)=0$ 根据极限四则运算

\begin{aligned}
\lim_{\alpha\to\infty}I(\alpha)=&\lim_{\alpha\to\infty}\left{-\arctan(\alpha)+C\right}\\
=&\lim_{\alpha\to\infty}\left{-\arctan(\alpha)\right}+C\\
=&-\frac{\pi}{2}+C\\
=&0\\
\end{aligned}

则有 $C=\frac{\pi}{2}$

则有 $I(\alpha) = -\arctan(\alpha)+\frac{\pi}{2},\alpha\in[\alpha_0,\infty)$ 进一步当 $\alpha=\alpha_0$ 时 $I(\alpha_0) = -\arctan(\alpha_0)+\frac{\pi}{2}$

由于等式成立于 $\alpha_0\in(0,\infty)$ 则当 $\alpha_0\to0$ 时存在 $\lim_{\alpha_0\to0}I(\alpha_0)=\frac{\pi}{2}$

根据第一步有 $\lim_{\alpha\to 0}I(\alpha)=I(0)=I=\int_a^\infty \frac{\sin(x)}{x}dx=\frac{\pi}{2}$

** 无界函数

*** 定义

函数 $f(x,y)$ 在 $[a,b)\times[c,d]$ 上有定义且连续，若反常积分 $\int_a^b f(x,y)dx = \lim_{B\to b}\int_a^b f(x,y)dx$ 对于任意 $y\in[c,d]$ 均收敛

则称 $I(y)=\int_a^b f(x,y)dx$ 是被积区间无限的含参变量的反常积分

*** 一致收敛定义

若 $I(y)=\int_a^b f(x,y)dx$ 是含参变量反常积分，其中 $b$ 为奇点。若满足 $\forall\epsilon>0,\exists \eta_0>0,\forall \eta<\eta_0,\forall y\in[c,d]\Rightarrow \left|\int_{b-\eta}^b f(x,y)dx\right|<\epsilon$

*** 一致收敛判别法

**** 柯西收敛原理

若 $I(y)=\int_a^b f(x,y)dx$ 是含参变量反常积分 $\forall\epsilon>0,\exists \eta>0,\forall \eta''<\eta'<\eta,\forall y\in[c,d]\Rightarrow \left|\int_{b-\eta'}^{b-\eta''} f(x,y)dx\right|<\epsilon$

是含参变量反常积分一致收敛的充要条件

***** 证明

****** 充分

$I(y)=\int_a^b f(x,y)dx$ 收敛，则有 $\forall\epsilon>0,\exists \eta>0,\forall \eta''<\eta'<\eta,\forall y\in[c,d]\Rightarrow \left|\int_{\eta'}^b f(x,y)dx\right|<\frac{\epsilon}{2},\left|\int_{\eta''}^b f(x,y)dx\right|<\frac{\epsilon}{2}$ 则有

\begin{aligned}
\left|\int_{b-\eta'}^{b-\eta''} f(x,y)dx\right|&=\left|\int_{b-\eta'}^{b} f(x,y)dx-\int_{b-\eta''}^{b} f(x,y)dx\right|\\
&\leq \left|\int_{b-\eta'}^{b} f(x,y)dx\right|+\left|\int_{b-\eta''}^{b} f(x,y)dx\right|\\
&<\frac{\epsilon}{2}+\frac{\epsilon}{2}=\epsilon
\end{aligned}

****** 必要

已知 $\forall\epsilon>0,\exists \eta_0>0,\forall \eta''<\eta'<\eta_0,\forall y\in[c,d]\Rightarrow \left|\int_{b-\eta'}^{b-\eta''} f(x,y)dx\right|<\epsilon$

根据[[~/文档/note/数学分析/Chap8Note.org][无界函数反常积分收敛判别-柯西收敛原理-证明-必要]]可得在以上条件下 $\forall \eta<\eta_0,\forall y\in[c,d]\Rightarrow\left|\int_a^{b-\eta} f(x,y)dx-K(y)\right|<2\epsilon$

则有 $\forall\epsilon>0,\exists \eta_0>0,\forall \eta<\eta_0,\forall y\in[c,d]\Rightarrow \left|\int_a^{b-\eta}f(x,y)dx-K(y)\right|<\epsilon$ 根据[[~/文档/note/数学分析/Chap8Note.org][无界函数反常积分收敛判别-定义]]可得 $K(y)=\int_a^b f(x,y)dx=I(y)$

故 $\forall\epsilon>0,\exists \eta_0>a,\forall \eta<\eta_0,\forall y\in[c,d]\Rightarrow \left|\int_{b-\eta}^b f(x,y)dx\right|<\epsilon$
**** <<MK12>>Weierstrass判别

若 $|f(x,y)|\leq F(x),\forall x\in[a,b),y\in[c,d]$ 且 $\int_a^b F(x)dx$ 收敛，则有 $\int_a^b f(x,y)dx$ 一致收敛

***** 证明

由于 $\int_a^b F(x)dx$ 收敛，根据[[~/文档/note/数学分析/Chap8Note.org][无界函数反常积分收敛判别-柯西收敛原理]]可得 $\forall\epsilon>0,\exists \eta_0,\forall \eta''<\eta'<\eta_0\Rightarrow\left|\int_{b-\eta'}^{b-\eta''}F(x)dx\right|<\epsilon$

由于 $0\leq|f(x,y)|\leq F(x)$ 故有 $\forall\epsilon>0,\exists \eta_0,\forall\eta''<\eta'<\eta_0\Rightarrow\int_{b-\eta'}^{b-\eta''}F(x)dx<\epsilon$

根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-保序]]及[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-绝对可积]]可得 $\left|\int_{b-\eta'}^{b-\eta''}f(x,y)dx\right|\leq\int_{b-\eta'}^{b-\eta''}|f(x,y)|dx\leq\int_{b-\eta'}^{b-\eta''}F(x)dx$

* 欧拉积分

** Beta函数

*** <<MK21>>定义

$\beta(p,q)=\int_0^1x^{p-1}(1-x)^{q-1}dx$

*** 定义域（敛散性）

$\beta(p,q)$ 定义域为 $(p,q)\in(0,\infty)\times(0,\infty)$

**** <<MK11>>证明
函数为无界反常积分，奇点为 $x=0,x=1$ ，故写为 $\beta(p,q)=\int_0^{\frac{1}{2}}x^{p-1}(1-x)^{q-1}dx+\int_{\frac{1}{2}}^1x^{p-1}(1-x)^{q-1}dx$

***** 第一部分 

显然 $\int_0^{\frac{1}{2}}x^{p-1}(1-x)^{q-1}dx$ 奇点在 $x=0$

由于 $x^{p-1}(1-x)^{q-1}$ 在定义域上为非负函数 $\frac{1}{2}x^{p-1}\leq x^{p-1}(1-x)^{q-1}\leq x^{p-1},\ x\in\left(0,\frac{1}{2}\right]$ 且 $\int_a^{\frac{1}{2}}x^{p-1}dx$ 为 $p$ 积分

故有 $\int_a^{\frac{1}{2}}x^{p-1}dx=\begin{cases}\frac{2^p}{p}-\frac{a^p}{p}&p\ne0\\\ln(\frac{1}{2})-\ln(a)&p=0\end{cases}$ 故 $\lim_{a\to0}\int_a^{\frac{1}{2}}x^{p-1}dx$ 在 $p>0$ 时收敛 $p\leq0$ 时发散。

则根据[[~/文档/note/数学分析/Chap8Note.org][无界函数反常积分收敛判别-非负反常积分判别法-比较判别法]]当且仅当 $p>0$ 时 $\int_0^{\frac{1}{2}}x^{p-1}(1-x)^{q-1}dx$ 收敛

***** 第二部分

同理可证当且仅当 $q>0$ 时 $\int_{\frac{1}{2}}^1x^{p-1}(1-x)^{q-1}dx$

***** 结论

故Beta函数定义域为 $(p,q)\in(0,\infty)\times(0,\infty)$

*** 连续性

$\beta(p,q)$ 在 $(p,q)\in(0,\infty)\times(0,\infty)$ 上连续

**** 证明

定义 $p_0>0,q_0>0$ 可得区域 $[p_0,\infty)\times[q_0,\infty)$ 则有 $\left|x^{p-1}(1-x)^{q-1}\right|\leq x^{p_0-1}(1-x)^{q_0-1},x\in(0,1)$

由于[[MK11][敛散性证明]]中已证 $\int_0^1x^{p_0-1}(1-x)^{q_0-1}dx$ 在 $p_0>0,q_0>0$ 上收敛

故根据[[MK12][Weierstrass判别]] $\beta(p,q)=\int_0^1x^{p-1}(1-x)^{q-1}dx$ 在 $[p_0,\infty)\times[q_0,\infty)$ 上一致收敛

*** <<MK23>>对称性

$\beta(p,q)=\beta(q,p)$

**** 证明

$\beta(p,q)=\int_0^1x^{p-1}(1-x)^{q-1}dx$ 变量代还 $t=x-1\Rightarrow dx=-dt$ 则有

\begin{aligned}
\int_0^1x^{p-1}(1-x)^{q-1}dx=&\int_1^0(t-1)^{p-1}t^{q-1}-dt\\
=&\int_0^1t^{q-1}(t-1)^{p-1}dt
\end{aligned}

*** 递推公式

$\beta(p,q)=\frac{q-1}{p+q-1}\beta(p,q-1),\ (p,q)\in(0,\infty)\times(1,\infty)$

**** 证明

\begin{aligned}
\beta(p,q)=&\int_0^1x^{p-1}(1-x)^{q-1}dx\\
=&\frac{1}{p}\int_0^1(1-x)^{q-1}dx^p\\
=&\frac{1}{p}\left\{x^p(1-x)^{q-1}\bigg|_0^1+(q-1)\int_0^1x^p(1-x)^{q-2}dx\right\}&\because q>1\Rightarrow x^p(1-x)^{q-1}\bigg|_0^1=0\\
=&\frac{q-1}{p}\int_0^1x^{p-1}(x+1-1)(1-x)^{q-2}dx\\
=&\frac{q-1}{p}\left\{\int_0^1x^{p-1}(1-x)^{q-2}dx-\int_0^1x^{p-1}(1-x)^{q-1}dx\right\}\\
=&\frac{q-1}{p}\left\{\beta(p,q-1)-\beta(p,q)\right\}
\end{aligned}

整理得 $\beta(p,q)=\frac{q-1}{p+q-1}\beta(p,q-1)$

*** 其他表示

**** <<MK19>>三角函数

变量代还 $x=\cos^2(\phi)$ 得 $\beta(p,q)=2\int_0^{\frac{\pi}{2}}\cos^{2p-1}(\phi)\sin^{2q-1}(\phi)d\phi$

**** <<MK22>>分式

变量代还 $x=\frac{1}{1+t}$ 得 $dx=-(1+t)^{-2}dt$

\begin{aligned}
\beta(p,q)=&\int_0^1x^{p-1}(1-x)^{q-1}dx\\
=&\int_\infty^0-\frac{1}{(1+t)^{p-1}}\frac{t^{q-1}}{(1+t)^{q-1}}\frac{1}{(1+t)^2}dt\\
=&\int_0^\infty\frac{t^{q-1}}{(1+t)^{q+p}}dt\\
=&\int_0^1\frac{t^{q-1}}{(1+t)^{q+p}}dt+\int_1^\infty\frac{t^{q-1}}{(1+t)^{q+p}}dt\\
\end{aligned}

其中第二部分令 $t=\frac{1}{u}$ 得 $dt=-\frac{1}{u^2}du$

\begin{aligned}
\beta(p,q)=&\int_0^1\frac{t^{q-1}}{(1+t)^{q+p}}dt+\int_1^\infty\frac{t^{q-1}}{(1+t)^{q+p}}dt\\
=&\int_0^1\frac{t^{q-1}}{(1+t)^{q+p}}dt + \int_1^0-\frac{\frac{1}{u^{q-1}}}{\left(\frac{1+u}{u}\right)^{q+p}}\frac{1}{u^2}du\\
=&\int_0^1\frac{t^{q-1}}{(1+t)^{q+p}}dt + \int_0^1\frac{u^{p-1}}{(1+u)^{q+p}}du\\
=&\int_0^1\frac{t^{q-1}}{(1+t)^{q+p}}dt + \int_0^1\frac{t^{p-1}}{(1+t)^{q+p}}dt\\
=&\int_0^1\frac{t^{q-1}+t^{p-1}}{(1+t)^{q+p}}dt
\end{aligned}

** Gamma函数

*** 定义

$\Gamma(s)=\int_0^\infty x^{s-1}e^{-x}dx$

*** 定义域（收敛域）

$\Gamma(s)$ 定义域为 $s\in(0,\infty)$

**** 证明

反常积分，当 $x\to\infty$ 时为区间无限反常积分，当 $x\to0$ 时可能为无界函数反常积分，

故根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-区间可加]]分割积分区域 $\Gamma(s)=\int_0^1 x^{s-1}e^{-x}dx+\int_1^\infty x^{s-1}e^{-x}dx$

***** 第一部分

由于当 $x\in(0,1]$ 时 $x^{s-1}e^{-x}>0,x^{s-1}>0$ 且有 $\left|x^{s-1}e^{-x}\right|\leq x^{s-1}$

根据[[MK11][之前证明]]可得积分 $\int_0^{1}x^{p-1}dx$ 当 $0<p<1$ 时为反常积分，积分收敛。当 $p\geq 1$ 时为常义积分，可积。

故根据[[~/文档/note/数学分析/Chap8Note.org][无界函数反常积分收敛判别-非负反常积分判别法-比较判别法]]当 $s>0$ 时 $\int_0^1 x^{s-1}e^{-x}dx$ 存在

***** <<MK13>>第二部分

$\int_1^\infty x^{s-1}e^{-x}dx=\int_1^\infty \frac{1}{x^2}\frac{x^{s+1}}{e^x}dx$ 定义 $f(x)=\frac{1}{x^2},g(x)=\frac{x^{s+2}}{e^x}$

则有 $g'(x)=\frac{(s+2)x^{s+1}e^x-x^{s+2}e^x}{e^{2x}}=\frac{x^{s+1}(s+2-x)}{e^x}$ 故当 $x>s+2$ 时 $g(x)$ 单调递减

由于当 $x\in[1,s+2]$ 时 $x^{s-1}e^{-x}$ 连续，故根据[[~/文档/note/数学分析/Chap7Note.org][定积分可积定理-定积分可积充要条件2-推论1]]若 $s>1$ 则 $\int_1^{s+2} x^{s-1}e^{-x}dx$ 必可积

对于 $\int_1^\infty \frac{1}{x^2}\frac{x^{s+1}}{e^x}dx$

（1） $\forall A>s+2,\forall s>0\Rightarrow\int_{s+2}^A\frac{1}{x^2}dx=-\frac{1}{x}\big|_{s+2}^A=\frac{1}{s+2}-\frac{1}{A}$ 有界

（2） $\lim_{x\to\infty}\frac{x^{2s}}{e^x}=0$ （幂函数阶小于指数函数，可用洛必达法则证明）且单调

则根据[[~/文档/note/数学分析/Chap8Note.org][区间无限反常积分收敛判别-一般函数（不定号）反常积分判别法-Dirichlet]] $\int_s^\infty \frac{1}{x}\frac{x^s}{e^x}dx$ 对于任意 $s$ 收敛

根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-区间可加]] $\int_1^\infty \frac{1}{x}\frac{x^s}{e^x}dx$ 对于任意 $s$ 收敛

***** 结论

故当 $s>1$ 是Gamma函数收敛，故定义域 $s\in(0,\infty)$

*** 一致收敛域

函数：

（1） $\Gamma(s)=\int_0^\infty x^{s-1}e^{-x}dx$ 

（2） $\int_0^\infty x^{s-1}e^{-x}(\ln(x))^ndx$ 

均对 $(0,\infty)$ 内闭一致收敛

**** 证明

***** 函数（1）

定义 $[a,b]$ 其中 $a>0,b<\infty$ 同样根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-区间可加]]分割积分区域

$\int_0^\infty x^{s-1}e^{-x}dx=\int_0^1 x^{s-1}e^{-x}dx+\int_1^\infty x^{s-1}e^{-x}dx$

****** 第一部分

由于 $\left|x^{s-1}e^{-x}\right|\leq x^{a-1}$ 由于 $a>0$ 根据[[MK11][之前证明]] $\int_0^1 x^{a-1}dx$ 收敛

故根据[[MK12][Weierstrass判别]] $\int_0^1 x^{s-1}e^{-x}dx$ 对于 $s\in[a,b]$ 一致收敛

****** 第二部分

由于 $\left|x^{s-1}e^{-x}\right|\leq x^{b-1}e^{-x}$ 对于 $\int_1^\infty x^{b-1}e^{-x}dx$ 根据[[MK13][之前证明]]可得反常积分收敛

故根据[[MK14][Weierstrass判别]]有 $\int_1^\infty x^{s-1}e^{-x}dx$ 关于 $s\in[a,b]$ 一致收敛

***** 函数（2）

定义 $[a,b]$ 其中 $a>0,b<\infty$ 同样根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-区间可加]]分割积分区域

$\int_0^\infty x^{s-1}e^{-x}dx=\int_0^1 x^{s-1}e^{-x}(\ln(x))^ndx+\int_1^\infty x^{s-1}e^{-x}(\ln(x))^ndx$

****** 第一部分

由于 $|x^{s-1}e^{-x}(\ln(x))^n|\leq x^{a-1}|(\ln(x))^n|=x^{0.5a-1}\frac{|(\ln(x))^n|}{x^{-0.5a}}=x^{0.5a-1}\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|$

******* <<MK15>>证明 $\lim_{x\to0}\frac{(\ln(x))^{n}}{x^{-0.5a}}=0$ 

定义 $f(x)=(\ln(x))^n,g(x)=x^{-a}$ 根据定义域有 $0.5a>0$ ，下面用数学归纳法求极限

******** 当 $n=1$ 时

$f'(x)=\frac{1}{x},g'(x)=-0.5ax^{-0.5a-1}$ 故有 $\frac{f'(x)}{g'(x)}=\frac{1}{-0.5ax^{-0.5a}}=\frac{x^{0.5a}}{-0.5a}$ 由于

（1） $\lim_{x\to0^+}g(x)=\lim_{x\to0^+}x^{-0.5a}=\infty$

（2） $\lim_{x\to0^+}\frac{f'(x)}{g'(x)}=0$

故根据[[~/文档/note/大学物理/Note/DiffEq.org][洛必达法则]]有 $\lim_{x\to0^+}\frac{f(x)}{g(x)}=\lim_{x\to0^+}\frac{f'(x)}{g'(x)}$ 即 $\lim_{x\to0^+}\frac{(\ln(x))^n}{x^{-0.5a}}=\lim_{x\to0^+}\frac{x^{0.5a}}{-0.5a}=0$ 

******** 当 $n>1$ 时

$f'(x)=n(\ln(x))^{n-1}\frac{1}{x},g'(x)=-0.5ax^{-0.5a-1}$ 故有 $\frac{f'(x)}{g'(x)}=\frac{n(\ln(x))^{n-1}}{-0.5ax^{-0.5a}}$ 

根据极限四则运算 $\lim_{x\to0}\frac{f'(x)}{g'(x)}=\frac{n}{-0.5a}\lim_{x\to0}\frac{(\ln(x))^{n-1}}{x^{-0.5a}}$ 

同理 $\lim_{x\to0^+}g(x)=\lim_{x\to0^+}x^{-0.5a}=\infty$ 故若 $\lim_{x\to0}\frac{(\ln(x))^{n-1}}{x^{-0.5a}}=0$ 

则根据[[~/文档/note/大学物理/Note/DiffEq.org][洛必达法则]]有 $\lim_{x\to0^+}\frac{f(x)}{g(x)}=\lim_{x\to0^+}\frac{f'(x)}{g'(x)}=0$

******** 结论

综上说书，对于任意 $n\in N^+,N<\infty$ 均有 $\lim_{x\to0}\frac{(\ln(x))^{n}}{x^{-s}}=0$ 

******* <<MK16>>证明 $\int_0^1x^{0.5a-1}\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|dx$ 收敛

定义 $g(x)=\frac{(\ln(x))^n}{x^{-0.5a}}$ 由于当 $x\in(0,1]$ 时 $\ln(x)\leq0,x^{-0.5a}>0$ 

故 $g(x)$ 定号则有 $|g(x)|=\begin{cases}g(x)&n\ even\\-g(x)&n\ odd\end{cases}$ 所以若 $g(x)$ 在 $x\in[\alpha,\beta]$ 上单调 $|g(x)|$ 在此区间亦单调

求导得 $g'(x)=x^{0.5a-1}(\ln(x))^{n-1}\left[0.5a\ln(x)+n\right]$，此时 $n\geq1,a>0$

由于 $\lim_{x\to0^+}\ln(x)=-\infty$ 故对于 $\epsilon=\frac{n}{0.5a},\exists\delta,\forall0<x<\delta\Rightarrow\ln(x)<\epsilon$ 

由于 $x^{0.5a-1}(\ln(x))^{n-1}$ 在 $x\in(0,1]$ 间不变号，故当 $x<\delta$ 时 $g'(x)$ 不变号，即 $g(x)$ 单调

由于 $\ln(x)$ 当且仅当 $x<0$ 时为负，且 $\frac{n}{0.5a}>0$ 故必有 $0<\delta<1$ 

则根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-区间可加]]分割积分 $\int_0^1x^{0.5a-1}\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|dx=\int_0^\delta x^{0.5a-1}\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|dx+\int_\delta^1x^{0.5a-1}\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|dx$
由于 $x^{0.5a-1}\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|dx$ 在 $[\delta,1]$ 上连续，

故根据根据[[~/文档/note/数学分析/Chap7Note.org][定积分可积定理-定积分可积充要条件2-推论1]] $\int_\delta^1x^{0.5a-1}\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|dx$ 可积

另一方面由于 $\int_0^\delta x^{0.5a-1}\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|dx$ 满足

（1） 根据[[MK11][之前证明]]可得 $F(A)=\int_A^1x^{0.5a-1}dx,A\in(0,1],a>0$ 有界

（2） $\lim_{x\to0}\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|=0$ 且 $\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|$ 在 $x\in(0,\delta]$ 上单调

则根据[[~/文档/note/数学分析/Chap8Note.org][无界函数反常积分收敛判别-一般函数（不定号）反常积分判别法-Dirichlet]] $\int_0^\delta x^{0.5a-1}\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|dx$ 收敛

故 $\int_0^1x^{0.5a-1}\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|dx$ 收敛

******* 结论

由于 $|x^{s-1}e^{-x}(\ln(x))^n|\leq x^{a-1}|(\ln(x))^n|=x^{0.5a-1}\frac{|(\ln(x))^n|}{x^{-0.5a}}=x^{0.5a-1}\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|$

且 $\int_0^1x^{0.5a-1}\left|\frac{(\ln(x))^n}{x^{-0.5a}}\right|dx$ 收敛，故根据[[MK12][Weierstrass判别]] $\int_0^1 x^{s-1}e^{-x}(\ln(x))^ndx$ 关于 $s\in[a,b]$ 一致收敛

****** 第二部分

由于 $|x^{s-1}e^{-x}(\ln(x))^n|\leq x^{b-1}e^{-x}(\ln(x))^n,x\in[1,\infty)$ 

$x^{b-1}e^{-x}|(\ln(x))^n|=\frac{1}{x^2}\frac{x^{b+1}(\ln(x))^n}{e^x}$ 定义 $f(x)=\frac{1}{x^2},g(x)=\frac{x^{b+1}(\ln(x))^n}{e^x}$

根据[[MK15][之前证明]]可同理得 $\lim_{x\to\infty}g(x)=0$

由于 $g'(x)=\frac{x^b(\ln(x))^{n-1}[\ln(x)(b+1-x)-n]}{e^x}$ 根据[[MK16][之前证明]]同理可得存在 $\delta$ 使得 $g(x)$ 在 $x>\delta$ 上单调

又有 $\forall A>s+2,\forall s>0\Rightarrow\int_{s+2}^A\frac{1}{x^2}dx=-\frac{1}{x}\big|_{s+2}^A=\frac{1}{s+2}-\frac{1}{A}$ 有界

故根据[[~/文档/note/数学分析/Chap8Note.org][无界函数反常积分收敛判别-一般函数（不定号）反常积分判别法-Dirichlet]]得 $\int_1^\infty x^{b-1}e^{-x}(\ln(x))^ndx$ 收敛

故根据[[MK14][Weierstrass判别]]有 $\int_1^\infty x^{s-1}e^{-x}(\ln(x))^2dx$ 关于 $s\in[a,b]$ 一致收敛

**** <<MK28>>推论1：连续

由于 $\Gamma(s)=\int_0^\infty x^{s-1}e^{-x}dx$ 中：

（1） $x^{s-1}e^{-x}$ 在 $(x,s)\in[0,\infty)\times(0,\infty)$ 上内闭连续

（2） $\Gamma(s)$ 在 $(0,\infty)$ 内闭一致收敛

故根据[[MK17][连续性]] $\Gamma(s)$ 在 $(0,\infty)$ 上连续 

**** 推论2：可导

对于 $x^{s-1}e^{-x}$ 的 $n$ 次导数为 $x^{s-1}e^{-x}(\ln(x))^n$ 由于

（1） $x^{s-1}e^{-x}(\ln(x))^n$ 在 $(x,s)\in[0,\infty)\times(0,\infty)$ 上内闭连续

（2） $x^{s-1}e^{-x}$ 在 $(x,s)\in[0,\infty)\times(0,\infty)$ 上内闭连续

（3） $\int_0^\infty x^{s-1}e^{-x}(\ln(x))^ndx$ 在 $(0,\infty)$ 内闭一致收敛

（4） $\int_0^\infty x^{s-1}e^{-x}dx$ 在 $(0,\infty)$ 点态收敛

故根据[[MK10][可导性]]得 $\Gamma^{(n)}(s)=\int_0^\infty x^{s-1}e^{-x}(\ln(x))^nxdx$ 对于 $s\in(0,\infty)$ 成立

*** 性质

**** <<MK29>> $\ln(\Gamma(s))$ 为凸函数

根据[[MK28][之前证明]] $\Gamma(s)$ 在定义域上连续，故 $\ln(\Gamma(s))$ 亦为定义域上连续函数 

根据凸函数定义，对于任意 $x,y$ 在定义域内有 $f\left(\frac{x+y}{2}\right)\leq \frac{1}{2}f(x)+\frac{1}{2}f(y)$

***** 证明

根据[[MK27][不等式]]若定义 $0<\delta<\Delta$ 则有 

\begin{aligned}
\left(\int_\delta^\Delta x^{\frac{s+t}{2}-1}e^{-x}dx\right)^2=&\left(\int_\delta^\Delta\left(x^{\frac{s-1}{2}}e^{\frac{-x}{2}}\right)\left(x^{\frac{t-1}{2}}e^{\frac{-x}{2}}\right)dx\right)^2\\
\leq&\int_\delta^\Delta x^{s-1}e^{-x}dt\int_\delta^\Delta x^{t-1}e^{-x}dt
\end{aligned}

根据极限四则运算 $\lim_{\delta\to0,\Delta\to\infty}\left\{\int_\delta^\Delta x^{\frac{s+t}{2}-1}e^{-x}dx\right\}^2\leq\lim_{\delta\to0,\Delta\to\infty}\left\{\int_\delta^\Delta x^{s-1}e^{-x}dt\int_\delta^\Delta x^{t-1}e^{-x}dt\right\}$

即为 $\left(\Gamma\left(\frac{s+t}{2}\right)\right)^2\leq\Gamma(t)\Gamma(s)$ 取对数得

\begin{aligned}
\ln\left(\left(\Gamma\left(\frac{s+t}{2}\right)\right)^2\right)\leq&\ln\left(\Gamma(t)\Gamma(s)\right)\\
2\ln\left(\left(\Gamma\left(\frac{s+t}{2}\right)\right)\right)\leq&\ln\left(\Gamma(t)\right)+\ln\left(\Gamma(t)\right)\\
\ln\left(\left(\Gamma\left(\frac{s+t}{2}\right)\right)\right)\leq&\frac{1}{2}\ln\left(\Gamma(t)\right)+\frac{1}{2}\ln\left(\Gamma(t)\right)\\
\end{aligned}

故 $\ln(\Gamma(s))$ 为凸函数

*** 递推公式

$\Gamma(s+1)=s\Gamma(s)$

**** 推导

\begin{aligned}
\Gamma(s+1)=&\int_0^\infty x^{s}e^{-x}dx\\
&=\int_0^\infty -x^{s}de^{-x}\\
&=-e^{-x}x^{s}\big|_0^\infty+s\int_0^\infty x^{s-1}e^{-x}dx\\
&=s\Gamma(s)
\end{aligned}

**** 推论

$\Gamma(n+1)=n!$

*** 其他表示

**** <<MK18>>变量代换 $x=t^2$

$\Gamma(s)=\int_0^\infty x^{s-1}e^{-x}dx=2\int_0^\infty t^{2s-1}e^{-t^2}dt$

**** 变量代换 $x=at$

$\Gamma(s)=\int_0^\infty x^{s-1}e^{-x}dx=a^s\int_0^\infty t^{s-1}e^{-at}dt$

** <<MK20>>Beta函数与Gamma函数关系

$\beta(p,q)=\frac{\Gamma(p)\Gamma(q)}{\Gamma(p+q)}$

*** 证明

**** 转换为重积分

根据[[MK18][之前证明]]可得 $\Gamma(p)=2\int_0^\infty t^{2p-1}e^{-t^2}dt,\Gamma(q)=2\int_0^\infty t^{2q-1}e^{-t^2}dt$

则有 $\Gamma(p)\Gamma(q)=4\int_0^\infty s^{2p-1}e^{-s^2}ds\int_0^\infty t^{2q-1}e^{-t^2}dt=4\int_0^\infty\int_0^\infty s^{2p-1}t^{2q-1}e^{-s^2-t^2}dsdt$ 满足

（1） 函数 $f(s,t)=s^{2p-1}t^{2q-1}e^{-s^2-t^2}$ 连续

（2） $\int_0^\infty\int_0^\infty s^{2p-1}t^{2q-1}e^{-s^2-t^2}dsdt$ 以及 $\int_0^\infty\int_0^\infty\left|s^{2p-1}t^{2q-1}e^{-s^2-t^2}\right|dsdt$ 均收敛

故根据[[~/文档/note/数学分析/Chap13Note.org][反常重积分-区域无限反常重积分-区域无限反常重积分计算]]以及[[~/文档/note/数学分析/Chap13Note.org][反常重积分-无界函数反常重积分-无界反常重积分计算]]

定义 $D=(0,\infty)\times(0,\infty)$ 则有累次反常积分等于反常重积分 $\int_0^\infty\int_0^\infty s^{2p-1}t^{2q-1}e^{-s^2-t^2}dsdt=\int_D s^{2p-1}t^{2q-1}e^{-s^2-t^2}dv$

**** 反常重积分变量代还

***** 有界区域变量代还

定义 $s=r\cos\theta,t=r\sin\theta$ ，定义 $D'=\left\{(r\cos\theta,r\sin\theta)\big|a\leq r\leq b,c\leq\theta\leq d\right\}$ 为第一象限扇形，

其中 $a>0,b<\infty,c>0,d<\frac{\pi}{2}$ 则有

（1） $s,t$ 关于 $r,\theta$ 有连续偏导，且一一对应（重复点面积为零）

（2） 雅克比行列式为 $r$ ，且当 $(s,t)\in D'$ 时 $r\ne0$

（3） 函数 $f(s,t)=s^{2p-1}t^{2q-1}e^{-s^2-t^2}$ 连续

（4） $D'$ 为有界闭集且连通

则根据[[~/文档/note/数学分析/Chap13Note.org][重积分变量代还]]有 $\int_{D'} s^{2p-1}t^{2q-1}e^{-s^2-t^2}dv=\int_{T(D')} r^{2(p+1)-1}e^{-r^2}(\cos\theta)^{2p-1}(\sin\theta)^{2q-1}dv$

其中 $T(D')=\left\{(r,\theta)\big|r\in[a,b],\theat\in[c,d]\right\}$

***** 定义满足条件区域

定义 $D'_k=\left\{(r\cos\theta,r\sin\theta)\big|a_k\leq r\leq b_k,c_k\leq\theta\leq d_k\right\}$

其中 $a_k>0,b_k<\infty,c_k>0,d_k<\frac{\pi}{2}$ 且 $\lim_{k\to\infty}a_k=0,\lim_{k\to\infty}b_k=\infty,\lim_{k\to\infty}c_k=0,\lim_{k\to\infty}d_k=\frac{\pi}{2}$

则有 $\lim_{k\to\infty}D_k=D$

根据[[~/文档/note/数学分析/Chap13Note.org][反常重积分-区域无限反常重积分-敛散性-引理1]]和[[~/文档/note/数学分析/Chap13Note.org][反常重积分-无界函数反常重积分-敛散性-引理1]]

则有 $\lim_{k\to\infty}\int_{D'_k}s^{2p-1}t^{2q-1}e^{-s^2-t^2}dv=\int_Ds^{2p-1}t^{2q-1}e^{-s^2-t^2}dv$

同理 $\lim_{k\to\infty}\int_{T(D'_k)}r^{2(p+1)-1}e^{-r^2}(\cos\theta)^{2p-1}(\sin\theta)^{2q-1}dv=\int_{T(D)}r^{2(p+1)-1}e^{-r^2}(\cos\theta)^{2p-1}(\sin\theta)^{2q-1}dv$

又有 $\int_{D'_k} s^{2p-1}t^{2q-1}e^{-s^2-t^2}dv=\int_{T(D'_k)} r^{2(p+1)-1}e^{-r^2}(\cos\theta)^{2p-1}(\sin\theta)^{2q-1}dv$

故有 $\int_Ds^{2p-1}t^{2q-1}e^{-s^2-t^2}dv=\int_{T(D)}r^{2(p+1)-1}e^{-r^2}(\cos\theta)^{2p-1}(\sin\theta)^{2q-1}dv$

**** 证明结论

同理由于

（1） 函数 $f(r,\theta)=r^{2(p+1)-1}e^{-r^2}(\cos\theta)^{2p-1}(\sin\theta)^{2q-1}$ 在 $r\in(0,\infty),\theta\in\left(0,\frac{\pi}{2}\right)$ 上连续

（2） 反常累次积分 $\int_0^\infty\int_{2}^{\frac{\pi}{2}}r^{2(p+1)-1}e^{-r^2}(\cos\theta)^{2p-1}(\sin\theta)^{2q-1}d\theta dr=\int_0^\infty\int_{2}^{\frac{\pi}{2}}\left|r^{2(p+1)-1}e^{-r^2}(\cos\theta)^{2p-1}(\sin\theta)^{2q-1}\right|d\theta dr$ 存在可积

故根据[[~/文档/note/数学分析/Chap13Note.org][反常重积分-区域无限反常重积分-区域无限反常重积分计算]]以及[[~/文档/note/数学分析/Chap13Note.org][反常重积分-无界函数反常重积分-无界反常重积分计算]]

可得 $\int_{T(D)}r^{2(p+1)-1}e^{-r^2}(\cos\theta)^{2p-1}(\sin\theta)^{2q-1}dv=\int_0^\infty\int_{0}^{\frac{\pi}{2}}r^{2(p+1)-1}e^{-r^2}(\cos\theta)^{2p-1}(\sin\theta)^{2q-1}d\theta dr$

整理积分式可得 $\int_{T(D)}r^{2(p+1)-1}e^{-r^2}(\cos\theta)^{2p-1}(\sin\theta)^{2q-1}dv=\int_0^\infty r^{2(p+1)-1}e^{-r^2}dr\int_{0}^{\frac{\pi}{2}}(\cos\theta)^{2p-1}(\sin\theta)^{2q-1}d\theta$

其中根据[[MK18][Gamma函数其他表示]] $\int_0^\infty r^{2(p+1)-1}e^{-r^2}dr=\frac{1}{2}\Gamma(p+q)$

根据[[MK19][Beta函数其他表示]] $\int_{0}^{\frac{\pi}{2}}(\cos\theta)^{2p-1}(\sin\theta)^{2q-1}d\theta=\frac{1}{2}\beta(p,q)$

故有 $\Gamma(p)\Gamma(q)=4\frac{1}{2}\Gamma(p+q)\frac{1}{2}\beta(p,q)$ 证毕

** 相关公式

*** Legendre公式

$\Gamma(s)\Gamma\left(s+\frac{1}{2}\right)=\frac{\sqrt{\pi}}{2^{2s-1}}\Gamma(2s)$

**** 证明

根据[[MK20][函数关系]] $\beta(s,s)=\frac{\Gamma(s)\Gamma(s)}{\Gamma(2s)}$ ，根据[[MK21][定义]] $\beta(s,s)=\int_0^1x^{s-1}(1-x)^{s-1}dx$ 

若 $f(x)=x^{s-1}(1-x)^{s-1}$ 则有 $f\left(\frac{1}{2}+x\right)=\int_0^1\left(\frac{1}{2}+x\right)^{s-1}\left(\frac{1}{2}-x\right)^{s-1}dx=f\left(\frac{1}{2}-x\right)$

故函数在 $x\in(0,1)$ 上沿 $\frac{1}{2}$ 堆成，则有 $\beta(s,s)=\int_0^1x^{s-1}(1-x)^{s-1}dx=2\int_0^\frac{1}{2}x^{s-1}(1-x)^{s-1}dx$

且由于 $\Gamma\left(\frac{1}{2}\right)=\sqrt{\pi}$ 故有

\begin{aligned}
\frac{\Gamma(s)\Gamma(s)}{\Gamma(2s)}=&2\int_0^\frac{1}{2}x^{s-1}(1-x)^{s-1}dx\\
=&2\int_0^\frac{1}{2}\left(x-x^2\right)^{s-1}dx\\
=&2\int_0^\frac{1}{2}\left(\frac{1}{4}-\frac{1}{4}+x-x^2\right)^{s-1}dx\\
=&2\int_0^\frac{1}{2}\left[\frac{1}{4}-\left(\frac{1}{2}-x\right)^2\right]^{s-1}dx\\
=&2\int_1^0\left[\frac{1}{4}-\frac{1}{4}t\right]^{s-1}-\frac{1}{4}t^{-\frac{1}{2}}dt&x =\frac{1}{2}-\frac{1}{2}\sqrt{t},dx =-\frac{1}{4}t^{-\frac{1}{2}}\\
=&2\int_0^1(1-t)^{s-1}\frac{1}{4^{s}}t^{-\frac{1}{2}}dt\\
=&\frac{1}{2^{2s-1}}\int_0^1(1-t)^{s-1}t^{\frac{1}{2}-1}dt\\
=&\frac{1}{2^{2s-1}}\beta\left(s,\frac{1}{2}\right)\\
\frac{\Gamma(s)\Gamma(s)}{\Gamma(2s)}=&\frac{1}{2^{2s-1}}\frac{\Gamma\left(s\right)\Gamma\left(\frac{1}{2}\right)}{\Gamma\left(s+\frac{1}{2}\right)}\\
\frac{\Gamma(s)}{\Gamma(2s)}=&\frac{1}{2^{2s-1}}\frac{\Gamma\left(\frac{1}{2}\right)}{\Gamma\left(s+\frac{1}{2}\right)}\\
\Gamma(s)\Gamma\left(s+\frac{1}{2}\right)=&\frac{\sqrt{\pi}}{2^{2s-1}}\Gamma(2s)\\
\end{aligned}

*** 余元公式

$\Gamma(s)\Gamma(1-s)=\frac{\pi}{\sin(\pi s)},0<s<1$

**** 证明

***** <<MK24>>引理1

函数项级数 $\{u_n(x)\}$ 函数 $u(x)$ 及 $\phi(x)$ 在区间 $[a,b)$ 上有定义，若满足：

（1） $\lim_{n\to\infty}u_n(x)=u(x),\forall x\in[a,b)$

（2） 对于任意 $n\in N^+$ 在区间 $[a,b)$ 上的反常积分 $\int_a^bu_n(x)dx$ 存在

（3） 反常积分 $\int_a^b\phi(x)dx$ 收敛

（4） $0\leq u_n(x)\leq\phi(x)$

（5） $\forall\eta>0$ 函数项级数 $\{u_n(x)\}$ 在 $[a,b-\eta]$ 上一致收敛

则有 $\lim_{n\to\infty}\int_a^b u_n(x)dx=\int_a^b u(x)dx$ 即积分极限可互换

****** 证明

根据条件（4）可得 $0\leq u(x)\leq\phi(x)$

根据条件（3）及[[~/文档/note/数学分析/Chap8Note.org][无界函数反常积分收敛判别-非负反常积分判别]]得 $\int_a^b u(x)dx$ 也收敛

故 $\forall\epsilon>0$

根据条件（3），（4）及[[~/文档/note/数学分析/Chap8Note.org][无界函数反常积分收敛判别-定义]]有 $\exists\delta,\forall 0<\eta<\delta\Rightarrow\int_{b-\eta}^b\phi(x)dx<\frac{\epsilon}{3}$

且根据条件（4）有 $\int_{b-\eta}^bu_n(x)dx\leq\int_{b-\eta}^b\phi(x)dx<\frac{\epsilon}{3},\int_{b-\eta}^b u(x)dx\leq\int_{b-\eta}^b\phi(x)dx<\frac{\epsilon}{3}$

又由于条件（5），条件（1）得 $\exsits N,\forall n>N\Rightarrow\left|\int_a^{b-\eta}u_n(x)dx-\int_a^{b-\eta}u(x)dx\right|<\frac{\epsilon}{3}$ 故有

\begin{aligned}
\left|\int_a^b u_n(x)dx-\int_a^b u(x)dx\right|&=\left|\int_a^{b-\eta} u_n(x)dx-\int_a^{b-\eta} u(x)dx+\int_{b-\eta}^b u_n(x)dx-\int_{b-\eta}^b u(x)dx\right|\\
\leq&\left|\int_a^{b-\eta} u_n(x)dx-\int_a^{b-\eta} u(x)dx\right|+\left|\int_{b-\eta}^b u_n(x)dx\right|+\left|\int_{b-\eta}^b u(x)dx\right|\\
<&\epsilon\\
\end{aligned}

则有 $\lim_{n\to\infty}\int_a^b u_n(x)dx=\int_a^b u(x)dx$ 证毕

****** <<MK25>>推论

函数项级数 $\{u_n(x)\}$ 函数 $u(x)$ 及 $\phi(x)$ 在区间 $(a,b)$ 上有定义

若满足同样条件，则仍有 $\lim_{n\to\infty}\int_a^b u_n(x)dx=\int_a^b u(x)dx$ 

******* 证明

切分 $(a,b)$ 为 $(a,c],[c,b)$ 利用[[MK24][引理1]]可得 $\lim_{n\to\infty}\int_a^c u_n(x)dx=\int_a^c u(x)dx,\lim_{n\to\infty}\int_c^b u_n(x)dx=\int_c^b u(x)dx$

根据极限四则运算 $\lim_{n\to\infty}\int_a^c u_n(x)dx+\lim_{n\to\infty}\int_c^b u_n(x)dx=\lim_{n\to\infty}\left\{\int_a^c u_n(x)dx+\int_c^b u_n(x)dx\right\}$

根据[[~/文档/note/数学分析/Chap7Note.org][定积分基本性质-区间可加]] $\int_a^c u(x)dx+\int_c^b u(x)dx=\int_a^b u(x)dx,\int_a^c u_n(x)dx+\int_c^b u_n(x)dx=\int_a^b u_n(x)dx$

故有 $\lim_{n\to\infty}\int_a^b u_n(x)dx=\lim_{n\to\infty}\left\{\int_a^c u_n(x)dx+\int_c^b u_n(x)dx\right\}=\int_a^c u(x)dx+\int_c^b u(x)dx=\int_a^b u(x)dx$

***** <<MK26>>引理2

对于 $x\in(0,1)$ 成立 $\frac{\pi}{\sin(\pi x)}=\frac{1}{x}+\sum_{n=1}^\infty(-1)^n(\frac{1}{x+n}+\frac{1}{x-n})$

****** 证明

******* 对数转换

根据[[~/文档/note/数学分析/Chap9Note.org][部分公式证明-正弦函数无穷乘积展开]]得 $\sin(x)=x\prod_{i=1}^\infty\left(1-\frac{x^2}{i^2\pi^2}\right)$

取绝对值和对数 $\ln|\sin(x)|=\ln|x|+\sum_{i=1}^\infty\ln\left|1-\frac{x^2}{i^2\pi^2}\right|$

定义 $x\in(0,\pi)$ 则有 $\ln(\sin(x))=\ln(x)+\sum_{i=1}^\infty\ln\left(1-\frac{x^2}{i^2\pi^2}\right)$

******* 内闭一致连续

函数项级数 $u_n(x)=\sum_{i=1}^n\ln\left(1-\frac{x^2}{i^2\pi^2}\right)$

故有 $\lim_{n\to\infty}u_n(x)=\ln(\sin(x))-\ln(x)$ 即 $u_n(x)$ 点态收敛

且有 $u_n'(x)=\sum_{i=1}^n\frac{-\frac{2x}{i^2\pi^2}}{1-\frac{x^2}{i^2\pi^2}}=\sum_{i=1}^n\frac{2x}{x^2-i^2\pi^2}$ 由于 $x\in(0,\pi)$ 故有 $x^2-i^2\pi^2<0$

则有 $|u_n'(x)|=-u_n'(x)=\sum_{i=1}^n\frac{2x}{i^2\pi^2-x^2}>0$ 继续对 $-u_n'(x)$ 求导 $(-u_n'(x))'=\sum_{i=1}^\infty\frac{2(i^2\pi^2-x^2)-2x(-2x)}{(i^2\pi^2-x^2)^2}=\sum_{i=1}^\infty\frac{2i^2\pi^2+x^2}{(i^2\pi^2-x^2)^2}>0$

故 $-u_n'(x)$ 关于 $x$ 在 $x\in(0,\pi)$ 上单调递增，则定义 $b<\pi$ 则有 $\forall x\in(0,b]\Rightarrow|u_n'(x)|=\frac{2x}{i^2\pi^2-x^2}\leq\frac{2b}{i^2\pi^2-b^2}$

根据[[~/文档/note/数学分析/Chap9Note.org][部分极限证明-P级数]]得 $\sum_{i=1}^\infty \frac{2b}{i^2\pi^2}$ 收敛，且 $l=\lim_{n\to\infty}\frac{\frac{2b}{i^2\pi^2-b^2}}{\frac{2b}{i^2\pi^2}}=\frac{1}{1-\frac{b^2}{i^2\pi^2}}=1$ 故 $0<l<\infty$ 

又由于 $b<\pi\Rightarrow\frac{2b}{i^2\pi^2-b^2}>0$ 根据[[~/文档/note/数学分析/Chap9Note.org][级数敛散性-正项级数-比较判别法]]得 $\sum_{i=1}^\infty\frac{2b}{i^2\pi^2-b^2}$ 亦收敛

又根据[[~/文档/note/数学分析/Chap10Note.org][函数项级数一致收敛-判别-Weierstrass判别]]得 $u_n'(x)$ 在 $x\in(0,b]$ 上一致收敛

******* 求导

故对于 $x\in(0,b]$

（1） $u_n(x)=\sum_{i=1}^n\ln\left(1-\frac{x^2}{i^2\pi^2}\right)$ 点态收敛与 $\ln(\sin(x))-\ln(x)$

（2） $u_n(x)$ 在 $x\in(0,b]$ 上有连续导数
 
（3） $u_n'(x)$ 关于 $x\in(0,b]$ 一致收敛

故当 $x\in(0,b]$ 时根据[[~/文档/note/数学分析/Chap10Note.org][函数项级数-一致收敛性质-可导性]]可得 $u_n'(x)=(\ln(\sin(x))-\ln(x))'$

即有 $\sum_{i=1}^\infty\frac{2x}{x^2-i^2\pi^2}=\frac{\cos(x)}{\sin(x)}-\frac{1}{x}$

******* 证明结论

整理上式 $\frac{\cos(x)}{\sin(x)}=\frac{1}{x}+\sum_{i=1}^\infty\frac{2x}{x^2-i^2\pi^2}=\frac{1}{x}+\sum_{i=1}^\infty\left(\frac{1}{x-i\pi}+\frac{1}{x+i\pi}\right)$

即 $\cot(x)=\frac{1}{x}+\sum_{i=1}^\infty\left(\frac{1}{x-i\pi}+\frac{1}{x+i\pi}\right)$

当 $x\in\left(0,\frac{\pi}{2}\right)$ 时，有 $\tan(x)=\cot\left(\frac{\pi}{2}-x\right)$ 故此时

\begin{aligned}
\tan(x)=&\frac{1}{\frac{\pi}{2}-x\right}+\sum_{i=1}^\infty\left(\frac{1}{\frac{\pi}{2}-x-i\pi}+\frac{1}{\frac{\pi}{2}-x+i\pi}\right)\\
=&-\frac{1}{x-\frac{\pi}{2}\right}-\sum_{i=1}^\infty\left(\frac{1}{x+\frac{2i-1}{2}\pi}+\frac{1}{x-\frac{2i+1}{2}\pi}\right)\\
=&-\left[\frac{1}{x-\frac{\pi}{2}}+\sum_{i=1}^\infty\left(\frac{1}{x+\frac{2i-1}{2}\pi}+\frac{1}{x-\frac{2i+1}{2}\pi}\right)\right]\\
=&-\sum_{i=1}^\infty\left(\frac{1}{x+\frac{2i-1}{2}\pi}+\frac{1}{x-\frac{2i-1}{2}\pi}\right)
\end{aligned}

又因为 $\frac{1}{\sin(x)}=\frac{1}{2}\left(\tan\frac{x}{2}+\cot\frac{x}{2}\right)$ 故当 $x\in(0,\pi)$ 时 $\frac{x}{2}\in\left(0,\frac{\pi}{2}\right)$ 

\begin{aligned}
\frac{1}{\sin(x)}=&\frac{1}{2}\left\{\frac{1}{\frac{x}{2}}+\sum_{i=1}^\infty\left(\frac{1}{\frac{x}{2}-i\pi}+\frac{1}{\frac{x}{2}+i\pi}\right)-\sum_{i=1}^\infty\left(\frac{1}{\frac{x}{2}+\frac{2i-1}{2}\pi}+\frac{1}{\frac{x}{2}-\frac{2i-1}{2}\pi}\right)\right\}\\
=&\frac{1}{x}+\sum_{i=1}^\infty\left(\frac{1}{x-2i\pi}+\frac{1}{x+2i\pi}\right)-\sum_{i=1}^\infty\left(\frac{1}{x+2i-1\pi}+\frac{1}{x-2i-1\pi}\right)\\
=&\frac{1}{x}+\sum_{i=1}^\infty\left(\frac{1}{x-i\pi}+\frac{1}{x+i\pi}\right)\\
\end{aligned}

则定义 $x=\pi t$ 故有 $\frac{1}{\sin(\pi t)}=\frac{1}{\pi t}+\sum_{i=1}^\infty\left(\frac{1}{\pi t-i\pi}+\frac{1}{\pi t+i\pi}\right)$

整理得 $\frac{\pi}{\sin(\pi t)}=\frac{1}{t}+\sum_{i=1}^\infty\left(\frac{1}{t-i}+\frac{1}{t+i}\right)$

***** 证明公式

****** 转换函数式

根据[[MK20][欧拉函数关系]]得 $\beta(s,1-s)=\frac{\Gamma(s)\Gamma(1-s)}{\Gamma(1)}=\Gamma(s)\Gamma(1-s)$

根据[[MK22][Beta函数分式表述]]及[[MK23][对称性]]得 $\beta(s,1-s)=\beta(1-s,s)=\int_0^1\frac{t^{s-1}}{1+t}dt+\int_0^1\frac{t^{-s}}{1+t}dt$

根据[[~/文档/note/数学分析/Chap10Note.org][幂级数-幂级数展开-经典例题]]得 $(1+t)^{-1}=\sum_{i=0}^\infty\left(\binom {-1} n t^i\right)$

根据定义 $\binom {-1} n = \frac{-1(-2)(-3)...(-n)}{n!}=(-1)^n$ 则有 $(1+t)^{-1}=\sum_{i=0}^\infty(-1)^it^i$

****** 利用引理1转换积分

故有 $\frac{t^{s-1}}{1+t}=\sum_{i=0}^\infty(-1)^nt^{s+i-1}$ 则 $\int_0^1\frac{t^{s-1}}{1+t}dt=\int_0^1\lim_{n\to\infty}\sum_{i=0}^{n-1}(-1)^it^{s+i-1}dt$

则上述列式满足

（1） $\lim_{n\to\infty}\sum_{i=0}^{n-1}(-1)^nt^{s+i-1}=\frac{t^{s-1}}{1+t}$

（2） 对于任意 $n\in N^+$ 在区间 $(0,1)$ 上反常积分 $\int_0^1\left\{\sum_{i=0}^{n-1}(-1)^nt^{s+i-1}\right\}dt$ 存在，其中 $s\in(0,1)$

（3） 由于 $s\in(0,1)$ 反常积分 $\int_0^1t^{s-1}dt$ 可积

（4） 根据等比数列求和公式 $\sum_{i=0}^n(-1)^it^{s+i-1}=\frac{t^{s-1}(1-(-t)^n)}{1+t}$ 由于 $t\in(0,1)$ 则有 $0\leq\sum_{i=0}^n(-1)^it^{s+i-1}\leq t^{s-1}$

（5） $\forall\eta>0$ 定义 $a_n(t)=t^{s+i-1},b_n(t)=(-1)^n$ 则当 $t\in[\eta,1-\eta]$ 时有

      a) $0<a_n(t)<(1-\eta)^{s+n-1}$ 且 $\lim_{n\to\infty}(1-\eta)^{s+n-1}=0$ ，
      
         则根据[[~/文档/note/数学分析/Chap10Note.org][函数项级数一致收敛-判别-Weierstrass判别]]及夹逼定理得 $a_n(t)$ 一致收敛到 $0$

      b) $\left|\sum_{i=0}^n b_i(t)\right|\leq 1<1.5$

      故根据[[~/文档/note/数学分析/Chap10Note.org][函数项级数-函数项级数一致收敛-判别-A-D判别-Dirichlet]]得函数项级数 $\left\{\sum_{i=0}^n(-1)^it^{s+i-1}\right\}$ 在 $[\eta,1-\eta],1>\eta>0$ 上一致收敛 

则根据[[MK25][推论]]有 $\lim_{n\to\infty}\int_0^1\left\{\sum_{i=0}^n(-1)^it^{s+i-1}\right\}dx=\int_0^1\frac{t^{s-1}}{1+t}dt$ 

同理第二部分有 $\lim_{n\to\infty}\int_0^1\left\{\sum_{i=0}^n(-1)^it^{-s+i}\right\}dx=\int_0^1\frac{t^{-s}}{1+t}dt$ 

****** 推导结论

故综合之前推导，极限四则运算和[[MK26][引理2]]，当 $s\in(0,1)$ 时有

\begin{aligned}
\Gamma(s)\Gamma(1-s)=&\lim_{n\to\infty}\left\{\sum_{i=0}^n\left[\int_0^1(-1)^it^{s+i-1}dx+\int_0^1(-1)^it^{-s+i}dx\right]\right\}\\
=&\sum_{i=0}^\infty(-1)^i\left\{\frac{t^{s+i}}{s+i}\bigg|_0^1+\frac{t^{-s+i+1}}{-s+i+1}\bigg|_0^1\right\}\\
=&\sum_{i=0}^\infty\frac{(-1)^i}{s+i}+\sum_{i=0}^\infty\frac{(-1)^i}{-s+i+1}\\
=&\frac{1}{s}+\sum_{i=1}^\infty\frac{(-1)^i}{i+s}+\sum_{i=1}^\infty\frac{(-1)^i}{i-s}\\
=&\frac{\pi}{\sin(\pi s)}
\end{aligned}

*** Stirling公式

$\Gamma(s+1)=\sqrt{2\pi s}\left(\frac{s}{e}\right)^se^{\frac{\theta}{12s}}$ 其中 $\theta\in(0,1),s>0$

特别当 $s=n$ 时有 $n!=\sqrt{2\pi n}\left(\frac{n}{e}\right)^ne^{\frac{\theta}{12n}}$

**** 证明

***** <<MK30>>不等式

定义 $0<y<1$ 则有 $(y+s)^y\Gamma(s+1)\leq\Gamma(y+s+1)\leq(s+1)^y\Gamma(s+1)$

****** 证明

定义 $\alpha+\beta=1,\alpha>0,\beta>0$ 由于[[MK29][之前证明]]可得 $\ln(\Gamma(s))$ 为凸函数

故有 $\ln(\Gamma(y+s+1))=\ln(\Gamma((1-y)(s+1)+y(s+2))\leq(1-y)\ln(\Gamma(s+1))+y\ln(\Gamma(s+2))$ 则有 

\begin{aligned}
\Gamma(y+s+1)\leq&\left(\Gamma(s+1)\right)^{1-y}\left(\Gamma(s+2)\right)^y\\
=&\left(\Gamma(s+1)\right)^{1-y}\left((s+1)\Gamma(s+1)\right)^y\\
=&(s+1)^y\Gamma(s+1)
\end{aligned}

同理有 $\ln(\Gamma(s+1))=\ln(\Gamma((y)(s+y)+(1-y)(s+y+1))\leq y\ln(\Gamma(s+y))+(1-y)\ln(\Gamma(s+y+1))$ 则有

\begin{aligned}
\Gamma(s+1)\leq&\left(\Gamma(s+y)\right)^{y}\left(\Gamma(s+y+1)\right)^{1-y}\\
=&\left(\Gamma(s+y)\right)^{y}\left((s+y)\Gamma(s+y)\right)^{1-y}\\
=&(s+y)^{1-y}\Gamma(s+y)\\
=&(s+y)^{-y}\Gamma(s+y+1)\\
\end{aligned}

故有 $(s+y)^y\Gamma(s+1)\leq\Gamma(s+y+1)$

结合两式，证毕。

***** <<MK32>>Gamma函数等价极限

$\lim_{s\to\infty}\frac{\Gamma(s)}{\sqrt{2\pi}s^ss^{-\frac{1}{2}}e^{-s}}=1$

****** 证明

定义 $s=n+y+1$ 其中 $n\in N^+,0<y<1$ 则根据[[MK30][不等式]]有 $(n+y)^y\Gamma(n+1)\leq\Gamma(s)\leq(n+1)^y\Gamma(n+1)$

故有 $\frac{(n+y)^yn!}{\sqrt{2\pi}(n+y+1)^{n+y+1}(n+y+1)^{-\frac{1}{2}}e^{-(n+y+1)}}=\frac{(n+y)^y\Gamma(n+1)}{\sqrt{2\pi}s^ss^{-\frac{1}{2}}e^{-s}}\leq\frac{\Gamma(s)}{\sqrt{2\pi}s^ss^{-\frac{1}{2}}e^{-s}}\leq\frac{(n+1)^y\Gamma(n+1)}{\sqrt{2\pi}s^ss^{-\frac{1}{2}}e^{-s}}=\frac{(n+1)^yn!}{\sqrt{2\pi}(n+y+1)^{n+y+1}(n+y+1)^{-\frac{1}{2}}e^{-(n+y+1)}}$

根据[[~/文档/note/数学分析/Chap9Note.org][部分公式证明-Stirling公式]]得 $\lim_{n\to\infty}\frac{n!}{\sqrt{2\pi}n^{n+\frac{1}{2}}e^{-n}}=1$ 故根据极限保序性及四则运算有：

\begin{aligned}
\lim_{s\to\infty}\frac{\Gamma(s)}{\sqrt{2\pi}s^ss^{-\frac{1}{2}}e^{-s}}\leq&\lim_{n\to\infty}\left\{\frac{(n+1)^yn!}{\sqrt{2\pi}(n+y+1)^{n+y+1}(n+y+1)^{-\frac{1}{2}}e^{-(n+y+1)}}\right\}\\
=&\lim_{n\to\infty}\left\{\frac{(n+1)^y\sqrt{2\pi}n^{n+\frac{1}{2}}e^{-n}}{\sqrt{2\pi}(n+y+1)^{n+y+1}(n+y+1)^{-\frac{1}{2}}e^{-(n+y+1)}}\frac{n!}{\sqrt{2\pi}n^{n+\frac{1}{2}}e^{-n}}\right\}\\
=&\lim_{n\to\infty}\left\{\frac{(n+1)^y}{(n+y+1)^y}\left(\frac{n}{n+y+1}\right)^n\frac{n^\frac{1}{2}}{(n+y+1)^\frac{1}{2}}e^{y+1}\frac{n!}{\sqrt{2\pi}n^{n+\frac{1}{2}}e^{-n}}\right\}\\
=&\lim_{n\to\infty}\left\{\frac{(n+1)^y}{(n+y+1)^y}\left(1+\frac{y+1}{n}\right)^{-n}\frac{n^\frac{1}{2}}{(n+y+1)^\frac{1}{2}}e^{y+1}\frac{n!}{\sqrt{2\pi}n^{n+\frac{1}{2}}e^{-n}}\right\}\\
=&1\cdot e^{-(1+y)}\cdot 1\cdot e^{y+1}\cdot 1\\
=&1
\end{aligned}

以及：

\begin{aligned}
\lim_{s\to\infty}\frac{\Gamma(s)}{\sqrt{2\pi}s^ss^{-\frac{1}{2}}e^{-s}}\geq&\lim_{n\to\infty}\left\{\frac{(n+y)^yn!}{\sqrt{2\pi}(n+y+1)^{n+y+1}(n+y+1)^{-\frac{1}{2}}e^{-(n+y+1)}}\right\}\\
=&\lim_{n\to\infty}\left\{\frac{(n+y)^y\sqrt{2\pi}n^{n+\frac{1}{2}}e^{-n}}{\sqrt{2\pi}(n+y+1)^{n+y+1}(n+y+1)^{-\frac{1}{2}}e^{-(n+y+1)}}\frac{n!}{\sqrt{2\pi}n^{n+\frac{1}{2}}e^{-n}}\right\}\\
=&\lim_{n\to\infty}\left\{\frac{(n+y)^y}{(n+y+1)^y}\left(\frac{n}{n+y+1}\right)^n\frac{n^\frac{1}{2}}{(n+y+1)^\frac{1}{2}}e^{y+1}\frac{n!}{\sqrt{2\pi}n^{n+\frac{1}{2}}e^{-n}}\right\}\\
=&\lim_{n\to\infty}\left\{\frac{(n+y)^y}{(n+y+1)^y}\left(1+\frac{y+1}{n}\right)^{-n}\frac{n^\frac{1}{2}}{(n+y+1)^\frac{1}{2}}e^{y+1}\frac{n!}{\sqrt{2\pi}n^{n+\frac{1}{2}}e^{-n}}\right\}\\
=&1\cdot e^{-(1+y)}\cdot 1\cdot e^{y+1}\cdot 1\\
=&1
\end{aligned}

故根据夹逼定理有 $\lim_{s\to\infty}\frac{\Gamma(s)}{\sqrt{2\pi}s^ss^{-\frac{1}{2}}e^{-s}}=1$

***** <<MK31>>证明泰勒展开

根据[[~/文档/note/数学分析/Chap10Note.org][幂级数-幂级数展开]]在 $x_0=0$ 点有展开

（1） $\ln(1+x)=x-\frac{1}{2}x^2+\frac{1}{3}x^3-...,\ x\in(0,1)$ 

（2） $\ln(1-x)=-x-\frac{1}{2}x^2-\frac{1}{3}x^3-...,\ x\in(0,1)$ 

****** 证明

******* 收敛半径

对于式（1）通项为 $u_n(x)=(-1)^n\frac{1}{n}x^n$ 

则根据[[~/文档/note/数学分析/Chap10Note.org][幂级数-收敛半径-幂级数收敛半径判别-达朗贝尔]]以及[[~/文档/note/数学分析/Chap9Note.org][绝对收敛 & 条件收敛-收敛性质]]

$\lim_{n\to\infty}\left|\frac{\frac{1}{n+1}x^{n+1}}{\frac{1}{n}x^{n}}\right|=\lim_{n\to\infty}\left|\frac{n}{n+1}\right||x|$ 故当 $x\in(0,1)$ 时级数收敛

同理可证式（2）

******* 余项

式（1）拉格朗日余项为 $R_n(x)=\frac{f^{(n+1)}(\xi)}{(n+1)!}(x-x_0)^{n+1}=\frac{(-1)^{n}x^{n+1}}{n(1+\xi)},\ \ \xi\in [x,x_0]$

由于 $x\in(0,1)$ 故余项亦有 $\lim_{n\to\infty}R_n(x)=0$

同理可证式（2）

***** <<MK33>>证明不等式 $e<\left(1+\frac{1}{s}\right)^{s+\frac{1}{2}}<e^{1+\frac{1}{12s(s+1)}}$ 

根据[[MK31][泰勒展开有]] $\ln\frac{1+x}{1-x}=\ln(1+x)-\ln(1-x)=2\left(x+\frac{1}{3}x^3+\frac{1}{5}x^5+...\right)$ 

带入 $x=\frac{1}{2s+1}$ 由于 $s\in(0,\infty)$ 则有 $x\in(0,1)$

\begin{aligned}
\ln\frac{1+\frac{1}{2s+1}}{1-\frac{1}{2s+1}}=&2\left(\frac{1}{2s+1}+\frac{1}{3}\left(\frac{1}{2s+1}\right)^3+\frac{1}{5}\left(\frac{1}{2s+1}\right)^5+...\right)\\
\ln\left(\frac{s+1}{s}\right)=&\frac{2}{2s+1}\left(1+\frac{1}{3}\left(\frac{1}{2s+1}\right)^2+\frac{1}{5}\left(\frac{1}{2s+1}\right)^4+...\right)\\
\left(s+\frac{1}{2}\right)\ln\left(\frac{s+1}{s}\right)=&1+\frac{1}{3}\left(\frac{1}{2s+1}\right)^2+\frac{1}{5}\left(\frac{1}{2s+1}\right)^4+...
\end{aligned}

利用等比数列求和公式可得 $\left(\frac{1}{2s+1}\right)^2+\left(\frac{1}{2s+1}\right)^4+...=\frac{\left(\frac{1}{2s+1}\right)^2}{1-\left(\frac{1}{2s+1}\right)^2}=\frac{\frac{1}{(2s+1)^2}}{\frac{(2s+1)^2-1}{(2s+1)^2}}=\frac{1}{4s(s-1)}$

故有 $1<\left(s+\frac{1}{2}\right)\ln\left(\frac{s+1}{s}\right)<1+\frac{1}{3}\left(\left(\frac{1}{2s+1}\right)^2+\left(\frac{1}{2s+1}\right)^4+...\right)=1+\frac{1}{12s(s+1)}$

故有 $e<\left(1+\frac{1}{s}\right)^{s+\frac{1}{2}}<e^{1+\frac{1}{12s(s+1)}}$ 

***** 定义数列及其极限

定义 $a(s)=\frac{\Gamma(s+1)e^s}{s^{s+\frac{1}{2}}}$ 则有 $\frac{a(s)}{a(s+1)}=\frac{\Gamma(s+1)}{\Gamma(s+2)}\frac{1}{e}\frac{(s+1)^{s+1+\frac{1}{2}}}{s^{s+\frac{1}{2}}}=\frac{\left(1+\frac{1}{s}\right)^{s+\frac{1}{2}}}{e}$ 

故根据[[MK33][不等式]] $1<\frac{a(s)}{a(s+1)}<e^{\frac{1}{12s(s+1)}}=e^{\frac{1}{12}\left(\frac{1}{s}-\frac{1}{s+1}\right)}=\frac{e^{\frac{1}{12s}}}{e^{\frac{1}{12(s+1)}}}$

故得 $a(s)e^{-\frac{1}{12s}}<a(s+1)e^{-\frac{1}{12(s+1)}}$ 故定义 $s=n+y,n\in N^+,y\in[0,1]$

则对于数列 $a(n+y)e^{-\frac{1}{12(n+y)}}$ 关于 $n$ 单调递增 $a(n+y)$ 关于 $n$ 单调递减

则故两个极限必存在且有 $\lim_{n\to\infty}a(n+y)=\lim_{n\to\infty}a(n+y)e^{-\frac{1}{12(n+y)}}=A$

***** 证明结论

故有 $a(n+y)e^{-\frac{1}{12(n+y)}}<A<a(n+y)\Rightarrow e^{-\frac{1}{12(n+y)}}<\frac{A}{a(n+y)}<1\Rightarrow -\frac{1}{12(n+y)}<\ln\frac{A}{a(s)}<0$

整理得 $0<\frac{\ln\frac{A}{a(s)}}{-\frac{1}{12s}}<1$ 定义 $\theta=\frac{\ln\frac{A}{a(s)}}{-\frac{1}{12s}}$ 则有 $a(s)e^{-\frac{\theta}{12s}}=a(s)e^{\ln\frac{A}{a(s)}}=A$

则 $a(s)=Ae^{\frac{\theta}{12s}}\Rightarrow\frac{\Gamma(s+1)e^s}{s^{s+\frac{1}{2}}}=Ae^{\frac{\theta}{12s}}\Rightarrow\Gamma(s+1)=A\sqrt{s}\left(\frac{s}{e}\right)^se^{\frac{\theta}{12s}}$

且由于 $A=\lim_{n\to\infty}a(n+y)=\lim_{s\to\infty}\frac{\Gamma(s)e^s}{s^{s+\frac{1}{2}}}$ 则根据[[MK32][Gamma函数极限]]以及极限四则运算有：

\begin{aligned}
\lim_{s\to\infty}\frac{\Gamma(s+1)e^s}{s^{s-\frac{1}{2}}}=&\lim_{s\to\infty}\frac{\Gamma(s+1)}{s^{s+\frac{1}{2}}e^{-s}}\frac{(s+1)^{s+\frac{1}{2}}}{(s+1)^{s+\frac{1}{2}}}\\
=&\lim_{s\to\infty}\frac{\Gamma(s+1)}{(s+1)^{(s+1)-\frac{1}{2}}e^{-s-1}}e\left(1+\frac{1}{s}\right)^{-s}\left(\frac{s}{s+1}\right)^{\frac{1}{2}}\\
=&\sqrt{2\pi}\cdot e\cdot e^{-1}\cdot 1\\
=&\sqrt{2\pi}
\end{aligned}

故有 $\Gamma(s+1)=\sqrt{2\pi s}\left(\frac{s}{e}\right)^se^{\frac{\theta}{12s}}$

