#+LATEX_CLASS: ctexart

#+TITLE: 重积分

current mark: MK47

* 有理函数不定积分

** 有理函数定义

定义有理函数为 $\frac{p(x)}{q(x)}$ 其中 $p(x),q(x)$ 分别为关于 $x$ 的 $m,n$ 次多项式

** <<MK20>>定义真分式

有理函数 $\frac{p(x)}{q(x)}$ 当 $m<n$ 时，定义为真分式。

若 $m>n$ 则可通过多项式带余除法求得 $\frac{p(x)}{q(x)}=p_{m-n}(x)+\frac{r(x)}{q(x)}$ 其中 $p_{m-n}(x)$ 为 $m-n$ 次多项式

以下证明中 $\frac{p(x)}{q(x)}$ 均为真分式。

*** 带余除法举例

计算 $\frac{x^2+9x+25}{x+4}$ 其中 $m=2,n=1$

第一步 $x^2+9x+25-x(x+4)=5x+25$

第二步 $5x+25-5(x+4)=5$

故有 $\frac{(x^2+9x+25)}{(x+4)}=\frac{5}{x+4}+x+5$

** 定义符号

由于 $q(x)$ 为实函数，故只有实根或共轭复根 

定义 $\alpha_1,\alpha_2,...,\alpha_i$ 为 $q_n(x)$ 的实根，重数为 $u_1,u_2,...,u_i$

定义 $\beta_1\pm i\gamma_1,\beta_2\pm i\gamma_2,...,\beta_j\pm i\gamma_j$ 为 $q_n(x)$ 的共轭复根，重数为 $v_1,v_2,...,v_j$

故有 $q_n(x)=\Pi_{k=1}^i (x-\alpha_k)^{u_k}\Pi_{k=1}^j\left[(x-\beta_k)^2+\gamma_k^2\right]^{v_j}$

** <<MK21>>引理1

若 $\alpha$ 为 $q(x)$ 的一个解，重数为 $u$ 即 $q(x)=(x-\alpha)^uq_1(x)$ ，

则存在实数 $\lambda$ 及多项式 $p_1(x)$ 次数小于 $(x-\alpha)^{u-1}q_1(x)$ ，即 $n-1$ 次，使得 $\frac{p(x)}{q(x)}=\frac{\lambda}{(x-\alpha)^u}+\frac{p_1(x)}{(x-\alpha)^{u-1}q_1(x)}$ 成立

*** 证明

定义 $\lambda=\frac{p(\alpha)}{q_1(\alpha)}$ ，根据定义 $q_1(\alpha)\ne0$ ,则 $\alpha$ 是函数 $p(x)-q_1(x)$ 的一个实根，则有 $p(x)-\lambda q_1(x)=(x-\alpha)p_1(x)$ 

由于 $q_1(x)$ 次数为 $n-u$ 其中 $u>=1$ ， $p(x)$ 次数根据[[MK20][真分式定义]]为 $m<n$ 故 $p_1(x)$ 次数为 $\max(n-u-1,m-1)<n-1$

故有 $\frac{p(x)}{q(x)}=\frac{(x-\alpha)p_1(x)+\lambda q_1(x)}{(x-\alpha)^uq_1(x)}=\frac{\lambda}{(x-\alpha)^u}+\frac{p_1(x)}{(x-\alpha)^{u-1}q_1(x)}$ 

** <<MK22>>引理2

若 $\beta\pm i\gamma$ 是 $q(x)$ 一对共轭复根，重数为 $v$ ，即 $q(x)=\left[(x-\beta)^2+\gamma^2\right]^vq^1(x)$ ，

则存在实数 $\xi,\eta$ 及多项式 $p^1(x)$ 次数小于 $\left[(x-\beta)^2+\gamma^2\right]^{v-1}q^1(x)$ ，即 $n-1$ 次，使得 $\frac{p(x)}{q(x)}=\frac{\xi x+\eta}{\left[(x-\beta)^2+\gamma^2\right]^v}+\frac{p^1(x)}{\left[(x-\beta)^2+\gamma^2\right]^{v-1}q_1(x)}$ 成立

*** 证明 

定义 $\xi,\eta$ 使得 $\frac{p(\beta+i\gamma)}{q^1(\beta+i\gamma)}=\xi(\beta+i\gamma)+\eta$ 成立，根据定义 $q^1(\beta+i\gamma)\ne0$

由于分母分子均为多项式，则等式展开后形式为 $\frac{f_1(\beta,\gamma)+ig_1(\beta,\gamma)}{f_2(\beta,\gamma)+ig_2(\beta,\gamma)}$ 分子分母同乘 $f_2(\beta,\gamma)-ig_2(\beta,\gamma)$ 

得 $\frac{f_1(\beta,\gamma)f_2(\beta,\gamma)+g_1(\beta,\gamma)g_2(\beta,\gamma)}{f_2(\beta,\gamma)+g_2(\beta,\gamma)}+i\frac{-f_1(\beta,\gamma)g_2(\beta,\gamma)+f_2(\beta,\gamma)g_1(\beta,\gamma)}{f_2(\beta,\gamma)+g_2(\beta,\gamma)}$ ，其中 $f_1(\beta,\gamma),f_2(\beta,\gamma),g_1(\beta,\gamma),g_2(\beta,\gamma)$ 均为多项式函数

由于 $i,\gamma$ 同次，且 $i^2=-1$ ，故 $f_1(\beta,\gamma),f_2(\beta,\gamma)$ 中每一项必为 $\gamma$ 的偶次项（包含零次），即 $f_1(\beta,\gamma)=f_1(\beta,-\gamma),f_2(\beta,\gamma)=f_2(\beta,-\gamma)$

同理， $g_1(\beta,\gamma),g_2(\beta,\gamma)$ 中每一项必为 $\gamma$ 的奇次项，则有 $g_1(\beta,\gamma)=-g_1(\beta,-\gamma),g_2(\beta,\gamma)=-g_2(\beta,-\gamma)$

又因为  $\frac{f_1(\beta,\gamma)-ig_1(\beta,\gamma)}{f_2(\beta,\gamma)-ig_2(\beta,\gamma)}$ 分子分母同乘 $f_2(\beta,\gamma)+ig_2(\beta,\gamma)$ 得 $\frac{f_1(\beta,\gamma)f_2(\beta,\gamma)+g_1(\beta,\gamma)g_2(\beta,\gamma)}{f_2(\beta,\gamma)+g_2(\beta,\gamma)}+i\frac{f_1(\beta,\gamma)g_2(\beta,\gamma)-f_2(\beta,\gamma)g_1(\beta,\gamma)}{f_2(\beta,\gamma)+g_2(\beta,\gamma)}$ 

故若 $\frac{p(\beta+i\gamma)}{q^1(\beta+i\gamma)}=\xi(\beta+i\gamma)+\eta$ 则 $\frac{p(\beta-i\gamma)}{q^1(\beta-i\gamma)}=\xi(\beta-i\gamma)+\eta$

得出 $\beta\pm i\gamma$ 是函数 $p(x)-(\xi x+\eta)q^1(x)$ 的共轭复根，则有 $p(x)-(\xi x+\eta)q^1(x)=\left[(x-\beta)^2+\gamma^2\right]p^1(x)$ 

由于 $q^1(x)$ 次数为 $n-v$ 其中 $v>=1$ ， $p(x)$ 次数根据[[MK20][真分式定义]]为 $m<n$ 故 $p^1(x)$ 次数为 $\max(n-v-1,m-1)<n-1$

则有  $\frac{p(x)}{q(x)}=\frac{\left[(x-\beta)^2+\gamma^2\right]p^1(x)+(\xi x+\eta)q^1(x)}{\left[(x-\beta)^2+\gamma^2\right]^vq^1(x)}=\frac{\xi x+\eta}{\left[(x-\beta)^2+\gamma^2\right]^v}+\frac{p^1(x)}{\left[(x-\beta)^2+\gamma^2\right]^{v-1}q_1(x)}$ 

** <<MK23>>引理3

定义 $I_n=\int\frac{1}{(x^2+a^2)^n}dx$ 则有 $I_n=\begin{cases}\frac{1}{a}\arctan\left(\frac{x}{a}\right)+C&n=1\\\frac{2n-3}{2a^2(n-1)}I_{n-1}+\frac{x}{2a^2(n-1)(x^2+a^2)^{n-1}}&n\geq 2\end{cases}$

*** 证明

**** 先证 $n=1$

定义 $u=\frac{x}{a}$ 则有 $\frac{du}{dx}=\frac{1}{a}\Rightarrow adu=dx$

\begin{aligned}
I_1&=\int\frac{1}{x^2+a^2}dx\\
&=\frac{1}{a^2}\int\frac{1}{\frac{x^2}{a^2}+1}dx\\
&=\frac{1}{a^2}\int\frac{1}{u^2+1}adu\\
&=\frac{1}{a}\arctan\left(\frac{x}{a}\right)+C\\
\end{aligned}

**** 证明 $n\geq 2$

定义 $u=\frac{1}{(x^2+a^2)^{n-1}}=(x^2+a^2)^{-n+1}$ 则有 $\frac{du}{dx}=-2(n-1)\frac{x}{(x^2+a^2)^n}\Rightarrow \frac{-1}{2(n-1)}du=\frac{x}{(x^2+a^2)^n}dx$

\begin{aligned}
I_1&=\int\frac{1}{(x^2+a^2)^n}dx\\
&=\frac{1}{a^2}\int\frac{a^2}{(x^2+a^2)^n}dx\\
&=\frac{1}{a^2}\int\frac{x^2+a^2-x^2}{(x^2+a^2)^n}dx\\
&=\frac{1}{a^2}\int\frac{x^2+a^2}{(x^2+a^2)^n}dx-\frac{1}{a^2}\int\frac{x^2}{(x^2+a^2)^n}dx\\
&=\frac{I_{n-1}}{a^2}-\frac{1}{a^2}\int x\frac{-1}{2(n-1)}d\left(\frac{1}{(x^2+a^2)^{n-1}}\right)\\
&=\frac{I_{n-1}}{a^2}+\frac{1}{2a^2(n-1)}\int x d\left(\frac{1}{(x^2+a^2)^{n-1}}\right)\\
&=\frac{I_{n-1}}{a^2}+\frac{1}{2a^2(n-1)}\left\{\frac{x}{(x^2+a^2)^{n-1}}-\int \frac{1}{(x^2+a^2)^{n-1}}dx\right\}\\
&=\frac{I_{n-1}}{a^2}+\frac{x}{2a^2(n-1)(x^2+a^2)^{n-1}}-\frac{I_{n-1}}{2a^2(n-1)}\\
&=\frac{(2n-3)I_{n-1}}{2a^2(n-1)}+\frac{x}{2a^2(n-1)(x^2+a^2)^{n-1}}\\
\end{aligned}

** 有理函数不定积分定理

若被积函数为有理函数，即 $\frac{p(x)}{q(x)}$ 则必能求出期不定积分表达式

*** 证明

由于 $\frac{p(x)}{q(x)}=\frac{p(x)}{\Pi_{k=1}^i (x-\alpha_k)^{u_k}\Pi_{k=1}^j\left[(x-\beta_k)^2+\gamma_k^2\right]^{v_j}}$ 则可根据[[MK21][引理1]]及[[MK22][引理2]]函数可化为 $\frac{p(x)}{q(x)}=\sum_{k=1}^i\sum_{r=1}^{u_k}\frac{\lambda_{kr}}{(x-\alpha_k)^r}+\sum_{k=1}^i\sum_{r=1}^{u_k}\frac{\xi_{kr} x+\eta_{kr}}{\left[(x-\beta_k)^2+\gamma_k^2\right]^r}$

故根据不定积分线性 $\int\frac{p(x)}{q(x)}dx=\sum_{k=1}^i\sum_{r=1}^{u_k}\int\frac{\lambda_{kr}}{(x-\alpha_k)^r}dx+\sum_{k=1}^i\sum_{r=1}^{u_k}\int\frac{\xi_{kr} x+\eta_{kr}}{\left[(x-\beta_k)^2+\gamma_k^2\right]^r}dx$

**** 对于项 $\int\frac{\lambda_{kr}}{(x-\alpha_k)^r}dx$

\begin{aligned}
\int\frac{\lambda_{kr}}{(x-\alpha_k)^r}dx&=\lambda_{kr}\int\frac{1}{(x-\alpha_k)^r}dx\\
&=\begin{cases}
\lambda_{kr}\ln\left|x-\alpha_k\right|+C&r=1\\
\frac{\lambda_{kr}}{r-1}\frac{1}{(x-\alpha_k)^(r-1)}&r\geq2\\
\end{cases}
\end{aligned}

**** 对于项 $\int\frac{\xi_{kr} x+\eta_{kr}}{\left[(x-\beta_k)^2+\gamma_k^2\right]^r}dx$

定义 $u=x^2-2\beta_kx+\beta_k^2+\gamma_k^2$ 则有 $\frac{du}{dx}=2x-2\beta_k\Rightarrow du=(2x-2\beta_k)dx$

定义 $v=x-\beta_k$ 则有 $\frac{dv}{dx}=1\Rightarrow dv=dx$

\begin{aligned}
\int\frac{\xi_{kr} x+\eta_{kr}}{\left[(x-\beta_k)^2+\gamma_k^2\right]^r}dx&=\frac{\xi_{kr}}{2}\int\frac{ 2x+2\frac{\eta_{kr}}{\xi_{kr}}}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx\\
&=\frac{\xi_{kr}}{2}\int\frac{ 2x-2\beta_k+2\beta_k+2\frac{\eta_{kr}}{\xi_{kr}}}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx\\
&=\frac{\xi_{kr}}{2}\int\frac{ 2x-2\beta_k}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx+\frac{\xi_{kr}}{2}\left(2\beta_k+2\frac{\eta_{kr}}{\xi_{kr}}\right)\int\frac{1}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx\\
&=\frac{\xi_{kr}}{2}\int\frac{ 2x-2\beta_k}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx+\left(\beta_k\xi_{kr}+\eta_{kr}\right)\int\frac{1}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx\\
&=\frac{\xi_{kr}}{2}\int\frac{1}{u^r}du+\left(\beta_k\xi_{kr}+\eta_{kr}\right)\int\frac{1}{\left[v^2+\gamma_k^2\right]^r}dv\\
\end{aligned}

其中 $\int\frac{1}{u^r}du=\begin{cases}\ln |u|+C&r=1\\\frac{-1}{r-1}\frac{1}{u^{r-1}}&r\geq 2\end{cases}$ 故 $\int\frac{ 2x-2\beta_k}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx=\begin{cases}\ln |x^2-2\beta_kx+\beta_k^2+\gamma_k^2|+C&r=1\\\frac{-1}{r-1}\frac{1}{\left(x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right)^{r-1}}&r\geq 2\end{cases}$

其中 $\int\frac{1}{\left[v^2+\gamma_k^2\right]^r}dv$ 可根据[[MK23][引理3]]迭代求得并带入 $v=x-\beta_k$

* 光滑曲线（面）的面（体）积为零

定义曲面 $\vec{f}(\vec{t})=\begin{cases}f_1(t_1,t_2,...,t_{n-1})\\f_2(t_1,t_2,...,t_{n-1})\\...\\f_n(t_1,t_2,...,t_{n-1})\\\end{cases}$ 是 $\vec{t}\in D_{n-1}$ 到 $R^n$ 的映射，其中

（1） $D_{n-1}$ 为 $R^{n-1}$ 上的有界连通闭集

（2） $\vec{f}(\vec{t})$ 连续，即 $\lim_{\vec{t}\to\vec{t}_0}\vec{f}(\vec{t})=\vec{f}(\vec{t}_0)$

（3） $\vec{f}(\vec{t})$ 具有连续一阶偏导 

则映射 $\vec{f}(\vec{t})$ 的体积为零

** 证明 

*** 证明存在 $L$ 使得 $\left|\vec{f}(\vec{t}_2)-\vec{f}(\vec{t}_1)\right|\leq L|\vec{t}_2-\vec{t}_1|$

因为 $\vec{f}(\vec{t})$ 在 $D_{n-1}$ 上存在偏导且连续，故偏导数 $\frac{\partial f_i(\vec{t})}{\partial t_j},1\leq i\leq n, 1\leq j\leq n-1$ 亦为 $\vec{t}$ 的连续映射

由于 $D_{n-1}$ 有界闭集，故根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-Heine-Borel定理]] $D_{n-1}$ 为紧集

根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][连续函数性质-紧集的连续映射（连续函数）也是紧集]]得出 $\frac{\partial f_i(\vec{t})}{\partial t_j}$ 亦为紧集，同理为有界闭集，则存在 $m_{ij}\leq\frac{\partial f_i(\vec{t})}{\partial t_j}\leq M_{ij}$ 

定义 $M=\max\left\{|M_{ij}|,|m_{ij}|\big|1\leq i\leq n, 1\leq j\leq n-1\right\}$ ，定义 $\vec{t}_1,\vec{t}_2\in D_{n-1}$ 为区域内任意两点

若 $\vec{t}_1,\vec{t}_2$ 之间的连线 $l_{12}\in D_{n-1}$ 则根据[[e:/OneDrive/数学分析/Note/Chapter 12/Chap12Note.org][多元函数中值定理与Taylor公式-中值定理]]有

\begin{aligned}
\left|f_i(\vec{t}_2)-f_i(\vec{t}_1)\right|&=\left|\sum_{j=1}^{n-1} \frac{\partial f_i(\vec{t}_1+\theta(\vec{t}_2-\vec{t}_1))}{\partial t_j}(t_{2j}-t_{1j})\right|\\
&\leq \sum_{j=1}^{n-1} \left|\frac{\partial f_i(\vec{t}_1+\theta(\vec{t}_2-\vec{t}_1))}{\partial t_j}\right||t_{2j}-t_{1j}|\\
&\leq \sum_{j=1}^{n-1} M|t_{2j}-t_{1j}|\\
&=M \sum_{j=1}^{n-1}|t_{2j}-t_{1j}|\\
&\leq M \sum_{j=1}^{n-1}\left|\vec{t}_2-\vec{t}_1\right|\\
&\leq M(n-1)\left|\vec{t}_2-\vec{t}_1\right|\\
\end{aligned}

若 $l_{12}\not\in D_{n-1}$ 但存在分段连线 $l_{13},l_{34},...,l_{(n-1)n},l_{n2}$ ，同理可证以上结论。

由于 $D_{n-1}$ 为连通集，根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][连续函数性质-补充连通定义-连通集定义]]不存在 $\vec{t}_1,\vec{t}_2$ 没有通路的情况，所以

\begin{aligned}
\left|\vec{f}(\vec{t}_2)-\vec{f}(\vec{t}_1)\right|&=\sqrt{\sum_{i=1}^n \left(f_i(\vec{t}_2)-f_i(\vec{t}_1)\right)^2}\\
&\leq \sqrt{\sum_{i=1}^n \left(M(n-1)|\vec{t}_2-\vec{t}_1|\right)^2}\\
&= M(n-1)\sqrt{\sum_{i=1}^n \left(|\vec{t}_2-\vec{t}_1|\right)^2}\\
&=M\sqrt{n}(n-1)|\vec{t}_2-\vec{t}_1|\\
\end{aligned}

定义 $L=M\sqrt{n}(n-1)$ 则有 $\left|\vec{f}(\vec{t}_2)-\vec{f}(\vec{t}_1)\right|\leq L|\vec{t}_2-\vec{t}_1|$

*** 证明体积为零

将 $D_{n-1}$ 分割成 $N^{n-1}$ 个长方体，即每个维度 $N$ 等分。

因为有界，所以对于 $t_j$ 均有上下界，即 $t_j\in[a_j,b_j]$

定义某一长方体 $d$ 故对于 $d\cap D_{n-1}$ 而言：

（1） 两点间距离 $|\vec{t}_2-\vec{t}_1|\leq \sqrt{\sum_{j=1}^{n-1}\left(\frac{b_j-a_j}{N}\right)^2}=\frac{\sqrt{\sum_{j=1}^{n-1}(b_j-a_j)^2}}{N}$ 定义 $Z=\sqrt{\sum_{j=1}^{n-1}(b_j-a_j)^2}$

（2） 定义 $\vec{\tau}$ 为矩形的中点，则对于任意一点 $\vec{t}$ 均有 $|\vec{t}-\vec{\tau}|\leq \frac{Z}{N}$

故根据上一步证明，有 $\left|\vec{f}(\vec{t})-\vec{f}(\vec{\tau})\right|\leq L|\vec{t}-\vec{\tau}|\leq L\frac{Z}{N}$

即对于 $d\cap D_{n-1}$ 而言，所有 $\vec{t}$ 在 $\vec{f}(\vec{t})$ 的映射均落在领域 $O\left(\vec{\tau},L\frac{Z}{N}\right)\in R^n$ 内

领域落在边长为 $2L\frac{Z}{N}$ 的长方体内，对于 $n$ 维度空间，长方体体积为 $\left(2L\frac{Z}{N}\right)^n$

由于 $\vec{f}(\vec{t})$ 的所有映射均包含在长方体内，且一共有 $N^{n-1}$ 个长方体

定义 $V$ 为 $\vec{f}(\vec{t})$ 的体积，则有 $0\leq V\leq  N^{n-1}\left(2L\frac{Z}{N}\right)^n=2L\frac{Z}{N}$ 故有 $\lim_{N\to\infty} 2L\frac{Z}{N}=0$

故，根据夹逼定理 $V=0$

* 有界闭集上的重积分

** 可求封闭曲线（曲面）的面积（体积）充要条件

有界点集 $D$ 可求面积（体积）的充要条件是他的边界点集 $\partial D$ 的面积（体积）是零

边界点 $\vec{x}\in \partial D$ 定义为 $\forall \delta>0, \exists \vec{\alpha},\vec{\beta} \in O(\vec{x},\delta)\Rightarrow \alpha\in D, \beta\in D^c$

*** 举例（边界点集面积不为零）

定义点集 $S=\left\{(x,y)\big|0\leq x\leq1,0\leq y\leq D(x)\right\}$ 其中 $D(x)=\begin{cases}1,&x=\frac{p}{q},p,q\in N^+\\0,&x\ne\frac{p}{q},p,q\in N^+\end{cases}$ 为Dirichlet函数

故对于任意一点 $(x_0,y_0)\in [0,1]\times[0,1]$ 根据有理数稠密性 $\forall\rho>0,O((x_0,y_0),\rho),\exists (x_1,y_1)\in D,(x_2,y_2)\not\in D\Rightarrow (x_0,y_0)\in \partial D$

故 $\partial D$ 的面积为 $1$

** 曲面体直径定义

若 $D$ 为有界点集，其边界点 $\partial D$ 。直径的定义为 $\phi=\max(|\vec{x}-\vec{y}|),\ \ \vec{x},\vec{y}\in \partial D$

** 二重积分

*** 定义

定义曲顶柱体：顶为 $z=f(x,y),(x,y)\in D$ 其中 $D$ 为边界为零的平面区域；侧面为 $D$ 为准线，母线平行与 $z$ 轴的柱面。

用面积为零的网格线将 $D$ 分割为 $D_i,i=1,2,...,n$ 若 $\sigma_i$ 是 $D_i$ 的底面积 $(\xi_i,\eta_i)\in D_i$ 则曲顶柱体的面积可近似为 $\sum_{i=1}^n f(\xi_i,\eta_i)\sigma_i$

若 $\phi_i$ 是 $D_i$ 的直径，定义 $\lambda=\max(\phi_i),\ i=1,2,...,n$ 当 $\lambda\to0$ 时有：

（1） 极限 $\lim_{\lambda\to0}\sum_{i=1}^n f(\xi_i,\eta_i)\sigma_i=V$ 存在

（2） $V$ 的值与划分 $D_i$ 及取点 $(\xi_i,\eta_i)$ 无关

则定义 $f(x,y)$ 在 $D$ 上可积，极限 $V$ 为 $f(x,y)$ 在 $D$ 上的二重积分，记为 $\iint_D f(x,y)d\sigma=\lim_{\lambda\to0}\sum_{i=1}^n f(\xi_i,\eta_i)\sigma_i=V$

*** 推论

若 $D$ 是有界闭集，且 $f(x,y)$ 在 $D$ 上连续，则可积

**** <<MK1>>证明

由于有界闭集，则根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][Euclid空间基本定理-Heine-Borel定理]]得 $D$ 是紧集，又由于 $f(x,y)$ 连续，根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][连续函数性质-康托定理]]得函数一直连续，

定义 $S=\sum_{i=1}^n \sigma_i$ 为 $D$ 的面积，故有 $\forall \epsilon>0, \exists \delta, \forall \vec{x}',\vec{x}''\in K, |\vec{x}'-\vec{x}''|<\delta \Rightarrow \left|\vec{f}(\vec{x}')-\vec{f}(\vec{x}'')\right|<\frac{\epsilon}{S}$

定义 $\omega_i=sup\{f(\xi_i,\eta_i)\}-inf\{f(\xi_i,\eta_i)\},\ \ \xi_i,\eta_i\in D_i$ 为振幅，则当 $\lambda<\delta$ 时 $\omega_i<\epsilon$ ，则和式 $\sum_{i=1}^n \omega_i\sigma_i<\sum_{i=1}^n \frac{\epsilon}{S}\sigma_i=\epsilon$ 

故的 $\forall \epsilon>0,\exists \delta,\forall \lambda<\delta\Rightarrow \sum_{i=1}^n\omega_i\sigma_i<\epsilon$ 即 $\lim_{\lambda\to0}\sum_{i=1}^n\omega_i\sigma_i=0$ 故根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定积分可积充要条件2]]得黎曼积分可积

** 多重积分

*** 定义

若 $D$ 为 $R^n$ 上的有界点集，且期边界点 $\partial D$ 的面积为零。用体积为零的网面将 $D$ 分割为 $D_i,i=1,2,...,n$

定义 $f(\vec{x})$ 为 $\vec{x}\in D$ 上的函数， $v_i$ 为 $D_i$ 的体积， $\vec{\xi}_i\in D_i$ 是 $D_i$ 中的一点， $\phi_i$ 为 $D_i$ 的直径 $\lambda=\max(\phi_i)$

则黎曼和为 $\sum_{i=1}^n f(\vec{\xi}_i)v_i$ 若：

（1） 极限 $\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{\xi}_i)v_i=A$ 存在；

（2） $A$ 的值与划分和取点无关

则定义 $f(\vec{x})$ 在 $D$ 上可积，极限 $A$ 为 $f(\vec{x})$ 在 $D$ 上的 $n$ 重积分，记为 $\int...\int_D f(\vec{x})dv=\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{\xi}_i)v_i=A$

*** <<MK11>>推论

若 $D$ 是有界闭集，且 $f(\vec{x})$ 在 $D$ 上连续，则可积。证明与[[MK1][之前证明]]同理

** Peano曲线

*** 曲线构造

曲线为函数 $\vec{f}(t)$ 的映射，其中 $t\in[0,1]$ ， $\vec{f}(t)\in R^2$ 为数轴到平面的映射

对于边长为 $\frac{1}{2}$ 的等边三角形进行 $n$ 个分形，每一次分形将其中的每一个三角形边的中点相连分割成 $4$ 个子三角形。

故最小子三角形的边长为 $\frac{1}{2^{n+1}}$ ，个数为 $4^n$ 。可用 $\Delta^i_j$ 来表示第 $i$ 次分型后最小子三角形编号 $j=1,2,...,4^i$

第 $i$ 次分形对应的曲线函数 $\vec{f}_i(t)$ 为过每个最小子三角形的分段曲线，即 $\vec{f}_i(t)\in\Delta^i_j,\ \ t\in\left[\frac{j-1}{4^i},\frac{j}{4^i}\right]$

*** 映射构造

对于给定 $t$ 定义点列 $\{\vec{f}_n(t)\}$ 当给定 $m>n$ 时，对于 $t\in\left[\frac{j-1}{4^n},\frac{j}{4^n}\right]\subset[0,1]$ 均有 $\vec{f}_m(t)\in \Delta^n_j$ 

因为分形只将原有三角形继续分割，且 $\vec{f}_m(t)$ 为 $\vec{f}_n(t)$ 分形后的曲线，故只要 $t\in\left[\frac{j-1}{4^n},\frac{j}{4^n}\right]\subset[0,1]$ 则必定属于分形前三角形区域内

由于等边三角形 $\Delta^n_i$ 边长为 $\frac{1}{2^{n+1}}$ 故综上所述 $\forall m>n>0,m\in N^+,n\in N^+\Rightarrow \left|\vec{f}_n(t)-\vec{f}_m(t)\right|\leq \frac{1}{2^{n+1}}$

综上所述 $\forall \epsilon>0,\exists N=\frac{\ln\frac{1}{2\epsilon}}{\ln 2},\forall n>N\Rightarrow \left|\vec{f}_n(t)-\vec{f}_m(t)\right|\leq\frac{1}{2^{n+1}}<\epsilon$

根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-柯西收敛原理]] $\lim_{n\to\infty}\vec{f}_n(t)$ 收敛，定义 $\vec{f}(t)=\lim_{n\to\infty}\vec{f}_n(t)$

故对于任意给定 $t\in[0,1]$ 存在映射 $\vec{f}(t)$

*** 证明面积

定义 $S=\left\{\vec{f}(t)\big|t\in[0,1]\right\}$ 由于 $[0,1]$ 有界闭集，根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][Euclid空间基本定理-Heine-Borel定理]]得出是紧集。

又根据据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][连续函数性质-紧集的连续映射（连续函数）也是紧集]]得出 $S$ 也为紧集，同理 $S$ 有界闭集。 

则根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][构造Euclid空间-开集与闭集-闭集定义]]故有 $S$ 包含聚点。

由于 $\vec{f}(t)=\lim_{n\to\infty}\vec{f}_n(t)$ 故有 $\forall \delta>0,\exists N_1,\forall n>N_1\Rightarrow \left|\vec{f}_n(t)-\vec{f}(t)\right|<\frac{\delta}{2}$

又因为对于任意 $\vec{a}$ 在三角形内，其必定属于其中某一个子三角形 $\vec{a}\in\Delta^n_i$ 故 $\forall \delta >0, \exists N_2=\frac{\ln\frac{1}{4\delta}}{\ln2},\forall n>N_2,\exists t\in\left[\frac{i-1}{4^n},\frac{i}{4^n}\right]\Rightarrow \left|\vec{f}_n(t)-\vec{a}\right|<\frac{\delta}{2}$

故 $\forall \delta>0, \exists N=\max(N_1,N_2),\forall n>N,\exists t_0\in\left[\frac{i-1}{4^n},\frac{i}{4^n}\right]\Rightarrow \left|f(t_0)-\vec{a}\right|\leq\left|f(t_0)-f_n(t_0)\right|+\left|f_n(t_0)-\vec{a}\right|<\delta$ 即 $\vec{f}(t_0)\in O(\vec{a},\delta)$

故对于 $\vec{a}$ 的任意领域均包含 $S$ 的点，故根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][构造Euclid空间-开集与闭集-点的定义]] $\vec{a}$ 为 $S$ 的聚点。又由于 $S$ 闭集，故 $\vec{a}\in S$

由此三角形内所有点都为曲线聚点，曲线 $S$ 面积为三角形的面积。

* 可积条件：

** <<MK33>>可积充要条件1：

$L=l\Leftrightarrow \lim_{\lambda \to 0}{\sum_{i=1}^n f(\vec{\xi}_i)v_i} = L$

其中 $L$ 为达布大和， $l$ 为达布小和，证明同[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定积分可积充要条件1]]

** <<MK31>>可积充要条件2：

\begin{aligned}
&\omega_i=M_i-m_i \\
&\lim_{\lambda \to 0} \overline S(P)=\lim_{\lambda \to 0} \underline S(P) \Leftrightarrow \forall P:\lim_{\lambda \to 0} \sum_{i=1}^n \omega_i v_i = 0
\end{aligned}

其中 $M_i$ 为区域 $\sigma_i$ 中最大值， $m_i$ 为区域 $\sigma_i$ 中的最小值，则 $\omega_i$ 为该区域的振幅

证明同[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定积分可积充要条件2]]

** <<MK2>>重积分可积充要条件3

若边界为零的有界点集 $D$ 被面积为零的曲面网分割为 $D_i,i=1,2,...,n$ ，存在函数 $f(\vec{x})$ 为被积函数

\begin{aligned}
&\omega_i=M_i-m_i \\
&\forall \epsilon > 0, \exists P:\ \sum_{i=1}^n \omega_i v_i < \epsilon \Leftrightarrow\forall P: \lim_{\lambda \to 0} \sum_{i=1}^n \omega_i v_i = 0
\end{aligned}

其中 $P$ 为某一类对区域 $D$ 的划分 $\lambda=\min(\phi_i)$ 。对于某个分割的区域 $D_i$ 来说： $\omega_i$ 为振幅 $v_i$ 为体积 $\phi_i$ 为直径

*** 证明

**** 充分性

假设对于 $R^k$ 上可积函数 $f(\vec{x})$ 有 $\forall \epsilon>0,\exists P'\Rightarrow \sum_{i=1}^{n'}\omega'_iv'_i<\frac{\epsilon}{2}$ 其中 $\lambda'=\max(\phi'_i)$

根据任意新分点 $\forall P$ 在 $P'$ 上构建 $P^*$ 为 $P'$ 增加了 $P$ 划分，是两个划分的合集，即曲面网的重叠。

***** $P$ 与 $P^*$ 划分的关系

对于任意一个 $P$ 划分下的子点集 $D_i$ ，在 $P^*$ 划分下存在两种情况：

（1） $D_i$ 不包含 $P'$ 划分的曲面网，该子点集与 $P^*$ 划分的对应子点集振幅、面积相同 

（2） $D_i$ 包含 $P'$ 划分的曲面网，并被曲面网进一步划分

      定义此类子点集为 $D_{i^*},i^*=1,2,...,k$ 定义 $\lambda_*=\max(\phi_{i^*})$
  
      定义内部被划分为 $n_{i^*}$ 个，每个为 $D_{i^*j},j=1,2,...,n_{i^*}$

则有 $\sum_{i=1}^n\omega_iv_i-\sum_{i=1}^{n^*}\omega^*_iv^*_i&=\sum_{i^*=1}^k\left\{\omega_{i^*} v_{i^*}-\sum_{j=1}^{n_{i*}}\omega_{i^*j}v_{i^*j}\right\}\leq \sum_{i^*=1}^k \omega_{i^*} v_{i^*}$

根据定义 $P'$ 划分的曲面网体积为零，又因为 $D_{i^*}$ 为包含曲面网的划分子点集，故有 $\lim_{\lambda_*\to0}\sum_{i^*=1}^k v_{i^*}=0$ 对于任意划分 $P$ 均成立

又由于 $\sum_{i=1}^{n'}\omega'_iv'_i<\frac{\epsilon}{2}<\infty$ 故 $\omega'_i$ 有上界，由于 $\omega'_i=M'_i-m'_i$ 其中 $M'_i$ 为区域 $D'_i$ 中 $f(\vec{\xi}'_i)$ 的最大值 $m'_i$ 为最小值 

故定义 $\omega'=\max(M'_i)-\min(m'_i)$ 由于 $D'_i$ 覆盖整个被积区域，故 $\omega'$ 可视为 $f(\vec{x})$ 在 $D$ 上的最大振幅，即 $\omega'\geq\omega_{i^*}$

综上所述，有 $\forall \epsilon>0,\exists \delta,\forall \lambda<\delta\Rightarrow \forall P: \sum_{i^*=1}^k v_{i^*}<\frac{\epsilon}{2\omega'}$ 即 $\sum_{i=1}^n\omega_iv_i-\sum_{i=1}^{n^*}\omega^*_iv^*_i\leq \sum_{i^*=1}^k \omega_{i^*} v_{i^*}\leq \omega'\sum_{i^*=1}^k  v_{i^*}<\frac{\epsilon}{2}$

***** $P'$ 与 $P^*$ 划分的关系

对于 $P'$ 划分下的子点集 $D'_i$ ，在 $P^*$ 划分下存在两种情况：

（1） $D'_i$ 不被进一步分割

（2） $D'_i$ 被进一步分割

      定义此类子点集为 $D'_{i^*},i^*=1,2,...,k$ 

      定义内部被划分为 $n_{i^*}$ 个，每个为 $D'_{i^*j},j=1,2,...,n_{i^*}$

则有 $\sum_{i=1}^n\omega'_iv'_i-\sum_{i=1}^{n^*}\omega^*_iv^*_i&=\sum_{i^*=1}^k\left\{\omega'_{i^*} v'_{i^*}-\sum_{j=1}^{n_{i*}}\omega'_{i^*j}v'_{i^*j}\right\}$

由于 $\omega'_{i^*j}$ 为振幅为 $\omega'_{i^*}$ 的区域进一步划分而得，故有 $\omega'_{i^*}\geq\omega'_{i^*j}$ 又因为 $v'_{i^*}=\sum_{j=1}^{n_{i*}}v'_{i^*j}$ 故有 $\omega'_{i^*} v'_{i^*}\geq\sum_{j=1}^{n_{i*}}\omega'_{i^*j}v'_{i^*j}$

综上所述 $\sum_{i=1}^n\omega'_iv'_i-\sum_{i=1}^{n^*}\omega^*_iv^*_i\geq 0$ 即 $\sum_{i=1}^{n^*}\omega^*_iv^*_i-\sum_{i=1}^n\omega'_iv'_i\leq 0$

***** 综合条件

故当 $\lambda<\min(\lambda',\delta)$ 时，对于任意划分 $P$ 有：

\begin{aligned}
\sum_{i=1}^n \omega_i v_i &=\left\{\sum_{i=1}^n \omega_i v_i-\sum_{i=1}^{n^*} \omega^*_i v^*_i \right\} + \left\{\sum_{i=1}^{n^*} \omega^*_i v^*_i - \sum_{i=1}^{n'} \omega'_i v'_i \right\} + \sum_{i=1}^{n'} \omega'_i \Delta x_i\\
&< \frac{\epsilon}{2} + 0 + \frac{\epsilon}{2} \\
&= \epsilon
\end{aligned}
 
又由于 $\sum_{i=1}^n \omega_i v_i>0$ ，故充分性证毕。

**** 必要性

根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定积分可积充要条件2]]得 $\forall P:\lim_{\lambda \to 0} \sum_{i=1}^n \omega_i v_i = 0$ 即 $\forall\epsilon>0,\exists \delta, \forall \lambda<\delta\Rightarrow \forall P: \sum_{i=1}^n \omega_iv_i<\epsilon$

故 $&\forall \epsilon > 0, \exists P:\ \sum_{i=1}^n \omega_i v_i < \epsilon$

* 重积分性质与计算

** 性质

*** <<MK3>>线性

若 $f(\vec{x}),g(\vec{x})$ 在有界点集 $D$ 上可积，则 $Af(\vec{x})+Bg(\vec{x})$ 在点集 $D$ 上亦可积，且 $\int_D\{Af(\vec{x})+Bg(\vec{x})\}dv=A\int_Df(\vec{x})dv+B\int_Dg(\vec{x})dv$

**** 证明

根据极限四则运算 $\lim_{\lambda\to0}\sum_{i=1}^n\{Af(\vec{\xi}_i)+Bg(\vec{\xi}_i)\}\sigma_i=A\lim_{\lambda\to0}\sum_{i=1}^nf(\vec{\xi}_i)\sigma_i+B\lim_{\lambda\to0}\sum_{i=1}^ng(\vec{\xi}_i)\sigma_i$

由于 $f(\vec{x}),g(\vec{x})$ 可积，故有 $\int_D f(\vec{x})dv=\lim_{\lambda\to0}\sum_{i=1}^nf(\vec{\xi}_i)\sigma_i,\int_D g(\vec{x})dv=\lim_{\lambda\to0}\sum_{i=1}^ng(\vec{\xi}_i)\sigma_i$ 且与划分，取点无关

故对于任意划分，取点 $\lim_{\lambda\to0}\sum_{i=1}^n\{Af(\vec{\xi}_i)+Bg(\vec{\xi}_i)\}\sigma_i=A\int_D f(\vec{x})dv+B\int_D g(\vec{x})dv$ 故 $Af(\vec{x})+Bg(\vec{x})$ 亦可积，且 $\int_D\{Af(\vec{x})+Bg(\vec{x})\}dv=A\int_Df(\vec{x})dv+B\int_Dg(\vec{x})dv$
 
*** <<MK6>>区间可加性

设 $D$ 被面积为零的曲面分为两个内点不相交的有界区域 $D_1,D_2$ ：

（1） 若 $f(\vec{x})$ 在 $D$ 上可积，则在 $D_1,D_2$ 上亦可积

（2） 若 $f(\vec{x})$ 在 $D_1,D_2$ 上可积，

且两者均有 $\int_D f(\vec{x})dv=\int_{D_1} f(\vec{x})dv+\int_{D_2} f(\vec{x})dv$

**** 证明

***** 证明（1）

根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定积分可积充要条件2]]得 $\lim_{\lambda\to0}\sum_{i=1}^n v_i \sigma_i=0$ 对于任意划分，其中 $\omega_i$ 为区域 $D_i$ 上函数的振幅

则存在一种划分（划分曲面面积为零），将 $D$ 分割成 $D_1,D_2$ 即 $\lim_{\lambda\to0}\sum_{i=1}^n \omega_i v_i=\lim_{\lambda\to0}\sum_{i=1}^n \omega_i v^1_i+\lim_{\lambda\to0}\sum_{i=1}^n \omega_i v^2_i=0$ 其中 $v^1_i$ 为 $D_{1i}$ 的体积

由于振幅和体积均为正数，故 $\lim_{\lambda\to0}\sum_{i=1}^n \omega_i v^1_i=\lim_{\lambda\to0}\sum_{i=1}^n \omega_i v^2_i=0$

即有 $\forall \epsilon >0,\exists P\Rightarrow \sum_{i=1}^n \omega_i v^1_i<\epsilon$ 则根据[[MK2][重积分可积充要条件3]]得 $\forall P:\lim_{\lambda\to0} \sum_{i=1}^n \omega_iv^1_i=0$ 同理可得 $\forall P:\lim_{\lambda\to0} \sum_{i=1}^n \omega_iv^2_i=0$ 

又根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定积分可积充要条件2]]得 $f(\vec{x})$ 在 $D_1,D_2$ 上分别可积

***** 证明（2）

由 $f(\vec{x})$ 在 $D_1,D_2$ 上可积得 $\int_{D_2} f(\vec{x})dv=\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{\xi}_i) v^1_i,\int_{D_1} f(\vec{x})dv=\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{\xi}_i) v^2_i$

且根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定积分可积充要条件2]]得 $\lim_{\lambda\to0}\sum_{i=1}^n \omega_i v^1_i=0,\lim_{\lambda\to0}\sum_{i=1}^n \omega_i v^2_i=0$

由于存在一种划分将 $D$ 切分为 $D_1,D_2$ （划分曲面面积为零）则这种划分下有 $\lim_{\lambda\to0}\sum_{i=1}^n \omega_i v_i=\lim_{\lambda\to0}\sum_{i=1}^n \omega_i v^1_i+\lim_{\lambda\to0}\sum_{i=1}^n \omega_i v^2_i=0$

则有 $\forall \epsilon>0,\exists P\Rightarrow \sum_{i=1}^n \omega_i v_i<\epsilon$ 故根据[[MK2][重积分可积充要条件3]]得 $\forall P:\lim_{\lambda\to0} \sum_{i=1}^n \omega_iv_i=0$ 即 $f(\vec{x})$ 在 $D$ 上可积 

***** 证明等式

由于存在一种划分切分 $D$ 为 $D_1,D_2$ ，故有 $\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{\xi}_i) v_i=\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{\xi}_i) v^1_i+\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{\xi}_i) v^2_i$

由于根据可积定义，对于任意划分 $\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{\xi}_i) v_i,\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{\xi}_i) v^1_i,\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{\xi}_i) v^2_i$ 的值不变，故对于任意划分 $P$ 均有上述性质。

又由于可积得 $\int_D f(\vec{x})dv=\int_{D_1} f(\vec{x})dv+\int_{D_2} f(\vec{x})dv$

*** <<MK5>>当 $f(\vec{x})=1$ 时

$\int_D f(\vec{x})dv=\int_D dv$ 为被积区域的体积（被积区域为平面时为面积）

**** 证明

根据可积定义 $\int_D f(\vec{x})dv=\lim_{\lambda\to0}\sum_{i=1}^nf(\vec{\xi}_i)v_i$ 当 $f(\vec{x})=1$ 时为 $\lim_{\lambda\to0}\sum_{i=1}^nv_i$ 由于对于任意 $\lambda$ 均有 $V=\sum_{i=1}^nv_i$ 其中 $V$ 为被积区域体积

故有 $\forall \epsilon>0,\exists \delta=1,\forall \lambda<\delta\Rightarrow \sum_{i=1}^n v_i-V=0<\epsilon$ 即 $\lim_{\lambda\to0}\sum_{i=1}^nf(\vec{\xi}_i)v_i=V=\int_Ddv$

*** <<MK4>>保序性

若 $f(\vec{x}),g(\vec{x})$ 在有界区域 $D$ 上可积，且有 $f(\vec{x})\geq g(\vec{x})$ ，则可得 $\int_D f(\vec{x})dv\geq \int_D g(\vec{x})dv$

**** 证明

由于 $f(\vec{x})-g(\vec{x})\geq0$ 根据重积分[[MK3][线性]]性质 $\int_D f(\vec{x})dv-\int_D g(\vec{x})dv=\int_D\left\{f(\vec{x})-g(\vec{x})\right\}dv>0$ 

*** 重积分上下确界

若 $f(\vec{x})$ 在有界区域 $D$ 上可积，且 $f(\vec{x})$ 在 $D$ 上上下确界分别为 $M,m$ 则 $mV\leq\int_D f(\vec{x})dv\leq MV$

**** 证明

根据[[MK3][线性]]有 $\int_D Mdv=M\int_D dv$ 根据[[MK5][该性质]]有 $\int_D Mdv=M\int_D dv=MV$ 同理可证 $\int_D mdv=mv$ 

由于 $m\leq f(x)\leq M$ 根据[[MK4][保序性]] $mV\leq\int_D f(\vec{x})dv\leq MV$

*** 绝对可积性

若 $f(\vec{x})$ 在有界区域 $D$ 上可积，则 $|f(\vec{x})|$ 在区域 $D$ 上也可积，且有 $\left|\int_D f(\vec{x})dv\right|\leq \int_D |f(\vec{x})|dv$

**** 证明

***** 证明可积

由于可积，根据[[MK31][可积充要条件2]]可得 $\lim_{\lambda \to 0} \sum_{i=1}^n \omega^f_i v_i = 0$ 其中 $\omega^f_i$ 为函数 $f(\vec{x})$ 在区域 $\sigma_i$ 中的振幅

定义 $g(\vec{x})=|f(\vec{x})|$ 则有 $\omega^g_i\leq\omega^f_i$ 其中 $\omega^g_i$ 为函数 $g(\vec{x})$ 在区域 $\sigma_i$ 中的振幅

则有 $\omega_i^g\leq \omega_i^f\Rightarrow 0\leq\lim_{\lambda \to 0} \sum_{i=1}^n \omega_i^g \Delta x_i\leq \lim_{\lambda \to 0} \sum_{i=1}^n \omega_i^f \Delta x_i=0$

根据夹逼定理 $\lim_{\lambda \to 0} \sum_{i=1}^n \omega_i^g \Delta x_i=0$ 根据[[MK1][定积分可积充要条件2]] $g(\vec{x})=|f(\vec{x})|$ 可积

***** 证明不等式

由于 $-|f(\vec{x})|\leq f(\vec{x})\leq|f(\vec{x})|$ 故根据[[MK4][保序性]]可得 $\int_D-|f(\vec{x})|dv\leq \int_D f(\vec{x})dv\leq\int_D|f(\vec{x})|dv$

根据[[MK3][线性]] $-\int_D|f(\vec{x})|dv\leq \int_D f(\vec{x})dv\leq\int_D|f(\vec{x})|dv\Rightarrow \left|\int_D f(\vec{x})dx\right|\leq\int_D|f(\vec{x})|dv$

*** 相乘可积

若 $f(\vec{x}),g(\vec{x})$ 在有界区域 $D$ 上可积，则 $f(\vec{x})g(\vec{x})$ 在区域 $D$ 上也可积

**** 证明

由于可积，则有 $\lim_{\lambda^f\to 0}\sum_{i=1}^n (M^f_i-m^f_i)v_i=0,\lim_{\lambda^g\to 0}\sum_{i=1}^n (M^g_i-m^g_i)v_i=0$ 故 $f(\vec{x}),g(\vec{x})$ 在区域 $D$ 上有上下确界，定义 $M>|f(\vec{x})|,M>|g(\vec{x})|,\vec{x}\in D$

又根据极限定义有 $\forall \epsilon>0,\exsists \delta_1,\forall\lambda<\delta\Rightarrow \forall P:\sum_{i=1}^n (M^f_i-m^f_i)v_i<\frac{\epsilon}{2M}$ 及 $\forall \epsilon>0,\exsists \delta_2,\forall\lambda<\delta\Rightarrow \forall P:\sum_{i=1}^n (M^g_i-m^g_i)v_i<\frac{\epsilon}{2M}$

则当 $\lambda<\min(\delta_1,\delta_2)$ 时有

\begin{aligned}
\left|\sum_{i=1}^n (M^{fg}_i-m^{fg}_i)v_i\right|&=\left|\sum_{i=1}^n \left[f(\vec{\xi}_i)g(\vec{\xi}_i)-f(\vec{\eta}_i)g(\vec{\eta}_i)\right]v_i\right|\\
&=\left|\sum_{i=1}^n \left[f(\vec{\xi}_i)g(\vec{\xi}_i)-g(\vec{\xi}_i)f(\vec{\eta}_i)+g(\vec{\xi}_i)f(\vec{\eta}_i)-f(\vec{\eta}_i)g(\vec{\eta}_i)\right]v_i\right|\\
&=\left|\sum_{i=1}^n \left[g(\vec{\xi}_i)\left(f(\vec{\xi}_i)-f(\vec{\eta}_i)\right)+f(\vec{\eta}_i)\left(g(\vec{\xi}_i)-g(\vec{\eta}_i)\right)\right]v_i\right|\\
&\leq \sum_{i=1}^n \left|g(\vec{\xi}_i)\left(f(\vec{\xi}_i)-f(\vec{\eta}_i)\right)+f(\vec{\eta}_i)\left(g(\vec{\xi}_i)-g(\vec{\eta}_i)\right)\right|v_i\\
&\leq \sum_{i=1}^n \left\{|g(\vec{\xi}_i)|\left|f(\vec{\xi}_i)-f(\vec{\eta}_i)\right|+|f(\vec{\eta}_i)|\left|g(\vec{\xi}_i)-g(\vec{\eta}_i)\right|\right\}v_i\\
&\leq \sum_{i=1}^nM\left|f(\vec{\xi}_i)-f(\vec{\eta}_i)\right|v_i+\sum_{i=1}^nM\left|g(\vec{\xi}_i)-g(\vec{\eta}_i)\right|v_i\\
&\leq M\sum_{i=1}^n\left(M^f_i-m^f_i\right)v_i+M\sum_{i=1}^n\left(M^g_i-m^g_i\right)v_i\\
&<\frac{\epsilon}{2}+\frac{\epsilon}{2}=\epsilon\\
\end{aligned}

*** <<MK9>>积分中值定理

若 $f(\vec{x}),g(\vec{x})$ 在有界区域 $D$ 上可积且 $g(\vec{x})$ 不变号，设 $M=sup\left\{f(\vec{x})\big|\vec{x}\in D\right\},m=inf\left\{f(\vec{x})\big|\vec{x}\in D\right\}$ 

则存在常数 $\eta\in [m,M]\Rightarrow \int_D f(\vec{x})g(\vec{x})dv=\eta\int_D g(\vec{x})dv$

若函数 $f(\vec{x})$ 在 $D$ 上连续，则存在点 $\vec{\xi}\in D\Rightarro \int_D f(\vec{x})g(\vec{x})dv=f(\xi)\int_D g(\vec{x})dv$

**** 证明

***** 存在常数 $\eta$

由于 $M,m$ 为上下确界，则必有不等式 $mg(\vec{x})\leq f(\vec{x})g(\vec{x})\leq Mg(\vec{x})$

根据[[MK4][保序性]]有 $\int_D mg(\vec{x})dv\leq \int_D f(\vec{x})g(\vec{x})dv\leq \int_DMg(\vec{x})dv$

根据[[MK3][线性]]有 $m\int_D g(\vec{x})dv\leq \int_D f(\vec{x})g(\vec{x})dv\leq M\int_Dg(\vec{x})dv$

由于 $g(\vec{x})$ 不变号，不妨设 $g(\vec{x})>0$ 则有 $m\leq \frac{\int_D f(\vec{x})g(\vec{x})dv}{\int_Dg(\vec{x})dv}\leq M$

故定义 $\eta=\frac{\int_D f(\vec{x})g(\vec{x})dv}{\int_Dg(\vec{x})dv}$ 则有 $\eta\in [m,M], \int_D f(\vec{x})g(\vec{x})dv=\eta\int_D g(\vec{x})dv$

***** 连续情况下

假设 $D\in R^n$ 若 $D$ 为空集，则以上结论均为零。

若 $D$ 非空，可根据维度将区域 $D$ 划分成 $2^n$ 个子区域 $D^1_i,i=1,2,...,2^n$ 

切分时每个维度以 $D$ 在该维度轴上映射可取到的最大值与最小值的中点展开的数轴法平面为切分面。

由于 $D$ 有界，故必有直径 $diam D<\infty$ 由于切分方法，必有 $diam D^1_i<diam D$ 

由于 $\eta\in [m,M]$ 故必有某些个 $D^1_i$ 区域上 $f(\vec{x}),\vec{x}\in D^1_i$ 的上下确界 $[m^1_i,M^1_i]$ 包含 $\eta \in [m^1_i,M^1_i]$

假定 $D^1_i$ 为其中一个，一同样的方法对期进行分割，并选取同样的 $D^2_i$ 再进行分割。

故形成闭区间套 $D\supset D^1_i\supset D^2_i\supset...\supset D^n_i\supset...\\$ ，由于分割方法，故有 $\lim_{n\to\infty}diam D^n_i=0$

故根[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][据构造Euclid空间-Euclid空间基本定理-康托闭区域套定理]]，必有唯一一点 $\vec{\xi}\in \cap_{n=1}^\infty D^n_i$ ，且有 $\eta\in[m^k_i,m^k_j],\forall k\in N^+$

由于函数连续 $\lim_{\vec{x}\to\vec{\xi}}f(\vec{x})=f(\vec{\xi})$ 故有 $\forall \epsilon>0,\exists \delta>0,\forall \vec{x}\in O(\vec{\xi},\delta)\Rightarrow |f(\vec{x})-f(\vec{\xi})|<\epsilon\Rightarrow f(\vec{\xi})-\epsilon<f(\vec{x})<f(\vec{\xi})+\epsilon$

由于 $\lim_{n\to\infty}diam D^n_i=0$ ，故 $\exists N,\forall n>N\Rightarrow D^n_i\subset O(\vec{\xi},\delta)$ 且该 $D^n_i$ 的上下确界 $f(\vec{\xi})-\epsilon\leq m^n_i\leq M^n_i\leq f(\vec{\xi})+\epsilon$ 

即 $\forall \epsilon>0,\exists N,\forall n>N\Rightarrow |m^n_i-f(\vec{\xi})|<\epsilon, |M^n_i-f(\vec{\xi})|<\epsilon$ 故 $\lim_{n\to\infty}m^n_i=\lim_{n\to\infty}M^n_i=f(\vec{\xi})$

又因为 $m^n_i\leq \eta\leq M^n_i$ 故 $\lim_{n\to\infty}\eta=f(\vec{\xi})$ 由于 $\eta$ 常数，故得 $\eta=f(\vec{\xi})$

** 重积分计算

*** <<MK7>>矩形上的重积分

定义矩形 $D=[a_1,b_1]\times[a_2,b_2]\times...\times[a_n,b_n]\subset R^n$ （矩形 $\Rightarrow$ 边界为零），定义 $D^*=[a_2,b_2]\times...\times[a_n,b_n]\subset R^{n-1}$ 若：

（1） $f(\vec{x})$ 在 $D$ 上可积，即 $\int_D f(\vec{x})dv$ 存在

（2） 对于任意 $x_1\in[a_1,b_1]$ 重积分 $\int_{D^*}f(\vec{x})dv$ 存在

（3） 对于任意 $x_2\in[a_2,b_2],...,x_n\in[a_n,b_n]$ 积分 $\int_{a_1}^{b_1}f(\vec{x})dx_1$ 存在

则有条件（1），（2）推出 $\int_D f(\vec{x})dv=\int_{a_1}^{b_1}\left\{\int_{D^*}f(\vec{x})dv\right\}dx_1$

条件（1），（3）推出 $\int_D f(\vec{x})dv=\int_{D^*}\left\{\int_{a_1}^{b_1}f(\vec{x})dx_1\right\}dv$

**** 证明

***** 前提定义

定义 $\vec{x}=(x_1,\vec{x}^*)=(x_1,x_2,...,x_n)$ 

定义划分 $P^n$ 为将 $[a_i,b_i]$ 做法平面划分为 $a_i=x_{i_0}<x_{i_1}<...<x_{i_{k_i}}=b_i$ 

定义 $x_{i_v}-x_{i_{v-1}}=\Delta x_{i_v}$ 定义 $\lambda_i=\max(\Delta x_{i_v})$

划分 $P^n$ 将矩形划分为 $K=\Pi_{i=1}^n k_i=k_1\Pi_{i=2}^n k_i=k_1K^*$ 个子矩形，定义 $D_{v_1v_2...v_n}=D_{\vec{v}}=D_{v_1\vec{v}^*}$ 为各维度对应的子矩形区域

定义 $M_{\vec{v}}=sup\{f(\vec{x})|\vec{x}\in D_{\vec{v}}\},m_{\vec{v}}=inf\{f(\vec{x})|\vec{x}\in D_{\vec{v}}\}$ ，定义 $Vol_{\vec{v}}$ 为 $D_{\vec{v}}$ 的体积，则在当前划分下 $Vol_{\vec{v}_j}=\Pi_{i=1}^n \Delta x_{ij}=Vol_{\vec{v}_j}^*\Delta x_{1j}$

定义 $\lambda=\max(Diam(D_{\vec{v}}))$ 为所有子矩形 $D_{\vec{v}}$ 的最大直径

***** 函数有界推出不等式

\begin{aligned}
&\int_{D^*}f(\vec{x})dv=\sum_{j=1}^{K^*}\int_{D_{\vec{v}_j}}f(\vec{x})dv\\
&\int_{a_1}^{b_1}f(\vec{x})dx_1=\sum_{i=1}^{k_1}\int_{a_{1i}}^{b_{1i}}f(\vec{x})dx_1
\end{aligned} 

根据定义 $m_{\vec{v}_j} \leq f(\vec{x})\leq M_{\vec{v}_j},\vec{x}\in D_{\vec{v}_j}$ 根据[[MK4][保序性]]有不等式

\begin{aligned}
&\sum_{j=1}^{K^*}\int_{D_{\vec{v}_j}}m_{\vec{v}_j}dv\leq\sum_{j=1}^{K^*}\int_{D_{\vec{v}_j}}f(\vec{x})dv\leq\sum_{j=1}^{K^*}\int_{D_{\vec{v}_j}}M_{\vec{v}_j}dv\\
&\sum_{i=1}^{k_1}\int_{a_{1i}}^{b_{1i}}m_{i\vec{v}_j}dx_1\leq\sum_{i=1}^{k_1}\int_{a_{1i}}^{b_{1i}}f(\vec{x})dx_1\leq \sum_{i=1}^{k_1}\int_{a_{1i}}^{b_{1i}}M_{i\vec{v}_j}dx_1\\
\end{aligned}

根据[[MK3][线性]]及[[MK5][重积分性质]]又可对以上不等式做以下推论

\begin{aligned}
\sum_{j=1}^{K^*}\int_{D_{\vec{v}_j}}M_{\vec{v}_j}dv=\sum_{j=1}^{K^*}M_{\vec{v}_j}\int_{D_{\vec{v}_j}}dv=\sum_{j=1}^{K^*}M_{\vec{v}_j}Vol_{\vec{v}_j}=\sum_{j=1}^{K^*}M_{\vec{v}_j}\Pi_{i=2}^n \Delta x_{ij}\\
\sum_{j=1}^{K^*}\int_{D_{\vec{v}_j}}m_{\vec{v}_j}dv=\sum_{j=1}^{K^*}m_{\vec{v}_j}\int_{D_{\vec{v}_j}}dv=\sum_{j=1}^{K^*}m_{\vec{v}_j}Vol_{\vec{v}_j}=\sum_{j=1}^{K^*}m_{\vec{v}_j}\Pi_{i=2}^n \Delta x_{ij}
\end{aligned}

同理亦有

\begin{aligned}
&\sum_{i=1}^{k_1}\int_{a_{1i}}^{b_{1i}}m_{i\vec{v}_j}dx_1=\sum_{i=1}^{k_1}m_{i\vec{v}_j}\int_{a_{1i}}^{b_{1i}}dx_1=\sum_{i=1}^{k_1}m_{i\vec{v}_j}\Delta x_{1i}\\
&\sum_{i=1}^{k_1}\int_{a_{1i}}^{b_{1i}}M_{i\vec{v}_j}dx_1=\sum_{i=1}^{k_1}M_{i\vec{v}_j}\int_{a_{1i}}^{b_{1i}}dx_1=\sum_{i=1}^{k_1}M_{i\vec{v}_j}\Delta x_{1i}\\
\end{aligned}

***** 根据定义构建不等式

根据累次积分定义：

\begin{aligned}
&\int_{a_1}^{b_1}\left\{\int_{D^*}f(\vec{x})dv\right\}dx_1=\lim_{\lambda_1\to0}\sum_{v_1=1}^{k_1}\int_{D^*}f(\vec{x})dv\Delta x_{1v_1}\\
&\int_{D^*}\left\{\int_{a_1}^{b_1}f(\vec{x})dx_1\right\}dv=\lim_{\lambda\to0}\sum_{j=1}^{K^*}\left\{\sum_{i=1}^{k_1}\int_{a_{1i}}^{b_{1i}}f(\vec{x})dx_1\right\}Vol_{\vec{v}_j}^*
\end{aligned}

对于黎曼和 $\sum_{j=1}^{k_1}\int_{D^*}f(\vec{x})dv\Delta x_{1_j}$ 结合之前不等式有 

\begin{aligned}
&\sum_{v_1=1}^{k_1} \left\{\sum_{j=1}^{K^*}m_{\vec{v}_j}\Pi_{i=2}^n \Delta x_{ij}\right\}\Delta x_{1v_1}\leq\sum_{v_1=1}^{k_1}\int_{D^*}f(\vec{x})dv\Delta x_{1v_1}\leq\sum_{v_1=1}^{k_1}\left\{\sum_{j=1}^{K^*}M_{\vec{v}_j}\Pi_{i=2}^n \Delta x_{ij}\right\}\Delta x_{1v_1}\\
\Rightarrow &\sum_{j=1}^{K}m_{\vec{v}_j}\Pi_{i=1}^n \Delta x_{ij}\leq\sum_{v_1=1}^{k_1}\int_{D^*}f(\vec{x})dv\Delta x_{1v_1}\leq\sum_{j=1}^{K}M_{\vec{v}_j}\Pi_{i=1}^n \Delta x_{ij}\\
\Rightarrow &\sum_{j=1}^{K}m_{\vec{v}_j}Vol_{\vec{v}_j}\leq\sum_{v_1=1}^{k_1}\int_{D^*}f(\vec{x})dv\Delta x_{1_{v_1}}\leq\sum_{j=1}^{K}M_{\vec{v}_j}Vol_{\vec{v}_j}\\
\end{aligned}

对于黎曼和 $\sum_{j=1}^{K^*}\left\{\sum_{i=1}^{k_1}\int_{a_{1i}}^{b_{1i}}f(\vec{x})dx_1\right\}Vol_{\vec{v}_j}^*$ 结合之前不等式有

\begin{aligned}
&\sum_{j=1}^{K^*}\left\{\sum_{i=1}^{k_1}m_{i\vec{v}_j}\Delta x_{1i}\right\}Vol_{\vec{v}_j}^*\leq\sum_{j=1}^{K^*}\left\{\sum_{i=1}^{k_1}\int_{a_{1i}}^{b_{1i}}f(\vec{x})dx_1\right\}Vol_{\vec{v}_j}^*\leq\sum_{j=1}^{K^*}\left\{\sum_{i=1}^{k_1}M_{i\vec{v}_j}\Delta x_{1i}\right\}Vol_{\vec{v}_j}^*\\
\Rightarrow&\sum_{j=1}^{K}m_{\vec{v}_j}\Pi_{i=1}^n \Delta x_{ij}\leq\sum_{j=1}^{K^*}\left\{\sum_{i=1}^{k_1}\int_{a_{1i}}^{b_{1i}}f(\vec{x})dx_1\right\}Vol_{\vec{v}_j}^*\leq\sum_{j=1}^{K}M_{\vec{v}_j}\Pi_{i=1}^n \Delta x_{ij}\\
\Rightarrow&\sum_{j=1}^{K}m_{\vec{v}_j}Vol_{\vec{v}_j}\leq\sum_{j=1}^{K^*}\left\{\sum_{i=1}^{k_1}\int_{a_{1i}}^{b_{1i}}f(\vec{x})dx_1\right\}Vol_{\vec{v}_j}^*\leq\sum_{j=1}^{K}M_{\vec{v}_j}Vol_{\vec{v}_j}
\end{aligned}

***** 证明结论

其中 $\sum_{j=1}^{K}M_{\vec{v}_j}Vol_{\vec{v}_j},\sum_{j=1}^{K}m_{\vec{v}_j}Vol_{\vec{v}_j}$ 分别为 $P^n$ 划分下 $\int_D f(\vec{x})dv$ 对应的达布大和与达布小和

又因为 $\int_D f(\vec{x})dv$ 可积，则根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定积分可积充要条件1]]得 

\begin{aligned}
&\forall P:\lim_{\lambda\to0}\overline{S}(P)=\lim_{\lambda\to0}\underline{S}(P)=\lim_{\lambda\to0}\sum_{j=1}^{K}f(\vec{\xi}_j)Vol_{\vec{v}_j}=\int_D f(\vec{x})dv,&\vec{\xi}_j\in D_{\vec{v}_j}
\end{aligned}

故有 $\lim_{\lambda\to0}\sum_{j=1}^{K}m_{\vec{v}_j}Vol_{\vec{v}_j}=\lim_{\lambda\to0}\sum_{j=1}^{K}M_{\vec{v}_j}Vol_{\vec{v}_j}=\int_D f(\vec{x})dv$ 

又因 $\lambda_1\leq\lambda$ 故 $\lambda\to0\Rightarrow\lambda_1\to0$ 所以 $\lim_{\lambda_1\to0}\sum_{v_1=1}^{k_1}\int_{D^*}f(\vec{x})dv\Delta x_{1_{v_1}}=\lim_{\lambda\to0}\sum_{v_1=1}^{k_1}\int_{D^*}f(\vec{x})dv\Delta x_{1_{v_1}}$ 故根据夹逼定理

\begin{aligned}
\lim_{\lambda_1\to0}\sum_{v_1=1}^{k_1}\int_{D^*}f(\vec{x})dv\Delta x_{1v_1}=\lim_{\lambda\to0}\sum_{j=1}^{K^*}\left\{\sum_{i=1}^{k_1}\int_{a_{1i}}^{b_{1i}}f(\vec{x})dx_1\right\}Vol_{\vec{v}_j}^*=\int_D f(\vec{x})dv
\end{aligned}

所以 $\int_D f(\vec{x})dv=\int_{a_1}^{b_1}\left\{\int_{D^*}f(\vec{x})dv\right\}dx_1=\int_{a_1}^{b_1}dx_1\int_{D^*}f(\vec{x})dv=\int_{D^*}\left\{\int_{a_1}^{b_1}f(\vec{x})dx_1\right\}dv$ 证毕。

**** 推论

定义矩形 $D=[a_1,b_1]\times[a_2,b_2]\times...\times[a_n,b_n]\subset R^n$ （矩形 $\Rightarrow$ 边界为零），定义 $D^i=[a_i,b_i]\times...\times[a_n,b_n]\subset R^{n-i}$ 若：

（1） $f(\vec{x})$ 在 $D$ 上可积，即 $\int_D f(\vec{x})dv$ 存在

（2） 对于任意给定一组 $x_j\in[a_j,b_j],j=1,2,...,i-1$ 积分 $\int_{D^i}f(\vec{x})dv$ 均存在 $i=1,2,...,n$

则有 $\int_D f(\vec{x})dv=\int_{a_1}^{b_1}...\int_{a_n}^{b_n}f(\vec{x})dx_n...dx_1=\int_{a_1}^{b_1}dx_1...\int_{a_{n-1}}^{b_{n-1}}dx_{n-1}\int_{a_n}^{b_n}f(\vec{x})dx_n$

*** <<MK8>>不规则区域上重积分

定义零边界点集 $D\subset R^n$ ，定义 $D^*=\left\{\vec{x}^*\big|\exists x_1\Rightarrow (x_1,\vec{x}^*)\in D\right\}$

定义 $x_1\in[a,b]$ 且 $D^*(x_1)$ 为当给定 $x_1$ 剩下 $n-1$ 维度中包含于 $D$ 的区域，若：

（1） $f(\vec{x})$ 在 $D$ 上可积，即 $\int_D f(\vec{x})dv$ 存在

（2） 对于任意 $x_1\in[a,b]$ 重积分 $\int_{D^*(x_1)}f(\vec{x})dv$ 存在

则有 $\int_D f(\vec{x})dv=\int_{a_1}^{b_1}\left\{\int_{D^*}f(\vec{x})dv\right\}dx_1$

定义 $\vec{x}^*=(x_2,x_3,...,x_n)\in D^*$ 时 $x_1\in\left[a(\vec{x}^*),b(\vec{x}^*)\right]\Rightarrow (x_1,\vec{x}^*)\in D$ 若：

（1） $f(\vec{x})$ 在 $D$ 上可积，即 $\int_D f(\vec{x})dv$ 存在

（2） 对于任意 $x_2\in[a_2,b_2],...,x_n\in[a_n,b_n]$ 积分 $\int_{a(\vec{x}^*)}^{b(\vec{x}^*)}f(\vec{x})dx_1$ 存在

则有 $\int_D f(\vec{x})dv=\int_{D^*}\left\{\int_{a(\vec{x}^*)}^{b(\vec{x}^*)}f(\vec{x})dx_1\right\}dv$

**** 证明

***** 前提定义

定义区域 $\overline{D}=[a,b]\times[a_2,b_2]\times...\times[a_n,b_n]$ 为包含 $D$ 的矩形区域，即 $D\subset \overline{D}$ 

定义 $\overline{D}_c=D_c\cap\overline{D}$ 为 $D$ 的补集 $D_c$ 与 $\overline{D}$ 的交集

同样定义 $\overline{D}^*=[a_2,b_2]\times...\times[a_n,b_n],\overline{D}^*_c=D^*_c\cap\overline{D}^*$ 

定义 $\overline{f}(\vec{x})=\begin{cases}f(\vec{x})&\vec{x}\in D\\0&\vec{x}\in\overline{D}_c\end{cases}$

由于 $\overline{f}(\vec{x})$ 在 $D,\overline{D}_c$ 上均可积，根据[[MK6][区域可加性]]则有 $\int_{\overline{D}}\overline{f}(\vec{x})dv$ 可积，且 $\int_{\overline{D}}\overline{f}(\vec{x})dv=\int_{\overline{D}_c}\overline{f}(\vec{x})dv+\int_{D}\overline{f}(\vec{x})dv=0+\int_{D}f(\vec{x})dv$

***** 证明 $\int_D f(\vec{x})dv=\int_{a_1}^{b_1}\left\{\int_{D^*}f(\vec{x})dv\right\}dx_1$

根据[[MK7][矩形区域重积分]]可得 $\int_{\overline{D}}\overline{f}(\vec{x})dv=\int_a^b\left\{\int_{\overline{D}^*}\overline{f}(\vec{x})dv\right\}dx_1$ 当给定 $x_1$ 时 

$\forall\vec{x}^*\in D^*(x_1)\Rightarrow (x_1,\vec{x}^*)\in D$ 

$\forall\vec{x}^*\not\in D^*(x_1)\Rightarrow (x_1,\vec{x}^*)\not\in D$ 

根据条件 $\int_{D^*(x_1)}\overline{f}(\vec{x})dv=\int_{D^*(x_1)}f(\vec{x})dv$ 存在 $\int_{\overline{D}^*_c(x_1)}\overline{f}(\vec{x})dv=0$ 同样可积

故根据[[MK6][区域可加性]]有 $\int_{\overline{D}^*}\overline{f}(\vec{x})dv=\int_{D^*(x_1)}\overline{f}(\vec{x})dv+\int_{\overline{D}^*_c(x_1)}\ovelrline{f}(\vec{x})dv=\int_{D^*(x_1)}f(\vec{x})dv$

故综上所述 $\int_{D}f(\vec{x})dv=\int_{\overline{D}}\overline{f}(\vec{x})dv=\int_a^b\left\{\int_{\overline{D}^*}\overline{f}(\vec{x})dv\right\}dx_1=\int_a^b\left\{\int_{D^*(x_1)}f(\vec{x})dv\right\}dx_1$ 证毕。

***** 证明 $\int_D f(\vec{x})dv=\int_{D^*}\left\{\int_{a_1}^{b_1}f(\vec{x})dx_1\right\}dv$

根据[[MK7][矩形区域重积分]]可得 $\int_{\overline{D}}\overline{f}(\vec{x})dv=\int_{\overline{D}^*}\left\{\int_a^b\overline{f}(\vec{x})dx_1\right\}dv$

又根据定义 $\overline{D}^*=D^*\cup\overline{D}^*_c$ 故根据[[MK6][区域可加性]] $\int_{\overline{D}^*}\left\{\int_{a}^{b}f(\vec{x})dx_1\right\}dv=\int_{D^*}\left\{\int_{a}^{b}f(\vec{x})dx_1\right\}dv+\int_{\overline{D}^*_c}\left\{\int_{a}^{b}f(\vec{x})dx_1\right\}dv$

两者均可积，且因为 $\forall x_1,\vec{x}^*\in \overline{D}^*_c\Rightarrow (x_1,\vec{x}^*)\in \overline{D}_c\Rightarrow f(x_1,\vec{x}^*)=0$ 故根据[[MK3][线性]] $\int_{\overline{D}^*_c}\left\{\int_{a}^{b}f(\vec{x})dx_1\right\}dv=0$

则有 $\int_{\overline{D}^*}\left\{\int_{a}^{b}f(\vec{x})dx_1\right\}dv=\int_{D^*}\left\{\int_{a}^{b}f(\vec{x})dx_1\right\}dv$

根据条件 $\int_{a(\vec{x}^*)}^{b(\vec{x}^*)}\overline{f}(\vec{x})dx_1=\int_{a(\vec{x}^*)}^{b(\vec{x}^*)}f(\vec{x})dx_1$ 存在 $\int_{a}^{a(\vec{x}^*)}\overline{f}(\vec{x})dx_1=\int_{b(\vec{x}^*)}^{b}\overline{f}(\vec{x})dx_1=0$

故根据[[MK6][区域可加性]]有 $\int_{D^*}\left\{\int_a^b\overline{f}(\vec{x})dx_1\right\}dv=\int_{D^*}\left\{\int_{a}^{a(\vec{x}^*)}\overline{f}(\vec{x})dx_1+\int_{a(\vec{x}^*)}^{b(\vec{x}^*)}\overline{f}(\vec{x})dx_1+\int_{b(\vec{x}^*)}^{b}\overline{f}(\vec{x})dx_1\right\}dv=\int_{D^*}\left\{\int_{a(\vec{x}^*)}^{b(\vec{x}^*)}f(\vec{x})dx_1\right\}dv$

故综上所述 $\int_{D}f(\vec{x})dv=\int_{\overline{D}}\overline{f}(\vec{x})dv=\int_{\overline{D}^*}\left\{\int_a^b\overline{f}(\vec{x})dx_1\right\}dv=\int_{D^*}\left\{\int_{a}^{b}f(\vec{x})dx_1\right\}dv=\int_{D^*}\left\{\int_{a(\vec{x}^*)}^{b(\vec{x}^*)}f(\vec{x})dx_1\right\}dv$ 证毕。

**** 推论

定义 $\vec{x}_i=(x_1,x_2,...,x_{i-1})$ 定义函数 $u_i(\vec{x}_i)>v_i(\vec{x}_i),v_1(\vec{x}_1)=a,u_1(\vec{x}_1)=b$ ，定义 $D_i=[v_i(\vec{x}_i),u_i(\vec{x}_i)]\times[v_{i+1}(\vec{x}_{i+1}),u_{i+1}(\vec{x}_{i+1})]\times...\times[v_n(\vec{x}_n),u_n(\vec{x}_n)]$ 若：

（1） 区域 $D_i,i=1,2,...,n$ 为零边界区域

（1） $f(\vec{x})$ 在 $D_1=D$ 上可积，即 $\int_D f(\vec{x})dv$ 存在

（2） 对于任意给定定义域内 $\vec{x}_i$ ，积分 $\int_{D^i}f(\vec{x})dv$ 均存在 $i=1,2,...,n$

则有 $\int_D f(\vec{x})dv=\int_{v_1(\vec{x}_1)}^{u_1(\vec{x}_1)}...\int_{v_n(\vec{x}_n)}^{u_n(\vec{x}_n)}f(\vec{x})dx_n...dx_1=\int_{v_1(\vec{x}_1)}^{u_1(\vec{x}_1)}dx_1...\int_{v_{n-1}(\vec{x}_{n-1})}^{u_{n-1}(\vec{x}_{n-1})}dx_{n-1}\int_{v_n(\vec{x}_n)}^{u_n(\vec{x}_n)}f(\vec{x})dx_n$

*** 经典例子

**** 黎曼函数

定义黎曼函数 $R(x)=\begin{cases}\frac{1}{q},&x=\frac{p}{q}\\0,&x\ne\frac{p}{q},x=0,x=1\end{cases}$ 其中 $p,q$ 为互质的正整数 $x\in[0,1]$

黎曼函数在定义域上的积分 $\int_0^1R(x)dx=0$

***** 可积性

由于 $p,q$ 为互质的正整数，故对于任意 $\epsilon>0$ 来说，假设 $\frac{1}{k}>\frac{\epsilon}{2}\geq \frac{1}{k+1}$ 

则大于 $\frac{\epsilon}{2}$ 的 $x$ 取值可列为 $\frac{1}{2},\frac{1}{3},\frac{2}{3},...,\frac{1}{k},\frac{2}{k},...,\frac{k-1}{k}$ 中去掉非互质的值。

由于 $\epsilon$ 已经给定，故 $k$ 为正整数（有限），故大于 $\frac{\epsilon}{2}$ 的 $x$ 取值为有限个，定义为 $K$ 个，定义集合 $S=\{x|R(x)>\frac{\epsilon}{2}\}$

定义划分 $P:0=x_1<x_2<...<x_n=1$ 定义 $\Delta x_i=x_i-x_{i-1},\xi_i\in[x_{i-1},x_i]$ 定义 $\lambda=\max(\Delta x_i)$

写出黎曼和为 $\sum_{i=1}^n R(\xi_i)\Delta x_i$ 由于一共有 $k-1$ 个点大于 $\frac{\epsilon}{2}$ 则最多有 $2(k-1)$ 个区间包含这些点

故将黎曼和分为两部分 $\sum_{i=1}^n R(\xi_i)\Delta x_i=\sum_{i=1}^{n'} R(\xi'_i)\Delta x'_i+\sum_{i=1}^{n''} R(\xi''_i)\Delta x''_i$ 

其中 $\sum_{i=1}^{n'} R(\xi'_i)\Delta x'_i$ 定义为 $[x_{i-1},x_i]\cap S\ne \varnothing$ 的区间的黎曼和，由于 $S$ 只有 $K$ 个元素，故 $n'\leq 2K$

$\sum_{i=1}^{n''} R(\xi''_i)\Delta x''_i$ 定义为 $[x_{i-1},x_i]\cap S=\varnothing$ 的区间的黎曼和

当 $\lambda<\frac{\epsilon}{2K}$ 时，有：

（1） $\sum_{i=1}^{n'} R(\xi'_i)\Delta x'_i\leq \frac{1}{2}\sum_{i=1}^{n'}\Delta x'_i\leq\frac{1}{2}\sum_{i=1}^{n'}\frac{\epsilon}{2K}=\frac{1}{2}\frac{n'\epsilon}{2K}\leq\frac{\epsilon}{2}$

（2） $\sum_{i=1}^{n''} R(\xi''_i)\Delta x''_i\leq \frac{\epsilon}{2}\sum_{i=1}^{n''} \Delta x''_i\leq \frac{\epsilon}{2}$ 由于积分区间为 $[0,1]$ 

又由于函数均为正值，故可知 $\forall \epsilon>0,\exists \delta=\frac{\epsilon}{2K},\forall \lambda<\delta\Rightarrow \forall P:\sum_{i=1}^n R(\xi_i)\Delta x_i=\sum_{i=1}^{n'} R(\xi'_i)\Delta x'_i+\sum_{i=1}^{n''} R(\xi''_i)\Delta x''_i<\epsilon$

即为 $\lim_{\lambda\to0}\sum_{i=1}^n R(\xi_i)\Delta x_i=0=\int_0^1R(x)dx$ 证毕。

**** 二维空间黎曼函数

定义函数 $R(x,y)=\begin{cases}\frac{1}{p_x}+\frac{1}{p_y},&x=\frac{q_x}{p_x},y=\frac{q_y}{p_y}\\0,& x\ne\frac{q_x}{p_x},y\ne\frac{q_y}{p_y}\end{cases}$ 其中 $q_x,p_x$ 互质正整数 $q_y,p_y$ 也互质正整数 $(x,y)\in D=[0,1]\times[0,1]$

***** 可积性

定义函数 $R_1(x,y)=\begin{cases}\frac{1}{p_x},&x=\frac{q_x}{p_x},y=\frac{q_y}{p_y}\\0,& x\ne\frac{q_x}{p_x},y\ne\frac{q_y}{p_y}\end{cases},R_2(x,y)=\begin{cases}\frac{1}{p_y},&x=\frac{q_x}{p_x},y=\frac{q_y}{p_y}\\0,& x\ne\frac{q_x}{p_x},y\ne\frac{q_y}{p_y}\end{cases}$ 

****** 下面证明函数 $R_1(x,y)$ 在定义域 $D$ 上可积， $R_2(x,y)$ 同理可证 

对于任意 $\epsilon>0$ 仅存在有限个 $\frac{1}{2},\frac{1}{3},...,\frac{1}{k}>\frac{\epsilon}{2}$ 对应 $x$ 可列 $\frac{1}{2},\frac{1}{3},\frac{2}{3},...,\frac{1}{k},\frac{2}{k},...,\frac{k-1}{k}$ 有限个值，记一共 $K$ 个，定义集合 $S=\{x|R\left(x,\frac{1}{2}\right)>\frac{\epsilon}{2}\}$

将区域 $D$ 用垂直于 $x$ 轴，交于 $x\in S$ 的 $K$ 条线段分割为 $K+1$ 个区域。定义 $K$ 条线段的集合为 $U$ 用方格法可证明 $U$ 的面积为零。

当边界为零的网格线划分 $D$ 为 $D_i,i=1,2,...,n$ 后，写出黎曼和 $\sum_{i=1}^n R_1(\xi_i,\eta_i)\sigma_i$ 其中 $(\xi_i,\sigma_i)\in D_i$ 且 $\sigma_i$ 为 $D_i$ 的面积。定义 $\lambda=\max(diam D_i)$

将黎曼和分为两部分 $\sum_{i=1}^n R_1(\xi_i,\eta_i)\sigma_i=\sum_{i=1}^{n'} R_1(\xi'_i,\eta'_i)\sigma'_i+\sum_{i=1}^{n''} R_1(\xi''_i,\eta''_i)\sigma''_i$ 其中

$\sum_{i=1}^{n'} R_1(\xi'_i,\eta'_i)\sigma'_i$  为对应 $D_i\cap U\ne\varnothing$ 的黎曼和部分， $\sum_{i=1}^{n''} R_1(\xi''_i,\eta''_i)\sigma''_i$ 为对应 $D_i\cap U=\varnothing$ 的黎曼和部分

由于 $U$ 的面积为零，所以 $\exists \delta, \forall \lambda<\delta\Rightarrow\forall P:\sum_{i=1}^{n'}\sigma'_i<\epsilon$ 故当 $\lambda<\delta$ 时

（1） 函数只有在 $x\in U$ 上可能有 $R_1(x,y)>\frac{\epsilon}{2}$ ，即 $\sum_{i=1}^{n''} R_1(\xi''_i,\eta''_i)\sigma''_i\leq\frac{\epsilon}{2}\sum_{i=1}^{n''}\sigma''_i\leq\frac{\epsilon}{2}$ 

（2） 函数在 $x\in U$ 上的值最大为 $\frac{1}{2}$ 则有 $\sum_{i=1}^{n'} R_1(\xi'_i,\eta'_i)\sigma'_i\leq\frac{1}{2}\sum_{i=1}^{n'}\sigma'_i\leq\frac{1}{2}\epsilon$

综上所述，即 $\forall\epsilon>0,\exists\delta,\forall\lambda<\delta\Rightarrow\forall P:\sum_{i=1}^n R_1(\xi_i,\eta_i)\sigma_i=\sum_{i=1}^{n'} R_1(\xi'_i,\eta'_i)\sigma'_i+\sum_{i=1}^{n''} R_1(\xi''_i,\eta''_i)\sigma''_i<\epsilon$ 

即 $\lim_{\lambda\to0}\sum_{i=1}^n R_1(\xi_i,\eta_i)\sigma_i=0$ 对于任意划分与取点，即 $\int_D R_1(x,y)d\sigma=0$

****** 证明 $R(x,y)$ 在 $D$ 上可积

$R(x,y)=R_1(x,y)+R_2(x,y)$ 由于 $\int_DR_1(x,y)d\sigma=\int_DR_2(x,y)d\sigma=0$ 

根据重积分[[MK3][线性]]性质 $\int_DR(x,y)d\sigma$ 亦可积且 $\int_DR(x,y)d\sigma=\int_DR_1(x,y)d\sigma+\int_DR_2(x,y)d\sigma=0$ 证毕

***** 重积分存在累次积分不存在

当 $y=\frac{1}{2}$ 时 $R(x,y)=\begin{cases}\frac{1}{p_x}+\frac{1}{2}>\frac{1}{2},&x=\frac{q_x}{p_x}\\0,& x\ne\frac{q_x}{p_x}\end{cases}$ 由有理数稠密性得，对于任意区域 $[x_{i-1},x_i]\subset[0,1]$ 均包含有理数及无理数，故振幅 $\omega_i>\frac{1}{2}$

故对于任意划分，均有 $\sum_{i=1}^n \omega_i\Delta x_i>\frac{n}{2}$ 推出积分 $\int_0^1 R\left(x,\frac{1}{2}\right)dx$ 不存在，即不可积。

* 重积分变量代还

假设 $T$ 为区域 $D\subset R^n$ 上的映射，即对于 $\vec{x}\in D$ 有函数 $\vec{t}=\vec{T}(\vec{x})=\begin{cases}t_1=T_1(x_1,x_2,...,x_n)\\t_2=T_2(x_1,x_2,...,x_n)\\...\\t_n=T_n(x_1,x_2,...,x_n)\\\end{cases}$ 定义为 $\vec{t}\in T(D)\in R^n$ 若

（1） 函数 $\vec{T}(\vec{x})$ 有连续偏导，且映射关系一一对应，即 $\vec{x}_1=\vec{x}_2\Rightarrow \vec{T}(\vec{x})=\vec{T}(\vec{x}),\ \ \vec{x}_1\ne\vec{x}_2\Rightarrow \vec{T}(\vec{x})\ne\vec{T}(\vec{x})$

（2） 雅克比行列式不为零，即 $\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial \vec{x}}\right)\ne0$

（3） 存在连续函数 $f(\vec{t})$

（4） $D$ 为连通的有界闭集（不连通可根据[[MK6][区域可加性]]化为 $n<\infty$ 个连通有界闭集）

则重积分可用以下变量代换 $$\int_D f\left(\vec{T}(\vec{x})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial\vec{x}}\right)\right|dv=\int_{T(D)} f(\vec{t})dv$$

** 证明

*** <<MK13>>引理1：本源映射长方体的体积有 $\left|\det\left(\frac{\partial \vec{T}(\vec{\xi})}{\partial\vec{x}}\right)\right|V(A)=V(T(A)),\vec{\xi}\in A$

**** 定义本源映射

假设对于某个 $1\leq k\leq n$ 来说 $t_k=T_k(\vec{x})$ 其余均为 $t_i=x_i,i=1,2,...,n, i\ne k$ 

**** 本源映射性质

定义 $T_{kx_i}=\frac{\partial T_k(\vec{x})}{\partial x_i}$ 则其在点 $\vec{x}$ 的雅克比矩阵为：

$$\left[\begin{matrix}
1&0&...&0\\
0&1&...&0\\
...&...&...&...\\
T_{kx_1}&T_{kx_2}&...&T_{kx_n}\\
...&...&...&...\\
0&0&...&1\\
\end{matrix}\right]$$

由于雅克比行列式为 $\vec{T}(\vec{x})$ 偏导乘加所得，故偏导连续得出<<MK10>> $\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial \vec{x}}\right)$ 连续，又因为 $\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial \vec{x}}\right)\ne0$ 故 $\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial \vec{x}}\right)$ 不变号 

该式雅克比行列式为 $T_{kx_k}=\frac{\partial T_k(\vec{x})}{\partial x_k}$ 

**** 等式推导

假设 $\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial \vec{x}}\right)=\frac{\partial T_k(\vec{x})}{\partial x_k}>0$ ，定义一个长方体为 $A=[a_1,b_1]\times[a_2,b_2]\times...\times[a_n,b_n]\subset D$ 

定义 $(a_k,\vec{x}_k)=(x_1,x_2,...,a_k,...,x_n),(b_k,\vec{x}_k)=(x_1,x_2,...,b_k,...,x_n)$

则经过以上映射的到的图形 $B$ 来说，对于 $i\ne k$ 为度的映射值域 $t_i\in[a_i,b_i]$ 对于 $i=k$ 则 $t_k\in[T_k(a_k,\vec{x}_k),T_k(b_k,\vec{x}_k)]$

根据定义 $A$ 的体积 $V(A)=\Pi_{i=1}^n(b_i-a_i)$ 由于 $B$ 不是长方体，故体积为重积分 $\int_B dv$ 被积函数为 $1$ 

由于 $1$ 为连续函数，故对于任意降维零边界积分均存在，则根据[[MK8][重积分化累次积分]]有

\begin{aligned}
\int_B dv&=\int_{a_1}^{b_1}dt_1...\int_{a_{k-1}}^{b_{k-1}}dt_{k-1}\int_{a_{k+1}}^{b_{k+1}}dt_{k+1}...\int_{a_n}^{b_n}dt_n\int_{T_k(b_k,\vec{x}_k)}^{T_k(a_k,\vec{x}_k)}dt_k\\
&=\int_{a_1}^{b_1}dt_1...\int_{a_{k-1}}^{b_{k-1}}dt_{k-1}\int_{a_{k+1}}^{b_{k+1}}dt_{k+1}...\int_{a_n}^{b_n}[T_k(b_k,\vec{x}_k)-T_k(a_k,\vec{x}_k)]dt_n
\end{aligned}

定义 $\vec{x}_k\in A^k=[a_1,b_1]\times[a_2,b_2]\times...\times[a_{k-1},b_{k-1}]\times[a_{k+1},b_{k+1}]\times...\times[a_n,b_n]$ 故同理根据[[MK8][重积分化累次积分]]的逆运算

\begin{aligned}
\int_B dv&=\int_{a_1}^{b_1}dt_1...\int_{a_{k-1}}^{b_{k-1}}dt_{k-1}\int_{a_{k+1}}^{b_{k+1}}dt_{k+1}...\int_{a_n}^{b_n}dt_n\int_{T_k(b_k,\vec{x}_k)}^{T_k(a_k,\vec{x}_k)}dt_k\\
&=\int_{a_1}^{b_1}dt_1...\int_{a_{k-1}}^{b_{k-1}}dt_{k-1}\int_{a_{k+1}}^{b_{k+1}}dt_{k+1}...\int_{a_n}^{b_n}[T_k(b_k,\vec{x}_k)-T_k(a_k,\vec{x}_k)]dt_n\\
&=\int_{A^k}[T_k(b_k,\vec{x}_k)-T_k(a_k,\vec{x}_k)]dv\\
\end{aligned}

定义 $[T_k(\vec{x}_u)-T_k(\vec{x}_l)] *1$ 为被积函数，则有结论

（1） 函数 $1$ 不变号

（2） 由于 $T_k(\vec{x})$ 有连续偏导，故根据[[e:/OneDrive/数学分析/Note/Chapter 12/Chap12Note.org][偏导数与全微分-可微条件]]得出可微，根据[[e:/OneDrive/数学分析/Note/Chapter 12/Chap12Note.org][偏导数与全微分-欧几里得空间连续，可导，可微及方向导数关系-可微与连续]]推出<<MK12>> $T_k(\vec{x})$ 连续

（3） $[T_k(b_k,\vec{x}_k)-T_k(a_k,\vec{x}_k)]$ 根据结论（2）也连续 

（4） 由于连续映射，且 $A^k$ 为有界集闭集，

      根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-Heine-Borel定理]]及[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][连续函数性质-紧集的连续映射（连续函数）也是紧集]]得出 $[T_k(\vec{x}_u)-T_k(\vec{x}_l)]$ 有界

定义  则根据[[MK9][积分中值定理]]有

\begin{aligned}
\int_B dv&=\int_{a_1}^{b_1}dt_1...\int_{a_{k-1}}^{b_{k-1}}dt_{k-1}\int_{a_{k+1}}^{b_{k+1}}dt_{k+1}...\int_{a_n}^{b_n}dt_n\int_{T_k(b_k,\vec{x}_k)}^{T_k(a_k,\vec{x}_k)}dt_k\\
&=\int_{a_1}^{b_1}dt_1...\int_{a_{k-1}}^{b_{k-1}}dt_{k-1}\int_{a_{k+1}}^{b_{k+1}}dt_{k+1}...\int_{a_n}^{b_n}[T_k(b_k,\vec{x}_k)-T_k(a_k,\vec{x}_k)]dt_n\\
&=\int_{A^k}[T_k(b_k,\vec{x}_k)-T_k(a_k,\vec{x}_k)]dv\\
&=[T_k(b_k,\vec{\xi}_k)-T_k(a_k,\vec{\xi}_k)]\int_{A^k}dv &\vec{\xi}_k\in A^k\\
&=\frac{[T_k(b_k,\vec{\xi}_k)-T_k(a_k,\vec{\xi}_k)]}{b_k-a_k}\Pi_{i=1}^n(b_i-a_i) &\vec{\xi}_k\in A^k\\
\end{aligned}

又因为结论（2）可得 $T_k(u,\vec{\xi})$ 对于 $u$ 在 $[a,b]$ 连续，根据条件（1）得出 $u$ 在 $(a,b)$ 可导，故根据[[e:/OneDrive/大学物理/Note/DiffEq.org][导数基本知识-拉格朗日中值定理]]可得

\begin{aligned}
\int_B dv&=\int_{a_1}^{b_1}dt_1...\int_{a_{k-1}}^{b_{k-1}}dt_{k-1}\int_{a_{k+1}}^{b_{k+1}}dt_{k+1}...\int_{a_n}^{b_n}dt_n\int_{T_k(b_k,\vec{x}_k)}^{T_k(a_k,\vec{x}_k)}dt_k\\
&=\int_{a_1}^{b_1}dt_1...\int_{a_{k-1}}^{b_{k-1}}dt_{k-1}\int_{a_{k+1}}^{b_{k+1}}dt_{k+1}...\int_{a_n}^{b_n}[T_k(b_k,\vec{x}_k)-T_k(a_k,\vec{x}_k)]dt_n\\
&=\int_{A^k}[T_k(b_k,\vec{x}_k)-T_k(a_k,\vec{x}_k)]dv\\
&=[T_k(b_k,\vec{\xi})-T_k(a_k,\vec{\xi})]\int_{A^k}dv &\vec{\xi}\in A^k\\
&=\frac{[T_k(b_k,\vec{\xi}_k)-T_k(a_k,\vec{\xi}_k)]}{b_k-a_k}\Pi_{i=1}^n(b_i-a_i) &\vec{\xi}_k\in A^k\\
&=\frac{[T_k(b_k,\vec{\xi}_k)-T_k(a_k,\vec{\xi}_k)]}{b_k-a_k}V(A) &\vec{\xi}_k\in A^k\\
&=\frac{\partial T_k(\xi_k,\vec{\xi}_k)}{\partial x_k}V(A) &\vec{\xi}_k\in A^k,\xi_k\in[a_k,b_k]\\
&=\frac{\partial T_k(\vec{\xi})}{\partial x_k}V(A) &\vec{\xi}\in A\\
&=\det\left(\frac{\partial \vec{T}(\vec{\xi})}{\partial\vec{x}}\right)V(A) &\vec{\xi}\in A\\
\end{aligned}

若 $\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial \vec{x}}\right)=\frac{\partial T_k(\vec{x})}{\partial x_k}<0$ 则积分区域由小到大，故积分结果为负，与行列式符号抵消。

故得 $\left|\det\left(\frac{\partial \vec{T}(\vec{\xi})}{\partial\vec{x}}\right)\right|V(A)=V(T(A)),\vec{\xi}\in A$

*** <<MK19>>引理2：本源映射，结论成立，即 $\int_D f\left(\vec{T}(\vec{x})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial\vec{x}}\right)\right|dv=\int_{T(D)} f(\vec{t})dv$

**** 两个积分均可积

根据条件（3） $f(\vec{t})$ 连续，根据[[MK11][重积分推论]]可得 $\int_{T(D)} f(\vec{t})dv$ 可积

根据[[MK12][之前证明]] $\vec{T}(\vec{x})$ 连续，结合条件（3）得 $f\left(\vec{T}(\vec{x})\right)$ 连续，根据[[MK10][之前证明]] $\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial \vec{x}}\right)$ 连续且不变号，故得 $f\left(\vec{T}(\vec{x})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial\vec{x}}\right)\right|$ 连续

同样根据[[MK11][重积分推论]] $\int_D f\left(\vec{T}(\vec{x})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial\vec{x}}\right)\right|dv$ 可积

**** 定义特殊划分 $P^*$ ，并写出特殊划分下的黎曼和

故定义一种划分，将 $D$ 划分为小矩形 $D_i$ 并写出两个积分的黎曼和：

（1） $\int_D f\left(\vec{T}(\vec{x})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial\vec{x}}\right)\right|dv$ 的黎曼和为 $\sum_{i=1}^n  f\left(\vec{T}(\vec{\xi_i})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{\xi_i})}{\partial\vec{x}}\right)\right|V(D_i),\ \vec{\xi}_i\in D_i$

（2） $\int_{T(D)} f(\vec{t})dv$ 的黎曼和 $\sum_{i=1}^n f(\vec{\eta}_i)V(T(D_i)),\ \vec{\eta}_i\in T(D_i)$

**** 特殊划分取点 $(P^*,\xi)$ 下面积等式

根据[[MK13][引理1]]对于 $D_i\subset D$ 有 $\exists\xi_i\in D_i\Rightarrow \left|\det\left(\frac{\partial \vec{T}(\vec{\xi_i})}{\partial\vec{x}}\right)\right|V(D_i)=V(T(D_i))$ 则当 $\vec{\eta_i}=\vec{T}(\vec{\xi}_i)$ 由于映射一一对应，且 $\vec{\xi}_i\in D_i$ 故得 $\vec{T}(\vec{\xi}_i)\in T(D_i)$

则有 $\sum_{i=1}^n  f\left(\vec{T}(\vec{\xi_i})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{\xi_i})}{\partial\vec{x}}\right)\right|V(D_i)=\sum_{i=1}^n f\left(T(\vec{\xi}_i)\right)V(T(D_i))=\sum_{i=1}^n f(\vec{\eta}_i)V(T(D_i)),\ \vec{\xi}_i\in D_i$ 

**** 处理边界点

***** $D$ 与 $T(D)$ 边界点的对应关系

若 $D_i$ 中包含 $D$ 的边界点，则根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][构造Euclid空间-开集与闭集-点的定义-边界点]]的定义 $D_i$ 中包含不属于 $D$ 的点

由于当 $D_i$ 包含不属于 $D$ 的点时，映射未定义。故根据条件（1）补全映射，使得 $\vec{x}\in D_i\Rightarrow \vec{t}=\vec{T}(\vec{x})\in T(D_i)$ 

由于 $T(D)$ 为区域 $D$ 的映射，故有 $\vec{x}\in D\Rightarrow \vec{t}=\vec{T}(\vec{x})\in T(D)$ 且由条件（1） $\vec{x}_1=\vec{x}_2\Rightarrow \vec{T}(\vec{x})=\vec{T}(\vec{x})$ 得不存在一个 $\vec{x}$ 对应一个以上 $\vec{T}(\vec{x})$ 则有 $\vec{x}\in D_i\Rightarrow \vec{T}(\vec{x})\in T(D_i)$

同理 $\vec{x}\in D_i,\vec{x}\not\in D\Rightarrow \vec{T}(\vec{x})\in T(D_i),\vec{T}(\vec{x})\not\in T(D)$ 故有结论

（1） $D_i\subset D\Rightarrow T(D_i)\subset T(D)$

（2）<<MK14>> $D_i$ 包含 $D$ 的边界点，则 $T(D_i)$ 包含 $T(D)$ 的边界点 

综上所述当且仅当 $D_i$ 包含 $D$ 的边界点时 $T(D_i)$ 包含 $T(D)$ 的边界点

***** <<MK16>>边界点面积为零

当 $D_i$ 中包含不属于 $D$ 的点时有

（1） $V(D_i)$ 比区域的体积大

（2） 可能不存在 $\xi_i\in D_i$ 使得面积等式成立

由于根据可积定义，边界点的体积为零。故定义包含边界点的区域为 $D'_{i'}$ 不包含边界点的矩形为 $D''_{i''}$

则有 $\forall\epsilon>0,\exists\delta,\forall \lambda>\delta\Rightarrow\forall P:\sum_{i'=1}^{n'}V(D'_{i'})<\epsilon$

由于[[MK14][之前证明]] 当且仅当 $D_i$ 包含 $D$ 的边界点时 $T(D_i)$ 包含 $T(D)$ 的边界点

亦有 $\forall\epsilon>0,\exists\delta,\forall \lambda>\delta\Rightarrow\forall P:\sum_{i'=1}^{n'}V(T(D'_{i'}))<\epsilon$

**** 证明结论


根据条件（4）有 $D$ 为有界闭集，根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-Heine-Borel定理]] $D$ 紧集

根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][连续函数性质-紧集的连续映射（连续函数）也是紧集]]得 $T(D)$ 紧集，同理 $T(D)$ 有界闭集 

故 $f(\vec{t})$ 为有界闭集上的连续函数，根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][连续函数性质-最大值定理]]存在 $m'\leq f(\vec{t})\leq M',\vec{t}\in T(D)$ 同理存在 $m''\leq f\left(\vec{T}(\vec{x})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial\vec{x}}\right)\right|\leq M''$

定义 $M=\max(M',M''),m=\min(m',m'')$ ，定义包含边界点的区域为 $D'_{i'}$ 不包含边界点的矩形为 $D''_{i''}$ 

根据[[MK13][引理1]]，在 $(P^*,\xi)$ 下给定 $\vec{\eta_i}=\vec{T}(\vec{\xi}_i)$ 有 $f\left(\vec{T}(\vec{\xi_{i''}})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{\xi_{i''}})}{\partial\vec{x}}\right)\right|V(D_{i''})=f(\vec{\eta}_{i''})V(T(D_{i''}))$ 即重积分的[[MK4][保序性]]得

\begin{aligned}
&\left|\left\{\sum_{i=1}^n  f\left(\vec{T}(\vec{\xi_i})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{\xi_i})}{\partial\vec{x}}\right)\right|V(D_i)-
\sum_{i=1}^n f(\vec{\eta}_i)V(T(D_i))\right\}\right|\\
=&\left|\left\{
\sum_{i'=1}^{n'} f\left(\vec{T}(\vec{\xi_{i'}})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{\xi_{i'}})}{\partial\vec{x}}\right)\right|V(D_{i'})-
\sum_{i'=1}^{n'} f(\vec{\eta}_{i'})V(T(D_{i'}))+
\sum_{i''=1}^{n''} f\left(\vec{T}(\vec{\xi_{i''}})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{\xi_{i''}})}{\partial\vec{x}}\right)\right|V(D_{i''})-
\sum_{i''=1}^{n''} f(\vec{\eta}_{i''})V(T(D_{i''}))
\right\}\right|\\
=&
\left|\left\{
\sum_{i'=1}^{n'} f\left(\vec{T}(\vec{\xi_{i'}})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{\xi_{i'}})}{\partial\vec{x}}\right)\right|V(D_{i'})-
\sum_{i'=1}^{n'} f(\vec{\eta}_{i'})V(T(D_{i'}))
\right\}\right|\\
\leq&
\left|\left\{
\sum_{i'=1}^{n'} f\left(\vec{T}(\vec{\xi_{i'}})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{\xi_{i'}})}{\partial\vec{x}}\right)\right|V(D_{i'})
\right\}\right|+
\left|\left\{
\sum_{i'=1}^{n'} f(\vec{\eta}_{i'})V(T(D_{i'}))
\right\}\right|\\
\leq&\left|\sum_{i'=1}^{n'} MV(D_{i'})\right|+\left|\sum_{i'=1}^{n'} MV(T(D_{i'}))\right|\\
=&\left|M\sum_{i'=1}^{n'} V(D_{i'})\right|+\left|M\sum_{i'=1}^{n'} V(T(D_{i'}))\right|
\end{aligned}

根据[[MK16][边界点面积为零]]可得

（1） $\forall\epsilon>0,\exists\delta_1,\forall \lambda>\delta\Rightarrow\forall P:\sum_{i'=1}^{n'}V(D'_{i'})<\frac{\epsilon}{2M}$

（1） $\forall\epsilon>0,\exists\delta_2,\forall \lambda>\delta\Rightarrow\forall P:\sum_{i'=1}^{n'}V(T(D'_{i'}))<\frac{\epsilon}{2M}$

综上所述 

\begin{aligned}
&\forall\epsilon>0,\exists \delta=\min(\delta_1,\delta_2),\forall\lambda<\delta\\
&\Rightarrow\\
&\left|\left\{\sum_{i=1}^n  f\left(\vec{T}(\vec{\xi_i})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{\xi_i})}{\partial\vec{x}}\right)\right|V(D_i)-\sum_{i=1}^n f(\vec{\eta}_i)V(T(D_i))\right\}\right|\\
&\leq \left|M\sum_{i'=1}^{n'} V(D_{i'})\right|+\left|M\sum_{i'=1}^{n'} V(T(D_{i'}))\right|\\
&\right|<\epsilon
\end{aligned}

即特殊划分下 $\lim_{\lambda\to0}\left\{\sum_{i=1}^n  f\left(\vec{T}(\vec{\xi_i})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{\xi_i})}{\partial\vec{x}}\right)\right|V(D_i)-\sum_{i=1}^n f(\vec{\eta}_i)V(T(D_i))\right\}=0$

根据极限四则运算 $\lim_{\lambda\to0}\left\{\sum_{i=1}^n  f\left(\vec{T}(\vec{\xi_i})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{\xi_i})}{\partial\vec{x}}\right)\right|V(D_i)\right\}=\lim_{\lambda\to0}\left\{\sum_{i=1}^n f(\vec{\eta}_i)V(T(D_i))\right\}$


（1）  $\forall\epsilon>0,\exists\delta_1,\forall\lambda<\delta_1\Rightarrow\left|\left\{\sum_{i=1}^n  f\left(\vec{T}(\vec{\xi_i})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{\xi_i})}{\partial\vec{x}}\right)\right|V(D_i)-\int_D f\left(\vec{T}(\vec{x})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial\vec{x}}\right)\right|dv\right\}\right|<\frac{\epsilon}{2}$ 

（2）  $\forall\epsilon>0,\exists\delta_2,\forall\lambda<\delta_2\Rightarrow\left|\left\{\sum_{i=1}^n f(\vec{\eta}_i)V(T(D_i))-\int_{T(D)} f(\vec{t})dv\right\}\right|<\frac{\epsilon}{2}$

由于可积，故对于任意划分取点（包括 $(P^*,\xi)$ ）均有以下结论

（1）  $\lim_{\lambda\to0}\sum_{i=1}^n  f\left(\vec{T}(\vec{\xi_i})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{\xi_i})}{\partial\vec{x}}\right)\right|V(D_i)=\int_D f\left(\vec{T}(\vec{x})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial\vec{x}}\right)\right|dv$ 

（2）  $\lim_{\lambda\to0}\sum_{i=1}^n f(\vec{\eta}_i)V(T(D_i))=\int_{T(D)} f(\vec{t})dv$

故有本源映射下 $\int_D f\left(\vec{T}(\vec{x})\right)\left|\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial\vec{x}}\right)\right|dv=\int_{T(D)} f(\vec{t})dv$

*** <<MK17>>引理3：复合映射的雅克比行列式等于两个映射雅克比行列式乘积

定义 $\vec{F}(\vec{x}_0)=\vec{T}\left(\vec{G}(\vec{x}_0)\right)\in R^n, \vec{x}_0\in R^n$ 满足[[e:/OneDrive/数学分析/Note/Chapter 12/Chap12Note.org][多元复合函数求导-链式法则]]的两个条件，即

（1） 所有分量导数对两个函数均存在

（2） $\vec{T}(\vec{y}),\vec{y}\in R^n$ 在 $\vec{y}_0=\vec{G}(\vec{x}_0)$ 点处可微

则有 $\det\left(\frac{\partial\vec{F}(\vec{x}_0)}{\partial\vec{x}}\right)=\det\left(\frac{\partial\vec{T}(\vec{y}_0)}{\partial\vec{y}}\right)\det\left(\frac{\partial\vec{G}(\vec{x}_0)}{\partial\vec{x}}\right)$ 下面证明结论

对于行列式 $\frac{\partial\vec{F}(\vec{x}_0)}{\partial\vec{x}}=\{F_{ij}\}$ 中的某个元素 $F_{ij}=\frac{\partial F_j(\vec{x}_0)}{\partial x_i}=\frac{\partial T_j\left(\vec{G}(\vec{x}_0)\right)}{\partial x_i}$ 

由于满足链式法则条件，则有 $F_{ij}=\sum_{k=1}^n \frac{\partial T_j(\vec{y}_0)}{\partial y_k}\frac{\partial G_k(\vec{x}_0)}{\partial x_i}=\left[\begin{matrix}\frac{\partial T_j(\vec{y}_0)}{\partial y_1}&\frac{\partial T_j(\vec{y}_0)}{\partial y_2}&...&\frac{\partial T_j(\vec{y}_0)}{\partial y_n}\end{matrix}\right]\left[\begin{matrix}\frac{\partial G_1(\vec{x}_0)}{\partial x_i}\\\frac{\partial G_2(\vec{x}_0)}{\partial x_i}\\...\\\frac{\partial G_n(\vec{x}_0)}{\partial x_i}\end{matrix}\right]$

即 $\frac{\partial\vec{F}(\vec{x}_0)}{\partial\vec{x}}$ 中的第 $j$ 行 $i$ 列的元素为 $\frac{\partial\vec{T}(\vec{y}_0)}{\partial\vec{y}}$ 中第 $j$ 行与 $\frac{\partial\vec{G}(\vec{x}_0)}{\partial\vec{x}}$ 第 $i$ 列对应元素的乘积和，即为矩阵相乘的定义

则有 $\frac{\partial\vec{F}(\vec{x}_0)}{\partial\vec{x}}=\frac{\partial\vec{T}(\vec{y}_0)}{\partial\vec{y}}\frac{\partial\vec{G}(\vec{x}_0)}{\partial\vec{x}}$ 又因为乘积的行列式等于行列式的乘积，故有 $\det\left(\frac{\partial\vec{F}(\vec{x}_0)}{\partial\vec{x}}\right)=\det\left(\frac{\partial\vec{T}(\vec{y}_0)}{\partial\vec{y}}\right)\det\left(\frac{\partial\vec{G}(\vec{x}_0)}{\partial\vec{x}}\right)$

证毕。

*** <<MK18>>引理4：对于任意给定 $\vec{x}_0\in D$ 的某领域内 $O(\vec{x}_0,\delta)$ 映射 $\vec{T}(\vec{x})$ 可以表示为 $n$ 个本源映射的复合

**** 第一次迭代

***** 选取不为零的行列式

根据条件（2），则雅克比行列式第一行必有一个元素不为零，不妨设 $\frac{\partial T_1(\vec{x}_0)}{\partial x_1}\ne0$ 

***** 定义本源映射

\begin{aligned}
\vec{t}^1=\vec{T}^1(\vec{x})=\begin{cases}t^1_1=T_1(x_1,x_2,...,x_n)\\t^1_2=x_2\\...\\t^1_n=x_n\end{cases}
\end{aligned}

***** 列出逆映射条件

根据假设 $\frac{\partial T_1(\vec{x}_0)}{\partial x_1}\ne0$ 此时，映射满足以下条件

（1） $\vec{t}^1_0=\vec{T}^1(\vec{x}_0)$

（2） $\vec{T}^1(\vec{x})$ 在 $D$ 上有连续偏导且 $\vec{x}_0\in D$ ，则存在闭长方体 $G$ 使得 $\vec{x}_0\in G\in D$ ，故 $\vec{T}^1(\vec{x})$ 在 $G\in D$ 上也有连续偏导

（3） 函数 $\vec{T}^1(\vec{x})$ 在 $\vec{x}_0$ 点出的雅克比行列式不为零，即 $\det\left(\frac{\partial \vec{T}^1(\vec{x}_0)}{\partial \vec{x}}\right)=\left|\begin{matrix}\frac{\partial T_1(\vec{x}_0)}{\partial x_1}&\frac{\partial T_1(\vec{x}_0)}{\partial x_1}&...&\frac{\partial T_1(\vec{x}_0)}{\partial x_1}\\0&1&...&0\\...&...&...&...\\0&0&...&1\end{matrix}\right|=\frac{\partial T_1(\vec{x}_0)}{\partial x_1}\ne0$

***** 逆映射定理结论

故根据[[e:/OneDrive/数学分析/Note/Chapter 12/Chap12Note.org][隐函数-逆映射定理]]在 $O(\vec{t}^1_0,\rho_1)$ 内有

（1） 逆函数 $\vec{x}=\vec{F}^1(\vec{t}^1)=\begin{cases}x_1=F_{1_1}(t^1_1,t^1_2,...,t^1_n)\\x_2=t^1_2\\...\\x_n=t^1_n\end{cases}$

（2） 满足 $\vec{x}_0=\vec{F}^1(\vec{t}^1_0)$ 

（3） 逆映射函数有连续偏导（ $\frac{\parital \vec{F}^1(\vec{t}^1)}{\partial\vec{t}^1}=\left(\frac{\parital \vec{T}^1(\vec{x})}{\partial\vec{x}}\right)^{-1}$ ，由于 $\frac{\partial T^1_j(\vec{x})}{\partial x_i}$ 连续，矩阵求逆为初等运算，故 $\frac{\partial F^1_j(\vec{t}^1)}{\partial t^1_i}$ 也连续，故逆映射为连续函数。）

***** 下一次迭代准备

由于[[MK12][之前证明]] $\vec{t}^1=\vec{T}^1(\vec{x})$ 连续映射，故 $\lim_{\vec{x}\to\vec{x}_0}\vec{T}^1(\vec{x})=\vec{T}^1(\vec{x}_0)=\vec{t}^1_0$ 根据有 $\exists\delta_1,\forall\vec{x}\in O(\vec{x}_0,\delta_1)\Rightarrow |\vec{T}^1(\vec{x})-\vec{t}^1_0|<\rho_1$

故有当 $\vec{x}\in O(\vec{x}_0,\delta_1)$ 时 $\vec{t}^1=\vec{T}^1(\vec{x})\in O(\vec{t}^1_0,\rho_1)$ 逆映射成立 $x_1=F_{1_1}(\vec{t}^1)$

**** 第二次迭代

***** 选取不为零的行列式

由于条件（2）与前 $1$ 次迭代假设，则必有一行与第一行前两个元素组成的 $2\times2$ 行列式不为零

不妨假设第 $2$ 行，即 $\left|\begin{matrix}\frac{\partial T_1(\vec{x}_0)}{\partial x_1}&\frac{\partial T_1(\vec{x}_0)}{\partial x_2}\\\frac{\partial T_2(\vec{x}_0)}{\partial x_1}&\frac{\partial T_2(\vec{x}_0)}{\partial x_2}\end{matrix}\right|\ne0$

***** 定义本源映射

\begin{aligned}
\vec{t}^2=\vec{T}^2(\vec{t}^1)=\begin{cases}t^2_1=t^1_1\\t^2_2=T_2\left(F_1(\vec{t}^1),t^1_2,...,t^1_n\right)\\...\\t^2_n=t^1_n\end{cases}
\end{aligned}

***** 列出逆映射条件

（1） $\vec{t}^2_0=\vec{T}^2(\vec{t}^1_0)$

（2） 根据之前证明 $\vec{F}^1(\vec{t}^1)$ 为连续逆映射，有根据条件（1） $T_2(\vec{x})$ 为连续映射，故复合映射 $T_2\left(F_1(\vec{t}^1),t^1_2,...,t^1_n\right)$ 也连续

（3） 当 $\vec{x}\in O(\vec{x}_0,\delta_1)$ 时逆映射 $x_1=F_1(\vec{t}^1)$ 成立，故有复合映射 $\vec{t}^2=\vec{T}^2\left(\vec{T}^1(\vec{x})}\right)$  

故根据[[MK17][引理3可得]] $\det\left(\frac{\partial \vec{T}^1(\vec{x}_0)}{\partial \vec{x}}\right)\det\left(\frac{\partial \vec{T}^2(\vec{t}^1_0)}{\partial \vec{t}^1}\right)=\left|\begin{matrix}\frac{\partial T_1(\vec{x}_0)}{\partial x_1}&\frac{\partial T_1(\vec{x}_0)}{\partial x_2}&...&\frac{\partial T_1(\vec{x}_0)}{\partial x_n}\\\frac{\partial T_2(\vec{x}_0)}{\partial x_1}&\frac{\partial T_2(\vec{x}_0)}{\partial x_2}&...&\frac{\partial T_2(\vec{x}_0)}{\partial x_n}\\...&...&...&...\\0&0&...&1\end{matrix}\right|=\left|\begin{matrix}\frac{\partial T_1(\vec{x}_0)}{\partial x_1}&\frac{\partial T_1(\vec{x}_0)}{\partial x_2}\\\frac{\partial T_2(\vec{x}_0)}{\partial x_1}&\frac{\partial T_2(\vec{x}_0)}{\partial x_2}\end{matrix}\right|$

根据之前假设 $\left|\begin{matrix}\frac{\partial T_1(\vec{x}_0)}{\partial x_1}&\frac{\partial T_1(\vec{x}_0)}{\partial x_2}\\\frac{\partial T_2(\vec{x}_0)}{\partial x_1}&\frac{\partial T_2(\vec{x}_0)}{\partial x_2}\end{matrix}\right|\ne0$ 且 $\det\left(\frac{\partial \vec{T}^1(\vec{x}_0)}{\partial \vec{x}}\right)\ne0$ 故 $\det\left(\frac{\partial \vec{T}^2(\vec{t}^1_0)}{\partial \vec{t}^1}\right)\ne0$

***** 逆映射定理结论

同理根据[[e:/OneDrive/数学分析/Note/Chapter 12/Chap12Note.org][隐函数-逆映射定理]]在 $O(\vec{t}^2_0,\rho_2)$ 内

（1） 逆函数 $\vec{t}^1=\vec{F}^2(\vec{t}^2)=\begin{cases}t^1_1=t^2_1\\t^1_2=F_2(t^2_1,t^2_2,...,t^2_n)\\...\\t^2_n=t^1_n\end{cases}$

（2） 满足 $\vec{t}^1_0=\vec{F}^2(\vec{t}^2_0)$ 

（3） 逆映射函数有连续偏导

***** 下一次迭代准备

由于[[MK12][之前证明]] $\vec{t}^2=\vec{T}^1(\vec{x})$ 为连续映射，故复合映射 $\vec{t}^2=\vec{T}^2\left(\vec{T}^1(\vec{x})}\right)$ 亦连续，

同理根据连续定义有 $\exists\delta_2\leq \delta_1,\forall\vec{x}\in O(\vec{x}_0,\delta_2)\Rightarrow \left|\vec{t}^2-\vec{t}^2_0\right|<\rho_2$ ，则当 $\vec{x}\in O(\vec{x}_0,\delta_2)$ 时有

（1） $\vec{t}^2=\vec{T}^2\left(\vec{T}^1(\vec{x})\right)\in O(\vec{t}^2_0,\rho_2)$ 逆映射成立 $x_2=t^1_2=F_2(\vec{t}^2)$ 且为连续映射

（2） $x_1=F_1(\vec{t}^1)$ 成立，故有 $x_1=F_1(t^2_1,F_2(\vec{t}^2),...,t^2_n)=F_{1_2}(\vec{t}^2)$ 成立，且由于为连续映射的复合，亦为连续映射

**** 第三次迭代

***** 选取不为零的行列式

由于条件（2）与前 $2$ 次迭代假设，则必有一行与第一行前两个元素组成的 $3\times3$ 行列式不为零

不妨假设第 $3$ 行，即 $\left|\begin{matrix}\frac{\partial T_1(\vec{x}_0)}{\partial x_1}&\frac{\partial T_1(\vec{x}_0)}{\partial x_2}&\frac{\partial T_1(\vec{x}_0)}{\partial x_3}\\\frac{\partial T_2(\vec{x}_0)}{\partial x_1}&\frac{\partial T_2(\vec{x}_0)}{\partial x_2}&\frac{\partial T_2(\vec{x}_0)}{\partial x_3}\\\frac{\partial T_3(\vec{x}_0)}{\partial x_1}&\frac{\partial T_3(\vec{x}_0)}{\partial x_2}&\frac{\partial T_3(\vec{x}_0)}{\partial x_3}\\\end{matrix}\right|\ne0$

***** 定义本源映射

\begin{aligned}
\vec{t}^3=\vec{T}^3(\vec{t}^2)=\begin{cases}t^3_1=t^2_1\\t^3_2=t^2_2\\t^3_3=T_3\left(F_{1_2}(\vec{t}^2),F_2(\vec{t}_2),...,t^2_n\right)\\...\\t^3_n=t^2_n\end{cases}
\end{aligned}

***** 列出逆映射条件

（1） $\vec{t}^3_0=\vec{T}^3(\vec{t}^2_0)$

（2） 根据之前证明复合映射 $T_3\left(F_{1_2}(\vec{t}^2),F_2(\vec{t}_2),...,t^2_n\right)$ 连续

（3） 当 $\vec{x}\in O(\vec{x}_0,\delta_2)$ 时逆映射 $x_2=F_2(\vec{t}^2),x_1=F_{1_2}(\vec{t}^2)$ 成立，故有复合映射 $\vec{t}^3=\vec{T}^3\left(\vec{T}^2\left(\vec{T}^2(\vec{x})\right)\right)$

故根据[[MK17][引理3可得]] $\det\left(\frac{\partial \vec{T}^1(\vec{x}_0)}{\partial \vec{x}}\right)\det\left(\frac{\partial \vec{T}^2(\vec{t}^1_0)}{\partial \vec{t}^1}\right)\det\left(\frac{\partial \vec{T}^3(\vec{t}^2_0)}{\partial \vec{t}^2}\right)=\left|\begin{matrix}\frac{\partial T_1(\vec{x}_0)}{\partial x_1}&\frac{\partial T_1(\vec{x}_0)}{\partial x_2}&...&\frac{\partial T_1(\vec{x}_0)}{\partial x_n}\\\frac{\partial T_2(\vec{x}_0)}{\partial x_1}&\frac{\partial T_2(\vec{x}_0)}{\partial x_2}&...&\frac{\partial T_2(\vec{x}_0)}{\partial x_n}\\\frac{\partial T_3(\vec{x}_0)}{\partial x_1}&\frac{\partial T_3(\vec{x}_0)}{\partial x_2}&...&\frac{\partial T_3(\vec{x}_0)}{\partial x_n}\\...&...&...&...\\0&0&...&1\end{matrix}\right|=\left|\begin{matrix}\frac{\partial T_1(\vec{x}_0)}{\partial x_1}&\frac{\partial T_1(\vec{x}_0)}{\partial x_2}&\frac{\partial T_1(\vec{x}_0)}{\partial x_3}\\\frac{\partial T_2(\vec{x}_0)}{\partial x_1}&\frac{\partial T_2(\vec{x}_0)}{\partial x_2}&\frac{\partial T_2(\vec{x}_0)}{\partial x_3}\\\frac{\partial T_3(\vec{x}_0)}{\partial x_1}&\frac{\partial T_3(\vec{x}_0)}{\partial x_2}&\frac{\partial T_3(\vec{x}_0)}{\partial x_3}\\\end{matrix}\right|\ne0$

由于之前假设 $\det\left(\frac{\partial \vec{T}^1(\vec{x}_0)}{\partial \vec{x}}\right)\det\left(\frac{\partial \vec{T}^2(\vec{t}^1_0)}{\partial \vec{t}^1}\right)\ne0\Rightarrow\det\left(\frac{\partial \vec{T}^3(\vec{t}^2_0)}{\partial \vec{t}^2}\right)\ne0$

***** 逆映射定义结论

同理根据[[e:/OneDrive/数学分析/Note/Chapter 12/Chap12Note.org][隐函数-逆映射定理]]在 $O(\vec{t}^3_0,\rho_3)$ 内

（1） 逆函数 $\vec{t}^2=\vec{F}^3(\vec{t}^3)=\begin{cases}t^2_1=t^3_1\\t^2_2=t^3_2\\t^2_3=F_3(t^3_1,t^3_2,...,t^3_n)\\...\\t^2_n=t^3_n\end{cases}$

（2） 满足 $\vec{t}^2_0=\vec{F}^3(\vec{t}^3_0)$ 

（3） 逆映射函数有连续偏导

***** 下次迭代准备

由于 $\vec{T}^1(\vec{x}),\vec{T}^2(\vec{t}^2),\vec{T}^3(\vec{t}^2)$ 均为连续映射，故 $\vec{t}^3=\vec{T}^3\left(\vec{T}^2\left(\vec{T}^2(\vec{x})\right)\right)$ 连续

同理根据连续定义有 $\exists\delta_3\leq \delta_2,\forall\vec{x}\in O(\vec{x}_0,\delta_3)\Rightarrow \left|\vec{t}^3-\vec{t}^3_0\right|<\rho_3$ ，则当 $\vec{x}\in O(\vec{x}_0,\delta_3)$ 时有

（1） $\vec{t}^3=\vec{T}^3\left(\vec{T}^2\left(\vec{T}^2(\vec{x})\right)\right)\in O(\vec{t}^3_0,\rho_3)$ 故逆映射成立 $x_3=t^1_3=t^2_3=F_3(\vec{t}^3)$

（2） $x_2=F_2(\vec{t}^2)$ 成立，故 $x_2=F_2(t^3_1,t^3_2,F_3(\vec{t}^3),...,t^3_n)=F_{2_3}(\vec{t}^3)$ 成立

（3） $x_1=F_{1_2}(\vec{t}^2)$ 成立，同理 $x_1=F_{1_3}(\vec{t}^3)$ 成立

**** 第 $n$ 次迭代

***** 定义本源映射

\begin{aligned}
\vec{t}^n=\vec{T}^n(\vec{t}^{n-1})=\begin{cases}t^n_1=t^{n-1}_1\\t^n_2=t^{n-1}_2\\...\\t^n_{n-1}=t^{n-1}_{n-1}\\t^n_n=
T_n\left(F_{1_{n-1}}(\vec{t}^{n-1}),F_{2_{n-1}}(\vec{t}^{n-1}),...,F_{(n-1)_{n-1}}(\vec{t}^{n-1}),t^{n-1}_n\right)
\end{cases}
\end{aligned}

***** 雅克比行列式不为零

根据条件（2） $\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial \vec{x}}\right)\ne0$ 且根据之前映射规则 $\det\left(\frac{\partial \vec{T}(\vec{x})}{\partial \vec{x}}\right)=\Pi_{i=1}^n \det\left(\frac{\partial \vec{T}^i(\vec{t}^{i-1}_0)}{\partial \vec{t}^{i-1}}\right)$ 

且对于 $i=1,2,...,n-1$ 来说 $\det\left(\frac{\partial \vec{T}^i(\vec{t}^{i-1}_0)}{\partial \vec{t}^{i-1}}\right)\ne0$ 故 $\det\left(\frac{\partial \vec{T}^n(\vec{t}^{n-1}_0)}{\partial \vec{t}^{n-1}}\right)\ne0$

**** 证明结论

定义复合映射 $\vec{t}^n=\vec{T}^n\circ\vec{T}^{n-1}\circ...\circ\vec{T}^1(\vec{x})$ 定义 $\vec{t}^0=\vec{x}$ 

根据之前推导，存在 $\delta_{n-1}>0$ 使得当 $\vec{x}\in O(\vec{x}_0,\delta_{n-1})$ 时之前所列逆映射均成立，故有 

（1） $x_i=F_{i_j}(\vec{t}^j),j\geq i$

（2） $x_i=t^j_i,j<i$

根据映射定义 $t^n_i=t^{n-1}_i=...=t^i_i=T_i\left(\vec{F}_{1_i}(\vec{t}^{i-1}),\vec{F}_{2_i}(\vec{t}^{i-1}),...,\vec{F}_{(i-1)_i}(\vec{t}^{i-1}),t^{i-1}_i,t^{i-1}_{i+1},...,t^{i-1}_n\right)$

故得 $t^n_i=T_i(\vec{x})$ 故 $\vec{t}=\vec{T}(\vec{x})$ 在 $O(\vec{x}_0,\delta_{n-1})$ 上可分解 $n$ 个本源映射

*** 重积分变量代换证明

**** 定义有限开覆盖及划分

定义 $D$ 的无限开覆盖 $\left\{U\big|O\left(\vec{x},\frac{\delta}{2}\right),\vec{x}\in D\right\}$ 其中 $\delta$ 是根据[[MK18][引理4]]导出的在 $\vec{x}$ 点周围可将映射分解为 $n$ 个本源映射的领域半径

根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-Heine-Borel定理]] $D$ 为紧集，

根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-Heine-Borel定理-前提定义-紧集]]给出的定义，任意无限开覆盖必有有限子覆盖。

故定义有限子覆盖 $\cup_{i=1}^s O\left(\vec{x}_i,\frac{\delta_i}{2}\right)$ ，进一步定义 $\delta^*=\min(\delta_i)$

将 $D$ 用光滑曲面划分为 $D_i$ 使得直径 $\phi(D_i)<\frac{\delta^*}{2}$ 故若 $D_i$ 与 $O\left(\vec{x}_j,\frac{\delta_j}{2}\right)$ 相交，则必有 $D_i\subset O(\vec{x}_j,\delta_j)$ 

由于 $D$ 与 $T(D)$ 一一映射，故有对应的 $s$ 个 $T(D_i)$ 区域与 $D_i$ 对应

**** 整理行列式

定义 $G_i(\vec{t}^{i-1})=\det\left(\frac{\partial \vec{T}^i(\vec{t}^{i-1})}{\partial \vec{t}^{i-1}}\right)$ 为偏导函数经行列式计算得的关于自变量 $\vec{t}^{i-1}$ 的函数，根据之前证明，在定义域内的点处可微。

故若有复合映射 $\vec{T}(\vec{t}^{i-2})=\vec{T}^i\left(\vec{T}^{i-1}(\vec{t}^{i-2})\right)$ 其中 $\vec{t}^{i-1}=\vec{T}^{i-1}(\vec{t}^{i-2})$ 则根据[[MK17][引理3]]有 $G_i\left(\vec{T}^{i-1}(\vec{t}^{i-2})\right)G_{i-1}(\vec{t}^{i-2})=\det\left(\frac{\partial\vec{T}(\vec{t}^{i-2})}{\partial\vec{t}^{i-2}}\right)$

由于 $\vec{T}(\vec{x})=\vec{T}^n\circ\vec{T}^{n-1}\circ...\circ\vec{T}^1(\vec{x})$ 则根据[[MK18][引理4]]中的复合映射规则 $\Pi_{i=1}^n G_i\left(\vec{T}^{i-1}\circ\vec{T}^{i-2}\circ...\circ\vec{T}^1(\vec{x})\right)=\det\left(\frac{\partial\vec{T}(\vec{x})}{\partial\vec{x}}\right)$

**** 定义划分下 $D_i$ 的重积分

则根据[[MK19][引理2]]有如下推导

\begin{aligned}
\int_{T(D_i)} f(\vec{t})dv&=\int_{T^n\cdot T^{n-1}\cdot...\cdot T^1(D_i)} f(\vec{t}^n)dv\\
&=\int_{T^n\cdot T^{n-1}\cdot...\cdot T^1(D_i)} f(\vec{T}^n(\vec{t}^{n-1}))dv\\
&=\int_{T^{n-1}\cdot...\cdot T^1(D_i)} f\left(\vec{T}^n(\vec{t}^{n-1})\right)\left|\det\left(\frac{\partial \vec{T}^n(\vec{t}^{n-1})}{\partial \vec{t}^{n-1}}\right)\right|dv\\
&=\int_{T^{n-1}\cdot...\cdot T^1(D_i)} f\left(\vec{T}^n(\vec{t}^{n-1})\right)\left|G_n(\vec{t}^{n-1})\right|dv\\
&=\int_{T^{n-1}\cdot...\cdot T^1(D_i)} f\left(\vec{T}^n\circ\vec{T}^{n-1}(\vec{t}^{n-2})\right)\left|G_n\left(\vec{T}^{n-1}(\vec{t}^{n-2})\right)\right|dv\\
&=\int_{T^{n-2}\cdot...\cdot T^1(D_i)} f\left(\vec{T}^n\circ\vec{T}^{n-1}(\vec{t}^{n-2})\right)
\left|G_n\left(\vec{T}^{n-1}(\vec{t}^{n-2})\right)\right|\left|G_{n-1}(\vec{t}^{n-2})\right|dv\\
&=...\\
&=\int_{D_i}f\left(\vec{T}^n\circ\vec{T}^{n-1}\circ...\circ\vec{T}^1(\vec{x})\right)\Pi_{i=1}^n \left|G_i\left(\vec{T}^{i-1}\circ\vec{T}^{i-2}\circ...\circ\vec{T}^1(\vec{x})\right)\right|dv\\
&=\int_{D_i}f\left(\vec{T}(\vec{x})\right)\left|\Pi_{i=1}^n G_i\left(\vec{T}^{i-1}\circ\vec{T}^{i-2}\circ...\circ\vec{T}^1(\vec{x})\right)\right|dv\\
&=\int_{D_i}f\left(\vec{T}(\vec{x})\right)\left|\det\left(\frac{\partial\vec{T}(\vec{x})}{\partial\vec{x}}\right)\right|dv\\
\end{aligned}

**** 结论

根据重积分[[MK6][区域可加性]]有

\begin{aligned}
\int_{T(D)} f(\vec{t})dv&=\sum_{i=1}^s\int_{T(D_i)} f(\vec{t})dv\\
&=\sum_{i=1}^s \int_{D_i}f\left(\vec{T}(\vec{x})\right)\left|\det\left(\frac{\partial\vec{T}(\vec{x})}{\partial\vec{x}}\right)\right|dv\\
&=\int_{D}f\left(\vec{T}(\vec{x})\right)\left|\det\left(\frac{\partial\vec{T}(\vec{x})}{\partial\vec{x}}\right)\right|dv\\
\end{aligned}

结论证毕。

** 常见变量代还

*** 二维坐标

**** 极坐标

被积函数 $\iint_D f(x,y)dxdy$ 变量代还 $\begin{cases}x=r\cos(\theta)\\y=r\sin(\theta)\end{cases}$ 其中：

（1） $r$ 为向量 $(x,y)$ 的长度即 $\sqrt{x^2+y^2}$

（2） $\theta$ 为向量 $(x,y)$ 与 $x$ 轴的夹角

***** 变换后取值范围

$\left\{T(D)\big| r\in(0,\infty),\theta\in(0,2\pi)\right\}$

***** 雅克比行列式

\begin{aligned}
\frac{\partial (x,y)}{\partial (r,\theta)}&=\left|\begin{matrix}\cos(\theta)&-r\sin(\theta)\\\sin(\theta)&r\cos(\theta)\end{matrix}\right|\\
&=r\cos^2(\theta)+r\sin^2(\theta)\\
&=r
\end{aligned}

*** 三维坐标

**** 柱面坐标

被积函数 $\iiint_D f(x,y,z)dxdydz$ 变量代还 $\begin{cases}x=r\cos(\theta)\\y=r\sin(\theta)\\z=z\end{cases}$ 其中：

（1） $r$ 为向量 $(x,y)$ 的长度即 $\sqrt{x^2+y^2}$

（2） $\theta$ 为向量 $(x,y)$ 与 $x$ 轴的夹角

***** 变换后取值范围

$\left\{T(D)\big| r\in(0,\infty),z\in(-\infty,+\infty),\theta\in(0,2\pi)\right\}$

***** 雅克比行列式

\begin{aligned}
\frac{\partial (x,y,z)}{\partial (r,\theta,z)}&=\left|\begin{matrix}\cos(\theta)&-r\sin(\theta)&0\\\sin(\theta)&r\cos(\theta)&0\\0&0&1\end{matrix}\right|\\
&=\left|\begin{matrix}\cos(\theta)&-r\sin(\theta)\\\sin(\theta)&r\cos(\theta)\end{matrix}\right|\\
&=r\cos^2(\theta)+r\sin^2(\theta)\\
&=r
\end{aligned}

**** <<MK24>>球面坐标变换

被积函数 $\iiint_D f(x,y,z)dxdydz$ 变量代还 $\begin{cases}x=r\sin(\phi)\cos(\theta)\\y=r\sin(\phi)\sin(\theta)\\z=r\cos(\phi)\end{cases}$ 其中：

（1） $r$ 为向量 $(x,y,z)$ 的长度，即 $\sqrt{x^2+y^2+z^2}$

（2） $\theta$ 为向量 $(x,y)$ 与 $x$ 轴的夹角

（3） $\phi$ 为向量 $(x,y,z)$ 与 $z$ 轴的夹角

***** 变换后取值范围

$\left\{T(D)\big| r\in(0,\infty),\phi\in(0,\pi),\theta\in(0,2\pi)\right\}$

***** 雅克比行列式

\begin{aligned}
\frac{\partial (x,y,z)}{\partial (r,\phi,\theta)}&=\left|\begin{matrix}\sin(\phi)\cos(\theta)&r\cos(\phi)\cos(\theta)&-r\sin(\phi)\sin(\theta)\\
\sin(\phi)\sin(\theta)&r\cos(\phi)\sin(\theta)&r\sin(\phi)\cos(\theta)\\\cos(\phi)&-r\sin(\phi)&0\end{matrix}\right|\\
&=cos(\phi)\left|\begin{matrix}r\cos(\phi)\cos(\theta)&-r\sin(\phi)\sin(\theta)\\r\cos(\phi)\sin(\theta)&r\sin(\phi)\cos(\theta)\end{matrix}\right|
+r\sin(\phi)\left|\begin{matrix}\sin(\phi)\cos(\theta)&-r\sin(\phi)\sin(\theta)\\\sin(\phi)\sin(\theta)&r\sin(\phi)\cos(\theta)\end{matrix}\right|\\
&=cos(\phi)r^2\cos(\phi)\sin(\phi) +r\sin(\phi)r\sin^2(\phi)\\
&=r^2\sin(\phi)\left(cos^2(\phi)+\sin^2(\phi)\right)\\
&=r^2\sin(\phi)
\end{aligned}

*** <<MK34>> $n$ 维坐标球面变换

被积函数 $\int_D f(\vec{x})\Pi_{i=1}^n dx_i$ 变量代还 $\begin{cases}x_i=r\cos(\phi_i)\Pi_{j=1}^{i-1}\sin(\phi_j) & 1\leq i\leq n-1\\x_n=r\Pi_{j=1}^{n-1}\sin(\phi_j)\end{cases}$ 其中：

（1） $r$ 为球半径

（2） $\phi_i$ 为 $(x_1,x_2,...x_{i+1})$ 与第 $i+2$ 条（不属于点 $(x_1,x_2,...x_{i+1})$ 在的 $R^{i+1}$ 空间的）坐标轴

**** 变换后取值范围

$\left\{T(D)\big| r\in(0,\infty),\phi_1\in(0,\pi),\phi_2\in(0,\pi),...,\phi_{n-1}\in(0,\pi),\phi_n\in(0,2\pi)\right\}$

**** 雅克比行列式

值为 $\det(J)=r^{n-1}\Pi_{i=1}^{n-2}\sin^{n-i-1}(\phi_i)$

** 均匀球体引力场

均匀球体 $D$ 半径为 $a$ 密度为 $\rho$ ，对某一不为球心的单位质点（质量为 $1$ ）形成的引力场

*** 建立坐标系

建立坐标系，以质点与球心连线为 $y$ 轴，球心为原点。

单位质点为 $\vec{P}_0=(0,0,s)$

*** 微元法引理场大小

求内某点 $\vec{P}$ 包含在体积微元 $dv$ 中，引力大小公式 $F=G\frac{M_1M_2}{r^2}$ 

由于 $\vec{P}_0$ 单位质点，则有 $F=G\frac{M_1}{r^2}$ 且 $r^2$ 为 $\vec{P},\vec{P}_0$ 两点距离，则有 $F=G\frac{M_1}{x^2+y^2+(z-s)^2}$

再根据微元法带入质量得 $dF=G\frac{\rho}{x^2+y^2+(z-s)^2}dv$

*** 微元法引力场方向

根据坐标，方向为 $(x,y,z-s)$ 调整长度为单位向量，故得 $\vec{e}=\frac{1}{\sqrt{x^2+y^2+(z-s)^2}}(x,y,z-s)$

由于 $\vec{P}_0$ 点关于 $x,y$ 轴对称，故引理抵消，方向由 $z$ 轴方向向下

$z$ 轴方向大小为 $\frac{z-s}{\sqrt{x^2+y^2+(z-s)^2}}dF=G\rho\frac{z-s}{(x^2+y^2+(z-s)^2)^{\frac{3}{2}}}dv$

*** 列出积分

\begin{aligned}
F&=\int_D G\rho\frac{z-s}{(x^2+y^2+(z-s)^2)^{\frac{3}{2}}}dv\\
&=G\rho \int_D \frac{z-s}{(x^2+y^2+(z-s)^2)^{\frac{3}{2}}}dxdydz
\end{aligned}

*** 重积分变量代还

运用[[MK24][球面坐标变换]]  $\begin{cases}x=r\sin(\phi)\cos(\theta)\\y=r\sin(\phi)\sin(\theta)\\z=r\cos(\phi)\end{cases}$ 其中 $\left\{T(D)\big| r\in(0,a),\phi\in(0,\pi),\theta\in(0,2\pi)\right\}$

带入积分式

\begin{aligned}
F&=G\rho \int_D \frac{z-s}{(x^2+y^2+(z-s)^2)^{\frac{3}{2}}}dxdydx\\
&=G\rho \int_{D} \frac{z-s}{(x^2+y^2+z^2-2zs+s^2)^{\frac{3}{2}}}dxdydx\\
&=G\rho \int_{T(D)} \frac{r\cos(\phi)-s}{(r^2-2r\cos(\phi)s+s^2)^{\frac{3}{2}}}r^2\sin(\phi)drd\phid\theta\\
&=G\rho\int_0^{2\pi}d\theta\int_0^a dr\int_0^\pi \frac{r\cos(\phi)-s}{(r^2-2rs\cos(\phi)+s^2)^{\frac{3}{2}}} r^2\sin(\phi)d\phi\\
\end{aligned}

*** 定积分换元

定义 $\xi^2=r^2-2rs\cos(\phi)+s^2$ 两边求导 $2\xi \frac{d\xi}{d\phi}=2rs\sin(\phi)\Rightarrow \frac{\xi}{rs}d\xi=\sin(\phi)d\phi$

另有 $2rs\cos(\phi)=r^2+s^2-\xi^2\Rightarrow r\cos(\phi)-s=\frac{r^2+s^2-\xi^2}{2s}-s=\frac{r^2-s^2-\xi^2}{2s}$

积分区间由于 $-2rs\cos(\phi)$ 对于 $\phi$ 单调递增，故 $(r-s)^2=r^2-2rs\cos(0)+s^2\leq\xi^2\leq r^2-2rs\cos(\pi)+s^2=(r+s)^2$

根据定义 $r>0,s>0$ 故有 $|r-s|\leq r\leq r+s$

故有：

\begin{aligned}
F&=G\rho\int_0^{2\pi}d\theta\int_0^a dr\int_0^\pi \frac{r\cos(\phi)-s}{(r^2-2rs\cos(\phi)+s^2)^{\frac{3}{2}}} r^2\sin(\phi)d\phi\\
&=G\rho\int_0^{2\pi}d\theta\int_0^a r^2 dr\int_{|r-s|}^{r+s} \frac{\frac{r^2-s^2-\xi^2}{2s}}{\xi^3} \frac{\xi}{rs}d\xi\\
&=G\rho\int_0^{2\pi}d\theta\int_0^a r^2 \frac{1}{2rs^2} dr\int_{|r-s|}^{r+s} \frac{r^2-s^2}{\xi^2}-1 d\xi\\
\end{aligned}

*** 计算 $\int_{|r-s|}^{r+s} \frac{r^2-s^2}{\xi^2}-1 d\xi$

化简原始

\begin{aligned}
&\int_{|r-s|}^{r+s} \frac{r^2-s^2}{\xi^2}-1 d\xi\\
=&\int_{|r-s|}^{r+s} \frac{r^2-s^2}{\xi^2}d\xi -\int_{|r-s|}^{r+s}d\xi\\
=&(r^2-s^2)\left\{-\frac{1}{\xi}\bigg|^{r+s}_{|r-x|}\right\}-\left\{r+s-|r-s|\right\}\\
=&(r-s)(r+s)\left\{-\frac{1}{r+s}+\frac{1}{|r-s|}\right\}-(r+s)+|r-s|\\
=&-(r-s)+\frac{(r-s)(r+s)}{|r-s|}-(r+s)+|r-s|\\
=&-2r+\frac{(r-s)(r+s)}{|r-s|}+|r-s|\\
\end{aligned}

当 $r>s$ 时

\begin{aligned}
&\int_{|r-s|}^{r+s} \frac{r^2-s^2}{\xi^2}-1 d\xi\\
=&-2r+\frac{(r-s)(r+s)}{|r-s|}+|r-s|\\
=&-2r+\frac{(r-s)(r+s)}{r-s}+r-s\\
=&0
\end{aligned}

当 $r<s$ 时

\begin{aligned}
&\int_{|r-s|}^{r+s} \frac{r^2-s^2}{\xi^2}-1 d\xi\\
=&-2r+\frac{(r-s)(r+s)}{|r-s|}+|r-s|\\
=&-2r-\frac{(r-s)(r+s)}{r-s}-r+s\\
=&-2r-(r+s)-r+s\\
=&-4r
\end{aligned}

*** 计算累次积分

当 $a<s$ 时

\begin{aligned}
F&=G\rho\int_0^{2\pi}d\theta\int_0^a r^2 \frac{1}{2rs^2} dr\int_{|r-s|}^{r+s} \frac{r^2-s^2}{\xi^2}-1 d\xi\\
&=G\rho\int_0^{2\pi}d\theta\int_0^a r^2 \frac{1}{2rs^2}(-4r) dr\\
&=\frac{-2}{s^2}G\rho\int_0^{2\pi}d\theta\int_0^ar^2 dr\\
&=\frac{-2}{s^2}G\rho2\pi\frac{1}{3}a^3\\
&=-G\frac{\frac{4}{3}a^3\rho}{s^2}\\
\end{aligned}

当 $a>s$ 时

\begin{aligned}
F&=G\rho\int_0^{2\pi}d\theta\int_0^a r^2 \frac{1}{2rs^2} dr\int_{|r-s|}^{r+s} \frac{r^2-s^2}{\xi^2}-1 d\xi\\
&=G\rho\int_0^{2\pi}d\theta\left\{\int_0^s r^2 \frac{1}{2rs^2}\int_{|r-s|}^{r+s} \frac{r^2-s^2}{\xi^2}-1 d\xi+\int_s^a r^2 \frac{1}{2rs^2}\int_{|r-s|}^{r+s} \frac{r^2-s^2}{\xi^2}-1 d\xi\right\}\\
&=G\rho\int_0^{2\pi}d\theta\int_0^s r^2 \frac{1}{2rs^2}\int_{|r-s|}^{r+s} \frac{r^2-s^2}{\xi^2}-1 d\xi\\
&=-G\frac{\frac{4}{3}s^3\rho}{s^2}\\
\end{aligned}

* 反常重积分

** 积分极限等价定理（ARZELA'S DOMINATED CONVERGENCE THEOREM）

定义 $\{f_n(x)\}$ 为在 $x\in[a,b]$ 上有定义的函数项级数，若

（1） $\forall n\in N^+$ 定积分 $\int_a^b f_n(x)dx$ 可积

（2） $\forall x\in[a,b]$ 有 $\lim_{n\to\infty}f_n(x)=f(x)$

（3） $\forall x\in[a,b],\forall n\in N^+\Rightarrow |f_n(x)|\leq M$ 其中 $M$ 为有界正实数

（4） 定积分 $\int_a^b f(x)dx$ 可积

则结论为 $\lim_{n\to\infty}\left\{\int_a^b |f_n(x)-f(x)|dx\right\}=0$

*** 证明

**** <<MK25>>引理1：

若函数 $f(x)$ ：

（1） 在定义域 $[a,b]$ 上有定义且可积；

（2） $0\leq f(x)\leq M,x\in[a,b]$ （ $\leq M$ 可能不需要）

则存在连续函数 $g(x)$ 满足：

（1） $0\leq g(x)\leq f(x),x\in[a,b]$

（2） $\int_a^b f(x)dx\leq\int_a^bg(x)dx+\epsilon$

***** 证明

****** 转化条件到达布小和

定义 $[a,b]$ 上函数 $f(x)$ 的达布小和： $\lim_{\lambda\to0}\sum_{i=1}^n f(m_i)\Delta x_i=\underline{\int_a^b}f(x)dx$ 

其中 $\Delta x_i=x_i-x_{i-1},\lambda=\max(\Delta x_i),m_i=inf\left\{f(x)\big|x\in[x_{i-1},x_i]\right\}$

则根据极限定义有 $\forall\epsilon>0,\exists\delta,\forall\lambda<\delta,\forall P\Rightarrow \left|\sum_{i=1}^n f(m_i)\Delta x_i-\underline{\int_a^b}f(x)dx\right|<\frac{\epsilon}{4}$ 其中 $P$ 表划分

由于 $f(x)>0,x\in[a,b]$ 且根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定理1]]得 $\sum_{i=1}^n f(m_i)\Delta x_i\leq\underline{\int_a^b}f(x)dx\right$

故极限定义可写成 $\forall\epsilon>0,\exists\delta,\forall\lambda<\delta,\forall P\Rightarrow \underline{\int_a^b}f(x)dx-\sum_{i=1}^n f(m_i)\Delta x_i<\frac{\epsilon}{4}$

****** 构建满足条件的单步函数

对于给定 $\epsilon$ ，取任意一个满足 $\underline{\int_a^b}f(x)dx-\sum_{i=1}^n f(m_i)\Delta x_i<\frac{\epsilon}{4}$ 的划分 $P$ 与取点 $a=x_1<x_1<...<x_n=b$

接下来定义一个单步函数 $s(x)=\max\left(f(m_i)-\frac{\epsilon}{4(b-a)},0\right),x\in[x_{i-1},x_i]$

由于 $0\leq s(x) \leq f(m_i)\leq f(x),x\in[x_{i-1},x_i]$ 故有 $f(x)\geq s(x)$

则根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-区间可加]]，在某一给定划分满足条件的划分 $P: a=x_0<x_1<x_2<...<x_{n-1}<x_n=b,\lambda<\delta$ 成立 

\begin{aligned}
\int_a^b s(x)dx&=\sum_{i=1}^n \int_{x_{i-1}}^{x_i}s(x)dx\\
&=\sum_{i=1}^n \max\left(f(m_i)-\frac{\epsilon}{4(b-a)},0\right)\int_{x_{i-1}}^{x_i}dx\\
&=\sum_{i=1}^n \max\left(f(m_i)-\frac{\epsilon}{4(b-a)},0\right)\Delta x_i\\
\end{aligned}

进一步推导 

\begin{aligned}
&\sum_{i=1}^n f(m_i)\Delta x_i-\int_a^b s(x)dx\\
=&\sum_{i=1}^n f(m_i)\Delta x_i - \sum_{i=1}^n \max\left(f(m_i)-\frac{\epsilon}{4(b-a)},0\right)\Delta x_i\\
\leq&\sum_{i=1}^n\frac{\epsilon}{4(b-a)}\Delta x_i\\
=&\frac{\epsilon}{4(b-a)}\sum_{i=1}^n\Delta x_i\\
=&\frac{\epsilon}{4}\\
\end{aligned}

故有：

（1） $f(x)>s(x)$

（2） $\underline{\int_a^b}f(x)dx-\sum_{i=1}^n f(m_i)\Delta x_i<\frac{\epsilon}{4}\Rightarrow \underline{\int_a^b}f(x)dx<\sum_{i=1}^n f(m_i)\Delta x_i+\frac{\epsilon}{4}\leq\int_a^b s(x)dx+\frac{\epsilon}{2}$

故得到满足条件的单步不连续函数

****** 基于单步函数作 $g(x)$

在 $s(x)$ 的基础上以直线连接不连续点，做连续的梯形函数 $g(x)$ 使得

（1） $g(x)\leq s(x)$

（2） $0\leq\underline{\int_a^b}s(x)dx<\int_a^b g(x)dx+\frac{\epsilon}{2}$

故根据 $s(x)$ 性质可推导：

（1） $g(x)\leq s(x)\leq f(x)$

（2） $\underline{\int_a^b}f(x)dx<\int_a^b s(x)dx+\frac{\epsilon}{2}<\int_a^b g(x)dx+\epsilon$

又因为 $f(x)$ 在 $[a,b]$ 上可积，根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分可积定理-定积分可积充要条件1]] $\underline{\int_a^b}f(x)dx=\int_a^bf(x)dx$

故证毕。

**** <<MK26>>引理2：

定义 $\{f_n(x)\}$ 为在 $x\in[a,b]$ 上有定义的函数项级数，若

（1） $f_n(x)\geq f_{n+1}(x)$ 即对于固定的 $x\in[a,b]$ 函数项级数单调递减

（2） $\forall n\in N^+$ 定积分 $\int_a^b f_n(x)dx$ 可积

（3） $\forall x\in[a,b]$ 有 $\lim_{n\to\infty}f_n(x)=0$

（4） $\forall x\in[a,b],\forall n\in N^+\Rightarrow f_n(x)\geq0$

则有 $\lim_{n\to\infty}\int_a^b f_n(x)=0$

***** 证明

****** 使用[[MK25][引理1]]做连续函数 $g(x)$

由于单调递减且 $f_0(x),x\in[a,b]$ 有定义，即 $f_0(x)<\infty$ 故 $\froall x\in[a,b],\forall n\in N^+\Rightarrow f_n(x)\leq f_0(x)<\infty$

故为有界函数项级数，且 $\forall n\in N^+$ 定积分 $\int_a^b f_n(x)dx$ 可积

则根据[[MK25][引理1]]有 $\forall\epsilon>0,\forall n\in N^+,\exists g_n(x)>0\Rightarrow g_n(x)\leq f_n(x),\int_a^b f_n(x)<g_n(x)+\frac{\epsilon}{2^n}$ 其中 $g_n(x)$ 为连续梯形函数

****** 使用[[e:/OneDrive/数学分析/Note/Chapter 10/Chap10Note.org][函数项级数-一致收敛性质-Dini定理]]

定义 $h_n(x)=\min(g_1(x),g_2(x),...,g_n(x))$ 由于 $h_n(x)$ 满足：

（1） $0\leq h_n(x)\leq g_n(x)\leq f_n(x), \lim_{n\to\infty}f_n(x)=0,x\in[a,b]$ 故根据夹逼定理 $\lim_{n\to\infty}h_n(x)=0,x\in[a,b]$

（2） $h_n(x)$ 根据定义在 $x\in[a,b]$ 上连续，$h(x)=\lim_{n\to\infgy}h_n(x)=0,x\in[a,b]$ 故 $h(x)$ 在 $x\in[a,b]$ 上也连续

（3） 对于固定 $x\in[a,b]$ ，有 $h_n(x)$ 单调递减

故根据[[e:/OneDrive/数学分析/Note/Chapter 10/Chap10Note.org][函数项级数-一致收敛性质-Dini定理]]函数 $h_n(x)$ 在定义域 $x\in[a,b]$ 上一致收敛

又根据[[e:/OneDrive/数学分析/Note/Chapter 10/Chap10Note.org][函数项级数-一致收敛性质-可积性]] $\lim_{n\to\infty}\left\{\int_a^b h_n(x)dx\right\}=\int_a^b \left\{\lim_{n\to\infty}h_n(x)\right\}dx=0$

****** 推导不等式

对于任意 $i<n$ 均有：

\begin{aligned}
0&\leq g_n(x)=g_i(x)+(g_n(x)-g_i(x))\leq g_i(x)+\left\{\max(g_1(x),g_2(x),...,g_n(x))-g_i(x)\right\}\\
&\leq g_i(x)+\sum_{i=1}^{n-1} \left\{\max(g_i(x),g_{i+1}(x),...,g_n(x))-g_i(x)\right\}
\end{aligned}

由于 $h_n(x)=\min(g_1(x),g_2(x),...,g_n(x))$ 故也有 $0\leq g_n(x)\leq h_n(x)+\sum_{i=1}^{n-1} \left\{\max(g_i(x),g_{i+1}(x),...,g_n(x))-g_i(x)\right\}$

由于 $f_i(x)\geq f_j(x),i>j$ 且 $g_i(x)\leq f_i(x)$ 故有 $\max(g_i(x),g_{i+1}(x),...,g_n(x))\leq\max(f_i(x),f_{i+1}(x),...,f_n(x))\leq f_i(x)$

则根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-保序性]]及[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-线性]]有：

\begin{aligned}
\int_a^b f_i(x)&\geq \int_a^b \max(g_i(x),g_{i+1}(x),...,g_n(x))dx\\
&=\int_a^b \max(g_i(x),g_{i+1}(x),...,g_n(x))-g_i(x)+g_i(x)dx\\
&=\int_a^b \max(g_i(x),g_{i+1}(x),...,g_n(x))-g_i(x)dx+\int_a^bg_i(x)dx\\
\therefore & \int_a^b \max(g_i(x),g_{i+1}(x),...,g_n(x))-g_i(x)dx\leq \int_a^b f_i(x)-\int_a^bg_i(x)dx\leq \frac{\epsilon}{2^i}\\
\end{aligned}

故根据之前推导和[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-保序性]]及[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-线性]]有：

\begin{aligned}
0&\leq \int_a^b g_n(x)dx\leq \int_a^b \left\{h_n(x)+\sum_{i=1}^{n-1} \left\{\max(g_i(x),g_{i+1}(x),...,g_n(x))-g_i(x)\right\}\right\}dx\\
&\leq \int_a^b h_n(x)dx +\sum_{i=1}^{n-1} \int_a^b \left\{\max(g_i(x),g_{i+1}(x),...,g_n(x))-g_i(x)\right\}dx\\
&\leq \int_a^b h_n(x)dx + \sum_{i=1}^{n-1}\frac{\epsilon}{2^i}\\
&=\int_a^b h_n(x)dx + \epsilon\left(1-\frac{1}{2^{n-1}}\right)
\end{aligned}

又根据定义 $\int_a^b f_n(x)dx<\int_a^b g(x)+\frac{\epsilon}{2^n}$ 故有

\begin{aligned}
\int_a^b f_n(x)dx&<\int_a^b g(x)+\frac{\epsilon}{2^n}\\
&\leq \int_a^b h_n(x)dx + \epsilon\left(1-\frac{1}{2^{n-1}}\right) + \frac{\epsilon}{2^n}\\
&= \int_a^b h_n(x)dx + \epsilon\left(1-\frac{1}{2^n}\right)
\end{aligned}

****** 结论

故综上所述 $\forall\epsilon>0$ 存在一组函数 $\left\{h_n(x)\big|\int_a^b f_n(x)dx\leq\int_a^b h_n(x)dx + \frac{\epsilon}{2}\left(1-\frac{1}{2^n}\right),\lim_{n\to\infty}\left\{\int_a^b h_n(x)dx\right\}=0\right\}$

故根据极限定义 $\exists N,\forall n>N\Rightarrow \int_a^b h_n(x)dx<\frac{\epsilon}{2}\Rightarrow \int_a^b f_n(x)dx\leq\int_a^b h_n(x)dx + \frac{\epsilon}{2}\left(1-\frac{1}{2^n}\right)<\frac{\epsilon}{2}+\frac{\epsilon}{2}\left(1-\frac{1}{2^n}\right)<\epsilon$

故综上所述 $\forall\epsilon>0,\exists N,\forall n>N\Rightarrow \int_a^bf_n(x)dx<\epsilon$ 即为 $\lim_{n\to\infty}\int_a^bf_n(x)dx=0$ 的定义，故证毕。

**** 证明定理

根据条件，定义函数 $\phi_n(x)=\left|f_n(x)-f(x)\right|$ 根据定义，函数有：

（1） <<MK27>> $0\leq\phi_n(x)\leq M,\forall n\in N^+,\forall x\in[a,b]$ 即有界；

（2） $\lim_{n\to\infty}\phi_n(x)=0,\forall x\in[a,b]$ 

（3） $f_n(x),f(x)$ 在 $[a,b]$ 上均可积，故根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-线性]] $\int_a^bf_n(x)-f(x)dx$ 也可积，
  
     又根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-绝对可积]] $\int_a^b|f_n(x)-f(x)|dx$ 也可积 

定义函数 $\psi_n(x)=sup_{k\geq0}\{\phi_{n+k}(x)\}$ 同理函数有：

（1） $\psi_n(x)\geq \psi_{n+1}(x)$ 即单调递减；

（2） $\forall n\in N^+$ 定积分 $\int_a^b\psi_n(x)dx$ 可积；

（3） $\forall x\in[a,b]$ 有 $\lim_{n\to\infty}\psi_n(x)=0$；

（4） $\forall x\in[a,b],\forall n\in N^+\Rightarrow \psi_n(x)\geq0$

则根据[[MK26][引理2]]有 $\lim_{n\to\infty}\int_a^b\psi_n(x)dx=0$ 

且由于 $\psi_n(x)\geq\phi_n(x)$ 和之前条件[[MK27][（1）]]有 $0\leq\phi_n(x)\leq\psi_n(x)$ 

故根据夹逼定理 $\lim_{n\to\infty}\phi_n(x)=\lim_{n\to\infty}\left\{\int_a^b|f_n(x)-f(x)|dx\right\}=0$

*** <<MK37>>推论

$\lim_{n\to\infty}\int_a^b f_n(x)dx=\int_a^b f(x)dx=\int_a^b \lim_{n\to\infty}f_n(x)dx$

**** 证明

由于 $-|f_n(x)-f(x)|\leq f_n(x)-f(x)\leq|f_n(x)-f(x)|$ 

则根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-保序]]可得 $\int_a^b-|f_n(x)-f(x)|dx\leq \int_a^b f_n(x)-f(x)dx\leq\int_a^b|f_n(x)-f(x)|dx$

则根据极限四则运算 $\lim_{n\to\infty}\int_a^b-|f_n(x)-f(x)|dx=-\lim_{n\to\infty}\int_a^b|f_n(x)-f(x)|dx=\lim_{n\to\infty}\int_a^b|f_n(x)-f(x)|dx=0$

则根据极限夹逼定理 $\lim_{n\to\infty}\int_a^b f_n(x)-f(x)dx=0$ 

再根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-线性]]和极限四则运算有 $\lim_{n\to\infty}\int_a^b f_n(x)-f(x)dx=0=\lim_{n\to\infty}\int_a^b f_n(x)dx-\lim_{n\to\infty}\int_a^b f(x)dx$ 

证毕。

** 区域无限反常重积分

*** 定义

定义符号：

（1） 存在 $R^n$ 欧式空间上的零边界无界区域 $D$

（2） 零边界曲面 $\Gamma$ 将无界区域 $D$ 切割，形成零边界有界区域 $D_\Gamma$

（3） 定义 $d(\Gamma)=inf\left\{|\vec{x}|\big|\vec{x}\in\Gamma\right\}$ 其中 $|\vec{x}|$ 为向量 $\vec{x}$ 到原点的距离，根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][构造Euclid空间-定义距离]]计算

（4） 定义 $f(\vec{x})$ 为 $D_\Gamma$ 上的可积函数

则当 $d(\Gamma)$ 趋向于无限大，对于任取 $\Gamma$ 极限 $\lim_{d(\Gamma)\to\infty}\left\{\int_{D_\Gamma}f(\vec{x})d\vec{x}\right\}=I$ 存在，则称反常重积分 $\int_{D}f(\vec{x})d\vec{x}=\lim_{d(\Gamma)\to\infty}\left\{\int_{D_\Gamma}f(\vec{x})d\vec{x}\right\}$

即为 $\forall\epsilon>0,\exists\delta,\forall \left\{\Gamma\big|d(\Gamma)>\delta\right\}\Rightarrow \left|\int_{D_\Gamma}f(\vec{x})d\vec{x}-I\right|<\epsilon$

亦称反常重积分收敛，反之则称发散。

*** 敛散性

**** <<MK28>>引理1 

若函数 $f(\vec{x})\geq 0$ 是零边界无界区域 $D$ 上可积的函数，若存在一组零边界曲面 $\left\{\Gamma_n\right\}$ 分割 $D$ 为 $D_1,D_2,...,D_n$ 且满足：

（1） $D_1\subset D_2\subset...\subset D_n\subset...\a$ 

（2） $\lim_{n\to\infty}d(\Gamma_n)=\infty$

则反常重积分 $\int_Df(\vec{x})d\vec{x}$ 收敛的充要条件是数列 $\left\{\int_{D_n}f(\vec{x})d\vec{x}\right\}$ 收敛，

且在收敛时有 $\int_Df(\vec{x})d\vec{x}=\lim_{n\to\infty}\left\{\int_{D_n}f(\vec{x})d\vec{x}\right\}$ 

***** 证明

****** 充分性

已知 $\int_D f(\vec{x})d\vec{x}=I$ 根据定义 $\lim_{d(\Gamma)\to\infty}\left\{\int_{D_\Gamma}f(\vec{x})d\vec{x}\right\}=I$

写成数学语言 $\forall\epsilon>0,\exists\delta,\forall \left\{\Gamma\big|d(\Gamma)>\delta\right\}\Rightarrow \left|\int_{D_\Gamma}f(\vec{x})d\vec{x}-I\right|<\epsilon$

由于 $\lim_{n\to\infty}d(\Gamma_n)=\infty$ 则有 $\forall\delta>0,\exists N,\forall n>N\Rightarrow d(\Gamma_n)>\delta$ 

连接以上两个条件得 $\forall\epsilon>0,\exists N,\forall n>N\Rightarrow \left|\int_{D_n}f(\vec{x})d\vec{x}-I\right|<\epsilon$

即为 $\lim_{n\to\infty}\left\{\int_{D_n}f(\vec{x})d\vec{x}\right\}=I$ 证毕。

****** 必要性

已知 $\lim_{n\to\infty}\left\{\int_{D_n}f(\vec{x})d\vec{x}\right\}=I$ 即为 $\forall\epsilon>0,\exists N,\forall n>N\Rightarrow \left|\int_{D_n}f(\vec{x})d\vec{x}-I\right|<\epsilon$

由于 $f(\vec{x})$ 在 $D$ 上均大于零，且由于条件（1），故有 $\int_{D_{n+1}}f(\vec{x})d\vec{x}>\int_{D_n}f(\vec{x})d\vec{x}$ 即数列单调递增

故 $I$ 为数列的上确界，重写已知条件为 $\forall\epsilon>0,\exists N,\forall n>N\Rightarrow I-\int_{D_n}f(\vec{x})d\vec{x}<\epsilon$

定义 $\rho(\Gamma)=sup\left\{|\vec{x}|\big|\vec{x}\in\Gamma\right\}$ 则定义曲面 $\Gamma$ 满足：

（1） $\left\{\Gamma\big|d(\Gamma)\geq\rho(\Gamma_{N+1})\right\}$

（2） 与 $D$ 组成有界区域 $D_\Gamma$

因为 $\lim_{n\to\infty}d(\Gamma_n)=\infty$ 则存在 $k$ 使得 $d(\Gamma_{N+k})>\rho(\Gamma)$ 

故有 $\int_{D_{N+1}}f(\vec{x})d\vec{x}\leq \int_{D_\Gamma}f(\vec{x})d\vec{x}\leq \int_{D_{N+k}}f(\vec{x})d\vec{x}\leq I\Rightarrow 0\leq I-\int_{D_\Gamma}f(\vec{x})d\vec{x}\leq I-\int_{D_{N+1}}f(\vec{x})d\vec{x}\leq \epsilon$

结合上述条件 $\forall\epsilon>0,\exists\delta,\forall\left\{\Gamma\big|d(\Gamma)>\delta\right\}\Rightarrow\left|I-\int_{D_\Gamma}f(\vec{x})d\vec{x}\right|<\epsilon$

**** <<MK29>>比较判别法

$D$ 为 $R^n$ 上的零边界无界区域，若 $0\leq f(\vec{x})\leq g(\vec{x})$ 则有：

（1） 当 $\int_D g(\vec{x})d\vec{x}$ 收敛时 $\int_Df(\vec{x})d\vec{x}$ 也收敛；

（2） 当 $\int_D f(\vec{x})d\vec{x}$ 发散时 $\int_Dg(\vec{x})d\vec{x}$ 也发散；

***** 证明

****** 证明（1）

由于 $\int_D g(\vec{x})d\vec{x}=I$ 收敛，则根据[[MK28][引理1]]存在一组满足相应条件的 $\{\Gamma_n\}$ 使得 $\lim_{n\to\infty}\left\{\int_{D_n}g(\vec{x})d\vec{x}\right\}=I$

由于 $0\leq f(\vec{x})\leq g(\vec{x})$ 根据[[MK4][保序性]]有 $\int_{D_n}f(\vec{x})d\vec{x}\leq\int_{D_n}g(\vec{x})d\vec{x}$ 且 $I\geq\int_{D_n}g(\vec{x})d\vec{x}\geq\int_{D_n}f(\vec{x})d\vec{x}$

故 $\int_{D_n}f(\vec{x})d\vec{x}$ 有界且单调递增，根据极限定理 $\lim_{n\to\infty}\left\{\int_{D_n}f(\vec{x})d\vec{x}\right\}$ 存在

故根据[[MK28][引理1]] $\int_D f(\vec{x})d\vec{x}$ 收敛。

****** 证明（2）

由于 $f(\vec{x})>0$ 故若 $\int_Df(\vec{x})d\vec{x}$ 发散，则 $\int_Df(\vec{x})d\vec{x}=\infty$ 即 $\forall G>0,\exists\alpha,\forall \left\{\Gamma|d(\Gamma)>\alpha\right\}\Rightarrow \int_{D_\Gamma}f(\vec{x})d\vec{x}>G$

由于 $0\leq f(\vec{x})\leq g(\vec{x})$ 根据[[MK4][保序性]] $\int_{D_\Gamma}g(\vec{x})d\vec{x}>G>\int_{D_\Gamma}f(\vec{x})d\vec{x}>G$

故 $\forall G>0,\exists\alpha,\forall \left\{\Gamma|d(\Gamma)>\alpha\right\}\Rightarrow \int_{D_\Gamma}g(\vec{x})d\vec{x}>G$ 即反常积分发散。

**** <<MK30>>引理2：

定义无界区域 $D\subset R^n$ ，若函数 $f(\vec{x})\geq0,\vec{x}\in D$ 且反常积分 $\int_Df(\vec{x})d\vec{x}$ 发散，则有 $\lim_{d(\Gamma)\to\infty}\int_{D_\Gamma}f(\vec{x})d\vec{x}=\infty$

***** 证明

反正法，若 $\int_D f(\vec{x})d\vec{x}$ 发散且有上界 $M$ ：

（1） 定义光滑曲面 $\Gamma$ 与 $D$ 围成边界点体积为零的有界区域 $D_\Gamma$

（2） 由于 $f(\vec{x})>0,x\in D$ 根据[[MK4][保序性]]有 $\int_{D_\Gamma}f(\vec{x})dx>\int_{D_\Gamma}0dx=0$

故取一列 $\{\Gamma_n\},n\in N^+$ 分割 $D$ 为 $D_1,D_2,...,D_n$ 且满足：

（1） $D_1\subset D_2\subset...\subset D_n\subset...\a$ 

（2） $\lim_{n\to\infty}d(\Gamma_n)=\infty$

根据[[MK28][引理1]]，由于 $\int_D f(\vec{x})d\vec{x}$ 发散，则有 $\lim_{n\to\infty}\left\{\int_{D_n}f(\vec{x})d\vec{x}\right\}$ 发散

又由于 $0\leq\int_{D_n} f(\vec{x})d\vec{x}\leq M$ 故数列 $\left\{\int_{D_n}f(\vec{x})d\vec{x}\right\}$ 有界，根据[[e:/OneDrive/数学分析/Note/Chapter 11/Chap11Note.org][实数系基本定理-Bolzano-Weierstrass定理]]，有界数列必有收敛子列

故得一列 $\left\{\int_{D_k}f(\vec{x})d\vec{x}\right\}$ 当 $k\to\infty$ 时，数列收敛。同样根据[[MK28][引理1]]得反常积分收敛，故推出矛盾

**** <<MK32>>引理3：

若 $f(\vec{x}),g(\vec{x})$ 在边界为零的有界区域 $D$ 上可积，则 $H(\vec{x})=\max\left(f(\vec{x}),g(\vec{x})\right),h(\vec{x})=\min\left(f(\vec{x}),g(\vec{x})\right)$ 在区域 $D$ 上亦可积

***** 证明

根据定义: 

（1） $H(\vec{x})=\frac{1}{2}\left\{f(\vec{x})+g(\vec{x})+|f(\vec{x})-g(\vec{x})|\right\}$

（2） $h(\vec{x})=\frac{1}{2}\left\{f(\vec{x})+g(\vec{x})-|f(\vec{x})-g(\vec{x})|\right\}$

下面证明 $H(\vec{x})$ 可积， $h(\vec{x})$ 同理：

光滑曲面划分区域 $D$ 到 $\sigma_i$ ，则定义 $H(\vec{x}),x\in \sigma_i$ 的振幅为 $\omega_i=H(\vec{M}_i)-H(\vec{m}_i)$

则有

\begin{aligned}
\omega_i&=\frac{1}{2}\left\{f(\vec{M})+g(\vec{M})+|f(\vec{M})-g(\vec{M})|\right\}-\frac{1}{2}\left\{f(\vec{m})+g(\vec{m})+|f(\vec{m})-g(\vec{m})|\right\}\\
&=\frac{1}{2}\left\{\left[f(\vec{M})-f(\vec{m})\right]+\left[g(\vec{M})-g(\vec{m})\right] + \left[|f(\vec{M})-g(\vec{M})|-|f(\vec{m})-g(\vec{m})|\right]\right\}\\
&\leq \frac{1}{2}\left\{\left[f(\vec{M})-f(\vec{m})\right]+\left[g(\vec{M})-g(\vec{m})\right] + \left|f(\vec{M})-g(\vec{M})-f(\vec{m})+g(\vec{m})\right|\right\}\\
&=\frac{1}{2}\left\{\left[f(\vec{M})-f(\vec{m})\right]+\left[g(\vec{M})-g(\vec{m})\right] + \left|[f(\vec{M})-f(\vec{m})]-[g(\vec{M})-g(\vec{m})]\right|\right\}\\
&\leq \frac{1}{2}\left\{\left[f(\vec{M})-f(\vec{m})\right]+\left[g(\vec{M})-g(\vec{m})\right] + \left|f(\vec{M})-f(\vec{m})\right|+\left|g(\vec{M})-g(\vec{m})\right|\right\}\\
&\leq \frac{1}{2}\left\{\left[f(\vec{M})-f(\vec{m})\right]+\left[g(\vec{M})-g(\vec{m})\right] + \left|f(\vec{M})-f(\vec{m})\right|+\left|g(\vec{M})-g(\vec{m})\right|\right\}\\
\end{aligned}

又定义 $\omega_i^f$ 为 $f(\vec{x})$ 在 $\sigma_i$ 上的振幅， $\omega_i^g$ 为 $g(\vec{x})$ 在 $\sigma_i$ 上的振幅，

则有 $f(\vec{M})-f(\vec{m})\leq\left|f(\vec{M})-f(\vec{m})\right|\leq\omega^f_i,g(\vec{M})-g(\vec{m})\leq\left|g(\vec{M})-g(\vec{m})\right|\leq\omega^g_i$

故有 $\omega_i\leq \frac{1}{2}\left\{2\omega^f_i+2\omega^g_i\right\}=\omega^f_i+\omega^g_i$ 故 $\sum_{i=1}^n \omega_i v_i\leq \sum_{i=1}^n \omega^f_i v_i+\sum_{i=1}^n \omega^g_i v_i$

又因为振幅，故 $\sum_{i=1}^n \omega_i v_i\geq 0$

由于 $f(\vec{x}),g(\vec{x})$ 可积，故根据[[MK31][可积充要条件]] $\forall P\Rightarrow \lim_{\lambda\to0}\sum_{i=1}^n \omega^f_i v_i=\lim_{\lambda\to0}\sum_{i=1}^n \omega^g_i v_i=0$

故根据极限夹逼定理可得 $\forall P\Rightarrow \lim_{\lambda\to0}\sum_{i=1}^n \omega_i v_i=0$ 同理根据[[MK31][可积充要条件]] $H(\vec{x})$ 在 $D$ 上可积，证毕。

**** <<MK36>>引理4：

存在 $R^n$ 欧式空间上的零边界无界区域 $D$ ，函数 $f(\vec{x})$ 在 $D$ 上反常积分可积的充要条件是 $|f(\vec{x})|$ 在 $D$ 上可积

***** 证明

定义两个函数 $f^+(\vec{x})=\begin{cases}f(\vec{x})&f(\vec{x})\geq0\\0&f(\vec{x})<0\end{cases},f^-(\vec{x})=\begin{cases}0&f(\vec{x})>0\\f(\vec{x})&-f(\vec{x})\leq0\end{cases}$

****** 充分性

已知 $|f(\vec{x})|$ 可积，根据定义函数 $f^+(\vec{x}),f^-(\vec{x})$ 均大于 $0$ 小于 $|f(\vec{x})|$ 

故根据[[MK29][比较判别法]]得 $\int_Df^+(\vec{x})d\vec{x},\int_Df^-(\vec{x})d\vec{x}$ 均可积

故根据[[MK3][线性]]性质有 $\int_Df(\vec{x})d\vec{x}=\int_Df^+(\vec{x})-f^-(\vec{x})d\vec{x}=\int_Df^+(\vec{x})d\vec{x}-\int_Df^-(\vec{x})d\vec{x}$ 

故 $\int_Df(\vec{x})d\vec{x}$ 可积，证毕。

****** 必要性

反证法：已知 $\int_Df(\vec{x})d\vec{x}=I$ 可积，若 $|f(\vec{x})|$ 不可积

******* 基础条件

则 $f^+(\vec{x}),f^-(\vec{x})$ 中必有一个不可积，假设 $f^+(\vec{x})$ 不可积

由于 $f^+(\vec{x})\geq0$ ，则根据[[MK30][引理2]]可得发散的定义 $\forall K>0,\exists\delta,\forall \left\{\Gamma\big|d(\Gamma)>\delta\right\}\Rightarrow \int_{D_\Gamma}f^+(\vec{x})d\vec{x}>K$

由于反常积分 $\int_D f(\vec{x})d\vec{x}$ 可积，则对于有界区域 $D_i\subset D$ 来说 $\int_{D_i} f(\vec{x})d\vec{x}$ 可积是前提条件 

又由于 $f^+(\vec{x})=\max(f(\vec{x}),0)$ 故根据[[MK32][引理3]] $\int_{D_i} f^+(\vec{x})d\vec{x}$ 也可积

且根据[[MK6][区域可加]]有 $\int_{D_i-D_j}f^+(\vec{x})d\vec{x},\ D_j\subset D_i$ 亦可积

******* 下面开始取 $\{\Gamma_n\}$ ：

（1） 取 $\Gamma_1$ 为任一满足条件的曲面

（2） 取 $\Gamma_{n+1}$ 使得 $\left\{\int_{D_{n+1}-D_n}f^+(\vec{x})d\vec{x}\right\}>n$ 由于 $\int_{D_i}f^+(\vec{x})d\vec{x}$ 可积，故利用反常积分不可积定义
  
      对于 $K=\int_{D_i}f^+(\vec{x})d\vec{x}+n$ 存在一个 $\Gamma_{n+1}$ 使得 $\int_{D_\Gamma}f^+(\vec{x})d\vec{x}>K$ 且围成的体积 $D_n\subset D_{n+1}$

（3） $\lim_{n\to\infty}d(\Gamma_n)=\infty$

（4)  $\Gamma_n$ 零边界

******* 下面开始取 $\{\Gamma_n'\}$

（1） 区域 $D_{n+1}-D_{n}$ 由零边界曲面划分为小区域 $\sigma_i$ ，定义 $m_i=\min\{f^+(\vec{x})\},\vec{x}\in \sigma_i$ 由于可积，

      故[[MK33][可积定理1]]可得 $\lim_{\lambda\to0}\sum_{i=0}^n m_iv_i=\int_{D_{n+1}-D_n}f^+(\vec{x})d\vec{x}$ 故只要划分足够细，则有 $\sum_{i=0}^n m_iv_i>\int_{D_{n+1}-D_n}f^+(\vec{x})d\vec{x}-1>n-1$

      取 $P_n=\cup \sigma_k,m_k>0$

（2） 用体积（面积）极小的零边界通道连接 $D_n$ 与 $P_n$ 使得函数在通道 $u_n$ 上的积分 $\int_{u_n}f(\vec{x})d\vec{x}>-1$

（3） 将 $\Gamma_n$ ,通道 $u_n$ 以及 $P_n$ 连成新的曲面 $\Gamma_n'$

******* 结论

由于 $\lim_{n\to\infty}d(\Gamma_n)=\infty$ 根据重积分可积定义 $\lim_{n\to\infty}\int_{D_n}f(\vec{x})d\vec{x}=I$

由于 $\int_{P_n}f(\vec{x})d\vec{x}=\int_{P_n}f^+(\vec{x})d\vec{x}$ 故 $\int_{D_n'}f(\vec{x})d\vec{x}=\int_{D_n}f(\vec{x})d\vec{x}+\int_{Du_n}f(\vec{x})d\vec{x}+\int_{P_n}f^+(\vec{x})d\vec{x}>\int_{D_n}f(\vec{x})d\vec{x}+n-2$

故当 $n\to\infty$ 时 $\int_{D_n}f(\vec{x})d\vec{x}$ 收敛 $n-2$ 发散

则 $\int_{D_n}f(\vec{x})d\vec{x}+n-1$ 发散，由于 $\int_{D_n'}f(\vec{x})d\vec{x}>\int_{D_n}f(\vec{x})d\vec{x}+n-2$ 

故根据极限比较判别法 $\lim_{n\to\infty}\int_{D_n'}f(\vec{x})d\vec{x}$ 发散，由于 $d(\Gamma_n')\geq d(\Gamma_n)$ 且 $\lim_{n\to\infty}d(\Gamma_n)=\infty$ 故 $\lim_{n\to\infty}d(\Gamma_n')=\infty$

重积分定义为任意 $d(\Gamma)\to\infty$ 的零边界曲面极限均收敛，故与 $\int_Df(\vec{x})d\vec{x}=I$ 可积矛盾。

***** 推论（柯西收敛）

设 $D$ 为 $R^n$ 空间上 $\left\{\vec{x}\big|\sum_{i=1}^n x_i^2\geq A^2\right\}$ 及立体角 $\Omega$ 围成的区域， $f(\vec{x})$ 为定义在 $D$ 上的函数，则：

（1） 若存在常数 $M$ 使得 $|f(\vec{x})|\leq \frac{M}{(\sum_{i=1}^n x_i^2)^{\frac{p}{2}}}$ 且 $p>n$ 则反常重积分 $\int_Df(\vec{x})d\vec{x}$ 收敛

（2） 若存在常数 $M$ 使得 $|f(\vec{x})|\geq \frac{M}{(\sum_{i=1}^n x_i^2)^{\frac{p}{2}}}$ 且 $p\leq n$ 则反常重积分 $\int_Df(\vec{x})d\vec{x}$ 发散

****** 证明

根据[[MK35][推论]]，当 $p>n$ 时 $\int_D\frac{1}{(\sum_{i=1}^n x_i^2)^{\frac{p}{2}}}d\vec{x}$ 收敛，则 $\int_D\frac{M}{(\sum_{i=1}^n x_i^2)^{\frac{p}{2}}}d\vec{x}$ 收敛

又由于 $|f(\vec{x})|\geq 0$ 根据[[MK29][比较判别法]] $\int_D|f(\vec{x})|d\vec{x}$ 收敛，又根据[[MK36][引理4]]得 $\int_Df(\vec{x})d\vec{x}$ 收敛。

（2）同理可证。

*** 性质

**** <<MK42>>线性

若无界区域 $D$ 上函数 $f(\vec{x}),g(\vec{x})$ 反常积分均收敛，则 $\int_D \left\{Af(\vec{x})+Bg(\vec{x})\right\}d\vec{x}=A\int_Df(\vec{x})d\vec{x}+B\int_Dg(\vec{x})d\vec{x}$

***** 证明

定义光滑曲面 $\Gamma$ 与 $D$ 为成 $D_\Gamma$

根据有界区域重积分[[MK3][线性]] $\int_{D_\Gamma} \left\{Af(\vec{x})+Bg(\vec{x})\right\}d\vec{x}=A\int_{D_\Gamma}f(\vec{x})d\vec{x}+B\int_{D_\Gamma}g(\vec{x})d\vec{x}$

由于 $f(\vec{x}),g(\vec{x})$ 反常积分均收敛，写为定义

（1） $\forall\epsilon>0,\exists\delta_1,\forall \left\{\Gamma\big|d(\Gamma)>\delta_1\right\}\Rightarrow \left|\int_{D_\Gamma}f(\vec{x})d\vec{x}-I_1\right|<\frac{\epsilon}{2A}$

（2） $\forall\epsilon>0,\exists\delta_2,\forall \left\{\Gamma\big|d(\Gamma)>\delta_2\right\}\Rightarrow \left|\int_{D_\Gamma}g(\vec{x})d\vec{x}-I_2\right|<\frac{\epsilon}{2B}$

则有 

\begin{aligned}
&\forall\epsilon>0,\exists\delta>\max(\delta_1,\delta_2),\forall \left\{\Gamma\big|d(\Gamma)>\delta\right\}\\
&\Rightarrow \\
&\left|\int_{D_\Gamma}\left{Af(\vec{x})+Bg(\vec{x})\right\}d\vec{x}-(AI_1+BI_2)\right|\\
=&\left|A\left(\int_{D_\Gamma}f(\vec{x})d\vec{x} - I_1\right)+B\left(\int_{D_\Gamma}g(\vec{x})d\vec{x}-I_2\right)\right|\\
\leq&A\left|\int_{D_\Gamma}f(\vec{x})d\vec{x} - I_1\right|+B\left|\int_{D_\Gamma}g(\vec{x})d\vec{x}-I_2\right|\\
<&\epsilon
\end{aligned}

故 $\int_D \left\{Af(\vec{x})+Bg(\vec{x})\right\}d\vec{x}=AI_1+BI_2=A\int_Df(\vec{x})d\vec{x}+B\int_Dg(\vec{x})d\vec{x}$

*** <<MK41>>累次反常积分线性

若累次反常积分 $\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f(\vec{x})dx_ndx_{n-1}...dx_1,\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty g(\vec{x})dx_ndx_{n-1}...dx_1$ 收敛

则有 $\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty \left\{Af(\vec{x})+Bg(\vec{x})\right\}dx_ndx_{n-1}...dx_1=A\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f(\vec{x})dx_ndx_{n-1}...dx_1+B\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty g(\vec{x})dx_ndx_{n-1}...dx_1$

**** <<MK47>>证明 

数学归纳法

***** 先证明对于给定 $x_1,x_2,...,x_{n-1}$ 下 

若 $\int_a^\infty f(\vec{x})dx_n=I_1,\int_a^\infty g(\vec{x})dx_n=I_2$ 收敛，则有 $\int_a^\infty\left\{Af(\vec{x})+Bg(\vec{x})\right\}dx_n=A\int_a^\infty f(\vec{x})dx_n+B\int_a^\infty f(\vec{x})dx_n$

****** <<MK40>>证明

根据反常积分定义

（1） $\forall\epsilon>0,\exists\delta_1,\forall K>\delta_1\Rightarrow \left|\int_a^Kf(\vec{x})d\vec{x}-I_1\right|<\frac{\epsilon}{2A}$

（2） $\forall\epsilon>0,\exists\delta_2,\forall K>\delta_2\Rightarrow \left|\int_a^Kg(\vec{x})d\vec{x}-I_2\right|<\frac{\epsilon}{2B}$

则根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-线性]]

\begin{aligned}
&\forall\epsilon>0,\exists\delta>\max(\delta_1,\delta_2),\forall K>\delta\\
&\Rightarrow \\
&\left|\int_a^K\left{Af(\vec{x})+Bg(\vec{x})\right\}d\vec{x}-(AI_1+BI_2)\right|\\
=&\left|A\left(\int_a^Kf(\vec{x})d\vec{x} - I_1\right)+B\left(\int_a^Kg(\vec{x})d\vec{x}-I_2\right)\right|\\
\leq&A\left|\int_a^Kf(\vec{x})d\vec{x} - I_1\right|+B\left|\int_a^Kg(\vec{x})d\vec{x}-I_2\right|\\
<&\epsilon
\end{aligned}

即 $\lim_{A\to\infty}\int_a^A\left\{Af(\vec{x})+Bg(\vec{x})\right\}dx_n=AI_1+BI_2$ 证毕

***** 证明对于给定 $x_1,x_2,...,x_{i-1}$ 下

若 $\int_{a_{i+1}}^\infty...\int_{a_n}^\infty \left\{Af(\vec{x})+Bg(\vec{x})\right\}dx_n...dx_{i+1}=A\int_{a_{i+1}}^\infty...\int_{a_n}^\infty f(\vec{x})dx_n...dx_{i+1}+B\int_{a_{i+1}}^\infty...\int_{a_n}^\infty g(\vec{x})dx_n...dx_{i+1}$ 成立，

且 $\int_{a_i}^\infty...\int_{a_n}^\infty f(\vec{x})dx_n...dx_i=I_1,\int_{a_i}^\infty...\int_{a_n}^\infty g(\vec{x})dx_n...dx_i=I_2$ 均可积

则有 $\int_{a_i}^\infty...\int_{a_n}^\infty\left\{Af(\vec{x})+Bg(\vec{x})\right\}dx_n...dx_i=A\int_{a_i}^\infty...\int_{a_n}^\infty f(\vec{x})dx_n...dx_i+B\int_{a_i}^\infty...\int_{a_n}^\infty g(\vec{x})dx_n...dx_i$

****** 证明

定义 $K>a_i,F(x_i)=\int_{a_{i+1}}^\infty...\int_{a_n}^\infty f(\vec{x})dx_n...dx_{i+1},G(x_i)=\int_{a_{i+1}}^\infty...\int_{a_n}^\infty g(\vec{x})dx_n...dx_{i+1}$ ，根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-线性]]及给定条件

\begin{aligned} 
&\int_{a_i}^K\int_{a_{i+1}}^\infty...\int_{a_n}^\infty \left\{Af(\vec{x})+Bg(\vec{x})\right\}dx_n...dx_{i+1}dx_i\\
=&\int_{a_i}^K\left\{A\int_{a_{i+1}}^\infty...\int_{a_n}^\infty f(\vec{x})dx_n...dx_{i+1}+B\int_{a_{i+1}}^\infty...\int_{a_n}^\infty g(\vec{x})dx_n...dx_{i+1}\right\}dx_i\\
=&A\int_{a_i}^K\int_{a_{i+1}}^\infty...\int_{a_n}^\infty f(\vec{x})dx_n...dx_{i+1}dx_i+B\int_{a_i}^K\int_{a_{i+1}}^\infty...\int_{a_n}^\infty g(\vec{x})dx_n...dx_{i+1}dx_i\\
=&A\int_{a_i}^KF(x_i)dx_i+B\int_{a_i}^KG(x_i)dx_i
\end{aligned}

接下来根据[[MK40][同上]]证明便可得命题结论

***** 结合条件

由于 $\int_a^\infty\left\{Af(\vec{x})+Bg(\vec{x})\right\}dx_n=A\int_a^\infty f(\vec{x})dx_n+B\int_a^\infty f(\vec{x})dx_n$ 

且对于任意给定 $x_1,x_2,...,x_{i-1},1<i\leq n,i\in N^+$ 在：

（1） $\int_{a_{i+1}}^\infty...\int_{a_n}^\infty \left\{Af(\vec{x})+Bg(\vec{x})\right\}dx_n...dx_{i+1}=A\int_{a_{i+1}}^\infty...\int_{a_n}^\infty f(\vec{x})dx_n...dx_{i+1}+B\int_{a_{i+1}}^\infty...\int_{a_n}^\infty g(\vec{x})dx_n...dx_{i+1}$ 成立

（2） $\int_{a_i}^\infty...\int_{a_n}^\infty f(\vec{x})dx_n...dx_i=I_1,\int_{a_i}^\infty...\int_{a_n}^\infty g(\vec{x})dx_n...dx_i=I_2$ 均可积

条件下均有 $\int_{a_i}^\infty...\int_{a_n}^\infty\left\{Af(\vec{x})+Bg(\vec{x})\right\}dx_n...dx_i=A\int_{a_i}^\infty...\int_{a_n}^\infty f(\vec{x})dx_n...dx_i+B\int_{a_i}^\infty...\int_{a_n}^\infty g(\vec{x})dx_n...dx_i$

故数学归纳法成立，证毕。

*** <<MK43>>区域无限反常重积分计算

定义无界区域 $D=[a_1,\infty)\times[a_2,\infty)\times...\times[a_n,\infty)\subset R^n$ ，若在 $D$ 上：

（1） $f(\vec{x})$ 连续；

（2） 累次反常积分 $\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f(\vec{x})dx_ndx_{n-1}...dx_1,\ \int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty |f(\vec{x})|dx_ndx_{n-1}...dx_1$ 均收敛

则有 $\int_D f(\vec{x})d\vec{x}=\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f(\vec{x})dx_ndx_{n-1}...dx_1$

**** <<MK46>>证明

***** <<MK39>>先证 $f(\vec{x})\geq 0$

****** 证明给定 $x_1,x_2,...,x_{i-1}$ 情况下 

对于给定满足条件的 $x_1,x_2,...,x_{i-1}$ 若有：

（1） $\int_{a_i}^\infty\int_{a_{i+1}}^\infty...\int_{a_n}^\infty f(\vec{x})dx_ndx_{n-1}...dx_i$ 收敛且

（2） 存在一组数列 $\left\{A^k_s\big|\lim_{k\to\infty}A^k_s=\infty,A^{k+1}_s\geq A^k_s,\forall s\in N^+\right\}$ 使得 $\lim_{k\to\infty}\int_{a_{i+1}}^{A^k_{i+1}}...\int_{a_n}^{A^k_n} f(\vec{x})dx_n...dx_{i+1}=\int_{a_{i+1}}^\infty...\int_{a_n}^\infty f(\vec{x})dx_n...dx_{i+1}$

则存在数列组 $\left\{B^k_s\big|\lim_{k\to\infty}B^k_s=\infty,B^{k+1}_s\geq B^k_s,\forall s\in N^+\right\}$ 使得 $\lim_{k\to\infty}\int_{a_i}^{B^k_i}\int_{a_{i+1}}^{B^k_{i+1}}...\int_{a_n}^{B^k_n} f(\vec{x})dx_n...dx_i=\int_{a_i}^\infty\int_{a_{i+1}}^\infty...\int_{a_n}^\infty f(\vec{x})dx_n...dx_i$

******* 证明

******** 利用积分极限等价定理

定义 $\psi_u(x_i)=\int_{a_{i+1}}^{A^u_{i+1}}...\int_{a_n}^{A^u_n} f(\vec{x})dx_n...dx_{i+1},\psi(x_i)=\int_{a_{i+1}}^{\infty}...\int_{a_n}^{\infty} f(\vec{x})dx_n...dx_{i+1}$ 则函数满足

（1） $\forall u\in N^+$ 定积分 $\int_{a_i}^{A_i^u} \psi_n(x_i)dx_i$ 可积（根据[[e:/OneDrive/数学分析/Note/Chapter 8/Chap8Note.org][反常积分定义-边界无穷积分]]及反常累次积分可积条件）

（2） $\forall x_i\in[a_i,A^u_i]$ 有 $\lim_{u\to\infty}\psi_n(x_i)=\psi(x)$ 

（3） $\forall x_i\in[a_i,A^u_i],\forall u\in N^+\Rightarrow |\psi_u(x_i)|\leq M$ 其中 $M$ 为有界正实数（即为 $\lim_{u\to\infty}\psi_u(x_i)=\psi(x_i)<\infty,\forall x_i\in[a_i,A^u_i]$ )

（4） 定积分 $\int_{a_i}^{A^u_i} \psi(x_i)dx_i$ 可积（给定条件（1））

故根据[[MK37][积分极限等价定理推论]]有 $\lim_{u\to\infty}\int_{a_i}^{A^k_i}\psi_u(x_i)dx_i=\int_{a_i}^{A^k_i}\lim_{u\to\infty}\psi_u(x_i)dx_i=\int_{a_i}^{A^k_i}\psi(x_i)dx_i$

******** 取数列组 $B$

故函数满足以下两种性质

（1） $\lim_{k\to\infty}\int_{a_i}^{A_i^k}\psi(x_i)dx_i=I$ 即 $\forall\epsilon>0,\exitsts K,\forall k>K\Rightarrow\left|\int_{a_i}^{A_i^k}\psi(x_i)dx_i-I\right|<\epsilon$

（2） 对于给定 $k$ 有 $\lim_{u\to\infty}\int_{a_i}^{A^k_i}\psi_u(x_i)dx_i=\int_{a_i}^{A^k_i}\psi(x_i)dx_i$ 即 $\forall\epsilon>0,\exists U(k),\forall u>U(k)\Rightarrow\left|\int_{a_i}^{A^k_i}\psi_u(x_i)dx_i-\int_{a_i}^{A^k_i}\psi(x_i)dx_i\right|<\frac{\epsilon}{2}$

则取 $\epsilon=\frac{1}{v}$ 取 $B_s^k=A_s^{U(k)+1},i<s\leq n$ 以及 $B^k_i=A^k_i$ 则有 $\left|\int_{a_i}^{B^k_i}\int_{a_{i+1}}^{B^k_{i+1}}...\int_{a_n}^{B^k_n} f(\vec{x})dx_n...dx_i-\int_{a_i}^{B^k_i}\int_{a_{i+1}}^{\infty}...\int_{a_n}^{\infty} f(\vec{x})dx_n...dx_i\right|<\frac{1}{2k}$

即 $\left|\int_{a_i}^{B^k_i}\int_{a_{i+1}}^{B^k_{i+1}}...\int_{a_n}^{B^k_n} f(\vec{x})dx_n...dx_i-\int_{a_i}^{B^k_i}\psi(x_i)dx_i\right|<\frac{1}{2k}$

******** 证明结论

故 $\forall\epsilon>0$ 定义 $L>\frac{1}{\epsilon},L\in N^+$ 故有 $\frac{1}{L}<\epsilon$ 故取 $Z=\max(K,L)$ 则对于任意 $z>Z$ 有

\begin{aligned}
&\left|\int_{a_i}^{B^z_i}\int_{a_{i+1}}^{B^z_{i+1}}...\int_{a_n}^{B^z_n} f(\vec{x})dx_n...dx_i-I\right|\\
=&\left|\int_{a_i}^{B^z_i}\int_{a_{i+1}}^{B^z_{i+1}}...\int_{a_n}^{B^z_n} f(\vec{x})dx_n...dx_i-\int_{a_i}^{B^z_i}\int_{a_{i+1}}^{\infty}...\int_{a_n}^{\infty} f(\vec{x})dx_n...dx_i+\int_{a_i}^{B^z_i}\int_{a_{i+1}}^{\infty}...\int_{a_n}^{\infty} f(\vec{x})dx_n...dx_i-I\right|\\
\leq&\left|\int_{a_i}^{B^z_i}\int_{a_{i+1}}^{B^z_{i+1}}...\int_{a_n}^{B^z_n} f(\vec{x})dx_n...dx_i-\int_{a_i}^{B^z_i}\int_{a_{i+1}}^{\infty}...\int_{a_n}^{\infty} f(\vec{x})dx_n...dx_i\right|+\left|\int_{a_i}^{B^z_i}\int_{a_{i+1}}^{\infty}...\int_{a_n}^{\infty} f(\vec{x})dx_n...dx_i-I\right|\\
<&\frac{1}{2L}+\frac{\epsilon}{2}<\frac{\epsilon}{2}+\frac{\epsilon}{2}=\epsilon
\end{aligned}

故根据极限定义 $\lim_{k\to\infty}\int_{a_i}^{B^k_i}\int_{a_{i+1}}^{B^k_{i+1}}...\int_{a_n}^{B^k_n} f(\vec{x})dx_n...dx_i=I$

****** 结论

显然当 $i=n$ 的时候 $\psi_u(x_{n-1})=\int_0^{A_n^u}f(\vec{x})dx_n$ 满足

（1）  $\int_0^\infty f(\vec{x})dx_n$ 收敛（根据条件（2）累次反常积分存在）

（2） 存在数列 $A^k_n$ 满足 $\lim_{k\to\infty}A^k_n=\infty,A^{k+1}_n\geq A^k_n$

故根据数学归纳法可得存在数组 $\left\{B^k_s\big|\lim_{k\to\infty}B^k_s=\infty,B^{k+1}_s\geq B^k_s,\forall s\in N^+\right\}$ 使得 $\lim_{k\to\infty}\int_{a_1}^{B^k_1}...\int_{a_n}^{B^k_n} f(\vec{x})dx_n...dx_i=\int_{a_1}^\infty...\int_{a_n}^\infty f(\vec{x})dx_n...dx_i$ 

定义区域 $D_k=[a_1,B_1^k]\times[a_2,B_2^k]\times...\times[a_n,B_n^k]\subset D$

故根据[[MK28][引理1]]若 $\lim_{k\to\infty}\int_{D_k}f(\vec{x})d\vec{x}$ 收敛，则有 $\lim_{k\to\infty}\int_{D_k}f(\vec{x})d\vec{x}=\int_Df(\vec{x})d\vec{x}$

根据[[MK8][重积分计算]]有 $\int_{a_1}^{B^k_1}\int_{a_2}^{B^k_2}...\int_{a_n}^{B^k_n} f(\vec{x})dx_ndx_{n-1}...dx_1=\int_{D_k}f(\vec{x})d\vec{x}$

故有 $\int_{a_1}^\infty...\int_{a_n}^\infty f(\vec{x})dx_n...dx_i=\lim_{k\to\infty}\int_{a_1}^{B^k_1}...\int_{a_n}^{B^k_n} f(\vec{x})dx_n...dx_i=\lim_{k\to\infty}\int_{D_k}f(\vec{x})d\vec{x}=\int_Df(\vec{x})d\vec{x}$ 证毕 

***** 证明一般情况

****** 前提定义
定义两个函数 $f^+(\vec{x})=\begin{cases}f(\vec{x})&f(\vec{x})\geq0\\0&f(\vec{x})<0\end{cases},f^-(\vec{x})=\begin{cases}0&f(\vec{x})>0\\f(\vec{x})&-f(\vec{x})\leq0\end{cases}$

定义

（1） $\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f(\vec{x})dx_ndx_{n-1}...dx_1=I_1$

（2） $\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty |f(\vec{x})|dx_ndx_{n-1}...dx_1=I_2$

****** 证明 $\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f^+(\vec{x})dx_ndx_{n-1}...dx_1,\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f^-(\vec{x})dx_ndx_{n-1}...dx_1$ 收敛

由于 $f(\vec{x})=f^+(\vec{x})-f^-(\vec{x}),|f(\vec{x})|=f^+(\vec{x})+f^-(\vec{x})$ 且 $\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f(\vec{x})dx_ndx_{n-1}...dx_1=I_1,\ \int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty |f(\vec{x})|dx_ndx_{n-1}...dx_1=I_2$ 均收敛

故根据[[MK41][累次反常积分线性]]

\begin{aligned}
&\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f^+(\vec{x})dx_ndx_{n-1}...dx_1\\
=&\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty \frac{f(\vec{x})+|f(\vec{x})|}{2}dx_ndx_{n-1}...dx_1\\
=&\frac{1}{2}\left\{\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f(\vec{x})dx_ndx_{n-1}...dx_1-\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty |f(\vec{x})|dx_ndx_{n-1}...dx_1\right\}\\
=&\frac{I_1+I_2}{2}
\end{aligned}

故 $\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f^+(\vec{x})dx_ndx_{n-1}...dx_1=\frac{I_1+I_2}{2}$ 收敛

同理可证 $\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f^-(\vec{x})dx_ndx_{n-1}...dx_1=\frac{I_2-I_1}{2}$ 也收敛

****** 证明结论

由于 $f^+(\vec{x})\geq0,f^-(\vec{x})\geq0$ 且累次反常积分收敛，

故根据[[MK39][之前证明]]可得 $\int_D f^+(\vec{x})d\vec{x}=\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f^+(\vec{x})dx_ndx_{n-1}...dx_1=\frac{I_1+I_2}{2}$

对于 $f^-(\vec{x})$ 同理可得 $\int_D f^-(\vec{x})d\vec{x}=\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f^-(\vec{x})dx_ndx_{n-1}...dx_1=\frac{I_2-I_1}{2}$

则根据[[MK42][反常重积分线性]]有

\begin{aligned}
&\int_D f(\vec{x})d\vec{x}\\
=&\int_D f^+(\vec{x})d\vec{x}-\int_D f^-(\vec{x})d\vec{x}\\
=&\frac{I_1+I_2}{2}-\frac{I_2-I_1}{2}\\
=&I_1\\
=&\int_{a_1}^\infty\int_{a_2}^\infty...\int_{a_n}^\infty f(\vec{x})dx_ndx_{n-1}...dx_1
\end{aligned}

证毕

*** 常见反常重积分

**** 泊松积分

定义 $\int_{-\infty}^{+\infty} e^{-x^2}dx$

***** 求解

原函数沿 $x$ 轴对称，故 $\int_{-\infty}^{+\infty} e^{-x^2}dx=2\int_0^{ +\infty} e^{-x^2}dx$

定义重积分 $\int_D e^{-(x^2+y^2)}d\sigma,D=[0,\infty]\times[0,\infty]$ 由于：

（1） $e^{-(x^2+y^2)}$ 初等函数，故连续

（2） 累次积分 $\int_0^\infty\int_0^\infty e^{-(x^2+y^2)}dydx=\int_0^\infty e^{-x^2}dx\int_0^\infty e^{-y^2}dy=\left(\int_0^\infty e^{-x^2}dx\right)^2$

      由于 $0<e^{-x^2}<e^{-x},x\in[1,\infty]$ 且根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][牛顿莱布尼茨公式]] $\int_1^\infty e^{-x} dx=-\frac{1}{e^\infty}-\left(-\frac{1}{e}\right)<\infty$

      故根据保序性 $\int_1^\infty e^{-x^2}dx<\int_1^\infty e^{-x}dx<\frac{1}{e}$ 有界，且函数 $f(A)=\int_0^A e^{-x^2}dx,A>0$ 为单调递增函数

      故 $\int_1^\infty e^{-x^2}dx$ 收敛，又由于 $\int_0^1 e^{-x^2}dx$ 收敛，故根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][定积分基本性质-区间可加]]  $\int_0^\infty e^{-x^2}dx$ 收敛

则根据[[MK43][重积分计算]]得 $\int_D e^{-(x^2+y^2)}d\sigma=\int_0^\infty\int_0^\infty e^{-(x^2+y^2)}dydx=\int_0^\infty e^{-x^2}dx\int_0^\infty e^{-y^2}dy=\left(\int_0^\infty e^{-x^2}dx\right)^2$

对 $\int_D e^{-(x^2+y^2)}dxdy$ 极坐标变量代换得 $\int_D re^{-r^2}drd\theta,r\in[0,\infty],\theta\in\left[0,\frac{\pi}{2}\right]$

同理有：

（1） $re^{-r^2}$ 连续

（2） $\int_0^{\frac{\pi}{2}}\int_0^\infty re^{-r^2}drd\theta=\frac{\pi}{2}\left\{-\frac{1}{e^\infty}+\frac{1}{2e^0}\right\}=\frac{\pi}{4}$

故 $\int_D e^{-(x^2+y^2)}d\sigma=\frac{\pi}{4}\Rightarrow \int_0^\infty e^{-x^2}dx=\frac{\sqrt{\pi}}{2}$

故的泊松积分 $\int_{-\infty}^{+\infty} e^{-x^2}dx=\sqrt{\pi}$
**** $p$ 积分

定义 $f(\vec{x})=\frac{1}{\left(\sum_{i=1}^n x_i^2}\right)^{\frac{p}{2}},\vec{x}\in R^n$ 求其在区域 $D=\left\{\vec{x}\big|\sum_{i=1}^n x_i^2\geq A^2\right\}$ 上的反常积分

***** 解题

定义 $\Gamma=\left\{\vec{x}\big|\sum_{i=1}^n x_i^2}\leq R^2\right\}$ 则 $D_\Gamma=\left\{\vec{x}\big|A^2\leq\sum_{i=1}^n x_i^2\leq R^2\right\}$ 计算有界区域重积分

根据[[MK34][求变坐标变换]]可得

\begin{aligned}
\int_{D_\Gamma} f(\vec{x})d\vec{x}&=\int_{D_\Gamma}\frac{1}{\left(\sum_{i=1}^n x_i^2}\right)^{\frac{p}{2}}d\vec{x}\\
&=\int_{T(D_\Gamma)}\frac{1}{r^p}r^{n-1}\Pi_{i=1}^{n-2}\sin^{n-i-1}(\phi-i)drd\phi_{n-1}...d\phi_1\\
&=\int_{T(D_\Gamma)}\frac{1}{r^{p-n+1}}\Pi_{i=1}^{n-2}\sin^{n-i-1}(\phi-i)drd\phi_{n-1}...d\phi_1\\
\end{aligned} 

利用[[MK8][重积分计算]]，化为累次积分

\begin{aligned}
\int_{D_\Gamma} f(\vec{x})d\vec{x}&=\int_{T(D_\Gamma)}\frac{1}{r^{p-n+1}}\Pi_{i=1}^{n-2}\sin^{n-i-1}(\phi-i)drd\phi_{n-1}...d\phi_1\\
&=\int_a^R\frac{1}{r^{p-n+1}}dr\int_0^{2\pi}d\phi_{n-1}\prod_{i=1}^{n-2}\int_0^\pi \sin^{n-i-1}(\phi_i)d\phi_i
\end{aligned} 

显然其敛散性取决于 $\int_a^R\frac{1}{r^{p-n+1}}dr$ 根据[[e:/OneDrive/数学分析/Note/Chapter 7/Chap7Note.org][牛顿莱布尼茨公式]]

\begin{aligned}
\int_a^R\frac{1}{r^{p-n+1}}dr&=
\begin{cases}
\ln(R)-\ln(a) & p=n\\
\frac{1}{R^{p-n}}-\frac{1}{a^{p-n}} & p\ne n\\
\end{cases}
\end{aligned}

故 $p>n$ 时，反常积分收敛，反之发散。

***** <<MK35>>推论

若 $D_1$ 为 $D=\left\{\vec{x}\big|\sum_{i=1}^n x_i^2\geq A^2\right\}$ 及立体角 $\Omega$ 围成的区域 $p$ 积分在 $D_1$ 上的敛散性不变。

原因为变量代换后未对 $\int_a^R\frac{1}{r^{p-n+1}}dr$ 有影响。

** 无界函数反常重积分

*** <<MK45>>定义

对于光滑曲面围成的有界区域 $D$ 中存在面积为零的点集 $S$

函数 $f(\vec{x})$ 在 $\vec{x}\in D,\vec{x}\not\in S$ 上有定义

若 $\Gamma$ 为包含 $S$ 的曲面 $P$ 为 $\Gamma$ 上一点 $Q$ 为 $S$ 上一点，定义 $\rho(\Gamma)=sup\left\{|P-Q|\big|P\in\Gamma,Q\in S\right\}$

定义 $D_\Gamma$ 为区域 $D$ 中去掉 $\Gamma$ 包含的区域

则若对于任意 $\Gamma$ 重积分 $\int_{D_\Gamma}f(\vec{x})d\vec{x}$ 均可积且有 $\lim_{\rho(\Gamma)\to0}\int_{D_\Gamma}f(\vec{x})d\vec{x}$ 收敛

则称反常重积分 $\int_{D}f(\vec{x})dx=\lim_{\rho(\Gamma)\to0}\left\{\int_{D_\Gamma}f(\vec{x})d\vec{x}\right\}$

亦称反常重积分收敛，反之则称发散。

*** 敛散性

**** 引理1

定义有界区域 $D$ 及面积为零的点集 $S$ ，定义函数 $f(\vec{x})\geq0$ 在 $\vec{x}\in D,\vec{x}\not\in S$ 有定义

若存在一组零边界曲面 $\left\{\Gamma_n\right\}$ 分割 $D$ 为 $D_1,D_2,...,D_n$ 且满足：

（1） $D_1\subset D_2\subset...\subset D_n\subset...\a$ 

（2） $\lim_{n\to\infty}D_n=D$

（3） $\forall \vec{x}\in S\Rightarrow \vec{x}\not\in D_\Gamma$

则反常重积分 $\int_Df(\vec{x})d\vec{x}$ 收敛的充要条件是数列 $\left\{\int_{D_n}f(\vec{x})d\vec{x}\right\}$ 收敛，

且在收敛时有 $\int_Df(\vec{x})d\vec{x}=\lim_{n\to\infty}\left\{\int_{D_n}f(\vec{x})d\vec{x}\right\}$ 

***** 证明

****** 充分性

根据[[MK45][定义]] $\int_{D}f(\vec{x})dx=\lim_{\rho(\Gamma)\to0}\left\{\int_{D_\Gamma}f(\vec{x})d\vec{x}\right\}$

即 $\forall\epsilon>0,\exists\delta,\forall\rho(\Gamma)<\delta\Rightarrow\left|\int_{D_\Gamma}f(\vec{x})d\vec{x}-\int_{D}f(\vec{x})d\vec{x}\right|<\epsilon$

由于条件（2），故可得 $\lim_{n\to\infty}\rho(\Gamma_n)=0$ 即 $\forall\delta>0,\exists N,\forall n>N\Rightarrow\rho(\Gamma_n)<\delta$

则有 $\forall\epsilon,\exists N,\forall n>N\Rightarrow\left|\int_{D_n}f(\vec{x})d\vec{x}-\int_{D}f(\vec{x})d\vec{x}\right|<\epsilon$ 

即 $\lim_{n\to\infty}\int_{D_n}f(\vec{x})d\vec{x}=\int_{D}f(\vec{x})d\vec{x}$

****** 必要性

已知 $\lim_{n\to\infty}\int_{D_n}f(\vec{x})d\vec{x}=I$ 即 $\forall\epsilon>0,\exists N,\forall n>N\Rightarrow\left|\int_{D_n}f(\vec{x})d\vec{x}-I\right|<\epsilon$ 

由于条件（2），故可得 $\lim_{n\to\infty}\rho(\Gamma_n)=0$ 

若曲面 $\Gamma$ 满足 $\rho(\Gamma)<\rho(\Gamma_{N+1})$ 且 $\forall \vec{x}\in S\Rightarrow \vec{x}\not\in D_\Gamma$

则必有 $d(\Gamma)>0$ 由于 $\lim_{n\to\infty}\rho(\Gamma_n)=0$ 故必有 $\exists N,\forall m>N\Rightarrow \rho(\Gamma_m)<d(\Gamma)$

由于 $f(\vec{x})>0$ 故有 $\int_{D_n}f(\vec{x})d\vec{x}>0,\int_{D_\Gamma}f(\vec{x})d\vec{x}>0,I>0$ 且有 $\int_{D_m}f(\vec{x})d\vec{x}\geq\int_{D_n}f(\vec{x})d\vec{x},\forall m>n$

故有 $I\geq\int_{D_m}f(\vec{x})d\vec{x}\geq\int_{D_\Gamma}f(\vec{x})d\vec{x}\geq\int_{D_n}f(\vec{x})d\vec{x}\geq0$

则有 $0\leq I-\int_{D_\Gamma}f(\vec{x})d\vec{x}\leq I-\int_{D_n}f(\vec{x})d\vec{x}$

即 $\forall\epsilon>0,\exists\delta=\rho(\Gamma_{N+1}),\forall\rho(\Gamma)<\delta\Rightarrow \left|I-\int_{D_\Gamma}f(\vec{x})d\vec{x}\right|<\epsilon$ 

即 $\lim_{\rho(\Gamma)\to0}\int_{D_\Gamma}f(\vec{x})d\vec{x}=I$

*** 累次反常积分线性

若累次反常积分 $\int_{a_1}^{b_1}...\int_{a_n}^{b_n} f(\vec{x})dx_n...dx_1,\int_{a_1}^{b_1}...\int_{a_n}^{b_n} g(\vec{x})dx_ndx_{n-1}...dx_1$ 收敛

则有 $\int_{a_1}^{b_1}...\int_{a_n}^{b_n} Af(\vec{x})+Bg(\vec{x})dx_n...dx_1=A\int_{a_1}^{b_1}...\int_{a_n}^{b_n} f(\vec{x})dx_n...dx_1+B\int_{a_1}^{b_1}...\int_{a_n}^{b_n} g(\vec{x})dx_n...dx_1$

**** 证明

同[[MK47][区间无限证明]]

*** 无界反常重积分计算

定义区域 $D=[a_1,b_1)\times[a_2,b_2)\times...\times[a_n,b_n)$ 其中 $S$ 为奇点集合，即边界 $\vec{b}$ 上的点

函数 $f(\vec{x})$ 在 $\vec{x}\in D,\vec{x}\ne S$ 上有定义，若：

（1） 函数 $f(\vec{x})$ 在 $D$ 上连续

（2） 累次反常积分 $\int_{a_1}^{b_1}...\int_{a_1}^{b_1}f(\vec{x})dx_1...dx_n,\int_{a_1}^{b_1}...\int_{a_1}^{b_1}|f(\vec{x})|dx_1...dx_n$ 均收敛

则有 $\int_D f(\vec{x})d\vec{x}=\int_{a_1}^{b_1}...\int_{a_1}^{b_1}f(\vec{x})dx_1...dx_n$ 即反常重积分等于累次反常积分

**** 证明

同[[MK46][区间无限反常积分]]证明

** （未完成）混合区域积分

*** 定义

定义区域 $D$ 为无界区域，且其中 $S$ 为奇点集合

函数 $f(\vec{x})$ 在 $\vec{x}\in D,x\not\in S$ 上有定义

定义一组区域 $D_k$ 满足 $D_k\subset D_{k+1}$ 且 $\lim_{k\to\infty}D_k=D$ 并由 $D_k\cap S=\varnothing$

若 $\lim_{k\to\infty}\int_{D_k}f(\vec{x})$



*** 性质及计算

由于两类积分性质，证明方法相同，故混合区域积分具有同样性质





