#+LATEX_CLASS: ctexart

#+TITLE: 函数项级数

* 函数项级数

** 定义：

\begin{aligned}
S(x)=\sum_{i=1}^\infty u_i(x),\ \ x\in D
\end{aligned}

其中：

$u_i(x)$ 为关于 $x$ 的函数。

\begin{aligned}
S_n(x)=\sum_{i=1}^n u_i(x)
\end{aligned}

为函数项级数的部分和。

** 函数项级数一致收敛：

*** 定义：

\begin{aligned}
\forall \epsilon>0,\ \ \exists N,\ \ \forall n>N,\ \ \forall x \in D\Rightarrow |S_n(x)-S(x)| <\epsilon
\end{aligned}

*** 推论：

**** 推论1：

若 $\sum_{i=1}^\infty u_i(x)$ 一致收敛，则 $u_i(x)$ 一致收敛于0。

***** 证明

\begin{aligned}
&\because \forall \epsilon>0,\ \ \exists N,\ \ \forall n>N,\ \ \forall x \in D\Rightarrow |S_n(x)-S(x)| <\frac{\epsilon}{2}\\
&\therefroe |u_n(x)|=|S_{n+1}(x)-S_n(x)|\leq |S_{n+1}(x)-S(x)|+|S(x)-S_n(x)|<\epsilon\\
\end{aligned}

**** 推论2：

定义 $d_n=sup\{|S_n(x)-S(x)|\},\ x\in D$ ，若函数项级数点态收敛于 $S(x)$ ，则一直收敛的充要条件为 $\lim_{n \to \infty}d_n=0$

***** 证明必要性：

\begin{aligned}
&\because \forall \epsilon>0,\ \ \exists N,\ \ \forall n>N,\ \ \forall x \in D\Rightarrow |S_n(x)-S(x)| <\epsilon\\
&\therefore sup\{|S_n(x)-S(x)|\} <\epsilon,\ x\in D\\
\end{aligned}

***** 证明充分性：

\begin{aligned}
&\forall \epsilon>0,\ \ \exists N,\ \ \forall n>N,\ \ \forall x \in D
\Rightarrow |S_n(x)-S(x)|\leq d_n=sup\{|S_n(x)-S(x)|\} <\epsilon\\
\end{aligned}

**** 推论3：

若函数项级数点态收敛于 $S(x)$ ，则一致收敛的充要条件是对于任意数列 $x_n \in D$ 有 $\lim_{n\to\infty} |S_n(x_n)-S(x_n)|=0$

***** 证明必要性：

因为一致收敛，则有推论2，故：

\begin{aligned}
&\forall \epsilon>0,\ \ \exists N,\ \ \forall n>N,\ \ \forall x \in D
\Rightarrow |S_n(x_n)-S(x_n)|\leq d_n=sup\{|S_n(x)-S(x)|\} <\epsilon\\
\end{aligned}

***** 证明充分性：

证明若函数项级数非一致收敛，则一定可以找到一列 $x_n \in D$ 有 $\lim_{n\to\infty} |S_n(x_n)-S(x_n)|\neq 0$ ：

根据一致收敛条件得出非一致收敛：

\begin{aligned}
&\exists \epsilon>0,\ \ \forall N,\ \ \exists n>N,\ \ \exists x \in D\Rightarrow |S_n(x)-S(x)| > \epsilon\\
\end{aligned}

则当 $N=1$ 时，存在 $n_1,\ x_{n_1}\Rightarrow |S_{n_1}(x_{n_1})-S(x_{n_1})|> \epsilon$

则当 $N=n_1$ 时，存在 $n_2,\ x_{n_2}\Rightarrow |S_{n_2}(x_{n_2})-S(x_{n_2})|> \epsilon$

...

则当 $N=n_k$ 时，存在 $n_{k+1},\ x_{n_{k+1}}\Rightarrow |S_{n_{k+1}}(x_{n_{k+1}})-S(x_{n_{k+1}})|> \epsilon$

故取数列 $x_m$ 满足如下：

\begin{aligned}
x_m=\begin{cases}
x_{n_i} &,m=n_i\\
a&,m\neq n_i,a\in D
\end{cases}
\end{aligned}

则有如下表述：

\begin{aligned}
&\forall N,\ \ \exists n_i>N,\ \ \exists x_{n_i} \in D\Rightarrow |S_{n_i}(x_{n_i})-S(x_{n_i})| > \epsilon 
\Rightarrow \lim_{n\to\infty} |S_n(x_n)-S(x_n)|\neq 0\\
\end{aligned}

*** 判别：

**** 柯西收敛原理：

***** 描述：

函数项级数 $\sum_{n=1}^\infty u_n(x)$ 一致收敛的充要条件是:

\begin{aligned}
&\forall \epsilon >0,\exists N,\forall m>n>N,\forall x \in D \Rightarrow \left|\sum_{i=n+1}^m u_i(x)\right|=\left|S_m(x)-S_n(x)\right|<\epsilon\\
\end{aligned}

***** 证明：

****** 充分性

\begin{aligned}
&\because \forall \epsilon>0,\ \ \exists N,\ \ \forall m>n>N,\ \ \forall x \in D\Rightarrow |S_n(x)-S(x)| <\frac{\epsilon}{2},|S_m(x)-S(x)| <\frac{\epsilon}{2}\\
&\therefore |S_m(x) - S_n(x)| = |S_m(x)-S(x) + S(x)-S_n(x)| \leq |S_m(x)-S(x)| + |S(x)-S_n(x)|<\epsilon
\end{aligned}

****** 必要性

对于任意 $x_0$ ，根据数项级数收敛原理，$\lim_{n\to\infty}\sum_{i=1}^n u_i(x_0)$ 收敛，假设收敛于 $S(x)=\lim_{n\to\infty}\sum_{i=1}^n u_i(x)$ 则

\begin{aligned}
&\forall \epsilon >0,\exists N,\forall m>n>N,\forall x \in D \Rightarrow \left|\sum_{i=n+1}^m u_i(x)\right|=
\left|S_n(x)-S_m(x)\right|<\frac{\epsilon}{2}\\
&\lim_{m\to\infty}\left|S_n(x)-S_m(x)\right|=\left|S_n(x)-S(x)\right|\leq \frac{\epsilon}{2} <\epsilon\\
\end{aligned}

**** Weierstrass判别：

***** 描述：

若 $\forall x\in D,|u_n(x)|\leq a_n$ ，且 $\sum_{n=1}^\infty a_n$ 收敛，则 $\sum_{n=1}^\infty u_n(x)$ 一致收敛。

***** 证明：

根据数项级数柯西收敛原理：

\begin{aligned}
&\forall \epsilon>0,\ \ \exists N,\ \ \forall m>n>N\Rightarrow \left|\sum_{i=n+1}^m a_i\right|<\epsilon\\
&\therefore \left|\sum_{i=n+1}^m u_i(x)\right|  \leq \sum_{i=n+1}^m |u_i(x)| \leq \left|\sum_{i=n+1}^m a_i\right|<\epsilon\\
\end{aligned}

根据函数项级数柯西收敛原理，级数收敛。

**** A-D判别：

***** Abel:

****** 描述：

若函数项级数满足 $a_n(x)$ 对于任何 $x\in D$ 单调有界 $a_n(x)<K$ ，$\sum_{i=1}^\infty b_i(x)$ 一致收敛，则 $\sum_{i=1}^\infty a_i(x)b_i(x)$ 一致收敛。

****** 证明：

根据Abel引理：

\begin{aligned}
&\forall \epsilon>0,\exists N,\forall m>n>N,\forall x\in D \Rightarrow |B_k(x)|=\left|\sum_{i=n}^k b_i(x)\right| < \epsilon\\
& |a_i(x)| \leq K\\
& \left| \sum_n^m a_i(x) b_i(x) \right| \leq \epsilon (|a_n(x)|+2|a_m(x)|) \leq 3K\epsilon\\
\end{aligned}

***** Dirichlet:

****** 描述:

若函数项级数满足 $a_n(x)$ 对于任何 $x\in D$ 一致单调趋于0，$\sum_{i=1}^n b_i(x)$ 对于任何 $x\in D$ 有界 $|\sum_{i=1}^n b_i(x)|<K$ ，则 $\sum_{i=1}^\infty a_i(x)b_i(x)$ 一致收敛。

****** 证明：

\begin{aligned}
&\lim_{n\to\infty}a_n(x)=0\Rightarrow\forall \epsilon>0,\Exists N,\forall n>N,\forall x\in D\Rightarrow |a_n(x)|<\epsilon\\
&\because |B_n(x)|<K\\
&\therefore \left|\sum_n^m b_i(x)\right|=|B_m(x)-B_n(x)| \leq |B_m(x)| + |B_n(x)| \leq 2K\\
&\therefore \forall m>n>N \Rightarrow \left| \sum_n^m a_i(x) b_i(x) \right| \leq 2K(|a_n(x)|+2|a_m(x)|) < 6K\epsilon
\end{aligned}

** 一致收敛性质：

*** 连续性：

**** 描述：

若函数项级数一致收敛，且部分和 $S_n(x)$ 连续，则 $\lim_{x\to x_0}S(x)=S(x_0),x_0\in D$

**** 证明：

设由 $S_n(x)$ 连续性得：

\begin{aligned}
&\forall \epsilon>0,\exists h>0,\forall x\in D\ \&\ |x-x_0|<h\Rightarrow|S_n(x)-S_n(x_0)|<\frac{\epsilon}{3}\\ 
\end{aligned}

由函数项级数一致收敛得：

\begin{aligned}
&\forall \epsilon>0,\exists N,\forall n>N,\forall x \in D\Rightarrow |S_n(x)-S(x)|<\frac{\epsilon}{3}\\
\therefore& |S_n(x_0)-S(x_0)|<\frac{\epsilon}{3},|S_n(x)-S(x)|<\frac{\epsilon}{3}\\
\therefore& |x-x_0|<h\\ 
&|S(x)-S(x_0)|=|S(x)-S_n(x)+S_n(x)-S_n(x_0)+S_n(x_0)-S(x_0)|\\
&\leq |S(x)-S_n(x)|+|S_n(x)-S_n(x_0)|+|S_n(x_0)-S(x_0)|<\epsilon\\
\end{aligned}

**** 推论：

\begin{aligned}
&\lim_{x\to x_0}\sum_{i=1}^\infty u_i(x)=\lim_{x\to x_0}S(x)=S(x_0)=\sum_{i=1}^\infty u_i(x_0)=\sum_{i=1}^\infty \lim_{x\to x_0}u_i(x)\\
\end{aligned}

*** 可积性：

**** 描述：

若函数项级数一致收敛，且部分和 $S_n(x)$ 连续，则 $\int_a^b S(x) dx=\lim_{n\to\infty}\int_a^b S_n(x) dx$ ，且 $\int_a^x S_n(r) dr$ 一致收敛于 $\int_a^x S_n(r) dr$ 。

**** 证明：

\begin{aligned}
\because &\forall \epsilon>0,\exists N,\forall n>N,\forall x \in D\Rightarrow |S_n(x)-S(x)| <\epsilon\\
\therefore & \left|\int_a^b S_n(x) dx-\int_a^b S(x) dx\right|=\left|\int_a^b S_n(x) - S(x) dx\right|\\
&\leq \int_a^b |S_n(x) - S(x)| dx < \int_a^b \epsilon dx=\epsilon(b-a)
\end{aligned}

同理：

\begin{aligned}
\because &\forall \epsilon>0,\exists N,\forall n>N,\forall x \in D\Rightarrow |S_n(x)-S(x)| <\epsilon\\
\therefore & \left|\int_a^x S_n(r) dr-\int_a^x S(r) dr\right|=\left|\int_a^x S_n(r) - S(r) dr\right|\\
&\leq \int_a^x |S_n(r) - S(r)| dr < \int_a^x \epsilon dr=\epsilon(x-a) \leq \epsilon(b-a)
\end{aligned}

**** 推论：

\begin{aligned}
&\int_a^b \sum_{i=1}^\infty u_i(x) dx
= \int_a^b S(x) dx=\lim_{n\to\infty}\int_a^b S_n(x) dx=\lim_{n\to\infty}\int_a^b \sum_{i=1}^n u_i(x) dx
=\lim_{n\to\infty} \sum_{i=1}^n \int_a^b u_i(x) dx = \sum_{i=1}^\infty \int_a^b u_i(x) dx\\
&\int_a^x \sum_{i=1}^\infty u_i(r) dr=\sum_{i=1}^\infty \int_a^x u_i(r) dr
\end{aligned}

*** 可导性：

**** 描述：

若函数满足以下条件：

（1） $S_n(x)$ 有连续导数 $S_n'(x)$ ；
（2） $S_n(x)$ 点态收敛于 $S(x)$ ；
（3） $S_n'(x)$ 一致收敛于 $\sigma(x)$

则有 $S'(x)=\sigma(x)$ ，且 $S_n(x)$ 一致收敛于 $S(x)$

**** 证明：

根据条件（3）及函数项级数可积性得：

\begin{aligned}
\int_a^x \sigma(r) dr &= \lim_{n\to\infty} \int_a^x S_n'(r) dr\\
&=\lim_{n\to\infty} S_n(x) - S_n(a)\\
\end{aligned}

根据条件（2）点态收敛，则

\begin{aligned}
&\lim_{n\to\infty} S_n(x) - S_n(a) = S(x)-S(a)\\
\therefore & \int_a^x \sigma(r) dr = S(x)-S(a)\\
\therefore & \sigma(x)=S'(x)\\
\end{aligned}

又根据可积性，$\int_a^x S_n'(r) dr=S(x)-S(a)$ 一直收敛于 $\int_a^x \sigma(r) dr=\int_a^x S'(r) dr=S(x)-S(a)$ ，故得一致收敛性。 

**** 推论：

\begin{aligned}
&\frac{d}{dx} \left\{\lim_{n\to\infty} \sum_{i=1}^n u_i(x)\right\} = 
\frac{d}{dx}S(x)=\sigma(x)=\lim_{n\to\infty} \left\{\frac{d}{dx} S_n(x)\right\}=
\lim_{n\to\infty} \left\{ \frac{d}{dx} \left\{\sum_{i=1}^n u_i(x)\right\}\right\}
=\lim_{n\to\infty} \left\{\sum_{i=1}^n  \frac{d}{dx} u_i(x)\right\}\\
&\frac{d}{dx} \left\{\sum_{i=1}^\infty u_i(x)\right\} = \sum_{i=1}^\infty  \left\{\frac{d}{dx} u_i(x)\right\}\\
\end{aligned}

*** Dini定理：

**** 描述：

若函数项级数（部分和： $S_n(x)$ ）在有界闭区间 $D=[a,b]$ 中满足以下条件：

（1） $S_n(x)$ 点态收敛于 $S(x)$ ；
（2） $S(x)$ 和 $S_n(x)$ 于 $x\in D$ 上连续；
（3） 对于固定 $x$ ，有 $S_n(x)$ 关于 $n$ 单调；

则有 $S_n(x)$ 一致收敛于 $S(x),\ x\in D$ ；

**** 证明（反证）：

***** 假设非一致收敛：

根据一致收敛条件得出非一致收敛：

\begin{aligned}
&\exists \epsilon>0,\ \ \forall N,\ \ \exists n>N,\ \ \exists x \in D\Rightarrow |S_n(x)-S(x)| > \epsilon\\
\end{aligned}

则当 $N=1$ 时，存在 $n_1,\ x_{n_1}\Rightarrow |S_{n_1}(x_{n_1})-S(x_{n_1})|> \epsilon$

则当 $N=n_1$ 时，存在 $n_2,\ x_{n_2}\Rightarrow |S_{n_2}(x_{n_2})-S(x_{n_2})|> \epsilon$

...

则当 $N=n_k$ 时，存在 $n_{k+1},\ x_{n_{k+1}}\Rightarrow |S_{n_{k+1}}(x_{n_{k+1}})-S(x_{n_{k+1}})|> \epsilon$

***** 由于 $D=[a,b]$ 为有界闭区间，根据定理：有界数列必有收敛子列：

假设 $\{x_{n_i}\}\in\{x_{n_k}\}$ 是收敛于某数值 $\xi\in D$ 的子列，则有 $\lim_{i\to\infty} |x_{n_i}-\xi|=0$

根据函数项级数点态收敛，又有 $\lim_{n\to\infty} |S_n(\xi)-S(\xi)|=0$ ，分析表述 $\forall \epsilon>0,\exists N-1,\forall n>N-1\Rightarrow |S_n(\xi)-S(\xi)|<\frac{\epsilon}{2}$

又根据函数的连续性，当 $n=N$ 时，不仅满足 $|S_N(\xi)-S(\xi)|<\frac{\epsilon}{2}$ 另还有 $\lim_{i\to\infty} |S_N(x_{n_i})-S(x_{n_i})|=|S_N(\xi)-S(\xi)|$ ，

（接上）分析表述  $\forall \epsilon>0,\exists I,\forall i>I\Rightarrow |[S_N(x_{n_i})-S(x_{n_i})]-[S_N(\xi)-S(\xi)]|<\frac{\epsilon}{2}$

则综合上述条件，设 $I'=\min\{i|i>I\ \&\ n_i>N\}$ 有：

\begin{aligned}
& \forall \epsilon >0, \exists I',\forall i>I'\Rightarrow |S_N(\xi)-S(\xi)|<\frac{\epsilon}{2}, |[S_N(x_{n_i})-S(x_{n_i})]-[S_N(\xi)-S(\xi)]|<\frac{\epsilon}{2}\\
\therefore & |S_N(x_i)-S(x_i)|-|S_N(\xi)-S(\xi)|\leq |[S_N(x_{n_i})-S(x_{n_i})]-[S_N(\xi)-S(\xi)]|<\frac{\epsilon}{2}\\
\therefore & |S_N(x_{n_i})-S(x_{n_i})|-|S_N(\xi)-S(\xi)|<\frac{\epsilon}{2}\\
\therefore & |S_N(x_{n_i})-S(x_{n_i})|<|S_N(\xi)-S(\xi)|+\frac{\epsilon}{2}\\
\because & |S_N(\xi)-S(\xi)|<\frac{\epsilon}{2}\\
\therefore & |S_N(x_{n_i})-S(x_{n_i})|<\epsilon\\
\end{aligned}

***** 由于函数的单调性+点态收敛：

\begin{aligned}
&|S_n(x) - S(x)| \leq |S_N(x) - S(x)|,\ \ n>N\\
\because   & i>I'=\min\{i|i>I\ \&\ n_i>N\}\\
\therefore & n_i>N\\
\therefore & |S_{n_i}(x_{n_i}) - S(x_{n_i})| \leq |S_N(x_{n_i})-S(x_{n_i})|<\epsilon\\
\because   & \{x_{n_i}\}\in\{x_{n_k}\}\\
\therefore & |S_{n_i}(x_{n_i})-S(x_{n_i})|> \epsilon
\end{aligned}

故推出矛盾。

** 函数项级数表示函数：处处连续，处处不可导

*** Van Der Waerden 函数

**** 表述：

\begin{aligned}
&f(x)=\sum_{n=0}^\infty \frac{\phi(10^nx)}{10^n}\\
\end{aligned}

式中:

\begin{aligned}
&x\in R\\
&\phi(x)=\begin{cases}
0.5,&x-[x]=0.5\\
x-[x],&x-[x]<0.5\\
[x]+1-x,&x-[x]>0.5\\
\end{cases}
\end{aligned}

其中 $[x]$ 为对 $x$ 向下取整。

****  $\phi(x)$ 部分性质：

\begin{aligned}
&0\leq\phi(x)\leq0.5\\
&\phi(x)=\phi(x+1)\\
&\forall x,y \in \{x,y|x,y\in R,[x]=[y]=k\in N\}\\
&\Rightarrow \phi(x)-\phi(y)=\begin{cases}
x-y,&x,y\in [k,k+0.5]\\
y-x,&x,y\in [k+0.5,k+1]\\
\end{cases}
\end{aligned}

**** 证明连续：

\begin{aligned}
\because   &0\leq\phi(x)\leq0.5\\
\therefore &\left|\frac{\phi(10^nx)}{10^n}\right| \leq \frac{1}{2*10^n}\\
\end{aligned}

由于 $\sum_{n=1}^\infty\frac{1}{2*10^n}$ 收敛，根据Weierstrass判别法， $f(x)=\sum_{n=0}^\infty \frac{\phi(10^nx)}{10^n}$ 一致收敛。

又由于 $\frac{\phi(10^nx)}{10^n}$ 连续，结合一致收敛得出 $f(x)$ 连续。

**** 证明不可导：

设 $x$ 可有以下表述：

\begin{aligned}
x=K+\sum_{n=1}^\infty 10^{-n}a_n\\
\end{aligned}

其中：

\begin{aligned}
&K\in N\\
&a_n\in \{0,1,2,3,4,5,6,7,8,9\}\\
\end{aligned}

取 $h_m=\begin{cases} 10^{-m},&a_m \in \{0,1,2,3,5,6,7,8\}\\-10^{-m},&a_m \in \{5,9\} \end{cases}$ 则有 $\lim_{m\to \infty} h_m=0$

则利用 $h_m$ 的性质写出导数定义:

\begin{aligned}
&\lim_{m\to\infty} \frac{f(x+h_m)-f(x)}{h_m}\\
=&\lim_{m\to\infty} \sum_{n=0}^\infty \frac{\phi(10^nx+10^nh_m)-\phi(10^nx)}{h_m10^n}\\
=&\lim_{m\to\infty} \sum_{n=0}^{m-1} \frac{\phi(10^nx+10^nh_m)-\phi(10^nx)}{h_m10^n} + \lim_{m\to\infty} \sum_{n=m}^\infty \frac{\phi(10^nx+10^nh_m)-\phi(10^nx)}{h_m10^n}\\
\end{aligned}

注：这里没有改变求导与 $n\to\infty$ 的顺序，仅加法结合。求导的实质为 $m\to\infty$ ，操作仍然在 $n\to\infty$ 之后。

对于无限项中分母差值 $\phi(10^nx+10^nh_m)-\phi(10^nx)$ 中函数代入项的差为 $(10^nx+10^nh_m)-(10^nx)=10^nh_m$ ，其中 $n>m\Rightarrow10^nh_m\in N$ 故两代入数差为整数，又由于 $\phi(x)$ 周期为1，则有 $\phi(10^nx+10^nh_m)-\phi(10^nx)=0$ ，更有 $\lim_{m\to\infty} \sum_{n=m}^\infty \frac{\phi(10^nx+10^nh_m)-\phi(10^nx)}{h_m10^n}=0$ ，故得：

\begin{aligned}
&\lim_{m\to\infty} \frac{f(x+h_m)-f(x)}{h_m}\\
=&\lim_{m\to\infty} \sum_{n=0}^{m-1} \frac{\phi(10^nx+10^nh_m)-\phi(10^nx)}{h_m10^n}\\
\end{aligned}

由于 $h_m$ 的性质，对于 $n<m$ 的情况： 

若 $a_m<5\Rightarrow a_m+10^mh_m<5$ ，反之亦然 $5\leq a_m\leq9\Rightarrow 5\leq a_m+10^mh_m\leq 9$ ；

则有 $\phi(10^nx+10^nh_m)-\phi(10^nx)=10^n(\pm h_m)=10^{n-m} (\pm 1)$ ；

则 $\frac{\phi(10^nx+10^nh_m)-\phi(10^nx)}{h_m10^n}=\frac{10^n(\pm h_m)}{h_m10^n}=(\pm 1)$ ；

故原式：

\begin{aligned}
&\lim_{m\to\infty} \frac{f(x+h_m)-f(x)}{h_m}\\
=&\lim_{m\to\infty} \sum_{n=0}^{m-1} \frac{\phi(10^nx+10^nh_m)-\phi(10^nx)}{h_m10^n}\\
=&\lim_{m\to\infty} \sum_{n=0}^{m-1} (\pm 1)\\
\end{aligned}

加和数列为摇摆数列或无限大，极限不收敛。故不可导。

* 幂级数

** 定义：

函数项级数表述为 $\sum_{n=1}^\infty a_n x^n$ ，是形式特殊的函数项级数

** 收敛半径:

*** 定义：

定义收敛半径 $R$ 当幂级数 $\sum_{n=1}^\infty a_n x^n < R$ 时，幂级数绝对收敛；当 $\sum_{n=1}^\infty a_n x^n > R$ 幂级数非绝对收敛。 

*** 幂级数收敛半径判别：

**** [[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][柯西判别]]：


判别下式：

\begin{aligned}
r=\overline{\lim_{n\to\infty}} \sqrt[n]{\left|a_n x^n\right|}=\overline{\lim_{n\to\infty}} \sqrt[n]{\left|a_n\right|}\cdot |x|
\end{aligned}

若：

$r<1$ 收敛；

$r>1$ 发散；

$r=1$ 不能判断。

故收敛半径:

\begin{aligned}
R=\frac{1}{\overline{\lim_{n\to\infty}} \sqrt[n]{\left|a_n\right|}}
\end{aligned}

注：判别式本身判断绝对收敛，如果绝对收敛，级数也收敛。

**** [[e:/OneDrive/数学分析/Note/Chapter 9/Chap9Note.org][达朗贝尔]]：

判别下式：

\begin{aligned}
r=\lim_{n\to\infty}\left| \frac{a_{n+1} x^{n+1}}{a_n x^n} \right|=\lim_{n\to\infty}\left| \frac{a_{n+1}}{a_n} \right| |x|
\end{aligned}

收敛半径：

\begin{aligned}
R=\frac{1}{\lim_{n\to\infty}\left| \frac{a_{n+1}}{a_n}\right|}
\end{aligned}

** Abel第二定理：

*** 描述：

设幂级数 $\sum_{n=1}^\infty a_nx^n$ 其收敛半径为 $R$ ，则有：

（1）幂级数在 $(-R,R)$ 上内闭一致收敛；

（2）若幂级数在 $x=R$ 上收敛，则幂级数在任意闭区间 $[a,R]\in(-R,R]$ 一致收敛。

*** 证明：

\begin{aligned}
\because & \sum_{n=1}^\infty a_n x^n < \infty,\ \ x\in (-R,R)\\
\therefore & \sum_{n=1}^\infty a_n x^n < \infty,\ \ x\in [-R+\delta,R-\delta],\ \ \delta>0\\
\because &  |x^n| \leq max\{|-R+\delta|,|R-\delta|\}^n=L^n\\
\therefore & |a_n x^n| \leq |a_n|L^n\\
\end{aligned}

根据Weierstrass判别，幂级数在 $[-R+\delta,R-\delta]$ 上一致收敛

\begin{aligned}
\because & \sum_{n=1}^\infty a_n x^n < \infty,\ \ x\in (-R,R)\\
\therefore & \sum_{n=1}^\infty a_n x^n < \infty,\ \ x\in [-R+\delta,R],\ \ \delta>0\\
\because &  |x^n| \leq max\{|-R+\delta|,|R|\}^n=L^n\\
\therefore & |a_n x^n| \leq |a_n|L^n\\
\end{aligned}

根据Weierstrass判别，幂级数在 $[-R+\delta,R]$ 上一致收敛，同理可证 $-R$ 收敛。

** 幂级数一致收敛性质：

*** 连续性：

若 $[a,b]\in D$ ，$D$ 为幂级数收敛域 ，则 $\lim_{x\to x_0}\sum_{n=1}^\infty a_n x^n=\sum_{n=1}^\infty \lim_{x\to x_0} a_n x^n,\ \ x_0\in[a,b]$

*** 可积性：

若 $[a,b]\in D$ ，$D$ 为幂级数收敛域 ，则 $\int_a^b \sum_{n=1}^\infty a_n x^n dx=\sum_{n=1}^\infty \int_a^b a_n x^n dx$ 

另让 $a=0,b=x,x\in(-R,R)$ 则有 $\int_0^x \sum_{n=1}^\infty a_n r^n dr=\sum_{n=1}^\infty \int_0^x a_n r^n dr = \sum_{n=1}^\infty \frac{a_n}{n+1} x^{n+1}$ 

且收敛半径为 $\overline{\lim_{n\to\infty}} \sqrt[n+1]{\frac{|a_n|}{n+1}}=\overline{\lim_{n\to\infty}} \sqrt[n]{|a_n|}$ ，与原函数相同。

*** 可导性：

幂级数 $\sum_{n=0}^\infty a_n x^n$ 逐项求导得 $\sum_{n=1}^\infty na_n x^{n-1}=\sum_{n=0}^\infty (n+1)a_{n+1} x^{n}$ 仍然为幂级数

收敛半径 $\overline{\lim_{n\to\infty}} \sqrt[n]{(n+1)|a_{n+1}|}}=\overline{\lim_{n\to\infty}} \sqrt[n]{|a_n|}$ ，故逐项求导结果一致收敛，且两函数项级数连续。

得出幂级数可逐项求导。 

** 幂级数展开：

*** 补充1：柯西中值定理

**** 描述：

若 $f(x),g(x)$ 在 $[a,b]$ 连续 $(a,b)$ 可导，且 $g(a)-g(b) \ne 0, g'(\xi) \ne 0$ ，则

\begin{aligned}
\frac{f(a)-f(b)}{g(a)-g(b)}=\frac{f'(\xi)}{g'(\xi)}
\end{aligned}

其中 $\xi \in (a,b)$

**** 证明：

根据[[e:/OneDrive/大学物理/Note/DiffEq.org][导数基本知识-拉格朗日中值定理]]，给定描述中的条件：

\begin{aligned}
&F(x)=[f(b)-f(a)][g(x)-g(a)]-[g(b)-g(a)][f(x)-f(a)]\\
\therefore &F(a)=F(b)=0\\
\therefore &\exists \xi\in (a,b)\Rightarrow F'(\xi)=0\\
\because & F'(x)=[f(b)-f(a)]g'(x)-[g(b)-g(a)]f'(x)\\
\therefore & F'(\xi)=[f(b)-f(a)]g'(\xi)-[g(b)-g(a)]f'(\xi)=0\Rightarrow \frac{f(a)-f(b)}{g(a)-g(b)}=\frac{f'(\xi)}{g'(\xi)}\\
\end{aligned}

*** 补充2：Taylor公式

**** 带Peano余项：

***** 描述：

设函数 $f(x)$ 在 $x=x_0$ 处 $n$ 介可导，则：

\begin{aligned}
f(x)=\sum_{i=0}^n \frac{f^{(i)}(x_0)}{i!}(x-x_0)^i+o\left((x-x_0)^n\right)
\end{aligned}

其中：

$f^{(i)}(x_0)$ 为 $f(x)$ 的 $i$ 介导数在 $x_0$ 的值

$o\left((x-x_0)^n\right)$ 为关于 $(x-x_0)^n$ 的高阶无穷小量

***** 证明：

定义如下函数：

\begin{aligned}
&P_n(x)=\sum_{i=0}^n \frac{f^{(i)}(x_0)}{i!}(x-x_0)^i\\
&R_n(x)=f(x)-P_n(x)
\end{aligned}

对余项函数 $R_n(x)$ 分次求导并带入 $x_0$ 得：

\begin{aligned}
&R_n^{(1)}(x_0)=\left\{f^{(1)}(x)-\sum_{i=1}^n \frac{f^{(i)}(x_0)}{(i-1)!}(x-x_0)^{i-1}\right\}\bigg|_{x=x_0}=0\\
&R_n^{(2)}(x_0)=\left\{f^{(2)}(x)-\sum_{i=2}^n \frac{f^{(i)}(x_0)}{(i-2)!}(x-x_0)^{i-2}\right\}\bigg|_{x=x_0}=0\\
&...\\
&R_n^{(n-1)}(x_0)=\left\{f^{(n-1)}(x)-\sum_{i=n-1}^n \frac{f^{(i)}(x_0)}{(i-n+1)!}(x-x_0)^{i-n+1}\right\}\bigg|_{x=x_0}\\
&=\left\{f^{(n-1)}(x)-f^{(n-1)}(x_0)-f^{(n)}(x_0)(x-x_0)\right\}\bigg|_{x=x_0}=0\\
\end{aligned}

故根据洛必达法则：

\begin{aligned}
&\lim_{x\to x_0}\frac{R_n(x)}{(x-x_0)^n}=\lim_{x\to x_0}\frac{R_n^{(1)}(x)}{n(x-x_0)^{n-1}}
=\lim_{x\to x_0}\frac{R_n^{(2)}(x)}{n(n-1)(x-x_0)^{n-2}} =... = \lim_{x\to x_0}\frac{R_n^{(n-1)}(x)}{n!(x-x_0)}\\
&=\lim_{x\to x_0}\frac{f^{(n-1)}(x)-f^{(n-1)}(x_0)-f^{(n)}(x_0)(x-x_0)}{n!(x-x_0)}\\
&=\frac{1}{n!}\left(\lim_{x\to x_0}\frac{f^{(n-1)}(x)-f^{(n-1)}(x_0)}{(x-x_0)}-f^{(n)}(x_0)\right)=0\\
\end{aligned}

根据导数的定义。

故 $R_n=o\left((x-x_0)^n\right)$ ，定理证毕。

**** 带拉格朗日余项：

***** 描述：

若函数 $f(x)$ 在 $[a,b]$ 上连续 $(a,b)$ 上 $n+1$ 介可导，且 $x,x_0\in (a,b)$ 则：

\begin{aligned}
f(x)=\sum_{i=0}^n \frac{f^{(i)}(x_0)}{i!}(x-x_0)^i+R_n(x)
\end{aligned}

其中：

\begin{aligned}
R_n(x)=\frac{f^{(n+1)}(\xi)}{(n+1)!}(x-x_0)^{n+1},\ \ \xi\in [x,x_0]
\end{aligned}

***** 证明：

\begin{aligned}
&G(t)=f(x)-\sum_{i=0}^n \frac{f^{(i)}(t)}{i!}(x-t)^i\\
&H(t)=(x-t)^{n+1}\\
\therefore & G(x)=f(x)-\sum_{i=0}^n \frac{f^{(i)}(t)}{i!}(x-x)^i=0\\
\therefore & H(x)=0\\
\therefore & G(x_0)=f(x)-\sum_{i=0}^n \frac{f^{(i)}(t)}{i!}(x-x_0)^i=R_n(x)\\
\therefore & H(x_0)=(x-x_0)^{n+1}\\
\therefore & \frac{G(x_0)}{H(x_0)}=\frac{G(x_0)-G(x)}{H(x_0)-H(x)}=\frac{G'(\xi)}{H'(\xi)},\xi\in (x,x_0)\\
\because & G'(t)=-\sum_{i=0}^n \frac{f^{(i+1)}(t)}{i!}(x-t)^i+\sum_{i=1}^n \frac{f^{(i)}(t)}{(i-1)!}(x-t)^{i-1}\\
&=-\sum_{i=1}^{n+1} \frac{f^{(i)}(t)}{(i-1)!}(x-t)^{i-1}+\sum_{i=1}^n \frac{f^{(i)}(t)}{(i-1)!}(x-t)^{i-1}\\
&=-\frac{f^{(n+1)}(t)}{n!}(x-t)^{n}\\
\because & H'(t)=-(n+1)(x-t)^n\\
\therefore &\frac{R_n(x)}{(x-x_0)^{n+1}}=\frac{G(x_0)}{H(x_0)}=\frac{G(x_0)-G(x)}{H(x_0)-H(x)}\\
&=\frac{-\frac{f^{(n+1)}(\xi)}{n!}(x-\xi)^{n}}{-(n+1)(x-\xi)^n}=\frac{f^{(n+1)}(\xi)}{(n+1)!}\\
\therefore & R_n(x)=\frac{f^{(n+1)}(\xi)}{(n+1)!}(x-x_0)^{n+1}\\
\end{aligned}

*** 幂级数展开充要条件：

\begin{aligned}
\lim_{n\to \infty}\frac{f^{(n+1)}(\xi)}{(n+1)!}(x-x_0)^{n+1}=0,\ \ \xi\in [x,x_0]
\end{aligned}

*** Taylor公式余项的积分表示

**** 描述：

若函数 $f(x)$ 在 $[a,b]$ 上连续 $(a,b)$ 上 $n+1$ 介可导，且 $x,x_0\in (a,b)$ 则：

\begin{aligned}
f(x)=\sum_{i=0}^n \frac{f^{(i)}(x_0)}{i!}(x-x_0)^i+R_n(x)
\end{aligned}

其中：

\begin{aligned}
R_n(x)=\frac{1}{n!}\int_{x_0}^x f^{(n+1)}(t)(x-t)^ndt
\end{aligned}

**** 证明：

函数级数展开的余项 $R_n(x)=f(x)-\sum_{i=0}^n \frac{f^{(i)}(x_0)}{i!}(x-x_0)^i$ ，则有以下推导：

\begin{aligned}
&R_n(x_0)=f(x_0)-f(x_0)-\sum_{i=1}^n \frac{f^{(i)}(x_0)}{i!}(x_0-x_0)^i=0\\
&R_n^{(1)}(x_0)=f^{(1)}(x_0)-f^{(1)}(x_0)-\sum_{i=2}^n \frac{f^{(i)}(x_0)}{(i-1)!}(x_0-x_0)^{i-1}=0\\
&...\\
&R_n^{(j)}(x_0)=f^{(j)}(x_0)-f^{(j)}(x_0)-\sum_{i=j+1}^n \frac{f^{(i)}(x_0)}{(i-j)!}(x_0-x_0)^{i-j}=0\\
&...\\
&R_n^{(n)}(x_0)=f^{(n)}(x_0)-f^{(n)}(x_0)\\
&R_n^{(n+1)}(x)=f^{(n+1)}(x)\\
\end{aligned}

由于函数 $f(x)$ 和 $\sum_{i=0}^n \frac{f^{(i)}(x_0)}{i!}(x-x_0)^i$ 均为 $n+1$ 阶可导，则有 $R_n(x)$ 也为 $n+1$ 阶可导

\begin{aligned}
R_n(x)-R_n(x_0)&=\int_{x_0}^x R_n^{(1)}(t)dt=\int_{x_0}^x R_n^{(1)}(t)d(t-x)\\
&=(t-x) R_n^{(1)}(t)\big|_{x_0}^x-\int_{x_0}^x (t-x)dR_n^{(1)}(t)\\
&=(x-x) R_n^{(1)}(x)-(x-x_0) R_n^{(1)}(x_0)-\int_{x_0}^x R_n^{(2)}(t)(t-x)dt\\
&=-\int_{x_0}^x R_n^{(2)}(t)(t-x)dt&=\frac{1}{1!}\int_{x_0}^x R_n^{(2)}(t)(x-t)dt\\
&=-\frac{1}{2}\int_{x_0}^x R_n^{(2)}(t)d(t-x)^2\\
&=-\frac{1}{2}(t-x)^2 R_n^{(2)}(t)\big|_{x_0}^x+\frac{1}{2}\int_{x_0}^x (t-x)^2dR_n^{(2)}(t)\\
&=\frac{1}{2}\int_{x_0}^x R_n^{(3)}(t)(t-x)^2dt&=\frac{1}{2!}\int_{x_0}^x R_n^{(3)}(t)(x-t)^2dt\\
&=...\\
&=(-1)^n\frac{1}{n!}\int_{x_0}^x R_n^{(n+1)}(t)(t-x)^ndt&=\frac{1}{n!}\int_{x_0}^x R_n^{(n+1)}(t)(x-t)^ndt\\
\end{aligned}

由于 $R_n^{(n+1)}(x)=f^{(n+1)}(x)$ 且 $R_n(x_0)=0$ 则有：

\begin{aligned}
R_n(x)=R_n(x)-R_n(x_0)=\frac{1}{n!}\int_{x_0}^x f^{(n+1)}(t)(x-t)^ndt
\end{aligned}

**** 推导1（拉格朗日余项）：

由于 $x_0$ 在 $x$ 的单侧，故 $(x-t)^n$ 在积分区间内不变号，且 $f(x)$ 在区间内可导(连续)

故可用[[E:\OneDrive\数学分析\Note\Chapter 8\反常积分概念.org][无界函数反常积分收敛判别-一般函数（不定号）反常积分判别法-第一积分中值定理]]，则有：

\begin{aligned}
&\frac{1}{n!}\int_{x_0}^x f^{(n+1)}(t)(x-t)^ndt=\frac{1}{n!}f^{(n+1)}(\xi)\int_{x_0}^x (x-t)^ndt\\
&=\frac{1}{(n)!}f^{(n+1)}(\xi)(-\frac{1}{n+1})[(x-x)^{(n+1)}-(x-x_0)^{(n+1)}]\\
&=\frac{1}{(n+1)!}f^{(n+1)}(\xi)(x-x_0)^{(n+1)}\\
\end{aligned}

其中 $\xi \in [x_0,x]$ 。

**** 推导2（柯西余项）:

同理根据用[[E:\OneDrive\数学分析\Note\Chapter 8\反常积分概念.org][第一积分中值定理]]：

\begin{aligned}
&\frac{1}{n!}\int_{x_0}^x f^{(n+1)}(t)(x-t)^ndt=\frac{1}{n!}f^{(n+1)}(\xi)(x-\xi)^n\int_{x_0}^x dt=\frac{1}{n!}f^{(n+1)}(\xi)(x-\xi)^n(x-x_0)\\
&=\frac{1}{n!}f^{(n+1)}(x_0+\theta(x-x_0))(x-x_0-\theta(x-x_0))^n(x-x_0)\\
&=\frac{1}{n!}f^{(n+1)}(x_0+\theta(x-x_0))[(1-\theta)(x-x_0)]^n(x-x_0)\\
&=\frac{1}{n!}f^{(n+1)}(x_0+\theta(x-x_0))(1-\theta)^n(x-x_0)^{n+1}\\
\end{aligned}

其中 $\theta \in [0,1]$ 。

*** 经典例题：

求 $f(x)=(1+x)^\alpha$ 在 $x=0$ 点的Taylor展开。

**** 先写Taylor展开式：

\begin{aligned}
\sum_{n=0}^\infty \frac{1}{n!} f^{(n)}(x_0)(x-x_0)^n&=\sum_{n=0}^\infty \frac{1}{n!} \left\{ \alpha(\alpha-1)(\alpha-2)...(\alpha-n+1)x_0^{\alpha-n} \right\}(x-x_0)^n\\
&=\sum_{n=0}^\infty \frac{\alpha(\alpha-1)(\alpha-2)...(\alpha-n+1)}{n!}x^n
\end{aligned}

定义 $\binom \alpha n = \frac{\alpha(\alpha-1)(\alpha-2)...(\alpha-n+1)}{n!}$ 则Taylor展开式为：

\begin{aligned}
\sum_{n=0}^\infty \binom \alpha n x^n\Rightarrow u_n(x)=\binom \alpha n x^n
\end{aligned}

**** 求展开无穷级数的收敛半径：

利用[[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][达朗贝尔]]判别：

\begin{aligned}
\lim_{n\to\infty}\left|\frac{u_{n+1}}{u_n}\right|&=\lim_{n\to\infty}\left|\frac{\binom \alpha {n+1} x^{n+1}}{\binom \alpha n x^n}\right|\\
&=\lim_{n\to\infty}\left|\frac{\alpha-n}{n+1}x\right|\\
&=\lim_{n\to\infty}\left|\frac{\alpha}{n+1}-\frac{n}{n+1}\right||x|\\
&=\left|0-1\right||x|\\
&=|x|\\
\end{aligned}

故，当 $|x|<1,x\in(-1,1)$ 是幂级数收敛。

**** 求余项是否收敛：

尝试拉格朗日余项

\begin{aligned}
R_n&=\frac{1}{(n+1)!}f^{(n+1)}(\xi)(x-x_0)^{(n+1)}\\
&=\frac{1}{(n+1)!}\left\{\alpha(\alpha-1)...(\alpha-n)(1+\xi)^{\alpha-n-1}\right\}(x-0)^{n+1}\\
&=\binom \alpha {n+1}x^{n+1} \left(\frac{1}{1+\xi}\right)^n \xi^{\alpha-1}\\
\end{aligned}

由于幂级数 $\sum_{n=0}^\infty \binom \alpha n x^n$ 在 $x\in (-1,1)$ 收敛，根据[[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][柯西收敛原理-推论2]]，

通项极限为0： $\lim_{n\to\infty}\binom \alpha n x^n=0,\ \ x\in(-1,1)$

由于 $\xi\in (x,x_0)$ 且 $x_0=0,\ x\in(-1,1)$ 故 $\xi\in(-1,1)$ 得出 $\left(\frac{1}{1+\xi}\right)^n$ 可能发散（ $\xi<0$ ）

尝试柯西余项：

\begin{aligned}
R_n&=\frac{1}{n!}f^{(n+1)}(x_0+\theta(x-x_0))(1-\theta)^n(x-x_0)^{n+1}\\
&=\frac{1}{n!}(1-\theta)^n\left\{\alpha(\alpha-1)(\alpha-2)...(\alpha-n+1)(1+\theta x)^{\alpha-n-1}\right\}(x-0)^{n+1}\\
&=\binom \alpha {n+1} (n+1) x^{n+1} (1-\theta)^n (1+\theta x)^{\alpha-n-1}\\
&=\binom \alpha {n+1} (n+1) x^{n+1} \left(\frac{1-\theta}{1+\theta x}\right)^n (1+\theta x)^{\alpha-1}\\
\end{aligned}

同样根据[[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][达朗贝尔]]判别可证 $\sum_{n=0}^\infty \binom \alpha {n+1} (n+1) x^{n+1}$ 在 $x\in (-1,1)$ 收敛，故根据[[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][柯西收敛原理-推论2]]，

通项极限为0： $\lim_{n\to\infty}\binom \alpha {n+1} (n+1) x^{n+1}=0$

又由于当 $|x|\leq 1,\theta\in [0,1]$ ，则 $\frac{1-\theta}{1+\theta x}\leq 1$ ，故 $\left(\frac{1-\theta}{1+\theta x}\right)^{n+1} \leq \left(\frac{1-\theta}{1+\theta x}\right)^n$ 且 $0<\left(\frac{1-\theta}{1+\theta x}\right)<\infty$ ，所以 $\lim_{n\to\infty}\left(\frac{1-\theta}{1+\theta x}\right)^n=C<\infty$

极限为无穷小量和有界量乘积，结果为无穷小量。

**** 求边界值：

***** 当 $\alpha \leq -1$ 时，通项：

\begin{aligned}
&\lim_{n\to\infty}|u_n|=\lim_{n\to\infty}\left|\binom \alpha n\right|= \lim_{n\to\infty}\left|\frac{\alpha(\alpha-1)...(\alpha-j+1)...(\alpha-n+1)}{(1)(2)...(j)...(n)}\right|\\
\because &\alpha \leq -1\\
\because &\forall 0<j<n+1,j\in N^+\Rightarrow \left|\frac{\alpha-j+1}{j}\right|>1\\
\therefore & \lim_{n\to\infty}\left|\frac{\alpha(\alpha-1)...(\alpha-j+1)...(\alpha-n+1)}{(1)(2)...(j)...(n)}\right|>1\\
\end{aligned}

根据[[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][柯西收敛原理-推论2]]，通项不趋于零，级数发散。

***** 当 $-1<\alpha<0$ 时：

****** 当 $x=1$ 时，通项 $u_n=\binom \alpha n$ ：

******* 证明级数收敛：

由于 $\binom \alpha {n+1}=\binom \alpha n \frac{\alpha-n}{n+1}$ 且 $n \geq 1,-1<a<0$ 故通项 $u_n(x)=\binom \alpha n x^n$ 为交错级数

\begin{aligned}
u_n&=(-1)^n|u_n|\\
|u_n|&=\left|\frac{\alpha(\alpha-1)...(\alpha-n+1)}{n!}\right|\\
&=\frac{-\alpha(-\alpha+1)...(-\alpha+n-1)}{n!}\\
&=\frac{-\alpha}{1}\frac{-\alpha+1}{2}...\frac{-\alpha+n-1}{n}\\
\because &-1<\alpha<0\\
\therefore & \frac{-\alpha-n}{n+1}<1,\ \forall n\in N^+\\
\because & |u_{n+1}|=|u_n|\frac{-\alpha-n}{n+1}\\
\therefore &|u_{n+1}|<|u_n|\\
|u_n|&=\frac{-\alpha}{1}\frac{-\alpha+1}{2}...\frac{-\alpha+n-1}{n}\\
&=\left(1-\frac{1+\alpha}{1}\right)\left(1-\frac{1+\alpha}{2}\right)\left(1-\frac{1+\alpha}{3}\right)...\left(1-\frac{1+\alpha}{n}\right)\\
&=\prod_{i=1}^n\left(1-\frac{1+\alpha}{i}\right)\\
\end{aligned}

根据[[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][无穷乘积与无穷级数-推论1]]， $-\frac{1+\alpha}{i}$ 不编号，则无穷乘积 $\prod_{i=1}^\infty\left(1-\frac{1+\alpha}{i}\right)$ 与 $\sum_{n=1}^\infty -\frac{1+\alpha}{n}$ 同时敛散。

又根据[[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][部分极限证明-P级数]]，无穷乘积发散。由于 $-1<-\frac{1+\alpha}{i}<0\Rightarrow 0<\left(1-\frac{1+\alpha}{i}\right)<1, \forall i\geq 1$ 故无穷乘积发散到0。

至此，通项 $u_n$ 具有以下性质：

（1） $u_n=(-1)^n|u_n|$ 为交错级数；
（2） $|u_n|>0$ 单调递减；
（3） $\lim_{n\to\infty}|u_n|=0$ ;

满足莱布尼茨级数，故级数 $\sum_{n=1}^\infty \binom \alpha n$ 为莱布尼茨级数，得出收敛。

******* <<P2>>证明余项收敛：

此时积分余项为:

\begin{aligned}
R_n(1)&=\frac{1}{n!}\int_{x_0}^x f^{(n+1)}(t)(x-t)^ndt\\
&=\frac{1}{n!}\int_{x_0}^x \alpha(\alpha-1)...(\alpha-n)(1+t)^{\alpha-n-1}(x-t)^ndt\\
&=\frac{\alpha(\alpha-1)...(\alpha-n)}{n!}\int_{x_0}^x(1+t)^{\alpha-n-1}(x-t)^ndt\\
&=\binom \alpha {n+1} (n+1) \int_{x_0}^x(1+t)^{\alpha-n-1}(x-t)^ndt\\
\end{aligned}

带入 $x_0=0,x=1$ 得：

\begin{aligned}
R_n(1)&=\binom \alpha {n+1} (n+1) \int_{x_0}^x(1+t)^{\alpha-n-1}(x-t)^ndt\\
&=\binom \alpha {n+1} (n+1) \int_0^1 (1+t)^{\alpha-n-1}(1-t)^ndt\\
&=\binom \alpha {n+1} (n+1) \int_0^1 \left(\frac{1-t}{1+t}\right)^n (1+t)^{\alpha-1}dt\\
\end{aligned}

由于在积分区域中 $1+t\geq 1\ \&\ \alpha-1<0\Rightarrow (1+t)^{\alpha-1}\leq 1$ ，又有 $\frac{1-t}{1+t} \leq 1-t\ \&\ n>0\Rightarrow \left(\frac{1-t}{1+t}\right)^n \leq (1-t)^n$ 且积分项恒为正，故有

\begin{aligned}
\because &|R_n(1)|=\left|\binom \alpha {n+1} (n+1) \int_0^1 \left(\frac{1-t}{1+t}\right)^n (1+t)^{\alpha-1}dt\right|
=\left|\binom \alpha {n+1} (n+1)\right|\left|\int_0^1 \left(\frac{1-t}{1+t}\right)^n (1+t)^{\alpha-1}dt\right|\\
\therefore &|R_n(1)| \leq \left|\binom \alpha {n+1} (n+1)\right|\left|\int_0^1 (1-t)^n 1^{\alpha-1}dt\right|
=\left|\binom \alpha {n+1} (n+1)\right|\left|\frac{-1}{n+1} (1-t)^{n+1}\bigg|_0^1 \right|\\
&=\left|\binom \alpha {n+1} (n+1)\right|\frac{1}{n+1}=\left|\binom \alpha {n+1} \right|\\
\end{aligned}

根据上一步证明级数收敛中对 $\lim_{n\to\infty}\left|\binom \alpha n\right|=0$ 的证明可得 $\lim_{n\to\infty}\left|\binom \alpha {n+1}\right|=0$ 故由于 $0<|R_n(1)| \leq \left|\binom \alpha {n+1}\right|$ 可得 $-\left|\binom \alpha {n+1}\right| \leq R_n(1) \left|\binom \alpha {n+1}\right|$ 故由夹逼定理得 $\lim_{n\to\infty}R_n(1)=0$  

****** 当 $x=-1$ ，通项 $u_n=\binom \alpha n (-1)^n$ 为正项级数：

故用[[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][拉得判别法]]：

\begin{aligned}
r&=\lim_{n\to\infty}n\left(\frac{u_n}{u_{n+1}}-1\right)\\
&=\lim_{n\to\infty}n\left(-\frac{n+1}{\alpha-n}-1\right)\\
&=\lim_{n\to\infty}n\frac{1+\alpha}{n-\alpha}\\
&=\lim_{n\to\infty}(1+\alpha)\frac{n}{n-\alpha}\\
&=1+\alpha\\
\end{aligned}

由于 $-1<\alpha<0$ 故 $r<1$ 得出级数发散。

***** 当 $\alpha > 0$ 时: 

****** <<P1>>证明级数收敛：

当 $x=1,-1$ 时，通项 $u_n(x)=\binom \alpha n x^n$ Talyor级数为 $\sum_{n=0}^\infty \binom \alpha n x^n$

故用[[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][拉得判别法]]：

\begin{aligned}
r&=\lim_{n\to\infty}n\left(\frac{|u_n|}{|u_{n+1}|}-1\right)\\
&=\lim_{n\to\infty}n\left(\frac{n+1}{|\alpha-n|}-1\right)\\
&=\lim_{n\to\infty}n\frac{1+\alpha}{n-\alpha}\\
&=\lim_{n\to\infty}(1+\alpha)\frac{n}{n-\alpha}\\
&=1+\alpha\\
\end{aligned}

由于 $\alpha >0\Rightarrow r>1$ 所以级数绝对收敛，故当 $x=1,-1$ 时级数均收敛。

****** 证明余项趋于零：

******* $x=1$ :

根据之前[[P2][证明余项收敛]]的结论，当 $x_0=0,x=1$ 时：

\begin{aligned}
&|R_n(1)| \leq \left|\binom \alpha {n+1}\right|
\end{aligned} 

又根据[[P1][之前证明]] $\sum_{n=0}^\infty \binom \alpha n$ 在 $\alpha>0$ 时绝对收敛，故根据[[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][柯西收敛原理-推论2]]可得 $\lim_{n\to\infty}\binom \alpha n=0,\alpha>0$

故根据夹逼定理  $\lim_{n\to\infty}R_n(1)=0$

******* $x=-1$ :

此时积分余项为:

\begin{aligned}
R_n(1)&=\binom \alpha {n+1} (n+1) \int_{x_0}^x(1+t)^{\alpha-n-1}(x-t)^ndt\\
\end{aligned}

带入 $x_0=0,x=-1$

\begin{aligned}
R_n(-1)&=\binom \alpha {n+1} (n+1) \int_{x_0}^x(1+t)^{\alpha-n-1}(x-t)^ndt\\
&=\binom \alpha {n+1} (n+1) \int_0^{-1} (1+t)^{\alpha-n-1}(-1-t)^ndt\\
&=\binom \alpha {n+1} (n+1)(-1)^n \int_0^{-1} (1+t)^{\alpha-n-1}(1+t)^ndt\\
&=\binom \alpha {n+1} (n+1)(-1)^n \int_0^{-1} (1+t)^{\alpha-1}dt\\
\Rightarrow&R_n(-1)=C(-1)^n\binom \alpha {n+1} (n+1)\\
\end{aligned}

其中 $C$ 为与 $n$ 不相关的常数，且由于 $-\infty<\alpha<\infty$ 可得 $-\infty<C<\infty$ 即常数项有界。

假设 $N-1<\alpha<N, N\in N^+$ 则有：

\begin{aligned}
\lim_{n\to\infty}(-1)^n\binom \alpha {n+1} (n+1)&= \lim_{n\to\infty}\alpha \frac{1-\alpha}{1}\frac{2-\alpha}{2}...\frac{n-\alpha}{n}\\
&=\lim_{n\to\infty}\alpha\prod_{i=1}^n\left(1-\frac{\alpha}{i}\right)\\
&=\lim_{n\to\infty}\alpha\prod_{i=1}^N\left(1-\frac{\alpha}{i}\right)\prod_{i=N+1}^n\left(1-\frac{\alpha}{i}\right)\\
&=A\lim_{n\to\infty}\prod_{i=N+1}^n\left(1-\frac{\alpha}{i}\right)\\
\end{aligned}

其中 $A$ 为与 $n$ 不相关的常数且 $0<\alpha<\infty\Rightarrow 0<A<\infty$ 故有界，由于 $\forall i>N\Rightarrow0<\frac{\alpha}{i}<1$ 故根据[[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][无穷乘积与无穷级数-推论1]]，无穷乘积与 $\sum_{n=N}^\infty \frac{\alpha}{n}$ 同时敛散。

又根据[[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][部分极限证明-P级数]]可知级数发散。由于 $0<\frac{\alpha}{i}<1\Rightarrow 0<\left(1-\frac{\alpha}{i}\right)<1$ ，故级数发散到 $0$ 。故 $\lim_{n\to\infty}\prod_{i=N+1}^n\left(1-\frac{\alpha}{i}\right)=0$ 

最后证得：

\begin{aligned}
\lim_{n\to\infty} R_n(-1)=CA\lim_{n\to\infty}\prod_{i=N+1}^n\left(1-\frac{\alpha}{i}\right)=0
\end{aligned}

**** 总结：

\begin{aligned}
(1+x)^\alpha=\sum_{n=0}^\infty \binom \alpha x x^n,\ \begin{cases}
&x\in(-1,1),\ \ \alpha \leq 1\\
&x\in(-1,1],\ \ 1<\alpha<0\\
&x\in[-1,1],\ \ \alpha>0\\
\end{cases}
\end{aligned}

* 连续函数多项式逼近

** Weierstrass第一逼近定理

*** 描述

函数 $f(x)$ 在闭区间 $[a,b]$ 上连续，则存在多项式 $P_n(x)$ ，使得

$\forall \epsilon>0,\ \exists N,\ \forall n>N,\forall x\in[a,b]\Rightarrow |f(x)-P_n(x)|<\epsilon$

*** 证明

**** 二项式展开：

\begin{aligned}
(a+b)^n=\sum_{i=0}^n C_n^i a^ib^{n-i}
\end{aligned} 

其中 $C_n^i=\frac{n!}{i!(n-i)!}$

**** 先证明 $[a,b]=[0,1]$

***** Berstein多项式

定义多项式 $B_n(f:x)=\sum_{i=0}^n f(\frac{i}{n})C_n^i x^i(1-x)^{n-i}$

***** Berstein多项式性质

****** 线性

\begin{aligned}
B_n(\alpha f+\beta g:x)=\alpha B_n(f:x)+\beta B_n(g:x)
\end{aligned}

****** 单调性

\begin{aligned}
&g(x)>f(x)\Rigtharrow B_n(g:x)>B_n(f:x),x\in[0,1]\\
\because &x\in[0,1]\\
\therefore &C_n^i x^i(1-x)^{n-1}>0\\
\therefore &\sum_{i=0}^n g(\frac{i}{n})C_n^i x^i(1-x)^{n-i}-\sum_{i=0}^n f(\frac{i}{n})C_n^i x^i(1-x)^{n-i}=\sum_{i=0}^n \left(f(\frac{i}{n})-f(\frac{i}{n})\right)C_n^i x^i(1-x)^{n-i}>0
\end{aligned}

***** Berstein多项式部分值

****** $f(x)=1$

\begin{aligned}
&B_n(1:x)=\sum_{i=0}^n C_n^i x^i(1-x)^{n-i}=[1+(1-x)]^n=1\\
&B_n(\alpha:x)=\alpha B(1:x)=\alpha\\
\end{aligned}

****** $f(x)=x$

\begin{aligned}
B_n(x:x)&=\sum_{i=0}^n \frac{i}{n}C_n^i x^i(1-x)^{n-i}=\frac{0}{n}C_n^i x^i(1-x)^{n-i}+\sum_{i=1}^n \frac{i}{n}C_n^i x^i(1-x)^{n-i}\\
&=0+\sum_{i=1}^n \frac{i}{n} \frac{n!}{i!(n-i)!} x^i(1-x)^{n-i}\\
&=\sum_{i=1}^n \frac{(n-1)!}{(i-1)!(n-i)!} x^i(1-x)^{n-i}\\
&=x\sum_{i=1}^n C_{n-1}^{i-1} x^(i-1)(1-x)^{n-i}\\
&=x[x+(1-x)]^{n-1}\\
&=x\\
\end{aligned}

****** $f(x)=x^2$

\begin{aligned}
B_n(x^2:x)&=\sum_{i=0}^n \frac{i^2}{n^2}C_n^i x^i(1-x)^{n-i}=0+\sum_{i=1}^n \frac{i^2}{n^2}C_n^i x^i(1-x)^{n-i}\\
&=\sum_{i=1}^n \frac{i}{n}C_{n-1}^{i-1} x^i(1-x)^{n-i}\\
&=\sum_{i=1}^n \frac{i-1+1}{n}C_{n-1}^{i-1} x^i(1-x)^{n-i}\\
&=\sum_{i=1}^n \frac{i-1}{n}C_{n-1}^{i-1} x^i(1-x)^{n-i}+\sum_{i=1}^n \frac{1}{n}C_{n-1}^{i-1} x^i(1-x)^{n-i}\\
&=\sum_{i=1}^n \frac{i-1}{n}\frac{(n-1)!}{(i-1)!(n-i)!} x^i(1-x)^{n-i}+\frac{x}{n}\sum_{i=1}^n C_{n-1}^{i-1} x^{i-1}(1-x)^{n-i}\\
&=0+\sum_{i=2}^n \frac{n-1}{n}\frac{(n-2)!}{(i-2)!(n-i)!} x^i(1-x)^{n-i}+\frac{x}{n}\\
&=\frac{n-1}{n}x^2\sum_{i=2}^n C_{n-2}^{i-2} x^{i-2}(1-x)^{n-i}+\frac{x}{n}\\
&=\frac{n-1}{n}x^2+\frac{x}{n}\\
&=x^2+\frac{x-x^2}{n}\\
\end{aligned}

***** 证明定理

因为 $f(x)$ 在闭区间 $[0,1]$ 上连续，根据[[E:\OneDrive\数学分析\Note\Chapter 7\IntegrationCondition.org][康托定理]] $f(x)$ 在闭区间内一致连续： 

$\forall \epsilon>0, \exists \delta,\forall |x-y|<\delta,x,y\in[0,1]\Rightarrow |f(x)-f(y)|<\frac{\epsilon}{2}$

下面证明多项式:

****** 先将多项式分段：

\begin{aligned} 
|B_n(f:x)-f(x)|&=\left|\sum_{i=0}^n f(\frac{i}{n})C_n^i x^i(1-x)^{n-i}-f(x)\cdot 1\right|\\
&=\left| \sum_{i=0}^n f(\frac{i}{n})C_n^i x^i(1-x)^{n-i}-\sum_{i=0}^n f(x)C_n^i x^i(1-x)^{n-i} \right|\\
&=\left| \sum_{i=0}^n\left[f(\frac{i}{n})-f(x)\right]C_n^i x^i(1-x)^{n-i} \right|\\
&=\left| \sum_{\left|\frac{i}{n}-x\right|<\delta}\left[f(\frac{i}{n})-f(x)\right]C_n^i x^i(1-x)^{n-i} 
+ \sum_{\left|\frac{i}{n}-x\right|>\delta}\left[f(\frac{i}{n})-f(x)\right]C_n^i x^i(1-x)^{n-i} \right|\\
&\leq \left| \sum_{\left|\frac{i}{n}-x\right|<\delta}\left[f(\frac{i}{n})-f(x)\right]C_n^i x^i(1-x)^{n-i} \right|
+ \left|\sum_{\left|\frac{i}{n}-x\right|>\delta}\left[f(\frac{i}{n})-f(x)\right]C_n^i x^i(1-x)^{n-i} \right|
\end{aligned}

****** 前半部分:

\begin{aligned}
&\left| \sum_{\left|\frac{i}{n}-x\right|<\delta}\left[f(\frac{i}{n})-f(x)\right]C_n^i x^i(1-x)^{n-i} \right|\\
&\leq \sum_{\left|\frac{i}{n}-x\right|<\delta}\left|f(\frac{i}{n})-f(x)\right|C_n^i x^i(1-x)^{n-i}\\
&< \sum_{\left|\frac{i}{n}-x\right|<\delta}\epsilon C_n^i x^i(1-x)^{n-i}\\
&\leq \epsilon \sum_0^n C_n^i x^i(1-x)^{n-i}\\
&=\epsilon\\
\end{aligned}

****** 后半部分：

因为 $f(x)$ 为闭区间上连续函数，根据[[E:\OneDrive\数学分析\Note\Chapter 7\IntegrationCondition.org][有界性定理]]， $f(x)$ 必有界，即 $M=max(f(x)),x\in[a,b]$ ：

\begin{aligned}
&\left|\sum_{\left|\frac{i}{n}-x\right|>\delta}\left[f(\frac{i}{n})-f(x)\right]C_n^i x^i(1-x)^{n-i} \right|\\
&\leq \sum_{\left|\frac{i}{n}-x\right|>\delta}\left|f(\frac{i}{n})-f(x)\right|C_n^i x^i(1-x)^{n-i}\\
&\leq \sum_{\left|\frac{i}{n}-x\right|>\delta}\left[\left|f(\frac{i}{n})\right|+\left|f(x)\right|\right]C_n^i x^i(1-x)^{n-i}\\
&= \sum_{\left|\frac{i}{n}-x\right|>\delta}2MC_n^i x^i(1-x)^{n-i}\\
&< 2M\sum_{\left|\frac{i}{n}-x\right|>\delta} \frac{\left(\frac{i}{n}-x\right)^2}{\delta^2} C_n^i x^i(1-x)^{n-i}\\
&< \frac{2M}{\delta^2}\sum_{\left|\frac{i}{n}-x\right|>\delta} \left(\frac{i^2}{n^2}-2x\frac{i}{n}+x^2\right) C_n^i x^i(1-x)^{n-i}\\
&< \frac{2M}{\delta^2}\sum_0^n \left(\frac{i^2}{n^2}-2x\frac{i}{n}+x^2\right) C_n^i x^i(1-x)^{n-i}\\
&=\frac{2M}{\delta^2}\left\{B_n(x^2:x)-2xB_n(x:x)+x^2B_n(1:x)\right\}\\
&=\frac{2M}{\delta^2}\left(x^2+\frac{x-x^2}{n}-2x^2+x^2\right)\\
&=\frac{2M}{\delta^2}\frac{(1-x)x}{n}\\
\because &x\in[0,1],\ \therefore (1-x)x\leq \frac{1}{4}\\
\therefore &\left|\sum_{\left|\frac{i}{n}-x\right|>\delta}\left[f(\frac{i}{n})-f(x)\right]C_n^i x^i(1-x)^{n-i} \right| < \frac{2M}{4n\delta^2}\\
\end{aligned}

****** 结合两部分

故结合上述表述可得 $|B_n(f:x)-f(x)|<\epsilon+\frac{2M}{4n\delta^2}$ 

所以:

\begin{aligned}
\because &\forall \epsilon>0, \exists \delta, \forall |x-y|<\delta,x,y\in[0,1]\Rightarrow |f(x)-f(y)|<\frac{\epsilon}{2}\\
\therefore &\forall \epsilon>0, \exists N=\frac{M}{\delta^2\epsilon},\forall n>N\Rightarrow |B_n(f:x)-f(x)|<\frac{\epsilon}{2}+\frac{2M}{4n\delta^2}<\frac{\epsilon}{2}+\frac{2M}{4\frac{M}{\delta^2\epsilon}\delta^2}=\epsilon\\
\end{aligned}

证毕。

**** 再证明对于任意闭区间 $[a,b]$

函数 $f(x)$ 在闭区间 $[a,b]$ 上连续，则构建 $x=a+y(b-a)$ 带入 $f(x)=f(a+y(b-a))=\phi(y)$

故可对 $\phi(y)$ 做Berstein多项式：
$B_n(\phi:y)=\sum_{i=0}^n \phi(\frac{i}{n})C_n^iy^i(1-y)^{n-i}=\sum_{i=0}^n f(a+\frac{i}{n}(b-a))C_n^i\left(\frac{x-a}{b-a}\right)^i\left(1-\frac{x-a}{b-a}\right)^{n-i}$
