#+LATEX_CLASS: ctexart
#+OPTIONS: ^:nil
#+TITLE: 定积分

currnet mark: 8

* 定积分定义

** 定义: 

函数: $f(x)$ 在 $\left[a,b\right]$ 上有界

划分: $P: a=x_0<x_1<x_2<...<x_{n-1}<b=x_n$ 

** 定义如下符号:

$\Delta x_i=x_i-x_{i-1}$; $\xi_i \in \left[ x_i, x_{i-1}
\right]$; $\lambda=max(\Delta x_i)$

** 定义黎曼和:

$\sum_{i=1}^n f(\xi_i)\Delta x$

** <<MK6>>定义定积分: 黎曼和的极限收敛 $\Rightarrow$ 黎曼可积(注: 与划分及区间取值无关)

$\forall (P,\ \xi_i)$ :

$\lim_{\lambda \to 0}{\sum_{i=1}^n f(\xi_i)\Delta x_i} = I$ 

即如下表示：

$\forall \epsilon > 0$, $\exists \delta > 0$, $\forall (P,\ \xi_i)$ 只要 $\lambda < \delta$ 

$\Rightarrow \bigg| \sum_{i=1}^n f(\xi_i)\Delta x_i - I \bigg| < \epsilon$

** <<MK4>>推论

可积函数必有界

*** 证明

若 $f(x)$ 在 $[a,b]$ 中可积且积分为 $I$ ，且 $f(c)=\infty,c\in[a,b]$ 

故对于 $\epsilon$ 定义划分与取点 $(P_1,\xi_{i_1})$ 为满足 $\left| \sum_{i_1=1}^n f(\xi_{i_1})\Delta x_{i_1} - I \right| < \epsilon$ ，且 $c\not\in\{\xi_i\}$ 的划分取点

定义  $(P_2,\xi_{i_2})$ 为比 $(P_1,\xi_{i_1})$ 多一个划分在包含 $c$ 点的分段，且多一个取点 $\xi_k=c$

则当 $\xi_k=c$ 时，黎曼和为 $\sum_{i_2\in N^+,1\leq i_2\leq,i_2\ne k} n f(\xi_{i_2})\Delta x_{i_2}+f(\xi_k)\Delta x_k$

根据极限定义，当 $\xi_k=c$ 时需满足 $\forall \epsilon > 0,\exists \delta > 0,\forall (P,\ \xi_i)\Rightarrow \left|\sum_{i\in N^+,1\leq i\leq,i\ne k} n f(\xi_i)\Delta x_i+f(\xi_k)\Delta x_k-I\right|<\epsilon$ 

因为 $\left|\sum_{i_2\in N^+,1\leq i_2\leq,i_2\ne k} n f(\xi_{i_2})\Delta x_{i_2}-I\right|=\left| \sum_{i_1=1}^n f(\xi_{i_1})\Delta x_{i_1} - I \right| < \epsilon$ 有界，故 $\left|\sum_{i\in N^+,1\leq i\leq,i\ne k} n f(\xi_i)\Delta x_i+f(\xi_k)\Delta x_k-I\right|=+\infty>\epsilon$ 

故不满足 $\forall (P,\xi_i)$ 推出矛盾，则 $f(x)$ 必有界

* 定积分可积定理

** 基础定义:

函数: $f(x)$ 在 $\left[a,b\right]$ 上有界

划分: $P: a=x_0<x_1<x_2<...<x_{n-1}<b=x_n$ 

符号: $\Delta x_i=x_i-x_{i-1}$;

     $\xi_i \in \left[ x_i, x_{i-1} \right]$;
    
     $\lambda=max(\Delta x_i)$;

     $M_i = sup(f(x))\,\ x \in \left[\ x_{i-1}, x_i \right]$;

     $m_i = inf(f(x))\,\ x \in \left[\ x_{i-1}, x_i \right]$;

     $M = sup(f(x))\ x \in \left[ a,b \right]$;

     $m = inf(f(x))\ x\in \left[ a,b \right]$

** 定义达布和:

达布大和: $\overline S(P) = \sum_{i=1}^n M_i \Delta x_i$

达布小和: $\underline S(P) = \sum_{i=1}^n m_i \Delta x_i$

** <<L1>> 定理1: 

*** 定义:

给定划分 $P$ 中，增加分点 $\Rightarrow$ 大和不增，小和不减:

*** 证明:

$x_k \in \left[ x_{i-1}, x_i \right]$

定义以下符号: 

$M_{ik} = sup(f(x))\,\ x \in \left[\ x_{i-1}, x_k \right]$ , $M_{ki} = sup(f(x))\,\ x \in \left[\ x_k, x_i \right]$

$m_{ik} = inf(f(x))\,\ x \in \left[\ x_{i-1}, x_k \right]$ , $m_{ki} = inf(f(x))\,\ x \in \left[\ x_k, x_i \right]$

$\Delta x_{ik} = x_k - x_{i - 1}$ , $\Delta x_{ki} = x_i - x_k$ 

因为:

$M_{ik} \Delta x_{ik}  + M_{ki} \Delta x_{ki} \leq M_i (\Delta x_{ik} + \Delta x_{ki}) = M_i \Delta x_i$

$m_{ik} \Delta x_{ik}  + m_{ki} \Delta x_{ki} \geq m_i (\Delta x_{ik} + \Delta x_{ki}) = m_i \Delta x_i$

故 $\Rightarrow$ 大和不增，小和不减

** 定理2:

*** 表述:

$\forall (P_1, P_2) \Rightarrow m(b-a) < \underline S(P_1) < \overline S(P_2) < M(b-a)$

*** 证明:

$P_0: a=x_0<x_1=b \Rightarrow \overlint S(P_0)=M(b-a)$

定义划分: $P = P_1 \cup P_2$

根据[[L1][定理1]]:

$m(b-a) \leq \underline S(P_0) \leq \underline S(P_1) \leq \underline
S(P) \leq \overline S(P) \leq \overline S(P_2) \leq \overline S(P_0) = M(b-a)$

** 达布定理:

*** 表述:
对于: $L = inf \left\{ \overline S(P') \bigg| P' \in \forall P \right\}$ , $l = sup \left\{ \underline S(P') \bigg| P' \in \forall P \right\}$ ，

$\Rightarrow \lim_{\lambda \to 0} \overline S(P) = L &,\ & \lim_{\lambda \to 0} \underline S(P) = l,\forall P$

*** 证明:

根据下确界定义:

$\forall \epsilon >0,\ \exists P'\Rightarrow 0 \leq \overline S(P')-L < \frac{\epsilon}{2}$

$P': a=x'_1<x'_2<...<x'_{n'}=b$

取值: $\delta=min\left\{\Delta x'_i, \frac{\epsilon}{2(n'-1)(M-m)}\right\}$

$\forall P\ (\lambda<\delta)\text{,\ } P: a=x_1<x_2<...<x_n$

构造分点: $P^*: a=x^*_0<x^*_1<...<x_{n^*}^*,\ \ \{x_i^*\} = \{x_i,x'_i \}$

$0 \leq \overline S(P)-L = \overline S(P) - \overline S(P^*) + \overline S(P^*) - \overline S(P') + \overline S(P') - L$

$\overline S(P') - L < \frac{\epsilon}{2}$

$\overline S(P^*) - \overline S(P') \leq 0$ [[L1][定理1]]

因为 $\Delta x'_i \geq \lambda \geq \Delta x_i$ 故对于一个区间 $\left[x_{i-1},x_i\right]$ 中，$P^*$ 最多比 $P$ 增加一个分点 $x'_j$ , 且最多 $n'-1$ 个区间内可插入新的分点, 所以:

\begin{aligned}
\overline S(P) - \overline S(P^*) &= \sum_{i=1}^n M_i(x_i-x_{i-1}) - \sum_{j=1}^{n^*} M_j(x^*_j-x^*_{j-1}) \\
                                  &= \sum_{i:\exists x_{i-1}<x^*_j<x_i}\left\{ M_i(x_i-x_{i-1}) - M_{ij}(x^*_j-x_{i-1}) - M_{ji}(x_i-x^*_j)\right\} \\
                                  &\leq \sum_{i:\exists x_{i-1}<x^*_j<x_i} \left\{M_i(x_i-x_{i-1}) - m_i(x_i-x_{i-1})\right\} \\
                                  &= \sum_{i:\exists x_{i-1}<x^*_j<x_i} \left\{(M-m)\Delta x_i \right\} \\
                                  &\leq \sum_{i:\exists x_{i-1}<x^*_j<x_i} \left\{\frac{\epsilon}{2(n'-1)} \right\} \\
                                  &\leq \frac{\epsilon}{2}
\end{aligned}

故有 

\begin{aligned}
0\leq&\overline S(P)-L\\
=&\overline S(P)-\overline S(P^*)+\overline S(P^*)-\overline S(P')+\overline S(P')-L\\
\leq&\overline S(P)-\overline S(P^*)+\overline S(P')-L\\
<&\frac{\epsilon}{2}+\frac{\epsilon}{2}\\
=&\epsilon
\end{aligned}

$\Rightarrow \forall \epsilon>0 ,\ \  \exists \delta,\ \  \forall P(\lambda<\delta) \Rightarrow 0 \leq \overline S(P) - L<\epsilon \Rightarrow \lim_{\lambda \to 0} \overline S(P) = L$

同理可证:

$\lim_{\lambda \to 0} \underline S(P) = l$

** 定积分可积充要条件1:

*** 描述：

 $L=l\Leftrightarrow \lim_{\lambda \to 0}{\sum_{i=1}^n f(\xi_i)\Delta x_i} = L$

*** 证明充分:

$l \leq \lim_{\lambda \to 0}{\sum_{i=1}^n f(\xi_i)\Delta x_i} \leq L
\ ,\  L=l \Rightarrow \lim_{\lambda \to 0}{\sum_{i=1}^n f(\xi_i)\Delta
x_i} = L$ by 夹逼定理

*** 证明必要:

\begin{aligned}
&\forall \epsilon>0,\  \exists \delta,\ \forall P\ \&\  \forall \xi_i \in [x_{i-1},x_i]\\
&\lambda<\delta \Rightarrow \bigg| \sum_{i=1}^n f(\xi_i)\Delta x_i - I \bigg| < \frac{\epsilon}{2}\\
&\xi'_i:0 \leq M_i-f(\xi'_i)<\frac{\epsilon}{2(b-a)}\\
&\bigg|\sum_{i=1}^n M_i\Delta x_i - I\bigg| \\
&= \bigg|\sum_{i=1}^n M_i\Delta x_i - \sum_{i=1}^n f(\xi'_i)\Delta x_i+ \sum_{i=1}^n f(\xi'_i)\Delta x_i - I\bigg|\\
&\leq \bigg| \sum_{i=1}^n M_i\Delta x_i - \sum_{i=1}^n f(\xi'_i)\Delta x_i \bigg| + \bigg|\sum_{i=1}^n f(\xi'_i)\Delta x_i - I\bigg|\\
&\leq \epsilon\Rightarrow L=I 
\end{aligned}

同理可证:

$l=I$

** <<MK1>>定积分可积充要条件2:

*** 描述:

\begin{aligned}
&\omega_i=M_i-m_i \\
&\lim_{\lambda \to 0} \overline S(P)=\lim_{\lambda \to 0} \underline S(P) \Leftrightarrow \forall P:\lim_{\lambda \to 0} \sum_{i=1}^n \omega_i \Delta x_i = 0
\end{aligned}

*** 证明充分:


\begin{aligned}
&\because \lim_{\lambda \to 0} \overline S(P)=\lim_{\lambda \to 0}\underline S(P) =I \ \&\ \underline S(P) \leq l = I = L \leq \overline S(P)\\
&\therefore \forall \epsilon>0\\ 
&\exists \delta_1,\ \forall \lambda_1<\delta_1 \Rightarrow \forall P_1,\ \overline S(P_1) - I < \frac{\epsilon}{2} \\
&\exists \delta_2,\ \forall \lambda_2<\delta_2 \Rightarrow \forall P_2,\ I - \underline S(P_2) < \frac{\epsilon}{2} \\
&\therefore \forall \lambda < min(\delta_1, \delta_2) \Rightarrow \forall P,\ \overline S(P) - I + I - \underline S(P)=\overline S(P)-\underline S(P)=\sum_{i=1}^n \omega_i \Delta x_i<\epsilon 
\end{aligned}

*** 证明必要:

\begin{aligned}
&\because \lim_{\lambda \to 0} \sum_{i=1}^n \omega_i \Delta x_i = 0\ \&\ \underline S(P) \leq l = I = L \leq \overline S(P)\\
&\therefore \forall \epsilon>0,\ \exists \delta,\ \forall \lambda<\delta \Rightarrow \forall P:\ \  \sum_{i=1}^n \omega_i \Delta x_i < \epsilon\\
&\sum_{i=1}^n \omega_i \Delta x_i\\
&=\sum_{i=1}^n (M_i-m_i) \Delta x_i\\
&=\sum_{i=1}^n M_i \Delta x_i - \sum_{i=1}^n m_i \Delta x_i\\
&=\overline S(P) - \underline S(P) \\
&=\left[ \overline S(P) - I \right] + \left[ I - \underline S(P) \right]<\epsilon\\
&\because \left[ \overline S(P) - I \right]>0 \ \&\ \left[ I - \underline S(P) \right]>0\\
&\therefore \forall \epsilon>0,\ \exists \delta,\ \forall \lambda<\delta\\
&\Rightarrow \forall P\\
&\overline S(P) - I < \epsilon\\
&I - \underline S(P) < \epsilon
\end{aligned}

*** <<MK3>>推论1

若 $f(x)$ 在闭区间 $[a,b]$ 连续，则 $f(x)$ 必可积

**** 证明

要证明推论，可用条件 $\lim_{\lambda \to 0} \sum_{i=1}^n \omega_i \Delta x_i = 0$ 即 $\forall \epsilon_1>0,\exists\delta\Rightarrow \forall P(\lambda<\delta),\sum_{i=1}^n \omega_i \Delta x_i<\epsilon_1$

根据[[K3][康托定理]]可得 $f(x)$ 在 $[a,b]$ 上一致连续，则有 $\forall \epsilon_2>0,\ \exists \delta'>0, \forall |x-y|<\delta'\Rightarrow |f(x)-f(y)|<\epsilon_2$

取 $\epsilon_2=\frac{\epsilon_1}{b-a},\delta=\delta'$ 

则有 $\sum_{i=1}^n\omega_i\Delta x_i<\sum_{i=1}^n\epsilon_2\Delta x_i=\epsilon_2\sum_{i=1}^n\Delta x_i=\frac{\epsilon_1}{b-a}(b-a)=\epsilon_1$

*** 推论2

若 $f(x)$ 在闭区间 $[a,b]$ 单调，则 $f(x)$ 必可积

**** 证明

因为单调有界，则 $f(a)\leq f(x)\leq f(b),x\in[a,b]$ 故有 $0\leq f(x_1)-f(x_2)\leq f(b)-f(a),x_2>x_1,\{x_2,x_2\}\subset[a,b]$

且 $\sum_{i=1}^n\omega_i=\sum_{i=1}^n(f(x_i)-f(x_{i-1}))=f(x_n)-f(x_0)=f(b)-f(a)$

$\forall \epsilon>0$ 取 $\lambda=\frac{\epsilon}{2[f(b)-f(a)]}$ 

则有 $\sum_{i=1}^n\omega_i\Delta x_i\leq\sum_{i=1}^n\omega_i\frac{\epsilon}{2[f(b)-f(a)]}=\frac{\epsilon}{f(b)-f(a)}\sum_{i=1}^n\omega_i=\frac{\epsilon}{2[f(b)-f(a)]}[f(b)-f(a)]=\frac{\epsilon}{2}<\epsilon$

** <<MK2>>定积分可积充要条件3:

*** 描述:

\begin{aligned}
&\omega_i=M_i-m_i \\
&\forall \epsilon > 0, \exists P:\ \sum_{i=1}^n \omega_i \Delta x_i < \epsilon \Leftrightarrow\forall P: \lim_{\lambda \to 0} \sum_{i=1}^n \omega_i \Delta x_i = 0
\end{aligned}

*** 证明充分:

**** 准备工作:

假设 $P^*$ 为在分点 $P$ 上增加分点，根据[[L1][定理1]] (增加分点，大和不增，小和不减):

\begin{aligned}
&\sum_{i=1}^n M_i \Delta x_i \geq \sum_{j=1}^{n^*} M^*_j \Delta x^*_j\\
&-\sum_{i=1}^n m_i \Delta x_i \geq -\sum_{j=1}^{n^*} m^*_j \Delta x^*_j\\
&\Rightarrow \sum_{i=1}^n M_i \Delta x_i-\sum_{i=1}^n m_i \Delta x_i \geq \sum_{j=1}^{n^*} M^*_j \Delta x^*_j -\sum_{j=1}^{n^*} m^*_j \Delta x^*_j\\
&\Rightarrow \sum_{i=1}^n \omega_i \Delta x_i \geq \sum_{j=1}^{n^*} \omega^*_j \Delta x^*_j
\end{aligned}

且:

\begin{aligned}
&\omega_i=M_i-m_i \geq 0
\end{aligned}

**** 证明:

$\forall \epsilon >0,\ \exists P'\Rightarrow 0 \leq \sum_{i=1}^{n'} \omega_i \Delta x'_i < \frac{\epsilon}{2}$

$P': a=x'_1<x'_2<...<x'_{n'}=b$

取值: $\delta=\min\left\{\Delta x'_i, \frac{\epsilon}{2(n'-1)(M-m)}\right\}$

$\forall P\ (\lambda<\delta)\text{,\ } P: a=x_1<x_2<...<x_n$

构造分点: $P^*: a=x^*_0<x^*_1<...<x_{n^*}^*,\ \ \{x_i^*\} = \{x_i,x'_i \}$

因为 $\Delta x'_i \geq \lambda \geq \Delta x_i$ 故对于一个区间 $\left[x_{i-1},x_i\right]$ 中，$P^*$ 最多比 $P$ 增加一个分点 $x'_j$ , 且最多 $n'-1$ 个区间内可插入新的分点, 所以:

\begin{aligned}
\sum_{i=1}^n \omega_i \Delta x_i - \sum_{j=1}^{n^*} \omega^*_j \Delta x^*_j &= \sum_{i=1}^n \omega_i(x_i-x_{i-1}) - \sum_{j=1}^{n^*} \omega^*_j(x^*_j-x^*_{j-1}) \\
                                  &= \sum_{i:\exists x_{i-1}<x^*_j<x_i}\left\{ \omega_i(x_i-x_{i-1}) - \omega_{ij}(x^*_j-x_{i-1}) - \omega_{ji}(x_i-x^*_j)\right\} \\
                                  &\leq \sum_{i:\exists x_{i-1}<x^*_j<x_i} \left\{\omega_i(x_i-x_{i-1})\right\} \\
                                  &\leq \sum_{i:\exists x_{i-1}<x^*_j<x_i} \left\{(M-m)\Delta x_i \right\} \\
                                  &\leq \sum_{i:\exists x_{i-1}<x^*_j<x_i} \left\{\frac{\epsilon}{2(n'-1)} \right\} \\
                                  &\leq \frac{\epsilon}{2}
\end{aligned}

组合上列条件:

\begin{aligned}
\sum_{i=1}^n \omega_i \Delta x_i &=\left\{\sum_{i=1}^n \omega_i \Delta x_i-\sum_{i=1}^{n^*} \omega^*_i \Delta x^*_i \right\} + \left\{\sum_{i=1}^{n^*} \omega^*_i \Delta x^*_i - \sum_{i=1}^{n'} \omega'_i \Delta x_i \right\} + \left\{\sum_{i=1}^{n'} \omega'_i \Delta x_i-0\right\}\\
                                 &\leq \frac{\epsilon}{2} + 0 + \frac{\epsilon}{2} + 0 \\
                                 &= \epsilon
\end{aligned}

所以:

\begin{aligned}
&\left\{ \forall \epsilon > 0, \exists P:\ \sum_{i=1}^n \omega_i \Delta x_i < \epsilon \right\} \Rightarrow \left\{ \forall \epsilon>0,\ \exists \delta,\ \forall \lambda<\delta \Rightarrow \forall P:\ \sum_{i=1}^n \omega_i \Delta x_i \leq \epsilon \right\}
\end{aligned}

*** 证明必要

由[[MK1][可积充要条件2]]可知定积分可积 $\Rightarrow \lim_{\lambda \to 0} \sum_{i=1}^n \omega_i \Delta x_i = 0$

故写出详细定义 $\forall \epsilon>0, \exists \delta, \forall \lambda<\delta\Rightarrow \forall P(\lambda<\delta),\left|\sum_{i=1}^n \omega_i \Delta x_i-0\right|<\epsilon$

且因为 $\omega_i\geq0$ 则有 $\forall\epsilon>0 \exists P(\lambda<\delta)\Righarrow \sum_{i=1}^n \omega_i \Delta x_i<\epsilon$

*** 推论

函数 $f(x)$ 在闭区间 $[a,b]$ 上只有 $k<\infty$ 个不连续点，则 $f(x)$ 必可积

**** 证明

假设不连续点为 $x^*_1<x^*_2<...<x^*_k$ 则有

$\sum_{i=1}^n \omega_i \Delta x_i=\sum_{i=1}^k \omega^*_i \Delta x_i+\sum_{1\leq i\leq n,\{x^*_i\}\cap \{[x_{i-1},x_i]\}=\varnothing }\omega_i \Delta x_i$

当 $\lambda<\delta'=\frac{\epsilon}{2k(M-m)}$ 时则有 

\begin{aligned}
&\forall P\Rightarrow\sum_{i=1}^k \omega^*_i \Delta x_i\leq (M-m)\sum_{i=1}^k \Delta x_i<(M-m)k\frac{\epsilon}{2k(M-m)}\\
\therefore & \sum_{i=1}^k \omega^*_i \Delta x_i<\frac{\epsilon}{2k(M-m)},\forall P\\
\end{aligned}

另外 $\sum_{1\leq i\leq n,\{x^*_i\}\cap \{[x_{i-1},x_i]\}=\varnothing }\omega_i \Delta x_i$ 可视为为多个连续函数的黎曼和

假设包含 $x^*_j$ 包含在划分 $[x_{l_j},x_{u_j}]$ 中 $u_0=0,l_{k+1}=n$ 则

\begin{aligned}
&\sum_{1\leq i\leq n,\{x^*_i\}\cap \{[x_{i-1},x_i]\}=\varnothing }\omega_i \Delta x_i=\sum_{j=1}^{k+1}\left\{\sum_{i=u_{j-1}}^{l_j} \omega_i \Delta x_i\right\}\\
\end{aligned}

其中，任何一个 $\sum_{i=u_{j-1}}^{l_j} \omega_i \Delta x_i$ 可看成在 $[x_{u_{j-1}},x_{l_j}]$ 上的连续函数，则根据[[MK3][推论1]]以及[[MK1][可积充要条件2]] $\forall \epsilon>0,\exists \delta_j,\forall \lambda<\delta_j\Rightarrow \forall P,\sum_{i=u_{j-1}}^{l_j} \omega_i \Delta x_i<\frac{\epsilon}{2(k+1)}$

则当 $\lambda<min(\delta_j)$ 时

\begin{aligned}
\sum_{1\leq i\leq n,\{x^*_i\}\cap \{[x_{i-1},x_i]\}=\varnothing }\omega_i \Delta x_i&=\sum_{j=1}^{k+1}\left\{\sum_{i=u_{j-1}}^{l_j} \omega_i \Delta x_i\right\}\\
&<\sum_{j=1}^{k+1}\left\{\frac{\epsilon}{2(k+1)}\right\}\\
&=\frac{\epsilon}{2(k+1)}(k+1)\\
&=\frac{\epsilon}{2}\\
\end{aligned}

故当 $\lambda<min(\delta',min(\delta_j))$ 时

\begin{aligned}
\sum_{i=1}^n \omega_i \Delta x_i&=\sum_{i=1}^k \omega^*_i \Delta x_i+\sum_{1\leq i\leq n,\{x^*_i\}\cap \{[x_{i-1},x_i]\}=\varnothing }\omega_i \Delta x_i\\
&=\sum_{i=1}^k \omega^*_i \Delta x_i+\sum_{j=1}^{k+1}\left\{\sum_{i=u_{j-1}}^{l_j} \omega_i \Delta x_i\right\}\\
&<\frac{\epsilon}{2}+\frac{\epsilon}{2}\\
&=\epsilon\\
\end{aligned}

* 定积分基本性质

** <<MK5>>线性

*** 描述

若 $f(x),g(x)$ 在区间 $[a,b]$ 上可积，则有 $\int_a^b Af(x)+Bg(x)dx$ 在 $[a,b]$ 上也可积且 $\int_a^b Af(x)+Bg(x)dx=A\int_a^b f(x)dx+B\int_a^b g(x)dx$

*** 证明

$\forall (P,\ \xi_i)$ 写出黎曼和为 $\lim_{\lambda \to 0}\sum_{i=1}^n [Af(\xi_i)+Bg(\xi_i)]\Delta x_i$

根据极限四则运算 $\lim_{\lambda \to 0}{\sum_{i=1}^n [Af(\xi_i)+Bg(\xi_i)]\Delta x_i}=A\lim_{\lambda \to 0}\sum_{i=1}^n f(\xi_i) \Delta x_i+B\lim_{\lambda \to 0}\sum_{i=1}^n g(\xi_i) \Delta x_i$ 

又因为 $f(x),g(x)$ 在区间 $[a,b]$ 上可积，则黎曼和收敛，故 $\int_a^b \{Af(x)+Bg(x)\}dx$ 亦可积 

故写成 $\int_a^b \{Af(x)+Bg(x)\}dx=A\int_a^b f(x)dx+B\int_a^b g(x)dx$

*** 推论

若 $f(x)$ 在区间 $[a,b]$ 上可积， $g(x)$ 仅在有限点与 $f(x)$ 取值不同，则 $g(x)$ 也在 $[a,b]$ 上可积且 $\int_a^b f(x) dx=\int_a^b g(x)dx$

**** 证明

假设不连续点为 $x^*_1<x^*_2<...<x_h<...<x^*_k$ 则 $\forall (P,\xi_i)$ 写出两式相减黎曼和 $\sum_{i=1}^n \left\{f(\xi_i)-g(\xi_i)\right\}\Delta x_i$

假设 $\{x_{v_j}|0\leq j\leq u,j\in N^+\}=\{\xi_i\}\cap\{x^*_h\}$ 故 $u\leq k$ 则有 

\begin{aligned}
\sum_{i=1}^n \left\{f(\xi_i)-g(\xi_i)\right\}\Delta x_i&=\sum_{j=1}^u \left\{f(\xi_{v_j})-g(\xi_{v_j})\right\}\Delta x_{v_j}
\end{aligned}

定义 $M=max\{|f(x)-g(x)|\}$ 故 $\forall \epsilon>0$ 取 $\delta=\frac{\epsilon}{kM}$ 故 $\forall \lambda<\delta$ 有 

\begin{aligned}
&\left|\sum_{j=1}^u \left\{f(\xi_{v_j})-g(\xi_{v_j})\right\}\Delta x_{v_j}\right|\leq \sum_{j=1}^u \left|f(\xi_{v_j})-g(\xi_{v_j})\right|\Delta x_{v_j}\\
&\leq \sum_{j=1}^u M\Delta x_{v_j}< \sum_{j=1}^u M\frac{\epsilon}{kM}=uM\frac{\epsilon}{kM}\leq kM\frac{\epsilon}{kM}\\
&=\epsilon\\
\end{aligned}

综上所述 $\forall \epsilon>0, \exists \delta, \forall \lambda<\delta\Rightarrow \forall(P,\xi_i),\left|\sum_{i=1}^n \left\{f(\xi_i)-g(\xi_i)\right\}\Delta x_i-0\right|<\epsilon$ 即为 $f(x)-g(x)$ 在 $[a,b]$ 上可积，且积分为 $0$ 的定义

则记作 $\int_a^b f(x)-g(x) dx=0$ 又根据定积分线性性质 $f(x),f(x)-g(x)$ 可积，则 $f(x)+g(x)-f(x)=g(x)$ 也可积

且 $\int_a^b f(x)+g(x)-f(x)dx=\int_a^b g(x)dx=\int_a^b f(x)dx+\int_a^b f(x)-g(x)dx=\int_a^b f(x)dx$

** 乘积可积

若 $f(x),g(x)$ 在 $[a,b]$ 上可积，则 $f(x)g(x)$ 在 $[a,b]$ 上也可积

*** 证明

若 $f(x),g(x)$ 在 $[a,b]$ 上可积，根据[[MK4][定积分定义推论]] $f(x),g(x)$ 必有界，假设 $|f(x)|\leq M,|g(x)|\leq M$

则有

\begin{aligned}
&\forall x_1,x_2\in [a,b]\\
&\Rightarrow\\ 
&|f(x_1)g(x_1)-f(x_2)g(x_2)|\\
&=|f(x_1)g(x_1)-f(x_1)g(x_2)+f(x_1)g(x_2)-f(x_2)g(x_2)|\\
&\leq|f(x_1)||g(x_1)-g(x_2)|+|g(x_2)||f(x_1)-f(x_2)|\\
&\leq M[|g(x_1)-g(x_2)|+|f(x_1)-f(x_2)|]$
\end{aligned}

定义在区间 $[x_{i-1},x_i]$ 中 $f(x)g(x)$ 当 $\omega_i=f(x_{i_M})g(x_{i_M})-f(x_{i_m})g(x_{i_m}),\omega_i^f,\omega_i^g$ 分别为函数 $f(x)g(x),f(x),g(x)$ 的振幅，则

\begin{aligned}
&\lim_{\lambda \to 0} \sum_{i=1}^n \omega_i \Delta x_i=\lim_{\lambda \to 0} \sum_{i=1}^n [f(x_{i_M})g(x_{i_M})-f(x_{i_m})g(x_{i_m})] \Delta x_i\\
&=\lim_{\lambda \to 0} \sum_{i=1}^n [|f(x_{i_M})g(x_{i_M})-f(x_{i_m})g(x_{i_m})|] \Delta x_i\\
&\leq \lim_{\lambda \to 0} \sum_{i=1}^n M[|f(x_{i_M})-f(x_{i_m})|+|g(x_{i_M})-g(x_{i_m})|] \Delta x_i\\
&=M\left\{ \lim_{\lambda \to 0} \sum_{i=1}^n|f(x_{i_M})-f(x_{i_m})|\Delta x_i+\lim_{\lambda \to 0} \sum_{i=1}^n|g(x_{i_M})-g(x_{i_m})|\Delta x_i\right\}\\
\because &|f(x_{i_M})-f(x_{i_m})|\leq \omega_i^f,|g(x_{i_M})-g(x_{i_m})|\leq \omega_i^g\\
\therefore &\lim_{\lambda \to 0} \sum_{i=1}^n \omega_i \Delta x_i\\
&\leq M\left\{ \lim_{\lambda \to 0} \sum_{i=1}^n|f(x_{i_M})-f(x_{i_m})|\Delta x_i+\lim_{\lambda \to 0} \sum_{i=1}^n|g(x_{i_M})-g(x_{i_m})|\Delta x_i\right\}\\
&\leq M\left\{ \lim_{\lambda \to 0} \sum_{i=1}^n\omega_i^f\Delta x_i+\lim_{\lambda \to 0} \sum_{i=1}^n\omega_i^g\Delta x_i\right\}\\
\end{aligned}

因为 $f(x),g(x)$ 可积，则根据[[MK1][定积分可积充要条件2]] $\lim_{\lambda \to 0} \sum_{i=1}^n\omega_i^f\Delta x_i=\lim_{\lambda \to 0} \sum_{i=1}^n\omega_i^g\Delta x_i=0$ 故有

$0\leq\lim_{\lambda \to 0} \sum_{i=1}^n \omega_i \Delta x_i\leq M\left\{ \lim_{\lambda \to 0} \sum_{i=1}^n\omega_i^f\Delta x_i+\lim_{\lambda \to 0} \sum_{i=1}^n\omega_i^g\Delta x_i\right\}=M\left\{0+0\right\}=0$

根据夹逼定理 $\lim_{\lambda \to 0} \sum_{i=1}^n \omega_i \Delta x_i=0$ 同样根据[[MK1][定积分可积充要条件2]]可得 $f(x)g(x)$ 可积

** <<MK8>>保序

若 $f(x),g(x)$ 在 $[a,b]$ 上可积，且有 $f(x)\geq g(x),x\in [a,b]$ 则有 $\int_a^b f(x) dx\geq \int_a^b g(x) dx$

*** 证明

根据[[MK5][线性性质]] $\int_a^b f(x) dx-\int_a^b g(x) dx=\int_a^b [f(x)-g(x)] dx$ 且 $f(x)-g(x)\geq 0$ 故推出 $\int_a^b f(x) dx-\int_a^b g(x) dx=\int_a^b [f(x)-g(x)] dx\geq 0\Rightarrow \int_a^b f(x) dx\geq \int_a^b g(x) dx$

** 绝对可积

若 $f(x)$ 在 $[a,b]$ 上可积则 $|f(x)|$ 在 $[a,b]$ 上也可积，且有 $\left|\int_a^b f(x)dx\right|\leq\int_a^b|f(x)|dx$

*** 证明

**** 证明可积

$f(x)$ 可积，则根据[[MK1][定积分可积充要条件2]] $\lim_{\lambda \to 0} \sum_{i=1}^n \omega_i^f \Delta x_i = 0$

定义 $g(x)=|f(x)|$ 则有 $\omega_i^g\leq \omega_i^f\Rightarrow 0\leq\lim_{\lambda \to 0} \sum_{i=1}^n \omega_i^g \Delta x_i\leq \lim_{\lambda \to 0} \sum_{i=1}^n \omega_i^f \Delta x_i=0$

根据夹逼定理 $\lim_{\lambda \to 0} \sum_{i=1}^n \omega_i^g \Delta x_i=0$ 根据[[MK1][定积分可积充要条件2]] $g(x)=|f(x)|$ 可积

**** 证明不等式

由于 $-|f(x)|\leq f(x)\leq|f(x)|$ 故根据[[MK8][保序性]]可得 $\int_a^b-|f(x)|dx\leq \int_a^b f(x)dx\leq\int_a^b|f(x)|dx$

根据[[MK5][线性]] $-\int_a^b|f(x)|dx\leq \int_a^b f(x)dx\leq\int_a^b|f(x)|dx\Rightarrow \left|\int_a^b f(x)dx\right|\leq\int_a^b|f(x)|dx$

** <<MK7>>区间可加

（1）若 $f(x)$ 在 $[a,b]$ 上可积，对于任意 $c\in[a,b]$ , $f(x)$ 在 $[a,c],[c,b]$ 上都可积

（2）若 $f(x)$ 在 $[a,c],[c,b]$ 上都可积，则有 $\int_a^b f(x)dx=\int_a^c f(x)dx+\int_c^b f(x)dx$

*** 证明

**** 证明（1）

根据[[MK1][定积分可积充要条件2]]， $f(x)$ 在 $[a,b]$ 上可积可有 $\forall P\Rightarrow \lim_{\lambda \to 0} \sum_{i=1}^n \omega_i \Delta x_i = 0$

即 $\forall \epsilon>0,\exists \delta,\forall \lambda<\delta\Rightarrow \forall P,\sum_{i=1}^n \omega_i \Delta x_i<\epsilon$

则存在 $P$ 其中1个分点正好为 $C$ ，表述为 $\forall \epsilon >0,\exists P\Rightarrow \sum_{i=1}^k \omega_i \Delta x_i+\sum_{i=k+1}^n \omega_i \Delta x_i<\epsilon$

其中 $x_k=c$ 又因为 $\sum_{i=1}^k \omega_i \Delta x_i>0,\sum_{i=k+1}^n \omega_i \Delta x_i>0$ 故有 

$\forall \epsilon >0,\exists P\Rightarrow \sum_{i=1}^n \omega_i \Delta x_i<\epsilon$ 对于 $x\in[a,c]$

$\forall \epsilon >0,\exists P\Rightarrow \sum_{i=1}^n \omega_i \Delta x_i<\epsilon$ 对于 $x\in[c,b]$

根据[[MK2][定积分可积充要条件3]]推出 $f(x)$ 在 $[a,c],[c,b]$ 上都可积

**** 证明（2）

因为 $f(x)$ 在 $[a,c],[c,b]$ 上可积，则根据[[MK1][定积分可积充要条件2]] 

$\forall \epsilon >0,\exists \delta,\forall \lambda<\delta\Rightarrow \forall P_1, \sum_{i=1}^n \omega_i \Delta x_i<\frac{\epsilon}{2}$ 对于 $x\in[a,c]$

$\forall \epsilon >0,\exists \delta,\forall \lambda<\delta\Rightarrow \forall P_2, \sum_{i=1}^n \omega_i \Delta x_i<\frac{\epsilon}{2}$ 对于 $x\in[c,b]$

则 $\forall \epsilon >0,\exists P\Rightarrow \forall P, \sum_{i=1}^n \omega_i \Delta x_i=\sum_{i=1}^k \omega_i \Delta x_i+\sum_{i=k+1}^n \omega_i \Delta x_i<\frac{\epsilon}{2}+\frac{\epsilon}{2}=\epsilon$ 当 $P$ 的划分为上述 $P_1,P_2$ 的组合时 

故根据[[MK2][定积分可积充要条件3]]推出 $f(x)$ 在 $[a,b]$ 可积

**** 证明 $\int_a^b f(x)dx=\int_a^c f(x)dx+\int_c^b f(x)dx$

根据定积分定义，$\lim_{\lambda \to 0}{\sum_{i=1}^n f(\xi_i)\Delta x_i} = I$ 与划分 $P$ 取点 $\xi_i$ 无关

已经证明 $f(x)$ 在 $[a,b]$ 可积，故 $\lim_{\lambda \to 0}{\sum_{i=1}^n f(\xi_i)\Delta x_i} = I$ 对于任意划分与取点成立

取一类划分 $P'=\{x_i^{'}\}$ 使得其中一点 $x_k^{'}=c$ 则根据极限四则运算，上式可写成

\begin{aligned}
\lim_{\lambda \to 0}{\sum_{i=1}^n f(\xi_i^{'})\Delta x_i^{'}}&=\lim_{\lambda \to 0}\left\{\sum_{i=1}^k f(\xi_i^{'} )+\sum_{i=k+1}^n f(\xi_i^{'})\right\}\Delta x_i^{'}\\
&=\lim_{\lambda \to 0}\sum_{i=1}^k f(\xi_i^{'})\Delta x_i^{'}+\lim_{\lambda \to 0}\sum_{i=k+1}^n f(\xi_i^{'})\Delta x_i^{'}\\
\end{aligned}

根据积分定义 

\begin{aligned}
&\lim_{\lambda \to 0}{\sum_{i=1}^n f(\xi_i^{'})\Delta x_i^{'}}=\int_a^b f(x)dx\\
&\lim_{\lambda \to 0}\sum_{i=1}^k f(\xi_i^{'})\Delta x_i^{'}=\int_a^c f(x) dx\\
&\lim_{\lambda \to 0}\sum_{i=k+1}^n f(\xi_i^{'})\Delta x_i^{'}=\int_c^b f(x)dx\\
\end{aligned}

故推出 $\int_a^b f(x)dx=\int_a^c f(x)dx+\int_c^b f(x)dx$

* 牛顿莱布尼茨公式

** <<L1>>定理1:

*** 描述:

设 $f(x)$ 在 $[a,b]$ 上可积，构造函数:

$F(x)=\int_a^x f(t) dt$

则:

(1) $F(x)$ 在 $[a,b]$ 上连续;
(2) 若 $f(x)$ 连续，则 $F(x)$ 可导，且导数为 $F'(x)=f(x)$

*** 证明连续:

根据[[MK7][积分可加性]]及[[e:/OneDrive/大学物理/Note/DiffEq.org][闭区间连续函数-连续函数定义]]:

\begin{aligned}
&\lim_{\Delta x \to 0}F(x+\Delta x)-F(x)\\
&=\lim_{\Delta x \to 0}\int_a^{x+\Delta x} f(t) dt - \int_a^{x} f(t) dt\\
&=0
\end{aligned}

*** 证明导数:

根据[[e:/OneDrive/数学分析/Note/Chapter 8/Chap8Note.org][积分中值定理-第一积分中值定理]]:

\begin{aligned}
&F(x+\Delta x)-F(x)\\
&=\int_a^{x+\Delta x} f(t) dt - \int_a^{x} f(t) dt\\
&=\int_x^{x+\Delta x} f(t) dt\\
&=f(\xi) \Delta x,\ \ \xi \in [x,x+\Delta x]\\
&\Rightarrow\\
&\frac{F(x+\Delta x)-F(x)}{\Delta x}=f(\xi)\\
&\lim_{\Delta x \to 0}\frac{F(x+\Delta x)-F(x)}{\Delta x}=\lim_{\Delta x \to 0}f(\xi)\\
&\Rightarrow F'(x)=f(x)
\end{aligned}

** 牛顿莱布尼茨公式：

*** 描述：

若 $F(x)$ 是 $f(x)$ 的一个原函数，$f(x)$ 连续则：

$\int_a^b f(x) dx=F(b)-F(a)$

*** 证明：

根据[[L1][定理1]]及积分可加性：

\begin{aligned}
& (F(x)+C)'=\left(\int_t^x f(t) dt+C\right)'=f(x)\\
& \int_a^b f(x) dx = \left[\int_t^b f(x) dx + C\right] - \left[ \int_t^a f(x) dx + C  \right]\\
& = \int_t^b f(x) dx - \int_t^a f(x) dx\\ 
& = F(b)-F(a)
\end{aligned}

又因为 $\left\{\int f(t) dt\right\}'=f(t)$ 则 $\int f(t) dt$ 满足原函数条件，可作为 $F(x) =\int f(t) dt$

* 函数一致连续：

** 函数极限定义

若满足：

\begin{aligned}
\forall \epsilon>0,\ \exists \delta,\ \forall |x-x_0|<\delta \Rightarrow |f(x)-A|<\epsilon
\end{aligned}

则 $\lim_{x\to x_0}f(x_0)=A$ 根据定义 $A$ 为有界实数。

** 连续函数定义

\begin{aligned}
f(x_0)=\lim_{x\to x_0}f(x)
\end{aligned}

** 一致性连续定义

\begin{aligned}
&\forall \epsilon>0,\ \exists \delta>0, \forall |x-y|<\delta\Rightarrow |f(x)-f(y)|<\epsilon
\end{aligned}

** 有界性定理

*** 描述：

若函数 $f(x)$ 在闭区间 $[a,b]$ 上连续，则他在 $[a,b]$ 上有界。

*** 证明：

根据闭区间套定理，取闭区间套集合 $\{[a_n,b_n]\}$ 包含 $f(x)$ 无界部分，且 $\xi =\lim_{n\to\infty}a_n=\lim_{n\to\infty}b_n$

由于 $f(x)$ 在 $\xi$ 点连续，则 $\lim_{x\to\xi}f(x)=f(\xi)$ 根据函数极限定义 $f(\xi)$ 为有界实数，与无界假设冲突。

** <<K3>>康托定理（闭区间连续函数一定一致连续）

*** 描述：

若函数 $f(x)$ 在闭区间 $[a,b]$ 上连续，则 $f(x)$ 在 $[a,b]$ 上一致连续。

*** 证明：

一致连续定义：

\begin{aligned}
&\forall \epsilon>0,\ \exists \delta, \forall |x-y|<\delta\ \&\ x,y\in [a,b]\Rightarrow |f(x)-f(y)|<\epsilon
\end{aligned}

故用反证法，则：

\begin{aligned}
&\exists \epsilon>0,\ \forall \delta>0, \exists |x-y|<\delta\ \&\ x,y\in [a,b]\Rightarrow |f(x)-f(y)|>\epsilon
\end{aligned}

当 $\delta=\frac{1}{n},\ n\in N^+$ 时，存在点列 $x_n,y_n\in[a,b]:|x_n-y_n|<\frac{1}{n},\ |f(x_n)-f(y_n)|>\epsilon$

根据[[E:\OneDrive\数学分析\Note\Chapter 9\Series.org][Bolzano-Weierstrass定理]]，有界数列 $x_n$ 必有收敛子列，得出 $\lim_{n_k\to\infty}x_{n_k}=\xi,\ \xi\in[a,b]$ ，与之对应 $y_{n_k}$ 使得 $|f(x_{n_k})-f(y_{n_k})|>\epsilon$

又因为 $\lim_{n_k\to\infty}\frac{1}{n_k}=0,\ 0<|x_{n_k}-y_{n_k}|<\frac{1}{n_k}$ ，根据夹逼定理 $\lim_{n_k\to\infty} |x_{n_k}-y_{n_k}|=0$ 根据极限四则运算 $\lim_{n_k\to\infty}x_{n_k}=\lim_{n_k\to\infty}y_{n_k}=\xi$ 

由于 $f(x)$ 在 $\xi$ 点有定义且连续，即 $\lim_{n_k\to\infty}f(x_{n_k})=\lim_{n_k\to\infty}f(y_{n_k})=f(\xi)$ 

故 $\lim_{n_k\to\infty}f(x_{n_k})-f(y_{n_k})=0$ 即： $\forall \epsilon>0,\ \exists N>0, \forall n_k>N \Rightarrow |f(x_{n_k})-f(y_{n_k})|<\epsilon$

故与之前矛盾。

* 定积分换元法

** 描述

已有定积分 $\int_a^b f(x)dx$ ，若 $x=G(y),\ \frac{dx}{dy}=g(y)$ ，且 $g(y)$ 在 $y\in [c,d]$ 中连续，$f(x)$ 有界，则 $\int_a^b f(x)dx=\int_c^d f[G(y)]g(y)dy$ 

其中 $a=G(c),b=G(d)$

** 证明

*** 条件1：

因为 $g(y)$ 在闭区间内连续，根据[[K3][康托定理]]故有 

$\forall \epsilon>0,\ \exists T>0,\ \forall |\xi-y|<T\ \&\ y\in[c,d] \Rightarrow |g(\xi)-g(y)|<\epsilon$

*** 条件2：

因为 $\frac{dx}{dy}=g(y)$ 根据微分定义则有 $g(y)=\lim_{\Delta y\to 0}\frac{G(y+\Delta y)-G(y)}{\Delta y}$ ，类似于[[K3][康托定理]]可写出反证法条件:

\begin{aligned}
\exists \eplison>0,\forall T'>0, \exists 0<y-y'<T', y,y'\in [c,d]\Rightarrow \left|g(y)-\frac{G(y+\Delta y)-G(y)}{\Delta y}\right| >\epsilon
\end{aligned}

以证明其不成立，故继续写出极限定义：

\begin{aligned}
&\forall \epsilon>0,\ \exists T'>0,\ \forall 0<\Delta y<T'\ \&\ y\in [c,d]\Rightarrow \left|g(y)-\frac{G(y+\Delta y)-G(y)}{\Delta y}\right| < \epsilon\\
\end{aligned}

*** <<K1>>结合条件1，2：

\begin{aligned}
&\forall \epsilon>0,\ \exists K=min(T,T'),\ \forall 0<\Delta y<T'\ \&\ |\xi-y|<K\ \&\ y\in [c,d]\\
&\Rightarrow \left|g(y)-\frac{G(y+\Delta y)-G(y)}{\Delta y}\right| < \epsilon\\
&\Rightarrow |g(\xi)-g(y)|<\epsilon\\
\therefore & \left|g(y)\Delta y-[G(y+\Delta y)-G(y)]\right| < \epsilon \Delta y\\
\therefore & |g(\xi)\Delta y-g(y)\Delta y|<\epsilon \Delta y\\
\therefore & \left|g(\xi)\Delta y-[G(y+\Delta y)-G(y)]\right|\leq \left|g(y)\Delta y-[G(y+\Delta y)-G(y)]\right|+|g(\xi)\Delta y-g(y)\Delta y|<2\epsilon \Delta y
\end{aligned}

故可得结论:

\begin{aligned}
&\forall \epsilon>0,\ \exists K>0,\ \forall 0<\Delta y<T'\ \&\ |\xi-y|<K\ \&\ y\in [c,d]\\
&\Rightarrow \left|g(\xi)\Delta y-[G(y+\Delta y)-G(y)]\right|<2\epsilon \Delta y
\end{aligned}

*** 写出换元法前后积分黎曼和：

\begin{aligned}
&\lim_{\lambda\to0} \sum_{i=0}^n f(\xi_{i}) \Delta x_i=I\\
&\lim_{\lambda\to0} \sum_{i=0}^n f(G(\xi_{i})) g(\xi_{i}) \Delta y_i\\
\end{aligned}

由于 $x=G(y)$ 为映射关系，故 $y$ 只有单一 $x$ 值与其对应， $x$ 可对应多个 $y$ 值。

*此处先考虑 $x$ 只对应一个 $y$ 值的情况，即 $G(y)$ 严格单调* ，若成立，则<<K2>>:

(1) 假设当 $y$ 的积分路径为 $[u,v],\ [v,w]$ 时， $x$ 取值 $[x_1,x_2],\ [x_2,x_1]$  

(2) 则通过单一对应成立有 $\int_{x_1}^{x_2} f(x) dx=\int_u^v f[G(y)]g(y)dy$ 及 $\int_{x_2}^{x_1} f(x) dx=\int_v^w f[G(y)]g(y)dy$

(3) 故有 $\int_u^w f[G(y)]g(y)dy=\int_u^v f[G(y)]g(y)dy+\int_v^w f[G(y)]g(y)dy=\int_{x_1}^{x_2} f(x) dx+\int_{x_2}^{x_1} f(x) dx=0$

(4) 若 $G(y)$ 在区间内保持不变，则导数 $g(y)$ 为0。

*** 证明极限相减等于零：

由于定积分可积条件为黎曼和与取点和划分无关，且 $x,\ y$ 一一对应，故对于任意划分 $P_y$ 必有 $P_x$ 与之对应，对于任意 $\xi_{yi}$ 必有 $\xi_{xi}$ 与之对应

故对于任意划分 $P_y:c=y_0<y_1..<y_n=d$ ，取对应划分 $P_x:x_i=G(y_i)$ ，对于任意取点 $\xi_{yi}\in[y_i,y_{i+1}]$ 取对应取点 $\xi_{xi}=G(\xi_{yi})$

根据极限可加性:

\begin{aligned}
&\lim_{\lambda\to0} \sum_{i=0}^n f(G(\xi_{yi})) g(\xi_{yi}) \Delta y_i-\lim_{\lambda\to0} \sum_{i=0}^n f(\xi_{xi}) \Delta x_i\\
&=\lim_{\lambda\to0}\left\{\sum_{i=0}^n f(G(\xi_{yi})) g(\xi_{yi}) \Delta y_i-\sum_{i=0}^n f(\xi_{xi}) \Delta x_i\right\}\\
&=\lim_{\lambda\to0}\sum_{i=0}^n f(\xi_{xi})\left\{g(\xi_{yi}) \Delta y_i-\Delta x_i\right\}\\
&=\lim_{\lambda\to0}\sum_{i=0}^n f(\xi_{xi})\left\{g(\xi_{yi}) \Delta y_i-[G(y_i+\Delta y_i)-G(y_i)]\right\}\\
\end{aligned}

假设 $M=max(|f(x)|),\ x\in[a,b]$ ，根据[[K1][之前证明]]:

\begin{aligned}
&\forall \epsilon'=\frac{\epsilon}{2M(d-c)}>0,\ \exists K'>0,\ \forall 0<\Delta y<T'\ \&\ |\xi-y|<K\ \&\ y\in [c,d]\\
&\Rightarrow \left|g(\xi)\Delta y-[G(y+\Delta y)-G(y)]\right|<2\epsilon' \Delta y=\frac{\epsilon}{M(d-c)}\Delta y\\
\end{aligned}

故有:

\begin{aligned}
&\forall \epsilon>0,\ \exists \delta=K'>0,\ \forall 0<\lambda<\delta\\
\Rightarrow &\left|\sum_{i=0}^n f(\xi_{xi})\left\{g(\xi_{yi}) \Delta y_i-[G(y_i+\Delta y_i)-G(y_i)]\right\}\right|\\
&\leq \sum_{i=0}^n |f(\xi_{xi})|\left|g(\xi_{yi}) \Delta y_i-[G(y_i+\Delta y_i)-G(y_i)]\right|\\
&\leq M \sum_{i=0}^n\left|g(\xi_{yi}) \Delta y_i-[G(y_i+\Delta y_i)-G(y_i)]\right|\\
&< M \sum_{i=0}^n \frac{\epsilon}{M(d-c)}\Delta y\\
&=M \frac{\epsilon}{M(d-c)}\sum_{i=0}^n \Delta y\\
&=M \frac{\epsilon}{M(d-c)} (d-c)\\
&=\epsilon
\end{aligned}

所以

\begin{aligned}
&\lim_{\lambda\to0} \sum_{i=0}^n f(G(\xi_{yi})) g(\xi_{yi}) \Delta y_i-\lim_{\lambda\to0} \sum_{i=0}^n f(\xi_{xi}) \Delta x_i=0\\
\Rightarrow & \lim_{\lambda\to0} \sum_{i=0}^n f(G(\xi_{yi})) g(\xi_{yi}) \Delta y_i=\lim_{\lambda\to0} \sum_{i=0}^n f(\xi_{xi}) \Delta x_i\\
\end{aligned}

又由于对于任意划分与取点 $\lim_{\lambda\to0} \sum_{i=0}^n f(\xi_{xi}) \Delta x_i=I$

所以对于任意划分与取点的 $\lim_{\lambda\to0} \sum_{i=0}^n f(G(\xi_{i})) g(\xi_{i}) \Delta y_i=I$ 。

有根据[[K2][之前推导]]，在 $x$ 对应多个 $y$ 时，可通过积分分段分解为多个单调函数，证明上述等式任然成立。

所以有 $\int_a^b f(x)dx=\int_c^d f[G(y)]g(y)dy,\ G(c)=a,G(d)=b$ ，证毕。

* 定积分几何应用

** 三角函数正交性:

*** 定义:

\begin{align*}
\int_{-\pi}^{\pi}{sin(nx)sin(mx)}dx = \left\{
\begin{aligned}
0       & , & if & &  n{\neq}m \\
\pi     & , & if & &  n=m
\end{aligned}
\end{align*}

\begin{align*}
\int_{-\pi}^{\pi}{cos(nx)cos(mx)}dx = \left\{
\begin{aligned}
0       & , & if & &  n{\neq}m \\
\pi     & , & if & &  n=m
\end{aligned}
\end{align*}

$\int_{-\pi}^{\pi}{cos(nx)cos(mx)}dx = 0$

*** 证明:

Since:

$sin(-nx)cos(-mx) = -sin(nx)cos(mx)$
   
Thus:
   
$\int_{-\pi}^{\pi}{sin(nx)cos(mx)}dx = 0$
   
Thus:

\begin{align*}
\int_{-\pi}^{\pi}{sin(nx)sin(mx)}dx &= 2\int_{0}^{\pi}{sin(nx)sin(mx)}dx \\
                                    &= 2\int_{0}^{\pi}{cos((n-m)x) - cos((n+m)x)}dx \\
				        &= \left\{
				        \begin{aligned}
			     	        &2 \int_{0}^{\pi}{1 - cos(2x)}dx = x\bigg|_0^{\pi}-\frac{sin(2x)}{2}\bigg|_0^{\pi} = \pi	   & , & if & &  n=m \\
				        &2 \left\{ \frac{sin((n - m)x)}{n - m} - \frac{sin((n + m)x)}{n + m} \right\} \bigg|_0^{\pi}=0     & , & if & &  n{\neq}m
				        \end{aligned}
\end{align*}

同理可证:

\begin{align*}
\int_{-\pi}^{\pi}{cos(nx)cos(mx)}dx = \left\{
\begin{aligned}
0       & , & if & &  n{\neq}m \\
\pi     & , & if & &  n=m
\end{aligned}
\end{align*}

$\int_{-\pi}^{\pi}{cos(nx)cos(mx)}dx = 0$

** 光滑曲线长度:

*** <<L2>> 光滑曲线定义:

$x'(t),\ y'(t)$ 连续且 $x'(t),y'(t)$ 不同时为零

*** 定义：

\begin{aligned}
&x=x(t) \\
&y=y(t) \\
&t \in \left[T_1, T_2 \right] \\
&P: T_1=t_0<t_1<...<t_n=T_2 \\
&\Delta t_i = t_i - t_{i-1} \\
&\lambda=max(\Delta t_i)\\
&M_i^x = sup(x'(t))\,\ t \in \left[\ t_{i-1}, t_i \right]\\
&M_i^y = sup(y'(t))\,\ t \in \left[\ t_{i-1}, t_i \right]\\
&m_i^x = inf(x'(t))\,\ t \in \left[\ t_{i-1}, t_i \right]\\
&m_i^y = inf(y'(t))\,\ t \in \left[\ t_{i-1}, t_i \right]\\
&\Omega_i^x=M_i^x-m_i^x\\
&\Omega_i^y=M_i^y-m_i^y\\
\end{aligned}

*** 构造和式:

$\sum_{i=1}^n \sqrt{\left[x(t_i)-x(t_{i-1})\right]^2 + \left[y(t_i)-y(t_{i-1})\right]^2 }$

因为[[L2][光滑曲线定义]]及拉格朗日中值定理:

$x(t_i)-x(t_{i-1})=x'(\eta_i)\Delta t_i, \ \eta_i \in \left[t_{i-1},t_i \right]$

$y(t_i)-y(t_{i-1})=y'(\sigma_i)\Delta t_i, \ \sigma_i \in \left[t_{i-1},t_i \right]$

故和式

$=\sum_{i=1}^n \sqrt{x'(\eta_i)^2 + y'(\sigma_i)^2 } \Delta t_i$

*** <<L3>> 证明不等式1:

\begin{aligned}
&\left( x_1 y_2 - x_2 y_1 \right)^2 \geq 0 \\
&\Rightarrow x_1^2 y_2^2 + x_2^2 y_1^2 \geq 2x_1y_1x_2y_2 \\
&\Rightarrow x_1^2y_1^2 + x_2^2y_2^2 + x_1^2 y_2^2 + x_2^2 y_1^2 \geq x_1^2y_1^2 + x_2^2y_2^2 + 2x_1y_1x_2y_2 \\
&\Rightarrow (x_1^2 + x_2^2)(y_1^2 + y_2^2) \geq (x_1y_1 + x_2y_2)^2  \\
&\Rightarrow -2\sqrt{(x_1^2 + x_2^2)(y_1^2 + y_2^2)} \leq -2\sqrt{(x_1y_1 + x_2y_2)^2} \\
&\Rightarrow x_1^2 + x_2^2 + y_1^2 + y_2^2 - 2\sqrt{(x_1^2 + x_2^2)(y_1^2 + y_2^2)} \leq x_1^2 + x_2^2 + y_1^2 + y_2^2 - 2x_1y_1 - 2x_2y_2 \\
&\Rightarrow \left(\sqrt{(x_1^2 + x_2^2)} - \sqrt{(y_1^2 + y_2^2)}\right)^2 \leq (x_1 - y_1)^2 + (x_2 - y_2)^2 \\
&\Rightarrow \bigg| \sqrt{(x_1^2 + x_2^2)} - \sqrt{(y_1^2 + y_2^2)} \bigg| \leq \sqrt{(x_1 - y_1)^2 + (x_2 - y_2)^2} \\
\end{aligned}

*** <<L4>> 证明不等式2:

$\sqrt{(x_1 - y_1)^2 + (x_2 - y_2)^2} \leq \bigg|x_1 - y_1\bigg| + \bigg|x_2 - y_2\bigg|$

直角三角形斜边小于直角边之和，连列不等式1,2得:

$\bigg| \sqrt{(x_1^2 + x_2^2)} - \sqrt{(y_1^2 + y_2^2)} \bigg| \leq \bigg|x_1 - y_1\bigg| + \bigg|x_2 - y_2\bigg|$

*** 证明和式与黎曼和极限相等

\begin{aligned}
&\bigg| \sum_{i=1}^n \sqrt{x'(\eta_i)^2 + y'(\sigma_i)^2 } \Delta t_i - \sum_{i=1}^n \sqrt{x'(\xi_i)^2 + y'(\xi_i)^2 } \Delta t_i \bigg| \\
&=\bigg|\sum_{i=1}^n \left\{ \sqrt{x'(\eta_i)^2 + y'(\sigma_i)^2 } - \sqrt{x'(\xi_i)^2 + y'(\xi_i)^2 \right\} \Delta t_i \bigg|\\
&\leq \sum_{i=1}^n \bigg| \sqrt{x'(\eta_i)^2 + y'(\sigma_i)^2 } - \sqrt{x'(\xi_i)^2 + y'(\xi_i)^2} \bigg| \Delta t_i
\end{aligned}

根据[[L3][不等式1]]和[[L4][不等式2]]:

\begin{aligned}
&\sum_{i=1}^n \bigg|{ \sqrt{x'(\eta_i)^2 + y'(\sigma_i)^2 } - \sqrt{x'(\xi_i)^2 + y'(\xi_i)^2} \bigg| \Delta t_i \\
&\leq \sum_{i=1}^n \bigg| x'(\eta_i) - x'(\xi_i) \bigg| \Delta t_i + \sum_{i=1}^n \bigg| y'(\sigma_i) - y'(\xi_i)\bigg| \Delta t_i \\
&\leq \sum_{i=1}^n \Omega_i^x \Delta t_i + \sum_{i=1}^n \Omega_i^y \Delta t_i 
\end{aligned}

因 $x'(t),\ y'(t)$ 连续,所以 $\Rightarrow x'(t),\ y'(t)$ 可积，故当 $\lambda \to 0$ 时:

\begin{aligned}
&\forall \epsilon>0,\ \ \exists \delta,\ \ \forall \lambda<\delta\\
&\sum_{i=1}^n \Omega_i^x \Delta t_i < \frac{\epsilon}{2},\ \ \sum_{i=1}^n \Omega_i^y \Delta t_i < \frac{\epsilon}{2}\\
&\Rightarrow \bigg| \sum_{i=1}^n \sqrt{x'(\eta_i)^2 + y'(\sigma_i)^2 } \Delta t_i - \sum_{i=1}^n \sqrt{x'(\xi_i)^2 + y'(\xi_i)^2 } \Delta t_i \bigg| \leq \sum_{i=1}^n \Omega_i^x \Delta t_i + \sum_{i=1}^n \Omega_i^y \Delta t_i \leq \epsilon \\
&\Rightarrow \lim_{\lambda \to 0}\left\{\sum_{i=1}^n \sqrt{x'(\eta_i)^2 + y'(\sigma_i)^2 } \Delta t_i - \sum_{i=1}^n \sqrt{x'(\xi_i)^2 + y'(\xi_i)^2 } \Delta t_i\right\}=\lim_{\lambda \to 0}\left\{\sum_{i=1}^n \sqrt{x'(\eta_i)^2 + y'(\sigma_i)^2 } \Delta t_i\right\} - \lim_{\lambda \to 0}\left\{\sum_{i=1}^n \sqrt{x'(\xi_i)^2 + y'(\xi_i)^2 } \Delta t_i\right\}=0 \\
&\Rightarrow \lim_{\lambda \to 0}\left\{\sum_{i=1}^n \sqrt{x'(\eta_i)^2 + y'(\sigma_i)^2 } \Delta t_i\right\} = \lim_{\lambda \to 0}\left\{\sum_{i=1}^n \sqrt{x'(\xi_i)^2 + y'(\xi_i)^2 } \Delta t_i\right\} \\
\end{aligned}

*** 结论:

$L=\int_{T_1}^{T_2}\sqrt{x'(t)^2+y'(t)^2} dt$

** 几何体体积

*** 构造几何体函数表示:

对于 $x \in \left[a,b\right]$ ，垂直于 $x$ 轴平面与几何体截面的面积表示为: $A=A(x)$，可积。

*** 求极限:

\begin{aligned}
&\forall P:\ a=x_0<x_1<...<x_n=b \\
&\forall \xi_i \in [x_{i-1},x_i],\ \ \Delta x_i=x_i-x_{i-1},\ \ \lambda=max(\Delta x_i) \\
&\lim_{\lambda to 0} \left\{\sum_{i=1}^n A(\xi_i) \Delta x_i\right\}\\
&=\int_a^b A(x) dx
\end{aligned}

** 旋转曲面面积:

*** [[L2][要求光滑曲线]]

*** 定义符号:

\begin{aligned}
& y=y(t) \\
& x=x(t) \\
& t \in [T_1,T_2] \\
& P:\ T_1=t_0<t_1<...<t_n=T_2 \\
& \Delta t_i = t_i-t_{i-1} \\
& M_i = sup(y(t)),\ \ t \in [t_{i-1},t_i] \\
& m_i = inf(y(t)),\ \ t \in [t_{i-1},t_i] \\
& M = sup(y(t)),\ \ t \in [T_1,T_2] \\
& m = inf(y(t)),\ \ t \in [T_1,T_2] \\
& |M|^x=max(|sup(x(t))|,|inf(x(t))|),\ \ t \in [t_1,t_2]\\
& |M|^y=max(|sup(y(t))|,|inf(y(t))|),\ \ t \in [t_1,t_2]\\
\end{aligned}

*** 证明:

圆台面积公式: $a=\pi (r_1+r_2)l$ ，$r_1$ 为上底半径 $r_2$ 为下底半径 $l$ 为母线。

以圆台近似表面积，并由拉格朗日中值定理得:

\begin{aligned}
& \sum_{i=1}^n \pi [y(t_{i-1})+y(t_i)] * \sqrt{(x(t_{i-1})-x(t_i))^2 + (y(t_{i-1})-y(t_i))^2} \\
& = \sum_{i=1}^n \pi [y(t_{i-1})+y(t_i)] * \sqrt{x(\eta_i)^2 + y(\sigma_i)^2} \Delta t,\ \ \eta_i & \sigma_i \in [t_{i-1},t_i]
\end{aligned}

同曲线长度计算，构造和式:

\begin{aligned}
&\pi \bigg| \sum_{i=1}^n \pi [y(t_{i-1})+y(t_i)] * \sqrt{x(\eta_i)^2 + y(\sigma_i)^2} \Delta t_i - \sum_{i=1}^n \pi [y(\xi_i)+y(\xi_i)] * \sqrt{x(\xi_i)^2 + y(\xi_i)^2} \Delta t_i \bigg| \\
&\leq 2\pi \bigg| \sum_{i=1}^n M_i * \sqrt{x(\eta_i)^2 + y(\sigma_i)^2} \Delta t_i - \sum_{i=1}^n m_i * \sqrt{x(\xi_i)^2 + y(\xi_i)^2} \Delta t_i \right\} \bigg| \\
&= 2\pi \bigg| \sum_{i=1}^n \sqrt{(M_i x(\eta_i))^2 + (M_i y(\sigma_i))^2} \Delta t_i - \sum_{i=1}^n \sqrt{(m_i x(\xi_i))^2 + (m_i y(\xi_i))^2} \Delta t_i \right\} \bigg| \\
&\leq 2\pi \sum_{i=1}^n \bigg| \sqrt{(M_i x(\eta_i))^2 + (M_i y(\sigma_i))^2} - \sqrt{(m_i x(\xi_i))^2 + (m_i y(\xi_i))^2} \bigg| \Delta t_i \\
&\leq 2\pi \left\{ \sum_{i=1}^n \bigg| M_i x(\eta_i)-m_i x(\xi_i) \bigg| \Delta t_i + \sum_{i=1}^n \bigg| M_i y(\sigma_i)-m_i y(\xi_i) \bigg| \Delta t_i \right\}\\
&= 2\pi \left\{ \sum_{i=1}^n \bigg| M_i x(\eta_i)-M_i x(\xi_i)+M_i x(\xi_i)-m_i x(\xi_i) \bigg| \Delta t_i + \sum_{i=1}^n \bigg| M_i y(\sigma_i)-M_i y(\xi_i) + M_i y(\xi_i) -m_i y(\xi_i) \bigg| \Delta t_i \right\}\\
&\leq 2\pi \left\{ \sum_{i=1}^n \bigg| M_i (x(\eta_i)- x(\xi_i))\bigg| \Delta t_i+ \sum_{i=1}^n \bigg| x(\xi_i)(M_i - m_i) \bigg| \Delta t_i + \sum_{i=1}^n \bigg| M_i (y(\sigma_i) - y(\xi_i)) \bigg| \Delta t_i + \sum_{i=1}^n \bigg| y(\xi_i) (M_i - m_i) \bigg| \Delta t_i \right\} \\
&\leq 2\pi \left\{ M \sum_{i=1}^n \Omega_i^x \Delta t_i + |M|^x \sum_{i=1}^n \Omega_i^y \Delta t_i + M \sum_{i=1}^n \Omega_i^y \Delta t_i + |M|^y \sum_{i=1}^n \Omega_i^y \Delta t_i \right\} \\
&= 2\pi \left\{  M \sum_{i=1}^n \Omega_i^x \Delta t_i +(|M|^x + M + |M|^y) \sum_{i=1}^n \Omega_i^y \Delta t_i \right\} \\
\end{aligned}

由于光滑曲线设定，$x(t)$ ，$y(t)$ 可积:

\begin{aligned}
&\forall \epsilon > 0,\ \ \forall P \\
&\exists \delta_1,\ \ \forall \lambda<\delta_1\\
&\Rightarrow 0 < \sum_{i=1}^n \Omega_i^x \Delta t_i < \frac{\epsilon}{4 \pi M}\\
&\exists \delta_2,\ \ \forall \lambda<\delta_2\\
&\Rightarrow 0 < \sum_{i=1}^n \Omega_i^y \Delta t_i < \frac{\epsilon}{4 \pi (|M|^x + M + |M|^y)}\\
&\forall \lambda<min(\delta_1,\delta_2)\\
&\pi \bigg| \sum_{i=1}^n \pi [y(t_{i-1})+y(t_i)] * \sqrt{x(\eta_i)^2 + y(\sigma_i)^2} \Delta t_i - \sum_{i=1}^n \pi [y(\xi_i)+y(\xi_i)] * \sqrt{x(\xi_i)^2 + y(\xi_i)^2} \Delta t_i \bigg| \\
&\leq 2\pi \left\{  M \sum_{i=1}^n \Omega_i^x \Delta t_i +(|M|^x + M + |M|^y) \sum_{i=1}^n \Omega_i^y \Delta t_i \right\} \\
&\leq 2\pi \left\{ \frac{\epsilon}{4\pi} + \frac{\epsilon}{4\pi}\right\}\\
&=\epsilon
\end{aligned}

** 曲率

*** 定义:

设符: 

$\Delta S$ 为曲线弧长
 
$\Delta \varphi$ 为弧长两点切线的夹角

$\overline K$ 为弧 $AB$ 的平均曲率

$K_x$ 为$x$点的曲率

\begin{aligned}
&\overline K = \bigg| \frac{\Delta \varphi}{\Delta S} \bigg| \\
&K_x = \lim_{\Delta S \to 0} \bigg| \frac{\Delta \varphi}{\Delta S} \bigg|=\bigg|\frac{d\varphi}{dS} \bigg|
\end{aligned}

*** 光滑曲线曲率公式推导:

\begin{aligned}
&x=x(t)\\
&y=y(t)\\
&K_x=\bigg| \frac{d\varphi}{dt}\bigg/\frac{dS}{dt} \bigg|\\
\end{aligned}

推导 $\frac{d\varphi}{dt}$ :

\begin{aligned}
&tan(\varphi)=\frac{y'(t)}{x'(t)}\\
&\Rightarrow \frac{d \varphi}{dt}=\left\{arctan \frac{y'(t)}{x'(t)}\right\}'\\
&=\frac{\frac{x''(t)y'(t)-y''(t)x'(t)}{x'(t)^2}}{1+\left\{\frac{y'(t)}{x'(t)}\right\}^2} \\
&=\frac{x''(t)y'(t)-y''(t)x'(t)}{x'(t)^2+y'(t)^2}
\end{aligned}

根据弧长公式:

\begin{aligned}
&\frac{dS}{dt}=\sqrt{x'(t)^2 + y'(t)^2}
\end{aligned}

合并曲率公式参数表示:

\begin{aligned}
&K_x=\frac{\left|x''(t)y'(t)-y''(t)x'(t)\right|}{\left\{x'(t)^2 + y'(t)^2\right\}^{\frac{3}{2}}}
\end{aligned}

弧长公式函数表示:

\begin{aligned}
K_x=\frac{|f''(x)|}{\left\{ 1+f'(x)^2\right\}^{\frac{3}{2}}}
\end{aligned}
* 有理函数不定积分

** 有理函数定义

定义有理函数为 $\frac{p(x)}{q(x)}$ 其中 $p(x),q(x)$ 分别为关于 $x$ 的 $m,n$ 次多项式

** <<MK20>>定义真分式

有理函数 $\frac{p(x)}{q(x)}$ 当 $m<n$ 时，定义为真分式。

若 $m>n$ 则可通过多项式带余除法求得 $\frac{p(x)}{q(x)}=p_{m-n}(x)+\frac{r(x)}{q(x)}$ 其中 $p_{m-n}(x)$ 为 $m-n$ 次多项式

以下证明中 $\frac{p(x)}{q(x)}$ 均为真分式。

*** 带余除法举例

计算 $\frac{x^2+9x+25}{x+4}$ 其中 $m=2,n=1$

第一步 $x^2+9x+25-x(x+4)=5x+25$

第二步 $5x+25-5(x+4)=5$

故有 $\frac{(x^2+9x+25)}{(x+4)}=\frac{5}{x+4}+x+5$

** 定义符号

由于 $q(x)$ 为实函数，故只有实根或共轭复根 

定义 $\alpha_1,\alpha_2,...,\alpha_i$ 为 $q_n(x)$ 的实根，重数为 $u_1,u_2,...,u_i$

定义 $\beta_1\pm i\gamma_1,\beta_2\pm i\gamma_2,...,\beta_j\pm i\gamma_j$ 为 $q_n(x)$ 的共轭复根，重数为 $v_1,v_2,...,v_j$

故有 $q_n(x)=\Pi_{k=1}^i (x-\alpha_k)^{u_k}\Pi_{k=1}^j\left[(x-\beta_k)^2+\gamma_k^2\right]^{v_j}$

** <<MK21>>引理1

若 $\alpha$ 为 $q(x)$ 的一个解，重数为 $u$ 即 $q(x)=(x-\alpha)^uq_1(x)$ ，

则存在实数 $\lambda$ 及多项式 $p_1(x)$ 次数小于 $(x-\alpha)^{u-1}q_1(x)$ ，即 $n-1$ 次，使得 $\frac{p(x)}{q(x)}=\frac{\lambda}{(x-\alpha)^u}+\frac{p_1(x)}{(x-\alpha)^{u-1}q_1(x)}$ 成立

*** 证明

定义 $\lambda=\frac{p(\alpha)}{q_1(\alpha)}$ ，根据定义 $q_1(\alpha)\ne0$ ,则 $\alpha$ 是函数 $p(x)-q_1(x)$ 的一个实根，则有 $p(x)-\lambda q_1(x)=(x-\alpha)p_1(x)$ 

由于 $q_1(x)$ 次数为 $n-u$ 其中 $u>=1$ ， $p(x)$ 次数根据[[MK20][真分式定义]]为 $m<n$ 故 $p_1(x)$ 次数为 $\max(n-u-1,m-1)<n-1$

故有 $\frac{p(x)}{q(x)}=\frac{(x-\alpha)p_1(x)+\lambda q_1(x)}{(x-\alpha)^uq_1(x)}=\frac{\lambda}{(x-\alpha)^u}+\frac{p_1(x)}{(x-\alpha)^{u-1}q_1(x)}$ 

** <<MK22>>引理2

若 $\beta\pm i\gamma$ 是 $q(x)$ 一对共轭复根，重数为 $v$ ，即 $q(x)=\left[(x-\beta)^2+\gamma^2\right]^vq^1(x)$ ，

则存在实数 $\xi,\eta$ 及多项式 $p^1(x)$ 次数小于 $\left[(x-\beta)^2+\gamma^2\right]^{v-1}q^1(x)$ ，即 $n-1$ 次，使得 $\frac{p(x)}{q(x)}=\frac{\xi x+\eta}{\left[(x-\beta)^2+\gamma^2\right]^v}+\frac{p^1(x)}{\left[(x-\beta)^2+\gamma^2\right]^{v-1}q_1(x)}$ 成立

*** 证明 

定义 $\xi,\eta$ 使得 $\frac{p(\beta+i\gamma)}{q^1(\beta+i\gamma)}=\xi(\beta+i\gamma)+\eta$ 成立，根据定义 $q^1(\beta+i\gamma)\ne0$

由于分母分子均为多项式，则等式展开后形式为 $\frac{f_1(\beta,\gamma)+ig_1(\beta,\gamma)}{f_2(\beta,\gamma)+ig_2(\beta,\gamma)}$ 分子分母同乘 $f_2(\beta,\gamma)-ig_2(\beta,\gamma)$ 

得 $\frac{f_1(\beta,\gamma)f_2(\beta,\gamma)+g_1(\beta,\gamma)g_2(\beta,\gamma)}{f_2(\beta,\gamma)+g_2(\beta,\gamma)}+i\frac{-f_1(\beta,\gamma)g_2(\beta,\gamma)+f_2(\beta,\gamma)g_1(\beta,\gamma)}{f_2(\beta,\gamma)+g_2(\beta,\gamma)}$ ，其中 $f_1(\beta,\gamma),f_2(\beta,\gamma),g_1(\beta,\gamma),g_2(\beta,\gamma)$ 均为多项式函数

由于 $i,\gamma$ 同次，且 $i^2=-1$ ，故 $f_1(\beta,\gamma),f_2(\beta,\gamma)$ 中每一项必为 $\gamma$ 的偶次项（包含零次），即 $f_1(\beta,\gamma)=f_1(\beta,-\gamma),f_2(\beta,\gamma)=f_2(\beta,-\gamma)$

同理， $g_1(\beta,\gamma),g_2(\beta,\gamma)$ 中每一项必为 $\gamma$ 的奇次项，则有 $g_1(\beta,\gamma)=-g_1(\beta,-\gamma),g_2(\beta,\gamma)=-g_2(\beta,-\gamma)$

又因为  $\frac{f_1(\beta,\gamma)-ig_1(\beta,\gamma)}{f_2(\beta,\gamma)-ig_2(\beta,\gamma)}$ 分子分母同乘 $f_2(\beta,\gamma)+ig_2(\beta,\gamma)$ 得 $\frac{f_1(\beta,\gamma)f_2(\beta,\gamma)+g_1(\beta,\gamma)g_2(\beta,\gamma)}{f_2(\beta,\gamma)+g_2(\beta,\gamma)}+i\frac{f_1(\beta,\gamma)g_2(\beta,\gamma)-f_2(\beta,\gamma)g_1(\beta,\gamma)}{f_2(\beta,\gamma)+g_2(\beta,\gamma)}$ 

故若 $\frac{p(\beta+i\gamma)}{q^1(\beta+i\gamma)}=\xi(\beta+i\gamma)+\eta$ 则 $\frac{p(\beta-i\gamma)}{q^1(\beta-i\gamma)}=\xi(\beta-i\gamma)+\eta$

得出 $\beta\pm i\gamma$ 是函数 $p(x)-(\xi x+\eta)q^1(x)$ 的共轭复根，则有 $p(x)-(\xi x+\eta)q^1(x)=\left[(x-\beta)^2+\gamma^2\right]p^1(x)$ 

由于 $q^1(x)$ 次数为 $n-v$ 其中 $v>=1$ ， $p(x)$ 次数根据[[MK20][真分式定义]]为 $m<n$ 故 $p^1(x)$ 次数为 $\max(n-v-1,m-1)<n-1$

则有  $\frac{p(x)}{q(x)}=\frac{\left[(x-\beta)^2+\gamma^2\right]p^1(x)+(\xi x+\eta)q^1(x)}{\left[(x-\beta)^2+\gamma^2\right]^vq^1(x)}=\frac{\xi x+\eta}{\left[(x-\beta)^2+\gamma^2\right]^v}+\frac{p^1(x)}{\left[(x-\beta)^2+\gamma^2\right]^{v-1}q_1(x)}$ 

** <<MK23>>引理3

定义 $I_n=\int\frac{1}{(x^2+a^2)^n}dx$ 则有 $I_n=\begin{cases}\frac{1}{a}\arctan\left(\frac{x}{a}\right)+C&n=1\\\frac{2n-3}{2a^2(n-1)}I_{n-1}+\frac{x}{2a^2(n-1)(x^2+a^2)^{n-1}}&n\geq 2\end{cases}$

*** 证明

**** 先证 $n=1$

定义 $u=\frac{x}{a}$ 则有 $\frac{du}{dx}=\frac{1}{a}\Rightarrow adu=dx$

\begin{aligned}
I_1&=\int\frac{1}{x^2+a^2}dx\\
&=\frac{1}{a^2}\int\frac{1}{\frac{x^2}{a^2}+1}dx\\
&=\frac{1}{a^2}\int\frac{1}{u^2+1}adu\\
&=\frac{1}{a}\arctan\left(\frac{x}{a}\right)+C\\
\end{aligned}

**** 证明 $n\geq 2$

定义 $u=\frac{1}{(x^2+a^2)^{n-1}}=(x^2+a^2)^{-n+1}$ 则有 $\frac{du}{dx}=-2(n-1)\frac{x}{(x^2+a^2)^n}\Rightarrow \frac{-1}{2(n-1)}du=\frac{x}{(x^2+a^2)^n}dx$

\begin{aligned}
I_1&=\int\frac{1}{(x^2+a^2)^n}dx\\
&=\frac{1}{a^2}\int\frac{a^2}{(x^2+a^2)^n}dx\\
&=\frac{1}{a^2}\int\frac{x^2+a^2-x^2}{(x^2+a^2)^n}dx\\
&=\frac{1}{a^2}\int\frac{x^2+a^2}{(x^2+a^2)^n}dx-\frac{1}{a^2}\int\frac{x^2}{(x^2+a^2)^n}dx\\
&=\frac{I_{n-1}}{a^2}-\frac{1}{a^2}\int x\frac{-1}{2(n-1)}d\left(\frac{1}{(x^2+a^2)^{n-1}}\right)\\
&=\frac{I_{n-1}}{a^2}+\frac{1}{2a^2(n-1)}\int x d\left(\frac{1}{(x^2+a^2)^{n-1}}\right)\\
&=\frac{I_{n-1}}{a^2}+\frac{1}{2a^2(n-1)}\left\{\frac{x}{(x^2+a^2)^{n-1}}-\int \frac{1}{(x^2+a^2)^{n-1}}dx\right\}\\
&=\frac{I_{n-1}}{a^2}+\frac{x}{2a^2(n-1)(x^2+a^2)^{n-1}}-\frac{I_{n-1}}{2a^2(n-1)}\\
&=\frac{(2n-3)I_{n-1}}{2a^2(n-1)}+\frac{x}{2a^2(n-1)(x^2+a^2)^{n-1}}\\
\end{aligned}

** 有理函数不定积分定理

若被积函数为有理函数，即 $\frac{p(x)}{q(x)}$ 则必能求出期不定积分表达式

*** 证明

由于 $\frac{p(x)}{q(x)}=\frac{p(x)}{\Pi_{k=1}^i (x-\alpha_k)^{u_k}\Pi_{k=1}^j\left[(x-\beta_k)^2+\gamma_k^2\right]^{v_j}}$ 则可根据[[MK21][引理1]]及[[MK22][引理2]]函数可化为 $\frac{p(x)}{q(x)}=\sum_{k=1}^i\sum_{r=1}^{u_k}\frac{\lambda_{kr}}{(x-\alpha_k)^r}+\sum_{k=1}^i\sum_{r=1}^{u_k}\frac{\xi_{kr} x+\eta_{kr}}{\left[(x-\beta_k)^2+\gamma_k^2\right]^r}$

故根据不定积分线性 $\int\frac{p(x)}{q(x)}dx=\sum_{k=1}^i\sum_{r=1}^{u_k}\int\frac{\lambda_{kr}}{(x-\alpha_k)^r}dx+\sum_{k=1}^i\sum_{r=1}^{u_k}\int\frac{\xi_{kr} x+\eta_{kr}}{\left[(x-\beta_k)^2+\gamma_k^2\right]^r}dx$

**** 对于项 $\int\frac{\lambda_{kr}}{(x-\alpha_k)^r}dx$

\begin{aligned}
\int\frac{\lambda_{kr}}{(x-\alpha_k)^r}dx&=\lambda_{kr}\int\frac{1}{(x-\alpha_k)^r}dx\\
&=\begin{cases}
\lambda_{kr}\ln\left|x-\alpha_k\right|+C&r=1\\
\frac{\lambda_{kr}}{r-1}\frac{1}{(x-\alpha_k)^(r-1)}&r\geq2\\
\end{cases}
\end{aligned}

**** 对于项 $\int\frac{\xi_{kr} x+\eta_{kr}}{\left[(x-\beta_k)^2+\gamma_k^2\right]^r}dx$

定义 $u=x^2-2\beta_kx+\beta_k^2+\gamma_k^2$ 则有 $\frac{du}{dx}=2x-2\beta_k\Rightarrow du=(2x-2\beta_k)dx$

定义 $v=x-\beta_k$ 则有 $\frac{dv}{dx}=1\Rightarrow dv=dx$

\begin{aligned}
\int\frac{\xi_{kr} x+\eta_{kr}}{\left[(x-\beta_k)^2+\gamma_k^2\right]^r}dx&=\frac{\xi_{kr}}{2}\int\frac{ 2x+2\frac{\eta_{kr}}{\xi_{kr}}}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx\\
&=\frac{\xi_{kr}}{2}\int\frac{ 2x-2\beta_k+2\beta_k+2\frac{\eta_{kr}}{\xi_{kr}}}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx\\
&=\frac{\xi_{kr}}{2}\int\frac{ 2x-2\beta_k}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx+\frac{\xi_{kr}}{2}\left(2\beta_k+2\frac{\eta_{kr}}{\xi_{kr}}\right)\int\frac{1}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx\\
&=\frac{\xi_{kr}}{2}\int\frac{ 2x-2\beta_k}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx+\left(\beta_k\xi_{kr}+\eta_{kr}\right)\int\frac{1}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx\\
&=\frac{\xi_{kr}}{2}\int\frac{1}{u^r}du+\left(\beta_k\xi_{kr}+\eta_{kr}\right)\int\frac{1}{\left[v^2+\gamma_k^2\right]^r}dv\\
\end{aligned}

其中 $\int\frac{1}{u^r}du=\begin{cases}\ln |u|+C&r=1\\\frac{-1}{r-1}\frac{1}{u^{r-1}}&r\geq 2\end{cases}$ 故 $\int\frac{ 2x-2\beta_k}{\left[x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right]^r}dx=\begin{cases}\ln |x^2-2\beta_kx+\beta_k^2+\gamma_k^2|+C&r=1\\\frac{-1}{r-1}\frac{1}{\left(x^2-2\beta_kx+\beta_k^2+\gamma_k^2\right)^{r-1}}&r\geq 2\end{cases}$

其中 $\int\frac{1}{\left[v^2+\gamma_k^2\right]^r}dv$ 可根据[[MK23][引理3]]迭代求得并带入 $v=x-\beta_k$
