#+LATEX_CLASS: ctexart

#+TITLE: 复变函数

current mark: 92

* 其他定理

** 简单曲线定义<<MK81>>

满足：

（1） [[~/OneDrive/数学分析/Chap14Note.org][可求长线段]]

（2） 没有交点（若闭合，则除首尾外无交点）

则定义为简单曲线

** 多边形三角化<<MK79>>

简单（边不相交，无重边）任意有限边多边形可以划分成若干个三角形的拼接

*** 证明

当边数 $n=3$ 时，图形本身为三角形，成立

假设边数为 $n$ 且对任意边数 $<n$ 的多边形均成立，此时定义多边形为 $S_n$

定义坐标系 $L$ 取 $L$ 下 $S_n$ 最左边顶点 $A$ 及其临近顶点 $B,C$ 若线段 $BC\subset S_n$ 则 $BC$ 分割 $S_n$

若 $BC\not\subset S_n$ ，则三角形 $\Delta ABC$ 中必存在一个或多个 $S_n$ 的顶点，定义为集合 $U$

取顶点 $V$ 定义为离 $BC$ 最远，连接线段 $AV$

由于 $V\in\Delta ABC$ 故必有 $A$ 到 $BC$ 的距离大于 $V$ 到 $BC$ 的距离

故若存在 $S_n$ 的边与 $AV$ 相交，则必有三角形内的顶点到 $BC$ 的距离大于 $V$ 到 $BC$ 的距离，与定义不符。

若存在三角形外到 $BC$ 的距离大于 $V$ 到 $BC$ 的距离的顶点，则必与 $AB$ 或 $AC$ 相交，与简单多边形定义不符。

故 $AV$ 与任意 $S_n$ 的边不相交。

由于 $A$ 为多边形最左边的点且 $B,C$ 为相邻端点，故顶点 $A$ 右侧为 $S_n$ 的区域

又因为 $V$ 位于 $A$ 的右侧，且不存在边交于 $AV$ 及与 $AB,AC$ 的交集为空，故有 $AV\subset S_n$ 

故 $AV$ 分割 $S_n$ 为两个多边形 $S',S''$ 

由于要形成多边形至少要有 $3$ 条边，故对于 $S'$ 来说 $S''$ 被线段 $AV$ 替换，至少为 $3$ 条边替换为 $1$ 条边

故必有 $S'$ 的边数小于 $n$ ，同理可证 $S''$ 边数小于 $n$

故根据前提定义小于 $n$ 的多边形可分割成若干三角形，结论成立。

故根据数学归纳法，任何边数有限的简单多边形必可划分成若干个三角形的拼接

* 构建复数

** 复数定义<<MK59>>

定义 $i$ 满足 $i^2=-1$ 对于任意实数 $\{a,b\}\subset\mathbb{R}$ 表达式 $a+bi$ 定义为复数

所有复数的集合为 $\mathbb{C}$

*** 复数相等<<MK60>>

两个复数 $a+ib,c+id$ 相等定义为 $a=c\land b=d$

** 共轭复数

若存在复数 $z=a+ib$ 则其共轭复数为 $\overline{z}=a-ib$

*** 性质

**** 保持加法

$\overline{(z_1+z_2)}=\overline{z_1}+\overline{z_2}$

***** 证明

定义 $z_1=a_1+ib_1,z_2=a_2+ib_2$ 则

\begin{aligned}
\overline{(z_1+z_2)}&=\overline{(a_1+a_2+i(b_i+b_2))}=a_1+a_2-i(b_i+b_2)\\
\overline{z_1}+\overline{z_2}&=a_1-ib_1+a_2-ib_2=a_1+a_2-i(b_i+b_2)
\end{aligned}

**** 保持乘法

$\overline{(z_1\times z_2)}=\overline{z_1}\times\overline{z_2}$

***** 证明

定义 $z_1=a_1+ib_1,z_2=a_2+ib_2$ 则

\begin{aligned}
\overline{(z_1\times z_2)}&=\overline{(a_1a_2-b_1b_2+i(a_1b_2+a_2b_1))}\\
&=a_1a_2-b_1b_2-i(a_1b_2+a_2b_1)\\
\overline{z_1}\times\overline{z_2}&=(a_1-ib_1)(a_2-ib_2)\\
&=a_1a_2-b_1b_2-i(a_1b_2+a_2b_1)\\
\end{aligned}

** 模<<MK56>>

若 $a+bi\in\mathbb{C}$ 则它的模定义为 $\sqrt{a^2+b^2}$ 记作 $|a+bi|=\sqrt{a^2+b^2}$

复数的模为实数，即 $|a+bi|\in\mathbb{R}$

*** 性质<<MK91>>

**** 相乘等价<<MK69>>

定义 $\{a,b\}\in\mathbb{C}$ 则有 $|ab|=|a||b|$

***** 证明

定义 $a=x+yi,b=u+vi$ 则有 $ab=xu-vy+i(xv+uy)$ 则有 

\begin{aligned}
|ab|&=\sqrt{(xu-vy)^2+(xv+uy)}\\
&=\sqrt{(xu)^2+(vy)^2+(xv)^2+(uy)^2}
\end{aligned}

另有 

\begin{aligned}
|a||b|&=\sqrt{x^2+y^2}\sqrt{u^2+v^2}\\
&=\sqrt{(xu)^2+(vy)^2+(xv)^2+(uy)^2}
\end{aligned}

故有 $|ab|=|a||b|$

**** 三角不等式<<MK68>>

定义 $\{a,b\}\in\mathbb{C}$ 则有 $|a+b|<|a|+|b|$

***** 证明

定义 $a=x+yi,b=u+vi$ 则有

\begin{aligned}
|a+b|^2&=\left|(x+u)+i(y+v)\right|\\
&=\sqrt{(x+u)^2+(v+y)^2}^2\\
&=x^2+y^2+v^2+z^2+2(xu+vy)
\end{aligned}

另有

\begin{aligned}
\left(|a|+|b|\right)^2&=\left(\sqrt{x^2+y^2}+\sqrt{u^2+v^2}\right)^2\\
&=x^2+y^2+u^2+v^2+2\sqrt{(x^2+y^2)(u^2+v^2)}
\end{aligned}

由于

\begin{aligned}
\left(\sqrt{(x^2+y^2)(u^2+v^2)}\right)^2&=(xu)^2+(yu)^2+(xv)^2+(yv)^2\\
&=(yu)^2+(xv)^2+(xu+vy)^2-2xuvy\\
&=(yu-xv)^2+(xu+vy)^2
\end{aligned}

则有 $\left(\sqrt{(x^2+y^2)(u^2+v^2)}\right)^2-(xu+vy)^2=(yu-xv)^2$ 

由于 $x,y,u,v$ 均为实数，故有 $\left(\sqrt{(x^2+y^2)(u^2+v^2)}\right)^2>(xu+vy)^2$

由于 $f(x)=x^2$ 单调递增函数，故有 $\sqrt{(x^2+y^2)(u^2+v^2)}>xu+vy$

进一步有 $x^2+y^2+u^2+v^2+2\sqrt{(x^2+y^2)(u^2+v^2)}>x^2+y^2+v^2+z^2+2(xu+vy)$

即三角不等式 $|a+b|<|a|+|b|$

**** 分母<<MK86>>

$$\left|\frac{1}{z}\right|=\frac{1}{|z|}$$

***** 证明

\begin{aligned}
\left|\frac{1}{z}\right|=&\left|\frac{1}{a+ib}\right|\\
=&\left|\frac{a-ib}{(a+ib)(a-ib)}\right|\\
=&\left|\frac{a-ib}{a^2+b^2}\right|\\
=&\left|\frac{a}{a^2+b^2}-i\frac{b}{a^2+b^2}\right|\\
=&\sqrt{\frac{a^2}{(a^2+b^2)^2}+\frac{b^2}{(a^2+b^2)^2}}\\
=&\sqrt{\frac{a^2+b^2}{(a^2+b^2)^2}}\\
=&\frac{1}{\sqrt{a^2+b^2}}
\end{aligned}

**** 分式<<MK87>>

定义 $\{a,b\}\in\mathbb{C}$ 则有 $\left|\frac{a}{b}\right|=\frac{|a|}{|b|}$

***** 证明

根据[[MK86][分母]]以及[[MK69][相乘]]

\begin{aligned}
\left|\frac{a}{b}\right|=\left|a\frac{1}{b}\right|=|a|\left|\frac{1}{b}\right|=|a|\frac{1}{|b|}=\frac{|a|}{|b|}
\end{aligned}

** 复领域<<MK55>>

对于点 $x_0\in\mathbb{C}$ 定义领域为集合 $\left\{x\big|x\in\mathbb{C}\land |x-x_0|<\rho\right\}$ 即 $x$ 为复数且 $x-x_0$ 的模小于 $\rho$ 的点集

记作 $O(x_0,\rho)$

** 函数极限<<MK57>>

复函数 $f(x)$ 在点 $x_0\in\mathbb{C}$ 的去心[[MK55][领域]] $O(x_0,\rho)$ 上有定义

则存在 $A$ 满足 $\forall\epsilon>0\rightarrow \exists H>0\big(\forall x(|x-x_0|<H\rightarrow |f(x)-A|<\epsilon)\big)$ 其中 $|x|$ 为对 $x$ 求[[MK56][模]]

记作 $\lim_{x\to x_0}f(x)=A$

** 函数连续<<MK62>>

若复函数 $f(x)$ 在点 $x_0$ 上有 $\lim_{x\to x_0}f(x)=f(x_0)$ 则称其在点 $x_0$ 连续

若对于 $x\in D\subset\matbb{C}$ 均有上述性质，则称其在区域 $D$ 上连续

** 一致连续<<MK66>>

若复函数 $f(z)$ 在定义域 $D$ 上满足 $\forall\epsilon>0,\exists\delta>,\forall|z'-z''|<\delta\Rightarrow|f(z')-f(z'')|<\epsilon$

** 基本定理

*** 有界复数列必有收敛子列<<MK72>>

定义复数数列 $S_1,S_2,...,S_n,...\a$ 若 $\exists M,\forall i\in\mathbb{N}^+\Rightarrow |S_i|<M$ 则必有数列 $S_{i_1},S_{i_2},...,S_{i_n},...\a$ 满足 $\lim_{n\to\infty}S_{i_n}=A$ 收敛

**** 证明

根据[[MK59][定义]]可得 $S_k=a_k+ib_k$ 且由于 $\exists M,\forall i\in\mathbb{N}^+\Rightarrow |S_i|<M$ 根据[[MK56][模]]定义可得 $a_k,b_k$ 均需有界

构造 $\vec{x}_k=(a_k,b_k)$ 由于 $a_k\in\mathbb{R}\land b_k\in\mathbb{R}$ 故根据[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-Bolzano-Weierstrass定理]]

可得 $\vec{x}_k$ 必有收敛子列，即有 $\vec{x}_{i_1},...,\vec{x}_{i_n}$ 满足 $\lim_{n\to\infty}\vec{x}_{in}=(A,B)\in\mathbb{R}^2$

故必有数列 $S_{i_1},S_{i_2},...,S_{i_n},...\a$ 满足 $\lim_{n\to\infty}S_{i_n}=A$ 收敛

*** 复函数与实函数<<MK61>>

若 $f(z)$ 为复函数，定义 $z=x+iy$ 则其可以有等价的 $f(x+iy)=u(x,y)+iv(x,y)$

**** 证明

根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-相关定义-函数定义]]，由于 $f(z)$ 为函数，故对于 $z=x+iy$ 必有一个 $f(z)=a+ib$ 形成映射

故对于 $u(x,y),v(x,y)$ 若 $x+iy=z$ 则必有 $u(x,y)=a,v(x,y)=b$

同理由于 $f(z)$ 为函数，故当 $a_1+ib_1=z_1=f(z)\land a_2+ib_2=z_2=f(z)$ 时必有 $z_1=z_2$

根据[[MK60][复数相等]]可得 $a_1=a_2,\land b_1=b_2$ 故友 $a_1=u(x,y)\land a_2=u(x,y)\rightarrow a_1=a_2$ 

同理可证 $v(x,y)$ 同样满足，故得 $u(x,y),v(x,y)$ 均为函数

* 导数、微分与解析<<MK83>>

** 导数<<MK63>>

复函数 $f(x)$ 在点 $x_0\in\mathbb{C}$ 的[[MK55][领域]] $O(x_0,\rho)$ 上有定义，则其在点 $x_0$ 的导数定义为 $$\lim_{\Delta x\to 0}\frac{f(x_0+\Delta x)-f(x_0)}{\Delta x}$$

进一步说明，即存在复数 $A$ 使得 $\forall\epsilon>0\rightarrow\exists H>0\left(\forall\Delta x\left(|\Delta x|<H\rightarrow \left|\frac{f(x_0+\Delta x)-f(x_0)}{\Delta x}-A\right|<\epsilon\right)\right)$

则 $A$ 为 $f(x)$ 在复点 $x_0$ 上的导数，记作 $f'(x)=A$

*** 可导必连续<<MK80>>

若函数 $f(z)$ 在 $z_0$ 点可导，则函数在 $z_0$ 点必连续，即 $\lim_{z\to z_0}f(z)=f(z_0)$

**** 证明

由于可导，则 $f(z_0)$ 必存在，则 $$\lim_{z\to z_0}\left(f(z)-f(z_0)\right)&=\lim_{z\to z_0}\left((z-z_0)\frac{f(z)-f(z_0)}{z-z_0}\right)$$

由于两部分极限均存在，则根据极限四则运算有

$$\lim_{z\to z_0}\left(f(z)-f(z_0)\right)=\lim_{z\to z_0}\left((z-z_0)\frac{f(z)-f(z_0)}{z-z_0}\right)=\lim_{z\to z_0}(z-z_0)\lim_{z\to z_0}\frac{f(z)-f(z_0)}{z-z_0}=0f'(z_0)=0$$

由于 $f(z_0)$ 存在，则 $$\lim_{z\to z_0}f(z_0)=f(z_0)$$ 故有 $\lim_{z\to z_0}f(z)=f(z_0)$

*** 充要条件

函数 $f(z)=u(x,y)+iv(x,y)$ 在点 $z_0=x_0+iy_0$ 可导的充要条件是：

（1） $u(x,y),v(x,y)$ 在点 $(x_0,y_0)$ 根据[[~/OneDrive/数学分析/Chap12Note.org][偏导数与全微分-偏导数，方向导数及全微分-全微分]]定义，可微

（2） 满足 $\frac{\partial u(x_0,y_0)}{\partial x}=\frac{\partial v(x_0,y_0)}{\partial y}\land \frac{\partial u(x_0,y_0)}{\partial y}=-\frac{\partial v(x_0,y_0)}{\partial x}$ 即柯西-黎曼方程

**** 证明

***** 充分

当可导时，根据[[MK64][微分]]证明可得 $f(\Delta z+z_0)-f(z_0)=f'(z_0)\Delta z+o(\Delta z)$ 

则定义 $\Delta z=\Delta x+i\Delta y,f'(z_0)=a+ib,o(\Delta z)=o_1(\Delta z)+io_2(\Delta z)$ 

其中满足 $\lim_{\Delta z\to 0}o_1(\Delta z)=\lim_{\Delta z\to 0}o_2(\Delta z)=0$ 则有 

\begin{aligned}
f(\Delta z+z_0)-f(z_0)=&\big(u(\Delta x+x_0,\Delta y+y_0)-u(x_0,y_0)\big)+i\big(v(\Delta x+x_0,\Delta y+y_0)-v(x_0,y_0)\big)\\
f'(z_0)\Delta z+o(\Delta z)=&(a+ib)(\Delta x+i\Delta y)+o_1(\Delta z)+io_2(\Delta z)\\
=&\big(a\Delta x-b\Delta y+o_1(\Delta z)\big)+i\big(b\Delta x+a\Delta y+o_2(\Delta z)\big)
\end{aligned}

故实部相等得 $u(\Delta x+x_0,\Delta y+y_0)-u(x_0,y_0)=a\Delta x-b\Delta y+o_1(\Delta z)$

由于 $\Delta z\to 0$ 等价于 $\Delta x\to0\land \Delta y\to0$ 则有 $\lim_{\Delta x\to0\land \Delta y\to0}o_1(\Delta z)=0$

即根据[[~/OneDrive/数学分析/Chap12Note.org][偏导数与全微分-偏导数，方向导数及全微分-全微分]]定义， $u(x,y)$ 在点 $x_0,y_0$ 可微

且根据[[~/OneDrive/数学分析/Chap12Note.org][偏导数与全微分-欧几里得空间连续，可导，可微及方向导数关系-可微与偏导]]

可得 $\frac{\partial u(x,y)}{\partial x}=a,\frac{\partial u(x,y)}{\partial y}=-b$

同理可证 $v(x,y)$ 在点 $x_0,y_0$ 可微，且有  $\frac{\partial v(x,y)}{\partial x}=b,\frac{\partial v(x,y)}{\partial y}=a$

即满足柯西-黎曼等式 $\frac{\partial u(x_0,y_0)}{\partial x}=\frac{\partial v(x_0,y_0)}{\partial y}\land \frac{\partial u(x_0,y_0)}{\partial y}=-\frac{\partial v(x_0,y_0)}{\partial x}$ 

***** 必要

定义 $z_0=x_0+iy_0$ 由于可微，则根据[[~/OneDrive/数学分析/Chap12Note.org][偏导数与全微分-欧几里得空间连续，可导，可微及方向导数关系-可微与偏导]]可得

\begin{aligned}
\Delta u=\Delta x\frac{\partial u(x_0,y_0)}{\partial x}+\Delta y\frac{\partial u(x_0,y_0)}{\partial y}+o_1\left(\sqrt{\Delta x^2+\Delta y^2}\right)\\
\Delta v=\Delta x\frac{\partial v(x_0,y_0)}{\partial x}+\Delta y\frac{\partial v(x_0,y_0)}{\partial y}+o_2\left(\sqrt{\Delta x^2+\Delta y^2}\right)
\end{aligned}

根据柯西-黎曼等式定义 $a=\frac{\partial u(x_0,y_0)}{\partial x}=\frac{\partial v(x_0,y_0)}{\partial y}\land b=\frac{\partial u(x_0,y_0)}{\partial y}=-\frac{\partial v(x_0,y_0)}{\partial x}$ 则有 

\begin{aligned}
&\lim_{z\to z_0}\frac{f(z)-f(z_0)}{z-z_0}\\
=&\lim_{z\to z_0}\frac{\Delta u+i\Delta v}{\Delta x+i\Delta y}\\
=&\lim_{z\to z_0}\frac{\left(a\Delta x+b\Delta y+o_1\left(\sqrt{\Delta x^2+\Delta y^2}\right)\right)+i\left(-b\Delta x+a\Delta y+o_2\left(\sqrt{\Delta x^2+\Delta y^2}\right)\right)}{\Delta x+i\Delta y}\\
=&\lim_{z\to z_0}\frac{a(\Delta x+i\Deltay)-ib\Delta x-bi^2\Delta y+o_1\left(\sqrt{\Delta x^2+\Delta y^2}\right)+io_2\left(\sqrt{\Delta x^2+\Delta y^2}\right)}{\Delta x+i\Delta y}\\
=&\lim_{z\to z_0}\frac{(a-ib)(\Delta x+i\Deltay)+o_1\left(\sqrt{\Delta x^2+\Delta y^2}\right)+io_2\left(\sqrt{\Delta x^2+\Delta y^2}\right)}{\Delta x+i\Delta y}\\
=&\lim_{z\to z_0}\left\{(a-ib)+\frac{o_1\left(\sqrt{\Delta x^2+\Delta y^2}\right)+io_2\left(\sqrt{\Delta x^2+\Delta y^2}\right)}{\Delta x+i\Delta y}\right\}\\
=&a-ib+\lim_{z\to z_0}\left\{\frac{o_1\left(\sqrt{\Delta x^2+\Delta y^2}\right)+io_2\left(\sqrt{\Delta x^2+\Delta y^2}\right)}{\sqrt{\Delta x+\Delta y}}\left(\frac{\Delta x}{\sqrt{\Delta x+\Delta y}}+i\frac{\Delta y}{\sqrt{\Delta x+\Delta y}}\right)\right\}\\
\end{aligned}

对于 $\frac{\Delta x}{\sqrt{\Delta x+\Delta y}},\frac{\Delta y}{\sqrt{\Delta x+\Delta y}}$ 来说是直角边的 $\sin,\cos$ 值，故有界

且 $\lim_{z\to z_0}\left\{\frac{o_1\left(\sqrt{\Delta x^2+\Delta y^2}\right)+io_2\left(\sqrt{\Delta x^2+\Delta y^2}\right)}{\sqrt{\Delta x+\Delta y}}\right\}=0$ 则有 $\lim_{z\to z_0}\frac{f(z)-f(z_0)}{z-z_0}=a-ib$

*** 基本公式

**** 幂函数

$(z^a)'=a z^{a-1},a\in\mathbb{N}$

**** 复合函数

$\left(g(f(z))\right)'=g'(f(z))f'(z)$

** 微分

若复函数 $f(x)$ 在点 $z_0$ 满足 $f(\Delta z+z_0)-f(z_0)=A\Delta z+o(\Delta z)$ 

其中定义 $o(\Delta z)$ 为满足 $\lim_{|\Delta z|\to0}\frac{o(\Delta z)}{\Delta z}=0+i0=0$ 关于 $\Delta z$ 的函数

则称函数在点 $z_0$ 可微，记作 $dw=Adz$

*** 与导数关系<<MK64>>

可微与可导等价，且 $dw=f'(z)dz$

**** 证明

***** 充分

若可微，则有 $f(\Delta z+z_0)-f(z_0)=A\Delta z+o(\Delta z)$

同除得 $\frac{f(\Delta z+z_0)-f(z_0)}{\Delta z}=A+\frac{o(\Delta z)}{\Delta z}$

故有 $\lim_{|\Delta z|\to 0}\frac{f(\Delta z+z_0)-f(z_0)}{\Delta z}=A=f'(x)$ 

***** 必要

定义 $\frac{o(\Delta z)}{\Delta z}=\frac{f(\Delta z+z_0)-f(z_0)}{\Delta z}-f'(z_0)$ 由于可导，必有 $\lim_{|\Delta z|\to 0}\frac{f(\Delta z+z_0)-f(z_0)}{\Delta z}=f'(z_0)$

故有 $\lim_{|\Delta z|\to0}\frac{o(\Delta z)}{\Delta z}=0$ 

则有 $\frac{f(\Delta z+z_0)-f(z_0)}{\Delta z}=f(z_0)+\frac{o(\Delta z)}{\Delta z}$ 即 $f(\Delta z+z_0)-f(z_0)=A\Delta z+o(\Delta z)$ 

** 解析<<MK65>>

若复函数 $f(z)$ 在 $z_0$ 点的复领域 $O(z_0,\rho)=\left\{z\big||z-z_0|<\rho\right\}$ 上[[MK63][可导]]，则称其在 $z_0$ 点解析

若 $f(z)$ 在 $D$ 上每一点均解析，则称 $f(z)$ 在 $D$ 上解析

*** 充要条件

函数 $f(z)=u(x,y)+iv(x,y)$ 在点 $D\subset\mathbb{C}$ 内解析的充要条件是：

（1） $u(x,y),v(x,y)$ 在点 $D$ 上可微

（2） 在 $x+iy\in D$ 上满足 $\frac{\partial u(x,y)}{\partial x}=\frac{\partial v(x,y)}{\partial y}\land \frac{\partial u(x,y)}{\partial y}=-\frac{\partial v(x,y)}{\partial x}$ 即柯西-黎曼方程

**** 证明

***** 充分

***** 必要

* 积分

** 积分定义<<MK67>>

设 $D\subset\mathbb{C}$ 为复平面上的区域，若存在复平面上[[~/OneDrive/数学分析/Chap14Note.org][可求长线段]] $L\subset D$

定义 $x_0,...,x_n$ 为线段上的点，将线段划分成 $n-1$ 份，其中 $x_0,x_n$ 分别为线段的起始和终止点

规定 $x_0\to x_n$ 为线段的正方向。若[[MK58][复函数]] $f(x)$ 在 $L$ 上有定义且有界（ $\forall z\in L\rightarrow|f(z)|<\infty$ ）

取 $\zeta_i$ 为线段 $x_i,x_{i+1}$ 上的一点，则有[[~/OneDrive/数学分析/Chap7Note.org][定积分定义-黎曼和]] $$\sum_{i=1}^{n-1}f(\zeta_i)(x_{i+1}-x_i)$$

定义 $s_i$ 为 $x_i,x_{i+1}$ 间的弧长， $\lambda=\max(\Delta s_i)$ 

则有[[MK57][极限]] $$\lim_{\lambda\to0}\sum_{i=1}^{n-1}f(\zeta_i)(x_{i+1}-x_i)$$ 若存在 $A$ 使得该极限对于任意的划分 $x_0,...,x_n$ 任意取点 $\zeta_i$ 

均有 $$\lim_{\lambda\to0}\sum_{i=1}^{n-1}f(\zeta_i)(x_{i+1}-x_i)=A$$ 则称线段 $L$ 上的积分是 $A$ 记作 $\int_Lf(x)dx=A$ 其中 $\{x,A\}\in\mathbb{C}$

** 积分性质

*** 与实数积分的转换<<MK73>>

复平面上的曲线段 $L$ 有参数表示 $z(t)=x(t)+iy(t)$ 其中 $t\in[a,b]$ 若在 $t:a\to b$ 上满足：

（1） 曲线分段光滑（分量函数分段一阶导数连续）

（2） 函数 $f(z)=f(x+iy)$ 在 $(x,y)\in L$ 上连续

则有 $$\int_Lf(z)dz=\int_a^b\bigg\{u\big(x(t),y(t)\big)x'(t)-v\big(x(t),y(t)\big)y'(t)\bigg\}dt+i\int_a^b\bigg\{v\big(x(t),y(t)\big)x'(t)+u\big(x(t),y(t)\big)y'(t)\bigg\}dt$$

或微分形式 $$\int_Lf(z)dz=\int_L u\big(x,y\big)dx-v\big(x,y\big)dy+i\int_L v\big(x,y\big)dx+u\big(x,y\big)dy$$

即转化为两个[[~/OneDrive/数学分析/Chap14Note.org][第二类曲线积分]]，其中 $u(x,y)+iv(x,y)=f(x+iy)$ 根据[[MK61][定理]]所得

**** 证明

***** 整理和式<<MK71>>

根据[[MK61][定理]]可得 $f(x+iy)=u(x,y)+iv(x,y)$

根据[[MK59][复数]]定义 $x_i=a_i+ib_i$ 故有 $x_{i+1}-x_i=(a_{i+1}-a_i)+i(b_{i+1}-b_i)=\Delta a_i+i\Delta b_i$

同理 $\zeta_i=\alpha_i+i\beta_i$ 则黎曼和为

\begin{aligned}
&\sum_{i=1}^{n-1}(u(\alpha_i,\beta_i)+iv(\alpha_i,\beta_i))(\Delta a_i+i\Delta b_i)\\
=&\sum_{i=1}^{n-1}\left\{u(\alpha_i,\beta_i)\Delta a_i+iv(\alpha_i,\beta_i)\Delta a_i+iu(\alpha_i,\beta_i)\Delta b_i-v(\alpha_i,\beta_i)\Delta b_i\right\}\\
=&\sum_{i=1}^{n-1}\left\{u(\alpha_i,\beta_i)\Delta a_i-v(\alpha_i,\beta_i)\Delta b_i\right\}+i\left(\sum_{i=1}^{n-1}\left\{v(\alpha_i,\beta_i)\Delta a_i+u(\alpha_i,\beta_i)\Delta b_i\right\}\right)\\
=&\sum_{i=1}^{n-1}(u(\alpha_i,\beta_i),-v(\alpha_i,\beta_i))\cdot(\Delta a_i,\Delta b_i)+i\left(\sum_{i=1}^{n-1}(v(\alpha_i,\beta_i),u(\alpha_i,\beta_i))\cdot(\Delta a_i,\Delta b_i)\right)
\end{aligned}

上述表达式中 $(u(\alpha_i,\beta_i),-v(\alpha_i,\beta_i))\cdot(\Delta a_i,\Delta b_i)$ 为向量点积 $\cos(a_i),\cos(b_i)$ 分别为 $x_{i+1}-x_i$ 与复平面 $x,y$ 轴沿曲线正方向的夹角余弦值，则根据极限四则运算

\begin{aligned}
&\lim_{\lambda\to0}\sum_{i=1}^{n-1}f(\zeta_i)(x_{i+1}-x_i)\\
=&\lim_{\lambda\to0}\left\{\sum_{i=1}^{n-1}(u(\alpha_i,\beta_i),-v(\alpha_i,\beta_i))\cdot(\Delta a_i,\Delta b_i)\right\}+i\lim_{\lambda\to0}\left\{\sum_{i=1}^{n-1}(v(\alpha_i,\beta_i),u(\alpha_i,\beta_i))\cdot(\Delta a_i,\Delta b_i)\right\}
\end{aligned}

由于形式一致，故以下仅证第一部分 $\lim_{\lambda\to0}\left\{\sum_{i=1}^{n-1}(u(\alpha_i,\beta_i),-v(\alpha_i,\beta_i))\cdot(\Delta a_i,\Delta b_i)\right\}$ 第二部分同理可证

***** 引入第二类曲线积分<<MK75>>

根据[[~/OneDrive/数学分析/Chap14Note.org][第二类曲线积分-计算-推论]] $\lim_{\lambda\to0}\left\{\sum_{i=1}^{n-1}(u(\alpha_i,\beta_i),-v(\alpha_i,\beta_i))\cdot(\Delta a_i,\Delta b_i)\right\}$ 为微分形式的黎曼和

由于满足

（1） 分量函数一阶导数分段连续（分段光滑）

（2） 分量导数即切线与数轴的夹角的余弦，当且仅当夹角均为 $\frac{\pi}{2}$ 时分量导数均为零。由于实轴虚轴在复平面夹角为 $\pi$ ，故分量导数不全为零

（3） 由于曲线段光滑，故可求长。故对于 $t\in[0,1]$ 选择点 $z$ 满足起始点到 $z$ 的弧长度为 $\frac{t}{l}$ 其中 $l$ 为曲线段 $L$ 的长度

     由于起始点到 $z$ 前后的点必然小于或大于 $\frac{t}{l}$ 故 $t$ 只对应 $z$ 一点，反之亦然，则一一对应。 

（4） 函数 $f(z)=f(x+iy)$ 在 $(x,y)\in L$ 上[[MK62][连续]]

故有 $\lim_{\lambda\to0}\left\{\sum_{i=1}^{n-1}(u(\alpha_i,\beta_i),-v(\alpha_i,\beta_i))\cdot(\Delta a_i,\Delta b_i)\right\}=\int_a^b\bigg\{u\big(x(t),y(t)\big)x'(t)-v\big(x(t),y(t)\big)y'(t)\bigg\}dt$ 

同理可证 $\lim_{\lambda\to0}\left\{\sum_{i=1}^{n-1}(v(\alpha_i,\beta_i),u(\alpha_i,\beta_i))\cdot(\Delta a_i,\Delta b_i)\right\}=\int_a^b\bigg\{v\big(x(t),y(t)\big)x'(t)+u\big(x(t),y(t)\big)y'(t)\bigg\}dt$

故结论成立

**** 推论<<MK82>>

同样条件下有 $$\int_Lf(z)dz=\int_a^bf\left(z(t)\right)z'(t)dt$$ 

其中 $z(t)=x(t)+iy(t)$ 为曲线参数方程 $z'(t)=x'(t)+iy'(t)$ 为参数方程的导数

***** 证明

由于 $$\int_Lf(z)dz=\int_a^b\bigg\{u\big(x(t),y(t)\big)x'(t)-v\big(x(t),y(t)\big)y'(t)\bigg\}dt+i\int_a^b\bigg\{v\big(x(t),y(t)\big)x'(t)+u\big(x(t),y(t)\big)y'(t)\bigg\}dt$$

根据[[~/OneDrive/数学分析/Chap7Note.org][定积分基本性质-线性]]可得：

\begin{aligned}
&\int_a^b\bigg\{u\big(x(t),y(t)\big)x'(t)-v\big(x(t),y(t)\big)y'(t)\bigg\}dt+i\int_a^b\bigg\{v\big(x(t),y(t)\big)x'(t)+u\big(x(t),y(t)\big)y'(t)\bigg\}dt\\
=&\int_a^b\bigg\{u\big(x(t),y(t)\big)x'(t)-v\big(x(t),y(t)\big)y'(t)+iv\big(x(t),y(t)\big)x'(t)+iu\big(x(t),y(t)\big)y'(t)\bigg\}dt\\
=&\int_a^b\bigg\{\left[u\big(x(t),y(t)\big)+iv\big(x(t),y(t)\big)\right]\left[x'(t)+iy'(t)\right]\bigg\}dt\\
=&\int_a^bf\left(z(t)\right)z'(t)dt
\end{aligned}

*** 连续可积

若 $f(z)$ [[MK62][连续]]，则 $f(z)$ 在有界闭区间内可积

**** 证明

根据[[MK71][之前证明]]可得

\begin{aligned}
&\sum_{i=1}^{n-1}(u(\alpha_i,\beta_i)+iv(\alpha_i,\beta_i))(\Delta a_i+i\Delta b_i)\\
=&\sum_{i=1}^{n-1}(u(\alpha_i,\beta_i),-v(\alpha_i,\beta_i))\cdot(\Delta a_i,\Delta b_i)+i\left(\sum_{i=1}^{n-1}(v(\alpha_i,\beta_i),u(\alpha_i,\beta_i))\cdot(\Delta a_i,\Delta b_i)\right)
\end{aligned}

即积分和式可转换为实部虚部两个第二类曲线积分的和式。

由于连续，故实部虚部均连续，故 $\vec{F}(x,y)=\left(u(x,y),-v(x,y)\right)$ 亦连续

根据[[~/OneDrive/数学分析/Chap14Note.org][第二类曲线积分-性质-连续函数可积]]可得 $\vec{F}(x,y)$ 可积

同理可证虚部可积，则函数可积。

*** 线性<<MK77>>

若 $f(z),g(z)$ 对于曲线 $L\subset\mathbb{C}$ 可积 $\{a,b\}\subset\mathbb{R}$ 则有 $\int_Laf(z)+bg(z)dz$ 收敛

且有 $\int_Laf(z)+bg(z)dz=a\int_Lf(z)dz+b\int_Lg(z)dz$

**** 证明 

根据积分定义 $f(z),g(z)$ 均可积

则有 $$\lim_{\lambda\to0}\sum_{i=1}^{n-1}f(\zeta_i)(x_{i+1}-x_i),\lim_{\lambda\to0}\sum_{i=1}^{n-1}g(\zeta_i)(x_{i+1}-x_i)$$ 两个极限对于对于任意划分和取点均收敛

则必有对于同样的划分，取点也会收敛于同一值，则根据极限四则运算

\begin{aligned}
&\int_Laf(z)+bg(z)dz\\
=&\lim_{\lambda\to0}\left\{\sum_{i=1}^{n-1}af(\zeta_i)(x_{i+1}-x_i)+\sum_{i=1}^{n-1}bg(\zeta_i)(x_{i+1}-x_i)\right\}\\
=&a\lim_{\lambda\to0}\sum_{i=1}^{n-1}f(\zeta_i)(x_{i+1}-x_i)+b\lim_{\lambda\to0}\sum_{i=1}^{n-1}g(\zeta_i)(x_{i+1}-x_i)\\
=&a\int_Lf(z)dz+b\int_Lg(z)dz
\end{aligned}

*** 区间可加<<MK74>>

若 $L$ 可分为 $L_1,L_2$ 两段，则有

（1） 若 $\int_Lf(z)dz$ 存在，则 $\int_{L_1}f(z)dz,\int_{L_2}f(z)dz$ 也存在

（2） 若 $\int_{L_1}f(z)dz,\int_{L_2}f(z)dz$ 存在，则 $\int_Lf(z)dz$ 也存在

且两种情况都有 $\int_Lf(z)dz=\int_{L_1}f(z)dz+\int_{L_2}f(z)dz$

**** 证明

根据[[MK71][之前证明]]可得

\begin{aligned}
&\sum_{i=1}^{n-1}(u(\alpha_i,\beta_i)+iv(\alpha_i,\beta_i))(\Delta a_i+i\Delta b_i)\\
=&\sum_{i=1}^{n-1}(u(\alpha_i,\beta_i),-v(\alpha_i,\beta_i))\cdot(\Delta a_i,\Delta b_i)+i\left(\sum_{i=1}^{n-1}(v(\alpha_i,\beta_i),u(\alpha_i,\beta_i))\cdot(\Delta a_i,\Delta b_i)\right)
\end{aligned}

即积分和式可转换为实部虚部两个第二类曲线积分的和式。

由于[[MK67][可积]]故实部虚部均可积。根据[[~/OneDrive/数学分析/Chap14Note.org][第二类曲线积分-性质-区间可加]]可得实部虚部均满足区间可加

故有复函数积分的区间可加性。

*** 长大不等式<<MK70>>

若 $f(z)$ 在可求长曲线 $L\subset\mathbb{C}$ 上可积且有：

（1） $l$ 为曲线 $L$ 的长度

（2） $M=\sup\left\{|f(z)|\big|z\in L\right\}$

则有 $\left|\int_Lf(z)dz\right|\leq Ml$

**** 证明

根据[[MK68][三角不等式]]，[[MK69][相乘等价]]可得 $\left|\sum_{i=1}^nf(\xi_i)\Delta z_i\right|\leq\sum_{i=1}^n\left|f(\xi_i)\right||\Delta z_i|\leq M\sum_{i=1}^n|\Delta z_i|$

根据[[~/OneDrive/数学分析/Chap14Note.org][可求长线段]]定义 $\lim_{\lambda\to0}\sum_{i=1}^n|\Delta z_i|=l$ 又由于弧长大于等于弦长，故有 $\sum_{i=1}^n|\Delta z_i|\leq l$

故有 $\left|\int_Lf(z)dz\right|\leq Ml$

** 引理

*** 引理1<<MK76>>

可求长曲线 $L\subset\mathbb{C}$ 其起点，终点分别为 $\alpha,\beta$ 则有：

（1） $$\int_Ldz=\beta-\alpha$$

（2） $$\int_Lzdz=\frac{1}{2}(\beta^2-\alpha^2)$$

**** 证明

***** 证明（1）

根据[[MK67][积分定义]]以及极限四则运算可得 

$$\int_Ldz=\lim_{\lambda\to0}\sum_{i=1}^n\Delta z_i=\lim_{\lambda\to0}\sum_{i=1}^n(z_{i+1}-z_i)=\lim_{\lambda\to0}\left\{z_{n+1}-z_n\right\}=\beta-\alpha$$

***** 证明（2）

根据[[MK67][积分定义]]以及极限四则运算可得 $$\int_Lzdz=\lim_{\lambda\to0}\sum_{i=1}^n\xi_i\Delta z_i=\lim_{\lambda\to0}\sum_{i=1}^n\xi_i(z_{i+1}-z_i)$$

由于 $\xi_i$ 需对任意取值均收敛于同一值，则有 $$\int_Lzdz=\lim_{\lambda\to0}\sum_{i=1}^n\z_i(z_{i+1}-z_i)=\lim_{\lambda\to0}\sum_{i=1}^n\z_{i+1}(z_{i+1}-z_i)$$ 则有

\begin{aligned}
&2\int_Lzdz=\lim_{\lambda\to0}\sum_{i=1}^n\z_i(z_{i+1}-z_i)+\lim_{\lambda\to0}\sum_{i=1}^n\z_{i+1}(z_{i+1}-z_i)\\
=&\lim_{\lambda\to0}\sum_{i=1}^n\left\{(z_{i+1}-z_i)(z_{i+1}-z_i)\right\}\\
=&\lim_{\lambda\to0}\sum_{i=1}^n\left\{z^2_{i+1}-z^2_i\right\}\\
=&\lim_{\lambda\to0}\left\{z^2_{n_1}-z^2_1\right\}\\
=&z^2_{n_1}-z^2_1
\end{aligned}

故有 $$\int_Lzdz=\frac{1}{2}(\beta^2-\alpha^2)$$

*** 引理2<<MK78>>

若 $D\subset\mathbb{C}$ 为有界闭区域且 $f(z)$ 是 $D$ 上的连续函数，则对于可求长曲线 $L\subset D$ 均存在折线 $P$ 满足：

（1） $P$ 与 $L$ 有相同首尾点，且 $P$ 的顶点落在 $L$ 上

（2） $\forall\epsilon>0$ 存在 $P$ 使得 $$\left|\int_L f(z)dz-\int_Pf(z)dz\right|<\epsilon$$

**** 证明

根据[[MK61][定理]]函数可有等价映射 $u(x,y)+iv(x,y)$ 根据[[MK62][连续]]定义可得 $u(x,y),v(x,y)$ 亦连续

定义 $L$ 长度为 $l$ ，由于 $L$ 为有界闭集，故根据[[~/OneDrive/数学分析/Chap11Note.org][连续函数性质-康托定理]]可得 $u(x,y),v(x,y)$ 一致连续。

则可证 $f(z)$ [[MK66][一致连续]]，即 $\forall\epsilon>0,\exists\delta'>0,\forall|z'-z''|<\delta\Rightarrow|f(z')-f(z'')|<\frac{\epsilon}{2l}$

根据[[MK67][积分]]定义 $\forall\epsilon>0,\exists\delta''>0,\forall\lambda<\delta\Rightarrow\left|\sum_{i=1}^{n-1}f(\zeta_i)\Delta z_i-\int_L f(z)dz\right|<\frac{\epsilon}{2}$ 其中 $\lambda=\max(|\Delta z_i|)$

则 $\forall\epsilon>0,\exists\delta=\min(\delta',\delta'')$ 取其中一种分点，构造折线 $P$ 满足 $\lambda<\delta$

由于上述条件对于任意划分取点均成立，故有

\begin{aligned}
&\left|\int_L f(z)dz-\int_Pf(z)dz\right|\\
=&\left|\int_L f(z)dz-\sum_{i=1}^{n-1}f(\zeta_i)\Delta z_i+\sum_{i=1}^{n-1}f(\zeta_i)\Delta z_i-\int_Pf(z)dz\right|\\
\leq&\left|\int_L f(z)dz-\sum_{i=1}^{n-1}f(\zeta_i)\Delta z_i\right|+\left|\sum_{i=1}^{n-1}f(\zeta_i)\Delta z_i-\int_Pf(z)dz\right|\\
<&\frac{\epsilon}{2}+\left|\sum_{i=1}^{n-1}f(\zeta_i)\Delta z_i-\int_P f(z)dz\right|\\
=&\frac{\epsilon}{2}+\left|\sum_{i=1}^{n-1}f(\zeta_i)\Delta z_i-\sum_{i=1}^{n-1}\int_{P_i} f(z)dz\right|\\
=&\frac{\epsilon}{2}+\left|\sum_{i=1}^{n-1}\int_{P_i}f(\zeta_i)dz-\sum_{i=1}^{n-1}\int_{P_i} f(z)dz\right|\\
=&\frac{\epsilon}{2}+\left|\sum_{i=1}^{n-1}\int_{P_i}\left(f(\zeta_i)dz-f(z)\right)dz\right|\\
\leq&\frac{\epsilon}{2}+\sum_{i=1}^{n-1}\left|\int_{P_i}\left(f(\zeta_i)dz-f(z)\right)dz\right|
\end{aligned}

由于 $L$ 可求长且 $P$ 为折线，则必有 $P$ 的长度小于 $l$ 。定义 $P_i$ 的长度为 $p_i$

故根据[[MK70][长大不等式]]可得

\begin{aligned}
&\left|\int_L f(z)dz-\int_Pf(z)dz\right|\\
\leq&\frac{\epsilon}{2}+\sum_{i=1}^{n-1}\left|\int_{P_i}\left(f(\zeta_i)dz-f(z)\right)dz\right|\\
\leq&\frac{\epsilon}{2}+\frac{\epsilon}{l2}\sum_{i=1}^{n-1}p_i\\
\leq&\frac{\epsilon}{2}+\frac{\epsilon}{l2}l=\epsilon
\end{aligned}

综上所述 $$\forall\epsilon>0,\exists\delta,\forall\lambda<\delta\Rightarrow\forall P\rightarrow\left|\int_L f(z)dz-\int_Pf(z)dz\right|<\epsilon$$ 其中 $P$ 为满足条件的分点构成的折线 

*** 引理3<<MK85>>

定义 $L$ 为复平面上任意半径 $r>0$ 的圆周，圆心为 $\alpha$ 则 $$\int_L\frac{1}{(z-\alpha)^n}dz=\begin{cases}2\pi i&n=1\\0&n\ne1\end{cases}$$ 其中 $n\in\mathbb{N}$ 为整数

**** 证明

定义 $L$ 的参数方程为 $z(t)=\alpha+r\left(\cos(t)+i\sin(t)\right)$ 根据[[~/OneDrive/大学物理/Note/DiffEq.org][欧拉公式]]可得 $z(t)=\alpha+re^{it}$ 其中 $t\in[0,2\pi]$

则根据[[MK82][推论]]可得 

\begin{aligned}
\int_L\frac{1}{(z-\alpha)^n}dz=&\int_0^{2\pi}\frac{1}{\left(re^{it}\right)^n}z'(t)dt\\
=&\int_0^{2\pi}\frac{ire^{it}}{r^ne^{nit}}dt\\
=&r^{1-n}i\int_0^{2\pi}e^{i(1-n)t}dt\\
\end{aligned}

此时当 $n=1$ 时 $$\int_L\frac{1}{(z-\alpha)^n}dz=i\int_0^{2\pi}1dt=i2\pi$$

此时当 $n\ne1$ 时，由于 $n\in\mathbb{N}$ 则有 $(1-n)2\pi$ 是 $2\pi$ 的整数倍，故有 $\cos((1-n)2\pi)=1,\sin((1-n)2\pi)=0$ 

则： 

\begin{aligned}
\int_L\frac{1}{(z-\alpha)^n}dz=&r^{1-n}i\int_0^{2\pi}e^{i(1-n)t}dt\\
=&r^{1-n}i\left(\frac{e^{i(1-n)2\pi}}{i(1-n)}-\frac{e^{i(1-n)0}}{i(1-n)}\right)\\
=&r^{1-n}i\frac{e^{(1-n)2\pi}-1}{i(1-n)}\\
=&r^{1-n}i\frac{\cos((1-n)2\pi)+i\sin((1-n)2\pi)-1}{i(1-n)}\\
=&r^{1-n}i\frac{1+i0-1}{i(1-n)}\\
=&0
\end{aligned}

** 定理

*** 柯西积分定理<<MK84>>

若 $D\subset\mathbb{C}$ 是[[~/OneDrive/数学分析/Chap14Note.org][Green公式，Gauss公式，Stokes公式-前提定义-平面单连通区域]]，函数 $f(z)$ 在 $z\in D$ 上[[MK65][解析]]

若有[[MK81][简单]]闭合曲线 $L\subset D$ ，其包含的区域亦为单连通，则有 $$\int_Lf(z)dz=0$$

**** 证明

***** 证明三角形区域

****** 划分区域

若闭合曲线 $L$ 围城的区域为三角形，定义为 $\Delta$ 。则连接三角形三条边中点，可将其分解为 $4$ 个子三角形

定义子三角形边为 $L_1,L_2,L_3,L_4$ 积分方向与 $L$ 的积分方向一致。

由于连接中点的边分在不同的子三角形以不同方向积分，故相互抵消

则根据[[MK74][区间可加]]有 $$\int_Lf(z)dz=\sum_{i=1}^4\int_{L_i}f(z)dz$$

根据[[MK68][三角不等式]]可得 $$\left|\int_Lf(z)dz\right|\leq\sum_{i=1}^4\left|\int_{L_i}f(z)dz\right|$$ 定义 $$M=\left|\int_Lf(z)dz\right|$$

则必有一个 $$\left|\int_{L_i}f(z)dz\right|\geq\frac{M}{4}$$ 定义三角形为 $\Delta_1$ 若 $L$ 曲线长度为 $l$ 则 $\Delta_1$ 的周长度为 $\frac{l}{2}$

三角形 $\Delta_1$ 可以以同样方式取到 $\Delta_2$ 依次类推可得，定义 $\Delta_n$ 的周边闭合曲线为 $L^{(n)}$ ：

（1） $\Delta_1\supset\Delta_1\supset...\supset\Delta_n\supset...\a$

（2） $\lim_{n\to\infty}diam\Delta_n=0$ 其中 $diam\Delta_n$ 为 $\Delta_n$ 包含点的最远距离

（3） $\Delta_n$ 周长为 $\frac{l}{2^n}$

（4） $$\left|\int_{L^{(n)}}f(z)dz\right|\geq\frac{M}{4^n}$$

利用以上（1）（2）条件，根据[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-康托闭区域套定理]]可得

复平面上必存在一个点 $z_0\in D$ 满足 $z_0\in\cap_{i=1}^\infty\Delta_i$

****** 利用解析性质

由于[[MK65][解析]]，则必有在 $z_0$ 点[[MK63][可导]]，则有 $\forall\epsilon>0,\exists\delta>0,\forall|z-z_0|<\delta\Rightarrow\left|\frac{f(z)-f(z_0)}{z-z_0}-f'(z_0)\right|<\epsilon$

根据[[MK69][相乘等价]]两边同乘 $|z-z_0|$ 整理后得 $\left|f(z)-f(z_0)-f'(z_0)z+f'(z_0)z_0\right|<\epsilon|z-z_0|$

取 $n$ 足够大使得 $\forall z\in\Delta_n\Rightarrow |z-z_0|<\delta$ 由于 $|z-z_0|$ 显然小于等于三角形周长

故有 $\left|f(z)-f(z_0)-f'(z_0)z+f'(z_0)z_0\right|<\epsilon\frac{l}{2^n}$ 。则根据[[MK76][引理1]]以及[[MK77][线性]]可得：

\begin{aligned}
&\int_{L^{(n)}}f(z)-f(z_0)-f'(z_0)z+f'(z_0)z_0dz\\
=&\int_{L^{(n)}}f(z)dz-f(z_0)\int_{L^{(n)}}dz-f'(z_0)\int_{L^{(n)}}zdz+f'(z_0)\int_{L^{(n)}}dz\\
=&\int_{L^{(n)}}f(z)dz
\end{aligned}

****** 结论

根据[[MK70][长大不等式]]可得 $$\left|\int_{L^{(n)}}f(z)\right|\leq\frac{l}{2^n}\epsilon\frac{l}{2^n}$$ 则有 $$\frac{M}{4^n}\leq\left|\int_{L^{(n)}}f(z)\right|\leq\frac{l}{2^n}\epsilon\frac{l}{2^n}$$

最终 $M\leq \epsilon l^2$ 由于对于任意小的 $\epsilon>0$ 该式成立，故有 $$\left|\int_Lf(z)dz\right|=M=0$$ 则 $$\int_Lf(z)dz=0$$
 
***** 其他区域

对于其他区域，利用[[MK78][引理2]]有折线 $P$ 满足：

（1） $P$ 与 $L$ 有相同首尾点，且 $P$ 的顶点落在 $L$ 上

（2） $\forall\epsilon>0$ 存在 $P$ 使得 $$\left|\int_L f(z)dz-\int_Pf(z)dz\right|<\epsilon$$

由于 $L$ 闭合曲线包围单连通区域，且除首尾外无交点，故 $P$ 围成边不相交的多边形

由于 $P$ 为有限边折线，则进一步根据[[MK79][多边形三角化]]可分割成有限个三角形。

故根据三角形区域证明及[[MK74][区间可加]]可得 $$\int_Pf(z)dz=\sum_{i=1}^n\int_{\Delta_i}f(z)dz=0$$

又有条件（2）得 $$\int_Lf(z)dz=0$$

*** 柯西积分公式<<MK88>>

若 $D\subset\mathbb{C}$ 是有界的[[~/OneDrive/数学分析/Chap14Note.org][Green公式，Gauss公式，Stokes公式-前提定义-平面单连通区域]]，函数 $f(z)$ 在 $D$ 上[[MK65][解析]]

若有[[MK81][简单]]闭合曲线 $L\subset D$ 且点 $z_0\not\in L$ 在 $L$ 包含的区域内，则有 $$f(z_0)=\frac{1}{2\pi i}\int_L\frac{f(z)}{z-z_0}dz$$

**** 证明 

***** 转化被积曲线

定义 $L$ 围成的区域为 $D'$ 由于 $z_0\in D'$ 且不在边界 $L$ 上，故必存在以 $z_0$ 为圆心的圆 $D^o_0\subset D'$

定义 $D^o_0$ 的半径为 $r'$ 。由于 $f(z)$ 解析，故根据[[MK83][导数与解析]]可得连续，

则根据[[MK62][函数连续]]与[[MK57][函数极限]]可得 $\forall\epsilon>0,\exists\rho>0,\forall|z-z_0|<\rho\Rightarrow\left|f(z)-f(z_0)\right|<\epsilon$

取 $z_0$ 为圆心 $r=\min\left(\frac{\rho}{2},r'\right)$ 的圆 $D^o_1$ 其边界为 $L^o$

此时 $D/D^o_1$ 并非单联通，原因为包含 $D^o_1$ 的闭合曲线

过 $z_0$ 点作直线 $l$ ，将 $D/D^o_1$ 划分为两个区域，由于无法不经过 $l$ 作包含 $D^o_1$ 且在 $D/D^o_1$ 内的曲线

故划分后两个区域均为单联通，记作 $D_1,D_2$ 

由 $L,l,L_o$ 围成，分别在 $D_1,D_2$ 上的闭合曲线记作 $L_1,L_2$ 此时有：

（1） $\frac{f(z)}{z-z_0}$ 在 $D_1,D_2$ 及其边界上解析

（2） $L$ 为简单曲线

（3） $l$ 为直线 $L_o$ 为圆周，两者亦为简单曲线

（4） 由（2），（3）可得 $L_1,L_2$ 亦为简单曲线

故根据[[MK84][柯西积分定理]]可得 $$\int_{L_1}\frac{f(z)}{z-z_0}dz=0\land\int_{L_2}\frac{f(z)}{z-z_0}dz=0$$

若规定顺时针为正方向，则 $L_1,L_2$ 在 $l$ 处重合且方向相反， $L$ 为顺时针 $L^o$ 为逆时针

根据[[MK47][区间可加]]可得 $$\int_{L_1}\frac{f(z)}{z-z_0}dz+\int_{L_2}\frac{f(z)}{z-z_0}dz=\int_{L}\frac{f(z)}{z-z_0}dz-\int_{L^o}\frac{f(z)}{z-z_0}dz=0$$

固有 $$\int_{L}\frac{f(z)}{z-z_0}dz=\int_{L^o}\frac{f(z)}{z-z_0}dz$$

***** 证明结论

根据[[MK85][引理3]]可得 $$\int_{L^o}\frac{1}{(z-z_0)^n}dz=2\pi i$$ 固有 $$f(z_0)\frac{1}{2\pi i}\int_{L^o}\frac{1}{(z-z_0)^n}dz=f(z_0)$$

即 $$f(z_0)=\frac{1}{2\pi i}\int_{L^o}\frac{f(z_0)}{(z-z_0)^n}dz$$ 另根据[[MK69][相乘等价]]以及[[MK86][分母]]可得

\begin{aligned}
\left|\frac{f(z)-f(z_0)}{z-z_0}\right|=&|f(z)-f(z_0)|\left|\frac{1}{z-z_0}\right|\\
=&\frac{|f(z)-f(z_0)|}{r}\\
<&\frac{\epsilon}{r}
\end{aligned}

则根据[[MK69][相乘等价]]、[[MK77][线性]]以及[[MK70][长大不等式]]

\begin{aligned}
&\left|\frac{1}{2\pi i}\int_L\frac{f(z)}{z-z_0}dz-\frac{1}{2\pi i}\int_{L^o}\frac{f(z_0)}{(z-z_0)^n}dz\right|\\
=&\left|\frac{1}{2\pi i}\int_{L_o}\frac{f(z)}{z-z_0}dz-\frac{1}{2\pi i}\int_{L^o}\frac{f(z_0)}{(z-z_0)^n}dz\right|\\
=&\left|\frac{1}{2\pi i}\int_{L_o}\frac{f(z)-f(z_0)}{z-z_0}dz\right|\\
=&\left|\frac{1}{2\pi i}\right|\left|\int_{L_o}\frac{f(z)-f(z_0)}{z-z_0}dz\right|\\
\leq&\frac{1}{2\pi}\frac{\epsilon}{r}2\pi r\\
=&\epsilon
\end{aligned}

由于 $\epsilon$ 的任意性，故有  $$f(z_0)=\frac{1}{2\pi i}\int_{L^o}\frac{f(z_0)}{(z-z_0)^n}dz=\frac{1}{2\pi i}\int_{L^o}\frac{f(z)}{(z-z_0)^n}dz=\frac{1}{2\pi i}\int_{L}\frac{f(z)}{(z-z_0)^n}dz$$

证毕 

*** 柯西积分公式推广<<MK92>>

若 $D\subset\mathbb{C}$ 是有界的[[~/OneDrive/数学分析/Chap14Note.org][Green公式，Gauss公式，Stokes公式-前提定义-平面单连通区域]]，函数 $f(z)$ 在 $D$ 上[[MK65][解析]]

若有[[MK81][简单]]闭合曲线 $L\subset D$ 且点 $z_0\not\in L$ 在 $L$ 包含的区域内，则有 $$f^{(n)}(z_0)=\frac{n!}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^{n+1}}dz$$

**** 证明

以数学归纳法证明

***** 当 $n=1$

****** 基础定义与证明<<MK89>>

任取一点 $z_0\not\in L$ 但被 $L$ 包含的点，定义 $\rho=\inf_{z\in L}\left|z-z_0\right|$ 定义 $\delta=\min\left(\frac{\rho}{2},1\right)$

则取 $\xi\in O(z_0,\delta)$ 时根据[[MK87][分式]]有 $\left|\frac{\xi-z_0}{z-z_0}\right|=\frac{|\xi-z_0|}{|z-z_0|}\leq\frac{|\xi-z_0|}{\rho}\leq\frac{\min\left(\frac{\rho}{2},1\right)}{\rho}\leq\frac{1}{2}$

另根据等比数列求和公式 $\sum_{i=0}^naq^i=a\frac{1-q^n}{1-q}$ 有：

\begin{aligned}
\frac{1}{z-\xi}=&\frac{1}{z-z_0}\frac{z-z_0}{z-\xi}\\
=&\frac{1}{z-z_0}\frac{1}{\frac{z-\xi}{z-z_0}}=\frac{1}{z-z_0}\frac{1}{\frac{z-z_0+z_0-\xi}{z-z_0}}\\
=&\frac{1}{z-z_0}\frac{1}{1+\frac{z_0-\xi}{z-z_0}}=\frac{1}{z-z_0}\frac{1}{1-\frac{\xi-z_0}{z-z_0}}\\
=&\frac{1}{z-z_0}\left(\sum_{i=0}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i}\right)\\
=&\frac{1}{z-z_0}\left(1+\frac{\xi-z_0}{z-z_0}+\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i\right)
\end{aligned}

****** 推导条件<<MK90>>

根据[[MK88][柯西积分公式]]、[[MK77][线性]]有 

\begin{aligned}
f(\xi)=&\frac{1}{2\pi i}\int_L\frac{f(z)}{z-\xi}dz\\
=&\frac{1}{2\pi i}\int_L\frac{f(z)}{z-z_0}\left(1+\frac{\xi-z_0}{z-z_0}}+\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i\right)dz\\
=&\frac{1}{2\pi i}\int_L\frac{f(z)}{z-z_0}dz+\frac{\xi-z_0}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^2}+\frac{1}{2\pi i}\int_L\frac{f(z)\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i}{z-z_0}dz\\
=&f(z_0)+\frac{\xi-z_0}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^2}+\frac{1}{2\pi i}\int_L\frac{f(z)\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i}{z-z_0}dz\\
f(\xi)-f(z_0)=&\frac{\xi-z_0}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^2}+\frac{1}{2\pi i}\int_L\frac{f(z)\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i}{z-z_0}dz\\
\frac{f(\xi)-f(z_0)}{\xi-z_0}=&\frac{1}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^2}+\frac{1}{2\pi i(\xi-z_0)}\int_L\frac{f(z)\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i}{z-z_0}dz\\
\end{aligned}

由于 $L$ 为有界闭集且 $f(z)$ 解析，故 $f(z)$ 连续，根据[[~/OneDrive/数学分析/Chap11Note.org][连续函数性质-有界性定理]]可得有界

定义 $M\geq\left|f(z)\right|,z\in L$ 则根据[[MK87][分式]]、[[MK69][相乘]]、[[MK68][三角不等式]]以及[[MK89][之前证明]]有：

\begin{aligned}
\left|\frac{f(z)\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i}{z-z_0}\right|=&\frac{|f(z)|\left|\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i\right|}{|z-z_0|}\\
\leq&\frac{M}{|z-z_0|}\sum_{i=2}^\infty\left|\frac{\xi-z_0}{z-z_0}\right|^i\\
=&\frac{M}{|z-z_0|}\left|\frac{\xi-z_0}{z-z_0}\right|^2\sum_{i=0}^\infty\left|\frac{\xi-z_0}{z-z_0}\right|^i\\
=&\frac{M|\xi-z_0|^2}{|z-z_0|^3}\sum_{i=0}^\infty\left|\frac{\xi-z_0}{z-z_0}\right|^i\\
\leq&\frac{M|\xi-z_0|^2}{|z-z_0|^3}\sum_{i=0}^\infty\left(\frac{1}{2}\right)^i\\
=&\frac{2M|\xi-z_0|^2}{|z-z_0|^3}\\
\leq&\frac{2M|\xi-z_0|^2}{\rho^3}
\end{aligned}

则定义 $L$ 长度 $l$ 根据[[MK70][长大不等式]]有 

\begin{aligned}
&\left|\frac{1}{2\pi i(\xi-z_0)}\int_L\frac{f(z)\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i}{z-z_0}dz\right|\\
\leq&\frac{1}{|2\pi i||\xi-z_0|}\frac{2M|\xi-z_0|^2}{\rho^3}l\\
=&\frac{2Ml|\xi-z_0|}{2\pi\rho^3}
\end{aligned}

****** 证明结论

由于模大于零，则根据夹逼定理有 $$\lim_{\xi\to z_0}\left|\frac{1}{2\pi i(\xi-z_0)}\int_L\frac{f(z)\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i}{z-z_0}dz\right|=0$$ 

故有  $$\lim_{\xi\to z_0}\frac{1}{2\pi i(\xi-z_0)}\int_L\frac{f(z)\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i}{z-z_0}dz=0$$ 

则有：

\begin{aligned}
\lim_{\xi\to z_0}\frac{f(\xi)-f(z_0)}{\xi-z_0}=&\lim_{\xi\to z_0}\left\{\frac{1}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^2}+\frac{1}{2\pi i(\xi-z_0)}\int_L\frac{f(z)\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i}{z-z_0}dz\right\}\\
=&\frac{1}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^2}+\lim_{\xi\to z_0}\left\{\frac{1}{2\pi i(\xi-z_0)}\int_L\frac{f(z)\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i}{z-z_0}dz\right\}\\
=&\frac{1}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^2}
\end{aligned}

即 $$f'(z_0)=\frac{1!}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^{1+1}}$$

***** 当 $k$ 成立时 $n=k+1$

****** 基础定义与证明

由于 $k$ 成立，则有 $$f^{(k)}(z_0)=\frac{k!}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^{k+1}}dz$$ 存在

沿用[[MK89][之前证明]]中的定义，并定义 $$U=\sum_{i=2}^\infty\left(\frac{\xi-z_0}{z-z_0}\right)^i$$ 来简化表达式，则根据二项式定理有：

\begin{aligned}
\frac{1}{(z-\xi)^{k+1}}=&\left(\frac{1}{z-z_0}\left(1+\frac{\xi-z_0}{z-z_0}+U\right)\right)^{k+1}\\
=&\frac{1}{(z-z_0)^{k+1}}\left(1+\frac{\xi-z_0}{z-z_0}+U\right)^{k+1}\\
=&\frac{1}{(z-z_0)^{k+1}}\sum_{j=0}^{k+1}\binom{k+1}{j}\left(\frac{\xi-z_0}{z-z_0}+U\right)^j\\
=&\frac{1}{(z-z_0)^{k+1}}\left(1+(k+1)\left(\frac{\xi-z_0}{z-z_0}+U\right)+\sum_{j=2}^{k+1}\binom{k+1}{j}\left(\frac{\xi-z_0}{z-z_0}+U\right)^j\right)\\
=&\frac{1}{(z-z_0)^{k+1}}\left(1+(k+1)\left\frac{\xi-z_0}{z-z_0}+\left((k+1)U+\sum_{j=2}^{k+1}\binom{k+1}{j}\left(\frac{\xi-z_0}{z-z_0}+U\right)^j\right)\right)\\
\end{aligned}

****** 推导不等式

根据[[MK91][模的性质]]，以及[[MK90][之前证明]]有 $$U\leq|\xi-z_0|^2\frac{2}{\rho^2}$$ 且收敛，故作如下定义及推导

\begin{aligned}
V=&\left|(k+1)U+\sum_{j=2}^{k+1}\binom{k+1}{j}\left(\frac{\xi-z_0}{z-z_0}+U\right)^j\right|\\
\leq&\left|(k+1)U\right|+\left|\sum_{j=2}^{k+1}\binom{k+1}{j}\left(\frac{\xi-z_0}{z-z_0}+U\right)^j\right|\\
\leq&|(\xi-z_0)^2|\left|\frac{2(k+1)}{\rho^2}\right|+\sum_{j=2}^{k+1}\binom{k+1}{j}\left|\left(\frac{\xi-z_0}{z-z_0}+U\right)^j\right|\\
=&|(\xi-z_0)^2|\left|\frac{2(k+1)}{\rho^2}\right|+\sum_{j=2}^{k+1}\binom{k+1}{j}\left|\left(\frac{\xi-z_0}{z-z_0}+U\right)^{j-2}\left(\left(\frac{\xi-z_0}{z-z_0}\right)^2+2\frac{\xi-z_0}{z-z_0}U+U^2\right)\right|\\
=&|(\xi-z_0)^2|\left|\frac{2(k+1)}{\rho^2}\right|+\sum_{j=2}^{k+1}\binom{k+1}{j}\left|\frac{\xi-z_0}{z-z_0}+U\right|^{j-2}\left|\left(\frac{\xi-z_0}{z-z_0}\right)^2+2\frac{\xi-z_0}{z-z_0}U+U^2\right|\\
\leq&|(\xi-z_0)^2|\left|\frac{2(k+1)}{\rho^2}\right|+\sum_{j=2}^{k+1}\binom{k+1}{j}\left|\frac{\xi-z_0}{z-z_0}+U\right|^{j-2}\left(\left|\frac{\xi-z_0}{z-z_0}\right|^2+2\left|\frac{\xi-z_0}{z-z_0}\right||U|+|U|^2\right)\\
\leq&|(\xi-z_0)^2|\left|\frac{2(k+1)}{\rho^2}\right|+\sum_{j=2}^{k+1}\binom{k+1}{j}\left|\frac{\xi-z_0}{z-z_0}+U\right|^{j-2}\left(\frac{|\xi-z_0|^2}{|z-z_0|^2}+2\left|\frac{\xi-z_0}{z-z_0}\right||\xi-z_0|^2\frac{2}{\rho^2}+|U||\xi-z_0|^2\frac{2}{\rho^2}\right)\\
=&|(\xi-z_0)^2|\left\{\left|\frac{2(k+1)}{\rho^2}\right|+\sum_{j=2}^{k+1}\binom{k+1}{j}\left|\frac{\xi-z_0}{z-z_0}+U\right|^{j-2}\left(\frac{1}{|z-z_0|^2}+2\left|\frac{\xi-z_0}{z-z_0}\right|\frac{2}{\rho^2}+|U|\frac{2}{\rho^2}\right)\right\}\\
\leq&|(\xi-z_0)^2|C
\end{aligned}

由于 $z_0$ 确定 $U$ 收敛 $|\xi-z_0|$ 有界，故后半部分有界，故存在常数 $C$ 大于其模

****** 推导导数结论

根据[[MK90][之前证明]]可推导 $$\frac{f^{(k)}(\xi)-f^{(k)}(z_0)}{\xi-z_0}=&\frac{k!(k+1)}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^{k+2}}+\frac{k!}{2\pi i(\xi-z_0)}\int_L\frac{f(z)V}{(z-z_0)^{k+1}}dz$$

同样根据[[MK90][之前定义]] $M\geq|f(z)|$ 有界，故根据[[MK70][长大不等式]]结合上一步证明有 $$\left|\int_L\frac{f(z)V}{z-z_0}dz\right|\leq\frac{|\xi-z_0|^2CMl}{|\rho|^{k+1}}$$

故有 $$\left|\frac{k!}{2\pi i(\xi-z_0)}\int_L\frac{f(z)V}{(z-z_0)^{k+1}}dz\right|\leq\frac{|\xi-z_0|CMl(k!)}{2\pi|\rho|^{k+1}}$$

由于模大于零，则根据夹逼定理有 $$\lim_{\xi\to z_0}\left|\frac{k!}{2\pi i(\xi-z_0)}\int_L\frac{f(z)V}{(z-z_0)^{k+1}}dz\right|=0$$ 则有:

\begin{aligned}
\lim_{\xi\to z_0}\frac{f^{(k)}(\xi)-f^{(k)}(z_0)}{\xi-z_0}=&\lim_{\xi\to z_0}\left\{\frac{k!(k+1)}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^{k+2}}+\frac{k!}{2\pi i(\xi-z_0)}\int_L\frac{f(z)V}{(z-z_0)^{k+1}}dz\right\}\\
=&\frac{k!(k+1)}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^{k+2}}+\lim_{\xi\to z_0}\left\{\frac{k!}{2\pi i(\xi-z_0)}\int_L\frac{f(z)V}{(z-z_0)^{k+1}}dz\right\}\\
=&\frac{k!(k+1)}{2\pi i}\int_L\frac{f(z)}{(z-z_0)^{k+2}}
\end{aligned}

证毕。

*** 刘维尔定理

若函数 $f(z)$ 在复平面 $z\in\mathbb{C}$ 上[[MK65][解析]]且有界，则 $f(z)$ 必定为常数函数，即 $f(z)=K$ 其中 $K\in\mathbb{C}$ 为常数

**** 证明

由于解析，故对于任意圆心为 $z_0$ 任意半径为 $R$ 的在复平面上的圆周曲线 $O$ 满足[[MK92][柯西积分推广公式]]

故有 $$f'(z_0)=\frac{1}{2\pi i}\int_O\frac{f(z)}{(z-z_0)^{2}}dz$$ 

同样由于解析，故 $f(z)$ 有界，定义 $\forall z\in\mathbb{C}\left(|f(z)|\leq M\right)$ 

故根据[[MK87][分式]]有 $$\left|\frac{f(z)}{(z-z_0)^{2}}\right|=\frac{|f(z)|}{|z-z_0|^{2}}\leq\frac{M}{R^2}$$

则根据[[MK70][长大不等式]]有 $$\left|\frac{1}{2\pi i}\int_O\frac{f(z)}{(z-z_0)^{2}}dz\right|\leq\frac{2\pi RM}{2\pi R^2}=\frac{M}{R}$$

由于半径任意，故 $R\to\infty\Rightarrow\frac{M}{R}\to 0$ 故 $f'(z_0)=0$

由于圆心任意，故 $f'(z)=0,\forall z\in\mathbb{C}$ 故在任意点的导数为另，即常函数 




