#+LATEX_HEADER:

#+TITLE: 离散数学概论

currnet mark: 337

free mark:
 
数理逻辑: P26

* 集合论

** 集合论语言<<MK1>>

*** 符号及表达式

集合论语言为[[~/文档/note/数理逻辑/sllj.org::MK104][一阶语言]]，除[[~/文档/note/数理逻辑/sllj.org::MK105][固定符号]]外尤其仅有一个[[~/文档/note/数理逻辑/sllj.org::MK110][谓词符号]] $\mathcal{A}_c=\{p_\in\}$ 其中根据[[~/文档/note/数理逻辑/sllj.org::MK112][符号假定]]有 $\pi_P(p_\in)=2$

为方便书写：

（1） 定义 $p_\in(x,y)$ 书写为 $(x\in y)$

（2） 定义 $(x\hat{=}y)$ 书写为 $(x=y)$

（3） 定义 $\lnot(x\hat{=}y)$ 书写为 $(x\ne y)$

集合论的[[~/文档/note/数理逻辑/sllj.org::MK129][表达式]]均遵循以上简写

*** 等式符号

语言规定[[~/文档/note/数理逻辑/sllj.org::MK105][等式符号]] $\hat{=}$ 必须满足[[MK132][等价关系]]，由[[MK2][外延公理]]定义

** 集合论非逻辑公理

*** 外延公理<<MK2>>

形式语言： $(\forall x(\forall y((x=y)\to(\forall z((z\in x)\leftrightarrow(z\in y))))))$

即当且仅当 $x,y$ 中具有相同的[[MK45][元素]]，集合 $x,y$ 相等，显然满足[[MK132][等价关系]]

该公理说明了：

（1） 集合元素的 *无序性*

（2） 集合表示的 *不唯一性*

*** 第一存在性<<MK3>>

$\exists x(x=x)$ 即存在一个集合

*** 幂集公理<<MK4>>

形式语言： $\forall A\exists B\forall z\big(z\in B\leftrightarrow z\subset A\big)$

即对于任意结合 $A$ 其[[MK20][幂集]] $B$ 存在且亦为集合

*** 分离公理模式<<MK5>>

形式语言： $\forall p_1(...(\forall p_n(\forall U(\exists S(\forall x((x\in S)\leftrightarrow((x\in U)\land \phi(p_1,...,p_n,x)))))))...)$

其中 $n\in\mathbb{N}$ 是自然数， $\phi(p_1,...,p_n,x)$ 是[[~/文档/note/数理逻辑/sllj.org::MK140][自由变元]]为 $p_1,...,p_n,x$ 且不包含 $U,S$ 的[[~/文档/note/数理逻辑/sllj.org::MK129][表达式]]

即对于任一集合 $U$ 存在 $S$ 使得 $x\in S$ 的充要条件是 $x\in U\land \phi(p_1,...,p_n,x)$ 

即对于任意一组给定的 $p_1,...,p_n$ 以及给定的 $U$ 均存在 $S=\left\{x\big|((x\in U)\land\phi(p_1,...,p_n,x))\right\}$

**** 唯一性

设 $x$ 为一个集合 $\phi(a_1,...,a_n,z)$ 是[[~/文档/note/数理逻辑/sllj.org::MK140][自由变元]]为 $a_1,...,a_n,z$ 且不包含 $x$ 的[[~/文档/note/数理逻辑/sllj.org::MK129][表达式]]

则当 $a_1,...,a_n$ [[~/文档/note/数理逻辑/sllj.org::MK154][赋值]]确定时，存在唯一的 $y$ 满足 $\forall z((z\in y)\leftrightarrow((z\in x)\land(\phi(a_1,...,a_n,z))))$

***** 证明

假设存在 $y_1,y_2$ 同时满足，则对于任意 $z$

有 $(z\in y_1)\leftrightarrow((z\in x)\land(\phi(a_1,...,a_n,z)))\leftrightarrow(z\in y_2)$

则根据[[MK2][外延公理]]可得 $y_1=y_2$

**** 推论

$\lnot(\exists x(\forall y(y\in x)))$ 即不存在包含一切集合的集合

***** 证明

假设 $\exists x(\forall y(y\in x))$ 成立，则存在 $x$ 包含所有集合

定义 $y=\left\{z\in x\big|z\not\in z\right\}$ 根据[[MK5][分离模式]]可得 $y$ 是一个集合，则有 $y\in x$

此时若 $y\in y$ 则根据 $y$ 的定义有 $y\not\in y$ ，若 $y\not\in y$ 则根据 $y$ 的定义有 $y\in y$

故推出矛盾，即假设不成立，有 $\lnot(\exists x(\forall y(y\in x)))$ 

**** 空集存在<<MK6>>

形式语言： $\exists A\big(\forall x(x\not\in A)\big)$

即存在一个集合 $A$ 他不包含任何[[MK45][元素]]（空集），记作 $\varnothing$

***** 证明

显然 $\lnot(z=z)$ 是[[MK1][集合论语言]]的合法[[~/文档/note/数理逻辑/sllj.org::MK129][表达式]]，则根据[[MK3][第一存在]]可得有集合 $x$

故根据[[MK5][分离模式]]可得 $y=\left\{z\in x\big|\lnot(z=z)\right\}$ 亦为一个集合

根据[[MK1][集合论语言]]可得 $=$ 符号满足[[MK132][等价关系]]，即有 $\forall z(z=z)$ 故不存在任意元素满足 $\lnot(z=z)$

综上所述，不存在 $x\in y$ 即 $y=\varnothing$

***** 唯一性<<MK7>>

有且仅有一个不包含任意元素的集合 $\varnothing$

****** 证明

根据定义可得 $\forall x(x\not\in\varnothing)$ ，若存在 $y$ 亦满足 $\forall x(x\not\in y)$

则对于[[~/文档/note/数理逻辑/sllj.org::MK129][表达式]] $\forall x((x\in\varnothing)\leftrightarrow (x\in y))$ 来说对于任意 $x$ 均有 $x\in\varnothing$ 与 $x\in y$ 均不成立

则有 $\forall x((x\in\varnothing)\leftrightarrow (x\in y))$ 成立，则根据[[MK2][外延公理]]有 $y=\varnothing$ 

***** 包含

$\forall x(\varnothing\subset x)$ 即空集是任意集合的子集

****** 证明

根据[[MK15][子集]]定义，对于集合 $x$ 均有 $\forall z(z\in\varnothing\rightarrow x\in x)$

由于 $z\in\varnothing$ 恒不成立，故可得 $z\in\varnothing\rightarrow x\in x$ 恒成立，故有 $\forall x(\forall z(z\in\varnothing\rightarrow x\in x))$

即 $\forall x(\varnothing\subset x)$ 

*** 配对公理<<MK8>>

形式语言： $\forall B(\forall C(\exists A(\forall x((x\in A)\leftrightarrow((x=B)\lor (x=C))))))$

即给定集合 $B,C$ ，存在集合 $A=\{B,C\}$

**** 推论

$\forall y\exists x(y\in x)$

***** 证明

根据[[MK8][配对公理]]可得当 $B=C$ 时有 $\forall C(\exists A(\forall x((x\in A)\leftrightarrow((x=C)\lor (x=C)))))$

故可得对于任意 $C$ 均存在 $A$ 满足 $C\in A$

*** 并集公理<<MK9>>

形式语言： $\forall A(\exists B(\forall x((x\in B)\leftrightarrow(\exists u((u\in A)\land(x\in u))))))$

即对于任意集合 $A$ 存在 $A$ [[MK45][元素]]的[[MK45][元素]]的集合 $B$

*** 无穷公理<<MK10>>

形式语言： $\exists A\big(\varnothing\in A\land (x\in A\rightarrow x\cup\{x\}\in A)\big)$

即存在一个集合 $A$ 包含[[MK6][空集]]，且任意元素 $x$ 若 $x\in A$ 则其后继 $x\cup\{x\}=\{x,\{x\}\}$ 也属于 $A$

定义所有满足 $((\varnothing\in A)\land ((x\in A)\rightarrow (x\cup\{x\}\in A)))$ 的集合为 $Inf$

*** 替换公理模式

形式语言： $\forall X\exists Y\big(f(x)\in Y\leftrightarrow x\in X\big)$

即对于任意[[MK175][函数]] $f(x)$ 和任意集合 $X$ ，若对于任意 $x\in X$ 来说 $f(x)$ 有定义

则存在集合 $Y$ 使得 $f(x)\in Y$ 是 $x\in X$ 的充要条件

*** 正则公理

形式语言： $\forall A\big((\exists z(z\in A))\rightarrow \left(\exists x((x\in A)\land(\lnot\exists y(y\in x\land y\in A)))\right)\big)$

即对于任意非空集合 $A$ ，存在元素 $x\in A$ 使得 $x\cap A=\varnothing$ 

注：由于所有[[MK45][元素]]亦为集合，故可由并集操作

**** 引理1<<MK11>>

$\forall A(\lnot(\exists B(B\in A\land B=A)))$ 即集合不包含自身

***** 证明

假设 $A\in A$ 即集合 $A$ 中有一个元素是其自身。

则根据[[MK8][配对公理]]设 $x=A,y=A$ 则存在 $B=\{A\}$ 

此时 $B$ 非空且仅含有一个元素，则 $A\cap B=A\cap \{A\}$

由于 $A\in A,A\in\{A\}$ 故有 $A\cap B=A$ 与正则公理矛盾，故 $A\not\in A$

**** 引理2<<MK12>>

无限递降序列 $\\...\in A_n\in...\in A_2\in A_1$ 不存在

***** 证明

根据[[MK8][无序对公理]]可得存在集合 $S'= \{\{A_1\},...\{A_n\},...\}$ 根据[[MK9][并集公理]]可得 $S=\{A_1,...A_n,...\}$ 存在

则根据正则公理，存在一个元素 $A_k\in S$ 使得 $A_k\cup S=\varnothing$

又根据无限序列，有 $A_{k+1}\in A_k$ 同时有 $A_{k+1}\in S$ 则有 $A_k\cap S$ 至少包含 $A_{k+1}$ 与正则公理矛盾。

**** 三岐性<<MK13>>

对于任意 $x=y$ 均有 $x\not\in y$ 且 $y\not\in x$

对于任意 $x\in y$ 均有 $x\ne y$ 且 $y\not\in x$

***** 证明

若有 $x=y$ 则根据[[MK11][引理1]]可得 $x\not\in y$ 且 $y\not\in x$

若有 $x\in y$ 则根据[[MK11][引理1]]可得 $x\ne y$ ，假设 $y\in x$ 则根据[[MK8][无序对公理]]可得存在集合 $S=\{x,y\}$

则 $S\ne\varnothing$ 且对于任意 $a\in S$ 均有 $b\in S-\{a\}$ 满足 $b\in a$ 与正则公理矛盾

*** 选择公理<<MK14>>

对于任意不包含空集的[[MK47][集合族]] $A=\left\{S_i\big|i\in I\right\}$ 存在选择[[MK175][函数]] $f:A\to\bigcup_{i\in I}S_i$ 满足 $f(S_i)\in S_i$

形式语言： $\forall A\left(S_i\ne\varnothing\land S_i\in A\rightarrow\exists (f:A\to\bigcup S_i)\rightarrow\left(f(S_i)\in S_i\right)\right)$

**** 推论

对于任意集合 $A$ 中的每个[[MK45][元素]]选择一个[[MK45][元素]]的[[MK45][元素]]，可组成一个新的集合 $B$

根据选择公理，存在选择函数。则对于任意 $S\in A$ 存在 $\{f(S)\}$ 使得 $f(S)\in S$

根据[[MK8][无序对公理]]及[[MK9][并集公理]]可得 $B=\left\{f(S)\big|S\in A\right\}$ 存在

** 罗素定理

形式语言： $(\lnot(\exists x(\forall y((y\in x)\rightarrow y\not\in y))))$

*** 证明

假设罗素定理不成立，则存在 $x$ 满足条件，定义为 $x^*$ 则有 $\forall y(y\in x^*\leftrightarrow y\not\in y)$

则若 $y=x^*$ 可得 $x^*\in x^*\leftrightarrow x^*\not\in x^*$ 显然矛盾。假设不成立，罗素定理为真

** 集合的关系

*** 包含（子集）<<MK15>>

若集合 $A$ 的每一个[[MK45][元素]]都是集合 $B$ 的元素，则称 $A$ 为 $B$ 的子集，记作 $A\subset B$ 。

即 $\forall x(x\in A\rightarrow x\in B)\rightarrow A\subset B$

**** 真子集

若 $A\subset B\land A\ne B$ 则称 $A$ 为 $B$ 的真子集

**** 定理1（自反性）<<MK16>>

对于任意集合 $A,B$ 当且仅当 $A\subset B$ 且 $B\subset A$ 时 $A=B$

***** 证明

当 $A=B$ 时，根据[[~/文档/note/数理逻辑/sllj.org::MK9][外延公理]]，[[~/文档/note/数理逻辑/sllj.org::MK49][等价等值式]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]有：

\begin{aligned}
&\forall x(x\in A\leftrightarrow x\in B)\\
{|\!\!\!=\!\!\!|}&\forall x((x\in A\rightarrow x\in B)\land(x\in B\rightarrow x\in A))\\
{|\!\!\!=\!\!\!|}&\forall x(x\in A\rightarrow x\in B)\land\forall x(x\in B\rightarrow x\in A)\\
{|\!\!\!=\!\!\!|}&(A\subset B)\land(B\subset A)\\
\end{aligned}

故得 $A=B{|\!\!\!=\!\!\!|}&(A\subset B)\land(B\subset A)$

**** 定理2（传递性）<<MK17>>

若 $A\subset B\land B\subset C$ 则有 $A\subset C$

***** 证明

根据[[~/文档/note/数理逻辑/sllj.org::MK37][蕴含传递]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]有：

\begin{aligned}
&A\subset B\land B\subset A\\
{|\!\!\!=\!\!\!|}&\forall x(x\in A\rightarrow x\in B) \land \forall x(x\in B\rightarrow x\in C)\\
{|\!\!\!=\!\!\!|}&\forall x((x\in A\rightarrow x\in B)\land(x\in B\rightarrow x\in C))\\
{|\!\!\!=}&\forall x(x\in A\rightarrow x\in C)\\
\end{aligned}

**** 定理3

对于任意集合 $A$ ，都存在 $A\in U$ 其中 $U$ 为[[~/文档/note/数理逻辑/sllj.org::MK118][全总域]]

***** 证明

由于 $x\in U$ 为永真，故有 $x\in A\rightarrow x\in U$ 永真，故 $\forall x(x\in A\rightarrow x\in U)\rightarrow A\subset U$

**** 定理4<<MK18>>

空集是任意集合的子集

***** 证明

对于任意元素 $x$ 表达式 $x\in\varnothing$ 永假式，故 $x\in\varnothing\rightarrow x\in A$ 永真，故 $\forall x(x\in\varnothing\rightarrow x\in A)\rightarrow \varnothing\subset A$

**** 定理5

空集是唯一的

***** 证明

假设存在两个空集 $\varnothing_1,\varnothing_2$ 根据[[MK18][定理4]]可得 $\varnothing_1\subset\varnothing_2,\varnothing_2\subset\varnothing_1$ 又根据[[MK16][定理1]]可得 $\varnothing_1=\varnothing_2$

**** 定理6<<MK19>>

若集合 $A$ 的[[MK35][基数]]为 $|A|=n$ ，则 $A$ 的子集数量为 $2^n$

***** 证明

集合 $A$ 中有 $n$ 个元素，定义子集为 $a$ ，每个元素 $x_i\in A,1\leq i\leq n$ 要么属于 $a$ 要么不属于 $a$

故一共 $n$ 个元素，组合得 $a$ 有 $2^n$ 中可能性。

*** 幂集<<MK20>>

若集合 $A$ ，则其幂集定义为 $\rho(A)=\left\{x\big|x\subset A\right\}$ ，根据[[MK4][幂集公理]]可得 $\rho(A)$ 存在

**** 性质1

[[MK82][有限集]]时 $|A|=n$ 时 $|\rho(A)|=2^n$

***** 证明

根据[[MK19][定理6]]可得

**** 性质2

若 $A,B$ 为集合，则 $A\subset B$ 的充要条件为 $\rho(A)\subset\rho(B)$ ，即 $(A\subset B)\leftrightarrow(\rho(A)\subset \rho(B))$ 

***** 证明

当 $A\subset B$ 时，根据[[MK20][定义]]对于任意 $x$ 有 $x\in \rho(A)\leftrightarrow x\subset A$ 又有 $A\subset B$ 根据[[MK17][传递性]]可得 $x\subset A\land A\subset B\rightarrow x\subset B$ 

根据[[MK20][定义]] $x\subset B\leftrightarrow x\in \rho(B)$ 最终得 $x\in \rho(A)\rightarrow x\in \rho(B)$ ，根据[[MK15][定义]]可得 $A\subset B\rightarrow \rho(A)\subset \rho(B)$

当 $\rho(A)\subset \rho(B)$ 根据[[MK20][定义]] $A\in \rho(A)$ 且根据[[MK15][子集定义]] $A\in \rho(B)$ 同理根据[[MK20][定义]] $A\in \rho(B)\rightarrow A\subset B$

即 $\rho(A)\subset \rho(B)\rightarrow A\subset B$

综上所述 $((A\subset B)\rightarrow (\rho(A)\subset \rho(B)))\land((\rho(A)\subset \rho(B))\rightarrow(A\subset B)){|\!\!\!=\!\!\!|}(A\subset B)\leftrightarrow(\rho(A)\subset \rho(B))$

**** 性质3

若 $x$ 是一个集合，则之多有一个 $y$ 满足 $\forall z((z\in y)\leftrightarrow(z\subset x))$

***** 证明

假设存在 $y_1,y_2$ 同时满足 $\forall z((z\in y_1)\leftrightarrow(z\subset x))$ 以及 $\forall z((z\in y_2)\leftrightarrow(z\subset x))$

则可得 $\forall z((z\in y_1)\leftrightarrow(z\subset x)\leftrightarrow (z\in y_2))$ 则根据[[MK2][外延公理]]可得 $y_1=y_2$

**** 康托定理

定义 $M$ 是任意一个集合，则有 $|M|<|\rho(M)|$ 即其[[MK20][幂集]]的[[MK35][基数]]严格大于其本身的基数

***** 证明

反正法，若假设成立，则有 $|M|\geq|\rho(M)|$ 显然 $\forall a\in M\rightarrow \{a\}\in\rho(M)$ 存在[[MK181][双射函数]]

且 $\bigcup_{a\in M}\{\{a\}\}\subset\rho(M)$ 为幂集的子集，故 $M$ 与 $\rho(M)$ 子集[[MK29][对等]]， 故 $|M|\not>|\rho(M)|$

则仅有可能 $|M|=|\rho(M)|$ ，根据[[MK29][对等]]存在[[MK181][双射函数]] $\sigma:M\to\rho(M)$ 根据[[MK188][定义]]存在 $\sigma^{-1}:\rho(M)\to M$ 亦为双射

定义集合 $A=\left\{x\big|x\in M\land x\not\in\sigma(x)\right\}$ 显然 $A\subset M$ 故存在 $\sigma^{-1}(A)$ 根据[[MK189][性质1]]可得 $\sigma(\sigma^{-1}(A))=A$

则若 $y=\sigma^{-1}(A)\in A$ 则根据 $A$ 的定义满足 $y\not\in\sigma(y)$ 其中 $\sigma(y)=\sigma(\sigma^{-1}(A))=A$ 

故推出 $y\not\in A$ 矛盾

若 $y=\sigma^{-1}(A)\not\in A$ 则根据 $A$ 的定义满足 $y\in\sigma(y)$ 同理 $\sigma(y)=\sigma(\sigma^{-1}(A))=A$ 

故推出 $y\in A$ 亦矛盾

故假设不成立

** 特殊集合

*** 传递集合<<MK21>>

若[[MK44][集合]] $X$ 满足 $\forall a(a\in X\rightarrow a\subset X)$ 则称 $X$ 是一个传递集合

**** 引理1<<MK22>>

[[MK21][传递集]]的[[MK60][交]]亦为传递集合

***** 证明

设 $X,Y$ 均为[[MK21][传递集]]，定义 $\gamma=X\cap Y$ 则对于任意 $a\in\gamma$ 可得 $a\in X\land a\in Y$

则有 $a\subset X\land a\subset Y$ 即有 $a\subset X\cap Y$ 综上所述 $\forall a((a\in\gamma)\to(a\subset\gamma))$

即 $\gamma=X\cap Y$ 是[[MK21][传递集合]]

**** 引理2<<MK23>>

$X$ 是[[MK21][传递集]]的等价条件是 $\forall x(\forall y((x\in y\land y\in X)\to(x\in X)))$

***** 证明

****** 充分

若是 $X$ 是[[MK21][传递集]]则有 $\forall y(y\in X\rightarrow y\subset X)$ 则对于任意 $x\in y$ 由于 $y\subset X$ 则根据[[MK15][子集]]有 $x\in X$

****** 必要

若 $\forall x(\forall y((x\in y\land y\in X)\to(x\in X)))$ 则对于任意 $y\in X$ 有任意 $x\in y$ 均有 $x\in X$

同理根据[[MK15][子集]]有 $y\subset X$

*** 序数<<MK24>>

集合 $X$ 满足：

（1） $\forall a(a\in X\rightarrow a\subset X)$ 即是[[MK21][传递集]]

（2） 对于任意 $x\in X,y\in X$ 可得 $x\in y,y\in x,x=y$ 有且仅有一个成立

（3） 对于任意 $y\subset X$ 若 $y\ne\varnothing$ 可得存在 $z\in y$ 满足 $z\cap y=\varnothing$

则称 $X$ 为序数。

注：空集 $\varnothing$ 是任意集合的[[MK15][子集]] $\varnothing\subset X$ ，而不是任意集合的元素，故 $\varnothing\not\in X$ 可满足

**** 后继序数<<MK25>>

[[MK24][序数]] $X$ 被称为[[MK24][序数]] $Y$ 的后继序数当且仅当 $X=Y\cup\{Y\}$ ，记作 $X=Y+1$

**** 极限序数

如果[[MK24][序数]] $X$ 不是[[MK25][后继序数]]，则 $X$ 是极限序数

**** 引理1<<MK26>>

若 $\alpha$ 是一个[[MK24][序数]]，有 $A\subset\alpha$ 且 $A$ 亦为[[MK24][序数]]，则有 $A\in\alpha$ 或这 $A=\alpha$

***** 证明

****** $\alpha-A=\varnothing$

则显然 $A=\alpha$

****** $\alpha-A\ne\varnothing$

则有 $\alpha-A\subset\alpha$ 根据[[MK24][定义（3）]]可得存在 $\beta\in\alpha-A$ 满足 $\beta\cap(\alpha-A)=\varnothing$

根据下列证明以及[[MK16][自反性]]有 $A=\beta$ 由于 $\beta\in\alpha$ 故有 $A\in\alpha$

******* 证明 $\beta\subset A$

由于 $\beta\in\alpha$ 根据[[MK24][定义（1）]]有 $\beta\subset\alpha$ 又由于 $\beta\cap(\alpha-A)=\varnothing$ 故有 $\beta\subset A$

******* 证明 $A\subset\beta$

假设 $A\not\subset\beta$ 则根据上一步证明有 $A-\beta\ne\varnothing$

由于 $A$ 亦为[[MK24][序数]]且 $A-\beta\subset A$ 故根据[[MK24][定义（3）]]可得存在 $\gamma\in A-\beta$ 满足 $\gamma\cap(A-\beta)=\varnothing$

由于 $A\subset\alpha$ 且 $\gamma\in A$ 则有 $\gamma\in\alpha$ ，由于 $\beta\in\alpha$ 故根据[[MK24][定义（2）]]可得 $\beta=\gamma,\beta\in\gamma,\gamma\in\beta$ 有且仅有一个成立

显然根据 $\gamma\in A-\beta$ 可得 $\gamma\not\in\beta$

假设 $\beta\in\gamma$ ，根据 $\gamma\in A-\beta$ 可得 $\gamma\in A$ 又由于 $A$ 为[[MK24][序数]]，根据[[MK24][定义（1）]]有 $\gamma\subset A$

即有 $\beta\in A$ 与 $\beta\in\alpha-A$ 矛盾，故假设不成立，可得 $\beta\not\in\gamma$

假设 $\gamma=\beta$ ，则根据 $\gamma\in A-\beta$ 有 $\beta\in A-\beta$ ，即 $\beta\in A$ 与 $\beta\in\alpha-A$ 矛盾

假设不成立，即有 $\beta\ne\gamma$

综上所述，假设与[[MK24][定义（2）]]中 $\beta=\gamma,\beta\in\gamma,\gamma\in\beta$ 矛盾，假设不成立，故有 $A\not\subset\beta$ 

**** 引理2<<MK27>>

若 $\alpha,\beta$ 是一个[[MK24][序数]]，则 $\alpha\cap\beta$ 亦为[[MK24][序数]]

***** 证明

根据[[MK22][引理1]]可得 $\alpha\cap\beta$ 亦为[[MK21][传递集]]

对于任意 $x\in\alpha\cap\beta,y\in\alpha\cap\beta$ 根据[[MK24][定义（2）]]以及[[MK13][三岐性]]可得 $x\in y,y\in x,x=y$ 有一成立

对于任意 $y\subset\alpha\cap\beta$ 有 $y\subset\alpha$ 则根据[[MK24][定义（3）]]存在 $\gamma\in y$ 满足 $\gamma\cap y=\varnothing$

综上所述 $\alpha\cap\beta$ 是[[MK24][序数]]

**** 引理3

$X$ 是[[MK24][序数]]，则有 $\varnothing\in X$

***** 证明

假设 $\varnothing\not\in X$ 根据下列证明以及数学归纳法可得存在无限递降序列 $\\...\in a_n\in...\in a_1\in a_0$ 与[[MK12][引理2]]矛盾

故假设不成立，即有 $\varnothing\in X$

****** 任意取 $a_0\in X$

对于任意 $a_0\in X$ 根据假设有 $a_0\ne\varnothing$ ，则根据[[MK24][定义（1）]]有 $a_0\subset X$ 结合 $\varnothing\not\in X$ 则有 $\varnothing\not\in a_0$

****** 归纳假设

任意 $i<n$ 均有 $a_i\in X$ 且 $a_i\ne\varnothing$

****** 存在 $a_n\in a_{n-1}$

由于 $a_{n-1}\in X$ 故有 $a_{n-1}\subset X$ 由于 $\varnothing\not\in X$ 故可得 $\varnothing\ne a_{n-1}$

根据[[MK24][定义（3）]]可得存在 $a_n\in a_{n-1}$ 又由于 $a_n\in a_{n-1}$ 以及 $a_{n-1}\subset X$ 可得 $a_n\in X$ 故 $a_n\ne\varnothing$

进而根据[[MK24][定义（1）]]可得 $a_n\subset X$ ，又由于 $\varnothing\not\in X$ 故可得 $\varnothing\not\in a_n$

**** 可比较性定理<<MK28>>

任意两个[[MK24][序数]] $\alpha,\beta$ 有 $\alpha\in\beta,\beta\in\alpha,\beta=\alpha$ 三者有且仅有一个成立

***** 证明

定义 $\gamma=\alpha\cap\beta$ 则根据[[MK27][引理2]]有 $\gamma$ 亦为[[MK24][序数]]，显然有 $\gamma\subset\alpha,\gamma\subset\beta$

根据[[MK26][引理1]]有 $\gamma\in\alpha,\gamma=\alpha$ 有且仅有一个成立， $\gamma\in\beta,\gamma=\beta$ 有且仅有一个成立

若 $\gamma\in\alpha$ 且 $\gamma\in\beta$ 则有 $\gamma\in\alpha\cap\beta=\gamma$ 与[[MK11][引理1]]矛盾

若 $\gamma=\alpha$ 且 $\gamma=\beta$ 则有 $\alpha=\beta$

若 $\gamma\in\alpha$ 且 $\gamma=\beta$ 则有 $\beta\in\alpha$

若 $\gamma=\alpha$ 且 $\gamma\in\beta$ 则有 $\alpha\in\beta$

综上所述，若 $\alpha,\beta$ 均为[[MK24][序数]]，则必有 $\alpha\in\beta,\beta\in\alpha,\beta=\alpha$ 三者有且仅有一个成立

*** 等势（对等）<<MK29>>

若集合 $A,B$ ：

（1） 存在[[MK181][双射函数]] $\sigma:A\to B$ 则称 $A,B$ 集合对等，记作 $|A|=|B|$

（2） 存在[[MK176][单射函数]] $\sigma:A\to B$ 则称 $A$ 的势小于等于 $B$ ，记作 $|A|\leq|B|$

（3） 记 $|A|<|B|$ 等价条件是 $|A|\leq|B|$ 且 $|A|\ne|B|$
 
规定空集与空集对等 $|\varnothing|=|\varnothing|$

**** 定理1<<MK30>>

集合等势是[[MK132][等价关系]]

***** 证明

根据等价关系定义证明自反性，对称性以及传递性

若 $\sigma:A\to A$ 为其中每一个元素于自身的映射，则显然满足映射中的双射关系，故 $|A|=|A|$

若 $|A|=|B|$ 则存在双射函数 $\sigma:A\to B$ 则根据[[MK188][函数求逆]]可得存在你函数 $\sigma^{-1}:B\to A$

根据[[MK190][性质2]]可得你函数亦为双射，故有 $|B|=|A|$

若有 $|A|=|B|\land |B|=|C|$ 则存在 $\sigma_1:A\to B,\sigma_2:B\to C$ 两个双射函数

根据[[MK182][传递性]]可得存在双射函数 $\sigma:A\to C$

故满足自反性，对称性以及传递性，即为等价关系

**** 定理2<<MK31>>

若有 $\forall i\in\mathbb{N}\rightarrow |A_i|=|B_i|$ 且 $\{A_n\}$ 中任意两个集合互不相交， $\{B_n\}$ 中任意两个集合互不相交

则有 $\left|\bigcup_{i=1}^\infty A_i\right|=\left|\bigcup_{i=1}^\infty B_i\right|$

***** 证明

根据[[MK29][定义]]可得有[[MK181][双射]] $\phi_i:A_i\to B_i$ 则定义[[MK175][映射]] $\phi=\bigcup_{i=1}^\infty\phi_i$

根据[[MK183][并双射]]可得 $\phi$ 亦是[[MK181][双射]]，即 $\left|\bigcup_{i=1}^\infty A_i\right|=\left|\bigcup_{i=1}^\infty B_i\right|$

**** 定理3<<MK32>>

若 $|A|=|B|$ 即存在 $\phi:A\to B$ 是[[MK181][双射函数]]，则对于 $C\subset A$

（1） $|C|=|\phi(C)|$ 且双射函数 $\phi'=\left\{<x,y>\big|<x,y>\in\phi\land x\in C\right\}$

（2） $|A-C|=|B-\phi(C)|$ 且双射函数 $\phi'=\left\{<x,y>\big|<x,y>\in\phi\land x\in A-C\right\}$

***** 证明

对于（1）根据[[MK185][子双射]]可得 $\phi'$ 以为双射函数，即可得 $|C|=|\phi(C)|$

对于任意 $x\not\in C$ 可得 $\phi(x)$ 假设 $\phi(x)\in\phi(C)$ ，则存在 $x'\in C$ 使得 $\phi(x')=\phi(x)$

即 $\phi$ 不是[[MK176][单射]]，与条件矛盾，故假设不成立，即 $x\not\in C\rightarrow \phi(x)\not\in\phi(C)$

同理易证 $\phi(x)\not\in\phi(C)\rightarrow x\not\in C$

定义 $D=A-C$ 则对于任意 $x\in D$ 显然 $\phi(x)\in B$ 又由于 $x\not\in C$ 且双射，故有 $\phi(x)\not\in\phi(C)$

即有 $\phi(D)\subset B-\phi(C)$ 同理对于任意 $y\in B-\phi(C)$ 可得 $\phi^{-1}(y)\in A$

又由于 $y\not\in\phi(C)$ 则有 $\phi^{-1}(y)\not\in C$ 即 $\phi^{-1}(B-\phi(C))=A-C$

则有 $\phi(D)=\phi(A-C)=\phi\left(\phi^{-1}(B-\phi(C))\right)=B-\phi(C)$

则运用（1）有 $|A-C|=|D|=|\phi(D)|=|B-\phi(C)|$ 证毕

**** 定理4<<MK328>>

若 $|A|\leq|B|$ 则有 $|B|\not<|A|$

***** 证明

假设 $|B|<|A|$ 则根据[[MK29][定义]]有 $|B|\leq|A|$ 且 $|B|\ne|A|$

又根据 $|A|\leq|B|$ 以及[[MK34][伯恩斯坦定理]]有 $|A|=|B|$ 与 $|A|\ne|B|$ 矛盾

故假设不成立，即有 $|B|\not<|A|$

**** 定理5<<MK33>>

若 $A\subset B$ 则有 $|A|\leq|B|$

***** 证明

由于 $A\subset B$ 则定义映射 $\phi(a)=a,a\in A$ 显然是[[MK181][双射函数]]

又由于 $\forall a((a\in A)\to(a\in B))$ 故有 $\phi$ 是 $A$ 到 $B$ 的[[MK176][单射]]函数

可得[[MK29][等势（2）]]必然成立，故满足[[MK29][等势（1）]]和可得[[MK29][等势（2）]]至少有一个成立

即有 $|A|\leq|B|$

**** 定理6<<MK327>>

若 $|A|\leq|B|$ 则：

（1） 对于任意 $|C|=|A|$ 均有 $|C|\leq|B|$

（2） 对于任意 $|C|=|B|$ 均有 $|A|\leq|C|$

***** 证明

仅证（1），（2）同理可证

根据[[MK29][定义]]有[[MK181][双射函数]] $\sigma:C\to A$ 以及[[MK176][单射函数]] $\eta:A\to B$

则显然 $g(c)=\eta(\sigma(c)),c\in C$ 是 $C\to B$ 的[[MK176][单射函数]]，故有 $|C|\leq|B|$

**** 伯恩斯坦定理<<MK34>>

若集合 $A,B$ 满足 $|A|\geq|B|\land|A|\leq|B|$ 则有 $|A|=|B|$

***** 证明

****** 定义集合

根据定义，存在 $A_0\subset A$ 使得 $|B|=|A_0|$ 即有[[MK181][双射]] $\psi:B\to A_0$

则定义 $A_1=A-A_0$ 又根据定义存在双射 $\phi:A_1\to B_1$

同理亦有 $\psi(B_1)=A_2$ 由于 $\psi:B\to A_0$ 固有 $A_2\subset A_0$ ，则 $A_1\cap A_2=\varnothing$

同理亦有 $\phi(A_2)=B_3,\psi(B_3)=A_3...\a$

****** 证明互不相交

若 $\phi(A_{n+1})=B_{n+1}$ 于任意一个 $B_i,1\leq i\leq n$ 相交，定义其中一个交点为 $\omega$

则存在 $\delta_1\in A_{n+1},\delta_2\in A_i$ 满足 $\phi(\delta_1)=\phi(\delta_2)=\omega$ 与 $\phi$ 是双射矛盾。

同理对于 $\psi(B_{n+1})=A_{n+2}$ 亦可证 $A_{n+2}$ 不与任何 $A_i,1\leq i\leq n+1$ 相交

则通过数学归纳法可得 $\forall \{i,j\}\subset\mathbb{N}\rightarrow A_i\cap A_j=\varnothing\land B_i\cap B_j=\varnothing$

****** 证明结论

由于 $\forall i\in\mathbb{N}\rightarrow\psi(B_i)=A_{i+1}$ 且 $\psi$ 是双射函数，根据[[MK32][定理3]]有 $|B_i|=|A_{i+1}|$ ，

由于 $A_i$ 互补相交且 $B_i$ 互不相交，则根据[[MK31][定理2]]有 $|\bigcup_{i=1}^\infty B_i|=|\bigcup_{i=2}^\infty A_i|$

易证 $\psi\left(\bigcup_{i=1}^\infty B_i\right)=\bigcup_{i=2}^\infty A_i$ ，又由于 $\psi(B)=A_0$

故根据[[MK32][定理3]] $\left|B-\bigcup_{i=1}^\infty B_i\right|=\left|A_0-\bigcup_{i=2}^\infty A_i\right|$

根据 $A_1$ 的定义有 $A=A_0\cup A_1$ 则易证 $A_0-\bigcup_{i=2}^\infty A_i=A-\bigcup_{i=1}^\infty A_i$

故有 $\left|B-\bigcup_{i=1}^\infty B_i\right|\sim\left|A-\bigcup_{i=1}^\infty A_i\right|$

又由于 $\phi$ 为双射，根据[[MK32][定理3]]可得 $|A_i|=|B_i|$ ，故根据[[MK31][定理2]]有 $|\bigcup_{i=1}^\infty B_i|=|\bigcup_{i=1}^\infty A_i|$

最终根据[[MK31][定理2]]有 $\left|\left(B-\bigcup_{i=1}^\infty B_i\right)\cup\left(\bigcup_{i=1}^\infty B_i\right)\right|=\left|\left(A-\bigcup_{i=1}^\infty A_i\right)\cup\left(\bigcup_{i=1}^\infty A_i\right)\right|$

显然 $A=\left(A-\bigcup_{i=1}^\infty A_i\right)\cup\left(\bigcup_{i=1}^\infty A_i\right)\land B=\left(B-\bigcup_{i=1}^\infty B_i\right)\cup\left(\bigcup_{i=1}^\infty B_i\right)$

最终证得 $|A|=|B|$

*** 基数<<MK35>>

集合 $\kappa$ 基数的充要条件为：

（1） $\kappa$ 是[[MK24][序数]]，且

（2） 任意[[MK24][序数]] $Y$ 若有 $|Y|=|\kappa|$ 即[[MK29][等势]]，则有 $\kappa\in Y$ 注：根据[[MK28][可比较定理]]任意两个[[MK24][序数可比较]]

则称 $\kappa$ 是基数

*** 滤子<<MK36>>

设集合 $X$ 非空，则 $F$ 是 $X$ 的滤子当且仅当 $F$ 满足：

（1） $F\subset\rho(X)$ 即是 $X$ [[MK20][幂集]]的子集

（2） $X\in F\land\varnothing\not\in F$

（3） 对于任意 $A\in F\land B\in F$ 则有 $A\cap B\in F$

（4） 对于任意 $A\in F\land A\subset B\subset X$ 则有 $B\in F$

显然，在已知 $X$ 表达式的情况下 $X$ 的滤子可用[[~/文档/note/数理逻辑/sllj.org::MK129][一阶表达式]]描述

**** 定理1

若 $X$ 是[[MK83][无限集]]，若存在 $E\subset\rho(X)$ 满足任意 $E$ 中[[MK82][有限]]个元素相[[MK60][交]]非空

则存在 $X$ 上的[[MK36][滤子]] $F$ 满足 $E\subset F$

***** 证明

对于任意 $n\in\mathbb{N}$ 且 $n<|E|$

定义 $\phi_n(A)=(A\subset X)\land(\exists B_1(...\exists B_n((B_1\in E)\land...\land(B_n\in E)\land((B_1\cap...\cap B_n)\subset A))...))$

由于 $n<\infty$ 故可得 $|\phi_n(A)|<\infty$ 故已知 $A$ 的情况下 $\phi(A)$ 是[[~/文档/note/数理逻辑/sllj.org::MK129][表达式]]

定义 $F_n=\left\{A\big|\phi_n(A)\right\}$ ，进一步定义 $F=\bigcup_{n\in\mathbb{N}}F_n$ 显然 $F\subset\rho(X)$

由于 $E\subset\rho(X)$ 故对于任意 $B_1\in E$ 又 $B_1\subset X$ 故可得 $X\in F_1$

对于任意 $f\in F$ 存在 $n$ 满足 $f\in F_n$ ，进而存在 $\{B_1,...,B_n\}\subset E$ 满足 $B_1\cap...\cap B_n\subset f$

由于 $E$ 中任意[[MK82][有限]]个元素相[[MK60][交]]非空，故 $B_1\cap...\cap B_n$ 非空，故有 $f$ 非空，故可得 $\varnothing\not\in F$

对于任意 $f_1\in F,f_2\in F$ 同理存在 $\{B_1,...,B_n\}\subset E,\{B'_1,...,B'_m\}\subset E$

满足 $B_1\cap...\cap B_n\subset f_1,B'_1\cap...\cap B'_m\subset f_2$ 则必有 $B_1\cap...\cap B_n\cap B'_1\cap...\cap B'_m\subset f_1\cap f_2$

则必有 $f_1\cap f_2\in F_{n+m}$ 故有 $f_1\cap f_2\in F$

对于任意 $f_1\in F,f_1\subset f_2\subset X$ 同理存在 $\{B_1,...,B_n\}\subset E$ 满足 $B_1\cap...\cap B_n\subset f$

则有 $B_1\cap...\cap B_n\subset f_1\subset f_2$ 故有 $f_2\in F_n$

综上所述，可得 $F$ 是[[MK36][滤子]]

**** 定理2<<MK37>>

设 $X$ 是一个非空集合，又有 $A=\left\{\left<x, A_x\right>\big|x\in X\right\}$ 满足 $A_x\ne\varnothing$ 是定义在 $X$ 上的[[MK175][函数]]

定义 $\prod_{x\in X}A_x$ 其中乘法为[[MK107][笛卡尔积]]，其结果为函数表示

即 $\prod_{x\in X}A_x=\left\{f\big|f:X\to\bigcup_{x\in X}A_x\land f(x)\in A_x\right\}$ 为所有 $f:X\to \bigcup_{x\in X}A_x$ 的[[MK14][选择函数]]的集合

若 $F$ 是 $X$ 上的[[MK36][滤子]]，定义关系 $\simeq$ 为 $\left\{\left<f,g\right>\big|\{f,g\}\subset\prod_{x\in X}A_x\land\left\{x\big|x\in X\land f(x)=g(x)\right\}\in F\right\}$

则 $\simeq$ 是[[MK132][等价关系]]

***** 证明

****** [[MK124][自反性]]

对于任意 $f\in\prod_{x\in X}A_x$ 均有对于任意 $x\in X$ 有 $f(x)=f(x)$ 故 $\left\{x\big|x\in X\land f(x)=f(x)\right\}=X$

根据[[MK36][滤子（2）]]可得 $\left\{x\big|x\in X\land f(x)=f(x)\right\}=X\in F$ 故有 $f\simeq f$

****** [[MK126][对称性]]

对于任意 $\{f,g\}\subset\prod_{x\in X}A_x$ 若有 $f\simeq g$ 则 $\left\{x\big|x\in X\land f(x)=g(x)\right\}\in F$

显然 $\left\{x\big|x\in X\land f(x)=g(x)\right\}=\left\{x\big|x\in X\land g(x)=f(x)\right\}\in F$ 故有 $g\simeq f$

****** [[MK128][传递性]]

对于任意 $\{f,g,h\}\subset\prod_{x\in X}A_x$ 若有 $f\simeq g,g\simeq h$ 则有 $X_1=\left\{x\big|x\in X\land f(x)=g(x)\right\}\in F$

以及 $X_2=\left\{x\big|x\in X\land g(x)=h(x)\right\}\in F$ 则对于任意 $x\in X_1\cap X_2$ 必有 $f(x)=g(x)=h(x)$

即有 $f(x)=h(x)$ 故有 $X_1\cap X_2\subset\left\{x\big|x\in X\land f(x)=h(x)\right\}$

根据[[MK36][滤子（3）（4）]]有 $\left\{x\big|x\in X\land f(x)=h(x)\right\}\in F$ 故有 $f\simeq h$

**** 定理3（弗雷歇滤子）<<MK38>>

设 $X$ 是[[MK83][无限集]]，定义 $F=\left\{x\big|x\subset X\land |X-x|<\infty\right\}$ 则 $F$ 是 $X$ 的[[MK36][滤子]]，称为弗雷歇滤子

***** 证明

由于 $X$ 是[[MK83][无限集]]，则 $|X-\varnothing|=\infty$ 故 $\varnothing\not\in F$ ，同理 $|X-X|=|\varnothing|=0$ 故 $X\in F$

若 $A\in F,B\in F$ 则 $|X-A|<\infty,|X-B|<\infty$ 则 $|(X-A)\cup(X-B)|<\infty$

根据[[MK75][差分配]]可得 $(X-A)\cup(X-B)=X-A\cap B$ 故可得 $A\cap B\in F$

若 $A\in F,A\subset B$ 则有 $X-B\subset X-A$ 根据[[MK33][定理5]]有 $|X-B|\leq|X-A|<\infty$

则有 $B\in F$ 。综上所述 $F$ 是 $X$ 上的[[MK36][滤子]]

*** 超滤子<<MK39>>

设集合 $X$ 非空，则 $U$ 是 $X$ 的滤子当且仅当 $U$ 满足：

（1） $U$ 是[[MK36][滤子]]

（2） 对于任意 $A\subset X$ 有 $A\in U$ 的充要条件是 $(X-A)\not\in U$

**** 平凡超滤子<<MK43>>

若 $U$ 是 $X$ 的[[MK39][超滤子]]，当且仅当 $U=\left\{A\big|a\in A\land A\subset X\right\}$ 时有 $U$ 是 $X$ 上的平凡超滤子

***** 证明

仅证充分，故当 $U=\left\{A\big|a\in A\land A\subset X\right\}$ 时

显然 $U\subset\rho(X)$ ，且 $a\not\in\varnothing$ 故可得 $\varnothing\not\in U$ ，同理 $a\in X$ 故有 $X\in U$

对于任意 $A\in U,B\in U$ 均有 $a\in A\land a\in B$ ，故有 $a\in A\cap B$ 即有 $A\cap B\in U$

对于任意 $A\in U$ 有 $a\in A$ ，故对于任意 $A\subset B\subset X$ 均有 $a\in B$ 故有 $B\in U$

综上所述， $U$ 是 $X$ 上的[[MK39][超滤子]]

***** 性质1

若 $X$ 是[[MK83][无限集]]，且 $F$ 是 $X$ 上的[[MK38][弗雷歇滤子]]，根据[[MK41][定理]]存在[[MK39][超滤子]] $U$ 满足 $F\subset U$

则 $U$ 不是[[MK43][平凡超滤子]]

****** 证明

假设 $U$ 是[[MK43][平凡超滤子]]，则存在 $x\in X$ 满足对于任意 $u\in U$ 均有 $x\in u$

由于 $X$ 是[[MK83][无限集]]，故 $|X-(X-x)|=1$ 故 $X-x\in F\subset U$

显然 $x\not\in X-x$ 故矛盾，假设不成立，即 $U$ 不是[[MK43][平凡超滤子]]

***** 性质2

若 $X$ 是[[MK83][无限集]] $U$ 是 $X$ 上的非[[MK43][平凡超滤子]]，则对于任意 $u\in U$ 均有 $u$ 是[[MK83][无限集]]

****** 证明

假设存在 $u^*\in U$ 有 $|u^*|<\infty$ 则定义 $u=\{x_1,...,x_n\}$ 其中 $x_i\in X$ 显然 $u=\bigcup_{1\leq i\leq n}\{x_i\}$

则根据[[MK43][推论]]可得存在 $\{x_i\}$ 满足 $\{x_i\}\in U$ 则对于任意 $u\in U$ 若有 $\{x_i\}\cap u=\varnothing$

则有 $\{x_i\}\cap u=\varnothing\in U$ 与[[MK36][滤子定义]]矛盾，故必有 $\{x_i\}\cap u\ne\varnothing$ 且 $u\subset X$ 故必有 $\{x_i\}\cap u=\{x_i\}$

即对于任意 $u\in U$ 均有 $x_i\in u$ 又根据[[MK36][滤子]]有 $U\subset\rho(X)$ 即有 $U\subset\left\{u\big|u\subset X\land x_i\in u\right\}$

又由于任意 $u\subset X$ 满足 $x\in u$ 均有 $\{x_i\}\subset u$ 结合[[MK36][滤子定义]]即 $\left\{u\big|u\subset X\land x_i\in u\right\}\subset U$

根据[[MK16][自反性]]可得 $U=\left\{u\big|u\subset X\land x_i\in u\right\}$ 即 $U$ 是[[MK43][平凡超滤子]]，矛盾

故假设不成立，即[[MK83][无限集]] $X$ 上的非[[MK43][平凡超滤子]] $U$ 中的元素均为[[MK83][无限集]]

**** 定理<<MK41>>

若 $X$ 是[[MK83][无限集]]，则 $X$ 上任一[[MK36][滤子]] $F$ 都存在[[MK39][超滤子]] $U$ 满足 $F\subset U$

***** 证明

定义 $\phi(A)$ 为 $A$ 是 $X$ 的[[MK36][滤子]]的[[~/文档/note/数理逻辑/sllj.org::MK129][表达式]]，则定义 $D=\left\{E\big|E\in\rho(X)\land F\subset E\land \phi(E)\right\}$

易证 $\left<D,\subset\right>$ 是[[MK143][偏序关系]]

****** [[MK144][极大元]] $U'$

对于任意 $\left<D,\subset\right>$ 中的[[MK153][链]] $D'$ 均有 $\bigcup_{d\in D'}d$ 是 $D'$ 在 $\left<D,\subset\right>$ 上的[[MK145][上界]]

则根据[[MK162][佐恩引理]]可得存在 $\left<D,\subset\right>$ 上的[[MK144][极大元]] $U$

****** $A\not\in U$ 则存在 $u\in U$ 满足 $u\cap A=\varnothing$

对于任意非空 $A\subset X$ 若有 $A\not\in U$ ，假设对于任意 $u\in U$ 均有 $A\cap u\ne\varnothing$

则定义 $U'=\left\{C\big|C\subset X\land A\subset C\right\}\cup U\cup\left\{C\big|(C\subset X)\land(\exists u((u\in U)\land(u\cap A\subset C)))\right\}$

（1） 显然 $U'\subset\rho(X)$

（2） $X\in U$ 故有 $X\in U'$ ，由于 $A$ 非空，故 $\left\{C\big|C\subset X\land A\subset C\right\}$ 不含 $\varnothing$

     由于对于任意 $u\in U$ 均有 $A\cap u\ne\varnothing$ 故 $\left\{C\big|(C\subset X)\land(\exists u((u\in U)\land(u\cap A\subset C)))\right\}$ 不含 $\varnothing$

其余（3）（4）易证，故可得 $U'$ 亦为 $X$ 的[[MK36][滤子]]，由于 $F\subset U$ 故有 $F\subset U'$

又根据假设 $A\not\in U$ 且 $A\in\left\{C\big|C\subset X\land A\subset C\right\}$ 可得 $U\ne U'$ ，又由于 $U\subset U'$ 故可得 $U$ 不是[[MK144][极大元]]

故矛盾，则假设不成立，故可得存在 $u\in U$ 满足 $u\cap A=\varnothing$

****** $U$ 是 $X$ 的[[MK39][超滤子]]

对于任意 $A\not\in U$ 且非空，根据上一步证明存在 $u\cap A=\varnothing$ ，由于 $u\in U\subset\rho(X)$ 故有 $u\subset X-A$

故根据[[MK36][滤子（4）]]可得 $X-A\in U$

对于任意 $A\in U$ 假设 $X-A\in U$ 则有 $A\cap(X-A)=\varnothing$ 根据[[MK36][滤子（3）]]可得 $\varnothing\in U$ 与[[MK36][滤子（1）]]矛盾

故假设不成立，即有 $X-A\not\in U$

综上所述， $A\in U$ 的充要条件是 $X-A\not\in U$ ，又由于 $U$ 是[[MK36][滤子]]，故 $U$ 是[[MK39][超滤子]]

**** 性质1<<MK42>>

集合 $X$ 非空且存在[[MK39][超滤子]] $U$ ，若 $X_1\cup X_2\in U$ 则 $X_1\in U,X_2\in U$ 至少有一个成立

***** 证明

假设均不成立，即 $X_1\not\in U,X_2\not\in U$ 则根据[[MK39][定义（2）]]有 $X-X_1\in U,X-X_2\in U$

根据[[MK36][滤子定义（3）]]有 $(X-X_1)\cap(X-X_2)\in U$

根据[[MK75][差分配]]可得 $(X-X_1)\cap(X-X_2)=X-X_1\cup X_2$ 又根据[[MK39][定义（2）]] $X_1\cup X_2\not\in U$ 矛盾

故假设不成立，即 $X_1\not\in U,X_2\not\in U$ 不成立，故 $X_1,X_2$ 至少有一个是 $U$ 的元素

***** 推论<<MK43>>

集合 $X$ 非空且存在[[MK39][超滤子]] $U$ ，若 $X_1,...,X_n$ 满足 $\bigcup_{i=1}^n X_i\in U$

则至少有一个 $X_i\in U$

****** 证明

由于 $n<\infty$ 故分成 $\left(\bigcup_{i=1}^{n-1} X_i\right)\cup X_n\in U$ 根据[[MK42][性质1]]可得 $\left(\bigcup_{i=1}^{n-1} X_i\right)\in U, X_n\in U$ 至少有一个成立

若 $X_n\in U$ 成立，则推论成立，若 $\left(\bigcup_{i=1}^{n-1} X_i\right)\in U$ 成立，则以此类推。

由于 $n<\infty$ 故可证推论



** 集合定义

*** 集合朴素定义<<MK44>>

做为整体识别的、确定的、互相区别的一些对象的总体。

其中：

（1） 整体识别：不再分割

（2） 确定：属于或者不属于整体

（3） 互相区别：各异的对象

用花括号表示，例如 $A=\{1,2,3\}$

*** 成员/元素<<MK45>>

组成集合的对象，可以是任意具体或抽象的事物。也可以是[[MK44][集合]]。

若 $a$ 是集合 $A$ 的成员，记作 $a\in A$ ，定义其否命题 $\lnot(a\in A)=a\not\in A$

*** 特殊集合

**** 多重集合<<MK46>>

在[[MK44][集合定义]]上扩展，可包含 *互相不区别* 的对象，即同一[[MK45][元素]]可在集合中出现多次。

其元素定义为[[MK105][有序组]] $<S,n>$ 其中 $S$ 是元素 $n\in\mathbb{N}^+$ 表示重数

用方括号表示，例如 $A=[1,1,1,2,2,3]=\{<1,3>,<2,2>,<3,1>\}$

*** 集合族<<MK47>>

集合 $A$ 中的元素都是集合，则 $A$ 称作集合族。

**** 标志集（指标集）<<MK48>>

定义集合族 $C$ 可表示为 $C=\left\{S_d\big|d\in D\right\}$ 那么下标所组成的集合称为 $C$ 的标志集

简化一般记作 $C_D$

** 集合的表示

*** 列举法

列举集合中所有的元素，例如 $A=\{1,2,3\}$

*** 描述法<<MK49>>

利用[[~/文档/note/数理逻辑/sllj.org::MK129][谓词公式定义]]描述集合中的元素。

例如 $A=\left\{x\big|P(x)\right\}$ 或 $A=\left\{x\big:P(x)\right\}$ 

定义为当且仅当[[~/文档/note/数理逻辑/sllj.org::MK129][谓词公式]] $P(x)=1$ 时，有 $x\in A$ 即 $\forall x(P(x)\leftrightarrow x\in A)=1$ 。

**** 替换引理<<MK50>>

若有 $A=\left\{x\big|P(x)\right\}$ 则 $A=\left\{x\bigg|x\in\left\{z\big|P(z)\right\}\right\}$

***** 证明

定义 $A'=\left\{x\bigg|x\in\left\{z\big|P(z)\right\}\right\}$ 则对于任意 $x^*\in A$ 均满足 $P(x^*)=1$

则显然 $x^*\in\left\{z\big|P(z)\right\}$ 为真，则 $x\in A'$ ，即根据[[MK15][定义]]可得 $A'\subset A$

对于任意 $x^*\in A'$ 必有 $x\in\left\{z\big|P(z)\right\}$ 为真，

由于 $A=\left\{x\big|P(x)\right\}=\left\{z\big|P(z)\right\}$ 即 $x\in A$ ，即根据[[MK15][定义]]可得 $A \subset A'$

故根据[[MK16][自反性]]可得 $A=A'$

*** 归纳法

**** 归纳定义<<MK51>>

根据以下三个条款：

（1） 基础条款<<MK52>>：规定某些元素为待定义集合成员，集合其它元素可以从基本元素出发逐步确定

（2） 归纳条款<<MK53>>：规定由已确定的集合元素去进一步确定其它元素的规则

（3） 终极条款<<MK54>>：规定待定义集合只含有基础条款和归纳条款所确定的成员

定义的集合。

其中[基础条款]与[归纳条款]为完备性条款，保证无遗漏产生集合所有成员

[终极条款]为纯粹性条款，保证集合中仅包含满足完备性条款的那些对象。

**** 归纳原理（数学归纳法）

若集合 $A$ 以[[MK51][归纳定义]]，若 $P(x)$ 是[[~/文档/note/数理逻辑/sllj.org::MK129][谓词公式]]其中 $x$ 是命题变元。要证明 $\forall x(x\in A\rightarrow P(x))$ 仅需证明：

（1） [[MK52][基础条款]]中定义的所有元素为真 $P(x^1_0)\land...\land P(x^u_0)=1$

（2） 证明当已确定的元素 $x_1,...,x_k$ 满足 $P$ 时，由[[MK53][归纳条款]]进一步确定的其他元素也满足 $P$ 

      即若其中任一归纳条款为 $\forall x_1...\forall x_k\left((x_1\in A\land...\land x_k\in A)\rightarrow (g_1(x_1,...,x_k)\in A\land...\land g_s(x_1,...,x_k)\in A)\right)$ 

      则有 $\forall x_1...\forall x_s\left((P(x_1)\land...\land P(x_s))\rightarrow (P(g_1(x_1,...,x_k))\land...\land P(g_s(x_1,...,x_k)))\right)$
 
***** 证明

假设集合 $A$ 有[[MK51][归纳定义]]，[[~/文档/note/数理逻辑/sllj.org::MK129][谓词公式]] $P$ 且两个条件均成立，即：

（1） $P(x^1_0)\land...\land P(x^u_0)=1$

（2） 对于任一归纳条款 $\forall x_1...\forall x_k\left((x_1\in A\land...\land x_k\in A)\rightarrow (g_1(x_1,...,x_k)\in A\land...\land g_s(x_1,...,x_k)\in A)\right)$ 

      均有 $\forall x_1...\forall x_s\left((P(x_1)\land...\land P(x_s))\rightarrow (P(g_1(x_1,...,x_k))\land...\land P(g_s(x_1,...,x_k)))\right)$

对于任意 $y\in A$ 若 $y\in(x^1_0,...,x^u_0)$ 则根据（1）有 $P(y)=1$

若 $y\not\in(x^1_0,...,x^u_0)$ 则由[[MK54][终极条款]]，必于有公式序列 $x^1_0,...,x^u_0,z_1,...,z_n,y$ 

其中 $n<\infty$ ， $z_i$ 可由 $x^1_0,...,x^u_0,z_1,...,z_{i-1}$ 由[[MK53][归纳条款]]导出。

根据条件（2）可得 $P(y)=1$

**** 自然数集合定义

***** 自然数归纳定义<<MK55>>

基础条款： $\varnothing\in N$

归纳条款： 如果 $x\in N$ 则 $x'=x\cup\{x\}\in N$ （即 $0=\varnothing,1=\left\{\varnothing\right\},2=\left\{\varnothing,\left\{\varnothing\right\}\right\},3=\left\{\varnothing,\left\{\varnothing\right\},\left\{\varnothing,\left\{\varnothing\right\}\right\}\right\}$ ）

终极条款： 只有有限次使用上述条款产生的集合为自然数。

***** 自然数加法

若 $x$ 是自然数，则：

（1） $x+0=x$ （ $A\cup\varnothing=A$ ）

（2） $x+y'=(x+y)'$ （ $A+(B\cup \{B\})=(A+B)\cup\{A+B\}$ ）

***** 自然数乘法

若 $x$ 是自然数，则：

（1） $x\times0=0$

（2） $x\times y'=(x\times y)+x$

** 集合的关系

*** 空集

根据[[MK6][空集存在]]公理，不含有任何[[MK45][元素]]的集合称为空集，记作 $\varnothing$

*** 全集

根据定义，包含研究对象全体的集合叫做全集，记作 $U$

全集亦为空集的[[MK63][补集]]

*** 相等

根据[[MK2][外延公理]]，集合间存在相等关系，且等价条件为 $\forall x(x\in A\leftrightarrow x\in B)$

** 集合的计算<<MK56>>

以[[MK44][集合]]作为运算对象，结果亦为[[MK44][集合]]的运算。

*** 运算<<MK57>>

**** 并运算<<MK58>><<MK59>>

定义为 $\bigcup C=\left\{x\big|\exists c((c\in C)\rightarrow (x\in c))\right\}$ 根据[[MK9][并集公理]]可得 $\bigcup C$ 存在

若 $C$ 为[[MK47][集合族]]，其[[MK48][标志集]]为 $\Lambda$ 则亦有 $\bigcup_{\lambda\in\Lambda} C_\lambda=\left\{x\big|\exists \lambda\in\Lambda\rightarrow x\in C_\lambda\right\}$

特别地当 $C=\{A,B\}$ 时可记作 $A\cup B=\left\{x\big|x\in A\lor x\in B\right\}$

**** 交运算<<MK60>><<MK61>>

定义为 $\bigcap C=\left\{x\big|\forall c((c\in C)\rightarrow (x\in c))\right\}$ 

若 $C$ 为[[MK47][集合族]]，其[[MK48][标志集]]为 $\Lambda$ 则亦有 $\bigcap_{\lambda\in\Lambda} C_\lambda=\left\{x\big|\forall \lambda\in\Lambda\rightarrow x\in C_\lambda\right\}$

特别地当 $C=\{A,B\}$ 时可记作 $A\cap B=\left\{x\big|x\in A\land x\in B\right\}$

***** 存在性证明

显然 $\forall c((c\in C)\rightarrow (x\in c))$ 是[[MK1][集合论语言]]的[[~/文档/note/数理逻辑/sllj.org::MK129][表达式]]，又根据[[MK9][并集公理]]可得 $\bigcup C$ 存在

根据[[MK5][分离模式]]定理存在 $S=\left\{x\big|((x\in\bigcup C)\land(\forall c((c\in C)\rightarrow (x\in c)))\right\}$

**** 差运算<<MK62>>

定义为 $A- B=\left\{x\big|x\in A\land x\not\in B\right\}$

**** 补运算<<MK63>>

定义为 $\overline{A}=U-A=\left\{x\big|x\not\in A\right\}$

*** 性质

**** 相同集合的广义交并相同<<MK64>>

\begin{aligned}
A=B{|\!\!\!=}\cup A=\cup B\\
A=B{|\!\!\!=}\cap A=\cap B\\
\end{aligned}

***** 证明

仅证明 $A=B{|\!\!\!=}\cup A=\cup B$ 且 $A,B$ 为集合族

根据[[MK2][外延公理]] $A=B{|\!\!\!=\!\!\!|}\forall S(S\in A\leftrightarrow S\in B)$

根据[[MK59][广义并]]可得 $x\in\cup A{|\!\!\!=\!\!\!|}\exists S(x\in S\land S\in A)$

故有 $x\in\cup A{|\!\!\!=\!\!\!|}\exists S(x\in S\land S\in A){|\!\!\!=\!\!\!|}\exists S(x\in S\land S\in B){|\!\!\!=\!\!\!|}x\in\cup B$ 根据[[MK2][外延公理]] $\cup A=\cup B$

**** 集合族运算与交并<<MK65>>

\begin{aligned}
A\cap\left(\bigcup_{\lambda\in\Lambda} C_\lambda\right)&=\bigcup_{\lambda\in\Lambda}\left(A\cap C_\lambda\right)\\
A\cup\left(\bigcap_{\lambda\in\Lambda} C_\lambda\right)&=\bigcap_{\lambda\in\Lambda}\left(A\cup C_\lambda\right)\\
A\cap\left(\bigcap_{\lambda\in\Lambda} C_\lambda\right)&=\bigcap_{\lambda\in\Lambda}\left(A\cap C_\lambda\right)\\
\end{aligned}

***** 证明

仅证 $A\cap\left(\bigcap_{\lambda\in\Lambda} C_\lambda\right)=\bigcap_{\lambda\in\Lambda}(A\cap C_\lambda)$

对于任意 $x\in A\cap\left(\bigcap_{\lambda\in\Lambda} C_\lambda\right)$ 有 $x\in A$ 且对于任意 $\lambda\in\Lambda$ 均有 $x\in C_\lambda$

故可得对于任意 $\lambda\in\Lambda$ 有 $x\in A\cap C_\lambda$ 即 $x\in\bigcap_{\lambda\in\Lambda}(A\cap C_\lambda)$

对于任意 $x\in\bigcap_{\lambda\in\Lambda}(A\cap C_\lambda)$ 有对于任意 $\lambda\in\Lambda$ 有 $x\in A\cap C_\lambda$

即对于任意 $\lambda\in\Lambda$ 有 $x\in A$ 且 $x\in C_\lambda$ 即 $x\in A$ 且对于任意 $\lambda\in\Lambda$ 均有 $x\in C_\lambda$

即 $x\in A\cap\left(\bigcap_{\lambda\in\Lambda} C_\lambda\right)$

综上所述，根据[[MK2][外延公理]]可得 $A\cap\left(\bigcap_{\lambda\in\Lambda} C_\lambda\right)=\bigcap_{\lambda\in\Lambda}(A\cap C_\lambda)$ 

**** 集合族运算与差<<MK66>>

\begin{aligned}
A-\left(\bigcup_{\lambda\in\Lambda} C_\lambda\right)&=\bigcap_{\lambda\in\Lambda}(A- C_\lambda)\\
A-\left(\bigcap_{\lambda\in\Lambda} C_\lambda\right)&=\bigcup_{\lambda\in\Lambda}(A- C_\lambda)\\
\end{aligned}

***** 证明

仅证 $A-\bigcup_{\lambda\in\Lambda} C=\bigcap_{\lambda\in\Lambda}(A-C_\lambda)$

则对于任意 $x\in A-\bigcup_{\lambda\in\Lambda} C$ 有 $x\in A\land x\not\in\bigcup_{\lambda\in\Lambda} C_\lambda$

根据[[MK61][广义交]] $x\in A\land\forall\lambda\in\Lambda\rightarrow x\not\in C_\lambda$

根据[[~/文档/note/数理逻辑/sllj.org::MK45][交换率]] $(\forall\lambda\in\Lambda\rightarrow x\not\in C_\lambda)\land x\in A$

根据[[~/文档/note/数理逻辑/sllj.org::MK183][辖域变化]] $\forall\lambda\in\Lambda\rightarrow (x\not\in C_\lambda\land x\in A)$ 即有 $\forall\lambda\in\Lambda\rightarrow (x\in(A-C_\lambda))$  

又根据[[MK59][广义并]] $x\in\bigcup_{\lambda\in\Lambda}(A-C_\lambda)$ 故有 $A-\bigcup_{\lambda\in\Lambda} C\subset\bigcap_{\lambda\in\Lambda}(A-C_\lambda)$

同理易证 $\bigcap_{\lambda\in\Lambda}(A-C_\lambda)\subset A-\bigcup_{\lambda\in\Lambda} C$

根据[[MK16][自反性]]有 $A-\bigcup_{\lambda\in\Lambda} C=\bigcap_{\lambda\in\Lambda}(A-C_\lambda)$

**** 集合族运算与补<<MK80>>

\begin{aligned}
\overline{\bigcup_{\lambda\in\Lambda} C_\lambda}&=\bigcap_{\lambda\in\Lambda}\overline{C_\lambda}\\
\overline{\bigcap_{\lambda\in\Lambda} C_\lambda}&=\bigcup_{\lambda\in\Lambda}\overline{C_\lambda}\\
\end{aligned}

**** 可数性质<<MK68>>

\begin{aligned}
&\forall x\left(x\in\bigcup_{i=1}^\infty S_i\leftrightarrow x\in\bigcup_{i\in\mathbb{N}^+} S_i\leftrightarrow \exists i\left(i\in\mathbb{N}^+\land x\in S_i\right)\right)\\
&\forall x\left(x\in\bigcap_{i=1}^\infty S_i\leftrightarrow x\in\bigcap_{i\in\mathbb{N}^+} S_i\leftrightarrow \forall i\left(i\in\mathbb{N}^+\rightarrow x\in S_i\right)\right)
\end{aligned}

***** 证明

根据[[MK89][可数]]定义可得必与整数集的子集有一一对应关系，则有 $\bigcup_{i=1}^\infty S_i=\bigcup_{i\in\mathbb{N}^+}S_i$

进一步根据[[MK59][广义并]]以及[[MK61][广义交]]定义，显然证得

**** 等利律（幂等律）<<MK69>>

\begin{aligned}
A\cap A=A\\
A\cup A=A
\end{aligned}

**** 交换律<<MK70>>

\begin{aligned}
A\cap B=B\cap A\\
A\cup A=B\cup A
\end{aligned}

**** 结合律<<MK71>>

\begin{aligned}
(A\cap B)\cap C=A\cap (B\cap C)\\
(A\cup B)\cup C=A\cup (B\cup C)\\
\end{aligned}

**** 同一律<<MK72>>

\begin{aligned}
A\cup\varnothing=A\\
A\cap U=A\\
\end{aligned}

**** 零律

\begin{aligned}
A\cap\varnothing=\varnothing\\
A\cup U=U\\
\end{aligned}

**** 分配律<<MK73>>

\begin{aligned}
A\cup (B\cap C)&=(A\cup B)\cap (A\cup C)\\
A\cap (B\cup C)&=(A\cap B)\cup (A\cap C)\\
\end{aligned}

进一步有：

\begin{aligned}
A\cup\left(\bigcap_{i=1}^\infty B_i\right)&=\bigcap_{i=1}^\infty\left(A\cup B_i\right)\\
A\cap\left(\bigcup_{i=1}^\infty B_i\right)&=\bigcup_{i=1}^\infty\left(A\cap B_i\right)\\
\end{aligned}

***** 证明

****** 有限个<<MK74>>

这里仅证 $A\cup (B\cap C)&=(A\cup B)\cap (A\cup C)$ 其余同理可证

根据[[MK58][并]]以及[[MK60][交]]运算可得 $B\cap C=\left\{x\big|x\in B\land x\in C\right\}$ 以及 $A\cup (B\cap C)=\left\{x\big|x\in A\lor x\in B\cap C\right\}$

根据[[~/文档/note/数理逻辑/sllj.org::MK47][分配率]]，[[MK49][描述法定义]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]可得对于任意 $x$

\begin{aligned}
&x\in A\cup (B\cap C)\\
\leftrightarrow&x\in A\lor x\in B\cap C\\
\leftrightarrow&x\in A\lor(x\in B\land x\in C)\\
\leftrightarrow&(x\in A\lor x\in B)\land(x\in A\lor x\in C)\\
\leftrightarrow&(x\in A\cup B)\land(x\in A\cup C)\\
\leftrightarrow&x\in(A\cup B)\cap(A\cup C)\\
\end{aligned}

即 $\forall x:(x\in A\cup (B\cap C))\leftrightarrow(x\in(A\cup B)\cap(A\cup C))$ 根据[[MK2][外延公理]] $A\cup (B\cap C)&=(A\cup B)\cap (A\cup C)$

****** [[MK89][可数]]个

这里仅证 $A\cup\left(\bigcap_{i=1}^\infty B_i\right)&=\bigcap_{i=1}^\infty\left(A\cup B_i\right)$ 其余同理

根据[[MK68][可数性质]]、[[~/文档/note/数理逻辑/sllj.org::MK183][辖域变化]]、[[MK70][交换律]]以及[[MK57][运算定义]]

\begin{aligned}
&\forall x\in \left(\bigcap_{i=1}^\infty\left(A\cup B_i\right)\right)\\
\leftrightarrow&\forall i(i\in\mathbb{N^+}\rightarrow x\in B_i\lor x\in A)\\
\leftrightarrow&\forall i(i\in\mathbb{N^+}\rightarrow x\in B_i)\lor x\in A\\
\leftrightarrow&x\in\left(\left(\bigcap_{i=1}^\infty B_i\right)\cup A\right)
\end{aligned}

根据[[MK2][外延公理]]可得 $A\cup\left(\bigcap_{i=1}^\infty B_i\right)&=\bigcap_{i=1}^\infty\left(A\cup B_i\right)$ 

**** 吸收律

\begin{aligned}
A\cap (A\cup B)&=A\\
A\cup (A\cap B)&=A\\
\end{aligned}

**** 双重否定率

\begin{aligned}
\overline{\overline{A}}=A\\
\end{aligned}

**** 特殊集合的差

\begin{aligned}
A-A=\varnothing\\
A-\varnothing=A\\
A-U=\varnothing\\
\end{aligned}

**** 差分配率<<MK75>>

\begin{aligned}
A-(B\cap C)&=(A-B)\cup (A-C)\\
A-(B\cup C)&=(A-B)\cap (A-C)\\
\end{aligned}

***** 证明

仅证 $A-(B\cap C)&=(A- B)\cup (A-C)$ 根据[[MK58][并]]，[[MK60][交]]以及[[MK62][差]]运算定义 $B\cap C=\left\{x\big|x\in B\land x\in C\right\},A-(B\cap C)=\left\{x\big|x\in A\land x\not\in B\cap C\right\}$

则根据[[MK45][成员定义]]，[[~/文档/note/数理逻辑/sllj.org::MK186][德摩根律]]，[[~/文档/note/数理逻辑/sllj.org::MK47][分配率]]，[[MK49][描述法定义]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]可得对于任意 $x$

\begin{aligned}
&x\in A-(B\cap C)\\
\leftrightarrow&x\in A\land x\not\in B\cap C\\
\leftrightarrow&x\in A\land\lnot(x\in B\land x\in C)\\
\leftrightarrow&x\in A\land(x\not\in B\lor x\not\in C)\\
\leftrightarrow&(x\in A\land x\not\in B)\lor(x\in A\land x\not\in C)\\
\leftrightarrow&(x\in A-B)\lor(x\in A-C)\\
\leftrightarrow&x\in (A-B)\cup(A-C)\\
\end{aligned}

即 $\forall x:x\in A-(B\cap C)\leftrightarrow x\in (A-B)\cup(A-C)$ ，根据[[MK2][外延公理]] $A-(B\cap C)&=(A- B)\cup (A-C)$

**** 矛盾律和排中律

\begin{aligned}
\overline{U}=\varnothing\\
\overline{\varnothing}=U\\
\end{aligned}

**** 自身补运算

\begin{aligned}
A\cup \overline{A}=U\\
A\cap \overline{A}=\varnothing\\
\end{aligned}

**** 德摩根律<<MK76>>

\begin{aligned}
\overline{A\cup B}=\overline{A}\cap \overline{B}\\
\overline{A\cap B}=\overline{A}\cup \overline{B}\\
\end{aligned}

进一步有

\begin{aligned}
\overline{\bigcup_{i=1}^\infty A_i}=\bigcap_{i=1}^\infty\overline{A_i}\\
\overline{\bigcap_{i=1}^\infty A_i}=\bigcup_{i=1}^\infty\overline{A_i}\\
\end{aligned}

***** 证明

****** 有限

仅证 $\overline{A\cup B}=\overline{A}\cap\overline{B}$ 根据[[MK58][并]]与[[MK63][补]]运算定义 $\overline{A\cup B}=\left\{x\big|x\not\in A\cup B\right\}$ 以及 $\overline{A}\cap\overline{B}=\left\{x\big|x\not\in A\land x\not\in B\right\}$

根据[[MK45][成员定义]]，[[MK49][描述法定义]]，[[~/文档/note/数理逻辑/sllj.org::MK186][德摩根律]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]可得对于任意 $x$

\begin{aligned}
&x\in \overline{A\cup B}\\
\leftrightarrow&x\not\in(A\cup B)\\
\leftrightarrow&\lnot(x\in(A\cup B))\\
\leftrightarrow&\lnot(x\in A\lor x\in B))\\
\leftrightarrow&\lnot(x\in A)\land\lnot(x\in B)\\
\leftrightarrow&x\not\in A\land x\not\in B\\
\leftrightarrow&x\in\overline{A}\cap\overline{B}\\
\end{aligned}

即 $\forall x\left((x\in\overline{A\cup B})\leftrightarrow(x\in\overline{A}\cap\overline{B})\right)$ ，根据[[MK2][外延公理]] $\overline{A\cup B}=\overline{A}\cap\overline{B}$ 

****** [[MK89][可数]]

仅证 $\overline{\bigcap_{i=1}^\infty A_i}=\bigcup_{i=1}^\infty\overline{A_i}$ 其余同理

根据[[MK68][可数性质]]、[[MK57][运算定义]]、[[~/文档/note/数理逻辑/sllj.org::MK48][蕴含等式]]、[[~/文档/note/数理逻辑/sllj.org::MK186][德摩根律]]、[[~/文档/note/数理逻辑/sllj.org::MK182][量词转换]]可得

\begin{aligned}
&x\in\bigcup_{i=1}^\infty\overline{A_i}\\
\leftrightarrow&\exists i\left(i\in\mathbb{N}^+\land x\in \overline{A_i}\right)\\
\leftrightarrow&\exists i\left(i\in\mathbb{N}^+\land x\not\in A_i\right)\\
\leftrightarrow&\exists i\left(\lnot\left(i\not\in\mathbb{N}^+\lor x\in A_i\right)\right)\\
\leftrightarrow&\lnot\forall i\left(i\not\in\mathbb{N}^+\lor x\in A_i\right)\\
\leftrightarrow&\lnot\forall i\left(i\in\mathbb{N}^+\rightarrow x\in A_i\right)\\
\leftrightarrow&\lnot\left(x\in\bigcup_{i=1}^\infty A_i\right)\\
\leftrightarrow&x\in\overline{\bigcup_{i=1}^\infty A_i}\\
\end{aligned}

根据[[MK2][外延公理]]可得 $\overline{\bigcap_{i=1}^\infty A_i}=\bigcup_{i=1}^\infty\overline{A_i}$ 

**** 补与减<<MK77>>

\begin{aligned}
A-B=A\cap\overline{B}\\
\end{aligned}

**** 连续减<<MK78>>

$A-B-C=A-B\cup C$

***** 证明

若 $x\in A-B$ 则等价于 $x\in A\land x\not\in B$

则 $x\in (A-B)-C$ 则满足 $x\in A-B$ 同时亦有 $x\not\in C$

即 $x\in A\land x\not\in B\land x\not\in C$

若 $x\not\in B\cup C$ 则根据[[MK58][并运算]]可得 $x\not\in B\land x\not\in C$

则 $x\in A-B\cup C$ 定义为 $x\in A\land x\not\in B\land x\not\in C$

故两者等价，即 $A-B-C=A-B\cup C$

**** 子集与计算<<MK79>>

\begin{aligned}
&A\subset A\cup B\\
&A\cup B\subset A\\
&A-B\subset A\\
&A\subset B\leftrightarrow A-B=\varnothing\leftrightarrow A\cup B=B\leftrightarrow A\cap B=A\\
&A\subset B\rightarrow \overline{B}\subset \overline{A}\\
&A\subset B\rightarrow B=A\cup(A-B)
\end{aligned}

**** [[~/文档/note/数理逻辑/sllj.org::MK106][量词]]与运算<<MK80>>

\begin{aligned}
\left\{x\big|\forall y\in Y\rightarrow P(x,y)\right\}=\bigcap_{y\in Y}\left\{x\big|P(x,y)\right\}\\
\left\{x\big|\exists y\in Y\rightarrow P(x,y)\right\}=\bigcup_{y\in Y}\left\{x\big|P(x,y)\right\}\\
\end{aligned}

***** 证明

仅证一式，二式同理易证

根据[[MK50][替换引理]]以及[[MK61][广义并]]有：

\begin{aligned}
&\left\{x\big|\forall y\in Y\rightarrow P(x,y)\right\}\\
=&\left\{x\bigg|\forall y\in Y\rightarrow x\in\left\{z\big|P(z,y)\right\}\right\}\\
=&\bigcap_{y\in Y}\left\{x\bigg|x\in\left\{z\big|P(z,y)\right\}\right\}\\
=&\bigcap_{y\in Y}\left\{x\big|P(x,y)\right\}\\
\end{aligned}

**** 补与并<<MK81>>

$A\cap B=C\cap B\rightarrow\overline{A}\cap B=\overline{C}\cap B$

***** 证明

由于 $A\cap B=C\cap B$ 则有 $x\in A\land x\in B\leftrightarrow x\in C\land x\in B$

对于任意 $a\in\overline{A}\cap B$ 可得 $a\not\in A\land a\in B$

假设 $a\in C$ 则根据 $x\in C\land a\in B$ 可得 $x\in A$ 与 $a$ 的定义矛盾

故假设不成立，则有 $x\not\in C$ 即 $x\not\in C\land x\in B\rightarrow x\in\overline{C}\cap B$ 即 $\overline{A}\cap B\subset\overline{C}\cap B$

同理易证 $\overline{C}\cap B\subset\overline{B}\cap B$ 则根据[[MK16][自反性]]可得 $\overline{A}\cap B=\overline{C}\cap B$

** 集合分类

*** 有限集<<MK82>>

空集和只含有限多个元素的集合称作有限集

*** 无限集<<MK83>>

不为[[MK82][有限集]]的集合均为无限集

**** 定理1<<MK84>>

任意无限集包含[[MK89][可数]]子集

***** 证明

对于[[MK83][无限集]] $S$ 定义 $X_0=\{x_0\}\subset S$

对于任意 $n\in\mathbb{N}$ 若 $X_{n-1}=\{x_0,...,x_{n-1}\}$ 是[[MK82][有限集]]，则 $S-X_{n-1}\ne\varnothing$

则任取 $x_n\in S-X_{n-1}$ 并定义 $X_n=X_{n-1}\cup\{x_n\}$

根据数学归纳法，对于任意 $n\in\mathbb{N}$ 均存在 $X_n$ 满足 $X_n=X_{n-1}\cup\{x_n\}=\{x_0,...,x_n\}$

定义 $X=\bigcup_{n\in\mathbb{N}}X_n$ 以及 $\sigma=\left\{\left<n,x_n\right>\big|n\in\mathbb{N}\land x_n\in X\right\}$

根据下列证明可得 $\sigma$ 是 $\mathbb{N}$ 到 $X$ 的[[MK181][双射函数]]，即有 $|\mathbb{N}|=|X|$ 且 $X\subset S$

****** 是[[MK175][函数]]

则对于任意 $n\in\mathbb{N}$ 假设存在 $\{a,b\}\subset X,a\ne b$ 则根据 $X$ 定义存在 $n\ne m$

满足 $a\not\in X_u\land a\in X_{u+1},b\not\in X_v\land b\in X_{v+1}$ 设 $u<v$ 则根据 $X_n$ 定义有 $X_u\subset X_v$

故有 $a\in X_v$ 若 $a=b$ 则有 $b\in X_v$ 与 $b\not\in X_v$ 矛盾，故假设不成立

即对于任意 $n\in\mathbb{N}$ 有且仅有为 $x_n$ 满足 $\left<n,x_n\right>\in\sigma$ 即 $\sigma$ 是[[MK175][函数]]

****** 是[[MK176][单射]]

对于任意 $\{n,m\}\subset\mathbb{N},n<m$ 可得 $\sigma(n)=x_n\in X,\sigma(m)=x_m\in X$

显然 $x_n\in X_n\subset X_{m-1}$ 且 $x_m\in S-X_{m-1}$ 故可得 $x_n\ne x_m$ 即 $\sigma$ 是[[MK176][单射]]

****** 是[[MK179][满射]]

对于任意 $a\in X$ 存在 $n$ 满足 $a\in X_n\land a\not\in X_{n+1}$ 根据 $X$ 定义可得 $a=x_n$

则有 $\sigma(n)=x_n=a$ 即 $\sigma$ 是[[MK179][满射]]

***** 推论<<MK329>>

[[MK89][可数]]集是[[MK29][势]]最小的[[MK83][无限集]]

****** 证明

根据[[MK84][定理1]]可得任意[[MK83][无限集]] $A$ 均有[[MK89][可数]]子集 $A'$ ，根据[[MK33][定理5]]有 $|\mathbb{N}|=|A'|\leq|A|$

根据[[MK327][定理7]]可得 $|\mathbb{N}|\leq|A|$ 又根据[[MK328][定理4]]可得 $|A|\not<|\mathbb{N}|$

综上所述，对于任意[[MK83][无限集]] $A$ 均有 $|A|\not<|\mathbb{N}|$ ，即 $\mathbb{N}$ 是[[MK29][势]]最小的[[MK83][无限集]]

**** 定理2<<MK85>>

任意无限集 $A$ 存在集合 $B\subset A$ 满足 $|B\times\mathbb{N}|=|A|$

***** 证明

****** 定义[[MK143][偏序关系]] $\left<F,\subset\right>$ 

定义

\begin{aligned}
&\text{IsFunc}(f,B)\\
=&((\forall x((x\in X)\rightarrow(\exists y(\left<x,y\right>\in f))))\land\\
&(\forall y_1(\forall y_2(((\left<x,y_1\right>\in f)\land(\left<x,y_2\right>\in f))\rightarrow(y_1=y_2))))\land\\
&(f\subset (B\times \mathbb{N})\times A)\land\\
&(\forall x_1(\forall x_2((\{x_1,x_2\}\subset(B\times \mathbb{N}))\to(f(x_1)\ne f(x_2)))))
)
\end{aligned}

即 $f$ 是 $(B\times\mathbb{N})\to A$ 的[[MK176][单射函数]]的[[~/文档/note/数理逻辑/sllj.org::MK129][表达式]]。定义 $F=\left\{f\big|(\text{IsFunc}(f,B)\land B\subset A)\right\}$

根据[[MK84][定理1]]可得存在 $B^*\subset A$ 满足 $|B^*|=|\mathbb{N}|$ 根据[[MK29][定义]]可得存在[[MK181][双射函数]] $\sigma:B^*\to\mathbb{N}$ 

此时任取 $a\in A$ 定义 $B_0=\{a\}$ 以及 $f_0(a,n)=\sigma^{-1}(n)$ 显然 $f_0:\{a\}\times\mathbb{N}\to A$ 满足 $f_0\in F$

即 $F$ 非空，定义 $\left<F,\subset\right>$ 显然为[[MK143][偏序关系]]

****** 任意 $\left<F,\subset\right>$ 的[[MK153][链]]有[[MK145][上界]]

对于任意 $\left<F,\subset\right>$ 的[[MK153][链]] $F'\subset F$

有对于任意 $\{f_1,f_2\}\in F'$ 有 $((f_1\subset f_2)\lor (f_2\subset f_1))$ 则定义 $f^*=\bigcup_{f\in F'}f,B^*=\bigcup_{f:(B_f\times\mathbb{N})\to A\land f\in F'} B_f$

根据以下证明可得 $f^*:(B^*\times\mathbb{N})\to A$ 是[[MK176][单射]]，根据 $B^*$ 定义可得 $B^*\subset A$

综上所述可得 $f^*\in F$ 且对于任意 $f\in F'$ 有 $f\subset f^*$ ，即 $f^*$ 是 $F'$ 的[[MK145][上界]]

******* $f^*$ 是[[MK175][函数]]

******** 定义域为 $B^*\times\mathbb{N}$

对于任意 $b\in B^*,n\in\mathbb{N}$ 存在 $B_f$ 满足 $b\in B_f$ 且有 $f:(B_f\times\mathbb{N})\to A$ 满足 $f\in F'$

故 $f$ 是[[MK175][函数]]，则存在 $a\in A$ 满足 $f(b,n)=a$ 进一步有 $\left<\left<b,n\right>,a\right>\in f^*$ 。

即对于任意 $b\in B^*,n\in\mathbb{N}$ 存在 $a\in A$ 满足 $\left<\left<b,n\right>,a\right>\in f^*$ 

******** 是[[MK175][函数]]

对于任意 $b\in B^*,n\in\mathbb{N}$ 假设存在 $a\in A,a'\in A,a\ne a'$ 满足 $\left<\left<b,n\right>,a\right>\in f^*,\left<\left<b,n\right>,a'\right>\in f^*$

则根据 $f^*$ 定义可得存在 $\{f_1,f_2\}\subset F'$ 满足 $\left<\left<b,n\right>,a\right>\in f_1,\left<\left<b,n\right>,a'\right>\in f_2$

又由于 $F'$ 是[[MK153][链]]，故有 $f_1\subset f_2\lor f_2\subset f_1$ ，不妨设前者成立，反之同理可证

则有 $f_1\subset f_2$ 故 $\{\left<\left<b,n\right>,a\right>,\left<\left<b,n\right>,a'\right>\}\subset f_2$ 由于 $f_2\in F'\subset F$ 故与 $f_2$ 是[[MK175][函数]]矛盾

则假设不成立，即对于任意 $b\in B^*,n\in\mathbb{N}$ 存在唯一 $a\in A$ 满足 $\left<\left<b,n\right>,a\right>\in f^*$

综上所述， $f^*$ 是 $B^*\times\mathbb{N}$ 到 $A$ 的[[MK175][函数]]

******* $f^*:(B^*\times\mathbb{N})\to A$ 是[[MK176][单射]]

对于任意 $\{\left<b_1,n_1\right>,\left<b_2,n_2\right>\}\subset B^*\times\mathbb{N}$ 根据上步证明可得存在 $f^*(b_1,n_1)=a_1\in A,f^*(b_2,n_2)=a_2\in A$

假设 $a_1=a_2$ ，根据 $f^*$ 定义可得存在 $\{f_1,f_2\}\subset F'$ 满足 $\left<\left<b_1,n_1\right>,a_1\right>\in f_1,\left<\left<b_2,n_2\right>,a_2\right>\in f_2$

又由于 $F'$ 是[[MK153][链]]，故有 $f_1\subset f_2\lor f_2\subset f_1$ ，不妨设前者成立，反之同理可证

则有 $f_1\subset f_2$ 故 $\{\left<\left<b_1,n_1\right>,a_1\right>,\left<\left<b_2,n_2\right>,a_2\right>\}\subset f_2$ 由于于 $f_2\in F'\subset F$ 故与 $f_2$ 是[[MK176][单射]]矛盾

则假设不成立，即 $f^*:(B^*\times\mathbb{N})\to A$ 是[[MK176][单射]]

****** 证明结论

根据上一步证明以及[[MK162][佐恩引理]]可得存在 $\left<F,\subset\right>$ 中的[[MK166][极大元]] $f^*:(B^*\times\mathbb{N})\to A$ 其中 $B^*\subset A$

定义 $A'=\left\{a\big|((a\in A)\land(\exists b(\exists n((b\in B^*)\land(n\in\mathbb{N})\land(f(b,n)=a)))))\right\}$ 即 $A'$ 是 $f^*$ 的相

则根据以下证明可得存在 $B^*\times\mathbb{N}$ 到 $A$ 的[[MK181][双射函数]] $g$ ，故根据[[MK29][等势]]可得 $|B^*\times\mathbb{N}|=|A|$ 且 $B^*\subset A$  

******* $A-A'$ 是[[MK82][有限集]]

则假设 $A-A'$ 是[[MK83][无限集]]，则根据[[MK84][定理1]] $A-A'$ 存在[[MK89][可数]]子集 $S$ 满足 $|S|=|\mathbb{N}|$

即存在[[MK181][双射函数]] $\sigma:S\to\mathbb{N}$ ，则任取 $a\in A-A'$ 并定义 $f:(\{a\}\times\mathbb{N})\to A$ 满足 $f(a,n)=\sigma(n)$

显然 $f$ 满足 $(\text{IsFunc}(f,\{a\})\land \{a\}\subset A)$ 即有 $f\in F$ 且易证 $f^*\cup f\in F$

故有 $f^*\subset f^*\cup f$ 则 $f^*$ 不是 $\left<F,\subset\right>$ 中的[[MK166][极大元]]，矛盾。故假设不成立，即有 $A-A'$ 是[[MK82][有限集]]

******* 构造[[MK181][双射函数]]

由于 $A-A'$ 是[[MK82][有限集]]，易证存在 $h:\{0,...,m-1\}\to A-A'$ 是[[MK181][双射函数]]

任取 $b_0\in B^*$ 定义 $g_1=\begin{cases}f^*(b,n)&b\ne b_0\\f^*(b,n-m)&b=b_0\land n\geq m\end{cases}$ 定义 $g_2=h(n),b=b_0\land n<m$

显然 $g_2$ 是 $B'=\{\left<b_0,0\right>,...,\left<b_0,m-1\right>\}$ 到 $A-A'$ 的[[MK181][双射函数]]

由于 $f^*$ 是[[MK176][单射]]，故易证 $g_1$ 亦为[[MK176][单射]]，且定义域为 $B^*-B'$ 值域与 $f^*$ 一致

根据[[MK178][蕴含双射]]易证 $f^*$ 是 $B^*\times\mathbb{N}$ 到 $A'$ 的[[MK181][双射]]，易证 $g_1$ 是 $B^*\times\mathbb{N}-B'$ 到 $A'$ 的[[MK181][双射]]

故根据[[MK183][并双射]]可得 $g=g_1\cup g_2$ 是 $B^*\times\mathbb{N}$ 到 $A$ 的[[MK181][双射函数]]

**** 定理3<<MK86>>

若 $A_i,i\in\mathbb{N}$ 满足：

（1） 均为无限集

（2） 对于任意 $i\in\mathbb{N}$ 有 $A_i$ 的最大[[MK35][基数]]为 $\kappa$

则 $\left|\bigcup_{i\in\mathbb{N}}A_i\right|=\kappa$

***** 证明

****** 定义 $\sigma:\bigcup_{i\in\mathbb{N}}A_i\to B_k\times\mathbb{N}$ 

对于任意 $a\in\bigcup_{i\in\mathbb{N}}A_i$ 必有 $A_{i_1},...,A_{i_n}$ 满足 $a\in A_{i_j}$ 且 $n\geq 1$ 则定义 $\sigma_{z}:\bigcup_{i\in\mathbb{N}}A_i\to \bigcup_{i\in\mathbb{N}}A_i\times\mathbb{N}$

满足 $\sigma_{z}(a)=\left<a,\min(i_1,...,i_n)\right>$ 进一步定义 $\sigma_z(a)=\left<\sigma_{z_1}(a),\sigma_{z_2}(a)\right>$ 其中 $\sigma_{z_1}(a)\in A_i,\sigma_{z_2}(a)\in\mathbb{N}$

若 $a\ne b$ 可得 $a=\sigma_{z_1}(a)\ne\sigma_{z_1}(b)=b$ 故 $\sigma_z$ 是[[MK176][单射]]

设 $k\in\mathbb{N}$ 满足 $|A_k|=\kappa$ 则对于任意 $A_i$ 均有 $|A_i|\leq|A_k|$ 根据[[MK29][等势]]可得有[[MK176][单射]] $\sigma_{i,k}:A_i\to A_k$

根据[[MK85][定理2]]可得存在 $B_k\subset A_k$ 满足 $|A_k|=|B_k\times\mathbb{N}|$ 故根据[[MK29][等势]]可得有[[MK181][双射]] $\sigma_k:A_k\to(B_k\times\mathbb{N})$

进一步定义 $\sigma_k(a)=\left<\sigma_{k_1}(a),\sigma_{k_2}(a)\right>$ 其中 $\sigma_{k_1}(a)\in A_k,\sigma_{k_2}(a)\in\mathbb{N}$

又根据[[MK98][定理2]]可得 $|\mathbb{N}\times\mathbb{N}|=|\mathbb{N}|$ 同理可得有[[MK181][双射]] $\sigma_n:(\mathbb{N}\times\mathbb{N})\to\mathbb{N}$

最终定义 $\sigma:\bigcup_{i\in\mathbb{N}}A_i\to B_k\times\mathbb{N}$ 为对于任意 $a\in\bigcup_{i\in\mathbb{N}}A_i$

有 $\sigma(a)=\left<\sigma_{k_1}\left(\sigma_{\sigma_{z_2}(a),k}\left(\sigma_{z_1}(a)\right)\right),\sigma_n\left(\sigma_{z_2}(a),\sigma_{k_2}\left(\sigma_{\sigma_{z_2}(a),k}\left(\sigma_{z_1}(a)\right)\right)\right)\right>$

****** $\sigma$ 是[[MK176][单射]]

易证 $\sigma:\bigcup_{i\in\mathbb{N}}A_i\to B_k\times\mathbb{N}$ 是[[MK175][函数]]

对于任意 $a\in\bigcup_{i\in\mathbb{N}}A_i,b\in\bigcup_{i\in\mathbb{N}}A_i,a\ne b$ 则根据 $\sigma_z$ 是[[MK176][单射]]可得 $\sigma_{z_1}(a)\ne\sigma_{z_1}(b)\lor\sigma_{z_2}(a)\ne\sigma_{z_2}(b)$

根据 $\sigma_z$ 定义可得若 $a\ne b$ 则必有 $\sigma_{z_1}(a)\ne\sigma_{z_1}(b)$ 

若有 $\sigma_{z_2}(a)\ne\sigma_{z_2}(b)$ 根据 $\sigma_n$ 是[[MK181][双射]]可得对于任意 $\{u,v\}\subset\mathbb{N}$ 均有 $\sigma_n(\sigma_{z_2}(a),u)\ne\sigma_n(\sigma_{z_2}(b),v)$

故有 $\sigma(a)\ne\sigma(b)$

若 $\sigma_{z_2}(a)=\sigma_{z_2}(b)$ ，根据 $\sigma_{\sigma_{z_2}(a),k}$ 是[[MK181][双射]]可得 $\sigma_{\sigma_{z_2}(a),k}(a)\ne\sigma_{\sigma_{z_2}(b),k}(b)$ 

根据 $\sigma_k$ 是[[MK181][双射]]可得 $\sigma_{k_1}\left(\sigma_{\sigma_{z_2}(a),k}\left(\sigma_{z_1}(a)\right)\right)\ne\sigma_{k_1}\left(\sigma_{\sigma_{z_2}(b),k}\left(\sigma_{z_1}(b)\right)\right)$

或 $\sigma_{k_2}\left(\sigma_{\sigma_{z_2}(a),k}\left(\sigma_{z_1}(a)\right)\right)\ne\sigma_{k_2}\left(\sigma_{\sigma_{z_2}(b),k}\left(\sigma_{z_1}(b)\right)\right)$


若后者成立，则根据 $\sigma_n$ 是[[MK181][双射]]可得对于任意 $\{u,v\}\subset\mathbb{N}$

均有 $\sigma_n\left(u,\sigma_{k_2}\left(\sigma_{\sigma_{z_2}(a),k}\sigma_{z_1}(a)\right)\right)\ne\sigma_n\left(v,\sigma_{k_2}\left(\sigma_{\sigma_{z_2}(b),k}\sigma_{z_1}(b)\right)\right)$ 即 $\sigma(a)\ne\sigma(b)$

若后者不成立，则必有前者成立，立即有 $\sigma(a)\ne\sigma(b)$

综上所述，对于任意 $a\in\bigcup_{i\in\mathbb{N}}A_i,b\in\bigcup_{i\in\mathbb{N}}A_i,a\ne b$ 有 $\sigma(a)\ne\sigma(b)$ 即 $\sigma$ 是[[MK176][单射]]

****** 证明结论

由于 $|B_k\times\mathbb{N}|=|A_k|$ 且 $\sigma$ 是[[MK176][单射]]，则根据[[MK29][等势]]可得 $\left|\bigcup_{i\in\mathbb{N}}A_i\right|\leq|A_k|$

又由于 $A_k\subset\bigcup_{i\in\mathbb{N}}A_i$ 根据[[MK33][定理7]]可得 $|A_k|\leq\left|\bigcup_{i\in\mathbb{N}}A_i\right|$

故根据[[MK34][伯恩斯坦定理]]可得 $\kappa=|A_k|=\left|\bigcup_{i\in\mathbb{N}}A_i\right|$ 

**** 定理4<<MK87>>

若 $A,B$ 均为[[MK83][无限集]]且有 $|A\cup B|=\kappa$ 以及 $|A|<\kappa$ ，则有 $|B|=\kappa$

***** 证明

假设 $|B|<\kappa$ 则定义 $|B|=\beta,|A|=\alpha$ 且 $\beta<\kappa,\alpha<\kappa$

则根据[[MK86][定理3]]可得 $|A\cup B|=\max(\alpha,\beta)<\kappa$ 与条件不符。故假设不成立

即有 $|B|=\kappa$

**** 定理5<<MK88>>

若 $X$ 是无限集，则有 $|X\times X|=|X|$

***** 证明

****** 定义[[MK143][偏序关系]] $\left<Y,\subset\right>$ 

定义

\begin{aligned}
\text{IsFunc}(f,A)=&((\forall x((x\in X)\rightarrow(\exists y(\left<x,y\right>\in f))))\land\\
&(\forall y_1(\forall y_2(((\left<x,y_1\right>\in f)\land(\left<x,y_2\right>\in f))\rightarrow(y_1=y_2))))\land\\
&(\forall x_1(\forall x_2((\{x_1,x_2\}\subset(B\times \mathbb{N}))\to(f(x_1)\ne f(x_2)))))\land\\
&(\forall y((y\in Y)\rightarrow(\exists x((x\in X)\land (\left<x,y\right>\in f)))))\land\\
&(\forall y(\forall x((\left<x,y\right>\in f)\to((x\in A)\land(y\in A\times A)))))
)
\end{aligned}

即 $f$ 是 $A$ 到 $A\times A$ 的[[MK181][双射函数]]的[[~/文档/note/数理逻辑/sllj.org::MK129][表达式]]，定义 $Y=\left\{f\big|A\subset X\land\text{IsFunc}(f,A)\right\}$

根据[[MK84][定理1]]可得存在 $C\in X$ 满足 $|C|=|\mathbb{N}|$ ，根据[[MK98][定理2]]易证 $|C\times C|=|C|$

根据[[MK29][等势]]定义可得存在[[MK181][双射函数]] $f_c:C\to C\times C$ ，即 $f_c\in Y$ ，故 $Y$ 非空

定义 $\left<Y,\subset\right>$ 显然为[[MK143][偏序关系]]

****** 任意 $\left<Y,\subset\right>$ 的[[MK153][链]]有[[MK145][上界]]

对于任意 $\left<Y,\subset\right>$ 的[[MK153][链]] $Y'\subset Y$

有对于任意 $\{f_1,f_2\}\in Y'$ 有 $((f_1\subset f_2)\lor (f_2\subset f_1))$ 则定义 $f^*=\bigcup_{f\in Y'}f,A^*=\bigcup_{f:A_f\to A_f\times A_f\land f\in Y'} A_f$

根据以下证明可得 $f^*:A^*\times A^*\to A^*$ 是[[MK181][双射]]，根据 $A^*$ 定义可得 $A^*\subset A$

综上所述可得 $f^*\in Y$ 且对于任意 $f\in Y'$ 有 $f\subset f^*$ ，即 $f^*$ 是 $Y'$ 的[[MK145][上界]]

******* $f^*$ 是[[MK175][函数]]

******** 任意 $a\in A^*$ 有 $b\in A^*\times A^*$ 满足 $\left<a,b\right>\in f^*$

对于任意 $a\in A^*$ 根据 $A^*$ 定义有 $f:A_f\to A_f\times A_f$ 满足 $f\in Y'$ 是[[MK175][函数]]

则存在 $b\in A_f\times A_f$ 满足 $\left<a,b\right>\in f$ ，则根据 $f^*$ 定义有 $\left<a,b\right>\in f^*$

又根据 $A^*$ 定义可得 $A_f\subset A^*$ 显然有 $b\in A_f\times A_f\subset A^*\times A^*$

综上所述，对于任意 $a\in A^*$ 有 $b\in A^*\times A^*$ 满足 $\left<a,b\right>\in f^*$

******** 任意 $\left<a,y_1\right>\in f^*,\left<a,y_2\right>\in f^*$ 有 $y_1=y_2$

任意 $\left<a,y_1\right>\in f^*,\left<a,y_2\right>\in f^*$ 根据 $f^*$ 定义有 $f_1\in Y',f_2\in Y'$

满足 $\left<a,y_1\right>\in f_1,\left<a,y_2\right>\in f_2$ ，又由于 $Y'$ 是[[MK153][链]]，故必有 $f_1\subset f_2$ 或 $f_2\subset f_1$ 。

若 $f_1\subset f_2$ ，则有 $\left<a,y_1\right>\in f_2,\left<a,y_2\right>\in f_2$ 由于 $f_2\in Y'\in Y$ 是[[MK175][函数]]，故 $y_1=y_2$

若 $f_2\subset f_1$ ，同理可证 $y_1=y_2$

******* $f^*$ 是[[MK176][单射]]

假设存在 $\{a,b\}\in A^*$ 是的 $f^*(a)=f^*(b)$ 则根据 $f^*$ 定义有 $f_1\in Y',f_2\in Y'$

满足 $\left<a,f^*(a)\right>\in f_1,\left<b,f^*(b)\right>\in f_2$ ，又由于 $Y'$ 是[[MK153][链]]，故必有 $f_1\subset f_2$ 或 $f_2\subset f_1$

若 $f_1\subset f_2$ ，则有 $\{\left<a,f^*(a)\right>,\left<b,f^*(b)\right>\}\subset f_2$

故有 $a\ne b$ 且 $f_2(a)=f_2(b)$ ，由于 $f_2\in Y$ 故可得 $f_2$ 是[[MK181][双射函数]]，故矛盾。

若 $f_2\subset f_1$ ，同理可证矛盾。故假设不成立，即任意 $\{a,b\}\in A^*$ 有 $f^*(a)\ne f^*(b)$ 即是[[MK176][单射]]

******* $f^*$ 是[[MK179][满射]]

对于任意 $b=\left<b_1,b_2\right>\in A^*\times A^*$ 根据定义有 $A_{f_1},A_{f_2}$ 满足 $b_1\in A_{f_1},b_2\in A_{f_2}$

以及有 $f_1:A_{f_1}\to A_{f_1}\times A_{f_1},f_2:A_{f_2}\to A_{f_2}\times A_{f_2}$ 均为[[MK181][双射]]且属于 $Y'$

由于 $Y'$ 是[[MK153][链]]，故必有 $f_1\subset f_2$ 或 $f_2\subset f_1$ ，不妨设 $f_1\subset f_2$ ，反之同理可证

由于 $f_1\in Y'\subset Y$ 是[[MK181][双射]]，故对于任意 $u\in A_{f_1}$ 均有 $v\in A_{f_1}\times A_{f_1}$ 满足 $\left<u,v\right>\in f_1\subset f_2$

即对于任意 $u\in A_{f_1}$ 均有 $f_2(u)=v$ 即 $f_2$ 的定义域包含 $A_{f_1}$ ，即 $A_{f_1}\subset A_{f_2}$

反之对于任意 $v\in A_{f_1}\times A_{f_1}$ 均有 $u\in A_{f_1}$ 满足 $\left<u,v\right>\in f_1\subset f_2$

即对于任意 $v\in A_{f_1}\times A_{f_1}$ 均有 $u\in A_{f_1}$ 满足 $f_2(u)=v$ 故 $f_2$ 的相包含 $A_{f_1}\times A_{f_1}$

即 $A_{f_1}\times A_{f_1}\subset A_{f_2}\times A_{f_2}$ 则有 $b=\left<b_1,b_2\right>\in A_{f_2}\times A_{f_2}$

又由于 $f_2\in Y'\subset Y$ 是[[MK181][双射]]，故存在 $a\in A_{f_2}\subset A^*$ 满足 $f_2(a)=b$

又根据 $f^*$ 定义可得 $f^*(a)=b$ 。

综上所述，对于任意 $b\in A^*\times A^*$ 均有 $a\in A^*$ 满足 $f^*(a)=b$ 即是[[MK179][满射]]

****** 证明结论

根据上一步证明以及以及[[MK162][佐恩引理]]可得存在 $\left<Y,\subset\right>$ 中的[[MK166][极大元]] $\bar{f}:\bar{A}\to\bar{A}\times\bar{A}$ 即有 $|\bar{A}|=|\bar{A}\times\bar{A}|$

假设 $|\bar{A}|<|X|$ 根据 $\bar{A}\cup(X-\bar{A})=X$ 可得 $|\bar{A}\cup(X-\bar{A})|=|X|$

又根据[[MK87][定理4]]可得 $|X-\bar{A}|=|X|$ ，由于 $|\bar{A}|<|X|=|X-\bar{A}|$ 根据[[MK29][等势]]可得存在[[MK176][单射]] $f_0:\bar{A}\to X-\bar{A}$

定义 $C=\left\{c\big|c\in X-\bar{A}\land\exists a((a\in\bar{A})\to(f_0(a)=c))\right\}$ 则根据[[MK178][蕴含双射]]可得 $f_1:\bar{A}\to C$ 是[[MK181][双射]]

即 $|C|=|\bar{A}|$ ，则定义 $D=(C\times C)\cup(\bar{A}\times C)\cup (C\times\bar{A})$ 

根据 $|C|=|\bar{A}|$ 以及 $|\bar{A}|=|\bar{A}\times\bar{A}|$ 易证 $|C\times C|=|\bar{A}\times C|=|C\times\bar{A}|=|C|$

又根据[[MK86][定理3]]可得 $|\bar{A}\cup C|=|(\bar{A}\times\bar{A})\cup(\bar{A}\times C)\cup(C\times\bar{A})\cup(C\times C)|=|(\bar{A}\cup C)\times(\bar{A}\cup C)|$

根据[[MK29][等势]]可得存在[[MK181][双射]] $f_2:\bar{A}\cup C\to(\bar{A}\cup C)\times(\bar{A}\cup C)$ 显然 $\bar{f}\subset f_2$ 且 $f_2\in Y$

与 $\bar{f}$ 是[[MK166][极大元]]矛盾，故假设不成立，即 $|\bar{A}|=|X|$ ，又根据 $|\bar{A}|=|\bar{A}\times\bar{A}|$ 可得 $|X\times X|=|X|$

*** 可数集<<MK89>>

根据[[MK55][自然数归纳定义]]所定义的自然数集合 $N$ ，若[[MK83][无限集]]与 $N$ [[MK29][等势]]，则称为可数集。

**** 推论

若 $A,B$ [[MK29][等势]]，则 $A$ 为可数集的充要条件是 $B$ 为可数集

***** 证明

必要条件，若 $B$ 为可数集，则存在[[MK181][双射函数]] $\Phi:N\rightarrow B$ ，又根据等势定义，存在双射函数 $\Psi:B\rightarrow A$

则根据[[MK182][双射传递]]，存在合成映射 $P:N\rightarrow A$ 亦为双射函数

故 $A$ 可数，同理可证充分

**** 定理

***** 定理0

[[MK82][有限集]]不是可数集

****** 证明

若存在[[MK181][双射函数]] $\sigma:\mathbb{N}\to A$ 其中 $A$ 为有限集且 $|A|=n$ 则集合可表述为 $A=\left\{a_1,...,a_n\right\}$

定义 $B=\left\{\sigma(i)\big|i\in\mathbb{N}\land i< k\right\}$ 由于双射，故 $\forall a\in\mathbb{N}\forall b\in\mathbb{N}\left(a\ne b\rightarrow\sigma(a)\ne\sigma(b)\right)$

故有 $|B|=k$ 即[[MK35][基数]]为 $k$ 且 $B\subset A$ 当 $k>n$ 时显然不成立。

***** 定理1<<MK90>>

任意[[MK83][无限集]]合至少包含一个可数子集

****** 证明

假设有无限集 $A$ 则定义 $B=\{A\}$ 根据[[MK82][有限集]]定义可知 $A\ne\varnothing$

故根据[[MK14][选择公理]]可得存在 $f:B\to A$ 使得 $f(A)\in A$

定义 $e_1=f(A)$ 定义 $A_1=A-e_1\subset A$ 为 $A$ 与 $e_1$ 的[[MK57][差]]，则有 $B_1 = \{A_1\}$ 

对于任意 $n\in\mathbb{N}$ 若存在 $A_n$ 则有 $B_n=\{A_n\}$ 此时若 $A_n=\varnothing$ 则有 $A=\{e_1,...,e_{n-1}\}$ 则为有限集

故同理根据选择公里存在 $f:B_n\to A_n$ 使得 $f(A_n)\in A_n$ 则定义 $e_n=f(A_n)\subset A$

综上所属：

（1） 存在 $e_1\in A$

（2） 对于任意 $n$ 若存在 $e_{n-1}$ 则存在 $e_n$

故有集合 $C=\{e_1,...,e_n,...\}$ 则对于任意 $n\in\mathbb{N}$ 定义映射 $f(n)=e_n$

显然是一一对应的[[MK181][双射函数]]，根据[[MK29][对等]]定义可得 $\mathbb{N}\sim C$ 且 $\forall e_i\in C\rightarrow e_i\in A$ 故有 $C\subset A$

***** 定理2<<MK91>>

可数集的任意无限子集仍是可数集

****** 证明

假设集合 $A$ [[MK89][可数]]，则根据[[MK29][对等]]有 $A\sim\mathbb{N}$

假设 $B\subset A$ 且为[[MK83][无限集]]，根据[[MK90][定理1]]其必定包含可数子集，定义为 $C\subset B$ ，则根据[[MK29][对等]]有 $C\sim\mathbb{N}$

根据[[MK30][定理]]对等是[[MK132][等价关系]]，故有[[MK129][传递性]]，故得 $C\sim A$ 

综上所述 $C\subset B\land C\sim A$ 根据[[MK35][基数]]定义可得 $|A|\leq |B|$

又因为 $B\subset A\land B\sim B$ 同理可得 $|B|\leq|A|$

故根据[[MK34][伯恩斯坦定理]]可得 $|A|=|B|$ 根据[[MK35][基数]]定义可得 $A\sim B$

同理根据等价关系传递性有 $B\sim A\sim\mathbb{N}$

****** 推论<<MK92>>

可数集的子集，要么是[[MK89][可数集]]，要么是[[MK82][有限集]]

***** 定理3<<MK330>>

若 $A$ 是[[MK89][可数集]]，则 $B=\left\{b\big|b\in\rho(A)\land |b|=n\right\}$ 亦是[[MK89][可数集]]

其中 $\rho(A)$ 是 $A$ 的[[MK20][幂集]]， $n\in\mathbb{N}$

****** 证明

根据[[MK88][定理5]]可得 $|A^n|=|A|$ 是[[MK89][可数集]]，其中 $A^n$ 是 $A$ 的 $n$ 次[[MK107][笛卡尔积]]

对于任意 $b=\{a_1,...,a_n\}\in B$ 根据[[MK105][有序组定义]]可定义 $g(b)=\left\{a\big|a\in A^n\land b\in a\right\}$ 

即 $A^n$ 中所有由 $\{a_1,...,a_n\}$ 组成的[[MK105][有序组]]，显然对于任意 $b\in B$ 有唯一 $c\subset A^n$ 满足 $g(b)=c$

故 $g$ 是[[MK175][函数]]，根据[[MK14][选择公理]]可得存在选择[[MK175][函数]] $f'$ 满足 $f'(g(b))\in g(b)$

最终定义 $f(b)=f'(g(b))$ 显然根据[[MK187][复合]]可得 $f$ 亦为[[MK175][函数]]

对于任意 $b_1\ne b_2$ 不妨设 $a^*\in b_1,a^*\not\in b_2$ 则根据[[MK105][有序组定义]]可得存在 $k_1\in f(b_1)$ 满足 $a^*\in k_1$

且不存在 $k_2\in f(b_2)$ 满足 $a^*\in k_2$ 则显然 $f(b_1)\ne f(b_2)$ 即 $f$ 是[[MK176][单射]]

即有 $|B|<|A^n|=|A|$ 显然 $B$ 是[[MK83][无限集]]，则根据[[MK90][定理1]]易证 $B$ 是[[MK89][可数集]]

*** 至多可数集<<MK93>>

即[[MK82][有限集]]和[[MK89][可数集]]的并集，即与正整数集子集对等

**** 定理<<MK94>>

***** 定理1<<MK95>>

至多可数个至多可数集的并，仍是至多可数集

即[[MK47][集合族]] $C_D$ 其中 $D$ 是[[MK48][指标集]]，集合 $C,D$ 均为至多可数集

则 $$\bigcup_{d\in D}C_d$$ 亦为至多可数集

****** 证明

******* 前提定义

定义 $d\in D$ 为指标集中某一元素，由于是至多可数集，故存在 $\sigma(d)=i\land i\in\mathbb{N}$ 

进一步定义 $C_i=C_{\sigma(d)}$ 故 $\bigcup_{d\in D}C_d=\bigcup_{i\in\{\sigma(d)|d\in D\}}C_i$

由于 $C_i$ 亦为至多可数集，故必有 $\sigma_i:C_i\to\mathbb{N}$ 则定义 $c_{ij}\in C_i$ 满足 $\sigma_i(c_{ij})=j$

仅证明 $D$ 以及 $C_d,d\in D$ 均为[[MK89][可数集]]，且 $C_d,d\in D$ 无交集的情况。

其他情况根据可视为该情况的子集，故根据[[MK92][推论]]可证得

******* 构建映射

定义 $$\alpha:\bigcup_{d\in D} C_d\to\mathbb{N}$$ 即 $$\alpha:\bigcup_{i\in\{\sigma(d)|d\in D\}}C_i\to\mathbb{N}$$

映射规则为 $\alpha(c_{ij})=\frac{i+j}{2}(i+j-1)-(j-1)$

******* 证明是函数

对于任意 $\{i,j\}\subset\mathbb{N}$ 均有 $\frac{i+j}{2}(i+j-1)-(j-1)$ 且唯一，故是[[MK175][函数]]

******* 证明[[MK176][单射]]

若不是单射，则存在 $\{i,j\}\ne\{i',j'\}$ 使得 $\alpha(c_{ij})-\alpha(c_{i'j'})=0$

若 $i+j=i'+j'$ 则有

\begin{aligned}
&\alpha(c_{ij})-\alpha(c_{i'j'})\\
=&\frac{1}{2}\left((i+j)^2-i-2j-(i'+j')^2+i'+2j'\right)\\
=&\frac{1}{2}\left(i'+j'-(i+j)+j'-j\right)\\
=&\frac{1}{2}\left(j'-j\right)\\
\end{aligned}

则有 $j=j'$ 又因为 $i+j=i'+j'$ 故有 $i=i'\land j=j'$ 与条件 $\{i,j\}\ne\{i',j'\}$ 不符

若 $i+j\ne i'+j'$ 则假设 $i+j>i'+j'$ 故有，反之同理 

\begin{aligned}
&\alpha(c_{ij})-\alpha(c_{i'j'})\\
=&\frac{1}{2}\left((i+j)^2-i-2j-(i'+j')^2+i'+2j'\right)\\
=&\frac{1}{2}\left([(i+j)^2-(i'+j')^2]-(i-i')-2(j-j')\right)\\
=&\frac{1}{2}\left((i+j-i'-j')(i+j+i'+j')-(i-i'+j-j')-(j-j')\right)\\
=&\frac{1}{2}\left((i+j-i'-j')(i+j+i'+j'-1)-(j-j')\right)\\
\end{aligned}

由于均为大于 $1$ 正整数且 $i+j>i'+j'$ ，故有 $i+j-i'-j'>1$

由于均为大于 $1$ 正整数，则有 $i+i'+j+j'-1>j+j'>j-j'$

故有 $(i+j-i'-j')(i+j+i'+j'-1)>i+j+i'+j'-1>j-j'$

则有 $\alpha(c_{ij})-\alpha(c_{i'j'})>0$

综上所述，对于任意 $\{i,j\}\ne\{i',j'\}$ 均有 $\alpha(c_{ij})\ne\alpha(c_{i'j'})$ 即单射

******* 证明[[MK179][满射]]

根据高斯公式可得 $\frac{(i+j)(i+j-1)}{2}=\sum_{k=1}^{i+j-1}k$ 则对于任意 $n\in\mathbb{N}$ 存在 $l$ 使得 $\sum_{k=1}^{l-2}k\leq n\land\sum_{k=1}^{l-1}k>n$

故对于该正整数 $n$ 取 $i+j=l$ 以及 $j=\sum_{k=1}^{l-1}k-n+1$ 

由于 $\sum_{k=1}^{l-1}k-\sum_{k=1}^{l-2}k=l-1$ 故有 $0\leq\sum_{k=1}^{l-1}k-n<l-1$ 则 $0\leq j-1<i+j-1$

故有 $1\leq j<i+j$ 满足均为大于等于 $1$ 的正整数条件，则有 

\begin{aligned}
\alpha(c_{ij})=&\frac{i+j}{2}(i+j-1)-(j-1)\\
=&\sum_{k=1}^{l-1}k-\left(\sum_{k=1}^{l-1}k-n+1-1\right)\\
=&n
\end{aligned}

故对于任意 $n\in\mathbb{N}$ 均有 $\{i>0,j>0\}\subset\mathbb{N}$ 使得 $\alpha(c_{ij})=n$

******* 结论

根据上述证明，存在[[MK181][双射函数]] $$\alpha:\bigcup_{d\in D} C_d\to\mathbb{N}$$ ，故根据[[MK29][定义]]可得 $\bigcup_{d\in D} C_d\sim\mathbb{N}$

进一步根据[[MK89][可数集]]定义可得 $\bigcup_{d\in D} C_d$ 是可数集。

由于其他情况均可视为可数集的子集，根据[[MK92][推论]]可得要么是[[MK89][可数集]]，要么是[[MK82][有限集]]

综上所述 $\bigcup_{d\in D} C_d$ 是至多可数集 

****** 推论1<<MK96>>

有理数集合是可数集

******* 证明

定义 $A_i=\left\{\frac{n}{i}\big| n\in\mathbb{N}\right\}$ 其中 $i\in\mathbb{N}$ 则定义[[MK47][集合族]] $A_\mathbb{N}$ 

其中显然 $|A_i|=|\mathbb{N}|$ 故 $A_i,\mathbb{N}$ 均为[[MK89][可数集]]，即属于[[MK93][至多可数集]]，故至多可数个至多可数集的并，仍是至多可数集

因为所有有理数均定义为 $\frac{p}{q},\{p,q\}\subset\mathbb{N}$ 故正有理数集合是至多可数集，同理可正负有理数集合为至多可数集

再次使用定理可得有理数集合为至多可数集。显然有理数结合不为[[MK82][有限集]]，则正有理数集合为[[MK89][可数集]]

****** 推论2<<MK97>>

两个至多可数集的[[MK107][直积]]仍是可数集

******* 证明

定义 $A,B$ 是至多可数集，对于任意 $a\in A$ 定义 $C_a=\left\{<a,b>\big|b\in B\right\}$

进而定义 $Z=\bigcup_{a\in A}C_a$ 易证 $Z=A\times B$

根据定理可得 $Z$ 是至多可数集，即 $A\times B$ 亦为至多可数集

***** 定理2<<MK98>>

有限个至多可数集的[[MK107][直积]]仍是至多可数集

****** 证明

定义 $A=\left\{A_i\big|i\in\mathbb{N}\land i\leq n \land n\in\mathbb{N}\right\}$ 其中 $A_i$ 是[[MK93][至多可数集]]，归纳法证明：

（1） 当 $n=1$ 时即 $A_1$ 本身，显然成立

（2） 当 $n-1$ 成立时，由于 $A_n$ 亦为至多可数集，则必有[[MK181][双射函数]] $\sigma:A_n\to\mathbb{N}$

     定义满足 $a\in A_n\land\sigma(a)=i$ 的元素为 $a_i$ 则有 $A_n=\{a_1,a_2,...,a_n,...\}$

     定义 $A^*=A_1\times...\times A_{n-1}$ 定义 $A_i^*=A_1\times...\times A_{n-1}\times\{a_i\}$ 

     后者是前 $n-1$ 个集合的[[MK107][直积]]的结果与 $\{a_i\}$ 的再次直积，显然 $A^*_i\sim A^*$ [[MK29][对等]]，故根据假设 $A^*_i$ 为至多可数集

     根据[[MK108][分配率]]可得 $A^*\times A_n=A^*\times\bigcup \{a_i\}=\bigcup A^*\times\{a_i\}=\bigcup A^*_i$ 

     由于 $A_n$ 是至多可数集，故根据[[MK95][定理1]]可得 $A^*\times A_n$ 亦为至多可数集

（3） 综上所述，当 $n$ 有限时 $A_1\times...\times A_n$ 为至多可数集

***** 定理3

代数数的全体是可数集

代数数为整系数多项式的[[~/文档/note/高等代数/Algb-4-Multi-equ.org][因式、可约与根-根]]，若不是，则定义为超越数（例如 $\pi$ ）

****** 证明

******* 证明多项式集合可数

定义 $A_n=\left\{f(x)\big|f(x)=\sum_{i=0}^na_ix^i\land i\in\mathbb{N}\right\}$ 是全体 $n$ 此整系数多项式集合

定义 $\sigma:A_n\to\mathbb{N}^n$ 规则为 $\sigma(f(x))=<a_1,...,a_n>$ 

定义 $g(x)=\sum_{i=0}^nb_ix^i$ 根据[[~/文档/note/高等代数/Algb-4-Multi-equ.org][一元多项式-一元多项式运算-相等]]可得若 $f(x)\ne g(x)$ 则至少有一组 $b_k\ne a_k$

根据[[MK105][有序组]]定义可得 $<a_1,...,a_{k-1},a_k,a_{k+1},...,a_n>\ne<a_1,...,a_{k-1},b_k,a_{k+1},...,a_n>$ 故[[MK176][单射]]

则根据单射定义，取 $K=\mathbb{N}^n-\left\{k\big|k\in\mathbb{N}^n\land \lnot\exists f(x)(f(x)\in A_n\land \sigma(f(x))=k)\right\}$ 

即去除 $\mathbb{N}^n$ 中没有原相的元素，则显然 $\sigma':A_n\to K$ 是[[MK181][双射]]且 $K\subset\mathbb{N}^n$ 

显然 $K$ 是无限集，故根据[[MK91][定理2]]可得 $K$ 是[[MK89][可数集]]，故 $A_n$ 亦为可数集

******* 证明根的集合

定义 $B_n$ 是全体 $f(x)\in A_n$ 的根的集合，则定义集合 $A_n\times\{1,2,...,n\}$ 

对于每一个 $f(x)\in A_n$ 定义 $<f(x),k>$ 对应 $f(x)$ 的第 $k$ 个根，显然 $k\in B_n$

则有映射 $\sigma:A_n\times\{1,2,...,n\}\to B_n$ 显然根据定义 $B_n$ 中的元素必为某个 $f(x)\in A_n$ 的根

进一步根据[[~/文档/note/高等代数/Algb-4-Multi-equ.org][因式、可约与根-根-根的个数]]可知 $f(x)$ 至多有 $n$ 个根，故 $\sigma$ 是[[MK179][满射]]

定义[[MK47][集合族]] $K=\left\{K_b\big|b\in B_n\right\}$ 其中 $K_b=\left\{a\big|\sigma(a)=b\right\}$

根据[[MK14][选择公理]]存在选择函数 $f(K_b)\in K_b$ 则定义 $K'=\left\{f(K_b)\big|K_b\in K\right\}$

则映射 $\sigma':K'\to B_n$ 是[[MK181][双射]]故根据[[MK29][定义]]可得 $K'\sim B_n$ 显然 $K'$ 是无限集且 $K'\subset A_n\times\{1,2,...,n\}$

由于 $\{1,2,...,n\}$ 是有限集，故是至多可数集。根据定理2可得 $A_n\times\{1,2,...,n\}$ 亦为至多可数集

显然 $K'$ 是[[MK83][无限集]]，故根据[[MK91][定理2]]可得 $K'$ 是[[MK89][可数集]]，故根据[[MK30][对等传递性]] $B_n$ 亦为可数集

显然所有代数数的集合可写为 $\bigcup_{i=1}^\infty B_i$ 根据[[MK95][定理1]]可得其为至多可数集

显然 $\bigcup_{i=1}^\infty B_i$ 是[[MK83][无限集]]故根据[[MK93][至多可数集定义]]代数数全体为可数集

*** 不可数集<<MK99>>

若[[MK83][无限集]]不是[[MK89][可数集]]，则称为不可数集

**** 推论<<MK100>>

若 $A,B$ [[MK29][等势]]，则 $A$ 为不可数集的充要条件是 $B$ 为不可数集

***** 证明

必要条件，当 $B$ 不可数时，假设 $A$ 可数。此时存在[[MK181][双射函数]] $\Phi:N\rightarrow A$ 

又根据等势定义，存在双射函数 $\Psi:B\rightarrow A$ 根据[[MK188][逆函数]]可得存在逆函数 $\Psi^{-1}:A\rightarrow B$ 

且 $\Psi^{-1}$ 亦为双射函数。则根据[[MK182][双射传递]]存在合成映射 $P:N\rightarrow B$ 亦为双射函数，则 $B$ 可数，推出矛盾。

故 $B$ 不可数时 $A$ 亦不可数。

充分条件同理。

*** 相关推论

**** $(0,1)$ 为不可数集

假设可数，则 $(0,1)$ 中的数与[[MK55][自然数]]一一对应，故有：

\begin{aligned}
&1\rightarrow0.a_{11}a_{12}...\\
&2\rightarrow0.a_{21}a_{22}...\\
&...\\
&n\rightarrow0.a_{n1}a_{n2}...\\
&...\\
\end{aligned}

其中 $a_{ij}\in\left\{x\big|x\in N\land x\leq 9\right\}$ 是对应的第 $i$ 个数小数位 $j$ 为上的数字

则取 $B=0.b_1b_2...\a$ 同理 $b_j\in\left\{x\big|x\in N\land x\leq 9\right\}$ 且 $b_i\ne a_{ii}$

可以看到，纵然序列无限， $B$ 任然不在序列当中

且 $B\in(0,1)$ 故与集合与[[MK55][自然数]]一一对应矛盾。故不为[[MK29][等势]]，根据[[MK89][定义]]不可数。

**** $[0,1]$ 为不可数集

定义映射 $f:(0,1)\rightarrow[0,1]$ 为 $f(x)=\begin{cases}0&x=\frac{1}{2}\\1&x=\frac{1}{4}\\\frac{1}{2^n}&x=\frac{1}{2^{n+2}},n=3,4,...\\x&x\ne\frac{1}{2^n}\end{cases}$ 

逆函数为 $f^{-1}(y)=\begin{cases}\frac{1}{2}&y=0\\\frac{1}{4}&y=1\\\frac{1}{2^{n+2}}&y=\frac{1}{2^n},n=3,4,...\\y&y\ne\frac{1}{2^n},0,1\end{cases}$ 

故有对于任意 $x\in(0,1)$ 都有唯一对应的 $f(x)\in [0,1]$ ，

对于任意 $y\in[0,1]$ 均有唯一对应的 $x\in(0,1)$ 使得 $x=f^{-1}(y)$

故 $f$ 为[[MK181][双射函数]]，即 $(0,1)$ 与 $[0,1]$ 等势。根据[[MK100][推论]]可得 $[0,1]$ 不可数。

***** 推论

同理可证 $[0,1),(0,1]$ 亦不可数

**** 任意实数区间均不可数<<MK101>>

对于任意区间 $(a,b),[a,b],[a,b),(a,b]$ 可由函数 $f(x)=(b-a)x\ \ x\in(0,1),[0,1],[0,1),(0,1]$ 映射。

对于整个实数区间，可由函数 $f(x)=\tan(x)$ 映射。

对于半封闭区间（例如 $[a,\infty)$ ），可由分段函数映射。

** 自然数

定义自然数集合 $\mathbb{N}$ 满足 $\mathbb{N}\in Inf\land W(\mathbb{N})=\mathbb{N}$ 即满足[[MK10][无穷公理]]以及[[MK102][ $W$ 运算]]后是本身

根据[[MK104][定理]]中结论（3）可得 $\mathbb{N}$ 唯一，进一步做如下定义

\begin{aligned}
&0=\varnothing\\
&1=0\cup\{0\}=\{\varnothing\}\\
&2=1\cup\{1\}=\{\varnothing\}\cup\{\{\varnothing\}\}=\{\varnothing,\{\varnothing\}\}\\
&...
\end{aligned}

即 $n\in\mathbb{N}=n-1\cup\{n-1\}$

*** $W$ 运算<<MK102>>

若 $u\in Inf$ 满足[[MK10][无穷公理]]，则定义 $W(u)=\left\{a\big|a\in u\land \forall V(V\in Inf\rightarrow a \in V)\right\}$

**** 性质<<MK103>>

对于任意 $u\in Inf$ 有 $W(u)=\bigcap_{V\in Inf} V$

***** 证明

对于任意 $u\in Inf$ 可得 $W(u)=\left\{a\big|a\in u\land \forall V(V\in Inf\rightarrow a \in V)\right\}$

则若 $a\in W(u)$ 则若存在 $V\in Inf$ 则对于任意满足条件的 $V$ 有 $a\in V$ 。又由于[[MK10][无穷公理]]可得 $Inf\ne\varnothing$

故 $a\in \bigcap_{V\in Inf} V$ 故有 $W(u)\subset\bigcap_{V\in Inf} V$

对于任意 $b\in\bigcap_{V\in Inf} V$ 由于 $u\in Inf$ 则有 $b\in u$ 且满足对于任意 $V\in Inf$ 均有 $b\in V$

故有 $\bigcap_{V\in Inf} V\subset W(u)$ ，根据[[MK16][自反性]]有 $W(u)=\bigcap_{V\in Inf} V$

**** 定理<<MK104>>

（1） 若 $u\in Inf$ 则 $W(u)\in Inf$

（2） 若 $\{u_1,u_2\}\subset Inf$ 则 $W(u_1)=W(u_2)$

（3） 若 $u\in Inf\land W(u)=u$ 则 $u$ 唯一

***** 证明

****** 证明（1）

根据[[MK103][性质]]可得 $W(u)=\bigcap_{V\in Inf} V$ 根据[[MK10][无穷公理]]定义可得对于任意 $A\in Inf$

有 $\varnothing\in A$ 故可得 $\varnothing\in \bigcap_{V\in Inf} V= W(u)$

对于任意 $x\in A$ 均有 $x\cup\{x\}\in A$ 故对于任意 $x\in\bigcap_{V\in Inf} V$ 有 $x\cup\{x\}\in\bigcap_{V\in Inf} V$

综上所述 $\bigcap_{V\in Inf} V$ 以满足[[MK10][无穷公理]]，则有 $W(u)=\bigcap_{V\in Inf} V\in Inf$

****** 证明（2）

根据[[MK103][性质]]可得 $W(u_1)=\bigcap_{V\in Inf} V=W(u_2)$ 

****** 证明（3）

根据[[MK103][性质]]可得任意 $u\in Inf$ 均有 $W(u)=\bigcap_{V\in Inf} V$ 且根据（1）有 $\bigcap_{V\in Inf} V\in Inf$

故当且仅当 $u=\bigcap_{V\in Inf} V$ 时有 $u\in Inf\land W(u)=u$ 故唯一
 
* 关系与函数

** 基本定义

*** 有序组<<MK105>>

$n$ 元有序组定义为：

（1） 当 $n=2$ 时 $\left<a_1,a_2\right>=\left\{\{a_1\},\{a_1,a_2\}\right\}$

（2） 当 $n>2$ 时 $\left<a_1,...a_n\right>=\left<\left<a_1,...,a_{n-1}\right>,a_n\right>$

进一步简化表达可有 $a_1a_2...a_n=\left<a_1,a_2,...,a_n\right>$

对于任意有序组 $s=\left<a_1,a_2,...,a_n\right>$ 定义 $s[i]=a_i$

**** 定理<<MK106>>

对于 $n$ 元有序数组 $<a_1,...,a_n>=<b_1,...,b_n>$ 当且仅当 $a_i=b_i,1\leq i\leq n$

***** 证明

******  $n=2$ 时

当 $n=2$ 时 $<a_1,a_2>=\left\{\{a_1\},\{a_1,a_2\}\right\},<b_1,b_2>=\left\{\{b_1\},\{b_1,b_2\}\right\}$

必要性显然，下面证充分性：

根据[[MK64][相同集合族广义交并]]对集合求广义交有 $\left\{\{a_1\},\{a_1,a_2\}\right\}=\left\{\{b_1\},\{b_1,b_2\}\right\}\rightarrow \{a_1\}=\{b_1\}\rightarrow a_1=b_1$

同理对集合求广义并由 $\{a_1,a_2\}=\{b_1,b_2\}$ 又由于 $u=v$ 故有 $a_2=b_2$

******  $n>2$ 时

假设 $<a_1,...,a_{n-1}>=<b_1,...,b_{n-1}>$ 的充要条件是 $a_i=b_i,1\leq i\leq n-1$

显然，当 $a_i=b_i,1\leq i\leq n$ 时 $<a_1,...,a_{n-1}>=<b_1,...,b_{n-1}>$

下面证明充分性：

定义 $<a_1,...,a_{n-1}>=u,<b_1,...,b_{n-1}>=v$ 则有 

\begin{aligned}
<a_1,...a_n>&=<<a_1,...,a_{n-1}>,a_n>=<u,a_{n}>\\
<b_1,...,b_n>&=<v,b_n>
\end{aligned}

若 $<a_1,...,a_n>=<b_1,...,b_n>\rightarrow <u,a_n>=<v,b_n>\rightarrow \left\{\{u\},\{u,a_n\}\right\}=\left\{\{v\},\{v,b_2\}\right\}$

根据[[MK64][相同集合族广义交并]]对集合求广义交有 $\left\{\{u\},\{u,a_n\}\right\}=\left\{\{v\},\{v,b_n\}\right\}\rightarrow \{u\}=\{v\}\rightarrow u=v$

根据前提假设 $u,v$ 均为 $n-1$ 元有序组，故有 $u=v\rightarrow a_i=b_i1\leq i\leq n-1$

同理对集合求广义并由 $\{u,a_n\}=\{v,b_n\}$ 又由于 $u=v$ 故有 $a_n=b_n$

*** 笛卡尔积/直积<<MK107>>

**** 有限个集合的笛卡尔积

当个集合做笛卡尔积时定义为 $A_1\times A_2=\left\{<u,v>\big|u\in A_1\land v\in A_2\right\}$ 记作 $A_1\times A_2$

多个结合做笛卡尔积时 $A_1\times...\times A_n=(A_1\times...\times A_{n-1})\times A_n$ 

集合 $A$ 对自己做 $n$ 次笛卡尔积运算可记作 $A^n=A\times...\times A$

***** 性质

****** 空集

\begin{aligned}
A\times\varnothing=\varnothing\times A=\varnothing
\end{aligned}

******* 证明

根据[[MK107][定义]]可得 $A\times\varnothing=\left\{<x,y>\big|x\in A\land y\in\varnothing\right\}$ 由于 $y\in\varnothing$ 永假

故有 $\forall x(x\in A\times\varnothing)$ 永假，故 $A\times\varnothing=\varnothing$

****** 分配率<<MK108>>

\begin{aligned}
A\times(B\cup C)&=(A\times B)\cup(A\times C)\\
A\times(B\cap C)&=(A\times B)\cap(A\times C)\\
A\times(B-C)&=(A\times B)-(A\times C)\\
\left(\bigcup_{n=1}^\infty I_n\right)\times\left(\bigcup_{n=1}^\infty I'_n\right)&=\bigcup_{i=1}^\infty\left(\bigcup_{j=1}^\infty I_i\times I'_j\right)\\
\end{aligned}

******* 证明

仅证以下，其他类似

（1） $A\times(B\cup C)=(A\times B)\cup(A\times C)$

（2） $\left(\bigcup_{n=1}^\infty I_n\right)\times\left(\bigcup_{n=1}^\infty I'_n\right)=\bigcup_{i=1}^\infty\left(\bigcup_{j=1}^\infty I_i\times I'_j\right)$

******** （1）

对于任意 $<x,y>$ 有

\begin{aligned}
&<x,y>\in A\times(B\cup C)\\
{|\!\!\!=\!\!\!|}&x\in A\land y\in (B\cup C)\\
{|\!\!\!=\!\!\!|}&x\in A\land (y\in B\lor y\in C)\\
{|\!\!\!=\!\!\!|}&(x\in A\land y\in B)\lor(x\in A\land y\in C)\\
{|\!\!\!=\!\!\!|}&(<x,y>\in A\times B)\lor(<x,y>\in A\times C)\\
{|\!\!\!=\!\!\!|}&<x,y>\in(A\times B)\cup(A\times C)\\
\end{aligned}

******** （2）

对于任意 $<x,y>\in\left(\bigcup_{n=1}^\infty I_n\right)\times\left(\bigcup_{n=1}^\infty I'_n\right)$ 可得 $x\in\bigcup_{n=1}^\infty I_n\land y\in \bigcup_{n=1}^\infty I'_n$

即等价于存在 $\{i,j\}\subset\mathbb{N}$ 满足 $x\in I_i\land y\in I'_j$ 即等价于 $<x,y>\in I_i\times I'_j$

则有 $x\in\bigcup_{i=1}^\infty\left(\bigcup_{j=1}^\infty I_i\times I'_j\right)$ 则有 $\left(\bigcup_{n=1}^\infty I_n\right)\times\left(\bigcup_{n=1}^\infty I'_n\right)\subset\bigcup_{i=1}^\infty\left(\bigcup_{j=1}^\infty I_i\times I'_j\right)$

同理易证 $\left(\bigcup_{n=1}^\infty I_n\right)\times\left(\bigcup_{n=1}^\infty I'_n\right)\supset\bigcup_{i=1}^\infty\left(\bigcup_{j=1}^\infty I_i\times I'_j\right)$

则根据[[MK16][自反性]]可得 $\left(\bigcup_{n=1}^\infty I_n\right)\times\left(\bigcup_{n=1}^\infty I'_n\right)=\bigcup_{i=1}^\infty\left(\bigcup_{j=1}^\infty I_i\times I'_j\right)$

****** 有限集基数

若 $A_1,...,A_n$ 为非空集合，则有 $|A_1\times...\times A_n|=\prod_{i=1}^n|A_i|$

****** 有无限集基数

若 $A_N$ 为非空[[MK47][集合族]]，其中 $N$ 为[[MK89][至多可数集]]，则有其笛卡尔积 $\left|\prod_{i\in N}A_i\right|\geq\max(|A_i|),i=1,2,...,n$

******* 证明

不妨设 $A_k$ 为其中基数最大的集合，由于非空，故乘积必包含对于任意 $a\in A_k$ 展开

对于给定的 $a\in A$ 定义 $\overline{a}$ 为直积有序组中第 $k$ 位是 $a$ 的所有元素的集合

则根据[[MK14][选择公理]]可得存在选择函数 $f:\bigcup_{a\in A_k}\{\overline{a}\}\to \bigcup_{a\in A_k}\overline{a}$ 且有 $\bigcup_{a\in A_k}\overline{a}\subset A_1\times...\times A_n$

故定义函数 $\sigma:\bigcup_{a\in A_k}\left\{f\left(\{\overline{a}\}\right)\right\}\to A_k$ 由于对于任意 $a$ 均存在 $\overline{a}$ 则有 $f\left(\{\overline{a}\}\right)$ 则为[[MK179][满射]]

对于 $b\in A_k\land b\ne a$ 必定 $\overline{b}$ 中有序组第 $k$ 位是 $b$ ，则根据[[MK105][有序组]]定义以及[[MK2][外延公理]]显然有序组不想等。

故为[[MK176][单射]]，即 $\sigma$ 是双射。则根据[[MK35][基数]]定义 $A_k$ 与 $A_1\times...\times A_n$ 子集对等，故有 $|A_k|\leq|A_1\times...\times A_n|$

****** 基数保序

若 $|A_I|\leq|B_I|$ 其中 $I$ 为[[MK89][至多可数集]]，则有 $\left|\prod_{i\in I}A_i\right|\leq\left|\prod_{i\in I}B_i\right|$

******* 证明

由于 $|A_I|\leq|B_I|$ 则根据[[MK178][蕴含双射]]即[[MK35][基数]]定义可知存在单射 $\sigma_i:A_i\to B_i$

则对于任意 $<a_1,a_2,...>\in\prod_{i\in I}A_i$ 则存在 $<\sigma_1(a_1),\sigma_2(a_2),...>\in\prod_{i\in I}B_i$

故同理根据蕴含双射以及基数定义可得 $\left|\prod_{i\in I}A_i\right|\leq\left|\prod_{i\in I}B_i\right|$

****** 直积与补集<<MK109>>

若 $A\subset X,B\subset Y$ 其中 $X,Y$ 分别为 $A,B$ 的全集

则有 $X\times B^c\cup A^c\times Y=(A\times B)^c$

******* 证明

若 $<x,y>\in (A\times B)^c$ 等价于 $<x,y>\not\in A\times B$ 根据直积定义可得等价于 $x\not\in A\lor y\not\in B$

若 $<x,y>\in X\times B^c\cup A^c\times Y$ 则等价于 $(x\in X\land y\not\in B)\lor(x\not\in A\land y\in Y)$

由于 $X,Y$ 是全集，即必有 $x\in X\land y\in Y$ 故有条件等价于 $x\not\in A\lor y\not\in B$

****** 直积与差<<MK110>>

若 $A_1\subset X,A_2\subset X,B_1\subset Y,B_2\subset Y$ 其中 $X,Y$ 分别为 $A_1,A_2,B_1,B_2$ 的全集

则有 $(A_1\times B_1)-(A_2\times B_2)=A_1\times(B_1-B_2)\cap(A_1-A_2)\times B_1$

******* 证明

若 $<x,y>\in(A_1\times B_1)-(A_2\times B_2)$ 即等价于 $<x,y>\in A_1\times B_1\land<x,y>\not\in A_2\times B_2$

进一步等价于 $(x\in A_1\land y\in B_1)\land\lnot(x\in A_2\land y\in B_2)$

根据[[~/文档/note/数理逻辑/sllj.org::MK186][德摩根律]]、[[~/文档/note/数理逻辑/sllj.org::MK47][分配率]]以及[[~/文档/note/数理逻辑/sllj.org::MK45][交换律]]

\begin{aligned}
&(x\in A_1\land y\in B_1)\land\lnot(x\in A_2\land y\in B_2)\\
{|\!\!\!=\!\!\!|}&(x\in A_1\land y\in B_1)\land(x\not\in A_2\lor y\not\in B_2)\\
{|\!\!\!=\!\!\!|}&((x\in A_1\land y\in B_1)\land x\not\in A_2)\lor((x\in A_1\land y\in B_1)\land y\not\in B_2)\\
{|\!\!\!=\!\!\!|}&(x\in (A_1-A_2)\land y\in B_1)\lor(x\in A_1\land y\in(B_1-B_2))\\
{|\!\!\!=\!\!\!|}&<x,y>\in(A_1-A_2)\times B_1\cup A_1\times(B_1-B_2)
\end{aligned}

**** 笛卡尔积的函数表示

设 $A=\left\{A_x\big|x\in X\right\},A_x\ne\varnothing$ 其中 $x$ 为[[MK99][不可数]]的[[MK48][指标集]]时 $A$ 中所有元素的笛卡尔积记为 $\prod_{x\in X} A_x$

由于 $X$ [[MK99][不可数]]，故 $\prod_{x\in X} A_x$ 不可列，不是[[MK105][有序组]]。

由于对于任意 $a\in\prod_{x\in X} A_x$ 其本质为表述对于每一个 $x$ 从 $A_x$ 中抽取一个元素

故可表述为[[MK175][函数]] $f:X\to\bigcup_{x\in X}A_x$ 满足 $f(x)\in A_x$ 显然根据[[MK14][选择公理]] $f$ 存在，即为选择函数

则 $\prod_{x\in X} A_x$ 为所有 $f:X\to A$ 的[[MK14][选择函数]]的集合

** 二元关系<<MK111>>

若 $R\subset A\times B$ 则称 $R$ 为集合 $A,B$ 上的二元关系

若 $<x,y>\in R$ 则记作 $xRy$ 其中 $<x,y>$ 为[[MK105][有序组]]

*** 特殊的关系

空关系： $\varnothing\subset A\times B$ 即 $R=\varnothing$

全关系<<MK112>>： $A\times B$

相等关系<<MK113>>： $E_A=\left\{<x,x>\big|x\in A\right\}$

*** 关系的相关概念

定义 $R\subset A\times B$ 则 $R$ 的：

定义域为 $Dom(R)=\left\{x\big|x\in A\land\exists y(<x,y>\in R)\right\}$

值域为 $Ran(R)=\left\{y\big|y\in B\land\exists x(<x,y>\in R)\right\}$

前域为 $A$

陪域为 $B$

*** 二元关系的矩阵表示<<MK114>>

若 $R\subset A\times B$ 且 $A=\{a_1,...,a_n\},B=\{b_1,...,b_m\}$

则定义关系矩阵 $M_{ij},1\leq i\leq n,1\leq j\leq m$ 其中：

$m_{ij}=0$ 当且仅当 $<a_i,b_j>\not\in R$ 即 $\lnot a_iRb_j$

$m_{ij}>0$ 当且仅当 $<a_i,b_j>\in R$ 即 $a_iRb_j$

*** 关系的运算

**** 关系基本运算

***** 定义

若 $R,S\subset A\times B$ 其中 $R,S$ 分别有关系矩阵 $R_{ij}=\{r_{ij}\},S_{ij}=\{s_{ij}\}$ 则：

****** 并 

$R\cup S=\left\{<x,y>\big|xRy\lor xSy\right\}$

关系矩阵为 $M=\{r_{ij}\lor s_{ij}\}$

****** 交 

$R\cap S=\left\{<x,y>\big|xRy\land xSy\right\}$

关系矩阵为 $M=\{r_{ij}\land s_{ij}\}$

****** 差 <<MK115>>

$R-S=\left\{<x,y>\big|xRy\land\lnot xSy\right\}$

关系矩阵为 $M=\{r_{ij}\land \lnot s_{ij}\}$

****** 补<<MK116>>

$\overline{R}=A\times B-R=\left\{<x,y>\big|\lnot xRy\right\}$

关系矩阵为 $M=\{\lnot r_{ij}\}$

****** 逆<<MK117>>

$R^{-1}=\left\{<y,x>\big|xR^{-1}y\right\}$

关系矩阵为 $M=R_{ij}^T$ 为 $R_{ij}$ 的转置

***** 性质

若 $R,S\subset A\times B$ 其中 $R,S$ 分别有关系矩阵 $R_{ij}=\{r_{ij}\},S_{ij}=\{s_{ij}\}$ 则：

****** 性质1

$(R^{-1})^{-1}=R$

******* 证明

根据[[MK117][逆]]的定义以及[[MK111][关系定义]]

\begin{aligned}
&<x,y>\in (R^{-1})^{-1}\\
{|\!\!\!=\!\!\!|}&<y,x>\in R^{-1}\\
{|\!\!\!=\!\!\!|}&<x,y>\in R\\
\end{aligned}

****** 性质2

$\overline{R^{-1}}=\left(\overline{R}\right)^{-1}$

******* 证明

根据[[MK114][矩阵表示]]，[[MK117][逆]]以及[[MK116][补]]的定义

\begin{aligned}
&<x,y>\in \overline{R^{-1}}\\
{|\!\!\!=\!\!\!|}&<x,y>\not\in R^{-1}\\
{|\!\!\!=\!\!\!|}&<y,x>\not\in R\\
{|\!\!\!=\!\!\!|}&<y,x>\in \overline{R}\\
{|\!\!\!=\!\!\!|}&<x,y>\in \left(\overline{R}\right)^{-1}\\
\end{aligned}

****** 性质3

\begin{aligned}
(R\cup S)^{-1}&=R^{-1}\cup S^{-1}\\
(R\cap S)^{-1}&=R^{-1}\cap S^{-1}\\
(R-S)^{-1}&=R^{-1}-S^{-1}\\
\end{aligned}

******* 证明

仅证 $(R-S)^{-1}=R^{-1}-S^{-1}$ 其余同理

根据[[MK114][矩阵表示]]，[[MK117][逆]]以及[[MK115][差]]的定义：

\begin{aligned}
&<x,y>\in (R-S)^{-1}\\
{|\!\!\!=\!\!\!|}&<y,x>\in R-S\\
{|\!\!\!=\!\!\!|}&<y,x>\in R\land <y,x>\not\in S\\
{|\!\!\!=\!\!\!|}&<x,y>\in R^{-1}\land <x,y>\not\in S^{-1}\\
{|\!\!\!=\!\!\!|}&<x,y>\in R^{-1}-S^{-1}\\
\end{aligned}

****** 性质4

$R\subset S{|\!\!\!=\!\!\!|}R^{-1}\subset S^{-1}$

******* 证明

根据[[MK117][逆]]的定义以及[[MK15][子集]]定义，对于任意 $<x,y>$

\begin{aligned}
&R\subset S\\
{|\!\!\!=\!\!\!|}&\forall <x,y>(<x,y>\in R\rightarrow<x,y>\in S)\\
{|\!\!\!=\!\!\!|}&\forall <y,x>(<x,y>\in R\rightarrow<x,y>\in S)\\
{|\!\!\!=\!\!\!|}&R^{-1}\subset S^{-1}\\
\end{aligned}

**** 关系复合运算

***** 定义<<MK118>>

若 $R\subset A\times B, S\subset B\times C$ 

则 $R,S$ 的合成关系 $R\cdot S$ 定义为 $R\cdot S=\left\{<x,z>\big|x\in A\land z\in C\land\exists y(y\in B\land xRy\land ySz)\right\}$

****** 推论<<MK119>>

$R\cdot S=\left\{<x,y>\big|\exists y(xRy\land ySz)\right\}$

******* 证明

由于 $xRy{|\!\!\!=\!\!\!|}<x,y>\subset R$ 又有 $R\subset A\times B$ 

故根据[[MK15][子集定义]]，[[MK111][二元关系]]以及[[MK49][描述法]]定义可得 $<x,y>\in R{|\!\!\!=}<x,y>\in A\times B{|\!\!\!=}x\in A\land y\in B$

同理可得 $ySz{|\!\!\!=}y\in B\land z\in C$ 故根据[[MK61][B不含x]] 

此时当 $\exists y(xRy\land ySz)=1$ 根据[[~/文档/note/数理逻辑/sllj.org::MK1][连词定义]]可得 $x\in A=1,z\in C=1$ 且 $\exists y(y\in B\land xRy\land ySz)=1$

故得 $x\in A\land z\in C\land\exists y(y\in B\land xRy\land ySz)=1$

当 $\exists y(xRy\land ySz)=0$ 时可得 $\exists y(y\in B\land xRy\land ySz)=0$ 故有 $x\in A\land z\in C\land\exists y(y\in B\land xRy\land ySz)=0$

故得 $x\in A\land z\in C\land\exists y(y\in B\land xRy\land ySz){|\!\!\!=\!\!\!|}\exists y(xRy\land ySz)$

故根据[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]以及[[MK49][描述法]]定义 $R\cdot S=\left\{<x,y>\big|\exists y(xRy\land ySz)\right\}$

***** 矩阵乘法

若 $A=\{a_1,...a_{n_a}\},B=\{b_1,...b_{n_b}\},C=\{c_1,...c_{n_c}\}$ 均为有限集合

定义矩阵的乘法为 $M_{ij}=R_{i_rj_r}\cdot S_{i_sj_s}=\left\{\sum_{k=1}^{n_b}r_{ik}s_{kj}\right\}$

则有 $S\cdot R$ 的关系矩阵为 $M_{ij}$

****** 证明

故根据[[MK114][矩阵表示]]当 $m_{ij}>0$ 时必存在 $r_{ik}>0\land s_{kj}>0$ 即有 $a_iRb_k\land b_kSc_j$

且 $a_i\in A,b_k\in B,c_j\in C$ 组合条件条件既得 $m_{ij}>0\rightarrow a_i\in A\land c_j\in C\land\exists b_k(b_k\in B\land a_iRb_k\land b_kSc_j)$

即 $<a_i,c_j>\in R\cdot S$ 的[[MK118][定义]]

若 $m_{ij}=0$ 则不存在 $r_{ik}>0\land s_{kj}>0$ 即对于任意 $1\leq k\leq n_b$ 均有 $r_{ik}>0\land s_{kj}>0=0$

且 $a_i\in A,b_k\in B,c_j\in C$ 组合条件条件既得 $m_{ij}=0\rightarrow a_i\in A\land c_j\in C\land\lnot\exists b_k(b_k\in B\land a_iRb_k\land b_kSc_j)$

根据[[MK118][定义]]可知 $<a_i,c_j>\not\in R\cdot S$

故根据[[MK114][矩阵表示]] $M_{ij}$ 为 $R\cdot S$ 的关系矩阵

***** 性质

****** 合成与并

\begin{aligned}
R\cdot(S\cup T)&=(R\cdot S)\cup(R\cdot T)\\
(S\cup T)\cdot R&=(S\cdot R)\cup(T\cdot R)\\
\end{aligned}

******* 证明

仅证 $R\cdot(S\cup T)=(R\cdot S)\cup(R\cdot T)$ 其余同理

定义 $R\in A\times B,S\in B\times C,T\in B\times C$ 

根据[[MK118][定义]]，[[MK58][并运算]]，[[MK61][B不包含x]]，[[~/文档/note/数理逻辑/sllj.org::MK45][交换律]]，[[~/文档/note/数理逻辑/sllj.org::MK46][结合律]]，[[~/文档/note/数理逻辑/sllj.org::MK47][分配率]]，[[~/文档/note/数理逻辑/sllj.org::MK183][辖域变化]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]对于任意 $<x,y>$

\begin{aligned}
&<x,y>\in R\cdot(S\cup T)\\
{|\!\!\!=\!\!\!|}&x\in A\land y\in C\land\exists z(z\in B\land xRz\land(zSy\lor zTy))\\
{|\!\!\!=\!\!\!|}&\exists z(x\in A\land y\in C\land z\in B\land xRz\land(zSy\lor zTy))\\
{|\!\!\!=\!\!\!|}&\exists z\left((x\in A\land y\in C\land z\in B\land xRz\land zSy)\lor(x\in A\land y\in C\land z\in B\land xRz\land zTy)\right)\\
{|\!\!\!=\!\!\!|}&\exists z(x\in A\land y\in C\land z\in B\land xRz\land zSy)\lor\exists z(x\in A\land y\in C\land z\in B\land xRz\land zTy)\\
{|\!\!\!=\!\!\!|}&\left(x\in A\land y\in C\land\exists z(z\in B\land xRz\land zSy)\right)\lor\left(x\in A\land y\in C\land\exists z(z\in B\land xRz\land zTy)\right)\\
{|\!\!\!=\!\!\!|}&<x,y>\in(R\cdot S)\cup(R\cdot T)\\
\end{aligned}

故 $\forall<x,y>(<x,y>\in R\cdot(S\cup T)\leftrightarrow<x,y>\in(R\cdot S)\cup(R\cdot T))=1$ 根据[[MK2][外延公理]]可得 $R\cdot(S\cup T)=(R\cdot S)\cup(R\cdot T)$

****** 合成与交

\begin{aligned}
R\cdot(S\cap T)&\subset(R\cdot S)\cap(R\cdot T)\\
(S\cap T)\cdot R&\subset(S\cdot R)\cap(T\cdot R)\\
\end{aligned}

******* 证明

仅证 $R\cdot(S\cap T)&\subset(R\cdot S)\cap(R\cdot T)$ 其余同理

定义 $R\in A\times B,S\in B\times C,T\in B\times C$ 

根据[[MK118][定义]]，[[MK58][并运算]]，[[MK61][B不包含x]]，[[~/文档/note/数理逻辑/sllj.org::MK45][交换律]]，[[~/文档/note/数理逻辑/sllj.org::MK46][结合律]]，[[~/文档/note/数理逻辑/sllj.org::MK47][分配率]]，[[~/文档/note/数理逻辑/sllj.org::MK183][辖域变化]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]对于任意 $<x,y>$

\begin{aligned}
&<x,y>\in R\cdot(S\cap T)\\
{|\!\!\!=\!\!\!|}&x\in A\land y\in C\land\exists z(z\in B\land xRz\land(zSy\land zTy))\\
{|\!\!\!=\!\!\!|}&\exists z(x\in A\land y\in C\land z\in B\land xRz\land(zSy\land zTy))\\
{|\!\!\!=\!\!\!|}&\exists z\left((x\in A\land y\in C\land z\in B\land xRz\land zSy)\land(x\in A\land y\in C\land z\in B\land xRz\land zTy)\right)\\
{|\!\!\!=}&\exists z(x\in A\land y\in C\land z\in B\land xRz\land zSy)\land\exists z(x\in A\land y\in C\land z\in B\land xRz\land zTy)\\
{|\!\!\!=\!\!\!|}&\left(x\in A\land y\in C\land\exists z(z\in B\land xRz\land zSy)\right)\land\left(x\in A\land y\in C\land\exists z(z\in B\land xRz\land zTy)\right)\\
{|\!\!\!=\!\!\!|}&<x,y>\in(R\cdot S)\cap(R\cdot T)\\
\end{aligned}

故得 $\forall<x,y>(<x,y>\in R\cdot(S\cap T)\rightarrow<x,y>\in(R\cdot S)\cap(R\cdot T))=1$ 根据[[MK15][子集定义]]可得 $R\cdot(S\cap T)&\subset(R\cdot S)\cap(R\cdot T)$ 

****** 合成与逆

\begin{aligned}
(R\cdot S)^{-1}=S^{-1}\cdot R^{-1}\\
\end{aligned}

******* 证明

定义 $R\in A\times B,S\in B\times C,T\in B\times C$ 

根据[[MK118][定义]]以及[[MK117][逆]]运算，[[~/文档/note/数理逻辑/sllj.org::MK3][交换律]]，[[~/文档/note/数理逻辑/sllj.org::MK46][结合律]]对于任意 $<x,y>$

\begin{aligned}
&<x,y>\in(R\cdot S)^{-1}\\
{|\!\!\!=\!\!\!|}&<y,x>\in(R\cdot S)\\
{|\!\!\!=\!\!\!|}&y\in A\land x\in C\land\exists z(z\in B\land yRz\land zSx)\\
{|\!\!\!=\!\!\!|}&y\in A\land x\in C\land\exists z(z\in B\land <y,z>\in R\land <z,x>\in S)\\
{|\!\!\!=\!\!\!|}&y\in A\land x\in C\land\exists z(z\in B\land <z,y>\in R^{-1}\land <x,z>\in S^{-1})\\
{|\!\!\!=\!\!\!|}&y\in A\land x\in C\land\exists z(z\in B\land <x,z>\in S^{-1}\land <z,y>\in R^{-1})\\
{|\!\!\!=\!\!\!|}&<x,y>\in S^{-1}\cdot R^{-1}
\end{aligned}

根据[[MK2][外延公理]]可得 $(R\cdot S)^{-1}=S^{-1}\cdot R^{-1}$

****** 合成结合律<<MK120>>

\begin{aligned}
(R\cdot S)\cdot T=R\cdot(S\cdot T)\\
\end{aligned}

******* 证明

定义 $R\in A\times B,S\in B\times C,T\in C\times D$ 

根据[[MK119][推论]]，[[MK118][关系定义]]，[[~/文档/note/数理逻辑/sllj.org::MK185][量词交换]]，[[~/文档/note/数理逻辑/sllj.org::MK183][辖域变化]]，[[~/文档/note/数理逻辑/sllj.org::MK3][交换律]]，[[~/文档/note/数理逻辑/sllj.org::MK46][结合律]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]对于任意 $<x,y>$

\begin{aligned}
&<x,y>\in(R\cdot S)\cdot T\\
{|\!\!\!=\!\!\!|}&\exists z(<x,z>\in (R\cdot S)\land<z,y>\in T)\\
{|\!\!\!=\!\!\!|}&\exists z(\exists w(<x,w>\in R\land <w,z>\in S)\land<z,y>\in T)\\
{|\!\!\!=\!\!\!|}&\exists z\exists w(<x,w>\in R\land <w,z>\in S\land<z,y>\in T)\\
{|\!\!\!=\!\!\!|}&\exists w\exists z(<x,w>\in R\land <w,z>\in S\land<z,y>\in T)\\
{|\!\!\!=\!\!\!|}&\exists w\exists z(<w,z>\in S\land<z,y>\in\land <x,w>\in R)\\
{|\!\!\!=\!\!\!|}&\exists w(\exists z(<w,z>\in S\land<z,y>\in)\land <x,w>\in R)\\
{|\!\!\!=\!\!\!|}&\exists w(<x,w>\in R\land \exists z(<w,z>\in S\land<z,y>\in T))\\
{|\!\!\!=\!\!\!|}&\exists w(<x,w>\in R\land <w,y>\in(S\cdot T))\\
{|\!\!\!=\!\!\!|}&<x,y>\in R\cdot(S\cdot T)\\
\end{aligned}

根据[[MK2][外延公理]]可得 $(R\cdot S)\cdot T=R\cdot(S\cdot T)$

****** 合成同一律

若 $R\subset A\times B$ 则有:

\begin{aligned}
&E_A\cdot R=R\\
&R\cdot E_B=R\\
\end{aligned}

**** 关系的幂运算

***** 定义<<MK121>>

若 $R\in A\times A$ 其幂运算定义为：

（1） $R^0=E_A$ 其中 $E_A$ 是[[MK113][相等关系]]

（2） $R^n=R^{n-1}\cdot R$ 即 $R^{n-1}$ 与 $R$ 的[[MK118][合成]]运算

***** 性质

****** 性质1

\begin{aligned}
R^n\cdot R^m=R^{n+m}
\end{aligned}

******* 证明

根据[[MK120][结合律]]可得 $R^n\cdot R^m=R^{n+m}$

****** 性质2

\begin{aligned}
(R^n)^m=R^{nm}
\end{aligned}

***** 幂关系有限定理<<MK122>>

若 $A$ 的基数为 $n$ 且 $R\in A\times A$ 则存在自然数 $0\leq i\leq j\leq 2^{n^2}$ 使得 $R^i=R^j$

****** 证明

由于基数为 $n$ 则可能的关系矩阵个数为 $2^{n^2}$ 个，故遍历 $2^{n^2}+1$ 次结果中必有相同。 

***** 幂运算收敛性

若 $A$ 的基数为 $n$ 且 $R\in A\times A$ 则 $\cup_{i=1}^\infty R^i=\cup_{i=1}^n R^i$ 此处为[[MK59][广义并]]

****** 证明

显然 $\cup_{i=1}^n R^i\subset \cup_{i=1}^\infty R^i$

根据[[MK70][交换律]]，[[MK71][结合律]]可得 $\cup_{i=1}^\infty R^i=\left(\cup_{i=1}^n R^i\right)\cup\left(\cup_{i=n+1}^\infty R^i\right)$ 显然 $\cup_{i=1}^n R^i\subset \cup_{i=1}^n R^i$

则对于任意 $k>n$ 的幂关系 $R^k$ ，必然存在 $<a,a_1>\in R\land...\land<a_{k-1},b>\in R$

则在 $a=a_0,a_1,...,a_{k-1},a_k=b$ 中有 $k+1$ 个元素，由于 $|A|=n$ 且 $k>n$ 故根据鸽笼原理至少存在两个元素相等

若 $a_i=a_j,0\leq i\leq j\leq k$ 则重新选取关系链  $<a,a_1>\in R\land...<a_{i-1},a_i>\in R\land<a_j,a_{j+1}>\in R\land...\land<a_{k-1},b>\in R$

由于 $a_i=a_j$ 根据[[MK118][复合定义]]以上关系亦可组成幂关系，其指数为 $R^{k_1}$ 其中 $k_1=k-{j-i}$ ，进一步有 $<a,b>=<a_0,b_k>\in R^{k_1}$

只要当 $k>n$ 即可根据以上步骤去除多余项，直至 $k\leq n$ 时，鸽笼原理不满足。

即对于任意 $<a,b>\in R^k$ 总能找到一个 $R^{k'}\land k'\leq n\rightarrow <a,b>\in R^{k'}$

综上说书 $\forall k>n\rightarrow R^k\subset\cup_{i=1}^nR^i$ 故可得 $\cup_{i=1}^\infty R^i=\cup_{i=1}^n R^i$ 

*** 关系性质

**** 定义<<MK123>>

若 $R\subset A\times A$ 则定义如下关系

自反关系<<MK124>>：   $\forall x(x\in A\rightarrow xRx)$ [[MK114][关系矩阵]]对角线为 $1$

反自反关系<<MK125>>： $\forall x(x\in A\rightarrow \lnot xRx)$ [[MK114][关系矩阵]]对角线为 $0$

对称关系<<MK126>>：   $\forall x\forall y(x\in A\land y\in A\land xRy\rightarrow yRx)$  [[MK114][关系矩阵]]为对称矩阵

反对称关系<<MK127>>： $\forall x\forall y(x\in A\land y\in A\land xRy\land yRx\rightarrow x=y)$

                    [[MK119][同理可证]]条件等价于 $\forall x\forall y(xRy\land yRx\rightarrow x=y)$

传递关系<<MK128>>：   $\forall x\forall y\forall z(\{x,y,z\}\subset A\land xRy\land yRz\rightarrow xRz)$ 

                    [[MK119][同理可证]]条件等价于 $\forall x\forall y\forall z(xRy\land yRz\rightarrow xRz)$

                    又根据[[~/文档/note/数理逻辑/sllj.org::MK114][量词顺序]] $\forall x\forall y\forall z(xRy\land yRz\rightarrow xRz){|\!\!\!=\!\!\!|}\forall x\forall z\forall y(xRy\land yRz\rightarrow xRz)$

                    进一步有 $\forall x\forall z\forall y(xRy\land yRz\rightarrow xRz)\Rightarrow\forall x\forall z(\exists y(xRy\land yRz)\rightarrow xRz)$

**** 定理

***** 定理1

$R$ 是[[MK124][自反关系]]当且仅当 $E_A\subset R$

****** 证明

******* 充分

若 $R$ [[MK124][自反]]，则有 $\forall x(x\in A\rightarrow xRx){|\!\!\!=\!\!\!|}\forall x(x\in A\rightarrow <x,x>\in R)$

根据[[MK113][定义]]对于任意 $<x,x>$ 若 $<x,x>\in E_A{|\!\!\!=\!\!\!|}x\in A{|\!\!\!=}<x,x>\in R$

故有 $E_A\subset R$

******* 必要

若 $E_A\subset R$ 则有 对于任意 $<x,x>$ 若 $x\in A{|\!\!\!=\!\!\!|}x\in E_A{|\!\!\!=}<x,x>\in R$

故有 $\forall x(x\in A\rightarrow xRx)$

***** 定理2

$R$ 是[[MK125][反自反]]当且仅当 $E_A\cap R=\varnothing$

****** 证明

充分：若 $R$ [[MK125][反自反]]，则有 $\forall x(x\in A\rightarrow \lnot xRx){|\!\!\!=\!\!\!|}\forall x(x\in A\rightarrow <x,x>\not\in R)$

此时若 $x\in A$ 则有 $<x,x>\in E_A\land <x,x>\not\in R$ ，若 $x\not\in A$ 则有 $<x,x>\not\in E$

故有 $E_A\cap R=\varnothing$ 。

必要证明类似。

***** 定理3

$R$ [[MK126][对称]]当且仅当 $R=R^{-1}$

****** 证明

******* 充分

根据[[MK126][定义]]以及[[MK117][逆运算]]可得对于任意 $<x,y>$

\begin{aligned}
&<x,y>\in R\\
{|\!\!\!=}&<y,x>\in R\\
{|\!\!\!=\!\!\!|}&<x,y>\in R^{-1}\\
\end{aligned}

且

\begin{aligned}
&<x,y>\in R^{-1}\\
{|\!\!\!=\!\!\!|}&<y,x>\in R\\
{|\!\!\!=\!\!\!|}&<y,x>\in R\\
\end{aligned}

根据[[MK15][自己定义]]可得 $R\subset R^{-1}\land R^{-1}\subset R$ ，根据[[MK16][定理]]可得 $R=R^{-1}$

******* 必要

根据[[MK15][子集定义]]可得对于任意 $<x,y>$

\begin{aligned}
&<x,y>\in R\\
{|\!\!\!=}&<x,y>\in R^{-1}\\
{|\!\!\!=\!\!\!|}&<y,x>\in R\\
\end{aligned}

根据[[MK126][定义]]可得 $R$ 对称

***** 定理4

$R$ [[MK127][反对称]]当且仅当 $R\cap R^{-1}\subset E_A$

****** 证明

******* 充分

$R$ [[MK127][反对称]]则有 $\forall x\forall y(xRy\land yRx\rightarrow x=y)$

对于任意 $<x,y>$

\begin{aligned}
&<x,y>\in R\cap R\sim\\
{|\!\!\!=\!\!\!|}&<y,x>\in R\land<x,y>\in R\sim\\
{|\!\!\!=\!\!\!|}&<y,x>\in R\land<y,x>\in R\\
{|\!\!\!=}&(x=y)\\
\end{aligned}

又由于 $<x,y>\in R$ 包含条件 $x\in A$ 故得 $<x,y>\in E_A$

根据[[MK15][子集定义]] $R\cap R\sim\subset E_A$

******* 必要

当 $R\cap R\sim\subset E_A$ 时，根据[[MK117][逆运算]]，[[MK60][交运算]]，[[MK15][子集定义]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]对于任意 $<x,y>$

\begin{aligned}
&xRy\land yRx\\
{|\!\!\!=\!\!\!|}&<x,y>\in R\land <y,x>\in R\\
{|\!\!\!=\!\!\!|}&<x,y>\in R\land <x,y>\in R\sim\\
{|\!\!\!=\!\!\!|}&<x,y>\in R\cap R\sim\\
{|\!\!\!=}&<x,y>\in E_A\\
\end{aligned}

***** 定理5<<MK129>>

$R$ [[MK128][传递]]当且仅当 $R^2\subset R$

****** 证明

******* 充分

$R$ [[MK128][传递]]则 $\forall x\forall y\forall z(xRy\land yRz\rightarrow xRz)$

\begin{aligned}
&<x,z>\in R^2\\
{|\!\!\!=\!\!\!|}&<x,z>\in R\cdot R\\
{|\!\!\!=\!\!\!|}&\exists y(xRy\land yRz)\\
{|\!\!\!=}&\exists y(xRz)\\
{|\!\!\!=\!\!\!|}&xRz\\
\end{aligned}

故根据[[MK15][子集]]定义 $R^2\subset R$

******* 必要

若 $R^2\subset R$ 则根据[[MK15][子集]]定义对于任意 $x,z$ 有 $<x,z>\in R^2{|\!\!\!=}<x,z>\in R$

又根据[[MK118][合成定义]] $<x,z>\in R^2{|\!\!\!=\!\!\!|}&\exists y(xRy\land yRz)$

即对于任意 $<x,z>$ 有 $\exists y(xRy\land yRz){|\!\!\!=}<x,z>\in R$

即 $R$ [[MK128][传递]]

**** 运算封闭性

***** 逆运算

[[MK123][关系基本特性]]对于[[MK117][逆运算]]封闭，即若 $R$ 均拥有某项[[MK123][关系基本特性]]则 $R^{-1}$ 亦有。

***** 交运算

[[MK123][关系基本特性]]对于[[MK60][交运算]]封闭，即若 $R_1,R_2$ 均拥有某项[[MK123][关系基本特性]]则 $R_1\cap R_2$ 亦有。

***** 并运算<<MK130>>

[[MK124][自反]]、[[MK125][反自反]]、[[MK126][对称性]]对并运算封闭，即若 $R_1,R_2$ 均拥有某项上述基本特性则 $R_1\cup R_2$ 亦有。

***** 差运算

[[MK125][反自反]]、[[MK126][对称]]、[[MK127][反对称]]对差运算封闭，即若 $R_1,R_2$ 均拥有某项上述基本特性则 $R_1-R_2$ 亦有。

***** 补运算

[[MK126][对称性]]对补运算封闭，即若 $R_1$ 均拥有某项上述基本特性则 $R_1\sim$ 亦有。

***** 合成运算

[[MK124][自反]]对合成运算封闭，即若 $R_1,R_2$ 均拥有某项上述基本特性则 $R_1\cdot R_2$ 亦有

**** 闭包

***** 定义<<MK131>>

设 $R$ 是集合 $A$ 上的关系，存在一个集合 $R'$ 满足：

（1） $R'$ 是[[MK124][自反]]（或[[MK126][对称]]或[[MK128][传递]]的）

（2） $R\subset R'$

（2） 对于任意 $A$ 上的[[MK124][自反]]（或[[MK126][对称]]或[[MK128][传递]]）关系 $R''$ 均有 $R'\subset R''$ 

即 $R'$ 是 $A$ 上包含 $R$ 的最小上[[MK124][自反]]（或[[MK126][对称]]或[[MK128][传递]]）关系

则称 $R'$ 是 $R$ 的自反闭包（或对称闭包或传递闭包），记作 $r(R)$ （或者 $s(R)$ 或者 $t(R)$）

***** 求解

****** 自反闭包

若 $R$ 是 $A\times A$ 上的关系，则根据[[MK124][自反]]定义可得 $r(R)=R\cup E_A$ 其中 $E_A$ 为[[MK113][相等关系]]。

****** 对称闭包

若 $R$ 是 $A\times A$ 上的关系，则根据[[MK126][对称]]定义可得 $s(R)=R\cup R^{-1}$ 其中 $R^{-1}$ 为 $R$ 的[[MK117][逆]]。

****** 传递闭包

若 $R$ 是 $A\times A$ 上的关系，则根据[[MK128][传递]]定义可得 $t(R)=\cup_{i=1}^\infty R^i$ 其中 $R^i$ 为 $R$ 的 $i$ 次[[MK121][幂]]

若 $|A|=n$ 则有 $t(R)=\cup_{i=1}^n R^i$

******* 证明

根据定义有 $\forall x\forall y\forall z\big(\{x,y,z\}\subset A\land xRy\land yRz\rightarrow xRz\big)$ 

******** 证明 $t(R)\subset\cup_{i=1}^\infty R$

则根据[[MK121][幂]]运算定义，对于任意 $\{<x,y>,<y,z>\}\in \cup_{i=1}^\infty R^i$ 均有 $<x,z>\in\cup_{i=1}^\infty R^i$ ：

（1） 若 $\{<x,y>,<y,z>\}\in R^k$ 则 $<x,z>\in R^{k+1}$

（2） 若 $<x,y>\in R^j\land <y,z>\in R^k\land j<k$ 则必然有 $\{<x,y>,<y,z_1>,...,<y,z_{k-j}>,<z_{k-1},z>\}\in R^j$ 则同理根据[[MK118][复合运算]]定义 $<x,z_1>\in R^{j+1}$

      以此类推，必有 $<x,z_{k-1}>\in R^k$ 故亦有 $<x,z>\in R^{k+1}$

即 $\cup_{i=1}^\infty R$ 对称，且有 $R\subset \cup_{i=1}^\infty R$ 则根据[[MK131][定义]]可得 $t(R)\subset\cup_{i=1}^\infty R$

******** 证明 $\cup_{i=1}^\infty R\subset t(R)$

对于任意 $n$ 当 $n=1$ 时，显然有 $R^1\subset t(R)$

当 $R^n\subset t(R)$ 时，对于任意 $<x,y>\in R^{n+1}$ 均可推出 $\exists z\big(<x,z>\in R^n\land <z,y>\in R^n\big)$

固有 $\{<x,z><z,y>\}\subset t(R)$ 则有 $<x,y>\in t(R)$

结合 $n=1$ 可得对于任意 $n$ 均有 $R^n\subset t(R)$ 故有 $\cup_{i=1}^\infty R^i\subset t(R)$

******** 结论

综上所属，根据条件有 $\big(\cup_{i=1}^\infty R^i\subset t(R)\big)\land\big(t(R)\subset\cup_{i=1}^\infty R^i\big)$ 根据[[MK16][子集定理]]可得 $t(R)=\cup_{i=1}^\infty R^i$

** 特殊关系

*** 等价关系<<MK132>>

定义集合 $A$ 若：

（1） $R$ 是 $A$ 上的[[MK111][二元关系]]，即 $R\in A\times A$

（2） $R$ 具有[[MK124][自反性]]，[[MK126][对称性]]以及[[MK128][传递性]]，即 $xRx,xRy\rightarrow yRx, xRy\land xRz\rightarrow xRz$

**** 等价类<<MK133>>

若 $R$ 是 $A$ 上的[[MK132][等价关系]]，则对于每一个 $a\in A$ ，集合 $\left\{x\big|x\in A\land aRx\right\}$ 称为 $a$ 在关系 $R$ 上的等价类，记作 $[a]_R$ 

**** 定理1<<MK134>>

若 $R$ 是 $A$ 上的[[MK132][等价关系]]，则任意 $\{a,b\}\subset A$ 有 $aRb\leftrightarrow[a]_R=[b]_R$

***** 证明

****** 充分

当 $aRb$ 时，若 $x\in[a]_R$ 则有 $xRa,aRb$ 根据[[MK128][传递性]]可得 $xRb$ 。又根据[[MK133][等价类定义]]可得 $x\in[b]_R$

同理可证若 $x\in[b]_R\rightarrow x\in[a]_R$ 根据[[~/文档/note/数理逻辑/sllj.org::MK49][等价等值式]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]可得对于任意 $x$ 有 $x\in[b]_R\leftrightarrow x\in[a]_R=1$

又根据[[MK2][外延公理]]可得 $[a]_R=[b]_R$

****** 必要

根据[[MK124][自反性]] $aRa,bRb$ 必定成立，故有 $a\in[a]_R$

由于 $[a]_R=[b]_R$ 根据[[MK2][外延公理]]可得 $a\in[b]_R$ 故有 $aRb$

**** 定理2<<MK135>>

若 $R$ 是 $A$ 上的[[MK132][等价关系]]，则任意 $\{a,b\}\subset A$ 且 $[a]_R\ne[b]_R$ 时必有 $[a]_R\cap[b]_R=\varnothing$

***** 证明

当 $\{a,b\}\subset A$ 且 $[a]_R\ne[b]_R$ 若存在 $x\in[a]_R\land x\in[b]_R$ 则有 $\forall(y\in[a]_R\rightarrow yRx\rightarrow yRb\rightarrow y\in[b]_R)$

同理可证 $\forall y(y\in[b]_R\rightarrow y\in[a]_R)$ 故根据[[~/文档/note/数理逻辑/sllj.org::MK49][等价等值式]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]可得对于任意 $y$ 有 $y\in[b]_R\leftrightarrow y\in[a]_R=1$

即根据[[MK2][外延公理]]可得 $[a]_R=[b]_R$ 与条件矛盾，故不存在 $x\in[a]_R\land x\in[b]_R$ 

即根据[[MK60][交运算]]定义 $[a]_R\cap[b]_R=\varnothing$

**** 定理3<<MK331>>

若 $R$ 是 $A$ 上的[[MK132][等价关系]] $B=\left\{[a]_R\big|a\in A\right\}$ 则有 $|B|\leq|A|$

***** 证明

对于任意 $[a]_R\in B$ 根据[[MK14][选择公理]]可得存在选择函数 $f$ 满足 $f([a]_R)\in[a]_R$ 显然有 $f([a]_R)\in A$

显然对于任意 $[a]_R\ne[b]_R$ 不存在 $c\in[a]_R\land c\in[b]_R$ ，故可得 $f([a]_R)\ne f([b]_R)$

即 $f$ 是[[MK176][单射]]，根据[[MK29][等势]]可得 $|B|\leq|A|$

*** 划分

**** 定义<<MK136>>

定义非空集合 $A$ 和[[MK47][集合族]] $\pi$ 若满足：

（1） 不空 $\forall(B\in\pi\rightarrow B\ne\varnothing)$

（2） 不漏 $\cup\pi=A$ 此处为[[MK59][广义并]]运算

（3） 不交 $\forall B\forall B'(\{B,B'\}\in\pi\land B\ne B'\rightarrow B\cap B'=\varnothing)$

则称 $\pi$ 是集合 $A$ 的 *划分* ， $\pi$ 中的元素称为 *单元，块(blcok)或类(class)* 。 $\pi$ 亦称为[[MK142][商集]]

定义若 $A=\varnothing$ 则 $\pi=\varnothing$ 是其划分

**** 有理划分<<MK137>>

定义非空集合 $A$ 和其[[MK136][划分]] $\pi$ ，若 $\pi$ 是[[MK93][至多可数集]]，则称 $\pi$ 是 $A$ 的有理划分

**** 定理

***** 定理1<<MK138>>

若 $R$ 是 $A$ 上的[[MK132][等价关系]]且 $A\ne\varnothing$ 则 $A$ 上的[[MK133][等价类]]构成的集合族 $\pi$ 为 $A$ 的[[MK136][划分]]

****** 证明

根据[[MK124][自反性]]任意等价类 $a\in A$ 都有 $aRa$ ，则根据[[MK133][等价类]]定义可得 $a\in[a]_R$ 即不空

根据[[MK133][等价类]]定义若 $x\in A$ 则必有 $[x]_R$ 存在，且若 $x\in[a]_R$ 其中 $[a]_R$ 为等价类，则必有 $x\in A$

故根据[[MK59][广义并]]定义 $\forall x(x\in A\leftrightarrow \exists[x]_R(x\in[x]_R\land[x]_R\in\pi)\leftrightarrow x\in\cup\pi)$ 

进一步根据[[~/文档/note/数理逻辑/sllj.org::MK39][等价传递]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]有 $\forall x(x\in A\leftrightarrow x\in\cup\pi)$

又根据[[MK2][外延公理]]可得 $A=\cup\pi$ 即不漏

根据[[MK135][定理2]]可得 $\forall B\forall B'(\{B,B'\}\in\pi\land B\ne B'\rightarrow B\cap B'=\varnothing)$ 即不交

故根据[[MK136][定义]]可得根据关系 $R$ 所构成的等价类集合族 $\pi$ 为 $A$ 的划分

***** 定理2<<MK139>>

若 $\pi$ 是 $A$ 上的一个[[MK136][划分]]，则存在对应的等价关系 $R$

****** 证明

若 $\pi$ 是 $A$ 上的一个[[MK136][划分]]，则定义关系 $R$ 即对于任意 $\{x,y\}\subset A$ 若存在 $\{x,y\}\subset S\in\pi$ 则有关系 $xRy$

下面证明 $R$ 是等价关系

（1） 自反性：由于 $S\in\pi$ 则根据[[MK136][划分]] $S$ 非空。故若 $x\in S$ 则必有 $xRx$

（2） 对称性：若 $\{x,y\}\subset S\in\pi$ 则根据 $R$ 定义，有 $xRy$

（3） 传递性：若 $xRy,yRz$ 则有 $\{x,y\}\subset S\in\pi\land\{y,z\}\subset S'\in\pi$ 根据[[MK136][定义]]划分必须不交，故 $x\in S\land x\in S'\rightarrow S=S'$ 即 $\{x,y,z\}\in S$ 故有 $xRz$

根据[[MK132][定义]]可得 $R$ 为等价关系。

***** 定理3

若集合 $A$ 非空，则[[MK136][划分]] $\pi$ 对应的等价关系为 $R$ 当且仅当 $R$ 对应的划分为 $\pi$

****** 证明

******* 必要

定义 $\pi$ 对应的等价关系是 $R$ ， $R$ 对应的划分为 $\pi'$

对于任意 $a\in A$ 根据[[MK136][划分]]不漏，存在 $B\in\pi$ 使得 $a\in B$ 同理存在 $a\in[a]_R\in\pi'$

对于任意 $b\in B$ 必有 $b\in B\rightarrow aRb\rightarrow b\in[a]_R$

同理对于任意 $b\in[a]_R\rightarrow aRb\rightarrow b\in B$

根据[[~/文档/note/数理逻辑/sllj.org::MK49][等价等值式]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]可得对于任意 $b$ 均有 $b\in B\leftrightarrow b\in[a]_R$

又根据[[MK2][外延公理]]可得 $B=[a]_R$

******* 充分

若 $R$ 对应的划分为 $\pi$ ， $\pi$ 对应的等价关系为 $R'$

若 $xRy\rightarrow \{x,y\}\subset S\in\pi\rightarrow xR'y$

若 $xR'y\rightarrow \{x,y\}\subset S\in\pi\rightarrow xRy$

根据[[~/文档/note/数理逻辑/sllj.org::MK49][等价等值式]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]可得对于任意 $x$ 均有 $xRy\leftrightarrow xR'y$ 

根据[[MK111][关系定义]]可得 $<x,y>\in R\leftrightarrow<x,y>\in R'$

又根据[[MK2][外延公理]]可得 $R=R'$

**** 划分细度

若集合 $A$ 上的[[MK136][划分]] $\pi_1,\pi_2$ 若 $\forall B_1\in\pi_1(\exists(B_2\in\pi_2\rightarrow B_1\subset B_2))$ 则称 $\pi_1$ 细于 $\pi_2$ 记作 $\pi_1\leq\pi_2$

**** 细度定理<<MK140>>

集合 $A$ 上的[[MK136][划分]] $\pi_1,\pi_2$ 对应的等价关系为 $R_1,R_2$ 则有 $R_1\subset R_2\leftrightarrow\pi_1\leq\pi_2$

***** 证明 

****** 充分

若 $R_1\subset R_2$ 对于任意 $\{a,b\}\subset A$ 当 $aR_1b$ 时便有 $aR_2b$ 故 $b\in[a]_{R_1}\land b\in[a]_{R_2}$

故有对于任意 $b$ 有 $b\in[a]_{R_1}\rightarrow b\in[a]_{R_2}$ 故根据[[MK15][子集]]的定义有 $[a]_{R_1}\subset[a]_{R_2}$

****** 必要

若 $\pi_1\leq\pi_2$ 故若 $\{x,y\}\subset S_1\in\pi_1$ 则存在 $\{x,y\}\subset S_1\subset S_2\in\pi_2$

故有对于任意 $xR_1y$ 均有 $xR_2y$ 即 $<x,y>\in R_1\rightarrow <x,y>\in R_2$

故根据[[MK15][子集]]的定义 $R_1\subset R_2$

***** 推论

[[MK113][相等关系]]是等价关系对应划分中最“细”的。

相应的最大的等价关系是[[MK112][全关系]]

**** 划分的运算

***** 积划分

$A$ 上的划分 $\pi_1,\pi_2$ 的积划分记作 $\pi_1\cdot\pi_2$ ，该划分满足：

（1） $\pi_1\cdot\pi_2\leq\pi_1\land\pi_1\cdot\pi_2\leq\pi_1$

（2） $\forall \pi(\pi\leq\pi_1\land\pi\leq\pi_1\rightarrow\pi\leq\pi_1\cdot\pi_2)$

****** 推论

若 $R_1,R_2$ 是 $\pi_1,\pi_2$ 对应的等价关系，则有 $\pi_1\cdot\pi_2$ 对应的等价关系是 $R_1\cap R_2$

******* 证明

由于 $R_1\cap R_2\subset R_1$ 根据[[MK140][细度定理]]可得 $\pi_1\cdot\pi_2\leq\pi_1$

同理可得 $\pi_1\cdot\pi_2\leq\pi_2$

若存在 $\pi\leq\pi_1\land\pi\leq\pi_2$ 根据[[MK139][定理2]]可得存在 $R$ 与 $\pi$ 对应

根据[[MK140][细度定理]]可得 $R\subset R_1\land R\subset R_2$ 根据[[MK60][交运算]]可得 $\forall x(x\in R\rightarrow x\in R_1\cap R_2)$

根据[[MK15][子集]]的定义有 $R\subset R_1\cap R_2$

***** 和划分

$A$ 上的划分 $\pi_1,\pi_2$ 的和划分记作 $\pi_1+\pi_2$ ，该划分满足：

（1） $\pi_1\leq\pi_1+\pi_2\land \pi_2\leq\pi_1+\pi_2$

（2） $\forall \pi(\pi_1\leq\pi\land\pi_2\leq\pi\rightarrow\pi_1+\pi_2\leq\pi)$

注：由于[[MK130][封闭性]]显示并运算对于[[MK128][传递性]]不封闭，故和划分不等价于集合并。

****** 传递闭包<<MK141>>

若 $R$ 是 $A$ 上的[[MK111][二元关系]]，则传递闭包 $R_t$ 满足：

（1） $R_t$ 具有传递性，即补足 $R$ 使得 $R\subset R_t$ 且 $\forall x\forall z(\exists y(xR_ty\land yR_tz)\rightarrow xR_tz)$

（2） 若存在 $R'$ 使得 $R\subset R'\land\forall x\forall z(\exists y(xR'y\land yR'z)\rightarrow xR'z)$ 则有 $R_t\subset R'$
 
****** 推论

若 $R_1,R_2$ 是 $\pi_1,\pi_2$ 对应的等价关系，则有 $\pi_1+\pi_2$ 对应的等价关系是 $(R_1\cup R_2)_t$ 即 $R_1\cup R_2$ 的传递闭包

******* 证明

根据[[MK58][并运算]]及[[MK141][传递闭包]]可得 $R_1\subset (R_1\cup R_2)_t\land R_2\subset (R_1\cup R_2)_t$ 根据[[MK140][细度定理]]可得 $\pi_1\leq\pi_1+\pi_2\land \pi_2\leq\pi_1+\pi_2$

若存在 $\pi$ 满足 $\pi_1\leq\pi\land\pi_2\leq\pi$ 根据[[MK139][定理2]]可得存在 $R$ 与 $\pi$ 对应，且 $R$ 具有[[MK128][传递性]]

根据[[MK140][细度定理]]可得 $R_1\subset R\land R_2\subset R$ 根据[[MK58][并运算]]以及[[MK141][传递闭包]]可得 $(R_1\cup R_2)_t\subset R$

根据[[MK140][细度定理]]可得 $\pi_1+\pi_2\leq\pi$

**** 商集<<MK142>>

$R$ 是 $A$ 上的[[MK132][等价关系]]，则称 $A$ 的划分 $\left\{[a]_R\big|a\in A\right\}$ 为 $A$ 的 $R$ 商集，记作 $A/R$

*** 偏序关系<<MK143>>

定义集合 $A$ 若：

（1） $R$ 是 $A$ 上的[[MK111][二元关系]]，即 $R\in A\times A$

（2） $R$ 具有[[MK124][自反性]]，[[MK127][反对称性]]以及[[MK128][传递性]]，即 $xRx,xRy\land yRx\rightarrow x=y, xRy\land xRz\rightarrow xRz$

则称 $R$ 为 $A$ 上的序关系，且 $A$ 称为有序集，记作 $<A,R>$

**** 可比与覆盖

定义 $R$ 为非空集合 $A$ 上的[[MK143][序]]关系，其中 $\{x,y,z\}\subset A$ 若：

（1） 存在 $xRy$ 或 $yRx$ 则称 $x,y$ 可比

（2） 存在 $xRy$ 且 $\lnot\exists z\big(z\in A\land xRz\land zRy\big)$

**** 元素

***** 元<<MK144>>

若 $<A,\leq>$ 是有序集，且 $B\subset A$ 则 $b$ 是：

$B$ 的最小元： $b\in B\land\forall x(x\in B\rightarrow b\leq x)$

$B$ 的最大元： $b\in B\land\forall x(x\in B\rightarrow x\leq b)$

$B$ 的极小元： $b\in B\land\lnot\exists x(x\in B\land x\ne b\land x\leq b)$ 

$B$ 的极大元： $b\in B\land\lnot\exists x(x\in B\land x\ne b\land b\leq x)$ 

****** 定理

（1） $B$ 的最大（小）元必为 $B$ 的极大（小）元

（2） 如果 $B$ 有最大（小）元，则它是唯一的

（3） 如果 $B$ 是有限集，则B的极大（小）元恒存在

（3） 最大（小）元未必存在，存在则唯一

（4） 极大（小）元对有限集必然存在，未必唯一

***** 界<<MK145>>

若 $<A,\leq>$ 是有序集，且 $B\subset A$ 则 $b$ 是：

$B$ 的上界： $b\in A\land\forall x(x\in B\rightarrow x\leq b)$ 

$B$ 的下界： $b\in A\land\forall x(x\in B\rightarrow b\leq x)$ 

$B$ 的上确界： $b$ 是上界的最小元 

$B$ 的下确界： $b$ 下界的最大元 

****** [[MK175][函数]]的界<<MK146>>

若 $<X,\leq>$ 是有序集，且 $Y\subset X$  

若 $I=\left\{f_a(x)\big|a\in A\right\}$ 是一个 $f:E\to Y$ 的[[MK175][函数]]的集合，其中 $A$ 为[[MK48][标志集]]则对于函数 $g:E\to X$ ：

是 $I$ 的上界： 则有对于任意 $x'\in E$ 均有 $g(x')$ 是 $\{f(x')\}$ 的[[MK145][上界]]

是 $I$ 的下界： 则有对于任意 $x'\in E$ 均有 $g(x')$ 是 $\{f(x')\}$ 的[[MK145][下界]]

是 $I$ 的上确界： 则有对于任意 $x'\in E$ 均有 $g(x')$ 是 $\{f(x')\}$ 的[[MK145][上确界]]

是 $I$ 的上确界： 则有对于任意 $x'\in E$ 均有 $g(x')$ 是 $\{f(x')\}$ 的[[MK145][下确界]]

****** 定理1

（1） 如果 $b$ 是 $B$ 的最大（小）元，则b是 $B$ 的上（下）确界

（2） 如果 $b$ 是 $B$ 的上（下）界，而且 $b\in B$ ，则 $b$ 一定是 $B$ 的最大（小）元

（3） 如果有上（下）确界，则上（下）确界是唯一的

（4） 上下界未必存在，存在时也未必唯一

（5） 有了上（下）界，也未必存在上（下）确界

******* 证明

只证（5），若存在 $\{c,d\}\in A$ 且两者无法比较，即 $\lnot(c\leq d)\land\lnot(d\leq c)$

若 $c,d$ 均为 $B$ 的上界，则不存在上确界。

****** 定理2<<MK147>>

（1） 若 $\forall b\in B\rightarrow b\leq c$ 则 $B$ 的上确界 $\sup\{B\}\leq c$

（2） 若 $\forall b\in B\rightarrow b\geq c$ 则 $B$ 的上确界 $\inf\{B\}\geq c$

******* 证明

仅证（1），（2）同理可证

假设 $\sup\{B\}>c$ 则根据定义 $c$ 是 $B$ 的上界

则 $\sup\{B\}$ 不是 $B$ 的最小上界，故不为上确界，矛盾

故假设不成立，则有 $\sup\{B\}\leq c$

****** 定理3<<MK148>>

若 $A\subset\mathbb{R}_e\land B\subset\mathbb{R}_e$ 其中 $\mathbb{R}_e$ 是[[~/文档/note/实变函数/SBHS.org::MK143][广义实数]]，定义 $C=\left\{a+b\big|a\in A\land b\in B\right\}$

则有 $\sup\{C\}=\sup\{A\}+\sup\{B\}$

******* 证明

******** 当 $|\sup\{A\}|<\infty\land|\sup\{B\}|<\infty$ 时<<MK149>>

由于 $\forall a\in A\rightarrow a\leq\sup\{A\}$ 以及 $\forall b\in B\rightarrow b\leq\sup\{B\}$

故有 $\forall a\in A,\forall b\in B\rightarrow a+b\leq\sup\{A\}+\sup\{B\}$ 即 $\sup\{A\}+\sup\{B\}$ 是 $C$ 的上界

对于任意 $\epsilon\in\mathbb{R}^+$ 有 $\sup\{A\}-\frac{\epsilon}{2}$ 以及 $\sup\{B\}-\frac{\epsilon}{2}$

根据上确界定义可得存在 $a'\in A$ 满足 $a'>\sup\{A\}-\frac{\epsilon}{2}$ 以及 $b'\in B$ 满足 $b'>\sup\{B\}-\frac{\epsilon}{2}$

即对于任意 $\epsilon>0$ 存在 $a'+b'\in C$ 满足 $a'+b'>\sup\{A\} +\sup\{B\}$

综上所述 $\sup\{A\}+\sup\{B\}$ 是 $C$ 的最小上界，即 $\sup\{C\}=\sup\{A\}+\sup\{B\}$

******** 否则

由于 $A\subset\mathbb{R}_e\land B\subset\mathbb{R}_e$ 根据[[~/文档/note/实变函数/SBHS.org::MK224][运算性质]]不能出现 $+\infty+(-\infty)$

则当 $\pm\infty+r$ 或者 $\pm(\infty+\infty)$ 时，显然 $\sup\{A\}+\sup\{B\}=\pm\infty$

[[MK149][同理]]易证 $\sup\{C\}=\sup\{A\}+\sup\{B\}$

****** 定理4<<MK150>>

若 $A\subset\mathbb{R}_e$ 其中 $\mathbb{R}_e$ 是[[~/文档/note/实变函数/SBHS.org::MK143][广义实数]]，则定义 $B=\left\{c\cdot a\big|a\in A\right\}$ 其中 $c\in\mathbb{R}^+$

则有 $\sup\{B\}=c\cdot\sup\{A\}$ 以及 $\inf\{B\}=c\cdot\inf\{A\}$ 

******* 证明

仅证上确界，下确界类似易证

定义 $h_B=\sup\{B\}$ 根据以下证明可得 $\frac{h_B}{c}=\sup\{A\}$

故可得 $\sup\{B\}=c\cdot\sup\{A\}$

******** $\frac{h_B}{c}$ 是 $A$ 的上界

由于是[[MK145][上确界]]，故有 $\forall b\in B\rightarrow h_B\geq b$

进一步根据 $B$ 的定义有 $\forall a\in A\rightarrow\left(\exists b\in B\rightarrow b=c\cdot a\right)$

综上所述 $\forall a\in A\rightarrow h_B\geq c\cdot a\rightarrow\frac{h_B}{c}\geq a$ 即 $\frac{h_B}{c}$ 是 $A$ 的[[MK145][上界]]

******** $\frac{h_B}{c}$ 是 $A$ 上确界

假设 $\frac{h_B}{c}$ 不是 $A$ 的上确界，由于是上界，故存在 $h^*$ 满足 $\forall a\in A\rightarrow h^*\geq a$ 且 $\frac{h_B}{c}>h^*$

则根据 $B$ 的定义有 $\forall b\in B\rightarrow c\cdot h^*\geq c\cdot a$ 则 $c\cdot h^*$ 是 $B$ 的[[MK145][上界]]

则进一步有 $h_B>c\cdot h^*$ 与 $h_B$ 是 $B$ 的[[MK145][上确界]]矛盾

故假设不成立，则 $\frac{h_B}{c}$ 是 $A$ 的上确界

****** 定理6<<MK151>>

若 $A\subset\mathbb{R}_e$ 其中 $\mathbb{R}_e$ 是[[~/文档/note/实变函数/SBHS.org::MK143][广义实数]]，则定义 $-A=\left\{-a\big|a\in A\right\}$ 其中 $c\in\mathbb{R}^-$

则有 $\sup\{-A\}=-\inf\{A\}$

******* 证明

定义 $\alpha=\sup\{-A\}$ 则有 $\forall a'\in-A\rightarrow a'\leq\alpha$ 且 $\forall\epsilon>0\rightarrow\left((\exists -a'\in-A)\rightarrow(\alpha-\epsilon<-a')\right)$

则根据[[~/文档/note/实变函数/SBHS.org::MK265][推论3]]可得 $-\alpha\leq-a'$ 根据 $-A$ 定义可得 $\forall a\in A\rightarrow -\alpha\leq a$

类似可证 $\forall\epsilon>0\rightarrow\left((\exists a'\in A)\rightarrow(a<-\alpha+\epsilon)\right)$

则显然可得 $-\alpha$ 是 $A$ 的[[MK145][下确界]]

****** 定理7<<MK152>>

若 $A\subset\mathbb{R}\land B\subset\mathbb{R}$ 且 $\forall a\in A,\forall b\in B\rightarrow a+b\leq c$

则有 $\sup(A)+\sup(C)\leq c$

******* 证明

根据[[MK145][定义]]可得 $\forall\epsilon>0,\exists a^*\in A\rightarrow a^*+\frac{\epsilon}{2}>\sup(A)$

同理 $\forall\epsilon>0,\exists b^*\in B\rightarrow b^*+\frac{\epsilon}{2}>\sup(B)$

故有 $\sup(A)+\sup(B)<a^*+b^*+\epsilon\leq c+\epsilon$

即对于任意 $\epsilon>0$ 均有 $\sup(A)+\sup(B)<c+\epsilon$ 假设 $\sup(A)+\sup(B)>c$

则取 $\epsilon=\sup(A)+\sup(B)-c$ 则有 $0<0$ 显然与[[~/文档/note/实变函数/SBHS.org::MK5][三岐性]]矛盾

故假设不成立，即有 $\sup(A)+\sup(C)\leq c$

***** 链<<MK153>>

若 $<A,R>$ 是有序集，且 $B\subset A$ 若：

$B$ 是链： $\forall x\forall y(\{x,y\}\subset B\rightarrow xRy\lor yRx)$

$B$ 是反链<<MK154>>： $\forall x\forall y(\{x,y\}\subset B\rightarrow \lnot(xRy)\land\lnot(yRx))$

****** 定理

若 $<A,R>$ 是有序集，且 $B\subset A$ 若 $A$ 中最长的链 $T$ 基数为 $n$ 则 $A$ 可划分为 $n$ 个单元，

每个单元都是一个[[MK154][反链]]

***** 前段<<MK155>>

若 $<S,\leq>$ 为[[MK170][全序集]]，任意 $T$ 满足：

（1） $T\subset S$

（2） $\forall (u,v)\subset S\land u\leq v$ 若 $v\in T$ 则有 $u\in T$

即对于给定的 $v\in S\rightarrow T=\left\{u\big|u\in S,u\leq v\right\}$ ，则称 $T$ 为 $S$ 的前段

当 $T\ne S$ 时称 $T$ 为 $S$ 的真前段

****** 推论<<MK156>>

设 $<S,\leq>$ 为[[MK170][全序集]]，若 $T=\{a\}$ 其中 $a$ 是 $S$ 的[[MK144][最小元]]，则 $T$ 为 $S$ 的前段

******* 证明

定义 $T=\{a\}$ 由于[[MK170][全序集]]，故满足[[MK124][自反性]]即有 $a\leq a$ 又由于 $a$ 是 $S$ 的最小元

故 $\forall c\in S\rightarrow a\leq c$

****** 定理1<<MK157>>

若 $<X,\leq>$ 是 $<Y,\leq>$ 的[[MK155][前段]]，则 $X$ 中有[[MK177][最小元]] $x$ 的充要条件是 $Y$ 中亦有[[MK177][最小元]] $x$

******* 证明

******** 充分

若 $X$ 中有[[MK177][最小元]] $x$ ，由于是前段，故有 $X\subset Y$ 假设存在 $y\in Y$ 满足 $y\leq x$

则根据[[MK155][前段]]定义有 $y\in X$ ，则 $x$ 不为最小元，与题目定义矛盾，故假设不成立

由于是[[MK155][前段]]，则 $<Y,\leq>$ 为[[MK170][全序集]]，则对于任意 $y\in Y$ 均有 $x\leq y\lor y\leq x$

由于假设不成立，故 $y\not\leq x$ 即有 $x\leq y$ ，故 $x$ 亦为 $Y$ 的[[MK177][最小元]]
 
******** 必要

若 $Y$ 中有[[MK177][最小元]] $x$ ，则由于 $X\subset Y$ 显然 $x$ 亦为 $X$ 的[[MK177][最小元]]

****** 定理2<<MK158>>

若 $<X,\leq>$ 是 $<Y,\leq>$ 的[[MK155][前段]]且 $U\cap X\ne\varnothing$ 则有 $<X\cap U,\leq>$ 是 $<Y\cap U,\leq>$ 的[[MK155][前段]]

******* 证明

由于是前段，故有 $X\subset Y$ 则显然有 $X\cap U\subset Y\cap U$

对于任意 $\{u,v\}\subset Y\cap U$ 且 $v\in X\cap U\land u\leq v$

则由于 $v\in X\cap U$ 有 $v\in X$ ，由于 $\{u,v\}\subset Y\cap U$ 则有 $u\in Y$ 以及 $u\in U$

由于 $u\leq v$ 以及 $<X,\leq>$ 是 $<Y,\leq>$ 的[[MK155][前段]]可得 $u\in X$ 进而 $u\in X\cap U$

综上所述，对于任意 $\{u,v\}\subset Y\cap U$ 且 $v\in X\cap U\land u\leq v$ 均有 $u\in X\cap U$

即 $<X\cap U,\leq>$ 是 $<Y\cap U,\leq>$ 的[[MK155][前段]]

****** 定理3（传递性）<<MK159>>

若 $<S,\leq>$ 为[[MK170][全序集]] $T_1,T_2,T_3$ 均为 $S$ 的[[MK15][子集]]且满足 $T_1$ 为 $T_2$ 的[[MK155][前段]]， $T_2$ 为 $T_3$ 的[[MK155][前段]]

则 $T_1$ 为 $T_3$ 的[[MK155][前段]]

******* 证明

显然根据[[MK272][定义]]有 $T_1\subset T_2\subset T_3$ 则根据[[MK17][传递性]]有 $T_1\subset T_3$

对于任意 $\{u,v\}\subset T_3$ 且 $u\leq v$ ，若 $v\in T_1$ 则根据 $T_1\subset T_2\subset T_3$ 则 $v\in T_2$

根据[[MK155][前段定义]]可得 $u\in T_2$ 又由于 $T_1$ 是 $T_2$ 的前段，故同理可得 $v\in T_1$ 推出 $u\in T_1$

综上所述， $T_1$ 为 $T_3$ 的[[MK155][前段]]

**** 相关定理

***** 定理1<<MK160>>

若[[MK143][偏序集]] $<P,\leq>$ 中存在[[MK171][良序集]] $<S,\leq>$ 满足 $S\subset P$ 且有[[MK145][上界]] $b\in P,b\not\in S$

则有 $S\cup \{b\}$ 亦为良序集

****** 证明

由于 $<S,\leq>$ 是[[MK171][良序集]]，故 $<S,\leq>$ 为[[MK170][全序集]] $\forall \{u,v\}\subset S\Rightarrow u\leq v\lor v\leq u$

根据[[MK145][上界]]定义有 $\forall a\in S\Rightarrow a\leq b$ 故显然 $<S\cup\{b\},\leq>$ 仍为[[MK170][全序集]]

则对于任意 $U'\subset S\cup\{b\}$ 取 $U=U'\cap S$ 由于 $S$ 良序集，故对于任意子集 $U\subset S$ 存在[[MK177][最小元]] $p$

若 $a\in U'\land a\ne p$ ，若 $a\ne b$ 则 $a\in U$ 若 $a=b$ 则由于是上界，故有 $p\leq b$

即 $p$ 是 $U'$ 的[[MK177][最小元]]综上所述 $S\cup\{b\}$ 亦为良序集

***** 定理2<<MK161>>

对于任意[[MK170][偏序集]] $<P,\leq>$ 定义集合 $C$ 如下 

（1） $\forall S\in C$ 满足 $S\subset P$ 且 $<S,\leq>$ 是[[MK171][良序集]]

（2） $\forall \{X,Y\}\subset C$ 满足 $X$ 是 $Y$ 的[[MK155][前段]]或 $Y$ 是 $X$ 的[[MK155][前段]]

则有 $<\bigcup_{X\in C} X,\leq>$ 也是[[MK171][良序集]]

****** 证明

******* 并集为全序集

首先证明是全序集，设 $(x,y)\subset\bigcup_{Z\in C} Z$ 则必有 $x\in X\in C,y\in Y\in C$ 

则必满足 $X$ 是 $Y$ 的[[MK155][前段]]，或 $Y$ 是 $X$ 的[[MK155][前段]]其一，这里假设 $X$ 是 $Y$ 的前段

则有 $X\subset Y$ 故得 $\{x,y\}\subset Y$ 由于 $<Y,\leq>$ 是[[MK171][良序集]]，故必为[[MK170][全序集]]

故必满足 $x\leq y,y\leq x$ 其一，故 $\bigcup_{Z\in C} Z$ 为[[MK170][全序集]]

******* 任意子集都有[[MK177][最小元]]

对于任意 $U\subset\bigcup_{Z\in C} Z$ 任取 $u_0\in U$ 则存在一个 $S_0\in C$ 使得 $u_0\in S_0$

定义 $T_0=S_0\cap U$ 则有 $T_0\subset S_0$ 故 $T_0$ 存在[[MK177][最小元]]，记作 $u^*$

对于任意 $u_1\in U$ 同理必有 $u_1\in S_1$ 定义 $T_1=S_1\cap U$

根据 $C$ 的定义，必有 $S_0,S_1$ 中某个必为另一个的[[MK155][前段]]

假设 $S_0$ 为 $S_1$ 的[[MK155][前段]]，则根据[[MK158][定理]]可得 $T_0$ 是 $T_1$ 的[[MK155][前段]]

故若 $u_1\leq u_0$ 则有 $u_1\in T_0$ ，进一步有 $u^*\leq u_1$ 若 $u_0\leq u_1$ 则根据[[MK128][传递性]] $u^*\leq u_0\leq u$

反之若 $S_1$ 为 $S_0$ 的[[MK155][前段]]，则同理可证 $T_1=U\cap S_1$ 是 $T_0=U\cap S_0$ 的[[MK155][前段]]

根据[[MK157][定理]]可得 $T_1$ 中的最小元亦为 $u^*$ ，故必有 $u^*\leq u_1$

综上所述，对于任意 $U\subset\bigcup_{Z\in C} Z$ 均存在 $u^*\in U$ 满足对于任意 $u_1\in U$ 均有 $u^*\leq u_1$

***** 佐恩引理<<MK162>>

若非空偏序集 $\left<P,\leq\right>$ 的每条[[MK153][链]]都有[[MK145][上界]]，则 $P$ 中存在[[MK144][极大元]]

****** 证明

******* 反证假设<<MK163>>

对于非空偏序集 $\left<P,\leq\right>$ 假设命题不成立，即全序子集有上界，但 $P$ 中不存在[[MK144][极大元]]，即满足

（1） 对于任意[[MK170][全序集]] $\left<S,\leq\right>$ 满足 $S\subset P$ 均有上界，即 $\exists b\in P,\forall a\in S\Rightarrow a\leq b$

（2） $\forall x\in P,\exists b\in P\Rightarrow x\leq b$

其中（1）是给定条件，（2）是假设。于是对于任意给定元素 $p\in P$ 做以下推导从而推出矛盾

******* 定义集合 $B(S)$

定义 $S\subset P$ 是 $P$ 的[[MK170][全序集]]，则根[[MK163][据命题（1）]]必有 $p\in P$ 是 $S$ 的上界，即 $\forall a\in S\Rightarrow a\leq p$

对于任意全序子集 $\left<S,\leq\right>$ 定义集合 $B(S)=\left\{p\bit|p\in P-S\land\forall a\in S\Rightarrow a\leq p\right\}$

根据[[MK163][命题（2）]]必有 $p'\in P\Rightarrow p\leq p'$ 则根据[[MK128][传递性]] $\forall a\in S\Rightarrow a\leq p\leq p'$

又由于 $p$ 是 $S$ 的上界，故必有 $p'\not\in S$ 即 $p'\in B(S)$ 故 $B(S)\ne\varnothing$

******* 定义函数 $\phi(S)$

对于的[[MK170][全序子集]] $\left<S,\leq\right>$ 有对应的集合 $B(S)$ 必为非空集合

故由于[[MK14][选择公理]]可知存在选择函数 $\psi(B(S))\in B(S)$ 则定义 $\phi(S)=\psi(B(S))$ 显然满足 $\phi(S)\in B(S)$

根据 $B(S)$ 的定义有 $\forall s\in S\rightarrow s\leq\phi(S)$

******* 定义集合 $C$ <<MK164>>

对于任意给定的元素 $p_0\in P$ ，定义集合 $C$ ，其中的元素是所有满足以下条件的 $S\subset P$ 

（1） $S$ 是[[MK171][良序集]]

（2） [[MK144][最小元]]为 $p_0$

（3） 若 $T\subset S$ 是[[MK170][全序子集]]的非空[[MK155][真前段]]，则 $S-T$ 的[[MK144][最小元]]为 $\phi(T)$

首先推断 $C\ne\varnothing$ ，定义 $\{p_1\}=\phi(\{p_0\}),\phi(\{p_0,p_1\})=p_2$ 定义 $S_3=\{p_0,p_1,p_2\}$ 显然 $\left<S,\leq\right>$ 是[[MK171][良序集]]

且最小元为 $p$ ，$S$ 的真前段有且仅有 $\{p_0\},\{p_0,p_1\}$ 显然 $S-T$ 的最小元为 $\phi(T)$ ，故满足条件。

显然对于任意 $S_n=\{p_0,...,p_n\}$ 若 $S_n\in C$ 则定义 $S_{n+1}=\{p_0,...,p_n,\phi(S_n)\}$ 易证 $S_{n+1}\in C$

则根据数学归纳法，对于任意 $S_n,n\geq3$ 均有 $S_n\in C$

******* 证明 $C$ 中任意两个元素其中一个为另一个的前段

若 $S,S'\in P$ 定义 $R$ 为最大的 $S,S'$ 的共有[[MK155][前段]]，由[[MK164][ $C$ 的定义]]可得 $p_0\in S\cap S'$

根据[[MK156][推论]]可得 $\{p_0\}$ 是 $S,S'$ 的公共前段，故 $R\ne\varnothing$ 。若 $R$ 为真前段，则有 $\phi(R)\in S-R,\phi(R)\in S'-R$

且 $\phi(R)$ 为 $S-R,S'-R$ 的[[MK29][最小元素]]，则 $R\cup \phi(R)$ 亦为 $S,S'$ 的共有[[MK57][前段]]，与 $R$ 定义冲突。

故 $R$ 必定等于其中一个，即 $S$ 是 $S'$ 的前段，或者 $S'$ 是 $S$ 的前段必成立其一。

******* 定义并集 $U$

定义 $U$ 为所有 $C$ 中所有元素的并集，根据以下三步证明可知 $U$ 亦满足 $C$ 的定义，故 $U\in C$

******** 证明良序

根据[[MK161][定理2]]可得 $\left<U,\leq\right>$ 亦是[[MK171][良序集]]

******** 证明最小元是 $p_0$

对于任意 $x\in U$ 根据定义必有 $S\subset U$ 满足 $x\in S\land S\in C$

由于对于任意 $S\in C$ 均有 $p_0$ 是 $S$ 的最小元，则有 $p_0\leq x$

******** 证明若 $T\subset U$ 是非空[[MK155][真前段]]，则 $U-T$ 的[[MK144][最小元]]为 $\phi(T)$

若 $T$ 为 $U$ 的非空[[MK155][真前段]]，则 $U-T$ 非空，则对于某个 $u\in U-T$ 必然存在 $S\in C\Rightarrow u\in S$

由于 $U$ 良序，故必为全序，故对于任意 $t\in T$ 必存在 $t$ 与 $u$ 的偏序关系

由于前段的定义以及 $u\not\in T$ 故得 $t\leq u$

且由于 $\forall t\in T\subset U$ 则必有 $\exists S'\in C\Rightarrow t\in S'$ 根据 $C$ 的定义 $S,S'$ 其中一个必为另一个的[[MK57][前段]]

无论哪种情况，必有 $t\in S$ 故有 $\forall t\in T\rightarrow t\in S$ 故有 $T\subset S$

另外若 $\forall (a,b)\subset S$ 若满足 $a\leq b,b\in T$ 则根据 $T$ 为 $U$ 的[[MK57][前段]]有 $a\leq b$ 故 $a\in T$

故 $T$ 满足 $T\subset S$ 及 $\forall (a,b)\subset S,a\leq b,b\in T\Rightarrow a\in T$ 

故 $T$ 亦为 $S$ 的[[MK57][前段]]，故 $S-T$ 的[[MK29][最小元素]]为 $\phi(T)$

且根据定义 $\forall S\in C\land T\subset S$ 其 $S-T$ 的最小元素为 $\phi(T)$

根据 $U$ 的定义可得 $U-T$ 的最小元素亦为 $\phi(T)$

******* 推导矛盾

由于 $U$ 是良序，故为全序。则根据条件 $U$ 有上界，且 $P$ 无[[MK144][极大元]]则 $\phi(U)$ 必不为空集，定义 $\{b\}=\phi(U)$

由于 $\left<U,\leq>$ 是全续集，及选择函数定义有 $\forall u\in U,u\leq b$ 且 $b\not\in U$ 故：

（1） 根据[[MK160][定理1]]可得 $\left<U\cup\{b\},\leq\right>$ 亦为良序集

（2） 亦有 $\forall u\in U\cup\{b\}\Rightarrow p_0\leq u$

（3） 若 $T\subset U\cup \{b\}$ 为非空[[MK155][真前段]]，则 $U-T$ 的[[MK144][最小元]]为 $\phi(T)$

故 $U\cup\phi(U)$ 亦为满足条件 $C$ 的元素，这与 $U$ 的定义矛盾，故[[MK163][假设]]不成立，即 $\left<P,\leq\right>$ 中有最大元

*** 拟序关系<<MK165>>

定义集合 $A$ 若：

（1） $R$ 是 $A$ 上的[[MK111][二元关系]]，即 $R\subset A\times A$

（2） $R$ 具有[[MK125][反自反性]]、[[MK127][反对称性]]以及[[MK128][传递性]]，即 $\lnot xRx,xRy\land yRx\rightarrow x=y, xRy\land xRz\rightarrow xRz$

则称 $R$ 为 $A$ 上的拟序关系，且 $A$ 称为有拟序集，记作 $<A,R>$

**** 推论

非空集合 $A$ 上的拟序关系 $R$ 必然有[[MK127][反对称性]]

***** 证明

假设 $\{x,y\}\subset A$ 有 $xRy,yRx$ 且有 $x\ne y$ ，即不满足反对称性

则根据[[MK128][传递性]]有 $xRy\land yRx\rightarrow xRx$ 与[[MK125][反自反性]]矛盾。

故满足反对称性。

**** 元<<MK166>>

若 $<A,<>$ 是拟序集，且 $B\subset A$ 则 $b$ 是：

$B$ 的最小元： $b\in B\land\forall x(x\in B\rightarrow b< x)$

$B$ 的最大元： $b\in B\land\forall x(x\in B\rightarrow x<b)$

$B$ 的极小元： $b\in B\land\lnot\exists x(x\in B\land x< b)$ 

$B$ 的极大元： $b\in B\land\lnot\exists x(x\in B\land b<x)$ 

***** 定理<<MK167>>

（1） $B$ 的最大（小）元必为 $B$ 的极大（小）元

（2） 如果 $B$ 有最大（小）元，则它是唯一的

（3） 如果 $B$ 是有限集，则B的极大（小）元恒存在

（3） 最大（小）元未必存在，存在则唯一

（4） 极大（小）元对有限集必然存在，未必唯一

**** 排列<<MK168>>

若 $<A,<>$ 是拟序集，存在有序组 $<a_1,...,a_n>$ 满足：

（1） $|A|=n<\infty$

（2） $a_i<a_{i+1}$

（3） $a_i\in A$

则定义 $a_1<...<a_n$ 为 $A$ 基于 $<$ 排列

***** 定理<<MK169>>

对于拟序集 $<A,\prec>$ ：

（1） 每一个 $a_i\in A$ 排列 $a_1<...<a_n$ 正好出现一次

（2） 排列唯一

****** 证明

根据定义 $A$ 有基于 $\prec$ 的排列 $\delta_1\prec...\prec\delta_k$ 即有有序组 $r=<\delta_1,...,\delta_k>$ 满足 $\delta_i\prec\delta_{i+1}$

******* （1）

由于是[[MK165][拟序关系]]，则对于任意 $i\ne j\land i<j$ 根据 $\delta_i\prec...\prec\delta_j$ 以及[[MK128][传递性]]有 $\delta_i\prec\delta_j$

则根据[[MK125][反自反性]]有 $\delta_i\ne\delta_j$ 同理有 $\delta'_i\ne\delta'_j$ 由于 $k=|A|=|r|$ 

故根据鸽笼原理，每一个 $A$ 中的元素在 $r$ 上正好出现一次

******* （2）

根据定义 $A$ 有基于 $\prec$ 的排列 $\delta_1\prec...\prec\delta_k$ 即有有序组 $r=<\delta_1,...,\delta_k>$ 满足 $\delta_i\prec\delta_{i+1}$

假设存在有序组 $r'=<\delta'_1,...,\delta'_k>\ne r$ 亦满足 $\delta'_i\prec\delta'_{i+1}$ 则至少存在一个 $\delta_i\ne\delta'_i$ 假设 $\delta_k\ne\delta'_k$

根据（1）每一个 $A$ 中的元素在 $r,r'$ 上正好出现一次

故必有 $\delta'_{k'}$ 与 $\delta'_k$ 互换位置，则在 $r$ 中若有 $\delta’_k\prec...\prec\delta'_{k'}$ 则在 $r'$ 中有 $\delta’_{k‘}\prec...\prec\delta'_{k}$

进一步根据传递性有 $\delta’_k\prec\delta'_{k'}$ 以及 $\delta’_{k'}\prec\delta'_{k}$ 与[[MK127][反对称性]]矛盾，则假设不成立

即不存在 $r'$

*** 全序关系<<MK170>>

若[[MK143][偏序集]] $(P,\leq)$ 中任意两个元素 $(a,b)\subset P$ 至少成立 $a\leq b,b\leq a$ 中的一个

则称 $<P,\leq>$ 为全序集

*** 良序关系<<MK171>>

集合 $S$ 上的[[MK143][偏序关系]] $\leq$ 满足：

（1） $\left<S,\leq\right>$ 为[[MK170][全序集]]

（2） 任意非空子集 $T\subset S$ 都有[[MK144][最小元]]

满足此定义的集合与偏序关系称为良序集，记作 $\left<S,\leq\right>$

**** 定理<<MK172>>

良序集的子集亦为良序集

***** 证明

若 $<S,\leq>$ 是[[MK171][良序集]]，有 $L\subset S$

则对于任意 $\{a,b\}\subset L$ 均有 $\{a,b\}\subset S$ 故有 $a\leq b\lor b\leq a$ 则 $<L,\leq>$ 为[[MK170][全序集]]

对于任意 $K\subset L$ 均有 $K\subset S$ 故 $K$ 中有最小元，故 $<L,\leq>$ 是[[MK171][良序集]]

**** 良序定理<<MK173>>

任意非空集合 $X$ 均存在其上的[[MK143][偏序关系]] $\leq$ 使得 $\left<X,\leq\right>$ 是[[MK171][良序关系]]

***** 证明

****** 定义 $\left<P,\preceq\right>$ <<MK174>>

定义 $\rho(X)$ 是 $X$ 的[[MK20][幂集]]，定义集合 $P$ 满足对于任意 $\left<Y,\leq_Y\right>\in P$ 有：

（1） $Y\in\rho(X)$

（2） $\left<Y,\leq_Y\right>$ 是[[MK171][良序关系]]

进一步在 $P$ 上定义关系 $\preceq$ 为 $\left<Y_1,\leq_{Y_1}\right>\preceq\left<Y_2,\leq_{Y_2}\right>$ 为：

（1） $\leq_{Y_1}\subset\leq_{Y_2}$ 且 $Y_1\subset Y_2$

（2） 在 $\left<Y_2,\leq_{Y_2}\right>$ 下 $Y_1$ 是 $Y_2$ 的[[MK155][前段]]

****** 证明 $\left<P,\preceq\right>$ 是[[MK143][偏序关系]]

则对于代数结构 $\left<P,\preceq\right>$ 有：

（1） 对于任意 $\left<Y,\leq_Y\right>\in P$ 有 $Y\subset Y\land \leq_Y\subset\leq_Y$ 且 $Y$ 是 $Y$ 的[[MK155][前段]]，即 $\left<Y,\leq_{Y}\right>\preceq\left<Y,\leq_{Y}\right>$

（2） 若有 $\left<Y_1,\leq_{Y_1}\right>\preceq\left<Y_2,\leq_{Y_2}\right>\land\left<Y_2,\leq_{Y_2}\right>\preceq\left<Y_1,\leq_{Y_1}\right>$

     则根据[[MK16][自反性]]显然 $\left<Y_1,\leq_{Y_1}\right>=\left<Y_2,\leq_{Y_2}\right>$ 

（3） 若有 $\left<Y_1,\leq_{Y_1}\right>\preceq\left<Y_2,\leq_{Y_2}\right>\land\left<Y_2,\leq_{Y_2}\right>\preceq\left<Y_3,\leq_{Y_3}\right>$

     则有 $Y_1\subset Y_3$ 以及 $\leq_{Y_1}\subset\leq_{Y_3}$ 又根据[[MK159][传递性]]可得在 $\left<Y_3,\leq_{Y_3}\right>$ 下 $Y_1$ 是 $Y_3$ 的[[MK155][前段]]

综上所述 $\left<P,\preceq\right>$ 满足[[MK124][自反性]]，[[MK127][反对称性]]以及[[MK128][传递性]]，是[[MK143][偏序关系]]

****** 证明 $\left<P,\preceq\right>$ 有[[MK144][极大元]]

对于任意 $\left<P,\preceq\right>$ [[MK153][链]] $C\subset P$ 定义 $Y^*=\bigcup_{\left<Y,\leq_Y\right>\in C}Y,\leq_{Y^*}=\bigcup_{\left<Y,\leq_Y\right>\in C}\leq_{Y}$

易证 $\left<Y^*,\leq_{Y^*}\right>$ 亦为[[MK143][偏序关系]]且任意 $\left<Y,\leq_Y\right>\in C$ 有 $\left<Y,\leq_{Y}\right>\preceq\left<Y^*,\leq_{Y^*}\right>$

则 $\left<Y^*,\leq_{Y^*}\right>$ 是 $C$ 在 $\left<P,\preceq>$ 中的[[MK145][上届]]，根据[[MK162][佐恩引理]]可得 $\left<P,\preceq\right>$ 存在[[MK144][极大元]]

定义为 $\left<M,\leq_M\right>$

****** 证明 $M=X$

假设 $M\ne X$ 根据[[MK174][定义]]可得 $M\subset X$ 则存在 $a\in X-M$

定义 $M'=M\cup\{a\}$ 定义 $\leq_{M'} =\leq_M\cup\left\{\left<x,a\right>\big|x\in M\right\}$

易证 $\left<M',\leq_{M'}\right>$ 亦为[[MK171][良序关系]]且在 $\left<M',\leq_{M'}\right>$ 下 $M$ 是 $M'$ 的[[MK155][前段]]

进而有 $\left<M,\leq_M\right>\preceq\left<M',\leq_{M'}\right>$ 与 $\left<M,\leq_M\right>$ 是[[MK144][极大元]]矛盾

故假设不成立 $X=M$ 进而有 $\left<X,\leq_M\right>$ 是[[MK171][良序关系]]

**** 超限归纳

任意[[MK171][良序关系]] $\left<X,\leq\right>$ 若对于命题 $P$ 满足：

（1） $P(x_0)$ 为真，其中 $x_0$ 是 $X$ 的[[MK144][最小元]]

（2） 对于任意 $a<b,a\ne b$ 均有命题 $P(a)$ 为真，则 $P(b)$ 为真

则对于任意 $a\in X$ 均有命题 $P(a)$ 为真

***** 证明

对于任意[[MK171][良序关系]] $\left<X,\leq\right>$ 满足条件，假设存在 $a\in X$ 满足 $P(a)$ 为假

则定义集合 $S=\left\{a\big|a\in X\land(\lnot P(a))\right\}$ 显然 $S$ 非空，则根据[[MK171][良序]]可得存在 $s\in S$

满足对于任意 $s'\in S$ 均有 $s<s'$ 即 $S$ 上的[[MK144][最小元]]

则若 $s=x_0$ 则根据条件（1）可得 $P(x_0)$ 为真，矛盾

若 $s\ne x_2$ 则 $x_0\in Z=\left\{x\big|x\in X\land x<s\land x\ne s\right\}$ 即 $Z$ 非空

显然根据 $s$ 定义可得任意 $x\in Z$ 满足 $x<s$ 均有 $x\not\in S$ 则有 $P(x)$ 为真

则根据条件（2）可得 $P(s)$ 为真，矛盾

综上所述，假设不成立，即不存在 $a\in X$ 满足 $P(a)$ 为假

** 函数（映射）

*** 相关定义

**** 函数（映射）定义<<MK175>>

如果 $X,Y$ 为集合 $f\subset X\times Y$ 是[[MK111][二元关系]]，若：

（1） $(\forall x((x\in X)\rightarrow(\exists y(<x,y>\in f))))$ 

（2） $(\forall y_1(\forall y_2(((\left<x,y_1\right>\in f)\land(\left<x,y_2\right>\in f))\rightarrow(y_1=y_2))))$

则称 $f$ 是 $X$ 到 $Y$ 上的函数

当 $X=X_1\times...\times X_n$ 时 $f$ 称为 $n$ 元函数

记作 $f:X\rightarrow Y$ 特别的当 $<x,y>\in f$ 时可表示为 $y=f(x)$ 此时 $x$ 成为自变量 $y$ 成为因变量

基于上述定义，进一步对于任意 $Z\subset X$ 定义 $f(Z)=\left\{f(x)\big|x\in Z\right\}$

***** 推论1

若 $X,Y$ 的[[MK35][基数]]为 $|X|=m,|Y|=n$ 则可能的函数个数为 $n^m$

****** 证明

定义 $f:X\rightarrow Y$ ，则定义，对于任意一个 $x\in X$ 均有唯一的关系 $<x,y>\in f$

故必然有且仅有 $|X|$ 个元素属于 $f$ ，每个元素可从 $Y$ 中选择一个元素作为对应。

故若 $|X|=m,|Y|=n$ ，则最终有 $n^m$

***** 推论2

若集合 $X=X_1\times...\times X_n,\ Y=Y_1\times...\times Y_m$ 则同理可定义多元函数 $f\in X\times Y$ 满足：

（1） $\forall x(x\in X\rightarrow\exists y(<x,y>\in f))$ 

（2） $\forall y_1\forall y_2(<x,y_1>\in f\land <x,y_2>\in f\rightarrow y_1=y_2)$

此时可记作 $f(x_1,...,x_n)=[y_1,...,y_m]$

**** 函数的相等

若 $f:A\rightarrow B,g:C\rightarrow D$ 是两个函数，若：

（1） $A=C\land B=D$

（2） $\forall x(x\in A\rightarrow f(x)=g(x))$

则称两函数相等 $f=g$ 

**** 函数的包含

若 $f:A\rightarrow B,g:C\rightarrow D$ 是两个函数，若：

（1） $A\subset C\land B=D$

（2） $\forall x(x\in A\rightarrow f(x)=g(x))$

则称两函数相等 $f\subset g$ 

**** 子集的映像（值域）

***** 定义

若 $f:A\rightarrow B,A\subset B$ 则将 $f(A)$ 称作 $A$ 的映像，定义为 $f(A)=\left\{y\big|x\in A\land y=f(x)\right\}$

***** 性质

\begin{aligned}
f(A\cup B)&=f(A)\cup f(B)\\
f(A\cap B)&\subset f(A)\cap f(B)\\
f(A)-f(B)&\subset f(A-B)\\
\end{aligned}

****** 证明

仅证 $f'(A\cup B)=f'(A)\cup f'(B)$ 

根据[[~/文档/note/数理逻辑/sllj.org::MK46][结合律]]，[[MK58][并运算]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]，对于任意 $y$

\begin{aligned}
&y\in f'(A\cup B)\\
{|\!\!\!=\!\!\!|}&x\in A\cup B\land y=f(x)\\
{|\!\!\!=\!\!\!|}&(x\in A\lor x\in B)\land y=f(x)\\
{|\!\!\!=\!\!\!|}&(x\in A\land y=f(x))\lor(x\in B\land y=f(x))\\
{|\!\!\!=\!\!\!|}&y\in f'(A)\lor y\in f'(B)\\
{|\!\!\!=\!\!\!|}&y\in f'(A)\cup f'(B)\\
\end{aligned}

故根据[[MK2][外延公理]]可得 $f'(A\cup B)=f'(A)\cup f'(B)$ 

*** 特殊的函数类型

**** 单射<<MK176>>

若 $f$ 是 $X$ 到 $Y$ 上的函数，对于任意 $\{x_1,x_2\}\subset X\land x_1\ne x_2$ 均有 $f(x_1)\ne f(x_2)$ 则称 $f$ 为单射函数

***** 传递性<<MK177>>

若 $N,A,B$ 为集合，存在单射函数 $\Phi:N\rightarrow B$ 和 $\Psi:B\rightarrow A$ 则[[MK187][复合函数]] $P:A\rightarrow B$ 亦为单射函数

****** 证明

根据[[MK187][函数合成]]，合成映射 $P:N\rightarrow B\rightarrow A$ 亦为[[MK175][函数]]

根据定义：

（1） 对于任意 $\{x_1,x_2\}\subset N\land x_1\ne x_2$ 均有 $\Phi(x_1)\ne \Phi(x_2)$ 且 $\{\Phi(x_1),\Phi(x_1)\}\subset B$

（2） 对于任意 $\{\Phi(x_1),\Phi(x_2)\}\subset B\land \Phi(x_1)\ne\Phi(x_2)$ 均有 $\Psi(\Phi(x_1))\ne\Psi(\Phi(x_2))$ 

     且 $\{\Psi(\Phi(x_1)),\Psi(\Phi(x_2))\}\subset A$ 

故对于任意 $\{x_1,x_2\}\subset N$ 均有 $\Psi(\Phi(x_1))\ne\Psi(\Phi(x_2))$ 且 $\{\Psi(\Phi(x_1)),\Psi(\Phi(x_2))\}\subset A$ 

故 $P$ 亦为单射函数

***** 蕴含双射<<MK178>>

若 $f$ 是 $X$ 到 $Y$ 上的单射函数的充要条件是存在 $S\subset Y$ 使得 $f:X\to S$ 为双射

****** 证明

******* 充分

由于 $f$ 是[[MK175][函数]]，故对于任意 $x\in X$ 均有 $f(x)\in Y$

则根据[[MK5][分离公理模式]]定义集合 $S=\left\{y\big|\exists x\in X\rightarrow f(x)\in Y\right\}$

则由定义可知 $S$ 对于函数 $f:X\to S$ 满足[[MK179][满射]]，故其为[[MK181][双射]]

******* 必要

显然。

**** 满射<<MK179>>

若 $f$ 是 $X$ 到 $Y$ 上的函数满足 $(\forall y((y\in Y)\rightarrow(\exists x((x\in X)\land (\left<x,y\right>\in f)))))$ 则称为满射函数

***** 传递性<<MK180>>

若 $N,A,B$ 为集合，存在满射函数 $\Phi:N\rightarrow B$ 和 $\Psi:B\rightarrow A$ 则[[MK187][复合函数]] $P:A\rightarrow B$ 亦为满射函数

****** 证明

根据[[MK187][函数合成]]，合成映射 $P:N\rightarrow B\rightarrow A$ 亦为[[MK175][函数]]

根据定义：

（1） 对于任意 $y_1\in B$ 均有 $x\in N\land \Phi(x)=y$

（2） 对于任意 $y_2\in A$ 均有 $y_1\in B\land\Psi(y_1)=y_2$ 

故对于任意 $y_2\in A$ 均有 $x\in N\land \Psi(\Phi(x))=y_2$ 

故 $P$ 亦为满射函数

***** 蕴含逆[[MK176][单射]]<<MK332>>

若 $f:X\to Y$ 是[[MK179][满射]]，则存在 $g:Y\to X$ 是[[MK176][单射]]

****** 证明

定义 $f'(y)=\left\{x\big|x\in X\land f(x)=y\right\}$ 由于是[[MK179][满射]]，故对于任意 $y\in Y$ 均有 $f'(y)\ne\varnothing$

则根据[[MK14][选择公理]]可得存在选择函数 $h$ 满足 $h(f'(y))\in f'(y)$ ，则定义 $g:Y\to X$ 为 $g(y)=h(f'(y))$

对于任意 $y_1\ne y_2$ 假设 $g(y_1)=g(y_2)$ 则 $f(g(y_1))=y_1=y_2=f(g(y_2))$

即对于 $g(y_1)\in X$ 有 $\left<g(y_1),y_1\right>\in f,\left<g(y_1),y_2\right>\in f$ ，与 $f$ 是[[MK175][函数]]矛盾

故假设不成立，即对于任意 $y_1\ne y_2$ 均有 $g(y_1)\ne g(y_2)$ ，即 $g$ 是[[MK176][单射]]

**** 双射<<MK181>>

若 $f$ 是 $X$ 到 $Y$ 上的函数，且 $f$ 既是[[MK176][单射函数]]又是[[MK179][满射函数]]，则称为双射函数，即一一对应。

***** 传递性<<MK182>>

若 $N,A,B$ 为集合，存在双射函数 $\Phi:A\rightarrow N$ 和 $\Psi:N\rightarrow B$ 则[[MK187][复合函数]] $P=\Phi\cdot\Psi:A\rightarrow B$ 亦为双射函数

****** 证明

根据[[MK177][单射传递性]]和[[MK180][满射传递性]]可得双射亦传递

***** 并双射1<<MK183>>

定义 $\phi_i:A_i\to B_i$ 是双射函数，且对于任意 $i\ne j$ 均有 $A_i\cap A_j=\varnothing,B_i\cap B_j=\varnothing$

则 $\phi=\bigcup_{i\in I}\phi_i$ 以为双射函数

****** 证明

对于任意 $\{x,y\}\subset\bigcup_{i\in I} A_i$ 根据[[MK59][广义并定义]]必有 $x\in A_i,y\in A_j$

则根据 $\{A_n\}$ 互不相交有 $x\ne y$ ，则有 $\phi(x)\in B_i,\phi(y)\in B_j$

若 $i\ne j$ 则根据 $\{B_n\}$ 互不相 有 $\phi(x)\ne\phi(y)$

若 $i=j\land x\ne y$ 则根据 $\phi_i$ 是双射可得 $\phi_i(x)\ne\phi_i(y)$ 故 $\phi$ 是[[MK176][单射]]

又由于对于任意 $y\in\bigcup_{i\in I} B_i$ 有 $y\in B_i$ 则由于 $\phi_i$ 是双射，故存在 $x\in A_i$ 满足 $\phi_i(x)=y$

即 $\phi$ 是[[MK179][满射]]，则 $\phi$ 是[[MK181][双射]]

***** 并双射2<<MK184>>

定义 $\phi_i:A_i\to B_i$ 是双射函数，且对于任意 $i<j$ 均有 $\phi_i\subset\phi_j$ 则 $\phi=\bigcup_{i\in\mathbb{N}}\phi_i$ 亦为双射函数

****** 证明

定义 $A=\bigcup_{i\in\mathbb{N}} A_i,B=\bigcup_{i\in\mathbb{N}} B_i$

******* 是函数

对于任意 $x\in A$ 必有 $x\in A_i$ 进而可得 $<x,\phi_i(x)>\in\phi_i$ 则根据 $\phi=\bigcup_{i\in\mathbb{N}}\phi_i$ 可得 $<x,\phi_i(x)>\in\phi$

对于任意 $x\in A$ 假设存在 $\{y_1,y_2\}\subset B$ 满足 $<x,y_1>\in\phi\land<x,y_2>\in\phi$

则存在 $\phi_i,\phi_j$ 满足 $<x,y_1>\in\phi_i\land<x,y_2>\in\phi_j$ 显然 $i,j$ 是整数

则定义 $k=\max(i,j),z=\min(i,j)$ 后必有 $\phi_z\subset\phi_k$ ，即 $<x,y_1>\in\phi_k\land<x,y_2>\in\phi_k$

这与 $\phi_k$ 是双射函数矛盾，故假设不成立

综上所述，根据[[MK175][函数定义]]可得 $\phi$ 是函数

******* 是双射

对于任意 $\{x_1,x_2\}\in A$ 有 $x_1\in A_i,x_2\in A_j$ 则存在 $\phi_i,\phi_j$ 满足 $\phi_i(x_1),\phi_j(x_2)$

显然 $\{i,j\}\subset\mathbb{N}$ 则可取 $k=\max(i,j),z=\min(i,j)$ 故根据条件必有 $\phi_z\subset\phi_k$

即 $\{<x_1,\phi_k(x_1)>,<x_2,\phi_k(x_2)>\}\subset \phi_k$ 又由于 $\phi_k$ 是[[MK176][单射]]，故可得 $\phi_k(x_1)\ne\phi_k(x_2)$

根据 $\phi$ 定义可得 $\{<x_1,\phi_k(x_1)>,<x_2,\phi_k(x_2)>\}\subset \phi$ 又根据上一步可得 $\phi$ 是[[MK175][函数]] 

故可得 $\phi(x_1)=\phi_k(x_1)\ne\phi_k(x_2)=\phi(x_2)$ 即 $\phi$ 是[[MK176][单射]]

对于任意 $y\in B$ 根据其定义，可得存在 $\phi_i$ 使得 $y\in B_i$ ，由于 $\phi_i$ 是双射函数，故存在 $x\in A_i$

满足 $<y,x>\in\phi_i$ ，又根据 $\phi$ 定义可得 $<x,y>\in\phi$ 即 $\phi$ 是[[MK179][满射]]

综上所述， $\phi$ 是[[MK181][双射]]

***** 子双射<<MK185>>

定义 $\phi:A\to B$ 是双射函数，对于任意 $C\subset A$ 定义 $\phi'=\left\{<x,y>\big|<x,y>\in\phi\land x\in C\right\}$

则有 $\phi'$ 仍为双射函数

****** 证明

假设 $\phi'$ 不是[[MK179][满射]]，则存在 $y\in\phi(C)$ 使得 $\forall x\in C\rightarrow \phi'(x)\ne y$

又由于 $\phi$ 是双射，则存在 $x\in A$ 使得 $\phi(x)=y$ 若 $x\not\in C$ 则与 $\phi'$ 定义矛盾

故假设不成里 $\phi'$ 是满射

假设 $\phi'$ 不是[[MK176][单射]]，则存在 $\{x_1,x_2\}\subset C$ 使得 $\phi'(x_1)=\phi'(x_2)=y$

则根据 $\phi'$ 定义则有 $\phi(x_1)=\phi(x_2)=y$ 与 $\phi$ 是双射矛盾，假设不成立

综上所术 $\phi'$ 亦为双射

***** 相分离<<MK186>>

定义 $\phi:A\to B$ 是双射函数，若 $A=\bigcup_{i=1}^\infty A_i$ 且 $A_i$ 互不相交

则有 $B=\bigcup_{i=1}^\infty\phi(A_i)$

****** 证明

对于任意 $b\in\bigcup_{i=1}^\infty\phi(A_i)$ 可得 $b\in\phi(A_i)$ 即存在 $a\in A_i\rightarrow \phi(a)=b\in B$

则 $B\subset\bigcup_{i=1}^\infty\phi(A_i)$ 又由于任意 $a\in A$ 均有 $\phi(a)\in B$ 故有 $\bigcup_{i=1}^\infty\phi(A_i)\subset B$

故根据[[MK16][自反性]]可得 $B=\bigcup_{i=1}^\infty\phi(A_i)$

*** 函数的计算

**** 函数的复合<<MK187>>

若 $f:X\rightarrow Y,g:Y\rightarrow Z$ 是两个函数，则其[[MK118][合成关系]] $f\cdot g:X\to Z$ 亦为函数

当 $<x,z>\in f\cdot g$ 时记作 $z=g(f(x))$

***** 证明

对于任意 $x\in X$ 根据[[MK175][函数定义]]有对应的 $y\in Y$ 使得 $<x,y>\in f$ 同理有 $<y,z>\in g$ 故有 $<x,z>\in f\cdot g$

即 $\forall x(x\in X\rightarrow\exists z(<x,z>\in f\cdot g))$

若 $z_1,z_2$ 满足 $\{<x,z_1>,<x,z_2>\}\subset f\cdot g$ 则根据[[MK118][合成关系]]定义存在 $\{<x,y_1>,<x,y_2>\}\subset Y$

根据[[MK175][函数定义]]有 $y_1=y_2$ 同理亦有 $z_1=z_2$ 即 $\forall z_1\forall z_2(<x,z_1>\in f\cdot g\land <x,z_2>\in f\cdot g\rightarrow z_1=z_2)$

故 $f\cdot z$ 亦为函数

**** 函数求逆<<MK188>>

若 $f$ 是 $X$ 到 $Y$ 上的函数， $f$ 的[[MK117][逆]]记作 $f^{-1}$

则 $f^{-1}$ 为[[MK175][函数]]的充要条件为 $f$ 是[[MK181][双射函数]]，此时 $f^{-1}$ 称为 $f$ 的逆函数

***** 证明

****** 充分

若 $f$ 是双射函数，则一一对应，故逆函数存在

****** 必要

若 $f$ 存在逆函数，则若 $f$ 不是[[MK179][满射]]，则存在 $y\in Y$ 使得 $\forall x(<x,y>\not\in f)$

即 $\exists y(\forall x(<y,x>\not\in f^{-1}))$ 则不满足[[MK175][函数定义]]中第一条

若 $f$ 不是[[MK176][单射]]，则存在 $x_1\ne x_2$ 使得 $<x_1,y>\in f\land<x_2,y>\in f$

则有 $<y,x_1>\in f\sim\land<y,x_2>\in f\sim\land x_1\ne x_2$ 则不满足[[MK175][函数定义]]中第二条

故 $f$ 必为[[MK181][双射函数]]，否则 $f\sim$ 不是函数

***** 双射性质

****** 性质1<<MK189>>

\begin{aligned}
\left(f^{-1}\right)^{-1}&=f\\
f^{-1}\cdot f&=E_X\\
f\cdot f^{-1}&=E_Y\\
(g\cdot f)^{-1}&=f^{-1}\cdot g^{-1}\\
\end{aligned}

******* 证明

仅证 $(f\cdot g)^{-1}=g^{-1}\cdot f^{-1}$ 定义 $f:X\rightarrow Y,g:Y\rightarrow Z$ 是两个[[MK181][双射函数]]

根据[[MK188][逆函数定义]]，[[~/文档/note/数理逻辑/sllj.org::MK45][交换律]]以及[[~/文档/note/数理逻辑/sllj.org::MK40][替换原理]]可得对于任意 $<z,x>\in (f\cdot g)^{-1}$ 均有

\begin{aligned}
&<z,x>\in(f\cdot g)^{-1}\\
{|\!\!\!=\!\!\!|}&<z,x>\in(f\cdot g)\sim\\
{|\!\!\!=\!\!\!|}&<x,z>\in(f\cdot g)\\
{|\!\!\!=\!\!\!|}&x\in X\land z\in Z\land\exists y(y\in Y\land <x,y>\in f\land <y,z>\in g)\\
{|\!\!\!=\!\!\!|}&z\in Z\land x\in X\land\exists y(y\in Y\land <x,y>\in f\sim \land <y,z>\in g\sim)\\
{|\!\!\!=\!\!\!|}&z\in Z\land x\in X\land\exists y(y\in Y\land <x,y>\in f^{-1} \land <y,z>\in g^{-1})\\
{|\!\!\!=\!\!\!|}&<z,y>\in f^{-1}\cdot g^{-1}\\
\end{aligned}

即 $\forall z\forall x\left(<z,x>\in(g\cdot f)^{-1}{|\!\!\!=\!\!\!|}<z,x>\in f^{-1}\cdot g^{-1}\right)$ 由于函数是[[MK111][二元关系]]，故仅包含 $<a,b>$ 项

故即任意 $\forall L\left(L\in(f\cdot g)^{-1}{|\!\!\!=\!\!\!|}L\in f^{-1}\cdot g^{-1}\right)$ ，则根据[[MK2][外延公理]]可得 $(g\cdot f)^{-1}=f^{-1}\cdot g^{-1}$

****** 性质2<<MK190>>

[[MK181][双射函数]]的逆函数亦为双射

******* 证明

略

***** 非双射定义

****** 左逆<<MK191>>

若 $f:X\rightarrow Y,g:Y\rightarrow X$ 是两个函数且 $f\cdot g=E_X$ 则称 $g$ 是 $f$ 的左逆函数

****** 右逆<<MK192>>

若 $f:X\rightarrow Y,g:Y\rightarrow X$ 是两个函数且 $g\cdot f=E_Y$ 则称 $g$ 是 $f$ 的右逆函数

***** 非双射性质

$f$ 有[[MK191][左逆函数]]当且仅当 $f$ 是[[MK176][单射]]

$f$ 有[[MK192][右逆函数]]当且仅当 $f$ 是[[MK179][满射]]

$f$ 有逆函数当且仅当 $f$ 有[[MK191][左逆函数]] $g$ 和[[MK192][右逆函数]] $h$ ，且 $g=h$

****** 证明

仅证 $f$ 有[[MK192][右逆函数]]当且仅当 $f$ 是[[MK179][满射]]

******* 充分

若 $f$ 有[[MK192][右逆函数]]，则存在 $g:Y\rightarrow X$ 使得 $f\cdot g=E_Y$ 即对于任意 $y\in Y$ 均有 $<y,y>\in f\cdot g$

进一步，即对于任意 $y\in Y$ 均存在唯一 $x\in X$ 使得 $<y,x>\in g\land <x,y>\in f$

故 $\forall y(y\in Y\rightarrow\exists x(x\in X\land y=f(x)))$ 即 $f$ 是[[MK179][满射]]

******* 必要

若 $f$ 是[[MK179][满射]]则构造如下[[MK175][函数]] $g(y)=\begin{cases}x\\x_0\end{cases}$ 其中：

（1） $x$ 是指仅有唯一的 $x$ 使得 $f(x)=y$ 成立 

（2） $x_0$ 是指（1）不成立时，任意一个 $x_0$ 使得 $f(x_0)=y$ 成立

根据[[MK179][满射]]定义 $\forall y(y\in Y\rightarrow\exists x(x\in X\land y=f(x)))$ 故可得对于任意 $y$ 均有上述情况之一

故 $f(x)=y$  $g\cdot f(y)=f(g(y))=y$，故 $g\cdot f=E_Y$

* 图论

** 图的定义<<MK193>>

由[[MK194][节点]] $V$ 以及其[[MK201][赋权函数]]和连接节点的[[MK196][边]] $E$ 以及其[[MK202][赋权函数]]构成的离散结构，记作 $G=<V,E,f,g>$ 

若图省略表示为 $G=<V,E>$ ，则默认其满足[[MK200][基础假设]]

若有[[MK35][基数]] $|V|=p,|E|=q$ 则亦称 $G$ 为 $(p,q)$ 图

*** 相关定义

**** 节点相关

***** 节点<<MK194>>

$V$ 表示节点的非空[[MK82][有限集]]，例如 $V=\{a,b,c\}$

***** 孤立结点<<MK195>>

不是任何[[MK196][边]]的[[MK197][端点]]的[[MK194][节点]]

***** 悬挂点

[[MK203][度数]] $d(v)=1$ 的[[MK196][节点]]

**** 边相关

***** 边<<MK196>>

$E$ 表示边的[[MK46][多重集合]]，且是[[MK82][有限集]]。附带重数属性（同样元素在集合中的个数），其中

（1） 有向边为[[MK105][二元有序组]]，第一分量为起始节点，第二分量为终止节点，例如 $E=[<a,b>,<b,c>]$

（2） 无向边用[[MK35][基数]]为 $2$ 的[[MK44][集合]]表示，表示内容同上，例如 $E=[\{a,b\},\{b,c\},\{a,b\}]$

为方便，以上两种情况统一记作 $ab\in E$

***** 端点<<MK197>>

对于某条[[MK196][边]] $e\in E$ 其连接的两个顶点定义为其两个端点。

***** 重边<<MK198>>

[[MK196][边]] $E$ 中[[MK196][重数]]大于 $1$ 的边为重边

***** 环<<MK199>>

[[MK196][边]] $E$ 中若有连接同一[[MK194][节点]]的[[MK196][边]]，则称为环。若为[[MK196][有向边]]则称为有向环，不是则为无向环

**** 赋权相关

***** 基础假设<<MK200>>

在没有特殊说明的情况下，一般认为 $\forall x\forall y(x\in V\land y\in E\rightarrow f(x)=1\land g(y)=1)$ 为基本前提假设

***** 节点赋权函数<<MK201>>

定义为[[MK194][节点]] $V$ 到实数的[[MK175][函数]] $f:V\to\mathbb{R}$ 以描述节点的权重。

***** 边赋权函数<<MK202>>

定义为[[MK196][边]] $E$ 到实数的[[MK175][函数]] $g:E\to\mathbb{R}$ 以描述每条边的权重。

**** 度<<MK203>>

对于[[MK193][图]] $G=<V,E>$ 若 $v\in V$ ，则定义 $d(v)$ 为 $E$ 中包含 $v$ 的元素的个数。

特别的，对于[[MK206][有向图]]进一步定义：

（1） $d^+(v)$ 为 $E$ 中 $v$ 做为起 *始点* 的元素个数，称为出度

（2） $d^-(v)$ 为 $E$ 中 $v$ 做为 *终结* 点的元素个数，称为入度

定义符号 $\delta(G)=\min\left\{d(v)\big|v\in V\right\},\Delta(G)=\max\left\{d(v)\big|v\in V\right\}$ 即最小/大度数

***** 性质

****** 性质1<<MK204>>

所有[[MK194][节点]]的[[MK203][度]]的和为偶数，是[[MK196][边]]的数目的两倍

****** 性质2 

[[MK206][有向图]]中[[MK203][出度]]和[[MK203][入度]]的总和相等

****** 性质3 

对于[[MK209][无向限]]，奇数[[MK203][度]]的[[MK194][节点]]个数必为偶数个

******* 证明

设共有 $(a_1,a_2,...,a_n)$ 个[[MK194][节点]]的[[MK203][度]]为奇数，则定义 $d(a_i)=2k_i+1$ 故 $\sum_{i=1}^nd(a_i)=2\left(\sum_{i=1}^nk_i\right)+n$

设共有 $(b_1,b_2,...,b_m)$ 个[[MK194][节点]]的[[MK203][度]]为偶数，则定义 $d(b_i)=2l_i$ 故 $\sum_{i=1}^nd(a_i)=2\left(\sum_{i=1}^nl_i\right)$

故可得节点度的和为 $\sum_{i=1}^nd(a_i)+\sum_{i=1}^md(b_i)=2\left(\sum_{i=1}^nk_i+\sum_{i=1}^ml_i\right)+n$

假设 $n$ 为奇数时，度的总数为奇数，与[[MK204][性质1]]冲突。故证毕。

****** 性质4

任意[[MK210][简单图]] $G=<V,E>$ 满足 $|V|=p>1$ 则必有两个顶点 $v_1,v_2$ 的度相等，即 $d(v_1)=d(v_2)$

******* 证明

定义 $|V|=p$ 则根据简单图定义，对于任意一个顶点 $v\in V$ 有 $0\leq d(v)\leq p$

则若任意两个[[MK194][节点]]的[[MK203][度]]均不相等，则当且仅当 $d(v_i)=i$ 的情况满足

则必有 $d(v_1)=0,d(v_p)=p-1$ 

说明 $v_p$ 与所有其余点之间均有[[MK196][边]]相连， $v_1$ 与所有其余点之间无边相连

故矛盾。

** 图的分类

*** 正则图<<MK205>>

[[MK193][图]]中所有[[MK194][节点]]的[[MK203][度]]均相等，即满足 $\forall v\in V\rightarrow(\exists n\in\mathbb{N}^+\rightarrow d(v)=n)$ 的[[MK193][图]]为 $n$ 正则图 

*** 有向图<<MK206>>

[[MK196][边]] $E$ 中的任意元素均为[[MK196][有向边]]的[[MK193][图]]，通常记为 $D=<V,E>$

*** 有向无圈图<<MK207>>

不含[[MK225][有向圈]]的[[MK206][有向图]]，亦称为 DAG

**** 定理<<MK208>>

若 $G=<V,E>$ 是有向无圈图，则是少有一个顶点入度为零，一个顶点出度为零

***** 证明

定义 $r=<v_1,...,v_n>$ 是图 $G$ 中的[[MK223][最长]]的[[MK222][有向路]]

则假设 $d^-(v_1)>0$ 则必有 $v\in V$ 满足 $<v,v_1>\in E$

若 $v$ 在 $r$ 上，则有[[MK225][有向圈]] $c=<v_1,...,v,e,v_1>$ 与 $G$ 无圈矛盾

若 $v$ 不在 $r$ 上则有 $r'=<v,e,v_1,...,v_n>$ 满足 $\phi(r')>\phi(r)$ 与最长路矛盾

故假设不成立 $d^-(v_1)=0$ 同理可证 $d^+(v_n)=0$

*** 无向图<<MK209>>

[[MK196][边]] $E$ 中的任意元素均为[[MK217][无向边]]的[[MK193][图]]

*** 重图

[[MK196][边]] $E$ 少有一个元素重数大于 $1$ ，不为重图便为单图

*** 简单图<<MK210>>

不包含[[MK199][环]]和[[MK198][重边]]的[[MK209][无向图]]

*** 完全图<<MK211>>

任何两个不同结点间都有边关联的[[MK209][无向图]]称为完全无向图，记做 $K_n$

任何两个不同结点 $u,v$ 见都有边 $\{<u,v>,<v,u>\}\subset E$ 的[[MK206][有向图]]称为完全有向图

*** 正则图

所有[[MK194][节点]]的[[MK203][度]]均相等的[[MK193][图]]为正则图

*** 零图<<MK212>>

仅有[[MK195][孤立结点]]构成的[[MK193][图]]

*** 平凡图

仅包含 $1$ 个[[MK196][节点]] $0$ 条[[MK196][边]]的 $(1,0)$ 图

** 图的关系

*** 相等<<MK213>>

根据图的[[MK193][定义]]可得，对于任意 $G=<V,E>,H=<U,F>$ 有 $G=H$ 的充要条件是

（1） $V=U$

（2） $E=F$

*** 子图<<MK214>>

若 $G_1=<V_1,E_1>,G_2=<V_2,E_2>$ 均为[[MK193][图]]，若满足：

（1） $V_1\subset V_2\land E_1\subset E_2$ 

（2） $E_1$ 中所有边的[[MK197][端点]]均在 $V_1$ 中

则称 $G_1$ 为 $G_2$ 的子图。

特别的当不[[MK213][相等]] $G_1\ne G_2$ 时，称为真子图

**** 生成子图<<MK215>>

若 $G_1=<V_1,E_1>,G_2=<V_2,E_2>$ 均为[[MK193][图]]，若满足：

（1） $V_1=V_2$

（2） $G_1$ 是 $G_2$ 的[[MK214][子图]]

 则称 $G_1$ 是 $G_2$ 的生成子图。

**** 导出子图<<MK216>>

若 $G=<V,E>$ 为[[MK193][图]]，定义 $X\subset V$ 若存在 $G'=<V',E'>$ 满足：

（1） $V'=V/X$

（2） 对于任意 $G$ 的子图 $G^*=<V^*,E^*>$ ，若 $V^*=V/X$ 则有 $G^*$ 是 $G'$ 的[[MK214][子图]]

则成 $G'$ 是 $G$ 关于 $V'$ 的导出子图

亦可表示为  $G'=<V',(V'\times V')\cap E>$ 其中 $V'\times V'$ 是[[MK107][笛卡尔积]] 

*** 补图

**** 无向图

若 $G_1=<V_1,E_1>,G_2=<V_2,E_2>$ 均为[[MK210][简单图]]，若满足：

（1） $V_1=V_2\land E_1\cap E_2=\varnothing$ 

（2） $G'=<V_1,E_1\cup E_2>$ 是无向[[MK211][完全图]]

则称 $G_1,G_2$ 互为补图。

**** 有向图

若 $G_1=<V_1,E_1>,G_2=<V_2,E_2>$ 均为无[[MK198][重边]]与[[MK199][环]]的[[MK193][图]]，若满足：

（1） $V_1=V_2\land E_1\cap E_2=\varnothing$ 

（2） $G'=<V_1,E_1\cup E_2>$ 是有向[[MK211][完全图]]

则称 $G_1,G_2$ 互为补图。

*** 同构图

若 $G_1=<V_1,E_1>,G_2=<V_2,E_2>$ 均为[[MK193][图]]，若满足：

（1） $|V_1|=|V_2|\land|E_1|=|E_2|$ 即[[MK35][基数]]相等

（2） 存在[[MK181][双射]] $f:V_1\to V_2$ 满足充要条件 $\forall <v_1,v_2>\in E_1\leftrightarrow <f(v_1),f(v_2)>\in E_2$

则称 $G_1,G_2$ 互为同构。

** 图的连通

*** 连通

**** 通道<<MK217>>

若存在图 $G=<V,E>$ 且 $\{v_1,v_n\}\subset V$ 

若存在[[MK82][有限]]的[[MK111][有序组]] $t=<v_1,e_1,v_2,e_2,....e_{n-1},v_n>$ 满足 $e_i\in E\land\left(e_i=\{v_{i-1},v_i\}\right)$

则称有序组是 $v_1v_n$ 通道

当 $G$ 是[[MK206][有向图]]，若存在[[MK82][有限]]的[[MK111][有序组]] $t=<v_1,e_1,v_2,e_2,....e_{n-1},v_n>$ 满足 $e_i\in E\land\left(e_i=<v_i,v_{i+1}>\right)$

则称有序组是 $v_1v_n$ 通道的有向通道

***** 取边<<MK218>>

若 $t=<v_1,e_1,v_2,e_2,....e_{n-1},v_n>$ 则定义 $E(t)=\{e_1,...,e_{n-1}\}$

为通道 $t$ 中所有边的集合

***** 取节点<<MK219>>

若 $t=<v_1,e_1,v_2,e_2,....e_{n-1},v_n>$ 则定义 $E(t)=\{v_1,...,v_n\}$

为通道 $t$ 中所有节点的集合

**** 迹<<MK220>>

若存在图 $G=<V,E>$ 且 $\{v_1,v_n\}\subset V$ 若存在无重复[[MK196][边]]的 $v_1v_n$ [[MK217][通道]] $l$ ，则称该通道为 $v_1v_n$ 迹

特别的，当 $v_1=v_n$ 时，称为 *闭迹*

若 $G=<V,E>$ 是[[MK206][有向图]]，则存在无重复[[MK196][边]]的 $v_1v_n$ [[MK217][有向通道]] $l$ ，则称该通道为 $v_1v_n$ 有向迹

***** 定理<<MK221>>

在图 $G$ 中，如果有顶点 $v_1$ 到 $v_k$ 的[[MK217][通道]] $t$ 且其[[MK232][长度]] $\phi(t)<\infty$

则 $v_1$ 到 $v_k$ 必有[[MK220][迹]]

****** 证明

若存在有限长度的[[MK217][通道]]则必有序列 $v_1,e_1,....,e_{k-1},v_k$ 

若存在 $e_i=e_j$ 则必有子序列 $v_i,<v_i,v_{i+1}>,v_{i+1},...,v_j,<v_j,v_{j+1}>,v_{j+1}$

由于相等，则有 $v_i=v_j\land v_{i+1}=v_{j+1}$

则消去中间部分可得 $v_i,<v_i,v_{j+1}>,v_{j+1}$ 不改变起始点或终止点，以此方法可以去除所有重复[[MK196][边]]。

**** 路<<MK222>>

若存在图 $G=<V,E>$ 且 $\{v_1,v_n\}\subset V$ 若存在无重复[[MK194][节点]]的 $v_1v_n$ [[MK217][通道]] $r$ ，则称该通道为 $v_1v_n$ 路

若 $G=<V,E>$ 是[[MK206][有向图]]，则存在无重复[[MK194][节点]]的 $v_1v_n$ [[MK217][有向通道]] $r$ ，则称该通道为 $v_1v_n$ 有向路

若把 $G$ 变为无向图后存在无重复[[MK194][节点]]的 $v_1v_n$ [[MK217][通道]] $r$ ，此时则称 $r$ 为 $G$ 的弱路

***** 性质

由于[[MK196][边]]的顶点不重复，故不存在重复[[MK196][边]]

***** 最长路<<MK223>>

任意图均有最长路。最长路定义为根据[[MK222][路]]的长度定义，取得最大值的路。

****** 证明存在

由于[[MK194][顶点]]为非空[[MK82][有限集]]，且根据路定义无法重复出现，故最多有 $|V|=p$ 个顶点出现在一个[[MK222][路]]上

故对于任意路其长度均小于等于 $p$ 故有最长路存在。

***** 定理<<MK224>>

在有 $n$ 个顶点的图 $G$ 中，如果有顶点 $v_1$ 到 $v_k$ 有[[MK220][迹]]

则必有长度不大于 $n-1$ 的[[MK225][路]]

****** 证明

由于[[MK196][边]]是有限集，且[[MK220][迹]]不重复边，故若存在[[MK220][迹]]，则其长度必小于 $\infty$

故存在[[MK220][迹]]则必有有限序列 $v_1,e_1,....,e_{k-1},v_k$ 其中无重复[[MK196][边]]

若存在 $v_i=v_j$ 则必有子序列 $e_{i-1},v_i,e_i,...,e_{j-1},v_{j},e_j$ 则亦可消去中间部分组成 $e_{i-1},v_i,e_j$

同理可消除所有重复[[MK194][节点]]

若[[MK217][通道]]长度大于 $n-1$ 则必有 $n+1$ 个[[MK194][节点]]在[[MK217][通道]]中。

根据鸽笼原理，必有一个重复的节点，同样可以用上述方法消去。

**** 圈<<MK225>>

若存在图 $G=<V,E>$ 且 $\{v_1,v_n\}\subset V$ 若存 $v_1v_n$ [[MK222][路]] $c$ 满足 $v_1=v_n$ ，则成该路为 $v_1$ 圈

若 $G=<V,E>$ 是[[MK206][有向图]]，则称 $c$ 为有向圈

若 $G=<V,E>$ 是[[MK206][有向图]]，且存在 $v_1v_n$ [[MK222][弱路]] $c$ 满足 $v_1=v_c$ 则称 $c$ 是若圈

***** 定理1<<MK226>>

[[MK209][无向图]] $G=<V,E>$ 任意一个顶点的[[MK203][度]]满足 $d(v)>1$ ，则 $G$ 中存在圈

****** 证明<<MK227>>

定义 $<v_1,...,v_n>$ 是 $G$ 中的[[MK223][最长路]]，根据条件 $d(v_1)>1$ ，则必有另一条边 $e_k=v_1v_k\in E$

若 $v_k\not\in\{v_1,...,v_n\}$ 则 $<v_k,e_k,v_1,...,v_n>$ 比原[[MK222][路]]对一条边，故[[MK232][长度]]大于u原路

这与 $<v_1,...,v_n>$ 是 $G$ 中的[[MK223][最长路]]矛盾，故必有 $v_k\in\{v_1,...,v_n\}$ 

则 $<v_1,...,e_k,v_1>$ 显然长度大于 $1$ ，是[[MK225][圈]]

***** 定理2

若[[MK210][简单图]] $G=<V,E>$ 任意一个顶点的[[MK203][度]]满足 $d(v)\geq m\geq2$ ，

则 $G$ 中存在长度大于等于 $m+1$ 的[[MK225][圈]]

****** 证明

根据[[MK226][定理1]]可得由于 $\forall v\in V\rightarrow d(v)>1$ 故存在圈，定义 $<v_1,...,v_n>$ 是 $G$ 中的[[MK223][最长路]]

根据[[MK227][之前证明]]显然必有 $m-1$ 个包含在 $\{v_3,...,v_n\}$ 不同[[MK194][顶点]]与 $v_1$ 相连

故依次取长度最短的可能圈 $v_3,...,v_{m+1}$ 则有 $<v_1,v_2,...,v_{m+1},v_1>$

根据定义该圈的长度为 $m+1$ 即满足条件

***** 定理3<<MK228>>

若[[MK210][简单图]] $G=<V,E>$ 的两个顶点 $\{u,v\}\subset V$ 存在两条不同的[[MK222][路]]，则存在圈

****** 证明

定义 $P_1=<u,u_1,...,u_n,v>, P_2=<u,v_1,...,v_m,v>$

由于[[MK194][顶点]]是有限集，以及[[MK222][路]]中不包含重复顶点，故 $P_1,P_2$ 长度均有限

由于是两条不同的路且不含[[MK199][环]]和[[MK198][重边]]，故比存在 $1\leq k\leq\min(n,m)$ 满足 $u_k\ne v_k$

取最小满足条件的 $k^*$ 作为圈的起点。取最小的 $i$ 满足存在 $j$ 使得 $u_i=v_j$ 依然取最小 $j$

若存在 $i$ 则定义[[MK217][通道]] $<u_{k^*},u_{k^*+1}...,u_i,v_{j-1},v_{j-2},...v_{k^*}>$

由于 $<u_{k^*},u_{k^*+1}...,u_i>,<v_{j-1},v_{j-2},...v_{k^*}>$ 为两条路上子路，故必然顶点不重复

若存在 $u_l=v_k$ 满足 $l<i$ 则与 $i$ 定义矛盾，同理可证与 $j$ 定义矛盾

故 $<u_{k^*},u_{k^*+1}...,u_i,v_{j-1},v_{j-2},...v_{k^*}>$ 不存在重复顶点，且 $u_{k^*}=v_{k^*}$ 故是[[MK225][圈]]

若不存在，同理可证 $<u_{k^*},u_{k^*+1}...,v,v_m,v_{m-1},...v_{k^*}>$ 是圈 

***** 定理4<<MK229>>

若[[MK206][有向图]] $D=<V,E>$ 没有[[MK225][圈]]，则其至少包含一个[[MK203][出度]]为 $0$ 的[[MK194][顶点]]

****** 证明

定义 $r=<v_1,...,v_n>$ 是 $D$ 中的[[MK223][最长路]]，此时考虑 $v_n$ 的[[MK203][出度]]

假设 $d^+(v_n)>0$ 则必有 $e=<v_n,v>\in E$ 

此时若 $v$ 在 $t$ 上，则有圈 $c=<v,...,v_n,e,v>$

若 $v$ 不在 $t$ 上，则有 $r'=<v_1,...,v_n,e,v>$ 是更长的路，与最长路假设矛盾

故假设不成立，此时 $d^+(v_n)=0$

***** 定理5<<MK230>>

若[[MK206][有向图]] $D=<V,E>$ 有[[MK225][圈]]的充要条件是存在子图 $D_1=<V_1,E_1>$ 

满足 $\forall v\in V_1\rightarrow d^+(v)>0\land d^-(v)>0$ 

****** 证明

******* 充分

若存在圈 $c$ 则其包含的[[MK194][顶点]]和[[MK196][边]]构成的[[MK193][图]]即满足。

******* 必要

假设 $D_1$ 没有圈，则根据[[MK229][定理4]]可得必有一个[[MK194][顶点]]的[[MK203][出度]]为 $0$ 显然与条件矛盾。

故假设不成立 $D_1$ 有圈。由于 $D_1$ 是 $D$ 的[[MK214][子图]]，故 $D$ 有圈

**** 可达<<MK231>>

若存在图 $G=<V,E>$ 对于 $\{v_1,v_n\}\subset V$ 均存在 $v_1v_n$ [[MK222][路]] ，则称 $v_1$ 可达 $v_n$

若存在[[MK206][有向图]] $G=<V,E>$ 对于 $\{v_1,v_n\}\subset V$ 均存在 $v_1v_n$ [[MK222][有向路]]，则称 $v_1$ 有向可达 $v_n$

定义 $v\in V$ 的所有有向可达节点的集合为 $\mathcal{A}(v)$

**** 长度<<MK232>>

[[MK217][通道]]，[[MK220][迹]]，[[MK222][路]]，[[MK225][圈]]的长度定义为其边的赋权映射和

即对于通道/迹/路/圈 $t=<v_1,e_1,...,e_{n-1},v_n>$ 其长度为 $\phi(t)=\sum_{i=1}^{n-1}g(e_{i})$

若 $v_1,v_n$ 两个[[MK194][顶点]]之间不存在通道/迹/路/圈，则其长度定义为 $\phi(<>)=\infty$

根据[[MK200][基础假设]]，该定义可简化为边的条数

**** 距离<<MK233>>

定义两个[[MK194][顶点]] $\{u,v\}\subset V$ 间的距离为 $\phi(u,v)=\min\left\{\phi(t)\big|t=<u,...,v>\right\}$ 

即 $u,v$ 间通道/迹/路的最小[[MK232][长度]]

**** 割点<<MK234>>

定义[[MK193][图]] $G=<V,E>$ 若有 $v\in V$ 满足 $G$ 关于 $V/\{v\}$ 的[[MK216][导出子图]] $T$ 的[[MK230][支]]数大于 $G$ 的支树数

则称 $v$ 是 $G$ 的割点

***** 等价定义

定义[[MK242][连通图]]（不连通用连通子图） $G=<V,E>$ ，对于任意 $v\in V$ 下列命题等价

（1） $v$ 是[[MK234][割点]]

（2） $\exists u\in V\land\exists w\in V$ 他们之间的所有[[MK222][路]]均经过 $v$

（3） 存在 $V/\{v\}$ 的一个[[MK136][划分]] $X,Y$ 满足 $\forall x\in X,\forall y\in Y$ 有 $x,y$ 之间的[[MK222][路]]都经过 $v$

****** 证明<<MK235>>

******* （1）证（3）

根据[[MK234][定义]]可得去除 $v$ 的[[MK216][导出子图]] $G'$ 支数增加。取其中一个支的[[MK194][顶点]]定义为 $V_1$ 

剩余的顶点定义为 $V_2$ 。由于 $G$ 连通，故对于任意 $u\in V_1,w\in V_2$ 在 $G$ 上连通

根据[[MK230][支]]的定义 $u,w$ 在 $G'$ 上不连通。

假设有路 $r=<u,...,w>$ 不经过 $v$ 由于 $G'$ 为导出子图，故 $r$ 亦包含与 $G'$

与在 $G'$ 上不连通矛盾，故假设不成立。则证毕

******* （3）证（2）

显然

******* （2）证（1）

根据[[MK234][定义]]可得去除 $v$ 的[[MK216][导出子图]] $G'$ ，由于所有[[MK222][路]]均经过 $v$

故 $u,v$ 间没有路，则不[[MK242][连通]]。根据[[MK241][支]]的定义支数增加

***** 性质

****** 性质1

设[[MK210][简单图]] $G=<V,E>,|V|>2$ ，则其至少有两个顶点不是割点

******* 证明

定义 $r=<v_1,...,v_n>$ 为最长路，则 $v_1,v_n$ 不能与 $r$ 意外的[[MK194][顶点]]邻接，否则不为最长路

故去除 $v_1,v_n$ 后有 $r'=<v_2,...,v_{n-1}>$ 不产生新的[[MK241][支]]

****** 性质2

[[MK259][哈密顿图]]不含割点

******* 证明

根据哈密顿图定义，存在[[MK225][圈]]经过所有[[MK194][顶点]]，定义为 $c=<v_1,...,v_n,e_n,v_1>$

则显然去除任一顶点形成[[MK257][哈密顿路]]，图仍为连通。

**** 桥<<MK236>>

定义[[MK193][图]] $G=<V,E>$ 若有 $e\in E$ 满足 $G$ 的[[MK214][子图]] $T=<V,E/\{e\}>$ 的[[MK230][支]]数大于 $G$ 的支树数

则称 $e$ 是 $G$ 的桥

***** 等价性质

定义[[MK242][连通图]]（不连通用连通子图） $G=<V,E>$ ，对于任意 $e\in E$ 下列命题等价

（1） $e$ 是[[MK236][桥]]

（2） $\exists u\in V\land\exists w\in V$ 他们之间的所有[[MK222][路]]均经过 $e$

（3） 存在 $V/\{v\}$ 的一个[[MK136][划分]] $X,Y$ 满足 $\forall x\in X,\forall y\in Y$ 有 $x,y$ 之间的[[MK222][路]]都经过 $e$

（4） $e$ 不在 $G$ 的任意[[MK225][圈]]上

****** 证明

（1）（2）（3）的证明与[[MK235][之前]]同理

假设 $e$ 是桥。则若 $e$ 在圈上，则显然去除后 $G$ 仍连通，故[[MK241][支]]不增加。故 $e$ 不在圈上

若 $e=\{u,w\}$ 不在[[MK225][圈]]上，则去除 $e$ 后 $u,w$ 之间没有[[MK222][路]]。故满足（2）

证毕

*** 关系相关

**** 通道关系<<MK237>>

是一种[[MK111][二元关系]] $\mathcal{T}\subset V\times V$ 定义为 $<v_a,v_b>\in\mathcal{T}$ 的充要条件为存在 $v_av_b$ [[MK217][通道/有向通道]]

**** 迹关系<<MK238>>

是一种[[MK111][二元关系]] $\mathcal{L}\subset V\times V$ 定义为 $<v_a,v_b>\in\mathcal{L}$ 的充要条件为存在 $v_av_b$ [[MK220][迹]]

**** 路关系<<MK239>>

是一种[[MK111][二元关系]] $\mathcal{R}\subset V\times V$ 定义为 $<v_a,v_b>\in\mathcal{R}$ 的充要条件为存在 $v_av_b$ [[MK222][路]]

**** 互达关系<<MK240>>

是一种[[MK111][二元关系]] $\mathcal{R}_D\subset V\times V$ 

定义为 $<v_a,v_b>\in\mathcal{R}_D$ 的充要条件为存在 $v_av_b$ [[MK222][有向路]]以及 $v_bv_a$ [[MK222][有向路]]

**** 定理

对于[[MK209][无向图]] $G=<V,E>$ [[MK237][通道关系]]、[[MK238][迹关系]]、[[MK239][路关系]]以及[[MK240][互达关系]]均为[[MK132][等价关系]]

***** 证明

根据[[MK132][定义]]证明[[MK239][路关系]] $\mathcal{R}$ 是等价关系，其余同理可证。

****** 自反性

根据[[MK217][通道]]定义，对于任意 $v\in V$ 存在有序组 $<v>$ 满足[[MK194][顶点]] $v$ 只出现一次，没有[[MK196][边]]

故有序组中没有重复顶点和重复边，故 $<v>$ 是[[MK222][路]]，则有 $<v,v>\in\mathcal{R}$ 故有[[MK124][自反性]]

****** 对称性

由于是无向图，故显然若 $<u,v>\in\mathcal{R}$ 则有 $<v,u>\in\mathcal{R}$ 故有[[MK126][对称性]]

****** 传递性

若 $<u,v>\in\mathcal{R}\land <v,z>\in\mathcal{R}$ 且 $u\ne z$ 则显然存在两个有序组 $r_1=<u,...,v>,r'_1=<v,...,z>$

若存在顶点 $v_1$ 包含于 $r_1,r'_1$ 则存在有序组 $r_2=<u,...,v_1>,r'_2=<v_1,...,z>$

依次类推，根据[[MK222][路]]定义顶点不重复，且根据[[MK194][顶点]]定义 $V$ 是有限集

则必能找到 $r_k=<u,...,v_k>,r'_k=<v_k,...,z>$ 不包含重复顶点

故有据[[MK217][通道]] $<u,...,v_k,...,z>$ 不包含重复顶点，则存在 $uz$ [[MK222][路]]即有[[MK128][传递性]]

***** 推论1<<MK241>>

由于 $\mathcal{T},\mathcal{L},\mathcal{R}$ 为等价关系，则可有 $V$ 的[[MK133][等价类]]，这些等价类满足：

（1） $\mathcal{T},\mathcal{L},\mathcal{R}$ 关系生成的等价类相同

（2） 定义 $V$ 划分为 $V_1,...,V_n$ 个等价类 $G_i=<V_i,E_i>$ 是 $G$ 关于 $V_i$ 的[[MK216][导出子图]]

     则有 $V=\bigcup_{i=1}^n V_i\land E=\bigcup_{i=1}^n E_i$ 称每一个 $G_i$ 是 $G$ 的 *支*

****** 证明

******* 证明（1）

根据[[MK221][迹定理]]和[[MK224][路定理]]可得对于任意 $\{u,v\}\in V$ 有 $\exists t\in\mathcal{T}\rightarrow\exists l\in\mathcal{L}\rightarrow\exists r\in\mathcal{R}$

又根据定义显然有 $u,v$ 间存在[[MK222][路]]则有 $u,v$ 间存在[[MK217][通道]]

故有 $\exists t\in\mathcal{T}\leftrightarrow\exists l\in\mathcal{L}\leftrightarrow\exists r\in\mathcal{R}$ 则有 $\mathcal{T}=\mathcal{L}=\mathcal{R}$ 故证毕

******* 证明（2） 

根据[[MK138][定理1]]可得等价类是 $V$ 的[[MK136][划分]]，则有 $V=\bigcup_{i=1}^n V_i$

根据[[MK237][通道关系]]、[[MK238][迹关系]]以及[[MK239][路关系]]定义可得对于任意 $v\in V_i,u\in V_j$ 有 $i\ne j\rightarrow \{u,v\}\not\in E$

进一步根据[[MK216][导出子图]]定义可得 $E_i=(V_i\times V_i)\cap E$ 

假设存在 $e\in E\land\forall i(e\not\in E_i)$ 则有 $\forall i(e\not\in (V_i\times V_i))$ 又由于 $E\subset(V\times V)$

故有 $e\in(V\times V)-\bigcup_{i=1}^n V_i\times V_i$ 则必定存在 $i\ne j\rightarrow e\in V_i\times V_j$

与上述推论矛盾，故假设不成立，则有 $E=\bigcup_{i=1}^n E_i$

***** 推论2

[[MK241][同理]]对于[[MK206][有向图]]， $\mathcal{R}_D$ 亦为等价关系，可划分 $V$ 的[[MK133][等价类]]。

定义 $V$ 划分为 $V_1,...,V_n$ 个等价类 $G_i=<V_i,E_i>$ 是 $G$ 关于 $V_i$ 的[[MK216][导出子图]]

则有 $V=\bigcup_{i=1}^n V_i\land E=\bigcup_{i=1}^n E_i$ 称每一个 $G_i$ 是 $G$ 的 *强支*

*** 图相关

**** 无向图连通<<MK242>>

若[[MK209][无向图]] $G=<V,E>$ 且对于任意 $\{u,v\}\subset V$ 均有 $<u,v>\in\mathcal{L}$ ，则是连通图

其中 $\mathcal{L}$ 是[[MK239][迹关系]]

***** 定理1<<MK243>>

对于[[MK210][简单图]] $G=<V,E>$ 且 $|V|=p$ 若对于任意 $\{u,v\}\subset V$ 且 $uv\not\in E$ 若有 $d(u)+d(v)\geq p-1$

则 $G$ 是连通图

****** 证明

假设 $G$ 不是连通图且 $d(u)+d(v)\geq p-1$ ，则存在 $\{u,v\}\subset V$ 满足 $<u,v>\not\in\mathcal{L}$

由于 $G$ 是简单图，故无[[MK199][环]]和[[MK198][重边]]，则若 $d(u)=k\leq p-2$ 则有 $k$ 个[[MK194][顶点]]与 $u$ 相连

由于 $<u,v>\not\in\mathcal{R}$ 则与 $u$ 相连的 $k$ 个顶点必然不与 $v$ 相连

进一步由于 $uv\not\in E$ 则必有 $d(v)\leq p-k-1-1$ 则有 $d(v)+d(u)\leq p-2$

显然与条件 $d(u)+d(v)\geq p-1$ 矛盾，故假设不成立 $G$ 是连通图

****** 推论

对于[[MK210][简单图]] $G=<V,E>$ 且 $|V|=p$ 若对于任意 $v\in V$ 有 $d(v)\geq\frac{p}{2}$

则 $G$ 是连通图

******* 证明

对于任意 $\{u,v\}\in V$ 有 $d(u)+d(v)\geq 2\frac{p}{2}\geq p$ 则根据[[MK243][定理]]可得是连通图

**** 有向图的连通

***** 强连通

若[[MK206][有向图]] $G=<V,E>$ 任意两[[MK194][节点]]都相互[[MK231][可达]]，则称无向图是强联通。

***** 单向连通

若[[MK206][有向图]] $G=<V,E>$ 任意两[[MK194][节点]]中，至少有一个节点到另一个节点[[MK231][可达]]，则称无向图是单向联通。

***** 弱连通<<MK244>>

若[[MK206][有向图]] $G=<V,E>$ 将所有有向[[MK196][边]]替换成无向[[MK196][边]]，进而形成的[[MK209][无向图]]是联通的，则称有向图为弱连通。

**** 极小连通图<<MK245>>

若图 $G=<V,E>$ [[MK242][连通]]，对于任意 $e\in E$ 均有 $G'=<V,E/\{e\}>$ 不连通，则称其为极小连通图

** 特殊图

*** 二分图（双图）

**** 定义<<MK246>>

若[[MK209][无向图]] $G=<V,E>$ 满足：

（1） 有非空集合 $X,Y$ 满足 $X\cup Y=V\land X\cap Y=\varnothing$

（2） 对于任意 $e=\{v_1,v_2\}\in E$ 满足 $v_1\in X\land v_2\in Y$

则图 $G$ 称为二分图，可记作 $G=<X,E,Y>$

特别当 $X,Y$ 中任意两个[[MK194][节点]]均有[[MK196][边]]相连时，称为完全二分图。记作 $K_{m,n}$ 其中 $m=|X|,n=|Y|$

**** 等价条件

[[MK209][无向图]] $G=<V,E>$ 是[[MK246][双图]]的等价条件为：

（1） $G$ 至少有两个[[MK194][节点]]

（2） 所有[[MK225][圈]]的长度（边数和）均为偶数

（3） 图是[[MK242][连通]]的

***** 证明

****** 充分

若 $G=<X,E,Y>$ 是二分图，且定点 $v_1\in X$ 存在[[MK225][回路]]，根据[[MK246][定义]]所有边均连接 $X,Y$

则当且仅当长度为偶数时，顶点落在 $X$ 内，故若存在回路，必为偶数

****** 必要

若[[MK242][无向连通图]]（若非连通，则可分为若干个连通分支图） $G=<V,E>$ 所有回路均为偶数，取任意[[MK194][节点]] $v\in V$ 定义

（1） $X$ 为 $v'\in V$ 且 $v',v$ 之间存在[[MK222][路]]且其[[MK232][长度]]为偶数

（2） $Y=V-X$

显然 $v\in X$ 故 $X\ne\varnothing$ 由于 $|V|>2$ 故 $Y\ne\varnothing$

若 $\{v_1,v_2\}\subset X$ 则 $v$ 到 $v_1$ 或 $v_2$ 均有偶数[[MK232][长度]]的[[MK222][路]]定义为 $r_1=<v,...,v_1>,r_2=<v,...,v_2>$

则根据[[MK217][定义]]可知 $t=<v_1,...,v,...,v_2>$ 是通道，由于有长度且为偶数，故有 $\phi(t)$ 为偶数且 $\phi(t)<\infty$ 

根据之前方法寻找 $t$ 中重复[[MK194][顶点]]，假设 $v_{k_0}$ ，则存在子链 $<v_{k_0},...,v_{k_0}>$

若子链中仍有重复[[MK194][顶点]] $v_{k_1}$ 则存在子链 $<v_{k_1},...,v_{k_1}>$

由于 $\phi(t)<\infty$ 则依次类推，可以找到除两端外无重复顶点的子链 $s$ ，显然该子链满足[[MK225][圈]]定义

根据条件该圈的长度 $\phi(s)$ 为偶数，从 $t$ 中去除该圈变为 $t_1$

则根据[[MK232][长度]]定义去除的边数为偶数，则 $\phi(t_1)$ 亦为偶数。

由于长度有限，故可依次类推直到 $t^*=<v_1,...,v_2>$ 中无重复顶点，且根据之前推断可得 $\phi(t^*)$ 亦为偶数。

此时若存在[[MK196][边]] $e={v_1,v_2}$ 则圈 $<v_1,...,v_2,v_1>$ 的长度为 $\phi(t^*)+1$ 为奇数

故矛盾。故 $X$ 中不能存在内部边

由于是[[MK242][连通图]]，故 $Y$ 中所有[[MK194][顶点]]存在到 $v'$ 奇数[[MK232][长度]]的[[MK222][路]]，则同理可证 $Y$ 中亦不能存在内部边

**** 性质

双图没有[[MK199][环]]

***** 证明

若[[MK194][顶点]] $v\in V$ 存在环，则无论 $v\in X\lor v\in Y$ 均存在 $e={x,x}$ 不满足[[MK246][定义]]中（2）

**** 图兰定理

设 $G=<V,E>$ 是 $(p, q)$ 的[[MK210][简单图]]，如果 $G$ 中没有[[MK232][长度]]为 $3$ 的[[MK225][圈]]，则其边数 $q\leq\frac{p^2}{4}$

***** 证明

显然当 $p=1,p=2,p=3$ 时成立，此时假设 $p$ 是奇数：

则若当 $p=2n-1$ 时成立，定义有 $(2n+1,q)$ 图 $G$ ，若 $G$ 是[[MK212][零图]]则显然 $q=0<\frac{(2n+1)^2}{4}$

若不是，则 $E\ne\varnothing$ 故取任意 $e=\{v_1,v_2\}\in E$ 故定义 $G'=<V',E'>$ 是 $G$ 关于 $V/\{v_1,v_2\}$ 的[[MK216][最大子图]] 

定义 $p'=|V'|,q'=|E'|$ 此时显然 $p'=2n-1$ 故 $G'$ 满足条件

则有 $q'\leq \frac{(2n-1)^2}{4}=\frac{4n^2-4n+1}{4}=n^2-n+\frac{1}{4}$ 由于边数为正整数，故有 $q'\leq n^2-n$

在图 $G$ 中：

对于 $v_1,v_2$ 假设 $d(v_1)=k$ ，由于 $G$ 中存在[[MK196][边]] $e$ 连接 $v_1,v_2$ 

则 $v_2$ 必须满足不与 $v_1$ 连接的节点连接，否则结合边 $e$ 形成[[MK232][长度]]为 $3$ 的[[MK225][圈]]

显然去除 $v_2$ 有 $k-1$ 个顶点与 $v_1$ 相连，故加上 $v_1$ 有 $p-k$ 个点可以与 $v_2$ 相连

故有 $d(v_1)+d(v_2)=p=2n+1$ 则与两点相连的边数为 $p-1$ 

故图 $G$ 最多有 $q'+p-1\leq n^2-n +\frac{1}{4}+2n=\frac{(2n+1)^2}{4}$ 证毕

同理可证当 $p$ 为偶数时 $q'\leq \frac{(2n-2)^2}{4}=n^2-2n+1$

则有 $q\leq q'+p\leq n^2-2n+1+2n\leq n^2+1<n^2+2n+1=\frac{(2n+2)^2}{4}$

**** 匹配

***** 定义<<MK247>>

定义[[MK246][二分图]] $G=<X,E,Y>$ 若 $M\subset E$ 且任意 $e_1=\{v_1,v'_1\}\land e_2=\{v_2,v'_2\}\land\{e_1,e_2\}\subset E$ 

均有 $v_1\ne v_2\land v'_1\ne v'_2$ 即任意两条边无公共端点

则称 $M$ 为匹配。若 $M$ 为边数最多的集合，则称为最大匹配。

若 $X,Y$ 中的所有定点均出现在匹配 $M$ 中，则称为完全匹配。

***** 匈牙利算法（求最大匹配）

步骤如下：

（1） 任取一个[[MK247][匹配]] $M$ 

（2） 定义 $S$ 是尚未匹配点的集合

（3） 若 $S=\varnothing$ 则 $M$ 为最大匹配

（4） 取 $u_0\in S$ 为起点，找任一最大[[MK225][通路]]，满足属于 $M$ 和不属于 $M$ 的边交替出现，定义其边的集合为 $P$

（5） 若（4）中通路的终点亦在 $S$ 中，则 $M^{(1)}=(M-P)\cup (P-M)$ 

（6） 若终点不在 $S$ 中，则回到（3）

*** 欧拉图

**** 定义

***** 欧拉迹<<MK248>>

若图 $G=<V,E>$ 存在一条通过所有[[MK194][节点]]和[[MK196][边]]的[[MK220][迹]]，则该路径为欧拉路径。

***** 欧拉闭迹<<MK249>>

若图 $G=<V,E>$ 存在一条通过所有[[MK194][节点]]和[[MK196][边]]的[[MK220][闭迹]]，则该路径为欧拉路径。

***** 欧拉图<<MK250>>

若图 $G=<V,E>$ 存[[MK249][欧拉闭迹]]，则称图 $G$ 为欧拉图。

**** 定理

***** 定理1（判定无向图）<<MK251>>

[[MK209][无向图]]为[[MK250][欧拉图]]的充要条件是图 $G=<V,E>$ 是[[MK242][连通]]的，且所有[[MK194][节点]]的[[MK203][度]]都是偶数

****** 证明

******* 充分<<MK252>>

若图 $G=<V,E>$ 是[[MK250][欧拉图]]，则有[[MK249][欧拉闭迹]]，即存在[[MK217][通道]] $t=<v_1,e_1,v_2,...,v_k,e_k,v_1>$ 

且其中 $e_i$ 不存在重复，且 $E=\{e_1,...,e_k\}$ ，即该[[MK220][闭迹]]包含所有[[MK196][边]]以及[[MK194][顶点]]

故 $\forall v\in V$ 均存在于 $t$ 中，且必以 $e_u,v,e_v$ 形式出现，该形式的度为 $2$ 

故所有[[MK194][节点]]的[[MK203][度]]都是 $2$ 乘以其在拟路径中出现的次数 $n$ ，即 $2n$ 为偶数。

又由于存在[[MK220][迹]]连通所有[[MK194][节点]]，故图是[[MK242][连通图]]

******* 必要<<MK253>>

******** 构建圈集<<MK254>>

由于 $G=<V,E>$ 是[[MK209][无向图]]且[[MK203][度]]为偶数，即大于 $1$ 定义 $G=G_0$

则根据[[MK226][定理1]]存在[[MK225][圈]] $C_1$ 显然 $C_1$ 满足[[MK193][图定义]]，故定义 $C_1=<U_1,F_1>$

在 $G_0$ 中去除 $C_1$ 中包含的[[MK196][边]]形成子图 $G_1'=<V,E_1>$ 其中 $E_1=E/F_1$

由于 $C_1$ 是圈，故删除边后 $G$ 其上每个[[MK194][顶点]]要么不受影响，要么度减二

故 $G'_1$ 中顶点的度要么是 $0$ 要么仍为偶数，进一步与 $G'_1$ 中去除度为零的点形成 $G_1=<V_1,E_1>$

则 $G_1$ 上顶点的度仍为偶数，则根据[[MK226][定理1]]取 $C_2$ 

由于 $G$ 中的[[MK196][边]]为有限集，且每次去掉圈边数必减少

故依次类推后将在 $k$ 次后得 $G_{k}=<V_k,E_k>$ 无法继续

此时若 $V_k\ne\varnothing$ 则，则根据之前证明对于任意 $v\in V_k$ 可得 $d(v)$ 必为偶数

[[MK226][同理]]亦得存在圈，与无法继续矛盾，故 $V_k=\varnothing$

由于当且仅当度为零时，节点才会被去除，故必有 $E_k=\varnothing$ 才能删除说有 $V_{k-1}$ 中的节点

定义 $C=\{C_1,...,C_k\}$ 是该图的圈集，其中 $C_i=<U_i,F_i>$

******** 归纳法证明

********* 最小圈 $G_{k-1}$

由于 $G_k=<\varnothing,\varnothing>$ 则根据[[MK254][构建规则]]显然有 $G_{k-1}=C_k$

显然 $C_{k-1}$ 是[[MK225][圈]]，故无重复边，则是[[MK249][欧拉闭迹]]

********* 假设 $G_i$ 证明 $G_{i-1}$<<MK255>>

假设 $G_i$ 包含限条不[[MK242][连通]]的独立[[MK220][闭迹]]，且这些[[MK220][迹]]包含所有 $G_i$ 的[[MK194][顶点]]与[[MK196][边]]

根据[[MK254][构建规则]] $G_{i-1}$ 较 $G_i$ 新增边 $F_i$ ，且沿该组边以及所经过的节点形成[[MK225][圈]]

定义该[[MK225][圈]]为 $c=<u_1,f_1,...,f_m,u_1>$ 若不与 $G_i$ 中任意[[MK220][闭迹]]有公共[[MK194][顶点]]，则该圈为新增的独立[[MK220][闭迹]]

显然 $c$ 包含所有新增的[[MK194][顶点]]与[[MK196][边]]，故 $G_{i-1}$ 同样有有限条闭迹，且这些[[MK220][迹]]包含所有 $G_{i-1}$ 的[[MK194][顶点]]与[[MK196][边]]

若存在闭迹与 $c$ 有公共顶点，则去其中一条闭迹，定义为 $l=<v_1,e_1,...,e_n,v_1>$

由于 $f_i$ 均为新增边，故 $l$ 与 $t$ 无重边，假设公共点为 $v^*$

则存在[[MK222][闭迹]] $l'=<v^*,...,f_m,u_1,f_1,...,v^*,...e_n,v_1,e_1,...v^*>$ 经过 $l,t$ 上所有的的[[MK194][顶点]]与[[MK196][边]]

继续选取下一条有公共[[MK194][顶点]]的迹，形成新的闭迹

由于 $G_i$ 的独立闭迹有限，故依次类推直到只剩一条独立闭迹或不存在与 $c$ 有公共顶点的独立迹

则同样 $G_{i-1}$ 有若干条闭迹，且这些[[MK220][迹]]包含所有 $G_{i-1}$ 的[[MK194][顶点]]与[[MK196][边]]

********* 证明 $G_0$ 即 $G$ 本身

由于最小圈 $G_{k-1}$ 包含有限（一条）独立[[MK220][闭迹]]，且包含所有 $G_{k-1}$ 的[[MK194][顶点]]与[[MK196][边]]，以及 $k<\infty$

则根据[[MK255][之前证明]]可知 $G_1$ 亦包含有限条不[[MK242][连通]]的独立[[MK220][闭迹]]，且这些[[MK220][迹]]包含所有 $G_1$ 的[[MK194][顶点]]与[[MK196][边]]

由于 $G_0$ 是连通图，故 $C_1$ 必与每一条独立[[MK220][闭迹]]均有公共顶点

根据[[MK255][之前证明]]合并闭迹的方法依次类推，直至形成唯一闭迹。

同样根据[[MK255][之前证明]]该闭迹包含 $G$ 的所有[[MK194][顶点]]与[[MK196][边]]，即为[[MK249][欧拉闭迹]]

则 $G$ 是[[MK250][欧拉图]]

***** 定理2（无向欧拉迹）

有限无向图有[[MK248][欧拉迹]]的充要条件是：图 $G=<V,E>$ 是[[MK242][连通]]的，且仅有两个[[MK194][节点]]的[[MK203][度]]是奇数

****** 证明

******* 充分

若图 $G=<V,E>$ 有[[MK248][欧拉迹]]，则必有一条[[MK220][迹]] $l=<v_1,e_1,v_2,...,v_{n-1},e_{n-1},v_n>$ 经过所有所有[[MK194][节点]]和[[MK196][边]]

故对于 $v_i\in V\land v_i\ne v_1\land v_i\ne v_n$ 来说，必出现在上述拟路径中，且必有格式 $e_{i},v_i,e_{i+1}$ 每出现一次度增加 $2$

若出现 $n_i$ 次则 $d(v_i)=2n_i$ 即为偶数

对于 $v_1$ 同理 $d(v_1)=2n_i+1$ 为奇数，同理 $v_n$ 亦为奇数。

证毕。

******* 必要

由于[[MK242][连通]]，定义 $v_1,v_n$ 为度是奇数的两个节点。定义 $e^*=\{v_1,v_n\},E'=E\cup\{e^*\}$ 则有无向图 $G'=<V,E'>$

显然此时所有[[MK194][顶点]]的[[MK203][度]]均为偶数，故根据[[MK251][判定]] $G'$ 是[[MK250][欧拉图]]，存在[[MK249][欧拉闭迹]]经过所有[[MK194][节点]]和[[MK196][边]]

故 $e^*,v_1,v_n$ 必在其中，定义为 $t=<v_1,...,v_n,e^*,v_1>$

显然当 $t'=<v_1,...,v_n>$ 时 $t'$ 是 $G$ 中的[[MK220][迹]]，且经过 $G$ 的所有[[MK194][节点]]和[[MK196][边]]，即为[[MK248][欧拉迹]]

***** 定理3

假设[[MK209][无向图]] $G=<V,E>$ 有 $2n$ 个奇数[[MK194][顶点]]，

则 $G$ 的全部[[MK194][顶点]]和[[MK196][边]]可以排列成至少有 $n$ 条[[MK220][迹]]（要么是迹，要么是[[MK195][孤立点]]）

****** 证明

******* 可以排列成 $n$ 条

由于有 $2n$ 个奇数顶点，则有 $n$ 对奇数[[MK203][度]]的顶点。则在每对奇数度[[MK194][顶点]]间添加一条辅助[[MK196][边]]

此时所有顶点均有偶数度，根据[[MK251][定理1]]可得是欧拉图，有[[MK249][欧拉闭迹]]

然后去除所有辅助边，得 $n$ 条满足条件的[[MK220][迹]]（或[[MK195][孤立点]]）

由于去除的均为辅助边，且[[MK249][欧拉闭迹]]经过所有[[MK194][顶点]]和[[MK196][边]]，故这 $n$ 条迹亦经过所有点和边

******* 至少有 $n$ 条

设全部[[MK194][顶点]]和[[MK196][边]]可以排列成 $q$ 条开迹，且 $q<n$

则每条开迹的非两端[[MK194][顶点]]的[[MK203][度]]必为偶数，故仅可能在[[MK220][迹]]两端有奇数度的顶点。

故有且仅有 $2q$ 个偶数节点。由于假设 $q<n$ 故有 $2q<2n$ 与有 $2n$ 个奇数节点矛盾

故假设不成立，则证毕。

***** 定理4（判定有向图）

有限有向图为[[MK250][欧拉图]]的充要条件是：图 $G=<V,E>$ 是[[MK244][弱连通]]的，且任意[[MK194][节点]]的出[[MK203][度]]和入[[MK203][度]]相等

****** 证明<<MK256>>

******* 充分

若图 $G=<V,E>$ 是[[MK250][欧拉图]]，则有[[MK249][欧拉闭迹]]，即存在[[MK217][通道]] $t=<v_1,e_1,v_2,...,v_k,e_k,v_1>$ 

且其中 $e_i$ 不存在重复，且 $E=\{e_1,...,e_k\}$ ，即该[[MK220][闭迹]]包含所有[[MK196][边]]以及[[MK194][顶点]]

故 $\forall v\in V$ 均存在于 $t$ 中，且必以 $e_u,v,e_v$ 形式出现，该形式对于顶点 $v$ 出[[MK203][度]]和入[[MK203][度]]均增加 $1$

故对于任意节点，设在拟路径中出现的次数 $n$ ，则其出[[MK203][度]]和入[[MK203][度]]均为 $n$

由于有向[[MK220][迹]]连通所有[[MK194][节点]]，则显然转换为[[MK209][无向图]]是[[MK242][连通]]的

******* 必要

根据[[MK230][定理5]]采用[[MK253][有向图]]类似方法可证。此处暂时不多叙述

***** 定理5（有向欧拉迹）

有限有向图有[[MK248][欧拉路径]]的充要条件是：图 $G=<V,E>$ 是[[MK244][弱连通]]的，

且有一个[[MK194][节点]]的出[[MK203][度]]比另一个节点的入度大 $1$ ，其余节点出度入度相等

证明与[[MK256][之前证明]]类似

*** 哈密顿图

**** 定义

***** 哈密顿路<<MK257>>

若图 $G=<V,E>$ 存在一条通过所有[[MK194][节点]]的[[MK222][路]]，则称该路为图 $G$ 的哈密尔顿路。

***** 哈密顿圈<<MK258>>

若图 $G=<V,E>$ 存在一条通过所有[[MK194][节点]]的[[MK225][圈]]，则称该路为图 $G$ 的哈密尔顿圈。

***** 哈密顿图<<MK259>>

若图 $G=<V,E>$ 存在[[MK258][哈密顿圈]]，则称该路为图 $G$ 的哈密尔顿图。

定义所有哈密顿图集合 $\mathcal{H}$

**** 定理

***** 定理1

若[[MK209][无向图]] $G=<V,E>$ 是[[MK259][哈密顿图]]，定义 $G'=<S,E'>$ 是 $G$ 关于 $S$ 的[[MK216][导出子图]]

定义 $\omega(G')$ 是 $G'$ 的[[MK241][支]]的数量，则有 $\omega(G')\leq |S|$

****** 证明

由于是[[MK259][哈密顿图]]故存在[[MK258][哈密顿圈]]，定义为 $c=<v_1,e_1,...,e_n,v_1>$

显然 $c$ 包含所有[[MK194][节点]]，故 $c$ 包含的所有[[MK194][节点]]与[[MK196][边]]构成 $G$ 的[[MK215][生成子图]]，定义为 $H=<V,F>$

同时定义 $H$ 关于 $S$ 的[[MK216][导出子图]] $H'=<S,F'>$ 显然 $\omega(H')\leq |S|$
 
且有 $H'$ 是 $G'$ 的[[MK215][生成子图]]，即 $G'$ 与 $H'$ 顶点相同且 $F'\subset E'$

显然[[MK196][边]]数增加只会导致[[MK241][支]]的数量减少或不变，故必有 $\omega(G')\leq\omega(H')$

***** 定理2<<MK260>>

若 $G=<V,E>$ [[MK211][完全图]] $K_n$ 是[[MK259][哈密顿图]]

****** 证明

根据[[MK211][完全图]]定于可得对于任意两点 $\{u,v\}\subset V\rightarrow \{u,v\}\in E$

由于[[MK194][顶点]] $V$ 是[[MK82][有限集]]，故定义 $V=\{v_1,...,v_n\}$

则有[[MK225][圈]] $c=<v_1,\{v_1,v_2\},v_2,...,\{v_{n-1},v_n\},v_n,\{v_n,v_1\},v_1>$ 

显然其中每条[[MK196][边]]不重复，且除 $v_1$ 外无重复顶点，并且经过所有顶点。

故是[[MK258][哈密顿圈]]，则 $G$ 是[[MK259][哈密顿图]]

***** 定理3（Dirac定理）

若[[MK210][简单图]] $G=<V,E>$ 是 $(p,q)$ [[MK193][图]]且 $|V|=p>3$ 若 $\forall v\in V\rightarrow d(v)\geq\frac{p}{2}$ 

则 $G$ 是[[MK259][哈密顿图]]

****** 证明<<MK261>>

若 $G$ 不是[[MK259][哈密顿图]]，则根据[[MK260][定理2]] $G$ 不是[[MK211][完全图]]，则必有[[MK194][顶点]] $\{u,v\}\subset V$ 满足 $\{u,v\}\not\in E$

于是添加边 $\{u,v\}$ 到 $E$ 中形成 $E_1$ ，若 $G_1=<V,E_1>$ 仍不是[[MK259][哈密顿图]]，则继续添加边。

由于[[MK194][顶点]]与[[MK196][边]]均为[[MK82][有限集]]，故一直添加可使其成为[[MK211][完全图]]。

故根据[[MK260][定理2]]最终有 $G_k$ 是[[MK259][哈密顿图]]，定义[[MK258][哈密顿圈]]为 $c=<v_1,...,v_n,e_n,v_1>$

则取 $G_{k-1}=<V,E_{k-1}>$ 较 $G_k$ 少一条边且不是[[MK259][哈密顿图]]

则少去的边必在 $c$ 上，不妨设缺少了 $e_n$ 故有[[MK257][哈密顿路]] $r=<v_1,...,v_n>$

此时假设存在 $v_m$ 使得 $e_p=\{v_1,v_m\}\in E_{k-1}\land e_q=\{v_n,v_{m-1}\}\in E_{k-1}$ 

则有圈 $c=<v_1,...,v_{m-1},e_q,v_n,e_n,v_{n-1},...,e_{m+1},v_m,e_p,v_1>$

故 $v_n$ 不能与 $v_1$ 邻接的前一个节点邻接。

此时设 $d(v_1)=s$ 则有 $d(v_n)\leq p-1-k$ 故有 $d(v_1)+d(v_n)\leq p-1$

故有 $d(v_1)<\frac{p}{2}\lor d(v_n)<\frac{p}{2}$ 。

由于 $G$ 是 $G_{k-1}$ 的[[MK215][生成子图]]，故任意节点在 $G$ 的[[MK203][度]]小于等于 $G_{k-1}$ 中的度

综上所述，若 $G$ 不是哈密顿图，则存在 $v\in V$ 使得 $d(v)<\frac{p}{2}$ 

即 $G\not\in\mathcal{H}\rightarrow \exists v\in V\left(d(v)<\frac{p}{2}\right)$ 则根据[[~/文档/note/数理逻辑/sllj.org::MK182][量词转换]]以及[[~/文档/note/数理逻辑/sllj.org::MK53][假言易位]]有：

\begin{aligned}
&G\not\in\mathcal{H}\rightarrow \exists v\in V\left(d(v)<\frac{p}{2}\right)\\
{|\!\!\!=\!\!\!|}&\lnot(G\not\in\mathcal{H})\rightarrow \lnot\left(\exists v\in V\left(d(v)<\frac{p}{2}\right)\right)\\
{|\!\!\!=\!\!\!|}&G\in\mathcal{H}\rightarrow\forall v\in V\left(\lnot\left(d(v)<\frac{p}{2}\right)\right)\\
{|\!\!\!=\!\!\!|}&G\in\mathcal{H}\rightarrow\forall v\in V\left(d(v)\geq\frac{p}{2}\right)
\end{aligned}

证毕。

***** 定理4（Ore定理）

若[[MK210][简单图]] $G=<V,E>$ 是 $(p,q)$ 满足 $\forall \{u,v\}\subset V\land \{u,v\}\not\in E\rightarrow d(u)+d(v)\geq p$ 

则 $G$ 是[[MK259][哈密顿图]]

****** 证明

根据[[MK261][之前证明]]可得若 $G$ 不是[[MK259][哈密顿图]]，则存在两点 $v_1,v_n$ 满足 $\{v_1,v_n\}\not\in E$ 且 $d(v_1)+d(v_n)\leq p-1$

故同样根据之前证明可得其逆否命题成立 $G\in\mathcal{H}\rightarrow\left(\forall v\in V\forall u\in V\left(\{u,v\}\not\in E\rightarrow d(u)+d(v)\geq p\right)\right)$

***** 定理5

若[[MK242][连通]]的[[MK210][简单图]] $G=<V,E>$ 是 $(p,q)$ 满足 $\forall \{u,v\}\subset V\land \{u,v\}\not\in E\rightarrow d(u)+d(v)\geq p-1$ 

则 $G$ 有[[MK257][哈密顿路]]

****** 证明

定义 $G$ 中的[[MK223][最长路]] $r=<v_1,...,v_n>$ 则根据条件有 $d(v_1)+d(v_n)\geq p-1$

则假设（1）存在 $v\in V$ 不在 $r$ 上，

显然对于任意 $v$ 与 $v_1,v_k$ 之间不存在[[MK196][边]]否则 $r$ 不是最长路，故与 $v_1,v_k$ 邻接的[[MK194][节点]]必在 $r$ 上。

假设（2） $r$ 上不存在[[MK225][圈]]，则根据[[MK261][之前证明]]故 $v_n$ 不能与 $v_1$ 邻接的前一个节点邻接。

故可得 $d(v_1)+d(v_k)\leq n-1$ 且由于存在 $v$ 有 $n\leq p-1$ 

则有 $d(v_1)+d(v_1)\leq n-1\leq p-2<p-1$ 与条件矛盾

故在假设（1）的基础上假设（2）不成立，即在假设（1）的基础上 $r$ 上存在圈

定义 $r$ 上的圈为 $c=<v_z,...,v_{z-1},v_z>$

由于存在圈且[[MK242][连通]]，故必有 $r$ 上的 $v_k$ 与 $v$ 相连，则存在 $r'=<v,v_k,...,v_z,...v_{k-1}>$

显然又与最长路矛盾，故假设（1）不成立，即不存在 $v\in V$ 不在 $r$ 上

则 $r$ 包含所有节点，即为[[MK257][哈密顿路]]

*** 无向树

**** 基础定义

***** 定义<<MK262>>

一个[[MK242][连通]]无[[MK225][圈]]的[[MK210][简单图]] $G=<V,E>$ 定义为树

***** 平凡树<<MK263>>

只有一个顶点的[[MK262][树]]

***** 叶<<MK264>>

[[MK203][度]]为 $1$ 的[[MK194][顶点]]成为该树的叶

****** 推论<<MK265>>

非[[MK263][平凡树]]至少有两个[[MK264][叶]]

******* 证明

定义 $G=<V,E>$ 是[[MK262][树]]，则其[[MK223][最长路]]为 $r=<v_1,...,v_n>$

若 $d(v_1)\ne1$ 则要么有不在 $r$ 上的[[MK194][顶点]]与之邻接，则 $r$ 不是最长路

要么存在 $r$ 上的顶点与之邻接，则形成[[MK225][圈]]，与[[MK262][树]]定义矛盾。

故 $d(v_1)=1$ 同理可证 $d(v_n)=1$

***** 分支<<MK266>>

非[[MK264][叶]]节点称作分支点

***** 森林

一个无[[MK225][圈]]的[[MK210][简单图]] $G=<V,E>$ 定义为森林

对比[[MK262][树]]去除了[[MK242][连通]]条件。树也是森林

***** 偏心率<<MK267>>

定义[[MK262][树]] $G=<V,E>$ 对于任意[[MK194][顶点]] $v\in V$ 定义 $e(v)=\max\left\{\phi(u,v)\big|u\in V\right\}$ 

其中 $\phi(u,v)$ 是 $u,v$ 两点间的[[MK233][距离]]

***** 半径<<MK268>>

定义[[MK262][树]] $G=<V,E>$ 定义其半径 $r(G)=\min\left\{e(v)\big|v\in V\right\}$ 

其中 $e(v)$ 是[[MK194][顶点]] $v$ 的[[MK267][偏心率]]

***** 中心<<MK269>>

定义[[MK262][树]] $G=<V,E>$ 定义 $H=\left\{v\big|e(v)=r(G)\right\}$ 则称 $H$ 是树 $G$ 的中心

其中 $e(v)$ 是[[MK194][顶点]] $v$ 的[[MK267][偏心率]]， $r(G)$ 是树的[[MK268][半径]]

****** 推论

树仅有一个或者两个中心，可用去[[MK264][叶]]法找到

******* 证明

定义[[MK262][树]] $G=<V,E>$ 对于任意[[MK264][叶]] $v$ 任意 $u\in V$ 到 $v$ 均需要经过连接 $v$ 的[[MK266][分支]] $v'$

则可得 $\phi(u,v)=\phi(u,v')+1$ 即有 $e(v)>e(v')$ 其中 $\phi$ 是的[[MK233][距离]] $e$ 是[[MK267][偏心率]]

则定义去除所有[[MK264][叶]]后的[[MK216][导出子图]]为 $G_1=<V_1,E_1>$ 

则有 $V_1$ 中包含的[[MK194][顶点]]在 $G$ 中的[[MK267][偏心率]]大于 $V-V_1$ 中包含的顶点在 $G$ 中的偏心率

依次类推可得 $V_k$ 中包含的[[MK194][顶点]]在 $G$ 中的[[MK267][偏心率]]大于 $V_{k-1}-V_k$ 中包含的顶点在 $G$ 中的偏心率

即大于 $V-V_k$ 中包含的顶点在 $G$ 中的偏心率

根据[[MK265][推论]]可得 $V_k\ne\varnothing$ 时至少有两个叶。故当 $V_k$ 仅有一个或两个顶点时无法继续

则证毕 

**** 等价条件

[[MK210][简单图]] $G=<V,E>$ 是 $(p,q)$ [[MK193][图]]，则以下五个命题等价：

（1） $G$ 是[[MK262][树]]

（2） $G$ 中任意两个[[MK194][顶点]]有唯一[[MK222][路]]

（3） $G$ [[MK242][连通]]且 $p=q+1$

（4） $G$ 中无[[MK225][圈]]且 $p=q+1$

（5） $G$ 中无[[MK225][圈]]，且 $G$ 中任意两个不邻接的[[MK194][顶点]]间加一条边，得到一个有唯一圈的图

（6） $G$ 是[[MK245][极小连通图]]

***** 证明

****** （1）证（2）

（1）成立，则 $G$ 是[[MK262][树]]

故[[MK242][连通]]，则对于任意 $\{u,v\}\subset V$ 均有是[[MK220][迹]]，根据[[MK224][定理]]则有[[MK222][路]]

若 $u,v$ 之间存在两条路，则根据[[MK228][定理]]存在[[MK225][圈]]，与树矛盾。

故 $u,v$ 之间有唯一路。证毕

****** （2）证（3）

（2）成立，则 $G$ 中任意两个[[MK194][顶点]]有唯一[[MK222][路]]，则 $G$ [[MK242][连通]]

假设对于有 $p$ 个顶点的图 $G$ ，若任意两个[[MK194][顶点]]有唯一[[MK222][路]]，则有 $p=q+1$ 即 $q=p-1$

则对于 $p'=p+1$ 个顶点的 $(p',q')$ 图 $G'$ 若有任意两个[[MK194][顶点]]有唯一[[MK222][路]]时：

若此时 $q'=p-1$ 则无新增边，显然 $G$ 中的顶点与新增顶点不连通，故假设不成立

若此时 $q'>p$ 由于是[[MK210][简单图]]，故无重边，则新增的顶点 $v'$ 必有两条新增边，假设与 $v_1,v_2$ 相连

由于 $v_1,v_2$ 存在路，故此时 $<v_1,e_1,v',e_2,v_2>$ 形成新的路，则 $G'$ 中存在两个点之间有两条路

故矛盾，假设亦不成立。

故当 $(p,q)$ 图满足任意两个[[MK194][顶点]]有唯一[[MK222][路]]时，有 $p=q+1$ 

则 $(p'=q+1,q')$ 图满足任意两个[[MK194][顶点]]有唯一[[MK222][路]]时亦有 $p'=q'+1$ 

显然 $(2,q)$ 图若任意两个[[MK194][顶点]]有唯一[[MK222][路]]的，则满足 $p=q+1$ 

则根据数学归纳法，对于任意 $|V|<\infty$ 的图 $G$ 若有任意两个[[MK194][顶点]]有唯一[[MK222][路]]，则有 $p=q+1$ 

由于[[MK194][顶点]]是有限集，则证毕 

****** （3）证（4）

（3）成立，则 $G$ [[MK242][连通]]且 $p=q+1$

假设有[[MK225][圈]] $c=<v_1,...,v_n,e_n,v_1>$ 则显然 $c$ 中至少包含 $n$ 条[[MK196][边]]，故 $n\leq q$

此时若 $p=n$ 则有 $p=n\leq q$ 与 $p=q+1$ 矛盾

若 $p>n$ 则有不在 $c$ 上的[[MK194][顶点]] $p-n$ 个。由于连通，故每个顶点与 $c$ 至少存在一条边

故边数 $q\geq n+p-n\geq p$ 显然与 $p=q+1$ 矛盾

故假设不成立 $G$ 中不含[[MK225][圈]]

****** （4）证（5）

（4）成立，则有 $(p,q)$ 图 $G$ 中无[[MK225][圈]]且 $p=q+1$

假设 $G$ 不[[MK242][连通]]，则 $G$ 有 $k\geq 2$ 个支，根据[[MK241][推论]]可得每个支是 $G$ 的连通子图

根据（4）可得 $G$ 无[[MK225][圈]]，则其支 $G_i$ 亦无[[MK225][圈]]，则根据[[MK262][定义]] $G_i$ 是树，定义 $G_i$ 是 $(p_i,q_i)$ [[MK193][图]]

则根据（1）证（2），（2）证（3）可得 $p_k=q_k+1$ 根据[[MK241][推论]]亦有 $p=\sum_{i=1}^k p_k,q=\sum_{i=1}^k q_k$

则 $p=q+k$ 由于条件有 $k=1$ 矛盾，故假设不成立， $G$ [[MK242][连通]]

则又根据[[MK262][定义]]有 $G$ 是[[MK262][树]]，进一步根据（1）证（2）可得对于任意两个[[MK194][顶点]]有唯一[[MK222][路]]

则显然，添加边后有唯一圈。

****** （5）证（1）

（5）成立，则有 $(p,q)$ 图 $G$ 中无[[MK225][圈]]且中任意两个不邻接的[[MK194][顶点]]间加一条边，得到一个有唯一圈

则对于任意两个不邻接顶点 $\{u,v\}\subset V$ 添加[[MK196][边]]有唯一圈，则圈必定经过 $u,v$ 定义 $c=<u,...,v,e,u>$

则去掉 $e$ 后有[[MK222][路]] $r=<u,...,v>$ 则对于任意 $\{u,v\}\subset V$ 要么邻接，要么存在路

故 $G$ [[MK242][连通]]，结合无[[MK225][圈]]可得 $G$ 是[[MK262][树]]

****** （1）与（6）充要

******* 充分

由于（1）则有（2），则对于任意 $e=\{u,v\}\in E$ 可得去除 $e$ 后 $u,v$ 间不含其他[[MK222][路]]

则 $G'=<V,E/\{e\}>$ 不是[[MK242][连通图]]

******* 必要

若 $G$ 是[[MK245][极小连通图]]则 $G$ [[MK242][连通]]，此时假设存在[[MK225][圈]] $c=<v_1,...,v_n,e_n,v_1>$

则去除 $e_n$ 显然图仍然连通。故假设不成立 $G$ 中无圈

故 $G$ [[MK242][连通]]，结合无[[MK225][圈]]可得 $G$ 是[[MK262][树]]

**** 性质

***** 树是简单图

根据[[MK262][定义]]，树无回路，即无环。且树为无向无重边图，即满足[[MK210][简单图]]定义

***** 树是[[MK246][双图]]

树 $G=<V,E>$ 取任一 $v\in V$ ，定义 $X$ 为到 $v$ 的[[MK232][距离]]为奇数的[[MK194][节点]]， $Y$ 为到 $v$ 的[[MK232][距离]]为偶数的[[MK194][节点]]

若任一节点 $v'\in X\land v'\in Y$ ，则必有两条不同的[[MK217][拟路径]]连接 $v,v'$ 根据[[MK228][通路定理]]必有两条[[MK225][通路]]形成[[MK225][回路]]

故有 $X\cap Y=\varnothing$

由于[[MK262][树]]为连通图，故所有节点到 $v$ 均存在[[MK220][路径]]，即 $X\cup Y=V$

对于任意 $\{v_1,v_2\}\subset X$ 若 存在边 $e=\{v_1,v_2\}$ 根据 $v_1,v_2$ 均与 $v$ 存在通路，

则存在 $v,...,v_1,e,v_2,...,v$ 的回路，与条件不符。

故 $X$ 中的点不连通。综上所述，树为二分图。

***** 树是平面图

根据[[MK262][定义]]树不含[[MK225][回路]]，进一步根据[[MK291][等价条件]] $K_{5},K_{3,3}$ 均含回路，故不可能为树的子图。

故树是平面图。
 
**** 生成树

***** 定义<<MK270>>

若图 $T,G$ 满足：

（1） $T$ 是 $G$ 的[[MK215][生成子图]]

（2） $T$ 是[[MK262][树]]

则 $T$ 称为 $G$ 的生成树。

***** 定理

[[MK210][简单图]] $G=<V,E>$ 有[[MK270][生成树]]的充要体案件是 $G$ [[MK242][连通]]

****** 证明

******* 充分

若 $G$ 有生成树，故有[[MK215][生成子图]] $T$ 且是[[MK262][树]]。则 $T$ 连通。

根据[[MK215][生成子图]]定义 $G$ 与 $T$ [[MK194][顶点]]相同，[[MK196][边]]包含 $T$ 的边。故 $G$ 亦连通

******* 必要

如果无向连通图 $G$ 有回路，则删去回路上的一条边，然后继续构造直到没有回路

*** 有向树

*** 有向树<<MK271>>

[[MK244][弱连通]]且无[[MK225][弱圈]]的[[MK193][图]]定义为有向树

*** 有根树<<MK272>>

若[[MK206][有向图]] $G=<V,E>$ 满足：

（1） $\exists v\in V\rightarrow d^-(v)=0$

（2） $\forall v'\in V/\{v\}\rightarrow d^-(v')=1$

（3） 是[[MK271][有向树]]

此时 $v$ 成为树根，任意 $v^*\in V\rightarrow d^+(v^*)=0$ 成为树叶

其余的[[MK194][顶点]]定义为分支/节点

**** 等价条件<<MK273>>

若[[MK206][有向图]] $G=<V,E>$ 是有根树的充要条件是

存在 $v\in V$ 满足对于任意 $u\in V/\{v\}$ 均有 $v$ [[MK231][有向可达]] $u$ 且 $G$ 中没有[[MK225][弱圈]]

***** 证明

****** 充分<<MK274>>

若 $G$ 是有根树，则存在树根 $v$ 由于 $d^-(u)=1$ 故必存在 $u_1$ 满足 $e_1=<u_1,u>\in E$

若 $u_1\ne v$ 则有 $d^-(u_1)=1$ ，则必有 $<u_2,u_1>\in E$

依次类推，由于[[MK194][顶点]] $|V|<\infty$ 故必有以 $u$ 结尾的最长[[MK222][有向路]] $r=<u_k,...,u_1,e_1,u>$

此时假设 $u_k\ne v$ 则必有 $e=<u_{k+1},u_k>\in E$ 若 $u_{k+1}$ 在 $r$ 上，则有[[MK225][弱圈]]与有根树定义矛盾

若 $u_{k+1}$ 不在 $r$ 上，则有 $r'=<u_{k+1},e,u_k,...,u>$ [[MK232][长度]]大于 $r$ 与最长路矛盾

故假设不成立，必有 $v=u_k$ 则有路 $r=<v,...,u>$ 即 $v$ 到 $u$ [[MK231][有向可达]]

无弱圈条件等价，故充分性证毕

****** 必要

若存在 $v\in V$ 满足对于任意 $u\in V/\{v\}$ 均有 $v$ 到 $u$ [[MK231][有向可达]]且 $G$ 中没有[[MK225][弱圈]]

假设 $d^-(v)=1$ 则必有 $e=<u,v>\in E$ 由于可达，故存在[[MK222][有向路]] $r=<v,...,u>$

故有[[MK225][弱圈]] $c=<v,...,u,e,v>$ 与条件矛盾，故假设不成立 $d^-(v)=0$

若存在 $u\in V/\{v\}$ 满足 $d^-(u)>1$ 则有 $d^-(u)\geq 2$

则任取两条[[MK196][边]]，分别去经过这两条边的最长路，根据[[MK274][之前证明]]可得必终结于 $v$

故必有[[MK225][弱圈]]，矛盾。故有假设不成立，不存在 $u\in V/\{v\}$ 且 $d^-(u)>1$

无弱圈条件等价，故必要性证毕

**** 性质

***** 性质1<<MK275>>

对于任意 $u\in V/\{v\}$ 其中 $v$ 是树根，有唯一[[MK222][有向路]] $r=<v,e_1,u_1,...,u_{n-1},e_n,u>$

****** 证明

假设存在两条不同有向路，则有[[MK225][弱圈]]，与定义矛盾，则假设不成立

***** 性质2

对于任意 $\{u,v\}\subset V$ 至多存在一条[[MK222][有向路]] $r=<u,e_1,u_1,...,u_{n-1},e_n,v>$

****** 证明

若存在多条，则有[[MK225][弱圈]]

***** 性质3<<MK276>>

对于任意 $\{u,v\}\subset V$ 若 $\mathcal{D}(u)<\mathcal{D}(v)$ 且 $u$ 到 $v$ [[MK231][有向可达]]

则树根 $r$ 到 $v$ 的[[MK222][有向路]]必经过 $u$

****** 证明

根据[[MK275][性质1]]可得 $r$ 到 $u,v$ 均[[MK231][有向可达]]

假设存在 $r$ 到 $v$ 的[[MK222][有向路]]不经过 $u$ 则有[[MK225][弱圈]]，矛盾故假设不成立

***** 性质4<<MK277>>

对于任意 $\{u,v\}\subset V$ 若有[[MK222][有向路]] $r=<u,e,v>$

则任意 $z\in V\land z\not\in\{u,v\}$ 满足 $z$ 到 $v$ [[MK231][有向可达]]，其[[MK222][有向路]]必经过 $u$

****** 证明

若存在不经过 $u$ 的路，则 $d^-(v)=2$ 与定义矛盾。

**** 定理

***** 定理1<<MK278>>

有根树 $G=<V,E>$ 中任意不是树根 $r$ 的[[MK280][分支]] $v$ 

定义 $Y=\mathcal{A}(v)\cup\{v\}$ 其中 $\mathcal{A}(v)$ 是 $v$ 的所有[[MK231][有向可达]]的[[MK194][节点]]的集合

定义 $X=M/Y\cup\{v\}$ 

则 $G_Y=<Y,Y\times Y\cap E>,G_X=<X,X\times X\cap E>$ 均为有根树

****** 证明

仅证 $G_X$ 对于 $G_Y$ 类似可证

显然 $G_X$ 是[[MK206][有向图]]，根据[[MK273][等价条件]]依次证明

******* 无弱圈

由于 $X\subset V,E_X\subset E$ ，则若 $G_X$ 有[[MK225][弱圈]] $<v_1,...,v_n,e_n,v_1>$

则 $G$ 中亦有圈，与 $G$ 是有根树矛盾，故 $G_X$ 无弱圈

******* 任意非树根节点可达

对于任意 $z\in X$ 在图 $G$ 中根据[[MK275][性质1]]有 $r$ 到 $z$ 有向可达

则有通路 $<r,...,z>$ 若经过任意 $x\in Y$ 则 $v$ 到 $z$ 可达，故有 $z\in Y$

若 $z\ne v$ 则与 $z\in X$ 矛盾，若 $z=v$ 则与之前证明无弱圈矛盾，故通路不经过任意 $x\in Y$

由于 $E_X=X\times X\cap E$ 故在 $G_X$ 中 $r$ 到 $z$ 亦有向可达

**** 其他定义

***** 叶<<MK279>>

若[[MK272][有根树]] $G=<V,E>$ 若有 $v\in V$ 满足 $d^+(v)=0$ 则定义 $v$ 是 $G$ 的叶

并定义 $\mathcal{L}(V)$ 是 $G$ 所有叶的集合

****** 定理1

[[MK272][有根树]] $G=<V,E>$ 必有叶

******* 证明 

假设无叶，则对于任意[[MK217][通道]] $t=<v_1,...,v_n>$ 由于 $d^+(v_n)>0$

则必有 $e_n=<v_n,v_{n+1}>\in E\land v_{n+1}\in V$ 故有 $t_1=<v_1,...,v_{n+1}>$

由于 $|V|<\infty$ 故必有[[MK225][圈]]，与[[MK272][定义]]矛盾

故假设不成立，必有叶

****** 定理2

[[MK272][有根树]] $G=<V,E>$ 若 $|V|>1$ 则 $r\not\in\mathcal{L}(V)$ 其中 $r$ 是树根

******* 证明

假设 $r\in\mathcal{L}(V)$ 则 $d^+(r)=0$ 又因为 $r$ 是树根，故有 $d^-(r)=0$

则不存在边连接 $r$ ，故 $G$ 不是[[MK244][弱连通]]，则不是[[MK271][有向树]]，故不是有根树

与条件矛盾，故假设不成立 $r\not\in\mathcal{L}(V)$ 
 
***** 分支<<MK280>>

不是[[MK279][叶]]的[[MK194][节点]]定义为分支

***** 深度<<MK281>>

若[[MK272][有根树]] $G=<V,E>$ 以 $v$ 为树根

对于任意 $u\in V/\{v\}$ 定义 $\phi(v,u)$ 即 $u,v$ 的[[MK233][距离]]为 $u$ 的深度，记作 $\mathcal{D}(u)$

***** 高<<MK282>>

若[[MK272][有根树]] $G=<V,E>$ 

若[[MK194][节点]] $v$ 是[[MK266][分支]]，则高定义为 $\mathcal{H}(v)=\max\left\{\phi(v,u)\big|u\in V/\{v\}\right\}$

即 $v$ 与其所有[[MK232][有向可达]]节点的最大[[MK233][距离]]

若[[MK194][节点]] $v$ 不是[[MK266][分支]]，则高 $\mathcal{H}(v)=0$

[[MK272][树根]] $r$ 的节点亦定义为树的高，即 $\mathcal{H}(r)=\mathcal{H}(v)$

***** 层<<MK283>>

若[[MK272][有根树]] $G=<V,E>$ 以 $v$ 为树根，所有[[MK281][深度]]为 $k$ 的顶点的集合统称为该图的第 $k$ 层

即 $L_k=\left\{u\big|\phi(v,u)=k\land u\in V\right\}$

***** 父子<<MK284>>

若[[MK272][有根树]] $G=<V,E>$ 若 $<u,v>\in E$ 则称 $v$ 是 $u$ 的父[[MK194][顶点]]， $u$ 是 $v$ 的子顶点

定义 $\mathcal{P}(v)=\left\{u\big|<u,v>\in E\right\}$ 为顶点 $v$ 的父顶点集

定义 $\mathcal{S}(v)=\left\{u\big|<v,u>\in E\right\}$ 为顶点 $v$ 的子节点集

***** 子树<<MK285>>

若[[MK272][有根树]] $G=<V,E>$ 对于任意 $u\in V/\{r\}$ 其中 $r$ 是树根，则定义

（1） $V_s(u)=\left\{x\big|x\in V\land <u,x>\in\mathcal{T}\right\}$ 其中 $\mathcal{T}$ 是[[MK237][通道关系]]

（2） $E_s(u)=\left\{<x,y>\big|\{x,y\}\in V_s(u)\land <x,y>\in E\right\}$

则有[[MK214][子图]] $G_s(u)=<V_s(u),E_s(u)>$ 由于原图不含弱圈，且 $d^-(u)=1$

故易证 $G_s(u)$ 亦为有根树且根为 $u$

***** 兄弟节点<<MK286>>

若[[MK272][有根树]] $G=<V,E>$ 定义 $V'=V/\{r\}$ 即去除[[MK272][根]]

定义[[MK111][关系]] $\mathcal{B}\subset V'\times V'$ 为 $\mathcal{B}=\left\{<v,w>\big|(\exists u\in V\rightarrow\{<u,v>,<u,w>\}\subset E\right\}$

则若 $\{v,w\}\subset V'$ 满足 $v\mathcal{B}w$ 则称 $v,w$ 互为兄弟[[MK194][节点]]

****** 性质

对于任意 $\{v,w,x\}\subset V'$

******* 对称性

显然 $v\mathcal{B}w\rightarrow w\mathcal{B}v$

******* 自反性

显然 $v\mathcal{B}v$

******* 传递性

$v\mathcal{B}w\land w\mathcal{B}x\rightarrow v\mathcal{B}x$

******** 证明 

若有 $v\mathcal{B}w\land w\mathcal{B}x$ 则存在 $\{<p,v>,<p,w>\}\subset E\land \{<q,w>,<q,x>\}\subset E$

根据[[MK272][有根树]]定义，由于 $w\in V'$ 则有 $d^-(w)=1$ 则假设 $p\ne q$ 则 $d^-(w)=2$ 矛盾。

故假设不成立，有 $q=p$ 则有 $\{<p,v>,<p,x>\}\subset E$ 即 $v\mathcal{B}w\land w\mathcal{B}x\rightarrow v\mathcal{B}x$ 

******* 等价关系<<MK287>>

由定义可知 $\mathcal{B}$ 是 $V'$ 上的[[MK111][二元关系]]

结合之前证明，可得 $\mathcal{B}$ 是[[MK132][等价关系]]

则对于任意 $v\in V$ 定义 $[v]_\mathcal{B}$ 是 $v$ 的[[MK133][等价类]]，亦称 $v$ 的兄弟类

******* 划分

根据[[MK287][之前证明]] $\mathcal{B}$ 是 $V'$ 上的[[MK132][等价关系]]，则根据[[MK138][定理1]]得 $\mathcal{B}$ 的兄弟集合划分 $V'$

******* 兄弟节点[[MK281][深度]]相等

若有 $v\mathcal{B}w$ 则有 $\{v,w\}\subset V'$ 根据[[MK273][等价条件]]可得树[[MK272][根]] $r$ 到 $u,v$ 均[[MK231][有向可达]]

由于 $v\mahtcal{B}w$ 故 $v,w$ 分别有唯一射入边 $<u,v>,<u,w>$

根据[[MK272][有根树]]定义必为[[MK271][有向树]]则无[[MK225][弱圈]]，故 $r,u$ 之间存在唯一[[MK222][有向路]]

则显然有 $\phi(r,v)=\phi(r,w)=\phi(r,u)+1$

** 图的矩阵表示

*** 邻接矩阵<<MK288>>

对于无[[MK198][重边]]的[[MK206][有向图]] $G=<V,E>$ 其邻接矩阵定义为 $A=\{a_{ij}\}$ 其中 $a_{ij}=\begin{cases}1&<v_i,v_j>\in E\\0&<v_i,v_j>\not\in E\end{cases}$

对于无[[MK198][重边]]的[[MK209][无向图]] $G=<V,E>$ 其邻接矩阵定义为 $A=\{a_{ij}\}$ 其中 $a_{ij}=\begin{cases}1&\{v_i,v_j\}\in E\\0&\{v_i,v_j\}\not\in E\end{cases}$

**** 性质

***** 性质1

无向图的邻接矩阵是对角线对称矩阵

***** 性质2

若 $|V|=n$ 则

对有向图，[[MK194][顶点]] $v_k\in V$ 其[[MK203][出度]]为 $d^+(v_k)=\sum_{i=1}^na_{ki}$ 

即[[MK288][邻接矩阵]]行的和，入度为 $d^-(v_k)=\sum_{i=1}^na_{ik}$ 即[[MK288][邻接矩阵]]列的和

对无向图，[[MK194][顶点]] $v_k\in V$ 其[[MK203][度]]为 $d(v_k)=\sum_{i=1}^na_{ki}$ 或 $d(v_k)=\sum_{i=1}^na_{ik}$ 

**** 定理

***** 定理1

$A^n=A\times...\times A=\left\{a^{(n)}_{ij}\right\}$ 是 $n$ 个[[MK288][邻接矩阵]]相乘，则 $a^{(n)}_{ij}$ 为[[MK194][节点]] $v_i$ 到 $v_j$ 长度为 $n$ 的[[MK217][通道]]条数

****** 证明<<MK289>>

[[MK288][邻接矩阵]]与自身相乘 $A\times A=A^2=\left\{a^{(2)}_{ij}\right\}$ 

则有 $a^{(2)}_{ij}=\sum_{k=1}^na_{ik}a_{kj}$ 当且仅当 $a_{ik}>0\land a_{kj}>0$ 时 $a_{ik}a_{kj}>0$

故 $a^{(2)}_{ij}$ 为 $v_i$ 到 $v_j$ 经过边数为 $2$ 的[[MK217][拟路径]]条数。

当 $n-1$ 成立时 $A^{n-1}\times A=\left\{a^{(n)}_{ij}\right\}$ 其中 $a^{(n)}_{ij}=\sum_{k=1}^na^{(n-1)}_{ik}a_{kj}$ 

这里面 $a^{(n-1)}_{ik}$ 为 $v_i$ 到 $v_k$ 长度为 $n-1$ 拟路径条数，若此时 $<v_k,v_j>\in E$ 

则 $v_i$ 可通过 $a^{(n-1)}_{ik}$ 条拟路径到达 $v_k$ 在由 $v_k$ 到达 $v_j$

故 $a^{(n)}_{ij}$ 为 $v_i$ 到 $v_j$ 长度为 $n$ 的[[MK217][拟路径]]条数

***** 定理2

定义 $A^{|V|}=\left\{ a_{ij} \right\}$ 定义 $b_{ij}=\begin{cases}1&a_{ij}\ne0\\0&a_{ij}=0\end{cases}$ 定义矩阵 $B=\{b_{ij}\}$ 

则矩阵 $B$ 为路径矩阵，若 $b_{ij}=1$ 则[[MK194][节点]] $v_i$ 到 $v_j$ 存在[[MK220][迹]]

****** 证明

根据[[MK289][之前证明]]同理可证 $A^{(n)}=\left\{a^{(n)}_{ij}\right\}$ 中 $\left\{a^{(2)}_{ij}\right\}$ 表示[[MK194][节点]] $v_i$ 到 $v_j$ 存在长度为 $n$ 的[[MK217][通道]]

则 $b_{ij}$ 表示[[MK194][节点]] $v_i$ 到 $v_j$ 存在拟路径，根据[[MK221][定理]]可知必存在[[MK220][迹]]

*** 关联矩阵

若[[MK210][简单图]] $G=<V,E>$ 其中 $V=\{v_1,...,v_n\},E=\{e_1,...,e_m\}$ 

则关联矩阵 $A_{mn}=\{a_{ij}\}$ 其中根据[[MK105][有序组]]定义 $a_{ij}=\begin{cases}1&\{v_i\}\in e_j\\0&\{v_i\}\not\in e_j\end{cases}$

** 图算法

*** 拓扑排序<<MK290>>

定义[[MK207][有向无圈图]] $G=<V,E>$ 为依赖关系。求满足 $G$ 定义的排序

**** 计算

第一步：

求所有 $G$ 中[[MK203][入度]]为 $0$ 的[[MK194][顶点]]作为最前排序，定义为 $V'_1$

根据[[MK208][定理]]可得 $G$ 中必然存在[[MK203][入度]]为 $0$ 的[[MK194][顶点]]，根据排序要求此类顶点无依赖

第二步：

定义 $V_1=V/V'_1$ 并有[[MK216][导出子图]] $G_1=<V_1,E_2>$

第三步：

从 $G_1$ 中寻找入度为 $0$ 的顶点作为最前排序

显然 $G_1$ 仍为[[MK207][有向无圈图]]，故[[MK208][同理]]必有入度为 $0$ 的顶点

以后几步：

依次类推直至 $V_k=\varnothing$ 由于 $G_i$ 均为[[MK207][有向无圈图]]，故必有入度为 $0$ 的顶点

且 $|V|<\infty$ 故终有 $V_k=\varnothing$

*** 最小生成树

定义[[MK210][简单图]] $G=<V,E,g>$ 其中 $g$ 为[[MK196][边]]的[[MK202][赋权函数]]

则求 $G$ 的[[MK270][生成树]] $T$ 使得 $T$ 包含的所有[[MK196][边]]的赋权和最小

以下方法均可用数学归纳法证明

**** Prime

任取一顶点 $v_1\in V$ ，取与之相连的赋权值最小的边，定义为 $e_1=\{v_1,v_2\}$

然后取与 $v_1,v_2$ 相连的不形成[[MK225][圈]]的最小边，定义为 $e_2=\{v,v_3\}$ 其中 $v$ 是 $v_1,v_2$ 的任意一点

依次类推，由于[[MK194][顶点]]是[[MK82][有限集]]，故可以取到包含所有顶点。

**** Kruscal

将 $g(e),e\in E$ 排序，依次取赋权最小的，每取一次判断是否形成[[MK225][圈]]。

若形成圈，则取下一条最小的。直到连通

** 平面图

*** 定义

若[[MK209][无向图]] $G=<V,E>$ 满足：

（1） 可以在一个平面上图示出来

（2） 各[[MK196][边]]仅在顶点处相交

则称为平面图

*** 最小非平面图

顶点数最少的非平面图是 $5$ 个[[MK194][节点]]的[[MK211][完全图]]，即 $K_5$

边数最少的是 $X,Y$ 均有 $3$ 个[[MK194][节点]]的[[MK246][完全二分图]]，即 $K_{3,3}$

*** 平面图等价条件<<MK291>>

$G$ 或者 $G$ 的[[MK214][子图]]作任何同胚操作后得到的图均不能以 $K_5$ 及 $K_{3,3}$ 为子图

*** 同胚操作

在原图的边上增加或者删除二[[MK203][度]]的[[MK194][节点]]。

其本身将一条边分解为一个节点两条边，或做相反操作。不改变图的平面性质。

* 抽象代数

** 代数的构建

*** 运算

**** 定义<<MK292>>

运算是集合 $S^n=S\times ...\times S$（即 $n$ 个 $S$ 的[[MK107][笛卡尔积]]）到 $S$ 的[[MK175][函数]] 

通常用 $*$ 表示二元运算，如 $*(x,y)=x*y$

通常用 $\Delta$ 表示一元运算，如 $\Delta x$

**** 基本性质<<MK293>>

所有二元运算均满足：

普遍性： $S$ 中的所有元素均可参与运算

单值性<<MK294>>： $\forall x\forall y\forall x'\forall y'(x=x'\land y=y'\rightarrow x*y=x'*y')$

封闭性： $\forall x\forall y(x\in S\land y\in S\rightarrow x*y\in S)$

**** 一般性质

二元运算可以满足：

结合律<<MK295>>： $\forall x\forall y\forall z\left(\{x,y,z\}\subset S\rightarrow (x*y)*z=x*(y*z)\right)$

交换律<<MK296>>： $\forall x\forall y(\{x,y\}\subset S\rightarrow x*y=y*x)$

分配率<<MK297>>： 对于运算 $*,\#$ 有 $\forall x\forall y\forall z\left(\{x,y,z\}\subset S\rightarrow x*(y\#z)=x*y\#x*z)\right)$ 则称运算 $*$ 对 $\#$ 可分配

*** 代数结构定义<<MK298>>

非空集合 $S$ 上存在若干满足[[MK293][基本性质]]的运算，通常记作 $<S,*,\#,...>$

** 特殊元素

*** 幺元<<MK299>>

[[MK298][代数结构]] $<S,*>$ 上存在元素 $e$ 对于任意 $x\in S$ 均满足 $e*x=x*e=x$ 则 $e$ 为幺元

若仅满足 $x*e=x$ 则为左幺元

若仅满足 $e*x=x$ 则为右幺元

**** 性质<<MK300>>

若存在左右幺元，则左幺元等于右幺元，且幺元唯一

***** 证明

若 $e_1,e_2$ 分别为左，右幺元，则有 $e_1=e_1*e_2=e_2$ 故左右幺元相等。

若存在其他幺元 $e_3$ 同理可证 $e_1=e_3$

*** 零元<<MK301>>

[[MK298][代数结构]] $<S,*>$ 上存在元素 $o$ 对于任意 $x\in S$ 均满足 $o*x=x*o=o$ 则 $o$ 为零元

若仅满足 $x*o=o$ 则为左零元

若仅满足 $o*x=o$ 则为右零元

**** 性质

若存在左右零元，则左零元等于右零元，且零元唯一

***** 证明

同[[MK300][之前证明]]

*** 逆元<<MK302>>

[[MK298][代数结构]] $<S,*>$ 上存在[[MK299][幺元]] $e$ ，若 $x*y=e$ 则：

$x$ 是 $y$ 的左逆元

$y$ 是 $x$ 的右逆元

若[[MK292][运算]]满足[[MK296][交换律]]，则称互为逆元

**** 性质1<<MK303>>

若[[MK298][代数结构]] $<S,*>$ 上 $|S|>1$ 且有幺元 $e$ 零元 $o$ ，则零元没有逆元

***** 证明

若 $o=e$ 则对于任意 $a\in S\land a\ne o$ 均有 $a=a*e=a*o=o$ ，与条件矛盾。由于 $|S|>1$ 故必存在 $a\ne o\land a\in S$ 故 $o\ne e$ 。

假设存在左逆元 $x$ ，则有 $o=x*o=e$ 与 $o\ne e$ 矛盾

**** 性质2<<MK304>>

满足[[MK295][结合律]]的[[MK298][代数结构]]中，逆元唯一

***** 证明

若 $x$ 分别有左右逆元 $l,r$ 则 $r=e*r=(l*x)*r=l*(x*r)=l*e=l$

**** 性质3

满足[[MK295][结合律]]的[[MK298][代数结构]]中，逆元的逆元一定是本身

***** 证明

根据定义若满足 $x*y=y*x=e$ 则 $x$ 的逆元是 $y$

则同理对于 $y$ 来说 $x$ 满足 $y*x=x*y=e$ 即 $x$ 是 $y$ 的逆元

且根据[[MK304][性质2]]可得逆元唯一，故 $x$ 的逆元只能是 $y$ 且 $y$ 的逆元只能是 $x$

故 $x$ 逆元的逆元一定是 $x$

*** 可约元素<<MK305>>

[[MK298][代数结构]] $<S,*>$ 中存在 $a\in S$ 满足：

（1） $\forall x\forall y(a*x=a*y\land x\in S\land y\in S\rightarrow x=y)$ 称为左可约

（2） $\forall x\forall y(x*a=y*a\land x\in S\land y\in S\rightarrow x=y)$ 称为左可约

若同时满足（1）和（2），则 $a$ 称为可约

**** 性质1

满足[[MK295][结合律]]的[[MK298][代数结构]]中，有[[MK302][逆元]]的元素[[MK305][可约]]

***** 证明

根据条件有：

（1） $a$ 存在逆元 $-a$ 

（2） $x*a=y*a$

则根据[[MK294][单值性]]有 $x*a=y*a\land -a=-a\rightarrow x*a*-a=y*a*-a$

又因为满足结合律，则有: 

\begin{aligned}
x*a*-a&=y*a*-a\\
x*(a*-a)&=y*(a*-a)\\
x*e&=y*e\\
x&=y\\
\end{aligned}

同理可证左可约，故 $a$ 可约

** 代数结构的关系

*** 同类型定义

两个[[MK298][代数结构]] $<S,*>,<\bar{S},\bar{*}>$ 若满足 $|S|=|\bar{S}|$ 即集合[[MK35][基数]]相等

*** 同态映射<<MK306>>

两个[[MK298][代数结构]] $<S,\Delta,*>,<\bar{S},\bar{\Delta},\bar{*}>$ 若存在[[MK175][函数]] $f:S\rightarrow\bar{S}$ ，对于任意 $\{a,b\}\subset S$ 满足 $h(\Delta a)=\bar{\Delta}h(a)\land h(a*b)=h(a)\bar{ *}h(b)$

则称 $f$ 是 $S$ 到 $S'$ 的同态映射，特别的：

（1） 当 $f$ [[MK176][单射]]时称为单一同态

（2） 当 $f$ [[MK179][满射]]时称为满同态

（3） 当 $f$ [[MK181][双射]]时称为同构映射

*** 同构定义

两个[[MK298][代数结构]] $<S,*>,<\bar{S},\bar{*}>$ 若存[[MK306][同构映射]] $f$ ，则称两个[[MK298][代数结构]]同构。

** 代数结构的类型

*** 环

**** 语言<<MK333>>

除[[~/文档/note/数理逻辑/sllj.org::MK105][固定符号]]外有：

（1） [[~/文档/note/数理逻辑/sllj.org::MK109][函数符号]] $f_\times,f_+$ 分别表示乘法，加法

（3） [[~/文档/note/数理逻辑/sllj.org::MK108][常元符号]] $c_0$

则有 $\mathcal{A}_\mathcal{R}=\{f_\times,f_+,c_0\}$ 进一步有 $\mathcal{L}_{\mathcal{A}_\mathcal{R}}$ 是环理论的[[~/文档/note/数理逻辑/sllj.org::MK151][语言]]

**** 公理<<MK334>>

定义以下公理集合为 $T_\mathcal{R}$

（1） $(\forall x_1(\forall x_2(f_+(x_1,x_2)\hat{=}f_+(x_2,x_1))))$ 加法交换律

（2） $(\forall x_2(\forall x_2(\forall x_3(f_+(f_+(x_1,x_2),x_3)\hat{=}f_+(x_1,f_+(x_2,x_3))))))$ 加法结合律

（3） $(\forall x_1(f_+(x_1,c_0)\hat{=}x_1))$ 加法幺元

（4） $(\forall x_1(f_+(x_1,f_-(x_1))\hat{=}c_0))$ 加法逆元

（5） $(\forall x_2(\forall x_2(\forall x_3(f_\times(f_\times(x_1,x_2),x_3)\hat{=}f_\times(x_1,f_\times(x_2,x_3))))))$ 乘法结合律

（6） $(\forall x_1(\forall x_2(\forall x_3((f_\times(x_1,f_+(x_2,x_3))\hat{=}f_+(f_\times(x_1,x_2),f_\times(x_1,x_3)))))))$ 乘法分配律

**** 性质

***** 性质1<<MK337>>

加法幺元唯一且为 $c_0$ ，即 $T_\mathcal{R}\vdash(\forall x_1((\forall x_2(f_+(x_1,x_2)\hat{=}x_2))\to(x_1\hat{ =}c_0)))$

****** 证明

对于任意 $\mathcal{L}_{\mathcal{A}_\mathcal{R}}$ 的[[~/文档/note/数理逻辑/sllj.org::MK153][结构]] $\mathcal{M}=\left<M,I\right>$ 及其[[~/文档/note/数理逻辑/sllj.org::MK154][赋值]] $v$ 若满足 $\left<\mathcal{M},v\right>\vDash(\forall x_2(f_+(x_1,x_2)\hat{=}x_2))$

则对于其[[~/文档/note/数理逻辑/sllj.org::MK154][赋值]] $v^*$ 满足 $v^*(x_2)=I(c_0),v^*(x_1)=v(x_1)$ 根据[[~/文档/note/数理逻辑/sllj.org::MK158][满足]]有 $\left<\mathcal{M},v^*\right>\vDash(f_+(x_1,x_2)\hat{ =}x_2)$

根据[[~/文档/note/数理逻辑/sllj.org::MK158][满足]] $v^*(x_1)=I(f_+)(v^*(x_1),v^*(x_2))$

根据[[MK334][公理（3）]]有 $\left<\mathcal{M},v^*\right>\vDash(f_+(x_1,x_2)\hat{=}x_1)$ 且 $\left<\mathcal{M},v^*\right>\vDash(x_1\hat{ =}f_+(x_1,x_2))$   

根据[[~/文档/note/数理逻辑/sllj.org::MK158][满足]] $I(f_+)(v^*(x_1),v^*(x_2))=v^*(x_2)=I(c_0)$

即有 $v^*(x_1)\hat{=}I(c_0)$ 根据[[~/文档/note/数理逻辑/sllj.org::MK158][满足]] $\left<\mathcal{M},v^*\right>\vDash(x_1\hat{ =}c_0)$ 又根据 $v^*(x_1)=v(x_1)$ 以及[[~/文档/note/数理逻辑/sllj.org::MK168][局部确定]] $\left<\mathcal{M},v\right>\vDash(x_1\hat{ =}c_0)$

综上所述，对于任意 $\mathcal{L}_{\mathcal{A}_\mathcal{R}}$ 的[[~/文档/note/数理逻辑/sllj.org::MK153][结构]] $\mathcal{M}=\left<M,I\right>$ 及其[[~/文档/note/数理逻辑/sllj.org::MK154][赋值]] $v$ 若 $\left<\mathcal{M},v\right>\vDash(\forall x_2(f_+(x_1,x_2)\hat{=}x_2))$

则 $\left<\mathcal{M},v\right>\vDash(x_1\hat{ =}c_0)$ ，则显然 $\left<\mathcal{M},v\right>\vDash((\forall x_2(f_+(x_1,x_2)\hat{ =}x_2))\to(x_1\hat{ =}c_0))$

又根据 $v$ 的任意性以及[[~/文档/note/数理逻辑/sllj.org::MK158][满足]]有 $\left<\mathcal{M},v\right>\vDash(\forall x_1((\forall x_2(f_+(x_1,x_2)\hat{ =}x_2))\to(x_1\hat{ =}c_0)))$

综上所述，对于任意 $\mathcal{L}_{\mathcal{A}_\mathcal{R}}$ 的[[~/文档/note/数理逻辑/sllj.org::MK153][结构]] $\mathcal{M}=\left<M,I\right>$ 及其[[~/文档/note/数理逻辑/sllj.org::MK154][赋值]] $v$

均有 $\left<\mathcal{M},v\right>\vDash(\forall x_1((\forall x_2(f_+(x_1,x_2)\hat{ =}x_2))\to(x_1\hat{ =}c_0)))$

故根据[[~/文档/note/数理逻辑/sllj.org::MK255][完备性]]有 $T_\mathcal{R}\vdash(\forall x_1((\forall x_2(f_+(x_1,x_2)\hat{=}x_2))\to(x_1\hat{ =}c_0)))$

*** 域

**** 语言<<MK335>>

除[[~/文档/note/数理逻辑/sllj.org::MK105][固定符号]]外有：

（1） [[~/文档/note/数理逻辑/sllj.org::MK109][函数符号]] $f_\times,f_+,f_-$ 分别表示乘法，加法

（3） [[~/文档/note/数理逻辑/sllj.org::MK108][常元符号]] $c_0,c_1$

则有 $\mathcal{A}_\mathbb{F}=\{f_\times,f_+,f_-,c_0,c_1\}$ 进一步有 $\mathcal{L}_{\mathcal{A}_\mathcbb{F}}$ 是环理论的[[~/文档/note/数理逻辑/sllj.org::MK151][语言]]

**** 公理<<MK337>>

显然[[MK335][域语言]]包含[[MK333][环语言]]，即 $\mathcal{A}_\mathcal{R}\subset\mathcal{A}_\mathbb{R}$ 故[[MK334][环公理]] $T_\mathcal{R}$ 显然满足 $T_\mathcal{R}\subset\mathcal{L}_{\mathcal{A}_\mathbb{F}}$

定义域公理集合为 $T_\mathbb{F}$ ，除 $T_\mathcal{R}$ 外包含以下公理

（1） $(\forall x_1(\forall x_2(f_\times(x_1,x_2)\hat{=}f_\times(x_2,x_1))))$ 乘法交换律 

（2） $(\forall x_1(f_\times(x_1,c_1)\hat{=}x_1))$ 乘法幺元

（3） $(\forall x_1((\lnot(x_1\hat{=}c_0))\to(\exists x_2(f_\times(x_1,x_2)\hat{ =}c_1))))$ 乘法逆元

（4） $(\forall x_1(f_\times(x_1,c_0)\hat{=}c_0))$ 乘法零元

（5） $(\lnot(c_0\hat{=}c_1))$

**** 性质

***** 性质1

加法幺元唯一且为 $c_0$ ，即 $T_\mathbb{F}\vdash(\forall x_1((\forall x_2(f_\times(x_1,x_2)\hat{=}x_2))\to(x_1\hat{ =}c_0)))$

乘法幺元唯一且为 $c_1$ ，即 $T_\mathbb{F}\vdash(\forall x_1((\forall x_2(f_\times(x_1,x_2)\hat{=}x_2))\to(x_1\hat{ =}c_0)))$

****** 证明

[[MK337][类似可证]]

*** 代数封闭域

**** 语言

同[[MK333][域语言]] $\mathcal{A}_\mathbb{F}=\{f_\times,f_+,f_-,c_0,c_1\}$ 为区分记作 $\mathcal{A}_{\text{ACF}}$ 即有 $\mathcal{L}_{\mathcal{A}_{\text{ACF}}}$ 是代数封闭域的[[~/文档/note/数理逻辑/sllj.org::MK151][语言]

**** 多项式<<MK336>>

定义：

（1） $\tau^n$ 为[[~/文档/note/数理逻辑/sllj.org::MK117][项]] $f_\times(\tau,f_\times(\tau,f_\times(...f_\times(\tau,\tau)...)))$ 即 $n$ 个 $\tau$ 相乘，其中 $\tau$ 亦为[[~/文档/note/数理逻辑/sllj.org::MK117][项]]

（2） $\sum_{i=a}^{a+b}{\tau_i}$ 为[[~/文档/note/数理逻辑/sllj.org::MK117][项]] $f_+(\tau_a,f_+(\tau_{a+1},f+(...f_+(\tau_{a+(b-1)},\tau_{a+b})...)))$

     即为 $\tau_a$ 到 $\tau_{a+b}$ 的连加，其中 $\tau$ 亦为[[~/文档/note/数理逻辑/sllj.org::MK117][项]]

对于任意 $n\in\mathbb{N}$ 定义 $\phi_n=\sum_{i=1}^{n}f_\times(x_i,x_0^i)$ 为 $n$ 次多项式

**** 公理

定义代数封闭域公理集合为 $T_\text{ACF}$ ，则代数封闭域需要满足所有[[MK337][域公理]] $T_\mathbb{F}\subset T_\text{ACF}$ 外

对于任意[[MK336][ $n$ 次多项式]] $\phi_n$ 均满足 $(\forall x_1(...(\forall x_n((\lnot(x_n\hat{=}c_0))\to(\exists x_0(\phi_n\hat{ =}c_0))))...))\in T_\text{ACF}$

** 代数结构的类型

*** 半群<<MK307>>

对于[[MK298][代数结构]] $<S,*>$ 来说，若：

（1） 满足[[MK295][结合律]]

则称为半群

*** 独异点

对于[[MK298][代数结构]] $<S,*>$ 来说，若：

（1） 满足[[MK295][结合律]]

（2） 存在[[MK299][幺元]]

则称为独异点

*** 群

对于[[MK298][代数结构]] $<S,*>$ 来说，若：

（1） 满足[[MK295][结合律]]

（2） 存在[[MK299][幺元]]

（3） 每个元素存在[[MK302][逆元]]

则称为群（因为结合律故 $|S|>1$ ，又根据[[MK303][性质1]]可知群没有[[MK301][零元]]）

*** 交换群<<MK308>>

对于[[MK298][代数结构]] $<S,*>$ 来说，若：

（1） 满足[[MK295][结合律]]

（2） 存在[[MK299][幺元]]

（3） 每个元素存在[[MK302][逆元]]

（4） 满足[[MK296][交换律]]

则称为交换群（同上没有零元）

*** 环<<MK309>>

对于[[MK298][代数结构]] $<S,+,*>$ 来说，若：

（1） $<S,+>$ 是[[MK308][交换群]]

（2） $<S,*>$ 是[[MK307][半群]]

（3） 运算 $*$ 对 $+$ [[MK297][可分配]]

则称为环

*** 域

对于[[MK298][代数结构]] $<S,+,*>$ 来说，若：

（1） $<S,+,*>$ 是[[MK309][环]]

（2） $<S-\{0\},*>$ 是[[MK308][交换群]]（ $S-\{0\}$ 表示 $S$ 中去掉[[MK301][零元]]）

则称为域

* 电路设计

** DFG（数据流图）

*** 定义<<MK310>>

定义为[[MK206][有向图]] $G=<V,E,f,g>$ 其中

（1） $V$ 为[[MK194][节点]]集合，表示计算/功能模块，是[[MK82][有限集]]

（2） 存在 $S\in V$ 为数据输入节点集合，存在若敢 $F\subset V$ 为数据输出节点集合

（3） $E$ 为有向[[MK196][边]]集合，表示数据流动先后顺序，是[[MK82][有限集]]

（4） $f$ 为节点[[MK201][赋权函数]]，表示关联计算时间

（5） $g$ 为边[[MK201][赋权函数]]，表示该边的延迟（通常由dff类寄存器产生）

     若无延迟设备，则定义为 $f(e)=0,e\in E$

通常表述粒度为：

（1） 细粒度：节点 $v\in V$ 只包含加/乘等基本运算单元

（2） 粗粒度：节点 $v\in V$ 包含复杂的功能模块

*** 函数表示<<MK311>>

[[MK310][DFG]]表示一组功能单元的电路组合，以及单元间连接的延迟

理想情况下，电路会无限工作，即在离散时间 $t\in\mathbb{N}$ 时刻接受 $x_t$ 输出 $y_t$

基于现实 $y_t$ 的值取决于 $x_{t},...,x_{t-n}$ 其中 $n\in\mathbb{N}\cup 0$ 由电路性质决定

且当 $x_t,...,x_{t-n}$ 确定时 $y_t$ 确定，即满足满足[[MK175][函数定义]]

故对于任意[[MK310][DFG]] $G$ 故可将其视为函数 $P_G:\prod_{i=1}^{n} X_G\times\to Y_G$ 其中

（1） $X_G$ 为输入信号所有可能的集合

（2） $Y_G$ 为输出信号所有可能的集合

（3） 此处乘法为[[MK107][笛卡尔积]]

故可有等价函数 $P_G(x_{t},...,x_{t-n})=y_t$

*** 等价<<MK312>>

对于不同的[[MK310][DFG]] $G_1,G_2$ ，定义其[[MK311][函数表示]] $P_{G_1},P_{G_2}$ 满足：

（1） $X_{G_1}=X_{G_2}$

（2） $\exists c\in\mathbb{W},\forall x\in X_{G_1}\rightarrow P_{G_1}(x_{t},...,x_{t-n})=P_{G_1}(x_{t-c},...,x_{t-n-c})$

则称 $G_1,G_2$ 等价

*** 延迟单元<<MK313>>

定义为[[MK310][DFG]] $G=<V,E,f,g>$ 中边赋权大于 $0$ 的边集合

即 $E^*_G=\left\{e\big|e\in E\land g(e)>0\right\}$

*** 路径<<MK314>>

[[MK310][DFG]] $G=<V,E,f,g>$ 中任意两个节点 $\{u,v\}\subset C$ 间的任一[[MK217][有向通道]] $r_{uv}$

若满足单次电平信号在有限时间内可由 $u$ 通过 $r_{uv}$ 传播至 $v$ 则 $r_{uv}$ 是 $G$ 中 $u$ 到 $v$ 的路径

进一步定义 $G$ 中路径集合为 $\mathcal{R}_G$ 实践证明 $\mathcal{R}_G$ 是有限集

*** 时延路径<<MK315>>

[[MK310][DFG]] $G=<V,E,f,g>$ 中的[[MK314][路径]] $r$ 若满足 $i=\sum_{e\in E(r_{uv})}g(e)$

则称 $r$ 是时延为 $i$ 的路径，反之对于 $r$ 其 *路径时延* 为 $i$

定义 $\tau_G(i)=\left\{r\big|r\in\mahtcal{R}_G\land i=\sum_{e\in E(r_{uv})}g(e)\right\}$ 为时延为 $i$ 的路径的集合

*** 路径时间<<MK316>>

[[MK310][DFG]] $G=<V,E,f,g>$ 中任意[[MK314][路径]] $r_{uv}$

其路径时间定义为 $t(r)=\sum_{v\in V(r_{uv})}f(v)+\sum_{e\in E(r_{uv})}g(e)$

其中 $E(r)$ 为[[MK218][取边]]运算， $V(r)$ 为[[MK219][取节点]]运算

*** 关键路径<<MK317>>

对于[[MK310][DFG]] $G=<V,E,f,g>$ 定义 $T_{E'}=\left\{t(r)\big|r\in\tau_G(0)\right\}$

是 $G$ 中零[[MK315][时延路径]]的[[MK316][路径时间]]集合，根据[[MK310][DFG定义]]易证 $T_{E'},\tau_G(0)$ 为有限集

则易证存在 $r\in\tau_G(0)$ 满足 $t_{\infty}(G)=\max(T_{E'})$ 则 $r$ 定义为 $G$ 的关键路径

*** 时钟周期<<MK318>>

即系统工作的时钟周期，系统必须在一个周期内完成[[MK313][延迟单元]]间的电平信号传输

故可得时钟周期 $T_{clk}\leq t_\infty(G)$ 即时钟周期小于等于[[MK317][关键路径]]的[[MK316][路径时间]]

** 迭代边界

*** 定义

定义为[[MK310][DFG]] $G=<V,E,f,g>$ 中的最大[[MK320][环路边界]] $T_\infty=\max\left(\left\{T_{LB}(r)\big|r\in L(G)\land T_{LB}(r)\ne\infty\right\}\right)$

其中 $L(G)$ 为 $G$ 中所有[[MK319][环路]]集合 

**** 迭代

定义为[[MK310][DFG]]中所有节点执行一次的过程

**** 迭代周期

电路系统处理一个输入样点，并输出结果所用的时间，表示为符号 $T_{it}$

**** 时钟周期

电路系统时钟信号提供的工作周期，表示为符号 $T_{\text{clk}}$

电路系统时钟频率为周期的倒数 $f=\frac{1}{T_{\text{clk}}}$

**** 环路<<MK319>>

定义为[[MK310][DFG]] $G=<V,E,f,g>$ 的[[MK225][圈]]，定义 $L(G)$ 为 $G$ 中所有环路集合

**** 环路边界<<MK320>>

定义为[[MK310][DFG]] $G=<V,E,f,g>$ 中的[[MK319][环路]] $r_{uu}$ 的节点的时延 $T_L(r)=\sum_{v\in V(r)}f(v)$

与边的时延 $W_L(r)=\sum_{e\in E(r)}G(e)$ 的比值 $T_{LB}(r)=\frac{T_L(r)}{W_L(r)}$

其中 $E(r)$ 为[[MK218][取边]]运算， $V(r)$ 为[[MK219][取节点]]运算

*** 求解（LPM）

对于[[MK310][DFG]] $G=<V,E,f,g>$ 其[[MK313][延迟单元]]个数为 $n=|E^*_G|$

**** 定义矩阵

对于任意[[MK313][延迟单元]] $e_i=<v_i,u_i>\land e_j=<v_j,u_j>\land\{e_i,e_j\}\subset E^*_G$

则定义 $Z=\left\{t(r_{u_iv_j})\big|r_{u_iv_j}\in\tau_G(m-1)\right\}$ 对于矩阵元素 $l_{ij}^m=\begin{cases}-1&Z=\varnothing\\\max(Z)&|Z|>0\end{cases}$

即从[[MK313][延迟单元]] $e_i$ 到 $e_j$ [[MK316][路径时间]]最长的 $m-1$ [[MK315][时延路径]]，若无通路则取 $-1$

最终定义矩阵 $L^m=\{l_{ij}^m\}$ 其中 $i=$

**** 初始矩阵 & 计算方法<<MK321>>

即矩阵 $L^1=\{l^1_{ij}\}$ 其中 $i\leq n\land j\leq n$

则定义计算 $L^m=L_1*L^{m-1}=\{l^m_{ij}\}$ 定义 $z_{ij}(k)=\begin{cases}-1&l^1_{ik}=-1\lor l^{m-1}_{kj}=-1\\l^1_{ik}+l^{m-1}_{kj}&\text{others}\end{cases}$

则 $l^2_{ij}=\max\left(\left\{z_k\big|1\leq k\leq n\land k\in\mathbb{N}\right\}\right)$
 
**** 矩阵意义<<MK322>>

定义 $e_i=<u_i,v_i>$ 满足 $g(e_i)>0$

则对于 $L^m$ 若对角线上 $l^m_{ii}\ne-1$ 则根据[[MK321][定义]]

可得 $l^m_{ii}$ 是[[MK315][路径时延]]为 $m-1$ 且[[MK316][路径时间]]最长的 $v_i$ 到 $u_i$ 的[[MK314][路径]] $r_{v_iu_i}$

进一步可得 $\frac{l^m_{ii}}{m}$ 即为 $r_{v_iu_i}$ 的[[MK320][环路边界]]

**** 可能环路<<MK323>>

对于[[MK313][延迟单元]] $e_i=<u_i,v_i>$ 来说，若存在单次信号由 $v_i$ 到 $u_i$ 的[[MK314][路径]]

则该路径 $r_{v_iu_i}$ 可能不经过、经过若干或经过所有其他[[MK313][延迟单元]]

即 $r_{v_iu_i}$ 可能经过 $0$ 至 $n-1$ 个除 $e_i$ 外的延迟单元

**** 信号往复（不比往复前大）<<MK324>>

当 $r_{v_iu_i}$ 至多经过 $k-1<n-1$ 个其他[[MK313][延迟单元]]时，则在 $L^{k}$ 之后信号出现往复

假设存在 $m>k$ 使得对于任意 $j\leq k$ 均有 $\frac{l^m_{ii}}{m}>\frac{l^j_{ii}}{j}$

进一步定义 $s\in\mathbb{N}$ 满足 $sk<m\leq(s+1)k\leq n$ 即信号从 $L^{sk+1}$ 开始最新一轮往复

故 $l^m_{ii}$ 时信号往复了 $s$ 轮后继续经过了 $z=m-sk$ 个[[MK313][延迟单元]]

每一轮往复耗时 $l^k_{ii}$ 经过 $k$ 个[[MK313][延迟单元]]，即有 $\frac{l^m_{ii}}{m}=\frac{sl^k_{ii}+l^z_{ii}}{sk+z}$ 定义 $x=\frac{l^z_{ii}}{z}$

定义 $f(x)=\frac{sl^k_{ii}+xz}{sk+z}$ 由于均为正数，显然求导可得递增

当 $x=\frac{l^k_{ii}}{k}$ 时可得 $f(x)=\frac{l^k_{ii}}{k}$ 故当且仅当 $x>\frac{l^k_{ii}}{k}$ 时有 $f(x)>\frac{l^k_{ii}}{k}$

由于 $x=\frac{l^z_{ii}}{z}$ 且 $\frac{l^m_{ii}}{m}>\frac{l^k_{ii}}{k}$ 故有 $x=\frac{l^z_{ii}}{z}>\frac{l^k_{ii}}{k}$

同理定义 $y=\frac{l^k_{ii}}{k}$ 则有 $g(y)=\frac{sky+l^z_{ii}}{sk+z}$ 由于均为正数故 $g(y)$ 递增

与之前类似可证当当且仅当 $y>\frac{l^z_{ii}}{z}$ 时有 $g(y)>\frac{l^z_{ii}}{z}$

结合 $y=\frac{l^k_{ii}}{k}$ 以及 $\frac{l^m_{ii}}{m}>\frac{l^z_{ii}}{z}$ 可得 $y=\frac{l^k_{ii}}{k}>\frac{l^z_{ii}}{z}$ 

总上所述，由于 $\forall j\leq k\rightarrow \frac{l^m_{ii}}{m}>\frac{l^j_{ii}}{j}$ 故有 $\frac{l^k_{ii}}{k}>\frac{l^z_{ii}}{z}\land \frac{l^z_{ii}}{z}>\frac{l^k_{ii}}{k}$ 与[[~/文档/note/离散数学/Disc_Math.org::MK5][三岐性]]矛盾

故假设不成立，则不存在 $m>k$ 满足 $\forall j\leq k\rightarrow \frac{l^m_{ii}}{m}>\frac{l^j_{ii}}{j}$ 

**** 最终取值

根据[[MK324][信号往复]]可得往复后的 $\frac{l^m_{ii}}{m}$ 不可能大于所有往复前的 $\frac{l^m_{ii}}{m}$ 

根据[[MK323][可能环路]]可得最多只能经过 $n-1$ 个[[MK313][延迟单元]]

综上所述，只需计算 $L^1,...,L^n$ 并取 $T_\infty=\max\left(\left\{\frac{l^m_{ii}}{m}\big|1\leq i\leq n\land 1\leq m\leq n\right\}\right)$

** 并行

每个周期输入 $n$ 个数据，复制 $n$ 倍硬件资源同时处理这 $n$ 个数据。

由于硬件资源复制，故[[MK317][关键路径]]一般保持不变

** 流水线

在[[MK316][路径]]中插入寄存器来减少[[MK317][关键路径]]长度，从而降低[[MK318][时钟周期]]

*** 割集<<MK325>>

存在[[MK310][DFG]] $G=<V,E,f,g>$ 一组边 $E'\subset E$

使得 $G'=<V,E-E'>$ 此时 $G'$ 存在不是[[MK244][弱联通]]的子图

则定义 $E'$ 是 $G$ 的割集

*** 前馈割集<<MK326>>

若[[MK310][DFG]] $G=<V,E,f,g>$ 的[[MK325][割集]] $E'$ 将 $G$ 划分为 $2$ 个非[[MK244][弱联通]]的[[MK214][子图]]

定义为 $G_1=<V_1,E_1>,G_2=<V_2,E_2>$ 则定义：

（1） $E_a(i)=\left\{e\big|e=<u,v>\in E'\land (v\in V_i\lor u\in V_i)\land u\not\in S\land v\not\in F\right\}$

（2） $E_b(i)=\left\{e\big|e=<u,v>\in E'\land u\in V_i\land u\not\in S\land v\not\in F\right\}$

（3） $E_c(i)=\left\{e\big|e=<u,v>\in E'\land v\in V_i\land u\not\in S\land v\not\in F\right\}$

其中 $S,F$ 为[[MK310][数据输入/输出]]节点集合，则若满足：

（1） $S\subset V_1\land F\subset V_2$

（2） $E_a(1)=E_b(1)\land E_a(2)=E_c(2)$

则定义 $E'$ 是 $G$ 的前馈割集。

即对于数据输入子图 $V_1$ 来说，所有 $E'$ 中的边均为数据流出方向

对于数据输出子图 $V_2$ 来说，所有 $E'$ 中的边均为数据流入方向

*** 定理

若 $E'$ 是[[MK310][DFG]] $G=<V,E,f,g>$ 的[[MK326][前馈割集]]，则在 $E'$ 上添加统一时钟寄存器

即定义 $g'(e)=\begin{cases}g(e)+1&e\in E'\\g(e)&e\not\in E'\end{cases}$ 以及 $G'=<V,E,f,g'>$

则 $G'$ 与 $G$ [[MK312][等价]]

**** 证明

定义 $G_1=<V_1,E_1>,G_2=<V_2,E_2>$ 其中 $S\subset V_1\land F\subset V_2$

定义 $E'=\{<u_i,v_i>\}$ 则对于任意 $i$ 均有 $u_i\in V_1\land v_i\in V_2$

由于 $G_1,G_2$ 在去除 $E'$ 后非[[MK244][弱联通]]，故可得 $\{v_i\}$ 接受的信号为 $G_2$ 的输入信号集

以及 $G_1$ 的所有信号输出集。则根据[[MK311][函数表示]]定义 $y_t=P_{G_1}(x_{t},...,x_{t-n}),P_{G_2}(y_{t},...,y_{t-m})$

则有 $P_G(x_{t},...,x_{t-n})=P_{G_2}\big(y_t,...,y_{t-m}\big)$

即 $P_G(x_{t},...,x_{t-n})=P_{G_2}\big(P_{G_1}(x_{t},...,x_{t-n}),...,P_{G_1}(x_{t-m},...,x_{t-n-m})\big)$

又由于 $G'$ 在 $E'$ 的所有边上增加 $1$ 延迟

故有 $P_{G'}(x_{t},...,x_{t-n})=P_{G_2}\big(P_{G_1}(x_{t-1},...,x_{t-n-1}),...,P_{G_1}(x_{t-m-1},...,x_{t-n-m-1})\big)$

即：

\begin{aligned}
P_{G'}(x_{t+1},...,x_{t-n+1})=&P_{G_2}\big(P_{G_1}(x_{t},...,x_{t-n}),...,P_{G_1}(x_{t-m},...,x_{t-n-m})\big)\\
=&P_G(x_{t},...,x_{t-n})$
\end{aligned}

故满足[[MK312][等价]]定义

