#+LATEX_CLASS: ctexart
#+OPTIONS: ^:nil
#+TITLE:

current mark: MK5

* 椭圆

** 定义

平面内到达两个焦点 $F_1(x_1,y_1),F_2(x_2,y_2)$ 的距离为常数 $2a$ 且 $2a>|F_1F_2|$ 的点集

即 $\left\{(x,y)\big|\sqrt{(x-x_1)^2+(y-y_1)}+\sqrt{(x-x_2)^2+(y-y_2)}=2a>\sqrt{(x_1-x_2)^2+(y_1-y_2)}\right\}$

** 点线距离公式

定义直线 $l:Ax+By+C=0$ 以及点 $M(x_0,y_0)$ ，则点到直线的距离为 $\frac{|Ax_0+ By_0+C|}{\sqrt{A^2+B^2}}$

*** 证明

定义直线 $l:Ax+By+C=0$ 以及点 $M(x_0,y_0)$ 故有过 $M$ 点垂直于直线 $l$ 的直线函数为 $l':Bx-Ay-Bx_0+Ay_0=0$

将直线 $l$ 的函数乘以 $\frac{A}{B}$ 加上 $l'$ 可得

\begin{aligned}
0&=\frac{A^2}{B}x+Ay+\frac{AC}{B}+Bx-Ay-Bx_0+Ay_0\\
\frac{A^2+B^2}{B}x&=Bx_0-Ay_0-\frac{AC}{B}\\
(A^2+B^2)x&=B^2x-ABy_0-AC\\
x&=\frac{B^2x-ABy_0-AC}{A^2+B^2}
\end{aligned}

同理可证 $y=\frac{A^2y_0-ABx_0-BC}{A^2+B^2}$ 故距离为

\begin{aligned}
\sqrt{(x-x_0)^2+(y-y_0)^2}&=\sqrt{\left(\frac{B^2x-ABy_0-AC}{A^2+B^2}-x_0\right)^2+\left(\frac{A^2y_0-ABx_0-BC}{A^2+B^2}-y_0\right)^2}\\
&=\sqrt{\left(\frac{B^2x-ABy_0-AC-A^2x_0-B^2x_0}{A^2+B^2}\right)^2+\left(\frac{A^2y_0-ABx_0-BC-A^2y_0-B^2y_0}{A^2+B^2}\right)^2}\\
&=\sqrt{\left(\frac{ A^2x_0+ ABy_0+AC}{A^2+B^2}\right)^2+\left(\frac{B^2y_0+ABx_0+BC}{A^2+B^2}\right)^2}\\
&=\sqrt{\frac{A^2(Ax_0+ By_0+C)^2+B^2(Ax_0+ By_0+C)^2}{(A^2+B^2)^2}}\\
&=\sqrt{\frac{(Ax_0+ By_0+C)^2}{A^2+B^2}}\\
&=\frac{|Ax_0+ By_0+C|}{\sqrt{A^2+B^2}}\\
\end{aligned}

** 函数形式

*** 基本形式

$\frac{x^2}{a^2}+\frac{y^2}{b^2}=1,(a>b>0)$ 其焦点为 $(\pm c,0),c=\sqrt{a^2-b^2}$ 准线为 $x$ 轴 

**** 证明满足定义

根据上式有 $y^2=b^2-\frac{b^2}{a^2}x^2$ 故点到焦点 $(c,0)$ 的距离为

\begin{aligned}
&\sqrt{(x-c)^2+y^2}\\
=&\sqrt{(x-\sqrt{a^2-b^2})^2+b^2-\frac{b^2}{a^2}x^2}\\
=&\sqrt{x^2-2\sqrt{a^2-b^2}x+a^2-b^2+b^2-\frac{b^2}{a^2}x^2}\\
=&\sqrt{x^2-2\sqrt{a^2-b^2}x+a^2-b^2+b^2-\frac{b^2}{a^2}x^2}\\
=&\sqrt{\frac{a^2-b^2}{a^2}x^2-2\sqrt{a^2-b^2}x+a^2}\\
=&\sqrt{\left(\frac{\sqrt{a^2-b^2}}{a}x-a\right)^2}\\
=&\left|\frac{\sqrt{a^2-b^2}}{a}x-a\right|
\end{aligned}

由于 $\frac{x^2}{a^2}+\frac{y^2}{b^2}=1,\frac{y^2}{b^2}\geq0$ 故有 $\frac{x^2}{a^2}<1$ 且 $a>0$ 故有 $|x|<a\Rightarrow -a\leq x\leq a$

由于 $\sqrt{a^2-b^2}<a\Rightarrow \frac{\sqrt{a^2-b^2}}{a}<1\Rightarrow \frac{\sqrt{a^2-b^2}}{a}x<q$ 故有 $\left|\frac{\sqrt{a^2-b^2}}{a}x-a\right|=a-\frac{\sqrt{a^2-b^2}}{a}x$

同理可证到另一个焦点 $(-c,0)$ 的距离 $\sqrt{(x+c)^2+y^2}=a+\frac{\sqrt{a^2-b^2}}{a}x$

综上所述，满足函数的点到两焦点距离和为 $2a$
 
* 简谐运动

** <<MK2>>定义

运动离开平衡位置的位移 $x$ 随时间 $t$ 的变化是正弦或者余弦函数的运动，即 $x=A\cos(\omega t+\phi)$

其中 $A>0$ 为振幅， $\omega$ 为角频率

周期 $T=\frac{2\pi}{\omega}$

频率 $\nu=\frac{1}{T}=\frac{\omega}{2\pi}$

相位 $\omega t+\phi$

初相位 $\phi$

** 简谐运动的速度与加速度

速度 $v=\frac{dx}{dt}=A\omega\sin(\omega t+ \phi)$

加速度 $a=\frac{dv}{dt}=-A\omega^2\cos(\omega t+ \phi)$

** 简谐运动的初始条件

振幅 $A$ 和初相位 $\phi$ 由初始条件决定，当简谐运动的初始位置为 $x_0$ ，初始速度为 $v_0$ 则连列：

\begin{cases}
&x_0=A\cos(\phi)\\
&v_0=-\omega A\sin(\phi)\Rightarrow A\sin(\phi)=\frac{v_0}{\omega}
\end{cases}

解方程组，两式平方相加

\begin{aligned}
&(A\cos(\phi))^2+(A\sin(\phi))^2=x_0^2+\frac{v_0^2}{\omega^2}\\
\therefore &A=\sqrt{x_0^2+\frac{v_0^2}{\omega^2}}
\end{aligned}

另两式相除得

\begin{aligned}
&\frac{v_0}{x_0}=-\omega \frac{\sin(\phi)}{\cos(\phi)}\\
&\tan(\phi)=-\frac{v_0}{\omega x_0}\\
&\phi=\arctan(-\frac{v_0}{\omega x_0})
\end{aligned}

** 旋转矢量表示法

*** 图像描述

向量 $\vec{A}$ 为平面坐标系上从 点 $(0,0)$ 开始，长度为振幅 $A$ 有向线段。

$\vec{A}$ 与 $x$ 夹角为 $\omega t+\phi$ 于 $x$ 轴投影为 $x=A\cos(\omega t+\phi)$

** <<MK5>>相图

*** 相平面

以坐标和速度定义坐标轴

*** 相点

系统一个运动状态对应相平面上的一点，称为相点

*** 相图

相点运动的轨迹称为相图

** <<MK1>>线性恢复力

定义 $F=-kx$ 其中

（1） $F$ 为物体受到沿位移方向的力的大小

（2） $x$ 为物体离开平衡位置的位移

（3） $k>0$ 为常系数

** <<MK4>>简谐运动动力学方程

根据[[~/文档/note/大学物理/Note/Note1.org][质点运动-一般运动-牛顿三定律-动量定律]]以及[[MK1][线性恢复力]]可得 $F=ma\Rightarrow m\frac{d^2x}{dt^2}=-kx$

整理上式得 $\frac{d^2x}{dt^2}+\frac{k}{m}x=0$ 定义 $\omega^2=\frac{k}{m}$ 则有 $\frac{d^2x}{dt^2}+\omega^2x=0$ 此为 *简谐运动的动力学方程*

上式为二阶常系数齐次微分方程，根据[[~/文档/note/大学物理/Note/DiffEq.org][二阶微分方程-二阶线性齐次方程-二阶常系数齐次微分方程]]

可得该方程特征方程为 $r^2+\omega^2=0$ 拥有共轭复根，且 $p=0,\frac{\sqrt{-(p^2-4q)}}{2}=\frac{\sqrt{4\omega^2}}{2}=\omega$

故有 $x=C_3 \cos(\omega t)+iC_4\sin(\omega t)$ 由于 $C_3,C_4$ 为任意常数，定义 $C_3=A\cos(\phi),C_4=iA\sin(\phi)$

故有 $x=A\left[\cos(\omega t)\cos(\phi)-\sin(\omega t)\sin(\phi)\right]=A\cos(\omega t+\phi)$ 该形式与简写运动[[MK2][定义]]一致

** 单摆

*** 定义

长度为 $L$ 质量为 $0$ 的线上端固定，下端链接质量为 $m$ 的质点，拉直线提高倾斜角 $\theta$ 后放开。

质点以 $L$ 为半径在重力作用下做左右来回圆周摆动。

*** <<MK3>>动力学方程1

由于向心力不做功，故不对线速度大小有影响。

定义线与垂直方向的夹角随时间变化函数为 $\theta(t)$ （弧度）则有角速度为 $\frac{d\theta(t)}{dt}$ 角加速度为 $\frac{d^2\theta(t)}{dt^2}$

角加速度与线加速度转换为 $a(t)=L\frac{d^2\theta(t)}{dt^2}$ 

另一方面根据力的分解可得运动方向受力为 $-mg\sin(\theta)$

带入得单摆动力学方程 $-mg\sin(\theta)=mL\frac{d^2\theta(t)}{dt^2}\Rightarrow \frac{d^2\theta(t)}{dt^2}+\frac{g}{L}\sin(\theta)=0$

*** 动力学方程2

定义 $x$ 为质点偏离中心的水平位置，则需要计算水平方向受力 $F=-mg\frac{x(t)}{L}\frac{\sqrt{L^2-(x(t))^2}}{L}$

同理推导动力学方程 $-mg\frac{x(t)\sqrt{L^2-(x(t))^2}}{L^2}=m\frac{d^2x(t)}{dt^2}\Rightarrow\frac{d^2x(t)}{dt^2}+g\frac{x(t)\sqrt{L^2-(x(t))^2}}{L^2}=0$

*** 动力学方程近似

由于 $\lim_{\theta\to0}\frac{\sin(\theta)}{\theta}=1$ 即当 $\theta\to0$ 时 $\theta\sim\sin(\theta)$

故[[MK3][动力学方程1]]可简化为 $\frac{d^2\theta(t)}{dt^2}+\frac{g}{L}\theta=0$ 近似视为简谐运动

** 简谐运动能量

*** 动能

简谐运动动能为 $E_k=\frac{1}{2}m(v(t))^2$ 其中 $v(t)=\frac{dx(t)}{dt}=A\omega\sin(\omega t+\phi)$

带入得 $E_k=\frac{1}{2}mA^2\omega^2\sin^2(\omega t+\phi)$ 其中又根据[[MK4][动力学方程]]有 $\omega^2=\frac{k}{m}$

带入得 $E_k=\frac{1}{2}kA^2\sin^2(\ometa t+\phi)$

*** 势能

势能可看做位移返回平衡位置时[[MK1][线性恢复力]]做的功，故当距离为 $x$ 时积分 $E_s=\int_x^0ktdt=\frac{1}{2}kx^2$ 为线性恢复力做的功

带入 $x=A\cos(\omega t+\phi)$ 得 $E_s=\frac{1}{2}kA^2\cos^2(\omega t+\phi)$

*** 简谐运动能量守恒

根据上述分析，简谐运动动能势能和为 $E_k+E_s=\frac{1}{2}kA^2\sin^2(\ometa t+\phi)+\frac{1}{2}kA^2\cos^2(\omega t+\phi)=\frac{1}{2}kA^2=\frac{1}{2}m\omega^2A^2$

与时间，位移等变量无关，故能量守恒

* 简写运动合成

** 同方向

*** 同方向同频率简谐运动合成

**** 基本定义

定义两个简谐运动 $x_1=A_1\cos(\omega t+\phi_1),x_2=A_2\cos(\omega t+\phi_2)$ 期合成为以为 $x=x_1+x_2$

**** 证明合成后为简谐运动

当 $t=0$ 时 $x=A_1\cos(\phi_1)+A_2\cos(\phi_2)$ 接下来利用[[MK5][相图]]求距离和 $x$ 的值 

做向量 $\vec{A}_1=(A_1\sin(\phi_1),A_1\cos(\phi_1)),\vec{A}_2=(A_2\sin(\phi_2),A_2\cos(\phi_2))$ 

则 $\vec{A}_1$ 长度为 $A_1$ 与 $x$ 轴夹角为 $\phi_1$ 同样 $\vec{A}_2$ 长度为 $A_2$ 与 $x$ 轴夹角为 $\phi_2$ 

则 $\vec{A}_1,\vec{A}_2$ 在 $x$ 轴投影和为 $\vec{A}_1,\vec{A}_2$ 组成的平行四边形对角线在 $x$ 轴的投影，即 $\vec{A}=\vec{A}_1+\vec{A}_2$

当 $t>0$ 时 $\vec{A}_1$ 与 $x$ 轴夹角为 $\omega t+\phi_1$ ， $\vec{A}_2$ 为 $\omega t+\phi_2$ 故两向量夹角不变

故平行四边形形状不变，只是绕原点转动。

定义对角线向量为 $\vec{A}$ 其转动的频率与 $x_1,x_2$ 相同为 $\omega$ ；长度固定不变定义为 $A$ 角相位同样为 $\omega t+\phi$

其中 $\phi$ 为合成简谐运动的初相位，故有 $x=A\cos(\omega t+\phi)$ 合成后亦为简谐运动

**** 求解初相位即振幅

振幅即 $\vec{A}$ 的长度，平行四边形内角和为 $2\pi$ 故 $\vec{A}$ 对应的内角为 $\pi-(\phi_2-\phi_1)$ 此处定义 $\phi_2>\phi_1$

故根据余弦定理 $A=\sqrt{A_1^2+A_2^2-2\cos(\pi-(\phi_2-\phi_1))}=\sqrt{A_1^2+A_2^2+2\cos(\phi_2-\phi_1)}$

初相位在 $x,y$ 轴的投影长度分别为 $\vec{A}_1,\vec{A}_2$ 在对应坐标轴投影长度和

故其正切 $\tan(\phi)=\frac{A_1\sin(\phi_1)+A_2\sin(\phi_2)}{A_1\cos(\phi_1)+A_2\cos(\phi_2)}$ 故得初相位 $\phi=\arctan\left(\frac{A_1\sin(\phi_1)+A_2\sin(\phi_2)}{A_1\cos(\phi_1)+A_2\cos(\phi_2)}\right)$

**** 多个同频率简谐运动叠加

根据上述证明同理，结果任然为简谐运动。利用[[MK5][相图]]可得 $\vec{A}=\sum_{i=1}^n\vec{A}_i$ 即为

*** 同方向不同频率简写运动合成（拍）

若 $A_1=A_2=A,\phi_1=\phi_2=0$ 则两个简谐运动 $x_1=A\cos(\omega_1 t),x_2=A\cos(\omega_2 t)$ 的合成为 

$x=x_1+x_2=A\left(\cos(\omega_1 t)+\cos(\omega_2 t)\right)=2A\cos\left(\frac{\omega_1-\omega_2}{2}t\right)\cos\left(\frac{\omega_1+\omega_2}{2}t\right)$

为方便，接下来作如下定义 $\omega_1=2\pi v_1,\omega_2=2\pi v_2$ 则有合成后 $x=2A\cos\left(\frac{v_1-v_2}{2}2\pi t\right)\cos\left(\frac{v_1+v_2}{2}2\pi t\right)$

定义 $2A\cos\left(\frac{v_1-v_2}{2}2\pi t\right)$ 部分为振幅 $\cos\left(\frac{v_1+v_2}{2}2\pi t\right)$ 为震动项，合成后 *不是简谐运动*

**** 拍

由于振幅随时间变化，即振幅 $A'=\left|2A\cos\left(\frac{v_1-v_2}{2}2\pi t\right)\right|$ 故形成拍。

拍的形成跟振幅的绝对值有关，正负只改变其振动方向，故 $0\leq A'\leq 2A$

**** 拍的周期

由于 $A'=\left|2A\cos\left(\frac{v_1-v_2}{2}2\pi t\right)\right|=\left|2A\cos\left(\frac{v_1-v_2}{2}2\pi t \pm \pi\right)\right|=\left|2A\cos\left(\frac{v_1-v_2}{2}2\pi\left(t\pm\frac{1}{v_1-v_2}\right}\right)\right|$

故推出 $\left|2A\cos\left(\frac{v_1-v_2}{2}2\pi t\right)\right|=\left|2A\cos\left(\frac{v_1-v_2}{2}2\pi\left(t+\frac{1}{|v_1-v_2|}\right}\right)\right|$ 则周期为 $\frac{1}{|v_1-v_2|}$ （周期不为负）

**** 拍的形成条件

拍的震动周期为 $\frac{1}{|v_1-v_2|}$ 震动项的周期为 $\frac{2}{v_1+v_2}$ 由于拍的形成条件是在振幅变化的周期内震动多次发生。

故必须要 $\frac{1}{|v_1-v_2|}>>\frac{2}{v_1+v_2}$ 化简得 $2|v_1-v_2|<<v_1+v_2$ 亦可表示为 $|v_1-v_2|<<v_1+v_2$

** 垂直


