#+LATEX_CLASS: ctexart

#+TITLE: 实变函数

current video: P22

current mark: 94

* 集合列

** 定义

定义[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-集合族]] $\{A_i\}_{i\in\mathbb{N}}$ 其中[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-集合族-标志集]]是正整数

** 集合列上下确界

定义[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-集合族]] $\{A_i\}_{i\in\mathbb{N}}$

根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-集合族-集合族运算]]

其上确界定义为 $\cup_{i\in\mathbb{N}}A_i$

其下确界定义为 $\cap_{i\in\mathbb{N}}A_i$

** 集合列上下极限<<MK1>>

定义[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-集合族]] $\{A_i\}_{i\in\mathbb{N}}$ ，则根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-集合族-集合族运算]]

其上极限定义为 $\overline{\lim_{n\to\infty}}A_n=\cap_{i\geq 1}\left(\cup_{k\geq i}A_k\right)$ 即 $\overline{\lim_{n\to\infty}}A_n=\left\{a\big|\forall i\in\mathbb{N},\exists k\geq i\rightarrow a\in A_k\right\}$

其下极限定义为 $\underline{\lim_{n\to\infty}}A_n=\cup_{i\geq 1}\left(\cap_{k\geq i}A_k\right)$ 即 $\underline{\lim_{n\to\infty}}A_n=\left\{a\big|\exists i\in\mathbb{N},\forall k\geq i\rightarrow a\in A_k\right\}$

注：此处可取无限

*** 推论<<MK3>>

$\underline{\lim_{n\to\infty}}A_n\subset\overline{\lim_{n\to\infty}}A_n$

**** 证明

根据定义 $\underline{\lim_{n\to\infty}}A_n=\cup_{i\geq 1}\left(\cap_{k\geq i}A_k\right)$ 故对于任意 $a\in\underline{\lim_{n\to\infty}}A_n$ 有 $a\in\cup_{i\geq 1}\left(\cap_{k\geq i}A_k\right)$ 

即 $\exists i\rightarrow \left(\forall k>i\rightarrow a\in A_k\right)$ 则 $\forall i'\in\mathbb{N}$ 定义并集 $\cup_{k\geq i'}A_k$ 取 $l=\max\{i,i'\}$ 则有 $a\in A_l\land A_l\subset\cup_{k>i'}A_k$

故 $\forall i'\in\mathbb{N}\rightarrow a\in\cup_{k\geq i'}A_k$ 进一步 $a\in\cap_{i\geq 1}\left(\cup_{k\geq i}A_k\right)$ 根据定义 $a\in\overline{\lim_{n\to\infty}}A_n$

根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的关系-包含]]可得 $\underline{\lim_{n\to\infty}}A_n\subset\overline{\lim_{n\to\infty}}A_n$ 

** 单调集列<<MK69>>

定义[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-集合族]] $\{A_i\}_{i\in\mathbb{N}}$ 定义

递增集列满足 $\forall i\in\mathbb{N}\rightarrow A_i\subset A_{i+1}$

递减集列满足 $\forall i\in\mathbb{N}\rightarrow A_{i+1}\subset A_i$

*** 定理<<MK70>>

单调集列有[[MK2][极限]]，且对于递增 $\lim_{n\to\infty}A_n=\cup_{i=1}^\infty A_i$ 对于递减 $\lim_{n\to\infty}A_n=\cap_{i=1}^\infty A_i$ 

**** 证明

***** 极限存在

根据集合列极限定义需要证明 $\cup_{i\geq 1}\left(\cap_{k\geq i}A_k\right)=\cap_{i\geq 1}\left(\cup_{k\geq i}A_k\right)$ 

且根据[[MK3][推论]]有 $\cup_{i\geq 1}\left(\cap_{k\geq i}A_k\right)\subset\cap_{i\geq 1}\left(\cup_{k\geq i}A_k\right)$ 故若能证明 $\cap_{i\geq 1}\left(\cup_{k\geq i}A_k\right)\subset\cup_{i\geq 1}\left(\cap_{k\geq i}A_k\right)$ 

则根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的关系-包含-定理1]]可得 $\cup_{i\geq 1}\left(\cap_{k\geq i}A_k\right)=\cap_{i\geq 1}\left(\cup_{k\geq i}A_k\right)$ 

****** 递增集列

若 $a\in\cap_{i\geq 1}\left(\cup_{k\geq i}A_k\right)$ 则 $\forall i\in\mathbb{N}\rightarrow\left(\exists k_i\geq i\rightarrow a\in A_k\right)$ 

特殊地取 $i=1$ 则有 $k_1\geq 1$ 使得 $a\in A_{k_1}$ 根据递增定义有 $\forall k\geq k_1\rightarrow A_{k_1}\subset A_k\rightarrow a\in A_k$ 即 $a\in \cap_{k\geq k_1}A_k$

则有 $a\in\cup_{i\geq 1}\left(\cap_{k\geq i}A_k\right)$ ，根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的关系-包含]]可得 $\cap_{i\geq 1}\left(\cup_{k\geq i}A_k\right)\subset\cup_{i\geq 1}\left(\cap_{k\geq i}A_k\right)$ 

****** 递减集列

取任意 $a\in\cap_{i\geq 1}\left(\cup_{k\geq i}A_k\right)$ ，假设 $\forall z\in\mathbb{N}\rightarrow a\not\in\cap_{k\geq z}A_k$ 则对于任意给定 $z$ 必有 $u\in\mathbb{N}$ 使得 $a\not\in A_u$

由于 $a\in\cap_{i\geq 1}\left(\cup_{k\geq i}A_k\right)$ 则 $\forall i\in\mathbb{N}\rightarrow\left(\exists k_i\geq i\rightarrow a\in A_k\right)$ 即存在 $k_u$ 使得 $a\in A_{k_u}$

根据递减定义可得 $\forall v\leq k_u\rightarrow A_{k_u}\subset A_v$ 显然 $u\leq k_u$ 故有 $a\in A_{k_u}\subset A_u$ 即 $a\in A_u$ 矛盾

故命题错误，则 $\exists z\in\mathbb{N}\rightarrow a\in\cap_{k\geq z}A_k$ 即 $a\in\cup_{i\geq 1}\left(\cap_{k\geq i}A_k\right)$ 

根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的关系-包含]]可得 $\cap_{i\geq 1}\left(\cup_{k\geq i}A_k\right)\subset\cup_{i\geq 1}\left(\cap_{k\geq i}A_k\right)$ 

***** 等式

****** 递增集列

已证极限存在，则上下极限相等，故 $\lim_{n\to\infty}A_n=\underline{\lim_{n\to\infty}}A_n=\cup_{i\geq 1}\left(\cap_{k\geq i}A_k\right)$

根据递增性质可得 $\cap_{k\geq i}A_k=A_i$ 故有 $\lim_{n\to\infty}A_n=\cup_{i\geq 1}A_i$

****** 递减集列

已证极限存在，则上下极限相等，故 $\lim_{n\to\infty}A_n=\underline{\lim_{n\to\infty}}A_n=\cap_{i\geq 1}\left(\cup_{k\geq i}A_k\right)$

根据递减性质可得 $\cup_{k\geq i}A_k=A_i$ 故有 $\lim_{n\to\infty}A_n=\cap_{i\geq 1}A_i$

** 集合列极限<<MK2>>

定义[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-集合族]] $\{A_i\}_{i\in\mathbb{N}}$ ，若[[MK1][上下极限]]相等，即 $\overline{\lim_{n\to\infty}}A_n=\underline{\lim_{n\to\infty}}A_n$

则称集合列有极限，且极限等于上下极限，记作 $\lim_{n\to\infty}A_n$

* 实数定义

** 实数公理

若 $\mathbb{R}$ 是一个集合，若他满足以下三组公里，则成为实数系，其元素成为实数

*** 域公理<<MK4>>

对于任意 $\{a,b\}\subset\mathbb{R}$ 有二元[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-代数的构建-运算]] $a+b$ 与 $a\cdot b$ 定义为加法，乘法，满足：

（0） 封闭性： $\forall a\in\mathbb{R}\forall b\in\mathbb{R}\left(a+b\in\mathbb{R}\land a\cdot b\in\mathbb{R}\right)$

（1） 交换律： $\forall a\in\mathbb{R}\forall b\in\mathbb{R}\left(a+b=b+a\land a\cdot b=b\cdot a\right)$

（2） 结合律： $\forall a\in\mathbb{R}\forall b\in\mathbb{R}\forall c\in\mathbb{R}\left((a+b)+c=a+(b+c)\land (a\cdot b)\cdot c=a\cdot (b\cdot c)\right)$

（3） 分配率： $\forall a\in\mathbb{R}\forall b\in\mathbb{R}\forall c\in\mathbb{R}\left((a+b)\cdot c=a\cdot c+b\cdot c\right)$

（4） 存在加乘法[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-特殊元素-幺元]]： $\exists 0\in\mathbb{R}\forall a\in\mathbb{R}\left(0+a=a\right)\land\exists1\in\mathbb{R}\forall a\in\mathbb{R}\left(1\cdot a=a\right)$

（5） 存在加成法[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-特殊元素-逆元]]： $\forall a\in\mathbb{R}\exists -a\in\mathbb{R}\left(-a+a=0\right)\land\forall a\in\mathbb{R}\exists a^{-1}\in\mathbb{R}\left(a^{-1}\cdot a=1\right)$

**** 不可数加法<<MK53>>

定义集合 $I$ 则 $\sum_{i\in I}x_i=\sup\left\{\sum_{i\in F}x_i\big|F\subset I\land |F|<\infty\right\}$ 即定义 $F$ 是 $I$ 的可数子集

则无穷加法的定义为所有满足 $F$ 的加和的上确界

**** 推论1<<MK21>>

整数是实数的子集

***** 证明

根据（4）以及（0）可得 $\{0,1\}\in\mathbb{R}$ 则任意 $n\in\mathbb{N}$ 均可表述为 $n=1+1+....+1\in\mathbb{R}$

且根据（5）可知加法逆元 $-n\in\mathbb{R}$

**** 推论2<<MK10>>

有理数是实数的子集

***** 证明

根据推论1可得 $\forall n\in\mathbb{N}\rightarrow n\in\mathbb{R}$ 根据（5）乘法逆元可得 $\frac{1}{n}n=1$ 则有 $\frac{1}{n}\in\mathbb{R}$

进一步根据乘法封闭可得 $\forall m\in\mathbb{N}$ 亦有 $m\frac{1}{n}=\frac{m}{n}\in\mathbb{R}$

**** 加法幺元的逆元是其本身

即 $-0=0$ 因为 $0+0=0$ 且根据[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-特殊元素-逆元-性质2]]可得逆元唯一

**** 减法定义<<MK6>>

根据[[MK4][域公理]]中加法和逆元可定义减法为 $a-b=a+(-b)$

**** 零元<<MK16>>

加法幺元 $0$ 是乘法[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-特殊元素-零元]]

***** 证明

定义 $\foral a\in\mathbb{R}$ 由加法零元定义可得 $0=0+0$ 则有 $a\cdot 0=a\cdot (0+0)=a\cdot 0+a\cdot 0$

由于乘法封闭，故 $a\cdot 0\in U$ ，根据定义有逆元 $-a\cdot 0$ 满足 $a\cdot 0+(-a\cdot 0)=0$

则有 $a\cdot 0+(-a\cdot 0)=a\cdot 0+a\cdot 0+(-a\cdot 0)\rightarrow 0=a\cdot 0$ 

同理可证 $0\cdot a=0$ 综上所述 $0$ 是零因子 

**** 逆元等价<<MK17>>

若 $a\ne0$ 则有 $(-1)\cdot a=-a$ 即 $a$ 的加法逆元等于 $a$ 与 $1$ 的逆元的乘法

***** 证明 

由于 $1$ 是乘法幺元，故有 $1\cdot a=a\cdot 1=a$ 且 $1$ 有加法逆元，记作 $-1$

根据分配率 $(1+(-1))\cdot a=0\cdot a=a+(-1)a$ 根据[[MK16][零元]]可得 $0\cdot a=0$

故有 $a+(-1)\cdot a=0$ 即 $(-1)\cdot a$ 是逆元

根据[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-特殊元素-逆元-性质2]]可得逆元唯一，故有 $(-1)\cdot a=a$

**** 相等充要条件<<MK8>>

若 $\{a,b\}\subset\mathbb{R}$ 则 $a=b$ 的充要条件是 $a-b=0$

***** 证明

****** 充分

若 $a=b$ 则根据[[MK6][减法]] $a-b=a+(-b)=a+(-a)$ 即 $a$ 与其逆元相加，则根据逆元定义 $a-b=0$

****** 必要

若 $a-b=0$ 则根据[[MK6][减法]]可得 $a+(-b)=0$

则 $(-b)$ 是 $a$ 的[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-特殊元素-逆元]]，且有 $-b$ 亦定义为 $b$ 的逆元

由于加法满足结合律，故根据[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-特殊元素-逆元-性质3]]可得 $a,b$ 逆元的逆元均为 $a,b$ 本身 

由于 $a,b$ 的逆元均为 $-b$ 根据[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-特殊元素-逆元-性质2]]可得 $-b$ 的逆元唯一，故有 $a=b$

**** 相等是等价关系<<MK11>>

根据法[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-特殊关系-等价关系]]若 $\{a,b\}\subset\mathbb{R}$ 则 $a=b$ 满足自反性，对称性以及传递性

***** 证明

****** 自反性

显然 $a\in\mathbb{R}$ 是集合中的元素，则 $a=a$

****** 对称性

若 $a=b$ 则根据[[MK4][域公理]]（5） $a$ 的逆元 $-a\in\mathbb{R}$ 则根据域公理交换律 $b-a=-a+b=-a+a=a-a=0$ 

则根据[[MK8][相等充要条件]] $b-a=0$ 则 $b=a$ 

****** 传递性

若 $a=b\land b=c$ 则有等价条件 $a-b=0\land b-c=0$

由于加法是[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-代数的构建-运算]]故满足单值性，则有 $a-b+b-c=0+0$

根据域公理结合律，分配率可得 $a-b+b-c=a-c=0+0=0$ 即 $a-c=0$

则根据[[MK8][相等充要条件]] $a=c$

**** 除法定义<<MK9>>

根据[[MK4][域公理]]中乘法和乘法逆元，定义除法为 $a\div b=a\cdot\frac{1}{b}$

**** 整数幂定义<<MK20>>

若 $a\in\mathbb{R},b\in\mathbb{N}^+$ 则定义 $a^b=a\cdot...\cdot a$ 即 $b$ 个 $a$ 相乘，若 $a^0=1\land a^1=a$

*** 序公理<<MK5>>

对于任意 $\{a,b,c\}\subset\mathbb{R}$ 存在[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-二元关系]] $>$ 满足：

1. 三歧性： $a>b, b>a, a=b$ 上述三个条件有且仅有一个成立

2. 传递性： $a>b\land b>c\rightarrow a>c$

3. 运算相容： $a>b\rightarrow a+c>b+c$ 以及 $a>b\land c>0\rightarrow a\cdot c>b\cdot c$

**** 大于等于关系<<MK14>>

定义[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-二元关系]] $\geq$ 为 $a\geq b{|\!\!\!=\!\!\!|}a>b\lor a=b$

则对于任意 $\{a,b,c\}\subset\mathbb{R}$ 满足：

1. 反对称： $a\geq b\land b\geq a\rightarrow a=b$

2. 传递性： $a\geq b\land b\geq c\rightarrow a\geq c$

3. 运算相容： $a\geq b\rightarrow a+c\geq b+c$ 以及 $a>b\land c\geq 0\rightarrow a\cdot c\geq b\cdot c$

***** 证明

****** 反称性

根据定义展开 $a\geq b\land b\geq a$ 等价于 $(a>b\lor a=b)\land(b>a\lor b=a)$ 

根据[[MK5][三歧性]]可得，当且仅当 $a=b$ 时同时满足 $a\geq b\land b\geq a$

****** 传递性

根据定义 $a\geq b\land b\geq c$ 等价于 $(a>b\lor a=b)\land(b>c\lor b=c)$ 则若

（1） $a>b\land b>c$ 则根据传递性有 $a>c\rightarrow a>c\lor a=c$ 即 $a\geq c$

（2） $a=b\land b=c$ 则根据[[MK11][传递性]] $a=c$ 同理即 $a\geq c$

（3） $a>b\land b=c$ 或 $a=b\land b>c$ 则有 $a>c$ 即 $a\geq c$

即证得传递性

****** 运算相容

仅证加法相容，乘法同理。若 $a\geq b$ 则等价于 $a>b\lor a=b$ 故：

（1） $a=b$ 根据[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-代数的构建-运算]]单值性有 $a+c=b+c$

（2） $a>b$ 根据序公理计算相容可得 $a+c>b+c$

最终有 $a>b\lor a=b\rightarrow a+c=b+c\lor a+c>b+c$ 即 $a+c\geq b+c$

**** 推论1<<MK7>>

序关系有以下等价条件

（1） $a>b\Leftrightarrow a-b>0$

（2） $a\geq b\Leftrightarrow a-b\geq 0$

***** 证明

根据[[MK6][减法定义]]可得 $b-b=0$ 则根据运算相容 $a>b\Leftrightarrow a-b>b-b=0$

同理可证 $a\geq b\Leftrightarrow a-b\geq 0$

**** 推论2<<MK32>>

\begin{aligned}
a>b\land c>d&\rightarrow a+c>b+d\\
a<b\land c<d&\rightarrow a+c<b+d\\
a\geq b\land c\geq d&\rightarrow a+c\geq b+d\\
a\leq b\land c\leq d&\rightarrow a+c\leq b+d\\
\end{aligned}

***** 证明

仅证 $a>b\land c>d&\rightarrow a+c>b+d$ 根据[[MK7][推论1]]有 $a-b>0\land c-d>0$ 

若 $(a-b)+(c-d)=0$ 则 $(a-b)$ 是 $(c-d)$ 的逆元，根据[[MK29][逆元相反]]可得 $a-b<0$ 不符合条件

若 $(a-b)+(c-d)<0$ 则 $(a-b)<-(c-d)$ 即 $(a-b)$ 小于 $(c-d)$ 的逆元

根据逆元相反 $-(c-d)<0$ 则根据传递性 $(a-b)<-(c-d)<0$ 不符合条件

故根据三歧性，仅有可能 $(a-b)+(c-d)>0$ 根据推论1即 $a+c>b+d$

**** 逆元相反<<MK29>>

若 $a>b$ 则有 $-a<-b$

同理可有 $a\geq b\rightarrow -b\geq -a$ 等其他

***** 证明

根据[[MK7][推论1]]可得 $a>b\rightarrow a-b>0$ 则根据计算相容 $a-b-a<-a$ 即得 $-b<-a$

**** 绝对值<<MK15>>

根据[[MK7][推论1]]以及[[MK4][域公理]]中（5），对于任意 $x\in\mathbb{R}$ 定义其绝对值 $|x|=\begin{cases}x&x\geq0\\-x&x<0\end{cases}$

**** 三角不等式<<MK22>>

根据[[MK15][绝对值]]定义，有 $\{a,b\}\subset\mathbb{R}$ 则有 $|a+b|\leq|a|+|b|$

***** 证明

若 $a<0\land b<0$ 则有 $|a|+|b|=(-a)+(-b)$ 

根据运算相容有 $a+b<0$ 则 $|a+b|=-(a+b)$ 根据[[MK17][逆元等价]]可得 $-(a+b)=(-1)(a+b)$

故根据[[MK4][分配率]]可得 $(-1)(a+b)=(-1)a+(-1)b=(-a)+(-b)$ 故有 $|a+b|=|a|+|b|$

**** 二分定理<<MK12>>

对于任意 $\{a,b\}\subset\mathbb{R}$ 且 $b>a$ 则有 $\frac{a+b}{2}\in\mathbb{R}$ 且满足

（1） $a<\frac{a+b}{2}<b$

（2） $b-\frac{a+b}{2}=\frac{a+b}{2}-a=\frac{b-a}{2}$

（3） $\left[a,\frac{a+b}{2}\right]\subset[a,b]\land\left[\frac{a+b}{2},b\right]\subset[a,b]$

***** 证明

****** 证明（1）

根据[[MK10][推论2]]可得 $\frac{1}{2}\in\mathbb{R}$ 根据[[MK4][域公理]]中（0）封闭性可得 $a+b\in\mathbb{R}$ 进一步有 $(a+b)\frac{1}{2}\in\mathbb{R}$

****** 证明（2）

根据[[MK9][减法]]可得 $b-\frac{a+b}{2}=\frac{a+b}{2}-a=\frac{b-a}{2}$ 根据[[MK1][推论1]]可得 $\frac{b-a}{2}>0\rightarrow a<\frac{a+b}{2}<b$

****** 证明（3）

对于任意 $x\in\left[a,\frac{a+b}{2}\right]$ 则根据[[MK13][区间]]可得 $a\leq x\leq\frac{a+b}{2}$

根据（2）有及[[MK14][大于等于]]定义有 $\frac{a+b}{2}<b\rightarrow \frac{a+b}{2}\leq b$

根据[[MK14][大于等于]]传递性有 $a\leq x\leq b$ 故根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的关系-包含]]可得 $\left[a,\frac{a+b}{2}\right]\subset[a,b]$

同理可证 $\left[\frac{a+b}{2},b\right]\subset[a,b]$

**** 区间<<MK13>>

若 $\{a,b\}\subset\mathbb{R}\land a<b$ 则定义 $[a,b]=\left\{x\big|x\in\mathbb{R}\land a \leq x\leq b\right\}$ 以及 $(a,b)=\left\{x\big|x\in\mathbb{R}\land a<x<b\right\}$

***** 高维区间<<MK55>>

高维区间定义为 $\mathbb{R}$ 的笛卡尔积，即定义 $I\subset\mathbb{R}^n$ 为 $\mathbb{R}^n$ 上的区间

则定义 $I=\prod_{i=1}^n[a_i,b_i]$ 即 $n$ 个一维区间 $[a_i,b_i]$ 的笛卡尔积

*** 连续性公理<<MK3>>

如果两个集合 $A\subset\mathbb{R}\land B\subset\mathbb{R}$ 满足：

（1） $A\ne\varnothing\land B\ne\varnothing$

（2） $A\cup B=\mathbb{R}$

（3） $\forall x\in A\forall y\in B(x<y)$

则有 $\exists c\in\mathbb{R}\left(\forall x\in A\forall y\in B(x\leq c\leq y)\right)$

**** 充要条件<<MK18>>

满足[[MK4][域公理]]以及[[MK5][序公理]]的前提下，连续性公理的充要条件是确界存在定理，即有上界必有上确界，有下界必有下确界

***** 证明

****** 充分

若集合 $S\subset\mathbb{R}$ 有上界，即存在 $c\in\mathbb{R}$ 满足 $\forall x\in S\rightarrow x\leq c$

定义集合 $B=\left\{a\in\mathbb{R}\big|\forall x\in S\rightarrow x<a\right\}$ 定义 $A=\mathbb{R}/B$ 下面证明满足（0）的三个条件

（1） $A\ne\varnothing\land B\ne\varnothing$

     由于有界，则 $\forall x\in S\rightarrow x\leq c$ 故有 $c\in B$ 故 $B$ 非空

     由于 $S$ 非空，且 $\forall x\in S\subset\mathbb{R}$ 不满足 $B$ 且 $A=\mathbb{R}/B$ 故有 $x\in A$ 故 $A$ 非空

（2） $A\cup B=\mathbb{R}$

     根据 $A=\mathbb{R}/B$ 得 $A\cup B=\mathbb{R}$

（3） $\forall x\in A\forall y\in B(x<y)$

     任取 $x\in A,y\in B$ 由于 $x\in A\rightarrow x\not\in B$ 则 $\exists z\in S\rightarrow z\geq x$ 由于 $y\in B$ 及 $z\in S$ 则有 $y>z$

     根据[[MK5][传递性]]可得 $y>x$

故根据（0）有 $\exists c\in\mathbb{R}\left(\forall x\in A\forall y\in B(x\leq c\leq y)\right)$ 则有

（1） 根据之前证明 $\forall x\in S(x\in A)$ 则有 $\forall x\in S(x\leq c)$

（2） 对于任意 $\epsilon>0$ 根据[[MK14][等价表述]]可证 $c-\epsilon<c$ 则有 $c-\epsilon\not\in B$ 根据 $B$ 的定义可得则 $\exists z\in S\rightarrow z\geq c$

故 $c$ 是 $S$ 的上确界

****** 必要

如果两个集合 $A\subset\mathbb{R}\land B\subset\mathbb{R}$ 满足：

（1） $A\ne\varnothing\land B\ne\varnothing$

（2） $A\cup B=\mathbb{R}$

（3） $\forall x\in A\forall y\in B(x<y)$

显然 $A$ 有上界，根据（1）有上确界 $c_1$ ，同理 $B$ 有下确界 $c_2$

若 $c_1<c_2$ 则根据[[MK12][二分定理]]存在 $x\in\mathbb{R}$ 满足 $c_1<x<c_2$ 则 $x\not\in A\land x\not\in B$ 显然与（2）矛盾

同理可证 $c_1>c_2$ 亦矛盾，故根据[[MK4][序公理]]三歧性可得 $c_1=c_2$ 即戴德金定理

**** 阿基米德性质<<MK19>>

对于任意 $\{a,b\}\in\mathbb{R}\land a\geq0$ 存在 $n\in\mathbb{N}^+$ 满足 $na>b$ 其中 $na$ 是 $n$ 个 $a$ 相加

***** 证明

当 $a=0$ 时 $1\in\mathbb{N}^+$ 满足

当 $a>0$ 时，由于满足连续性公理，则[[MK18][确界存在定理]]等价，定义 $S=\left\{na\big|n\in\mathbb{N}^+\right\}$

假设存在 $b\in\mathbb{R}$ 满足 $\forall na\rightarrow b>na$ 则 $S$ 有上界 $b$ 故必有上确界，定义为 $\beta$

则根据[[MK4][域公理]]分配率以及自然数定义有 $\forall na\in S\rightarrow na+a=(n+1)a\in S\rightarrow(n+1)a<\beta$ 

故根据[[MK5][序公理]]运算相容可得 $na<\beta-a$

结合上述条件可得 $\forall na\in S\rightarrow na<\beta-a$ 故 $\beta-a$ 亦为上界

由于 $a>0$ 故有 $\beta-a<\beta$ 与上确界定义矛盾，故证得

***** 推论<<MK23>>

对于任意 $a\in\mathbb{R}\land K\in\mathbb{N^+}\land K>1$ 存在 $n\in\mathbb{N}^+$ 满足 $K^n>a$

****** 证明

根据[[MK20][幂定义]]可得 $K^n=(K^{n-1})\cdot K$

（1） 根据条件 $K\in\mathbb{N}^+$ 

（2） 若 $K^n\in\mathbb{N}$ 则 $K\cdot K^n=\sum_{i=1}^KK^n$ 根据整数定义仍然有 $K^{n+1}\in\mathbb{N}$

故当 $n\in\mathbb{N}$ （整数必有限）则有 $K^n\in\mathbb{N}$ 故 $K^n$ 定义为 $K$ 个 $K^{n-1}$ 相加

根据条件有

（1） $K^1>1$ 

（2） 若 $K^n>n$ 则由[[MK32][推论2]] $K^{n+1}=\sum_{i=1}^KK^{n}>Kn$ 由于 $K>1\land K\in\mathbb{N}^+$ 故有 $K\geq 2$ 即 $K^{n+1}>Kn\geq2n\geq n+1$ 

根据传递性，即 $K^n>n$ 

根据阿基米德性质，定义 $b=1$ 则必有 $nb=n>a$ 结合之前证明 $K^n>n>a$ 证毕

***** 推论2<<MK30>>

对于任意 $a\in\mathbb{R}$ 存在 $i\in\mathbb{N}$ 满足 $i\leq a< i+1$

****** 证明

不妨设 $a\geq 0$ 则根据[[MK19][阿基米德性质]]对于任意 $a\in\mathbb{R}$ 以及 $b=1\in\mathbb{R}$ 存在 $n\in\mathbb{N}^+$ 满足 $nb=n>a$

定义 $I=\{i|i\in\mathbb{N}\land 0\leq i< n\}$ 定义 $\exists i\in I\rightarrow i\leq a< i+1$ 的逆否命题为 $\forall i\in I\rightarrow \lnot(i\leq a< i+1)$

根据[[~/OneDrive/离散数学/Disc_Math.org][命题逻辑-命题公式-命题公式关系-逻辑等价-举例-德摩根律]]可得等价命题 $\forall i\in I\rightarrow (a<i\lor a\geq i+1)$

假设成立，故：

（1） 对于 $n-1$ 必有 $a<n-1\lor a\geq n$ 由于 $n>a$ 则根据[[MK5][三歧性]] $a\geq 0$ 不成立，仅有可能 $a<n-1$

（2） 对于任意 $i\in I$ 满足 $a<i$ 则必有 $a<i-1\lor a\geq i$ 同理则根据[[MK5][三歧性]] $a\geq i$ 不成立，必有 $a<i-1$

故得对于任意 $i\in I$ 均有 $a<i$ ，显然 $i=0$ 时与 $a\geq 0$ 矛盾，故有假设不成立。

即对于任意 $a\geq 0$ 成立存在 $i\in\mathbb{N}$ 满足 $i\leq a\leq i+1$

则对于 $a<0$ 是 $-a$ 的逆元，可根据[[MK29][逆元相反]]推论证明

** 完备性等价定理<<MK31>>

满足[[MK4][域公理]]以及[[MK5][序公理]]的前提下，以下六组定理等价：

（1） [[~/OneDrive/数学分析/Chap11Note.org][实数系基本定理-确界存在定理]]（确界亦为实数）

（2） [[~/OneDrive/数学分析/Chap11Note.org][实数系基本定理-单调有界数列定理]]（收敛于实数）

（3） [[~/OneDrive/数学分析/Chap11Note.org][实数系基本定理-闭区间套定理]]（收敛于实数） + [[MK19][阿基米德性质]]

（4） 有限覆盖定理：闭[[MK13][区间]] $[a,b]$ 上的开覆盖 $H$ 中存在有限个开区间，构成 $[a,b]$ 上的一个覆盖

（5） 聚点定理：若 $S\in\mathbb{R}$ 是[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-无限集]]且有界，则必有[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-开集与闭集-点的定义-聚点]]

（6） [[~/OneDrive/数学分析/Chap11Note.org][实数系基本定理-柯西收敛原理]]（收敛于实数） + [[MK19][阿基米德性质]]

**** 证明

定义对于任意满足[[MK3][完备性公理]]的数列 $K=\left\{x_n\big|n\in\mathbb{N}\land x_n\in\mathbb{R}\right\}$ 简单记作 $\{x_n\}$

***** （1）证（2）

若 $\{x_n\}$ 单调增加有上界，则根据确界存在定理，必有上确界 $\xi\in\mathbb{R}$ 满足：

（1） $\forall n\in N^+\Rightarrow a_n\leq\xi$

（2） $\forall \epsilon>0,\exists x_i\in\{x_n\}\Rightarrow \xi-x_i<\epsilon$

故取 $N=i$ 由于单调递增，则根据[[MK5][序公理]]运算相容得 $\forall n>N\Rightarrow x_n\geq x_N\Rightarrow \xi-x_N+x_N\leq\epsilon+x_n$

故 $\forall \epsilon >0,\exists N,\forall n>N\Rightarrow \xi-x_n<\epsilon$ 则 $\lim_{n\to\infty}x_n=\xi$

有下界且单调递减同理

***** （2）证（3）

****** 闭区间套<<MK27>>

根据条件 $[a_{n+1},b_{n+1}]\subset [a_{n},b_{n}]$ 结合[[MK5][序公理]]显然 $a_{n+1}\geq a_n$ 且有 $\forall a_i\rightarrow a_i\leq b_i$

故数列 $\{a_n\}$ 有上界且单调递增，则根据（2）可得 $\{a_n\}$ 收敛，同理可证 $\{b_n\}$ 收敛

定义 $\lim_{n\to\infty}a_n=a,\lim_{n\to\infty}a_n=b$ 

则根据极限四则运算有 $\lim_{n\to\infty}(b_n-a_n)=\lim_{n\to\infty}a_n-\lim_{n\to\infty}a_n=b-a=0$

根据[[MK8][相等等价]]可得 $a=b$

****** [[MK19][阿基米德性质]]

对于任意 $\{a,b\}\subset\mathbb{R}\land a>0$ 定义数列 $\{na\}$ 则有 $(n+1)a-na=a>0$ 根据[[MK7][推论1]]有 $(n+1)a>na$

故单调递增。

假设阿基米德性质不成立，故 $\forall n\in\mathbb{N}^+\rightarrow na<b$ 则数列 $\{na\}$ 有界，则根据（2）必收敛

定义其收敛极限为 $A\in\mathbb{R}$ 则根据定义有 $\forall\epsilon>0,\exists N,\forall n>N\rightarrow |na-A|<\epsilon$

取 $\epsilon=\frac{a}{2}$ 则 $\exists N,\forall n>N\rightarrow |na-A|<\frac{a}{2}$ 根据[[MK15][绝对值]]定义可得 $|A-na|<\frac{a}{2}$

根据[[MK7][推论1]] $n+1>n$ 根据[[MK5][序公理]]传递性有 $n+1>N$

则有 $|(n+1)a-A|<\frac{a}{2}$ 根据[[MK4][域公理]]分配率可得 $|na+a-A|<\frac{a}{2}$ 

根据[[MK22][三角不等式]]可得 $a=|a|=|na+a-A+A-na|<|na+a-A|+|A-na|<\frac{a}{2}+\frac{a}{2}=a$

即得 $a<a$ 根据[[MK11][相等是等价关系]]的自反性可得 $a=a$ 则与[[MK5][序公理]]三歧性矛盾

故假设不成立，阿基米德性质成立

***** （3）证（4）

****** 反正法假设

根据[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-Euclid空间基本定理-Heine-Borel定理-前提定义-开覆盖]]的定义

故任意 $U\in H$ 是满足[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-开集与闭集-开集定义]]的集合

假设不能被有限个开集覆盖

****** 构造闭区间套<<MK24>>

则根据[[MK12][二分定理]]可得有 $c=\frac{a+b}{2}\in\mathbb{R}$ 满足:

（1） $a<c<b$ 

（2） $b-c=c-a=\frac{b-a}{2}$

（3） $[a,c]\subset[a,b]\land[c,b]\subset[a,b]$

若 $[a,c]\subset \bigcup_{i=1}^n U_i$ 其中 $U_i\in H$ 且 $[c,b]\subset \bigcup_{i=1}^n V_i$ 且 $V_i\in H$

则有 $[a,b]=[a,c]\cup[b,c]\subset\left(\bigcup_{i=1}^n U_i\right)\cup\left(\bigcup_{i=1}^n V_i\right)$ 即可被有限个开集覆盖

故 $[a,c],[c,b]$ 中必有一个不能被有限个开集覆盖，定义不可被覆盖的区间为 $[a_1,b_1]$

同理对于区间 $[a_n,b_n]$ 定义 $c=\frac{a_n+b_n}{2}$ 则 $[a_n,c],[c,b_n]$ 必有一个不能被有限覆盖

定义不能被有限覆盖的区间为 $[a_{n+1},b_{n+1}]\subset[a_n,b_n]$ 且有 $b_{n+1}-a_{n+1}=\frac{b_n-a_n}{2}$

****** 证明极限满足闭区间套<<MK25>>

根据[[MK4][域公理]]结合律可得 $(b_n-a_n)\frac{1}{2}=\left((b_{n-1}-a_{n-1})\frac{1}{2}\right)\frac{1}{2}=\frac{b_n-a_n}{2^2}$

故有 $b_n-a_n=\frac{b-a}{2^n}$ 对于任意 $\epsilon>0\land\epsilon\in\mathbb{R}$ 则根据[[MK4][域公理]]封闭性有 $\frac{b-a}{\epsilon}\in\mathbb{R}$

故根据[[MK23][推论]]则存在 $N\in\mathbb{N}$ 使得 $2^N>\frac{b-a}{\epsilon}$ 

由于 $\forall n\in\mathbb{N}^+\left(n>N\rightarrow 2^n>2^N\right)$ 故根据[[MK5][序公理]]传递性有 $\forall n\in\mathbb{N}^+\left(n>N\rightarrow 2^n>\frac{b-a}{\epsilon}\right)$ 

根据[[MK5][序公理]]乘法相容得 $\epsilon=\frac{\epsilon}{2^n}2^n>\frac{b-a}{\epsilon}\frac{\epsilon}{2^n}=\frac{b-a}{2^n}$ 且根据[[MK15][绝对值]]定义以及 $b>a$ 有 $\left|\frac{b-a}{2^n}\right|=\frac{b-a}{2^n}$

综上所述，即 $\forall\epsilon>0,\exists N,\forall n>N\rightarrow \left|\frac{b-a}{2^n}\right|<\epsilon$ 即 $\lim_{n\to\infty}\frac{b-a}{2^n}=\lim_{n\to\infty}b_n-a_n=0$

****** 证明结论

根据之前证明 $[a_n,b_n]$ 满足闭区间套定理

故存在唯一实数 $\xi$ 属于所有 $[a_n,b_n]$ 且 $\lim_{n\to\infty}a_n=\lim_{n\to\infty}b_n=\xi$

由于 $\xi\in[a,b]$ 且 $H$ 是覆盖，故必然存在 $\xi\in C\in H$ 

其中 $C$ 是一个满足[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-开集与闭集-开集定义]]的开集

则根据开集定义可知 $\xi$ 是[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-开集与闭集-点的定义-内点]]，故 $\exists\epsilon>0\rightarrow (\xi-\epsilon,\xi+\epsilon)\subset C$

由于 $\lim_{n\to\infty}a_n=\lim_{n\to\infty}b_n=\xi$ 故必存在 $N$ 满足 $\forall n>N\rightarrow\xi-a_n<\epsilon\land b_n-\xi<\epsilon$

故有 $[a_n,b_n]\subset(\xi-\epsilon,\xi+\epsilon)\subset C$ 即可被一个开集 $C$ 包含，与证明第一步中假设不能被包含矛盾。

故假设不成立，则存在 $H$ 中的有限开覆盖

***** （4）证（5）<<MK26>>

因为有界，故有上下界，即 $\forall x\in S\left(\exists \{a,b\}\in R\rightarrow a<x<b\right)$ 故根据[[MK13][区间]]可得 $S\subset [a,b]$

根据[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-开集与闭集-点的定义-聚点-充要条件1]]

定义存在聚点的条件 $\exists x\in S\left(\forall\epsilon>0\rightarrow\exists s\in S(s\ne x\land s\in(x-\epsilon,x+\epsilon))\right)$

则不存在聚点（逆否命题）的定义为 $\forall x\in S\left(\exists\epsilon_0>0\rightarrow\forall s\in S(s\ne x\rightarrow s\not\in(x-\epsilon,x+\epsilon))\right)$

定义 $E=\bigcup_{x\in[a,b]}(x-\epsilon_0,x+\epsilon_0)$ 则显然 $S\subset[a,b]\subset E$ 即 $E$ 为 $S$ 的开覆盖

根据（4）必有有限开覆盖，根据定义每个 $(x-\epsilon_0,x+\epsilon_0)$ 区间至多包含一个 $S$ 中的点

则存在有限开覆盖即 $S$ 中存在有限个元素，与无限集矛盾。故必存在聚点

***** （5）证（6）

****** [[MK19][阿基米德性质]]

对于任意 $\{a,b\}\subset\mathbb{R}\land a>0$ 定义数列 $\{na\}$ 则有 $(n+1)a-na=a>0$ 根据[[MK7][推论1]]有 $(n+1)a>na$

故单调递增。

假设阿基米德性质不成立，故 $\forall n\in\mathbb{N}^+\rightarrow na<b$ 则数列 $\{na\}$ 有界

显然 $\{na\}\sim\mathbb{N}$ 即为可数集，根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-可数集]]可知 $\{na\}$ 是无限集

故根据（5）必存在聚点

显然对于任意 $na$ 根据[[MK4][序公理]]有 $(n-1)a<na<(n+1)a$ 即 $na\in(na+a,na-a)$

故有 $\forall na\in S\left(\exists \epsilon=a>0\rightarrow \forall ma\in S(ma\ne na\rightarrow ma\not\in(na-\epsilon,na+\epsilon))\right)$

即[[MK26][之前证明]]中描述的无聚点，与（5）矛盾。故必存在 $na>b$ 即阿基米德性质成立

****** 柯西收敛原理

定义 $\{x_n\}$ 是满足 $\forall \epsilon>0,\exists N,\forall n,m>N\Rightarrow |x_n-x_m|<\epsilon$ 的[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-可数集]]

根据可数集定义 $\{x_n\}$ 是无限集，则根据（5）存在 $\xi\in\mathbb{R}$ 满足 $\forall\epsilon>0,\exists x_M\in\{x_n\}\rightarrow x_M\in(\xi-\epsilon,\xi+\epsilon)$

则取 $\delta = \min\left(|x_M-(\xi-\epsilon)|,|x_M-(\xi+\epsilon)|\right)$ 

则对 $\delta$ 有 $\exists L,\forall n,m>L\Rightarrow |x_n-x_m|<\epsilon$ 取 $N=\max(M,L)$ 则对于任意 $n>N$ 满足上述两个条件

故根据[[MK5][序公理]]以及[[MK13][区间]]可得 $x_n\in(\xi-\epsilon,\xi+\epsilon)\rightarrow -\epsilon<x_n-\xi<\epsilon$ 进一步根据[[MK15][绝对值]]可得 $|x_n-\xi|<\epsilon$

综上所述，对于任意 $\epsilon>0$ 存在 $N=\max(M,L)$ 对于一切 $n>N$ 均有 $|x_n-\xi|<\epsilon$

即极限存在且为 $\xi$

***** （6）证（1）

****** 构建区间<<MK28>>

若 $S\subset\mathbb{R}$ 有上界（下界同理可证） $b$ ，即 $\forall x\in S\rightarrow x<b$ 则取任意 $a\in S$ 构建[[MK13][区间]] $[a,b]$

根据[[MK24][之前证明]]构建闭区间套，取存在 $S$ 中元素的区间构成 $[a_n,b_n]$ 取数列 $a_n,b_n$ 

显然根据构建规则 $a_{n+1}\geq a_n,b_{n+1}\leq b_n$ 并且有：

（1） 对于任意 $n$ 总存在 $x\in S$ 满足 $x\geq a_n$

（2） 对于任意 $n$ 均有 $\forall x\in S\rightarrow x\leq b_n$

****** 证明不等式<<MK26>>

当 $m>n$ 且 $\{m,n\}\subset\mathbb{N}^+$ 时根据[[MK5][序公理]]计算相容 $a_n-a_m=\frac{1}{2^n}-\frac{1}{2^m}=\frac{1}{2^n}\left(1-\frac{1}{2^{m-n}}\right)$

根据[[MK14][等价条件]]可得 $m-n>1$ 根据实数减法定义可得 $m-n$ 仍为整数

则根据[[MK20][幂定义]]以及[[MK19][阿基米德性质]]里乘法定义，故有 $2^{m+n}>1$ 根据[[MK5][序公理]]计算相容 $1>\frac{1}{2^{m-n}}$

则 $1-\frac{1}{2^{m-n}}>0$ 根据[[MK14][等价条件]] $1<1+\frac{1}{2^{m-n}}$ 则根据[[MK5][序公理]]加法计算相容 $1-\frac{1}{2^{m-n}}<1$

根据[[MK5][序公理]]乘法计算相容 $0<\frac{1}{2^n}\left(1-\frac{1}{2^{m-n}}\right)<\frac{1}{2^n}$

****** 证明极限

则对于任意 $\epsilon>0\land\epsilon\in\mathbb{R}$ 根据[[MK23][阿基米德推论]]存在 $N\in\mathbb{N}^+$ 时的 $2^N>\frac{1}{\epsilon}$ 进一步根据计算相容 $\epsilon<\frac{1}{2^N}$

根据[[MK26][之前证明]]可得 $\forall n,m>N\rightarrow 0<\frac{1}{2^N}-\frac{1}{2^n}<\frac{1}{2^N}\land0<\frac{1}{2^N}-\frac{1}{2^m}<\frac{1}{2^N}$

则根据[[MK5][序公理]]传递性以及[[MK15][绝对值]]定义 $\left|\frac{1}{2^n}-\frac{1}{2^N}\right|<\epsilon\land\left|\frac{1}{2^N}-\frac{1}{2^m}\right|<\epsilon$ 根据[[MK22][三角不等]]有 $\left|\frac{1}{2^m}-\frac{1}{2^n}\right|<\epsilon$

即满足（5）中柯西收敛原理，则 $\{a_n\}$ 有极限，定义为 $\xi_a\in\mathbb{R}$ 同理可证 $b_n$ 亦有极限，定义为 $\xi_b\in\mathbb{R}$

根据[[MK25][之前证明]]可得 $\lim_{n\to\infty}b_n-a_n=0$ 则根据[[MK27][之前证明]]有 $\xi_a=\xi_b=\xi$

****** 证明确界

则 $\forall\epsilon>0,\exists N,\forall n>N\rightarrow |b_n-\xi|<\epsilon$ 由于 $b_n$ 递减，故有 $b_n\geq\xi\rightarrow b_n-\xi\geq0$

根据[[MK15][绝对值]]可得 $|b_n-\xi|<\epsilon\rightarrow b_n-\xi<\epsilon$ 则若存在 $x\in S\land x>\xi$ 则取 $\epsilon=x-\xi$

故存在 $b_n-\xi<x-\xi$ 根据[[MK5][序公理]]计算相容 $b_n<x$ 与[[MK28][构建区间中]]（2）矛盾，故 $\forall x\in S\rightarrow x<\xi$

同理 $\forall\epsilon>0,\exists N,\forall n>N\rightarrow |a_n-\xi|<\epsilon$ 由于 $a_n$ 递增，则相反有 $\xi-a_n<\epsilon\rightarrow \xi-\epsilon<a_n$

根据[[MK28][构建区间]]中条件（1）可得 $\forall n(\exists x\in S\rightarrow x>a_n)$ 

则根据[[MK5][序公理]]传递性可得 $\forall\epsilon>0(\exists x\in S\rightarrow x>a_n>\xi-\epsilon)$

综上所述 $\xi$ 是集合 $S$ 的上确界

** 实数定理

*** 定理0<<MK36>>

实数上的任意[[MK13][区间]]均与实数[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的关系-对等]]

**** 证明

***** 单一开区间

定义区间 $(a,b)\subset\mathbb{R}$ 显然函数 $\tan(x)$ 是[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-特殊的函数类型-双射]]函数

函数其值域是 $\mathbb{R}$ 定义域为弧度 $x\in\left(-\frac{\pi}{2},\frac{\pi}{2}\right)$ 则根据对等定义有 $\left(-\frac{\pi}{2},\frac{\pi}{2}\right)\sim\mathbb{R}$

由于对等是等价关系，故根据对称性 $\mathbb{R}\sim\left(-\frac{\pi}{2},\frac{\pi}{2}\right)$

进一步定义函数 $f(x)=\left(x+\frac{\pi}{2})\right\frac{b-a}{\pi}+a$ 显然亦为双射

函数定义域为 $x\in\left(-\frac{\pi}{2},\frac{\pi}{2}\right)$ 值域为 $(a,b)$ 则又根据对等定义有 $\left(-\frac{\pi}{2},\frac{\pi}{2}\right)\sim(a,b)$

同样根据对等是等价关系，以及其传递性有 $\mathbb{R}\sim(a,b)$

***** 单一闭区间

定义区间 $[a,b]\subset\mathbb{R}$ 根据开区间证明有 $(a,b)\sim\mathbb{R}$ 另有显然 $[a,b]\sim[a,b]\subset\mathbb{R}$

则根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-基数-伯恩斯坦定理]]可得 $|[a,b]|=|\mathbb{R}|$

由于两者均为无限集，故基数相等与对等等价。

***** 多区间

对于多区间，根据之前证明，显然其中一个区间与 $\mathbb{R}$ 对等，同时多区间与其自身对等。即与 $\mathbb{R}$ 的子集对等。

同样根据伯恩斯坦定理，可证对等

*** 定理1

实数集合 $\mathbb{R}$ 是[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-不可数集]]

**** 证明

根据[[MK36][定理0]]可得 $\mathbb{R}\sim(0,1)$ 假设 $(0,1)$ 区间与 $\mathbb{N}^+$ [[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的关系-对等]]，则存在双射函数 $\sigma$

定义 $a^{(i)}$ 是 $a\in(0,1)$ 中 $\sigma(a)=i$ 的元素，由于其属于实数，故根据[[MK33][定理2]]存在小数表述

定义 $K=10$ 则有 $a^{(i)}=\sum_{u=1}^\infty\frac{a^{(i)}_u}{10^u}$ 定义一个数字 $\sum_{u=1}^\infty\frac{a_u}{10^u}$ 其中 $a_u=\begin{cases}2&a_u^{(u)}=1\\1&a_u^{(u)}\ne1\end{cases}$

根据[[MK35][推论]]可知 $\sum_{u=1}^\infty\frac{a_u}{10^u}\in\mathbb{R}$ 且对于任意 $a^{(i)}$ 均有 $a_i\ne a^{(i)}_i$ 故 $a\ne a^{(i)}$

即 $a$ 不在数列中，则不存在 $\sigma(a)$ 故不满足[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-相关定义-函数定义]]与 $\sigma$ 是双射函数矛盾

即假设不成立 $(0,1)$ 不可数，根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的关系-对等-定理]]其为等价关系。

根据等价关系传递性可得 $\mathbb{R}$ 不可数

**** 推论1

定义 $A_N$ 是[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-集合族]]其中指标集 $N$ ，满足：

（1） 任意 $A_n\land n\in N$ 均与 $\mathbb{R}$ [[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的关系-对等]]

（2） 任意 $\{n,m\}\subset N$ 均有 $A_n\cap A_m=\varnothing$

（2） $N$ 是[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-至多可数集]]

则有 $\bigcup_{n\in N}A_n$ 亦与 $\mathbb{R}$ 对等

***** 证明

由于 $N$ 是至多可数集，故有 $N\sim S\land S\subset\mathbb{N}$ 定义其双射函数 $\sigma:N\to S$

由于 $A_n\sim\mathbb{R}$ 则根据对等传递性，以及[[MK36][定理0]]可得 $A_n\sim(\sigma(n),\sigma(n)+1)$

则满足 $(\sigma(n),\sigma(n)+1)$ 对于不同 $n$ 互不相交

则有 $\bigcup_{n\in N}A_n\sim\bigcup_{n\in N}(\sigma(n),\sigma(n)+1)$ 进一步根据[[MK36][定理0]]可得 $\bigcup_{n\in N}(\sigma(n),\sigma(n)+1)\sim\mathbb{R}$

故根据传递性可得 $\bigcup_{n\in N}A_n\sim\mathbb{R}$ 

**** 推论2<<MK37>>

定义 $A_N$ 是[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-集合族]]其中指标集 $N$ ，满足：

（1） 任意 $A_n\land n\in N$ 均与 $\mathbb{R}$ [[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的关系-对等]]

（2） $N$ 是[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-至多可数集]]

则其笛卡尔积 $\prod_{n\in N}A_n$ 亦与 $\mathbb{R}$ 对等

***** 证明

根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-基本定义-直积-性质-基数]]可得 $\left|\prod_{n\in N}A_n\right|\geq |A_n|=|\mathbb{R}|$

对于任意 $a\in \prod_{n\in N}A_n$ 其元素均为[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-基本定义-有序组]]，故有 $<a^{(1)},a^{(2)},....>$ 的表达式

其中 $a^{(i)}\in A_i$ 由于与实数对等以及[[MK36][定理0]]，则有 $\sigma_i:A_i\to(0,1)$ 进一步根据[[MK33][定理2]]有 $\sigma_i(a^{(i)})=\sum_{j=1}^\infty\frac{a^{(i)}_j}{10}$

定义函数 $\alpha(i,j)=\frac{i+j}{2}(i+j-1)-(j-1)$ 

根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-至多可数集-定理1-证明]]可得对于 $i,j$ 均为整数时 $\alpha$ 是双射函数

根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-函数的计算-函数求逆]]可得存在你函数 $\alpha^{-1}(k)=<i,j>$ 亦为双射函数

定义 $\alpha^{-1}(k)=<i,j>=<\phi(k),\psi(k)>$ 为 $\alpha^{-1}$ 对应的第一，第二个元素的映射

则构建映射 $$f\left(<a^{(1)},a^{(2)},....>\right)=\sum_{k=1}^\infty\frac{a^{(\phi(k))}_{\psi(k)}}{10^k}\in\mathbb{R}$$ 

显然根据定义对于任意元素 $<a^{(1)},a^{(2)},....>$ 均存在 $f\left(<a^{(1)},a^{(2)},....>\right)$ 则其为函数

当两组元素不想等时，必定有序组上至少一个位置元素不相等。

同一位置的元素源自同一 $A_i$ ，故其通过 $\sigma_i$ 映射的实数亦不相等。则 $f\left(<a^{(1)},a^{(2)},....>\right)$ 映射对应小数为上的数不同

故映射结果不想等。故  $f\left(<a^{(1)},a^{(2)},....>\right)$ 是单射。

则根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-特殊的函数类型-单射-蕴含双射]]可得存在 $S\subset\mathbb{R}$ 使得 $f:\prod_{n\in N}A_n\to S$ 是双射函数

故根据基数定义有 $\left|\prod_{n\in N}A_n\right|\leq|\mathbb{R}|$ 故根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-基数-伯恩斯坦定理]]有 $\left|\prod_{n\in N}A_n\right|=|\mathbb{R}|$ 

**** 推论3

定义 $A_i=\{0,1,...,K\}$ 是[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-有限集]]，则有 $\left|\prod_{i=1}^\infty A_i\right|=|\mathbb{R}|$

***** 证明

若 $|B_i|=|\mathbb{R}|$ 则显然 $|B_i|\geq|A_i|$ 根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-基本定义-直积-性质-基数保序]]可得 $\left|\prod_{i\in I}A_i\right|\leq\left|\prod_{i\in I}B_i\right|$

根据[[MK37][推论2]]可得 $\left|\prod_{i\in I}A_i\right|\leq\left|\prod_{i\in I}B_i\right|=|\mathbb{R}|$ 根据等价关系性质有 $\left|\prod_{i\in I}A_i\right|\leq|\mathbb{R}|$

对于任意 $a\in(0,1)$ 根据[[MK34][定理2]]有 $a=\sum_{i=1}^\infty\frac{a_i}{(K+1)^i}$ 其中 $a_i\in\{0,1,...,K\}$

则存在 $<a_1,a_2,...>\in\prod_{i=1}^\infty A_i$ 故有单射 $\sigma:\mathbb{R}\to\prod_{i=1}^\infty A_i$

则根据[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-特殊的函数类型-单射-蕴含双射]]可得 $\left|\prod_{i=1}^\infty A_i\right|\geq|\mathbb{R}|$

故根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-基数-伯恩斯坦定理]]有 $\left|\prod_{n\in N}A_n\right|=|\mathbb{R}|$ 

**** 推论4

根据[[MK37][推论2]]， $n$ 维[[~/OneDrive/数学分析/Chap11Note.org][欧式空间]] $\mathbb{R}^n$ 亦与 $\mathbb{R}$ 对等

*** 定理2<<MK33>>

任何 $a\in\mathbb{R}$ 均可表示为 $a=n+\sum_{i=1}^\infty\frac{a_i}{K^i}$ 其中 $n\in\mathbb{N}\land K\in\mathbb{N}^+\land K>1$ 且 $a_i\in\{0,1,...,K-1\}$

**** 证明<<MK34>>

根据[[MK30][推论2]]可得有 $n\leq a< n+1$ 定义 $I_1=\left\{\frac{0}{K^1},...,\frac{K-1}{K^1}\right\}$ ，故 $n+\frac{0}{K^1}\leq a< n+\frac{K-1}{K^1}+\frac{1}{K^1}$

则根据[[MK30][推论2]]证明方法可证存在 $a_1\in\{0,1,...,K-1\}$ 满足 $n+\frac{a_1}{K^1}\leq a<n+\frac{a_1}{K^1}+\frac{1}{K^1}$

继续定义 $I_2,...,I_k$ 则可依次证得存在 $a_1,...,a_k$ 满足 $n+\sum_{i=1}^k\frac{a_i}{K^i}\leq a<n+\sum_{i=1}^k\frac{a_i}{K^i}+\frac{1}{K^k}$

定义 $x_u=n+\sum_{i=1}^u\frac{a_i}{K^i},y_u=n+\sum_{i=1}^u\frac{a_i}{K^i}+\frac{1}{K^u}$ 

则有 $x_{u+1}-x_u=\frac{a_{u+1}}{K^{u+1}}\geq0$ 且 $y_{u+1}-y_u=\frac{a_{u+1}+1}{K^{u+1}}-\frac{1}{K^u}\leq0$

故根据[[MK7][推论1]]可得 $x_{u+1}\geq x_u,y_{u+1}\leq y_u$ 则根据[[MK13][区间定义]]的得 $[x_{u+1},y_{u+1}]\subset[x_u,y_u]$

又由于 $x_u-y_u=\frac{1}{K^u}$ 则根据[[MK23][推论]]有对于任意 $\epsilon>0\land\epsilon\in\mathbb{R}$ 存在 $l\in\mathbb{N}^+$ 满足 $\frac{1}{K^l}<\epsilon$

故有 $\lim_{u\to\infty}(y_u-x_u)=\lim_{u\to\infty}(y_u-x_u)=\frac{1}{K^u}=0$ 

结合上述条件，根据根据[[MK31][闭区间套]]可得存在唯一 $\xi\in\mathbb{R}$ 满足 $\forall u\rightarrow x_u\leq \xi\leq y_u$

显然根据构造 $a$ 满足 $\forall u\rightarrow x_u\leq a< y_u$ 根据唯一性可得 $\xi=a$

同样根据[[MK31][闭区间套]]可得 $\lim_{u\to\infty}x_u=n+\sum_{i=1}^\infty\frac{a_i}{K^i}=\xi=a$ 即 $a=n+\sum_{i=1}^\infty\frac{a_i}{K^i}$ 

**** 推论<<MK35>>

若 $a=n+\sum_{i=1}^\infty\frac{a_i}{K^i}$ 其中 $n\in\mathbb{N}\land K\in\mathbb{N}^+\land K>1$ 且 $a_i\in\{0,1,...,K-1\}$ 则 $a\in\mathbb{R}$

***** 证明

定义 $a_u=n+\sum_{i=1}^u\frac{a_i}{K^i},x_u=n+\sum_{i=1}^u\frac{a_i}{K^i},y_u=n+\sum_{i=1}^u\frac{a_i}{K^i}+\frac{1}{K^u}$ 

同[[MK34][之前证明]]可构造闭区间套 $[x_{u+1},y_{u+1}]\subset[x_u,y_u]$ 

且有 $\lim_{u\to\infty}(y_u-x_u)=\lim_{u\to\infty}(y_u-x_u)=\frac{1}{K^u}=0$ 

则根据[[MK31][闭区间套]]可得存在唯一 $\xi\in\mathbb{R}$ 满足 $\forall u\rightarrow x_u\leq \xi\leq y_u$

同样根据[[MK31][闭区间套]]可得 $\lim_{u\to\infty}x_u=n+\sum_{i=1}^\infty\frac{a_i}{K^i}=\xi=a$ 

*** 有理数稠密性<<MK43>>

对于任意 $\{x_1,x_2\}\subset\mathbb{R}$ 且 $x_1<x_2$ 可得存在 $x\in\mathbb{Q}$ 满足 $x_1<x<x_2$

**** 证明

根据[[MK7][推论1]]可得 $x_2-x_1>0$ 运用[[MK19][阿基米德性质]]可得存在 $n(x_2-x_1)>1\rightarrow nx_2>1+nx_1$ 其中 $n\in\mathbb{N}$

根据[[MK30][推论2]]可得存在 $m-1\leq nx_1<m$ 其中 $m\in\mathbb{N}$ 即 $nx_1<m\leq nx_1+1<nx_2$

即 $x_1<\frac{m}{n}<x_2$ 证毕

* 度量

** 度量空间<<MK38>>

定义[[~/OneDrive/离散数学/Disc_Math.org][抽象代数-代数的构建-代数结构]] $<X,d>$ 运算 $d:X\times X\to\mathbb{R}$ 满足：

（1） 非负性： $\forall\{x,y\}\subset X\rightarrow d(x,y)\geq0$

（2） 对称性： $\forall\{x,y\}\subset X\rightarrow d(x,y)=d(y,x)$

（3） 三角性： $\forall\{x,y,z\}\subset X\rightarrow d(x,y)+d(y,z)\geq d(x,z)$

则称代数结构 $<X,d>$ 是一个度量空间

*** 性质

**** 自身为零

对于度量空间 $<X,d>$ 若 $x\in X$ 则有 $d(x,x)$ 是所有距离的下确界

***** 证明

据三角性有 $d(x,x)\leq d(x,x)+d(x,x)=2d(x,x)$

两边同[[MK6][减]] $d(x,x)$ 得 $d(x,x)=0$

** 度量子空间

对于[[MK38][度量空间]] $<X,d>$ 存在 $S\subset X$ 且满足 $<S,d>$ 亦为度量空间，则称其为度量子空间

** 子集距离<<MK89>>

对于[[MK38][度量空间]] $<X,d>$ 若存在 $A\subset X\land B\subset X$ 则 $A,B$ 之间的距离是 $\inf\left\{d(a,b)\big|\forall a\in A\land\forall b\in B\right\}$

** 子集的直径

对于[[MK38][度量空间]] $<X,d>$ 若存在 $A\subset X$ 则其直径 $\phi(A)=\sup\left\{d(a,b)\big|\forall \{a,b\}\subset A\right\}$ 

若 $\phi(A)<\infty$ 则定义此类集合是有界集

** 领域<<MK59>>

定义 $\delta\in\mathbb{R}$ 代数结构 $<X,d>$ ，对于点 $x\in X$ 的 $\delta$ 领域定义为 $O(x,\delta)=\left\{y\big|y\in X\land d(x,y)<\delta\right\}$

*** 性质

（1） $x\in O(x,\delta)$

（2） 对于任意 $\{\delta_1,\delta_2\}\subset\mathbb{R}$ 存在 $\delta_3$ 满足 $O(x,\delta_3)\subset O(x,\delta_1)\subset\cap O(x,\delta_2)$

（3） $\forall y\in O(x,\delta)$ 

（4） 若 $\{x,y\}\subset X\land x\ne y$ 则存在 $\delta$ 使得 $O(x,\delta)\cap O(y,\delta)=\varnothing$

* 测度

** $\sigma$ 代数<<MK50>>

集合 $X$ 上的 $\sigma$ 代数记作 $\sigma(X)$ ，是 $\rho(X)$ 即 $X$ 幂集的一个子集，满足：

（1） 包含集合本身 $X\in\sigma(X)$

（2） 任元素合的补封闭 $\forall A\left(A\in\sigma(X)\rightarrow A^c\in\sigma(X)\right)$ 

（3） [[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-可数]]个元素的并封闭 $A_i\in\sigma(X)\rightarrow\bigcup_{i=1}^\infty A_i\in\sigma(X)$

*** 性质

**** 可数交封闭<<MK67>>

设 $X$ 中的子集列 $\{S_i\}$ 满足 $\forall i\in\mathbb{N}^+\rightarrow S_i\in\sigma(X)$ 则有 $\bigcap_{i=1}^\infty S_i\in\sigma(X)$

***** 证明

根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的计算-性质]]中德摩根率可得 $\bigcap_{i=1}^\infty S_i=((\bigcap_{i=1}^\infty S_i)^c)^c=\left(\bigcup_{i=1}^\infty S_i^c\right)^c$

由于 $S_i\in\sigma(X)$ 则有 $S^c_i\in\sigma(X)$ 则根据可数并封闭 $\bigcup_{i=1}^\infty S_i^c\subset\sigma(X)$

最终根据（2）可得 $\bigcap_{i=1}^\infty S_i=\left(\bigcup_{i=1}^\infty S_i^c\right)^c\in\sigma(X)$

**** 差封闭<<MK74>>

若 $\{S_1,S_2\}\subset\sigma(X)$ 则有 $S_1-S_2\in\sigma(X)$ 

进一步若 $S_1,S_2$ [[MK65][外测度可测]] $S_2\subset S_1$ 且 $\varphi(S_2)<\infty$ 则有 $\varphi(S_1-S_2)=\varphi(S_1)-\varphi(S_2)$

***** 证明

根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的计算-性质-补与减]]可得 $S_1-S_2=S_1\cap S^c_2$ 根据[[MK50][定义]]中（3）以及[[MK67][交封闭]]得 $S_1\cap S_2^c\in\sigma(X)$

根据[[MK65][Caratheodory定理]]可得若 $S_2$ 外测度可测，则满足 $\varphi(S_1)=\varphi(S_1\cap S_2)+\varphi(S_1-S_2)$

根据 $S_2\subset S_1$ 得 $S_1\cap S_2=S_2$ 则有 $\varphi(S_1)=\varphi(S_2)+\varphi(S_1-S_2)$

此时若 $\varphi(S_2)<\infty$ 则有 $\varphi(S_1-S_2)=\varphi(S_1)-\varphi(S_2)$

**** [[MK69][递增]]集合列[[MK1][极限]]封闭<<MK73>>

若 $\{S_i\}\subset\sigma(X)$ [[MK69][递增]]，则 $\lim_{i\to\infty}S_i\in\sigma(X)$ 

进一步若 $\{S_i\}$ 是[[MK65][外测度可测集列]]，则有 $\varphi(\lim_{i\to\infty}S_i)=\lim_{i\to\infty}\varphi(S_i)$

***** 证明

****** 封闭

根据[[MK70][定理]]可得 $\lim_{n\to\infty}S_n=\cup_{i=1}^\infty S_i$ 且 $\forall i\in\mathbb{N}^+\rightarrow S\in\sigma(X)$ 则根据[[MK50][定义]]（3）可得 $\cup_{i=1}^\infty S_i\in\sigma(X)$

****** 等式

定义 $S_0=\varnothing$ 以及 $S'_i=S_i-S_{i-1}$ 则对于任意 $i\ne j$ 假设 $i>j$

若 $S'_i=\varnothing\lor S'_j=\varnothing$ 则有 $S'_i\cap S'_j=\varnothing$ 

若均不为空集，则根据递增有 $S_j\subset S_{i-1}\subset S_i$ 则有 $\forall x\in S'_j\rightarrow x\in S_j-S_{j-1}\rightarrow x\in S_{i-1}$ 

则有 $x\not\in S'_i$ 故 $S'_i\cap S'_j=\varnothing$ 故 $\{S'_i\}$ 互不相交

由于 $S_1=S'_1-S'_0=S'_1$ 且 $S_i=S'_i\cup S_{i-1}$ 故根据数学归纳法可得 $S_n=\bigcup_{i=1}^n S'_i$

故有 $\lim_{n\to\infty}S_n=\lim_{n\to\infty}\bigcup_{i=1}^n S'_i=\bigcup_{i=1}^\infty S'_i$

根据[[MK65][Caratheodory定理]]由于 $\{S_i\}$ 均外测度可测，则有可数可加性

即 $\varphi(\bigcup_{i=1}^\infty S'_i)=\sum_{i=1}^\infty \varphi(S'_i)=\sum_{i=1}^\infty \varphi(S_i-S_{i-1})=\lim_{n\to\infty}\sum_{i=1}^n \varphi(S_i-S_{i-1})$

则进一步利用可数可加性 $\lim_{n\to\infty}\sum_{i=1}^n \varphi(S_i-S_{i-1})=\lim_{n\to\infty}\varphi\left(\bigcup_{i=1}^n(S_i-S_{i-1})\right)$

由于 $S_{i-1}\subset S_{i}$ 则有 $S_{i}=(S_i-S_{i-1})\cup S_{i-1}$ 且 $S_1-S_0=S_1$

故根据数学归纳法有 $\bigcup_{i=1}^n(S_i-S_{i-1})=S_n$ 最终有 $\varphi(\lim_{i\to\infty}S_i)=\lim_{i\to\infty}\varphi(S_i)$

**** [[MK69][递减]]集合列[[MK1][极限]]封闭<<MK75>>

若 $\{S_i\}\subset\sigma(X)$ [[MK69][递减]]，则 $\lim_{i\to\infty}S_i\in\sigma(X)$

进一步若 $\{S_i\}$ 是[[MK65][外测度可测集列]]且当 $\varphi(S_1)<\infty$ 时有 $\varphi(\lim_{i\to\infty}S_i)=\lim_{i\to\infty}\varphi(S_i)$

***** 证明

****** 封闭

根据[[MK70][定理]]可得 $\lim_{n\to\infty}S_n=\bigcap_{i=1}^\infty S_i$ 且 $\forall i\in\mathbb{N}^+\rightarrow S\in\sigma(X)$ 则根据[[MK71][定理（4）]]有 $\bigcap_{i=1}^\infty S_i\in\sigma(X)$

****** 等式

定义 $S'_{i}=S_1-S_i$ 则 $S'_i$ 是[[MK69][递增]]列，由于 $S_i$ 外测度可测，则根据[[MK65][Caratheodory定理]]可得 $S'_i$ 外测度可测

则根据[[MK73][递增封闭]]有 $\varphi(\lim_{i\to\infty}S'_i)=\lim_{i\to\infty}\varphi(S'_i)$

则进一步 $\varphi(S_1-\lim_{i\to\infty}S_i)=\lim_{i\to\infty}\varphi(S_1-S_i)$ 由于 $S_i\subset S_1$ 且 $\varphi(S_1)<\infty$

则根据[[MK60][单调性]]有 $\forall i\in\mathbb{N}^+\rightarrow\varphi(S_i)<\infty$ 以及 $\varphi(\lim_{i\to\infty}S_i)<\infty$ 

故根据[[MK74][差封闭]]有 $\varphi(S_1)-\varphi(\lim_{i\to\infty}S_i)=\lim_{i\to\infty}[\varphi(S_1)-\varphi(S_i)]$ 

故根据极限四则运算有 $\varphi(S_1)-\varphi(\lim_{i\to\infty}S_i)=\varphi(S_1)-\lim_{i\to\infty}\varphi(S_i)$

再一次根据 $\varphi(S_1)<\infty$ 有 $\varphi(\lim_{i\to\infty}S_i)=\lim_{i\to\infty}\varphi(S_i)$

*** 生成<<MK85>>

定义 $\beta\subset\rho(X)$ ，则所有包含 $\beta$ 的[[MK50][ $\sigma$ 代数]]之并定义为 $\beta$ 生成的 $\sigma$ 代数

**** 存在性

由于 $\rho(X)$ 本身为 $\sigma$ 代数且不为空，进一步由于 $\beta\subset\rho(X)$ 且任意 $\sigma$ 代数均不为空集

故必然存在由 $\beta$ 生成的 $\sigma$ 代数

** 测度<<MK56>>

设 $\Gamma$ 是集合 $X$ 的[[MK50][ $\sigma$ 代数]]，函数 $\rho:\Gamma\to\mathbb{R}\cup\{+\infty\}$ 满足：

（1） 非负性： $\forall A\in\Gamma\rightarrow \rho(A)\geq0$

（2） 规范性： $\rho(\varnothing)=0$

（3） 可数可加性： $\rho(\bigcup_{i=1}^\infty A_i)=\sum_{i=1}^\infty\rho(A_i)$ 注意此处 $i$ 为[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-可数]]个，且当 $i\ne j$ 时 $A_i\cap A_j=\varnothing$

则称 $\rho$ 是 $X$ 上的测度，其中 $\Gamma$ 是可测集。

** 外测度<<MK61>>

定义集合 $X$ 则定义映射 $\varphi:\rho(X)\to\mathbb{R}\cup\{\infty\}$ 其中 $\rho(X)$ 是 $X$ 的[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的关系-幂集]]

若映射满足：

（1） 非负性： $\forall A\subset X\rightarrow\varphi(A)\geq 0$

（2） 规范性： $\varphi(\varnothing)=0$

（3） 单调性： $A\subset B\rightarrow\varphi(A)\leq\varphi(B)$

（4） 次可数可加性： $\varphi\left(\bigcup_{i=1}^\infty A_i\right)\leq\sum_{i=1}^\infty\varphi(A_i)$

则称 $\varphi$ 是 $X$ 上的外测度

** Caratheodory定理<<MK65>>

对于任意 $S\subset X$ 若满足 $\forall A\subset X\rightarrow\varphi(A)=\varphi(A\cap S)+\varphi(A/S)$ 其中 $\varphi:\rho(X)\to\mathbb{R}$ 是[[MK61][外测度]]

则 $S$ 定义为外测度可测集且：

（1） 所有外测度可测集的集合构成 $X$ 上的[[MK50][ $\sigma$ 代数]]

（2） 在外测度可测集上的[[MK61][外测度]]是[[MK56][测度]]

*** 证明

**** 可测集满足[[MK56][测度]]

根据[[MK61][外测度]]以及[[MK56][测度]]定义可得满足非负性及规范性，以下证明可数可加性。

取任意互不相交的可测集序列 $\{A_i\}\subset X$ 取任意 $n\in\mathbb{N}^+$ 则有 $\bigcup_{i=1}^n A_i\subset\bigcup_{i=1}^\infty A_i$

则根据[[MK61][单调性]]有 $\varphi\left(\bigcup_{i=1}^n A_i\right)\leq\varphi\left(\bigcup_{i=1}^\infty A_i\right)$

由于 $A_1\subset X$ 则根据条件 $\varphi\left(\bigcup_{i=1}^n A_i\right)=\varphi\left(\bigcup_{i=1}^n A_i\cap A_1\right)+\varphi\left(\bigcup_{i=1}^n A_i/A_1\right)=\varphi\left(A_1\right)+\varphi\left(\bigcup_{i=2}^n A_i\right)$

依次类推可得 $\varphi\left(\bigcup_{i=1}^n A_i\right)=\sum_{i=1}^n\varphi(A_i)$ 结合上式有 $\varphi\left(\bigcup_{i=1}^\infty A_i\right)\geq\sum_{i=1}^n\varphi(A_i)$

又由于 $n$ 的任意性以及[[MK53][无穷加法]]定义可得 $\varphi\left(\bigcup_{i=1}^\infty A_i\right)\geq\sum_{i=1}^\infty\varphi(A_i)$

又根据[[MK61][次可数可加性]]有 $\varphi\left(\bigcup_{i=1}^\infty A_i\right)\leq\sum_{i=1}^\infty\varphi(A_i)$ 最终根据[[MK5][三歧性]]有 $\varphi\left(\bigcup_{i=1}^\infty A_i\right)=\sum_{i=1}^\infty\varphi(A_i)$

**** 是 $\sigma$ 代数

***** 全集可测

取任意 $A\subset X$ 则有 $\varphi(A\cup X)+\varphi(A/X)=\varphi(A)+\varphi(\varnothing)=\varphi(A)$ 故 $X$ 外测度可测

***** 补集可测<<MK63>>

若 $S$ 外测度可测，则有 $\forall A\subset X\rightarrow\varphi(A)=\varphi(A\cap S)+\varphi(A/S)$ 

则对 $S^c$ 有 $\varphi(A\cap S^c)+\varphi(A/S^c)=\varphi(A/S)+\varphi(A\cap S)=\varphi(A)$ 故若 $S$ 外测度可测，则有 $S^c$ 外测度可测 

***** 可数并可测

****** 有限可加性<<MK62>>

假设 $S_1,S_2$ 均是外测度可测集，取任意 $A\subset X$ 根据[[MK61][次可加性]] $\varphi(A)\leq\varphi(A\cap(S_1\cup S_2))+\varphi(A/(S_1\cup S_2))$

则根据可测集定义，[[MK61][次可加性]]以及[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的计算-性质]]中分配率、结合律、补与减有：

\begin{aligned}
\varphi(A)=&\varphi(A\cap S_1)+\varphi(A/S_1)\\
=&\varphi((A\cap S_1)\cap S_2)+\varphi((A\cap S_1)/ S_2)+\varphi((A/S_1)\cap S_2)+\varphi((A/S_1)/S_2)\\
\geq&\varphi\big(((A\cap S_1)\cap S_2)\cup((A\cap S_1)/ S_2)\cup((A/S_1)\cap S_2)\big)+\varphi((A/S_1)/S_2)\\
=&\varphi\big((A\cap (S_1\cap S_2))\cup(A\cap (S_1\cap S_2^c))\cup(A\cap (S_1^c\cap S_2))\big)+\varphi(A\cap(S_1^c\cap S_2^c))\\
=&\varphi\bigg(A\cap\big((S_1\cap S_2)\cup(S_1\cap S_2^c)\cup(S_1^c\cap S_2)\big)\bigg)+\varphi(A\cap(S_1\cup S_2)^c)\\
=&\varphi(A\cap(S_1\cup S_2))+\varphi(A/(S_1\cup S_2))\\
\end{aligned}

综上所述若 $S_1,S_2$ 外测度可测，则 $\forall A\subset X\rightarrow\varphi(A)=\varphi(A\cap(S_1\cup S_2))+\varphi(A/(S_1\cup S_2))$ 

即 $S_1\cup S_2$ 亦外测度可测，则根据数学归纳法可得 $\forall n\in\mathbb{N}^$ 若 $S_1,...,S_n$ 外测度可测，可得 $\bigcup_{i=1}^n S_i$ 外测度可测

****** 不相交集可数并<<MK64>>

取 $\forall n\in\mathbb{N}^$ 根据[[MK62][有限可加性]]对于任意 $A\subset X$ 均有 

\begin{aligned}
\varphi\left(A\cap\bigcup_{i=1}^nS_i\right)=&\varphi\left(\left(A\cap\bigcup_{i=1}^nS_i\right)\cap S_n\right)+\varphi\left(\left(A\cap\bigcup_{i=1}^nS_i\right)/S_n\right)\\
=&\varphi\left(A\cap\left(\bigcup_{i=1}^nS_i\cap S_n\right)\right)+\varphi\left(A\cap\left(\bigcup_{i=1}^nS_i\right)\cap S_n^c\right)\\
=&\varphi\left(A\cap S_n\right)+\varphi\left(A\cap\bigcup_{i=1}^nS_i\cap S_n^c\right)\\
\end{aligned}

则根据数学归纳法可得 $\varphi\left(A\cap\bigcup_{i=1}^nS_i\right)=\sum_{i=1}^n\varphi(A\cap S_i)$

由于 $\bigcup_{i=1}^nS_i\subset \bigcup_{i=1}^\infty S_i$ 故有 $A\cap\left(\bigcup_{i=1}^\infty S_i\right)^c\subset A\cap\left(\bigcup_{i=1}^n S_i\right)^c$ 

根据[[MK61][单调性]]可得 $\varphi\left(A\cap\left(\bigcup_{i=1}^\infty S_i\right)^c\right)\leq\varphi\left(A\cap\left(\bigcup_{i=1}^n S_i\right)^c\right)$ 故有

\begin{aligned}
\varphi(A)=&\varphi\left(A\cap\left(\bigcup_{i=1}^n S_i\right)\right)+\varphi\left(A/\left(\bigcup_{i=1}^n S_i\right)\right)\\
=&\sum_{i=1}^n\varphi(A\cap S_i)+\varphi\left(A\cap\left(\bigcup_{i=1}^n S_i\right)^c\right)\\
\geq&\sum_{i=1}^n\varphi(A\cap S_i)+\varphi\left(A\cap\left(\bigcup_{i=1}^\infty S_i\right)^c\right)
\end{aligned}

由于 $n$ 的任意性可得 $\varphi(A)\geq \sum_{i=1}^\infty\varphi(A\cap S_i)+\varphi\left(A\cap\left(\bigcup_{i=1}^\infty S_i\right)^c\right)$ 进一步根据[[MK61][次可数可加性]]有

\begin{aligned}
\varphi(A)\geq&\sum_{i=1}^\infty\varphi(A\cap S_i)+\varphi\left(A\cap\left(\bigcup_{i=1}^\infty S_i\right)^c\right)\\
\geq&\varphi\left(\bigcup_{i=1}^\infty (A\cap S_i)\right)+\varphi\left(A\cap\left(\bigcup_{i=1}^\infty S_i\right)^c\right)\\
=&\varphi\left(A\cap\left(\bigcup_{i=1}^\infty S_i\right)\right)+\varphi\left(A/\left(\bigcup_{i=1}^\infty S_i\right)\right)
\end{aligned}

故有 $\varphi(A)\geq\varphi\left(A\cap\left(\bigcup_{i=1}^\infty S_i\right)\right)+\varphi\left(A/\left(\bigcup_{i=1}^\infty S_i\right)\right)$ 由于 $A=\left(A\cap\left(\bigcup_{i=1}^\infty S_i\right)\right)\cup\left(A/\left(\bigcup_{i=1}^\infty S_i\right)\right)$ 

则由次可数可加性得 $\varphi(A)\leq\varphi\left(A\cap\left(\bigcup_{i=1}^\infty S_i\right)\right)+\varphi\left(A/\left(\bigcup_{i=1}^\infty S_i\right)\right)$ 

故根据[[MK5][三歧性]]，若 $S_1,...,S_\infty$ 互不相交且外测度可测

则 $\forall A\subset X\rightarrow\varphi(A)=\varphi\left(A\cap\left(\bigcup_{i=1}^\infty S_i\right)\right)+\varphi\left(A/\left(\bigcup_{i=1}^\infty S_i\right)\right)$ 即其可数个集合的并外测度可测

****** 一般可数并 

对集合列 $\{S_i\}$ 其中 $S_i\subset X$ 且外测度可测。定义 $S'_j=S_j/\bigcup_{i=1}^{j-1} S_i$

根据[[MK63][补集可测]]以及[[MK62][有限可加]]可得由 $S^c_j,\ \bigcup_{i=1}^{j-1} S_i$ 均可测，则 $S^c_j\cup\left(\bigcup_{i=1}^{j-1} S_i\right),\ \left(S^c_j\cup\left(\bigcup_{i=1}^{j-1} S_i\right)\right)^c$ 可测 

根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的计算-性质]]德摩根律 $\left(S^c_j\cup\left(\bigcup_{i=1}^{j-1} S_i\right)^c\right)^c=S_j\cap\left(\bigcup_{i=1}^{j-1} S_i\right)^c=S_j/\left(\bigcup_{i=1}^{j-1} S_i\right)=S'_j$ 

即 $S'_j$ 外而测度可测，另根据定义显然有 $\bigcup_{i=1}^nS'_i=\bigcup_{i=1}^nS_i$ （证明 $\forall x\big(x\in\bigcup_{i=1}^nS_i\leftrightarrow x\in\bigcup_{i=1}^nS'_i\big)$ ）

则对于任意 $n\in\mathbb{N}^+$ 均有 $\bigcup_{i=1}^nS'_i=\bigcup_{i=1}^nS_i\subset\bigcup_{i=1}^\infty S_i$ 故根据 $n$ 任意性有 $\bigcup_{i=1}^\infty S'_i\subset\bigcup_{i=1}^\infty S_i$

同理 $\bigcup_{i=1}^nS_i=\bigcup_{i=1}^nS'_i\subset\bigcup_{i=1}^\infty S'_i$ 则有 $\bigcup_{i=1}^\infty S_i\subset\bigcup_{i=1}^\infty S'_i$

根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的关系-包含-定理1]]可得 $\bigcup_{i=1}^\infty S_i=\bigcup_{i=1}^\infty S'_i$

故进一步根据[[MK64][不相交可数可加]]可得 $\bigcup_{i=1}^\infty S'_i$ 外测度可测，即 $\bigcup_{i=1}^\infty S_i$ 亦外测度可测

* 实数(勒贝格)测度

** 内测度

若 $E\subset\mathbb{R}^n$ 其内测度定义为 $m'(E)=$ 其中 $|I_i|$ 为[[MK13][开区间]] $I_i$ 的[[MK56][测度]]

** 勒贝格测度定义<<MK52>>

（1） 有界区间 $I=[a,b]$ 的[[MK56][测度]]为 $b-a$ 记作 $|I|=b-a$ ，[[MK55][高维区间]] $I\in\mathbb{R}^n$ 的测度为 $|I|=\prod_{i=1}^n(b_i-a_i)$

（2） 开区间的测度等于其对应的闭区间或半开闭区间

（3） 对于任意 $E\subset\mathbb{R}^n$ 其测度为 $E$ 的[[MK51][外测度]] $m^*(E)$

*** 性质

**** 区间单调性<<MK91>>

若 $I\subset\bigcup_{i=1}^\infty I_i$ 其中 $I,I_i$ 均为有界[[MK13][区间]]，则有 $\sum_{i=1}^\infty |I_i|\geq|I|$

***** 证明

定义 $I_i=\prod_{j=1}^n[a_{i,j},b_{i,j}]$ 以及 $I=\prod_{j=1}^n[a_j,b_j]$ 定义按大小重排所有 $a_{i,j},b_{i,j},a_j,b_j$ 后得 $\{x_{1,j},x_{2,j},...\}$

则根据此划分分割出多个区间定义为 $\{I'_i\}$ 

根据[[MK4][分配率]]易证 $I,I_i$ 的[[MK52][测度]]均为所有是其子集的 $I'_k$ 测度的和，即 $|I_i|=\sum_{I'_k\subset I_i}|I'_k|$

由于 $I\subset\bigcup_{i=1}^\infty I_i$ ，则对于任意 $I'_k\subset I\rightarrow I'_k\subset\bigcup_{i=1}^\infty I_i$ 故有 $\sum_{i=1}^\infty |I_i|\geq|I|$

** 外测度<<MK51>>

若 $E\subset\mathbb{R}^n$ 其外测度定义为可数个开区间覆盖的最小测度，即 $m^*(E)=\inf\left\{\sum_{i=1}^\infty |I_i|\big|E\subset\bigcup_{i=1}^\infty I_i\right\}$ 

其中 $|I_i|$ 为[[MK13][开区间]] $I_i$ 的[[MK56][测度]]

*** 满足[[MK61][定义]]<<MK66>>

**** 非负性<<MK54>>

对于任意 $E\subset\mathbb{R}^n$ 其[[MK51][外测度]]必大于等于零 $m^*(E)\geq0$

***** 证明

对与任意 $E\subset\mathbb{R}^n$ 根据定义其外测度为 $m^*(E)=\inf\left\{\sum_{i=1}^\infty |I_i|\big|E\subset\bigcup_{i=1}^\infty I_i\right\}$

定义 $S=\left\{\sum_{i=1}^\infty |I_i|\big|E\subset\bigcup_{i=1}^\infty I_i\right\}$ 若 $|E|<0$ 则对于任意 $a\in S$ 均有 $a=\sum_{i=1}^\infty |I_i|$ 

由于 $|I_i|$ 是[[MK56][测度]]，故 $|I_i|>0$ 

根据[[MK53][无穷加法]]定义以及[[MK32][推论2]]可得任意有限个 $|I_i|$ 相加的上确界 $>0$ 故得 $a>0$ 故 $m^*(E)=\inf{S}\geq0$

**** 规范性<<MK78>>

在[[MK52][勒贝格测度]]定义下有 $m^*(\varnothing)=0$

***** 证明

对于 $\mathbb{R}^n$ 定义区间 $I=\prod_{i=1}^n\left[-\frac{\epsilon}{2},\frac{\epsilon}{2}\right]$ 根据[[MK52][勒贝格区间]]测度定义有 $|I|=\epsilon^n$

根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的关系-包含-定理4]]可得对于任意 $\epsilon>0\land\epsilon\in\mathbb{R}$ 均有 $\varnothing\subset I$

则 $I$ 是 $\varnothing$ 的开覆盖，由于外测度定义为下确界，故有 $m^*(\varnothing)\leq |I|=\epsilon^n$

根据 $\epsilon$ 任意性可得 $m^*(\varnothing)\leq0$ 根据[[MK54][非负性]]可得 $m^*(\varnothing)\geq0$

故根据[[MK5][三歧性]]可得 $m^*(\varnothing)=0$

**** 次可加性<<MK57>>

若 $A=\bigcup_{i=1}^\infty A_i$ 且 $A_i\subset\mathbb{R}^n$ 则其[[MK51][外测度]]有次可加性，即 $m^*(A)\leq\sum_{i=1}^\infty m^*(A_i)$ 

***** 证明

定义可数个集合 $A_i$ 定义第 $i$ 个集合的某一个至多可数开覆盖为 $A_i\subset\bigcup_{m=1}^\infty I_{i,m}$ 定义集合的并 $A=\bigcup_{i=1}^\infty A_i$

则有 $A\subset\bigcup_{i=1}^\infty\left(\bigcup_{m=1}^\infty I_{i,m}\right)$ 根据[[MK51][外测度]]定义 $m^*(A)$ 为下确界，故必有 $m^*(A)\leq \sum_{i=1}^\infty\left(\sum_{m=1}^\infty |I_{i,m}|\right)$

进一步根据 $m^*(A_i)$ 是 $\sum_{m=1}^\infty|I_{i,m}|$ 的下确界可得

对于任意 $\epsilon>0\land\epsilon\in\mathbb{R}$ 必存在开覆盖 $I_{i,m}$ 使得 $m^*(A_i)\geq \sum_{m=1}^\infty |I_{i,m}|-\frac{\epsilon}{2^i}$ 

即 $m^*(A_i)+\frac{\epsilon}{2^i}\geq \sum_{m=1}^\infty |I_{i,m}|$

根据传递性可得 $m^*(A)\leq \sum_{i=1}^\infty\left(\sum_{m=1}^\infty |I_{i,m}|\right)\leq\sum_{i=1}^\infty \left(m^*(A_i)+\frac{\epsilon}{2^i}\right)$

根据等比数列求和公式 $m^*(A)\leq\sum_{i=1}^nm^*(A_i)+\epsilon$ 进一步由 $\epsilon$ 任意性可得 $m^*(A)\leq\sum_{i=1}^\infty m^*(A_i)$ 

**** 单调性<<MK60>>

若 $A\subset B$ 则其外测度 $m^*(A)\leq m^*(B)$

***** 证明

任取 $B$ 的开覆盖有 $A\subset B\subset\sum_{i=1}^\infty I_i$ 则根据外测度定义 $m^*(A)\leq\sum_{i=1}^\infty|I_i|$

即 $m^*(A)$ 是 $\left\{\sum_{i=1}^\infty |I_i|\big|B\subset\bigcup_{i=1}^\infty I_i\right\}$ 的下界，且由于 $m^*(B)=\inf\left\{\sum_{i=1}^\infty |I_i|\big|B\subset\bigcup_{i=1}^\infty I_i\right\}$ 是下确界

故根据定义下确界是最大下界，故有 $m^*(A)\leq m^*(B)$ 

*** 正则性<<MK79>>

在[[MK52][勒贝格测度]]定义下，任意有界[[MK13][区间]] $I=\prod_{i=1}^n[a_i,b_i]\in\mathbb{R}^n$ 其中乘法为[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-基本定义-直积]]

其外测度等于区间测度 $m^*(I)=|I|=\prod_{i=1}^n(b_i-a_i)$ 乘法为[[MK4][实数乘法]]

**** 证明

定义区间具体描述 $I=\prod_{i=1}^n[a_i,b_i]$ 为有界闭区间

对于任意 $\epsilon>0\land\epsilon\in\mathbb{R}$ 均有 $I\subset\prod_{i=1}^n[a_i,b_i+\epsilon]$

根据外测度下确界定义可得 $m^*(I)\leq|\prod_{i=1}^n[a_i,b_i+\epsilon]|=\prod_{i=1}^n(b_i+\epsilon-a_i)$

根据 $\epsilon$ 任意性以及区间在[[MK52][勒贝格测度]]下定义可得 $m^*(I)\leq|\prod_{i=1}^n[a_i,b_i]|=\prod_{i=1}^n(b_i-a_i)=|I|$

根据下确界定义，对与任意 $\epsilon>0\land\epsilon\in\mathbb{R}$ 均存在覆盖 $\{I_i\}$ 满足 $m^*(I)\geq \sum_{i=1}^\infty |I_i|-\epsilon$

定义 $I'= \bigcup_{i=1}^\infty I_i$ 根据[[MK91][区间单调性]]可得 $|I|\leq\sum_{i=1}^\infty|I_i|$

根据[[MK5][运算相容]]可得 $\sum_{i=1}^\infty|I_i|-\epsilon\leq|I|-\epsilon$ 根据[[MK5][传递性]]可得 $m^*(I)\geq \sum_{i=1}^\infty |I_i|-\epsilon\geq|I|-\epsilon$

根据 $\epsilon$ 任意性可得 $m^*(I)\geq |I|$ 故根据[[MK5][三歧性]]可得 $m^*(I)=|I|$

对于开区间，半开半闭区间区间，其在勒贝格测度下定义其测度等于闭区间，故同理可证

*** 存在性

对于任意 $E\subset\mathbb{R}^n$ 其外测度 $m^*(E)$ 存在

**** 证明

对于任意 $i\in\mathbb{N}^+$ 定义 $K_i=\prod_{j=1}^n[-i,i]$ 其中 $n$ 为欧式空间的维数，乘法为[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-基本定义-直积]]

显然 $K_i$ 是[[MK13][区间]]，且 $\bigcup_{i=1}^\infty K_i=\mathbb{R}^n$ 由于 $E\subset\mathbb{R}^n$ 则有 $E\subset\bigcup_{i=1}^\infty K_i$

则 $\left\{\sum_{i=1}^\infty |I_i|\big|E\subset\bigcup_{i=1}^\infty I_i\right\}$ 不为空集，且显然 $\forall x\in \left\{\sum_{i=1}^\infty |I_i|\big|E\subset\bigcup_{i=1}^\infty I_i\right\}\rightarrow x>0$

故 $\left\{\sum_{i=1}^\infty |I_i|\big|E\subset\bigcup_{i=1}^\infty I_i\right\}$ 有下界，根据[[~/OneDrive/数学分析/Chap11Note.org][实数系基本定理-确界存在定理]]必有下确界

故 $\inf\left\{\sum_{i=1}^\infty |I_i|\big|E\subset\bigcup_{i=1}^\infty I_i\right\}$ 存在，即外测度对于任意集合均存在

** 可测集<<MK81>>

根据[[MK65][Caratheodory定理]]可得，若 $S\subset\mathbb{R}^n$ 可测，则 $S$ 则有 $\forall A\subset X\rightarrow m^*(A)=m^*(A\cap S)+m^*(A/S)$

对于某个欧式空间 $\mathbb{R}^n$ 下的所有可测集定义为 $M_{\mathbb{R}^n}$

*** 等价条件<<MK68>>

对于 $S\subset\mathbb{R}^n$ 以下三个条件等价：

（1） $\forall A\subset X\rightarrow m^*(A)=m^*(A\cap S)+m^*(A/S)$

（2） $\forall I\subset X\rightarrow m^*(I)=m^*(I\cap S)+m^*(I/S)$ 其中 $I$ 是[[MK13][区间]]

（3） $\forall A\forall B\big(A\subset S\land B\subset S^c\rightarrow m^*(A\cup B)=m^*(A)+m^*(B)\big)$

**** 证明

***** （1）到（2）

根据[[MK13][区间]]定义 $I$ 是一种特殊的 $\mathbb{R}^n$ 的子集，故 $I\subset\mathbb{R}^n$

故当满足（1）时（2）亦满足

***** （2）到（1）

对于 $\forall A\subset\mathbb{R}^n$ 根据[[MK51][外测度]]定义可得 $\forall\epsilon\big(\epsilon\in\mathbb{R}\land\epsilon>0\rightarrow(\exists\{I_i\}\rightarrow (A\subset\bigcup_{i=1}^\infty I_i\land m^*(A)\geq\sum_{i=1}^\infty|I_i|-\epsilon))\big)$

由于 $A\subset\bigcup_{i=1}^\infty I_i$ 则有 $A\cap S\subset \bigcup_{i=1}^\infty I_i\cap S$ 以及 $A\cap S^c\subset \bigcup_{i=1}^\infty I_i\cap S^c$ 

则根据[[MK60][单调性]]可得 $m^*(A\cap S)\leq m^*(\bigcup_{i=1}^\infty I_i\cap S)$ 以及 $m^*(A\cap S^c)\leq m^*(\bigcup_{i=1}^\infty I_i\cap S^c)$

进一步根据[[MK57][次可数可加性]]有 $m^*(A\cap S)\leq\sum_{i=1}^\infty m^*(I_i\cap S)$ 以及 $m^*(A\cap S^c)\leq\sum_{i=1}^\infty m^*(I_i\cap S^c)$

则有 $m^*(A\cap S)+m^*(A\cap S^c)\leq\sum_{i=1}^\infty\left(m^*(I_i\cap S)+m^*(I_i\cap S^c)\right)$

由于满足条件（2）则有 $m^*(A\cap S)+m^*(A\cap S^c)\leq\sum_{i=1}^\infty m^*(I_i)$

进一步根据下确界条件有 $m^*(A\cap S)+m^*(A\cap S^c)\leq m^*(A)+\epsilon$ 

根据 $\epsilon$ 任意性有 $m^*(A\cap S)+m^*(A\cap S^c)\leq m^*(A)$ 

又由于 $A\cap S\cup A\cap S^c=A$ 根据[[MK57][次可数可加性]]有 $m^*(A\cap S)+m^*(A\cap S^c)\geq m^*(A)$

则根据[[MK5][三歧性]]可得 $m^*(A\cap S)+m^*(A\cap S^c)=m^*(A)$

综上所述，对于任意 $A\subset\mathbb{R}^n$ 均有 $m^*(A\cap S)+m^*(A\cap S^c)=m^*(A)$ 即（2）到（1）充分

***** （1）到（3）

取 $T=A\cup B$ 则有 $T\subset\mathbb{R}^n$ 且 $T\cap S=A\land T\cap S^c=B$

故根据（1）有 $m^*(T)=m^*(A\bup B)=m^*(T\cap S)+m^*(T/S)=m^*(A)+m^*(B)$

***** （3）到（1）

对于任意 $T\subset\mathbb{R}^n$ 取 $A=T\cap S,B=T\cap S^c$ 则有 $T=A\cup B$

则根据（3）有 $m^*(T)=m^*(A\cup B)=m^*(A)+m^*(B)=m^*(T\cup S)+m^*(T/S)$

*** 计算<<MK84>>

可测及对于[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合的运算-运算]]中定义的计算有以下性质：

（1） 若 $S$ 可测，则 $S^c$ 可测

（2） 若 $\forall i\in\mathbb{N}^+\rightarrow S_i\in M$ 可测，则有 $\bigcup_{i=1}^\infty S_i\in M$ 可测

     且若 $\forall\{i,j\}\subset\mathbb{N}\land i\ne j\rightarrow S_i\cap S_j=\varnothing$ 则有 $m^*\left(\bigcup_{i=1}^\infty S_i\right)=\sum_{i=1}^\infty m^*(S_i)$

（3） 若 $\{S_1,S_2\}\subset M$ 可测，则有 $S_1-S_2$ 可测

     若满足 $S_2\subset S_1\land m^*(S_2)<\infty$ 则有 $m^*(S_1-S_2)=m^*(S_1)-m^*(S_2)$

（4） 若 $\forall i\in\mathbb{N}^+\rightarrow S_i\in M$ 可测，则有 $\bigcap_{i=1}^\infty S_i\in M$ 可测

（5） $\{S_i\}\subset M$ 是[[MK69][递增]]的可测集列，则 $\lim_{i\to\infty}S_i$ 可测，且有 $m^*(\lim_{i\to\infty}S_i)=\lim_{i\to\infty}m^*(S_i)$

（6） $\{S_i\}\subset M$ 是[[MK69][递减]]的可测集列，则 $\lim_{i\to\infty}S_i$ 可测

     且当 $m^*(S_1)<\infty$ 时有 $m^*(\lim_{i\to\infty}S_i)=\lim_{i\to\infty}m^*(S_i)$

**** 证明

根据[[MK66][外测度满足证明]]以及[[MK65][Caratheodory定理]]可得 $M$ 构成[[MK50][ $\sigma$ 代数]]且 $m^*:\mathbb{R}^n\to\mathbb{R}$ 是[[MK56][测度]]

根据 $\sigma$ 代数定义（2）可得（1）

根据 $\sigma$ 代数定义（3）可得（2）

根据[[MK74][差封闭]]可得（3）

根据[[MK67][可数交封闭]]可得（4）

根据[[MK73][递增封闭]]以及[[MK75][递减封闭]]可得（5）和（6）

*** 区间可测<<MK82>>

对于任意[[MK13][区间]] $I\subset\mathbb{R}^n\land n<\infty$ 可得 $I$ 是可测集

**** 证明

定义 $I=\prod_{i=1}^n[a_i,b_i],I'=\prod_{i=1}^n[a'_i,b'_i]$ 

***** 不相交

若存在 $[a_i,b_i]\cap[a'_i,b'_i] =\varnothing$ 则对于任意 $\vec{x} =\{x_1,...,x_n\}\in I$ 均有 $x_i\not\in[a'_i,b'_i]$ 

故有 $\vec{x}\not\in I'$ 即 $I'\cap I=\varnothing$ 则 $I'/I=I'$ 

则有 $m^*(I'\cap I)+m^*(I'/I)=m^*(\varnothing)+m^*(I')$ 根据[[MK78][规范性]]可得 $m^*(\varnothing)=0$

故有 $m^*(I'\cap I)+m^*(I'/I)=m^*(I')$ 

***** 相交

****** 划分区间

若相交，则根据[[MK86][之前证明]]可得不存在 $[a_i,b_i]\cap[a'_i,b'_i] =\varnothing$ 

则对于 $i=1$ 则定义 $a_1,b_1,a'_1,b'_1$ 根据大小依次排列为 $u_1,v_1,x_1,y_1$ 

则将划分区间为 $\prod_{i=2}^n[a_i,b_i]\times[u_1,v_1],\prod_{i=2}^n[a_i,b_i]\times[v_1,x_1],\prod_{i=2}^n[a_i,b_i]\times[x_1,y_1]$

以及 $\prod_{i=2}^n[a'_i,b'_i]\times[u_1,v_1],\prod_{i=2}^n[a'_i,b'_i]\times[v_1,x_1],\prod_{i=2}^n[a'_i,b'_i]\times[x_1,y_1]$

以上6个集合为元素组成的集合族定义为 $I_1$ 取 $I'_1=\left\{K\left|K\in I_1\land K\subset I'\right\}$

接下来当 $i=2$ 时对于每一个 $I'_1$ 中的元素做同样操作，依次类推，最终形成 $I'_n$

****** 划分后集合的性质<<MK80>>

显然：

（1） 由于 $n<\infty$ 故 $I'_n$ 是有限集

（2） 每一个 $I'_n$ 中的元素满足[[MK13][区间]]定义

（3） 每一个 $I'_n$ 中的元素是 $I'$ 的子集

（4） $\bigcup_{K\in I'_n}K=I'$

进一步有 $I'\cap I$ 是所有纬度上的交集，即从1至n纬度上的相交区间，故必存在 $K\in I'_n\rightarrow K=I\cap I'$

****** 证明结论

则根据[[MK57][次可加性]] $m^*(I\cap I')+m^*(I'/I)=m^*(K)+m^*\left(\bigcup_{J\in I'_n\land J\ne K}J\right)\leq m^*(K)+\sum_{i=1}^{|I'_n|-1}m^*(L_i)$

根据[[MK80][之前证明]]中（4）、（1）以及次可加性得 $m^*(K)+\sum_{i=1}^{|I'_n|-1}m^*(L_i)\leq m^*(I')$ 

则有 $m^*(I')\geq m^*(I\cap I')+m^*(I'/I)$ 

又根据[[MK57][次可加性]]以及 $(I'\cap I)\cup (I'/I)=I'$ 可得 $m^*(I')\leq m^*(I\cap I')+m^*(I'/I)$

则根据[[MK5][三歧性]]可得 $m^*(I')=m^*(I\cap I')+m^*(I'/I)$ 故根据[[MK68][定理]]可得区间 $I$ 外测度可测

*** 开集可测<<MK87>>

对于任意开集 $G\subset\mathbb{R}^n\land n<\infty$ 可得 $G$ [[MK81][可测]]

**** 证明

根据[[MK83][有限偶是空间开集构造]]可得任意开集可由有限个[[MK13][区间]]的并表述，根据[[MK82][区间可测]]以及[[MK84][计算]]中可数并封闭得 $G$ 亦[[MK81][可测]]

*** 引理<<MK92>>

对于 $E\subset\mathbb{R}^n$ 且 $E$ [[MK81][可测]]，有：

（1） $\forall\epsilon>0\land\epsilon\in\mathbb{R}$ 存在开集 $G$ 满足 $E\subset G$ 使得 $m^*(G/E)<\epsilon$ 

（2） $\forall\epsilon>0\land\epsilon\in\mathbb{R}$ 存在闭集 $F$ 满足 $F\subset E$ 使得 $m^*(E/F)<\epsilon$ 

其中 $m^*(E)$ 指 $E$ 的[[MK51][外测度]]

**** 证明

***** 证明（1）

****** 当 $m^*(E)<\infty$ 时<<MK90>>

根据[[MK51][外测度]]定义，对于可测集 $E$ 的外测度为 $m^*(E)=\inf\left\{\sum_{i=1}^\infty |I_i|\big|E\subset\bigcup_{i=1}^\infty I_i\right\}$ 

根据确界定义，对于任意 $\forall\epsilon>0\land\epsilon\in\mathbb{R}$ 存在一组开区间 $\{I_i\}$ 满足 $E\subset\bigcup_{i=1}^\infty I_i\land \sum_{i=1}^\infty|I_i|< m^*(E)+\epsilon$

则定义 $G=\bigcup_{i=1}^\infty I_i$ 根据[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-集合定义-部分定理-定理3]]可得 $G$ 仍为开集

根据[[MK57][次可加性]]可得 $m^*(G)\leq \sum_{i=1}^\infty m^*(I_i)<m^*(E)+\epsilon$ 故有 $m^*(G)-m^*(E)<\epsilon$

由于 $m^*(E)<\infty$ 且为[[MK81][可测集]]，故根据[[MK84][计算]]中（3）有 $m^*(G/E)<\epsilon$

****** 当 $m^*(E)=\infty$ 时

对于任意 $i\in\mathbb{N}^+$ 定义 $K_i=\prod_{j=1}^n[-i,i]$ 其中 $n$ 为欧式空间的维数，乘法为[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-基本定义-直积]]

显然 $K_i$ 是[[MK13][区间]]，根据外测度[[MK79][正则性]]可得 $m^*(K_i)=(2i)^n<\infty$

进一步定义 $E_i=E\cap K_i$ 则有 $E\cap K_i\subset K_i$ 则根据[[MK60][单调性]]有 $m^*(E_i)\leq m^*(K_i)<\infty$ 以及 $E_i\subset E$

由于 $\infty\not\in\mathbb{R}$ 则显然有 $E=\bigcup_{i=1}^\infty E_i$ 根据[[MK90][之前证明]]对于每一个 $E_i$ 均有引理（1）成立

故对于任意 $\forall\epsilon>0\land\epsilon\in\mathbb{R}$ 定义 $G_i$ 为满足 $m^*(G_i-E_i)<\frac{\epsilon}{2^i}$ 的开集，定义 $G=\bigcup_{i=1}^\infty G_i$

则有 $m^*(G-E)=m^*\left(\bigcup_{i=1}^\infty(G_i-E_i)\right)\leq\sum_{i=1}^\infty m^*(G_i-E_i)<\sum_{i=1}^\infty\frac{\epsilon}{2^i}=\epsilon$

即有 $m^*(G/E)<\epsilon$

***** 证明（2）

根据条件（1）可得对于 $E^c$ 有 $\forall\epsilon$ 存在开集 $G$ 满足 $m^*(G/E^c)<\epsilon$ 

由于 $G/E^c=E/G^c$ 且由于 $G$ 是开集，则根据[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-集合定义-部分定理-定理1]]可得 $G^c$ 是闭集

定义 $G^c=F$ 则有 $m^*(G/E^c)=m^*(E/F)<\epsilon$

*** 正规性定理

定义 $\Gamma$ 表示 $\mathbb{R}^n$ 所有开集的[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-集合族]]，定义 $\Theta$ 为所有闭集的集合族，若 $E\subset\mathbb{R}^n$ 则：

（1） $E$ 是[[MK81][可测集]]，则有 $m^*(E)=\inf\left\{m^*(G)\big|E\subset G\land G\in\Gamma\right\}=\sup\left\{m^*(F)\big|F\subset E\land F\in\Theta\right\}$

（2） 若满足 $\inf\left\{m^*(G)\big|E\subset G\land G\in\Gamma\right\}=\sup\left\{m^*(F)\big|F\subset E\land F\in\Theta\right\}$ 且 $m^*(E)<\infty$ 

     则 $E$ 是[[MK81][可测集]]且 $m^*(E)=\sup\left\{m^*(F)\big|F\subset E\land F\in\Theta\right\}$

其中 $m^*(E)$ 表示 $E$ 的[[MK51][外测度]]

**** 证明

***** 证明（1）

****** 外正规性

定义为 $m^*(E)=\inf\left\{m^*(G)\big|E\subset G\land G\in\Gamma\right\}$ 

******* 当 $m^*(E)<\infty$ 时

由于 $E$ 是[[MK81][可测集]]，则根据[[MK92][引理]]可得对于任意 $\epsilon>0\land\epsilon\in\mathbb{R}$ 均存在 $G$ 使得 $E\subset G\land m^*(G/E)<\epsilon$

进一步根据[[MK84][计算]]中（3）有 $m^*(G)-m^*(E)<\epsilon$ 由于 $m^*(E)<\infty$ 故有 $m^*(E)>m^*(G)-\epsilon$

且根据[[MK60][单调性]]以及 $E\subset G$ 有 $m^*(E)\leq m^*(G)$ 

结合上述两条性质可得 $m^*(E)=\inf\left\{m^*(G)\big|E\subset G\land G\in\Gamma\right\}$ 

******* 当 $m^*(E)=\infty$ 时

根据[[MK60][单调性]]可得对于任意 $G$ 满足 $E\subset G$ 必有 $m^*(G)\geq m^*(E)$ 即 $m^*(G)=\infty$

故有 $m^*(E)=m^*(G)$

****** 内正规性

定义为 $m^*(E)=\sup\left\{m^*(F)\big|F\subset E\land F\in\Theta\right\}$ 

******* 当 $m^*(E)<\infty$ 时<<MK93>>

由于 $E$ 是[[MK81][可测集]]，则根据[[MK92][引理]]可得对于任意 $\epsilon>0\land\epsilon\in\mathbb{R}$ 均存 $F$ 使得 $F\subset E\land m^*(E/F)<\epsilon$

进一步根据[[MK84][计算]]中（3）有 $m^*(E)-m^*(F)<\epsilon$ 由于 $m^*(E)<\infty$ 故有 $m^*(E)<m^*(F)+\epsilon$

且根据[[MK60][单调性]]以及 $F\subset E$ 有 $m^*(F)\leq m^*(E)$ 

结合上述两条性质可得 $m^*(E)=\sup\left\{m^*(F)\big|F\subset E\land F\in\Theta\right\}$ 

******* 当 $m^*(E)=\infty$ 时

对于任意 $i\in\mathbb{N}^+$ 定义 $K_i=\prod_{j=1}^n[-i,i]$ 其中 $n$ 为欧式空间的维数，乘法为[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-基本定义-直积]]

显然 $K_i$ 是[[MK13][区间]]，根据外测度[[MK79][正则性]]可得 $m^*(K_i)=(2i)^n<\infty$

进一步定义 $E_i=E\cap K_i$ 则有 $E\cap K_i\subset K_i$ 则根据[[MK60][单调性]]有 $m^*(E_i)\leq m^*(K_i)<\infty$ 以及 $E_i\subset E$

由于 $\infty\not\in\mathbb{R}$ 则显然有 $E=\lim_{i\to\infty} E_i$ 根据[[MK93][之前证明]]对于 $\frac{1}{i}$ 存在有界闭集 $F_i$ 满足 $m^*(E_i)<m^*(F_i)+\frac{1}{i}$

根据[[MK82][区间可测]]可得 $K_i$ 可测，由于 $E$ 可测，则根据[[MK84][计算]]中（4）可得 $E_i$ 可测

由于显然 $E_i\subset E_{i+1}$ 故根据[[MK84][计算]]中（5）可得 $m^*\left(\lim_{k\to\infty}E_i\right)=\lim_{i\to\infty}m^*(E_i)$

同理有 $m^*\left(\lim_{i\to\infty} F_i\right)=\lim_{i\to\infty} m^*(F_i)\geq\lim_{i\to\infty}\left(m^*(E_i)+\frac{1}{i}\right)=\lim_{i\to\infty}m^*(E_i)$ 

又由于 $F_i\subset E_i\subset E$ 根据[[MK60][单调性]]有 $m^*(F_i)\leq m^*(E_i)\leq m^*(E)$

则根据夹逼定理有 $m^*(E)=\lim_{i\to\infty}m^*(F_i)$ 其中 $F_i$ 为有界闭集

故有 $m^*(E)=\sup\left\{m^*(F)\big|F\subset E\land F\in\Theta\right\}$ 

***** 证明（2）

定义 $\alpha=\inf\left\{m^*(G)\big|E\subset G\land G\in\Gamma\right\}$ 

****** 定义集列

根据下确界定义，存在开集 $G_i$ 满足 $E\subset G_i\land G_i\subset G_{i-1} \land m^*(G_i)<\alpha+\frac{1}{2i}$

根据上确界定义，存在闭集 $F_i$ 满足 $F_i\subset E\land F_i\subset F_{i+1} \land m^*(F_i)>\alpha-\frac{1}{2i}$

则有 $0\leq m^*(G_i)-m^*(F_i)<\frac{1}{i}$ 定义 $A=\bigcap_{i=1}^\infty G_i,B=\bigcup_{i\to\infty}F_i$

****** 推导测度

根据定义有 $\forall i(A\subset G_i\land F_i\subset B\land B\subset E\subset A)$ 

则根据[[MK60][单调性]]有 $\forall i\big(m^*(A)\leq m^*(G_i)\land m^*(F_i)\leq m^*(B)\land m^*(B)\leq m^*(A)\big)$

故有 $0\leq m^*(A)-m^*(B)\leq m^*(G_i)-m^*(F_i)<\frac{1}{i}$ 由 $i$ 的任意性得 $m^*(A)-m^*(B)=0$

****** 差集零测

由于 $m^*(E)<\infty$ 且 $B\subset E$ 根据单调性有 $m^*(B)<\infty$ 

由于 $G_i$ 为开集，故根据[[MK87][开集可测]]可得可测

同理 $F_i$ 为闭集，结合[[MK84][计算]]中（1）以及[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-集合定义-部分定理-定理1]]可得亦可测

根据[[MK84][计算]]中（2）和（4）可得 $A,B$ 亦可测，结合 $m^*(B)<\infty$ 有 $m^*(A)-m^*(B)=m^*(A-B)=0$

****** 证明可测

由于 $E\subset A$ 故有 $E-B\subset A-B$ 根据[[MK60][单调性]] $m^*(E-B)\leq m^*(A-B)=0$

根据[[MK54][非负性]]可得 $m^*(E-B)\geq0$ 根据[[MK5][三歧性]]可得 $m^*(E-B)=0$ 故根据[[MK94][可测性]]可得 $E-B$ 可测

故根据[[MK84][计算]]中（2）可得 $E=(E-B)\cup B$ 为可测集

****** 证明等式

且由于 $(E-B)\cap B=\varnothing$ 故有 $m^*(E)=m^*\left((E-B)\cup B\right)=m^*(E-B)+m^*(B)=m^*(B)$

由于 $F_i$ [[MK69][递增]]，故根据[[MK70][定理]]可得 $B=\bigcup_{i\to\infty}F_i=\lim_{i\to\infty}F_i$ 

进一步由于 $F_i$ 可测，则[[MK84][计算]]中（5）可得 $m^*(\lim_{i\to\infty}F_i)=\lim_{i\to\infty}m^*(F_i)$

由于上确界，故有 $m^*(F_i)\leq\alpha$ 又根据定义 $m^*(F_i)<m^*(F_i)+\frac{1}{i}$ 故根据夹逼定理 $\lim_{i\to\infty}m^*(F_i)=\alpha$

故最终 $m^*(E)=m^*(B)=m^*(\lim_{i\to\infty}F_i)=\lim_{i\to\infty}m^*(F_i)=\alpha$

即 $m^*(E)=\sup\left\{m^*(F)\big|F\subset E\land F\in\Theta\right\}$

** Borel集合

由所有 $\mathbb{R}^n$ 上开集[[MK85][生成]]的[[MK50][ $\sigma$ 代数]]

*** 定理1

Borel集中元素均为可测集

**** 证明

根据[[MK87][开集可测]]可得开集均为可测集。

则根据开集[[MK85][生成]]定义以及[[MK84][计算]]可得borel集中的元素均可测

** 零测集

[[MK51][外测度]]为零的集合定义为零测集

*** 性质

**** 可测性<<MK94>>

零测集均为[[MK81][可测集]]

***** 证明

若 $S\subset\mathbb{R}^n\land m^*(S)=0$ 取任意 $T\subset\mathbb{R}^n$ 可得 $T\cap S\subset S$ 以及 $T/A\subset T$

根据[[MK60][单调性]]可得 $m^*(T\cap S)\leq m^*(S)\land m^*(T/S)\leq m^*(T)$ 

进一步由于[[MK54][非负性]]以及 $m^*(S)=0$ 则有 $0\leq m^*(T\cap S)\leq m^*(S)\leq0$ 

根据[[MK5][三歧性]]可得 $m^*(T\cap S)=0$ 则有 $m^*(T\cap S)+m^*(T/S)=m^*(T/S)\leq m^*(T)$

又根据[[MK57][次可加性]]得 $m^*(T)\leq m^*(T\cap S)+m^*(T/S)$

进一步根据三歧性可得 $m^*(T)=m^*(T\cap S)+m^*(T/S)$ 即[[MK81][可测]]

**** 子集零测

若 $S\subset\mathbb{R}^n\land m^*(S)=0$ 则对于任意 $T\subset S$ 有 $m^*(T)=0$ 且[[MK81][可测]]

***** 证明

根据[[MK60][单调性]]以及 $T\subset S$ 可得 $m^*(T)\leq m^*(S)=0$

根据[[MK54][非负性]]可得 $m^*(T)\geq 0$ 根据[[MK5][三歧性]]可得 $m^*(T)=0$

根据[[MK88][可测性]]可得 $T$ 可测 

**** 可数零测

若 $S_i\subset\mathbb{R}^n\land m^*(S_i)=0$ 其中 $i\in\mathbb{N}^+$ 则 $m^*\left(\bigcup_{i=1}^\infty S_i\right)=0$ 

即至多可数个零测集的并仍然零测，且[[MK81][可测]]

***** 证明

根据[[MK57][次可加性]] $m^*\left(\bigcup_{i=1}^\infty S_i\right)\leq \sum_{i=1}^\infty m^*(S_i)=0$

根据[[MK54][非负性]]可得 $m^*\left(\bigcup_{i=1}^\infty S_i\right)\geq 0$ 根据[[MK5][三歧性]]可得 $m^*\left(\bigcup_{i=1}^\infty S_i\right)=0$

根据[[MK88][可测性]]可得 $\bigcup_{i=1}^\infty S_i$ 可测 

* 拓扑

** 拓扑定义<<MK39>>

设 $T$ 是 $X$ 的非空子集的[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-集合族]]若满足：

（1） $X,\varnothing$ 均属于 $T$

（2） $T$ 中任意个元素的并集属于 $T$

（3） $T$ 中有限个元素的交集属于 $T$

则称 $T$ 是 $X$ 上的拓扑， $<X,T>$ 是一个拓扑空间

其中 $T$ 的元素称为开集， $T$ 中元素的补集称为闭集。

*** 定理1<<MK41>>

开集的补集是闭集，闭集的补集是开集

** 开覆盖

若 $S\subset X$ ，存在一组[[MK39][开集]] $\{U_\alpha\}\Rightarrow S\subset\cup_\alpha U_\alpha$ ，则称 $\{U_\alpha\}$ 是 $S$ 的开覆盖

** 点的分类

任意 $x\in X$ 定义为拓扑空间的点

*** 聚点<<MK44>>

对于有[[MK38][度量]]的拓扑空间 $<X,T>$ 的点集 $S\subset T$ ，其聚点 $x\in S$ 定义为对于任意 $\delta\in\mathbb{R}\land\delta>0$ 

均存在 $y\in S$ 满足 $d(x,y)<\delta$ 则称 $x$ 是 $S$ 的聚点

为方便，定义 $S$ 所有聚点的集合为 $S'$

** 子集分类

*** 紧集<<MK40>>

若 $S$ 的任意一个[[MK11][开覆盖]]，必有有限子覆盖，即 $\exists U_{\alpha_i}\in \{U_\alpha\},0\leq i\leq p<+\infty\Rightarrow S\subset \cup_{i=0}^p U_{\alpha_i}$ 

则定义 $S$ 为紧集

注： $U_{\alpha_i}$ 为集合 $\{U_\alpha\}$ 的元素

***** 引理

任意紧集的闭子集亦为紧集

****** 证明

若 $M\subset X$ 为紧集，其闭子集 $F\subset M$ 对于任意 $F$ 的开覆盖 $\{U_{\lambda\in\Lambda}\}$ 

根据定义 $F^c$ 为 $F$ 的补集，且有 $F\cup F^c=X$  

可知 $M\subset X=\left(\bigcup_{\lambda\in\Lambda}U_\lambda\right)\cup F^c$ 根据[[MK41][定理1]]以及 $F$ 是闭集的条件可得 $F^c$ 是开集 

则有 $\{U_{\lambda\in\Lambda},F^c\}$ 是 $M$ 的开覆盖，由于 $M$ 是[[MK40][紧集]]则必有有限子覆盖 $\{U_1,...,U_n,F^c\}$

由于 $F^c\cap F=\varnothing$ 且 $F\subset M$ 故 $\bigcup_{i=1}^n U_i$ 必定覆盖 $F$ 即 $F$ 亦有有限子覆盖

*** 完备集<<MK45>>

若 $(T,X)$ 是一个有[[MK38][度量]]的拓扑空间，且 $S\subset X$ ，若 $S=S'$ 即 $S$ 中的任意一点均为 $S$ 的[[MK44][聚点]]

则称 $S$ 是完备集

* 开集构造

** 直线

*** 构成区间<<MK42>>

对于开集 $G\subset\mathbb{R}$ 若 $(\alpha,\beta)\subset G$ 且 $\alpha\not\in G\land\beta\not\in G$ 则称 $(\alpha,\beta)$ 是 $G$ 的构成区间 

*** 开集构造定理<<MK47>>

直线上的开集可表示为[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-至多可数]]个不相交的[[MK42][构成区间]]的并

**** 证明

***** 不同构成区间不相交

若两个构成区间 $(a_1,b_1),(a_2,b_2)$ 相交，则必有某区间端点落在另一个区间内。

由于 $(a_1,b_1)\subset G\land(a_2,b_2)\subset G$ 则落在区间内的端点亦属于 $G$

这与[[MK42][构成区间]]端点不属于 $G$ 矛盾，故不相交

定义 $T$ 是所有属于 $G$ 的构成区间的集合

***** 构成区间有至多可数个

根据[[MK43][有理数稠密性]]可知，对于任意开区间 $(a,b)$ 均存在一个有理数 $q\in(a,b)$

对每一个构成区间任取一个有理数，则构成[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-特殊的函数类型-单射]]

进一步根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-基数]]可得 $|T|\leq|\mathbb{Q}|$ 

由于有理数是可数集，故得 $T$ 即是至多可数集

***** 证明结论

定义 $G'=\bigcup_{t\in T}t$ 即所有属于 $G$ 的构成区间的并。

对于任意 $x\in G'$ 必有 $x\in t\subset G$

对于任意 $x\in G$ 定义开区间集合 $A_{x}=\left\{(a,b)\big|x\in (a,b)\land(a,b)\subset G\right\}$

进一步定义 $\{a\}_{x}=\{a|(a,b)\in A_{x}\},\{b\}_{x}=\{b|(a,b)\in A_{x}\}$ 则定义 $\alpha=\inf\{a\}_{x},\beta=\sup\{b\}_{x}$

则任取 $y\in (\alpha,\beta)$ 根据确界定义必存在 $\alpha<a<y<b<\beta\land (a,b)\in A_x$ 则有 $y\in(a,b)\subset G$ ，故有 $(\alpha,\beta)\subset G$ 

若 $\alpha\in G$ 由于 $G$ 是[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-集合定义-开集]]，则存在 $O(\alpha,\delta)\subset G$

结合上述证明可得 $(\alpha-\delta,\beta)\subset G$ 与下确界定义矛盾，故 $\alpha\not\in G$ 同理可证 $\beta\not\in G$

故 $(\alpha,\beta)$ 是 $x$ 在 $G$ 上的构成区间，即 $(\alpha,\beta)\in T$ 故 $x\in G'$

综上所属 $\forall x\in G'\rightarrow x\in G\land \forall x\in G\rightarrow x\in G'$ 

则根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-ZFC公理化集合论-外延公理]]可得 $G'=G$

*** 闭集的构造<<MK48>>

直线上挖掉至多可数个不相交的[[MK42][构成区间]]的余集是闭集

**** 证明

对于任意闭集 $K\in\mathbb{R}$ 根据[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-集合定义-部分定理-定理1]]可得其补集 $K^c$ 是开集

相反 $K$ 可以理解为 $\mathbb{R}$ 去除开集 $K^c$ 根据[[MK47][开集构造定理]]可得 $K^c$ 可由至多可数个不相交的开区间的并构成

故任意闭集 $K$ 均可表述为直线 $\mathbb{R}$ 去掉 $K^c$ 等价的至多可数个开区间的并。

*** 完备集的构造<<MK49>>

直线上挖掉至多可数个不相邻的[[MK42][构成区间]]的集合是完备集。

相邻：对于任意 $(a_k,b_k),(a_l,b_l)$ ，若满足 $b_k=a_l$ 则两个区间相邻

**** 证明

***** 前提定义

根据[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-集合定义-完备集]]可得不含孤立点的闭集是完备集。

假设点 $x$ 是[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-点的定义-孤立点]]，则根据定义存在 $\delta>0$ 使得去心领域 $O(x,\delta)/x$ 不属于 $S$

根据[[MK48][闭集构造]]可得任意闭集均可表示为为直线 $\mathbb{R}$ 去掉至多可数个开区间的并。

根据[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-集合定义-部分定理-定理1]]得 $S$ 的补集 $S^c$ 是开集

根据[[MK47][开集构造]]可得 $S^c=\bigcup_{i=1}^\infty(a_i,b_i)$ 其中 $(a_i,b_i)$ 是[[MK42][构成区间]]

***** 不含孤立点的充要条件是没有相邻构成区间

根据德摩根路，我们证明含孤立点的充要条件是有相邻构成区间

****** 充分

若 $(a_k,b_k),(a_l,b_l)$ 相邻，即 $a_l=b_k$ ，则由于 $(a_i,b_i)$ 是[[MK42][构成区间]]，故无相交

假设孤立点 $x\in S$ 则根据定义有 $(x-\delta,x),(x,x+\delta)$ 均不属于 $S$ 故有 $\exists(a_k,b_k)\rightarrow (x-\delta,x)\subset(a_k,b_k)$

同理可得 $\exists(a_l,b_l)\rightarrow (x,x+\delta)\subset(a_l,b_l)$ 且满足 $(a_k,b_k)\cap(a_l,b_l)=\varnothing$ 以及 $x\not\in(a_k,b_k)\land x\not\in(a_l,b_l)$

若 $x\ne a_l$ 根据[[MK5][三歧性]]可得比满足 $x>a_l\lor x<a_l$ 若 $x>a_l$ 结合 $(x,x+\delta)\subset (a_l,b_l)$ 可得 $x\in(a_l,b_l)\subset S^c$ 

与 $x\in S$ 矛盾。若 $x<a_l$ 则与 $(x,x+\delta)\subset(a_l,b_l)$ 矛盾。

故必有 $x=a_l$ 同理可证 $x=b_k$ 故根据[[MK5][传递性]]有 $a_l=b_k$ 即 $(a_k,b_k),(a_l,b_l)$ 相邻

****** 必要

若 $(a_k,b_k),(a_l,b_l)$ 相邻，即 $a_l=b_k$ ，则若存在构成区间 $(a_u,b_u)$ 满足 $b_k\in(a_u,b_u)$

则根据开集定义存在 $(b_k-\delta,b_k+\delta)\subset(a_u,b_u)$ 即 $(b_k-\delta,b_k)\subset (a_u,b_u)$

同理可证，存在 $\gamma$ 满足 $(b_k-\gamma,b_k)\subset(a_k,b_k)$ 则取 $\tau=\min(\delta,\gamma)$ 

故有 $(b_k-\tau,b_k)\subset(a_k,b_k)\land(b_k-\tau,b_k)\subset(a_u,b_u)$ 与构成区间不相交矛盾

故有 $b_k\not\in S^c$ 即 $b_k\in S$ 定义 $\tau=\min(b_l-a_l,b_k-a_k)$ 则有 $O(b_k,\tau)/b_k\in S^c$

即 $b_k$ 是 $S$ 的孤立点。

***** 结论

当挖去至多可数个[[MK42][构成区间]]时，剩余集合是闭集

根据之前证明，当构成区间没有相邻时等价于不含孤立点

故得命题

*** 康托三分集

若 $E_n=\bigcup_{\lambda\in\Lambda} [a_\lambda,b_\lambda]$ 为若干个闭区间的并，则定义 $E_{n+1}=\bigcup_{\lambda\in\Lambda}\left(\left[a_\lambda,a_\lambda+\frac{b_\lambda-a_\lambda}{3}\right]\cup\left[b_\lambda-\frac{b_\lambda-a_\lambda}{3},b_\lambda\right]\right)$

定义  $E_0=[0,1]$ 则 $P=\lim_{n\to\infty}E_n$ 即为康托三分集

**** 性质

***** 是完备集

康托三分集挖去的均为不相邻的开集，故根据[[MK49][完备集构造]]可得康托三分集是完备集

***** 有连续基数

根据[[MK33][定理2]]可得，所有实数均有小数表示，此处选择二进制。

根据定义， $E_0=[0,1]$ 定义映射 $0\to0.0,1\to0.1$

若 $E_n=\bigcup_{\lambda\in\Lambda} [a_\lambda,b_\lambda]$ 假设每个 $a_\lambda,b_\lambda$ 均有对应的二进制小数 $\alpha_\lambda,\beta_\lambda$

则在 $E_{n+1}=\bigcup_{\lambda\in\Lambda}\left(\left[a_\lambda,a_\lambda+\frac{b_\lambda-a_\lambda}{3}\right]\cup\left[b_\lambda-\frac{b_\lambda-a_\lambda}{3},b_\lambda\right]\right)$ 中，

每个端点根据挖去区域的左右，在之前端点映射二进制小数的末尾加 $0$ 或 $1$

即 $a_\lambda=\alpha_\lambda0,a_\lambda+\frac{b_\lambda-a_\lambda}{3}\to\alpha_\lambda1,b_\lambda-a_\lambda}{3}=\beta_\lambda0,b_\lambda=\beta_\lambda1$

由于三分集是无限划分，且所有端点均属于该集合，故实数 $[0,1]$ 内的所有点均有对应的映射

即 $\sigma:P\to[0,1]$ 是[[~/OneDrive/离散数学/Disc_Math.org][关系与函数-函数-特殊的函数-满射]]，

则根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-基数]]可得 $|P|\geq|[0,1]|$ 又根据[[MK36][定理0]]以及传递性可得 $|P|\geq|\mathbb{R}|$

由于 $P$ 是从 $\mathbb{R}$ 上取的，故显然有 $|P|\leq|\mathbb{R}|$ 根据基数定义中伯恩斯坦定理 $|P|=|\mathbb{R}|$

***** 长度为零

第 $n$ 次挖掉的长度为 $\frac{2^{n-1}}{3^n}$ 则挖掉的长度可定义为 $S=\lim_{n\to\infty}\sum_{i=1}^n\frac{2^{n-1}}{3^n}$

根据等比数列求和公式 $S=\lim_{n\to\infty}\frac{1}{3}\frac{1-\left(\frac{2}{3}\right)^n}{1-\frac{2}{3}}=\frac{1}{3}\frac{1}{1-\frac{2}{3}}=1$

故康托三分集的长度为 $d([0,1])-1=0$

** 有限欧式空间开集构造定理<<MK83>>

对于任意[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-集合定义-开集]] $G\subset\mathbb{R}^n\land n<\infty$ 

其可表述为[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-至多可数]]个不相交的半开闭[[MK13][区间]]的并

*** 证明

**** 构建二进方体

将 $\mathbb{R}^n$ 空间分割为长度为 $1$ 的矩体区间

则每对应一组 $\vec{x}=(x_1,...,x_n),x_i\in\mathbb{N}$ 均有一个矩体区间 $\prod_{i=1}^n[x_i,x_i+1)\in H_0$ 

其中 $H_0$ 定义为所有矩体的集合，根据[[MK43][有理数稠密性]]可知每个 $H_0$ 中的区间内必有有理点。

由于有理数可数，且 $\mathbb{R}^n$ 中有理点是 $\mathbb{R}$ 中有理点的 $n$ 次直积

则根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-至多可数集-定理2]]可得 $H_0$ 是可数集

将 $H_0$ 中所有矩体二分，则矩体的长度为 $\frac{1}{2}$ ，定义此次划分的所有矩体集合为 $H_1$ 同理可证是可数集

依次类推 $H_k$ 的矩长度为 $\left(\frac{1}{2}\right)^k$ 且 $H_k$ 为可数集

**** 构建并集

定义 $\Gamma_0=\left\{J\left|J\in H_0\land J\subset G\right\}$ 进一步定义 $\Gamma_k=\left\{J\left|J\in H_k\land\left(J\subset G/\bigcup_{i=0}^{k-1}\left(\bigcup_{J\in\Gamma_i}J\right)\right)\right\}$

由于 $\Gamma_k\subset H_k$ 且 $H_k$ 可数，则根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-基数-无限集]]可得 $\Gamma_k$ 至多可数

则根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合分类-至多可数集-定理1]]可得 $\bigcup_{i=0}^\infty\Gamma_i$ 亦为至多可数

且根据构造，每个 $J\in\bigcup_{i=0}^\infty\Gamma_i$ 是区间，且两两互不相交 

**** 证明结论

根据[[~/OneDrive/数学分析/Chap11Note.org][构造Euclid空间-集合定义-开集]]定义，对于任意 $x\in G$ 均存在 $\delta\in\mathbb{R}\land\delta>0$ 满足 $O(x,\delta)\subset G$ 

对于正闭矩体 $J$ 包含的点集，距离最远的点为矩体对角端点，距离为 $\sqrt{nl^2}$ 其中 $l$ 为矩体的边长

由于 $\lim_{k\to\infty}\frac{1}{2}^k=0$ 则定义 $l_k=\frac{1}{2}^k$ 必存在 $k'$ 使得 $\sqrt{nl^2_{k'}}<\delta$ 

由于 $H_{k'}$ 划分整个 $\mathbb{R}^n$ 空间，则必存在区间 $x\in J'\in H_{k'}$ 且对于任意 $y\in J'$ 均有 $|y-x|<\sqrt{nl^2_{k'}}<\delta$

故有 $J'\subset O(x,\delta)\subset G$ 故 $J'$ 满足 $J'\in H_{k'}\land J'\subset G$ 

根据二进方体构建规则 $J'$ 与 $\bigcup_{i=0}^{k'-1}\left(\bigcup_{J\in\Gamma_i}J\right)$ 的关系仅存在属于或不属于，故

此时若 $J'\subset \bigcup_{i=0}^{k'-1}\left(\bigcup_{J\in\Gamma_i}J\right)$ 则有 $x\in J'\subset \bigcup_{i=0}^{k'-1}\left(\bigcup_{J\in\Gamma_i}J\right)\subset \bigcup_{i=0}^\infty\left(\bigcup_{J\in\Gamma_i}J\right)$ 

若 $J'\not\subset \bigcup_{i=0}^{k'-1}\left(\bigcup_{J\in\Gamma_i}J\right)$ 

则 $J'\in H_{k'}\land\left(J'\subset G/\bigcup_{i=0}^{k'-1}\left(\bigcup_{J\in\Gamma_i}J\right)\right)$ 则 $J'\in\Gamma_{k'}$ 故有 $x\in J'\subset \bigcup_{i=0}^\infty\left(\bigcup_{J\in\Gamma_i}J\right)$

故对于任意 $x\in G$ 均有 $x\in\bigcup_{i=0}^\infty\left(\bigcup_{J\in\Gamma_i}J\right)$ 由于 $\Gamma_k$ 的构造，对于任意 $J\in\bigcup_{i=0}^\infty\Gamma_i$ 均有 $J\subset G$

故对于任意 $x\in\bigcup_{i=0}^\infty\left(\bigcup_{J\in\Gamma_i}J\right)$ 均有 $x\in G$ 

综上所述根据[[~/OneDrive/离散数学/Disc_Math.org][集合论-集合定义-ZFC公理化集合论-外延公理]]可得 $G=\bigcup_{i=0}^\infty\left(\bigcup_{J\in\Gamma_i}J\right)$

证毕

